/* ============================================================================
   ORBIT — lesson validator
   ----------------------------------------------------------------------------
   "Nothing left out" is enforced here: a module's lessons must together cover
   every topic the module lists, every formula must parse, and every lesson
   must carry the parts a learner needs (worked examples, check-yourself
   questions with answers). Set LESSON_MODULE=<moduleId> to check one module
   while writing it.
   ========================================================================== */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import katex from 'katex'
import { describe, expect, it } from 'vitest'
import { buildCoverage, buildManifest } from '../../scripts/lessons-manifest'
import { moduleById } from './index'
import { LESSON_COVERAGE, LESSON_MANIFEST } from './lessons/manifest'
import { parseLesson, proseWordCount } from './lessons/parse'

const dir = fileURLToPath(new URL('./lessons', import.meta.url))
const only = process.env.LESSON_MODULE
/*
 * A module directory holding no lesson yet is skipped rather than failed.
 *
 * Git cannot commit an empty directory, so such a directory never reaches CI
 * and never reaches a reader — it exists only on the machine of whoever is
 * part-way through writing that module, in the window between creating the
 * folder and saving the first lesson into it. Failing on it means every
 * writing run reports a red suite for a state that cannot ship, which trains
 * whoever is watching to ignore red. Nothing is lost by skipping: a module
 * that is genuinely missing its lessons is caught by the coverage check,
 * which reads the module's topic list rather than the folder.
 */
const moduleDirs = fs
  .readdirSync(dir)
  .filter((d) => fs.statSync(path.join(dir, d)).isDirectory() && (!only || d === only))
  .filter((d) => fs.readdirSync(path.join(dir, d)).some((f) => f.endsWith('.md')))
  .sort()

const MIN_WORDS = 600
const MAX_WORDS = 7000
const KINDS = ['example', 'key', 'check', 'answer', 'note', 'warning', 'video']
// `::: video <id>` — 11 URL-safe base64 characters, as the provider issues them.
const VIDEO_ID_RE = /^[A-Za-z0-9_-]{11}$/

function mathSpans(body: string): { tex: string; display: boolean }[] {
  const out: { tex: string; display: boolean }[] = []
  const noCode = body.replace(/```[\s\S]*?```/g, '')
  const display = /\$\$([\s\S]*?)\$\$/g
  let m: RegExpExecArray | null
  while ((m = display.exec(noCode)) !== null) out.push({ tex: m[1]!.trim(), display: true })
  const rest = noCode.replace(/\$\$[\s\S]*?\$\$/g, ' ')
  const inline = /\$(?!\s)(?:[^$\n\\]|\\.)+?(?<!\s)\$/g
  while ((m = inline.exec(rest)) !== null) out.push({ tex: m[0].slice(1, -1), display: false })
  return out
}

// The manifest is regenerated by the orchestrator after a batch of lessons
// lands, so a single-module run (LESSON_MODULE set) does not check it.
if (!only) {
  describe('lesson manifest', () => {
    it('matches the files on disk (run `npm run lessons:manifest`)', () => {
      expect(LESSON_MANIFEST).toEqual(buildManifest())
    })

    // The UI reads these numbers to tell the learner a module is still being
    // written, so a stale value would be a lie rather than a cosmetic drift.
    it('carries coverage derived from those same files', () => {
      expect(LESSON_COVERAGE).toEqual(buildCoverage())
    })
  })
}

if (moduleDirs.length === 0) {
  describe('lessons', () => {
    it('has no lesson directories yet', () => {
      expect(moduleDirs).toEqual([])
    })
  })
}

describe.each(moduleDirs)('lessons for %s', (moduleId) => {
  const module = moduleById(moduleId)
  const modDir = path.join(dir, moduleId)
  const files = fs.readdirSync(modDir).filter((f) => f.endsWith('.md')).sort()
  const parsed = files.map((file) => {
    const src = fs.readFileSync(path.join(modDir, file), 'utf8')
    return { file, src, ...parseLesson(src, `${moduleId}/${file}`) }
  })

  it('belongs to a real module and is numbered contiguously', () => {
    expect(module, `${moduleId} is not a module id`).toBeDefined()
    expect(files.length).toBeGreaterThan(0)
    files.forEach((f, i) => {
      expect(f, 'file names are <nn>-<slug>.md').toMatch(/^\d{2}-[a-z0-9][a-z0-9-]*\.md$/)
      expect(Number(f.slice(0, 2)), `${f} should be number ${i + 1}`).toBe(i + 1)
    })
    const ids = parsed.map((p) => p.header.id)
    expect(new Set(ids).size, 'lesson ids are unique').toBe(ids.length)
  })

  it('only claims topics the module actually lists', () => {
    const topics = new Set(module!.topics)
    for (const p of parsed) {
      for (const c of p.header.covers) {
        expect(topics.has(c), `${p.file}: "covers" entry is not a module topic (must match verbatim): "${c}"`).toBe(true)
      }
    }
  })

  /*
   * Full coverage is the finish line, not the gate on every commit: modules are
   * written one at a time and a half-written module must be able to land and be
   * reviewed. What keeps that honest is that incompleteness is derived, not
   * declared — LESSON_COVERAGE is computed from the files, the module page shows
   * the shortfall to the learner, and `npm run lessons:check` makes it an error.
   * So a partial module is always visible as partial and can never be mistaken
   * for a finished one.
   */
  const strict = process.env.LESSONS_STRICT === '1'
  const coverageTest = strict ? it : it.skip
  coverageTest('covers every topic of the module', () => {
    const covered = new Set<string>()
    for (const p of parsed) for (const c of p.header.covers) covered.add(c)
    const missing = module!.topics.filter((t) => !covered.has(t))
    expect(missing, 'topics no lesson covers').toEqual([])
  })

  describe.each(parsed.map((p) => [p.file, p] as const))('%s', (_file, p) => {
    it('has a sane header', () => {
      expect(p.header.title.length).toBeLessThanOrEqual(90)
      expect(p.header.minutes).toBeGreaterThanOrEqual(5)
      expect(p.header.minutes).toBeLessThanOrEqual(90)
    })

    /*
     * A merge or a stash that went wrong leaves these markers in the prose,
     * and every other rule here passes straight over them: the word count is
     * fine, the blocks balance, the maths parses. It happened, it shipped, and
     * the only reason it was caught is that a writer mentioned it. So it is a
     * rule now.
     */
    it('carries no leftover conflict markers', () => {
      const markers = p.src
        .split('\n')
        .filter((l) => /^(<{7}|={7}|>{7})(\s|$)/.test(l))
      expect(markers, 'unresolved merge or stash conflict in the lesson').toEqual([])
    })

    it('is a full lesson, not a stub', () => {
      const words = proseWordCount(p.body)
      expect(words, `prose words (min ${MIN_WORDS})`).toBeGreaterThanOrEqual(MIN_WORDS)
      expect(words, `prose words (max ${MAX_WORDS})`).toBeLessThanOrEqual(MAX_WORDS)
      expect(p.body, 'at least two worked examples').toMatch(/^:::\s*example[\s\S]*^:::\s*example/m)
      expect(p.body, 'a Check yourself section').toMatch(/^##\s+Check yourself/m)
      expect(p.body, 'check questions').toMatch(/^:::\s*check/m)
      expect(p.body, 'answers that fold open').toMatch(/^:::\s*answer/m)
      expect(p.body, 'a Summary section').toMatch(/^##\s+Summary/m)
    })

    /*
     * A question with no answer behind it is a dead end: she reads the check,
     * thinks, opens nothing, and has no way to find out whether she was right.
     * That is worse than no question at all, because it costs her the attempt
     * and gives her nothing back. The counts are what catch it — a missing
     * `::: answer` is invisible in the rendered page until you click.
     */
    it('answers every question it asks', () => {
      const checks = (p.body.match(/^:::\s*check/gm) ?? []).length
      const answers = (p.body.match(/^:::\s*answer/gm) ?? []).length
      expect(answers, `${checks} check questions but ${answers} answers`).toBe(checks)
      expect(checks, 'at least three check questions').toBeGreaterThanOrEqual(3)
    })

    /*
     * `minutes` is not decoration: the focus planner budgets a session from
     * it, so a number invented rather than counted either strands her
     * mid-lesson or leaves her sitting on a finished one. The house estimate
     * is words/180 plus two minutes per worked example. The window here is
     * wide on purpose — the whole written corpus falls inside 0.87 to 1.65 of
     * that estimate, and this is meant to catch a number nobody counted at
     * all, not to referee a writer's judgement about a dense derivation.
     */
    it('claims a plausible reading time', () => {
      const est =
        proseWordCount(p.body) / 180 + 2 * (p.body.match(/^:::\s*example/gm) ?? []).length
      const ratio = p.header.minutes / est
      expect(
        ratio,
        `minutes: ${p.header.minutes} against an estimated ${est.toFixed(1)} ` +
          `(${proseWordCount(p.body)} words / 180 + 2 per example)`,
      ).toBeGreaterThan(0.5)
      expect(ratio, `minutes: ${p.header.minutes} against an estimated ${est.toFixed(1)}`).toBeLessThan(2.5)
    })

    it('uses only the markdown the renderer supports', () => {
      const lines = p.body.split('\n')
      const openers = lines.filter((l) => /^\s*:::\s*[a-z]+/.test(l))
      const closers = lines.filter((l) => /^\s*:::\s*$/.test(l))
      expect(closers.length, 'every ::: block is closed').toBe(openers.length)
      for (const l of openers) {
        const kind = /^\s*:::\s*([a-z]+)/.exec(l)![1]!
        expect(KINDS, `unknown callout kind "${kind}"`).toContain(kind)
        if (kind === 'video') {
          // A mistyped id renders a dead panel in the middle of a lesson, and
          // nothing downstream would catch it, so it is caught here.
          const id = /^\s*:::\s*video\s+(\S+)/.exec(l)?.[1] ?? ''
          expect(id, `"::: video" needs a video id: "${l.trim()}"`).toMatch(VIDEO_ID_RE)
        }
      }
      // Code first: `# comment` opens a Python line and `<T>` is a template
      // parameter. Neither is markdown, and both are common in these lessons.
      const noCode = p.body.replace(/```[\s\S]*?```/g, '')
      expect(
        noCode.split('\n').filter((l) => /^#\s/.test(l)),
        'no # headings (the title is the h1)',
      ).toEqual([])
      const noMath = noCode
        .replace(/\$\$[\s\S]*?\$\$/g, '')
        .replace(/\$[^$\n]+\$/g, '')
        .replace(/`[^`\n]+`/g, '')
      expect(noMath.match(/<[a-z][a-z0-9-]*[\s>/]/gi) ?? [], 'no raw HTML').toEqual([])
      expect(noMath.match(/\\\(|\\\[|\\begin\{equation/g) ?? [], 'math uses $ and $$ delimiters only').toEqual([])
      const dollars = (p.body.replace(/```[\s\S]*?```/g, '').match(/\$\$/g) ?? []).length
      expect(dollars % 2, 'balanced $$').toBe(0)
      // Against the code-free text: a C++ lambda written inline, `[omega](double
      // t)`, has a link's exact shape and is not a link.
      for (const m of noMath.matchAll(/\]\(([^)]+)\)/g)) {
        expect(m[1], 'links are https or in-app').toMatch(/^(https:\/\/|#\/)/)
      }
    })

    it('has mathematics KaTeX can render', () => {
      const bad: string[] = []
      for (const { tex, display } of mathSpans(p.body)) {
        try {
          katex.renderToString(tex, { displayMode: display, throwOnError: true, strict: 'ignore' })
        } catch (err) {
          bad.push(`${tex.slice(0, 80)} → ${err instanceof Error ? err.message : String(err)}`)
        }
      }
      expect(bad).toEqual([])
    })
  })
})
