/* ============================================================================
   ORBIT — lesson validator
   ----------------------------------------------------------------------------
   "Nothing left out" is enforced here: a module's lessons must together cover
   every topic the module lists, every formula must parse, and every lesson
   must carry the parts a learner needs (worked examples, check-yourself
   questions with answers). Set LESSON_MODULE=<moduleId> to check one module
   while writing it.
   ========================================================================== */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import katex from 'katex'
import { describe, expect, it } from 'vitest'
import { buildManifest } from '../../scripts/lessons-manifest'
import { moduleById } from './index'
import { LESSON_MANIFEST } from './lessons/manifest'
import { parseLesson, proseWordCount } from './lessons/parse'

const dir = fileURLToPath(new URL('./lessons', import.meta.url))
const only = process.env.LESSON_MODULE
const moduleDirs = fs
  .readdirSync(dir)
  .filter((d) => fs.statSync(path.join(dir, d)).isDirectory() && (!only || d === only))
  .sort()

const MIN_WORDS = 600
const MAX_WORDS = 7000
const KINDS = ['example', 'key', 'check', 'answer', 'note', 'warning']

function mathSpans(body: string): { tex: string; display: boolean }[] {
  const out: { tex: string; display: boolean }[] = []
  const noCode = body.replace(/```[\s\S]*?```/g, '')
  const display = /\$\$([\s\S]*?)\$\$/g
  let m: RegExpExecArray | null
  while ((m = display.exec(noCode)) !== null) out.push({ tex: m[1]!.trim(), display: true })
  const rest = noCode.replace(/\$\$[\s\S]*?\$\$/g, ' ')
  const inline = /\$(?!\s)(?:[^$\n\\]|\\.)+?(?<!\s)\$/g
  while ((m = inline.exec(rest)) !== null) out.push({ tex: m[0].slice(1, -1), display: false })
  return out
}

// The manifest is regenerated by the orchestrator after a batch of lessons
// lands, so a single-module run (LESSON_MODULE set) does not check it.
if (!only) {
  describe('lesson manifest', () => {
    it('matches the files on disk (run `npm run lessons:manifest`)', () => {
      expect(LESSON_MANIFEST).toEqual(buildManifest())
    })
  })
}

if (moduleDirs.length === 0) {
  describe('lessons', () => {
    it('has no lesson directories yet', () => {
      expect(moduleDirs).toEqual([])
    })
  })
}

describe.each(moduleDirs)('lessons for %s', (moduleId) => {
  const module = moduleById(moduleId)
  const modDir = path.join(dir, moduleId)
  const files = fs.readdirSync(modDir).filter((f) => f.endsWith('.md')).sort()
  const parsed = files.map((file) => {
    const src = fs.readFileSync(path.join(modDir, file), 'utf8')
    return { file, src, ...parseLesson(src, `${moduleId}/${file}`) }
  })

  it('belongs to a real module and is numbered contiguously', () => {
    expect(module, `${moduleId} is not a module id`).toBeDefined()
    expect(files.length).toBeGreaterThan(0)
    files.forEach((f, i) => {
      expect(f, 'file names are <nn>-<slug>.md').toMatch(/^\d{2}-[a-z0-9][a-z0-9-]*\.md$/)
      expect(Number(f.slice(0, 2)), `${f} should be number ${i + 1}`).toBe(i + 1)
    })
    const ids = parsed.map((p) => p.header.id)
    expect(new Set(ids).size, 'lesson ids are unique').toBe(ids.length)
  })

  it('covers every topic of the module, and only those', () => {
    const topics = new Set(module!.topics)
    const covered = new Set<string>()
    for (const p of parsed) {
      for (const c of p.header.covers) {
        expect(topics.has(c), `${p.file}: "covers" entry is not a module topic (must match verbatim): "${c}"`).toBe(true)
        covered.add(c)
      }
    }
    const missing = [...topics].filter((t) => !covered.has(t))
    expect(missing, `topics no lesson covers`).toEqual([])
  })

  describe.each(parsed.map((p) => [p.file, p] as const))('%s', (_file, p) => {
    it('has a sane header', () => {
      expect(p.header.title.length).toBeLessThanOrEqual(90)
      expect(p.header.minutes).toBeGreaterThanOrEqual(5)
      expect(p.header.minutes).toBeLessThanOrEqual(90)
    })

    it('is a full lesson, not a stub', () => {
      const words = proseWordCount(p.body)
      expect(words, `prose words (min ${MIN_WORDS})`).toBeGreaterThanOrEqual(MIN_WORDS)
      expect(words, `prose words (max ${MAX_WORDS})`).toBeLessThanOrEqual(MAX_WORDS)
      expect(p.body, 'at least two worked examples').toMatch(/^:::\s*example[\s\S]*^:::\s*example/m)
      expect(p.body, 'a Check yourself section').toMatch(/^##\s+Check yourself/m)
      expect(p.body, 'check questions').toMatch(/^:::\s*check/m)
      expect(p.body, 'answers that fold open').toMatch(/^:::\s*answer/m)
      expect(p.body, 'a Summary section').toMatch(/^##\s+Summary/m)
    })

    it('uses only the markdown the renderer supports', () => {
      const lines = p.body.split('\n')
      const openers = lines.filter((l) => /^\s*:::\s*[a-z]+/.test(l))
      const closers = lines.filter((l) => /^\s*:::\s*$/.test(l))
      expect(closers.length, 'every ::: block is closed').toBe(openers.length)
      for (const l of openers) {
        const kind = /^\s*:::\s*([a-z]+)/.exec(l)![1]!
        expect(KINDS, `unknown callout kind "${kind}"`).toContain(kind)
      }
      expect(lines.filter((l) => /^#\s/.test(l)), 'no # headings (the title is the h1)').toEqual([])
      const noMath = p.body.replace(/```[\s\S]*?```/g, '').replace(/\$\$[\s\S]*?\$\$/g, '').replace(/\$[^$\n]+\$/g, '')
      expect(noMath.match(/<[a-z][a-z0-9-]*[\s>/]/gi) ?? [], 'no raw HTML').toEqual([])
      expect(noMath.match(/\\\(|\\\[|\\begin\{equation/g) ?? [], 'math uses $ and $$ delimiters only').toEqual([])
      const dollars = (p.body.replace(/```[\s\S]*?```/g, '').match(/\$\$/g) ?? []).length
      expect(dollars % 2, 'balanced $$').toBe(0)
      for (const m of p.body.matchAll(/\]\(([^)]+)\)/g)) {
        expect(m[1], 'links are https or in-app').toMatch(/^(https:\/\/|#\/)/)
      }
    })

    it('has mathematics KaTeX can render', () => {
      const bad: string[] = []
      for (const { tex, display } of mathSpans(p.body)) {
        try {
          katex.renderToString(tex, { displayMode: display, throwOnError: true, strict: 'ignore' })
        } catch (err) {
          bad.push(`${tex.slice(0, 80)} → ${err instanceof Error ? err.message : String(err)}`)
        }
      }
      expect(bad).toEqual([])
    })
  })
})
