// Generated by scripts/lessons-manifest.ts — do not edit by hand.
// Lesson metadata for every module that has lessons on disk; bodies load lazily.
import type { LessonMeta } from './types'

export const LESSON_MANIFEST: Record<string, LessonMeta[]> = {
  "t0_m01_algebra_precalc": [
    {
      "id": "l01-signed-numbers-and-fractions",
      "title": "Signed numbers, fractions and ratios",
      "minutes": 16,
      "covers": [
        "arithmetic with signed numbers and fractions"
      ],
      "file": "t0_m01_algebra_precalc/01-signed-numbers-and-fractions.md"
    },
    {
      "id": "l02-exponents-and-radicals",
      "title": "Exponents, radicals and scaling laws",
      "minutes": 16,
      "covers": [
        "exponents and radicals"
      ],
      "file": "t0_m01_algebra_precalc/02-exponents-and-radicals.md"
    },
    {
      "id": "l03-polynomials-and-factoring",
      "title": "Polynomials, expanding and factoring",
      "minutes": 16,
      "covers": [
        "polynomial manipulation and factoring"
      ],
      "file": "t0_m01_algebra_precalc/03-polynomials-and-factoring.md"
    },
    {
      "id": "l04-linear-and-quadratic-equations",
      "title": "Linear and quadratic equations",
      "minutes": 16,
      "covers": [
        "linear and quadratic equations"
      ],
      "file": "t0_m01_algebra_precalc/04-linear-and-quadratic-equations.md"
    },
    {
      "id": "l05-systems-of-equations",
      "title": "Systems of equations",
      "minutes": 14,
      "covers": [
        "systems of equations"
      ],
      "file": "t0_m01_algebra_precalc/05-systems-of-equations.md"
    },
    {
      "id": "l06-functions",
      "title": "Functions, domain, range, composition and inverses",
      "minutes": 21,
      "covers": [
        "functions: domain, range, composition, inverses"
      ],
      "file": "t0_m01_algebra_precalc/06-functions.md"
    },
    {
      "id": "l07-exponentials-and-logarithms",
      "title": "Exponentials, logarithms and the rocket equation",
      "minutes": 17,
      "covers": [
        "exponentials and logarithms"
      ],
      "file": "t0_m01_algebra_precalc/07-exponentials-and-logarithms.md"
    },
    {
      "id": "l08-sequences-and-series",
      "title": "Sequences, series and sigma notation",
      "minutes": 15,
      "covers": [
        "sequences, series, and sigma notation"
      ],
      "file": "t0_m01_algebra_precalc/08-sequences-and-series.md"
    },
    {
      "id": "l09-inequalities",
      "title": "Inequalities and design constraints",
      "minutes": 19,
      "covers": [
        "inequalities"
      ],
      "file": "t0_m01_algebra_precalc/09-inequalities.md"
    },
    {
      "id": "l10-units-and-dimensional-analysis",
      "title": "Units, conversions and dimensional analysis",
      "minutes": 17,
      "covers": [
        "units and dimensional analysis"
      ],
      "file": "t0_m01_algebra_precalc/10-units-and-dimensional-analysis.md"
    },
    {
      "id": "l11-scientific-notation-and-significant-figures",
      "title": "Scientific notation and significant figures",
      "minutes": 19,
      "covers": [
        "scientific notation and significant figures"
      ],
      "file": "t0_m01_algebra_precalc/11-scientific-notation-and-significant-figures.md"
    },
    {
      "id": "l12-fermi-estimation",
      "title": "Order-of-magnitude estimation",
      "minutes": 20,
      "covers": [
        "order-of-magnitude (Fermi) estimation"
      ],
      "file": "t0_m01_algebra_precalc/12-fermi-estimation.md"
    }
  ],
  "t0_m02_trigonometry": [
    {
      "id": "l01-angles-radians-unit-circle",
      "title": "Angles, radians and the unit circle",
      "minutes": 20,
      "covers": [
        "radians vs degrees",
        "the unit circle"
      ],
      "file": "t0_m02_trigonometry/01-angles-radians-unit-circle.md"
    },
    {
      "id": "l02-sin-cos-tan-inverses",
      "title": "Sine, cosine, tangent and their inverses",
      "minutes": 20,
      "covers": [
        "sin, cos, tan and their inverses"
      ],
      "file": "t0_m02_trigonometry/02-sin-cos-tan-inverses.md"
    },
    {
      "id": "l03-atan2-quadrants-wrapping",
      "title": "atan2, quadrants and angle wrapping",
      "minutes": 20,
      "covers": [
        "atan2 and quadrant correctness"
      ],
      "file": "t0_m02_trigonometry/03-atan2-quadrants-wrapping.md"
    },
    {
      "id": "l04-trig-identities",
      "title": "Trigonometric identities",
      "minutes": 16,
      "covers": [
        "identities: Pythagorean, sum/difference, double-angle"
      ],
      "file": "t0_m02_trigonometry/04-trig-identities.md"
    },
    {
      "id": "l05-law-of-sines-and-cosines",
      "title": "The law of sines and the law of cosines",
      "minutes": 19,
      "covers": [
        "law of sines and law of cosines"
      ],
      "file": "t0_m02_trigonometry/05-law-of-sines-and-cosines.md"
    },
    {
      "id": "l06-small-angle-approximations",
      "title": "Small-angle approximations",
      "minutes": 17,
      "covers": [
        "small-angle approximations"
      ],
      "file": "t0_m02_trigonometry/06-small-angle-approximations.md"
    },
    {
      "id": "l07-polar-and-spherical-coordinates",
      "title": "Polar, spherical and geodetic coordinates",
      "minutes": 19,
      "covers": [
        "polar and spherical coordinates"
      ],
      "file": "t0_m02_trigonometry/07-polar-and-spherical-coordinates.md"
    },
    {
      "id": "l08-conic-sections",
      "title": "Conic sections and the shape of orbits",
      "minutes": 17,
      "covers": [
        "conic sections in geometric and polar form"
      ],
      "file": "t0_m02_trigonometry/08-conic-sections.md"
    },
    {
      "id": "l09-complex-numbers-and-euler",
      "title": "Complex numbers and the Euler formula",
      "minutes": 18,
      "covers": [
        "complex numbers and Euler formula"
      ],
      "file": "t0_m02_trigonometry/09-complex-numbers-and-euler.md"
    }
  ],
  "t0_m03_python_scicomp": [
    {
      "id": "l01-python-basics",
      "title": "Python from zero: values, names and control flow",
      "minutes": 20,
      "covers": [
        "Python syntax, control flow, functions, classes"
      ],
      "file": "t0_m03_python_scicomp/01-python-basics.md"
    },
    {
      "id": "l02-functions-modules",
      "title": "Functions, errors and modules",
      "minutes": 20,
      "covers": [
        "Python syntax, control flow, functions, classes"
      ],
      "file": "t0_m03_python_scicomp/02-functions-modules.md"
    },
    {
      "id": "l03-workbench",
      "title": "The workbench: environments, pip, notebooks and git",
      "minutes": 22,
      "covers": [
        "virtual environments and pip",
        "Jupyter notebooks",
        "git and GitHub"
      ],
      "file": "t0_m03_python_scicomp/03-workbench.md"
    },
    {
      "id": "l04-classes-and-pytest",
      "title": "Classes and pytest: a tested Vec3 and Quaternion",
      "minutes": 20,
      "covers": [
        "Python syntax, control flow, functions, classes",
        "pytest and test-driven numerical code"
      ],
      "file": "t0_m03_python_scicomp/04-classes-and-pytest.md"
    },
    {
      "id": "l05-numpy-arrays",
      "title": "NumPy: arrays, broadcasting and vectorised thinking",
      "minutes": 22,
      "covers": [
        "NumPy arrays, broadcasting, vectorisation, dtypes, float64 semantics"
      ],
      "file": "t0_m03_python_scicomp/05-numpy-arrays.md"
    },
    {
      "id": "l06-floating-point",
      "title": "Floating point: machine epsilon and catastrophic cancellation",
      "minutes": 20,
      "covers": [
        "floating-point pitfalls: catastrophic cancellation, machine epsilon"
      ],
      "file": "t0_m03_python_scicomp/06-floating-point.md"
    },
    {
      "id": "l07-scipy",
      "title": "SciPy: integrating, solving, filtering and fitting",
      "minutes": 24,
      "covers": [
        "SciPy: integrate.solve_ivp, optimize, linalg, signal, stats"
      ],
      "file": "t0_m03_python_scicomp/07-scipy.md"
    },
    {
      "id": "l08-matplotlib",
      "title": "matplotlib: figures a design review will accept",
      "minutes": 21,
      "covers": [
        "matplotlib and publication-grade plots"
      ],
      "file": "t0_m03_python_scicomp/08-matplotlib.md"
    },
    {
      "id": "l09-telemetry-csv-hdf5",
      "title": "Telemetry files: reading and plotting CSV and HDF5",
      "minutes": 21,
      "covers": [
        "reading and plotting CSV / HDF5 telemetry"
      ],
      "file": "t0_m03_python_scicomp/09-telemetry-csv-hdf5.md"
    }
  ],
  "t0_m04_linear_algebra_1": [
    {
      "id": "l01-vectors-norms-dot-product",
      "title": "Vectors, norms and the dot product",
      "minutes": 19,
      "covers": [
        "vectors, dot and cross products, norms, projections"
      ],
      "file": "t0_m04_linear_algebra_1/01-vectors-norms-dot-product.md"
    },
    {
      "id": "l02-matrices-as-linear-maps",
      "title": "Matrices as linear maps",
      "minutes": 21,
      "covers": [
        "matrix multiplication as composition of maps",
        "identity, inverse, transpose"
      ],
      "file": "t0_m04_linear_algebra_1/02-matrices-as-linear-maps.md"
    },
    {
      "id": "l03-gaussian-elimination-and-lu",
      "title": "Gaussian elimination and LU factorisation",
      "minutes": 18,
      "covers": [
        "Gaussian elimination and LU factorisation"
      ],
      "file": "t0_m04_linear_algebra_1/03-gaussian-elimination-and-lu.md"
    },
    {
      "id": "l04-independence-rank-and-null-space",
      "title": "Independence, basis, rank and null space",
      "minutes": 22,
      "covers": [
        "linear independence and basis",
        "rank, null space, column space"
      ],
      "file": "t0_m04_linear_algebra_1/04-independence-rank-and-null-space.md"
    },
    {
      "id": "l05-the-determinant",
      "title": "The determinant and what it measures",
      "minutes": 19,
      "covers": [
        "determinant and its geometric meaning"
      ],
      "file": "t0_m04_linear_algebra_1/05-the-determinant.md"
    },
    {
      "id": "l06-orthogonality-gram-schmidt-qr",
      "title": "Orthogonality, Gram–Schmidt and QR",
      "minutes": 19,
      "covers": [
        "orthogonality, Gram-Schmidt, QR"
      ],
      "file": "t0_m04_linear_algebra_1/06-orthogonality-gram-schmidt-qr.md"
    },
    {
      "id": "l07-change-of-basis-between-frames",
      "title": "Change of basis between reference frames",
      "minutes": 21,
      "covers": [
        "change of basis between reference frames"
      ],
      "file": "t0_m04_linear_algebra_1/07-change-of-basis-between-frames.md"
    },
    {
      "id": "l08-skew-symmetric-cross-product-matrix",
      "title": "Skew-symmetric matrices and the cross-product matrix",
      "minutes": 23,
      "covers": [
        "skew-symmetric matrices and the cross-product matrix"
      ],
      "file": "t0_m04_linear_algebra_1/08-skew-symmetric-cross-product-matrix.md"
    }
  ],
  "t0_m05_linear_algebra_2": [
    {
      "id": "l01-eigenvalues-and-diagonalisation",
      "title": "Eigenvalues, eigenvectors and diagonalisation",
      "minutes": 20,
      "covers": [
        "eigenvalues, eigenvectors, diagonalisation"
      ],
      "file": "t0_m05_linear_algebra_2/01-eigenvalues-and-diagonalisation.md"
    },
    {
      "id": "l02-matrix-exponential",
      "title": "The matrix exponential and the state transition matrix",
      "minutes": 22,
      "covers": [
        "the matrix exponential and the state transition matrix"
      ],
      "file": "t0_m05_linear_algebra_2/02-matrix-exponential.md"
    },
    {
      "id": "l03-similarity-transforms-modes-stability",
      "title": "Similarity transforms, modal coordinates and stability",
      "minutes": 21,
      "covers": [
        "similarity transforms"
      ],
      "file": "t0_m05_linear_algebra_2/03-similarity-transforms-modes-stability.md"
    },
    {
      "id": "l04-symmetric-matrices-spectral-theorem",
      "title": "Symmetric matrices and the spectral theorem",
      "minutes": 21,
      "covers": [
        "symmetric matrices and the spectral theorem"
      ],
      "file": "t0_m05_linear_algebra_2/04-symmetric-matrices-spectral-theorem.md"
    },
    {
      "id": "l05-positive-definiteness-quadratic-forms",
      "title": "Positive definiteness and quadratic forms",
      "minutes": 22,
      "covers": [
        "positive definiteness and quadratic forms"
      ],
      "file": "t0_m05_linear_algebra_2/05-positive-definiteness-quadratic-forms.md"
    },
    {
      "id": "l06-cholesky-factorisation",
      "title": "The Cholesky factorisation",
      "minutes": 21,
      "covers": [
        "Cholesky factorisation"
      ],
      "file": "t0_m05_linear_algebra_2/06-cholesky-factorisation.md"
    }
  ],
  "t0_m06_calculus_single": [
    {
      "id": "l01-limits-and-continuity",
      "title": "Limits and continuity",
      "minutes": 22,
      "covers": [
        "limits and continuity"
      ],
      "file": "t0_m06_calculus_single/01-limits-and-continuity.md"
    },
    {
      "id": "l02-the-derivative",
      "title": "The derivative from first principles",
      "minutes": 24,
      "covers": [
        "the derivative: definition, chain, product and quotient rules"
      ],
      "file": "t0_m06_calculus_single/02-the-derivative.md"
    },
    {
      "id": "l03-differentiation-rules",
      "title": "The product, quotient and chain rules",
      "minutes": 25,
      "covers": [
        "the derivative: definition, chain, product and quotient rules"
      ],
      "file": "t0_m06_calculus_single/03-differentiation-rules.md"
    },
    {
      "id": "l04-implicit-differentiation-related-rates",
      "title": "Implicit differentiation and related rates",
      "minutes": 22,
      "covers": [
        "implicit differentiation and related rates"
      ],
      "file": "t0_m06_calculus_single/04-implicit-differentiation-related-rates.md"
    },
    {
      "id": "l05-maxima-minima-optimisation",
      "title": "Maxima, minima and optimising a scalar function",
      "minutes": 24,
      "covers": [
        "maxima, minima and optimisation of a scalar function"
      ],
      "file": "t0_m06_calculus_single/05-maxima-minima-optimisation.md"
    },
    {
      "id": "l06-linearisation-and-differentials",
      "title": "Linearisation and differentials",
      "minutes": 25,
      "covers": [
        "linearisation and differentials"
      ],
      "file": "t0_m06_calculus_single/06-linearisation-and-differentials.md"
    },
    {
      "id": "l07-taylor-series-truncation-error",
      "title": "Taylor series and truncation error",
      "minutes": 26,
      "covers": [
        "Taylor series and truncation error"
      ],
      "file": "t0_m06_calculus_single/07-taylor-series-truncation-error.md"
    },
    {
      "id": "l08-definite-integral-fundamental-theorem",
      "title": "The definite integral and the fundamental theorem of calculus",
      "minutes": 24,
      "covers": [
        "the definite integral and the fundamental theorem of calculus"
      ],
      "file": "t0_m06_calculus_single/08-definite-integral-fundamental-theorem.md"
    },
    {
      "id": "l09-substitution-and-integration-by-parts",
      "title": "Substitution and integration by parts",
      "minutes": 23,
      "covers": [
        "integration by parts and substitution"
      ],
      "file": "t0_m06_calculus_single/09-substitution-and-integration-by-parts.md"
    },
    {
      "id": "l10-improper-integrals",
      "title": "Improper integrals",
      "minutes": 22,
      "covers": [
        "improper integrals"
      ],
      "file": "t0_m06_calculus_single/10-improper-integrals.md"
    },
    {
      "id": "l11-separable-first-order-odes",
      "title": "Separable first-order ODEs and the rocket equation",
      "minutes": 26,
      "covers": [
        "separable first-order ODEs"
      ],
      "file": "t0_m06_calculus_single/11-separable-first-order-odes.md"
    }
  ],
  "t0_m07_calculus_multi": [
    {
      "id": "l01-partial-derivatives",
      "title": "Functions of several variables and partial derivatives",
      "minutes": 20,
      "covers": [
        "partial derivatives"
      ],
      "file": "t0_m07_calculus_multi/01-partial-derivatives.md"
    },
    {
      "id": "l02-gradient",
      "title": "The gradient and the directional derivative",
      "minutes": 21,
      "covers": [
        "gradient and directional derivative"
      ],
      "file": "t0_m07_calculus_multi/02-gradient.md"
    },
    {
      "id": "l03-jacobian",
      "title": "The Jacobian and the measurement matrix",
      "minutes": 22,
      "covers": [
        "Jacobian and Hessian"
      ],
      "file": "t0_m07_calculus_multi/03-jacobian.md"
    },
    {
      "id": "l04-chain-rule-hessian",
      "title": "The chain rule for vector functions, and the Hessian",
      "minutes": 26,
      "covers": [
        "chain rule for vector functions",
        "Jacobian and Hessian"
      ],
      "file": "t0_m07_calculus_multi/04-chain-rule-hessian.md"
    },
    {
      "id": "l05-curves-and-rotating-frames",
      "title": "Trajectories as vector functions of time",
      "minutes": 26,
      "covers": [
        "vector-valued functions of time, arc length, curvature"
      ],
      "file": "t0_m07_calculus_multi/05-curves-and-rotating-frames.md"
    },
    {
      "id": "l06-multiple-integrals",
      "title": "Double and triple integrals",
      "minutes": 25,
      "covers": [
        "multiple integrals"
      ],
      "file": "t0_m07_calculus_multi/06-multiple-integrals.md"
    },
    {
      "id": "l07-line-and-surface-integrals",
      "title": "Line integrals and surface integrals",
      "minutes": 25,
      "covers": [
        "line and surface integrals"
      ],
      "file": "t0_m07_calculus_multi/07-line-and-surface-integrals.md"
    },
    {
      "id": "l08-div-curl-laplacian",
      "title": "Divergence, curl and the Laplacian",
      "minutes": 25,
      "covers": [
        "divergence, curl, Laplacian"
      ],
      "file": "t0_m07_calculus_multi/08-div-curl-laplacian.md"
    },
    {
      "id": "l09-divergence-and-stokes-theorems",
      "title": "The divergence theorem and Stokes' theorem",
      "minutes": 25,
      "covers": [
        "divergence and Stokes theorems"
      ],
      "file": "t0_m07_calculus_multi/09-divergence-and-stokes-theorems.md"
    },
    {
      "id": "l10-conservative-fields",
      "title": "Conservative fields, potentials and orbital energy",
      "minutes": 27,
      "covers": [
        "conservative fields and potential functions"
      ],
      "file": "t0_m07_calculus_multi/10-conservative-fields.md"
    }
  ],
  "t0_m08_odes": [
    {
      "id": "l01-first-order-odes",
      "title": "First-order ODEs and the actuator lag",
      "minutes": 20,
      "covers": [
        "first-order ODEs: separable, linear, integrating factor"
      ],
      "file": "t0_m08_odes/01-first-order-odes.md"
    },
    {
      "id": "l02-second-order-characteristic-equation",
      "title": "Second-order equations and the characteristic equation",
      "minutes": 20,
      "covers": [
        "second-order linear constant-coefficient ODEs and the characteristic equation"
      ],
      "file": "t0_m08_odes/02-second-order-characteristic-equation.md"
    },
    {
      "id": "l03-damped-oscillator-zeta-omega-n",
      "title": "The damped oscillator, natural frequency and damping ratio",
      "minutes": 19,
      "covers": [
        "the damped oscillator: natural frequency and damping ratio"
      ],
      "file": "t0_m08_odes/03-damped-oscillator-zeta-omega-n.md"
    },
    {
      "id": "l04-state-space-and-matrix-exponential",
      "title": "State-space form and the matrix exponential",
      "minutes": 18,
      "covers": [
        "systems of first-order ODEs and state-space form",
        "matrix exponential solution"
      ],
      "file": "t0_m08_odes/04-state-space-and-matrix-exponential.md"
    },
    {
      "id": "l05-forced-response-and-resonance",
      "title": "Forced response and resonance",
      "minutes": 19,
      "covers": [
        "forced response and resonance"
      ],
      "file": "t0_m08_odes/05-forced-response-and-resonance.md"
    },
    {
      "id": "l06-laplace-transform-partial-fractions",
      "title": "The Laplace transform, partial fractions, and the value theorems",
      "minutes": 22,
      "covers": [
        "Laplace transform, inverse transform, partial fractions",
        "initial and final value theorems"
      ],
      "file": "t0_m08_odes/06-laplace-transform-partial-fractions.md"
    }
  ],
  "t0_m09_probability_stats": [
    {
      "id": "l01-probability-and-bayes",
      "title": "Sample spaces, conditional probability and Bayes' theorem",
      "minutes": 20,
      "covers": [
        "sample spaces, conditional probability, Bayes theorem"
      ],
      "file": "t0_m09_probability_stats/01-probability-and-bayes.md"
    },
    {
      "id": "l02-random-variables-pdf-cdf",
      "title": "Random variables, PDF and CDF",
      "minutes": 21,
      "covers": [
        "random variables, PDF and CDF"
      ],
      "file": "t0_m09_probability_stats/02-random-variables-pdf-cdf.md"
    },
    {
      "id": "l03-expectation-variance-moments",
      "title": "Expectation, variance and moments",
      "minutes": 21,
      "covers": [
        "expectation, variance, moments"
      ],
      "file": "t0_m09_probability_stats/03-expectation-variance-moments.md"
    },
    {
      "id": "l04-gaussian-and-covariance",
      "title": "The Gaussian, covariance matrices and error ellipsoids",
      "minutes": 23,
      "covers": [
        "the Gaussian and multivariate Gaussian, covariance matrices, correlation"
      ],
      "file": "t0_m09_probability_stats/04-gaussian-and-covariance.md"
    },
    {
      "id": "l05-linear-transformations",
      "title": "Linear transformations of random vectors",
      "minutes": 24,
      "covers": [
        "linear transformations of random vectors"
      ],
      "file": "t0_m09_probability_stats/05-linear-transformations.md"
    },
    {
      "id": "l06-sums-and-central-limit-theorem",
      "title": "Sums of random variables and the central limit theorem",
      "minutes": 24,
      "covers": [
        "sums of random variables and the central limit theorem"
      ],
      "file": "t0_m09_probability_stats/06-sums-and-central-limit-theorem.md"
    },
    {
      "id": "l07-random-processes-white-noise-brownian",
      "title": "Random processes, white noise and Brownian motion",
      "minutes": 26,
      "covers": [
        "stochastic processes and Brownian motion",
        "white noise, random walk, Gauss-Markov processes"
      ],
      "file": "t0_m09_probability_stats/07-random-processes-white-noise-brownian.md"
    },
    {
      "id": "l08-gauss-markov-and-imu-error-models",
      "title": "Gauss-Markov processes and IMU error models",
      "minutes": 28,
      "covers": [
        "white noise, random walk, Gauss-Markov processes"
      ],
      "file": "t0_m09_probability_stats/08-gauss-markov-and-imu-error-models.md"
    }
  ],
  "t0_m10_numerical_methods": [
    {
      "id": "l01-floating-point",
      "title": "Floating point in flight software",
      "minutes": 18,
      "covers": [
        "floating-point representation, machine epsilon, catastrophic cancellation"
      ],
      "file": "t0_m10_numerical_methods/01-floating-point.md"
    },
    {
      "id": "l02-root-finding-and-keplers-equation",
      "title": "Root finding and Kepler's equation",
      "minutes": 26,
      "covers": [
        "root finding: bisection, Newton-Raphson, secant, and convergence rates"
      ],
      "file": "t0_m10_numerical_methods/02-root-finding-and-keplers-equation.md"
    },
    {
      "id": "l03-euler-heun-rk4",
      "title": "Euler, Heun and RK4",
      "minutes": 28,
      "covers": [
        "numerical ODE integration: Euler, Heun, RK4, RK45 / Dormand-Prince",
        "local vs global truncation error"
      ],
      "file": "t0_m10_numerical_methods/03-euler-heun-rk4.md"
    }
  ],
  "t0_m11_optimization": [
    {
      "id": "l01-descent-and-line-search",
      "title": "Unconstrained optimisation I: optimality conditions, gradient descent and line search",
      "minutes": 20,
      "covers": [
        "unconstrained optimisation: gradient descent, Newton, BFGS, line search, trust region"
      ],
      "file": "t0_m11_optimization/01-descent-and-line-search.md"
    },
    {
      "id": "l02-lagrange-and-kkt",
      "title": "Constrained optimisation: Lagrange multipliers and the KKT conditions",
      "minutes": 26,
      "covers": [
        "constrained optimisation and Lagrange multipliers",
        "KKT conditions"
      ],
      "file": "t0_m11_optimization/02-lagrange-and-kkt.md"
    },
    {
      "id": "l03-convex-sets-and-functions",
      "title": "Convex sets and convex functions",
      "minutes": 25,
      "covers": [
        "convex sets and convex functions"
      ],
      "file": "t0_m11_optimization/03-convex-sets-and-functions.md"
    },
    {
      "id": "l04-why-convexity-matters",
      "title": "Why convexity matters: global optimum, polynomial time, certificates",
      "minutes": 24,
      "covers": [
        "why convexity matters: global optimum, polynomial time, certificates"
      ],
      "file": "t0_m11_optimization/04-why-convexity-matters.md"
    },
    {
      "id": "l05-linear-and-quadratic-programming",
      "title": "Linear and quadratic programming",
      "minutes": 27,
      "covers": [
        "linear and quadratic programming"
      ],
      "file": "t0_m11_optimization/05-linear-and-quadratic-programming.md"
    }
  ],
  "t0_m12_cpp": [
    {
      "id": "l01-from-python-to-compiled-cpp",
      "title": "From Python to compiled C++",
      "minutes": 24,
      "covers": [
        "C++17/20 core language"
      ],
      "file": "t0_m12_cpp/01-from-python-to-compiled-cpp.md"
    },
    {
      "id": "l02-values-references-const",
      "title": "Value semantics, references and const",
      "minutes": 22,
      "covers": [
        "value semantics, references, const-correctness"
      ],
      "file": "t0_m12_cpp/02-values-references-const.md"
    },
    {
      "id": "l03-raii-ownership-and-moves",
      "title": "RAII, ownership, smart pointers and moves",
      "minutes": 25,
      "covers": [
        "RAII, ownership, smart pointers",
        "move semantics"
      ],
      "file": "t0_m12_cpp/03-raii-ownership-and-moves.md"
    },
    {
      "id": "l04-classes-inheritance-virtual-dispatch",
      "title": "Classes, inheritance and the cost of virtual dispatch",
      "minutes": 24,
      "covers": [
        "classes, inheritance, virtual dispatch and its cost"
      ],
      "file": "t0_m12_cpp/04-classes-inheritance-virtual-dispatch.md"
    },
    {
      "id": "l05-templates-and-generic-programming",
      "title": "Templates and generic programming",
      "minutes": 25,
      "covers": [
        "templates and generic programming"
      ],
      "file": "t0_m12_cpp/05-templates-and-generic-programming.md"
    },
    {
      "id": "l06-stl-containers-algorithms-iterators",
      "title": "The STL: containers, algorithms and iterators",
      "minutes": 24,
      "covers": [
        "the STL: containers, algorithms, iterators"
      ],
      "file": "t0_m12_cpp/06-stl-containers-algorithms-iterators.md"
    },
    {
      "id": "l07-constexpr-compile-time",
      "title": "constexpr and compile-time computation",
      "minutes": 25,
      "covers": [
        "constexpr and compile-time computation"
      ],
      "file": "t0_m12_cpp/07-constexpr-compile-time.md"
    },
    {
      "id": "l08-error-handling-without-exceptions",
      "title": "Error handling without exceptions",
      "minutes": 24,
      "covers": [
        "error handling without exceptions"
      ],
      "file": "t0_m12_cpp/08-error-handling-without-exceptions.md"
    },
    {
      "id": "l09-memory-cache-hot-loops",
      "title": "Memory layout, the cache, and allocation-free hot loops",
      "minutes": 27,
      "covers": [
        "memory layout, cache behaviour, allocation-free hot loops"
      ],
      "file": "t0_m12_cpp/09-memory-cache-hot-loops.md"
    },
    {
      "id": "l10-eigen-and-geometry",
      "title": "Eigen, including the Geometry module",
      "minutes": 24,
      "covers": [
        "Eigen, including the Geometry module"
      ],
      "file": "t0_m12_cpp/10-eigen-and-geometry.md"
    },
    {
      "id": "l11-cmake-and-googletest",
      "title": "Building with CMake and testing with GoogleTest",
      "minutes": 24,
      "covers": [
        "CMake, with Bazel awareness",
        "GoogleTest"
      ],
      "file": "t0_m12_cpp/11-cmake-and-googletest.md"
    },
    {
      "id": "l12-undefined-behaviour-and-sanitizers",
      "title": "Undefined behaviour, and the sanitizers that catch it",
      "minutes": 25,
      "covers": [
        "undefined behaviour",
        "profiling and sanitizers: perf, valgrind, ASan/UBSan"
      ],
      "file": "t0_m12_cpp/12-undefined-behaviour-and-sanitizers.md"
    },
    {
      "id": "l13-profiling-and-static-analysis",
      "title": "Profiling and static analysis: perf, valgrind, clang-tidy and cppcheck",
      "minutes": 26,
      "covers": [
        "profiling and sanitizers: perf, valgrind, ASan/UBSan",
        "static analysis: clang-tidy, cppcheck"
      ],
      "file": "t0_m12_cpp/13-profiling-and-static-analysis.md"
    },
    {
      "id": "l14-pybind11-simulation-core",
      "title": "pybind11 bindings over a C++ simulation core",
      "minutes": 26,
      "covers": [
        "pybind11 bindings over a C++ simulation core"
      ],
      "file": "t0_m12_cpp/14-pybind11-simulation-core.md"
    }
  ],
  "t1_m13_classical_mechanics": [
    {
      "id": "l01-newton-laws-inertial-frames",
      "title": "Newton's laws and inertial frames",
      "minutes": 21,
      "covers": [
        "Newton laws and inertial frames"
      ],
      "file": "t1_m13_classical_mechanics/01-newton-laws-inertial-frames.md"
    },
    {
      "id": "l02-force-momentum-impulse",
      "title": "Force, momentum and impulse",
      "minutes": 20,
      "covers": [
        "force, momentum, impulse"
      ],
      "file": "t1_m13_classical_mechanics/02-force-momentum-impulse.md"
    },
    {
      "id": "l03-work-energy-theorem",
      "title": "Work, kinetic energy and power",
      "minutes": 21,
      "covers": [
        "the work-energy theorem"
      ],
      "file": "t1_m13_classical_mechanics/03-work-energy-theorem.md"
    },
    {
      "id": "l04-conservative-forces-potential-energy",
      "title": "Conservative forces and potential energy",
      "minutes": 20,
      "covers": [
        "conservative forces and potential energy"
      ],
      "file": "t1_m13_classical_mechanics/04-conservative-forces-potential-energy.md"
    },
    {
      "id": "l05-systems-of-particles-centre-of-mass",
      "title": "Systems of particles and the centre of mass",
      "minutes": 23,
      "covers": [
        "systems of particles and the centre of mass"
      ],
      "file": "t1_m13_classical_mechanics/05-systems-of-particles-centre-of-mass.md"
    },
    {
      "id": "l06-rocket-equation-done-properly",
      "title": "Variable mass and the rocket equation, done properly",
      "minutes": 23,
      "covers": [
        "variable-mass systems and the rocket equation done properly"
      ],
      "file": "t1_m13_classical_mechanics/06-rocket-equation-done-properly.md"
    },
    {
      "id": "l07-ascent-losses-gravity-turn",
      "title": "Gravity, drag and steering losses on ascent",
      "minutes": 21,
      "covers": [
        "variable-mass systems and the rocket equation done properly"
      ],
      "file": "t1_m13_classical_mechanics/07-ascent-losses-gravity-turn.md"
    },
    {
      "id": "l08-constraints-generalised-coordinates",
      "title": "Constraints and generalised coordinates",
      "minutes": 24,
      "covers": [
        "constraints and generalised coordinates"
      ],
      "file": "t1_m13_classical_mechanics/08-constraints-generalised-coordinates.md"
    },
    {
      "id": "l09-lagrangian-mechanics-hamilton-principle",
      "title": "Lagrangian mechanics and Hamilton's principle",
      "minutes": 23,
      "covers": [
        "Lagrangian mechanics and the Euler-Lagrange equation",
        "Hamilton principle"
      ],
      "file": "t1_m13_classical_mechanics/09-lagrangian-mechanics-hamilton-principle.md"
    }
  ],
  "t1_m14_rigid_body_dynamics": [
    {
      "id": "l01-rigid-body-kinematics",
      "title": "Rigid body kinematics and the angular velocity vector",
      "minutes": 18,
      "covers": [
        "rigid body kinematics and the angular velocity vector"
      ],
      "file": "t1_m14_rigid_body_dynamics/01-rigid-body-kinematics.md"
    },
    {
      "id": "l02-inertia-tensor-and-parallel-axis-theorem",
      "title": "The inertia tensor and the parallel axis theorem",
      "minutes": 20,
      "covers": [
        "the moment of inertia tensor, products of inertia, parallel axis theorem"
      ],
      "file": "t1_m14_rigid_body_dynamics/02-inertia-tensor-and-parallel-axis-theorem.md"
    },
    {
      "id": "l03-principal-axes-and-principal-moments",
      "title": "Principal axes and principal moments",
      "minutes": 20,
      "covers": [
        "principal axes and principal moments"
      ],
      "file": "t1_m14_rigid_body_dynamics/03-principal-axes-and-principal-moments.md"
    },
    {
      "id": "l04-angular-momentum-h-equals-i-omega",
      "title": "Angular momentum H = Iω and rotational kinetic energy",
      "minutes": 16,
      "covers": [
        "angular momentum H = I omega"
      ],
      "file": "t1_m14_rigid_body_dynamics/04-angular-momentum-h-equals-i-omega.md"
    }
  ],
  "t1_m15_rotating_frames": [
    {
      "id": "l01-frames-coordinates-and-rotation-matrices",
      "title": "Frames, coordinates and rotation matrices",
      "minutes": 18,
      "covers": [
        "frame transformation chains and notation discipline"
      ],
      "file": "t1_m15_rotating_frames/01-frames-coordinates-and-rotation-matrices.md"
    },
    {
      "id": "l02-the-transport-theorem",
      "title": "The transport theorem",
      "minutes": 16,
      "covers": [
        "the transport theorem"
      ],
      "file": "t1_m15_rotating_frames/02-the-transport-theorem.md"
    },
    {
      "id": "l03-velocity-and-acceleration-in-rotating-frames",
      "title": "Velocity and acceleration in rotating frames",
      "minutes": 17,
      "covers": [
        "velocity and acceleration in rotating frames"
      ],
      "file": "t1_m15_rotating_frames/03-velocity-and-acceleration-in-rotating-frames.md"
    },
    {
      "id": "l04-coriolis-centrifugal-and-euler-terms",
      "title": "Coriolis, centrifugal and Euler terms",
      "minutes": 20,
      "covers": [
        "Coriolis, centrifugal and Euler acceleration terms"
      ],
      "file": "t1_m15_rotating_frames/04-coriolis-centrifugal-and-euler-terms.md"
    },
    {
      "id": "l05-eci-ecef-and-the-earth-rotation-rate",
      "title": "ECI, ECEF and the Earth rotation rate",
      "minutes": 21,
      "covers": [
        "Earth rotation rate",
        "ECI (J2000 / GCRF) and ECEF (ITRF)"
      ],
      "file": "t1_m15_rotating_frames/05-eci-ecef-and-the-earth-rotation-rate.md"
    },
    {
      "id": "l06-wgs-84-geodetic-latitude-ned-and-enu",
      "title": "WGS-84, geodetic latitude, NED and ENU",
      "minutes": 19,
      "covers": [
        "geodetic vs geocentric latitude and the WGS-84 ellipsoid",
        "NED and ENU local-level frames"
      ],
      "file": "t1_m15_rotating_frames/06-wgs-84-geodetic-latitude-ned-and-enu.md"
    },
    {
      "id": "l07-body-lvlh-perifocal-topocentric-and-sensor-frames",
      "title": "Body, LVLH, perifocal, topocentric and sensor frames",
      "minutes": 24,
      "covers": [
        "body, LVLH / RIC, perifocal, topocentric and sensor frames"
      ],
      "file": "t1_m15_rotating_frames/07-body-lvlh-perifocal-topocentric-and-sensor-frames.md"
    },
    {
      "id": "l08-ut1-tai-gps-and-tt-time-scales",
      "title": "UT1, TAI, GPS and TT time scales",
      "minutes": 22,
      "covers": [
        "UT1, TAI, GPS and TT time scales"
      ],
      "file": "t1_m15_rotating_frames/08-ut1-tai-gps-and-tt-time-scales.md"
    },
    {
      "id": "l09-precession-nutation-and-polar-motion",
      "title": "Precession, nutation and polar motion",
      "minutes": 22,
      "covers": [
        "precession, nutation, polar motion"
      ],
      "file": "t1_m15_rotating_frames/09-precession-nutation-and-polar-motion.md"
    }
  ],
  "t1_m18_atmospheric_flight": [
    {
      "id": "l01-standard-atmosphere",
      "title": "The standard atmosphere",
      "minutes": 18,
      "covers": [
        "standard atmosphere models: US Standard 1976, exponential, NRLMSISE-00",
        "density, pressure and temperature vs altitude"
      ],
      "file": "t1_m18_atmospheric_flight/01-standard-atmosphere.md"
    },
    {
      "id": "l02-dynamic-pressure-and-max-q",
      "title": "Dynamic pressure and max-Q",
      "minutes": 17,
      "covers": [
        "dynamic pressure and max-Q"
      ],
      "file": "t1_m18_atmospheric_flight/02-dynamic-pressure-and-max-q.md"
    },
    {
      "id": "l03-mach-regimes-and-drag",
      "title": "Mach number, flow regimes and the drag coefficient",
      "minutes": 20,
      "covers": [
        "Mach number and the subsonic / transonic / supersonic / hypersonic regimes",
        "drag coefficient vs Mach"
      ],
      "file": "t1_m18_atmospheric_flight/03-mach-regimes-and-drag.md"
    },
    {
      "id": "l04-angle-of-attack-and-wind-frame",
      "title": "Angle of attack, sideslip and the wind frame",
      "minutes": 18,
      "covers": [
        "angle of attack and sideslip; body vs wind frame"
      ],
      "file": "t1_m18_atmospheric_flight/04-angle-of-attack-and-wind-frame.md"
    },
    {
      "id": "l05-normal-force-and-static-margin",
      "title": "Normal force, centre of pressure and static margin",
      "minutes": 19,
      "covers": [
        "normal force, centre of pressure vs centre of gravity, static margin"
      ],
      "file": "t1_m18_atmospheric_flight/05-normal-force-and-static-margin.md"
    },
    {
      "id": "l06-unstable-booster-and-tvc",
      "title": "The aerodynamically unstable booster and its TVC loop",
      "minutes": 19,
      "covers": [
        "aerodynamic instability of a boosting rocket"
      ],
      "file": "t1_m18_atmospheric_flight/06-unstable-booster-and-tvc.md"
    },
    {
      "id": "l07-q-alpha-and-load-relief",
      "title": "The q-alpha load indicator and load relief",
      "minutes": 18,
      "covers": [
        "the q-alpha load indicator and load relief control"
      ],
      "file": "t1_m18_atmospheric_flight/07-q-alpha-and-load-relief.md"
    },
    {
      "id": "l08-winds-gusts-and-shear",
      "title": "Wind profiles, gusts and wind shear",
      "minutes": 19,
      "covers": [
        "wind profiles and gust models (Dryden, von Karman), wind shear"
      ],
      "file": "t1_m18_atmospheric_flight/08-winds-gusts-and-shear.md"
    },
    {
      "id": "l09-bending-modes-and-structural-filters",
      "title": "Bending modes, flexible-body dynamics and structural filters",
      "minutes": 21,
      "covers": [
        "bending modes, flexible body dynamics and structural filter design"
      ],
      "file": "t1_m18_atmospheric_flight/09-bending-modes-and-structural-filters.md"
    },
    {
      "id": "l10-propellant-slosh",
      "title": "Propellant slosh as a pendulum or mass-spring",
      "minutes": 21,
      "covers": [
        "propellant slosh as a pendulum or mass-spring"
      ],
      "file": "t1_m18_atmospheric_flight/10-propellant-slosh.md"
    },
    {
      "id": "l11-control-structure-interaction",
      "title": "Control-structure interaction",
      "minutes": 20,
      "covers": [
        "control-structure interaction"
      ],
      "file": "t1_m18_atmospheric_flight/11-control-structure-interaction.md"
    },
    {
      "id": "l12-grid-fins-and-entry",
      "title": "Grid fins, control surfaces and entry aerodynamics",
      "minutes": 22,
      "covers": [
        "grid fins and aerodynamic control surfaces",
        "ballistic coefficient and lift-to-drag ratio in entry"
      ],
      "file": "t1_m18_atmospheric_flight/12-grid-fins-and-entry.md"
    }
  ],
  "t2_m19_two_body": [
    {
      "id": "l01-two-body-equation",
      "title": "Newton's gravitation and the two-body equation",
      "minutes": 16,
      "covers": [
        "Newton law of gravitation and the restricted two-body equation"
      ],
      "file": "t2_m19_two_body/01-two-body-equation.md"
    },
    {
      "id": "l02-constants-of-motion",
      "title": "Constants of motion – angular momentum, energy and the eccentricity vector",
      "minutes": 16,
      "covers": [
        "constants of motion: specific angular momentum, eccentricity vector, specific energy"
      ],
      "file": "t2_m19_two_body/02-constants-of-motion.md"
    },
    {
      "id": "l03-orbit-equation-conics",
      "title": "The orbit equation and conic sections",
      "minutes": 17,
      "covers": [
        "the orbit equation and conic sections"
      ],
      "file": "t2_m19_two_body/03-orbit-equation-conics.md"
    },
    {
      "id": "l04-kepler-laws-vis-viva",
      "title": "Kepler's three laws and the vis-viva equation",
      "minutes": 16,
      "covers": [
        "Kepler three laws, derived",
        "vis-viva"
      ],
      "file": "t2_m19_two_body/04-kepler-laws-vis-viva.md"
    },
    {
      "id": "l05-orbit-families",
      "title": "Circular, elliptical, parabolic and hyperbolic orbits",
      "minutes": 16,
      "covers": [
        "circular, elliptical, parabolic and hyperbolic orbits"
      ],
      "file": "t2_m19_two_body/05-orbit-families.md"
    },
    {
      "id": "l06-classical-elements",
      "title": "The classical orbital elements and equinoctial alternatives",
      "minutes": 16,
      "covers": [
        "classical orbital elements and equinoctial alternatives"
      ],
      "file": "t2_m19_two_body/06-classical-elements.md"
    },
    {
      "id": "l07-state-vector-conversions",
      "title": "State vector to orbital elements and back",
      "minutes": 17,
      "covers": [
        "state vector to orbital element conversion, both directions"
      ],
      "file": "t2_m19_two_body/07-state-vector-conversions.md"
    },
    {
      "id": "l08-anomalies-kepler-equation",
      "title": "True, eccentric and mean anomaly, and Kepler's equation",
      "minutes": 17,
      "covers": [
        "true, eccentric and mean anomaly",
        "Kepler equation: elliptic, hyperbolic and parabolic (Barker)"
      ],
      "file": "t2_m19_two_body/08-anomalies-kepler-equation.md"
    },
    {
      "id": "l09-solving-kepler",
      "title": "Solving Kepler's equation robustly",
      "minutes": 19,
      "covers": [
        "Kepler equation: elliptic, hyperbolic and parabolic (Barker)"
      ],
      "file": "t2_m19_two_body/09-solving-kepler.md"
    },
    {
      "id": "l10-time-of-flight",
      "title": "Time of flight and analytic propagation",
      "minutes": 19,
      "covers": [
        "time of flight"
      ],
      "file": "t2_m19_two_body/10-time-of-flight.md"
    },
    {
      "id": "l11-universal-variables",
      "title": "Universal variables and the Stumpff functions",
      "minutes": 17,
      "covers": [
        "universal variables and the Stumpff functions"
      ],
      "file": "t2_m19_two_body/11-universal-variables.md"
    },
    {
      "id": "l12-lagrange-coefficients",
      "title": "The Lagrange f and g coefficients",
      "minutes": 15,
      "covers": [
        "Lagrange f and g coefficients"
      ],
      "file": "t2_m19_two_body/12-lagrange-coefficients.md"
    },
    {
      "id": "l13-ground-tracks-orbit-types",
      "title": "Ground tracks and the named orbit types",
      "minutes": 18,
      "covers": [
        "ground tracks and orbit types: LEO, MEO, GEO, GTO, SSO, Molniya, frozen"
      ],
      "file": "t2_m19_two_body/13-ground-tracks-orbit-types.md"
    },
    {
      "id": "l14-tle-sgp4",
      "title": "The TLE format and SGP4",
      "minutes": 19,
      "covers": [
        "TLE format and SGP4"
      ],
      "file": "t2_m19_two_body/14-tle-sgp4.md"
    }
  ]
}

/** Derived: how much of each module its lessons actually teach. */
export interface LessonCoverage {
  covered: number
  total: number
  complete: boolean
  missing: string[]
}

export const LESSON_COVERAGE: Record<string, LessonCoverage> = {
  "t0_m01_algebra_precalc": {
    "covered": 12,
    "total": 12,
    "complete": true,
    "missing": []
  },
  "t0_m02_trigonometry": {
    "covered": 10,
    "total": 10,
    "complete": true,
    "missing": []
  },
  "t0_m03_python_scicomp": {
    "covered": 10,
    "total": 10,
    "complete": true,
    "missing": []
  },
  "t0_m04_linear_algebra_1": {
    "covered": 10,
    "total": 10,
    "complete": true,
    "missing": []
  },
  "t0_m05_linear_algebra_2": {
    "covered": 6,
    "total": 11,
    "complete": false,
    "missing": [
      "singular value decomposition",
      "pseudoinverse and rank deficiency",
      "condition number",
      "least squares: normal equations vs QR vs SVD",
      "matrix calculus: gradients and Jacobians"
    ]
  },
  "t0_m06_calculus_single": {
    "covered": 10,
    "total": 10,
    "complete": true,
    "missing": []
  },
  "t0_m07_calculus_multi": {
    "covered": 10,
    "total": 10,
    "complete": true,
    "missing": []
  },
  "t0_m08_odes": {
    "covered": 8,
    "total": 12,
    "complete": false,
    "missing": [
      "transfer functions",
      "convolution and impulse response",
      "stability from pole locations",
      "phase-plane basics"
    ]
  },
  "t0_m09_probability_stats": {
    "covered": 8,
    "total": 13,
    "complete": false,
    "missing": [
      "power spectral density and autocorrelation",
      "maximum likelihood estimation",
      "confidence intervals and hypothesis testing",
      "Monte Carlo methods and convergence rates",
      "the chi-square distribution and filter consistency testing"
    ]
  },
  "t0_m10_numerical_methods": {
    "covered": 4,
    "total": 13,
    "complete": false,
    "missing": [
      "adaptive step-size control",
      "Adams-Bashforth / Adams-Moulton multistep methods",
      "stiffness and implicit methods: backward Euler, BDF",
      "symplectic integrators for long orbit propagation",
      "energy drift as a correctness check",
      "interpolation: linear and cubic spline",
      "numerical differentiation and complex-step derivatives",
      "quadrature: Simpson, Gauss-Legendre",
      "conditioning and stability of linear solves, sparse matrices"
    ]
  },
  "t0_m11_optimization": {
    "covered": 6,
    "total": 14,
    "complete": false,
    "missing": [
      "second-order cone programming",
      "semidefinite programming",
      "duality and the dual problem",
      "interior-point methods",
      "sequential quadratic programming",
      "nonlinear programming solvers (IPOPT, SNOPT)",
      "modelling languages and solvers: CVXPY, ECOS, SCS, OSQP, Clarabel",
      "real-time embedded convex solvers and code generation"
    ]
  },
  "t0_m12_cpp": {
    "covered": 17,
    "total": 17,
    "complete": true,
    "missing": []
  },
  "t1_m13_classical_mechanics": {
    "covered": 9,
    "total": 9,
    "complete": true,
    "missing": []
  },
  "t1_m14_rigid_body_dynamics": {
    "covered": 4,
    "total": 12,
    "complete": false,
    "missing": [
      "Euler rotational equations of motion",
      "torque-free motion, polhode and herpolhode",
      "major/minor axis spin stability and the intermediate axis theorem",
      "energy dissipation and the flat-spin instability",
      "gyroscopic effects, nutation, precession",
      "dual-spin spacecraft",
      "momentum wheels and control moment gyros",
      "introduction to flexible modes and propellant slosh"
    ]
  },
  "t1_m15_rotating_frames": {
    "covered": 11,
    "total": 11,
    "complete": true,
    "missing": []
  },
  "t1_m18_atmospheric_flight": {
    "covered": 15,
    "total": 15,
    "complete": true,
    "missing": []
  },
  "t2_m19_two_body": {
    "covered": 15,
    "total": 15,
    "complete": true,
    "missing": []
  }
}
