// Generated by scripts/lessons-manifest.ts — do not edit by hand.
// Lesson metadata for every module that has lessons on disk; bodies load lazily.
import type { LessonMeta } from './types'

export const LESSON_MANIFEST: Record<string, LessonMeta[]> = {}
