import type { CommandRef } from './types'

export const COMMANDS: CommandRef[] = [
  // ---------------------------------------------------------------- CMake: setting up a project
  {
    name: 'cmake_minimum_required',
    lang: 'cmake',
    kind: 'function',
    official: 'Require a minimum version of cmake.',
    source: 'CMake documentation',
    when: 'The very first line of every top-level CMakeLists.txt. It stops with a clear error on an older CMake, and it also switches on the behavior (the policies) of that version, so raising the number can change how your project builds.',
    flags: [['VERSION', 'the oldest CMake this project promises to work with, such as 3.28']],
    example: { command: 'cmake_minimum_required(VERSION 3.28)', says: 'Configuring with CMake 3.28 or newer goes ahead; an older CMake stops at line 1 and says which version it needs.' },
    seeAlso: ['project', 'cmake_policy', 'CMAKE_MINIMUM_REQUIRED_VERSION'],
  },
  {
    name: 'project',
    lang: 'cmake',
    kind: 'function',
    official: 'Set the name of the project.',
    source: 'CMake documentation',
    when: 'Right after cmake_minimum_required, once per top-level CMakeLists.txt. It also finds the compilers for the languages you list, so a missing C++ compiler shows up here.',
    flags: [
      ['VERSION', 'the project version, such as 0.1.0; it fills PROJECT_VERSION'],
      ['LANGUAGES', 'which languages the project uses, such as CXX for C++ (C and CXX if you leave it out)'],
    ],
    example: { command: 'project(orbit_speed VERSION 0.1.0 LANGUAGES CXX)', says: 'Names the project orbit_speed, sets its version to 0.1.0 and looks for a C++ compiler only.' },
    seeAlso: ['cmake_minimum_required', 'add_executable'],
  },
  {
    name: 'set',
    lang: 'cmake',
    kind: 'function',
    official: 'Set a normal, cache, or environment variable to a given value.',
    source: 'CMake documentation',
    when: 'You want to store a value in a variable, or give one of CMake\'s own CMAKE_ variables a value, as a toolchain file does. Read it back with ${NAME}. Several values become one list with semicolons between them, and a variable set inside a subfolder\'s CMakeLists.txt is not seen by its parent.',
    flags: [
      ['CACHE', 'store it in the build folder\'s cache, so it can be changed with -D on the command line'],
      ['PATH', 'after CACHE: the value is a folder, with a help string after it'],
    ],
    example: { command: 'set(CMAKE_CXX_STANDARD 20)', says: 'Every C++ target made after this line is compiled as C++20.' },
    seeAlso: ['option', 'list', 'message'],
  },
  {
    name: 'option',
    lang: 'cmake',
    kind: 'function',
    official: 'Provide a boolean option that the user can optionally select.',
    source: 'CMake documentation',
    when: 'You want an on-or-off switch that whoever builds the project can flip with -D, such as turning sanitizers on. It is OFF unless you give ON, and the value is remembered in the build folder, so changing the line later does not change an existing build folder.',
    example: {
      command: 'option(GNC_SANITIZE "Build with AddressSanitizer and UBSan" OFF)',
      says: 'Adds a switch that is off by default; cmake -S . -B build -DGNC_SANITIZE=ON turns it on.',
    },
    seeAlso: ['if', 'set'],
  },
  {
    name: 'message',
    lang: 'cmake',
    kind: 'function',
    official: 'Log a message.',
    source: 'CMake documentation',
    when: 'You want to print something while CMake configures, such as the value of a variable you are checking. With FATAL_ERROR it stops configuring altogether.',
    flags: [['STATUS', 'an ordinary progress line, printed with -- in front']],
    example: { command: 'message(STATUS "Configuring ${PROJECT_NAME} ${PROJECT_VERSION}")', says: 'Prints -- Configuring orbit_speed 0.1.0 while CMake configures.' },
    seeAlso: ['set'],
  },
  {
    name: 'include',
    lang: 'cmake',
    kind: 'function',
    official: 'Load and run CMake code from a file or module.',
    source: 'CMake documentation',
    when: 'You need commands from one of CMake\'s modules, such as FetchContent, GoogleTest or GNUInstallDirs, or from a .cmake file of your own. The module\'s commands do not exist until this line has run.',
    example: { command: 'include(GoogleTest)', says: 'Loads the GoogleTest module, so gtest_discover_tests can be used after it.' },
    seeAlso: ['CMAKE_MODULE_PATH', 'gtest_discover_tests', 'fetchcontent_declare'],
  },
  {
    name: 'cmake_policy',
    lang: 'cmake',
    kind: 'function',
    official: 'Manage CMake Policy settings.',
    source: 'CMake documentation',
    when: 'You want to see or change how CMake handles one behavior that changed between versions (a policy, named like CMP0135). Most projects never need it: cmake_minimum_required already picks the policies of its version.',
    flags: [['GET', 'copy a policy\'s setting (NEW, OLD or empty) into a variable']],
    example: { command: 'cmake_policy(GET CMP0135 ts)', says: 'Puts NEW, OLD or nothing into the variable ts, depending on the version in cmake_minimum_required.' },
    seeAlso: ['cmake_minimum_required'],
  },
  {
    name: 'if',
    lang: 'cmake',
    kind: 'function',
    official: 'Conditionally execute a group of commands.',
    source: 'CMake documentation',
    when: 'Some lines should run only in some builds: when an option is ON, when cross-compiling, or for one build type. It must be closed with endif(). Compare text with STREQUAL, not ==, and note that a bare variable name counts as false when it is OFF, 0, empty or NOTFOUND.',
    flags: [['STREQUAL', 'true when the two strings are exactly the same']],
    example: { command: 'if(CMAKE_BUILD_TYPE STREQUAL "Debug")', says: 'The lines up to endif() run only when configuring a Debug build.' },
    seeAlso: ['else', 'endif', 'option'],
  },
  {
    name: 'else',
    lang: 'cmake',
    kind: 'function',
    official: 'Starts the else portion of an if block.',
    source: 'CMake documentation',
    when: 'Between if() and endif(), for the lines that should run when the condition is false. Write it as else() with empty brackets; like every CMake command, it needs them.',
    example: {
      command: 'if(CMAKE_CROSSCOMPILING)\n  ...\nelse()\n  enable_testing()\nendif()',
      says: 'Turns testing on only when building for the machine you are sitting at.',
    },
    seeAlso: ['if', 'endif'],
  },
  {
    name: 'endif',
    lang: 'cmake',
    kind: 'function',
    official: 'Ends a list of commands in an if block.',
    source: 'CMake documentation',
    when: 'Closes every if(). Leave the brackets empty: old projects repeat the condition inside, but that is only kept for backward compatibility.',
    example: { command: 'if(GNC_SANITIZE)\n  target_link_options(tests PRIVATE -fsanitize=address,undefined)\nendif()', says: 'Adds the sanitizer link flag only when the GNC_SANITIZE option is ON.' },
    seeAlso: ['if', 'else'],
  },
  {
    name: 'list',
    lang: 'cmake',
    kind: 'function',
    official: 'Operations on semicolon-separated lists.',
    source: 'CMake documentation',
    when: 'You want to add to, read or change a CMake list, which is really one string with semicolons between the items. Pass the list by its name, without ${}.',
    flags: [['APPEND', 'add items to the end of the list']],
    example: { command: 'list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake)', says: 'Adds the project\'s cmake folder to the places include() looks for modules.' },
    seeAlso: ['set', 'CMAKE_MODULE_PATH'],
  },
  {
    name: 'file',
    lang: 'cmake',
    kind: 'function',
    official: 'File manipulation command.',
    source: 'CMake documentation',
    when: 'You need to read, write or search for files while CMake configures. Do not use file(GLOB ...) to collect source files: it runs only at configure time, so a new .cpp file is silently left out of the build until someone configures again.',
    flags: [['GLOB', 'make a list of the files that match a pattern such as src/*.cpp']],
    example: { command: 'file(GLOB SRCS src/*.cpp)', says: 'Puts every .cpp file in src into SRCS, as they were when CMake configured. List sources by name instead.' },
    seeAlso: ['add_library'],
  },

  // ---------------------------------------------------------------- CMake: targets
  {
    name: 'add_executable',
    lang: 'cmake',
    kind: 'function',
    official: 'Add an executable to the project using the specified source files.',
    source: 'CMake documentation',
    when: 'You want CMake to build a program. List only the .cpp files; headers are found through the include path. The name you give becomes the target name you use in later commands.',
    example: { command: 'add_executable(orbit_report apps/orbit_report.cpp)', says: 'Builds a program called orbit_report from that one source file.' },
    seeAlso: ['add_library', 'target_link_libraries'],
  },
  {
    name: 'add_library',
    lang: 'cmake',
    kind: 'function',
    official: 'Add a library to the project using the specified source files.',
    source: 'CMake documentation',
    when: 'You want code that several programs or tests share. Say the kind: STATIC is copied into each program, SHARED is loaded when the program starts, INTERFACE is header-only and builds nothing. Leave the kind out and the BUILD_SHARED_LIBS switch decides.',
    flags: [
      ['STATIC', 'an archive, libname.a, copied into the program at link time'],
      ['SHARED', 'a libname.so file the program loads every time it starts'],
      ['INTERFACE', 'no sources and no file, only settings for users (header-only code)'],
      ['ALIAS', 'a second name for an existing target, such as gnc::gnc'],
      ['IMPORTED', 'stands for a library that was already built elsewhere'],
    ],
    example: { command: 'add_library(gnc STATIC src/orbit.cpp)', says: 'Builds libgnc.a from orbit.cpp, ready to link into programs.' },
    seeAlso: ['add_executable', 'target_link_libraries', 'target_include_directories'],
  },
  {
    name: 'target_link_libraries',
    lang: 'cmake',
    kind: 'function',
    official: 'Specify libraries or flags to use when linking a given target and/or its dependents.',
    source: 'CMake documentation',
    when: 'One target uses another: a program uses your library, or your library uses Eigen. It also hands over the other target\'s include folders and settings. A misspelled plain name is quietly passed to the linker as -lname, so prefer names with :: such as Eigen3::Eigen, which CMake checks.',
    flags: [
      ['PRIVATE', 'needed to build this target only'],
      ['PUBLIC', 'needed by this target and by everything that links it'],
      ['INTERFACE', 'needed only by the targets that link this one'],
    ],
    example: { command: 'target_link_libraries(nav_app PRIVATE gnc)', says: 'Links the gnc library into nav_app and gives nav_app the include folders gnc passes on.' },
    seeAlso: ['add_library', 'target_include_directories', 'find_package'],
  },
  {
    name: 'target_include_directories',
    lang: 'cmake',
    kind: 'function',
    official: 'Add include directories to a target.',
    source: 'CMake documentation',
    when: 'Tell the compiler where a target\'s headers live, the -I flag. Make the folder of your public headers PUBLIC (INTERFACE on a header-only library) so users find them too; a relative path is relative to this CMakeLists.txt.',
    flags: [
      ['PRIVATE', 'only this target\'s own files search here'],
      ['PUBLIC', 'this target and everything that links it search here'],
      ['INTERFACE', 'only the targets that link this one search here'],
    ],
    example: { command: 'target_include_directories(gnc PUBLIC include PRIVATE src)', says: 'gnc and its users find headers in include; only gnc\'s own files look in src.' },
    seeAlso: ['target_link_libraries', 'include_directories'],
  },
  {
    name: 'target_compile_features',
    lang: 'cmake',
    kind: 'function',
    official: 'Add expected compiler features to a target.',
    source: 'CMake documentation',
    when: 'A target needs a certain C++ version, such as C++20. Make it PUBLIC when your public headers need it, so every user is compiled with that version too.',
    flags: [['cxx_std_20', 'this code needs at least C++20']],
    example: { command: 'target_compile_features(gnc PUBLIC cxx_std_20)', says: 'Compiles gnc, and everything that links it, as C++20 or newer.' },
    seeAlso: ['CMAKE_CXX_STANDARD', 'target_compile_options'],
  },
  {
    name: 'target_compile_options',
    lang: 'cmake',
    kind: 'function',
    official: 'Add compile options to a target.',
    source: 'CMake documentation',
    when: 'You want extra compiler flags on one target, such as warnings. Keep warning flags PRIVATE: a PUBLIC -Werror is forced onto everyone who links your library and can break their build.',
    flags: [
      ['PRIVATE', 'for this target\'s own files only'],
      ['INTERFACE', 'for the targets that link this one'],
    ],
    example: { command: 'target_compile_options(gnc PRIVATE -Wall -Wextra -Wpedantic)', says: 'Compiles gnc\'s own files with those warnings switched on.' },
    seeAlso: ['target_link_options', 'target_compile_definitions', 'CMAKE_CXX_FLAGS'],
  },
  {
    name: 'target_compile_definitions',
    lang: 'cmake',
    kind: 'function',
    official: 'Add compile definitions to a target.',
    source: 'CMake documentation',
    when: 'You want a preprocessor macro, the -D flag, defined for one target. Make it PUBLIC only if a public header tests it; otherwise PRIVATE.',
    flags: [
      ['PUBLIC', 'defined for this target and everything that links it'],
      ['PRIVATE', 'defined for this target\'s own files only'],
    ],
    example: { command: 'target_compile_definitions(gnc PRIVATE GNC_LOG_LEVEL=2)', says: 'Compiles gnc\'s files as if each started with #define GNC_LOG_LEVEL 2.' },
    seeAlso: ['add_compile_definitions', 'add_definitions', 'target_compile_options'],
  },
  {
    name: 'target_link_options',
    lang: 'cmake',
    kind: 'function',
    official: 'Add options to the link step for an executable, shared library or module library target.',
    source: 'CMake documentation',
    when: 'A flag must reach the linker, not only the compiler: sanitizers and coverage need it in both places, and firmware needs its linker script. It does nothing on a STATIC library, which is never linked on its own.',
    flags: [
      ['PRIVATE', 'for linking this target only'],
      ['INTERFACE', 'for linking the targets that link this one'],
    ],
    example: { command: 'target_link_options(tests PRIVATE -fsanitize=address,undefined)', says: 'Links the tests program with the sanitizer libraries it was compiled for.' },
    seeAlso: ['target_compile_options', 'target_link_libraries'],
  },
  {
    name: 'set_target_properties',
    lang: 'cmake',
    kind: 'function',
    official: 'Sets properties on targets.',
    source: 'CMake documentation',
    when: 'You need to set one of a target\'s properties directly, such as a file its link depends on, or the paths of an imported target. For everyday settings the target_ commands are clearer.',
    flags: [['PROPERTIES', 'then pairs of property name and value']],
    example: { command: 'set_target_properties(fc.elf PROPERTIES LINK_DEPENDS ${CMAKE_SOURCE_DIR}/stm32f4.ld)', says: 'Relinks fc.elf whenever the linker script changes.' },
    seeAlso: ['set_property'],
  },
  {
    name: 'set_property',
    lang: 'cmake',
    kind: 'function',
    official: 'Set a named property in a given scope.',
    source: 'CMake documentation',
    when: 'Like set_target_properties, but it can also add to a property instead of replacing it, and works on tests, files and folders too. You mostly meet it in files CMake writes for you.',
    flags: [
      ['TARGET', 'the property belongs to these targets'],
      ['APPEND', 'add to the existing value instead of replacing it'],
      ['PROPERTY', 'then the property name and its value'],
    ],
    example: { command: 'set_property(TARGET gnc::gnc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)', says: 'Adds RELEASE to the list of builds the imported gnc::gnc has files for.' },
    seeAlso: ['set_target_properties'],
  },
  {
    name: 'include_directories',
    lang: 'cmake',
    kind: 'function',
    official: 'Add include directories to the build.',
    source: 'CMake documentation',
    when: 'Old-style CMake. It adds the folder for every target in this folder and below, and cannot be passed on to another project; use target_include_directories on the one target that needs it.',
    example: { command: 'include_directories(mathlib/include)', says: 'Every target from here down searches mathlib/include for headers, whether it needs to or not.' },
    seeAlso: ['target_include_directories'],
  },
  {
    name: 'add_definitions',
    lang: 'cmake',
    kind: 'function',
    official: 'Add -D define flags to the compilation of source files.',
    source: 'CMake documentation',
    when: 'Old-style CMake: it applies to every target in this folder and below. Use target_compile_definitions on the target that needs the macro.',
    example: { command: 'add_definitions(-DGNC_LOG_LEVEL=2)', says: 'Defines GNC_LOG_LEVEL as 2 for every target from here down.' },
    seeAlso: ['target_compile_definitions', 'add_compile_definitions'],
  },
  {
    name: 'add_compile_definitions',
    lang: 'cmake',
    kind: 'function',
    official: 'Add preprocessor definitions to the compilation of source files.',
    source: 'CMake documentation',
    when: 'You want a macro defined for every target in this folder and below. Write it without -D. For one target, target_compile_definitions is the better choice.',
    example: { command: 'add_compile_definitions(GNC_CHECK_LEVEL=2)', says: 'Defines GNC_CHECK_LEVEL as 2 for every target from here down.' },
    seeAlso: ['target_compile_definitions', 'add_definitions'],
  },
  {
    name: 'add_subdirectory',
    lang: 'cmake',
    kind: 'function',
    official: 'Add a subdirectory to the build.',
    source: 'CMake documentation',
    when: 'Your project is split into folders such as src, apps and tests, each with its own CMakeLists.txt. The folder must contain a CMakeLists.txt; an empty git submodule folder fails here.',
    example: { command: 'add_subdirectory(tests)', says: 'Runs tests/CMakeLists.txt as part of this build, with its own folder under build/.' },
    seeAlso: ['enable_testing', 'fetchcontent_makeavailable'],
  },
  {
    name: 'add_custom_command',
    lang: 'cmake',
    kind: 'function',
    official: 'Add a custom build rule to the generated build system.',
    source: 'CMake documentation',
    when: 'A tool must run as part of the build, such as turning a finished firmware file into a raw image for the chip.',
    flags: [
      ['TARGET', 'attach the command to this existing target'],
      ['POST_BUILD', 'run it right after the target is built'],
      ['COMMAND', 'the program to run and its arguments'],
      ['COMMENT', 'a line to print while it runs'],
    ],
    example: {
      command: 'add_custom_command(TARGET fin_controller POST_BUILD\n  COMMAND ${CMAKE_OBJCOPY} -O binary $<TARGET_FILE:fin_controller> fin_controller.bin)',
      says: 'After fin_controller is built, writes fin_controller.bin, the raw image to flash onto the chip.',
    },
    seeAlso: ['add_custom_target', 'CMAKE_OBJCOPY'],
  },
  {
    name: 'add_custom_target',
    lang: 'cmake',
    kind: 'function',
    official: 'Add a target with no output so it will always be built.',
    source: 'CMake documentation',
    when: 'You want a named job you run on purpose, such as regenerating test data, with cmake --build build --target name. Without ALL it is left out of a normal build.',
    flags: [
      ['COMMAND', 'the program to run and its arguments'],
      ['WORKING_DIRECTORY', 'the folder to run it in'],
      ['COMMENT', 'a line to print when it starts'],
    ],
    example: {
      command: 'add_custom_target(regenerate_golden\n  COMMAND Python3::Interpreter tools/make_golden_leo_j2.py)',
      says: 'cmake --build build --target regenerate_golden runs the script; a normal build never does.',
    },
    seeAlso: ['add_custom_command'],
  },

  // ---------------------------------------------------------------- CMake: dependencies
  {
    name: 'find_package',
    lang: 'cmake',
    kind: 'function',
    official: 'Find a package (usually provided by something external to the project), and load its package-specific details.',
    source: 'CMake documentation',
    when: 'Your project uses a library already installed on the machine, such as Eigen or GoogleTest; afterwards you link its imported target, like Eigen3::Eigen. If it is installed somewhere unusual, point CMAKE_PREFIX_PATH at it.',
    flags: [
      ['3.4 (a version)', 'the oldest version you accept'],
      ['REQUIRED', 'stop with an error if it is not found'],
      ['NO_MODULE / CONFIG', 'use only the package\'s own <Name>Config.cmake file'],
      ['COMPONENTS', 'the parts of the package you need'],
    ],
    example: { command: 'find_package(Eigen3 3.4 REQUIRED NO_MODULE)', says: 'Finds Eigen 3.4 or newer, or stops configuring; then Eigen3::Eigen can be linked.' },
    seeAlso: ['target_link_libraries', 'fetchcontent_declare', 'find_dependency'],
  },
  {
    name: 'fetchcontent_declare',
    aliases: ['FetchContent_Declare'],
    lang: 'cmake',
    kind: 'function',
    official: 'The FetchContent_Declare() function records the options that describe how to populate the specified content.',
    source: 'CMake documentation (FetchContent module)',
    when: 'You want CMake to download a dependency\'s source and build it with your project. It only records what to get; FetchContent_MakeAvailable downloads it. Pin a commit hash, never a branch, or two builds can get different code.',
    flags: [
      ['GIT_REPOSITORY', 'the address of the git repository'],
      ['GIT_TAG', 'the exact commit hash or release tag to check out'],
      ['FIND_PACKAGE_ARGS', 'try find_package first and download only if that fails (CMake 3.24+)'],
    ],
    example: {
      command: 'FetchContent_Declare(googletest\n  GIT_REPOSITORY https://github.com/google/googletest.git\n  GIT_TAG v1.14.0)',
      says: 'Records where to get GoogleTest 1.14.0. Nothing is downloaded yet.',
    },
    seeAlso: ['fetchcontent_makeavailable', 'find_package', 'include'],
  },
  {
    name: 'fetchcontent_makeavailable',
    aliases: ['FetchContent_MakeAvailable'],
    lang: 'cmake',
    kind: 'function',
    official: 'This command ensures that each of the named dependencies are made available to the project by the time it returns.',
    source: 'CMake documentation (FetchContent module)',
    when: 'After FetchContent_Declare: it downloads the source into build/_deps and adds it to your build, so its targets can be linked. Every fresh build folder downloads and compiles it again.',
    example: { command: 'FetchContent_MakeAvailable(googletest)', says: 'Downloads GoogleTest if needed and builds it with your project; GTest::gtest_main now exists.' },
    seeAlso: ['fetchcontent_declare', 'add_subdirectory'],
  },
  {
    name: 'find_library',
    lang: 'cmake',
    kind: 'function',
    official: 'This command is used to find a library.',
    source: 'CMake documentation',
    when: 'You need the full path of a library file on the machine. The answer is stored in a variable and remembered, so a later change on disk is not noticed until you clear it. If nothing is found the variable ends in -NOTFOUND.',
    example: { command: 'find_library(Z_LIB z)', says: 'Stores the path of libz, such as /usr/lib/x86_64-linux-gnu/libz.so, in Z_LIB.' },
    seeAlso: ['find_path', 'find_package', 'CMAKE_FIND_ROOT_PATH_MODE_LIBRARY'],
  },
  {
    name: 'find_path',
    lang: 'cmake',
    kind: 'function',
    official: 'This command is used to find a directory containing the named file.',
    source: 'CMake documentation',
    when: 'You need the folder that holds a header, to add it to an include path. Like find_library, the result is remembered, and is NAME-NOTFOUND if the file is missing.',
    example: { command: 'find_path(Z_INC zlib.h)', says: 'Stores the folder that contains zlib.h, such as /usr/include, in Z_INC.' },
    seeAlso: ['find_library', 'CMAKE_FIND_ROOT_PATH_MODE_INCLUDE'],
  },

  // ---------------------------------------------------------------- CMake: testing
  {
    name: 'enable_testing',
    lang: 'cmake',
    kind: 'function',
    official: 'Enable testing for current directory and below.',
    source: 'CMake documentation',
    when: 'You want ctest to run your tests. Put it in the root CMakeLists.txt, before the add_subdirectory lines: ctest starts reading at the top of the build folder and cannot see tests registered only lower down.',
    example: { command: 'enable_testing()', says: 'CMake writes a test list into the build folder, so ctest --test-dir build finds the tests.' },
    seeAlso: ['add_test', 'gtest_discover_tests', 'ctest'],
  },
  {
    name: 'add_test',
    lang: 'cmake',
    kind: 'function',
    official: 'Add a test to the project to be run by ctest(1).',
    source: 'CMake documentation',
    when: 'You want one program run as one test, passing when it exits with 0. For a GoogleTest program use gtest_discover_tests instead, or all its tests show up as a single pass or fail.',
    flags: [
      ['NAME', 'the test\'s name, as ctest shows it'],
      ['COMMAND', 'the program to run; a target name is swapped for the built program\'s path'],
    ],
    example: { command: 'add_test(NAME demo_runs COMMAND gnc_demo)', says: 'ctest runs gnc_demo and reports demo_runs as passed if it exits with 0.' },
    seeAlso: ['set_tests_properties', 'enable_testing', 'gtest_discover_tests'],
  },
  {
    name: 'set_tests_properties',
    lang: 'cmake',
    kind: 'function',
    official: 'Set a property of the tests.',
    source: 'CMake documentation',
    when: 'You want to change how ctest judges a test: by its output instead of its exit code, with a time limit, or with a label. Inside a CMake string, write \\\\. for a real dot in the pattern.',
    flags: [
      ['PASS_REGULAR_EXPRESSION', 'passes only if the output matches this pattern'],
      ['TIMEOUT', 'fails the test if it runs longer than this many seconds'],
      ['WILL_FAIL', 'turns the verdict around, for a test meant to fail'],
      ['LABELS', 'tags, so ctest -L can run just one group'],
    ],
    example: { command: 'set_tests_properties(demo_runs PROPERTIES TIMEOUT 10)', says: 'Fails demo_runs if it has not finished after 10 seconds.' },
    seeAlso: ['add_test'],
  },
  {
    name: 'gtest_discover_tests',
    lang: 'cmake',
    kind: 'function',
    official: 'Automatically add tests with CTest by querying the compiled test executable for available tests',
    source: 'CMake documentation (GoogleTest module)',
    when: 'You have a GoogleTest program and want each TEST to show up in ctest by itself, so a failure names the exact test. Load it first with include(GoogleTest).',
    flags: [
      ['PROPERTIES', 'set test properties such as LABELS or TIMEOUT on every test it finds'],
      ['NO_PRETTY_VALUES', 'name value-parameterized tests by number instead of printing the value'],
    ],
    example: { command: 'gtest_discover_tests(unit_tests PROPERTIES LABELS "unit")', says: 'After the build, lists every test inside unit_tests and registers each one with ctest, labeled unit.' },
    seeAlso: ['add_test', 'include', 'catch_discover_tests', 'enable_testing'],
  },
  {
    name: 'catch_discover_tests',
    lang: 'cmake',
    kind: 'function',
    official: 'Catch.cmake provides function catch_discover_tests to get tests from a target.',
    source: 'Catch2 documentation (docs/cmake-integration.md)',
    when: 'The Catch2 twin of gtest_discover_tests: each TEST_CASE shows up in ctest by itself. It comes with Catch2, not CMake, so load it with include(Catch) after find_package(Catch2).',
    example: { command: 'catch_discover_tests(catch_tests)', says: 'Registers every Catch2 test case inside catch_tests with ctest.' },
    seeAlso: ['gtest_discover_tests', 'find_package'],
  },

  // ---------------------------------------------------------------- CMake: install and export
  {
    name: 'install',
    lang: 'cmake',
    kind: 'function',
    official: 'Specify rules to run at install time.',
    source: 'CMake documentation',
    when: 'You want cmake --install to copy your library, headers and CMake files into a folder (the prefix) where other projects can use them. Nothing is copied at build time. Without --prefix it installs into /usr/local, which needs administrator rights.',
    flags: [
      ['TARGETS', 'install these built targets'],
      ['EXPORT', 'after TARGETS: add them to a named export set; on its own: write that set as a .cmake file'],
      ['ARCHIVE / LIBRARY / RUNTIME', 'static libraries / shared libraries / programs'],
      ['DESTINATION', 'the folder inside the prefix to copy into'],
      ['DIRECTORY', 'copy a whole folder, such as the headers'],
      ['FILES', 'copy these files'],
      ['NAMESPACE', 'put this in front of the exported target names, such as gnc::'],
    ],
    example: { command: 'install(DIRECTORY include/gnc DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})', says: 'cmake --install copies the gnc header folder into <prefix>/include.' },
    seeAlso: ['CMAKE_INSTALL_LIBDIR', 'configure_package_config_file'],
  },
  {
    name: 'configure_package_config_file',
    lang: 'cmake',
    kind: 'function',
    official: 'Create a config file for a project',
    source: 'CMake documentation (CMakePackageConfigHelpers module)',
    when: 'You are making your library findable with find_package. It turns your gncConfig.cmake.in template into gncConfig.cmake without fixed paths, so the install can be moved. Load it with include(CMakePackageConfigHelpers).',
    flags: [['INSTALL_DESTINATION', 'the folder the config file will be installed into']],
    example: {
      command: 'configure_package_config_file(cmake/gncConfig.cmake.in\n  ${CMAKE_CURRENT_BINARY_DIR}/gncConfig.cmake\n  INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/gnc)',
      says: 'Writes gncConfig.cmake into the build folder, ready for install(FILES ...) to copy.',
    },
    seeAlso: ['write_basic_package_version_file', 'install', 'check_required_components'],
  },
  {
    name: 'write_basic_package_version_file',
    lang: 'cmake',
    kind: 'function',
    official: 'Create a version file for a project',
    source: 'CMake documentation (CMakePackageConfigHelpers module)',
    when: 'Next to the config file: it lets find_package(gnc 1.2) check whether the installed version is good enough. It uses the version from project() unless you give one.',
    flags: [['COMPATIBILITY', 'which versions count as good enough: SameMajorVersion suits semantic versioning; AnyNewerVersion accepts any newer one']],
    example: {
      command: 'write_basic_package_version_file(\n  ${CMAKE_CURRENT_BINARY_DIR}/gncConfigVersion.cmake\n  COMPATIBILITY SameMajorVersion)',
      says: 'With gnc 1.2.0 installed, find_package(gnc 1.0) is accepted, but 1.3 and 2.0 are not.',
    },
    seeAlso: ['configure_package_config_file', 'find_package'],
  },
  {
    name: 'find_dependency',
    lang: 'cmake',
    kind: 'function',
    official: 'The find_dependency() macro wraps a find_package() call for a package dependency',
    source: 'CMake documentation (CMakeFindDependencyMacro module)',
    when: 'Inside your package\'s config file, for every library your public headers need, before the targets file is included. If it is missing, the user sees a message naming it, instead of a confusing "target was not found".',
    example: { command: 'find_dependency(Eigen3 3.4 NO_MODULE)', says: 'Makes sure Eigen 3.4 is found whenever someone runs find_package(gnc).' },
    seeAlso: ['find_package', 'check_required_components'],
  },
  {
    name: 'check_required_components',
    lang: 'cmake',
    kind: 'function',
    official: 'This macro checks whether all requested, non-optional components have been found, and if this is not the case, sets the Foo_FOUND variable to FALSE, so that the package is considered to be not found.',
    source: 'CMake documentation (CMakePackageConfigHelpers module)',
    when: 'The last line of a config file made with configure_package_config_file. Call it even if your package has no components, so a user asking for one that does not exist gets an error.',
    example: { command: 'check_required_components(gnc)', says: 'Marks gnc as not found if the user asked for a component it does not have.' },
    seeAlso: ['configure_package_config_file', 'find_dependency'],
  },

  // ---------------------------------------------------------------- CMake: variables
  {
    name: 'CMAKE_CXX_STANDARD',
    lang: 'cmake',
    kind: 'constant',
    official: 'Default value for CXX_STANDARD target property if set when a target is created.',
    source: 'CMake documentation',
    when: 'You want every C++ target in the project compiled as one C++ version. Set it before the targets are made; on its own it is only a wish, and CMake may quietly use an older version unless CMAKE_CXX_STANDARD_REQUIRED is ON.',
    example: { command: 'set(CMAKE_CXX_STANDARD 20)', says: 'Targets made after this line are compiled as C++20.' },
    seeAlso: ['CMAKE_CXX_STANDARD_REQUIRED', 'CMAKE_CXX_EXTENSIONS', 'target_compile_features'],
  },
  {
    name: 'CMAKE_CXX_STANDARD_REQUIRED',
    lang: 'cmake',
    kind: 'constant',
    official: 'Default value for CXX_STANDARD_REQUIRED target property if set when a target is created.',
    source: 'CMake documentation',
    when: 'Set it ON next to CMAKE_CXX_STANDARD, so a compiler that cannot do that version is an error instead of being quietly used with an older one.',
    example: { command: 'set(CMAKE_CXX_STANDARD_REQUIRED ON)', says: 'Configuring fails if the compiler cannot do the C++ version you asked for.' },
    seeAlso: ['CMAKE_CXX_STANDARD'],
  },
  {
    name: 'CMAKE_CXX_EXTENSIONS',
    lang: 'cmake',
    kind: 'constant',
    official: 'Default value for CXX_EXTENSIONS target property if set when a target is created.',
    source: 'CMake documentation',
    when: 'Set it OFF to get standard C++ (-std=c++20) instead of the GNU flavor (-std=gnu++20), so your code does not lean on extras only GCC and Clang accept.',
    example: { command: 'set(CMAKE_CXX_EXTENSIONS OFF)', says: 'Compiles with -std=c++20 rather than -std=gnu++20.' },
    seeAlso: ['CMAKE_CXX_STANDARD'],
  },
  {
    name: 'CMAKE_CXX_FLAGS',
    lang: 'cmake',
    kind: 'constant',
    official: 'Language-wide flags for language <LANG> used when building for all configurations.',
    source: 'CMake documentation (CMAKE_<LANG>_FLAGS)',
    when: 'You meet it in old projects that add flags for every C++ file at once. Editing it forces the flags on everything, even code you pulled in; prefer target_compile_options on your own targets. It is one string, not a list.',
    example: { command: 'set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Werror")', says: 'Every C++ file in the build, dependencies included, is now compiled with -Wall -Werror.' },
    seeAlso: ['target_compile_options', 'CMAKE_CXX_FLAGS_INIT'],
  },
  {
    name: 'CMAKE_BUILD_TYPE',
    lang: 'cmake',
    kind: 'constant',
    official: 'Specifies the build type on single-configuration generators (e.g. Makefile Generators or Ninja).',
    source: 'CMake documentation',
    when: 'Pick a set of compiler flags when you configure: Debug (no optimization, debug info), Release (-O3 -DNDEBUG) or RelWithDebInfo. Set it with -D on the command line, not in CMakeLists.txt. Left empty, you get neither optimization nor debug info.',
    example: { command: 'cmake -S . -B build -DCMAKE_BUILD_TYPE=Release', says: 'Configures a build folder that compiles everything with optimization and asserts turned off.' },
    seeAlso: ['if', 'cmake'],
  },
  {
    name: 'CMAKE_SOURCE_DIR',
    lang: 'cmake',
    kind: 'constant',
    official: 'The path to the top level of the source tree.',
    source: 'CMake documentation',
    when: 'You need a path from the top of the whole source tree, such as a linker script there. If your project is ever pulled into another one, this points at the other project\'s top folder; PROJECT_SOURCE_DIR is safer.',
    example: { command: 'target_link_options(fc.elf PRIVATE -T${CMAKE_SOURCE_DIR}/stm32f4.ld)', says: 'Links fc.elf with the linker script from the top of the source tree.' },
    seeAlso: ['CMAKE_CURRENT_SOURCE_DIR'],
  },
  {
    name: 'CMAKE_CURRENT_SOURCE_DIR',
    lang: 'cmake',
    kind: 'constant',
    official: 'The path to the source directory currently being processed.',
    source: 'CMake documentation',
    when: 'You need the full path of the folder holding the CMakeLists.txt being read right now, for example to hand a data folder to a test.',
    example: { command: 'target_compile_definitions(numerics_tests PRIVATE GOLDEN_DIR="${CMAKE_CURRENT_SOURCE_DIR}/golden")', says: 'Tells the test program the full path of the golden folder next to this CMakeLists.txt.' },
    seeAlso: ['CMAKE_CURRENT_BINARY_DIR', 'CMAKE_SOURCE_DIR', 'CMAKE_CURRENT_LIST_DIR'],
  },
  {
    name: 'CMAKE_CURRENT_BINARY_DIR',
    lang: 'cmake',
    kind: 'constant',
    official: 'The path to the binary directory currently being processed.',
    source: 'CMake documentation',
    when: 'You are writing a generated file, and it belongs in the build folder that matches this CMakeLists.txt, never in the source folder.',
    example: { command: 'write_basic_package_version_file(${CMAKE_CURRENT_BINARY_DIR}/gncConfigVersion.cmake COMPATIBILITY SameMajorVersion)', says: 'Writes the version file into the build folder, such as build/gncConfigVersion.cmake.' },
    seeAlso: ['CMAKE_CURRENT_SOURCE_DIR'],
  },
  {
    name: 'CMAKE_CURRENT_LIST_DIR',
    lang: 'cmake',
    kind: 'constant',
    official: 'Full directory of the listfile currently being processed.',
    source: 'CMake documentation',
    when: 'Inside a .cmake file loaded from somewhere else, such as a package\'s config file: it is the folder that file sits in, so you can load its neighbors wherever it was installed.',
    example: { command: 'include("${CMAKE_CURRENT_LIST_DIR}/gncTargets.cmake")', says: 'Loads gncTargets.cmake from the same folder as the config file doing the loading.' },
    seeAlso: ['include', 'CMAKE_CURRENT_SOURCE_DIR'],
  },
  {
    name: 'CMAKE_MODULE_PATH',
    lang: 'cmake',
    kind: 'constant',
    official: 'Semicolon-separated list of directories, represented using forward slashes, specifying a search path for CMake modules to be loaded by the include() or find_package() commands before checking the default modules that come with CMake.',
    source: 'CMake documentation',
    when: 'You keep your own .cmake helper files in a folder, often called cmake, and want include(Name) to find them. Add to it with list(APPEND ...) rather than replacing it.',
    example: { command: 'list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake)', says: 'include(GncBuildOptions) now finds cmake/GncBuildOptions.cmake.' },
    seeAlso: ['list', 'include'],
  },
  {
    name: 'CMAKE_MINIMUM_REQUIRED_VERSION',
    lang: 'cmake',
    kind: 'constant',
    official: 'The <min> version of CMake given to the most recent call to the cmake_minimum_required(VERSION) command in the current variable scope or any parent variable scope.',
    source: 'CMake documentation',
    when: 'You want to read back the number from cmake_minimum_required, for example to print it while checking which policies it turned on. It is not the version of CMake that is running.',
    example: { command: 'message(STATUS "minimum ${CMAKE_MINIMUM_REQUIRED_VERSION}")', says: 'Prints -- minimum 3.28 when the first line says cmake_minimum_required(VERSION 3.28).' },
    seeAlso: ['cmake_minimum_required', 'cmake_policy'],
  },
  {
    name: 'CMAKE_INSTALL_LIBDIR',
    lang: 'cmake',
    kind: 'constant',
    official: 'object code libraries (lib or lib64)',
    source: 'CMake documentation (GNUInstallDirs module)',
    when: 'In install() lines, as the folder for libraries, instead of typing lib: systems disagree (lib, lib64, lib/x86_64-linux-gnu) and this picks the right one. It exists only after include(GNUInstallDirs).',
    example: { command: 'install(TARGETS gnc ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR})', says: 'Copies libgnc.a into <prefix>/lib, or whatever library folder this system uses.' },
    seeAlso: ['CMAKE_INSTALL_INCLUDEDIR', 'CMAKE_INSTALL_BINDIR', 'install'],
  },
  {
    name: 'CMAKE_INSTALL_INCLUDEDIR',
    lang: 'cmake',
    kind: 'constant',
    official: 'C header files (include)',
    source: 'CMake documentation (GNUInstallDirs module)',
    when: 'In install() lines and $<INSTALL_INTERFACE:...>, as the folder for headers. It exists only after include(GNUInstallDirs).',
    example: { command: 'install(DIRECTORY include/gnc DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})', says: 'Copies the gnc header folder into <prefix>/include.' },
    seeAlso: ['CMAKE_INSTALL_LIBDIR', 'install'],
  },
  {
    name: 'CMAKE_INSTALL_BINDIR',
    lang: 'cmake',
    kind: 'constant',
    official: 'user executables (bin)',
    source: 'CMake documentation (GNUInstallDirs module)',
    when: 'In install() lines, as the folder for programs (and for Windows DLLs). It exists only after include(GNUInstallDirs).',
    example: { command: 'install(TARGETS gnc RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})', says: 'Copies any program files of the target into <prefix>/bin.' },
    seeAlso: ['CMAKE_INSTALL_LIBDIR', 'install'],
  },

  // ---------------------------------------------------------------- CMake: toolchain files and cross-compiling
  {
    name: 'CMAKE_SYSTEM_NAME',
    lang: 'cmake',
    kind: 'constant',
    official: 'The name of the operating system for which CMake is to build.',
    source: 'CMake documentation',
    when: 'In a toolchain file, to say what the target runs: Linux, Windows, or Generic for bare metal with no operating system. Setting it yourself is what turns cross-compiling on.',
    example: { command: 'set(CMAKE_SYSTEM_NAME Generic)', says: 'Tells CMake the program is for a chip with no operating system, and makes CMAKE_CROSSCOMPILING true.' },
    seeAlso: ['CMAKE_SYSTEM_PROCESSOR', 'CMAKE_CROSSCOMPILING'],
  },
  {
    name: 'CMAKE_SYSTEM_PROCESSOR',
    lang: 'cmake',
    kind: 'constant',
    official: 'When cross-compiling, a CMAKE_TOOLCHAIN_FILE should set the CMAKE_SYSTEM_PROCESSOR variable to match target architecture that it specifies (via CMAKE_<LANG>_COMPILER and perhaps CMAKE_<LANG>_COMPILER_TARGET).',
    source: 'CMake documentation',
    when: 'In a toolchain file, next to CMAKE_SYSTEM_NAME, to name the target\'s processor family, such as arm. CMake does not check it against the compiler; it is for your project and find modules to read.',
    example: { command: 'set(CMAKE_SYSTEM_PROCESSOR arm)', says: 'Records that the target is an Arm processor.' },
    seeAlso: ['CMAKE_SYSTEM_NAME'],
  },
  {
    name: 'CMAKE_CROSSCOMPILING',
    lang: 'cmake',
    kind: 'constant',
    official: 'This variable is set by CMake to indicate whether it is cross compiling, but note limitations discussed below.',
    source: 'CMake documentation',
    when: 'In the project, to skip what cannot run on the build machine, such as unit tests built for a chip. The limitation: it is true whenever CMAKE_SYSTEM_NAME was set by hand, even to the same system you are on.',
    example: { command: 'if(CMAKE_CROSSCOMPILING)', says: 'The lines up to else() or endif() run only when building with a toolchain file for another machine.' },
    seeAlso: ['CMAKE_SYSTEM_NAME', 'if'],
  },
  {
    name: 'CMAKE_C_COMPILER',
    lang: 'cmake',
    kind: 'constant',
    official: 'The full path to the compiler for LANG.',
    source: 'CMake documentation (CMAKE_<LANG>_COMPILER)',
    when: 'In a toolchain file, to name the C cross-compiler. It must be set before project() runs and cannot be changed in an existing build folder; start a fresh one.',
    example: { command: 'set(CMAKE_C_COMPILER arm-none-eabi-gcc)', says: 'Compiles C files with the Arm cross-compiler found on the PATH.' },
    seeAlso: ['CMAKE_CXX_COMPILER', 'CMAKE_ASM_COMPILER'],
  },
  {
    name: 'CMAKE_CXX_COMPILER',
    lang: 'cmake',
    kind: 'constant',
    official: 'The full path to the compiler for LANG.',
    source: 'CMake documentation (CMAKE_<LANG>_COMPILER)',
    when: 'In a toolchain file, to name the C++ cross-compiler. Like the C one, it only takes effect in a fresh build folder.',
    example: { command: 'set(CMAKE_CXX_COMPILER arm-none-eabi-g++)', says: 'Compiles C++ files with the Arm cross-compiler found on the PATH.' },
    seeAlso: ['CMAKE_C_COMPILER', 'CMAKE_ASM_COMPILER'],
  },
  {
    name: 'CMAKE_ASM_COMPILER',
    lang: 'cmake',
    kind: 'constant',
    official: 'The full path to the compiler for LANG.',
    source: 'CMake documentation (CMAKE_<LANG>_COMPILER)',
    when: 'In a toolchain file, to name the program that assembles .s startup files; for Arm it is usually the same gcc as the C compiler.',
    example: { command: 'set(CMAKE_ASM_COMPILER arm-none-eabi-gcc)', says: 'Assembles .s files with the Arm gcc.' },
    seeAlso: ['CMAKE_C_COMPILER', 'CMAKE_CXX_COMPILER'],
  },
  {
    name: 'CMAKE_TRY_COMPILE_TARGET_TYPE',
    lang: 'cmake',
    kind: 'constant',
    official: 'Type of target generated for try_compile() calls using the source file signature.',
    source: 'CMake documentation',
    when: 'For bare-metal toolchains. CMake tests the compiler by building a tiny program, which cannot link without startup code and a linker script; STATIC_LIBRARY makes the test build a library instead.',
    example: { command: 'set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)', says: 'CMake\'s compiler check now builds a library, so it passes for a bare-metal compiler.' },
    seeAlso: ['CMAKE_SYSTEM_NAME'],
  },
  {
    name: 'CMAKE_C_FLAGS_INIT',
    lang: 'cmake',
    kind: 'constant',
    official: 'Value used to initialize the CMAKE_<LANG>_FLAGS cache entry the first time a build tree is configured for language <LANG>.',
    source: 'CMake documentation (CMAKE_<LANG>_FLAGS_INIT)',
    when: 'In a toolchain file, for flags every C file needs on this target, such as the CPU type. It is read only when a build folder is first configured.',
    example: { command: 'set(CMAKE_C_FLAGS_INIT "-mcpu=cortex-m4 -mthumb")', says: 'Every C file is compiled for a Cortex-M4 in Thumb mode.' },
    seeAlso: ['CMAKE_CXX_FLAGS_INIT', 'CMAKE_EXE_LINKER_FLAGS_INIT'],
  },
  {
    name: 'CMAKE_CXX_FLAGS_INIT',
    lang: 'cmake',
    kind: 'constant',
    official: 'Value used to initialize the CMAKE_<LANG>_FLAGS cache entry the first time a build tree is configured for language <LANG>.',
    source: 'CMake documentation (CMAKE_<LANG>_FLAGS_INIT)',
    when: 'In a toolchain file, for flags every C++ file needs on this target. Like the C one, it is read only when a build folder is first configured.',
    example: { command: 'set(CMAKE_CXX_FLAGS_INIT "${CPU_FLAGS} -fno-exceptions -fno-rtti")', says: 'Every C++ file gets the CPU flags, with exceptions and run-time type information switched off.' },
    seeAlso: ['CMAKE_C_FLAGS_INIT', 'CMAKE_CXX_FLAGS'],
  },
  {
    name: 'CMAKE_EXE_LINKER_FLAGS_INIT',
    lang: 'cmake',
    kind: 'constant',
    official: 'Value used to initialize the CMAKE_EXE_LINKER_FLAGS cache entry the first time a build tree is configured.',
    source: 'CMake documentation',
    when: 'In a toolchain file, for flags the linker needs for every program on this target, such as which small C library to use.',
    example: { command: 'set(CMAKE_EXE_LINKER_FLAGS_INIT "${CPU_FLAGS} --specs=nano.specs --specs=nosys.specs")', says: 'Every program is linked with the small newlib-nano C library and no operating-system calls.' },
    seeAlso: ['CMAKE_C_FLAGS_INIT', 'target_link_options'],
  },
  {
    name: 'CMAKE_FIND_ROOT_PATH',
    lang: 'cmake',
    kind: 'constant',
    official: 'Semicolon-separated list of root paths to search on the filesystem.',
    source: 'CMake documentation',
    when: 'In a toolchain file, to say where the target\'s own libraries and headers live on your machine, so find_ commands look there instead of in the laptop\'s /usr.',
    example: { command: 'set(CMAKE_FIND_ROOT_PATH /usr/lib/arm-none-eabi)', says: 'find_library and friends search under /usr/lib/arm-none-eabi.' },
    seeAlso: ['CMAKE_FIND_ROOT_PATH_MODE_LIBRARY', 'CMAKE_FIND_ROOT_PATH_MODE_PROGRAM'],
  },
  {
    name: 'CMAKE_FIND_ROOT_PATH_MODE_PROGRAM',
    lang: 'cmake',
    kind: 'constant',
    official: 'This variable controls whether the CMAKE_FIND_ROOT_PATH and CMAKE_SYSROOT are used by find_program().',
    source: 'CMake documentation',
    when: 'Set it to NEVER in a toolchain file: tools such as Python run on your laptop, so they must come from the laptop, not the target folders.',
    flags: [
      ['NEVER', 'search only the host system'],
      ['ONLY', 'search only under CMAKE_FIND_ROOT_PATH'],
    ],
    example: { command: 'set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)', says: 'find_program looks for tools on the host system only.' },
    seeAlso: ['CMAKE_FIND_ROOT_PATH', 'CMAKE_FIND_ROOT_PATH_MODE_LIBRARY'],
  },
  {
    name: 'CMAKE_FIND_ROOT_PATH_MODE_LIBRARY',
    lang: 'cmake',
    kind: 'constant',
    official: 'This variable controls whether the CMAKE_FIND_ROOT_PATH and CMAKE_SYSROOT are used by find_library().',
    source: 'CMake documentation',
    when: 'Set it to ONLY in a toolchain file, so a laptop library built for the wrong processor can never be picked by mistake.',
    flags: [
      ['ONLY', 'search only under CMAKE_FIND_ROOT_PATH'],
      ['NEVER', 'search only the host system'],
    ],
    example: { command: 'set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)', says: 'find_library looks only in the target\'s own folders.' },
    seeAlso: ['CMAKE_FIND_ROOT_PATH', 'find_library'],
  },
  {
    name: 'CMAKE_FIND_ROOT_PATH_MODE_INCLUDE',
    lang: 'cmake',
    kind: 'constant',
    official: 'This variable controls whether the CMAKE_FIND_ROOT_PATH and CMAKE_SYSROOT are used by find_file() and find_path().',
    source: 'CMake documentation',
    when: 'Set it to ONLY in a toolchain file, so headers come from the target\'s folders, never from the laptop\'s /usr/include.',
    flags: [['ONLY', 'search only under CMAKE_FIND_ROOT_PATH']],
    example: { command: 'set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)', says: 'find_path looks only in the target\'s own folders.' },
    seeAlso: ['CMAKE_FIND_ROOT_PATH', 'find_path'],
  },
  {
    name: 'CMAKE_FIND_ROOT_PATH_MODE_PACKAGE',
    lang: 'cmake',
    kind: 'constant',
    official: 'This variable controls whether the CMAKE_FIND_ROOT_PATH and CMAKE_SYSROOT are used by find_package().',
    source: 'CMake documentation',
    when: 'Set it to ONLY in a toolchain file, so find_package finds the copy of a library built for the target, never the laptop\'s.',
    flags: [['ONLY', 'search only under CMAKE_FIND_ROOT_PATH']],
    example: { command: 'set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)', says: 'find_package(gnc) finds the Arm build of gnc, not the one for the laptop.' },
    seeAlso: ['CMAKE_FIND_ROOT_PATH', 'find_package'],
  },
  {
    name: 'CMAKE_OBJCOPY',
    lang: 'cmake',
    kind: 'constant',
    official: 'Path to a program.',
    source: 'CMake cache entry description (CMAKE_OBJCOPY has no page of its own in the CMake documentation)',
    when: 'You need objcopy, the tool that turns a finished program into a raw image for flashing. CMake finds the one that matches your compiler, so with a toolchain file it is the Arm version, not the laptop\'s.',
    example: { command: 'COMMAND ${CMAKE_OBJCOPY} -O binary $<TARGET_FILE:fin_controller> fin_controller.bin', says: 'Runs arm-none-eabi-objcopy to write the raw flash image fin_controller.bin.' },
    seeAlso: ['add_custom_command'],
  },

  // ---------------------------------------------------------------- Dockerfile
  {
    name: 'FROM',
    lang: 'dockerfile',
    kind: 'keyword',
    official: 'The FROM instruction initializes a new build stage and sets the base image for subsequent instructions.',
    source: 'Dockerfile reference (Docker docs)',
    when: 'The first instruction of every Dockerfile: the image you build on top of. A tag like python:3.12-slim can be moved to a different image later; add @sha256:... to pin the exact one.',
    flags: [
      ['AS', 'name this stage, so a later stage can copy from it'],
      ['@sha256:', 'pin the exact image by its digest'],
    ],
    example: { command: 'FROM python:3.12-slim', says: 'Starts from the slim Python 3.12 image; everything after is added on top.' },
    seeAlso: ['COPY', 'RUN', 'docker build'],
  },
  {
    name: 'RUN',
    lang: 'dockerfile',
    kind: 'keyword',
    official: 'The RUN instruction will execute any commands to create a new layer on top of the current image.',
    source: 'Dockerfile reference (Docker docs)',
    when: 'Installing packages or preparing files while the image is built. It runs once at build time, not when the container starts, and Docker reuses its saved result until this line or anything above it changes.',
    example: { command: 'RUN pip install --no-cache-dir -r requirements.txt', says: 'Installs the Python packages into the image, without keeping pip\'s download cache.' },
    seeAlso: ['CMD', 'COPY'],
  },
  {
    name: 'COPY',
    lang: 'dockerfile',
    kind: 'keyword',
    official: 'The COPY instruction copies new files or directories from <src> and adds them to the filesystem of the image at the path <dest>.',
    source: 'Dockerfile reference (Docker docs)',
    when: 'Putting your files into the image. Copy the requirements file and install before copying the rest, so editing your code does not re-run the slow install.',
    flags: [['--from', 'copy from an earlier build stage instead of your folder']],
    example: { command: 'COPY --from=build /src/period /usr/local/bin/period', says: 'Copies only the finished program out of the build stage into this slim image.' },
    seeAlso: ['WORKDIR', 'FROM'],
  },
  {
    name: 'WORKDIR',
    lang: 'dockerfile',
    kind: 'keyword',
    official: 'The WORKDIR instruction sets the working directory for any RUN, CMD, ENTRYPOINT, COPY and ADD instructions that follow it in the Dockerfile.',
    source: 'Dockerfile reference (Docker docs)',
    when: 'Choose the folder your app lives and runs in, instead of RUN cd, which lasts only for that one line. The folder is made if it is missing.',
    example: { command: 'WORKDIR /app', says: 'Later COPY, RUN and the container\'s command all work in /app.' },
    seeAlso: ['COPY', 'RUN'],
  },
  {
    name: 'ENV',
    lang: 'dockerfile',
    kind: 'keyword',
    official: 'The ENV instruction sets the environment variable <key> to the value <value>.',
    source: 'Dockerfile reference (Docker docs)',
    when: 'Setting an environment variable the build steps and the running container both see. It is stored in the image, so never put a password in it.',
    example: { command: 'ENV PYTHONUNBUFFERED=1', says: 'Python in the container prints output right away instead of holding it back.' },
    seeAlso: ['ARG'],
  },
  {
    name: 'ARG',
    lang: 'dockerfile',
    kind: 'keyword',
    official: 'The ARG instruction defines a variable that users can pass at build time to the builder with the docker build command using the --build-arg <varname>=<value> flag.',
    source: 'Dockerfile reference (Docker docs)',
    when: 'A value you want to choose at build time, such as a version label. It is gone once the image is built; copy it into ENV if the running container needs it. Build arguments show up in docker history, so they are no place for secrets.',
    example: { command: 'ARG APP_VERSION=dev', says: 'APP_VERSION is dev unless you build with --build-arg APP_VERSION=1.4.0.' },
    seeAlso: ['ENV', 'docker build'],
  },
  {
    name: 'USER',
    lang: 'dockerfile',
    kind: 'keyword',
    official: 'The USER instruction sets the user name (or UID) and optionally the user group (or GID) to use as the default user and group for the remainder of the current stage.',
    source: 'Dockerfile reference (Docker docs)',
    when: 'Near the end, so the container does not run as root. The user must exist first (make it with useradd in a RUN), or be given as a number such as 1000:1000.',
    example: { command: 'USER 1000:1000', says: 'Later RUN lines and the running container act as user 1000, group 1000, not root.' },
    seeAlso: ['RUN'],
  },
  {
    name: 'ENTRYPOINT',
    lang: 'dockerfile',
    kind: 'keyword',
    official: 'An ENTRYPOINT allows you to configure a container that will run as an executable.',
    source: 'Dockerfile reference (Docker docs)',
    when: 'The program the container always runs. Use the exec form with square brackets and double quotes; words after the image name in docker run are added after it as arguments.',
    example: { command: 'ENTRYPOINT ["python3", "/app/apogee.py"]', says: 'docker run apogee --alt 5000 runs python3 /app/apogee.py --alt 5000.' },
    seeAlso: ['CMD', 'docker run'],
  },
  {
    name: 'CMD',
    lang: 'dockerfile',
    kind: 'keyword',
    official: 'The CMD instruction sets the command to be executed when running a container from an image.',
    source: 'Dockerfile reference (Docker docs)',
    when: 'The default command, or with an ENTRYPOINT, the default arguments. Anything typed after the image name in docker run replaces it completely, and only the last CMD in a Dockerfile counts.',
    example: { command: 'CMD ["--alt", "3000", "--speed", "250"]', says: 'With the ENTRYPOINT above, a plain docker run apogee uses altitude 3000 and speed 250.' },
    seeAlso: ['ENTRYPOINT', 'RUN'],
  },
  {
    name: 'HEALTHCHECK',
    lang: 'dockerfile',
    kind: 'keyword',
    official: 'The HEALTHCHECK instruction tells Docker how to test a container to check that it\'s still working.',
    source: 'Dockerfile reference (Docker docs)',
    when: 'A container can be running but stuck. A health check runs a small command every so often and marks the container healthy or unhealthy, which docker ps shows. The command runs inside the container, so the tool it uses must be in the image.',
    flags: [
      ['--interval', 'how long to wait between checks'],
      ['--timeout', 'how long one check may take before it counts as failed'],
      ['--retries', 'how many failures in a row make it unhealthy'],
    ],
    example: {
      command: 'HEALTHCHECK --interval=10s --timeout=3s --retries=3 \\\n  CMD ["python3", "-c", "import urllib.request; urllib.request.urlopen(\'http://localhost:8000/\', timeout=2)"]',
      says: 'Every 10 seconds, asks the web server for its page; three failures in a row mark the container unhealthy.',
    },
    seeAlso: ['CMD', 'docker ps'],
  },
]
