import type { CommandRef } from './types'

export const COMMANDS: CommandRef[] = [
  {
    name: 'return',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Terminates the current function and returns the specified value (if any) to the caller.',
    source: 'cppreference.com',
    when: 'You want a function to stop and hand its answer back to whoever called it. Never return a pointer or reference to a local variable: the local is destroyed as the function ends, so the caller is left holding a dangling pointer to memory that is no longer yours.',
    example: { command: 'double twr(double thrust_n, double weight_n) { return thrust_n / weight_n; }', says: 'Gives the caller the thrust-to-weight ratio, for example 1.4.' },
    seeAlso: ['void', 'co_return'],
  },
  {
    name: 'int',
    lang: 'cpp',
    kind: 'keyword',
    official: "int — basic integer type. The keyword int may be omitted if any of the modifiers listed below are used. If no length modifiers are present, it's guaranteed to have a width of at least 16 bits.",
    source: 'cppreference.com (Fundamental types)',
    when: 'You need a whole number such as a count, a loop index or a return code. Dividing two ints throws away the fraction (7 / 2 is 3), and going past its largest value is undefined behavior, meaning the program may do anything; use std::int32_t and friends when the exact size matters.',
    example: { command: 'int stages = 3;', says: 'Makes a whole-number variable named stages holding 3.' },
    seeAlso: ['long', 'short', 'unsigned', 'std::int32_t'],
  },
  {
    name: 'const',
    lang: 'cpp',
    kind: 'keyword',
    official: 'A const object is an object whose type is const-qualified, or a non-mutable subobject of a const object. Such object cannot be modified: attempt to do so directly is a compile-time error, and attempt to do so indirectly (e.g., by modifying the const object through a reference or pointer to non-const type) results in undefined behavior.',
    source: 'cppreference.com (cv (const and volatile) type qualifiers)',
    when: 'You want a value that must not change after it is set, a function parameter the function promises not to change (const Vec3& v), or a member function that promises not to change the object. In a pointer, where it sits matters: const int* p means the int cannot change through p, int* const p means p itself cannot be pointed elsewhere.',
    flags: [
      ['const T&', 'a read-only reference: pass a big object without copying it and without changing it'],
      ['const T*', 'a pointer through which the value cannot be changed'],
      ['T* const', 'a pointer that cannot be pointed somewhere else'],
      ['after a member function', 'the function promises not to change the object it is called on'],
    ],
    example: { command: 'const double g0 = 9.80665;', says: 'Makes g0 a constant. A later line that tries g0 = 10; stops the build with an error.' },
    seeAlso: ['constexpr', 'mutable', 'const_cast'],
  },
  {
    name: 'if',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Conditionally executes another statement.',
    source: 'cppreference.com',
    when: 'You want code to run only when something is true. Watch for = where you meant ==: if (x = 0) sets x to 0 and is always false. The lessons also use if constexpr, which picks a branch while compiling, inside templates.',
    flags: [
      ['( condition )', 'the test; anything that converts to true or false'],
      ['else', 'the part that runs when the test is false'],
      ['if constexpr', 'decides while compiling, so the branch not taken is not even compiled'],
      ['if (init; condition)', 'declares a variable that only lives inside the if'],
    ],
    example: { command: 'if (altitude_m > 100000.0) std::puts("Above the Karman line");', says: 'Prints Above the Karman line only when the altitude is over 100 km.' },
    seeAlso: ['else', 'switch'],
  },
  {
    name: 'long',
    lang: 'cpp',
    kind: 'keyword',
    official: 'long — target type will have width of at least 32 bits.',
    source: 'cppreference.com (Fundamental types)',
    when: 'You need a bigger whole number than int promises; long long is at least 64 bits. Its size differs between systems (64 bits on Linux, 32 bits on Windows), so flight code writes std::int64_t when the size matters.',
    flags: [
      ['long long', 'at least 64 bits'],
      ['unsigned long', 'the same size, with no negative values'],
      ['long double', 'a floating-point type at least as precise as double'],
    ],
    example: { command: "long long ticks = 5'000'000'000LL;", says: 'Holds five billion, which would overflow a 32-bit int.' },
    seeAlso: ['int', 'short', 'unsigned', 'std::int64_t'],
  },
  {
    name: 'for',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Conditionally executes a statement repeatedly, where the statement does not need to manage the loop condition.',
    source: 'cppreference.com',
    when: 'You want to repeat something a set number of times, or once for every item in a container. Counting down with an unsigned index is a classic trap: i >= 0 is always true for std::size_t, so the loop never ends. Do not add or remove items from a vector while a range-for walks over it.',
    flags: [
      ['(init; condition; step)', 'the counting loop: start, keep going while true, then step'],
      ['(auto& x : container)', 'the range-for loop: visits every item, x refers to each in turn'],
      ['(const auto& x : container)', 'visits every item read-only without copying it'],
    ],
    example: { command: 'for (int s = 10; s > 0; --s) std::printf("%d ", s);', says: 'Prints the countdown 10 9 8 7 6 5 4 3 2 1.' },
    seeAlso: ['while', 'do', 'break', 'continue'],
  },
  {
    name: 'double',
    lang: 'cpp',
    kind: 'keyword',
    official: 'double — double precision floating-point type. Usually IEEE-754 binary64 format.',
    source: 'cppreference.com (Fundamental types)',
    when: 'You need a number with a fraction, like a mass, an altitude or a time in seconds. It keeps about 15 to 16 significant digits, and many decimals are not stored exactly (0.1 + 0.2 is not exactly 0.3), so compare doubles with a small tolerance, never with ==.',
    example: { command: 'double mass_kg = 549054.0;', says: 'Stores the rocket mass as a double-precision number.' },
    seeAlso: ['float', 'std::fabs'],
  },
  {
    name: 'auto',
    lang: 'cpp',
    kind: 'keyword',
    official: 'A placeholder type specifier designates a placeholder type that will be replaced later, typically by deduction from an initializer.',
    source: 'cppreference.com (Placeholder type specifiers)',
    when: 'The type is long or obvious from the right-hand side, such as an iterator, a clock reading or a lambda. Plain auto makes a copy and drops const and &; write auto& or const auto& when you want to refer to the original.',
    flags: [
      ['auto x = ...', 'a new variable whose type comes from the value'],
      ['auto& / const auto&', 'a reference to the original instead of a copy'],
      ['auto f() -> T', 'a function whose return type is written after the arrow'],
      ['auto in a parameter', 'a function template in short form (C++20)'],
    ],
    example: { command: 'auto t0 = std::chrono::steady_clock::now();', says: 'Makes t0 with whatever type now() returns, without spelling out the long type name.' },
    seeAlso: ['decltype', 'template'],
  },
  {
    name: 'public',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Public members form a part of the public interface of a class (other parts of the public interface are the non-member functions found by ADL). A public member of a class is accessible anywhere.',
    source: 'cppreference.com',
    when: 'You are marking the part of a class that any code may use: its constructor and the functions the rest of the program calls. Everything below public: is public until another label appears. In class Imu : public Sensor, it means the Sensor part stays usable from outside.',
    flags: [
      ['public:', 'members below this label can be used from anywhere'],
      [': public Base', 'inherit so that the base class stays usable through the derived one'],
    ],
    example: { command: 'class Engine { public: void ignite(); private: bool lit_ = false; };', says: 'Any code can call ignite(), but only Engine itself can touch lit_.' },
    seeAlso: ['private', 'protected', 'class'],
  },
  {
    name: 'class',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Classes are user-defined types, defined by class-specifier, which appears in decl-specifier-seq of the declaration syntax.',
    source: 'cppreference.com',
    when: 'You want your own type that bundles data with the functions that keep that data valid, like a Kalman filter or a sensor driver. Members of a class are private unless you say otherwise; that is the only difference from struct. Also used in template <class T> and in enum class.',
    flags: [
      ['class Name { ... };', 'defines the type; do not forget the semicolon after the brace'],
      [': public Base', 'inherits from another class'],
      ['enum class', 'a scoped enumeration'],
      ['template <class T>', 'the same as template <typename T>'],
    ],
    example: { command: 'class Thruster { public: explicit Thruster(double n) : thrust_n_(n) {} private: double thrust_n_; };', says: 'Defines a Thruster type whose thrust can only be set when one is built.' },
    seeAlso: ['struct', 'public', 'private', 'virtual'],
  },
  {
    name: 'bool',
    lang: 'cpp',
    kind: 'keyword',
    official: 'bool — integer type, capable of holding one of the two values: true or false. The value of sizeof(bool) is implementation defined and might differ from 1.',
    source: 'cppreference.com (Fundamental types)',
    when: 'You need a yes-or-no value: armed or not, a check passed or failed. Numbers and pointers turn into bool on their own (zero and nullptr are false, everything else true), which is handy in if but can hide mistakes.',
    example: { command: 'bool armed = false;', says: 'Makes a flag named armed that starts as false.' },
    seeAlso: ['true', 'false', 'if'],
  },
  {
    name: 'static_cast',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Converts between types using a combination of implicit and user-defined conversions.',
    source: 'cppreference.com',
    when: 'You want to change a value from one type to another on purpose, such as an int count into a double before dividing, or a signed index into std::size_t. It is checked while compiling, not while running: casting a double that is too big for an int, or a base pointer to the wrong derived type, is undefined behavior.',
    flags: [['static_cast<T>(x)', 'the type you want in the angle brackets, the value in the parentheses']],
    example: { command: 'double avg = static_cast<double>(sum) / count;', says: 'Turns sum into a double first, so the division keeps its fraction instead of rounding down.' },
    seeAlso: ['reinterpret_cast', 'const_cast'],
  },
  {
    name: 'void',
    lang: 'cpp',
    kind: 'keyword',
    official: 'void — type with an empty set of values. It is an incomplete type that cannot be completed (consequently, objects of type void are disallowed). There are no arrays of void, nor references to void. However, pointers to void and functions returning type void (procedures in other languages) are permitted.',
    source: 'cppreference.com (Fundamental types)',
    when: 'A function does its job and has nothing to hand back, like logging a line or setting a valve. void* is a pointer to raw memory of unknown type (what std::malloc returns); you must cast it back to the right type before using it.',
    flags: [
      ['void f()', 'a function that returns nothing'],
      ['void*', 'a pointer to memory of no particular type'],
      ['(void)x', 'marks a value as deliberately unused, to silence a warning'],
    ],
    example: { command: 'void log_event(const char* msg) { std::printf("[EVT] %s\\n", msg); }', says: 'A function that prints a message and returns nothing.' },
    seeAlso: ['return'],
  },
  {
    name: 'char',
    lang: 'cpp',
    kind: 'keyword',
    official: 'char — type for character representation which can be most efficiently processed on the target system (has the same representation and alignment as either signed char or unsigned char, but is always a distinct type).',
    source: 'cppreference.com (Fundamental types)',
    when: 'You are handling one character or raw bytes, and const char* is how C-style text such as "LOX" is passed around. Whether plain char can be negative depends on the system, so use unsigned char or std::uint8_t for bytes.',
    flags: [
      ['const char*', 'a pointer to C-style text that ends with a zero byte'],
      ['unsigned char', 'a byte from 0 to 255'],
      ['char buf[64]', 'a fixed buffer of characters'],
    ],
    example: { command: 'const char* callsign = "ORBIT-1";', says: 'Points callsign at the text ORBIT-1.' },
    seeAlso: ['std::string', 'std::uint8_t'],
  },
  {
    name: 'operator',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Customizes the C++ operators for operands of user-defined types.',
    source: 'cppreference.com',
    when: 'You want your own type to work with +, ==, [] or () so that code like a + b reads naturally for vectors or quaternions. Keep the meaning unsurprising: + should add, and == should agree with !=.',
    flags: [
      ['operator+ / operator-', 'arithmetic between your objects'],
      ['operator==', 'equality; in C++20 the compiler also writes != for you'],
      ['operator[]', 'indexing, like v[0]'],
      ['operator()', 'makes an object callable like a function'],
      ['operator<=>', 'the three-way comparison that gives <, <=, > and >= at once'],
    ],
    example: { command: 'Vec3 operator+(Vec3 a, Vec3 b) { return {a.x + b.x, a.y + b.y, a.z + b.z}; }', says: 'Lets you write pos + vel * dt with your own Vec3 type.' },
    seeAlso: ['class', 'struct'],
  },
  {
    name: 'private',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Private members form the implementation of a class, as well as the private interface for the other members of the class. A private member of a class is only accessible to the members and friends of that class, regardless of whether the members are on the same or different instances.',
    source: 'cppreference.com',
    when: 'You want to hide a class member so that only the class itself can read or change it, which keeps its data valid. This is the default inside a class. Other code that tries to use a private member gets a compile error.',
    flags: [['private:', 'members below this label can only be used inside the class and by its friends']],
    example: { command: 'class Tank { public: double level() const { return kg_; } private: double kg_ = 0; };', says: 'Anyone can read the level, but only Tank can change kg_.' },
    seeAlso: ['public', 'protected', 'friend'],
  },
  {
    name: 'false',
    lang: 'cpp',
    kind: 'keyword',
    official: 'The Boolean literals are the keywords true and false. They are prvalues of type bool.',
    source: 'cppreference.com',
    when: 'You need the "no" value of a bool, for example to start a flag off or to return failure. It turns into 0 if used as a number.',
    example: { command: 'bool abort_requested = false;', says: 'Starts the abort flag off as not requested.' },
    seeAlso: ['true', 'bool'],
  },
  {
    name: 'struct',
    lang: 'cpp',
    kind: 'keyword',
    official: 'class-key - one of class, struct and union. The keywords class and struct are identical except for the default member access and the default base class access. If it is union, the declaration introduces a union type.',
    source: 'cppreference.com',
    when: 'You want to group a few related values into one type, like a telemetry sample or a 3D vector. Members of a struct are public unless you say otherwise. The compiler may add padding between members, so sizeof can be bigger than the sum of the parts.',
    example: { command: 'struct Sample { double t_s; double alt_m; };', says: 'Defines a Sample with a time and an altitude, used as Sample s{0.5, 1200.0};' },
    seeAlso: ['class', 'union', 'sizeof'],
  },
  {
    name: 'while',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Conditionally executes a statement repeatedly.',
    source: 'cppreference.com',
    when: 'You want to keep looping for as long as something stays true, when you do not know in advance how many rounds that takes. Make sure something inside the loop can make the test false, or it runs forever.',
    example: { command: 'while (alt_m > 0.0) { alt_m += vel_ms * dt; vel_ms -= 9.81 * dt; }', says: 'Keeps stepping the flight until the altitude drops to the ground.' },
    seeAlso: ['do', 'for', 'break', 'continue'],
  },
  {
    name: 'template',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Templates are parameterized by one or more template parameters, of three kinds: type template parameters, non-type template parameters, and template template parameters.',
    source: 'cppreference.com (Templates)',
    when: 'You want one piece of code that works for many types or sizes, like a Pool<T, N> or a clamp that works for float and double. The compiler makes a separate copy for each type you use, and its error messages can be very long; concepts make them shorter.',
    flags: [
      ['template <typename T>', 'T stands for any type chosen by the user'],
      ['template <std::size_t N>', 'N stands for a number known while compiling'],
      ['template <typename... Ts>', 'any number of types (a variadic template)'],
      ['template <Concept T>', 'T must meet a concept'],
    ],
    example: { command: 'template <typename T> T clamp01(T x) { return x < 0 ? 0 : (x > 1 ? 1 : x); }', says: 'clamp01(1.7) gives 1.0 and clamp01(0.3f) gives 0.3f, from the same code.' },
    seeAlso: ['typename', 'concept', 'requires'],
  },
  {
    name: 'typename',
    lang: 'cpp',
    kind: 'keyword',
    official: 'In the template parameter list of a template declaration, typename can be used as an alternative to class to declare type template parameters and template template parameters (since C++17). Inside a declaration or a definition of a template, typename can be used to declare that a dependent qualified name is a type.',
    source: 'cppreference.com',
    when: 'You are writing a template and need to name a type parameter (template <typename T>). Inside a template, write typename in front of a name like T::value_type to tell the compiler it is a type; without it you get a confusing error.',
    flags: [
      ['template <typename T>', 'declares T as a type parameter'],
      ['typename T::value_type', 'says that a name that depends on T is a type'],
    ],
    example: { command: 'template <typename T> T average(const std::vector<T>& v);', says: 'Declares a function that averages a vector of any number type.' },
    seeAlso: ['template', 'class'],
  },
  {
    name: 'true',
    lang: 'cpp',
    kind: 'keyword',
    official: 'The Boolean literals are the keywords true and false. They are prvalues of type bool.',
    source: 'cppreference.com',
    when: 'You need the "yes" value of a bool, for example to set a flag or return success. It turns into 1 if used as a number.',
    example: { command: 'bool ok = true;', says: 'Makes a flag named ok that starts as true.' },
    seeAlso: ['false', 'bool'],
  },
  {
    name: 'override',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Specifies that a virtual function overrides another virtual function.',
    source: 'cppreference.com',
    when: 'You are replacing a virtual function from a base class. Always write it: if the name or parameters do not match the base exactly, the compiler stops with an error instead of quietly making a new function that never gets called.',
    example: { command: 'double read() override { return pressure_pa_; }', says: 'Replaces Sensor::read in a derived class, and fails to compile if Sensor has no matching virtual read().' },
    seeAlso: ['virtual', 'final'],
  },
  {
    name: 'unsigned',
    lang: 'cpp',
    kind: 'keyword',
    official: 'unsigned — target type will have unsigned representation',
    source: 'cppreference.com (Fundamental types)',
    when: 'You want a whole number that is never negative, such as a bit pattern or a byte. Unsigned math wraps around: 0u - 1 is a huge number, not -1, and comparing signed with unsigned values can give surprising answers.',
    flags: [
      ['unsigned int', 'a non-negative int; plain unsigned means the same'],
      ['unsigned char', 'a byte from 0 to 255'],
      ['unsigned long long', 'at least 64 bits, never negative'],
    ],
    example: { command: 'unsigned int frames = 0u;', says: 'A frame counter that can only hold 0 or more.' },
    seeAlso: ['int', 'std::uint32_t', 'std::size_t'],
  },
  {
    name: 'virtual',
    lang: 'cpp',
    kind: 'keyword',
    official: 'The virtual specifier specifies that a non-static member function is virtual and supports dynamic dispatch. It may only appear in the decl-specifier-seq of the initial declaration of a non-static member function (i.e., when it is declared in the class definition).',
    source: 'cppreference.com',
    when: 'You want a base-class pointer or reference to call the version of a function that belongs to the real object, like a Sensor& that reads an Imu. A class used this way needs a virtual destructor, or deleting it through the base pointer skips the derived part. Each call goes through a table lookup, which costs a little time.',
    flags: [
      ['virtual T f()', 'derived classes may replace f'],
      ['= 0', 'pure virtual: no body here, every derived class must write one'],
      ['virtual ~Base()', 'the destructor, so deleting through a base pointer cleans up fully'],
    ],
    example: { command: 'struct Sensor { virtual double read() = 0; virtual ~Sensor() = default; };', says: 'Defines an interface: every kind of Sensor must provide its own read().' },
    seeAlso: ['override', 'final', 'class'],
  },
  {
    name: 'static',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Inside a class definition, the keyword static declares members that are not bound to class instances.',
    source: 'cppreference.com (static members)',
    when: 'Inside a function, it keeps a variable alive between calls, set up once. Inside a class, it makes a member shared by every object instead of one per object. At file level, it keeps a name private to that file. Shared static variables are a data race if two threads change them.',
    flags: [
      ['static local variable', 'created on the first call and kept for the rest of the program'],
      ['static member', 'one copy for the whole class, used as Class::name'],
      ['static function at file level', 'visible only inside this .cpp file'],
      ['static constexpr', 'a compile-time constant that belongs to the class'],
    ],
    example: { command: 'int next_packet_id() { static int seq = 0; return ++seq; }', says: 'Returns 1, then 2, then 3 on later calls, because seq keeps its value.' },
    seeAlso: ['extern', 'thread_local', 'inline'],
  },
  {
    name: 'explicit',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Specifies that a constructor or conversion function (since C++11) or deduction guide (since C++17) is explicit, that is, it cannot be used for implicit conversions and copy-initialization.',
    source: 'cppreference.com',
    when: 'You have a constructor that takes one value and you do not want the compiler to turn a plain number into your type on its own. Mark single-argument constructors explicit by default, so that passing 5.0 where a Meters is expected is an error instead of a silent conversion.',
    example: { command: 'struct Meters { explicit Meters(double v) : v(v) {} double v; };', says: 'Meters m{3.0}; works, but passing 3.0 to a function that wants Meters no longer compiles.' },
    seeAlso: ['class', 'static_cast'],
  },
  {
    name: 'else',
    lang: 'cpp',
    kind: 'keyword',
    official: 'If the condition yields true, statement-true is executed. If the else part of the if statement is present and condition yields false, statement-false is executed.',
    source: 'cppreference.com (if statement)',
    when: 'You want something to happen when the if test is false. An else pairs with the nearest if that has none, so use braces when you nest ifs to keep it attached to the one you mean.',
    flags: [['else if', 'tries another test when the first one was false']],
    example: { command: 'if (fuel_kg > 0) burn(); else std::puts("Tank empty");', says: 'Burns while there is fuel; otherwise prints Tank empty.' },
    seeAlso: ['if', 'switch'],
  },
  {
    name: 'constexpr',
    lang: 'cpp',
    kind: 'keyword',
    official: 'The constexpr specifier declares that it is possible to evaluate the value of the entities at compile time. Such entities can then be used where only compile time constant expressions are allowed (provided that appropriate function arguments are given).',
    source: 'cppreference.com',
    when: 'You want a constant worked out while compiling, so it costs nothing while running and can size an array or feed a static_assert. A constexpr function may still run at run time if you call it with run-time values; use consteval if it must never do that.',
    flags: [
      ['constexpr variable', 'a constant whose value is known while compiling'],
      ['constexpr function', 'can be run by the compiler when its arguments are constants'],
      ['if constexpr', 'picks a branch while compiling'],
    ],
    example: { command: 'constexpr double deg_to_rad(double d) { return d * 3.141592653589793 / 180.0; }', says: 'constexpr double r = deg_to_rad(90.0); is worked out by the compiler as 1.5708.' },
    seeAlso: ['consteval', 'constinit', 'const', 'static_assert'],
  },
  {
    name: 'this',
    lang: 'cpp',
    kind: 'keyword',
    official: 'The expression this is a prvalue expression whose value is the address of the implicit object parameter (object on which the implicit object member function is being called).',
    source: 'cppreference.com',
    when: 'Inside a member function you need the object itself: to return *this so calls can be chained, to compare against another object, or to hand the object to a lambda or thread. Capturing this in a lambda that outlives the object leaves a dangling pointer.',
    flags: [
      ['this->x', 'the member x of this object'],
      ['*this', 'the object itself, for example to return it'],
      ['[this]', 'lets a lambda use the object\'s members'],
    ],
    example: { command: 'Burn& Burn::duration(double s) { duration_s_ = s; return *this; }', says: 'Sets the duration and returns the same object, so you can write burn.duration(12).throttle(0.8).' },
    seeAlso: ['class'],
  },
  {
    name: 'case',
    lang: 'cpp',
    kind: 'keyword',
    official: 'If one of the associated case label constants has the same value, control is passed to the statement labeled by the matched case label.',
    source: 'cppreference.com (switch statement)',
    when: 'Inside a switch, each case marks where to jump for one value. Execution falls through into the next case unless you end it with break or return; write [[fallthrough]]; when you mean it.',
    flags: [['case value:', 'the value must be a constant known while compiling, such as an enum member']],
    example: { command: 'case Phase::Ascent: throttle = 1.0; break;', says: 'When the phase is Ascent, sets full throttle, then leaves the switch.' },
    seeAlso: ['switch', 'default', 'break'],
  },
  {
    name: 'nullptr',
    lang: 'cpp',
    kind: 'keyword',
    official: 'The keyword nullptr denotes the pointer literal. It is a prvalue of type std::nullptr_t. There exist implicit conversions from nullptr to null pointer value of any pointer type and any pointer to member type.',
    source: 'cppreference.com',
    when: 'You need a pointer that points to nothing, to start it off safely or to report "not found". Check for it before using the pointer: reading through nullptr crashes the program. Prefer it to 0 or NULL, which are really numbers.',
    example: { command: 'if (sensor == nullptr) return;', says: 'Leaves the function early when there is no sensor to read.' },
    seeAlso: ['new', 'delete', 'std::unique_ptr'],
  },
  {
    name: 'break',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Causes the enclosing for, range-for, while or do-while loop or switch statement to terminate.',
    source: 'cppreference.com',
    when: 'You want to leave a loop early, as soon as you have found what you need, or to end one case of a switch. It only leaves the innermost loop or switch, not every loop it is nested in.',
    example: { command: 'for (auto& s : samples) { if (s.alt_m < 0) { impact = s.t_s; break; } }', says: 'Stops at the first sample below ground and records its time.' },
    seeAlso: ['continue', 'switch', 'for', 'while'],
  },
  {
    name: 'default',
    lang: 'cpp',
    kind: 'keyword',
    official: 'switch statement: as the declaration of the default case label',
    source: 'cppreference.com (C++ keyword: default)',
    when: 'In a switch, default: catches every value no case matched, a good place to report an unexpected value. After a special member function, = default asks the compiler to write the normal version for you, such as a plain destructor or copy constructor.',
    flags: [
      ['default:', 'the switch label for all other values'],
      ['= default', 'let the compiler write this constructor, destructor, assignment or comparison'],
    ],
    example: { command: 'virtual ~Sensor() = default;', says: 'Gives Sensor a virtual destructor that does the ordinary cleanup, without writing a body.' },
    seeAlso: ['switch', 'case', 'delete'],
  },
  {
    name: 'using',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Type alias is a name that refers to a previously defined type (similar to typedef).',
    source: 'cppreference.com',
    when: 'You want a short name for a long type (using Clock = std::chrono::steady_clock;) or to bring names from a namespace into view (using namespace std::chrono_literals; so that 10ms works). Never write using namespace in a header: it spills those names into every file that includes it.',
    flags: [
      ['using Name = Type;', 'a new, shorter name for a type'],
      ['using namespace ns;', 'lets you use everything in ns without the ns:: prefix'],
      ['using Base::f;', 'brings a name from a base class or namespace into this scope'],
    ],
    example: { command: 'using Vec3 = std::array<double, 3>;', says: 'Lets you write Vec3 instead of std::array<double, 3> from then on.' },
    seeAlso: ['typedef', 'namespace'],
  },
  {
    name: 'delete',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Destroys object(s) previously allocated by the new-expression and releases obtained memory area.',
    source: 'cppreference.com',
    when: 'You made an object with new and are finished with it; memory from new[] must be freed with delete[]. Using the pointer afterwards, or deleting twice, is undefined behavior, which is why modern code uses std::unique_ptr instead. Written = delete after a function, it forbids that function, for example copying.',
    flags: [
      ['delete p;', 'destroys one object made with new'],
      ['delete[] p;', 'destroys an array made with new[]'],
      ['= delete', 'forbids a function, such as the copy constructor; calling it will not compile'],
    ],
    example: { command: 'Radio(const Radio&) = delete;', says: 'Makes Radio impossible to copy; code that tries gets a compile error.' },
    seeAlso: ['new', 'default', 'std::unique_ptr'],
  },
  {
    name: 'inline',
    lang: 'cpp',
    kind: 'keyword',
    official: "The inline specifier, when used in a function's decl-specifier-seq, declares the function to be an inline function.",
    source: 'cppreference.com',
    when: 'You define a function or variable in a header that several .cpp files include; inline lets each file have the same definition without a "multiple definition" link error. It no longer really means "paste the code in"; the compiler decides that itself.',
    flags: [
      ['inline function in a header', 'allowed to be defined in every file that includes it'],
      ['inline static member', 'a static class member defined right in the class'],
      ['inline constexpr variable', 'one shared constant across all files'],
    ],
    example: { command: 'inline double kmh_to_ms(double v) { return v / 3.6; }', says: 'Can sit in a header included by many files without a link error.' },
    seeAlso: ['static', 'extern', '#include'],
  },
  {
    name: 'noexcept',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Specifies whether a function could throw exceptions.',
    source: 'cppreference.com',
    when: 'You want to promise that a function never throws, which lets containers such as std::vector move your objects instead of copying them. If an exception does escape a noexcept function, the program stops at once with std::terminate.',
    flags: [
      ['f() noexcept', 'promises f does not throw'],
      ['noexcept(expr)', 'asks, while compiling, whether expr can throw'],
    ],
    example: { command: 'Buffer(Buffer&& other) noexcept;', says: 'Declares a move constructor that promises not to throw, so a vector of Buffer moves them when it grows.' },
    seeAlso: ['throw', 'try'],
  },
  {
    name: 'new',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Creates and initializes objects with dynamic storage duration, that is, objects whose lifetime is not necessarily limited by the scope in which they were created.',
    source: 'cppreference.com',
    when: 'You need an object that lives on after the function that made it ends, with memory taken from the heap. Every new needs exactly one delete, or the memory leaks; prefer std::make_unique. Flight code avoids it inside the control loop because it can be slow and can fail.',
    flags: [
      ['new T(args)', 'makes one object on the heap and gives back a pointer'],
      ['new T[n]', 'makes an array; free it with delete[]'],
      ['new (place) T', 'placement new: builds an object in memory you already have'],
      ['new (std::nothrow) T', 'returns nullptr instead of throwing when memory runs out'],
    ],
    example: { command: 'Tracker* t = new Tracker(42);', says: 'Builds a Tracker on the heap; you must later write delete t;' },
    seeAlso: ['delete', 'nullptr', 'std::make_unique'],
  },
  {
    name: 'enum',
    lang: 'cpp',
    kind: 'keyword',
    official: 'An enumeration is a distinct type whose value is restricted to a range of values (see below for details), which may include several explicitly named constants ("enumerators").',
    source: 'cppreference.com',
    when: 'You have a fixed set of named choices, like flight phases or fault codes. Prefer enum class: its names must be written Phase::Coast and it does not turn into an int by itself. A plain enum spills its names into the surrounding code.',
    flags: [
      ['enum class Name', 'a scoped enumeration: write Name::Value'],
      [': std::uint8_t', 'chooses the underlying integer type and so its size'],
    ],
    example: { command: 'enum class Phase : std::uint8_t { Prelaunch, Ascent, Coast, Descent };', says: 'Defines four named phases stored in one byte, used as Phase::Coast.' },
    seeAlso: ['switch', 'class', 'std::to_underlying'],
  },
  {
    name: 'continue',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Causes the remaining portion of the enclosing for, range-for, while or do-while loop body to be skipped.',
    source: 'cppreference.com',
    when: 'You want to skip the rest of this round of a loop and go on to the next item, such as ignoring a bad sensor reading. In a while loop, make sure the variable that moves the loop forward is updated before the continue, or it loops forever.',
    example: { command: 'for (double p : readings) { if (!std::isfinite(p)) continue; sum += p; }', says: 'Adds up the readings, skipping any that are infinite or not a number.' },
    seeAlso: ['break', 'for', 'while'],
  },
  {
    name: 'static_assert',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Performs compile-time assertion checking.',
    source: 'cppreference.com',
    when: 'You want the build to fail with a clear message if an assumption is wrong, such as the size of a packet or a template argument that must be a float type. It costs nothing when the program runs, because it is checked while compiling.',
    flags: [['static_assert(condition, "message")', 'the condition must be known while compiling; the message is optional since C++17']],
    example: { command: 'static_assert(sizeof(Packet) == 16, "Packet must be 16 bytes on the wire");', says: 'Stops the build with that message if Packet is not exactly 16 bytes.' },
    seeAlso: ['constexpr', 'sizeof'],
  },
  {
    name: 'protected',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Protected members form the interface of a class to its derived classes (which is distinct from the public interface of the class).',
    source: 'cppreference.com',
    when: 'You want a member that derived classes can use but outside code cannot, such as a helper every kind of sensor shares. Protected data members make every derived class depend on them, so prefer protected functions over protected data.',
    flags: [['protected:', 'members below this label can be used by this class and classes derived from it']],
    example: { command: 'class Sensor { protected: double scale_ = 1.0; };', says: 'A class derived from Sensor can read scale_, but main() cannot.' },
    seeAlso: ['public', 'private', 'virtual'],
  },
  {
    name: 'switch',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Transfers control to one of several statements, depending on the value of a condition.',
    source: 'cppreference.com',
    when: 'You want to do something different for each value of an integer or enum, like a flight phase. Each case falls through into the next unless you break. Leave out default when switching on an enum class, and the compiler warns you if you forget a value.',
    flags: [
      ['switch (value)', 'the integer or enum to test'],
      ['case X:', 'where to go when the value is X'],
      ['default:', 'where to go for anything else'],
      ['break;', 'leaves the switch'],
    ],
    example: {
      command: 'switch (phase) { case Phase::Ascent: burn(); break; case Phase::Coast: wait(); break; }',
      says: 'Burns during ascent and waits during coast.',
    },
    seeAlso: ['case', 'default', 'break', 'enum'],
  },
  {
    name: 'decltype',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Inspects the declared type of an entity or the type and value category of an expression.',
    source: 'cppreference.com',
    when: 'You need "the type of this thing" without writing it out, often inside templates or to name the type of a lambda. decltype(x) and decltype((x)) differ: the extra parentheses give a reference type.',
    example: { command: 'decltype(thrust_n) margin = 0.0;', says: 'Makes margin the same type as thrust_n, for example double.' },
    seeAlso: ['auto', 'template'],
  },
  {
    name: 'concept',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Named sets of such requirements are called concepts. Each concept is a predicate, evaluated at compile time, and becomes a part of the interface of a template where it is used as a constraint.',
    source: 'cppreference.com',
    when: 'You want to state what a template needs from its type, such as "has a read() that returns double". Then a wrong type gets one short error at the call instead of pages of errors from deep inside the template.',
    flags: [
      ['template <typename T> concept Name = ...;', 'defines the concept from a true-or-false condition'],
      ['template <Name T>', 'uses it to limit a template'],
      ['Name auto x', 'the short form in a function parameter'],
    ],
    example: { command: 'template <typename T> concept Barometer = requires(T b) { { b.read_pa() } -> std::convertible_to<double>; };', says: 'Defines Barometer: any type with a read_pa() that returns something usable as a double.' },
    seeAlso: ['requires', 'template', 'std::floating_point'],
  },
  {
    name: 'requires',
    lang: 'cpp',
    kind: 'keyword',
    official: 'The keyword requires is used to introduce a requires clause, which specifies constraints on template arguments or on a function declaration.',
    source: 'cppreference.com (Constraints and concepts)',
    when: 'You want to limit which types a template accepts (requires std::floating_point<T>), or to test whether some code would compile for a type (a requires expression, usually inside a concept). It only checks that code would compile, not that it does the right thing.',
    flags: [
      ['requires Cond<T>', 'a requires-clause: the template only accepts types that meet Cond'],
      ['requires(T x) { ... }', 'a requires expression: true if every line inside would compile'],
      ['{ e } -> C<T>', 'e must compile and its type must meet concept C'],
    ],
    example: { command: 'template <typename T> requires std::floating_point<T> T half(T x) { return x / 2; }', says: 'half(3.0) works; half(3) does not compile, because int is not a floating-point type.' },
    seeAlso: ['concept', 'template', 'static_assert'],
  },
  {
    name: 'mutable',
    lang: 'cpp',
    kind: 'keyword',
    official: 'mutable - permits modification of the class member declared mutable even if the containing object is declared const (i.e., the class member is mutable).',
    source: 'cppreference.com',
    when: 'A const member function must still change something no caller can notice, like a cache or a mutex it locks. On a lambda, it lets the lambda change its own captured copies. Using it for real, visible state breaks the promise that const makes.',
    flags: [
      ['mutable member', 'can change even inside a const member function'],
      ['[x]() mutable { ... }', 'a lambda that may change its own copy of x'],
    ],
    example: { command: 'mutable std::mutex m_;', says: 'Lets a const function such as level() lock m_ while it reads.' },
    seeAlso: ['const', 'std::mutex'],
  },
  {
    name: 'const_cast',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Converts between types with different cv-qualification.',
    source: 'cppreference.com',
    when: 'You must pass a const value to an old C function that takes a non-const pointer but never writes through it. Actually changing an object that was created const through the result is undefined behavior; needing const_cast usually means a design problem.',
    flags: [['const_cast<T>(x)', 'the same type as x with const or volatile added or removed']],
    example: { command: 'legacy_log(const_cast<char*>(msg.c_str()));', says: 'Passes the text to an old function whose parameter is not marked const.' },
    seeAlso: ['const', 'static_cast'],
  },
  {
    name: 'sizeof',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Queries size of the object or type.',
    source: 'cppreference.com',
    when: 'You need the number of bytes a type or object takes, for example to copy it with std::memcpy or check a packet layout. On an array passed into a function it gives the size of a pointer, not of the array; use std::size or std::array::size for item counts.',
    flags: [
      ['sizeof(Type)', 'bytes for that type; parentheses are needed'],
      ['sizeof x', 'bytes for that object'],
      ['sizeof...(Ts)', 'how many types are in a template parameter pack'],
    ],
    example: { command: 'std::printf("%zu\\n", sizeof(double));', says: 'Prints 8 on ORBIT\'s machines.' },
    seeAlso: ['alignof', 'struct', 'static_assert'],
  },
  {
    name: 'final',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Specifies that a virtual function cannot be overridden in a derived class, or that a class cannot be derived from.',
    source: 'cppreference.com',
    when: 'You want to stop anyone from replacing a virtual function further down, or from deriving from a class at all. It also lets the compiler skip the table lookup and call the function directly.',
    flags: [
      ['class Name final', 'no class may derive from Name'],
      ['f() final', 'no further class may replace f'],
    ],
    example: { command: 'class Imu final : public Sensor { double read() override; };', says: 'Imu is a Sensor, and nothing can derive from Imu.' },
    seeAlso: ['override', 'virtual'],
  },
  {
    name: 'consteval',
    lang: 'cpp',
    kind: 'keyword',
    official: 'consteval - specifies that a function is an immediate function, that is, every call to the function must produce a compile-time constant',
    source: 'cppreference.com',
    when: 'A function must only ever run while compiling, such as one that builds a lookup table or checks a format string. Calling it with a value only known at run time is a compile error, which is the point.',
    example: { command: 'consteval int ticks_for(double period_s, double tick_s) { return int(period_s / tick_s); }', says: 'ticks_for(0.0025, 1e-6) becomes the number 2500 while compiling; there is no run-time version.' },
    seeAlso: ['constexpr', 'constinit'],
  },
  {
    name: 'float',
    lang: 'cpp',
    kind: 'keyword',
    official: 'float — single precision floating-point type. Usually IEEE-754 binary32 format.',
    source: 'cppreference.com (Fundamental types)',
    when: 'You need a fraction but want half the memory of a double, as on small flight processors or in big arrays. It keeps only about 7 significant digits, so errors build up quickly in long sums. Write 1.5f; plain 1.5 is a double.',
    example: { command: 'float gyro_rad_s = 0.012f;', says: 'Stores a gyro reading in single precision.' },
    seeAlso: ['double'],
  },
  {
    name: 'namespace',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Namespaces provide a method for preventing name conflicts in large projects.',
    source: 'cppreference.com',
    when: 'You want to group your code under a name, like gnc::, so that your normalize() cannot clash with someone else\'s. An unnamed namespace makes names private to one .cpp file.',
    flags: [
      ['namespace gnc { ... }', 'puts everything inside into gnc; use it as gnc::name'],
      ['namespace { ... }', 'names only visible in this file'],
      ['namespace a::b { ... }', 'a nested namespace in one line'],
    ],
    example: { command: 'namespace gnc { double wrap_pi(double a); }', says: 'Declares wrap_pi inside gnc, called as gnc::wrap_pi(angle).' },
    seeAlso: ['using', 'static'],
  },
  {
    name: 'volatile',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Every access (read or write operation, member function call, etc.) made through a glvalue expression of volatile-qualified type is treated as a visible side-effect for the purposes of optimization (that is, within a single thread of execution, volatile accesses cannot be optimized out or reordered with another visible side effect that is sequenced-before or sequenced-after the volatile access. This makes volatile objects suitable for communication with a signal handler, but not with another thread of execution, see std::memory_order).',
    source: 'cppreference.com (cv (const and volatile) type qualifiers)',
    when: 'You are reading or writing a hardware register, where every access matters and the compiler must not skip or merge them. It does not make code thread-safe: sharing a variable between threads needs std::atomic or a mutex.',
    example: { command: 'volatile std::uint32_t* const status = reinterpret_cast<volatile std::uint32_t*>(0x40001000);', says: 'Points at a device status register so that every read really goes to the hardware.' },
    seeAlso: ['std::atomic', 'reinterpret_cast', 'const'],
  },
  {
    name: 'extern',
    lang: 'cpp',
    kind: 'keyword',
    official: 'static storage duration with external linkage specifier',
    source: 'cppreference.com (C++ keyword: extern)',
    when: 'You want to say "this variable exists, defined in some other file" (extern int g_count; in a header, with the real definition in one .cpp). extern "C" makes a function callable from C, and extern template stops a template being built again in every file. Declaring it extern but defining it nowhere gives an "undefined reference" link error.',
    flags: [
      ['extern T name;', 'declares a variable defined in another file'],
      ['extern "C"', 'use C naming so C code, or Python through ctypes, can find the function'],
      ['extern template class X<T>;', 'do not build this template here; another file does'],
    ],
    example: { command: 'extern "C" double gnc_step(double dt);', says: 'Declares gnc_step with a plain C name, so C code or Python ctypes can call it.' },
    seeAlso: ['static', 'inline', 'template'],
  },
  {
    name: 'throw',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Throwing an exception transfers control to a handler.',
    source: 'cppreference.com (Throwing exceptions)',
    when: 'Something has gone wrong that this function cannot fix, and you want to jump out to a catch further up that can. If nothing catches it, the program ends. Many flight builds turn exceptions off, so the lessons also show other ways to report errors.',
    flags: [
      ['throw std::runtime_error("...")', 'throws an error object with a message'],
      ['throw;', 'inside a catch: throws the same error again'],
    ],
    example: { command: 'if (dt <= 0) throw std::invalid_argument("dt must be positive");', says: 'Stops the function and sends that error up to the nearest matching catch.' },
    seeAlso: ['try', 'catch', 'noexcept', 'std::runtime_error'],
  },
  {
    name: 'reinterpret_cast',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Converts between types by reinterpreting the underlying bit pattern.',
    source: 'cppreference.com',
    when: 'You are talking to hardware or raw bytes: turning an address number into a register pointer, or looking at an object as bytes. Reading an object through a pointer of an unrelated type is undefined behavior; to reuse the bits of a float as an integer, use std::bit_cast or std::memcpy.',
    flags: [['reinterpret_cast<T*>(p)', 'treats the address in p as pointing to a T']],
    example: { command: 'auto* bytes = reinterpret_cast<const unsigned char*>(&packet);', says: 'Lets you read the packet one byte at a time, for example to compute a checksum.' },
    seeAlso: ['static_cast', 'volatile', 'std::bit_cast'],
  },
  {
    name: 'typedef',
    lang: 'cpp',
    kind: 'keyword',
    official: 'typedef - creates an alias that can be used anywhere in place of a (possibly complex) type name.',
    source: 'cppreference.com',
    when: 'You read it in older C and C++ code to give a type a new name. New code uses using Name = Type; instead, which reads left to right and also works with templates.',
    example: { command: 'typedef double Seconds;', says: 'Makes Seconds another name for double, the same as using Seconds = double;' },
    seeAlso: ['using'],
  },
  {
    name: 'friend',
    lang: 'cpp',
    kind: 'keyword',
    official: 'The friend declaration appears in a class body and grants a function or another class access to private and protected members of the class where the friend declaration appears.',
    source: 'cppreference.com',
    when: 'A function outside the class, such as operator<< for printing or a test helper, needs to see private members. Use it sparingly: every friend is one more place that depends on the class\'s insides.',
    example: { command: 'friend std::ostream& operator<<(std::ostream& os, const Vec3& v);', says: 'Lets the printing operator read Vec3\'s private x, y and z.' },
    seeAlso: ['private', 'class', 'operator'],
  },
  {
    name: 'alignas',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Specifies the alignment requirement of a type or an object.',
    source: 'cppreference.com',
    when: 'You need an object to start at an address that is a multiple of some number, for fast vector math, DMA hardware, or to put two counters on separate cache lines so threads do not slow each other down. It may add padding and make the object bigger.',
    flags: [['alignas(N)', 'start at an address that is a multiple of N, which must be a power of two']],
    example: { command: 'struct alignas(64) Counter { std::atomic<int> n; };', says: 'Each Counter starts on its own 64-byte cache line.' },
    seeAlso: ['alignof', 'sizeof'],
  },
  {
    name: 'try',
    lang: 'cpp',
    kind: 'keyword',
    official: 'An exception thrown in a try block can possibly be handled by an associated handler.',
    source: 'cppreference.com (try block)',
    when: 'You are about to run code that may throw, and you want to handle the error here instead of letting the program end. Keep the try block small, around just the calls that can fail.',
    flags: [['try { ... } catch (...) { ... }', 'the code that may throw, followed by one or more handlers']],
    example: { command: 'try { cfg = load_config("flight.cfg"); } catch (const std::exception& e) { std::puts(e.what()); }', says: 'Loads the config, or prints the error message if loading throws.' },
    seeAlso: ['catch', 'throw', 'noexcept'],
  },
  {
    name: 'catch',
    lang: 'cpp',
    kind: 'keyword',
    official: 'An exception can be handled by a handler.',
    source: 'cppreference.com',
    when: 'You write it after a try to say which errors you handle and what to do. Catch by const reference (const std::exception& e) so derived errors are not sliced down to the base; handlers are tried in order, so put the most specific first. catch (...) catches everything.',
    flags: [
      ['catch (const T& e)', 'handles errors of type T or anything derived from it'],
      ['catch (...)', 'handles any error at all'],
      ['e.what()', 'the error message'],
    ],
    example: { command: 'catch (const std::out_of_range& e) { std::printf("bad index: %s\\n", e.what()); }', says: 'Handles an out-of-range error and prints its message.' },
    seeAlso: ['try', 'throw', 'std::exception'],
  },
  {
    name: 'alignof',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Queries alignment requirements of a type.',
    source: 'cppreference.com',
    when: 'You want to know which address multiple a type must start on, for example to understand the padding the compiler puts inside a struct. The answer is always a power of two.',
    flags: [['alignof(Type)', 'the alignment in bytes']],
    example: { command: 'std::printf("%zu\\n", alignof(double));', says: 'Prints 8: a double must start at an address divisible by 8.' },
    seeAlso: ['alignas', 'sizeof'],
  },
  {
    name: 'short',
    lang: 'cpp',
    kind: 'keyword',
    official: 'short — target type will be optimized for space and will have width of at least 16 bits.',
    source: 'cppreference.com (Fundamental types)',
    when: 'You need a small whole number to save space. In arithmetic it is turned into int first, so the result of adding two shorts is an int. Flight code usually writes std::int16_t so the size is exact.',
    example: { command: 'short temp_c = -40;', says: 'Stores a temperature in a 16-bit whole number.' },
    seeAlso: ['int', 'long', 'std::int16_t'],
  },
  {
    name: 'do',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Conditionally executes a statement repeatedly (at least once).',
    source: 'cppreference.com (do-while loop)',
    when: 'You want the loop body to run at least once before the test, like asking a sensor again until it answers. The lessons also use do { ... } while (false) in macros, to make several lines behave as one statement.',
    flags: [
      ['do { ... } while (cond);', 'runs once, then again while cond is true; note the semicolon'],
      ['do { ... } while (false)', 'the macro wrapper: runs exactly once'],
    ],
    example: { command: 'do { reading = read_baro(); } while (reading < 0);', says: 'Reads the barometer, and reads again as long as the value is invalid.' },
    seeAlso: ['while', 'for', '#define'],
  },
  {
    name: 'constinit',
    lang: 'cpp',
    kind: 'keyword',
    official: 'constinit - asserts that a variable has static initialization, i.e. zero initialization and constant initialization, otherwise the program is ill-formed.',
    source: 'cppreference.com',
    when: 'You have a global or static variable and want a guarantee that its starting value is set while compiling, so no other file can see it before it is ready. Unlike constexpr, the variable can still change later.',
    example: { command: 'constinit std::uint32_t g_frames_sent = 0;', says: 'A counter that starts at 0 before any code runs and can be increased afterwards.' },
    seeAlso: ['constexpr', 'consteval', 'static'],
  },
  {
    name: 'thread_local',
    lang: 'cpp',
    kind: 'keyword',
    official: 'All variables declared with thread_local have thread storage duration. The storage for these entities lasts for the duration of the thread in which they are created.',
    source: 'cppreference.com (Storage class specifiers)',
    when: 'You want a variable that works like a static, but with a separate copy for every thread, so threads never share it. Reading one may cost a small lookup, so measure it before using it in a fast loop.',
    example: { command: 'thread_local int t_retries = 0;', says: 'Each thread gets its own t_retries, starting at 0.' },
    seeAlso: ['static', 'std::thread'],
  },
  {
    name: 'co_await',
    lang: 'cpp',
    kind: 'keyword',
    official: 'The unary operator co_await suspends a coroutine and returns control to the caller.',
    source: 'cppreference.com',
    when: 'Inside a coroutine, a function that can pause and resume later, you want to wait for something without blocking, like the next control tick. Just using it turns the function into a coroutine, which then needs a return type with a promise_type.',
    example: { command: 'co_await NextTick{};', says: 'Pauses the warm-up sequence until the next cycle resumes it.' },
    seeAlso: ['co_yield', 'co_return', 'std::coroutine_handle'],
  },
  {
    name: 'export',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Marks a declaration, a group of declarations, or another module as exported by the current module.',
    source: 'cppreference.com',
    when: 'In a C++20 module, you mark which names other files may use when they import it; anything not exported stays hidden. Module support in compilers and build tools is still uneven.',
    flags: [
      ['export module name;', 'starts the file that defines a module'],
      ['export declaration', 'makes that function, type or constant visible to importers'],
    ],
    example: { command: 'export constexpr double deg_to_rad(double deg) { return deg * 3.141592653589793 / 180.0; }', says: 'Makes deg_to_rad usable in any file that writes import units;' },
    seeAlso: ['module', 'import'],
  },
  {
    name: 'typeid',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Queries information of a type.',
    source: 'cppreference.com',
    when: 'You want to ask, while the program runs, what type an object really is. It needs run-time type information, which many flight builds switch off with -fno-rtti; then typeid stops compiling.',
    example: { command: 'std::puts(typeid(*sensor).name());', says: 'Prints a (compiler-encoded) name of the real type behind the sensor pointer.' },
    seeAlso: ['virtual'],
  },
  {
    name: 'asm',
    lang: 'cpp',
    kind: 'keyword',
    official: 'asm-declaration gives the ability to embed assembly language source code within a C++ program.',
    source: 'cppreference.com (asm declaration)',
    when: 'You need to write processor instructions directly, which is rare. The lessons use an empty asm volatile line in benchmarks, so the compiler cannot delete work it thinks is unused. The syntax depends on the compiler.',
    example: { command: 'asm volatile("" : : "r"(&copy) : "memory");', says: 'Tells the compiler copy is used, so a benchmark loop is not optimized away.' },
    seeAlso: ['volatile'],
  },
  {
    name: 'union',
    lang: 'cpp',
    kind: 'keyword',
    official: 'A union is a special class type that can hold only one of its non-static data members at a time.',
    source: 'cppreference.com',
    when: 'You want several members to share the same memory, such as a pool slot that holds either a message or a link to the next free slot. Reading a member other than the one last written is undefined behavior in C++; for safe "one of several types" use std::variant.',
    example: { command: 'union Slot { Message msg; Slot* next; };', says: 'A Slot holds either a Message or a pointer, in the same bytes.' },
    seeAlso: ['struct', 'std::variant'],
  },
  {
    name: 'module',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Modules are a language feature to share declarations and definitions across translation units. They are an alternative to some use cases of headers.',
    source: 'cppreference.com',
    when: 'You want to share code between files without #include, so nothing is pasted in and including it twice is harmless (C++20). Compilers and build systems still differ in how well they support them.',
    flags: [['export module name;', 'the first line of the file that defines the module']],
    example: { command: 'export module units;', says: 'Starts a module named units that other files can import.' },
    seeAlso: ['export', 'import', '#include'],
  },
  {
    name: 'import',
    lang: 'cpp',
    kind: 'keyword',
    official: 'All declarations and definitions exported in the module interface units of the given named module will be available in the translation unit using the import declaration.',
    source: 'cppreference.com (Modules)',
    when: 'You want to use a C++20 module in this file. Unlike #include, it brings in only the names the module exported, and nothing from your file leaks into it.',
    example: { command: 'import units;', says: 'Makes everything the units module exported, such as deg_to_rad, available here.' },
    seeAlso: ['module', 'export', '#include'],
  },
  {
    name: 'co_yield',
    lang: 'cpp',
    kind: 'keyword',
    official: 'co_yield expression returns a value to the caller and suspends the current coroutine: it is the common building block of resumable generator functions.',
    source: 'cppreference.com',
    when: 'You are writing a generator, a function that hands out values one at a time and pauses between them. The caller must resume it to get the next value.',
    example: { command: 'for (int n = 0;; ++n) co_yield n;', says: 'Hands 0, then 1, then 2 to the caller, one each time it is resumed.' },
    seeAlso: ['co_await', 'co_return'],
  },
  {
    name: 'co_return',
    lang: 'cpp',
    kind: 'keyword',
    official: 'the co_return statement — to complete execution returning a value',
    source: 'cppreference.com',
    when: 'You want to finish a coroutine, optionally with a final result. A plain return is not allowed inside a coroutine; use co_return instead.',
    example: { command: 'co_return 0;', says: 'Ends the coroutine with the result 0 by calling its promise\'s return_value(0).' },
    seeAlso: ['co_await', 'co_yield', 'return'],
  },
  {
    name: '#include',
    lang: 'cpp',
    kind: 'directive',
    official: 'Includes other source file into current source file at the line immediately after the directive.',
    source: 'cppreference.com',
    when: 'You want to use something declared in another file, such as std::printf from <cstdio> or your own vec3.hpp. It really pastes the file in, so a header without an include guard or #pragma once can cause "redefinition" errors when it arrives twice.',
    flags: [
      ['#include <name>', 'a standard or installed library header'],
      ['#include "name"', 'your own header, searched for next to this file first'],
    ],
    example: { command: '#include <cstdio>', says: 'Brings in std::printf and std::puts so you can print.' },
    seeAlso: ['#pragma', '#ifndef', 'import'],
  },
  {
    name: '#pragma',
    lang: 'cpp',
    kind: 'directive',
    official: 'Implementation defined behavior is controlled by #pragma directive.',
    source: 'cppreference.com',
    when: 'You want to give the compiler a special instruction. In ORBIT it is almost always #pragma once at the top of a header, so the header is pasted in only once per file. It only works within one source file, and pragmas the compiler does not know are ignored.',
    flags: [
      ['#pragma once', 'include this header only once per source file'],
      ['#pragma pack', 'removes padding from structs; risky, since misaligned members can fault'],
    ],
    example: { command: '#pragma once', says: 'Placed first in vec3.hpp, it makes a second #include "vec3.hpp" in the same file paste nothing.' },
    seeAlso: ['#include', '#ifndef'],
  },
  {
    name: '#endif',
    lang: 'cpp',
    kind: 'directive',
    official: 'The conditional preprocessing block starts with #if, #ifdef or #ifndef directive, then optionally includes any number of #elif, #elifdef, or #elifndef (since C++23) directives, then optionally includes at most one #else directive and is terminated with #endif directive.',
    source: 'cppreference.com',
    when: 'It closes a block that began with #if, #ifdef or #ifndef. Every one of those needs its own #endif; a missing one gives an "unterminated conditional" error at the end of the file.',
    example: { command: '#endif  // VEC3_HPP', says: 'Ends the include guard; the comment reminds readers which #ifndef it closes.' },
    seeAlso: ['#if', '#ifdef', '#ifndef', '#else'],
  },
  {
    name: '#define',
    lang: 'cpp',
    kind: 'directive',
    official: 'The preprocessor supports text macro replacement. Function-like text macro replacement is also supported.',
    source: 'cppreference.com',
    when: 'You want the preprocessor to replace a name with text before compiling: include guards, build switches, and assert-style macros that need the file and line. Macros ignore scope and types, and an argument is pasted in as text, so wrap each use in parentheses; for constants prefer constexpr.',
    flags: [
      ['#define NAME value', 'replaces NAME with value everywhere after this line'],
      ['#define NAME(x) ...', 'a function-like macro; x is pasted in as text'],
      ['#x', 'turns a macro argument into a string'],
      ['\\ at line end', 'continues the macro on the next line'],
    ],
    example: { command: '#define GNC_MAX_THRUSTERS 12', says: 'Every later GNC_MAX_THRUSTERS in the file becomes 12 before the compiler sees it.' },
    seeAlso: ['#ifdef', '#ifndef', '#cond', 'constexpr'],
  },
  {
    name: '#ifdef',
    lang: 'cpp',
    kind: 'directive',
    official: '#ifdef identifier is essentially equivalent to #if defined identifier.',
    source: 'cppreference.com',
    when: 'You want code compiled only when a macro is defined, for example a feature-test macro or a -DUNIT_TEST flag. It only checks that the name exists, not its value. Test-only #ifdef code means the program you test is not the one you ship.',
    example: { command: '#ifdef __cpp_lib_hardware_interference_size', says: 'Compiles the lines up to #endif only if the library provides that feature.' },
    seeAlso: ['#ifndef', '#if', '#endif', '#define'],
  },
  {
    name: '#ifndef',
    lang: 'cpp',
    kind: 'directive',
    official: '#ifndef identifier is essentially equivalent to #if !defined identifier.',
    source: 'cppreference.com',
    when: 'You want code compiled only when a macro is not defined yet; its main use is the include guard (#ifndef, #define, #endif) that stops a header being pasted twice. The guard name must be unique across the whole project.',
    example: { command: '#ifndef VEC3_HPP\n#define VEC3_HPP', says: 'The first time, VEC3_HPP is not defined, so the header is kept and the name gets defined; the second time everything up to #endif is skipped.' },
    seeAlso: ['#ifdef', '#define', '#endif', '#pragma'],
  },
  {
    name: '#else',
    lang: 'cpp',
    kind: 'directive',
    official: 'The conditional preprocessing block starts with #if, #ifdef or #ifndef directive, then optionally includes any number of #elif, #elifdef, or #elifndef (since C++23) directives, then optionally includes at most one #else directive and is terminated with #endif directive.',
    source: 'cppreference.com',
    when: 'It marks the code to compile when the #if, #ifdef or #ifndef test above it was false. There can be at most one per block.',
    example: { command: '#ifdef UNIT_TEST\nusing Clock = FakeClock;\n#else\nusing Clock = std::chrono::steady_clock;\n#endif', says: 'Uses the fake clock in test builds and the real one otherwise.' },
    seeAlso: ['#if', '#ifdef', '#elif', '#endif'],
  },
  {
    name: '#cond',
    lang: 'cpp',
    kind: 'directive',
    official: 'In function-like macros, a # operator before an identifier in the replacement-list runs the identifier through parameter replacement and encloses the result in quotes, effectively creating a string literal.',
    source: 'cppreference.com',
    when: 'Inside a macro with a parameter named cond, #cond turns whatever code was passed in into text, so a check macro can print exactly which condition failed. It is not a directive of its own: it is the # (stringize) operator applied to the parameter cond, and it only works inside a #define.',
    example: {
      command: '#define CHECK(cond) do { if (!(cond)) std::printf("failed: %s\\n", #cond); } while (false)',
      says: 'CHECK(fuel_kg > 0); prints failed: fuel_kg > 0 when the check fails.',
    },
    seeAlso: ['#define', 'do'],
  },
  {
    name: '#if',
    lang: 'cpp',
    kind: 'directive',
    official: 'The preprocessor supports conditional compilation of parts of source file.',
    source: 'cppreference.com',
    when: 'You want code compiled only when a condition about macros is true, such as #if GNC_MAX_THRUSTERS > 8. It is decided before compiling, so it can only test macros and plain numbers, not your variables; an undefined name counts as 0.',
    flags: [
      ['#if expression', 'an integer test on macros, like #if GNC_MAX_THRUSTERS > 8'],
      ['defined(NAME)', 'true if the macro NAME exists'],
    ],
    example: { command: '#if GNC_MAX_THRUSTERS > 8', says: 'Keeps the following lines, up to #else or #endif, only in builds made with more than 8 thrusters.' },
    seeAlso: ['#elif', '#else', '#endif', '#ifdef'],
  },
  {
    name: '#elif',
    lang: 'cpp',
    kind: 'directive',
    official: 'The conditional preprocessing block starts with #if, #ifdef or #ifndef directive, then optionally includes any number of #elif, #elifdef, or #elifndef (since C++23) directives, then optionally includes at most one #else directive and is terminated with #endif directive.',
    source: 'cppreference.com',
    when: 'You want to try another preprocessor test when the #if above was false, like "else if" for the preprocessor. Only the first true branch is kept.',
    example: { command: '#if GNC_MAX_THRUSTERS > 8\n...\n#elif GNC_MAX_THRUSTERS > 4\n...\n#endif', says: 'Keeps the second part only when there are 5 to 8 thrusters.' },
    seeAlso: ['#if', '#else', '#endif'],
  },
  {
    name: '#error',
    lang: 'cpp',
    kind: 'directive',
    official: 'After encountering the #error directive, an implementation displays the message diagnostic-message and renders the program ill-formed (the compilation stops).',
    source: 'cppreference.com',
    when: 'You want the build to stop with your own message when the settings are wrong, such as a missing required flag. Put it inside an #if so it only fires in the bad case.',
    example: { command: '#ifndef GNC_MAX_THRUSTERS\n#error "Build with -DGNC_MAX_THRUSTERS=<n>"\n#endif', says: 'Stops the build with that message if the thruster count was not given.' },
    seeAlso: ['#if', '#ifndef', 'static_assert'],
  },
]
