import type { CommandRef } from './types'

export const COMMANDS: CommandRef[] = [
  {
    name: '<string>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::basic_string class template',
    source: 'cppreference.com',
    when: 'Include it whenever you use std::string, the text type that grows as you add to it. It also gives you std::to_string, std::stoi and std::getline. Some compilers let you skip it because another header pulls it in, but that is luck, so include it yourself.',
    example: { command: '#include <string>\nstd::string callsign = "ORBIT-" + std::to_string(7);', says: 'Builds the text ORBIT-7.' },
    seeAlso: ['std::string', 'std::to_string', '<string_view>'],
  },
  {
    name: '<vector>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::vector container',
    source: 'cppreference.com',
    when: 'Include it to use std::vector, the list that grows as you push things onto it. It is the container to reach for first. Warning: adding elements can move the whole list in memory, so pointers and references into it can go stale.',
    example: { command: '#include <vector>\nstd::vector<double> altitudes_km{0.0, 12.5, 48.0};', says: 'Makes a list of three altitudes that you can add to later with push_back.' },
    seeAlso: ['std::vector', '<array>'],
  },
  {
    name: '<utility>',
    lang: 'cpp',
    kind: 'header',
    official: 'Various utility components',
    source: 'cppreference.com',
    when: 'Include it for small helpers you use all the time: std::move, std::pair, std::swap, std::forward and std::exchange. Warning: std::move does not move anything by itself; it only marks an object as okay to take from, and afterward that object may be empty.',
    example: { command: '#include <utility>\nstd::pair<std::string, double> reading{"thrust_kN", 845.0};', says: 'Holds a name and a value together: reading.first is "thrust_kN" and reading.second is 845.' },
    seeAlso: ['std::move', 'std::pair', 'std::swap'],
  },
  {
    name: '<algorithm>',
    lang: 'cpp',
    kind: 'header',
    official: 'Algorithms that operate on ranges',
    source: 'cppreference.com',
    when: 'Include it for ready-made loops: std::sort, std::find, std::max_element, std::count_if, std::transform and many more. Warning: std::remove and std::remove_if do not shrink the container; they move the kept items forward, and you must call erase to cut off the rest.',
    example: { command: '#include <algorithm>\nstd::sort(temps.begin(), temps.end());', says: 'Sorts the temps vector from smallest to largest.' },
    seeAlso: ['std::sort', 'std::find', 'std::max_element', '<numeric>'],
  },
  {
    name: '<cstddef>',
    lang: 'cpp',
    kind: 'header',
    official: 'Standard macros and typedefs',
    source: 'cppreference.com',
    when: 'Include it for std::size_t (the type for sizes and counts), std::byte, std::ptrdiff_t and offsetof. Warning: std::size_t is unsigned, so counting down past zero wraps around to a huge number instead of going negative.',
    example: { command: '#include <cstddef>\nstd::size_t n_samples = 1024;', says: 'Makes a count of samples with the type the standard library uses for sizes.' },
    seeAlso: ['std::size_t', 'std::byte', '<stddef.h>'],
  },
  {
    name: '<sstream>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::basic_stringstream, std::basic_istringstream, std::basic_ostringstream class templates and typedefs',
    source: 'cppreference.com',
    when: 'Include it to treat a string like a stream: std::ostringstream builds text with <<, and std::istringstream pulls values out of text with >>. Warning: once a read fails, the stream stops reading until you clear it, so check it before you trust the value.',
    example: { command: '#include <sstream>\nstd::istringstream line("28.57 -80.65");  line >> lat >> lon;', says: 'Reads the two numbers out of the text into lat and lon.' },
    seeAlso: ['std::istringstream', 'std::ostringstream', 'std::stringstream'],
  },
  {
    name: '<optional>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::optional class template',
    source: 'cppreference.com',
    when: 'Include it for std::optional, a box that holds either a value or nothing, for answers that might be missing. Warning: using * on an empty optional is undefined behavior (the program may do anything), so check it first or use value_or.',
    example: { command: '#include <optional>\nstd::optional<double> last_fix = std::nullopt;', says: 'Makes a slot for a GPS fix that starts out empty.' },
    seeAlso: ['std::optional', 'std::nullopt', '<variant>'],
  },
  {
    name: '<cctype>',
    lang: 'cpp',
    kind: 'header',
    official: 'Functions to determine the category of narrow characters',
    source: 'cppreference.com',
    when: 'Include it to test or change single characters: std::isdigit, std::isalpha, std::isspace, std::toupper and std::tolower. Warning: passing a plain char that holds a negative value is undefined behavior, so cast it to unsigned char first.',
    example: { command: '#include <cctype>\nif (std::isdigit(static_cast<unsigned char>(c))) ++digits;', says: 'Counts c if it is a digit from 0 to 9.' },
    seeAlso: ['std::isdigit', 'std::toupper', 'std::isspace'],
  },
  {
    name: '<iostream>',
    lang: 'cpp',
    kind: 'header',
    official: 'Several standard stream objects',
    source: 'cppreference.com',
    when: 'Include it to print with std::cout and read typed input with std::cin. It is in almost every first program. Warning: std::endl also flushes the output each time, which is slow in a tight loop; "\\n" just ends the line.',
    example: { command: '#include <iostream>\nstd::cout << "T-minus " << 10 << "\\n";', says: 'Prints T-minus 10 and ends the line.' },
    seeAlso: ['std::cout', 'std::cin', 'std::endl', '<cstdio>'],
  },
  {
    name: '<map>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::map and std::multimap associative containers',
    source: 'cppreference.com',
    when: 'Include it for std::map, which stores key-value pairs kept sorted by key. Warning: reading m[key] for a key that is not there quietly adds it with a default value; use find or contains when you only want to look.',
    example: { command: '#include <map>\nstd::map<std::string, double> fuel_kg{{"stage1", 4000.0}};', says: 'Makes a table from stage name to fuel mass.' },
    seeAlso: ['std::map', '<unordered_map>'],
  },
  {
    name: '<memory>',
    lang: 'cpp',
    kind: 'header',
    official: 'High-level memory management utilities',
    source: 'cppreference.com',
    when: 'Include it for smart pointers, std::unique_ptr and std::shared_ptr, and their makers std::make_unique and std::make_shared. They delete the object for you when nobody needs it anymore. Warning: two shared_ptrs that point at each other are never freed; break the loop with std::weak_ptr.',
    example: { command: '#include <memory>\nauto engine = std::make_unique<Engine>("Merlin");', says: 'Creates an Engine on the heap that is deleted automatically when engine goes out of scope.' },
    seeAlso: ['std::unique_ptr', 'std::shared_ptr', 'std::make_unique'],
  },
  {
    name: '<type_traits>',
    lang: 'cpp',
    kind: 'header',
    official: 'Compile-time type information utilities',
    source: 'cppreference.com',
    when: 'Include it in templates to ask questions about types while the program compiles: std::is_same_v, std::is_integral_v, std::is_floating_point_v, std::decay_t and more. The answers are settled before the program runs, so they cost nothing at run time.',
    example: { command: '#include <type_traits>\nstatic_assert(std::is_floating_point_v<double>);', says: 'Checks at compile time that double is a floating-point type; the build fails if it is not.' },
    seeAlso: ['std::is_same_v', 'std::is_integral_v', '<concepts>'],
  },
  {
    name: '<iomanip>',
    lang: 'cpp',
    kind: 'header',
    official: 'Helper functions to control the format of input and output',
    source: 'cppreference.com',
    when: 'Include it to control how numbers print with std::cout: std::setprecision, std::setw and std::fixed. Warning: most of these settings stick to the stream for everything after, but std::setw only lasts for the next item.',
    example: { command: '#include <iomanip>\nstd::cout << std::fixed << std::setprecision(2) << 7.6612;', says: 'Prints 7.66.' },
    seeAlso: ['std::setprecision', 'std::setw', 'std::fixed'],
  },
  {
    name: '<numeric>',
    lang: 'cpp',
    kind: 'header',
    official: 'Numeric operations on values in ranges',
    source: 'cppreference.com',
    when: 'Include it for number-crunching loops: std::accumulate, std::reduce, std::iota, std::inner_product and std::gcd. Warning: std::accumulate adds using the type of its starting value, so starting at 0 instead of 0.0 throws away the decimals.',
    example: { command: '#include <numeric>\ndouble total = std::accumulate(burn.begin(), burn.end(), 0.0);', says: 'Adds up every value in burn.' },
    seeAlso: ['std::accumulate', 'std::iota', 'std::reduce', '<algorithm>'],
  },
  {
    name: '<variant>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::variant class template',
    source: 'cppreference.com',
    when: 'Include it for std::variant, a value that holds exactly one of several listed types at a time, and std::visit to handle each case. Warning: std::get with the wrong type throws std::bad_variant_access; check first with std::get_if or std::holds_alternative.',
    example: { command: '#include <variant>\nstd::variant<int, std::string> cmd = std::string("ABORT");', says: 'cmd now holds the string alternative, "ABORT".' },
    seeAlso: ['std::variant', 'std::visit', 'std::get_if', '<optional>'],
  },
  {
    name: '<cmath>',
    lang: 'cpp',
    kind: 'header',
    official: 'Common mathematics functions',
    source: 'cppreference.com',
    when: 'Include it for math: std::sqrt, std::pow, std::sin, std::cos, std::atan2, std::fabs, std::isnan and more. Warning: the trig functions work in radians, not degrees.',
    example: { command: '#include <cmath>\ndouble r = std::sqrt(x * x + y * y);', says: 'Finds the distance from the origin to the point (x, y).' },
    seeAlso: ['std::sqrt', 'std::pow', 'std::sin', '<numbers>'],
  },
  {
    name: '<iterator>',
    lang: 'cpp',
    kind: 'header',
    official: 'Range iterators',
    source: 'cppreference.com',
    when: 'Include it for tools that work with iterators (the position markers containers hand out): std::back_inserter, std::distance, std::begin and std::end. Warning: an iterator into a vector goes stale when the vector grows, like a bookmark in a book that got reprinted.',
    example: { command: '#include <iterator>\nstd::copy(src.begin(), src.end(), std::back_inserter(dst));', says: 'Copies every item of src onto the end of dst, growing dst as it goes.' },
    seeAlso: ['std::back_inserter', 'std::distance', 'std::begin'],
  },
  {
    name: '<unordered_map>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::unordered_map and std::unordered_multimap unordered associative containers',
    source: 'cppreference.com',
    when: 'Include it for std::unordered_map, a key-value table that finds keys very fast using hashing but keeps them in no order. Warning: looping over it gives the keys in no useful order, and, like std::map, m[key] adds a key that is missing.',
    example: { command: '#include <unordered_map>\nstd::unordered_map<std::string, int> crew_age{{"Ada", 34}};', says: 'Makes a fast lookup table from crew name to age.' },
    seeAlso: ['std::unordered_map', '<map>', 'std::hash'],
  },
  {
    name: '<cstdlib>',
    lang: 'cpp',
    kind: 'header',
    official: 'General purpose utilities: program control, dynamic memory allocation, random numbers, sort and search',
    source: 'cppreference.com',
    when: 'Include it for C-style helpers: std::exit, std::abort, std::atoi, std::malloc, std::free, EXIT_SUCCESS and EXIT_FAILURE. Warning: std::atoi returns 0 for text it cannot read, so you cannot tell "0" from junk; std::from_chars can tell you.',
    example: { command: '#include <cstdlib>\nif (!sensor_ok) return EXIT_FAILURE;', says: 'Ends main with the standard "something went wrong" exit code.' },
    seeAlso: ['std::exit', 'std::atoi', 'std::malloc', '<stdlib.h>'],
  },
  {
    name: '<initializer_list>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::initializer_list class template',
    source: 'cppreference.com',
    when: 'Include it when you write a function or constructor that takes a brace list like {1, 2, 3}. Warning: the items are read-only, and the list only lives as long as the line that made it, so do not keep one around.',
    example: { command: '#include <initializer_list>\ndouble sum(std::initializer_list<double> xs);', says: 'Lets you call sum({1.5, 2.5, 3.0}) with any number of values in braces.' },
    seeAlso: ['std::initializer_list'],
  },
  {
    name: '<functional>',
    lang: 'cpp',
    kind: 'header',
    official: 'Function objects, Function invocations, Bind operations and Reference wrappers',
    source: 'cppreference.com',
    when: 'Include it for std::function (a box that holds anything you can call: a function, a lambda or a function object), plus std::greater, std::hash and std::ref. Warning: calling an empty std::function throws std::bad_function_call.',
    example: { command: '#include <functional>\nstd::function<void(double)> on_alarm = [](double t) { log_alarm(t); };', says: 'Stores a lambda so it can be called later as on_alarm(12.5).' },
    seeAlso: ['std::function', 'std::greater', 'std::ref'],
  },
  {
    name: '<array>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::array container',
    source: 'cppreference.com',
    when: 'Include it for std::array, a fixed-size list whose size is part of its type, stored right in place with no heap memory. Warning: [] does no bounds check; .at() does, and throws if you go past the end.',
    example: { command: '#include <array>\nstd::array<double, 3> position_m{7000e3, 0.0, 0.0};', says: 'Makes exactly three numbers for x, y and z.' },
    seeAlso: ['std::array', '<vector>', '<span>'],
  },
  {
    name: '<string_view>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::basic_string_view class template',
    source: 'cppreference.com',
    when: 'Include it for std::string_view, a cheap read-only window onto text that someone else owns, great for function parameters. Warning: it does not own the text, so a view onto a temporary string dangles (points at freed memory) as soon as that string is gone.',
    example: { command: '#include <string_view>\nbool is_abort(std::string_view cmd) { return cmd == "ABORT"; }', says: 'Checks a command without copying its text.' },
    seeAlso: ['std::string_view', '<string>'],
  },
  {
    name: '<ostream>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::basic_ostream, std::basic_iostream class templates and typedefs',
    source: 'cppreference.com',
    when: 'Include it when your code writes to some output stream but does not need std::cout itself, for example to write operator<< for your own type. <iostream> already brings it in, so you mostly see it in headers that want to stay light.',
    example: { command: '#include <ostream>\nstd::ostream& operator<<(std::ostream& os, const Vec3& v) { return os << v.x << "," << v.y << "," << v.z; }', says: 'Teaches every output stream how to print a Vec3.' },
    seeAlso: ['std::ostream', '<iostream>'],
  },
  {
    name: '<concepts>',
    lang: 'cpp',
    kind: 'header',
    official: 'Fundamental library concepts',
    source: 'cppreference.com',
    when: 'Include it for ready-made concepts (named rules a template type must follow) such as std::integral, std::floating_point, std::same_as and std::convertible_to. A wrong type then gets a short, clear error instead of pages of template noise.',
    example: { command: '#include <concepts>\ntemplate <std::floating_point T> T half(T x) { return x / 2; }', says: 'half works for float and double, and refuses int at compile time.' },
    seeAlso: ['std::integral', 'std::floating_point', 'concept', 'requires'],
  },
  {
    name: '<ranges>',
    lang: 'cpp',
    kind: 'header',
    official: 'Range access, primitives, requirements, utilities and adaptors',
    source: 'cppreference.com',
    when: 'Include it for views, lazy pipelines you chain with |, like std::views::filter, std::views::transform and std::views::take. Warning: a view stores no results and works out each item only when asked, so a view onto a container that has gone away dangles.',
    example: { command: '#include <ranges>\nfor (int n : std::views::iota(1, 4)) std::cout << n;', says: 'Prints 123.' },
    seeAlso: ['std::views', 'std::views::filter', 'std::ranges::sort'],
  },
  {
    name: '<limits>',
    lang: 'cpp',
    kind: 'header',
    official: 'Query properties of arithmetic types',
    source: 'cppreference.com',
    when: 'Include it for std::numeric_limits, which tells you a number type\'s largest and smallest values, its epsilon (the smallest step above 1) and whether it has infinity. Warning: for floating-point types, min() is the smallest positive value, not the most negative; use lowest() for that.',
    example: { command: '#include <limits>\ndouble best = std::numeric_limits<double>::max();', says: 'Starts best at the biggest double, so any real value is smaller.' },
    seeAlso: ['std::numeric_limits', '<climits>'],
  },
  {
    name: '<queue>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::queue and std::priority_queue container adaptors',
    source: 'cppreference.com',
    when: 'Include it for std::queue (first in, first out) and std::priority_queue (always hands you the biggest item first). Warning: pop() returns nothing; read front() or top() before you pop.',
    example: { command: '#include <queue>\nstd::queue<std::string> uplink;  uplink.push("ARM");', says: 'Adds ARM to the back of the uplink command queue.' },
    seeAlso: ['std::priority_queue', '<deque>'],
  },
  {
    name: '<set>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::set and std::multiset associative containers',
    source: 'cppreference.com',
    when: 'Include it for std::set, a sorted collection where each value appears only once. Warning: your own types need an operator< (or operator<=>) so the set knows how to order them.',
    example: { command: '#include <set>\nstd::set<int> seen{3, 1, 3};', says: 'Holds 1 and 3; the second 3 is dropped.' },
    seeAlso: ['std::set', '<compare>'],
  },
  {
    name: '<climits>',
    lang: 'cpp',
    kind: 'header',
    official: 'Limits of integral types',
    source: 'cppreference.com',
    when: 'Include it for the C-style integer limits: INT_MAX, INT_MIN, CHAR_BIT and friends. Warning: going past INT_MAX with a signed int is undefined behavior, not a neat wrap-around.',
    example: { command: '#include <climits>\nint lowest_seen = INT_MAX;', says: 'Starts lowest_seen at the largest possible int.' },
    seeAlso: ['<limits>', '<limits.h>'],
  },
  {
    name: '<list>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::list container',
    source: 'cppreference.com',
    when: 'Include it for std::list, a doubly linked list: inserting or removing in the middle is cheap and never moves the other items. Warning: it has no [] and walking it is slow next to a vector, so pick it only when you really need that.',
    example: { command: '#include <list>\nstd::list<int> waypoints{1, 2, 4};  waypoints.insert(std::next(waypoints.begin(), 2), 3);', says: 'Puts 3 between 2 and 4 without shifting anything.' },
    seeAlso: ['std::list', '<vector>'],
  },
  {
    name: '<deque>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::deque container',
    source: 'cppreference.com',
    when: 'Include it for std::deque, a double-ended queue that is fast to add to or remove from at both the front and the back. Warning: adding at either end makes old iterators stale.',
    example: { command: '#include <deque>\nwindow.push_back(x);  if (window.size() > 10) window.pop_front();', says: 'Keeps a sliding window of the last 10 readings in a std::deque called window.' },
    seeAlso: ['std::deque', '<queue>'],
  },
  {
    name: '<tuple>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::tuple class template',
    source: 'cppreference.com',
    when: 'Include it for std::tuple, a fixed group of values of different types, with std::get, std::tie and std::make_tuple. It is handy for returning several values at once. Warning: numbered fields like std::get<2> are hard to read; a small struct with named fields is often clearer.',
    example: { command: '#include <tuple>\nauto [lat, lon, alt] = std::make_tuple(28.57, -80.65, 0.0);', says: 'Unpacks three values into three named variables.' },
    seeAlso: ['std::tuple', 'std::get', 'std::tie'],
  },
  {
    name: '<cstdio>',
    lang: 'cpp',
    kind: 'header',
    official: 'C-style input-output functions',
    source: 'cppreference.com',
    when: 'Include it for C-style printing and files: std::printf, std::snprintf, std::puts, std::fopen. Warning: printf trusts its format string, and a %d given a double prints garbage, so turn on compiler warnings (-Wall) to catch mismatches.',
    example: { command: '#include <cstdio>\nstd::printf("alt %.1f km\\n", 408.0);', says: 'Prints alt 408.0 km.' },
    seeAlso: ['std::printf', 'std::snprintf', '<stdio.h>'],
  },
  {
    name: '<cstdint>',
    lang: 'cpp',
    kind: 'header',
    official: 'Fixed-width integer types and limits of other types',
    source: 'cppreference.com',
    when: 'Include it for integer types with an exact size: std::int32_t, std::uint8_t, std::uint64_t and so on. Use them when the number of bits matters, as in telemetry packets and hardware registers. Warning: std::uint8_t prints as a character with std::cout; cast it to int to see the number.',
    example: { command: '#include <cstdint>\nstd::uint16_t health_word = 0x0204;', says: 'Makes a value that is exactly 16 bits wide.' },
    seeAlso: ['std::uint8_t', 'std::int32_t', '<stdint.h>'],
  },
  {
    name: '<Eigen/Dense>',
    lang: 'cpp',
    kind: 'header',
    official: 'Includes Core, Geometry, LU, Cholesky, SVD, QR, and Eigenvalues header files',
    source: 'Eigen documentation (Quick reference guide)',
    when: 'Include it to use Eigen, the linear algebra library: vectors, matrices and solvers like LLT and JacobiSVD, all in one line. Warning: auto with an Eigen expression stores a recipe, not the answer, so give results a real type such as Eigen::Vector3d.',
    example: { command: '#include <Eigen/Dense>\nEigen::Vector3d r(7000e3, 0.0, 0.0);  double dist = r.norm();', says: 'Makes a 3D position vector and finds its length, 7000 km.' },
    seeAlso: ['Eigen::Vector3d', 'Eigen::Matrix3d', 'Eigen::MatrixXd', '<Eigen/Geometry>'],
  },
  {
    name: '<chrono>',
    lang: 'cpp',
    kind: 'header',
    official: 'C++ time utilities',
    source: 'cppreference.com',
    when: 'Include it for durations, clocks and time points: std::chrono::milliseconds, std::chrono::steady_clock and duration_cast. The units are part of the type, so mixing seconds and milliseconds converts correctly. Warning: time things with steady_clock; system_clock can jump when the computer\'s clock is adjusted.',
    example: { command: '#include <chrono>\nauto t0 = std::chrono::steady_clock::now();', says: 'Records the current time so you can measure how long something takes.' },
    seeAlso: ['std::chrono::steady_clock', 'std::chrono::duration_cast', 'std::chrono::milliseconds'],
  },
  {
    name: '<gtest/gtest.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'This header file defines the public API for Google Test.',
    source: 'GoogleTest documentation (gtest.h header comment)',
    when: 'Include it in a test file to write GoogleTest tests with TEST and TEST_F and checks like EXPECT_EQ and ASSERT_TRUE. Warning: a failing ASSERT_ check stops the current test right there, while EXPECT_ records the failure and keeps going.',
    example: { command: '#include <gtest/gtest.h>\nTEST(Orbit, PeriodIsPositive) { EXPECT_GT(period_s(7000e3), 0.0); }', says: 'Defines a test that passes if the orbital period comes out above zero.' },
    seeAlso: ['TEST', 'TEST_F', 'EXPECT_EQ', 'ASSERT_TRUE', '<gmock/gmock.h>'],
  },
  {
    name: '<thread>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::thread class and supporting functions',
    source: 'cppreference.com',
    when: 'Include it to run code at the same time on another thread with std::thread or std::jthread, and for std::this_thread::sleep_for. Warning: a std::thread that is destroyed without join() ends the whole program; std::jthread joins for you.',
    example: { command: '#include <thread>\nstd::jthread logger([] { write_log(); });', says: 'Runs write_log on a second thread and waits for it at the end of the block.' },
    seeAlso: ['std::thread', 'std::jthread', 'std::this_thread::sleep_for', '<mutex>'],
  },
  {
    name: '<atomic>',
    lang: 'cpp',
    kind: 'header',
    official: 'Atomic operations library',
    source: 'cppreference.com',
    when: 'Include it for std::atomic, a variable that several threads can read and write safely without a mutex. Warning: only each single operation is safe; a check followed by a separate write can still race (another thread can slip in between).',
    example: { command: '#include <atomic>\nstd::atomic<int> packets{0};  ++packets;', says: 'Adds one to the packet count safely, even from many threads at once.' },
    seeAlso: ['std::atomic', 'std::memory_order', '<mutex>'],
  },
  {
    name: '<new>',
    lang: 'cpp',
    kind: 'header',
    official: 'Low-level memory management utilities',
    source: 'cppreference.com',
    when: 'Include it for the low-level side of new: std::nothrow, std::bad_alloc, placement new, and std::hardware_destructive_interference_size for keeping each thread\'s data on its own cache line. Warning: new (std::nothrow) returns nullptr when memory runs out instead of throwing, so you must check it.',
    example: { command: '#include <new>\nint* buf = new (std::nothrow) int[1000];  if (!buf) enter_safe_mode();', says: 'Asks for memory and gets nullptr, not an exception, if there is none.' },
    seeAlso: ['std::nothrow', 'std::bad_alloc', 'new'],
  },
  {
    name: '<mutex>',
    lang: 'cpp',
    kind: 'header',
    official: 'Mutual exclusion primitives',
    source: 'cppreference.com',
    when: 'Include it for std::mutex, a lock that lets only one thread at a time into a piece of code, plus std::lock_guard, std::unique_lock and std::scoped_lock to take it safely. Warning: lock through a guard object; if you call lock() yourself and an exception skips unlock(), every other thread waits forever.',
    example: { command: '#include <mutex>\nstd::lock_guard<std::mutex> lock(nav_mutex);', says: 'Locks nav_mutex until the end of the current block.' },
    seeAlso: ['std::mutex', 'std::lock_guard', 'std::scoped_lock', '<shared_mutex>'],
  },
  {
    name: '<cstring>',
    lang: 'cpp',
    kind: 'header',
    official: 'Various narrow character string handling functions',
    source: 'cppreference.com',
    when: 'Include it for C-style string and memory functions: std::memcpy, std::memset, std::strcmp, std::strlen. Warning: these check no sizes; copying more bytes than the destination holds overwrites whatever comes next in memory.',
    example: { command: '#include <cstring>\nstd::memcpy(&packet, raw_bytes, sizeof packet);', says: 'Copies the raw bytes into the packet struct.' },
    seeAlso: ['std::memcpy', 'std::memset', 'std::strcmp', '<string.h>'],
  },
  {
    name: '<Eigen/Geometry>',
    lang: 'cpp',
    kind: 'header',
    official: 'Transform, Translation, Scaling, Rotation2D and 3D rotations (Quaternion, AngleAxis)',
    source: 'Eigen documentation (Quick reference guide)',
    when: 'Include it for rotations and transforms: Eigen::Quaterniond, Eigen::AngleAxisd, Eigen::Isometry3d and cross products. <Eigen/Dense> already includes it. Warning: a quaternion that is not unit length stretches as well as rotates, so normalize it.',
    example: { command: '#include <Eigen/Geometry>\nEigen::AngleAxisd turn(1.5708, Eigen::Vector3d::UnitZ());', says: 'Describes a quarter turn (about 90 degrees) around the z axis.' },
    seeAlso: ['Eigen::Quaterniond', 'Eigen::AngleAxisd', 'Eigen::Isometry3d', '<Eigen/Dense>'],
  },
  {
    name: '<stdio.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'Input/output',
    source: 'cppreference.com (C standard library headers)',
    when: 'The C version of <cstdio>: printf, fopen, puts and friends, named without std::. Use it in C code; in C++ prefer <cstdio>. Warning: printf trusts its format string, so a %d with the wrong kind of argument prints garbage.',
    example: { command: '#include <stdio.h>\nprintf("rate %d counts/s\\n", rate);', says: 'Prints the rate as a whole number.' },
    seeAlso: ['<cstdio>', 'std::printf'],
  },
  {
    name: '<stdexcept>',
    lang: 'cpp',
    kind: 'header',
    official: 'Standard exception types',
    source: 'cppreference.com',
    when: 'Include it for the ready-made exception classes you throw: std::runtime_error, std::invalid_argument, std::out_of_range. Warning: catch them by const reference (const std::exception& e), not by value, so no details get sliced off.',
    example: { command: '#include <stdexcept>\nthrow std::out_of_range("throttle above 100%");', says: 'Stops the function and hands the error to the nearest matching catch.' },
    seeAlso: ['std::runtime_error', 'std::invalid_argument', 'std::out_of_range', '<exception>'],
  },
  {
    name: '<stdint.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'Fixed-width integer types',
    source: 'cppreference.com (C standard library headers)',
    when: 'The C version of <cstdint>: int32_t, uint8_t and friends, named without std::. You see it in C code and in headers shared between C, C++ and Rust. Warning: an unsigned type never goes below zero; 0 - 1 wraps around to its largest value.',
    example: { command: '#include <stdint.h>\nuint32_t word = 0x0A0B0C0D;', says: 'Makes a value that is exactly 32 bits wide.' },
    seeAlso: ['<cstdint>'],
  },
  {
    name: '<span>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::span view',
    source: 'cppreference.com',
    when: 'Include it for std::span, a view of elements sitting in a row (in an array, a vector or a raw buffer) without copying them. It is great for function parameters. Warning: it does not own the data, so a span onto a vector that grew or was destroyed dangles.',
    example: { command: '#include <span>\nfloat mean(std::span<const float> samples);', says: 'Lets mean take an array, a vector or part of either, without copying.' },
    seeAlso: ['std::span', '<array>', '<vector>'],
  },
  {
    name: '<numbers>',
    lang: 'cpp',
    kind: 'header',
    official: 'Math constants',
    source: 'cppreference.com',
    when: 'Include it for exact math constants such as std::numbers::pi, std::numbers::e and std::numbers::sqrt2 (C++20). They replace M_PI, which is not part of standard C++.',
    example: { command: '#include <numbers>\ndouble circumference = 2 * std::numbers::pi * r;', says: 'Uses pi at full double precision.' },
    seeAlso: ['std::numbers::pi', '<cmath>'],
  },
  {
    name: '<pthread.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'threads',
    source: 'pthread.h manual page (POSIX)',
    when: 'Include it for POSIX threads, the operating system layer under std::thread on Linux. ORBIT uses it to give a thread real-time priority (pthread_setschedparam), pin it to a CPU (pthread_setaffinity_np) and set up priority-inheriting mutexes. Warning: pthread functions return an error number instead of setting errno, so check what they return.',
    example: { command: '#include <pthread.h>\npthread_setschedparam(pthread_self(), SCHED_FIFO, &sp);', says: 'Gives the current thread real-time FIFO scheduling at the priority stored in sp.' },
    seeAlso: ['<thread>', '<sched.h>'],
  },
  {
    name: '<gmock/gmock.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'Google Mock - a framework for writing C++ mock classes.',
    source: 'GoogleTest documentation (gmock.h header comment)',
    when: 'Include it to make mock objects (stand-ins for real parts, like a fake sensor) with MOCK_METHOD, and to set expectations with EXPECT_CALL. It also brings matchers such as testing::Eq and testing::DoubleNear. Warning: set EXPECT_CALL before the code under test runs; calls made before it are not counted.',
    example: { command: '#include <gmock/gmock.h>\nEXPECT_CALL(imu, read_rate()).WillOnce(testing::Return(0.01));', says: 'Makes the fake IMU return 0.01 the first time read_rate is called, and fails the test if it is never called.' },
    seeAlso: ['MOCK_METHOD', 'EXPECT_CALL', 'testing::Return', '<gtest/gtest.h>'],
  },
  {
    name: '<format>',
    lang: 'cpp',
    kind: 'header',
    official: 'Formatting library including std::format',
    source: 'cppreference.com',
    when: 'Include it for std::format, which builds text with {} placeholders, a lot like Python\'s f-strings. It is type-safe: a wrong argument is a compile error, not garbage. Warning: it needs C++20 and a recent standard library (GCC 13 or newer).',
    example: { command: '#include <format>\nstd::string s = std::format("{:.2f} km/s", 7.6612);', says: 'Makes the text 7.66 km/s.' },
    seeAlso: ['std::format', 'std::format_to_n', '<fmt/core.h>'],
  },
  {
    name: '<sched.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'execution scheduling',
    source: 'sched.h manual page (POSIX)',
    when: 'Include it to choose how the Linux scheduler treats your program: sched_setscheduler with SCHED_FIFO for real time, sched_get_priority_max, and CPU pinning with sched_setaffinity. Warning: a real-time thread that never sleeps can starve the rest of the system, and switching to one usually needs extra permission.',
    example: { command: '#include <sched.h>\nsched_param sp{};  sp.sched_priority = 80;  sched_setscheduler(0, SCHED_FIFO, &sp);', says: 'Asks for real-time FIFO scheduling at priority 80 for this program.' },
    seeAlso: ['<pthread.h>', '<sys/resource.h>'],
  },
  {
    name: '<random>',
    lang: 'cpp',
    kind: 'header',
    official: 'Random number generators and distributions',
    source: 'cppreference.com',
    when: 'Include it for good random numbers: an engine such as std::mt19937 plus a distribution such as std::normal_distribution or std::uniform_real_distribution. Warning: seed the engine with a fixed number while testing so every run gives the same numbers; std::rand is the old, weaker way.',
    example: { command: '#include <random>\nstd::mt19937 rng(42);  std::normal_distribution<double> noise(0.0, 0.1);', says: 'Sets up sensor noise from a bell curve centered on 0 with spread 0.1; noise(rng) draws one value.' },
    seeAlso: ['std::mt19937', 'std::normal_distribution', 'std::uniform_real_distribution'],
  },
  {
    name: '<sys/mman.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'memory management declarations',
    source: 'sys/mman.h manual page (POSIX)',
    when: 'Include it for mlockall, which locks the program\'s memory in RAM so it is never swapped out to disk, a standard step before a real-time loop starts. It also declares mmap. Warning: locking memory needs permission (a raised memlock limit or root) and fails without it, so check the return value.',
    example: { command: '#include <sys/mman.h>\nmlockall(MCL_CURRENT | MCL_FUTURE);', says: 'Keeps all of the program\'s memory, now and from now on, in RAM.' },
    seeAlso: ['<sched.h>', '<sys/resource.h>'],
  },
  {
    name: '<cassert>',
    lang: 'cpp',
    kind: 'header',
    official: 'Conditionally compiled macro that compares its argument to zero',
    source: 'cppreference.com',
    when: 'Include it for assert, which stops the program with a message if something you believe is always true turns out false. Warning: asserts vanish when NDEBUG is defined (usual in release builds), so never put code that must run inside one.',
    example: { command: '#include <cassert>\nassert(dt > 0.0 && "time step must be positive");', says: 'Stops with a message naming the file and line if dt is not above zero.' },
    seeAlso: ['static_assert', '<stdexcept>'],
  },
  {
    name: '<pybind11/pybind11.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'Main header file of the C++11 python binding generator library',
    source: 'pybind11 documentation (pybind11.h header comment)',
    when: 'Include it to turn C++ functions and classes into a Python module, with PYBIND11_MODULE, py::class_ and py::arg. Warning: build against the same Python you will import the module into, or the import fails.',
    example: { command: '#include <pybind11/pybind11.h>\nPYBIND11_MODULE(orbit, m) { m.def("period_s", &period_s); }', says: 'Makes a Python module named orbit with a period_s function.' },
    seeAlso: ['PYBIND11_MODULE', 'py::class_', 'py::arg', '<pybind11/numpy.h>'],
  },
  {
    name: '<bit>',
    lang: 'cpp',
    kind: 'header',
    official: 'Bit manipulation functions',
    source: 'cppreference.com',
    when: 'Include it for bit-level tools: std::bit_cast (read the same bits as another type, safely), std::byteswap, std::endian and std::popcount. Warning: std::bit_cast needs both types to be exactly the same size, or it will not compile.',
    example: { command: '#include <bit>\nauto bits = std::bit_cast<std::uint32_t>(1.0f);', says: 'Gets the raw 32 bits of the float 1.0, which are 0x3F800000.' },
    seeAlso: ['std::bit_cast', 'std::byteswap', 'std::endian::native'],
  },
  {
    name: '<ctime>',
    lang: 'cpp',
    kind: 'header',
    official: 'C-style time/date utilities',
    source: 'cppreference.com',
    when: 'Include it for C time tools such as std::time and std::timespec. On Linux it also brings the POSIX clock functions ORBIT uses to run loops on a precise schedule, clock_gettime and clock_nanosleep. Warning: CLOCK_REALTIME can jump when the system clock is set; use CLOCK_MONOTONIC to measure and schedule.',
    example: { command: '#include <ctime>\ntimespec now{};  clock_gettime(CLOCK_MONOTONIC, &now);', says: 'Reads the steady clock, the one that never jumps, into now.' },
    seeAlso: ['<chrono>', '<time.h>'],
  },
  {
    name: '<condition_variable>',
    lang: 'cpp',
    kind: 'header',
    official: 'Thread waiting conditions',
    source: 'cppreference.com',
    when: 'Include it for std::condition_variable, which lets a thread sleep until another thread says something changed (notify_one). Warning: always wait with a condition to check, because threads can wake up for no reason.',
    example: { command: '#include <condition_variable>\ncv.wait(lock, [] { return !commands.empty(); });', says: 'Sleeps until another thread adds a command, then carries on holding the lock.' },
    seeAlso: ['std::condition_variable', 'std::condition_variable_any', '<mutex>'],
  },
  {
    name: '<pybind11/numpy.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'Basic NumPy support, vectorize() wrapper',
    source: 'pybind11 documentation (numpy.h header comment)',
    when: 'Include it to pass NumPy arrays between Python and C++ with py::array_t, reading and writing the numbers without copying them. Warning: check the shape before indexing; the fast unchecked accessors let you read past the end without any error.',
    example: { command: '#include <pybind11/numpy.h>\npy::array_t<double> out({n_steps + 1, 6});', says: 'Makes a NumPy array of shape (n_steps + 1, 6) to hand back to Python.' },
    seeAlso: ['py::array_t', 'py::array', '<pybind11/pybind11.h>'],
  },
  {
    name: '<stdlib.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'General utilities: memory management, program utilities, string conversions, random numbers, algorithms',
    source: 'cppreference.com (C standard library headers)',
    when: 'The C version of <cstdlib>: malloc, free, atoi and exit, named without std::. Use it in C code. Warning: atoi gives 0 for text it cannot read, and a number too big for an int is undefined behavior.',
    example: { command: '#include <stdlib.h>\nint count = atoi(argv[1]);', says: 'Turns the first command-line argument into an int.' },
    seeAlso: ['<cstdlib>', 'std::atoi'],
  },
  {
    name: '<stddef.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'Common macro definitions',
    source: 'cppreference.com (C standard library headers)',
    when: 'The C version of <cstddef>: size_t, NULL and offsetof, named without std::. You see it in C headers and in headers shared with other languages. Warning: size_t is unsigned, so it can never hold a negative number.',
    example: { command: '#include <stddef.h>\nint32_t gnc_mean(const double *samples, size_t len, double *out);', says: 'Declares a C function that takes a count of type size_t.' },
    seeAlso: ['<cstddef>', 'std::size_t'],
  },
  {
    name: '<sys/resource.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'definitions for XSI resource operations',
    source: 'sys/resource.h manual page (POSIX)',
    when: 'Include it to read or change the limits the system puts on your program with getrlimit and setrlimit (such as RLIMIT_RTPRIO, the highest real-time priority allowed), and to measure its use with getrusage, for example page faults. Warning: a normal user can lower a limit but cannot raise it past the hard limit.',
    example: { command: '#include <sys/resource.h>\nrusage u{};  getrusage(RUSAGE_SELF, &u);  long faults = u.ru_minflt;', says: 'Reads how many minor page faults the program has had so far.' },
    seeAlso: ['<sched.h>', '<sys/mman.h>'],
  },
  {
    name: '<future>',
    lang: 'cpp',
    kind: 'header',
    official: 'Primitives for asynchronous computations',
    source: 'cppreference.com',
    when: 'Include it for std::async, std::future, std::promise and std::packaged_task: start work now and collect its result, or its exception, later with get(). Warning: get() waits until the answer is ready and works only once, and a future from std::async waits for the work when it is destroyed.',
    example: { command: '#include <future>\nauto f = std::async(std::launch::async, compute_orbit);  double p = f.get();', says: 'Runs compute_orbit on another thread and then waits for its answer.' },
    seeAlso: ['std::async', 'std::future', 'std::promise'],
  },
  {
    name: '<charconv>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::to_chars and std::from_chars',
    source: 'cppreference.com',
    when: 'Include it for the fastest, strictest conversions between numbers and text: std::from_chars reads a number and reports exactly what went wrong, with no exceptions. Warning: it does not skip leading spaces or a leading +, so trim the text first.',
    example: { command: '#include <charconv>\nauto [ptr, ec] = std::from_chars(s.data(), s.data() + s.size(), value);', says: 'Reads an int from s into value; ec says whether it worked.' },
    seeAlso: ['std::from_chars', 'std::errc', '<system_error>'],
  },
  {
    name: '<filesystem>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::filesystem::path class and supporting functions',
    source: 'cppreference.com',
    when: 'Include it to work with files and folders: std::filesystem::path, exists, create_directories, file_size and remove_all, usually shortened with namespace fs = std::filesystem;. Warning: most functions throw on error unless you pass a std::error_code to fill in, and remove_all deletes without asking.',
    example: { command: '#include <filesystem>\nstd::filesystem::create_directories("logs/flight_07");', says: 'Makes logs, and flight_07 inside it, if they do not exist yet.' },
    seeAlso: ['std::filesystem', 'std::filesystem::file_size', '<fstream>'],
  },
  {
    name: '<expected>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::expected class template',
    source: 'cppreference.com',
    when: 'Include it for std::expected (C++23), a return value that holds either the answer or an error, so failure is part of the type instead of an exception. Warning: reading *result when it holds an error is undefined behavior, so check it first.',
    example: { command: '#include <expected>\nstd::expected<double, CmdError> t = parse_throttle("THROTTLE 0.72");', says: 't holds 0.72, or a CmdError saying what was wrong with the command.' },
    seeAlso: ['std::expected', 'std::unexpected', '<optional>'],
  },
  {
    name: '<pybind11/eigen.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'Transparent conversion for dense and sparse Eigen matrices',
    source: 'pybind11 documentation (eigen.h header comment)',
    when: 'Include it so Eigen vectors and matrices turn into NumPy arrays, and back, automatically when they cross into Python. Warning: passing by value or const reference copies the data; to change a NumPy array in place, take an Eigen::Ref with a matching memory layout.',
    example: { command: '#include <pybind11/eigen.h>\nm.def("rk4_step", &rk4_step);', says: 'Lets Python call rk4_step with a NumPy array and get a NumPy array back.' },
    seeAlso: ['Eigen::Ref', '<pybind11/pybind11.h>', '<Eigen/Dense>'],
  },
  {
    name: '<compare>',
    lang: 'cpp',
    kind: 'header',
    official: 'Three-way comparison operator support',
    source: 'cppreference.com',
    when: 'Include it for the spaceship operator <=> (C++20) and its result types like std::strong_ordering. Writing auto operator<=>(const T&) const = default; makes the compiler write all the comparisons for you. Warning: the default version compares members in the order they are declared.',
    example: { command: '#include <compare>\nauto operator<=>(const Waypoint&) const = default;', says: 'Makes Waypoints comparable with <, >, <= and >=, latitude first, then longitude.' },
    seeAlso: ['operator', '<set>'],
  },
  {
    name: '<cerrno>',
    lang: 'cpp',
    kind: 'header',
    official: 'Macro containing the last error number',
    source: 'cppreference.com',
    when: 'Include it for errno, the number many C and system functions set when they fail, and codes such as EPERM and EINVAL. Warning: errno only means something right after a call that reported failure; the next call can overwrite it.',
    example: { command: '#include <cerrno>\nif (sched_setscheduler(0, SCHED_FIFO, &sp) == -1) std::printf("%s\\n", std::strerror(errno));', says: 'Prints why the call failed, such as Operation not permitted.' },
    seeAlso: ['std::strerror', 'std::perror'],
  },
  {
    name: '<stop_token>',
    lang: 'cpp',
    kind: 'header',
    official: 'Stop tokens for std::jthread',
    source: 'cppreference.com',
    when: 'Include it for std::stop_token, which lets a std::jthread be asked politely to finish (request_stop) and lets the thread check stop_requested(). Warning: nothing is forced; the thread must look at its token and return on its own.',
    example: { command: '#include <stop_token>\nstd::jthread worker([](std::stop_token st) { while (!st.stop_requested()) poll_sensors(); });', says: 'Polls the sensors until the worker is asked to stop.' },
    seeAlso: ['std::stop_token', 'std::jthread', '<thread>'],
  },
  {
    name: '<csignal>',
    lang: 'cpp',
    kind: 'header',
    official: 'Functions and macro constants for signal management',
    source: 'cppreference.com',
    when: 'Include it to handle signals, messages the operating system sends a program such as SIGINT (Ctrl+C), SIGALRM (a timer) or SIGABRT, with std::signal, and std::sig_atomic_t for a flag the handler may set. Warning: a signal handler can do almost nothing safely; set a flag and return.',
    example: { command: '#include <csignal>\nstd::signal(SIGINT, [](int) { g_stop = 1; });', says: 'Sets g_stop when you press Ctrl+C, instead of killing the program.' },
    seeAlso: ['<sys/time.h>', '<atomic>'],
  },
  {
    name: '<time.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'Time/date utilities',
    source: 'cppreference.com (C standard library headers)',
    when: 'The C version of <ctime>. On Linux it also declares the POSIX clock functions ORBIT uses for real-time loops: clock_gettime and clock_nanosleep with CLOCK_MONOTONIC. Warning: sleep until an absolute deadline (TIMER_ABSTIME), not for a fixed amount, or small delays pile up and the loop drifts.',
    example: { command: '#include <time.h>\nclock_nanosleep(CLOCK_MONOTONIC, TIMER_ABSTIME, &next, nullptr);', says: 'Sleeps until the exact deadline stored in next.' },
    seeAlso: ['<ctime>', '<chrono>'],
  },
  {
    name: '<memory_resource>',
    lang: 'cpp',
    kind: 'header',
    official: 'Polymorphic allocators and memory resources',
    source: 'cppreference.com',
    when: 'Include it for std::pmr, containers that take memory from a source you choose, such as std::pmr::monotonic_buffer_resource over a fixed buffer, so a real-time loop never touches the general heap. Warning: a monotonic resource gives nothing back until it is destroyed, and the buffer must outlive every container that uses it.',
    example: { command: '#include <memory_resource>\nstd::pmr::monotonic_buffer_resource arena(buf, sizeof buf);  std::pmr::vector<int> ids(&arena);', says: 'Makes a vector that takes its memory from the buffer buf.' },
    seeAlso: ['std::pmr::monotonic_buffer_resource', 'std::pmr::vector', '<memory>'],
  },
  {
    name: '<fstream>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::basic_fstream, std::basic_ifstream, std::basic_ofstream class templates and typedefs',
    source: 'cppreference.com',
    when: 'Include it to read and write files with streams: std::ifstream to read, std::ofstream to write. The file closes by itself when the stream object goes away. Warning: opening a file that is not there fails quietly, so check if (!in) before reading.',
    example: { command: '#include <fstream>\nstd::ofstream log("alt.log", std::ios::app);  log << 408.2 << "\\n";', says: 'Adds a line with 408.2 to the end of alt.log.' },
    seeAlso: ['std::ifstream', 'std::ofstream', 'std::getline', '<filesystem>'],
  },
  {
    name: '<coroutine>',
    lang: 'cpp',
    kind: 'header',
    official: 'Coroutine support library',
    source: 'cppreference.com',
    when: 'Include it when you write coroutines (C++20 functions that can pause with co_yield or co_await and pick up later): it gives std::coroutine_handle, std::suspend_always and std::suspend_never. Warning: it only supplies the low-level parts; you write the promise_type yourself, and forgetting to destroy the handle leaks memory.',
    example: { command: '#include <coroutine>\nstd::suspend_always yield_value(int v) noexcept { current = v; return {}; }', says: 'Makes the coroutine pause each time it yields a value.' },
    seeAlso: ['std::coroutine_handle', 'std::suspend_always', 'co_yield'],
  },
  {
    name: '<exception>',
    lang: 'cpp',
    kind: 'header',
    official: 'Exception handling utilities',
    source: 'cppreference.com',
    when: 'Include it for std::exception (the base class of the standard exceptions), std::current_exception, std::exception_ptr and std::terminate. Warning: an exception that escapes a noexcept function calls std::terminate and ends the program.',
    example: { command: '#include <exception>\ntry { run(); } catch (const std::exception& e) { std::puts(e.what()); }', says: 'Catches any standard exception from run and prints its message.' },
    seeAlso: ['std::exception', 'std::current_exception', 'std::terminate', '<stdexcept>'],
  },
  {
    name: '<system_error>',
    lang: 'cpp',
    kind: 'header',
    official: 'Defines std::error_code, a platform-dependent error code',
    source: 'cppreference.com',
    when: 'Include it for std::error_code and std::errc, a way to report errors as values instead of exceptions, used by <filesystem> and <charconv>. Warning: an error_code counts as true when there IS an error, so if (ec) means something went wrong.',
    example: { command: '#include <system_error>\nstd::error_code ec = std::make_error_code(std::errc::invalid_argument);', says: 'Makes an error value; ec.message() says Invalid argument.' },
    seeAlso: ['std::error_code', 'std::errc', 'std::make_error_code'],
  },
  {
    name: '<execution>',
    lang: 'cpp',
    kind: 'header',
    official: 'Predefined execution policies for parallel versions of the algorithms',
    source: 'cppreference.com',
    when: 'Include it for execution policies such as std::execution::par and std::execution::par_unseq, which let algorithms like std::sort and std::reduce use several cores. Warning: with GCC it needs the TBB library linked (-ltbb) to really run in parallel, and the function you pass must not change shared data.',
    example: { command: '#include <execution>\nstd::sort(std::execution::par, v.begin(), v.end());', says: 'Sorts v using several threads at once.' },
    seeAlso: ['std::execution::par', 'std::execution::par_unseq', 'std::reduce', '<algorithm>'],
  },
  {
    name: '<bitset>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::bitset class template',
    source: 'cppreference.com',
    when: 'Include it for std::bitset<N>, a fixed row of N on/off bits with set, reset, test, count and to_string, handy for fault flags in a health word. Warning: bit 0 is the rightmost character when printed with to_string.',
    example: { command: '#include <bitset>\nstd::bitset<16> health;  health.set(2);', says: 'Turns on bit 2 (GPS has no fix) in a 16-bit health word.' },
    seeAlso: ['std::bitset', '<bit>'],
  },
  {
    name: '<cinttypes>',
    lang: 'cpp',
    kind: 'header',
    official: 'Formatting macros, intmax_t and uintmax_t math and conversions',
    source: 'cppreference.com',
    when: 'Include it for the printf macros that match the fixed-width types, such as PRId64 and PRIu32, so a std::int64_t prints correctly on every system. Warning: the macro goes outside the quotes, as in "%" PRId64.',
    example: { command: '#include <cinttypes>\nstd::printf("t = %" PRId64 " ns\\n", t_ns);', says: 'Prints a 64-bit time stamp correctly on any system.' },
    seeAlso: ['<cstdint>', 'std::printf'],
  },
  {
    name: '<limits.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'Ranges of integer types',
    source: 'cppreference.com (C standard library headers)',
    when: 'The C version of <climits>: INT_MAX, CHAR_BIT and friends. You see it in C code. Sizes like int and long differ between systems, and these macros tell you what this one uses.',
    example: { command: '#include <limits.h>\nprintf("int is %zu bits\\n", sizeof(int) * CHAR_BIT);', says: 'Prints how many bits an int has on this computer, usually 32.' },
    seeAlso: ['<climits>', '<limits>'],
  },
  {
    name: '<string.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'String handling',
    source: 'cppreference.com (C standard library headers)',
    when: 'The C version of <cstring>: memcpy, memset, strlen and strcmp, named without std::. Warning: nothing checks sizes, so copying past the end of a buffer silently corrupts memory.',
    example: { command: '#include <string.h>\nmemcpy(bytes, &word, sizeof word);', says: 'Copies the four raw bytes of word into the bytes array.' },
    seeAlso: ['<cstring>', 'std::memcpy'],
  },
  {
    name: '<stdarg.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'Variable arguments',
    source: 'cppreference.com (C standard library headers)',
    when: 'In C it gives va_list, va_start, va_arg and va_end for writing functions like printf that take any number of arguments. In ORBIT it appears at the top of a C header generated so Rust and C++ can share code. Warning: nothing checks the types; va_arg must be told the right type for each argument.',
    example: { command: '#include <stdarg.h>\nvoid log_msg(const char *fmt, ...) { va_list ap; va_start(ap, fmt); vprintf(fmt, ap); va_end(ap); }', says: 'Writes a logging function that takes a format and any number of values, like printf.' },
    seeAlso: ['<cstdio>'],
  },
  {
    name: '<stdbool.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'Macros for boolean type',
    source: 'cppreference.com (C standard library headers)',
    when: 'In C before C23, it defines bool, true and false so C code can use them. C++ has bool built in, so it only matters in C headers shared with C++ or Rust.',
    example: { command: '#include <stdbool.h>\nbool gnc_is_saturated(double x, double lo, double hi);', says: 'Declares a C function that returns true or false.' },
    seeAlso: ['bool', 'true', 'false'],
  },
  {
    name: '<malloc.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'Prototypes and definition for malloc implementation.',
    source: 'GNU C Library (malloc.h header comment)',
    when: 'A Linux (glibc) header, not standard C or C++, with extras about the heap such as mallinfo2. ORBIT uses mallinfo2 to prove a real-time loop does no heap allocation. Warning: it is Linux-only, so code that uses it will not build on macOS or Windows.',
    example: { command: '#include <malloc.h>\nstd::size_t in_use = mallinfo2().uordblks;', says: 'Reads how many bytes the heap has currently handed out to the program.' },
    seeAlso: ['std::malloc', 'std::free', '<cstdlib>'],
  },
  {
    name: '<unsupported/Eigen/AutoDiff>',
    lang: 'cpp',
    kind: 'header',
    official: 'This module features forward automatic differentation via a simple templated scalar type wrapper AutoDiffScalar.',
    source: 'Eigen documentation (AutoDiff module)',
    when: 'Include it for Eigen::AutoDiffScalar, a number type that carries its derivatives along with its value, so one function gives you both the answer and its exact gradient (automatic differentiation). Warning: "unsupported" means it sits outside Eigen\'s official modules and can change between versions.',
    example: { command: '#include <unsupported/Eigen/AutoDiff>\nusing AD = Eigen::AutoDiffScalar<Eigen::Vector3d>;', says: 'Defines a number type that tracks derivatives with respect to three inputs.' },
    seeAlso: ['Eigen::AutoDiffScalar', '<Eigen/Dense>'],
  },
  {
    name: '<cxxabi.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'The header provides an interface to the C++ ABI.',
    source: 'libstdc++ documentation',
    when: 'A GCC and Clang header, not standard C++. ORBIT uses its abi::__cxa_demangle to turn the scrambled type names from typeid into readable C++. Warning: the name it returns was made with malloc, so you must std::free it.',
    example: { command: '#include <cxxabi.h>\nchar* name = abi::__cxa_demangle(typeid(x).name(), nullptr, nullptr, &status);', says: 'Gets a readable name for the type of x, such as Eigen::Matrix<double, 3, 1, 0, 3, 1>.' },
    seeAlso: ['<typeinfo>', 'typeid', 'std::free'],
  },
  {
    name: '<typeinfo>',
    lang: 'cpp',
    kind: 'header',
    official: 'Runtime type information utilities',
    source: 'cppreference.com',
    when: 'Include it before using typeid, which gives a std::type_info describing a type, and for std::bad_cast. Warning: name() returns a compiler-specific, often scrambled string, not the name you wrote.',
    example: { command: '#include <typeinfo>\nstd::cout << typeid(3.0).name();', says: 'Prints the compiler\'s name for double; with GCC that is just d.' },
    seeAlso: ['typeid', '<cxxabi.h>'],
  },
  {
    name: '<shared_mutex>',
    lang: 'cpp',
    kind: 'header',
    official: 'Shared mutual exclusion primitives',
    source: 'cppreference.com',
    when: 'Include it for std::shared_mutex, a lock that lets many readers in together (std::shared_lock) but only one writer at a time (std::unique_lock). Warning: it costs more than a plain mutex, so it pays off only when reads are long and common.',
    example: { command: '#include <shared_mutex>\nstd::shared_lock<std::shared_mutex> lock(g_nav_mutex);', says: 'Takes a read lock; other readers can hold it at the same time.' },
    seeAlso: ['std::shared_mutex', 'std::shared_lock', '<mutex>'],
  },
  {
    name: '<barrier>',
    lang: 'cpp',
    kind: 'header',
    official: 'Barriers',
    source: 'cppreference.com',
    when: 'Include it for std::barrier (C++20), a meeting point: each thread calls arrive_and_wait() and none goes on until all have arrived. It can be reused round after round. Warning: if one thread never arrives, all the others wait forever.',
    example: { command: '#include <barrier>\nstd::barrier sync(2);  sync.arrive_and_wait();', says: 'Waits at this line until both threads have reached it.' },
    seeAlso: ['std::barrier', '<thread>'],
  },
  {
    name: '<sys/wait.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'declarations for waiting',
    source: 'sys/wait.h manual page (POSIX)',
    when: 'Include it for waitpid and wait, which let a parent process wait for a child process (made with fork) to finish and find out how it ended. Warning: a finished child that nobody waits for stays around as a "zombie" process.',
    example: { command: '#include <sys/wait.h>\nwaitpid(pid, nullptr, 0);', says: 'Waits until the child process pid has finished.' },
    seeAlso: ['<unistd.h>'],
  },
  {
    name: '<unistd.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'standard symbolic constants and types',
    source: 'unistd.h manual page (POSIX)',
    when: 'Include it for basic POSIX system calls: fork, getpid, sleep, read, write and close. Warning: fork copies the whole program, so the child gets its own copy of every variable, and changes in one never show up in the other.',
    example: { command: '#include <unistd.h>\npid_t pid = fork();', says: 'Splits the program into two processes; pid is 0 in the child.' },
    seeAlso: ['<sys/wait.h>'],
  },
  {
    name: '<sys/time.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'time types',
    source: 'sys/time.h manual page (POSIX)',
    when: 'Include it for struct timeval, gettimeofday and interval timers (setitimer). ORBIT uses setitimer to fake a hardware interrupt with a signal that repeats. Warning: gettimeofday follows the wall clock, which can jump; to measure time use clock_gettime(CLOCK_MONOTONIC) or std::chrono::steady_clock.',
    example: { command: '#include <sys/time.h>\nitimerval every_5ms{{0, 5000}, {0, 5000}};  setitimer(ITIMER_REAL, &every_5ms, nullptr);', says: 'Sends the program SIGALRM every 5 milliseconds, like a timer interrupt.' },
    seeAlso: ['<csignal>', '<time.h>'],
  },
  {
    name: '<source_location>',
    lang: 'cpp',
    kind: 'header',
    official: 'Supplies means to obtain source code location',
    source: 'cppreference.com',
    when: 'Include it for std::source_location (C++20), which records the file, line and function where it was made, so logging and check functions can report where they were called without macros. Warning: to get the caller\'s line, make it a default argument set to std::source_location::current().',
    example: { command: '#include <source_location>\nbool check(bool ok, std::source_location where = std::source_location::current());', says: 'Each failed check can report the line it was called from with where.line().' },
    seeAlso: ['std::source_location', 'std::source_location::current'],
  },
  {
    name: '<fmt/core.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'the core API providing main formatting functions for char/UTF-8 with C++20 compile-time checks and minimal dependencies',
    source: 'fmt documentation (API reference)',
    when: 'Include it to use the {fmt} library, which std::format grew out of, with fmt::print and fmt::format. It works even where <format> is missing. Warning: it is not part of the standard library, so the build must find and link it, for example with CMake FetchContent and fmt::fmt.',
    example: { command: '#include <fmt/core.h>\nfmt::print("ISS: {:.0f} km up\\n", 408.0);', says: 'Prints ISS: 408 km up.' },
    seeAlso: ['<format>', 'std::format'],
  },
  {
    name: '<mdspan>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::mdspan view',
    source: 'cppreference.com',
    when: 'Include it for std::mdspan (C++23), a view that treats a flat run of numbers as a grid with rows and columns, so you can write m[i, j]. It neither owns nor copies the data. Warning: it is new; GCC only added it in version 14, so older compilers do not have it.',
    example: { command: '#include <mdspan>\nstd::mdspan<double, std::extents<std::size_t, 3, 3>> m(buffer.data());', says: 'Views the 9 numbers in buffer as a 3 by 3 matrix.' },
    seeAlso: ['std::mdspan', 'std::extents', '<span>'],
  },
]
