import type { CommandRef } from './types'

export const COMMANDS: CommandRef[] = [
  // ---------------------------------------------------------------- GoogleTest assertions
  {
    name: 'EXPECT_TRUE',
    lang: 'cpp',
    kind: 'macro',
    official: 'Verifies that condition is true.',
    source: 'GoogleTest documentation',
    when: 'A test needs to check a yes-or-no fact, such as "the buffer is full" or "the reading is valid". If it fails, the test is marked failed but keeps running, so you see every problem in one run.',
    flags: [['<<', 'add your own message after it, printed only when the check fails']],
    example: { command: 'EXPECT_TRUE(buffer.full()) << "ring buffer should be full after 8 pushes";', says: 'Passes if full() returns true; otherwise records a failure with your message and carries on.' },
    seeAlso: ['EXPECT_FALSE', 'ASSERT_TRUE', 'TEST'],
  },
  {
    name: 'EXPECT_FALSE',
    lang: 'cpp',
    kind: 'macro',
    official: 'Verifies that condition is false.',
    source: 'GoogleTest documentation',
    when: 'A test needs to check that something is not true, such as "no fault flag is set". Like every EXPECT_ check, a failure is recorded and the test goes on.',
    example: { command: 'EXPECT_FALSE(monitor.sensor_fault());', says: 'Passes if sensor_fault() returns false; if it returns true, the test is marked failed and continues.' },
    seeAlso: ['EXPECT_TRUE', 'ASSERT_FALSE'],
  },
  {
    name: 'ASSERT_TRUE',
    lang: 'cpp',
    kind: 'macro',
    official: 'Verifies that condition is true.',
    source: 'GoogleTest documentation',
    when: 'The rest of the test only makes sense if this is true, for example a table or file loaded. On failure it stops the test function at once. It works by doing a hidden return, so it only compiles inside functions that return void.',
    flags: [['<<', 'add your own message, printed only when the check fails']],
    example: { command: 'ASSERT_TRUE(load_table("gains.csv", table)) << "table not loaded";', says: 'If loading fails, the test stops here with your message instead of crashing on the missing table later.' },
    seeAlso: ['EXPECT_TRUE', 'ASSERT_FALSE', 'ASSERT_NO_FATAL_FAILURE'],
  },
  {
    name: 'ASSERT_FALSE',
    lang: 'cpp',
    kind: 'macro',
    official: 'Verifies that condition is false.',
    source: 'GoogleTest documentation',
    when: 'Going on would be pointless or unsafe unless this is false, such as "the input text is not empty". On failure it ends the test function right away.',
    example: { command: 'ASSERT_FALSE(text.empty());', says: 'Stops the test if text is empty, so the lines after it never read a missing value.' },
    seeAlso: ['ASSERT_TRUE', 'EXPECT_FALSE'],
  },
  {
    name: 'EXPECT_EQ',
    lang: 'cpp',
    kind: 'macro',
    official: 'Verifies that val1==val2.',
    source: 'GoogleTest documentation',
    when: 'You want to check that two whole numbers, strings or other exactly comparable values are equal. Do not use it for double results of arithmetic: tiny rounding differences make it fail, so use EXPECT_NEAR or EXPECT_DOUBLE_EQ instead. On two C strings (char pointers) it compares addresses, not the text.',
    flags: [
      ['val1, val2', 'the two values; the failure message prints both'],
      ['<<', 'add your own message, printed only when the check fails'],
    ],
    example: { command: 'EXPECT_EQ(countdown.remaining(), 10);', says: 'Passes if remaining() is exactly 10; otherwise prints both values and continues.' },
    seeAlso: ['EXPECT_NE', 'ASSERT_EQ', 'EXPECT_NEAR', 'EXPECT_DOUBLE_EQ'],
  },
  {
    name: 'ASSERT_EQ',
    lang: 'cpp',
    kind: 'macro',
    official: 'Verifies that val1==val2.',
    source: 'GoogleTest documentation',
    when: 'Two values must be equal before the rest of the test can safely run, such as a vector having the size you are about to index into. On failure the test function stops at once.',
    example: { command: 'ASSERT_EQ(samples.size(), 4u);', says: 'Stops the test if there are not exactly 4 samples, so samples[3] below is never read out of range.' },
    seeAlso: ['EXPECT_EQ', 'ASSERT_NE'],
  },
  {
    name: 'EXPECT_NE',
    lang: 'cpp',
    kind: 'macro',
    official: 'Verifies that val1!=val2.',
    source: 'GoogleTest documentation',
    when: 'You want to check that two values differ, such as two sensors getting different IDs. A failure is recorded and the test continues.',
    example: { command: 'EXPECT_NE(baro.id(), gyro.id());', says: 'Passes if the two IDs are different.' },
    seeAlso: ['EXPECT_EQ', 'ASSERT_NE'],
  },
  {
    name: 'ASSERT_NE',
    lang: 'cpp',
    kind: 'macro',
    official: 'Verifies that val1!=val2.',
    source: 'GoogleTest documentation',
    when: 'Most often used to check that a pointer is not null before the test uses it. If the check fails, the test stops instead of crashing the whole test program on the null pointer.',
    flags: [['<<', 'add your own message, printed only when the check fails']],
    example: { command: 'ASSERT_NE(table, nullptr) << "table not loaded";', says: 'Stops the test with your message if table is null; otherwise the test goes on.' },
    seeAlso: ['EXPECT_NE', 'ASSERT_TRUE'],
  },
  {
    name: 'EXPECT_LT',
    lang: 'cpp',
    kind: 'macro',
    official: 'Verifies that val1<val2.',
    source: 'GoogleTest documentation',
    when: 'You want to check that one value is strictly less than another, such as speed falling as the orbit gets higher. A failure prints both values and the test continues.',
    example: { command: 'EXPECT_LT(circular_speed(r_high), circular_speed(r_low));', says: 'Passes if the higher orbit is slower.' },
    seeAlso: ['EXPECT_LE', 'EXPECT_GT'],
  },
  {
    name: 'EXPECT_LE',
    lang: 'cpp',
    kind: 'macro',
    official: 'Verifies that val1<=val2.',
    source: 'GoogleTest documentation',
    when: 'You want to check that a value stays at or below a limit, such as a loop time staying within its budget. A failure is recorded and the test continues.',
    example: { command: 'EXPECT_LE(step_time_us, 1000);', says: 'Passes if the step took 1000 microseconds or less.' },
    seeAlso: ['EXPECT_LT', 'EXPECT_GE'],
  },
  {
    name: 'EXPECT_GT',
    lang: 'cpp',
    kind: 'macro',
    official: 'Verifies that val1>val2.',
    source: 'GoogleTest documentation',
    when: 'You want to check that one value is strictly greater than another, such as a table entry being positive. A failure prints both values and the test continues.',
    example: { command: 'EXPECT_GT(period(r_high), period(r_low));', says: 'Passes if the higher orbit takes longer to go around.' },
    seeAlso: ['EXPECT_GE', 'EXPECT_LT', 'ASSERT_GT'],
  },
  {
    name: 'ASSERT_GT',
    lang: 'cpp',
    kind: 'macro',
    official: 'Verifies that val1>val2.',
    source: 'GoogleTest documentation',
    when: 'A later check only means something if one value is bigger than another, such as a fixture promising its radii increase. On failure the test function stops at once.',
    flags: [['<<', 'add your own message, printed only when the check fails']],
    example: { command: 'ASSERT_GT(radii_m[i], radii_m[i - 1]) << "fixture radii must increase";', says: 'Stops the test if the radii are not in increasing order.' },
    seeAlso: ['EXPECT_GT'],
  },
  {
    name: 'EXPECT_GE',
    lang: 'cpp',
    kind: 'macro',
    official: 'Verifies that val1>=val2.',
    source: 'GoogleTest documentation',
    when: 'You want to check that a value is at least some minimum, such as a sensor rate being 10 Hz or more. A failure is recorded and the test continues.',
    flags: [['<<', 'add your own message, such as which row failed']],
    example: { command: 'EXPECT_GE(s.rate_hz, 10.0) << "row " << i;', says: 'Passes if the rate is 10 Hz or more; otherwise names the row that failed.' },
    seeAlso: ['EXPECT_GT', 'EXPECT_LE'],
  },
  {
    name: 'EXPECT_NEAR',
    lang: 'cpp',
    kind: 'macro',
    official: 'Verifies that the difference between val1 and val2 does not exceed the absolute error bound abs_error.',
    source: 'GoogleTest documentation',
    when: 'You are checking a decimal result and you know how close is close enough, such as a speed within 0.1 m/s. You choose the tolerance; too small and rounding makes the test fail, too large and it lets real bugs through.',
    flags: [
      ['val1, val2', 'the value you got and the value you expected'],
      ['abs_error', 'the largest difference you will accept, in the same units'],
    ],
    example: { command: 'EXPECT_NEAR(circular_speed(kLeoRadius), 7668.6, 0.1);', says: 'Passes if the speed is within 0.1 of 7668.6 m/s.' },
    seeAlso: ['EXPECT_DOUBLE_EQ', 'EXPECT_FLOAT_EQ'],
  },
  {
    name: 'EXPECT_DOUBLE_EQ',
    lang: 'cpp',
    kind: 'macro',
    official: 'Verifies that the two double values val1 and val2 are approximately equal, to within 4 ULPs from each other.',
    source: 'GoogleTest documentation',
    when: 'Two doubles should be the same number, just reached by slightly different roundings. The allowed gap (4 ULPs, the four smallest steps a double can take at that size) scales with the numbers. Never use it to compare against 0.0: near zero the steps are so tiny it acts like exact equality, so use EXPECT_NEAR there.',
    example: { command: 'EXPECT_DOUBLE_EQ(0.1 + 0.2, 0.3);', says: 'Passes, even though 0.1 + 0.2 == 0.3 is false in C++, because the two differ by only one ULP.' },
    seeAlso: ['ASSERT_DOUBLE_EQ', 'EXPECT_FLOAT_EQ', 'EXPECT_NEAR'],
  },
  {
    name: 'ASSERT_DOUBLE_EQ',
    lang: 'cpp',
    kind: 'macro',
    official: 'Verifies that the two double values val1 and val2 are approximately equal, to within 4 ULPs from each other.',
    source: 'GoogleTest documentation',
    when: 'The same check as EXPECT_DOUBLE_EQ, but a failure ends the test function. Inside a loop over many cases that means you only hear about the first bad case, so prefer EXPECT_DOUBLE_EQ unless going on is unsafe.',
    example: { command: 'ASSERT_DOUBLE_EQ(wrap_deg(r.in), r.want);', says: 'Stops the test at the first row whose wrapped angle does not match.' },
    seeAlso: ['EXPECT_DOUBLE_EQ'],
  },
  {
    name: 'EXPECT_FLOAT_EQ',
    lang: 'cpp',
    kind: 'macro',
    official: 'Verifies that the two float values val1 and val2 are approximately equal, to within 4 ULPs from each other.',
    source: 'GoogleTest documentation',
    when: 'The float version of EXPECT_DOUBLE_EQ, for code that works in float, such as a small controller on a microcontroller. As with the double version, do not use it against zero.',
    example: { command: 'EXPECT_FLOAT_EQ(pid.update(1.0f, 0.01f), 0.35f);', says: 'Passes if the controller output is 0.35 to within float rounding.' },
    seeAlso: ['EXPECT_DOUBLE_EQ', 'EXPECT_NEAR'],
  },
  {
    name: 'ASSERT_NO_FATAL_FAILURE',
    lang: 'cpp',
    kind: 'macro',
    official: "statement doesn't generate any new fatal failures in the current thread.",
    source: 'GoogleTest documentation',
    when: 'You call a helper function that contains ASSERT_ checks. An ASSERT_ inside a helper only returns from the helper, so the test would carry on; wrapping the call makes the test stop too.',
    example: { command: 'ASSERT_NO_FATAL_FAILURE(load_sensor("baro", baro));', says: 'Runs the helper, and if an ASSERT_ inside it failed, stops this test as well.' },
    seeAlso: ['ASSERT_TRUE', 'TEST'],
  },
  {
    name: 'EXPECT_DEATH',
    lang: 'cpp',
    kind: 'macro',
    official: 'Verifies that statement causes the process to terminate with a nonzero exit status and produces stderr output that matches matcher.',
    source: 'GoogleTest documentation',
    when: 'You want to prove that code crashes on purpose when misused, such as a contract check firing on a bad index. It runs the code in a separate child process. The pattern is matched against standard error only, so a message printed to std::cout never matches.',
    flags: [
      ['statement', 'the code that should make the process die'],
      ['regex', 'a pattern the error output must contain'],
    ],
    example: { command: 'EXPECT_DEATH(gain_at(kGains, 3, 3), "contract violated: i < n");', says: 'Passes if the call aborts and its error output contains that message.' },
    seeAlso: ['EXPECT_EXIT'],
  },
  {
    name: 'EXPECT_EXIT',
    lang: 'cpp',
    kind: 'macro',
    official: 'Verifies that statement causes the process to terminate with an exit status that satisfies predicate, and produces stderr output that matches matcher.',
    source: 'GoogleTest documentation',
    when: 'Like EXPECT_DEATH, but you also say exactly how the process must end: a normal exit with a given code, or a given signal. Use it when the way it stops matters, such as safe mode exiting with code 42 so a supervisor can react.',
    flags: [
      ['statement', 'the code that should end the process'],
      ['predicate', 'how it must end: testing::ExitedWithCode(n) or testing::KilledBySignal(sig)'],
      ['regex', 'a pattern the error output must contain'],
    ],
    example: {
      command: 'EXPECT_EXIT(enter_safe_mode("sun sensor lost"), ::testing::ExitedWithCode(42), "SAFE MODE: sun sensor lost");',
      says: 'Passes only if the process exits normally with code 42 and prints that message to standard error.',
    },
    seeAlso: ['EXPECT_DEATH', 'testing::ExitedWithCode', 'testing::KilledBySignal'],
  },
  {
    name: 'testing::ExitedWithCode',
    aliases: ['::testing::ExitedWithCode', 'ExitedWithCode'],
    lang: 'cpp',
    kind: 'function',
    official: 'Returns true if the program exited normally with the given exit status code.',
    source: 'GoogleTest documentation',
    when: 'Inside EXPECT_EXIT, to require that the code finished by calling exit with one exact code. A crash or a different code fails the check.',
    example: { command: 'EXPECT_EXIT(shutdown(), ::testing::ExitedWithCode(0), "");', says: 'Passes if shutdown() ends the process with exit code 0.' },
    seeAlso: ['EXPECT_EXIT', 'testing::KilledBySignal'],
  },
  {
    name: 'testing::KilledBySignal',
    aliases: ['::testing::KilledBySignal', 'KilledBySignal'],
    lang: 'cpp',
    kind: 'function',
    official: 'Returns true if the program was killed by the given signal.',
    source: 'GoogleTest documentation',
    when: 'Inside EXPECT_EXIT, to require that the code died from a particular signal, such as SIGABRT from a failed assert. It is not available on Windows.',
    example: { command: 'EXPECT_EXIT(gain_at(kGains, 3, 7), ::testing::KilledBySignal(SIGABRT), "i < n");', says: 'Passes if the call aborts with SIGABRT and prints a message containing i < n.' },
    seeAlso: ['EXPECT_EXIT', 'testing::ExitedWithCode'],
  },
  // ---------------------------------------------------------------- GoogleTest tests and fixtures
  {
    name: 'TEST',
    lang: 'cpp',
    kind: 'macro',
    official: 'Defines an individual test named TestName in the test suite TestSuiteName, consisting of the given statements.',
    source: 'GoogleTest documentation',
    when: 'You want to write one test. The two names group and label it in the report; neither may contain an underscore. Use TEST_F instead when several tests share setup.',
    flags: [
      ['TestSuiteName', 'the group the test belongs to, such as Orbit'],
      ['TestName', 'what this one test checks, such as SpeedAtLeo'],
    ],
    example: { command: 'TEST(Orbit, SpeedAtLeo) { EXPECT_NEAR(circular_speed(kLeoRadius), 7668.6, 0.1); }', says: 'Defines a test that the report lists as Orbit.SpeedAtLeo.' },
    seeAlso: ['TEST_F', 'TEST_P', 'EXPECT_EQ'],
  },
  {
    name: 'TEST_F',
    lang: 'cpp',
    kind: 'macro',
    official: 'Defines an individual test named TestName that uses the test fixture class TestFixtureName. The test suite name is TestFixtureName.',
    source: 'GoogleTest documentation',
    when: 'Several tests need the same starting objects. Put them in a fixture class that inherits from testing::Test, and each TEST_F gets a fresh copy, built by SetUp before the test runs.',
    flags: [
      ['TestFixtureName', 'your fixture class, which must inherit from testing::Test'],
      ['TestName', 'what this test checks'],
    ],
    example: { command: 'TEST_F(OrbitFamily, SpeedFallsWithRadius) { EXPECT_LT(v[1], v[0]); }', says: 'Runs the test with a fresh OrbitFamily fixture, so it can use the fixture members directly.' },
    seeAlso: ['testing::Test', 'TEST', 'TEST_P'],
  },
  {
    name: 'testing::Test',
    aliases: ['::testing::Test'],
    lang: 'cpp',
    kind: 'class',
    official: 'The abstract class that all tests inherit from.',
    source: 'GoogleTest documentation',
    when: 'You are writing a fixture class for TEST_F. Inherit from it publicly, and override SetUp or TearDown for work done before or after each test. Spell them exactly SetUp and TearDown (capital U, capital D), or they are never called.',
    flags: [
      ['SetUp()', 'runs before each test'],
      ['TearDown()', 'runs after each test'],
    ],
    example: { command: 'class OrbitFamily : public ::testing::Test { protected: void SetUp() override { /* fill radii */ } };', says: 'Declares a fixture whose SetUp runs before every TEST_F that names it.' },
    seeAlso: ['TEST_F', 'testing::TestWithParam'],
  },
  {
    name: 'TEST_P',
    lang: 'cpp',
    kind: 'macro',
    official: 'Defines an individual value-parameterized test named TestName that uses the test fixture class TestFixtureName. The test suite name is TestFixtureName.',
    source: 'GoogleTest documentation',
    when: 'You want to run the same test on a table of inputs, each row reported as its own test. Inside it, GetParam() gives the current row. It runs nothing on its own: you also need INSTANTIATE_TEST_SUITE_P.',
    flags: [
      ['TestFixtureName', 'a fixture that inherits from testing::TestWithParam<T>'],
      ['GetParam()', 'the current row of the table'],
    ],
    example: { command: 'TEST_P(StepCount, IsNonNegative) { EXPECT_GE(GetParam(), 0); }', says: 'Defines a test that runs once for every value the instantiation supplies.' },
    seeAlso: ['INSTANTIATE_TEST_SUITE_P', 'testing::TestWithParam', 'testing::Values'],
  },
  {
    name: 'testing::TestWithParam',
    aliases: ['::testing::TestWithParam', 'TestWithParam'],
    lang: 'cpp',
    kind: 'class',
    official: 'A convenience class which inherits from both Test and WithParamInterface<T>.',
    source: 'GoogleTest documentation',
    when: 'You are writing the fixture for a TEST_P. The type in the angle brackets is the type of one row, often a small struct holding an input and the expected answer.',
    flags: [['T', 'the type of one parameter row, such as int or a struct']],
    example: { command: 'class WrapDegTest : public ::testing::TestWithParam<WrapCase> {};', says: 'Declares a fixture whose tests each receive one WrapCase through GetParam().' },
    seeAlso: ['TEST_P', 'testing::Test', 'INSTANTIATE_TEST_SUITE_P'],
  },
  {
    name: 'INSTANTIATE_TEST_SUITE_P',
    lang: 'cpp',
    kind: 'macro',
    official: 'Instantiates the value-parameterized test suite TestSuiteName (defined with TEST_P).',
    source: 'GoogleTest documentation',
    when: 'You wrote TEST_P tests and now say which rows to run them on. Forget it and no rows run; GoogleTest then reports a failing check so the mistake cannot pass quietly.',
    flags: [
      ['InstantiationName', 'a label for this batch of rows, added to the front of each test name'],
      ['TestSuiteName', 'the fixture used by the TEST_P tests'],
      ['generator', 'where the rows come from: Values, ValuesIn, Range, Bool or Combine'],
      ['name_generator', 'optional: a function or lambda that turns a row into a readable test name'],
    ],
    example: { command: 'INSTANTIATE_TEST_SUITE_P(ByRange, StepCount, ::testing::Range(0, 10, 3));', says: 'Runs every StepCount test four times, with 0, 3, 6 and 9.' },
    seeAlso: ['TEST_P', 'testing::Values', 'testing::ValuesIn', 'testing::Range', 'testing::TestParamInfo'],
  },
  {
    name: 'testing::Values',
    aliases: ['::testing::Values'],
    lang: 'cpp',
    kind: 'function',
    official: 'Yields values {v1, v2, ..., vN}.',
    source: 'GoogleTest documentation',
    when: 'You want to list the rows for a parameterized test right in the code. All the values must convert to the fixture parameter type.',
    example: { command: 'INSTANTIATE_TEST_SUITE_P(Altitudes, DragTest, ::testing::Values(0.0, 5000.0, 11000.0));', says: 'Runs each DragTest three times, once per altitude.' },
    seeAlso: ['testing::ValuesIn', 'testing::Range', 'INSTANTIATE_TEST_SUITE_P'],
  },
  {
    name: 'testing::ValuesIn',
    aliases: ['::testing::ValuesIn', 'ValuesIn'],
    lang: 'cpp',
    kind: 'function',
    official: 'Yields values from a C-style array, an STL-style container, or an iterator range [begin, end).',
    source: 'GoogleTest documentation',
    when: 'The table of rows is long or built by a function, so it lives in a std::vector, a std::array or a plain array. The container must still exist when the tests run, so make it a global or static.',
    example: { command: 'INSTANTIATE_TEST_SUITE_P(FromVector, StepCount, ::testing::ValuesIn(kRates));', says: 'Runs each StepCount test once for every element of kRates.' },
    seeAlso: ['testing::Values', 'INSTANTIATE_TEST_SUITE_P'],
  },
  {
    name: 'testing::Range',
    aliases: ['::testing::Range'],
    lang: 'cpp',
    kind: 'function',
    official: 'Yields values {begin, begin+step, begin+step+step, ...}. The values do not include end. step defaults to 1.',
    source: 'GoogleTest documentation',
    when: 'The rows are evenly spaced numbers. Like a for loop with <, the end value itself is never included.',
    flags: [
      ['begin', 'the first value'],
      ['end', 'where to stop; never produced itself'],
      ['step', 'optional: how much to add each time (1 if left out)'],
    ],
    example: { command: 'INSTANTIATE_TEST_SUITE_P(ByRange, StepCount, ::testing::Range(0, 10, 3));', says: 'Gives 0, 3, 6 and 9. It stops before 12 because 12 is not less than 10.' },
    seeAlso: ['testing::Values', 'INSTANTIATE_TEST_SUITE_P'],
  },
  {
    name: 'testing::Bool',
    aliases: ['::testing::Bool'],
    lang: 'cpp',
    kind: 'function',
    official: 'Yields sequence {false, true}.',
    source: 'GoogleTest documentation',
    when: 'A test should run with a switch both off and on, such as with and without a backup sensor. Often used inside Combine.',
    example: { command: 'INSTANTIATE_TEST_SUITE_P(Both, Switch, ::testing::Bool());', says: 'Runs each Switch test twice: first with false, then with true.' },
    seeAlso: ['testing::Combine', 'testing::Values'],
  },
  {
    name: 'testing::Combine',
    aliases: ['::testing::Combine', 'Combine'],
    lang: 'cpp',
    kind: 'function',
    official: 'Yields as std::tuple n-tuples all combinations (Cartesian product) of the values generated by the given n generators g1, g2, ..., gN.',
    source: 'GoogleTest documentation',
    when: 'Every value of one input should be tested with every value of another. Each row is a std::tuple, so the fixture parameter type must be a matching tuple, read with std::get. The row count multiplies quickly: 3 by 4 by 2 is already 24 tests.',
    example: { command: 'INSTANTIATE_TEST_SUITE_P(Grid, DragTest, ::testing::Combine(::testing::Values(0.0, 5000.0), ::testing::Values(0.6, 0.9)));', says: 'Runs each DragTest four times, once for every altitude and Mach pair.' },
    seeAlso: ['testing::Values', 'testing::Bool'],
  },
  {
    name: 'testing::TestParamInfo',
    aliases: ['::testing::TestParamInfo', 'TestParamInfo'],
    lang: 'cpp',
    kind: 'class',
    official: 'Describes a parameter to a value-parameterized test. The type T is the type of the parameter. Contains the fields param and index which hold the value of the parameter and its integer index respectively.',
    source: 'GoogleTest documentation',
    when: 'You write a name generator for INSTANTIATE_TEST_SUITE_P, so failures show a readable name instead of a number. The name you return may use only letters, digits and underscores, and must be different for every row.',
    flags: [
      ['info.param', 'the row this name is for'],
      ['info.index', 'the row number, counting from 0'],
    ],
    example: { command: '[](const ::testing::TestParamInfo<WrapCase>& info) { return info.param.name; }', says: 'A name generator that names each test after the name field of its row.' },
    seeAlso: ['INSTANTIATE_TEST_SUITE_P', 'testing::PrintToStringParamName'],
  },
  {
    name: 'testing::PrintToStringParamName',
    aliases: ['::testing::PrintToStringParamName', 'PrintToStringParamName'],
    lang: 'cpp',
    kind: 'class',
    official: 'testing::PrintToStringParamName is a builtin test suffix generator that returns the value of testing::PrintToString(GetParam()).',
    source: 'GoogleTest documentation',
    when: 'The rows are simple whole numbers or plain words and you want them as the test names. It breaks for decimals, strings with spaces and tuples, because dots, spaces, commas and brackets are not allowed in names; write your own generator for those.',
    example: { command: 'INSTANTIATE_TEST_SUITE_P(Rates, StepCount, ::testing::Values(50, 100), ::testing::PrintToStringParamName());', says: 'Names the tests Rates/StepCount.IsNonNegative/50 and .../100 instead of /0 and /1.' },
    seeAlso: ['testing::TestParamInfo', 'INSTANTIATE_TEST_SUITE_P'],
  },
  {
    name: 'testing::Types',
    aliases: ['::testing::Types'],
    lang: 'cpp',
    kind: 'class',
    official: 'The argument Types is a Types object representing the list of types to run the tests on.',
    source: 'GoogleTest documentation',
    when: 'The same tests should run once for each of several types, such as a ring buffer of int16_t, float and double. Give the list a name with using, then pass it to TYPED_TEST_SUITE.',
    example: { command: 'using SampleTypes = ::testing::Types<std::int16_t, float, double>;', says: 'Names a list of three types; each typed test then runs three times, once per type.' },
    seeAlso: ['testing::Test'],
  },
  // ---------------------------------------------------------------- GoogleMock
  {
    name: 'MOCK_METHOD',
    lang: 'cpp',
    kind: 'macro',
    official: 'Defines a mock method method_name with arguments (args...) and return type return_type within a mock class.',
    source: 'GoogleTest documentation',
    when: 'You are writing a fake version of an interface, such as a sensor or valve, so a test can control and check how your code talks to it. The argument list and the specs each go in their own brackets; forgetting override lets a typo create a new method instead of replacing the real one.',
    flags: [
      ['return_type', 'what the method returns'],
      ['method_name', 'the method you are faking'],
      ['(args...)', 'its parameters, in brackets'],
      ['(const, override)', 'the specs, in brackets: override always, const if the real one is const'],
    ],
    example: { command: 'MOCK_METHOD(bool, read, (int ch, double& kpa), (override));', says: 'Adds a fake read method to a mock pressure sensor class.' },
    seeAlso: ['EXPECT_CALL', 'testing::NiceMock', 'testing::StrictMock'],
  },
  {
    name: 'EXPECT_CALL',
    lang: 'cpp',
    kind: 'macro',
    official: 'Creates an expectation that the method method_name of the object mock_object is called with arguments that match the given matchers matchers.... EXPECT_CALL must precede any code that exercises the mock object.',
    source: 'GoogleTest documentation',
    when: 'A test says in advance which calls a mock should get, with what arguments, how often, and what it does in reply. Write it before the code that makes the calls; an expectation written afterwards sees nothing.',
    flags: [
      ['mock_object, method(matchers)', 'which method, and what each argument must match'],
      ['.Times(n)', 'how many calls are expected'],
      ['.WillOnce(action)', 'what to do on the next call, such as Return(true)'],
      ['.WillRepeatedly(action)', 'what to do on every call after that'],
    ],
    example: { command: 'EXPECT_CALL(sensor, read(Eq(2), _)).WillOnce(Return(true));', says: 'Expects exactly one read on channel 2, with any second argument, and makes it return true.' },
    seeAlso: ['MOCK_METHOD', 'testing::Return', 'testing::_', 'testing::Eq'],
  },
  {
    name: 'testing::_',
    aliases: ['::testing::_', '_'],
    lang: 'cpp',
    kind: 'constant',
    official: 'argument can be any value of the correct type.',
    source: 'GoogleTest documentation',
    when: 'In an EXPECT_CALL, for an argument you do not care about. It still has to be there, one per parameter.',
    example: { command: 'EXPECT_CALL(sensor, read(_, _)).WillOnce(Return(false));', says: 'Expects one read call with any channel and any output variable.' },
    seeAlso: ['EXPECT_CALL', 'testing::Eq'],
  },
  {
    name: 'testing::Eq',
    aliases: ['::testing::Eq'],
    lang: 'cpp',
    kind: 'function',
    official: 'argument == value',
    source: 'GoogleTest documentation',
    when: 'In an EXPECT_CALL, to require an argument equal to a value. Writing the value alone means the same thing; Eq just makes the intent visible. For computed doubles use DoubleNear instead.',
    example: { command: 'EXPECT_CALL(sensor, read(Eq(2), _));', says: 'Expects a read call whose channel argument equals 2.' },
    seeAlso: ['testing::Gt', 'testing::DoubleNear', 'testing::_'],
  },
  {
    name: 'testing::Gt',
    aliases: ['::testing::Gt'],
    lang: 'cpp',
    kind: 'function',
    official: 'argument > value',
    source: 'GoogleTest documentation',
    when: 'In an EXPECT_CALL, when any argument above a limit is fine, such as "the valve opens by some amount". Its relatives are Ge, Lt, Le and Ne.',
    example: { command: 'EXPECT_CALL(valve, set_open(Gt(0.0))).Times(1);', says: 'Expects exactly one set_open call with a fraction greater than zero.' },
    seeAlso: ['testing::Eq', 'EXPECT_CALL'],
  },
  {
    name: 'testing::DoubleNear',
    aliases: ['::testing::DoubleNear', 'DoubleNear'],
    lang: 'cpp',
    kind: 'function',
    official: 'argument is a double value close to a_double (absolute error <= max_abs_error), treating two NaNs as unequal.',
    source: 'GoogleTest documentation',
    when: 'In an EXPECT_CALL, when the argument is a computed double. Exact matching almost never works for computed decimals, so allow a tiny tolerance.',
    flags: [
      ['a_double', 'the value you expect'],
      ['max_abs_error', 'how far off it may be'],
    ],
    example: { command: 'EXPECT_CALL(valve, set_open(DoubleNear(0.5, 1e-9)));', says: 'Expects set_open with a fraction within 0.000000001 of 0.5.' },
    seeAlso: ['testing::Eq', 'EXPECT_NEAR'],
  },
  {
    name: 'testing::Return',
    aliases: ['::testing::Return'],
    lang: 'cpp',
    kind: 'function',
    official: "Return value. If the type of value is different to the mock function's return type, value is converted to the latter type at the time the expectation is set, not when the action is executed.",
    source: 'GoogleTest documentation (docs/reference/actions.md)',
    when: 'You want a mock method to hand back a chosen value, such as a sensor read that succeeds or fails. Use it inside WillOnce, WillRepeatedly or WillByDefault.',
    example: { command: 'EXPECT_CALL(sensor, read(_, _)).WillOnce(Return(false));', says: 'Makes the next read call return false, as if the sensor failed.' },
    seeAlso: ['EXPECT_CALL', 'testing::DoAll', 'testing::SetArgReferee'],
  },
  {
    name: 'testing::SetArgReferee',
    aliases: ['::testing::SetArgReferee', 'SetArgReferee'],
    lang: 'cpp',
    kind: 'function',
    official: 'Assign value to the variable referenced by the N-th (0-based) argument.',
    source: 'GoogleTest documentation',
    when: 'The mocked method gives its answer through a reference parameter (an out-parameter), like read(int ch, double& kpa). Positions count from zero, so the second parameter is 1.',
    flags: [
      ['<N>', 'which argument to write to, counting from 0'],
      ['(value)', 'what to write into it'],
    ],
    example: { command: 'EXPECT_CALL(sensor, read(2, _)).WillOnce(DoAll(SetArgReferee<1>(330.0), Return(true)));', says: 'On the call, writes 330.0 into kpa and then returns true.' },
    seeAlso: ['testing::DoAll', 'testing::Return'],
  },
  {
    name: 'testing::DoAll',
    aliases: ['::testing::DoAll', 'DoAll'],
    lang: 'cpp',
    kind: 'function',
    official: 'Do all actions a1 to an and return the result of an in each invocation.',
    source: 'GoogleTest documentation',
    when: 'One mocked call needs several things done, most often setting an out-parameter and returning a status. The actions run in order, and only the last one returns a value.',
    example: { command: 'EXPECT_CALL(sensor, read(2, _)).WillOnce(DoAll(SetArgReferee<1>(280.0), Return(true)));', says: 'Writes 280.0 into the output argument, then returns true.' },
    seeAlso: ['testing::SetArgReferee', 'testing::Return'],
  },
  {
    name: 'testing::NiceMock',
    aliases: ['::testing::NiceMock', 'NiceMock'],
    lang: 'cpp',
    kind: 'class',
    official: 'Represents a mock object that suppresses warnings on uninteresting calls.',
    source: 'GoogleTest documentation',
    when: 'A mock gets calls the test does not care about, and you want them to go ahead quietly with default answers. Being quiet also means it will not warn you about a call you forgot.',
    flags: [['T', 'your mock class']],
    example: { command: 'NiceMock<MockPressureSensor> sensor;', says: 'Makes a mock sensor that ignores calls without an EXPECT_CALL instead of printing warnings.' },
    seeAlso: ['testing::StrictMock', 'MOCK_METHOD'],
  },
  {
    name: 'testing::StrictMock',
    aliases: ['::testing::StrictMock', 'StrictMock'],
    lang: 'cpp',
    kind: 'class',
    official: 'Represents a mock object that generates test failures on uninteresting calls.',
    source: 'GoogleTest documentation',
    when: 'Any call the test did not expect should fail it, such as "no thruster may fire". It checks which calls happen, not their order; use InSequence for order.',
    flags: [['T', 'your mock class']],
    example: { command: 'StrictMock<MockThruster> thruster;', says: 'Makes a mock thruster where any call without a matching EXPECT_CALL fails the test.' },
    seeAlso: ['testing::NiceMock', 'testing::InSequence'],
  },
  {
    name: 'testing::InSequence',
    aliases: ['::testing::InSequence', 'InSequence'],
    lang: 'cpp',
    kind: 'class',
    official: 'An object of this type causes all EXPECT_CALL() statements encountered in its scope to be put in an anonymous sequence.',
    source: 'GoogleTest documentation',
    when: 'The order of calls matters, such as arm before fire before disarm. Create one as a local variable; every EXPECT_CALL written while it exists must then happen in the order written.',
    example: { command: 'InSequence seq;  // then EXPECT_CALL(pyro, arm()); EXPECT_CALL(pyro, fire(1));', says: 'Requires arm() to be called before fire(1); the other way round fails the test.' },
    seeAlso: ['EXPECT_CALL', 'testing::StrictMock'],
  },
  // ---------------------------------------------------------------- Eigen: the Matrix class and its nicknames
  {
    name: 'Eigen::Matrix',
    aliases: ['Matrix'],
    lang: 'cpp',
    kind: 'class',
    official: 'The matrix class, also used for vectors and row-vectors.',
    source: 'Eigen documentation',
    when: 'You need a matrix or vector with a size or number type that has no nickname, such as a 6-number state vector. Sizes fixed at compile time live on the stack and are fast; Eigen::Dynamic sizes are allocated at run time.',
    flags: [
      ['Scalar', 'the number type, such as double or float'],
      ['Rows', 'the number of rows, or Eigen::Dynamic'],
      ['Cols', 'the number of columns, or Eigen::Dynamic'],
      ['Options', 'optional: Eigen::RowMajor to store row by row'],
      ['RowsAtCompileTime', 'the row count as a constant, for static_assert'],
      ['rows(), cols()', 'the size'],
      ['transpose()', 'rows and columns swapped'],
      ['block(i, j, r, c)', 'an r by c piece starting at row i, column j'],
      ['col(j), row(i)', 'one column or one row'],
      ['array()', 'the same numbers, with * meaning entry by entry'],
      ['noalias()', 'promise the result does not overlap the inputs, to skip a temporary copy'],
      ['eval()', 'compute now into a real matrix'],
    ],
    example: { command: 'using Vector6d = Eigen::Matrix<double, 6, 1>;', says: 'Names a fixed-size column of six doubles, such as a position and velocity state.' },
    seeAlso: ['Eigen::Dynamic', 'Eigen::RowMajor', 'Eigen::Matrix3d', 'Eigen::MatrixXd'],
  },
  {
    name: 'Eigen::Matrix2d',
    aliases: ['Matrix2d'],
    lang: 'cpp',
    kind: 'type',
    official: 'MatrixSizeType where Size can be 2, 3, 4 for fixed size square matrices or X for dynamic size, and where Type can be i for integer, f for float, d for double, cf for complex float, cd for complex double.',
    source: 'Eigen documentation (Matrix.h, Global matrix typedefs)',
    when: 'You need a small 2 by 2 matrix, such as a 2D covariance. A new one is not set to zero; fill it with << or start from Zero() or Identity().',
    flags: [
      ['<<', 'fill it row by row: m << 1, 2, 3, 4;'],
      ['m(i, j)', 'the entry at row i, column j, counting from 0'],
      ['transpose(), inverse(), determinant()', 'the usual matrix operations'],
      ['llt(), ldlt()', 'factor it to solve equations'],
      ['cwiseProduct(b)', 'entry-by-entry product'],
    ],
    example: { command: 'Eigen::Matrix2d P;  P << 4.0, 1.0, 1.0, 2.0;', says: 'Makes a 2 by 2 matrix with rows (4, 1) and (1, 2).' },
    seeAlso: ['Eigen::Matrix3d', 'Eigen::Matrix'],
  },
  {
    name: 'Eigen::Matrix3d',
    aliases: ['Matrix3d'],
    lang: 'cpp',
    kind: 'type',
    official: 'For example, Matrix3d is a fixed-size 3x3 matrix type of doubles, and MatrixXf is a dynamic-size matrix of floats.',
    source: 'Eigen documentation (Matrix.h, Global matrix typedefs)',
    when: 'The workhorse for 3D: rotation matrices, inertia tensors, 3 by 3 covariances. A new one holds garbage, not zeros. In Eigen, * between two matrices is the matrix product, not entry by entry.',
    flags: [
      ['transpose()', 'rows and columns swapped (the inverse, for a rotation matrix)'],
      ['inverse()', 'the matrix inverse'],
      ['determinant(), trace()', 'one-number summaries'],
      ['diagonal()', 'the three diagonal entries as a vector'],
      ['col(j), row(i)', 'one column or row'],
      ['llt(), ldlt()', 'factor a symmetric matrix to solve equations'],
      ['setIdentity(), setZero()', 'overwrite with the identity or zeros'],
      ['cwiseAbs(), maxCoeff()', 'absolute values entry by entry; the largest entry'],
      ['transposeInPlace()', 'transpose it in its own storage'],
    ],
    example: { command: 'const Eigen::Matrix3d R = q.toRotationMatrix();', says: 'Turns a quaternion into the 3 by 3 rotation matrix for the same turn.' },
    seeAlso: ['Eigen::Matrix3d::Identity', 'Eigen::Vector3d', 'Eigen::Quaterniond'],
  },
  {
    name: 'Eigen::Matrix4d',
    aliases: ['Matrix4d'],
    lang: 'cpp',
    kind: 'type',
    official: 'MatrixSizeType where Size can be 2, 3, 4 for fixed size square matrices or X for dynamic size, and where Type can be i for integer, f for float, d for double, cf for complex float, cd for complex double.',
    source: 'Eigen documentation (Matrix.h, Global matrix typedefs)',
    when: 'You need a 4 by 4 matrix, most often a homogeneous transform: rotation and translation packed together. Its 16 doubles fit SIMD registers neatly, so products are fast.',
    flags: [
      ['block<3,3>(0,0)', 'the top-left 3 by 3 piece (the rotation part)'],
      ['col(3)', 'the last column (the translation part, plus a 1)'],
      ['inverse()', 'the matrix inverse'],
    ],
    example: { command: 'const Eigen::Matrix4d M = T_world_cam.matrix();', says: 'Copies a rigid transform out as a plain 4 by 4 matrix.' },
    seeAlso: ['Eigen::Isometry3d', 'Eigen::Matrix3d'],
  },
  {
    name: 'Eigen::MatrixXd',
    aliases: ['MatrixXd'],
    lang: 'cpp',
    kind: 'type',
    official: 'MatrixSizeType where Size can be 2, 3, 4 for fixed size square matrices or X for dynamic size, and where Type can be i for integer, f for float, d for double, cf for complex float, cd for complex double.',
    source: 'Eigen documentation (Matrix.h, Global matrix typedefs)',
    when: 'The size is only known at run time, such as a big covariance or a least-squares problem. Creating or resizing one allocates heap memory, which you must avoid inside a real-time loop.',
    flags: [
      ['rows(), cols()', 'the size'],
      ['resize(r, c)', 'change the size; the old values are lost'],
      ['setZero()', 'fill with zeros'],
      ['transpose()', 'rows and columns swapped'],
      ['noalias()', 'skip the temporary copy in a product'],
      ['block(i, j, r, c)', 'a piece of it'],
      ['colwise(), rowwise()', 'do something for each column or each row'],
      ['ldlt(), llt(), partialPivLu(), householderQr(), colPivHouseholderQr()', 'factor it to solve A x = b'],
      ['data()', 'a pointer to the raw numbers'],
    ],
    example: { command: 'Eigen::MatrixXd P(9, 9);  P.setZero();', says: 'Makes a 9 by 9 matrix on the heap and fills it with zeros.' },
    seeAlso: ['Eigen::MatrixXd::Zero', 'Eigen::MatrixXd::Identity', 'Eigen::VectorXd'],
  },
  {
    name: 'Eigen::Vector2d',
    aliases: ['Vector2d'],
    lang: 'cpp',
    kind: 'type',
    official: 'VectorNt for Matrix<type, N, 1>. For example, Vector2f for Matrix<float, 2, 1>.',
    source: 'Eigen documentation (TutorialMatrixClass.dox, Convenience typedefs)',
    when: 'A 2D point or velocity, or a two-number state. It is a column, so it is 2 by 1, not 1 by 2.',
    flags: [
      ['x(), y()', 'the two entries'],
      ['norm(), dot(w)', 'length; dot product'],
      ['transpose()', 'the same numbers as a row'],
    ],
    example: { command: 'Eigen::Vector2d v(1.0, 2.0);', says: 'Makes the column vector (1, 2).' },
    seeAlso: ['Eigen::Vector3d', 'Eigen::RowVector2d'],
  },
  {
    name: 'Eigen::Vector3d',
    aliases: ['Vector3d'],
    lang: 'cpp',
    kind: 'type',
    official: 'VectorNt for Matrix<type, N, 1>. For example, Vector2f for Matrix<float, 2, 1>.',
    source: 'Eigen documentation (TutorialMatrixClass.dox, Convenience typedefs)',
    when: 'The everyday 3D vector: position, velocity, angular rate, a direction. A new one is not zeroed; use Vector3d::Zero() or give three numbers. v * w between two vectors does not compile; say dot, cross or cwiseProduct.',
    flags: [
      ['x(), y(), z()', 'the three entries'],
      ['norm(), squaredNorm()', 'length, or length squared (no square root)'],
      ['normalized()', 'a copy with length 1'],
      ['normalize()', 'make this one length 1, in place'],
      ['dot(w)', 'dot product'],
      ['cross(w)', 'cross product'],
      ['transpose()', 'the same numbers as a row'],
      ['cwiseAbs(), maxCoeff(), minCoeff()', 'absolute values; largest or smallest entry'],
      ['asDiagonal()', 'a diagonal matrix with these on the diagonal'],
    ],
    example: { command: 'const Eigen::Vector3d r(6771e3, 0.0, 0.0);  double alt = r.norm() - 6371e3;', says: 'Makes a position vector and works out the altitude from its length, about 400 km.' },
    seeAlso: ['Eigen::Vector3d::UnitX', 'Eigen::Matrix3d', 'Eigen::VectorXd'],
  },
  {
    name: 'Eigen::Vector4d',
    aliases: ['Vector4d'],
    lang: 'cpp',
    kind: 'type',
    official: 'VectorNt for Matrix<type, N, 1>. For example, Vector2f for Matrix<float, 2, 1>.',
    source: 'Eigen documentation (TutorialMatrixClass.dox, Convenience typedefs)',
    when: 'Four numbers in a column, such as a quaternion coeffs() or a point in homogeneous form. When building a quaternion from one, the order is x, y, z, w, with w last.',
    flags: [['x(), y(), z(), w()', 'the four entries']],
    example: { command: 'const Eigen::Vector4d c = q.coeffs();', says: 'Copies a quaternion into four numbers in storage order x, y, z, w.' },
    seeAlso: ['Eigen::Quaterniond', 'Eigen::Vector4f'],
  },
  {
    name: 'Eigen::Vector4f',
    aliases: ['Vector4f'],
    lang: 'cpp',
    kind: 'type',
    official: 'VectorNt for Matrix<type, N, 1>. For example, Vector2f for Matrix<float, 2, 1>.',
    source: 'Eigen documentation (TutorialMatrixClass.dox, Convenience typedefs)',
    when: 'Four floats in a column. It is exactly 16 bytes, one SIMD register, so Eigen aligns it to 16 bytes; that is why a struct holding one needs care with alignment.',
    example: { command: 'Eigen::Vector4f v(1.0f, 2.0f, 3.0f, 4.0f);', says: 'Makes a 16-byte column of four floats.' },
    seeAlso: ['Eigen::Vector4d'],
  },
  {
    name: 'Eigen::VectorXd',
    aliases: ['VectorXd'],
    lang: 'cpp',
    kind: 'type',
    official: 'VectorNt for Matrix<type, N, 1>. For example, Vector2f for Matrix<float, 2, 1>.',
    source: 'Eigen documentation (TutorialMatrixClass.dox, Convenience typedefs)',
    when: 'A column whose length is set at run time, such as a batch of samples or singular values. Creating one allocates heap memory.',
    flags: [
      ['size()', 'how many entries'],
      ['head(n), tail(n), segment(i, n)', 'the first n, the last n, or n starting at i'],
      ['sum(), mean(), prod()', 'add up, average, multiply together'],
      ['maxCoeff(), minCoeff()', 'the largest or smallest entry'],
      ['norm()', 'length'],
      ['array()', 'use entry-by-entry math such as sqrt()'],
      ['cwiseProduct(w), cwiseSqrt()', 'entry-by-entry product; square root of each entry'],
      ['asDiagonal()', 'a diagonal matrix with these on the diagonal'],
    ],
    example: { command: 'Eigen::VectorXd s = svd.singularValues();', says: 'Stores the singular values in a vector sized to however many there are.' },
    seeAlso: ['Eigen::VectorXd::Constant', 'Eigen::MatrixXd', 'Eigen::Index'],
  },
  {
    name: 'Eigen::RowVector2d',
    aliases: ['RowVector2d'],
    lang: 'cpp',
    kind: 'type',
    official: 'RowVectorNt for Matrix<type, 1, N>. For example, RowVector3d for Matrix<double, 1, 3>.',
    source: 'Eigen documentation (TutorialMatrixClass.dox, Convenience typedefs)',
    when: 'Two numbers laid out as a row rather than a column, for example to subtract from every row of a matrix with rowwise(). Mixing it up with Vector2d is a size error.',
    flags: [['transpose()', 'the same numbers as a column']],
    example: { command: 'Eigen::RowVector2d r(1.0, -1.0);', says: 'Makes the 1 by 2 row (1, -1).' },
    seeAlso: ['Eigen::Vector2d'],
  },
  {
    name: 'Eigen::Dynamic',
    aliases: ['Dynamic'],
    lang: 'cpp',
    kind: 'constant',
    official: 'This value means that a positive quantity (e.g., a size) is not known at compile-time, and that instead the value is stored in some runtime variable.',
    source: 'Eigen documentation',
    when: 'In a Matrix type, in place of a row or column count that you only know at run time. Any Dynamic size means the numbers go on the heap.',
    example: { command: 'using RowMajor6 = Eigen::Matrix<double, Eigen::Dynamic, 6, Eigen::RowMajor>;', says: 'Names a matrix with any number of rows and exactly 6 columns.' },
    seeAlso: ['Eigen::Matrix', 'Eigen::MatrixXd'],
  },
  {
    name: 'Eigen::RowMajor',
    aliases: ['RowMajor'],
    lang: 'cpp',
    kind: 'constant',
    official: 'Storage order is row major (see Storage orders).',
    source: 'Eigen documentation',
    when: 'You need Eigen to store a matrix row by row, like C arrays and NumPy do. Eigen stores column by column unless told otherwise, so a Map over row-ordered data without it reads the numbers in the wrong places.',
    example: { command: 'Eigen::Map<Eigen::Matrix<double, 2, 3, Eigen::RowMajor>> m(buf);', says: 'Reads the six numbers in buf as two rows of three.' },
    seeAlso: ['Eigen::Map', 'Eigen::Matrix'],
  },
  {
    name: 'Eigen::Index',
    lang: 'cpp',
    kind: 'type',
    official: 'The Index type as used for the API.',
    source: 'Eigen documentation',
    when: 'For loop counters and sizes with Eigen objects. It is signed (normally std::ptrdiff_t), so comparing with size() gives no signed-unsigned warning the way int or std::size_t can.',
    example: { command: 'for (Eigen::Index i = 0; i < v.size(); ++i) sum += v(i);', says: 'Adds up every entry of v with a counter of the type Eigen itself uses.' },
    seeAlso: ['Eigen::VectorXd'],
  },
  // ---------------------------------------------------------------- Eigen: ready-made values
  {
    name: 'Eigen::Matrix3d::Identity',
    aliases: ['Matrix3d::Identity'],
    lang: 'cpp',
    kind: 'function',
    official: 'Returns an expression of the identity matrix (not necessarily square).',
    source: 'Eigen documentation',
    when: 'You want the 3 by 3 identity: ones on the diagonal, zeros elsewhere, meaning "no rotation" or "no change". For a fixed-size type it takes no arguments.',
    example: { command: 'Eigen::Matrix3d R = Eigen::Matrix3d::Identity();', says: 'Starts R as the identity matrix.' },
    seeAlso: ['Eigen::MatrixXd::Identity', 'Eigen::Matrix3d'],
  },
  {
    name: 'Eigen::MatrixXd::Identity',
    aliases: ['MatrixXd::Identity'],
    lang: 'cpp',
    kind: 'function',
    official: 'Returns an expression of the identity matrix (not necessarily square).',
    source: 'Eigen documentation',
    when: 'You want an identity of a size known only at run time, such as the I in a Kalman filter update. For a dynamic type you must give the rows and columns.',
    flags: [['(rows, cols)', 'the size of the identity']],
    example: { command: 'const Eigen::MatrixXd I = Eigen::MatrixXd::Identity(6, 6);', says: 'Makes a 6 by 6 identity matrix.' },
    seeAlso: ['Eigen::Matrix3d::Identity', 'Eigen::MatrixXd::Zero'],
  },
  {
    name: 'Eigen::MatrixXd::Zero',
    aliases: ['MatrixXd::Zero'],
    lang: 'cpp',
    kind: 'function',
    official: 'Returns an expression of a zero matrix.',
    source: 'Eigen documentation',
    when: 'You want a run-time-sized matrix that starts at all zeros, since a plain MatrixXd(r, c) is not zeroed.',
    flags: [['(rows, cols)', 'the size']],
    example: { command: 'Eigen::MatrixXd P = Eigen::MatrixXd::Zero(9, 9);', says: 'Makes a 9 by 9 matrix full of zeros.' },
    seeAlso: ['Eigen::MatrixXd::Identity', 'Eigen::MatrixXd'],
  },
  {
    name: 'Eigen::MatrixXd::Random',
    aliases: ['MatrixXd::Random'],
    lang: 'cpp',
    kind: 'function',
    official: 'Returns a random matrix expression',
    source: 'Eigen documentation (DenseBase::Random, Random.h)',
    when: 'You want a test or benchmark matrix full of made-up numbers between -1 and 1. It uses std::rand, so it gives the same numbers every run unless you seed it.',
    flags: [['(rows, cols)', 'the size']],
    example: { command: 'const Eigen::MatrixXd A = Eigen::MatrixXd::Random(40, 40);', says: 'Makes a 40 by 40 matrix of random numbers between -1 and 1.' },
    seeAlso: ['Eigen::Vector2d::Random', 'Eigen::MatrixXd'],
  },
  {
    name: 'Eigen::Vector2d::Random',
    aliases: ['Vector2d::Random'],
    lang: 'cpp',
    kind: 'function',
    official: 'Returns a fixed-size random matrix or vector expression',
    source: 'Eigen documentation (DenseBase::Random, Random.h)',
    when: 'A test needs a made-up 2D vector, such as a random true state to check a solver against. For a fixed-size type it takes no arguments.',
    example: { command: 'const Eigen::Vector2d x_true = Eigen::Vector2d::Random();', says: 'Makes a 2D vector whose two entries are random numbers between -1 and 1.' },
    seeAlso: ['Eigen::MatrixXd::Random', 'Eigen::Vector2d'],
  },
  {
    name: 'Eigen::VectorXd::Constant',
    aliases: ['VectorXd::Constant'],
    lang: 'cpp',
    kind: 'function',
    official: 'Returns an expression of a constant matrix of value value',
    source: 'Eigen documentation',
    when: 'You want a run-time-sized vector with every entry the same, such as a list of equal time steps.',
    flags: [
      ['size', 'how many entries'],
      ['value', 'the number every entry gets'],
    ],
    example: { command: 'const Eigen::VectorXd dt = Eigen::VectorXd::Constant(3600000, 0.001);', says: 'Makes 3.6 million time steps, each 0.001 s: one hour at 1 kHz.' },
    seeAlso: ['Eigen::VectorXd', 'Eigen::MatrixXd::Zero'],
  },
  {
    name: 'Eigen::Vector3d::UnitX',
    aliases: ['Vector3d::UnitX'],
    lang: 'cpp',
    kind: 'function',
    official: 'Returns an expression of the X axis unit vector (1{,0}^*)',
    source: 'Eigen documentation',
    when: 'You need the x-axis direction (1, 0, 0), such as the axis for a roll or a body forward vector to rotate.',
    example: { command: 'const Eigen::Vector3d nose = q * Eigen::Vector3d::UnitX();', says: 'Rotates the x-axis by q, giving where the nose points.' },
    seeAlso: ['Eigen::Vector3d::UnitY', 'Eigen::Vector3d::UnitZ', 'Eigen::AngleAxisd'],
  },
  {
    name: 'Eigen::Vector3d::UnitY',
    aliases: ['Vector3d::UnitY'],
    lang: 'cpp',
    kind: 'function',
    official: 'Returns an expression of the Y axis unit vector (0,1{,0}^*)',
    source: 'Eigen documentation',
    when: 'You need the y-axis direction (0, 1, 0), such as the axis for a pitch turn.',
    example: { command: 'const Eigen::AngleAxisd pitch(0.1, Eigen::Vector3d::UnitY());', says: 'Describes a turn of 0.1 radians about the y-axis.' },
    seeAlso: ['Eigen::Vector3d::UnitX', 'Eigen::Vector3d::UnitZ'],
  },
  {
    name: 'Eigen::Vector3d::UnitZ',
    aliases: ['Vector3d::UnitZ'],
    lang: 'cpp',
    kind: 'function',
    official: 'Returns an expression of the Z axis unit vector (0,0,1{,0}^*)',
    source: 'Eigen documentation',
    when: 'You need the z-axis direction (0, 0, 1), such as the axis for a yaw turn.',
    example: { command: 'const Eigen::Quaterniond q_z90(Eigen::AngleAxisd(M_PI / 2, Eigen::Vector3d::UnitZ()));', says: 'Makes a quaternion for a 90 degree turn about the z-axis.' },
    seeAlso: ['Eigen::Vector3d::UnitX', 'Eigen::Vector3d::UnitY'],
  },
  // ---------------------------------------------------------------- Eigen: views over memory
  {
    name: 'Eigen::Map',
    aliases: ['Map'],
    lang: 'cpp',
    kind: 'class',
    official: 'A matrix or vector expression mapping an existing array of data.',
    source: 'Eigen documentation',
    when: 'Numbers already sit in a plain array or buffer (from a sensor, a file, or NumPy) and you want to use them as an Eigen vector or matrix without copying. It does not own the memory, so the buffer must outlive the Map; and it reads column by column unless you say RowMajor.',
    flags: [
      ['<Type>', 'what to view the memory as, such as const Eigen::Vector3d'],
      ['<Type, 0, Stride>', 'optional alignment (0: no promise) and step between entries'],
      ['(ptr)', 'the address of the first number'],
      ['(ptr, rows, cols)', 'the size too, for a dynamic type'],
    ],
    example: { command: 'Eigen::Map<const Eigen::Vector3d> gyro(imu_buffer);', says: 'Views the first three doubles of imu_buffer as a Vector3d, with no copy.' },
    seeAlso: ['Eigen::InnerStride', 'Eigen::RowMajor', 'Eigen::Ref'],
  },
  {
    name: 'Eigen::InnerStride',
    aliases: ['InnerStride'],
    lang: 'cpp',
    kind: 'class',
    official: 'Convenience specialization of Stride to specify only an inner stride.',
    source: 'Eigen documentation',
    when: 'The numbers you want are spaced out in memory, such as every other value of interleaved data. Used as the third template argument of a Map.',
    flags: [['<N>', 'the step from one entry to the next, counted in numbers']],
    example: { command: 'Eigen::Map<const Eigen::Vector3d, 0, Eigen::InnerStride<2>> a(buf);', says: 'Views buf[0], buf[2] and buf[4] as one Vector3d.' },
    seeAlso: ['Eigen::Map'],
  },
  {
    name: 'Eigen::Ref',
    aliases: ['Ref'],
    lang: 'cpp',
    kind: 'class',
    official: 'A matrix or vector expression mapping an existing expression',
    source: 'Eigen documentation',
    when: 'A function should accept a vector or matrix from many sources (a real Vector3d, a column of a matrix, a Map) without being a template and without copying. For input, write const Eigen::Ref<const T>&.',
    example: { command: 'double along_track(const Eigen::Ref<const Eigen::Vector3d>& r, const Eigen::Ref<const Eigen::Vector3d>& v);', says: 'Declares a function that takes any 3-number vector view, with no copy.' },
    seeAlso: ['Eigen::Map', 'Eigen::Vector3d'],
  },
  // ---------------------------------------------------------------- Eigen: decompositions
  {
    name: 'Eigen::LLT',
    aliases: ['LLT'],
    lang: 'cpp',
    kind: 'class',
    official: 'Standard Cholesky decomposition (LL^T) of a matrix and associated features',
    source: 'Eigen documentation',
    when: 'You have a symmetric, positive definite matrix, like a covariance, and want to solve with it or draw correlated noise. It is the fastest choice. Building it never throws, so always check info() before trusting the answer.',
    flags: [
      ['<MatrixType>', 'the matrix type, such as Eigen::Matrix3d'],
      ['solve(b)', 'the x in A x = b'],
      ['info()', 'Eigen::Success if the factoring worked'],
      ['matrixL()', 'the lower-triangular factor L'],
    ],
    example: { command: 'const Eigen::LLT<Eigen::Matrix3d> llt(P);  if (llt.info() != Eigen::Success) return false;', says: 'Factors P as L times L-transpose and gives up if P is not positive definite.' },
    seeAlso: ['Eigen::LDLT', 'Eigen::Success'],
  },
  {
    name: 'Eigen::LDLT',
    aliases: ['LDLT'],
    lang: 'cpp',
    kind: 'class',
    official: 'Robust Cholesky decomposition of a matrix with pivoting',
    source: 'Eigen documentation',
    when: 'Like LLT for symmetric matrices, but it also copes with matrices that are only positive semidefinite (or slightly off), which happens to covariances after rounding. Check info() before using the result.',
    flags: [
      ['<MatrixType>', 'the matrix type'],
      ['solve(b)', 'the x in A x = b'],
      ['info()', 'Eigen::Success if the factoring worked'],
      ['isPositive()', 'true if the matrix is positive semidefinite'],
      ['rcond()', 'a quick estimate of how close to singular it is'],
    ],
    example: { command: 'const Eigen::LDLT<Eigen::Matrix3d> ldlt(P);  Eigen::Vector3d x = ldlt.solve(b);', says: 'Factors P and solves P x = b.' },
    seeAlso: ['Eigen::LLT', 'Eigen::Success'],
  },
  {
    name: 'Eigen::ColPivHouseholderQR',
    aliases: ['ColPivHouseholderQR'],
    lang: 'cpp',
    kind: 'class',
    official: 'Householder rank-revealing QR decomposition of a matrix with column-pivoting',
    source: 'Eigen documentation',
    when: 'You solve a least-squares problem and also want to know the rank, meaning how many columns really carry independent information. A little slower than plain HouseholderQR.',
    flags: [
      ['<MatrixType>', 'the matrix type'],
      ['rank()', 'how many independent columns'],
      ['solve(b)', 'the least-squares x'],
    ],
    example: { command: 'const Eigen::ColPivHouseholderQR<Eigen::MatrixXd> cpqr(B);  std::cout << cpqr.rank();', says: 'Factors B and prints its rank.' },
    seeAlso: ['Eigen::JacobiSVD'],
  },
  {
    name: 'Eigen::JacobiSVD',
    aliases: ['JacobiSVD'],
    lang: 'cpp',
    kind: 'class',
    official: 'Two-sided Jacobi SVD decomposition of a rectangular matrix',
    source: 'Eigen documentation',
    when: 'You want the singular values of a matrix, for example to see how close to singular it is, or the most careful least-squares solve. It is the slowest decomposition, so keep it to small matrices or offline work. To call solve() you must ask for U and V when you build it.',
    flags: [
      ['<MatrixType>', 'the matrix type'],
      ['ComputeThinU | ComputeThinV', 'also compute U and V, needed for solve()'],
      ['singularValues()', 'the singular values, largest first'],
      ['solve(b)', 'the least-squares x'],
      ['rank()', 'how many singular values are not tiny'],
    ],
    example: { command: 'const Eigen::JacobiSVD<Eigen::MatrixXd> svd(B, Eigen::ComputeThinU | Eigen::ComputeThinV);', says: 'Computes the SVD of B, ready to call svd.solve(b).' },
    seeAlso: ['Eigen::ComputeThinU', 'Eigen::ComputeThinV', 'Eigen::ColPivHouseholderQR'],
  },
  {
    name: 'Eigen::ComputeThinU',
    aliases: ['ComputeThinU'],
    lang: 'cpp',
    kind: 'constant',
    official: 'Used in JacobiSVD to indicate that the thin matrix U is to be computed.',
    source: 'Eigen documentation',
    when: 'You build a JacobiSVD and plan to call solve(). Combine it with ComputeThinV using |. Leave both out if you only need the singular values, which is cheaper.',
    example: { command: 'Eigen::JacobiSVD<Eigen::MatrixXd> svd(B, Eigen::ComputeThinU | Eigen::ComputeThinV);', says: 'Asks the SVD to keep the thin U and V matrices as well.' },
    seeAlso: ['Eigen::ComputeThinV', 'Eigen::JacobiSVD'],
  },
  {
    name: 'Eigen::ComputeThinV',
    aliases: ['ComputeThinV'],
    lang: 'cpp',
    kind: 'constant',
    official: 'Used in JacobiSVD to indicate that the thin matrix V is to be computed.',
    source: 'Eigen documentation',
    when: 'The partner of ComputeThinU: pass both, joined with |, when you want svd.solve().',
    example: { command: 'Eigen::JacobiSVD<Eigen::MatrixXd> svd(B, Eigen::ComputeThinU | Eigen::ComputeThinV);', says: 'Asks the SVD to keep the thin U and V matrices as well.' },
    seeAlso: ['Eigen::ComputeThinU', 'Eigen::JacobiSVD'],
  },
  {
    name: 'Eigen::SelfAdjointEigenSolver',
    aliases: ['SelfAdjointEigenSolver'],
    lang: 'cpp',
    kind: 'class',
    official: 'Computes eigenvalues and eigenvectors of selfadjoint matrices',
    source: 'Eigen documentation',
    when: 'You want the natural axes of a symmetric matrix, such as the directions and sizes of a covariance ellipse. It only reads one triangle, so it silently gives wrong answers for a matrix that is not symmetric.',
    flags: [
      ['<MatrixType>', 'the matrix type, such as Eigen::Matrix3d'],
      ['eigenvalues()', 'the eigenvalues, smallest first'],
      ['eigenvectors()', 'the matching eigenvectors, one per column'],
      ['info()', 'Eigen::Success if it worked'],
    ],
    example: { command: 'const Eigen::SelfAdjointEigenSolver<Eigen::Matrix3d> es(P);  std::cout << es.eigenvalues();', says: 'Finds the three eigenvalues of the covariance P and prints them, smallest first.' },
    seeAlso: ['Eigen::JacobiSVD', 'Eigen::Success'],
  },
  {
    name: 'Eigen::Success',
    aliases: ['Success'],
    lang: 'cpp',
    kind: 'constant',
    official: 'Computation was successful.',
    source: 'Eigen documentation',
    when: 'Compare a decomposition info() against it before using the result. Eigen decompositions do not throw on failure; the only sign is that info() is not Success.',
    example: { command: 'if (llt.info() != Eigen::Success) { /* not positive definite */ }', says: 'Catches a failed Cholesky factoring before its garbage result is used.' },
    seeAlso: ['Eigen::LLT', 'Eigen::LDLT'],
  },
  // ---------------------------------------------------------------- Eigen: geometry
  {
    name: 'Eigen::Quaterniond',
    aliases: ['Quaterniond'],
    lang: 'cpp',
    kind: 'type',
    official: 'double precision quaternion type',
    source: 'Eigen documentation',
    when: 'You store an attitude (which way a spacecraft points) or a rotation. The four-number constructor takes w first, Quaterniond(w, x, y, z), but it is stored and printed by coeffs() as x, y, z, w. A new one is not initialized; start from Identity().',
    flags: [
      ['w(), x(), y(), z()', 'the four parts'],
      ['vec()', 'the vector part (x, y, z)'],
      ['coeffs()', 'all four, in storage order x, y, z, w'],
      ['normalized(), normalize()', 'a length-1 copy; make this one length 1'],
      ['conjugate(), inverse()', 'the reverse turn'],
      ['toRotationMatrix()', 'the same turn as a Matrix3d'],
      ['slerp(t, q2)', 'smoothly blend toward q2, t from 0 to 1'],
      ['angularDistance(q2)', 'the angle between two attitudes'],
      ['q * v', 'rotate a Vector3d by q'],
    ],
    example: { command: 'const Eigen::Quaterniond q(Eigen::AngleAxisd(M_PI / 2, Eigen::Vector3d::UnitZ()));', says: 'Makes a quaternion for a 90 degree turn about the z-axis.' },
    seeAlso: ['Eigen::Quaterniond::Identity', 'Eigen::AngleAxisd', 'Eigen::Matrix3d'],
  },
  {
    name: 'Eigen::Quaterniond::Identity',
    aliases: ['Quaterniond::Identity'],
    lang: 'cpp',
    kind: 'function',
    official: 'Returns a quaternion representing an identity rotation',
    source: 'Eigen documentation',
    when: 'You mean "no rotation yet", such as the starting attitude of a filter. Use it instead of a bare Quaterniond, which holds garbage.',
    example: { command: 'Eigen::Quaterniond q = Eigen::Quaterniond::Identity();', says: 'Sets q to w = 1, x = y = z = 0: pointing straight ahead, no turn.' },
    seeAlso: ['Eigen::Quaterniond'],
  },
  {
    name: 'Eigen::AngleAxisd',
    aliases: ['AngleAxisd'],
    lang: 'cpp',
    kind: 'type',
    official: 'double precision angle-axis type',
    source: 'Eigen documentation',
    when: 'You describe a turn the way people think of it: this many radians about this axis. The axis must have length 1; pass a vector through normalized() first, or the rotation comes out wrong. The angle is in radians, not degrees.',
    flags: [
      ['(angle, axis)', 'the turn in radians and the unit axis'],
      ['angle(), axis()', 'read the two back'],
      ['toRotationMatrix()', 'the same turn as a Matrix3d'],
      ['AngleAxisd(q)', 'recover angle and axis from a quaternion'],
    ],
    example: { command: 'const Eigen::AngleAxisd roll(30.0 * M_PI / 180.0, Eigen::Vector3d::UnitX());', says: 'Describes a 30 degree roll about the x-axis.' },
    seeAlso: ['Eigen::Quaterniond', 'Eigen::Vector3d::UnitX'],
  },
  {
    name: 'Eigen::Translation3d',
    aliases: ['Translation3d'],
    lang: 'cpp',
    kind: 'type',
    official: 'Represents a translation transformation',
    source: 'Eigen documentation',
    when: 'You describe a pure move in 3D, almost always to combine with a rotation into an Isometry3d. The order matters: the rightmost part is applied first.',
    flags: [
      ['(x, y, z)', 'the move along each axis'],
      ['* rotation', 'combine with a turn to make a rigid transform'],
    ],
    example: { command: 'const Eigen::Isometry3d T = Eigen::Translation3d(0.5, 0.0, 0.2) * q;', says: 'Makes a transform that turns by q and then moves by (0.5, 0, 0.2).' },
    seeAlso: ['Eigen::Isometry3d', 'Eigen::Quaterniond'],
  },
  {
    name: 'Eigen::Isometry3d',
    aliases: ['Isometry3d'],
    lang: 'cpp',
    kind: 'type',
    official: 'Represents an homogeneous transformation in a N dimensional space',
    source: 'Eigen documentation',
    when: 'You need a rigid transform: a turn plus a move that keeps every length, such as camera to body or body to world. Read chains right to left. Its inverse is cheap because Eigen knows it is only a turn and a move.',
    flags: [
      ['translation()', 'the move part, as a Vector3d'],
      ['linear(), rotation()', 'the turn part, as a Matrix3d'],
      ['matrix()', 'the whole thing as a 4 by 4 matrix'],
      ['inverse()', 'the transform that undoes it'],
      ['T * p', 'apply it to a point'],
    ],
    example: { command: 'const Eigen::Vector3d p_world = T_world_cam * p_cam;', says: 'Takes a point seen by the camera and gives where it is in the world frame.' },
    seeAlso: ['Eigen::Translation3d', 'Eigen::Matrix4d', 'Eigen::Quaterniond'],
  },
  // ---------------------------------------------------------------- Eigen: extras
  {
    name: 'Eigen::AutoDiffScalar',
    aliases: ['AutoDiffScalar'],
    lang: 'cpp',
    kind: 'class',
    official: 'A scalar type replacement with automatic differentiation capability',
    source: 'Eigen documentation',
    when: 'You want exact derivatives (a Jacobian) of a function without working them out by hand: use it in place of double and every result carries its derivatives along. It lives in the unsupported module, <unsupported/Eigen/AutoDiff>.',
    flags: [
      ['<DerType>', 'the vector type that holds the derivatives'],
      ['AD(value, n, i)', 'a value that is input number i of n'],
      ['value()', 'the ordinary number'],
      ['derivatives()', 'the derivatives with respect to each input'],
    ],
    example: { command: 'using AD = Eigen::AutoDiffScalar<Eigen::Vector3d>;', says: 'Names a number type that tracks derivatives with respect to three inputs.' },
    seeAlso: ['Eigen::Vector3d'],
  },
  {
    name: 'Eigen::internal::set_is_malloc_allowed',
    aliases: ['set_is_malloc_allowed'],
    lang: 'cpp',
    kind: 'function',
    official: 'EIGEN_RUNTIME_NO_MALLOC - if defined, a new switch is introduced which can be turned on and off by calling set_is_malloc_allowed(bool). If malloc is not allowed and Eigen tries to allocate memory dynamically anyway, an assertion failure results.',
    source: 'Eigen documentation',
    when: 'A test should prove that a real-time loop never allocates heap memory. It only does anything when you compile with EIGEN_RUNTIME_NO_MALLOC defined, and it lives in Eigen::internal, so keep it in tests.',
    flags: [
      ['false', 'forbid allocation from here on'],
      ['true', 'allow it again'],
    ],
    example: { command: 'Eigen::internal::set_is_malloc_allowed(false);  step(state, dt);  Eigen::internal::set_is_malloc_allowed(true);', says: 'Runs step with allocation forbidden; if anything inside allocates, an assertion fires.' },
    seeAlso: ['Eigen::MatrixXd'],
  },
  // ---------------------------------------------------------------- pybind11
  {
    name: 'PYBIND11_MODULE',
    lang: 'cpp',
    kind: 'macro',
    official: 'This macro creates the entry point that will be invoked when the Python interpreter imports an extension module.',
    source: 'pybind11 documentation',
    when: 'You turn C++ code into a module Python can import. The first name must match the name of the built file and is written without quotes; the second is the module object you add functions and classes to.',
    flags: [
      ['name', 'the module name Python imports, not in quotes'],
      ['m', 'the module object'],
      ['m.def("name", &func, ...)', 'add a function'],
      ['m.doc() = "..."', 'set the module help text'],
    ],
    example: { command: 'PYBIND11_MODULE(gnc_core, m) { m.def("rk4_step", &rk4_step, py::arg("state"), py::arg("dt")); }', says: 'Makes a module that Python loads with import gnc_core, holding one function rk4_step.' },
    seeAlso: ['py::arg', 'py::class_'],
  },
  {
    name: 'py::arg',
    lang: 'cpp',
    kind: 'class',
    official: 'Annotation for arguments',
    source: 'pybind11 documentation',
    when: 'You give a bound function its argument names, so Python can call it with keywords like dt=1.0 and help() shows real names. Add = value to give a default.',
    flags: [
      ['("name")', 'the name Python sees'],
      ['= value', 'a default value'],
    ],
    example: { command: 'm.def("propagate", &propagate, py::arg("state"), py::arg("dt"), py::arg("n_steps"));', says: 'Lets Python call propagate(x0, dt=1.0, n_steps=100) with the arguments named.' },
    seeAlso: ['PYBIND11_MODULE', 'py::init'],
  },
  {
    name: 'py::class_',
    lang: 'cpp',
    kind: 'class',
    official: 'py::class_ creates bindings for a C++ class or struct-style data structure.',
    source: 'pybind11 documentation',
    when: 'You want a C++ struct or class to show up in Python as a class. Chain .def calls to add its constructor, methods and fields.',
    flags: [
      ['<Type>', 'the C++ class to expose'],
      ['(m, "Name")', 'the module and the class name Python sees'],
      ['.def(py::init<...>())', 'a constructor'],
      ['.def_readwrite("field", &Type::field)', 'a field Python can read and set'],
    ],
    example: { command: 'py::class_<Vehicle>(m, "Vehicle").def(py::init<double, double>(), py::arg("mass"), py::arg("cda"));', says: 'Makes a Python class Vehicle that you build with Vehicle(mass=500.0, cda=0.8).' },
    seeAlso: ['py::init', 'PYBIND11_MODULE'],
  },
  {
    name: 'py::init',
    lang: 'cpp',
    kind: 'function',
    official: "init() is a convenience function that takes the types of a constructor's parameters as template arguments and wraps the corresponding constructor (see the Custom constructors section for details).",
    source: 'pybind11 documentation',
    when: 'Inside a py::class_, to expose one of the class constructors to Python. The types in the angle brackets must match a real constructor, or it does not compile.',
    flags: [['<Types...>', 'the constructor parameter types, in order']],
    example: { command: '.def(py::init<double, double>(), py::arg("mass"), py::arg("cda"))', says: 'Exposes the constructor that takes two doubles, with argument names mass and cda.' },
    seeAlso: ['py::class_', 'py::arg'],
  },
  {
    name: 'py::array',
    lang: 'cpp',
    kind: 'class',
    official: 'By exchanging py::buffer with py::array in the above snippet, we can restrict the function so that it only accepts NumPy arrays (rather than any type of Python object satisfying the buffer protocol).',
    source: 'pybind11 documentation',
    when: 'In the lessons it appears for its flags, which go in the second slot of py::array_t to say what layout you need. With forcecast, pybind11 converts or copies the input to match instead of refusing it.',
    flags: [
      ['py::array::c_style', 'require row-by-row (C order) storage with no gaps'],
      ['py::array::forcecast', 'convert the input if it does not already match'],
    ],
    example: { command: 'void g_to_si(py::array_t<double, py::array::c_style | py::array::forcecast> samples);', says: 'Accepts any NumPy array, turned into C-ordered doubles if needed.' },
    seeAlso: ['py::array_t'],
  },
  {
    name: 'py::array_t',
    lang: 'cpp',
    kind: 'class',
    official: 'In many situations, we want to define a function which only accepts a NumPy array of a certain data type. This is possible via the py::array_t<T> template.',
    source: 'pybind11 documentation',
    when: 'Large arrays cross between Python and C++: take one as input without copying, or allocate one once in C++ and fill it for Python to use. Hold the GIL (do not release it) while creating or touching one.',
    flags: [
      ['<T>', 'the number type, such as double'],
      ['<T, flags>', 'layout rules from py::array, such as c_style | forcecast'],
      ['({rows, cols})', 'allocate a new array of that shape'],
      ['shape(i)', 'the size along axis i'],
      ['mutable_data()', 'a pointer you can write through'],
      ['unchecked<N>(), mutable_unchecked<N>()', 'fast element access with no bounds checks'],
    ],
    example: { command: 'py::array_t<double> out({n_steps + 1, 6});', says: 'Allocates a NumPy array with n_steps + 1 rows and 6 columns, ready to fill.' },
    seeAlso: ['py::array', 'Eigen::Map', 'py::ssize_t'],
  },
  {
    name: 'py::array::c_style',
    aliases: ['array::c_style'],
    lang: 'cpp',
    kind: 'constant',
    official: 'Sometimes, it can be useful to require a function to only accept dense arrays using either the C (row-major) or Fortran (column-major) ordering. This can be accomplished via a second template argument with values py::array::c_style or py::array::f_style.',
    source: 'pybind11 documentation (docs/advanced/pycpp/numpy.rst)',
    when: 'Your C++ code reads a NumPy array as one plain block of numbers, row after row, for example through an Eigen::Map with RowMajor. It goes in the second slot of py::array_t and makes sure the data arrives in C order with no gaps. Combine it with py::array::forcecast using |, so an array in another layout is copied into C order instead of being refused.',
    example: { command: 'void load_states(py::array_t<double, py::array::c_style | py::array::forcecast> states);', says: 'Accepts a NumPy array and guarantees the C++ side sees doubles stored row by row, copying first if needed.' },
    seeAlso: ['py::array_t', 'py::array::forcecast', 'Eigen::RowMajor'],
  },
  {
    name: 'py::array::forcecast',
    aliases: ['array::forcecast'],
    lang: 'cpp',
    kind: 'constant',
    official: 'The py::array::forcecast argument is the default value of the second template parameter, and it ensures that non-conforming arguments are converted into an array satisfying the specified requirements instead of trying the next function overload.',
    source: 'pybind11 documentation (docs/advanced/pycpp/numpy.rst)',
    when: 'You want your function to accept a NumPy array even when its number type or layout is not the one you asked for, such as integers or a Fortran-ordered array. pybind11 then converts it, which may mean a full copy. It is already on when the second slot of py::array_t is left out; write it out again when you add py::array::c_style, because the flags you give replace the default.',
    example: { command: 'void load_states(py::array_t<double, py::array::c_style | py::array::forcecast> states);', says: 'A Python list of ints or a column-major array is converted to C-ordered doubles instead of being rejected.' },
    seeAlso: ['py::array_t', 'py::array::c_style'],
  },
  {
    name: 'py::gil_scoped_release',
    lang: 'cpp',
    kind: 'class',
    official: 'The classes gil_scoped_release and gil_scoped_acquire can be used to acquire and release the global interpreter lock in the body of a C++ function call.',
    source: 'pybind11 documentation',
    when: 'A long pure-C++ calculation should let other Python threads run at the same time. The lock is released when the object is made and taken back at the closing brace. Inside that scope, never touch a Python object, py::array_t included.',
    example: { command: 'py::gil_scoped_release release;  // other Python threads may run now', says: 'Releases the Global Interpreter Lock until the end of the enclosing braces.' },
    seeAlso: ['py::array_t'],
  },
  {
    name: 'py::ssize_t',
    lang: 'cpp',
    kind: 'type',
    official: 'Py_ssize_t is a signed integral type such that sizeof(Py_ssize_t) == sizeof(size_t).',
    source: 'CPython header pyport.h (py::ssize_t is the pybind11 name for Py_ssize_t)',
    when: 'For loop counters and sizes when walking a NumPy array, because shape() and the index functions use this signed type. Using int or std::size_t instead can give signed-unsigned warnings.',
    example: { command: 'for (py::ssize_t i = 0; i < in.shape(0); ++i) res(i) = coast(veh, in(i), dt);', says: 'Walks every entry along the first axis of a NumPy array.' },
    seeAlso: ['py::array_t'],
  },
]
