import type { CommandRef } from './types'

export const COMMANDS: CommandRef[] = [
  {
    name: 'pwd',
    kind: 'builtin',
    official: 'Print the name of the current working directory.',
    source: 'bash built-in help',
    when: 'You want to know which folder you are in right now. Run it whenever you are not sure where you have landed; it changes nothing.',
    flags: [['-P', 'print the real folder, with any shortcut links followed to where they really point']],
    example: { command: 'pwd', says: 'Prints the full address of the folder you are in, such as /home/you/project.' },
    seeAlso: ['cd', 'ls'],
  },
  {
    name: 'ls',
    kind: 'file',
    official: 'list directory contents',
    source: 'ls manual page (GNU coreutils)',
    when: 'You want to see what is inside a folder. With no name it lists the folder you are in; give it a folder name to look somewhere else.',
    flags: [
      ['-a', 'show hidden files too (names that start with a dot)'],
      ['-l', 'long listing: type, permissions, owner, size and name, one per line'],
      ['-la', 'the long listing with hidden files included'],
      ['-ltr', 'long listing sorted by time, oldest first, so the newest file is at the bottom'],
      ['-d', 'show the folder itself instead of what is inside it'],
    ],
    example: {
      command: 'ls -la',
      says: 'Lists everything in the folder, hidden files like .env included, one line each with its permissions, owner and size.',
    },
    seeAlso: ['cd', 'pwd', 'find', 'stat'],
  },
  {
    name: 'cd',
    kind: 'builtin',
    official: 'Change the shell working directory.',
    source: 'bash built-in help',
    when: 'You want to move into another folder, so the commands you type next work there. On its own, with nothing after it, it takes you to your home folder.',
    flags: [
      ['..', 'go up one level, to the folder that holds this one'],
      ['~', 'go to your home folder'],
      ['-', 'jump back to the folder you were in before'],
    ],
    example: { command: 'cd mission-logs', says: 'Moves you into the mission-logs folder. The prompt changes to end in mission-logs $.' },
    seeAlso: ['pwd', 'ls', 'mkdir'],
  },
  {
    name: 'mkdir',
    kind: 'file',
    official: 'make directories',
    source: 'mkdir manual page (GNU coreutils)',
    when: 'You need a new folder. It only makes the folder; use cd to move into it afterwards.',
    flags: [['-p', 'make every missing folder along the path, and do nothing if it already exists']],
    example: { command: 'mkdir -p logs/2026/launch', says: 'Makes logs, then 2026 inside it, then launch inside that, all in one go.' },
    seeAlso: ['cd', 'rmdir'],
  },
  {
    name: 'rmdir',
    kind: 'file',
    official: 'remove empty directories',
    source: 'rmdir manual page (GNU coreutils)',
    when: 'You want to delete a folder you believe is empty. If anything is still inside, it refuses and leaves the folder alone, which makes it the safe choice.',
    example: {
      command: 'rmdir old-drafts',
      says: 'Deletes the empty folder old-drafts. If something is inside, it prints "Directory not empty" and deletes nothing.',
    },
    seeAlso: ['rm', 'mkdir'],
  },
  {
    name: 'touch',
    kind: 'file',
    official: 'change file timestamps',
    source: 'touch manual page (GNU coreutils)',
    when: 'You want a new, empty file to exist, for example to fill in later. On a file that already exists it only updates the time it was last changed, and leaves what is inside alone.',
    example: { command: 'touch flight-plan.txt', says: 'Makes an empty file called flight-plan.txt. ls now shows it.' },
    seeAlso: ['echo', 'mkdir'],
  },
  {
    name: 'cat',
    kind: 'text',
    official: 'concatenate files and print on the standard output',
    source: 'cat manual page (GNU coreutils)',
    when: 'You want to print a short file on the screen, or join several files one after the other. For long files, less, head or tail are easier to read.',
    flags: [
      ['-n', 'number each line'],
      ['-A', 'show hidden characters: $ at each line end, ^M for a Windows line ending, ^I for a tab'],
      ['-v', 'show control characters as visible symbols instead of sending them to the terminal'],
    ],
    example: { command: 'cat pre-flight.txt', says: 'Prints every line of pre-flight.txt: fuel, power, radio, weather, go.' },
    seeAlso: ['less', 'head', 'tail', 'echo'],
  },
  {
    name: 'echo',
    kind: 'builtin',
    official: 'Write arguments to the standard output.',
    source: 'bash built-in help',
    when: 'You want to print a message, or send a line of text into a file with > or >>. It is also a safe way to test a wildcard, because it only prints what the pattern turned into.',
    example: {
      command: 'echo "Launch at dawn" > flight-plan.txt',
      says: 'Writes the line Launch at dawn into flight-plan.txt, replacing whatever was there. Nothing is printed on the screen.',
    },
    seeAlso: ['printf', 'cat', 'tee'],
  },
  {
    name: 'cp',
    kind: 'file',
    official: 'copy files and directories',
    source: 'cp manual page (GNU coreutils)',
    when: 'You want a second copy of a file or folder, with the original kept where it is. The source comes first, the destination second. If the destination file already exists, cp replaces it without asking.',
    flags: [
      ['-r', 'copy a folder and everything inside it'],
      ['-i', 'ask before replacing a file that is already there'],
      ['-n', 'never replace a file that is already there'],
    ],
    example: { command: 'cp draft.txt backup.txt', says: 'Makes backup.txt, an exact copy of draft.txt. Both files now exist.' },
    seeAlso: ['mv', 'rm', 'rsync'],
  },
  {
    name: 'mv',
    kind: 'file',
    official: 'move (rename) files',
    source: 'mv manual page (GNU coreutils)',
    when: 'You want to move a file to another folder, or give it a new name; to the computer those are the same job. If a file with the new name already exists, mv replaces it without asking.',
    flags: [
      ['-i', 'ask before replacing a file that is already there'],
      ['-n', 'never replace a file that is already there ("no clobber")'],
    ],
    example: {
      command: 'mv draft.txt archive/old-draft.txt',
      says: 'Moves draft.txt into the archive folder and renames it old-draft.txt on the way.',
    },
    seeAlso: ['cp', 'rm'],
  },
  {
    name: 'rm',
    kind: 'file',
    official: 'remove files or directories',
    source: 'rm manual page (GNU coreutils)',
    when: 'You want to delete a file, or with -r a whole folder. There is no recycle bin and no "are you sure?", so run ls on the same name first and read it before you press Enter.',
    flags: [
      ['-r', 'delete a folder and everything inside it, all the way down'],
      ['-i', 'ask yes or no before each file'],
      ['-f', 'never ask and never complain; it also hides a typo in the name, so use it with care'],
    ],
    example: { command: 'rm -r build', says: 'Deletes the build folder, every file in it and every folder inside it. They cannot be brought back.' },
    seeAlso: ['rmdir', 'mv', 'find'],
  },
  {
    name: 'head',
    kind: 'text',
    official: 'output the first part of files',
    source: 'head manual page (GNU coreutils)',
    when: 'You want a quick look at the top of a file, such as its header line, without printing all of it. With no number it shows 10 lines.',
    flags: [
      ['-n', 'how many lines to show, as in head -n 3'],
      ['-c', 'how many bytes (characters) to show instead of lines'],
    ],
    example: { command: 'head -n 2 pre-flight.txt', says: 'Prints only the first two lines: fuel and power.' },
    seeAlso: ['tail', 'less', 'cat'],
  },
  {
    name: 'tail',
    kind: 'text',
    official: 'output the last part of files',
    source: 'tail manual page (GNU coreutils)',
    when: 'You want the end of a file, where a log keeps its newest lines. With a plus sign, as in -n +2, it starts from that line instead, which drops a header line.',
    flags: [
      ['-n', 'how many lines from the end, as in tail -n 5'],
      ['-n +2', 'start at line 2 and print to the end, skipping the first line'],
      ['-f', 'keep watching and print new lines as they are added'],
      ['-F', 'like -f, but keeps going even if the log is swapped for a new file'],
    ],
    example: { command: 'tail -n 2 launch.log', says: 'Prints the last two lines of launch.log, the newest events.' },
    seeAlso: ['head', 'less'],
  },
  {
    name: 'wc',
    kind: 'text',
    official: 'print newline, word, and byte counts for each file',
    source: 'wc manual page (GNU coreutils)',
    when: 'You want to count things: lines, words or bytes. Counting lines is the common one, because in a log one line is usually one event.',
    flags: [
      ['-l', 'count lines only'],
      ['-w', 'count words only'],
      ['-c', 'count bytes only'],
    ],
    example: { command: 'wc -l launch.log', says: 'Prints 6 launch.log: the file has six lines.' },
    seeAlso: ['grep', 'head', 'sort'],
  },
  {
    name: 'less',
    kind: 'text',
    official: 'opposite of more',
    source: 'less manual page',
    when: 'You want to read a long file one screen at a time without opening an editor. It opens instantly even on huge files, because it only reads what fits on the screen.',
    flags: [
      ['-N', 'show line numbers'],
      ['-S', 'do not wrap long lines; scroll sideways instead (handy for wide CSV files)'],
    ],
    example: {
      command: 'less launch.log',
      says: 'Opens launch.log one screen at a time. Press space for the next screen, type /ERROR to search, n for the next match, and q to quit.',
    },
    seeAlso: ['cat', 'head', 'tail'],
  },
  {
    name: 'file',
    kind: 'file',
    official: 'determine file type',
    source: 'file manual page',
    when: "You have a file and are not sure what is inside: text, a picture or a program. Check before you cat an unknown file, because printing a program's bytes can scramble your terminal.",
    example: {
      command: 'file mission-photo.jpg',
      says: 'Prints what kind of file it is, such as mission-photo.jpg: JPEG image data, followed by a few details.',
    },
    seeAlso: ['cat', 'od', 'stat'],
  },
  {
    name: 'grep',
    kind: 'text',
    official: 'print lines that match patterns',
    source: 'grep manual page (GNU grep)',
    when: 'You want only the lines that contain some text, like every ERROR in a log. The text to find comes first, then the file. It cares about capitals unless you add -i.',
    flags: [
      ['-i', 'ignore capitals: ERROR, Error and error all match'],
      ['-n', 'show the line number in front of each match'],
      ['-r', 'search every file in a folder and in the folders inside it'],
      ['-v', 'keep the lines that do not match'],
      ['-c', 'print how many lines match instead of the lines'],
      ['-l', 'print only the names of the files that match'],
      ['-q', 'print nothing; the exit status says found (0) or not found (1)'],
      ['-E', 'extended patterns, where + ? | and ( ) have special jobs'],
    ],
    example: {
      command: 'grep -rn TODO src',
      says: 'Searches every file under src and prints each line containing TODO, with its file name and line number in front.',
    },
    seeAlso: ['find', 'sed', 'awk', 'wc'],
  },
  {
    name: 'sort',
    kind: 'text',
    official: 'sort lines of text files',
    source: 'sort manual page (GNU coreutils)',
    when: 'You want lines in order, alphabetical or by number. It also brings repeated lines together, which is why uniq nearly always comes after it.',
    flags: [
      ['-r', 'reverse: last or biggest first'],
      ['-n', 'compare numbers as numbers, so 9 comes before 10'],
      ['-u', 'keep one of each repeated line'],
      ['-h', 'sort human-readable sizes such as 8.0K and 2.0M'],
      ['-t', 'the character between fields, as in -t ,'],
      ['-k', 'sort by one field, as in -k 2'],
    ],
    example: {
      command: 'sort visitors.txt | uniq -c | sort -rn',
      says: 'Counts how many times each city appears in visitors.txt and lists the most common first, like 4 lagos.',
    },
    seeAlso: ['uniq', 'cut', 'head'],
  },
  {
    name: 'uniq',
    kind: 'text',
    official: 'report or omit repeated lines',
    source: 'uniq manual page (GNU coreutils)',
    when: 'You want to squeeze repeated lines into one, or count them. It only compares each line with the line right above it, so sort the input first.',
    flags: [
      ['-c', 'put the count of each run of repeats in front of the line'],
      ['-d', 'show only the lines that were repeated'],
      ['-u', 'show only the lines that appeared once'],
    ],
    example: {
      command: 'sort colors.txt | uniq -c',
      says: 'Prints each color once with how many times it appeared, such as 2 blue and 3 red.',
    },
    seeAlso: ['sort', 'cut'],
  },
  {
    name: 'cut',
    kind: 'text',
    official: 'remove sections from each line of files',
    source: 'cut manual page (GNU coreutils)',
    when: 'You want one column out of data like a CSV file. Always give the separator with -d; without it, cut looks for tabs and prints every line whole.',
    flags: [
      ['-d', 'the separator between fields, as in -d ,'],
      ['-f', 'which fields to keep: -f 2, -f 1,3 or -f 2-4'],
      ['-c', 'keep characters by position instead, as in -c 1-10'],
    ],
    example: { command: 'cut -d , -f 2 people.csv', says: 'Prints the second field of every line: name, ada, lin.' },
    seeAlso: ['awk', 'sort', 'paste'],
  },
  {
    name: 'tr',
    kind: 'text',
    official: 'translate or delete characters',
    source: 'tr manual page (GNU coreutils)',
    when: 'You want to swap one character for another everywhere in some text, such as commas for new lines or capitals for small letters. It reads only text coming in through a pipe, not a file name.',
    flags: [
      ['-d', 'delete these characters instead of swapping them'],
      ['-s', 'squeeze a run of the same character into one'],
    ],
    example: { command: 'echo "MARS BASE" | tr "A-Z" "a-z"', says: 'Prints mars base: every capital letter swapped for its small letter.' },
    seeAlso: ['sed', 'cut'],
  },
  {
    name: 'find',
    kind: 'file',
    official: 'search for files in a directory hierarchy',
    source: 'find manual page (GNU findutils)',
    when: 'You want to know where a file is, anywhere inside a folder and the folders below it. Put wildcard patterns in quotes, so the star reaches find instead of being used up by the shell.',
    flags: [
      ['-name', 'match the whole name, wildcards allowed: -name "*.md"'],
      ['-iname', 'like -name, but ignores capitals'],
      ['-type', 'd for folders only, f for ordinary files only'],
      ['-exec', 'run a command on each match, where {} is the file name: -exec rm {} \\;'],
      ['-delete', 'delete every match (run the search without it first and read the list)'],
    ],
    example: {
      command: 'find . -iname "*.jpg"',
      says: 'Lists every photo ending in .jpg or .JPG in this folder and every folder inside it, such as ./trip/day1/Beach.JPG.',
    },
    seeAlso: ['grep', 'xargs', 'ls'],
  },
  {
    name: 'xargs',
    kind: 'text',
    official: 'build and execute command lines from standard input',
    source: 'xargs manual page (GNU findutils)',
    when: 'You have a list coming down a pipe, and the next command (like rm, mkdir or mv) only works on arguments, not piped text. xargs turns the list into arguments. It splits at every space, so names with spaces break it.',
    flags: [
      ['-n 1', 'run the command once for each item'],
      ['-I {}', 'put each item where {} is, one run per item'],
      ['-t', 'print each command just before running it'],
      ['-0', 'items are separated by a null character, to pair with find -print0 (safe with spaces)'],
      ['-r', 'do not run the command at all if the list is empty'],
      ['-P', 'run several commands at the same time'],
    ],
    example: {
      command: 'find build -name "*.tmp" | xargs rm',
      says: 'Finds every .tmp file under build and deletes them all with one rm command.',
    },
    seeAlso: ['find', 'rm'],
  },
  {
    name: 'sed',
    kind: 'text',
    official: 'stream editor for filtering and transforming text',
    source: 'sed manual page (GNU sed)',
    when: 'You want find-and-replace on text from the command line, or to delete or print some lines. It prints the result and leaves the file alone unless you add -i, so check the output first.',
    flags: [
      ['s/old/new/', 'substitute: replace the first old on each line with new'],
      ['g', 'after the last slash: replace every match on the line, not just the first'],
      ['/pattern/d', 'delete the lines that match'],
      ['-n', 'print nothing unless asked; -n "/pattern/p" prints only the matching lines'],
      ['-i', 'change the file itself instead of printing (there is no undo)'],
      ['-E', 'extended patterns, where + ? | and ( ) have special jobs'],
    ],
    example: {
      command: "sed -i 's/localhost/db.internal/g' settings.conf",
      says: 'Replaces every localhost with db.internal inside settings.conf itself. It prints nothing, so check with cat.',
    },
    seeAlso: ['grep', 'tr', 'awk'],
  },
  {
    name: 'awk',
    kind: 'text',
    official: 'pattern scanning and text processing language',
    source: 'awk manual page (mawk, the awk installed here)',
    when: 'You want to work with columns: pick them in any order, add them up, or keep the rows where one column has a certain value. It splits each line at spaces unless you give it another separator.',
    flags: [
      ["'{print $2}'", 'print the second field of every line ($1 is the first, $NF the last)'],
      ['-F', 'the field separator, as in -F ,'],
      ['-v', 'pass a value in from the shell, as in -v limit=5'],
      ['-f', 'read the awk program from a file'],
    ],
    example: {
      command: "awk -F , '{print $3, $2}' people.csv",
      says: 'Prints the third and second columns of people.csv in that order, such as oslo ada.',
    },
    seeAlso: ['cut', 'sort', 'sed'],
  },
  {
    name: 'tee',
    kind: 'text',
    official: 'read from standard input and write to standard output and files',
    source: 'tee manual page (GNU coreutils)',
    when: 'You want to see a result on the screen and save it in a file at the same time. Plain tee replaces the file, like >; add -a to add to the end instead.',
    flags: [['-a', 'add to the end of the file instead of replacing it']],
    example: {
      command: 'sort planets.txt | tee sorted.txt',
      says: 'Shows the sorted planet names on the screen and saves the same list in sorted.txt.',
    },
    seeAlso: ['echo', 'cat'],
  },
  {
    name: 'chmod',
    kind: 'file',
    official: 'change file mode bits',
    source: 'chmod manual page (GNU coreutils)',
    when: 'You want to change who may read, change or run a file, most often to make a script runnable with chmod +x.',
    flags: [
      ['+x', 'let the file run as a program'],
      ['755, 644', 'set all the permissions at once with numbers: 755 for scripts and folders, 644 for ordinary files'],
      ['u=rw,go-r', 'change permissions for the user (u), the group (g) and others (o)'],
      ['-R', 'change a folder and everything inside it; careful, chmod -R 644 takes x away from the folders too'],
    ],
    example: { command: 'chmod +x launch.sh', says: 'Makes launch.sh executable, so you can run it as ./launch.sh.' },
    seeAlso: ['ls', 'chown', 'stat'],
  },
  {
    name: 'chown',
    kind: 'file',
    official: 'change file owner and group',
    source: 'chown manual page (GNU coreutils)',
    when: 'You want a file or folder to belong to a different user or group. Giving files away to someone else needs administrator rights, so it usually runs with sudo.',
    flags: [['-R', 'change a folder and everything inside it']],
    example: {
      command: 'sudo chown -R you:crew mission-data',
      says: 'Makes the user you and the group crew the owners of mission-data and everything inside it.',
    },
    seeAlso: ['chmod', 'ls'],
  },
  {
    name: 'ln',
    kind: 'file',
    official: 'make links between files',
    source: 'ln manual page (GNU coreutils)',
    when: 'You want a second name for a file, or a shortcut that points to it from somewhere else. Most of the time you want -s, a symbolic link.',
    flags: [['-s', 'make a symbolic link: a small shortcut file that holds the path to the real one']],
    example: {
      command: 'ln -s runs/2026-09-29 latest',
      says: 'Makes a shortcut called latest that points to the runs/2026-09-29 folder. cd latest takes you there.',
    },
    seeAlso: ['readlink', 'ls', 'cp'],
  },
  {
    name: 'du',
    kind: 'file',
    official: 'estimate file space usage',
    source: 'du manual page (GNU coreutils)',
    when: 'You want to know how much disk space a folder or file takes, to find out what is filling up the disk.',
    flags: [
      ['-s', 'one total for each name you give'],
      ['-h', 'human-readable sizes such as 24K and 2.0M'],
      ['--max-depth=1', 'one line per folder, only one level down'],
    ],
    example: { command: 'du -sh telemetry', says: 'Prints the total size of the telemetry folder, such as 24K telemetry.' },
    seeAlso: ['df', 'ls', 'sort'],
  },
  {
    name: 'df',
    kind: 'file',
    official: 'report file system space usage',
    source: 'df manual page (GNU coreutils)',
    when: 'You want to know how much free space is left on a disk. Give it a path to ask about the disk that path lives on.',
    flags: [
      ['-h', 'human-readable sizes such as 7.9G'],
      ['-i', 'show free inodes (the slot every file needs) instead of free space'],
    ],
    example: { command: 'df -h .', says: 'Shows the size, the used space and the free space of the disk your current folder is on.' },
    seeAlso: ['du'],
  },
  {
    name: 'stat',
    kind: 'file',
    official: 'display file or file system status',
    source: 'stat manual page (GNU coreutils)',
    when: 'You want every detail the system keeps about a file: its size, permissions, owner, and the times it was last read and changed.',
    flags: [['-c', 'choose which details to print, as in -c "%a %n" for the permission number and the name']],
    example: {
      command: 'stat -c "%a %U %n" launch.sh',
      says: 'Prints the permission number, the owner and the name, such as 755 you launch.sh.',
    },
    seeAlso: ['ls', 'chmod', 'file'],
  },
  {
    name: 'diff',
    kind: 'text',
    official: 'compare files line by line',
    source: 'diff manual page (GNU diffutils)',
    when: 'You want to see exactly what changed between two versions of a file, or between two folders. It changes nothing; it only reports.',
    flags: [
      ['-u', 'unified format: - in front of removed lines, + in front of added ones (the format git uses)'],
      ['-r', 'compare whole folders, and the folders inside them'],
      ['-q', 'only say whether the files differ'],
      ['-w', 'ignore differences in spaces'],
    ],
    example: {
      command: 'diff -u flight-plan-v1.txt flight-plan-v2.txt',
      says: 'Prints the lines that changed, with - in front of each removed line and + in front of each added one. It prints nothing if the files are the same.',
    },
    seeAlso: ['patch'],
  },
  {
    name: 'patch',
    kind: 'text',
    official: 'apply a diff file to an original',
    source: 'patch manual page (GNU patch)',
    when: 'Someone sends you a diff instead of a whole file, and you want to make those changes to your copy. It edits your files, so try --dry-run first.',
    flags: [
      ['--dry-run', 'show what would happen without changing anything'],
      ['-R', 'undo a patch that was already applied'],
      ['-p1', 'strip the first folder from the paths inside the patch (needed for patches made by git)'],
    ],
    example: {
      command: 'patch flight-plan.txt < changes.diff',
      says: 'Applies the changes in changes.diff to flight-plan.txt. Any part that does not fit is saved in flight-plan.txt.rej.',
    },
    seeAlso: ['diff'],
  },
  {
    name: 'tar',
    kind: 'file',
    official: 'an archiving utility',
    source: 'tar manual page (GNU tar)',
    when: 'You want to pack a folder into one file to store or send it, or unpack one you were given. List an archive before you unpack it, because unpacking replaces files that have the same names.',
    flags: [
      ['-czf', 'create a new compressed archive with the name that follows'],
      ['-tzf', 'list what is inside a compressed archive'],
      ['-xzf', 'extract (unpack) a compressed archive'],
      ['-C', 'unpack into another folder'],
    ],
    example: {
      command: 'tar -czf mission-logs.tgz mission-logs',
      says: 'Packs the mission-logs folder and everything in it into one compressed file, mission-logs.tgz.',
    },
    seeAlso: ['rsync'],
  },
  {
    name: 'printf',
    kind: 'builtin',
    official: 'Formats and prints ARGUMENTS under control of the FORMAT.',
    source: 'bash built-in help',
    when: 'You want exact control over what gets printed: no new line unless you ask for one, and numbers or names laid out in a pattern. Unlike echo, it adds nothing you did not write.',
    flags: [
      ['%s', 'put the next argument here, as text'],
      ['%d', 'put the next argument here, as a whole number'],
      ['%03d', 'a whole number padded with zeros to three digits'],
      ['\\n', 'start a new line'],
    ],
    example: {
      command: 'printf "case_%03d\\n" 7',
      says: 'Prints case_007: the number 7 padded with zeros to three digits, then a new line.',
    },
    seeAlso: ['echo', 'seq'],
  },
  {
    name: 'seq',
    kind: 'text',
    official: 'print a sequence of numbers',
    source: 'seq manual page (GNU coreutils)',
    when: 'You want a list of numbers, one per line, often to drive a for loop.',
    example: {
      command: 'for i in $(seq 1 3); do touch "photo-$i.jpg"; done',
      says: 'seq 1 3 prints 1, 2 and 3, so the loop makes photo-1.jpg, photo-2.jpg and photo-3.jpg.',
    },
    seeAlso: ['printf'],
  },
  {
    name: 'column',
    kind: 'text',
    official: 'columnate lists',
    source: 'column manual page (util-linux)',
    when: 'You want text data lined up in neat columns so a person can read it. It is for looking at, not for feeding into other tools.',
    flags: [
      ['-t', 'make a table, lining up the columns'],
      ['-s', 'the separator between fields, as in -s ,'],
    ],
    example: { command: 'column -t -s , crew.csv', says: 'Shows crew.csv as a table, with each column lined up under its header.' },
    seeAlso: ['cut', 'paste', 'join'],
  },
  {
    name: 'paste',
    kind: 'text',
    official: 'merge lines of files',
    source: 'paste manual page (GNU coreutils)',
    when: 'You have two lists in separate files and want them side by side, line 1 next to line 1. It does not check that the lines really belong together.',
    flags: [
      ['-d', 'the separator to put between them, as in -d ,'],
      ['-s', 'join all the lines of one file into a single line'],
    ],
    example: {
      command: 'paste -d , names.txt scores.txt',
      says: 'Prints each name next to the score on the same line number, with a comma between, such as ada,97.',
    },
    seeAlso: ['join', 'cut', 'column'],
  },
  {
    name: 'join',
    kind: 'text',
    official: 'join lines of two files on a common field',
    source: 'join manual page (GNU coreutils)',
    when: 'You have two files that share a key, like an id, and want to merge their lines by that key. Both files must be sorted on that key first.',
    flags: [
      ['-t', 'the separator between fields, as in -t ,'],
      ['-a1', 'also keep lines from the first file that have no match (-a2 does the same for the second file)'],
    ],
    example: {
      command: 'join -t , crew.csv roles.csv',
      says: 'Merges each line of crew.csv with the line of roles.csv that starts with the same id, one combined line per match.',
    },
    seeAlso: ['paste', 'sort'],
  },
  {
    name: 'od',
    kind: 'text',
    official: 'dump files in octal and other formats',
    source: 'od manual page (GNU coreutils)',
    when: 'You want to see the exact bytes in a file, invisible ones included, when a file looks fine but a program says it is not.',
    flags: [['-c', 'show each byte as a character, with \\n for a new line and \\r for a Windows line ending']],
    example: {
      command: 'tail -c 1 data.csv | od -c',
      says: 'Shows the very last byte of data.csv. If it is \\n, the file ends with a new line.',
    },
    seeAlso: ['cat', 'file'],
  },
  {
    name: 'dd',
    kind: 'file',
    official: 'convert and copy a file',
    source: 'dd manual page (GNU coreutils)',
    when: 'You want to copy raw data in blocks, for example to make a test file of an exact size. Be careful: it overwrites whatever of= names completely, even a whole disk.',
    flags: [
      ['if=', 'the input file to read from'],
      ['of=', 'the output file to write to'],
      ['bs=', 'the size of each block, as in bs=64k'],
      ['count=', 'how many blocks to copy'],
    ],
    example: {
      command: 'dd if=/dev/zero of=test.bin bs=64k count=16',
      says: 'Makes test.bin out of 16 blocks of 64 KiB of zero bytes: exactly 1 MiB.',
    },
    seeAlso: ['cp', 'du'],
  },
  {
    name: 'basename',
    kind: 'file',
    official: 'strip directory and suffix from filenames',
    source: 'basename manual page (GNU coreutils)',
    when: 'You have a path and want only its last part, the name of the file or folder.',
    example: { command: 'basename /home/you/project', says: 'Prints project, the last part of the path.' },
    seeAlso: ['dirname', 'readlink'],
  },
  {
    name: 'dirname',
    kind: 'file',
    official: 'strip last component from file name',
    source: 'dirname manual page (GNU coreutils)',
    when: 'You have the path to a file and want the folder it is in.',
    example: {
      command: 'dirname /home/you/project/logs/run.log',
      says: 'Prints /home/you/project/logs: the same path with its last part removed.',
    },
    seeAlso: ['basename'],
  },
  {
    name: 'readlink',
    kind: 'file',
    official: 'print resolved symbolic links or canonical file names',
    source: 'readlink manual page (GNU coreutils)',
    when: 'You want to know where a shortcut (a symbolic link) really points, or the full absolute path of a file.',
    flags: [['-f', 'follow every link to the end and print the full real path']],
    example: {
      command: 'readlink -f latest',
      says: 'Prints the full real path that the latest link points to, such as /home/you/project/runs/2026-09-29.',
    },
    seeAlso: ['ln', 'basename', 'dirname', 'pwd'],
  },
  {
    name: 'mktemp',
    kind: 'file',
    official: 'create a temporary file or directory',
    source: 'mktemp manual page (GNU coreutils)',
    when: 'A script needs a scratch file or folder with a name nobody else is using. It makes one and prints its name, so save that name in a variable.',
    flags: [['-d', 'make a folder instead of a file']],
    example: {
      command: 'tmp=$(mktemp -d)',
      says: 'Makes a new, empty folder with a unique name, such as /tmp/tmp.k3Jd8s, and saves its path in the variable tmp.',
    },
    seeAlso: ['rm'],
  },
  {
    name: 'jq',
    kind: 'text',
    official: 'Command-line JSON processor',
    source: 'jq manual page',
    when: 'You want to read JSON, the text format many programs and web services use, or pull values out of it. It understands the structure, so it finds values by name instead of by position.',
    flags: [
      ['.', 'the whole input: jq . file.json prints it neatly and checks that it is valid'],
      ['-r', 'print plain text, without the JSON quote marks'],
      ['-c', 'print each result on one line'],
      ['-s', 'read every input into one big list'],
      ['-e', 'exit with status 1 if the result is null or false'],
      ['--arg', 'pass a value in from the shell, as in --arg name value'],
    ],
    example: {
      command: "jq -r '.status' mission.json",
      says: 'Prints the value of the status field in mission.json, such as OK, without quote marks.',
    },
    seeAlso: ['grep', 'sed', 'awk'],
  },
  {
    name: 'rsync',
    kind: 'file',
    official: 'a fast, versatile, remote (and local) file-copying tool',
    source: 'rsync manual page',
    when: 'You want to copy a folder to another place or another computer, and later copy only what changed. A slash at the end of the source means "what is inside", not the folder itself. With --delete it also removes files from the destination, so try -n first.',
    flags: [
      ['-a', 'copy everything inside, keeping times and permissions'],
      ['-v', 'list each file as it is copied'],
      ['-z', 'compress the data while it travels'],
      ['-P', 'show progress, and pick up where a stopped copy left off'],
      ['-n', 'dry run: show what would be copied and change nothing (also --dry-run)'],
      ['--delete', 'remove files from the destination that are no longer in the source'],
    ],
    example: {
      command: 'rsync -av mission-logs/ backup/mission-logs/',
      says: 'Copies everything in mission-logs into backup/mission-logs, listing each file. Run it again and only new or changed files are copied.',
    },
    seeAlso: ['cp', 'tar'],
  },
]
