import type { CommandRef } from './types'

export const COMMANDS: CommandRef[] = [
  /* ---------------------------------------------------------------- files */
  {
    name: 'chgrp',
    kind: 'file',
    official: 'change group ownership',
    source: 'chgrp manual page (GNU coreutils)',
    when: 'You want a file to belong to a different group, so the people in that group get the group permissions. You can only give a file to a group you are in yourself, unless you are root.',
    example: { command: 'chgrp flightops telemetry.csv', says: 'Makes flightops the owning group of telemetry.csv. ls -l now shows flightops in the group column.' },
    seeAlso: ['chown', 'chmod', 'id'],
  },
  {
    name: 'install',
    kind: 'file',
    official: 'copy files and set attributes',
    source: 'install manual page (GNU coreutils)',
    when: 'You want to copy a built program or file into place and set its permissions in the same step. It is what `make install` runs. Unlike cp, it replaces the file rather than writing into it.',
    flags: [
      ['-c', 'copy the file (it always copies; this old flag is accepted and ignored)'],
      ['-m MODE', 'set the permissions of the copy, such as 644 or 755'],
    ],
    example: { command: 'install -m 755 build/tracker ~/.local/bin/', says: 'Copies the tracker program into ~/.local/bin and makes it runnable by you and readable by everyone.' },
    seeAlso: ['cp', 'chmod', 'make'],
  },
  {
    name: 'namei',
    kind: 'file',
    official: 'follow a pathname until a terminal point is found',
    source: 'namei manual page (util-linux)',
    when: 'You get "Permission denied" on a file and want to see which folder along its path is blocking you. It prints every step of the path on its own line.',
    flags: [['-l', 'show the permissions and owner of every folder along the path, like ls -l']],
    example: { command: 'namei -l results/run_0001.log', says: 'Prints one line each for /, the folders down to results, and the file itself, with the permissions and owner of each.' },
    seeAlso: ['ls', 'chmod', 'stat'],
  },
  {
    name: 'gzip',
    kind: 'file',
    official: 'compress or expand files',
    source: 'gzip manual page (GNU gzip)',
    when: 'You want to make a file smaller to store or send it, such as a big log or a CSV. It replaces the file with a .gz version, and the original is gone unless you pass -k.',
    flags: [['-k', 'keep the original file next to the .gz']],
    example: { command: 'gzip -k telemetry.csv', says: 'Writes a smaller telemetry.csv.gz and keeps telemetry.csv as it was.' },
    seeAlso: ['gunzip', 'zcat', 'tar'],
  },
  {
    name: 'gunzip',
    kind: 'file',
    official: 'compress or expand files',
    source: 'gunzip manual page (GNU gzip)',
    when: 'You have a .gz file and want the original back. Like gzip, it replaces the file: the .gz is gone afterwards.',
    example: { command: 'gunzip telemetry.csv.gz', says: 'Turns telemetry.csv.gz back into telemetry.csv.' },
    seeAlso: ['gzip', 'zcat'],
  },
  {
    name: 'umount',
    kind: 'system',
    official: 'unmount filesystems',
    source: 'umount manual page (util-linux)',
    when: 'You are done with a disk, USB stick or network share and want to detach it safely, so everything waiting is written first. Note the spelling: umount, with no n. It fails with "target is busy" while any program still has a file open there.',
    example: { command: 'sudo umount /mnt/flightdata', says: 'Detaches the disk mounted at /mnt/flightdata. If a shell is still inside that folder, it says the target is busy.' },
    seeAlso: ['findmnt', 'lsof', 'df'],
  },
  {
    name: 'findmnt',
    kind: 'system',
    official: 'find a filesystem',
    source: 'findmnt manual page (util-linux)',
    when: 'You want to know which disk a file lives on and how it is mounted, for example to check for noexec, which stops scripts there from running even with chmod +x.',
    flags: [['-T PATH', 'show the filesystem that holds this file or folder']],
    example: { command: 'findmnt -T deploy.sh', says: 'Prints where the disk holding deploy.sh is mounted and its options. noexec in the list means nothing there can be run.' },
    seeAlso: ['df', 'umount', 'lsblk'],
  },
  {
    name: 'fsck',
    kind: 'system',
    official: 'check and repair a Linux filesystem',
    source: 'fsck manual page (util-linux)',
    when: 'A disk was not shut down cleanly and you want to check it for damage and fix it. Run it only on a filesystem that is not mounted, or you can make the damage worse. Pieces of files it rescues go into a folder called lost+found.',
    example: { command: 'sudo fsck /dev/sdb1', says: 'Checks the unmounted filesystem on /dev/sdb1 and asks before fixing each problem it finds.' },
    seeAlso: ['umount', 'git fsck'],
  },

  /* ----------------------------------------------------------------- text */
  {
    name: 'egrep',
    kind: 'text',
    official: 'print lines that match patterns',
    source: 'grep manual page (GNU grep)',
    when: 'You see it in older scripts: it is grep with extended patterns, where + ? | ( ) { } are special without a backslash. Newer grep prints a warning that egrep is obsolete, so write grep -E instead.',
    example: { command: "egrep 'FAIL|ABORT' run.log", says: 'Prints the lines of run.log that contain FAIL or ABORT, the same as grep -E.' },
    seeAlso: ['grep'],
  },
  {
    name: 'diff3',
    kind: 'text',
    official: 'compare three files line by line',
    source: 'diff3 manual page (GNU diffutils)',
    when: 'You have two edited versions of a file and the original they both started from, and want to see who changed what. In git lessons, diff3 is also a setting, merge.conflictStyle diff3, that makes conflicts show the original lines between the two sides in the same way.',
    flags: [['merge.conflictStyle diff3', 'the git setting named after this tool: conflicts also show the base version']],
    example: { command: 'diff3 mine.cfg base.cfg theirs.cfg', says: 'Lists each place the three files differ, and which file is the odd one out.' },
    seeAlso: ['diff', 'git merge', 'git config'],
  },
  {
    name: 'more',
    kind: 'text',
    official: 'display the contents of a file in a terminal',
    source: 'more manual page (util-linux)',
    when: 'You want to read a long file one screen at a time. It is the older pager and can only go forward; less does everything more does and can scroll back, so reach for less.',
    example: { command: 'more mission.log', says: 'Shows the first screen of mission.log. Space shows the next screen, and q quits.' },
    seeAlso: ['less', 'cat', 'head'],
  },
  {
    name: 'zcat',
    kind: 'text',
    official: 'compress or expand files',
    source: 'zcat manual page (GNU gzip)',
    when: 'You want to print what is inside a .gz file without unpacking it on disk, often to pipe it into another command. The .gz file stays as it is.',
    example: { command: 'zcat telemetry.csv.gz | head -3', says: 'Prints the first three lines of the compressed CSV, leaving the .gz file untouched.' },
    seeAlso: ['gzip', 'zgrep', 'zless', 'cat'],
  },
  {
    name: 'zgrep',
    kind: 'text',
    official: 'search possibly compressed files for a regular expression',
    source: 'zgrep manual page (GNU gzip)',
    when: 'You want to search inside .gz files the way grep searches plain ones, for example thousands of compressed logs, without unpacking them first. It takes the same flags as grep.',
    flags: [['-c', 'print how many lines match instead of the lines']],
    example: { command: 'zgrep -c , /tmp/t.csv.gz', says: 'Prints 202: the number of lines in the compressed CSV that contain a comma.' },
    seeAlso: ['grep', 'zcat', 'gzip'],
  },
  {
    name: 'zless',
    kind: 'text',
    official: 'file perusal filter for crt viewing of compressed text',
    source: 'zless manual page (GNU gzip)',
    when: 'You want to scroll through a .gz file in the less viewer without unpacking it. The keys are the same as in less, and q quits.',
    example: { command: 'zless run_0042.log.gz', says: 'Opens the compressed log in less so you can scroll and search it.' },
    seeAlso: ['less', 'zcat', 'gzip'],
  },
  {
    name: 'md5sum',
    kind: 'text',
    official: 'compute and check MD5 message digest',
    source: 'md5sum manual page (GNU coreutils)',
    when: 'You want a short fingerprint of a file to check that a copy is exactly the same as the original. Given a file name it prints the name after the fingerprint; fed from a pipe or < it prints a - instead. MD5 is fine for catching accidents but not for security, where sha256sum is the choice.',
    example: { command: 'md5sum < flight_plan.dat', says: 'Prints a 32-character fingerprint followed by a dash. Any change to the file gives a different fingerprint.' },
    seeAlso: ['diff'],
  },
  {
    name: 'mawk',
    kind: 'text',
    official: 'pattern scanning and text processing language',
    source: 'mawk manual page',
    when: 'You meet it as the awk on Ubuntu: typing awk there runs mawk. It is a small, fast awk. A few extras that GNU awk (gawk) has, such as its time functions, are missing, so a script written for gawk may fail here.',
    example: { command: "mawk -F, '{ s += $3 } END { print s }' fuel.csv", says: 'Adds up the third column of fuel.csv and prints the total, exactly as awk would.' },
    seeAlso: ['awk'],
  },

  /* --------------------------------------------------------------- system */
  {
    name: 'bc',
    kind: 'system',
    official: 'An arbitrary precision calculator language',
    source: 'bc manual page (GNU bc)',
    when: 'You need decimal math in a shell script, which bash itself cannot do. It cuts off the decimals unless you set scale first: echo "10/3" | bc prints 3.',
    flags: [['scale=N', 'keep N digits after the decimal point']],
    example: { command: 'echo "scale=4; 10/3" | bc', says: 'Prints 3.3333.' },
    seeAlso: ['awk', 'python3'],
  },
  {
    name: 'getconf',
    kind: 'system',
    official: 'Query system configuration variables',
    source: 'getconf manual page (GNU C Library)',
    when: 'You want to ask the system for a fixed fact about this machine, such as the size of a cache line or a memory page, instead of guessing it.',
    flags: [['LEVEL1_DCACHE_LINESIZE', 'the size of one cache line in bytes']],
    example: { command: 'getconf LEVEL1_DCACHE_LINESIZE', says: 'Prints 64 on a typical x86-64 machine: the processor moves memory in 64-byte blocks.' },
    seeAlso: ['nproc', 'uname'],
  },
  {
    name: 'locale',
    kind: 'system',
    official: 'get locale-specific information',
    source: 'locale manual page (Linux man-pages)',
    when: 'Two machines sort or format the same data differently and you want to see why. It prints the language and country settings (LANG and the LC_ variables) that change how sort, ls and number formatting behave.',
    example: { command: 'locale', says: 'Prints lines like LANG=en_US.UTF-8 and LC_ALL= showing the settings this shell uses.' },
    seeAlso: ['env', 'export', 'sort'],
  },
  {
    name: 'ldconfig',
    kind: 'system',
    official: 'configure dynamic linker run-time bindings',
    source: 'ldconfig manual page (Linux man-pages)',
    when: 'You installed a shared library (.so file) in a folder listed under /etc/ld.so.conf.d/ and programs still cannot find it. Running it as root rebuilds the list of libraries the system searches.',
    example: { command: 'sudo ldconfig', says: 'Rebuilds the library cache. A program that said "error while loading shared libraries" now finds the new library.' },
    seeAlso: ['ldd'],
  },
  {
    name: 'pstree',
    kind: 'system',
    official: 'display a tree of processes',
    source: 'pstree manual page (psmisc)',
    when: 'You want to see which process started which, drawn as a tree, for example to find the shell a stray python3 belongs to.',
    example: { command: 'pstree', says: 'Draws every running process as a tree, starting from systemd, the first process, with each program under the one that started it.' },
    seeAlso: ['ps', 'kill'],
  },
  {
    name: 'stdbuf',
    kind: 'system',
    official: 'Run COMMAND, with modified buffering operations for its standard streams.',
    source: 'stdbuf manual page (GNU coreutils)',
    when: 'A program writing to a file or pipe saves its output up in blocks, so a log looks empty while the job runs. It asks the program to send each line straight away. It does not help programs that set up their own buffering.',
    flags: [['-oL', 'send standard output line by line']],
    example: { command: 'stdbuf -oL ./run_sweep.sh > sweep.log', says: 'Runs the sweep with each line written to sweep.log as soon as it is printed.' },
    seeAlso: ['tee', 'nohup'],
  },
  {
    name: 'stty',
    kind: 'system',
    official: 'change and print terminal line settings',
    source: 'stty manual page (GNU coreutils)',
    when: 'Your terminal is behaving oddly, for example Ctrl-s freezes all output, and you want to change or check how it handles special keys.',
    flags: [['-ixon', 'turn off Ctrl-s and Ctrl-q flow control, so Ctrl-s no longer freezes the screen']],
    example: { command: 'stty -ixon', says: 'Switches off flow control in this terminal. Pressing Ctrl-s no longer makes the screen look dead.' },
    seeAlso: ['reset'],
  },
  {
    name: 'reset',
    kind: 'system',
    official: 'initialize or reset terminal state',
    source: 'reset manual page (ncurses)',
    when: 'Your terminal shows garbage or line-drawing symbols, usually after you cat a binary file. Type it and press Enter even if you cannot read what you type. Not the same as git reset, which undoes commits; in the git lessons a bare `reset` means git reset.',
    example: { command: 'reset', says: 'Clears the screen and puts the terminal back to its normal letters and settings.' },
    seeAlso: ['stty', 'git reset'],
  },
  {
    name: 'yes',
    kind: 'system',
    official: 'output a string repeatedly until killed',
    source: 'yes manual page (GNU coreutils)',
    when: 'A program asks "are you sure?" again and again and you want to answer y every time. It prints y (or the text you give) forever, until whatever reads it stops. In a pipeline under set -o pipefail it ends with status 141 when the reader quits, which looks like a failure but is not.',
    example: { command: 'yes | head -1', says: 'Prints one y. head then exits, and yes is stopped the next time it tries to write.' },
    seeAlso: ['head', 'set'],
  },
  {
    name: 'run-parts',
    kind: 'system',
    official: 'run scripts or programs in a directory',
    source: 'run-parts manual page (debianutils)',
    when: 'You meet it running every script in /etc/cron.daily and similar folders. By default it runs only files whose names use letters, digits, underscores and dashes, so a script named backup.sh is silently skipped.',
    flags: [['--test', 'list what would run, without running anything']],
    example: { command: 'run-parts --test /etc/cron.daily', says: 'Prints the scripts in /etc/cron.daily that would really run. A missing name means that file is being skipped.' },
    seeAlso: ['crontab'],
  },
  {
    name: 'systemd',
    kind: 'system',
    official: 'systemd system and service manager',
    source: 'systemd manual page (systemd)',
    when: 'You meet it as process 1, the first program Linux starts. It starts and watches every service, and it is what systemctl talks to and what journalctl reads from. You do not run it yourself.',
    example: { command: 'ps -p 1 -o comm=', says: 'Prints systemd on most modern Linux systems: it is the process with id 1.' },
    seeAlso: ['systemctl', 'journalctl', 'systemd-analyze'],
  },
  {
    name: 'systemd-tmpfiles',
    kind: 'system',
    official: 'Creates, deletes and cleans up volatile and temporary files and directories',
    source: 'systemd-tmpfiles manual page (systemd)',
    when: 'You want old scratch files swept away on a schedule by the system, instead of trusting every script to clean up after itself. Rules go in files under /etc/tmpfiles.d/.',
    example: { command: 'sudo systemd-tmpfiles --clean', says: 'Removes files in the listed scratch folders that are older than their rules allow.' },
    seeAlso: ['systemctl', 'mktemp'],
  },
  {
    name: 'visudo',
    kind: 'system',
    official: 'edit the sudoers file',
    source: 'visudo manual page (sudo)',
    when: 'You need to change who may use sudo. It opens the rules in your editor and checks them before saving, so a typo cannot lock everyone out of sudo. Never edit /etc/sudoers directly.',
    example: { command: 'sudo visudo', says: 'Opens /etc/sudoers in your editor, and refuses to save a file with a mistake in it.' },
    seeAlso: ['sudo', 'vim'],
  },

  /* ------------------------------------------------------------ editors */
  {
    name: 'vi',
    kind: 'text',
    official: 'screen-oriented (visual) display editor',
    source: 'vi manual page (POSIX Programmer\'s Manual)',
    when: 'You need to edit a file on a machine that may have no other editor. On Ubuntu, typing vi runs a build of Vim, so everything you learn for vim works. To get out without saving, press Esc and type :q!.',
    example: { command: 'vi ~/.bashrc', says: 'Opens .bashrc in the editor. Press i to type, Esc then :wq to save and quit.' },
    seeAlso: ['vim', 'view', 'vimtutor'],
  },
  {
    name: 'view',
    kind: 'text',
    official: 'Start in read-only mode. You will be protected from writing the files. Can also be done with the "-R" argument.',
    source: 'vim manual page',
    when: 'You want to look at a file in Vim with no risk of changing it, such as a log or someone else\'s configuration. For a very large file, less is still the better choice.',
    example: { command: 'view /etc/ssh/sshd_config', says: 'Opens the file in Vim read-only. Trying to save warns you instead of writing.' },
    seeAlso: ['vim', 'less'],
  },
  {
    name: 'vimtutor',
    kind: 'text',
    official: 'the Vim tutor',
    source: 'vimtutor manual page',
    when: 'You want to learn Vim properly. It opens a practice copy of a lesson file in Vim and walks you through the keys in about thirty minutes; nothing you change touches a real file.',
    example: { command: 'vimtutor', says: 'Opens the interactive Vim lesson. Follow the text on screen; :q! leaves at any time.' },
    seeAlso: ['vim', 'vi'],
  },

  /* ------------------------------------------------------ shell builtins */
  {
    name: 'readarray',
    kind: 'builtin',
    official: 'Read lines from a file into an array variable.',
    source: 'bash built-in help',
    when: 'Another name for mapfile: it puts every line of a command\'s output into an array, one line per element. Feed it with `< <(cmd)`, not a pipe, or the array is lost when the pipe ends.',
    flags: [['-t', 'drop the new line from the end of each element']],
    example: { command: 'readarray -t sats < <(cut -d, -f1 fleet.csv)', says: 'Fills the array sats with the first column of fleet.csv, one satellite name per element.' },
    seeAlso: ['mapfile', 'read'],
  },
  {
    name: 'typeset',
    kind: 'builtin',
    official: 'Set variable values and attributes.',
    source: 'bash built-in help',
    when: 'You see it in scripts written for ksh or zsh; in bash it is another name for declare. Like declare and local, `typeset x=$(cmd)` hides a failure of cmd, so declare first and assign on the next line.',
    example: { command: 'typeset count=0', says: 'Sets the variable count to 0, exactly as declare count=0 would.' },
    seeAlso: ['declare', 'local', 'readonly'],
  },
  {
    name: 'getopt',
    kind: 'system',
    official: 'parse command options (enhanced)',
    source: 'getopt manual page (util-linux)',
    when: 'Your script needs long options like --output as well as short ones, which the getopts builtin cannot read. This is the separate util-linux program; the getopt on macOS is an older, weaker one, so scripts that use it are not portable.',
    flags: [['--test', 'exit with status 4 if this is the enhanced version']],
    example: { command: 'getopt --test; echo $?', says: 'Prints 4 when this is the enhanced util-linux getopt that understands long options.' },
    seeAlso: ['getopts', 'case', 'shift'],
  },
  {
    name: 'dash',
    kind: 'system',
    official: 'command interpreter (shell)',
    source: 'dash manual page',
    when: 'You meet it as /bin/sh on Debian and Ubuntu, so any script with #!/bin/sh runs under it. It follows POSIX strictly and has none of bash\'s extras: [[ is not a keyword there, so an if using it quietly takes the wrong branch.',
    example: { command: 'dash -c \'[[ 1 -eq 1 ]] && echo yes\'', says: 'Prints an error like "[[: not found" instead of yes, because dash has no [[.' },
    seeAlso: ['sh', 'bash', 'shellcheck'],
  },

  /* ----------------------------------------------------------- building */
  {
    name: 'cc',
    kind: 'build',
    official: 'GNU project C and C++ compiler',
    source: 'gcc manual page (GCC; on Ubuntu, cc runs gcc)',
    when: 'You see it in build files and scripts as "the system\'s C compiler". On Ubuntu it is another name for gcc; on other systems it may be clang. A slim Docker image may have no compiler at all.',
    example: { command: 'which gcc cc', says: 'Prints where gcc and cc live, such as /usr/bin/gcc and /usr/bin/cc, or nothing if no compiler is installed.' },
    seeAlso: ['gcc', 'clang', 'make'],
  },
  {
    name: 'clang',
    kind: 'build',
    official: 'the Clang C, C++, and Objective-C compiler',
    source: 'clang manual page (LLVM)',
    when: 'You want to compile C (or, with clang++, C++). It takes almost the same flags as gcc and is known for clear error messages. For C++ use clang++, so the C++ standard library is linked in.',
    example: { command: 'clang blink.c -o blink', says: 'Compiles blink.c into a program called blink, printing any warnings or errors with the line they are on.' },
    seeAlso: ['clang++', 'gcc', 'cc'],
  },
  {
    name: 'size',
    kind: 'build',
    official: 'list section sizes and total size of binary files',
    source: 'size manual page (GNU binutils)',
    when: 'You want to know how much of a compiled program is code and how much is data. text is the code, data and bss are the variables. The file on disk can be bigger than this, because debug information is not counted.',
    example: { command: 'size a b', says: 'Prints one line per program with its text, data and bss sizes, so you can compare a build with -g and one without.' },
    seeAlso: ['nm', 'objdump', 'readelf'],
  },
  {
    name: 'node',
    kind: 'build',
    official: 'server-side JavaScript runtime',
    source: 'node manual page (Node.js)',
    when: 'You want to run a JavaScript file outside a web browser, or a tool that is written in JavaScript. Run it with no file to get a prompt where you can type JavaScript line by line.',
    example: { command: 'node orbit.js', says: 'Runs the JavaScript program in orbit.js and prints whatever it prints.' },
    seeAlso: ['npm', 'npx'],
  },

  /* ---------------------------------------------------------------- git */
  {
    name: 'git archive',
    kind: 'git',
    official: 'Create an archive of files from a named tree',
    source: 'git help',
    when: 'You want the files of one commit or tag, with no .git history, as a single tar or zip, for example to vendor a library or ship a release.',
    example: {
      command: 'git archive v0.4.0 | tar -x -C third_party/frames',
      says: 'Unpacks the files exactly as they were at tag v0.4.0 into third_party/frames, with no .git folder.',
    },
    seeAlso: ['tar', 'git tag'],
  },
  {
    name: 'git bundle',
    kind: 'git',
    official: 'Move objects and refs by archive',
    source: 'git help',
    when: 'You need to move a repository to a machine with no network, such as a controlled lab. It packs commits into one file you can carry on removable media, and git clone can read that file.',
    example: { command: 'git bundle create guidance.bundle --all', says: 'Writes the whole repository into one file, guidance.bundle. On the other machine, git clone guidance.bundle rebuilds it.' },
    seeAlso: ['git clone', 'git fetch'],
  },
  {
    name: 'git cherry',
    kind: 'git',
    official: 'Find commits yet to be applied to upstream',
    source: 'git help',
    when: 'You backport fixes and want to know which are already on a release branch. It compares the changes themselves (their patch IDs), not the commit ids, so a cherry-picked copy counts as already there.',
    flags: [['-v', 'show each commit\'s message after its id']],
    example: {
      command: 'git cherry -v main release/1.4',
      says: 'Lists release/1.4\'s commits: - means main already has the same change, + means it does not.',
    },
    seeAlso: ['git cherry-pick', 'git patch-id', 'git log'],
  },
  {
    name: 'git patch-id',
    kind: 'git',
    official: 'Compute unique ID for a patch',
    source: 'git help',
    when: 'You want a fingerprint of a change itself, ignoring its commit id, date, author and message, to tell whether two commits make the same edit. Change one character of the edit and the ID is completely different.',
    example: { command: 'git show fe4714c | git patch-id', says: 'Prints the patch ID of that commit\'s change, followed by the commit id.' },
    seeAlso: ['git cherry', 'git cherry-pick'],
  },
  {
    name: 'git difftool',
    kind: 'git',
    official: 'Show changes using common diff tools',
    source: 'git help',
    when: 'You want to see changes in a graphical comparison program instead of as text lines, for example for a model file that a text diff cannot show. It takes the same arguments as git diff.',
    example: { command: 'git difftool HEAD~1 -- model.slx', says: 'Opens the configured comparison tool on the old and new versions of model.slx.' },
    seeAlso: ['git diff', 'git mergetool'],
  },
  {
    name: 'git mergetool',
    kind: 'git',
    official: 'Run merge conflict resolution tools to resolve merge conflicts',
    source: 'git help',
    when: 'A merge stopped with conflicts and you would rather fix them in a visual program that shows base, ours and theirs side by side. It opens each conflicted file in turn. Test the result the same as any other fix.',
    example: { command: 'git mergetool', says: 'Opens each conflicted file in your configured merge program, one after another, with the three versions side by side.' },
    seeAlso: ['git merge', 'git difftool', 'git status'],
  },
  {
    name: 'git request-pull',
    kind: 'git',
    official: 'Generates a summary of pending changes',
    source: 'git help',
    when: 'You want to ask a maintainer by email to pull your branch, the way Linux kernel work is done. It prints the commits and where to fetch them from; hosting sites replaced this with pull requests.',
    example: {
      command: 'git request-pull v1.4 https://example.com/maya/guidance.git fix-yaw',
      says: 'Prints a summary of the commits on fix-yaw since v1.4 and the address to pull them from, ready to paste into an email.',
    },
    seeAlso: ['git push', 'git log'],
  },
  {
    name: 'git rev-list',
    kind: 'git',
    official: 'Lists commit objects in reverse chronological order',
    source: 'git help',
    when: 'You want commit ids or counts as plain output for a script, rather than the formatted history git log shows. The newest commit comes first.',
    flags: [
      ['--left-right --count A...B', 'print two counts: commits only A has, and commits only B has'],
      ['--max-parents=0', 'only commits with no parent, the first commit of the history'],
    ],
    example: { command: 'git rev-list --left-right --count main...origin/main', says: 'Prints two numbers, such as 2 3: you have 2 commits the remote lacks, and it has 3 you lack.' },
    seeAlso: ['git log', 'git rev-parse', 'git merge-base'],
  },
  {
    name: 'git filter-repo',
    kind: 'git',
    official: 'Rewrite repository history',
    source: 'git-filter-repo manual page',
    when: 'A secret or a huge file was committed and you must remove it from every commit in history. It is a separate tool you install, not part of git. It cannot reach copies already cloned elsewhere, so revoke any leaked key first, and everyone must re-clone afterwards.',
    example: { command: 'git filter-repo --path secrets.env --invert-paths', says: 'Rewrites every commit so secrets.env never existed. All the commit ids change.' },
    seeAlso: ['git push', 'git rm'],
  },
]
