import type { CommandRef } from './types'

/*
 * Terminal tools the lessons name that are not installed on ORBIT's own
 * machine: other distributions' package managers, older tools that newer ones
 * replaced, and project tools met once in a lesson. `official` is each tool's
 * own manual page (Ubuntu 24.04 packages) or, where Ubuntu ships none, the
 * project's own documentation, named in `source`.
 */
export const COMMANDS: CommandRef[] = [
  /* ---------------------------------------------------------------- files */
  {
    name: 'zstd',
    kind: 'file',
    official: 'Compress or decompress .zst files',
    source: 'zstd manual page',
    when: 'You want a big file or archive smaller, fast: nightly telemetry archives, or anything large going over a network. Unlike gzip, it keeps the original file unless you pass --rm. Higher levels shrink more but take much longer to compress; unpacking stays fast.',
    flags: [
      ['-19', 'compression level 19, the strongest normal level (the default is 3)'],
      ['-d', 'decompress a .zst file'],
      ['--rm', 'delete the original after compressing'],
    ],
    example: { command: 'zstd -19 campaign.tar', says: 'Writes a smaller campaign.tar.zst next to campaign.tar, which is still there.' },
    seeAlso: ['zstdcat', 'gzip', 'tar'],
  },
  {
    name: 'zstdcat',
    kind: 'file',
    official: 'Compress or decompress .zst files',
    source: 'zstd manual page (zstdcat)',
    when: 'You want to read or search a .zst file without unpacking it to disk. It is the zstd partner of zcat: it prints the unpacked text, so you can pipe it into grep, head or less.',
    example: { command: 'zstdcat run_0417.log.zst | grep -c WARN', says: 'Counts the lines with WARN in the compressed log. No unpacked copy is left behind.' },
    seeAlso: ['zstd', 'zcat', 'zgrep'],
  },
  {
    name: 'sftp',
    kind: 'file',
    official: 'OpenSSH secure file transfer',
    source: 'sftp manual page (OpenSSH)',
    when: 'You want to move files to or from another machine over SSH by typing commands at an sftp> prompt, like a small file browser. It fails with "Received message too long" if the remote ~/.bashrc prints anything, just like scp and rsync.',
    flags: [
      ['get FILE', 'at the prompt: download a file from the remote machine'],
      ['put FILE', 'at the prompt: upload a file to the remote machine'],
    ],
    example: { command: 'sftp eng@groundstation\nsftp> get telemetry.csv', says: 'Logs in over SSH, then downloads telemetry.csv into your current folder.' },
    seeAlso: ['scp', 'rsync', 'ssh'],
  },

  /* ----------------------------------------------------------------- text */
  {
    name: 'gawk',
    kind: 'text',
    official: 'pattern scanning and processing language',
    source: 'gawk manual page (GNU Awk)',
    when: 'You want awk with GNU\'s extras, such as choosing the order of a for-in loop. On Ubuntu, awk is often mawk, which quietly ignores those extras. A for (k in a) loop has no fixed order in any awk, so pipe to sort when order matters.',
    flags: [
      ['-F SEP', 'what separates the fields; can be a pattern such as \'[= ]+\''],
      ['PROCINFO["sorted_in"]', 'gawk only: sets the order of for-in loops, such as "@ind_str_asc"'],
    ],
    example: { command: 'gawk -F\'[= ]+\' \'{ n[$4]++ } END { for (c in n) print c, n[c] }\' logs/run.log', says: 'Counts how often each value in field 4 appears in run.log and prints each value with its count.' },
    seeAlso: ['awk', 'mawk', 'sort'],
  },
  {
    name: 'gsed',
    kind: 'text',
    official: 'stream editor for filtering and transforming text',
    source: 'GNU sed manual page (installed as gsed by Homebrew)',
    when: 'You are on a Mac and want GNU sed, the version the lessons use. Homebrew installs it as gsed, with a g for GNU, so it does not replace the Mac\'s own BSD sed. The two differ most in -i: GNU takes -i alone, BSD needs -i \'\'.',
    flags: [
      ['-i', 'edit the file in place'],
      ['-E', 'use extended regular expressions'],
    ],
    example: { command: 'gsed -i \'s/\\r$//\' deploy.sh', says: 'Removes the Windows \\r from the end of every line of deploy.sh, in place.' },
    seeAlso: ['sed', 'dos2unix'],
  },
  {
    name: 'dos2unix',
    kind: 'text',
    official: 'DOS/Mac to Unix and vice versa text file format converter',
    source: 'dos2unix manual page',
    when: 'A script written on Windows fails with "bad interpreter" or a pattern will not match, because every line ends in an invisible \\r. It changes the file in place. If it is not installed, sed -i \'s/\\r$//\' does the same job.',
    example: { command: 'dos2unix deploy.sh', says: 'Prints "dos2unix: converting file deploy.sh to Unix format..." and strips the \\r from every line.' },
    seeAlso: ['sed', 'gsed', 'file'],
  },
  {
    name: 'ed',
    kind: 'text',
    official: 'line-oriented text editor',
    source: 'ed manual page (GNU ed)',
    when: 'You meet it in the history of Unix: the first editor, from about 1970, and where sed, grep and vim\'s :s command come from. grep is named after its command g/re/p. You rarely use it today, but it still works in scripts.',
    flags: [
      ['g/re/p', 'for every line matching the pattern re, print it'],
      ['s/old/new/', 'replace text on the current line'],
      ['-s', 'quiet: do not print byte counts'],
    ],
    example: { command: 'printf \'%s\\n\' \'g/ERROR/p\' q | ed -s flight.log', says: 'Prints every line of flight.log that contains ERROR, exactly like grep ERROR flight.log.' },
    seeAlso: ['sed', 'grep', 'vim'],
  },
  {
    name: 'cowsay',
    kind: 'text',
    official: 'configurable speaking/thinking cow (and a bit more)',
    source: 'cowsay manual page',
    when: 'A harmless joke program, handy for practicing package installs: it is small, and it pulls in one extra library, so you can watch apt handle a dependency. On Ubuntu it lands in /usr/games.',
    example: { command: 'cowsay "T minus 10"', says: 'Draws an ASCII cow with a speech bubble saying T minus 10.' },
    seeAlso: ['apt', 'apt-get'],
  },

  /* ------------------------------------------------------ network & daemons */
  {
    name: 'sshd',
    kind: 'system',
    official: 'OpenSSH daemon',
    source: 'sshd manual page (OpenSSH)',
    when: 'It is the SSH server: the program on the far machine that answers when you run ssh. When it runs a command for you (ssh host \'cmd\'), the shell reads ~/.bashrc but not your login files. Test its config before restarting it, or a typo can lock you out.',
    flags: [['-t', 'test mode: only check the config file and keys']],
    example: { command: 'sudo sshd -t', says: 'Prints nothing if the SSH server\'s config is valid, or the line that is wrong.' },
    seeAlso: ['ssh', 'systemctl', 'ss'],
  },
  {
    name: 'netstat',
    kind: 'system',
    official: 'Print network connections, routing tables, interface statistics, masquerade connections, and multicast memberships',
    source: 'netstat manual page (net-tools)',
    when: 'You see it in older guides for "what is listening on which port". It was replaced by ss, which takes the same letters, and it is not installed on many new systems.',
    flags: [
      ['-t', 'TCP connections'],
      ['-l', 'only ports that are listening'],
      ['-n', 'show numbers, not names'],
      ['-p', 'show which program owns each one'],
    ],
    example: { command: 'sudo netstat -tlnp', says: 'Lists every listening TCP port with the program behind it. ss -tlnp shows the same today.' },
    seeAlso: ['ss', 'ip', 'lsof'],
  },
  {
    name: 'ifconfig',
    kind: 'system',
    official: 'configure a network interface',
    source: 'ifconfig manual page (net-tools)',
    when: 'You see it in older guides for "what is my IP address". It was replaced by ip, and it is not installed on many new systems. Use ip addr instead.',
    flags: [['-a', 'show every interface, even ones that are down']],
    example: { command: 'ifconfig', says: 'Lists each network interface that is up with its addresses. ip addr shows the same today.' },
    seeAlso: ['ip', 'ss'],
  },
  {
    name: 'ufw',
    kind: 'system',
    official: 'program for managing a netfilter firewall',
    source: 'ufw manual page',
    when: 'You want a simple firewall on an Ubuntu machine: say which ports may be reached and block the rest. Allow SSH before you enable it on a remote machine. Ports that Docker publishes with -p can bypass its rules.',
    flags: [
      ['allow PORT', 'let traffic in on that port, such as 22/tcp'],
      ['enable', 'turn the firewall on'],
      ['status', 'show whether it is on and which rules it has'],
    ],
    example: { command: 'sudo ufw allow 22/tcp', says: 'Adds a rule that lets SSH connections in.' },
    seeAlso: ['docker run', 'ss'],
  },
  {
    name: 'cron',
    kind: 'system',
    official: 'daemon to execute scheduled commands (Vixie Cron)',
    source: 'cron manual page (Vixie Cron)',
    when: 'It is the background program that runs everyone\'s crontab jobs; you edit the jobs with crontab, and cron starts them on time. Jobs run with a tiny environment: no ~/.bashrc and a short PATH, so use full paths.',
    flags: [
      ['PATH=...', 'a crontab line that sets where commands are looked up'],
      ['MAILTO=""', 'a crontab line that stops output being mailed to anyone'],
      ['%', 'in a job line, ends the command; write \\% for a real percent sign'],
    ],
    example: { command: 'journalctl -u cron --no-pager -n 3', says: 'Shows cron\'s last log lines. A "(root) CMD (...)" line proves the job was started.' },
    seeAlso: ['crontab', 'systemctl', 'journalctl'],
  },
  {
    name: 'logrotate',
    kind: 'system',
    official: 'rotates, compresses, and mails system logs',
    source: 'logrotate manual page',
    when: 'A service that runs for months would fill the disk with its log. logrotate, usually run once a day, renames app.log to app.log.1, shifts the older ones along and compresses or deletes the oldest. A program following the log should use tail -F, which notices the new file.',
    flags: [
      ['-d', 'debug: show what it would do and change nothing'],
      ['copytruncate', 'in the config: copy the log, then empty it, for programs that keep the file open'],
      ['rotate N', 'in the config: keep N old logs'],
    ],
    example: { command: 'sudo logrotate -d /etc/logrotate.d/nightly', says: 'Prints what it would rename, compress and delete for that config, without touching any log.' },
    seeAlso: ['tail', 'journalctl', 'gzip'],
  },
  {
    name: 'apport',
    kind: 'system',
    official: 'automatically generate crash reports for debugging',
    source: 'apport package description (Ubuntu)',
    when: 'You find your crashed program left no core file on Ubuntu. If /proc/sys/kernel/core_pattern starts with |/usr/share/apport/apport, apport took the crash and wrote a report to /var/crash.',
    example: { command: 'ls /var/crash', says: 'Lists the crash reports apport has written, one .crash file per crashed program.' },
    seeAlso: ['coredumpctl', 'gdb', 'ulimit'],
  },
  {
    name: 'ash',
    kind: 'system',
    official: 'Unix shell interpreter',
    source: 'BusyBox ash --help (BusyBox 1.36.1)',
    when: 'The lessons name ash as the small shell Kenneth Almquist wrote in 1989; dash, Ubuntu\'s /bin/sh, grew from it. You meet it today as /bin/sh in Alpine images, where BusyBox provides it and there is no bash. Bash extras such as arrays fail there.',
    example: { command: 'docker run --rm alpine readlink /bin/sh', says: 'Prints /bin/busybox: on Alpine, sh is BusyBox\'s ash.' },
    seeAlso: ['dash', 'sh', 'bash'],
  },

  /* ----------------------------------------------------- package managers */
  {
    name: 'dnf',
    kind: 'system',
    official: 'DNF is the next upcoming major version of YUM, a package manager for RPM-based Linux distributions.',
    source: 'dnf manual page, DESCRIPTION',
    when: 'You are on Fedora, Red Hat Enterprise Linux, Rocky or AlmaLinux, where it plays the part apt plays on Ubuntu. In a script, note that check-update exits with 100 when updates are waiting, which looks like a failure.',
    flags: [
      ['check-update', 'refresh the package index (like apt update)'],
      ['install NAME', 'install a package'],
      ['remove NAME', 'remove a package'],
      ['upgrade', 'upgrade everything'],
      ['search TEXT', 'find packages'],
      ['info NAME', 'show details (like apt show)'],
    ],
    example: { command: 'sudo dnf install gcc-c++', says: 'Installs the C++ compiler and everything it needs, after asking you to confirm.' },
    seeAlso: ['yum', 'rpm', 'apt'],
  },
  {
    name: 'yum',
    kind: 'system',
    official: 'Yellowdog Updater Modified',
    source: 'yum manual page (yum 3, rpm-software-management/yum)',
    when: 'You see it in older guides for Red Hat systems. dnf replaced it, and on many systems yum is now just another name for dnf, so the same commands work.',
    flags: [
      ['install NAME', 'install a package'],
      ['remove NAME', 'remove a package'],
    ],
    example: { command: 'sudo yum install git', says: 'Installs git. On a new system this actually runs dnf.' },
    seeAlso: ['dnf', 'rpm'],
  },
  {
    name: 'rpm',
    kind: 'system',
    official: 'RPM Package Manager',
    source: 'rpm manual page',
    when: 'You are on a Red Hat family system and want to ask about installed packages: it is the dpkg of that world, with dnf on top. Installing a .rpm file with rpm alone does not fetch what it depends on; let dnf do that.',
    flags: [
      ['-q NAME', 'is it installed, and which version (like dpkg -l)'],
      ['-qf PATH', 'which package owns this file (like dpkg -S)'],
      ['-ql NAME', 'which files the package installed (like dpkg -L)'],
    ],
    example: { command: 'rpm -qf /usr/bin/gcc', says: 'Prints the name and version of the package that installed gcc.' },
    seeAlso: ['dnf', 'dpkg'],
  },
  {
    name: 'apk',
    kind: 'system',
    official: 'Alpine Package Keeper',
    source: 'apk manual page (Alpine apk-tools)',
    when: 'You are writing a Dockerfile on an Alpine base image and need extra programs, such as compilers. Alpine uses musl instead of glibc, so a Python package with no musl wheel gets built from source, which is slow.',
    flags: [
      ['add NAME', 'install packages'],
      ['--no-cache', 'use no local cache, so no package index is left in the image'],
    ],
    example: { command: 'apk add --no-cache build-base', says: 'Installs gcc, make and the C headers, leaving no downloaded index behind.' },
    seeAlso: ['apt-get', 'docker build'],
  },

  /* ------------------------------------------------- environments & builds */
  {
    name: 'pyenv',
    kind: 'system',
    official: 'Simple Python version management',
    source: 'pyenv manual page (pyenv/pyenv)',
    when: 'You need several Python versions on one machine and want each project to pick its own. It puts its own python first on PATH, which is why #!/usr/bin/env python3 finds its choice. It builds each Python from source, so it needs a compiler.',
    flags: [
      ['install VERSION', 'download and build that Python'],
      ['local VERSION', 'use that Python in this folder (writes .python-version)'],
      ['versions', 'list the Pythons it has'],
    ],
    example: { command: 'pyenv local 3.12.4', says: 'Makes python in this folder and below mean Python 3.12.4.' },
    seeAlso: ['python3', 'uv', 'conda'],
  },
  {
    name: 'conda-lock',
    kind: 'system',
    official: 'Conda lock is a lightweight library that can be used to generate fully reproducible lock files for conda environments.',
    source: 'conda-lock README (conda/conda-lock)',
    when: 'Your environment.yml gives ranges ("any SciPy"), and you want every teammate and machine to get the exact same packages. It solves once per platform and writes conda-lock.yml with exact versions and checksums.',
    flags: [
      ['-f FILE', 'the environment file to solve'],
      ['-p PLATFORM', 'a platform to solve for, such as linux-64; repeat for more'],
      ['install -n NAME', 'create an environment called NAME from the lockfile'],
    ],
    example: { command: 'conda-lock -f environment.yml -p linux-64 -p osx-arm64', says: 'Writes conda-lock.yml with the exact packages for Linux and Apple Silicon Macs.' },
    seeAlso: ['conda', 'uv', 'pip'],
  },
  {
    name: 'spack',
    kind: 'build',
    official: 'Spack is a multi-platform package manager that builds and installs multiple versions and configurations of software.',
    source: 'Spack README (spack/spack)',
    when: 'You work on a supercomputer and need a library built with a particular compiler and options. Each build is written as a spec, and two specs that differ only in options, like +mpi and ~mpi, are different builds.',
    flags: [
      ['spec', 'show exactly what it would build, without building'],
      ['install', 'build and install a spec'],
      ['concretize', 'write every choice for a project into spack.lock'],
      ['@ + ~ % ^', 'in a spec: version, option on, option off, compiler, dependency'],
    ],
    example: { command: 'spack spec zlib@1.3.1 ~shared %gcc@13', says: 'Prints the full build plan for zlib 1.3.1 without a shared library, compiled with GCC 13.' },
    seeAlso: ['nix-shell', 'conda-lock', 'cmake'],
  },
  {
    name: 'docker-compose',
    kind: 'build',
    official: 'Docker Compose is a tool for running multi-container applications on Docker defined using the Compose file format.',
    source: 'Docker Compose README (docker/compose, v1 branch)',
    when: 'You see it in older guides and scripts. Today it is docker compose, with a space, a plugin of the docker command; the old Python program with the hyphen is no longer maintained.',
    flags: [
      ['up', 'create and start every service'],
      ['-d', 'with up: run in the background'],
    ],
    example: { command: 'docker-compose up -d', says: 'Starts every service in the compose file in the background. Today you type docker compose up -d.' },
    seeAlso: ['docker compose', 'docker'],
  },
  {
    name: 'gcovr',
    kind: 'build',
    official: 'generate simple coverage reports',
    source: 'gcovr manual page',
    when: 'You want to know which lines of your C++ code the tests ran, and to fail CI when coverage drops. Build with --coverage and run the tests first, or there is nothing to count.',
    flags: [
      ['--root .', 'the top folder of your source code'],
      ['--filter src/', 'count only files under src/'],
      ['--fail-under-line N', 'fail if fewer than N percent of lines ran'],
      ['--html-details FILE', 'also write a web page showing every line'],
    ],
    example: { command: 'gcovr --root . --filter src/ --fail-under-line 85', says: 'Prints line coverage for each file in src/ and exits with an error if the total is under 85 percent.' },
    seeAlso: ['ctest', 'g++', 'gcc'],
  },

  /* ---------------------------------------------------------------- git */
  {
    name: 'gh',
    kind: 'git',
    official: 'Work seamlessly with GitHub from the command line.',
    source: 'gh command help (cli/cli)',
    when: 'You want to do GitHub things, like pull requests and releases, from the terminal or a workflow. In GitHub Actions it reads its access key from GH_TOKEN.',
    flags: [
      ['pr create --draft', 'open a draft pull request'],
      ['pr ready', 'mark your draft ready for review'],
      ['release create TAG', 'publish a release for a tag'],
      ['--verify-tag', 'with release create: stop unless the tag is already on GitHub'],
      ['--generate-notes', 'with release create: write notes from the merged pull requests'],
    ],
    example: { command: 'gh pr create --draft', says: 'Asks for a title and description, then opens a draft pull request for your branch.' },
    seeAlso: ['git push', 'git tag'],
  },
  {
    name: 'git-lfs',
    kind: 'git',
    official: 'Work with large files in Git repositories',
    source: 'git-lfs manual page',
    when: 'It is the separate program behind git lfs, installed once per machine. A clone made without it has small text pointer files where the big files should be, so a program reading them gets about 133 bytes of text.',
    flags: [
      ['install', 'set up its hooks once on your machine'],
      ['pull', 'download the real files for pointers you already have'],
    ],
    example: { command: 'git lfs install\ngit lfs pull', says: 'Sets up LFS, then swaps each pointer file for the real file.' },
    seeAlso: ['git lfs', 'git clone'],
  },
  {
    name: 'git-subtree',
    kind: 'git',
    official: 'Merge subtrees together and split repository into subtrees',
    source: 'git-subtree manual page (Git contrib)',
    when: 'It is the add-on behind git subtree. It lives in Git\'s contrib folder, so some Linux distributions ship it as a separate package called git-subtree. Only the person who updates the subtree needs it.',
    flags: [
      ['--prefix=DIR', 'the folder the other project lives in'],
      ['--squash', 'bring in the other project as one commit, not its whole history'],
    ],
    example: { command: 'git subtree pull --prefix=extern/frames ../frames.git v0.4.0 --squash', says: 'Updates extern/frames to the library\'s v0.4.0 in one commit.' },
    seeAlso: ['git subtree', 'git submodule'],
  },
  {
    name: 'svn',
    kind: 'system',
    official: 'Subversion command line client tool',
    source: 'svn manual page (Subversion)',
    when: 'You meet a project still kept in Subversion, the version control tool many teams used before git. There is one central server: svn commit sends your change there at once, with no local commits first.',
    flags: [
      ['blame FILE', 'who last changed each line; also called praise and annotate'],
      ['checkout URL', 'get a working copy from the server'],
      ['commit', 'send your changes to the server'],
    ],
    example: { command: 'svn blame thrust.c', says: 'Prints each line of thrust.c with the revision number and the author who last changed it.' },
    seeAlso: ['git blame', 'git annotate'],
  },
]
