import type { CommandRef } from './types'

/** C++ names the lessons teach in their text that the first-wave batches missed: keywords, std:: names (C++23/26 included), headers, Eigen and GoogleTest. */
export const COMMANDS: CommandRef[] = [
  {
    name: '<any>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::any class',
    source: 'cppreference.com',
    when: 'Include it to use std::any, a box that can hold one value of any copyable type. Most flight builds leave it out, because std::any may allocate on the heap.',
    example: { command: '#include <any>', says: 'Makes std::any and std::any_cast available in this file.' },
    seeAlso: ['std::any', 'std::any_cast'],
  },
  {
    name: '<complex>',
    lang: 'cpp',
    kind: 'header',
    official: 'Complex number type',
    source: 'cppreference.com',
    when: 'Include it when you need complex numbers, such as the roots of a characteristic equation or a Fourier transform. It also brings in many extra operator* overloads, which makes template error messages longer.',
    example: { command: '#include <complex>\nstd::complex<double> root{-0.5, 2.0};', says: 'Makes std::complex available and builds the complex number -0.5 + 2i.' },
  },
  {
    name: '<flat_map>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::flat_map and std::flat_multimap container adaptors',
    source: 'cppreference.com',
    when: 'Include it to use std::flat_map, the C++23 map stored in sorted arrays. g++ 13 does not have this header yet, so the include fails there.',
    example: { command: '#include <flat_map>', says: 'Makes std::flat_map available, on a compiler new enough to have it.' },
    seeAlso: ['std::flat_map', '<map>'],
  },
  {
    name: '<flat_set>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::flat_set and std::flat_multiset container adaptors',
    source: 'cppreference.com',
    when: 'Include it to use std::flat_set, the C++23 set stored in one sorted array. Like <flat_map>, it is missing from g++ 13.',
    example: { command: '#include <flat_set>', says: 'Makes std::flat_set available, on a compiler new enough to have it.' },
    seeAlso: ['std::flat_set', '<set>'],
  },
  {
    name: '<generator>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::generator class template',
    source: 'cppreference.com',
    when: 'Include it to write coroutines that hand out values one at a time with std::generator (C++23). g++ 13 fails with "generator: No such file or directory"; it arrived in GCC 14.',
    example: { command: '#include <generator>', says: 'Makes std::generator available, on GCC 14 or newer.' },
    seeAlso: ['std::generator', '<coroutine>'],
  },
  {
    name: '<print>',
    lang: 'cpp',
    kind: 'header',
    official: 'Formatted output library including std::print',
    source: 'cppreference.com',
    when: 'Include it for std::print and std::println (C++23). libstdc++ 13 has no <print>, so on g++ 13 the include fails; use std::cout << std::format(...) there instead.',
    example: { command: '#include <print>', says: 'Makes std::print and std::println available, on libstdc++ 14 or newer.' },
    seeAlso: ['std::print', 'std::println', '<format>'],
  },
  {
    name: '<stacktrace>',
    lang: 'cpp',
    kind: 'header',
    official: 'Stacktrace library',
    source: 'cppreference.com',
    when: 'Include it to capture the chain of function calls that led to a point in the program, for a crash report. g++ 13 has it, but only with -std=c++23 and when you link with -lstdc++exp.',
    example: { command: '#include <stacktrace>', says: 'Makes std::stacktrace available.' },
    seeAlso: ['std::stacktrace'],
  },
  {
    name: 'Eigen::Isometry',
    lang: 'cpp',
    kind: 'constant',
    official: 'Transformation is an isometry.',
    source: 'Eigen documentation (Constants.h, TransformTraits)',
    when: 'The last template argument of Eigen::Transform when the transform is only a rotation plus a translation, with no scaling. Eigen then inverts it cheaply by transposing the rotation. Putting a scale into an Isometry breaks that promise and gives wrong inverses.',
    example: { command: 'Eigen::Transform<double, 3, Eigen::Isometry> T = Eigen::Transform<double, 3, Eigen::Isometry>::Identity();', says: 'Makes T a 3D rotation-plus-translation transform that starts as "do nothing". This is the same type as Eigen::Isometry3d.' },
    seeAlso: ['Eigen::Transform', 'Eigen::Isometry3d'],
  },
  {
    name: 'Eigen::Scaling',
    lang: 'cpp',
    kind: 'function',
    official: 'Constructs a uniform scaling from scale factor s',
    source: 'Eigen documentation (Scaling.h)',
    when: 'You want to grow or shrink everything by the same factor inside a chain of transforms. A scaled transform is no longer an Isometry, so store the result in an Affine3d.',
    example: { command: 'Eigen::Affine3d T = Eigen::Translation3d(1, 2, 3) * Eigen::Scaling(2.0);', says: 'Builds a transform that doubles every size, then moves the result by (1, 2, 3).' },
    seeAlso: ['Eigen::Transform', 'Eigen::Translation3d'],
  },
  {
    name: 'Eigen::Transform',
    lang: 'cpp',
    kind: 'class',
    official: 'Represents an homogeneous transformation in a N dimensional space',
    source: 'Eigen documentation (Transform.h)',
    when: 'You need to move and turn points between frames, such as body frame to launch-pad frame, as one object. You will usually meet it through its shorthands Isometry3d and Affine3d. The kind you pick (Isometry, Affine, AffineCompact, Projective) decides what is allowed and how the inverse is computed.',
    flags: [
      ['<Scalar, Dim, Mode>', 'the number type, 2 or 3 dimensions, and the kind of transform'],
      ['Isometry', 'rotation and translation only'],
      ['Affine', 'also allows scaling and shearing'],
      ['AffineCompact', 'affine, stored without the last row'],
      ['inverse()', 'the transform that undoes this one'],
    ],
    example: { command: 'Eigen::Transform<double, 3, Eigen::Isometry> body_to_pad;', says: 'Declares a 3D transform of kind Isometry: a rotation and a translation, stored as a 4 by 4 homogeneous matrix.' },
    seeAlso: ['Eigen::Isometry', 'Eigen::Isometry3d', 'Eigen::Scaling'],
  },
  {
    name: 'Eigen::Vector3d::Ones',
    aliases: ['Vector3d::Ones'],
    lang: 'cpp',
    kind: 'method',
    official: 'returns an expression of a fixed-size matrix or vector where all coefficients equal one.',
    source: 'Eigen documentation (CwiseNullaryOp.h)',
    when: 'You need a vector of ones, for example to add 1 to every entry of a Vector3d (v + 1.0 does not compile for matrices). The alternative is v.array() + 1.0.',
    example: { command: 'Eigen::Vector3d shifted = v + Eigen::Vector3d::Ones();', says: 'Adds 1 to each of the three entries of v.' },
    seeAlso: ['Eigen::Vector3d'],
  },
  {
    name: 'Eigen::VectorXd::LinSpaced',
    aliases: ['VectorXd::LinSpaced'],
    lang: 'cpp',
    kind: 'method',
    official: 'Sets a linearly spaced vector.',
    source: 'Eigen documentation (CwiseNullaryOp.h)',
    when: 'The Eigen version of np.linspace: evenly spaced values between two ends, both ends included. The count comes first here, where NumPy puts it last.',
    flags: [
      ['(size, low, high)', 'how many values, then the first and the last'],
    ],
    example: { command: 'Eigen::VectorXd t = Eigen::VectorXd::LinSpaced(21, -1.0, 1.0);', says: 'Makes 21 evenly spaced values from -1.0 to 1.0, both ends included.' },
    seeAlso: ['Eigen::VectorXd'],
  },
  {
    name: 'Eigen::aligned_allocator',
    aliases: ['aligned_allocator'],
    lang: 'cpp',
    kind: 'class',
    official: 'STL compatible allocator to use with types requiring a non standrad alignment.',
    source: 'Eigen documentation (Memory.h)',
    when: 'Old Eigen code puts it in std::vector<Eigen::Vector4d, ...> so the fixed-size vectors land on correctly aligned memory. Since C++17 the normal allocator handles over-aligned types, so you mostly see it in older code.',
    example: { command: 'std::vector<Eigen::Vector4d, Eigen::aligned_allocator<Eigen::Vector4d>> pts;', says: "Makes a vector of Vector4d whose memory is aligned the way Eigen's fast math needs." },
    seeAlso: ['std::vector', 'Eigen::Vector4d'],
  },
  {
    name: 'Eigen::all',
    lang: 'cpp',
    kind: 'constant',
    official: 'Can be used as a parameter to DenseBase::operator()(const RowIndices&, const ColIndices&) to index all rows or columns',
    source: 'Eigen documentation (IndexedViewHelper.h)',
    when: 'In Eigen 3.4 slicing, it means "every row" or "every column", like : in NumPy. It needs Eigen 3.4 or newer.',
    example: { command: 'auto rows = X(Eigen::seq(2, 4), Eigen::all);', says: 'Takes rows 2, 3 and 4 of X with all of their columns.' },
    seeAlso: ['Eigen::seq', 'Eigen::seqN'],
  },
  {
    name: 'Eigen::seq',
    lang: 'cpp',
    kind: 'function',
    official: 'returns an ArithmeticSequence starting at f, up (or down) to l, and unit increment',
    source: 'Eigen documentation (ArithmeticSequence.h)',
    when: "Slicing by first and last index in Eigen 3.4. Unlike NumPy's 1:3, the last index is included, so X[1:3] in NumPy is seq(1, 2) here.",
    flags: [
      ['(first, last)', 'first and last index, both included'],
    ],
    example: { command: 'auto part = X(Eigen::seq(1, 2), Eigen::seq(0, 1));', says: "Takes rows 1 to 2 and columns 0 to 1 of X: the same window as NumPy's X[1:3, 0:2]." },
    seeAlso: ['Eigen::seqN', 'Eigen::all'],
  },
  {
    name: 'Eigen::seqN',
    lang: 'cpp',
    kind: 'function',
    official: 'returns an ArithmeticSequence starting at first, of length size, and unit increment',
    source: 'Eigen documentation (ArithmeticSequence.h)',
    when: 'Slicing by start and count in Eigen 3.4: "start here, take this many". It matches block(), which also takes a start and a size.',
    flags: [
      ['(first, size)', 'where to start and how many to take'],
    ],
    example: { command: 'auto w = M(Eigen::seqN(1, 2), Eigen::seqN(2, 2));', says: 'Takes 2 rows starting at row 1 and 2 columns starting at column 2: the same as M.block(1, 2, 2, 2).' },
    seeAlso: ['Eigen::seq', 'Eigen::all'],
  },
  {
    name: 'and',
    lang: 'cpp',
    kind: 'keyword',
    official: 'alternative operators: as an alternative for &&',
    source: 'cppreference.com (keyword and)',
    when: 'Another spelling of &&, the logical "and". It works in every C++ compiler, but most code uses &&, so readers may find it surprising.',
    example: { command: 'if (fuel_ok and engines_ok) launch();', says: 'Calls launch() only when both are true, exactly like fuel_ok && engines_ok.' },
    seeAlso: ['or', 'not'],
  },
  {
    name: 'dynamic_cast',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Safely converts pointers and references to classes up, down, and sideways along the inheritance hierarchy.',
    source: 'cppreference.com',
    when: 'You hold a base-class pointer and need to check, while the program runs, whether the object is really a certain derived class. It needs RTTI (run-time type information), so it fails to compile with -fno-rtti, and it can search the class tree at run time, which is why real-time flight code avoids it.',
    flags: [
      ['<Derived*>', 'the type you hope it is; gives nullptr if it is not'],
      ['<Derived&>', 'the reference form; throws std::bad_cast if it is not'],
    ],
    example: { command: 'if (auto* g = dynamic_cast<Gyro*>(s)) g->calibrate();', says: 'Calls calibrate() only if the sensor s really is a Gyro; otherwise g is nullptr and nothing happens.' },
    seeAlso: ['static_cast', 'typeid'],
  },
  {
    name: 'goto',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Transfers control unconditionally.',
    source: 'cppreference.com',
    when: 'Jumps straight to a label elsewhere in the same function. Safety-critical rules such as the Power of Ten ban it, because jumps make the flow hard to follow and check.',
    example: { command: 'goto done;  // jumps to the line labeled done:', says: 'Skips everything up to the label done: and carries on from there.' },
  },
  {
    name: 'not',
    lang: 'cpp',
    kind: 'keyword',
    official: 'alternative operators: as an alternative for !',
    source: 'cppreference.com (keyword not)',
    when: 'Another spelling of !, the logical "not". It is legal everywhere, but ! is what most code uses.',
    example: { command: 'if (not armed) std::puts("SAFE");', says: 'Prints SAFE when armed is false, exactly like !armed.' },
    seeAlso: ['and', 'or'],
  },
  {
    name: 'or',
    lang: 'cpp',
    kind: 'keyword',
    official: 'alternative operators: as an alternative for ||',
    source: 'cppreference.com (keyword or)',
    when: 'Another spelling of ||, the logical "or". Like ||, it stops early: if the left side is true, the right side is never run.',
    example: { command: 'if (abort_cmd or pressure > limit) safe_mode();', says: 'Calls safe_mode() if either is true, exactly like ||.' },
    seeAlso: ['and', 'not'],
  },
  {
    name: 'register',
    lang: 'cpp',
    kind: 'keyword',
    official: 'Automatic storage duration specifier (deprecated). (until C++17) The keyword is unused and reserved. (since C++17)',
    source: 'cppreference.com (keyword register)',
    when: 'An old hint asking the compiler to keep a variable in a processor register. C++17 removed that meaning, so in modern C++ writing it is an error; you only meet it in old code or in C.',
    example: { command: 'register int i = 0;  // error in C++17', says: 'Fails to compile with -std=c++17 or later, because register no longer means anything.' },
  },
  {
    name: 'signed',
    lang: 'cpp',
    kind: 'keyword',
    official: 'signed — target type will have signed representation (this is the default if omitted)',
    source: 'cppreference.com (Fundamental types)',
    when: 'Says an integer type can hold negative numbers. int, short and long are already signed, so you mostly see it in signed char. Going past the largest value of a signed type is overflow, which is undefined behavior.',
    example: { command: 'signed char offset = -12;', says: 'Makes a one-byte integer holding -12.' },
    seeAlso: ['int', 'unsigned'],
  },
  {
    name: 'std::advance',
    aliases: ['advance'],
    lang: 'cpp',
    kind: 'function',
    official: 'A generalization of pointer arithmetic.',
    source: 'libstdc++ documentation',
    when: 'Moves an iterator n places, for containers such as std::list where it + n does not compile. It changes the iterator you pass and returns nothing; on a list it walks one step at a time.',
    flags: [
      ['(it, n)', 'the iterator to move and how many places'],
    ],
    example: { command: 'auto it = log.begin();\nstd::advance(it, 3);', says: 'Moves it forward three elements, so it points at the fourth entry.' },
    seeAlso: ['std::next', 'std::prev', 'std::distance'],
  },
  {
    name: 'std::align_val_t',
    aliases: ['align_val_t'],
    lang: 'cpp',
    kind: 'type',
    official: 'type used to pass alignment to alignment-aware allocation and deallocation functions',
    source: 'cppreference.com',
    when: 'Since C++17, when a type needs more alignment than the heap normally gives, new calls an operator new overload that also receives a std::align_val_t. A no-heap build that replaces operator new must replace those forms too.',
    example: { command: 'void* p = ::operator new(64, std::align_val_t{32});', says: 'Asks for 64 bytes that start at an address divisible by 32.' },
  },
  {
    name: 'std::any',
    lang: 'cpp',
    kind: 'class',
    official: 'A type-safe container of any type.',
    source: 'libstdc++ documentation',
    when: 'You need one variable that can hold a value of any type, decided while the program runs. It may allocate, and reading it back needs std::any_cast with the exact type, so flight code prefers std::variant.',
    flags: [
      ['has_value()', 'true if it holds something'],
      ['type()', 'the typeid of what it holds (needs RTTI)'],
    ],
    example: { command: 'std::any a = 3.5;', says: 'Stores the double 3.5 in a.' },
    seeAlso: ['std::any_cast', 'std::variant', '<any>'],
  },
  {
    name: 'std::any::type',
    aliases: ['any::type'],
    lang: 'cpp',
    kind: 'method',
    official: 'The typeid of the contained object, or typeid(void) if empty.',
    source: 'libstdc++ documentation',
    when: 'Asks a std::any what type it holds, while the program runs. It relies on RTTI, so under -fno-rtti the member disappears and the call fails with "has no member named".',
    example: { command: 'bool is_double = (a.type() == typeid(double));', says: 'Sets is_double to true if a holds a double.' },
    seeAlso: ['std::any', 'typeid'],
  },
  {
    name: 'std::any_cast',
    aliases: ['any_cast'],
    lang: 'cpp',
    kind: 'function',
    official: 'Access the contained object.',
    source: 'libstdc++ documentation',
    when: 'Gets the value back out of a std::any. Ask for the wrong type and the value form throws std::bad_any_cast; the pointer form, any_cast<T>(&a), returns nullptr instead and works without RTTI.',
    flags: [
      ['<T>(a)', 'the value; throws if a does not hold a T'],
      ['<T>(&a)', 'a pointer to the value, or nullptr if a does not hold a T'],
    ],
    example: { command: 'if (auto* p = std::any_cast<int>(&a)) std::printf("%d\\n", *p);', says: 'Prints the int inside a, or does nothing if a does not hold an int.' },
    seeAlso: ['std::any'],
  },
  {
    name: 'std::as_bytes',
    aliases: ['as_bytes'],
    lang: 'cpp',
    kind: 'function',
    official: 'converts a span into a view of its underlying bytes',
    source: 'cppreference.com',
    when: "You want to look at the raw bytes of some values, for example to write a telemetry packet, without copying. The bytes come out in your machine's byte order.",
    example: { command: 'auto raw = std::as_bytes(std::span{readings});', says: 'Views the same memory as readings as a read-only span of std::byte.' },
    seeAlso: ['std::span', 'std::byte'],
  },
  {
    name: 'std::atomic_flag',
    aliases: ['atomic_flag'],
    lang: 'cpp',
    kind: 'class',
    official: 'the lock-free boolean atomic type',
    source: 'cppreference.com',
    when: 'The simplest atomic type: a true/false flag that every platform promises is lock-free. You can build a tiny spin lock with test_and_set and clear.',
    flags: [
      ['test_and_set()', 'set it and return what it was before'],
      ['clear()', 'set it back to false'],
    ],
    example: { command: 'std::atomic_flag busy;  // starts clear since C++20\nwhile (busy.test_and_set(std::memory_order_acquire)) {}', says: 'Spins until this thread is the one that set the flag.' },
    seeAlso: ['std::atomic'],
  },
  {
    name: 'std::atomic_signal_fence',
    aliases: ['atomic_signal_fence'],
    lang: 'cpp',
    kind: 'function',
    official: 'fence between a thread and a signal handler executed in the same thread',
    source: 'cppreference.com',
    when: 'Stops the compiler from moving memory reads and writes across this point, for code shared with a signal handler on the same thread. It emits no processor instruction, so it does nothing for other threads.',
    example: { command: 'std::atomic_signal_fence(std::memory_order_release);', says: 'Keeps earlier writes before this line, as seen by a signal handler in this thread.' },
    seeAlso: ['std::atomic_thread_fence', 'std::memory_order'],
  },
  {
    name: 'std::auto_ptr',
    aliases: ['auto_ptr'],
    lang: 'cpp',
    kind: 'class',
    official: 'smart pointer with strict object ownership semantics',
    source: 'cppreference.com',
    when: 'The C++98 smart pointer that came before std::unique_ptr. Copying it secretly stole the object, which broke inside containers. C++17 removed it; use std::unique_ptr.',
    example: { command: 'std::auto_ptr<Engine> e(new Engine);  // gone in C++17', says: 'Fails to compile with -std=c++17 or later.' },
    seeAlso: ['std::unique_ptr'],
  },
  {
    name: 'std::bad_expected_access',
    aliases: ['bad_expected_access'],
    lang: 'cpp',
    kind: 'exception',
    official: 'Exception thrown by std::expected when the value() is not present.',
    source: 'libstdc++ documentation',
    when: 'Thrown when you call value() on a std::expected that holds an error. In a build without exceptions that means the program aborts, so test if (r) first.',
    example: { command: 'try { double v = r.value(); } catch (const std::bad_expected_access<Err>&) { /* handle */ }', says: 'Catches the case where r held an error instead of a value.' },
    seeAlso: ['std::expected'],
  },
  {
    name: 'std::bad_function_call',
    aliases: ['bad_function_call'],
    lang: 'cpp',
    kind: 'exception',
    official: "Exception class thrown when class template function's operator() is called with an empty target.",
    source: 'libstdc++ documentation',
    when: 'Thrown when you call a std::function that holds nothing. Test it with if (fn) before calling.',
    example: { command: 'std::function<void()> fn;\nif (fn) fn();', says: 'Calls fn only if it holds something, so bad_function_call is never thrown.' },
    seeAlso: ['std::function'],
  },
  {
    name: 'std::bad_variant_access',
    aliases: ['bad_variant_access'],
    lang: 'cpp',
    kind: 'exception',
    official: 'exception thrown on invalid accesses to the value of a variant',
    source: 'cppreference.com',
    when: 'Thrown by std::get<T>(v) when the variant holds a different alternative. std::get_if returns nullptr instead, and std::visit avoids the question.',
    example: { command: 'std::get<Coast>(mode);  // throws if mode is not Coast', says: 'Returns the Coast inside mode, or throws std::bad_variant_access.' },
    seeAlso: ['std::variant', 'std::get', 'std::get_if'],
  },
  {
    name: 'std::basic_format_string',
    aliases: ['basic_format_string'],
    lang: 'cpp',
    kind: 'class',
    official: 'class template that performs compile-time format string checks at construction time',
    source: 'cppreference.com',
    when: "You meet it in error messages: it is the type of std::format's first parameter. Its constructor is consteval, so the format string is checked against the argument types while compiling, which is why a bad format string is an error and not a crash.",
    example: { command: 'std::format("{:d}", "COAST");  // compile error', says: 'Fails to compile, because {:d} asks for a number and "COAST" is text.' },
    seeAlso: ['std::format'],
  },
  {
    name: 'std::bool_constant',
    aliases: ['bool_constant'],
    lang: 'cpp',
    kind: 'type',
    official: 'Alias template for compile-time boolean constant types.',
    source: 'libstdc++ documentation',
    when: 'The bool version of std::integral_constant. std::true_type and std::false_type are its two values, and most type traits inherit from one of them.',
    example: { command: 'using fast = std::bool_constant<(sizeof(void*) == 8)>;', says: 'Makes fast equal to std::true_type on a 64-bit machine.' },
    seeAlso: ['std::integral_constant', 'std::true_type', 'std::false_type'],
  },
  {
    name: 'std::call_once',
    aliases: ['call_once'],
    lang: 'cpp',
    kind: 'function',
    official: 'Invoke a callable and synchronize with other calls using the same flag',
    source: 'libstdc++ documentation',
    when: 'Runs a set-up function exactly once, even when several threads reach it at the same time. A function-local static does the same job with less code.',
    flags: [
      ['(flag, f, args...)', 'a std::once_flag and the function to run once'],
    ],
    example: { command: 'static std::once_flag once;\nstd::call_once(once, load_config);', says: 'Calls load_config the first time only; other threads wait until it finishes.' },
  },
  {
    name: 'std::cerr',
    aliases: ['cerr'],
    lang: 'cpp',
    kind: 'constant',
    official: 'Linked to standard error (unbuffered)',
    source: 'libstdc++ documentation',
    when: 'Send error messages here instead of std::cout. It writes at once, so the message survives even if the program crashes right after.',
    example: { command: 'std::cerr << "sensor timeout\\n";', says: 'Prints sensor timeout to the error stream straight away.' },
    seeAlso: ['std::cout', 'std::endl'],
  },
  {
    name: 'std::chrono::high_resolution_clock',
    aliases: ['high_resolution_clock', 'chrono::high_resolution_clock'],
    lang: 'cpp',
    kind: 'class',
    official: 'Highest-resolution clock',
    source: 'libstdc++ documentation',
    when: 'The name sounds right for timing, but it is allowed to be just another name for system_clock, which can jump. For measuring how long something took, use std::chrono::steady_clock.',
    example: { command: 'auto t = std::chrono::high_resolution_clock::now();', says: 'Reads the clock; on g++ this is the same as system_clock::now().' },
    seeAlso: ['std::chrono::steady_clock', 'std::chrono::system_clock'],
  },
  {
    name: 'std::chrono::seconds::zero',
    aliases: ['seconds::zero', 'chrono::seconds::zero'],
    lang: 'cpp',
    kind: 'method',
    official: 'returns the special duration value zero',
    source: 'cppreference.com',
    when: 'Gives a duration of zero seconds, for starting a total or comparing. It is a named function that builds an object, a pattern worth copying in your own types.',
    example: { command: 'auto total = std::chrono::seconds::zero();', says: 'Makes total a duration of 0 seconds.' },
    seeAlso: ['std::chrono::seconds', 'std::chrono::duration'],
  },
  {
    name: 'std::chrono::system_clock',
    aliases: ['system_clock', 'chrono::system_clock'],
    lang: 'cpp',
    kind: 'class',
    official: 'System clock.',
    source: 'libstdc++ documentation',
    when: 'The wall clock: the real date and time, counted from 1 January 1970 UTC. It can jump when the computer corrects its time, so use it for time stamps and std::chrono::steady_clock for measuring durations.',
    flags: [
      ['now()', 'the current time point'],
    ],
    example: { command: 'const auto wall = std::chrono::system_clock::now();', says: 'Reads the current date and time.' },
    seeAlso: ['std::chrono::system_clock::now', 'std::chrono::steady_clock'],
  },
  {
    name: 'std::condition_variable::wait',
    aliases: ['condition_variable::wait'],
    lang: 'cpp',
    kind: 'method',
    official: 'blocks the current thread until the condition variable is awakened',
    source: 'cppreference.com',
    when: 'Puts a thread to sleep until another thread signals that something changed. It takes a std::unique_lock, not a lock_guard, because it unlocks while asleep; always pass a predicate so spurious wake-ups and missed signals cannot fool you.',
    flags: [
      ['(lock)', 'a std::unique_lock on the mutex, held when you call'],
      ['(lock, pred)', 'also keeps waiting until pred() is true'],
    ],
    example: { command: 'cv.wait(lock, [&] { return !queue.empty(); });', says: 'Sleeps until the queue has something in it, then returns with the lock held again.' },
    seeAlso: ['std::condition_variable', 'std::unique_lock'],
  },
  {
    name: 'std::copyable_function',
    aliases: ['copyable_function'],
    lang: 'cpp',
    kind: 'class',
    official: 'copyable wrapper of any copy constructible callable object that supports qualifiers in a given call signature',
    source: 'cppreference.com',
    when: 'The C++26 tidier replacement for std::function: it holds any copyable callable with a given signature. g++ 13 does not have it.',
    example: { command: 'std::copyable_function<void(int)> on_tick = [](int n) { std::printf("%d\\n", n); };', says: 'Stores a lambda that prints its argument.' },
    seeAlso: ['std::function', 'std::move_only_function', 'std::function_ref'],
  },
  {
    name: 'std::count',
    lang: 'cpp',
    kind: 'function',
    official: 'Count the number of copies of a value in a sequence.',
    source: 'libstdc++ documentation',
    when: 'Counts how many elements equal a value. Beware using namespace std: then your own variable called count clashes with it and g++ reports "reference to count is ambiguous".',
    flags: [
      ['(first, last, value)', 'the range and the value to look for'],
    ],
    example: { command: 'auto n = std::count(codes.begin(), codes.end(), 42);', says: 'Counts how many times 42 appears in codes.' },
    seeAlso: ['std::count_if', 'std::ranges::count'],
  },
  {
    name: 'std::cref',
    aliases: ['cref'],
    lang: 'cpp',
    kind: 'function',
    official: 'Denotes a const reference should be taken to a variable.',
    source: 'libstdc++ documentation',
    when: 'std::thread and std::bind copy their arguments. Wrap an argument in std::cref to pass a read-only reference instead, and make sure the variable outlives the thread.',
    example: { command: 'std::thread t(print_stats, std::cref(samples));', says: 'Starts a thread that reads samples through a const reference instead of a copy.' },
    seeAlso: ['std::ref', 'std::reference_wrapper', 'std::thread'],
  },
  {
    name: 'std::cv_status::no_timeout',
    aliases: ['cv_status::no_timeout'],
    lang: 'cpp',
    kind: 'constant',
    official: 'the condition variable was awakened with notify_all, notify_one, or spuriously',
    source: 'cppreference.com',
    when: 'What wait_for and wait_until return without a predicate when the wait ended before the time ran out. It does not mean your condition is true: a wake-up can be spurious, so prefer the predicate versions.',
    example: { command: 'if (cv.wait_for(lock, 10ms) == std::cv_status::no_timeout) check_queue();', says: 'Checks the queue if the thread was woken before 10 ms passed.' },
    seeAlso: ['std::cv_status', 'std::cv_status::timeout'],
  },
  {
    name: 'std::default_delete',
    aliases: ['default_delete'],
    lang: 'cpp',
    kind: 'class',
    official: 'Primary template of default_delete, used by unique_ptr for single objects',
    source: 'libstdc++ documentation',
    when: 'The deleter std::unique_ptr uses when you do not give one: it calls delete. It refuses to compile if the class is incomplete at that point, which is why the pimpl idiom defines the destructor in the .cpp file.',
    example: { command: 'std::unique_ptr<Engine, std::default_delete<Engine>> e;', says: 'The same type as std::unique_ptr<Engine>, with the default deleter written out.' },
    seeAlso: ['std::unique_ptr'],
  },
  {
    name: 'std::dynamic_extent',
    aliases: ['dynamic_extent'],
    lang: 'cpp',
    kind: 'constant',
    official: 'a constant of type std::size_t signifying that the span has dynamic extent',
    source: 'cppreference.com',
    when: 'The marker a std::span uses for "size known only at run time". It is the largest value a std::size_t can hold.',
    example: { command: 'std::span<double, std::dynamic_extent> s = v;', says: 'The same as std::span<double>: a view whose size is stored at run time.' },
    seeAlso: ['std::span'],
  },
  {
    name: 'std::enable_if',
    aliases: ['enable_if'],
    lang: 'cpp',
    kind: 'class',
    official: 'Define a member typedef type only if a boolean constant is true.',
    source: 'libstdc++ documentation',
    when: 'The pre-C++20 way to switch a template off for some types (SFINAE). The error messages are long; in C++20 write a concept or a requires clause instead.',
    flags: [
      ['<Cond, T>', 'the condition, and the type to give when it is true'],
      ['::type', 'exists only when the condition is true'],
    ],
    example: { command: 'template <class T, class = std::enable_if_t<std::is_floating_point_v<T>>>\nT half(T x) { return x / 2; }', says: 'Makes half usable only with floating-point types; half(3) will not compile.' },
    seeAlso: ['std::enable_if_t', 'std::is_floating_point'],
  },
  {
    name: 'std::enable_shared_from_this',
    aliases: ['enable_shared_from_this'],
    lang: 'cpp',
    kind: 'class',
    official: 'Base class allowing use of the member function shared_from_this.',
    source: 'libstdc++ documentation',
    when: 'A class that is always owned by a std::shared_ptr inherits from it so its members can hand out more shared_ptrs to itself. Calling shared_from_this() when no shared_ptr owns the object throws std::bad_weak_ptr.',
    example: { command: 'class Link : public std::enable_shared_from_this<Link> { /* ... */ };', says: "Lets Link's members call shared_from_this() to get a shared_ptr to themselves." },
    seeAlso: ['std::shared_ptr', 'std::weak_ptr'],
  },
  {
    name: 'std::endian',
    aliases: ['endian'],
    lang: 'cpp',
    kind: 'type',
    official: 'Byte order constants',
    source: 'libstdc++ documentation',
    when: 'Tells you, while compiling, whether your machine stores the lowest byte first (little) or last (big). Use it with if constexpr when writing telemetry in a fixed byte order.',
    flags: [
      ['little, big', 'the two byte orders'],
      ['native', 'the byte order of the machine you compile for'],
    ],
    example: { command: 'if constexpr (std::endian::native == std::endian::little) { /* swap bytes */ }', says: 'Compiles the byte-swap only on little-endian machines such as x86.' },
    seeAlso: ['std::endian::native', 'std::endian::little', 'std::byteswap', '<bit>'],
  },
  {
    name: 'std::equal_range',
    aliases: ['equal_range'],
    lang: 'cpp',
    kind: 'function',
    official: 'Finds the largest subrange in which val could be inserted at any place in it without changing the ordering.',
    source: 'libstdc++ documentation',
    when: 'On a sorted range, gives both ends of the run of elements equal to a key, as a pair of iterators. The range must be sorted by the same rule, or the answer is meaningless.',
    example: { command: 'auto [lo, hi] = std::equal_range(ids.begin(), ids.end(), 7);', says: 'Makes lo point at the first 7 and hi just past the last 7; hi - lo is how many 7s there are.' },
    seeAlso: ['std::lower_bound', 'std::upper_bound'],
  },
  {
    name: 'std::errc::result_out_of_range',
    aliases: ['errc::result_out_of_range'],
    lang: 'cpp',
    kind: 'constant',
    official: 'The scoped enumeration std::errc defines the values of portable error conditions that correspond to the POSIX error codes.',
    source: 'cppreference.com (std::errc)',
    when: 'The portable name for ERANGE, "result out of range". std::from_chars returns it when the number in the text is too big for the type.',
    example: { command: 'if (ec == std::errc::result_out_of_range) std::puts("too big");', says: 'Prints too big when the parsed number did not fit.' },
    seeAlso: ['std::errc', 'std::errc::invalid_argument', 'std::from_chars'],
  },
  {
    name: 'std::exception_ptr',
    aliases: ['exception_ptr'],
    lang: 'cpp',
    kind: 'class',
    official: 'An opaque pointer to an arbitrary exception.',
    source: 'libstdc++ documentation',
    when: "A handle that keeps a caught exception alive so it can be carried to another thread and thrown there. Futures use it to pass a worker's exception back to get().",
    example: { command: 'std::exception_ptr err = std::current_exception();', says: 'Inside a catch block, saves the exception being handled in err.' },
    seeAlso: ['std::current_exception', 'std::rethrow_exception'],
  },
  {
    name: 'std::execution::seq',
    aliases: ['execution::seq'],
    lang: 'cpp',
    kind: 'constant',
    official: 'global execution policy objects',
    source: 'cppreference.com',
    when: 'Passed first to an algorithm to say "run it in order on the calling thread only". It is the safe default when the other policies (par, par_unseq) would make your code race.',
    example: { command: 'std::sort(std::execution::seq, v.begin(), v.end());', says: 'Sorts v on this thread only, the same as without a policy.' },
    seeAlso: ['std::execution::par', 'std::execution::par_unseq', '<execution>'],
  },
  {
    name: 'std::extent',
    aliases: ['extent'],
    lang: 'cpp',
    kind: 'class',
    official: 'obtains the size of an array type along a specified dimension',
    source: 'cppreference.com',
    when: 'A type trait that tells you, while compiling, how many elements a built-in array type has along one dimension. This is where std::span got the word "extent".',
    flags: [
      ['<T, N>', 'the array type and which dimension, counting from 0'],
    ],
    example: { command: 'static_assert(std::extent_v<double[3][4], 1> == 4);', says: 'Checks at compile time that the second dimension of double[3][4] has 4 elements.' },
    seeAlso: ['std::span'],
  },
  {
    name: 'std::false_type',
    aliases: ['false_type'],
    lang: 'cpp',
    kind: 'type',
    official: 'The type used as a compile-time boolean with false value.',
    source: 'libstdc++ documentation',
    when: 'A type whose value is false. Traits such as std::is_pointer<int> inherit from it, and tag dispatch uses it as an empty argument to choose an overload.',
    example: { command: 'static_assert(!std::false_type::value);', says: 'Passes, because std::false_type::value is false.' },
    seeAlso: ['std::true_type', 'std::bool_constant'],
  },
  {
    name: 'std::filesystem::filesystem_error',
    aliases: ['filesystem::filesystem_error', 'filesystem_error'],
    lang: 'cpp',
    kind: 'exception',
    official: 'an exception thrown on file system errors',
    source: 'cppreference.com',
    when: 'What the throwing forms of std::filesystem functions throw, for example when permission is denied. In a build without exceptions, use the overloads that take a std::error_code& instead.',
    example: { command: 'catch (const std::filesystem::filesystem_error& e) { std::puts(e.what()); }', says: 'Prints the message when a file operation failed.' },
    seeAlso: ['std::filesystem', 'std::error_code'],
  },
  {
    name: 'std::filesystem::remove',
    aliases: ['filesystem::remove'],
    lang: 'cpp',
    kind: 'function',
    official: 'removes a file or empty directory',
    source: 'cppreference.com',
    when: 'Deletes one file or one empty folder. The one-argument form throws on failure; pass a std::error_code as the second argument to get the failure as a value instead.',
    flags: [
      ['(p)', 'the path; throws filesystem_error on failure'],
      ['(p, ec)', 'reports failure in ec instead'],
    ],
    example: { command: 'std::error_code ec;\nstd::filesystem::remove("old.log", ec);', says: 'Deletes old.log; if that fails, ec holds the reason and nothing is thrown.' },
    seeAlso: ['std::filesystem', 'std::filesystem::filesystem_error', 'std::error_code'],
  },
  {
    name: 'std::fill',
    lang: 'cpp',
    kind: 'function',
    official: 'Fills the range [first,last) with copies of value.',
    source: 'libstdc++ documentation',
    when: 'Sets every element of a range to the same value, for example to reset a buffer. It only writes to elements that already exist; it never grows the container.',
    flags: [
      ['(first, last, value)', 'the range and the value to write'],
    ],
    example: { command: 'std::fill(buf.begin(), buf.end(), 0.0);', says: 'Sets every element of buf to 0.0.' },
    seeAlso: ['std::iota', 'std::transform'],
  },
  {
    name: 'std::flat_map',
    aliases: ['flat_map'],
    lang: 'cpp',
    kind: 'class',
    official: 'adapts two containers to provide a collection of key-value pairs, sorted by unique keys',
    source: 'cppreference.com',
    when: 'A C++23 map that keeps keys and values in sorted vectors instead of a tree, so lookups are cache friendly. Inserting in the middle moves elements; it suits tables built once and read often. libstdc++ 13 does not have it.',
    example: { command: 'std::flat_map<int, double> limits{{1, 3.5}, {2, 7.0}};', says: 'Makes a sorted table from channel number to limit.' },
    seeAlso: ['std::map', 'std::flat_set', '<flat_map>'],
  },
  {
    name: 'std::flat_set',
    aliases: ['flat_set'],
    lang: 'cpp',
    kind: 'class',
    official: 'adapts a container to provide a collection of unique keys, sorted by keys',
    source: 'cppreference.com',
    when: 'A C++23 set stored in one sorted vector: fast to search and to walk through, slow to insert into. libstdc++ 13 does not have it.',
    example: { command: 'std::flat_set<int> ids{7, 3, 9};', says: 'Makes a set holding 3, 7 and 9, kept in sorted order.' },
    seeAlso: ['std::set', 'std::flat_map', '<flat_set>'],
  },
  {
    name: 'std::for_each',
    aliases: ['for_each'],
    lang: 'cpp',
    kind: 'function',
    official: 'Apply a function to every element of a sequence.',
    source: 'libstdc++ documentation',
    when: 'Calls a function on every element of a range. Unlike most algorithms it returns the function object when done. With a parallel policy, a lambda that changes shared data is a data race.',
    flags: [
      ['(first, last, f)', 'the range and what to call on each element'],
      ['(policy, first, last, f)', 'the same, with an execution policy'],
    ],
    example: { command: 'std::for_each(v.begin(), v.end(), [](double& x) { x *= 2; });', says: 'Doubles every element of v.' },
    seeAlso: ['std::transform', 'std::execution::par'],
  },
  {
    name: 'std::formatter',
    aliases: ['formatter'],
    lang: 'cpp',
    kind: 'class',
    official: 'defines formatting rules for a given type',
    source: 'cppreference.com',
    when: 'Specialize it to teach std::format and std::print how to show your own type, the way operator<< teaches streams.',
    example: { command: 'template <> struct std::formatter<Vec3> : std::formatter<std::string> { /* format() */ };', says: 'Starts a formatter for Vec3 so std::format("{}", v) can print one.' },
    seeAlso: ['std::format'],
  },
  {
    name: 'std::forward_list',
    aliases: ['forward_list'],
    lang: 'cpp',
    kind: 'class',
    official: 'A standard container with linear time access to elements, and fixed time insertion/deletion at any point in the sequence.',
    source: 'libstdc++ documentation',
    when: 'A singly linked list: each element points only to the next one. Its iterators go forward only, and it has no size() member.',
    example: { command: 'std::forward_list<int> ids{3, 1, 4};\nids.push_front(9);', says: 'Makes a linked list 3, 1, 4 and adds 9 at the front.' },
    seeAlso: ['std::list', 'std::vector'],
  },
  {
    name: 'std::fstream',
    aliases: ['fstream'],
    lang: 'cpp',
    kind: 'class',
    official: 'implements high-level file stream input/output operations',
    source: 'cppreference.com (std::basic_fstream)',
    when: 'Opens a file for both reading and writing. It owns the file: the destructor closes it, and it can be moved but not copied. For one direction only, std::ifstream and std::ofstream are simpler.',
    example: { command: 'std::fstream f("track.dat", std::ios::in | std::ios::out);', says: 'Opens track.dat for reading and writing.' },
    seeAlso: ['std::ifstream', 'std::ofstream'],
  },
  {
    name: 'std::function::target_type',
    aliases: ['function::target_type', 'target_type'],
    lang: 'cpp',
    kind: 'method',
    official: 'Determine the type of the target of this function object wrapper.',
    source: 'libstdc++ documentation',
    when: 'Asks a std::function what type of callable it holds. It needs RTTI; under -fno-rtti libstdc++ leaves it out and the call fails with "has no member named".',
    example: { command: 'bool empty = (fn.target_type() == typeid(void));', says: 'Sets empty to true if fn holds nothing.' },
    seeAlso: ['std::function', 'typeid'],
  },
  {
    name: 'std::function_ref',
    aliases: ['function_ref'],
    lang: 'cpp',
    kind: 'class',
    official: 'non-owning wrapper of any callable object',
    source: 'cppreference.com',
    when: 'A C++26 parameter type for "any callable, used only during this call". It never allocates, but it does not own the callable, so storing one past the call dangles like a span. g++ 13 does not have it.',
    example: { command: 'void for_each_sample(std::function_ref<void(double)> f);', says: 'Declares a function that accepts any callable taking a double, without copying it.' },
    seeAlso: ['std::function', 'std::move_only_function', 'std::copyable_function'],
  },
  {
    name: 'std::future_error',
    aliases: ['future_error'],
    lang: 'cpp',
    kind: 'exception',
    official: 'Exception type thrown by futures.',
    source: 'libstdc++ documentation',
    when: 'Thrown by a future\'s get() when something is wrong with the shared state, most often "Broken promise": the std::promise was destroyed without setting a value. Treat it as a bug in the producer.',
    example: { command: 'catch (const std::future_error& e) { std::puts(e.what()); }', says: 'Prints the problem, for example std::future_error: Broken promise.' },
    seeAlso: ['std::future', 'std::promise'],
  },
  {
    name: 'std::future_status::deferred',
    aliases: ['future_status::deferred'],
    lang: 'cpp',
    kind: 'constant',
    official: 'the shared state contains a deferred function, so the result will be computed only when explicitly requested',
    source: 'cppreference.com',
    when: 'What wait_for returns for a future from std::async that has not started and will not until you call get() or wait(). A loop waiting for ready then never ends; pass std::launch::async.',
    example: { command: 'if (f.wait_for(0ms) == std::future_status::deferred) f.wait();', says: 'Runs the deferred work now if it has not started.' },
    seeAlso: ['std::future_status::ready', 'std::async', 'std::launch::async'],
  },
  {
    name: 'std::future_status::ready',
    aliases: ['future_status::ready'],
    lang: 'cpp',
    kind: 'constant',
    official: 'the shared state is ready',
    source: 'cppreference.com',
    when: 'What wait_for returns when the result is there and get() will not block.',
    example: { command: 'if (f.wait_for(0ms) == std::future_status::ready) use(f.get());', says: 'Uses the result only if it is already available.' },
    seeAlso: ['std::future_status::deferred', 'std::future'],
  },
  {
    name: 'std::generator',
    aliases: ['generator'],
    lang: 'cpp',
    kind: 'class',
    official: 'A view that represents synchronous coroutine generator',
    source: 'cppreference.com',
    when: 'The C++23 return type for a coroutine that hands out values with co_yield, one at a time, and works in a range-for. g++ 13 does not have it; it came with GCC 14.',
    example: { command: 'std::generator<int> countdown(int n) { while (n > 0) co_yield n--; }', says: 'Makes countdown(3) produce 3, 2, 1 as you loop over it.' },
    seeAlso: ['<generator>', 'std::coroutine_handle'],
  },
  {
    name: 'std::integral_constant',
    aliases: ['integral_constant'],
    lang: 'cpp',
    kind: 'class',
    official: 'compile-time constant of specified type with specified value',
    source: 'cppreference.com',
    when: 'A class whose only job is to carry a value known while compiling. Type traits inherit from it, which is where their ::value comes from.',
    flags: [
      ['<T, v>', 'the type and the value'],
      ['::value', 'the value itself'],
    ],
    example: { command: 'using three = std::integral_constant<int, 3>;', says: 'Makes three a type whose value is the int 3.' },
    seeAlso: ['std::bool_constant', 'std::true_type', 'std::false_type'],
  },
  {
    name: 'std::invocable',
    aliases: ['invocable'],
    lang: 'cpp',
    kind: 'library',
    official: 'specifies that a callable type can be invoked with a given set of argument types',
    source: 'cppreference.com',
    when: 'A C++20 concept that checks whether something can be called with certain arguments. Use it to constrain a template that takes a callback.',
    example: { command: 'void every_tick(std::invocable<int> auto f);', says: 'Accepts only callables that can be called with an int.' },
    seeAlso: ['std::invoke', 'std::integral'],
  },
  {
    name: 'std::invoke',
    aliases: ['invoke'],
    lang: 'cpp',
    kind: 'function',
    official: 'Invoke a callable object.',
    source: 'libstdc++ documentation',
    when: 'Calls anything callable in one uniform way, including a pointer to member: std::invoke(&Planet::moons, mars) gives mars.moons. The ranges algorithms call projections through it.',
    example: { command: 'int m = std::invoke(&Planet::moons, mars);', says: 'Reads the moons member of mars.' },
    seeAlso: ['std::invocable', 'std::function'],
  },
  {
    name: 'std::is_arithmetic_v',
    aliases: ['is_arithmetic_v'],
    lang: 'cpp',
    kind: 'constant',
    official: 'checks if a type is an arithmetic type',
    source: 'cppreference.com (std::is_arithmetic)',
    when: 'True while compiling when a type is an integer or floating-point type, bool and char included. Two overloads enabled for is_arithmetic_v and is_floating_point_v both match a double, which makes the call ambiguous.',
    example: { command: 'static_assert(std::is_arithmetic_v<float>);', says: 'Passes, because float is a number type.' },
    seeAlso: ['std::is_floating_point_v', 'std::is_integral_v'],
  },
  {
    name: 'std::is_pointer',
    aliases: ['is_pointer'],
    lang: 'cpp',
    kind: 'class',
    official: 'checks if a type is a pointer type',
    source: 'cppreference.com',
    when: 'A type trait that answers "is T a pointer?" while compiling. It also says yes for const and volatile pointers such as int* const, which a home-made version easily misses.',
    example: { command: 'static_assert(std::is_pointer<int* const>::value);', says: 'Passes: int* const is still a pointer.' },
    seeAlso: ['std::true_type', 'std::remove_cv_t'],
  },
  {
    name: 'std::istream_iterator',
    aliases: ['istream_iterator'],
    lang: 'cpp',
    kind: 'class',
    official: 'Provides input iterator semantics for streams.',
    source: 'libstdc++ documentation',
    when: 'Reads values from a stream as if it were a range, such as numbers arriving on a serial line. It is an input iterator: each value can be read once, going forward only.',
    example: { command: 'std::vector<double> v(std::istream_iterator<double>(std::cin), {});', says: 'Reads doubles from the keyboard until the input ends and stores them in v.' },
    seeAlso: ['std::cin', 'std::forward_iterator'],
  },
  {
    name: 'std::launder',
    aliases: ['launder'],
    lang: 'cpp',
    kind: 'function',
    official: 'Pointer optimization barrier [ptr.launder]',
    source: 'libstdc++ documentation',
    when: 'After placement new builds an object in raw storage, reading it through a cast of the storage address is formally undefined. Wrapping that cast in std::launder tells the compiler an object really lives there now. Keeping the pointer placement new returned avoids the problem.',
    example: { command: 'Reading* r = std::launder(reinterpret_cast<Reading*>(storage_));', says: 'Gets a usable pointer to the Reading built in storage_.' },
    seeAlso: ['std::construct_at'],
  },
  {
    name: 'std::layout_left',
    aliases: ['layout_left'],
    lang: 'cpp',
    kind: 'class',
    official: 'column-major multidimensional array layout mapping policy; leftmost extent has stride 1',
    source: 'cppreference.com',
    when: 'Tells a std::mdspan that the data is stored column by column, as Fortran, MATLAB and Eigen do by default.',
    example: { command: 'std::mdspan<double, std::extents<std::size_t, 3, 3>, std::layout_left> A(buf);', says: 'Views buf as a 3 by 3 matrix stored column by column.' },
    seeAlso: ['std::mdspan', 'std::layout_right', 'std::layout_stride'],
  },
  {
    name: 'std::layout_right',
    aliases: ['layout_right'],
    lang: 'cpp',
    kind: 'class',
    official: 'row-major multidimensional array layout mapping policy; rightmost extent has stride 1',
    source: 'cppreference.com',
    when: 'The default layout of std::mdspan: the data is stored row by row, like a C array.',
    example: { command: 'std::mdspan<double, std::extents<std::size_t, 3, 3>, std::layout_right> A(buf);', says: 'Views buf as a 3 by 3 matrix stored row by row.' },
    seeAlso: ['std::mdspan', 'std::layout_left', 'std::layout_stride'],
  },
  {
    name: 'std::layout_stride',
    aliases: ['layout_stride'],
    lang: 'cpp',
    kind: 'class',
    official: 'a layout mapping policy with user-defined strides',
    source: 'cppreference.com',
    when: 'Lets a std::mdspan step through memory by any fixed amount in each direction, for example to view every other column of a bigger matrix.',
    example: { command: 'std::layout_stride::mapping<std::extents<std::size_t, 3, 3>> m{{}, std::array<std::size_t, 2>{6, 2}};', says: 'Describes a 3 by 3 view that moves 6 elements per row and 2 per column.' },
    seeAlso: ['std::mdspan', 'std::layout_left', 'std::layout_right'],
  },
  {
    name: 'std::left',
    lang: 'cpp',
    kind: 'function',
    official: 'sets the placement of fill characters',
    source: 'cppreference.com',
    when: 'Makes the next padded outputs line up on the left, with the fill characters added on the right. Like std::fixed it stays in effect, while std::setw applies only to the next item.',
    example: { command: 'std::cout << std::left << std::setw(8) << "IMU" << "|";', says: 'Prints IMU followed by five spaces, then |.' },
    seeAlso: ['std::setw', 'std::fixed'],
  },
  {
    name: 'std::less',
    lang: 'cpp',
    kind: 'class',
    official: 'function object implementing x < y',
    source: 'cppreference.com',
    when: 'The comparison std::map, std::set and std::sort use unless you give another. It calls <, so a key type without operator< gives a long error that ends in std::less.',
    example: { command: 'std::set<int, std::less<int>> ids;', says: 'The same as std::set<int>: keys kept in increasing order.' },
    seeAlso: ['std::greater', 'std::ranges::less', 'std::map'],
  },
  {
    name: 'std::logic_error',
    aliases: ['logic_error'],
    lang: 'cpp',
    kind: 'exception',
    official: 'One of two subclasses of exception.',
    source: 'libstdc++ documentation',
    when: "The base class for errors in the program's own logic, such as std::out_of_range and std::invalid_argument. Catching it catches all of those.",
    example: { command: 'catch (const std::logic_error& e) { std::puts(e.what()); }', says: 'Catches an out_of_range from vector::at and prints its message.' },
    seeAlso: ['std::exception', 'std::out_of_range', 'std::runtime_error'],
  },
  {
    name: 'std::make_unique_for_overwrite',
    aliases: ['make_unique_for_overwrite'],
    lang: 'cpp',
    kind: 'function',
    official: 'creates a unique pointer that manages a new object',
    source: 'cppreference.com',
    when: 'Like std::make_unique for an array, but the elements are not set to zero. Use it when you will fill every element yourself; reading one before writing it is undefined behavior.',
    example: { command: 'auto buf = std::make_unique_for_overwrite<double[]>(1024);', says: 'Makes a heap array of 1024 doubles with no starting values.' },
    seeAlso: ['std::make_unique', 'std::unique_ptr'],
  },
  {
    name: 'std::memory_order_acq_rel',
    aliases: ['memory_order_acq_rel'],
    lang: 'cpp',
    kind: 'constant',
    official: 'A read-modify-write operation with this memory order is both an acquire operation and a release operation.',
    source: 'cppreference.com',
    when: 'For operations that read and write in one step, such as fetch_add or exchange: it acts as an acquire for what it reads and a release for what it writes. Taking a lock works this way.',
    example: { command: 'count.fetch_add(1, std::memory_order_acq_rel);', says: "Adds 1 to count, seeing earlier writes from other threads and publishing this thread's." },
    seeAlso: ['std::memory_order_acquire', 'std::memory_order_release', 'std::atomic'],
  },
  {
    name: 'std::midpoint',
    aliases: ['midpoint'],
    lang: 'cpp',
    kind: 'function',
    official: 'midpoint between two numbers or pointers',
    source: 'cppreference.com',
    when: 'Finds the middle of two numbers without the overflow that (a + b) / 2 can cause with big integers. With integers it rounds toward the first argument.',
    example: { command: 'int mid = std::midpoint(first, last);', says: 'Sets mid halfway between first and last, safely.' },
    seeAlso: ['<numeric>'],
  },
  {
    name: 'std::minmax',
    aliases: ['minmax'],
    lang: 'cpp',
    kind: 'function',
    official: 'Determines min and max at once as an ordered pair.',
    source: 'libstdc++ documentation',
    when: 'Gets the smaller and the larger value in one call. The pair comes back as min first, then max, and with structured bindings the names follow the position, not the meaning.',
    example: { command: 'auto [lo, hi] = std::minmax(a, b);', says: 'Sets lo to the smaller of a and b and hi to the larger.' },
    seeAlso: ['std::min', 'std::max', 'std::minmax_element'],
  },
  {
    name: 'std::monostate',
    aliases: ['monostate'],
    lang: 'cpp',
    kind: 'class',
    official: 'placeholder type for use as the first alternative in a variant of non-default-constructible types',
    source: 'cppreference.com',
    when: 'An empty type put first in a std::variant to mean "nothing yet". A variant starts out holding its first alternative, so std::variant<std::monostate, double> starts empty.',
    example: { command: 'std::variant<std::monostate, double> reading;', says: 'Makes reading start out holding nothing, at index 0.' },
    seeAlso: ['std::variant'],
  },
  {
    name: 'std::move_if_noexcept',
    aliases: ['move_if_noexcept'],
    lang: 'cpp',
    kind: 'function',
    official: 'Conditionally convert a value to an rvalue.',
    source: 'libstdc++ documentation',
    when: 'Moves an object if its move constructor cannot throw, and copies it otherwise. std::vector uses it when it grows, so mark your move constructors noexcept or the vector copies instead.',
    example: { command: 'T b = std::move_if_noexcept(a);', says: 'Moves a into b if moving cannot throw; otherwise copies it.' },
    seeAlso: ['std::move'],
  },
  {
    name: 'std::mutex::lock',
    aliases: ['mutex::lock'],
    lang: 'cpp',
    kind: 'method',
    official: 'locks the mutex, blocks if the mutex is not available',
    source: 'cppreference.com',
    when: 'Takes the mutex, waiting if another thread holds it. You rarely call it yourself: std::lock_guard calls it and also unlocks. A thread stuck inside it in gdb is waiting for a lock, often a deadlock.',
    example: { command: 'gps_lock.lock();', says: 'Waits until this thread owns gps_lock.' },
    seeAlso: ['std::mutex', 'std::lock_guard', 'std::unique_lock'],
  },
  {
    name: 'std::next',
    lang: 'cpp',
    kind: 'function',
    official: 'increment an iterator',
    source: 'cppreference.com',
    when: 'Gives an iterator n places further on, without changing the one you pass. For a list, std::next(l.begin(), 2) is how you write l.begin() + 2; it walks one step at a time.',
    flags: [
      ['(it)', 'one step forward'],
      ['(it, n)', 'n steps forward'],
    ],
    example: { command: 'auto third = std::next(l.begin(), 2);', says: 'Makes third point at the third element of l.' },
    seeAlso: ['std::prev', 'std::advance', 'std::distance'],
  },
  {
    name: 'std::none_of',
    aliases: ['none_of'],
    lang: 'cpp',
    kind: 'function',
    official: 'Checks that a predicate is false for all the elements of a sequence.',
    source: 'libstdc++ documentation',
    when: 'Asks whether no element passes a test. It stops at the first one that does, and an empty range gives true.',
    flags: [
      ['(first, last, pred)', 'the range and the yes-or-no test'],
    ],
    example: { command: 'bool calm = std::none_of(v.begin(), v.end(), [](double g) { return g > 6.0; });', says: 'Sets calm to true if no reading is above 6.0.' },
    seeAlso: ['std::all_of', 'std::any_of'],
  },
  {
    name: 'std::numbers::pi_v',
    aliases: ['numbers::pi_v', 'pi_v'],
    lang: 'cpp',
    kind: 'constant',
    official: 'the mathematical constant π',
    source: 'cppreference.com',
    when: 'Pi in whichever floating-point type you ask for, as a variable template. std::numbers::pi is the double version.',
    flags: [
      ['<T>', 'the floating-point type you want pi in'],
    ],
    example: { command: 'constexpr float pi_f = std::numbers::pi_v<float>;', says: 'Sets pi_f to pi as a float.' },
    seeAlso: ['std::numbers::pi', '<numbers>'],
  },
  {
    name: 'std::optional::value',
    aliases: ['optional::value'],
    lang: 'cpp',
    kind: 'method',
    official: 'returns the contained value',
    source: 'cppreference.com',
    when: 'Gets the value out of a std::optional, checking first: if it is empty, it throws std::bad_optional_access. Under -fno-exceptions that ends the program, so test has_value() first in flight code.',
    example: { command: 'double alt = maybe_alt.value();', says: 'Gives the altitude inside maybe_alt, or throws if there is none.' },
    seeAlso: ['std::optional', 'std::bad_optional_access'],
  },
  {
    name: 'std::partial_ordering',
    aliases: ['partial_ordering'],
    lang: 'cpp',
    kind: 'class',
    official: 'the result type of 3-way comparison that supports all 6 operators, is not substitutable, and allows incomparable values',
    source: 'cppreference.com',
    when: 'What <=> returns when some pairs cannot be compared at all, as with double, where NaN is neither less, equal nor greater. A struct with a double member gets it from a defaulted <=>, and std::sort cannot cope with NaN.',
    example: { command: 'std::partial_ordering r = 1.0 <=> std::nan("");', says: 'Sets r to std::partial_ordering::unordered.' },
    seeAlso: ['std::strong_ordering', 'std::weak_ordering', '<compare>'],
  },
  {
    name: 'std::pmr',
    lang: 'cpp',
    kind: 'library',
    official: 'Polymorphic allocators and memory resources',
    source: 'cppreference.com (<memory_resource>)',
    when: 'The namespace for containers that take their memory from a memory resource you choose, such as a fixed buffer, instead of the heap. With null_memory_resource as the fallback, running out of room throws instead of quietly using the heap.',
    example: { command: 'std::pmr::vector<double> v{&arena};', says: 'Makes a vector that gets its memory from arena.' },
    seeAlso: ['std::pmr::vector', 'std::pmr::monotonic_buffer_resource', 'std::pmr::null_memory_resource', '<memory_resource>'],
  },
  {
    name: 'std::popcount',
    aliases: ['popcount'],
    lang: 'cpp',
    kind: 'function',
    official: 'The number of bits set in x.',
    source: 'libstdc++ documentation',
    when: 'Counts the 1 bits in an unsigned integer, usually in a single processor instruction. It only accepts unsigned types.',
    example: { command: 'int n = std::popcount(0b1011u);', says: 'Sets n to 3.' },
    seeAlso: ['<bit>'],
  },
  {
    name: 'std::prev',
    lang: 'cpp',
    kind: 'function',
    official: 'decrement an iterator',
    source: 'cppreference.com',
    when: 'Gives an iterator n places back, without changing the one you pass. It needs an iterator that can go backward, so it does not work on std::forward_list.',
    flags: [
      ['(it)', 'one step back'],
      ['(it, n)', 'n steps back'],
    ],
    example: { command: 'auto last = std::prev(l.end());', says: 'Makes last point at the final element of l.' },
    seeAlso: ['std::next', 'std::advance'],
  },
  {
    name: 'std::print',
    lang: 'cpp',
    kind: 'function',
    official: 'prints to stdout or a file stream using formatted representation of the arguments',
    source: 'cppreference.com',
    when: "C++23's type-checked printf: std::format syntax, written straight to the output. libstdc++ 13 has no <print>, so on g++ 13 write std::cout << std::format(...) instead.",
    flags: [
      ['(fmt, args...)', 'the format string with {} places, then the values'],
      ['{:.1f}', 'a number with one decimal place'],
    ],
    example: { command: 'std::print("chamber {:.1f} kPa", p);', says: 'Prints chamber and the pressure with one decimal, with no new line.' },
    seeAlso: ['std::println', 'std::format', '<print>'],
  },
  {
    name: 'std::println',
    aliases: ['println'],
    lang: 'cpp',
    kind: 'function',
    official: 'same as std::print except that each print is terminated by additional new line',
    source: 'cppreference.com',
    when: 'Like std::print, but ends the line for you. Also C++23 and missing from libstdc++ 13.',
    example: { command: 'std::println("chamber {:.1f} kPa", p);', says: 'Prints one line, for example chamber 101.3 kPa.' },
    seeAlso: ['std::print', 'std::format', '<print>'],
  },
  {
    name: 'std::queue',
    lang: 'cpp',
    kind: 'class',
    official: 'A standard container giving FIFO behavior.',
    source: 'libstdc++ documentation',
    when: 'First in, first out: add at the back, take from the front, like ground commands waiting to run. It is a std::deque underneath by default. front() on an empty queue is undefined behavior.',
    flags: [
      ['push(x)', 'add at the back'],
      ['front()', 'the oldest element'],
      ['pop()', 'remove the oldest element'],
      ['empty()', 'true if nothing is waiting'],
    ],
    example: { command: 'std::queue<Command> q;\nq.push(open_valve);\nq.pop();', says: 'Adds a command at the back, then removes the oldest one from the front.' },
    seeAlso: ['std::deque', 'std::stack', 'std::priority_queue'],
  },
  {
    name: 'std::random_device',
    aliases: ['random_device'],
    lang: 'cpp',
    kind: 'class',
    official: 'A standard interface to a platform-specific non-deterministic random number generator (if any are available).',
    source: 'libstdc++ documentation',
    when: 'Gives unpredictable numbers from the operating system, good for seeding an engine. A run seeded this way cannot be repeated unless you log the seed.',
    example: { command: 'std::mt19937_64 eng{std::random_device{}()};', says: 'Seeds a random engine with a fresh unpredictable number.' },
    seeAlso: ['std::mt19937_64', 'std::seed_seq'],
  },
  {
    name: 'std::ranges',
    lang: 'cpp',
    kind: 'library',
    official: 'The ranges library is an extension and generalization of the algorithms and iterator libraries that makes them more powerful by making them composable and less error-prone.',
    source: 'cppreference.com (Ranges library)',
    when: 'The C++20 namespace of algorithms that take a whole range as one argument, plus views and concepts. std::ranges::sort(v) replaces std::sort(v.begin(), v.end()).',
    example: { command: 'std::ranges::sort(v);', says: 'Sorts the whole vector v.' },
    seeAlso: ['std::ranges::sort', 'std::views', '<ranges>'],
  },
  {
    name: 'std::ranges::begin',
    aliases: ['ranges::begin'],
    lang: 'cpp',
    kind: 'function',
    official: 'returns an iterator to the beginning of a range',
    source: 'cppreference.com',
    when: 'Gets the start of any range: a container with begin(), or a plain array. A type counts as a range when std::ranges::begin and std::ranges::end work on it.',
    example: { command: 'auto it = std::ranges::begin(readings);', says: 'Makes it point at the first reading.' },
    seeAlso: ['std::ranges::end', 'std::begin'],
  },
  {
    name: 'std::ranges::count',
    aliases: ['ranges::count'],
    lang: 'cpp',
    kind: 'function',
    official: 'returns the number of elements satisfying specific criteria',
    source: 'cppreference.com',
    when: 'Counts elements equal to a value, taking the whole range as one argument. It works on any range, including your own container once it has begin() and end().',
    example: { command: 'auto n = std::ranges::count(rb, 2);', says: 'Counts how many elements of rb equal 2.' },
    seeAlso: ['std::count', 'std::count_if'],
  },
  {
    name: 'std::ranges::dangling',
    aliases: ['ranges::dangling'],
    lang: 'cpp',
    kind: 'class',
    official: 'a placeholder type indicating that an iterator or a subrange should not be returned since it would be dangling',
    source: 'cppreference.com',
    when: 'What range algorithms return instead of an iterator when you pass a temporary container that dies at the end of the line. It has no * or ->, so the mistake becomes a compile error. Keep the container in a variable first.',
    example: { command: 'auto it = std::ranges::find(read_channels(), 42);  // std::ranges::dangling', says: 'Compiles, but *it fails with "no match for operator*", because the vector is already gone.' },
    seeAlso: ['std::ranges::find', 'std::ranges::enable_borrowed_range'],
  },
  {
    name: 'std::ranges::distance',
    aliases: ['ranges::distance'],
    lang: 'cpp',
    kind: 'function',
    official: 'returns the distance between an iterator and a sentinel, or between the beginning and end of a range',
    source: 'cppreference.com',
    when: 'Counts the elements of a range, or the steps between two iterators. On a range without random access it walks the whole way.',
    example: { command: 'auto n = std::ranges::distance(rb);', says: 'Sets n to the number of elements in rb.' },
    seeAlso: ['std::distance'],
  },
  {
    name: 'std::ranges::enable_borrowed_range',
    aliases: ['ranges::enable_borrowed_range'],
    lang: 'cpp',
    kind: 'constant',
    official: 'The enable_borrowed_range variable template is used to indicate whether a range is a borrowed_range.',
    source: 'cppreference.com',
    when: 'A flag that says iterators into a range stay valid after the range object dies, as with std::span or std::string_view. Range algorithms return real iterators for such types even from a temporary, and std::ranges::dangling for the rest.',
    example: { command: 'template <> inline constexpr bool std::ranges::enable_borrowed_range<MyView> = true;', says: 'Marks MyView as safe to take iterators from, even as a temporary.' },
    seeAlso: ['std::ranges::dangling', 'std::span'],
  },
  {
    name: 'std::ranges::end',
    aliases: ['ranges::end'],
    lang: 'cpp',
    kind: 'function',
    official: 'returns a sentinel indicating the end of a range',
    source: 'cppreference.com',
    when: 'Gets the end of any range, the partner of std::ranges::begin. Like end(), it points one past the last element, so never read through it.',
    example: { command: 'auto stop = std::ranges::end(readings);', says: 'Makes stop mark the end of readings.' },
    seeAlso: ['std::ranges::begin', 'std::end'],
  },
  {
    name: 'std::ranges::fold_left',
    aliases: ['ranges::fold_left'],
    lang: 'cpp',
    kind: 'function',
    official: 'left-folds a range of elements',
    source: 'cppreference.com',
    when: 'The C++23 ranges relative of std::accumulate: combines all elements into one value, starting from init. The type of init sets the type of the result, so start from 0.0 to add doubles.',
    flags: [
      ['(r, init, op)', 'the range, the starting value, and how to combine two values'],
    ],
    example: { command: 'double total = std::ranges::fold_left(thrust, 0.0, std::plus<>{});', says: 'Adds up every value in thrust.' },
    seeAlso: ['std::accumulate', 'std::reduce'],
  },
  {
    name: 'std::ranges::less',
    aliases: ['ranges::less'],
    lang: 'cpp',
    kind: 'class',
    official: 'constrained function object implementing x < y',
    source: 'cppreference.com',
    when: 'The default comparison of the range algorithms. Passing {} as the comparison argument of std::ranges::sort means this one.',
    example: { command: 'std::ranges::sort(planets, {}, &Planet::moons);', says: 'Sorts planets by number of moons, using std::ranges::less for the {}.' },
    seeAlso: ['std::less', 'std::ranges::sort'],
  },
  {
    name: 'std::ranges::random_access_range',
    aliases: ['ranges::random_access_range'],
    lang: 'cpp',
    kind: 'library',
    official: 'specifies a range whose iterator type satisfies random_access_iterator',
    source: 'cppreference.com',
    when: 'A C++20 concept for ranges you can jump around in, such as std::vector or std::deque. std::ranges::sort requires it, so passing a std::list is refused with a short message naming this concept.',
    example: { command: 'static_assert(!std::ranges::random_access_range<std::list<int>>);', says: 'Passes, because a list can only be walked step by step.' },
    seeAlso: ['std::ranges::range', 'std::ranges::sort'],
  },
  {
    name: 'std::ranges::range',
    aliases: ['ranges::range'],
    lang: 'cpp',
    kind: 'library',
    official: 'specifies that a type is a range, that is, it provides a begin iterator and an end sentinel',
    source: 'cppreference.com',
    when: 'The basic C++20 concept for anything you can loop over: std::ranges::begin and std::ranges::end must work on it.',
    example: { command: 'static_assert(std::ranges::range<RingBuffer<int, 5>>);', says: 'Checks at compile time that your ring buffer counts as a range.' },
    seeAlso: ['std::ranges::begin', 'std::ranges::end', 'std::ranges::random_access_range'],
  },
  {
    name: 'std::ranges::to',
    aliases: ['ranges::to'],
    lang: 'cpp',
    kind: 'function',
    official: 'constructs a new non-view object from an input range',
    source: 'cppreference.com',
    when: "C++23: copies a view into a new container at the end of a pipeline. libstdc++ 13 does not have it; there, build the container from the view's begin() and end().",
    example: { command: 'auto v = readings | std::views::filter(ok) | std::ranges::to<std::vector>();', says: 'Collects the readings that pass ok into a new std::vector.' },
    seeAlso: ['std::views', 'std::ranges::copy'],
  },
  {
    name: 'std::ranges::views',
    aliases: ['ranges::views'],
    lang: 'cpp',
    kind: 'library',
    official: 'The namespace alias std::views is provided as a shorthand for std::ranges::views.',
    source: 'cppreference.com (Ranges library)',
    when: 'The namespace where the standard views such as filter, transform and take live. Everyone writes the shorter std::views.',
    example: { command: 'auto evens = std::ranges::views::filter(v, [](int x) { return x % 2 == 0; });', says: 'Makes a view of the even numbers in v, the same as std::views::filter.' },
    seeAlso: ['std::views', 'std::views::filter', 'std::views::transform'],
  },
  {
    name: 'std::recursive_mutex',
    aliases: ['recursive_mutex'],
    lang: 'cpp',
    kind: 'class',
    official: 'provides mutual exclusion facility which can be locked recursively by the same thread',
    source: 'cppreference.com',
    when: 'A mutex the owning thread may lock again; it counts and unlocks when the count returns to zero. Needing it usually means a locking function calls another locking function; splitting out an unlocked helper is the better fix.',
    example: { command: 'std::recursive_mutex m;\nstd::lock_guard<std::recursive_mutex> g(m);', says: 'Locks m; the same thread may lock it again without deadlocking.' },
    seeAlso: ['std::mutex', 'std::lock_guard'],
  },
  {
    name: 'std::reference_wrapper',
    aliases: ['reference_wrapper'],
    lang: 'cpp',
    kind: 'class',
    official: 'CopyConstructible and CopyAssignable reference wrapper',
    source: 'cppreference.com',
    when: 'A reference that can be copied and stored, made with std::ref or std::cref. Storing one in a std::function never allocates.',
    example: { command: 'std::reference_wrapper<int> r = std::ref(total);', says: 'Makes r refer to total; changing r.get() changes total.' },
    seeAlso: ['std::ref', 'std::cref'],
  },
  {
    name: 'std::regex',
    aliases: ['regex'],
    lang: 'cpp',
    kind: 'class',
    official: 'Standard regular expressions.',
    source: 'libstdc++ documentation',
    when: 'A pattern for searching and matching text. It allocates and can be slow, so keep it out of flight code; it is fine in ground tools.',
    example: { command: 'std::regex ch{R"(CH(\\d+))"};', says: 'Makes a pattern that matches CH followed by digits.' },
    seeAlso: ['std::string'],
  },
  {
    name: 'std::remove_cv_t',
    aliases: ['remove_cv_t'],
    lang: 'cpp',
    kind: 'type',
    official: 'removes const and/or volatile specifiers from the given type',
    source: 'cppreference.com (std::remove_cv)',
    when: 'Gives a type with any top-level const or volatile removed, so const double and double are treated alike in a trait.',
    example: { command: 'static_assert(std::is_same_v<std::remove_cv_t<const double>, double>);', says: 'Passes: removing const from const double leaves double.' },
    seeAlso: ['std::remove_cvref_t', 'std::is_same_v'],
  },
  {
    name: 'std::rethrow_exception',
    aliases: ['rethrow_exception'],
    lang: 'cpp',
    kind: 'function',
    official: 'Throw the object pointed to by the exception_ptr.',
    source: 'libstdc++ documentation',
    when: 'Throws a saved exception again, often on another thread than the one that caught it. Futures use this inside get().',
    example: { command: 'if (err) std::rethrow_exception(err);', says: 'Throws the saved exception again here.' },
    seeAlso: ['std::exception_ptr', 'std::current_exception'],
  },
  {
    name: 'std::reverse',
    lang: 'cpp',
    kind: 'function',
    official: 'Reverse a sequence.',
    source: 'libstdc++ documentation',
    when: 'Turns a range back to front, in place.',
    example: { command: 'std::reverse(v.begin(), v.end());', says: 'Makes the last element of v first and the first element last.' },
    seeAlso: ['std::rotate'],
  },
  {
    name: 'std::seed_seq',
    aliases: ['seed_seq'],
    lang: 'cpp',
    kind: 'class',
    official: 'The seed_seq class generates sequences of seeds for random number generators.',
    source: 'libstdc++ documentation',
    when: 'Mixes several numbers into a good seed. Built from a base seed and a case number, it lets you rerun Monte Carlo case 812 on its own.',
    example: { command: 'std::seed_seq seq{base_seed, case_index};\nstd::mt19937_64 eng{seq};', says: 'Seeds eng from both numbers, so the same pair always gives the same random numbers.' },
    seeAlso: ['std::mt19937_64', 'std::random_device'],
  },
  {
    name: 'std::shared_future',
    aliases: ['shared_future'],
    lang: 'cpp',
    kind: 'class',
    official: 'waits for a value (possibly referenced by other futures) that is set asynchronously',
    source: 'cppreference.com',
    when: 'Like std::future, but it can be copied and get() can be called many times, so several threads can wait for the same result. Make one with f.share().',
    example: { command: 'std::shared_future<State> s = f.share();', says: 'Turns f into a shared future that several threads can copy and read.' },
    seeAlso: ['std::future', 'std::promise'],
  },
  {
    name: 'std::sig_atomic_t',
    aliases: ['sig_atomic_t'],
    lang: 'cpp',
    kind: 'type',
    official: 'the integer type that can be accessed as an atomic entity from an asynchronous signal handler',
    source: 'cppreference.com',
    when: 'The type the standard allows a signal handler to write, declared volatile. Use it only for a simple flag between a handler and the rest of the program.',
    example: { command: 'volatile std::sig_atomic_t stop = 0;', says: 'Makes a flag a signal handler may safely set to 1.' },
    seeAlso: ['<csignal>'],
  },
  {
    name: 'std::signed_integral',
    aliases: ['signed_integral'],
    lang: 'cpp',
    kind: 'library',
    official: 'specifies that a type is an integral type that is signed',
    source: 'cppreference.com',
    when: 'A C++20 concept that accepts only signed integer types such as int or long.',
    example: { command: 'void send(std::signed_integral auto x);', says: 'Accepts send(-5) but not send(5u).' },
    seeAlso: ['std::unsigned_integral', 'std::integral'],
  },
  {
    name: 'std::ssize',
    aliases: ['ssize'],
    lang: 'cpp',
    kind: 'function',
    official: 'returns the size of a container or array',
    source: 'cppreference.com',
    when: 'Gives the size as a signed number, so size minus something can go below zero instead of wrapping to a huge value.',
    example: { command: 'for (std::ptrdiff_t i = 0; i < std::ssize(v) - 1; ++i) { /* ... */ }', says: 'Loops safely even when v is empty, because std::ssize(v) - 1 is -1, not a huge number.' },
    seeAlso: ['std::size'],
  },
  {
    name: 'std::stack',
    lang: 'cpp',
    kind: 'class',
    official: 'A standard container giving FILO behavior.',
    source: 'libstdc++ documentation',
    when: 'Last in, first out: the most recent thing added comes off first, like matching brackets. top() or pop() on an empty stack is undefined behavior.',
    flags: [
      ['push(x)', 'add on top'],
      ['top()', 'the newest element'],
      ['pop()', 'remove the newest element'],
      ['empty()', 'true if nothing is on it'],
    ],
    example: { command: "std::stack<char> open;\nopen.push('(');\nopen.pop();", says: 'Pushes an opening bracket, then removes it again.' },
    seeAlso: ['std::vector', 'std::queue'],
  },
  {
    name: 'std::stacktrace',
    aliases: ['stacktrace'],
    lang: 'cpp',
    kind: 'class',
    official: 'approximate representation of an invocation sequence consists of stacktrace entries',
    source: 'cppreference.com (std::basic_stacktrace)',
    when: 'Captures the chain of function calls that led here, for a crash report. g++ 13 needs -std=c++23 and linking with -lstdc++exp.',
    example: { command: 'std::cout << std::stacktrace::current();', says: 'Prints the list of function calls that led to this line.' },
    seeAlso: ['<stacktrace>'],
  },
  {
    name: 'std::string::size',
    aliases: ['string::size'],
    lang: 'cpp',
    kind: 'method',
    official: 'Returns the number of characters in the string, not including any null-termination.',
    source: 'libstdc++ documentation',
    when: 'Gives the length of a string. As a member pointer, &std::string::size can be used as a projection that turns each string into its length.',
    example: { command: 'std::ranges::sort(names, {}, &std::string::size);', says: 'Sorts names from shortest to longest.' },
    seeAlso: ['std::string'],
  },
  {
    name: 'std::strlen',
    aliases: ['strlen'],
    lang: 'cpp',
    kind: 'function',
    official: 'returns the length of a given string',
    source: 'cppreference.com',
    when: 'Counts the characters of a C string up to, but not including, the zero byte at the end. It walks the text every time, and a missing zero byte makes it read past the end.',
    example: { command: 'std::size_t n = std::strlen("COAST");', says: 'Sets n to 5.' },
    seeAlso: ['std::strcmp', '<cstring>'],
  },
  {
    name: 'std::strong_ordering',
    aliases: ['strong_ordering'],
    lang: 'cpp',
    kind: 'class',
    official: 'the result type of 3-way comparison that supports all 6 operators and is substitutable',
    source: 'cppreference.com',
    when: 'What <=> returns when equal values are truly interchangeable and any two values can be compared, as with integers.',
    example: { command: 'std::strong_ordering r = 3 <=> 5;', says: 'Sets r to std::strong_ordering::less.' },
    seeAlso: ['std::weak_ordering', 'std::partial_ordering', '<compare>'],
  },
  {
    name: 'std::system_error',
    aliases: ['system_error'],
    lang: 'cpp',
    kind: 'exception',
    official: 'An exception type that includes an error_code value.',
    source: 'libstdc++ documentation',
    when: 'Thrown when an operating system call fails, for example when std::thread cannot start a thread or join() is called on a thread that is not joinable. code() tells you why.',
    example: { command: 'catch (const std::system_error& e) { std::puts(e.what()); }', says: 'Prints what went wrong, for example when starting a thread failed.' },
    seeAlso: ['std::error_code', 'std::thread'],
  },
  {
    name: 'std::true_type',
    aliases: ['true_type'],
    lang: 'cpp',
    kind: 'type',
    official: 'The type used as a compile-time boolean with true value.',
    source: 'libstdc++ documentation',
    when: 'A type whose value is true. Traits such as std::is_same<int, int> inherit from it, and tag dispatch passes it as an empty argument to pick an overload.',
    example: { command: 'static_assert(std::is_same<int, int>::value);', says: 'Passes: std::is_same<int, int> inherits value = true from std::true_type.' },
    seeAlso: ['std::false_type', 'std::bool_constant', 'std::is_same'],
  },
  {
    name: 'std::try_to_lock',
    aliases: ['try_to_lock'],
    lang: 'cpp',
    kind: 'constant',
    official: 'Tag used to prevent a scoped lock from blocking if a mutex is locked.',
    source: 'libstdc++ documentation',
    when: 'Makes a std::unique_lock try the mutex once instead of waiting. Always check owns_lock() before touching the shared data.',
    example: { command: 'std::unique_lock<std::mutex> lk(m, std::try_to_lock);\nif (lk.owns_lock()) update();', says: 'Updates only if m was free right now; otherwise moves on without waiting.' },
    seeAlso: ['std::unique_lock', 'std::defer_lock', 'std::adopt_lock'],
  },
  {
    name: 'std::type_identity',
    aliases: ['type_identity'],
    lang: 'cpp',
    kind: 'class',
    official: 'Identity metafunction.',
    source: 'libstdc++ documentation',
    when: 'A tiny C++20 struct whose ::type is just T. Wrapping a parameter type in std::type_identity_t stops the compiler from deducing T from that argument.',
    example: { command: 'template <class T> void scale(T& x, std::type_identity_t<T> k);', says: 'Deduces T from x only, so scale(d, 2) works for a double d.' },
    seeAlso: ['std::type_identity_t'],
  },
  {
    name: 'std::unordered_set',
    aliases: ['unordered_set'],
    lang: 'cpp',
    kind: 'class',
    official: "A standard container composed of unique keys (containing at most one of each key value) in which the elements' keys are the elements themselves.",
    source: 'libstdc++ documentation',
    when: 'A set of unique values found by hashing: fast lookups, but the values come out in no useful order. Growing it rehashes and invalidates iterators.',
    flags: [
      ['insert(x)', 'add x if it is not there yet'],
      ['contains(x)', 'true if x is in the set (C++20)'],
      ['count(x)', '1 if x is in the set, else 0'],
    ],
    example: { command: 'std::unordered_set<int> seen{3, 7};\nbool dup = seen.contains(7);', says: 'Makes a set of 3 and 7 and sets dup to true.' },
    seeAlso: ['std::unordered_map', 'std::set', 'std::hash'],
  },
  {
    name: 'std::unsigned_integral',
    aliases: ['unsigned_integral'],
    lang: 'cpp',
    kind: 'library',
    official: 'specifies that a type is an integral type that is unsigned',
    source: 'cppreference.com',
    when: 'A C++20 concept that accepts only unsigned integer types. It is defined as std::integral plus a check, so an overload using it wins over one using plain std::integral.',
    example: { command: 'void send(std::unsigned_integral auto x);', says: 'Accepts send(5u) but not send(-5).' },
    seeAlso: ['std::signed_integral', 'std::integral'],
  },
  {
    name: 'std::vector::at',
    aliases: ['vector::at'],
    lang: 'cpp',
    kind: 'method',
    official: 'Provides access to the data contained in the vector.',
    source: 'libstdc++ documentation',
    when: 'Reads element i with a bounds check: a bad index throws std::out_of_range instead of reading stray memory. Under -fno-exceptions that ends the program, so flight code checks the index itself.',
    example: { command: 'double first = v.at(0);', says: 'Gives the first element of v, or throws if v is empty.' },
    seeAlso: ['std::vector', 'std::out_of_range'],
  },
  {
    name: 'std::vector::push_back',
    aliases: ['vector::push_back'],
    lang: 'cpp',
    kind: 'method',
    official: 'Add data to the end of the vector.',
    source: 'libstdc++ documentation',
    when: 'Adds one element at the end. When the vector is full it allocates a bigger block and moves everything, which breaks pointers and iterators into it and is a hidden heap allocation in a hot loop. Call reserve first.',
    example: { command: 'v.reserve(64);\nv.push_back(9.81);', says: 'Makes room for 64 values, then adds 9.81 at the end without allocating.' },
    seeAlso: ['std::vector'],
  },
  {
    name: 'std::vector::size',
    aliases: ['vector::size'],
    lang: 'cpp',
    kind: 'method',
    official: 'Returns the number of elements in the vector.',
    source: 'libstdc++ documentation',
    when: 'Gives how many elements the vector holds, as an unsigned std::size_t. v.size() - 1 on an empty vector wraps around to a huge number.',
    example: { command: 'std::size_t n = v.size();', says: 'Sets n to the number of elements in v.' },
    seeAlso: ['std::vector', 'std::size_t', 'std::ssize'],
  },
  {
    name: 'std::weak_ordering',
    aliases: ['weak_ordering'],
    lang: 'cpp',
    kind: 'class',
    official: 'the result type of 3-way comparison that supports all 6 operators and is not substitutable',
    source: 'cppreference.com',
    when: 'What <=> returns when any two values compare but "equivalent" values may still differ, such as names compared ignoring upper and lower case.',
    example: { command: 'std::weak_ordering r = std::weak_ordering::equivalent;', says: 'Holds the result "neither is less than the other".' },
    seeAlso: ['std::strong_ordering', 'std::partial_ordering', '<compare>'],
  },
  {
    name: 'testing::InitGoogleTest',
    aliases: ['::testing::InitGoogleTest', 'InitGoogleTest'],
    lang: 'cpp',
    kind: 'function',
    official: 'Initializes GoogleTest.',
    source: 'GoogleTest documentation',
    when: "Call it at the start of your own main when you do not link gtest_main. It reads GoogleTest's command-line flags and removes them from argv. Call it before RUN_ALL_TESTS().",
    flags: [
      ['(&argc, argv)', 'the command line from main; GoogleTest takes out its own flags'],
    ],
    example: { command: '::testing::InitGoogleTest(&argc, argv);\nreturn RUN_ALL_TESTS();', says: 'Sets up GoogleTest from the command line, then runs every test.' },
    seeAlso: ['testing::Test'],
  },
]
