import type { CommandRef } from './types'

const BUILTIN = 'Python built-in docstring'
const DOC = 'Python standard library docstring'
const REF = 'Python Library Reference (docs.python.org)'
const NP = 'NumPy docstring'
const SP = 'SciPy docstring'
const MPL = 'Matplotlib docstring'

export const COMMANDS: CommandRef[] = [
  // ---- Methods on built-in types ----
  {
    name: 'readlines',
    lang: 'python',
    kind: 'method',
    official: 'Return a list of lines from the stream.',
    source: 'Python standard library docstring (io.IOBase.readlines)',
    when: 'You want every line of a small file in a list at once. Each line keeps its "\\n" at the end, and the whole file goes into memory, so for a big log loop over the file instead.',
    example: {
      command: 'with open("crew.txt") as f:\n    lines = f.readlines()',
      says: 'lines is a list like ["Ada\\n", "Sally\\n"], one string per line, each still ending in a newline.',
    },
    seeAlso: ['open', 'str.strip'],
  },
  {
    name: 'today',
    aliases: ['date.today', 'datetime.date.today'],
    lang: 'python',
    kind: 'method',
    official: 'Current date or datetime: same as self.__class__.fromtimestamp(time.time()).',
    source: 'Python standard library docstring (datetime.date.today)',
    when: 'You want today\'s date from the computer\'s clock. Call it once at the outer edge of a program and pass the date in: a function that calls date.today() inside can only be tested on the day you run it.',
    example: { command: 'from datetime import date\nprint(date.today())', says: 'Prints the date on the computer running it, such as 2026-09-29.' },
    seeAlso: ['datetime.timedelta'],
  },

  // ---- Exceptions and warnings ----
  {
    name: 'ArithmeticError',
    lang: 'python',
    kind: 'exception',
    official: 'Base class for arithmetic errors.',
    source: BUILTIN,
    when: 'You want to catch any math failure at once: ZeroDivisionError and OverflowError are both kinds of ArithmeticError. Catching the family is broad, so name the one error you expect when you can.',
    example: {
      command: 'try:\n    rate = fuel_used / seconds\nexcept ArithmeticError:\n    rate = 0.0',
      says: 'When seconds is 0 the ZeroDivisionError is caught, because it is a kind of ArithmeticError.',
    },
    seeAlso: ['ZeroDivisionError', 'try'],
  },
  {
    name: 'Ellipsis',
    lang: 'python',
    kind: 'constant',
    official: 'This object is commonly used by slicing (see Slicings). It supports no special operations. There is exactly one ellipsis object, named "Ellipsis" (a built-in name).',
    source: 'Python library reference (help("ELLIPSIS"), The Ellipsis Object)',
    when: 'You see it written as three dots, .... As a function body it means "left out on purpose", as in a Protocol. In NumPy indexing it means "all the axes I did not name". A function whose body is only ... quietly returns None.',
    example: { command: 'v[..., 0]', says: 'For an (N, 3) array of positions, picks the first column: the x of every point.' },
    seeAlso: ['pass', 'typing.Protocol'],
  },
  {
    name: 'FileExistsError',
    lang: 'python',
    kind: 'exception',
    official: 'File already exists.',
    source: BUILTIN,
    when: 'You tried to create a file or folder that is already there, most often with mkdir on a second run. Pass exist_ok=True to mkdir when "already there" is fine.',
    example: {
      command: 'Path("results").mkdir()',
      says: 'Works the first time; the second run raises FileExistsError. With exist_ok=True it succeeds both times.',
    },
    seeAlso: ['OSError'],
  },
  {
    name: 'KeyboardInterrupt',
    lang: 'python',
    kind: 'exception',
    official: 'Program interrupted by user.',
    source: BUILTIN,
    when: 'Pressing Ctrl-C raises it, so a runaway loop stops with a traceback showing where it was. It is not a kind of Exception, so except Exception lets it through, which is what you want. A bare except: catches it too, and then Ctrl-C stops working.',
    example: {
      command: 'try:\n    run_campaign()\nexcept KeyboardInterrupt:\n    print("stopped by user, saving partial results")',
      says: 'When you press Ctrl-C, prints the message instead of a traceback.',
    },
    seeAlso: ['SystemExit', 'BaseException', 'Exception'],
  },
  {
    name: 'MemoryError',
    lang: 'python',
    kind: 'exception',
    official: 'Out of memory.',
    source: BUILTIN,
    when: 'Python asked for more RAM than it could get, usually for one huge array. On Linux the system often kills the program first, with no traceback at all, so work in chunks before you get close to the limit.',
    example: { command: 'np.ones((200_000, 200_000))', says: 'Asks for about 320 GB at once; on a normal computer it raises MemoryError straight away.' },
  },
  {
    name: 'ModuleNotFoundError',
    lang: 'python',
    kind: 'exception',
    official: 'Module not found.',
    source: BUILTIN,
    when: 'An import could not find the module. Usually the package is not installed in the environment that is running (pip installed it somewhere else), the name has a typo, or a package folder was left out of the build. It is a kind of ImportError.',
    example: { command: 'import gnc.nav', says: 'ModuleNotFoundError: No module named \'gnc.nav\' if that subpackage is not where Python looks.' },
    seeAlso: ['import', 'ImportError', 'sys.path'],
  },
  {
    name: 'NameError',
    lang: 'python',
    kind: 'exception',
    official: 'Name not found globally.',
    source: BUILTIN,
    when: 'You used a name that was never created, most often a typo. A bare except: hides it and your program carries on with wrong results, which is one more reason to name the exception you catch.',
    example: { command: 'samples = [1.2, 1.4]\nprint(len(sampels))', says: 'NameError: name \'sampels\' is not defined.' },
    seeAlso: ['UnboundLocalError'],
  },
  {
    name: 'OSError',
    lang: 'python',
    kind: 'exception',
    official: 'Base class for I/O related errors.',
    source: BUILTIN,
    when: 'The operating system refused something: a missing file, no permission, a full disk, too many open files. FileNotFoundError, PermissionError and TimeoutError are all kinds of OSError, so catching it covers them all.',
    example: {
      command: 'try:\n    f = open("run_042.csv")\nexcept OSError as e:\n    print("cannot open:", e)',
      says: 'Catches a missing file, a permission problem or any other system error and prints the reason.',
    },
    seeAlso: ['FileNotFoundError', 'FileExistsError'],
  },
  {
    name: 'RecursionError',
    lang: 'python',
    kind: 'exception',
    official: 'Recursion limit exceeded.',
    source: BUILTIN,
    when: 'A function called itself too many times without returning, about 1,000 deep by default. Usually the base case is missing or never reached. For deep but correct work, a loop is safer than raising the limit.',
    example: {
      command: 'def countdown(n):\n    return countdown(n - 1)\ncountdown(5)',
      says: 'There is no base case, so it never stops: RecursionError: maximum recursion depth exceeded.',
    },
    seeAlso: ['sys.getrecursionlimit', 'sys.setrecursionlimit'],
  },
  {
    name: 'RuntimeWarning',
    lang: 'python',
    kind: 'exception',
    official: 'Base class for warnings about dubious runtime behavior.',
    source: BUILTIN,
    when: 'NumPy prints one when it divides by zero, overflows or takes the log of a negative number. It does not stop: it carries on with inf or nan, and the warning is easy to miss in a log. Use np.errstate to turn it into an error where it matters.',
    example: {
      command: 'np.array([1.0]) / 0',
      says: 'Gives array([inf]) and prints RuntimeWarning: divide by zero encountered in divide. The program keeps going.',
    },
    seeAlso: ['numpy.seterr', 'numpy.errstate', 'warnings'],
  },
  {
    name: 'SyntaxError',
    lang: 'python',
    kind: 'exception',
    official: 'Invalid syntax.',
    source: BUILTIN,
    when: 'Python checks the grammar of the whole file before it runs any of it, so a missing colon or an unclosed bracket stops everything. The arrow can point just after the real mistake; look at the line above too.',
    example: {
      command: 'if altitude > 100\n    print("space")',
      says: 'SyntaxError: expected \':\'. No line of the file runs, not even the ones above it.',
    },
  },
  {
    name: 'UnboundLocalError',
    lang: 'python',
    kind: 'exception',
    official: 'Local name referenced but not bound to a value.',
    source: BUILTIN,
    when: 'Assigning to a name anywhere in a function (count += 1 counts) makes it local in the whole function, so reading it first fails even though an outer variable has that name. Say global or nonlocal if you mean the outer one.',
    example: {
      command: 'count = 0\ndef tick():\n    count += 1\ntick()',
      says: 'UnboundLocalError: cannot access local variable \'count\' where it is not associated with a value.',
    },
    seeAlso: ['nonlocal', 'global', 'NameError'],
  },

  // ---- Built-in functions and objects ----
  {
    name: 'callable',
    lang: 'python',
    kind: 'function',
    official: 'Return whether the object is callable (i.e., some kind of function).',
    source: BUILTIN,
    when: 'You want to check that something can be called with () before you call it, such as a callback someone passed in. Classes count as callable, because calling a class makes an object.',
    example: { command: 'callable(print), callable(42)', says: 'Gives (True, False). Calling 42() would raise TypeError: \'int\' object is not callable.' },
    seeAlso: ['TypeError'],
  },
  {
    name: 'compile',
    lang: 'python',
    kind: 'function',
    official: 'Compile source into a code object that can be executed by exec() or eval().',
    source: BUILTIN,
    when: 'You have Python code as text and want to turn it into a code object once, then run it many times, or check its grammar without running it. Never compile and run text a user typed: it can do anything your program can.',
    flags: [
      ['filename', 'a name shown in error messages, such as "<formula>"'],
      ['"eval" / "exec"', 'the mode: one expression, or whole statements'],
    ],
    example: {
      command: 'code = compile("thrust / mass", "<formula>", "eval")\neval(code, {"thrust": 7600.0, "mass": 550.0})',
      says: 'Gives about 13.82. The formula is parsed once and can be run again with other numbers.',
    },
    seeAlso: ['exec', 'eval', 'dis.dis'],
  },
  {
    name: 'exec',
    lang: 'python',
    kind: 'function',
    official: 'Execute the given source in the context of globals and locals.',
    source: BUILTIN,
    when: 'You need to run Python statements that are stored as a string, as test checkers do. It always returns None; the results land in the dictionary you pass. Never exec text from a user or a file you do not trust.',
    flags: [['globals', 'the dictionary the code reads names from and writes new names into']],
    example: {
      command: 'ns = {}\nexec("g = 9.81\\nweight = 80 * g", ns)\nprint(ns["weight"])',
      says: 'Prints 784.8000000000001: the code ran inside ns, so its variables are keys there.',
    },
    seeAlso: ['eval', 'compile', 'globals'],
  },
  {
    name: 'exit',
    lang: 'python',
    kind: 'function',
    official: 'Objects that when printed, print a message like "Use quit() or Ctrl-D (i.e. EOF) to exit", and when called, raise SystemExit with the specified exit code.',
    source: REF,
    when: 'You want to leave the interactive Python prompt. It is a helper for the prompt only; in a script use sys.exit, which always exists.',
    example: { command: '>>> exit()', says: 'Ends the Python session and takes you back to the terminal. Ctrl-D on an empty line does the same.' },
    seeAlso: ['quit', 'sys.exit', 'SystemExit'],
  },
  {
    name: 'quit',
    lang: 'python',
    kind: 'function',
    official: 'Objects that when printed, print a message like "Use quit() or Ctrl-D (i.e. EOF) to exit", and when called, raise SystemExit with the specified exit code.',
    source: REF,
    when: 'Another name for exit at the interactive prompt. Typing quit without brackets only prints a reminder of how to leave. In a script use sys.exit instead.',
    example: { command: '>>> quit()', says: 'Leaves the Python prompt and returns to the terminal.' },
    seeAlso: ['exit', 'sys.exit'],
  },
  {
    name: 'license',
    lang: 'python',
    kind: 'function',
    official: 'Object that when printed, prints the message "Type license() to see the full license text", and when called, displays the full license text in a pager-like fashion (one screen at a time).',
    source: REF,
    when: 'You are at the interactive prompt and want to read Python\'s own license. It has nothing to do with the license key in a pyproject.toml, which names the license of your package.',
    example: { command: '>>> license()', says: 'Shows Python\'s license a screen at a time; press Return for more or q to stop.' },
    seeAlso: ['exit'],
  },
  {
    name: 'filter',
    lang: 'python',
    kind: 'function',
    official: 'Return an iterator yielding those items of iterable for which function(item) is true.',
    source: BUILTIN,
    when: 'You want to keep only the items that pass a test. It is lazy, so you can loop over the result only once. A comprehension with an if usually reads more clearly.',
    example: { command: 'list(filter(lambda r: r > 1.0, [0.4, 1.7, 2.2]))', says: 'Gives [1.7, 2.2], the readings above 1.0.' },
    seeAlso: ['map', 'lambda'],
  },
  {
    name: 'format',
    lang: 'python',
    kind: 'function',
    official: 'Return value.__format__(format_spec)',
    source: BUILTIN,
    when: 'You want one value as text in a set style, using the same codes that go after the colon in an f-string. It returns a string; it prints nothing.',
    example: { command: 'format(1234567.891, ",.2f")', says: 'Gives \'1,234,567.89\': thousands separated by commas, two digits after the point.' },
  },
  {
    name: 'frozenset',
    lang: 'python',
    kind: 'type',
    official: 'Build an immutable unordered collection of unique elements.',
    source: BUILTIN,
    when: 'You need a set that can never change, so it can be a dictionary key or live inside another set. A normal set cannot, because it can change.',
    example: {
      command: 'links = {frozenset({"GS1", "SAT7"}): 12.5}',
      says: 'A dictionary keyed by an unordered pair: frozenset({"SAT7", "GS1"}) finds the same entry.',
    },
    seeAlso: ['set', 'dict'],
  },
  {
    name: 'globals',
    lang: 'python',
    kind: 'function',
    official: 'Return the dictionary containing the current scope\'s global variables.',
    source: BUILTIN,
    when: 'You want to see the file\'s top-level names as a real dictionary, or hand them to exec. Changing that dictionary changes the real global variables.',
    example: { command: 'G = 6.674e-11\nprint("G" in globals())', says: 'Prints True: every top-level name in the file is a key in that dictionary.' },
    seeAlso: ['locals', 'exec'],
  },
  {
    name: 'locals',
    lang: 'python',
    kind: 'function',
    official: 'Return a dictionary containing the current scope\'s local variables.',
    source: BUILTIN,
    when: 'You are debugging and want to see every variable inside a function at once. Only read it: writing into it inside a function does not reliably change the variables.',
    example: {
      command: 'def burn(dv):\n    isp = 311\n    return locals()\nburn(12.0)',
      says: 'Gives {\'dv\': 12.0, \'isp\': 311}.',
    },
    seeAlso: ['globals'],
  },
  {
    name: 'hasattr',
    lang: 'python',
    kind: 'function',
    official: 'Return whether the object has an attribute with the given name.',
    source: BUILTIN,
    when: 'You want to know whether an object has a method or field before you use it. The name is a string. A runtime Protocol check works the same way: it looks only at names, not at what the method takes.',
    example: { command: 'hasattr(sensor, "read")', says: 'True if sensor has a read attribute (a method counts), False if not.' },
    seeAlso: ['getattr', 'setattr', 'isinstance'],
  },
  {
    name: 'setattr',
    lang: 'python',
    kind: 'function',
    official: 'Sets the named attribute on the given object to the specified value.',
    source: BUILTIN,
    when: 'You want to set an attribute whose name is in a string. setattr(x, "y", v) is the same as x.y = v, so inside a descriptor\'s __set__ it calls __set__ again and recurses forever; store into obj.__dict__ there instead.',
    example: { command: 'setattr(cfg, "debug", True)', says: 'Same as cfg.debug = True.' },
    seeAlso: ['getattr', 'hasattr'],
  },
  {
    name: 'ord',
    lang: 'python',
    kind: 'function',
    official: 'Return the Unicode code point for a one-character string.',
    source: BUILTIN,
    when: 'You want the number the computer stores for a character. It explains string sorting: "Kiwi" comes before "apple" because every capital letter has a smaller number than every small one.',
    example: { command: 'ord("K"), ord("a")', says: 'Gives (75, 97).' },
    seeAlso: ['sorted'],
  },

  // ---- Standard library ----
  {
    name: 'argparse.ArgumentDefaultsHelpFormatter',
    aliases: ['ArgumentDefaultsHelpFormatter'],
    lang: 'python',
    kind: 'class',
    official: 'Help message formatter which adds default values to argument help.',
    source: DOC,
    when: 'You want --help to show each option\'s default without writing it into every help text. Pass it as formatter_class= when you make the parser.',
    example: {
      command: 'parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)\nparser.add_argument("--seed", type=int, default=42, help="random seed")',
      says: '--help now shows the line: --seed SEED  random seed (default: 42).',
    },
    seeAlso: ['argparse.ArgumentParser'],
  },
  {
    name: 'ast.literal_eval',
    aliases: ['literal_eval'],
    lang: 'python',
    kind: 'function',
    official: 'Evaluate an expression node or a string containing only a Python expression.',
    source: DOC,
    when: 'You need to read plain Python values (numbers, strings, lists, dicts) back from text, safely. Unlike eval it refuses anything that would run code and raises ValueError instead.',
    example: {
      command: 'ast.literal_eval("[7.8, 11.2, 3.1]")',
      says: 'Gives the list [7.8, 11.2, 3.1]. A string like "__import__(\'os\')" raises ValueError instead of running.',
    },
    seeAlso: ['eval', 'json.loads'],
  },
  {
    name: 'binascii.crc32',
    lang: 'python',
    kind: 'function',
    official: 'Compute CRC-32 incrementally.',
    source: DOC,
    when: 'You want a checksum of some bytes to spot a corrupted packet or file. It gives the same number as zlib.crc32. It needs bytes, not str, and it catches accidents, not deliberate tampering.',
    example: { command: 'hex(binascii.crc32(b"123456789"))', says: 'Gives \'0xcbf43926\', the standard CRC-32 check value.' },
    seeAlso: ['zlib.crc32'],
  },
  {
    name: 'cmath.phase',
    lang: 'python',
    kind: 'function',
    official: 'Return argument, also known as the phase angle, of a complex.',
    source: DOC,
    when: 'You want the angle of a complex number, in radians from -pi to pi. It always lands in the right quarter of the plane, which math.atan(b / a) does not.',
    example: {
      command: 'math.degrees(cmath.phase(-1 - 1j))',
      says: 'Gives -135.0. math.atan(-1 / -1) would say 45 degrees, the wrong half of the plane.',
    },
    seeAlso: ['math.atan2', 'math.degrees'],
  },
  {
    name: 'collections.UserDict',
    aliases: ['UserDict'],
    lang: 'python',
    kind: 'class',
    official: 'Class that simulates a dictionary.',
    source: REF,
    when: 'You want your own dictionary-like class that changes how keys are stored or looked up. Unlike a dict subclass, its other methods (update, the constructor, setdefault) go through your __setitem__ and __getitem__. The real dict is in .data.',
    example: {
      command: 'class Channels(UserDict):\n    def __setitem__(self, key, value):\n        self.data[key.lower()] = value\nc = Channels(ALT=410.0)',
      says: 'c.data is {\'alt\': 410.0}: even the constructor used your __setitem__. A plain dict subclass would have skipped it.',
    },
    seeAlso: ['dict'],
  },
  {
    name: 'copy.copy',
    lang: 'python',
    kind: 'function',
    official: 'Shallow copy operation on arbitrary Python objects.',
    source: DOC,
    when: 'You want a new object with the same top-level contents. It is shallow: lists and dicts inside are shared with the original, so changing them changes both.',
    example: {
      command: 'state = {"crew": ["Ada"], "fuel": 90}\nsnap = copy.copy(state)\nsnap["crew"].append("Sally")',
      says: 'state["crew"] is now ["Ada", "Sally"] too, because the inner list is shared. copy.deepcopy copies every layer.',
    },
    seeAlso: ['copy.deepcopy', 'copy'],
  },
  {
    name: 'dis.dis',
    lang: 'python',
    kind: 'function',
    official: 'Disassemble classes, methods, functions, and other compiled objects.',
    source: DOC,
    when: 'You want to see the small bytecode steps Python really runs for a function, to understand what a line costs. The output changes between Python versions.',
    example: { command: 'import dis\ndis.dis(lambda v: v * 2.0)', says: 'Prints the steps: load v, load the constant 2.0, multiply, return.' },
    seeAlso: ['compile'],
  },
  {
    name: 'fractions.Fraction',
    aliases: ['Fraction'],
    lang: 'python',
    kind: 'class',
    official: 'This class implements rational numbers.',
    source: DOC,
    when: 'You want an exact ratio of two whole numbers, with no rounding ever. Build it from ints or a string: Fraction(0.1) records the float\'s binary error exactly, giving 3602879701896397/36028797018963968.',
    flags: [['Fraction(top, bottom)', 'the numerator and denominator, as integers']],
    example: { command: 'Fraction(5, 9) * 18', says: 'Gives Fraction(10, 1): exactly 10.' },
    seeAlso: ['decimal.Decimal'],
  },
  {
    name: 'functools.cache',
    lang: 'python',
    kind: 'function',
    official: 'Simple lightweight unbounded cache. Sometimes called "memoize".',
    source: DOC,
    when: 'Put @cache above a function whose answer depends only on its arguments, and each answer is worked out once and then remembered. The arguments must be hashable, and it never forgets, so memory grows with every new argument.',
    example: {
      command: '@functools.cache\ndef fib(n):\n    return n if n < 2 else fib(n - 1) + fib(n - 2)',
      says: 'fib(80) returns at once: each fib(k) is computed a single time.',
    },
    seeAlso: ['functools.lru_cache'],
  },
  {
    name: 'functools.cmp_to_key',
    aliases: ['cmp_to_key'],
    lang: 'python',
    kind: 'function',
    official: 'Convert a cmp= function into a key= function.',
    source: DOC,
    when: 'You have an old-style comparison function (it returns a negative number, zero or a positive number for two items) and sorted only accepts key=. Write a key function instead when you can; it is simpler and faster.',
    example: {
      command: 'def by_mass(a, b):\n    return a["kg"] - b["kg"]\nsorted(parts, key=functools.cmp_to_key(by_mass))',
      says: 'Sorts the parts lightest first, using the two-argument comparison.',
    },
    seeAlso: ['sorted'],
  },
  {
    name: 'gc.enable',
    lang: 'python',
    kind: 'function',
    official: 'Enable automatic garbage collection.',
    source: DOC,
    when: 'You want Python\'s garbage collector (the part that frees objects stuck pointing at each other) back on after it was switched off. timeit switches it off while timing; pass setup="gc.enable()" to time code as it will really run.',
    example: { command: 'gc.disable()\nbuild_tracks()\ngc.enable()', says: 'Runs build_tracks with the collector off, then turns automatic clean-up back on.' },
    seeAlso: ['timeit'],
  },
  {
    name: 'heapq.merge',
    lang: 'python',
    kind: 'function',
    official: 'Merge multiple sorted inputs into a single sorted output.',
    source: DOC,
    when: 'You have several streams that are each already sorted, like timestamped logs from two sensors, and want one sorted stream without loading everything. It does not check the inputs are sorted.',
    example: { command: 'list(heapq.merge([1, 4, 9], [2, 3, 10]))', says: 'Gives [1, 2, 3, 4, 9, 10].' },
    seeAlso: ['heapq', 'sorted'],
  },
  {
    name: 'importlib.reload',
    lang: 'python',
    kind: 'function',
    official: 'Reload the module and return it.',
    source: DOC,
    when: 'You edited a file while a Python session was running, and import again does nothing because the old module is cached. Objects made before the reload keep the old code, so restarting Python is the reliable fix.',
    example: { command: 'importlib.reload(telemetry)', says: 'Runs telemetry.py again into the same module object, picking up your edits.' },
    seeAlso: ['sys.modules', 'import'],
  },
  {
    name: 'json.load',
    lang: 'python',
    kind: 'function',
    official: 'Deserialize fp (a .read()-supporting file-like object containing a JSON document) to a Python object.',
    source: DOC,
    when: 'You want to read JSON from an open file. json.loads is the one for a string. JSON has no tuples, and dictionary keys always come back as strings.',
    example: { command: 'with open("mission.json") as f:\n    cfg = json.load(f)', says: 'cfg is ordinary Python: dicts, lists, strings and numbers.' },
    seeAlso: ['json.loads', 'json.dump'],
  },
  {
    name: 'logging.NullHandler',
    aliases: ['NullHandler'],
    lang: 'python',
    kind: 'class',
    official: 'This handler does nothing.',
    source: DOC,
    when: 'You are writing a library. Add one to your top-level logger so Python\'s last-resort handler stays quiet, and leave the real setup to the program that uses you. A library must not call basicConfig.',
    example: {
      command: 'logging.getLogger("gnc").addHandler(logging.NullHandler())',
      says: 'The gnc package shows no log output on its own, until the program using it sets up logging.',
    },
    seeAlso: ['logging.getLogger', 'logging.basicConfig'],
  },
  {
    name: 'logging.handlers.RotatingFileHandler',
    aliases: ['RotatingFileHandler'],
    lang: 'python',
    kind: 'class',
    official: 'Handler for logging to a set of files, which switches from one file to the next when the current file reaches a certain size.',
    source: DOC,
    when: 'A long-running job writes a log that must not fill the disk. Set both numbers: with the default maxBytes of 0 it never rotates.',
    flags: [
      ['maxBytes=', 'the size at which it starts a new file'],
      ['backupCount=', 'how many old files to keep (.1, .2, ...)'],
    ],
    example: {
      command: 'h = RotatingFileHandler("campaign.log", maxBytes=5_000_000, backupCount=3)',
      says: 'Writes campaign.log up to about 5 MB, then renames it campaign.log.1 and starts fresh, keeping three old files.',
    },
    seeAlso: ['logging.getLogger'],
  },
  {
    name: 'logging.info',
    lang: 'python',
    kind: 'function',
    official: 'Log a message with severity \'INFO\' on the root logger.',
    source: DOC,
    when: 'A quick script wants an INFO message. INFO is hidden until logging is set to that level. In real code use log = logging.getLogger(__name__) and log.info, because the module-level call quietly sets up the root logger for everyone.',
    example: {
      command: 'logging.basicConfig(level=logging.INFO)\nlogging.info("burn %d complete", 3)',
      says: 'Prints INFO:root:burn 3 complete. Without the basicConfig line, nothing appears.',
    },
    seeAlso: ['logging.getLogger', 'logging.basicConfig'],
  },
  {
    name: 'math.cbrt',
    lang: 'python',
    kind: 'function',
    official: 'Return the cube root of x.',
    source: DOC,
    when: 'You want a cube root, including of a negative number. (-8) ** (1/3) gives a complex number, not -2. It needs Python 3.11 or later.',
    example: { command: 'math.cbrt(-8)', says: 'Gives -2.0.' },
    seeAlso: ['math.sqrt'],
  },
  {
    name: 'math.erf',
    lang: 'python',
    kind: 'function',
    official: 'Error function at x.',
    source: DOC,
    when: 'You need a normal-distribution probability: the chance a reading lands within k standard deviations is erf(k / sqrt(2)). It takes one number; for arrays use scipy.special.erf.',
    example: { command: 'math.erf(3 / math.sqrt(2))', says: 'Gives about 0.9973: a normal reading lands within 3 standard deviations 99.73% of the time.' },
    seeAlso: ['scipy.special.erf'],
  },
  {
    name: 'math.inf',
    lang: 'python',
    kind: 'constant',
    official: 'A floating-point positive infinity. (For negative infinity, use -math.inf.) Equivalent to the output of float(\'inf\').',
    source: REF,
    when: 'You want a starting value bigger than anything, to find a smallest value by hand (use -math.inf for a largest). Watch out: math.inf - math.inf is nan, not zero.',
    example: {
      command: 'best = math.inf\nfor d in [412.0, 398.5]:\n    best = min(best, d)',
      says: 'best ends as 398.5: the first real value always beats infinity.',
    },
    seeAlso: ['math.isnan', 'numpy.inf'],
  },
  {
    name: 'math.isqrt',
    lang: 'python',
    kind: 'function',
    official: 'Return the integer part of the square root of the input.',
    source: DOC,
    when: 'You want the exact whole-number square root of an int, even a huge one, with no float rounding. It returns an int.',
    example: { command: 'math.isqrt(99)', says: 'Gives 9: 9 times 9 is 81, and 10 times 10 is already too big.' },
    seeAlso: ['math.sqrt'],
  },
  {
    name: 'math.prod',
    lang: 'python',
    kind: 'function',
    official: 'Calculate the product of all the elements in the input iterable.',
    source: DOC,
    when: 'You want to multiply all the items together, the way sum adds them. An empty list gives 1.',
    example: { command: 'math.prod([2, 3, 4])', says: 'Gives 24: 2 times 3 times 4.' },
    seeAlso: ['sum', 'numpy.prod', 'functools.reduce'],
  },
  {
    name: 'math.tan',
    lang: 'python',
    kind: 'function',
    official: 'Return the tangent of x (measured in radians).',
    source: DOC,
    when: 'You need the tangent of an angle. It wants radians, so convert degrees first, and it grows huge near 90 degrees.',
    example: { command: 'math.tan(math.radians(45))', says: 'Gives 0.9999999999999999: 1, apart from float rounding.' },
    seeAlso: ['math.radians', 'math.atan', 'math.sin'],
  },
  {
    name: 'os.system',
    lang: 'python',
    kind: 'function',
    official: 'Execute the command in a subshell.',
    source: DOC,
    when: 'You want to run a shell command in one line and only need to know whether it worked: it returns the exit status. subprocess.run is the better tool, and never build the command from text you do not trust.',
    example: { command: 'status = os.system("ls results")', says: 'The listing prints to the terminal; status is 0 if ls succeeded.' },
    seeAlso: ['subprocess.run'],
  },
  {
    name: 're.escape',
    lang: 'python',
    kind: 'function',
    official: 'Escape special characters in a string.',
    source: DOC,
    when: 'You want to match a piece of text exactly, but it contains characters that mean something in a pattern, such as brackets, dots, + or ?. Typical use: pytest.raises(..., match=re.escape(message)).',
    example: {
      command: 'pytest.raises(ValueError, match=re.escape("mass must be > 0 (kg)"))',
      says: 'Matches the message as written. Without re.escape, (kg) would be read as a group and the match would fail.',
    },
    seeAlso: ['re.search', 'pytest.raises'],
  },
  {
    name: 're.search',
    lang: 'python',
    kind: 'function',
    official: 'Scan through string looking for a match to the pattern, returning a Match object, or None if no match was found.',
    source: DOC,
    when: 'You want to find a pattern anywhere in a string, not only at the start. It gives None when there is no match, so check before calling .group().',
    example: { command: 'm = re.search(r"T\\+(\\d+)", "event at T+162 s")\nm.group(1)', says: 'Gives \'162\', the digits after T+.' },
    seeAlso: ['re.escape', 're.Pattern.search'],
  },
  {
    name: 'pdb.pm',
    lang: 'python',
    kind: 'function',
    official: 'Enter post-mortem debugging of the traceback found in sys.last_traceback.',
    source: REF,
    when: 'An exception just happened in an interactive session and you want to look around at the moment it failed. pm is short for post-mortem. Type q to leave.',
    example: { command: '>>> import pdb; pdb.pm()', says: 'Opens the debugger on the line that raised, with all its variables still there to print.' },
    seeAlso: ['pdb.set_trace', 'breakpoint'],
  },
  {
    name: 'pdb.set_trace',
    lang: 'python',
    kind: 'function',
    official: 'Enter the debugger at the calling stack frame.',
    source: REF,
    when: 'You want the program to stop at this line and open the debugger. Since Python 3.7, breakpoint() does the same and can be switched off or redirected without editing the code.',
    example: { command: 'import pdb; pdb.set_trace()', says: 'The program pauses here and shows the (Pdb) prompt. Type c to continue.' },
    seeAlso: ['breakpoint', 'pdb.pm'],
  },
  {
    name: 'sys.breakpointhook',
    lang: 'python',
    kind: 'function',
    official: 'This hook function is called by built-in breakpoint().',
    source: DOC,
    when: 'You want to know what breakpoint() will do. By default it opens pdb, but the PYTHONBREAKPOINT environment variable picks another debugger, and PYTHONBREAKPOINT=0 turns every breakpoint() off.',
    example: { command: 'PYTHONBREAKPOINT=0 python3 sim.py', says: 'Runs the script with every breakpoint() call doing nothing.' },
    seeAlso: ['breakpoint', 'pdb.set_trace'],
  },
  {
    name: 'sys.builtin_module_names',
    lang: 'python',
    kind: 'constant',
    official: 'A tuple of strings containing the names of all modules that are compiled into this Python interpreter.',
    source: REF,
    when: 'You want to know which modules are built into the Python program itself, so they need no file on disk. Which ones are there depends on how your Python was built.',
    example: { command: 'print("math" in sys.builtin_module_names)', says: 'Prints True on many Linux Pythons; on others math is a separate file.' },
    seeAlso: ['sys.modules'],
  },
  {
    name: 'sys.getrecursionlimit',
    lang: 'python',
    kind: 'function',
    official: 'Return the current value of the recursion limit.',
    source: DOC,
    when: 'You want to know how deep a chain of function calls can go before RecursionError. It is 1000 by default.',
    example: { command: 'sys.getrecursionlimit()', says: 'Gives 1000 unless something changed it.' },
    seeAlso: ['sys.setrecursionlimit', 'RecursionError'],
  },
  {
    name: 'sys.setrecursionlimit',
    lang: 'python',
    kind: 'function',
    official: 'Set the maximum depth of the Python interpreter stack to n.',
    source: DOC,
    when: 'A correct recursive function really needs to go deeper than 1,000 calls. Set it too high and Python itself can crash with no traceback; rewriting the recursion as a loop is usually the better answer.',
    example: { command: 'sys.setrecursionlimit(5000)', says: 'Lets calls go 5,000 deep before RecursionError.' },
    seeAlso: ['sys.getrecursionlimit', 'RecursionError'],
  },
  {
    name: 'sys.getswitchinterval',
    lang: 'python',
    kind: 'function',
    official: 'Return the current thread switch interval; see sys.setswitchinterval().',
    source: DOC,
    when: 'You want to know how often CPython asks the running thread to let another thread have a turn. Only one thread runs Python code at a time, and this is the time slice.',
    example: { command: 'sys.getswitchinterval()', says: 'Gives 0.005: a switch is requested every 5 milliseconds.' },
  },
  {
    name: 'sys.intern',
    lang: 'python',
    kind: 'function',
    official: 'This enters the string in the (global) table of interned strings whose purpose is to speed up dictionary lookups.',
    source: DOC,
    when: 'You have many copies of the same few strings, such as channel names read from a file, and want them to be one object each. It explains why "is" sometimes agrees with == for strings: never use is to compare text.',
    example: {
      command: 'a = sys.intern("".join(["ma", "in"]))\na is sys.intern("main")',
      says: 'Gives True: both names now point at the single interned "main".',
    },
  },
  {
    name: 'sys.meta_path',
    lang: 'python',
    kind: 'constant',
    official: 'A list of meta path finder objects that have their find_spec() methods called to see if one of the objects can find the module to be imported.',
    source: REF,
    when: 'You want to understand how import finds modules: for each import, Python asks these finders in turn, and the first that knows the name wins. Editable installs work by adding a finder here.',
    example: { command: 'for finder in sys.meta_path:\n    print(finder)', says: 'Lists the finders, such as BuiltinImporter, FrozenImporter and PathFinder.' },
    seeAlso: ['sys.modules', 'sys.path'],
  },
  {
    name: 'sys.modules',
    lang: 'python',
    kind: 'constant',
    official: 'This is a dictionary that maps module names to modules which have already been loaded.',
    source: REF,
    when: 'Every import looks here first, which is why a module runs only once and a second import after you edit the file changes nothing. Restart Python (or use importlib.reload) to pick up changes.',
    example: { command: 'import gnc\nprint("gnc" in sys.modules)', says: 'Prints True: the module is cached, and the next import gnc returns the same object.' },
    seeAlso: ['importlib.reload', 'import'],
  },
  {
    name: 'threading.Lock',
    lang: 'python',
    kind: 'class',
    official: 'The class implementing primitive lock objects.',
    source: REF,
    when: 'Two or more threads change the same variable. Hold the lock around the change so only one thread does it at a time. Use it with with, so it is released even if the code raises; a lock never released makes every other thread wait forever.',
    example: {
      command: 'lock = threading.Lock()\nwith lock:\n    counts["packets"] += 1',
      says: 'Only one thread at a time can run the increment, so no update is lost.',
    },
  },
  {
    name: 'time.monotonic',
    lang: 'python',
    kind: 'function',
    official: 'Monotonic clock, cannot go backward.',
    source: DOC,
    when: 'You are measuring a time interval: a loop period, a timeout, how stale a reading is. Its value alone means nothing; only the difference between two readings does.',
    example: {
      command: 't0 = time.monotonic()\nstep()\nelapsed = time.monotonic() - t0',
      says: 'elapsed is the seconds step took, and it can never come out negative.',
    },
    seeAlso: ['time.time', 'time.perf_counter'],
  },
  {
    name: 'time.time',
    lang: 'python',
    kind: 'function',
    official: 'Return the current time in seconds since the Epoch.',
    source: DOC,
    when: 'You want the wall-clock time, such as a timestamp for a log line. Do not use it to measure intervals: a clock sync can step it backward, and a loop period can come out negative.',
    example: { command: 'time.time()', says: 'Gives a float like 1790000000.25: seconds since 1 January 1970, UTC.' },
    seeAlso: ['time.monotonic', 'datetime.datetime.now'],
  },
  {
    name: 'typing.NamedTuple',
    aliases: ['NamedTuple'],
    lang: 'python',
    kind: 'class',
    official: 'Typed version of namedtuple.',
    source: DOC,
    when: 'You want a small record that cannot change, with named fields and type hints, that is also a tuple, so it can be unpacked and indexed. Use a dataclass instead when the fields must change.',
    example: {
      command: 'class Fix(NamedTuple):\n    lat: float\n    lon: float\np = Fix(28.5, -80.6)',
      says: 'p.lat is 28.5, p[1] is -80.6, and lat, lon = p unpacks it.',
    },
    seeAlso: ['dataclasses.dataclass', 'collections.namedtuple'],
  },
  {
    name: 'unittest.mock.patch.dict',
    aliases: ['patch.dict', 'mock.patch.dict'],
    lang: 'python',
    kind: 'function',
    official: 'Patch a dictionary, or dictionary like object, and restore the dictionary to its original state after the test.',
    source: DOC,
    when: 'A test needs a dictionary changed for a short while, most often os.environ. Everything is put back when the with block ends, even if the test fails.',
    flags: [['clear=True', 'empty the dictionary first, so only your values are in it']],
    example: {
      command: 'with patch.dict(os.environ, {"ORBIT_MODE": "sim"}):\n    run_checks()',
      says: 'Inside the block ORBIT_MODE is "sim"; afterwards os.environ is exactly as before.',
    },
    seeAlso: ['unittest.mock'],
  },

  // ---- Matplotlib ----
  {
    name: 'matplotlib.pyplot.axvline',
    aliases: ['plt.axvline', 'ax.axvline'],
    lang: 'python',
    kind: 'function',
    official: 'Add a vertical line spanning the whole or fraction of the Axes.',
    source: MPL,
    when: 'You want to mark a moment on a time plot, such as staging or engine cutoff. plt.axvline draws on the current axes; with several panels call ax.axvline on the one you mean.',
    flags: [
      ['x', 'where the line goes, in data units'],
      ['color=', 'the line color, such as "grey"'],
      ['linestyle= / ls=', '":" dotted, "--" dashed'],
      ['lw=', 'the line width'],
    ],
    example: { command: 'ax.axvline(162.0, color="grey", linestyle=":")    # MECO', says: 'Draws a dotted gray line straight up the panel at t = 162 s.' },
    seeAlso: ['matplotlib.pyplot.axhline'],
  },
  {
    name: 'matplotlib.pyplot.close',
    aliases: ['plt.close'],
    lang: 'python',
    kind: 'function',
    official: 'Close a figure window, and unregister it from pyplot.',
    source: MPL,
    when: 'You are done with a figure, especially inside a loop that makes one per case. pyplot keeps every figure until you close it, so memory grows each pass, and it warns once more than 20 are open.',
    example: { command: 'fig.savefig(f"case_{i}.png")\nplt.close(fig)', says: 'Saves the figure, then frees it, so a loop over 500 cases does not fill memory.' },
    seeAlso: ['matplotlib.pyplot.savefig', 'matplotlib.pyplot.figure'],
  },
  {
    name: 'matplotlib.pyplot.gcf',
    aliases: ['plt.gcf'],
    lang: 'python',
    kind: 'function',
    official: 'Get the current figure.',
    source: MPL,
    when: 'You want the figure pyplot will draw on next. If there is none yet, it makes one. Code that keeps fig from plt.subplots rarely needs it.',
    example: { command: 'fig = plt.gcf()', says: 'Gives the current figure, so you can call fig methods such as savefig on it.' },
    seeAlso: ['matplotlib.pyplot.gca', 'matplotlib.pyplot.subplots'],
  },
  {
    name: 'matplotlib.pyplot.imsave',
    aliases: ['plt.imsave'],
    lang: 'python',
    kind: 'function',
    official: 'Colormap and save an array as an image file.',
    source: MPL,
    when: 'You have an array of pixels and want it straight in an image file, with no axes or labels. A 2-D array is colored with a colormap, viridis unless you say otherwise.',
    flags: [['cmap=', 'the colormap for a 2-D array; "gray" keeps it gray']],
    example: { command: 'plt.imsave("grey.png", grey, cmap="gray")', says: 'Writes the array as a PNG in shades of gray, one pixel per element.' },
    seeAlso: ['matplotlib.pyplot.savefig'],
  },
  {
    name: 'matplotlib.pyplot.legend',
    aliases: ['plt.legend', 'ax.legend'],
    lang: 'python',
    kind: 'function',
    official: 'Place a legend on the Axes.',
    source: MPL,
    when: 'Your plot has several lines and the reader needs to know which is which. Give each line a label= when you plot it; lines without one are left out. With no loc=, Matplotlib searches for the emptiest corner, which is slow for big data.',
    flags: [
      ['loc=', 'where it goes, such as "upper right"'],
      ['bbox_to_anchor=', 'a point to pin it to; (1.02, 1.0) puts it just outside the top right'],
    ],
    example: { command: 'ax.plot(t, alt, label="altitude")\nax.legend(loc="upper right")', says: 'Adds a box in the top right corner naming the altitude line.' },
    seeAlso: ['matplotlib.pyplot.plot'],
  },
  {
    name: 'matplotlib.pyplot.plot',
    aliases: ['plt.plot', 'ax.plot'],
    lang: 'python',
    kind: 'function',
    official: 'Plot y versus x as lines and/or markers.',
    source: MPL,
    when: 'You want a line through your data, the most common plot of all. plt.plot draws on the current axes, which may not be the panel you mean; with fig, ax = plt.subplots() call ax.plot instead. x and y must be the same length.',
    flags: [
      ['x, y', 'the data; give only y and x is 0, 1, 2, ...'],
      ['"o"', 'a format string: dots instead of a line'],
      ['color=', 'the color, such as "C0" (first color of the cycle)'],
      ['label=', 'the name the legend shows'],
    ],
    example: { command: 'ax.plot(t, rate, color="C0", label="pitch rate")', says: 'Draws the pitch rate against time on the panel ax.' },
    seeAlso: ['matplotlib.pyplot.subplots', 'matplotlib.pyplot.legend'],
  },
  {
    name: 'matplotlib.pyplot.rcParams.update',
    aliases: ['plt.rcParams.update'],
    lang: 'python',
    kind: 'method',
    official: 'Update D from mapping/iterable E and F.',
    source: 'Python standard library docstring (MutableMapping.update, which rcParams inherits)',
    when: 'You want to change several plot defaults at once, such as font size and grid. Only figures made afterwards get the new look.',
    example: {
      command: 'plt.rcParams.update({"font.size": 12, "axes.grid": True})',
      says: 'Every figure made after this line uses 12-point text and shows a grid.',
    },
    seeAlso: ['matplotlib.pyplot.rcParams', 'matplotlib.pyplot.style.use'],
  },
  {
    name: 'matplotlib.pyplot.savefig',
    aliases: ['plt.savefig', 'fig.savefig'],
    lang: 'python',
    kind: 'function',
    official: 'Save the current figure as an image or vector graphic to a file.',
    source: MPL,
    when: 'You want the figure in a file for a report or slide. The file ending picks the format (.png, .pdf, .svg). Save before plt.show(), because after the window closes the figure may be gone. fig.savefig saves that exact figure; plt.savefig saves the current one.',
    flags: [
      ['dpi=', 'dots per inch for images like PNG'],
      ['format=', 'the format, when the file name does not say it'],
    ],
    example: { command: 'fig.savefig("maxq.png", dpi=100)', says: 'Writes the figure to maxq.png at 100 dots per inch.' },
    seeAlso: ['matplotlib.pyplot.close', 'matplotlib.pyplot.show'],
  },
  {
    name: 'matplotlib.pyplot.style.use',
    aliases: ['plt.style.use'],
    lang: 'python',
    kind: 'function',
    official: 'Use Matplotlib style settings from a style specification.',
    source: MPL,
    when: 'You want a whole ready-made look at once: colors, fonts, grid. It changes the defaults for every figure made after it; "default" goes back to normal.',
    example: { command: 'plt.style.use("tableau-colorblind10")', says: 'Later figures use a color set chosen to be readable by color-blind viewers.' },
    seeAlso: ['matplotlib.pyplot.rcParams.update'],
  },
  {
    name: 'matplotlib.pyplot.subplot_mosaic',
    aliases: ['plt.subplot_mosaic'],
    lang: 'python',
    kind: 'function',
    official: 'Build a layout of Axes based on ASCII art or nested lists.',
    source: MPL,
    when: 'You want panels of different sizes laid out like a sketch. Write the grid as rows of names; the same name in several cells makes one big panel. You get back the figure and a dictionary of panels by name.',
    example: {
      command: 'fig, axd = plt.subplot_mosaic([["alt", "alt"],\n                              ["vel", "acc"]])',
      says: 'axd["alt"] is one wide panel across the top; axd["vel"] and axd["acc"] sit side by side below it.',
    },
    seeAlso: ['matplotlib.pyplot.subplots'],
  },
  {
    name: 'matplotlib.pyplot.title',
    aliases: ['plt.title'],
    lang: 'python',
    kind: 'function',
    official: 'Set a title for the Axes.',
    source: MPL,
    when: 'You want a title over a plot. It goes on the current axes, usually the last panel made, so with several panels use ax.set_title on the one you mean.',
    example: { command: 'plt.title("Max-q pass")', says: 'Puts "Max-q pass" above the current panel.' },
    seeAlso: ['matplotlib.pyplot.xlabel', 'matplotlib.pyplot.gca'],
  },
  {
    name: 'matplotlib.pyplot.xlabel',
    aliases: ['plt.xlabel'],
    lang: 'python',
    kind: 'function',
    official: 'Set the label for the x-axis.',
    source: MPL,
    when: 'You want to name the horizontal axis, with its unit. It labels the current axes; on a named panel the same thing is ax.set_xlabel.',
    example: { command: 'plt.xlabel("Time (s)")', says: 'Writes Time (s) under the horizontal axis of the current panel.' },
    seeAlso: ['matplotlib.pyplot.ylabel'],
  },
  {
    name: 'matplotlib.pyplot.ylabel',
    aliases: ['plt.ylabel'],
    lang: 'python',
    kind: 'function',
    official: 'Set the label for the y-axis.',
    source: MPL,
    when: 'You want to name the vertical axis, with its unit. After plt.subplots made several panels, it lands on the last one made, not the one you drew on last; use ax.set_ylabel.',
    example: { command: 'plt.ylabel("Altitude (m)")', says: 'Writes Altitude (m) beside the vertical axis of the current panel.' },
    seeAlso: ['matplotlib.pyplot.xlabel'],
  },
  {
    name: 'matplotlib.pyplot.xlim',
    aliases: ['plt.xlim'],
    lang: 'python',
    kind: 'function',
    official: 'Get or set the x limits of the current Axes.',
    source: MPL,
    when: 'You want to zoom the horizontal axis to a range. It works on the current axes; on a named panel use ax.set_xlim.',
    example: { command: 'plt.xlim(0, 80)', says: 'Shows only t = 0 to 80 s on the current panel.' },
    seeAlso: ['matplotlib.pyplot.xlabel'],
  },

  // ---- Numba ----
  {
    name: 'numba.objmode',
    aliases: ['objmode'],
    lang: 'python',
    kind: 'function',
    official: 'Creates a contextmanager to be used inside jitted functions to enter object-mode for using interpreter features.',
    source: 'Numba docstring',
    when: 'Inside an @njit function you need one thing Numba cannot compile, such as reading the clock or printing with formatting. The block runs as slow ordinary Python, and you must give the type of every variable that leaves it.',
    flags: [['name="type"', 'the type of each variable the block hands back, such as t="float64"']],
    example: {
      command: 'with numba.objmode(t="float64"):\n    t = time.perf_counter()',
      says: 'Inside a compiled function, runs that one line as ordinary Python and hands t back as a float64.',
    },
    seeAlso: ['numba.njit'],
  },
  {
    name: 'numba.typed.Dict',
    aliases: ['typed.Dict'],
    lang: 'python',
    kind: 'class',
    official: 'A typed-dictionary usable in Numba compiled functions.',
    source: 'Numba docstring',
    when: 'An @njit function needs a dictionary. Every key must be one type and every value one type, fixed when you make it.',
    flags: [['Dict.empty(key_type=, value_type=)', 'make an empty one with those types']],
    example: {
      command: 'd = Dict.empty(key_type=types.int64, value_type=types.float64)',
      says: 'An empty dictionary from integers to floats that compiled functions can read and fill.',
    },
    seeAlso: ['numba.typed.List'],
  },

  // ---- NumPy ----
  {
    name: 'numpy.True_',
    aliases: ['np.True_'],
    lang: 'python',
    kind: 'constant',
    official: 'Boolean type (True or False), stored as a byte.',
    source: 'NumPy docstring (numpy.bool)',
    when: 'NumPy\'s own True, which comparisons and reductions like .any() give back; NumPy 2 prints it as np.True_. It works in an if like True, but it is a different object, so x is True is False.',
    example: { command: '(dist > 15.0).any()', says: 'Gives np.True_ if any sample is beyond 15. Test it with if, never with is True.' },
    seeAlso: ['numpy.False_'],
  },
  {
    name: 'numpy.False_',
    aliases: ['np.False_'],
    lang: 'python',
    kind: 'constant',
    official: 'Boolean type (True or False), stored as a byte.',
    source: 'NumPy docstring (numpy.bool)',
    when: 'NumPy\'s own False, what .all() or a comparison gives when the answer is no; NumPy 2 prints it as np.False_. Use it in an if like False, but x is False will not work on it.',
    example: { command: '(dist > 15.0).all()', says: 'Gives np.False_ unless every sample is beyond 15.' },
    seeAlso: ['numpy.True_'],
  },
  {
    name: 'numpy.add.at',
    aliases: ['np.add.at'],
    lang: 'python',
    kind: 'method',
    official: 'Performs unbuffered in place operation on operand \'a\' for elements specified by \'indices\'.',
    source: NP,
    when: 'You want to add values into an array at positions that may repeat, and every repeat must count. a[idx] += 1 counts each position only once, however many times it appears.',
    example: {
      command: 'counts = np.zeros(4)\nnp.add.at(counts, [1, 1, 1], 1.0)',
      says: 'counts[1] becomes 3.0. counts[[1, 1, 1]] += 1.0 would only make it 1.0.',
    },
    seeAlso: ['numpy.bincount'],
  },
  {
    name: 'numpy.add.reduce',
    aliases: ['np.add.reduce'],
    lang: 'python',
    kind: 'method',
    official: 'Reduces array\'s dimension by one, by applying ufunc along one axis.',
    source: NP,
    when: 'You want to see the machine under sum: it adds along one axis and removes it. All of NumPy\'s reductions work this way, which is why they share axis= and keepdims=.',
    flags: [['axis=', 'the axis to add along and remove']],
    example: { command: 'np.add.reduce(np.array([[1, 2], [3, 4]]), axis=0)', says: 'Gives array([4, 6]), the same as .sum(axis=0).' },
    seeAlso: ['numpy.sum', 'numpy.maximum.reduce'],
  },
  {
    name: 'numpy.maximum.reduce',
    aliases: ['np.maximum.reduce'],
    lang: 'python',
    kind: 'method',
    official: 'Reduces array\'s dimension by one, by applying ufunc along one axis.',
    source: NP,
    when: 'The mechanism under max: it keeps the larger value pairwise along one axis. np.max does the same with a friendlier name. A nan anywhere makes the answer nan.',
    flags: [['axis=', 'the axis to reduce along']],
    example: { command: 'np.maximum.reduce([3.1, 7.4, 5.0])', says: 'Gives 7.4, the same as np.max.' },
    seeAlso: ['numpy.add.reduce', 'numpy.max'],
  },
  {
    name: 'numpy.append',
    aliases: ['np.append'],
    lang: 'python',
    kind: 'function',
    official: 'Append values to the end of an array.',
    source: NP,
    when: 'You need an array one item longer, once. It builds a brand-new array and copies everything every time, so in a loop it gets slower and slower. Collect values in a list and call np.array once at the end.',
    example: { command: 'a = np.append(a, 7.5)', says: 'a is a new array with 7.5 on the end; the old items were copied across.' },
    seeAlso: ['numpy.concatenate', 'list.append'],
  },
  {
    name: 'numpy.ascontiguousarray',
    aliases: ['np.ascontiguousarray'],
    lang: 'python',
    kind: 'function',
    official: 'Return a contiguous array (ndim >= 1) in memory (C order).',
    source: NP,
    when: 'You are handing an array to compiled code (Numba, C, C++) that expects one unbroken row-by-row block. It copies only if needed, so a slice or a transposed view comes back fixed.',
    flags: [['dtype=', 'also convert to this type, such as np.float64']],
    example: { command: 'x = np.ascontiguousarray(x, dtype=np.float64)', says: 'x is now a row-major float64 block; if it already was, no copy is made.' },
    seeAlso: ['numpy.asfortranarray'],
  },
  {
    name: 'numpy.asfortranarray',
    aliases: ['np.asfortranarray'],
    lang: 'python',
    kind: 'function',
    official: 'Return an array (ndim >= 1) laid out in Fortran order in memory.',
    source: NP,
    when: 'Code you call wants column-by-column memory, such as Fortran routines or Eigen\'s default matrices. The values stay the same; only the order in memory changes.',
    example: { command: 'F = np.asfortranarray(C)', says: 'Same numbers as C, stored one column after another (F.flags["F_CONTIGUOUS"] is True).' },
    seeAlso: ['numpy.ascontiguousarray'],
  },
  {
    name: 'numpy.bincount',
    aliases: ['np.bincount'],
    lang: 'python',
    kind: 'function',
    official: 'Count number of occurrences of each value in array of non-negative ints.',
    source: NP,
    when: 'You have small whole numbers, such as bin numbers, and want a count for each. The result has one slot per value from 0 to the largest; a negative number raises ValueError.',
    example: { command: 'np.bincount([0, 2, 2, 3])', says: 'Gives array([1, 0, 2, 1]): one 0, no 1s, two 2s, one 3.' },
    seeAlso: ['numpy.add.at'],
  },
  {
    name: 'numpy.broadcast_shapes',
    aliases: ['np.broadcast_shapes'],
    lang: 'python',
    kind: 'function',
    official: 'Broadcast the input shapes into a single shape.',
    source: NP,
    when: 'You want to check what shape two arrays would combine to, using only their shapes, before building anything. Shapes that do not fit raise ValueError.',
    example: { command: 'np.broadcast_shapes((5, 1, 3), (4, 3))', says: 'Gives (5, 4, 3).' },
    seeAlso: ['numpy.broadcast_to'],
  },
  {
    name: 'numpy.broadcast_to',
    aliases: ['np.broadcast_to'],
    lang: 'python',
    kind: 'function',
    official: 'Broadcast an array to a new shape.',
    source: NP,
    when: 'You want to see, or pass on, an array stretched the way broadcasting would stretch it. It uses no extra memory, and the result is read-only, because many positions share one value.',
    example: {
      command: 'b4 = np.broadcast_to(np.array([0.05, -0.10, 0.10]), (4, 3))',
      says: 'A (4, 3) view showing the row four times, with no copies made. Writing into it raises ValueError.',
    },
    seeAlso: ['numpy.broadcast_shapes'],
  },
  {
    name: 'numpy.cumprod',
    aliases: ['np.cumprod'],
    lang: 'python',
    kind: 'function',
    official: 'Return the cumulative product of elements along a given axis.',
    source: NP,
    when: 'You want a running product, such as what survives after several stages that each keep a fraction. The result has the same shape as the input.',
    flags: [['axis=', 'the axis to run along']],
    example: { command: 'np.cumprod([1.0, 0.9, 0.9, 0.9])', says: 'Gives array([1., 0.9, 0.81, 0.729]).' },
    seeAlso: ['numpy.cumsum', 'numpy.prod'],
  },
  {
    name: 'numpy.dtype',
    aliases: ['np.dtype'],
    lang: 'python',
    kind: 'class',
    official: 'Create a data type object.',
    source: NP,
    when: 'You want to describe or check what kind of number an array holds; every array\'s .dtype is one of these. Compare it with ==, as in a.dtype == np.float64.',
    example: { command: 'np.dtype("float32").itemsize', says: 'Gives 4: each float32 takes 4 bytes.' },
      },
  {
    name: 'numpy.genfromtxt',
    aliases: ['np.genfromtxt'],
    lang: 'python',
    kind: 'function',
    official: 'Load data from a text file, with missing values handled as specified.',
    source: NP,
    when: 'You want a numeric CSV in an array and some cells may be empty. Empty cells become nan instead of crashing, which is what np.loadtxt does.',
    flags: [
      ['delimiter=', 'what separates the columns, such as ","'],
      ['names=True', 'read column names from the first line'],
    ],
    example: {
      command: 'data = np.genfromtxt("flight.csv", delimiter=",", names=True)',
      says: 'data["alt"] is the alt column as floats, with nan where a cell was empty.',
    },
    seeAlso: ['numpy.loadtxt', 'pandas.read_csv'],
  },
  {
    name: 'numpy.isclose',
    aliases: ['np.isclose'],
    lang: 'python',
    kind: 'function',
    official: 'Returns a boolean array where two arrays are element-wise equal within a tolerance.',
    source: NP,
    when: 'You want to compare computed floats element by element, since == almost never works. Choose the tolerances yourself: the default atol of 1e-8 calls 1e-9 and 0 "close", and rtol is measured against the second argument only.',
    flags: [
      ['rtol=', 'allowed difference as a fraction of b'],
      ['atol=', 'allowed difference in absolute terms, which matters near zero'],
    ],
    example: {
      command: 'np.isclose(10.0, 11.05, rtol=0.1, atol=0.0), np.isclose(11.05, 10.0, rtol=0.1, atol=0.0)',
      says: 'Gives (True, False): swapping the two numbers changes the answer.',
    },
    seeAlso: ['numpy.allclose', 'math.isclose'],
  },
  {
    name: 'numpy.ix_',
    aliases: ['np.ix_'],
    lang: 'python',
    kind: 'function',
    official: 'Construct an open mesh from multiple sequences.',
    source: NP,
    when: 'You want the block of some rows and some columns. Two plain lists pair up position by position instead; np.ix_ makes them cross, every row with every column. The result is a copy.',
    example: {
      command: 'm[np.ix_([0, 2], [1, 2])]',
      says: 'Gives the 2 by 2 block from rows 0 and 2, columns 1 and 2. m[[0, 2], [1, 2]] would give only m[0, 1] and m[2, 2].',
    },
  },
  {
    name: 'numpy.longdouble',
    aliases: ['np.longdouble'],
    lang: 'python',
    kind: 'type',
    official: 'Extended-precision floating-point number type, compatible with C long double but not necessarily with IEEE 754 quadruple-precision.',
    source: NP,
    when: 'You are tempted to buy more precision. It is 80-bit on x86 computers but plain float64 on many others (Apple silicon, Windows), so results change from machine to machine. Rearranging the math is usually the real fix.',
    example: { command: 'np.finfo(np.longdouble).eps', says: 'About 1.08e-19 on an x86 Linux computer, against 2.2e-16 for float64.' },
    seeAlso: ['numpy.finfo', 'numpy.float64'],
  },
  {
    name: 'numpy.matmul',
    aliases: ['np.matmul'],
    lang: 'python',
    kind: 'function',
    official: 'Matrix product of two arrays.',
    source: NP,
    when: 'You want matrix multiplication; a @ b is the same function. On stacks of matrices it multiplies each pair along the leading axis. Plain * multiplies element by element, a silent wrong answer if you meant @.',
    example: { command: 'np.matmul(R, v)', says: 'Rotates the vector v by the 3 by 3 matrix R, exactly like R @ v.' },
    seeAlso: ['numpy.dot', 'numpy.multiply'],
  },
  {
    name: 'numpy.may_share_memory',
    aliases: ['np.may_share_memory'],
    lang: 'python',
    kind: 'function',
    official: 'Determine if two arrays might share memory',
    source: NP,
    when: 'You want a quick check that two arrays might be views of the same data. True only means their byte ranges overlap; np.shares_memory gives the exact answer.',
    example: {
      command: 'a = np.arange(10)\nnp.may_share_memory(a[::2], a[1::2])',
      says: 'Gives True, although the even and odd slices share no element.',
    },
    seeAlso: ['numpy.shares_memory'],
  },
  {
    name: 'numpy.min',
    aliases: ['np.min'],
    lang: 'python',
    kind: 'function',
    official: 'Return the minimum of an array or minimum along an axis.',
    source: NP,
    when: 'You want the smallest value, of the whole array or along one axis. One nan makes the answer nan; use np.nanmin on data with gaps.',
    flags: [['axis=', 'the axis to reduce; leave out for the whole array']],
    example: { command: 'np.min(T, axis=0)', says: 'For T shaped (samples, sensors), gives the lowest reading of each sensor.' },
    seeAlso: ['numpy.nanmin', 'numpy.argmin', 'min'],
  },
  {
    name: 'numpy.mod',
    aliases: ['np.mod'],
    lang: 'python',
    kind: 'function',
    official: 'Returns the element-wise remainder of division.',
    source: NP,
    when: 'You want the remainder for a whole array, such as wrapping angles into 0 to 360. The answer has the sign of the divisor, like Python\'s %, unlike C\'s fmod.',
    example: { command: 'np.mod(np.array([370.0, -30.0]), 360.0)', says: 'Gives array([10., 330.]).' },
  },
  {
    name: 'numpy.multiply',
    aliases: ['np.multiply'],
    lang: 'python',
    kind: 'function',
    official: 'Multiply arguments element-wise.',
    source: NP,
    when: 'You want element-by-element multiplication, the same as *. Its out= argument writes the answer into an existing array instead of making a new one. It is not matrix multiplication.',
    flags: [['out=', 'the array to write the result into']],
    example: { command: 'np.multiply(q, rho, out=q)', says: 'Multiplies q by rho element by element and stores the result back in q, with no new array.' },
    seeAlso: ['numpy.matmul'],
  },
  {
    name: 'numpy.nanargmax',
    aliases: ['np.nanargmax'],
    lang: 'python',
    kind: 'function',
    official: 'Return the indices of the maximum values in the specified axis ignoring NaNs.',
    source: NP,
    when: 'You want where the biggest value is, in data with gaps. Plain argmax returns the position of the first nan, with no warning. A row that is all nan raises ValueError.',
    flags: [['axis=', 'the axis to search along']],
    example: { command: 'np.nanargmax(np.array([0.4, np.nan, 1.2]))', says: 'Gives 2, skipping the gap.' },
    seeAlso: ['numpy.nanargmin', 'numpy.nanmax'],
  },
  {
    name: 'numpy.nanargmin',
    aliases: ['np.nanargmin'],
    lang: 'python',
    kind: 'function',
    official: 'Return the indices of the minimum values in the specified axis ignoring NaNs.',
    source: NP,
    when: 'You want where the smallest value is, in data with gaps. A row that is all nan raises ValueError.',
    flags: [['axis=', 'the axis to search along']],
    example: { command: 'np.nanargmin(np.array([0.4, np.nan, 1.2]))', says: 'Gives 0.' },
    seeAlso: ['numpy.nanargmax', 'numpy.nanmin'],
  },
  {
    name: 'numpy.nanmax',
    aliases: ['np.nanmax'],
    lang: 'python',
    kind: 'function',
    official: 'Return the maximum of an array or maximum along an axis, ignoring any NaNs.',
    source: NP,
    when: 'You want the largest value of data with gaps. An all-nan slice gives nan and a RuntimeWarning.',
    flags: [
      ['axis=', 'the axis to reduce'],
      ['keepdims=True', 'keep the reduced axis with length 1'],
    ],
    example: { command: 'np.nanmax(np.array([0.4, np.nan, 1.2]))', says: 'Gives 1.2. np.max would give nan.' },
    seeAlso: ['numpy.nanmin', 'numpy.nanargmax'],
  },
  {
    name: 'numpy.nanmin',
    aliases: ['np.nanmin'],
    lang: 'python',
    kind: 'function',
    official: 'Return minimum of an array or minimum along an axis, ignoring any NaNs.',
    source: NP,
    when: 'You want the smallest value of data with gaps. An all-nan slice gives nan and a RuntimeWarning.',
    flags: [
      ['axis=', 'the axis to reduce'],
      ['keepdims=True', 'keep the reduced axis with length 1'],
    ],
    example: { command: 'np.nanmin(np.array([0.4, np.nan, 1.2]))', says: 'Gives 0.4.' },
    seeAlso: ['numpy.nanmax', 'numpy.min'],
  },
  {
    name: 'numpy.nansum',
    aliases: ['np.nansum'],
    lang: 'python',
    kind: 'function',
    official: 'Return the sum of array elements over a given axis treating Not a Numbers (NaNs) as zero.',
    source: NP,
    when: 'You want a total of data with gaps. It counts each nan as 0, so a slice that is all nan sums to 0, not nan; make sure that is what you mean.',
    flags: [['axis=', 'the axis to add along']],
    example: { command: 'x = np.array([0.4, np.nan, 1.2])\nprint(x.sum(), np.nansum(x))', says: 'Prints nan 1.6.' },
    seeAlso: ['numpy.sum', 'numpy.nanmean'],
  },
  {
    name: 'numpy.nanvar',
    aliases: ['np.nanvar'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the variance along the specified axis, while ignoring NaNs.',
    source: NP,
    when: 'You want the spread of data with gaps. Like np.var it divides by N unless you pass ddof=1, which you want for a sample estimate.',
    flags: [
      ['axis=', 'the axis to compute along'],
      ['ddof=1', 'divide by N - 1 (the sample variance)'],
    ],
    example: { command: 'np.nanvar(T, axis=0, ddof=1)', says: 'Gives the sample variance of each sensor column, skipping the gaps.' },
    seeAlso: ['numpy.nanstd', 'numpy.var'],
  },
  {
    name: 'numpy.newaxis',
    aliases: ['np.newaxis'],
    lang: 'python',
    kind: 'constant',
    official: 'A convenient alias for None, useful for indexing arrays.',
    source: 'NumPy documentation (Constants)',
    when: 'You want to add an axis of length 1 so shapes broadcast the way you mean. It is just None, and most people write None because it is shorter.',
    example: { command: 'x[:, np.newaxis]', says: 'Turns shape (N,) into (N, 1): one value per row.' },
    seeAlso: ['None'],
  },
  {
    name: 'numpy.random.rand',
    aliases: ['np.random.rand'],
    lang: 'python',
    kind: 'function',
    official: 'Random values in a given shape.',
    source: NP,
    when: 'Old code wanting uniform numbers from 0 up to 1. It draws from one hidden global generator that any library can also draw from, so runs are hard to repeat. New code makes rng = np.random.default_rng(seed) and calls rng.random.',
    example: { command: 'np.random.rand(3)', says: 'Gives three random floats between 0 and 1, such as array([0.42, 0.91, 0.07]).' },
    seeAlso: ['numpy.random.default_rng', 'numpy.random.random'],
  },
  {
    name: 'numpy.savez',
    aliases: ['np.savez'],
    lang: 'python',
    kind: 'function',
    official: 'Save several arrays into a single file in uncompressed .npz format.',
    source: NP,
    when: 'You want several arrays in one file, each under a name. Pass them as keywords, or they get names like arr_0. np.load gives them back by name.',
    flags: [['name=array', 'store that array under that name']],
    example: {
      command: 'np.savez("pass_17.npz", t=t, gyro=gyro, mode=mode)',
      says: 'Writes one file; np.load("pass_17.npz")["gyro"] gives the gyro array back.',
    },
    seeAlso: ['numpy.savez_compressed', 'numpy.load', 'numpy.save'],
  },
  {
    name: 'numpy.savez_compressed',
    aliases: ['np.savez_compressed'],
    lang: 'python',
    kind: 'function',
    official: 'Save several arrays into a single file in compressed .npz format.',
    source: NP,
    when: 'Like np.savez, but each array is squeezed the way zip files are. It helps a lot for repetitive data like mode flags and little for noisy sensor readings, and saving takes longer.',
    flags: [['name=array', 'store that array under that name']],
    example: { command: 'np.savez_compressed("pass_17.npz", t=t, mode=mode)', says: 'Writes a smaller .npz file that np.load reads the same way.' },
    seeAlso: ['numpy.savez', 'numpy.load'],
  },
  {
    name: 'numpy.seterr',
    aliases: ['np.seterr'],
    lang: 'python',
    kind: 'function',
    official: 'Set how floating-point errors are handled.',
    source: NP,
    when: 'You want NumPy to raise, warn or stay silent on divide by zero, overflow and invalid results. It changes the rule for the whole program and returns the old settings, which you must put back; the with np.errstate(...) block does that for you, even if the code raises.',
    flags: [
      ['over=', 'what to do on overflow: "ignore", "warn" or "raise"'],
      ['divide=', 'the same for divide by zero'],
      ['invalid=', 'the same for results like 0/0'],
    ],
    example: { command: 'old = np.seterr(over="raise")\n...\nnp.seterr(**old)', says: 'Overflow raises FloatingPointError until the last line puts the old rule back.' },
    seeAlso: ['numpy.errstate', 'RuntimeWarning'],
  },
  {
    name: 'numpy.transpose',
    aliases: ['np.transpose'],
    lang: 'python',
    kind: 'function',
    official: 'Returns an array with axes transposed.',
    source: NP,
    when: 'You want to reorder an array\'s axes. With no order it reverses them all, like .T; for a stack of matrices (N, 3, 3), list the order yourself so only the last two swap. It returns a view, not a copy.',
    flags: [['axes', 'the old axes in their new order, such as (0, 2, 1)']],
    example: { command: 'np.transpose(S, (0, 2, 1))', says: 'Transposes each 3 by 3 matrix in the stack S; axis 0 stays first.' },
  },
  {
    name: 'numpy.uint8',
    aliases: ['np.uint8'],
    lang: 'python',
    kind: 'type',
    official: 'Unsigned integer type, compatible with C unsigned char.',
    source: NP,
    when: 'You are handling image pixels or raw sensor bytes, which hold 0 to 255. Go past 255 and it wraps round to 0 with no error, like an odometer; convert to a wider type before doing math.',
    example: {
      command: 'np.array([200, 100], dtype=np.uint8) + np.uint8(100)',
      says: 'Gives array([44, 200], dtype=uint8): 300 wrapped round to 44.',
    },
    seeAlso: ['numpy.dtype'],
  },

  // ---- pandas and PyArrow ----
  {
    name: 'pandas.concat',
    aliases: ['pd.concat'],
    lang: 'python',
    kind: 'function',
    official: 'Concatenate pandas objects along a particular axis.',
    source: 'pandas docstring',
    when: 'You want several tables stacked into one. Collect the pieces in a list and concatenate once at the end: calling it inside a loop copies everything each time.',
    flags: [
      ['ignore_index=True', 'number the rows 0, 1, 2, ... again'],
      ['axis=1', 'put the tables side by side instead of stacking them'],
    ],
    example: { command: 'df = pd.concat([day1, day2, day3], ignore_index=True)', says: 'One table with all three days\' rows, numbered from 0.' },
    seeAlso: ['pandas.merge', 'numpy.concatenate'],
  },
  {
    name: 'pandas.isna',
    aliases: ['pd.isna'],
    lang: 'python',
    kind: 'function',
    official: 'Detect missing values for an array-like object.',
    source: 'pandas docstring',
    when: 'You want to test for a missing value. NaN is not equal to anything, not even itself, so x == np.nan is always False; this is the test that works.',
    example: { command: 'pd.isna(float("nan")), pd.isna(3.2)', says: 'Gives (True, False).' },
    seeAlso: ['numpy.isnan'],
  },
  {
    name: 'pandas.read_hdf',
    aliases: ['pd.read_hdf'],
    lang: 'python',
    kind: 'function',
    official: 'Read from the store, close it if we opened it.',
    source: 'pandas docstring',
    when: 'You want a table back that was saved with df.to_hdf. It needs the PyTables library, and the file layout is one mainly pandas reads well; for files other tools share, write the HDF5 with h5py instead.',
    flags: [['key=', 'the name the table was stored under']],
    example: { command: 'nav = pd.read_hdf("flight.h5", key="nav")', says: 'Loads the table stored under "nav" as a DataFrame.' },
    seeAlso: ['pandas.read_parquet'],
  },
  {
    name: 'pyarrow.parquet.ParquetFile.iter_batches',
    aliases: ['ParquetFile.iter_batches', 'iter_batches'],
    lang: 'python',
    kind: 'method',
    official: 'Read streaming batches from a Parquet file.',
    source: 'PyArrow docstring',
    when: 'A Parquet file is bigger than your memory, even one column of it. You get the rows a batch at a time and keep only running results between batches.',
    flags: [
      ['batch_size=', 'the most rows in each batch'],
      ['columns=', 'read only these columns'],
    ],
    example: {
      command: 'f = pq.ParquetFile("burn.parquet")\nfor batch in f.iter_batches(batch_size=100_000, columns=["chamber_p"]):\n    peak = max(peak, batch.column(0).to_numpy().max())',
      says: 'Walks through the file 100,000 rows at a time, keeping only the highest chamber pressure seen so far.',
    },
    seeAlso: ['pyarrow.parquet'],
  },

  // ---- pytest ----
  {
    name: 'pytest.mark.xfail',
    lang: 'python',
    kind: 'function',
    official: 'mark the test function as an expected failure if any of the conditions evaluate to True.',
    source: 'pytest built-in marker description (pytest --markers)',
    when: 'A test describes a known bug or a missing feature, so it is expected to fail for now. Add strict=True: then the day the bug is fixed and the test passes, pytest reports a failure, telling you to remove the mark.',
    flags: [
      ['reason=', 'why it is expected to fail, shown in the report'],
      ['strict=True', 'an unexpected pass counts as a failure'],
    ],
    example: {
      command: '@pytest.mark.xfail(reason="no J2 term yet", strict=True)\ndef test_node_drift(): ...',
      says: 'While the test fails it shows as x (xfailed). If it starts passing, the run fails.',
    },
    seeAlso: ['pytest.mark.skip', 'pytest.mark.skipif'],
  },
  {
    name: 'pytest.skip',
    lang: 'python',
    kind: 'function',
    official: 'Skip an executing test with the given message.',
    source: 'pytest docstring',
    when: 'A test finds out while running that it cannot go on, for example a needed file or device is missing. When you can decide before the test starts, a skipif marker is clearer.',
    example: {
      command: 'if not Path("ephemeris.bsp").exists():\n    pytest.skip("ephemeris file not downloaded")',
      says: 'The test stops there and shows as s (skipped) with that reason.',
    },
    seeAlso: ['pytest.mark.skip', 'pytest.mark.skipif', 'pytest.importorskip'],
  },

  // ---- SciPy ----
  {
    name: 'scipy.integrate.odeint',
    aliases: ['odeint'],
    lang: 'python',
    kind: 'function',
    official: 'Integrate a system of ordinary differential equations.',
    source: SP,
    when: 'You meet it in older code. It wants f(y, t), state first, the opposite of solve_ivp\'s f(t, y), and returns one row per time, while solve_ivp gives one row per state. New code should use solve_ivp.',
    flags: [
      ['func', 'f(y, t), giving dy/dt'],
      ['y0', 'the starting state'],
      ['t', 'the times you want answers at'],
    ],
    example: { command: 'ys = odeint(lambda y, t: -0.5 * y, 1.0, t)', says: 'ys has one row per time in t: y decaying from 1.0.' },
    seeAlso: ['scipy.integrate.solve_ivp'],
  },
  {
    name: 'scipy.integrate.quad',
    lang: 'python',
    kind: 'function',
    official: 'Compute a definite integral.',
    source: SP,
    when: 'You want the area under a function you can call, between two limits, even out to infinity. It returns two numbers: the answer and an estimate of its error.',
    flags: [
      ['func', 'the function to integrate'],
      ['a, b', 'the limits; np.inf is allowed'],
    ],
    example: {
      command: 'value, err = quad(lambda h: np.exp(-h / 8.5), 0, np.inf)',
      says: 'value is 8.5 and err is tiny: the integral of the density fall-off up to infinity.',
    },
    seeAlso: ['scipy.integrate.solve_ivp'],
  },
  {
    name: 'scipy.io.loadmat',
    aliases: ['loadmat'],
    lang: 'python',
    kind: 'function',
    official: 'Load MATLAB file.',
    source: SP,
    when: 'You have a MATLAB .mat file and want its variables in Python. It reads version 7 and older; a version 7.3 file is HDF5 inside, so open it with h5py. A MATLAB vector comes back 2-D, such as (1, 500).',
    example: { command: 'data = loadmat("run12.mat")\nq = data["q"]', says: 'data is a dictionary from variable names to NumPy arrays.' },
    seeAlso: ['numpy.load'],
  },
  {
    name: 'scipy.linalg.ldl',
    lang: 'python',
    kind: 'function',
    official: 'Computes the LDLt or Bunch-Kaufman factorization of a symmetric/ hermitian matrix.',
    source: SP,
    when: 'You want to split a symmetric matrix into L D L-transpose. Unlike Cholesky, it also works when the matrix is not positive definite. It returns three things: L, D and a row order.',
    example: { command: 'L, D, perm = scipy.linalg.ldl(A)', says: 'L @ D @ L.T rebuilds A; D is diagonal, or has small 2 by 2 blocks.' },
    seeAlso: ['scipy.linalg.cholesky', 'numpy.linalg.cholesky'],
  },
  {
    name: 'scipy.linalg.lstsq',
    lang: 'python',
    kind: 'function',
    official: 'Compute least-squares solution to the equation a @ x = b.',
    source: SP,
    when: 'You have more equations than unknowns, such as fitting a line to many noisy points, and want the x that fits best. It returns four things; the first is the answer.',
    example: { command: 'x, res, rank, sv = scipy.linalg.lstsq(A, b)', says: 'x makes A @ x as close to b as possible.' },
    seeAlso: ['numpy.linalg.lstsq', 'numpy.linalg.solve'],
  },
  {
    name: 'scipy.linalg.null_space',
    aliases: ['null_space'],
    lang: 'python',
    kind: 'function',
    official: 'Construct an orthonormal basis for the null space of A using SVD',
    source: SP,
    when: 'You want every direction x with A @ x = 0. For a measurement matrix, those are the state errors the measurement cannot see. The answer comes as perpendicular unit columns.',
    example: { command: 'N = scipy.linalg.null_space(np.array([[1.0, 0.0, 0.0]]))', says: 'N has shape (3, 2): the y and z directions, which a measurement of x alone cannot see.' },
    seeAlso: ['numpy.linalg.svd'],
  },
  {
    name: 'scipy.linalg.solve_continuous_lyapunov',
    aliases: ['solve_continuous_lyapunov'],
    lang: 'python',
    kind: 'function',
    official: 'Solves the continuous Lyapunov equation AX + XA^H = Q.',
    source: SP,
    when: 'You want the matrix P that proves a linear system is stable, or its steady-state covariance. Watch the form: for A.T P + P A = -Q, pass A.T and -Q.',
    example: { command: 'P = solve_continuous_lyapunov(A.T, -np.eye(2))', says: 'P is positive definite exactly when the system with matrix A is stable.' },
    seeAlso: ['scipy.linalg.solve_continuous_are'],
  },
  {
    name: 'scipy.optimize.differential_evolution',
    aliases: ['differential_evolution'],
    lang: 'python',
    kind: 'function',
    official: 'Finds the global minimum of a multivariate function.',
    source: SP,
    when: 'Your cost has many valleys and minimize keeps getting stuck in the nearest one. It searches the whole box you give it with a population of guesses. It needs many more function calls, and a seed makes runs repeatable.',
    flags: [
      ['bounds=', 'a (low, high) pair for each variable'],
      ['seed=', 'fix the random start so runs repeat'],
    ],
    example: {
      command: 'res = differential_evolution(cost, bounds=[(0, 90), (100, 400)], seed=1)',
      says: 'res.x is the best pair found inside those ranges, res.fun its cost.',
    },
    seeAlso: ['scipy.optimize.minimize'],
  },
  {
    name: 'scipy.optimize.fsolve',
    aliases: ['fsolve'],
    lang: 'python',
    kind: 'function',
    official: 'Find the roots of a function.',
    source: SP,
    when: 'You want where a function (or several at once) equals zero, starting from a guess. It can land on a different root or stop without a warning; when you can bracket a single root, brentq is safer.',
    flags: [['x0=', 'the starting guess']],
    example: {
      command: 'E = fsolve(lambda E: E - 0.3 * np.sin(E) - 1.2, x0=1.2)[0]',
      says: 'Solves Kepler\'s equation: E is about 1.4992.',
    },
    seeAlso: ['scipy.optimize.brentq', 'scipy.optimize.root'],
  },
  {
    name: 'scipy.optimize.linprog',
    aliases: ['linprog'],
    lang: 'python',
    kind: 'function',
    official: 'Linear programming: minimize a linear objective function subject to linear equality and inequality constraints.',
    source: SP,
    when: 'Your cost and all your limits are straight-line sums of the unknowns. It always minimizes, so negate c to maximize, and every limit is written as "less than or equal": multiply a "greater than" by -1.',
    flags: [
      ['c', 'the cost of each unknown'],
      ['A_ub=, b_ub=', 'the limits A_ub @ x <= b_ub'],
      ['bounds=', 'a (low, high) pair for each unknown; None means no limit'],
    ],
    example: {
      command: 'res = linprog(c=[1.0, 1.0], A_ub=[[-1.0, -2.0]], b_ub=[-4.0], bounds=[(0, None), (0, None)])',
      says: 'res.x is [0, 2]: the cheapest x and y with x + 2y at least 4.',
    },
    seeAlso: ['scipy.optimize.minimize'],
  },
  {
    name: 'scipy.signal.decimate',
    lang: 'python',
    kind: 'function',
    official: 'Downsample the signal after applying an anti-aliasing filter.',
    source: SP,
    when: 'You want a fast channel at a slower rate. It low-pass filters first, so fast wiggles do not fold into fake slow ones the way plain x[::q] lets them.',
    flags: [['q', 'keep one sample in q']],
    example: { command: 'slow = decimate(fast, 10)', says: 'Turns a 400 Hz channel into 40 Hz, filtered first.' },
    seeAlso: ['scipy.signal.butter'],
  },
  {
    name: 'scipy.signal.savgol_filter',
    aliases: ['savgol_filter', 'signal.savgol_filter'],
    lang: 'python',
    kind: 'function',
    official: 'Apply a Savitzky-Golay filter to an array.',
    source: SP,
    when: 'You want to smooth noisy samples, or get a rate from positions, without the noise blow-up of a plain difference. It fits a small polynomial to each stretch of samples. With deriv=1, pass delta= or the rate is per sample, not per second.',
    flags: [
      ['window', 'how many samples each fit uses (odd)'],
      ['poly', 'the polynomial degree, smaller than the window'],
      ['deriv=1', 'give the first derivative instead of the smoothed values'],
      ['delta=', 'the time between samples, for the derivative'],
    ],
    example: { command: 'vz = savgol_filter(alt, 21, 3, deriv=1, delta=dt)', says: 'vz is the climb rate in m/s, taken from a smoothed altitude.' },
    seeAlso: ['numpy.gradient'],
  },
]
