import type { CommandRef } from './types'

/**
 * Names the degree courses (the cs.* tracks: data structures, discrete maths, organisation,
 * operating systems, networks, security, parallel computing) and the newer practice teach,
 * which the earlier batches did not have.
 */

const BUILTIN = 'Python built-in docstring'
const DOC = 'Python standard library docstring'
const PYREF = 'Python documentation (docs.python.org)'
const CPPREF = 'cppreference.com'
const LIBSTD = 'libstdc++ documentation'

export const COMMANDS: CommandRef[] = [
  // ---- Python: methods on built-in types ----
  {
    name: 'str.find',
    aliases: ['find', 'bytes.find'],
    lang: 'python',
    kind: 'method',
    official: 'Return the lowest index in S where substring sub is found, such that sub is contained within S[start:end].',
    source: 'Python built-in docstring (str.find)',
    when: 'You want the position of some text inside a string or a bytes buffer, such as the blank line that ends an HTTP header. It gives -1 when the text is not there, so check for -1 before slicing: data[:-1] quietly drops the last byte. bytes.find works the same way on bytes.',
    flags: [
      ['sub', 'the text to look for'],
      ['start', 'where to begin looking, such as the end of the last match'],
    ],
    example: { command: 'end = buf.find(b"\\r\\n\\r\\n")', says: 'The index where the blank line starts, or -1 if the header has not all arrived yet.' },
    seeAlso: ['str.index', 'str.split'],
  },
  {
    name: 'str.isalpha',
    aliases: ['isalpha'],
    lang: 'python',
    kind: 'method',
    official: 'Return True if the string is an alphabetic string, False otherwise.',
    source: 'Python built-in docstring (str.isalpha)',
    when: 'A tokenizer asks whether a character starts a name. It counts letters from every alphabet, such as é, so add isascii() when only A to Z will do. An empty string gives False.',
    example: { command: 'elif ch.isalpha() or ch == "_":', says: 'Starts reading a name when ch is a letter or an underscore.' },
    seeAlso: ['str.isdigit', 'str.isalnum', 'str.isupper'],
  },
  {
    name: 'str.isupper',
    aliases: ['isupper'],
    lang: 'python',
    kind: 'method',
    official: 'Return True if the string is an uppercase string, False otherwise.',
    source: 'Python built-in docstring (str.isupper)',
    when: 'You check that a code or an HTTP method is written in capitals. Characters with no case, such as digits, are ignored, so "A1".isupper() is True, but a string needs at least one letter: "12".isupper() is False.',
    example: { command: 'method.isascii() and method.isalpha() and method.isupper()', says: 'True for "GET", False for "get" or "G3T".' },
    seeAlso: ['str.upper', 'str.isalpha'],
  },
  {
    name: 'int.bit_length',
    aliases: ['bit_length'],
    lang: 'python',
    kind: 'method',
    official: 'Number of bits necessary to represent self in binary.',
    source: 'Python built-in docstring (int.bit_length)',
    when: 'You want the largest power of two that fits in a number, as a sparse table does: L.bit_length() - 1. It is exact for any size of integer, unlike int(math.log2(L)), which can round the wrong way. The sign is ignored and 0 gives 0.',
    example: { command: 'k = (r - l).bit_length() - 1', says: 'For a range of length 10 gives 3, because 2**3 = 8 is the largest power of two in 10.' },
    seeAlso: ['int.bit_count', 'math.log2'],
  },
  {
    name: 'list.reverse',
    aliases: ['reverse'],
    lang: 'python',
    kind: 'method',
    official: 'Reverse *IN PLACE*.',
    source: 'Python built-in docstring (list.reverse)',
    when: 'You built a path backwards, following parent links from the goal, and want it start first. It turns the list itself around and returns None, so write path.reverse() on its own line; reversed(path) or path[::-1] give a reversed copy instead.',
    example: { command: 'back = [5, 4, 3, 1, 0]\nback.reverse()\nprint(back)', says: 'Prints [0, 1, 3, 4, 5].' },
    seeAlso: ['reversed', 'list.sort'],
  },
  {
    name: 're.Pattern.findall',
    aliases: ['findall', 'Pattern.findall'],
    lang: 'python',
    kind: 'method',
    official: 'Return a list of all non-overlapping matches of pattern in string.',
    source: 'Python built-in docstring (re.Pattern.findall)',
    when: 'You compiled a pattern once and want every match of it in some text. As with re.findall, a pattern with one group ( ) gives the group\'s text, and one with several groups gives tuples.',
    example: { command: 'PRICE = re.compile(r"\\$(\\d+\\.\\d\\d)")\nPRICE.findall("tea $3.50, cake $4.25")', says: 'Returns [\'3.50\', \'4.25\'], the text of the group in each match.' },
    seeAlso: ['re.findall', 're.compile'],
  },

  // ---- Python: exceptions and modules ----
  {
    name: 'ConnectionError',
    lang: 'python',
    kind: 'exception',
    official: 'Connection error.',
    source: BUILTIN,
    when: 'Something went wrong with a connection. It is the parent of ConnectionRefusedError (nobody is listening), ConnectionResetError and BrokenPipeError, and a kind of OSError, so one except ConnectionError: catches all of them.',
    example: {
      command: 'try:\n    data = await fetch(name)\nexcept ConnectionError:\n    results[name] = "failed"',
      says: 'Records the failure for this name and carries on, instead of letting one bad fetch stop every task.',
    },
    seeAlso: ['OSError', 'TimeoutError'],
  },
  {
    name: 'fractions',
    lang: 'python',
    kind: 'module',
    official: 'Fraction, infinite-precision, rational numbers.',
    source: DOC,
    when: 'You need exact ratios with no rounding at all, such as probabilities or a check that a float formula is right. Everything useful in it is the Fraction class.',
    example: { command: 'from fractions import Fraction\nprint(Fraction(1, 3) * 3 == 1)', says: 'Prints True: one third times three is exactly one.' },
    seeAlso: ['fractions.Fraction'],
  },
  {
    name: 'urllib.parse',
    lang: 'python',
    kind: 'module',
    official: 'Parse (absolute and relative) URLs.',
    source: DOC,
    when: 'You want the parts of a URL, such as its scheme, host and port, to compare origins. Use urlsplit rather than cutting the text at "/" and ":" yourself: a hand-written split is easy to fool with a URL like http://evil.com@bank.com/.',
    flags: [
      ['urlsplit(url)', 'the URL in parts: .scheme, .hostname, .port, .path, .query'],
      ['.port', 'the port as an int, or None when the URL does not give one'],
    ],
    example: { command: 'from urllib.parse import urlsplit\nu = urlsplit("https://Example.com:8443/a?b=1")\nprint(u.scheme, u.hostname, u.port)', says: 'Prints https example.com 8443; hostname is already lower-cased.' },
  },

  // ---- Python: math ----
  {
    name: 'math.isinf',
    lang: 'python',
    kind: 'function',
    official: 'Return True if x is a positive or negative infinity, and False otherwise.',
    source: DOC,
    when: 'You check a float for infinity, such as the result of an overflow or of 1e308 * 10. It is False for NaN, so use math.isfinite to reject both at once.',
    example: { command: 'print(math.isinf(float("-inf")))', says: 'Prints True.' },
    seeAlso: ['math.isnan', 'math.isfinite', 'math.inf'],
  },
  {
    name: 'math.ldexp',
    lang: 'python',
    kind: 'function',
    official: 'Return x * (2**i).',
    source: DOC,
    when: 'You build a float from a significand and a power of two, the way the hardware stores it. Scaling by a power of two is exact, with no rounding, unless the result overflows or becomes subnormal.',
    flags: [
      ['x', 'the significand'],
      ['i', 'the power of two, which may be negative'],
    ],
    example: { command: 'print(math.ldexp(3, -2))', says: 'Prints 0.75, which is 3 * 2**-2.' },
    seeAlso: ['math.ulp'],
  },
  {
    name: 'math.nextafter',
    lang: 'python',
    kind: 'function',
    official: 'Return the next floating-point value after x towards y.',
    source: DOC,
    when: 'You want the float just above or below a number, one step on the number line, to see the gap between floats there. math.nextafter(x, math.inf) is the next float up. It works on Python floats, which are 64-bit; a float32 needs its own bit pattern arithmetic.',
    flags: [
      ['x', 'where to start'],
      ['y', 'which direction to step in, such as math.inf for up'],
    ],
    example: { command: 'print(math.nextafter(1.0, math.inf) - 1.0)', says: 'Prints 2.220446049250313e-16, the gap between 1.0 and the next float.' },
    seeAlso: ['math.ulp', 'math.inf'],
  },
  {
    name: 'math.perm',
    lang: 'python',
    kind: 'function',
    official: 'Number of ways to choose k items from n items without repetition and with order.',
    source: DOC,
    when: 'You count ordered arrangements, n · (n − 1) · … · (n − k + 1), as an exact integer. It is 0 when k is more than n. Use math.comb when the order does not matter.',
    example: { command: 'print(math.perm(5, 3))', says: 'Prints 60: 5 choices for the first place, 4 for the second, 3 for the third.' },
    seeAlso: ['math.comb', 'math.factorial'],
  },

  // ---- Python: os, the system calls ----
  {
    name: 'os.open',
    lang: 'python',
    kind: 'function',
    official: 'Open a file for low level IO.  Returns a file descriptor (integer).',
    source: DOC,
    when: 'You want the open system call itself, with its flags, and a bare file descriptor back instead of a Python file object. Everyday code uses the built-in open(); the operating systems course uses os.open to show exactly what reaches the kernel.',
    flags: [
      ['path', 'the file to open'],
      ['flags', 'os.O_WRONLY, os.O_CREAT, os.O_TRUNC and others, joined with |'],
      ['mode', 'the permissions for a new file, such as 0o644'],
    ],
    example: { command: 'fd = os.open("config.json", os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o644)', says: 'Opens config.json for writing, creating it or emptying it, and gives back a small number such as 3.' },
    seeAlso: ['os.write', 'os.close', 'os.O_CREAT'],
  },
  {
    name: 'os.O_CREAT',
    aliases: ['os.O_WRONLY', 'os.O_TRUNC', 'os.O_RDONLY', 'os.O_RDWR', 'os.O_APPEND', 'os.O_EXCL'],
    lang: 'python',
    kind: 'constant',
    official: 'The following constants are options for the flags parameter to the open() function. They can be combined using the bitwise OR operator |.',
    source: PYREF,
    when: 'You tell os.open what to do with the file. Pick exactly one of O_RDONLY, O_WRONLY or O_RDWR, then add any of the others with |.',
    flags: [
      ['O_WRONLY', 'open for writing only'],
      ['O_CREAT', 'create the file if it does not exist'],
      ['O_TRUNC', 'empty the file first if it does exist'],
      ['O_APPEND', 'every write goes to the end'],
      ['O_EXCL', 'with O_CREAT: fail if the file already exists'],
    ],
    example: { command: 'os.O_WRONLY | os.O_CREAT | os.O_TRUNC', says: 'The flags of "write a fresh copy of this file", the same as open(path, "w").' },
    seeAlso: ['os.open'],
  },
  {
    name: 'os.write',
    lang: 'python',
    kind: 'function',
    official: 'Write a bytes object to a file descriptor.',
    source: DOC,
    when: 'You write raw bytes to a descriptor from os.open. It returns how many bytes were written, which can be fewer than you gave it, and the bytes may still be only in the kernel\'s memory: os.fsync makes them durable.',
    example: { command: 'os.write(fd, b\'{"mode": "safe"}\')', says: 'Hands the 16 bytes to the kernel and returns 16.' },
    seeAlso: ['os.open', 'os.fsync'],
  },
  {
    name: 'os.fsync',
    lang: 'python',
    kind: 'function',
    official: 'Force write of fd to disk.',
    source: DOC,
    when: 'You need the data to survive a power cut before you go on, as in the safe way to replace a file: write a temporary file, fsync it, then rename it over the old one. It waits for the disk, so it is slow; call it where it matters, not after every line.',
    example: { command: 'os.fsync(fd)', says: 'Returns only when the bytes written to fd (and the file\'s inode) are on the disk.' },
    seeAlso: ['os.write', 'os.close'],
  },
  {
    name: 'os.close',
    lang: 'python',
    kind: 'function',
    official: 'Close a file descriptor.',
    source: DOC,
    when: 'You are done with a descriptor from os.open. The number is freed and may be handed out again by the next open, so never use it after closing.',
    example: { command: 'os.close(fd)', says: 'Closes the file; using fd again raises OSError: Bad file descriptor.' },
    seeAlso: ['os.open'],
  },
  {
    name: 'os.stat',
    lang: 'python',
    kind: 'function',
    official: 'Perform a stat system call on the given path.',
    source: DOC,
    when: 'You want what the file system knows about a file without opening it: its inode number, link count, size and times.',
    flags: [
      ['.st_ino', 'the inode number'],
      ['.st_nlink', 'how many names (hard links) point to it'],
      ['.st_size', 'the size in bytes'],
      ['.st_blocks', 'space really used, in 512-byte units'],
    ],
    example: { command: 'st = os.stat("telemetry.log")\nst.st_nlink', says: 'The number of hard links to telemetry.log, 1 for an ordinary file.' },
    seeAlso: ['os.link', 'os.path.getsize'],
  },
  {
    name: 'os.link',
    lang: 'python',
    kind: 'function',
    official: 'Create a hard link to a file.',
    source: DOC,
    when: 'You want a second name for the same file: both names lead to the same inode, and neither is the "real" one. Both must be on the same file system.',
    flags: [
      ['src', 'the existing name'],
      ['dst', 'the new name'],
    ],
    example: { command: 'os.link("run.log", "run-backup.log")', says: 'Adds a second name; st_nlink is now 2, and deleting either name leaves the other working.' },
    seeAlso: ['os.symlink', 'os.unlink', 'os.stat'],
  },
  {
    name: 'os.symlink',
    lang: 'python',
    kind: 'function',
    official: 'Create a symbolic link pointing to src named dst.',
    source: DOC,
    when: 'You want a small file that holds a path, like a shortcut. It can point anywhere, even to another disk, and it dangles when its target is removed. Note the order: the target comes first.',
    example: { command: 'os.symlink("run.log", "latest.log")', says: 'Makes latest.log, a link holding the text "run.log".' },
    seeAlso: ['os.link', 'os.unlink'],
  },
  {
    name: 'os.unlink',
    lang: 'python',
    kind: 'function',
    official: 'Remove a file (same as remove()).',
    source: DOC,
    when: 'You remove a name from a folder. The file itself is freed only when its last name is gone and no program still has it open, which is why a deleted log can keep using disk space.',
    example: { command: 'os.unlink("run.log")', says: 'Removes the name run.log; a hard link to it still works, a symbolic link to it now dangles.' },
    seeAlso: ['os.link', 'os.symlink'],
  },

  // ---- Python: sockets, threads, secrets ----
  {
    name: 'socket.socket',
    lang: 'python',
    kind: 'class',
    official: 'Create a new socket using the given address family, socket type and protocol number.',
    source: PYREF,
    when: 'You open a socket, the thing a program sends and receives through. The family says what kind of address (AF_INET for IPv4) and the type says UDP or TCP. Use it in a with block, or close it, so the port is freed.',
    flags: [
      ['family', 'socket.AF_INET for IPv4 addresses'],
      ['type', 'socket.SOCK_DGRAM for UDP, socket.SOCK_STREAM for TCP'],
      ['.bind((ip, port))', 'give it a local address'],
      ['.sendto / .recvfrom', 'send and receive one UDP datagram'],
      ['.listen() / .accept()', 'wait for TCP connections'],
    ],
    example: { command: 'sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)\nsock.bind(("0.0.0.0", 9000))', says: 'Opens a UDP socket and has it receive datagrams sent to port 9000 on any local address.' },
    seeAlso: ['socket.AF_INET', 'socket.SOCK_STREAM', 'socket.create_connection'],
  },
  {
    name: 'socket.AF_INET',
    aliases: ['socket.AF_INET6', 'socket.AF_UNIX'],
    lang: 'python',
    kind: 'constant',
    official: 'These constants represent the address (and protocol) families, used for the first argument to socket().',
    source: PYREF,
    when: 'The first argument to socket.socket. AF_INET means IPv4 addresses, written as ("127.0.0.1", 8080); AF_INET6 is IPv6.',
    example: { command: 'socket.socket(socket.AF_INET, socket.SOCK_STREAM)', says: 'A TCP socket that uses IPv4 addresses.' },
    seeAlso: ['socket.socket', 'socket.SOCK_STREAM'],
  },
  {
    name: 'socket.SOCK_STREAM',
    aliases: ['socket.SOCK_DGRAM'],
    lang: 'python',
    kind: 'constant',
    official: 'These constants represent the socket types, used for the second argument to socket().',
    source: PYREF,
    when: 'The second argument to socket.socket: it picks the transport. SOCK_STREAM is a reliable byte stream, TCP; SOCK_DGRAM is separate datagrams, UDP.',
    flags: [
      ['SOCK_STREAM', 'TCP: a connection, bytes in order, no message edges'],
      ['SOCK_DGRAM', 'UDP: one message per send, which may be lost'],
    ],
    example: { command: 'srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)', says: 'A TCP socket, ready to bind and listen.' },
    seeAlso: ['socket.socket', 'socket.AF_INET'],
  },
  {
    name: 'socket.SOL_SOCKET',
    aliases: ['socket.SO_REUSEADDR'],
    lang: 'python',
    kind: 'constant',
    official: 'Many constants of these forms, documented in the Unix documentation on sockets and/or the IP protocol, are also defined in the socket module. They are generally used in arguments to the setsockopt() and getsockopt() methods of socket objects.',
    source: PYREF,
    when: 'You set an option on a socket. SOL_SOCKET says the option belongs to the socket layer itself; SO_REUSEADDR lets a restarted server bind its port at once, while old connections are still in TIME-WAIT.',
    example: { command: 'srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)', says: 'Turns on SO_REUSEADDR, so the server can restart without "address already in use".' },
    seeAlso: ['socket.socket'],
  },
  {
    name: 'socket.create_connection',
    lang: 'python',
    kind: 'function',
    official: 'Connect to *address* and return the socket object.',
    source: DOC,
    when: 'You are a TCP client: it makes the socket and connects in one call, doing the three-way handshake. It raises ConnectionRefusedError when nobody listens there. Pass timeout= so it cannot wait for ever.',
    flags: [
      ['address', 'a (host, port) pair'],
      ['timeout', 'seconds to wait before giving up'],
    ],
    example: { command: 'conn = socket.create_connection(("127.0.0.1", 8080))', says: 'A connected TCP socket to port 8080 on this computer, ready for sendall and recv.' },
    seeAlso: ['socket.socket', 'ConnectionError'],
  },
  {
    name: 'socket.timeout',
    lang: 'python',
    kind: 'exception',
    official: 'A deprecated alias of TimeoutError.',
    source: PYREF,
    when: 'You see it in older code that catches a socket timeout. Since Python 3.10 it is the same class as TimeoutError, so write except TimeoutError: in new code.',
    example: { command: 'sock.settimeout(2.0)\ntry:\n    reply = sock.recv(4096)\nexcept TimeoutError:\n    reply = None', says: 'Waits at most 2 seconds for data; older Pythons named the same error socket.timeout.' },
    seeAlso: ['TimeoutError'],
  },
  {
    name: 'threading.Thread',
    lang: 'python',
    kind: 'class',
    official: 'A class that represents a thread of control.',
    source: DOC,
    when: 'You want a function to run on its own thread, alongside the rest of the program. Create it with target=, then start() runs it and join() waits for it. In CPython only one thread runs Python code at a time, so threads help with waiting (sockets, files), not with number crunching.',
    flags: [
      ['target', 'the function the thread runs'],
      ['args', 'a tuple of arguments for it, such as (conn,)'],
      ['.start()', 'begin running it'],
      ['.join()', 'wait until it has finished'],
    ],
    example: { command: 't = threading.Thread(target=count_hits)\nt.start()\nt.join()', says: 'Runs count_hits on a new thread and waits for it to finish.' },
    seeAlso: ['threading.Thread.start', 'threading.Lock', 'threading.Condition'],
  },
  {
    name: 'threading.Thread.start',
    aliases: ['start', 'Thread.start'],
    lang: 'python',
    kind: 'method',
    official: 'Start the thread\'s activity.',
    source: DOC,
    when: 'Starts the new thread, which then runs its target while start returns straight away. Call it once per Thread; a second call raises RuntimeError. Calling the target yourself instead would run it on the current thread.',
    example: { command: 'threading.Thread(target=serve, args=(conn,)).start()', says: 'Serves this connection on its own thread, so the loop can accept the next one at once.' },
    seeAlso: ['threading.Thread'],
  },
  {
    name: 'threading.Condition',
    lang: 'python',
    kind: 'class',
    official: 'Class that implements a condition variable.',
    source: DOC,
    when: 'A thread must sleep until some state changes, such as a queue becoming non-empty. It is a lock with a condition variable built in: take it with with, wait() in a while loop (never an if), and have the other side call notify() after changing the state.',
    flags: [
      ['with cond:', 'take the lock'],
      ['.wait()', 'release the lock, sleep, take it back when woken'],
      ['.notify() / .notify_all()', 'wake one or every waiting thread'],
    ],
    example: {
      command: 'with cond:\n    while not queue:\n        cond.wait()\n    return queue.pop(0)',
      says: 'Sleeps until there is an item, testing again after every wake-up, then takes it.',
    },
    seeAlso: ['threading.Lock', 'threading.Thread'],
  },
  {
    name: 'secrets.token_bytes',
    lang: 'python',
    kind: 'function',
    official: 'Return a random byte string containing *nbytes* bytes.',
    source: DOC,
    when: 'You need random bytes an attacker cannot guess, such as a salt or a key. It draws from the operating system\'s secure generator; the random module is predictable and must never be used for this.',
    flags: [['nbytes', 'how many bytes; 16 bytes are 128 bits']],
    example: { command: 'salt = secrets.token_bytes(16)', says: '16 unpredictable random bytes, different on every call.' },
    seeAlso: ['secrets'],
  },
  {
    name: 'scipy.optimize.linear_sum_assignment',
    lang: 'python',
    kind: 'function',
    official: 'Solve the linear sum assignment problem.',
    source: 'SciPy docstring',
    when: 'You pair each worker with one job so the total cost is as small as possible: minimum-cost bipartite matching. It runs in O(n³) like the Hungarian algorithm, so call it rather than write it. Pass maximize=True to make the total as large as possible.',
    flags: [
      ['cost_matrix', 'cost[i][j] is the cost of giving job j to worker i'],
      ['returns', 'row_ind, col_ind: worker row_ind[k] gets job col_ind[k]'],
    ],
    example: {
      command: 'rows, cols = linear_sum_assignment(cost)\nprint(cost[rows, cols].sum())',
      says: 'Prints the smallest possible total cost of the assignment.',
    },
    seeAlso: ['scipy.optimize'],
  },

  // ---- Python: the interpreter's own tools (compilers course) ----
  {
    name: 'set.discard',
    aliases: ['discard'],
    lang: 'python',
    kind: 'method',
    official: 'Remove an element from a set if it is a member.',
    source: 'Python built-in docstring (set.discard)',
    when: 'You take an item out of a set and do not care whether it was there, as in liveness analysis: live.discard(d). set.remove raises KeyError for a missing item; discard does nothing.',
    example: { command: 'live = {"a", "b"}\nlive.discard("b")\nlive.discard("z")', says: 'live is {"a"}; removing "z", which was never there, is not an error.' },
    seeAlso: ['set.add'],
  },
  {
    name: 'ast.parse',
    lang: 'python',
    kind: 'function',
    official: 'Parse the source into an AST node.',
    source: DOC,
    when: 'You want Python\'s own parser to turn source text into a tree of statements and expressions, without running it, as linters and formatters do. Invalid code raises SyntaxError.',
    flags: [
      ['source', 'the code, as a string'],
      ['.body', 'the list of top-level statements in the tree'],
    ],
    example: { command: 'tree = ast.parse("x = 1\\nprint(x)")\nprint([type(node).__name__ for node in tree.body])', says: "Prints ['Assign', 'Expr']: an assignment, then an expression statement." },
    seeAlso: ['ast.literal_eval'],
  },
  {
    name: 'tokenize.generate_tokens',
    lang: 'python',
    kind: 'function',
    official: 'Tokenize a source reading Python code as unicode strings.',
    source: DOC,
    when: 'You want Python\'s own lexer to split source text into tokens. It takes a readline function, not a string, so wrap text in io.StringIO. Each token has .type, .string and .start, a (line, column) pair with lines from 1 and columns from 0.',
    example: {
      command: 'for tok in tokenize.generate_tokens(io.StringIO("speed = 12\\n").readline):\n    print(tokenize.tok_name[tok.type], repr(tok.string), tok.start)',
      says: "The first line printed is NAME 'speed' (1, 0).",
    },
  },
  {
    name: 'symtable.symtable',
    lang: 'python',
    kind: 'function',
    official: 'Return the toplevel *SymbolTable* for the source code.',
    source: DOC,
    when: 'You want to see how Python resolved the names in some code: which are local, global or free in each function. get_children() gives the tables of the functions inside.',
    flags: [
      ['code', 'the source text'],
      ['filename', 'a name for it, used in error messages'],
      ['compile_type', '"exec" for a module'],
    ],
    example: { command: 'top = symtable.symtable(code, "<orbit>", "exec")\nouter = top.get_children()[0]\nprint(sorted(outer.get_locals()))', says: "For a function outer(a) that sets b and defines inner, prints ['a', 'b', 'inner']." },
  },
  {
    name: 'sys.getrefcount',
    lang: 'python',
    kind: 'function',
    official: 'Return the reference count of object.',
    source: DOC,
    when: 'You want to watch reference counting at work. The number is one higher than you might expect, because passing the object to getrefcount makes a reference too, so compare two counts rather than reading one.',
    example: { command: 'before = sys.getrefcount(probe)\nalias = probe\nprint(sys.getrefcount(probe) - before)', says: 'Prints 1: the name alias is one more reference to the same list.' },
    seeAlso: ['sys.getsizeof'],
  },

  // ---- C++: headers and containers ----
  {
    name: '<stack>',
    lang: 'cpp',
    kind: 'header',
    official: 'std::stack container adaptor',
    source: CPPREF,
    when: 'Include it to use std::stack, a last-in, first-out wrapper around another container (std::deque unless you pick one).',
    example: { command: '#include <stack>\nstd::stack<int, std::vector<int>> s;', says: 'Makes std::stack available and builds one kept in a vector.' },
    seeAlso: ['std::stack', '<queue>'],
  },
  {
    name: 'std::multiset',
    aliases: ['multiset'],
    lang: 'cpp',
    kind: 'class',
    official: 'A standard container made up of elements, which can be retrieved in logarithmic time.',
    source: LIBSTD,
    when: 'A sorted set that keeps duplicates, such as a window of readings where the same value can appear twice. Careful: erase(x) removes every copy of x; to remove one, erase the iterator that find(x) gives.',
    flags: [
      ['insert(x)', 'add x, even if it is already there'],
      ['find(x)', 'an iterator to one copy of x, or end()'],
      ['erase(it)', 'remove the one element it points to'],
      ['equal_range(x)', 'every copy of x, as a pair of iterators'],
    ],
    example: { command: 'auto it = readings.find(x);\nif (it != readings.end()) readings.erase(it);', says: 'Removes exactly one copy of x, if there is one.' },
    seeAlso: ['std::set', 'std::multimap'],
  },
  {
    name: 'std::multimap',
    aliases: ['multimap'],
    lang: 'cpp',
    kind: 'class',
    official: 'A standard container made up of (key,value) pairs, which can be retrieved based on a key, in logarithmic time.',
    source: LIBSTD,
    when: 'A sorted map where one key can have several values, such as every event at the same timestamp. It has no [] operator, because a key does not name one value; use insert and equal_range.',
    example: { command: 'std::multimap<int, std::string> at;\nat.insert({10, "burn"});\nat.insert({10, "log"});', says: 'Keeps both events under the key 10, in the order they were inserted.' },
    seeAlso: ['std::map', 'std::multiset'],
  },
  {
    name: 'std::list::splice',
    aliases: ['list::splice'],
    lang: 'cpp',
    kind: 'method',
    official: 'Insert element from another list.',
    source: LIBSTD,
    when: 'You move a node from one place in a list, or from another list, to a position, in O(1) with no allocation. The node itself moves, so iterators and pointers to it stay valid; this is how an LRU cache moves an entry to the front.',
    flags: [
      ['pos', 'where the node goes'],
      ['other', 'the list it comes from (may be the same list)'],
      ['it', 'the node to move'],
    ],
    example: { command: 'order_.splice(order_.begin(), order_, found->second);', says: 'Moves the found entry to the front of the list, marking it most recently used.' },
    seeAlso: ['std::list'],
  },
  {
    name: 'std::vector::front',
    aliases: ['vector::front'],
    lang: 'cpp',
    kind: 'method',
    official: 'Returns a read/write reference to the data at the first element of the vector.',
    source: LIBSTD,
    when: 'Gives the first element. Calling it on an empty vector is undefined behaviour, with no check and no exception, so test empty() first.',
    example: { command: 'if (!v.empty()) first = v.front();', says: 'Reads the first element only when there is one.' },
    seeAlso: ['std::vector', 'std::vector::at'],
  },
  {
    name: 'std::string_view::npos',
    aliases: ['string_view::npos'],
    lang: 'cpp',
    kind: 'constant',
    official: 'special value. The exact meaning depends on the context',
    source: CPPREF,
    when: 'What find gives on a std::string_view when the text is not there, the same largest-std::size_t value as std::string::npos. Compare find\'s result with it before using it as a position.',
    example: { command: 'auto eq = line.find(\'=\');\nif (eq == std::string_view::npos) return std::nullopt;', says: 'Gives up when the line has no = in it.' },
    seeAlso: ['std::string_view', 'std::string::npos'],
  },
  {
    name: 'std::istream',
    aliases: ['istream'],
    lang: 'cpp',
    kind: 'class',
    official: 'wraps a given abstract device (std::basic_streambuf) and provides high-level input interface',
    source: 'cppreference.com (std::basic_istream)',
    when: 'Take a std::istream& when a function reads input, so it works with std::cin, a file or a std::istringstream in a test. Reading with >> stops at the end of the input or at bad data, and the loop condition sees it.',
    example: { command: 'std::vector<int> capture(std::istream& in, int threshold) {\n    int x;\n    while (in >> x) { /* ... */ }\n}', says: 'Reads whole numbers until the input runs out, from whatever stream the caller passes.' },
    seeAlso: ['std::cin', 'std::getline'],
  },

  // ---- C++: algorithms ----
  {
    name: 'std::partition',
    aliases: ['partition'],
    lang: 'cpp',
    kind: 'function',
    official: 'Move elements for which a predicate is true to the beginning of a sequence.',
    source: LIBSTD,
    when: 'You split a range into two groups by a yes/no test, in place, with exactly n tests. It returns where the second group starts. The order inside each group is not kept; use std::stable_partition for that.',
    example: { command: 'auto mid = std::partition(v.begin(), v.end(), [](int x) { return x % 2 == 0; });', says: 'Puts the even numbers first; mid points at the first odd one.' },
    seeAlso: ['std::stable_partition', 'std::partition_point', 'std::nth_element'],
  },
  {
    name: 'std::stable_partition',
    aliases: ['stable_partition'],
    lang: 'cpp',
    kind: 'function',
    official: 'Move elements for which a predicate is true to the beginning of a sequence, preserving relative ordering.',
    source: LIBSTD,
    when: 'Like std::partition, but both groups keep their original order, such as good packets staying in time order. It is O(n) with a spare buffer and O(n log n) without one.',
    example: { command: 'auto bad = std::stable_partition(p.begin(), p.end(), [](const Packet& k) { return k.valid; });', says: 'Valid packets first, still in time order, then the invalid ones; bad points at the first invalid one.' },
    seeAlso: ['std::partition', 'std::stable_sort'],
  },
  {
    name: 'std::partition_point',
    aliases: ['partition_point'],
    lang: 'cpp',
    kind: 'function',
    official: 'Find the partition point of a partitioned range.',
    source: LIBSTD,
    when: 'The range is already split by a test, all true then all false, and you want where the change happens. It uses binary search, O(log n); std::lower_bound is the special case of a sorted range.',
    example: { command: 'auto it = std::partition_point(v.begin(), v.end(), [](int x) { return x < 10; });', says: 'Points at the first element that is not below 10.' },
    seeAlso: ['std::partition', 'std::lower_bound'],
  },
  {
    name: 'std::adjacent_find',
    aliases: ['adjacent_find'],
    lang: 'cpp',
    kind: 'function',
    official: 'Find two adjacent values in a sequence that are equal.',
    source: LIBSTD,
    when: 'You look for the first place where two neighbours are equal, such as a repeated reading. Pass a two-argument test to look for other neighbour pairs, such as a drop. It needs only a forward iterator.',
    example: { command: 'auto it = std::adjacent_find(v.begin(), v.end());', says: 'Points at the first of two equal neighbours, or end() if there are none.' },
    seeAlso: ['std::find'],
  },
  {
    name: 'std::replace',
    aliases: ['replace'],
    lang: 'cpp',
    kind: 'function',
    official: 'Replace each occurrence of one value in a sequence with another value.',
    source: LIBSTD,
    when: 'You swap every copy of one value for another, in place, such as a -1 "no reading" marker for 0. It needs only a forward iterator.',
    example: { command: 'std::replace(v.begin(), v.end(), -1, 0);', says: 'Turns every -1 in v into 0.' },
    seeAlso: ['std::remove', 'std::transform'],
  },
  {
    name: 'std::make_heap',
    aliases: ['make_heap'],
    lang: 'cpp',
    kind: 'function',
    official: 'Construct a heap over a range.',
    source: LIBSTD,
    when: 'You turn a vector into a max-heap in place, in O(n), to use it as a priority queue you control. Pass the same comparator to every heap function; std::greater gives a min-heap.',
    example: { command: 'std::make_heap(v.begin(), v.end());\nint biggest = v.front();', says: 'Rearranges v so its largest element is first.' },
    seeAlso: ['std::push_heap', 'std::pop_heap', 'std::sort_heap', 'std::priority_queue'],
  },
  {
    name: 'std::push_heap',
    aliases: ['push_heap'],
    lang: 'cpp',
    kind: 'function',
    official: 'Push an element onto a heap.',
    source: LIBSTD,
    when: 'After v.push_back(x) on a heap, it moves the new last element up to its place, in O(log n). Push first, then call it.',
    example: { command: 'v.push_back(7);\nstd::push_heap(v.begin(), v.end());', says: 'Adds 7 to the heap in v.' },
    seeAlso: ['std::make_heap', 'std::pop_heap'],
  },
  {
    name: 'std::pop_heap',
    aliases: ['pop_heap'],
    lang: 'cpp',
    kind: 'function',
    official: 'Pop an element off a heap.',
    source: LIBSTD,
    when: 'It moves the top of the heap to the last position and repairs the rest, in O(log n). It does not remove anything: call v.pop_back() after it.',
    example: { command: 'std::pop_heap(v.begin(), v.end());\nint top = v.back();\nv.pop_back();', says: 'Takes the largest element out of the heap.' },
    seeAlso: ['std::make_heap', 'std::push_heap'],
  },
  {
    name: 'std::sort_heap',
    aliases: ['sort_heap'],
    lang: 'cpp',
    kind: 'function',
    official: 'Sort a heap.',
    source: LIBSTD,
    when: 'You turn a heap into a sorted range, smallest first, in O(n log n) by popping repeatedly. make_heap followed by sort_heap is heapsort. Afterwards the range is no longer a heap.',
    example: { command: 'std::make_heap(v.begin(), v.end());\nstd::sort_heap(v.begin(), v.end());', says: 'Sorts v in increasing order.' },
    seeAlso: ['std::make_heap', 'std::sort'],
  },
  {
    name: 'std::inclusive_scan',
    aliases: ['inclusive_scan'],
    lang: 'cpp',
    kind: 'function',
    official: 'Output the cumulative sum of one range to a second range',
    source: LIBSTD,
    when: 'You want running totals: position i gets the combination of everything up to and including i. Unlike std::partial_sum it may group the work in any order, so it can run in parallel with std::execution::par, and the operation must be associative.',
    example: { command: 'std::inclusive_scan(v.begin(), v.end(), out.begin());', says: 'For v = {5, 2, 8} writes {5, 7, 15}.' },
    seeAlso: ['std::exclusive_scan', 'std::reduce', 'std::execution::par'],
  },
  {
    name: 'std::exclusive_scan',
    aliases: ['exclusive_scan'],
    lang: 'cpp',
    kind: 'function',
    official: 'Output the cumulative sum of one range to a second range',
    source: LIBSTD,
    when: 'Running totals that leave out the element itself: position i gets the combination of everything before i, and position 0 gets the starting value you pass. It turns sizes into starting offsets.',
    example: { command: 'std::exclusive_scan(v.begin(), v.end(), out.begin(), 0);', says: 'For v = {5, 2, 8} writes {0, 5, 7}.' },
    seeAlso: ['std::inclusive_scan', 'std::reduce'],
  },
  {
    name: 'std::transform_reduce',
    aliases: ['transform_reduce'],
    lang: 'cpp',
    kind: 'function',
    official: 'Transform the elements of a range and reduce',
    source: LIBSTD,
    when: 'You change each element and add up the results in one pass, such as a sum of squares or a dot product, possibly in parallel. Like std::reduce it may combine in any order, so the combining operation must be associative and commutative.',
    flags: [
      ['init', 'the starting value, which also sets the result type'],
      ['reduce op', 'how results are combined, such as std::plus<>()'],
      ['transform op', 'what is done to each element'],
    ],
    example: { command: 'double ss = std::transform_reduce(v.begin(), v.end(), 0.0, std::plus<>(), [](double x) { return x * x; });', says: 'The sum of the squares of v.' },
    seeAlso: ['std::reduce', 'std::transform', 'std::accumulate'],
  },
  {
    name: 'std::ranges::count_if',
    aliases: ['ranges::count_if'],
    lang: 'cpp',
    kind: 'function',
    official: 'returns the number of elements satisfying specific criteria',
    source: CPPREF,
    when: 'Counts the elements that pass a test, taking the whole range as one argument instead of begin and end. The count comes back as the range\'s difference type, a signed number.',
    example: { command: 'return std::ranges::count_if(words, [n](const std::string& w) { return w.size() >= n; });', says: 'How many words have at least n characters.' },
    seeAlso: ['std::count_if', 'std::ranges::count'],
  },

  // ---- C++: iterators, concepts, traits ----
  {
    name: 'std::iterator_traits',
    aliases: ['iterator_traits'],
    lang: 'cpp',
    kind: 'class',
    official: 'Traits class for iterators.',
    source: LIBSTD,
    when: 'Reads the facts an iterator announces about itself (iterator_category, value_type, difference_type, pointer, reference), and works for plain pointers too. Algorithms and adaptors use it instead of asking the iterator directly.',
    example: { command: 'using value_type = typename std::iterator_traits<It>::value_type;', says: 'The element type of whatever It points at, even when It is a raw pointer.' },
    seeAlso: ['std::random_access_iterator_tag', 'std::forward_iterator_tag'],
  },
  {
    name: 'std::bidirectional_iterator_tag',
    aliases: ['bidirectional_iterator_tag'],
    lang: 'cpp',
    kind: 'class',
    official: 'Bidirectional iterators support a superset of forward iterator operations.',
    source: LIBSTD,
    when: 'Your iterator can go back with -- as well as forward, like a list\'s. Name it as iterator_category so algorithms know what it can do.',
    example: { command: 'using iterator_category = std::bidirectional_iterator_tag;', says: 'Announces that this iterator moves both ways, one step at a time.' },
    seeAlso: ['std::random_access_iterator_tag', 'std::forward_iterator_tag', 'std::bidirectional_iterator'],
  },
  {
    name: 'std::random_access_iterator_tag',
    aliases: ['random_access_iterator_tag'],
    lang: 'cpp',
    kind: 'class',
    official: 'Random-access iterators support a superset of bidirectional iterator operations.',
    source: LIBSTD,
    when: 'Your iterator can jump any distance in O(1) (it + n, it[n], it2 - it), like a vector\'s. It inherits from std::bidirectional_iterator_tag, which is how older algorithms picked the fastest version.',
    example: { command: 'using iterator_category = std::random_access_iterator_tag;', says: 'Announces that this iterator can jump, so std::sort accepts it.' },
    seeAlso: ['std::bidirectional_iterator_tag', 'std::random_access_iterator'],
  },
  {
    name: 'std::bidirectional_iterator',
    aliases: ['bidirectional_iterator'],
    lang: 'cpp',
    kind: 'library',
    official: 'specifies that a forward_iterator is a bidirectional iterator, supporting movement backwards',
    source: CPPREF,
    when: 'A C++20 concept: true for an iterator that can go forward and back, such as a std::list iterator. Use it in a static_assert or a requires clause to check your own iterator.',
    example: { command: 'std::cout << std::bidirectional_iterator<std::list<int>::iterator>;', says: 'Prints 1: list iterators can go both ways.' },
    seeAlso: ['std::random_access_iterator', 'std::forward_iterator'],
  },
  {
    name: 'std::random_access_iterator',
    aliases: ['random_access_iterator'],
    lang: 'cpp',
    kind: 'library',
    official: 'specifies that a bidirectional_iterator is a random-access iterator, supporting advancement in constant time and subscripting',
    source: CPPREF,
    when: 'A C++20 concept: true for an iterator that can jump in O(1), such as a pointer or a vector iterator, and false for a list\'s. std::ranges::sort requires it.',
    example: { command: 'std::cout << std::random_access_iterator<int*> << std::random_access_iterator<std::list<int>::iterator>;', says: 'Prints 10: a pointer can jump, a list iterator cannot.' },
    seeAlso: ['std::bidirectional_iterator', 'std::random_access_iterator_tag'],
  },
  {
    name: 'std::reverse_iterator',
    aliases: ['reverse_iterator'],
    lang: 'cpp',
    kind: 'class',
    official: 'iterator adaptor for reverse-order traversal',
    source: CPPREF,
    when: 'Turns a bidirectional iterator around, so ++ goes backwards; rbegin() and rend() return these. The trick: it holds the position one past the element it shows, so *r is *(base - 1).',
    example: { command: 'auto it = std::find(v.rbegin(), v.rend(), 7);', says: 'Finds the last 7 in v by searching from the back.' },
    seeAlso: ['std::reverse', 'std::bidirectional_iterator'],
  },
  {
    name: 'std::movable',
    aliases: ['movable'],
    lang: 'cpp',
    kind: 'library',
    official: 'specifies that an object of a type can be moved and swapped',
    source: CPPREF,
    when: 'A C++20 concept for a template that only needs to move its elements around, not copy them, so it accepts std::unique_ptr. A wrong type then fails with a short message at the call.',
    example: { command: 'template <std::movable T>\nclass Ring { /* ... */ };', says: 'Ring<std::unique_ptr<int>> compiles; a type that cannot be moved is refused.' },
    seeAlso: ['std::move'],
  },
  {
    name: 'std::is_nothrow_move_constructible',
    aliases: ['is_nothrow_move_constructible'],
    lang: 'cpp',
    kind: 'class',
    official: 'checks if a type can be constructed from an rvalue reference',
    source: CPPREF,
    when: 'The trait std::vector checks when it grows: it moves elements only if moving cannot throw, and copies them otherwise, to keep the strong guarantee. Mark your move constructor noexcept. The _v form gives the bool directly.',
    example: { command: 'static_assert(std::is_nothrow_move_constructible<Matrix3>::value);', says: 'Stops the build if moving a Matrix3 could throw.' },
    seeAlso: ['std::is_nothrow_move_constructible_v', 'std::move_if_noexcept'],
  },
  {
    name: 'std::remove_const_t',
    aliases: ['remove_const_t', 'std::remove_const'],
    lang: 'cpp',
    kind: 'type',
    official: 'removes const and/or volatile specifiers from the given type',
    source: 'cppreference.com (std::remove_cv)',
    when: 'You need the type without its const, such as an iterator\'s value_type when it points at const elements: const int becomes int. It comes from <type_traits>.',
    example: { command: 'using value_type = std::remove_const_t<U>;', says: 'For U = const double, value_type is double.' },
    seeAlso: ['std::remove_cv_t', '<type_traits>'],
  },
  {
    name: 'std::equal_to',
    aliases: ['equal_to'],
    lang: 'cpp',
    kind: 'class',
    official: 'function object implementing x == y',
    source: CPPREF,
    when: 'The default KeyEqual of std::unordered_map and std::unordered_set: it calls ==. Give your own when keys should compare differently, and keep it consistent with the hash: equal keys must have equal hashes.',
    example: { command: 'std::unordered_map<Key, int, KeyHash, std::equal_to<Key>> m;', says: 'The same as leaving the last argument out: keys are compared with ==.' },
    seeAlso: ['std::hash', 'std::unordered_map', 'std::less'],
  },

  // ---- C++: numbers and time ----
  {
    name: 'std::log',
    lang: 'cpp',
    kind: 'function',
    official: 'computes natural (base e) logarithm (ln(x))',
    source: CPPREF,
    when: 'The natural logarithm, from <cmath>. The ratio of two logarithms is the same in any base, so an exponent like log(t2 / t1) / log(n2 / n1) can use this one. Zero gives -infinity and a negative number gives NaN.',
    example: { command: 'return std::log(t2 / t1) / std::log(n2 / n1);', says: 'The exponent b for which the time grows like n to the b.' },
    seeAlso: ['std::log2', 'std::log10', 'std::exp'],
  },
  {
    name: 'std::llround',
    aliases: ['llround'],
    lang: 'cpp',
    kind: 'function',
    official: 'nearest integer, rounding away from zero in halfway cases',
    source: CPPREF,
    when: 'Rounds a double to the nearest whole number and gives it as a long long, from <cmath>. Halves go away from zero, so 2.5 becomes 3 and -2.5 becomes -3.',
    example: { command: 'long long k = std::llround(fitted_exponent(runs));', says: 'For a fitted exponent of 1.97 gives 2.' },
    seeAlso: ['std::lround', 'std::round'],
  },
  {
    name: 'std::strtoll',
    aliases: ['strtoll'],
    lang: 'cpp',
    kind: 'function',
    official: 'converts a byte string to an integer value',
    source: CPPREF,
    when: 'You want a long long from a C string without exceptions, as in a tokenizer. The third argument is the base, 10 for ordinary numbers. Pass a char** as the second to learn where the digits ended, or nullptr.',
    flags: [
      ['str', 'the C string, such as text.c_str()'],
      ['end', 'where to store the position after the number, or nullptr'],
      ['base', '10 for decimal'],
    ],
    example: { command: 'return std::strtoll(s.substr(start, i - start).c_str(), nullptr, 10);', says: 'For the digits "250" gives 250LL.' },
    seeAlso: ['std::strtod', 'std::stoi'],
  },
  {
    name: 'std::ratio',
    aliases: ['ratio'],
    lang: 'cpp',
    kind: 'class',
    official: 'Provides compile-time rational arithmetic.',
    source: LIBSTD,
    when: 'Writes the unit of a std::chrono::duration as a fraction of a second, fixed at compile time: std::ratio<60> is a minute and std::milli is std::ratio<1, 1000>.',
    example: { command: 'std::chrono::duration<double, std::ratio<60>> exact_minutes = burn;', says: 'Holds the burn time in minutes, with a fractional part: 90 s is 1.5.' },
    seeAlso: ['std::chrono::duration', 'std::milli'],
  },
  {
    name: 'std::chrono::hours',
    aliases: ['chrono::hours'],
    lang: 'cpp',
    kind: 'type',
    official: 'duration type with Period std::ratio<3600>',
    source: CPPREF,
    when: 'A duration counted in whole hours. duration_cast to it keeps only the whole hours, which is the first step in formatting elapsed time as HH:MM:SS.',
    example: { command: 'auto h = std::chrono::duration_cast<std::chrono::hours>(d);', says: 'For 3,723,004 ms gives 1 hour.' },
    seeAlso: ['std::chrono::minutes', 'std::chrono::seconds', 'std::chrono::duration_cast'],
  },
  {
    name: 'std::chrono::minutes',
    aliases: ['chrono::minutes'],
    lang: 'cpp',
    kind: 'type',
    official: 'duration type with Period std::ratio<60>',
    source: CPPREF,
    when: 'A duration counted in whole minutes. Converting seconds to it needs duration_cast, because it drops the remainder: 90 s becomes 1 minute.',
    example: { command: 'auto whole_minutes = std::chrono::duration_cast<std::chrono::minutes>(burn);', says: 'For a 90-second burn gives 1; the 30 s are dropped.' },
    seeAlso: ['std::chrono::hours', 'std::chrono::seconds', 'std::chrono::duration_cast'],
  },
  {
    name: 'std::chrono::round',
    aliases: ['chrono::round'],
    lang: 'cpp',
    kind: 'function',
    official: 'converts a duration to another, rounding to nearest, ties to even',
    source: CPPREF,
    when: 'Converts to a coarser unit and rounds to the nearest one, where duration_cast would simply cut off the remainder. std::chrono::floor and ceil round down and up (all C++17).',
    example: { command: 'auto s = std::chrono::round<std::chrono::seconds>(std::chrono::milliseconds{1999});', says: 'Gives 2 s; duration_cast would give 1 s.' },
    seeAlso: ['std::chrono::floor', 'std::chrono::duration_cast'],
  },

  // ---- C++: threads ----
  {
    name: 'std::counting_semaphore',
    aliases: ['counting_semaphore'],
    lang: 'cpp',
    kind: 'class',
    official: 'semaphore that models a non-negative resource count',
    source: CPPREF,
    when: 'Limits how many threads use something at once, such as four slots in a buffer. acquire() waits until the count is above zero and takes one; release() gives one back (C++20, <semaphore>).',
    flags: [
      ['acquire()', 'wait for a unit and take it'],
      ['release()', 'give a unit back, waking a waiter'],
    ],
    example: { command: 'std::counting_semaphore<4> slots{4};\nslots.acquire();\n/* use a slot */\nslots.release();', says: 'At most four threads are between acquire and release at any time.' },
    seeAlso: ['std::mutex', 'std::condition_variable', 'std::latch'],
  },
  {
    name: 'std::latch',
    aliases: ['latch'],
    lang: 'cpp',
    kind: 'class',
    official: 'single-use thread barrier',
    source: CPPREF,
    when: 'Waits until N things have happened, such as N workers finishing their setup. Each calls count_down(); wait() blocks until the count reaches zero. It cannot be reset; std::barrier is the reusable one (C++20, <latch>).',
    flags: [
      ['count_down()', 'lower the count by one'],
      ['wait()', 'block until the count is zero'],
    ],
    example: { command: 'std::latch done{3};\n// each of 3 workers: done.count_down();\ndone.wait();', says: 'The main thread goes on only after all three workers have counted down.' },
    seeAlso: ['std::barrier', 'std::counting_semaphore'],
  },
  // ---- Names the capstones teach ----
  {
    name: 'asyncio.run',
    lang: 'python',
    kind: 'function',
    official: 'Execute the coroutine and return the result. This function runs the passed coroutine, taking care of managing the asyncio event loop and finalizing asynchronous generators.',
    source: 'Python standard library docstring (asyncio.run)',
    when: 'The one call that starts an asyncio program from ordinary code: asyncio.run(main()). It makes a new event loop, runs main to the end and closes the loop. It refuses to run inside a loop that is already running, which is the case in ORBIT\'s browser Python: there, write await main() at the top level instead.',
    example: { command: 'asyncio.run(main())', says: 'Runs the coroutine main, and everything it starts, until main returns.' },
    seeAlso: ['asyncio.create_task', 'asyncio.gather', 'asyncio.sleep'],
  },
  {
    name: 'asyncio.start_server',
    lang: 'python',
    kind: 'function',
    official: 'Start a socket server, call back for each client connected.',
    source: 'Python standard library docstring (asyncio.start_server)',
    when: 'A real TCP server on a laptop: asyncio calls your handler with a StreamReader and a StreamWriter for each client that connects, each in its own task. Browsers have no sockets, so ORBIT\'s Python cannot run it; the HTTP capstone tests the same handler on a simulated network and shows this wiring for your own machine.',
    flags: [
      ['client_connected_cb', 'the coroutine called with (reader, writer) for each connection'],
      ['host, port', 'where to listen, such as "127.0.0.1", 8080'],
    ],
    example: { command: 'server = await asyncio.start_server(handle, "127.0.0.1", 8080)\nasync with server:\n    await server.serve_forever()', says: 'Listens on port 8080 and runs handle for every client until the program is stopped.' },
    seeAlso: ['asyncio.run', 'asyncio.create_task'],
  },
  {
    name: 'struct.Struct',
    lang: 'python',
    kind: 'class',
    official: 'Struct(fmt) --> compiled struct object',
    source: 'Python standard library docstring (struct.Struct)',
    when: 'The same layout packed or unpacked many times, such as every record in a log file. It reads the format string once, and its size attribute says how many bytes one record takes, so you can step through a buffer record by record.',
    example: { command: 'HEADER = struct.Struct("<IHH")\nmagic, version, count = HEADER.unpack_from(buf, 0)', says: 'Reads a 4-byte and two 2-byte little-endian numbers from the start of buf; HEADER.size is 8.' },
    seeAlso: ['struct.pack', 'struct.unpack', 'struct.unpack_from', 'struct.calcsize'],
  },
  {
    name: 'PRINTF',
    aliases: ['printf', 'FORMAT', 'format'],
    lang: 'sql',
    kind: 'function',
    official: 'The printf() SQL function is an alias for the format() SQL function. The format() SQL function works like the sqlite3_mprintf() C-language function and the printf() function from the standard C library.',
    source: 'SQLite documentation (lang_corefunc.html)',
    when: 'Numbers shown with a fixed number of decimals, or padded to a width, in a report query: printf(\'%.2f\', x) gives 3.14. The result is text, so sort on the number, not the formatted column. The name format() needs SQLite 3.38 or newer; printf() works everywhere.',
    example: { command: "SELECT sensor, printf('%.1f', AVG(value)) AS mean FROM readings GROUP BY sensor;", says: 'Shows each sensor with its average reading to one decimal place, such as 21.4.' },
    seeAlso: ['ROUND', 'CAST'],
  },
  {
    name: 'std::memmove',
    aliases: ['memmove'],
    lang: 'cpp',
    kind: 'function',
    official: 'moves one buffer to another',
    source: 'cppreference.com',
    when: 'You copy bytes where the source and the destination may overlap, such as sliding the unread part of a buffer to its front. std::memcpy is wrong there: with overlap its result is undefined. memmove copies as if through a temporary buffer.',
    example: { command: 'std::memmove(buf, buf + used, len - used);', says: 'Moves the bytes not yet read to the start of buf, even though the two ranges overlap.' },
    seeAlso: ['std::memcpy', 'std::copy'],
  },
  {
    name: 'std::strchr',
    aliases: ['strchr'],
    lang: 'cpp',
    kind: 'function',
    official: 'finds the first occurrence of a character',
    source: 'cppreference.com',
    when: 'You look for one character in a C string, such as the = in a key=value line. It returns a pointer to it, or nullptr when it is not there, so check before using the result.',
    example: { command: 'const char* eq = std::strchr(line, \'=\');\nif (eq) value = eq + 1;', says: 'Points value at the text after the first =, if the line has one.' },
    seeAlso: ['std::strncmp', 'std::string_view'],
  },
  {
    name: 'std::strncmp',
    aliases: ['strncmp'],
    lang: 'cpp',
    kind: 'function',
    official: 'compares a certain number of characters from two strings',
    source: 'cppreference.com',
    when: 'You compare only the start of a C string, such as checking whether a command begins with "SET ". Like std::strcmp it returns 0 on a match, so write == 0; it stops early at a terminating null.',
    example: { command: 'if (std::strncmp(cmd, "SET ", 4) == 0) handle_set(cmd + 4);', says: 'Handles the command when its first four characters are SET and a space.' },
    seeAlso: ['std::strcmp', 'std::strchr'],
  },
  {
    name: 'std::strtok',
    aliases: ['strtok'],
    lang: 'cpp',
    kind: 'function',
    official: 'finds the next token in a byte string',
    source: 'cppreference.com',
    when: 'Old C code splitting a line into words. It writes null characters into your string and remembers its place in hidden static state, so it cannot split two strings at once and is not safe in threads. Prefer std::string_view with find in new code.',
    example: { command: 'for (char* w = std::strtok(line, " "); w; w = std::strtok(nullptr, " ")) use(w);', says: 'Visits each space-separated word of line, cutting line up as it goes.' },
    seeAlso: ['std::strchr', 'std::string_view'],
  },
  {
    name: 'std::strtol',
    aliases: ['strtol'],
    lang: 'cpp',
    kind: 'function',
    official: 'converts a byte string to an integer value',
    source: 'cppreference.com',
    when: 'You parse a number from C text and need to know where it stopped and whether it fit. The end pointer shows the first character not used; if it equals the start, there was no number. Out of range sets errno to ERANGE. long is 4 bytes in ORBIT\'s browser C++ and 8 on most 64-bit laptops.',
    flags: [
      ['str_end', 'set to the first character after the number'],
      ['base', '10 for decimal, 16 for hex, 0 to go by the prefix (0x, 0)'],
    ],
    example: { command: 'char* end;\nlong n = std::strtol(text, &end, 10);\nif (end == text) error("not a number");', says: 'Reads a decimal number from text and reports when there was none.' },
    seeAlso: ['std::from_chars', 'std::stoi'],
  },
  // ---- Names that only a newer Python or a fuller machine has (found by CI) ----
  {
    name: 'os.unshare',
    lang: 'python',
    kind: 'function',
    official: 'Disassociate parts of a process (or thread) execution context.',
    source: 'Python standard library docstring (os.unshare)',
    when: 'Linux only, Python 3.12 or newer, and usually as root: the call a container runtime makes to give a process its own private copy of something the host shares, such as the host name or the list of mounts. The operating systems course shows it to explain containers; neither ORBIT\'s browser Python nor a Mac has it.',
    flags: [['flags', 'which namespaces to make private, such as os.CLONE_NEWUTS for the host name']],
    example: { command: 'os.unshare(os.CLONE_NEWUTS)\nsocket.sethostname("sandbox")', says: 'Gives this process its own host name, which the rest of the machine does not see (Linux, as root).' },
    seeAlso: ['os.CLONE_NEWUTS'],
  },
  {
    name: 'os.CLONE_NEWUTS',
    lang: 'python',
    kind: 'constant',
    official: 'Namespaces to be unshared.',
    source: 'Python standard library docstring (os.unshare, flags)',
    when: 'The flag for os.unshare that gives a process its own host name and domain name, the UTS namespace. It is one of several: CLONE_NEWNS for mounts, CLONE_NEWNET for the network, CLONE_NEWPID for process numbers. Linux only, Python 3.12 or newer.',
    example: { command: 'os.unshare(os.CLONE_NEWUTS)', says: 'Makes the host name private to this process from now on.' },
    seeAlso: ['os.unshare'],
  },
  {
    name: 'ping',
    kind: 'system',
    official: 'send ICMP ECHO_REQUEST to network hosts',
    source: 'ping manual page (iputils)',
    when: 'You want to know whether a machine answers on the network at all, and how long a round trip takes. Each reply shows its sequence number and time; a gap in the numbers is a lost packet. A machine that does not answer may still be up: many firewalls drop ping.',
    flags: [
      ['-c', 'stop after this many requests (without it, Linux pings until Ctrl+C)'],
      ['-i', 'seconds to wait between requests'],
      ['-W', 'seconds to wait for each reply'],
    ],
    example: { command: 'ping -c 4 8.8.8.8', says: 'Sends four requests and prints each reply time, then how many were lost and the average round trip.' },
    seeAlso: ['curl'],
  },
  {
    name: 'sys._is_gil_enabled',
    lang: 'python',
    kind: 'function',
    official: 'Return True if the GIL is currently enabled and False otherwise.',
    source: 'Python standard library docstring (sys._is_gil_enabled)',
    when: 'You want to know whether the Python running your code has the global interpreter lock on, which decides whether threads can run Python code in parallel. It is False only on a free-threaded build (python3.13t, python3.14t). Python 3.13 or newer; the underscore means it is not a promised interface and may change.',
    example: { command: 'print(sys._is_gil_enabled())', says: 'Prints True on an ordinary Python, False on a free-threaded one.' },
    seeAlso: ['sys'],
  },
]
