import type { CommandRef } from './types'

const STD = 'Rust standard library documentation'
const PG = 'PostgreSQL 16 documentation'
const MATLAB = 'MATLAB documentation (MathWorks)'
const DOC = 'Python standard library docstring'
const NP = 'NumPy docstring'

export const COMMANDS: CommandRef[] = [
  /* ------------------------------------------------------------ terminal */
  {
    name: 'actionlint',
    kind: 'build',
    official: 'actionlint is a static checker for GitHub Actions workflow files.',
    source: 'actionlint README (rhysd/actionlint)',
    when: 'Before you push a change to a GitHub Actions workflow, to catch typos in keys, bad ${{ }} expressions and broken shell in run: steps without waiting for CI to fail. Run it from the top of the repository and it checks every file in .github/workflows. Passing it means the file is well formed, not that your jobs will succeed.',
    example: { command: 'actionlint', says: 'Checks every workflow in .github/workflows. It prints nothing and exits with 0 when all of them are fine, or one line per problem with the file, line and column.' },
    seeAlso: ['shellcheck'],
  },
  {
    name: 'base64',
    kind: 'text',
    official: 'base64 encode/decode data and print to standard output',
    source: 'base64 manual page (GNU coreutils)',
    when: 'You need to carry bytes as plain letters and digits, for example inside a config file or a web page, or to read something that was written that way. It is an encoding, not encryption: anyone can turn it back with base64 -d, so a base64 secret is not hidden at all. The text comes out about a third bigger than the bytes went in.',
    flags: [['-d', 'decode: turn base64 text back into the original bytes']],
    example: { command: 'echo "GO for launch" | base64\necho "R08gZm9yIGxhdW5jaAo=" | base64 -d', says: 'The first line prints R08gZm9yIGxhdW5jaAo=. The second turns it back into GO for launch.' },
    seeAlso: ['sha256sum'],
  },
  {
    name: 'clang-format',
    kind: 'build',
    official: 'A tool to format C/C++/Java/JavaScript/JSON/Objective-C/Protobuf/C# code.',
    source: 'clang-format --help (LLVM)',
    when: 'You want every C++ file laid out the same way (indents, spaces, line breaks) without arguing about it. It reads its rules from a .clang-format file in the project. Without -i or --dry-run it only prints the formatted code, and with -i it rewrites your files in place.',
    flags: [
      ['--dry-run', 'do not change any file; just report the lines that would change'],
      ['--Werror', 'treat those reports as errors, so the command fails (good for CI)'],
    ],
    example: { command: 'clang-format --dry-run --Werror src/*.cpp src/*.hpp', says: 'Checks the layout of every source and header file and fails, naming each line, if any of them is not formatted to the project rules.' },
    seeAlso: ['clang-tidy'],
  },
  {
    name: 'clang-tidy',
    kind: 'build',
    official: 'clang-tidy is a clang-based C++ "linter" tool.',
    source: 'Clang-Tidy documentation (LLVM)',
    when: 'You want a program to read your C++ and point out likely bugs and old-fashioned code, such as using a value after moving it or copying a big vector for no reason. You pick the checks you want; it reads the code with the real compiler\'s parser, so it needs the same flags you compile with. It finds many bugs, never all of them.',
    flags: [
      ['--checks=\'-*,bugprone-*\'', 'turn every check off, then turn on the families you want'],
      ['-p build', 'read the compile flags from build/compile_commands.json'],
      ['--warnings-as-errors=\'*\'', 'make every warning fail the command (for CI)'],
      ['-- -std=c++20', 'everything after -- is passed to the compiler as flags'],
      ['-fix', 'apply the suggested fixes to your files'],
    ],
    example: { command: 'clang-tidy --checks=\'-*,bugprone-*,performance-*\' attitude.cpp -- -std=c++20', says: 'Reads attitude.cpp and prints a warning, with the check name in brackets, for each likely bug or slow copy it finds.' },
    seeAlso: ['clang-format', 'g++'],
  },
  {
    name: 'dockerd',
    kind: 'system',
    official: 'dockerd is the persistent process that manages containers.',
    source: 'dockerd reference (Docker CLI docs)',
    when: 'You rarely type it yourself: it is the Docker daemon, the background program that really builds images and runs containers. The docker command only sends it requests. When docker says it cannot connect to the Docker daemon, this is the program that is not running.',
    example: { command: 'pgrep -a dockerd', says: 'Shows the process number and command line of the running Docker daemon, such as 9802 dockerd. No output means Docker is not running.' },
    seeAlso: ['docker', 'pgrep'],
  },
  {
    name: 'getent',
    kind: 'system',
    official: 'get entries from Name Service Switch libraries',
    source: 'getent manual page (GNU C Library)',
    when: 'You want to know what a name turns into, the same way programs on this machine look it up: a hostname into an address, a user name into its account line. Inside a container it is the quick way to check that one service can find another by name. It exits with 2 when the name is not found.',
    flags: [['hosts NAME', 'look up the IP address for a hostname']],
    example: { command: 'getent hosts tracker', says: 'Prints the address and the name, such as 172.18.0.2 tracker, or nothing (exit code 2) if no one knows that name.' },
  },
  {
    name: 'mount',
    kind: 'system',
    official: 'mount a filesystem',
    source: 'mount manual page (util-linux)',
    when: 'You want a disk, a shared folder or a special filesystem to appear at a folder (the mount point) so you can use its files. It needs root, so it usually runs with sudo. Whatever was in the mount point folder before is hidden until you unmount.',
    flags: [
      ['-t TYPE', 'the kind of filesystem, such as ext4 or overlay'],
      ['-o OPTIONS', 'comma-separated settings, such as lowerdir=...,upperdir=... for overlay'],
    ],
    example: { command: 'sudo mount -t overlay overlay \\\n  -o lowerdir=lower2:lower1,upperdir=upper,workdir=work merged', says: 'Stacks two read-only folders and one writable folder into a single view at merged, the way Docker builds a container from image layers.' },
    seeAlso: ['umount', 'findmnt', 'df'],
  },
  {
    name: 'pg_isready',
    kind: 'system',
    official: 'check the connection status of a PostgreSQL server',
    source: PG,
    when: 'You need to wait until a PostgreSQL database is ready for connections, for example in a Docker Compose health check, since a started container is not yet a ready database. It answers with its exit code: 0 means accepting connections, anything else means not yet.',
    flags: [
      ['-U USER', 'the user name to check as'],
      ['-d DBNAME', 'the database to check'],
    ],
    example: { command: 'pg_isready -U sim -d telemetry', says: 'Prints something like /var/run/postgresql:5432 - accepting connections and exits with 0 once the server is up.' },
    seeAlso: ['psql', 'docker compose'],
  },
  {
    name: 'psql',
    kind: 'system',
    official: 'PostgreSQL interactive terminal',
    source: PG,
    when: 'You want to type SQL at a PostgreSQL database and see the results, or run one query from a script. Commands that start with a backslash, such as \\dt, belong to psql itself, not to SQL, so they do not work from Python or other tools. Each statement commits on its own unless you start a transaction with BEGIN.',
    flags: [
      ['-U USER', 'connect as this database user'],
      ['-d DBNAME', 'connect to this database'],
      ['-c "SQL"', 'run one command, print the result and quit'],
      ['-t', 'print only the rows, with no column headers or row count'],
      ['-E', 'show the real queries behind backslash commands'],
      ['\\dt, \\d NAME', 'list the tables; describe one table'],
    ],
    example: { command: 'psql -U sim -d telemetry -c "SELECT count(*) FROM drop_test;"', says: 'Connects to the telemetry database as sim, prints the number of rows in drop_test, and exits.' },
    seeAlso: ['pg_isready'],
  },
  {
    name: 'sha256sum',
    kind: 'file',
    official: 'compute and check SHA256 message digest',
    source: 'sha256sum manual page (GNU coreutils)',
    when: 'You want to know whether two files are exactly the same, byte for byte, or that a download was not damaged. Each file gets a 64-character fingerprint; change a single byte and it changes completely. Equal fingerprints mean equal files.',
    example: { command: 'sha256sum run1.csv run2.csv', says: 'Prints a 64-character fingerprint and the file name for each file. If the two fingerprints match, the two runs wrote identical results.' },
    seeAlso: ['base64'],
  },
  {
    name: 'unzip',
    kind: 'file',
    official: 'list, test and extract compressed files in a ZIP archive',
    source: 'unzip manual page (Info-ZIP)',
    when: 'You have a .zip file and want what is inside. Many files that do not end in .zip are ZIP archives too, such as Simulink .slx models, Word documents and Python wheels. By default it writes the files into the current folder and asks before overwriting.',
    flags: [['-p', 'print the contents of the files to the screen instead of writing them to disk']],
    example: { command: 'unzip -p models/attitude.slx | head', says: 'Prints the first lines of the XML files packed inside the Simulink model, without extracting anything.' },
    seeAlso: ['tar'],
  },
  {
    name: 'useradd',
    kind: 'system',
    official: 'create a new user or update default new user information',
    source: 'useradd manual page (shadow-utils)',
    when: 'You want a new user account, most often in a Dockerfile so the program does not run as root. It needs root. Without --create-home the user gets no home folder, which some programs then trip over.',
    flags: [
      ['--uid N', 'give the user this number, such as 1000, to match your own user on the host'],
      ['--create-home', 'make the user\'s home folder, /home/NAME'],
    ],
    example: { command: 'useradd --uid 1000 --create-home sim', says: 'Creates the user sim with user number 1000 and a home folder at /home/sim.' },
    seeAlso: ['chown', 'id'],
  },

  /* ---------------------------------------------------------------- rust */
  {
    name: 'const_assert_eq!',
    lang: 'rust',
    kind: 'macro',
    official: 'Asserts that constants are equal in value.',
    source: 'static_assertions crate documentation',
    when: 'You want the build to stop if two constants ever stop being equal, such as a buffer size and the frame size it must match. The check runs while compiling and adds no code to the program. Both sides must be things the compiler can work out, so no values read at run time.',
    flags: [['const_assert_eq!(a, b)', 'fail the build unless a equals b']],
    example: { command: 'const_assert_eq!(FRAME_BYTES, 16);', says: 'The build stops with an error if someone changes FRAME_BYTES to anything but 16.' },
    seeAlso: ['const_assert!', 'assert_eq_size!', 'assert_eq!'],
  },
  {
    name: 'continue',
    lang: 'rust',
    kind: 'keyword',
    official: 'Skip to the next iteration of a loop.',
    source: STD,
    when: 'Inside a loop, while or for, when you are done with this pass and want to jump straight to the next one, such as skipping a bad sensor reading. In a while loop, make sure whatever moves the loop forward happens before the continue, or it may loop forever.',
    example: { command: 'for r in readings {\n    if r.is_nan() {\n        continue;\n    }\n    total += r;\n}', says: 'Adds up every reading except the missing (NaN) ones.' },
    seeAlso: ['break', 'loop', 'for', 'while'],
  },
  {
    name: 'debug!',
    aliases: ['defmt::debug!'],
    lang: 'rust',
    kind: 'macro',
    official: 'Logs data at debug level.',
    source: 'defmt crate documentation',
    when: 'In embedded code using defmt, for detailed messages you only want while hunting a bug. It ranks below info!, and when DEFMT_LOG is not set only error! messages are kept, so debug! lines are removed from the build. Set DEFMT_LOG=debug and rebuild to see them.',
    example: { command: 'defmt::debug!("filter reset, gain = {}", gain);', says: 'Logs the gain at debug level, shown on your laptop by probe-rs only when the build keeps debug messages.' },
    seeAlso: ['info!', 'warn!', 'error!'],
  },
  {
    name: 'error!',
    aliases: ['defmt::error!'],
    lang: 'rust',
    kind: 'macro',
    official: 'Logs data at error level.',
    source: 'defmt crate documentation',
    when: 'In embedded code using defmt, for something that has gone wrong, like a sensor that stopped answering. It is the highest level, and the only one kept when DEFMT_LOG is not set. It only logs; the program carries on unless you also stop it.',
    example: { command: 'defmt::error!("IMU not responding after {} tries", tries);', says: 'Logs the failure at error level, shown on your laptop by probe-rs.' },
    seeAlso: ['warn!', 'info!', 'debug!'],
  },
  {
    name: 'macro_rules!',
    lang: 'rust',
    kind: 'macro',
    official: 'macro_rules allows users to define syntax extension in a declarative way.',
    source: 'The Rust Reference (Macros By Example)',
    when: 'You want to write your own macro, a pattern that turns into code when you call it with a !, the way println! and vec! work. Each rule has a pattern to match and the code to write out. Reach for a plain function first; use a macro only when a function cannot do the job, such as taking any number of arguments.',
    flags: [
      ['($x:expr) => { ... }', 'one rule: match one expression, call it $x, and write out the code in the braces'],
      ['$( ... ),*', 'repeat the part in brackets for each comma-separated item'],
    ],
    example: { command: 'macro_rules! square {\n    ($x:expr) => { $x * $x };\n}\nlet a = square!(3.0);', says: 'Defines a macro square! and uses it; square!(3.0) turns into 3.0 * 3.0, so a holds 9.0.' },
    seeAlso: ['println!', 'vec!'],
  },
  {
    name: 'panic!',
    lang: 'rust',
    kind: 'macro',
    official: 'Panics the current thread.',
    source: STD,
    when: 'Something has happened that should be impossible and the program cannot sensibly carry on. It stops the thread with your message and runs the cleanup for everything the thread owned. For errors you expect, such as a bad file, return a Result instead so the caller can decide.',
    example: { command: 'if mass_kg <= 0.0 {\n    panic!("mass must be positive, got {mass_kg}");\n}', says: 'Stops the program with the message mass must be positive, got -5 if the mass is not above zero.' },
    seeAlso: ['Result', 'assert!', 'unreachable!', 'todo!'],
  },
  {
    name: 'pin!',
    lang: 'rust',
    kind: 'macro',
    official: 'Constructs a Pin<&mut T>, by pinning a value: T locally.',
    source: STD,
    when: 'You need to poll a future, such as an async block, that is not Unpin: one that must stay at the same place in memory once it starts. pin! pins it on the stack, in the current function. If the pinned value has to outlive this function, use Box::pin to put it on the heap instead.',
    example: { command: 'use std::pin::pin;\nlet fut = pin!(async { read_gyro().await });', says: 'Pins the async block where it is, so fut can be polled and never moves.' },
  },
  {
    name: 'todo!',
    lang: 'rust',
    kind: 'macro',
    official: 'Indicates unfinished code.',
    source: STD,
    when: 'You want code to compile before you have written every part, such as a match arm for a new mode. It type-checks as any type, so it fits anywhere, but if it ever runs it panics with "not yet implemented". Search for it before you ship.',
    example: { command: 'AdcsMode::TargetTracking => todo!(),', says: 'The match compiles, and the program panics with not yet implemented if it ever reaches TargetTracking.' },
    seeAlso: ['unreachable!', 'panic!', 'match'],
  },
  {
    name: 'unreachable!',
    lang: 'rust',
    kind: 'macro',
    official: 'Indicates unreachable code.',
    source: STD,
    when: 'In a branch you are sure can never run, such as the last arm of a match after earlier checks ruled everything out. If you were wrong it panics with "internal error: entered unreachable code", so the bug shows up loudly instead of quietly doing something odd.',
    example: { command: 'match stage % 2 {\n    0 => "even",\n    1 => "odd",\n    _ => unreachable!(),\n}', says: 'Covers the impossible remainders so the match compiles; it panics if it is ever reached.' },
    seeAlso: ['todo!', 'panic!', 'match'],
  },

  /* -------------------------------------------------------------- matlab */
  {
    name: 'try',
    lang: 'matlab',
    kind: 'keyword',
    official: 'Execute statements and catch resulting errors',
    source: 'MATLAB documentation (MathWorks, try, catch)',
    when: 'You want to run code that might fail, such as a simulation or reading a file, and handle the error yourself instead of stopping the script. If any line in the try part errors, MATLAB jumps straight to catch; the lines after the failing one do not run.',
    flags: [['try ... catch ME ... end', 'run the code after try; on an error, run the code after catch with the error in ME']],
    example: { command: 'try\n    out = sim(\'pitch_loop\');\ncatch ME\n    disp(getReport(ME))\nend', says: 'Runs the model, and if it fails, prints the full error report instead of stopping.' },
    seeAlso: ['catch', 'error'],
  },
  {
    name: 'catch',
    lang: 'matlab',
    kind: 'keyword',
    official: 'Execute statements and catch resulting errors',
    source: 'MATLAB documentation (MathWorks, try, catch)',
    when: 'After try, the part that runs only if something in the try part errors. Name the error (catch ME) to read its message and its identifier, such as checkQuat:notUnit, so you can handle one kind of error and pass the rest on with rethrow(ME). A bare catch that ignores the error hides real bugs.',
    flags: [
      ['ME.identifier', 'the error\'s component:reason label, to test which error it was'],
      ['ME.message', 'the error text'],
    ],
    example: { command: 'try\n    checkQuat(q)\ncatch ME\n    if ME.identifier == "checkQuat:notUnit"\n        q = q / norm(q);\n    else\n        rethrow(ME)\n    end\nend', says: 'Fixes a quaternion that is not unit length, and passes any other error on.' },
    seeAlso: ['try', 'error'],
  },
  {
    name: 'global',
    lang: 'matlab',
    kind: 'keyword',
    official: 'Declare variables as global',
    source: MATLAB,
    when: 'It makes one variable shared by every function and workspace that declares it global. That hides what a function depends on and lets any code change the value behind your back, so tests can start depending on the order they run in. Pass values as arguments, or one struct of parameters, instead.',
    example: { command: 'global g0\ng0 = 9.80665;', says: 'Makes g0 a shared global and sets it; any function that also says global g0 now sees and can change the same value.' },
    seeAlso: ['persistent', 'function'],
  },

  /* ----------------------------------------------------------------- cpp */
  {
    name: '<benchmark/benchmark.h>',
    lang: 'cpp',
    kind: 'header',
    official: 'A library to benchmark code snippets, similar to unit tests.',
    source: 'Google Benchmark documentation',
    when: 'You want to time one small function precisely, such as two ways to normalize a quaternion. Only the code inside for (auto _ : state) is timed. The optimizer may delete work whose result nobody uses, and then you time nothing, so pass results to benchmark::DoNotOptimize. Link with -lbenchmark -lpthread.',
    flags: [
      ['benchmark::State&', 'the parameter every benchmark function takes'],
      ['BENCHMARK(name)', 'register a benchmark function'],
      ['BENCHMARK_MAIN()', 'write the main function that runs them all'],
      ['benchmark::DoNotOptimize(x)', 'make the compiler keep the work that produces x'],
      ['benchmark::ClobberMemory()', 'make the compiler finish all writes to memory here'],
    ],
    example: { command: 'static void BM_Norm(benchmark::State& state) {\n    for (auto _ : state) benchmark::DoNotOptimize(norm(q));\n}\nBENCHMARK(BM_Norm);\nBENCHMARK_MAIN();', says: 'Times norm(q) over as many repeats as it needs and prints the time per call.' },
    seeAlso: ['<gtest/gtest.h>'],
  },

  /* -------------------------------------------------------------- python */
  {
    name: 'string',
    lang: 'python',
    kind: 'module',
    official: 'A collection of string constants.',
    source: DOC,
    when: 'You need a ready-made set of characters, such as all the digits or all the capital letters, to check or build text. This is a module you import; a piece of text itself is a str, and its tools are str methods like split and upper.',
    flags: [
      ['string.ascii_uppercase', 'the letters A to Z'],
      ['string.digits', 'the characters 0 to 9'],
    ],
    example: { command: 'import string\nprint(all(c in string.digits for c in "0427"))', says: 'Prints True, because every character of "0427" is a digit.' },
    seeAlso: ['str'],
  },
  {
    name: 'heapq.heapify',
    lang: 'python',
    kind: 'function',
    official: 'Transform list into a heap, in-place, in O(len(heap)) time.',
    source: DOC,
    when: 'You already have a whole list and want to turn it into a heap in one step, which is faster than pushing the items one by one. It changes the list itself and returns None, so do not write heap = heapq.heapify(heap).',
    example: { command: 'heap = [(3.2, "ISS"), (0.8, "Hubble"), (1.5, "Tiangong")]\nheapq.heapify(heap)\nprint(heap[0])', says: 'Rearranges the list into heap order and prints (0.8, \'Hubble\'), the smallest item.' },
    seeAlso: ['heapq.heappush', 'heapq.heappop', 'heapq'],
  },
  {
    name: 'heapq.heapreplace',
    lang: 'python',
    kind: 'function',
    official: 'Pop and return the current smallest value, and add the new item.',
    source: DOC,
    when: 'You keep a heap of a fixed size, such as the k largest values so far, and a better value arrives: it swaps out the smallest in one step, faster than a pop then a push. It pops first, so the value it returns can be bigger than the one you added; check the new item beats heap[0] before you call it.',
    example: { command: 'if v > heap[0]:\n    heapq.heapreplace(heap, v)', says: 'Throws out the weakest of the best values so far and puts v in its place.' },
    seeAlso: ['heapq.heappush', 'heapq.heappop', 'heapq.nlargest'],
  },
  {
    name: 'numpy.full_like',
    aliases: ['np.full_like'],
    lang: 'python',
    kind: 'function',
    official: 'Return a full array with the same shape and type as a given array.',
    source: NP,
    when: 'You want a new array the same shape as one you have, with every entry set to one value, such as NaN for "not measured yet". It also copies the type, so filling an integer array with 2.7 gives 2 everywhere, and filling it with NaN gives a warning and a meaningless huge negative number; pass dtype=float to be safe.',
    flags: [
      ['a', 'the array whose shape and type to copy'],
      ['fill_value', 'the value to put in every entry'],
    ],
    example: { command: 'np.full_like(acc, np.nan).shape', says: 'Makes an array like acc filled with NaN and shows its shape, (2, 3), the same as acc.' },
    seeAlso: ['numpy.full', 'numpy.zeros_like'],
  },
  {
    name: 'numpy.int32',
    aliases: ['np.int32'],
    lang: 'python',
    kind: 'type',
    official: 'Signed integer type, compatible with C int.',
    source: NP,
    when: 'You want whole numbers that take 4 bytes each, to match a C program or a file format, or to save memory. It holds -2,147,483,648 to 2,147,483,647, and going past the top wraps around to the bottom with no error.',
    example: { command: 'print(np.array([2_147_483_647], dtype=np.int32) + 1)', says: 'Prints [-2147483648]: one past the largest value wraps around to the smallest.' },
    seeAlso: ['numpy.int64', 'numpy.int8'],
  },
  {
    name: 'numpy.int8',
    aliases: ['np.int8'],
    lang: 'python',
    kind: 'type',
    official: 'Signed integer type, compatible with C char.',
    source: NP,
    when: 'You want whole numbers that take one byte each, such as a flight-mode flag stored for every sample, to keep a big array small. It only holds -128 to 127, and going past either end wraps around with no error.',
    example: { command: 'mode = np.zeros(n, dtype=np.int8)\nmode[40_000:] = 2', says: 'Makes one byte-sized flag per sample, all 0, then sets the flag to 2 from sample 40,000 on.' },
    seeAlso: ['numpy.uint8', 'numpy.int32'],
  },
  {
    name: 'random.randint',
    lang: 'python',
    kind: 'function',
    official: 'Return random integer in range [a, b], including both end points.',
    source: DOC,
    when: 'You want a random whole number between two limits, such as a random test size or a dice roll. Unlike range, both ends can come up: randint(1, 6) can give 6. Call random.seed first if you need the same numbers every run.',
    flags: [['a, b', 'the smallest and largest numbers it may return']],
    example: { command: 'n = random.randint(1, 8)', says: 'Sets n to a random whole number from 1 to 8, with 1 and 8 both possible.' },
    seeAlso: ['random', 'random.random'],
  },
  {
    name: 'sys.monitoring',
    lang: 'python',
    kind: 'module',
    official: 'This namespace provides access to the functions and constants necessary to activate and control event monitoring.',
    source: 'Python documentation (sys.monitoring, new in 3.12)',
    when: 'Tools such as coverage.py and debuggers use it to be told when each line runs or a function is called, far more cheaply than the older sys.settrace. It lives inside sys: import sys, then use sys.monitoring.',
    flags: [
      ['use_tool_id(id, name)', 'claim one of the tool slots'],
      ['set_events(id, events)', 'choose which events to hear about'],
      ['register_callback(id, event, fn)', 'the function called on each event'],
    ],
    example: { command: 'import sys\nprint(sys.monitoring.COVERAGE_ID)', says: 'Prints 1, the tool slot kept for coverage tools (Python 3.12 or newer).' },
    seeAlso: ['sys'],
  },
  {
    name: 'perf',
    lang: 'shell',
    kind: 'system',
    official: 'Performance analysis tools for Linux',
    source: 'perf manual page (linux-tools-common)',
    when: 'A program is slow and you want to know where the time goes: perf samples the running program and reports which functions the processor was busy in.',
    flags: [
      ['stat', 'count cycles, instructions and cache misses for one run'],
      ['record', 'sample a run and save the profile'],
      ['report', 'show where the saved profile spent its time'],
    ],
    example: { command: 'perf stat ./sim', says: 'Runs ./sim once and prints how many cycles and instructions it took.' },
    seeAlso: ['gdb', 'time'],
  },
  {
    name: 'route',
    lang: 'shell',
    kind: 'system',
    official: 'show / manipulate the IP routing table',
    source: 'route manual page (net-tools)',
    when: 'You meet it in older guides. It was replaced by ip route, which shows the same table, and it is not installed on many new systems.',
    flags: [['-n', 'show numbers, not names']],
    example: { command: 'route -n', says: 'Prints the routing table with numeric addresses. ip route shows the same today.' },
    seeAlso: ['ip', 'ifconfig', 'netstat'],
  },
]
