import type { CommandRef } from './types'

/** Git and its subcommands, then build, packaging and devops tools ORBIT teaches. */
export const COMMANDS: CommandRef[] = [
  // ---------------------------------------------------------------- git
  {
    name: 'git',
    kind: 'git',
    official: 'the stupid content tracker',
    source: 'git manual page',
    when: 'You want to save versions of a project, see what changed, undo mistakes, or share work with a team. You type git, then a word that says what to do, like git status or git commit.',
    flags: [['--version', 'print which version of git is installed']],
    example: { command: 'git status', says: 'Git reports which branch you are on and which files are new, changed, or staged in this repository.' },
    seeAlso: ['git init', 'git status', 'git add', 'git commit', 'git log'],
  },
  {
    name: 'git init',
    kind: 'git',
    official: 'Create an empty Git repository or reinitialize an existing one',
    source: 'git help',
    when: 'You are starting a new project, or have a folder you want git to watch. It makes the hidden .git folder where every saved version will live. Run pwd first so you set up the right folder, not your home folder.',
    flags: [
      ['-b main', 'name the first branch main'],
      ['--bare', 'make a repository with no working files, used as a shared server copy'],
    ],
    example: { command: 'git init rocket', says: 'Turns the rocket folder into a repository and prints "Initialized empty Git repository in /home/you/rocket/.git/". Your files stay where they are.' },
    seeAlso: ['git clone', 'git status'],
  },
  {
    name: 'git status',
    kind: 'git',
    official: 'Show the working tree status',
    source: 'git help',
    when: 'You want to know where you stand before you do anything else: which branch you are on, which files changed, and which are staged for the next commit. It never changes anything, so run it often.',
    flags: [
      ['-s', 'short form: one line per file with a two-letter code (also --short)'],
      ['--porcelain', 'a steady short form meant for scripts to read'],
    ],
    example: { command: 'git status -s', says: 'Prints one line per file, such as " M launch-plan.txt" for a changed file and "?? notes.txt" for a file git is not tracking yet.' },
    seeAlso: ['git add', 'git diff', 'git commit'],
  },
  {
    name: 'git add',
    kind: 'git',
    official: 'Add file contents to the index',
    source: 'git help',
    when: 'You have changes you want in the next commit. Adding copies them into the staging area (the index), the list of what the next commit will hold, so you choose exactly what gets saved.',
    flags: [
      ['.', 'stage every change in this folder and below'],
      ['-A', 'stage every change in the whole repository, deletions included'],
      ['-p', 'go through the changes piece by piece and pick which ones to stage'],
    ],
    example: { command: 'git add launch-plan.txt', says: 'Stages launch-plan.txt. git status now lists it under "Changes to be committed".' },
    seeAlso: ['git status', 'git commit', 'git restore'],
  },
  {
    name: 'git commit',
    kind: 'git',
    official: 'Record changes to the repository',
    source: 'git help',
    when: 'The staged changes make one complete step and you want to save them as a version, with a short message saying why. Rewriting a commit with --amend changes history, so only do it before you push.',
    flags: [
      ['-m', 'write the commit message right on the command line'],
      ['-a', 'stage every change to files git already tracks, then commit (often written -am)'],
      ['--amend', 'replace the last commit with a fixed one'],
      ['--no-edit', 'keep the existing message (with --amend or after a merge)'],
      ['--fixup', 'make a small commit marked to be folded into an earlier one by rebase --autosquash'],
    ],
    example: { command: 'git commit -m "Add launch checklist"', says: 'Saves everything staged as a new commit and prints its short id and message, like "[main 3f9c2a1] Add launch checklist".' },
    seeAlso: ['git add', 'git log', 'git reset'],
  },
  {
    name: 'git log',
    kind: 'git',
    official: 'Show commit logs',
    source: 'git help',
    when: 'You want to read the history: which commits exist, who made them, when, and why. Press q to leave the long view.',
    flags: [
      ['--oneline', 'one short line per commit: its id and message'],
      ['--graph', 'draw the branch and merge lines next to the commits'],
      ['--all', 'show every branch, not just the one you are on'],
      ['-n', 'show only the newest n commits, e.g. -n 3'],
      ['--stat', 'list which files each commit changed'],
      ['-p', 'show the full changes inside each commit'],
      ['-S', 'find commits that added or removed a piece of text'],
      ['--first-parent', 'follow only the main line and skip commits inside merged branches'],
      ['--no-merges', 'leave out merge commits'],
      ['--format', 'choose exactly what each line prints'],
      ['--', 'end of options: the names after it are files, so you see only their history'],
    ],
    example: { command: 'git log --oneline --graph --all', says: 'Prints every branch as a small picture, one line per commit, with lines showing where branches split and merged.' },
    seeAlso: ['git show', 'git diff', 'git reflog', 'git shortlog'],
  },
  {
    name: 'git diff',
    kind: 'git',
    official: 'Show changes between commits, commit and working tree, etc',
    source: 'git help',
    when: 'You want to see exactly which lines changed before you stage or commit them, or compare two commits or branches. Lines starting with + were added and lines starting with - were removed.',
    flags: [
      ['--staged', 'show what is staged for the next commit (same as --cached)'],
      ['--stat', 'just list the changed files and how many lines changed'],
      ['--name-only', 'print only the names of the changed files'],
      ['HEAD', 'compare with the last commit, staged or not'],
    ],
    example: { command: 'git diff --staged', says: 'Shows the changes you have staged, the ones the next commit will save.' },
    seeAlso: ['git status', 'git show', 'git log'],
  },
  {
    name: 'git show',
    kind: 'git',
    official: 'Show various types of objects',
    source: 'git help',
    when: 'You want to look at one commit: its message and the changes it made. Name a commit, a colon and a path to print a file as it was back then.',
    flags: [['--stat', 'list the changed files instead of the full changes']],
    example: { command: 'git show HEAD~1:fan-speed.txt', says: 'Prints fan-speed.txt as it was one commit ago. Nothing in your folder changes.' },
    seeAlso: ['git log', 'git diff', 'git restore'],
  },
  {
    name: 'git switch',
    kind: 'git',
    official: 'Switch branches',
    source: 'git help',
    when: 'You want to move to another branch, or start a new one to try something without touching main. Git refuses if uncommitted changes would be overwritten; commit or stash them first.',
    flags: [
      ['-c', 'create a new branch and switch to it'],
      ['-', 'go back to the branch you were on before'],
      ['--detach', 'look at a single commit without being on any branch'],
    ],
    example: { command: 'git switch -c drag-model', says: 'Makes a new branch called drag-model where you are, and moves you onto it. Prints "Switched to a new branch \'drag-model\'".' },
    seeAlso: ['git branch', 'git checkout', 'git merge'],
  },
  {
    name: 'git branch',
    kind: 'git',
    official: 'List, create, or delete branches',
    source: 'git help',
    when: 'You want to list branches, make one without moving to it, or tidy up branches you have finished. Deleting with -D throws away commits that were never merged.',
    flags: [
      ['-d', 'delete a branch, only if it is already merged'],
      ['-D', 'delete a branch even if its work is not merged'],
      ['-a', 'also list the branches copied from the remote'],
      ['-v', 'show the last commit on each branch'],
      ['-vv', 'also show which remote branch each one tracks, and how far ahead or behind it is'],
      ['--merged', 'list only branches already merged into this one'],
      ['--contains', 'list branches that include a given commit'],
    ],
    example: { command: 'git branch -d drag-model', says: 'Deletes the drag-model branch after it has been merged. The commits stay safe in main.' },
    seeAlso: ['git switch', 'git merge', 'git tag'],
  },
  {
    name: 'git checkout',
    kind: 'git',
    official: 'Switch branches or restore working tree files',
    source: 'git help',
    when: 'You meet it in older guides and scripts: it both switches branches and throws away file changes. Newer git splits those jobs into git switch and git restore. With -- and a file name, your unsaved edits to that file are lost.',
    flags: [
      ['-b', 'create a new branch and switch to it'],
      ['--', 'the names after it are files: put them back as they were in the last commit'],
      ['--ours', 'during a conflict, take our version of the file'],
      ['--theirs', 'during a conflict, take their version of the file'],
    ],
    example: { command: 'git checkout -b new-ending', says: 'Makes a branch called new-ending and moves you onto it, the same as git switch -c new-ending.' },
    seeAlso: ['git switch', 'git restore'],
  },
  {
    name: 'git merge',
    kind: 'git',
    official: 'Join two or more development histories together',
    source: 'git help',
    when: 'A branch is finished and you want its commits in the branch you are on, usually main. If both sides changed the same lines, git stops with a conflict for you to fix.',
    flags: [
      ['--no-ff', 'always make a merge commit, even when git could just slide forward'],
      ['--ff-only', 'only merge if git can slide forward; refuse otherwise'],
      ['--abort', 'give up a merge with conflicts and go back to how things were'],
      ['--no-edit', 'accept the default merge message'],
    ],
    example: { command: 'git merge --no-ff drag-model', says: 'Joins the drag-model branch into the branch you are on and records a merge commit, so the history shows the branch was there.' },
    seeAlso: ['git switch', 'git rebase', 'git merge-base'],
  },
  {
    name: 'git rebase',
    kind: 'git',
    official: 'Reapply commits on top of another base tip',
    source: 'git help',
    when: 'You want your branch to start from the newest main so its history is one straight line, or you want to tidy your own commits before review. It makes brand new commits, so never rebase commits other people already have.',
    flags: [
      ['-i', 'interactive: edit a list to reorder, squash, reword or drop commits'],
      ['--continue', 'carry on after you fixed a conflict'],
      ['--abort', 'stop and put the branch back as it was'],
      ['--skip', 'drop the commit that stopped with a conflict and carry on'],
      ['--autosquash', 'fold fixup commits into the commits they fix'],
      ['--exec', 'run a command, like the tests, after each commit'],
    ],
    example: { command: 'git rebase main', says: 'Replays your branch\'s commits on top of the newest main, one at a time, so your branch looks like it started from there.' },
    seeAlso: ['git merge', 'git pull', 'git reflog', 'git cherry-pick'],
  },
  {
    name: 'git cherry-pick',
    kind: 'git',
    official: 'Apply the changes introduced by some existing commits',
    source: 'git help',
    when: 'You need one particular commit from another branch, like a bug fix, without merging the whole branch. It makes a new copy of that commit on your branch.',
    flags: [
      ['-x', 'add a line to the message saying which commit it was copied from'],
      ['--continue', 'carry on after you fixed a conflict'],
      ['--abort', 'give up and go back to how things were'],
      ['--skip', 'skip the commit that conflicted'],
      ['-m 1', 'when copying a merge commit, compare against its first parent'],
    ],
    example: { command: 'git cherry-pick -x 8491d16', says: 'Copies the change from commit 8491d16 onto your branch as a new commit, and notes the original id in the message.' },
    seeAlso: ['git rebase', 'git revert', 'git log'],
  },
  {
    name: 'git revert',
    kind: 'git',
    official: 'Revert some existing commits',
    source: 'git help',
    when: 'A commit that is already shared turned out to be wrong, and you want to undo it safely. It adds a new commit that does the opposite, so nobody\'s history is rewritten. Name the commit you want to cancel, not the one you want to go back to.',
    flags: [
      ['-m 1', 'undo a merge commit, keeping its first parent\'s side'],
      ['--abort', 'give up a revert that hit a conflict'],
    ],
    example: { command: 'git revert HEAD', says: 'Makes a new commit that undoes the last commit. The bad commit stays in the history, cancelled out.' },
    seeAlso: ['git reset', 'git show', 'git cherry-pick'],
  },
  {
    name: 'git reset',
    kind: 'git',
    official: 'Reset current HEAD to the specified state',
    source: 'git help',
    when: 'You want to move your branch back to an earlier commit, for example to undo commits you have not pushed yet. With --hard it also throws away every uncommitted change in your files, and that cannot be undone.',
    flags: [
      ['--soft', 'move the branch back but keep the changes staged'],
      ['--mixed', 'move the branch back and keep the changes, unstaged (the default)'],
      ['--hard', 'move the branch back and wipe the changes from your files too'],
    ],
    example: { command: 'git reset --soft HEAD~1', says: 'Undoes the last commit but keeps its changes staged, ready to commit again.' },
    seeAlso: ['git revert', 'git restore', 'git reflog'],
  },
  {
    name: 'git restore',
    kind: 'git',
    official: 'Restore working tree files',
    source: 'git help',
    when: 'You want to throw away changes to a file, unstage it, or bring back an older version of it. Restoring a file you edited loses those edits for good, because they were never committed.',
    flags: [
      ['--staged', 'unstage the file but keep your edits in it'],
      ['--source', 'take the file from a given commit, e.g. --source=HEAD~2'],
    ],
    example: { command: 'git restore --staged config.txt', says: 'Takes config.txt out of the staging area. Your edits to it are still in the file.' },
    seeAlso: ['git reset', 'git checkout', 'git show'],
  },
  {
    name: 'git rm',
    kind: 'git',
    official: 'Remove files from the working tree and from the index',
    source: 'git help',
    when: 'You want git to stop tracking a file. Plain git rm deletes the file from your folder too; use --cached to keep it on disk, for example a secrets file you committed by mistake.',
    flags: [
      ['--cached', 'stop tracking the file but keep it in your folder'],
      ['-r', 'remove a folder and everything inside it'],
    ],
    example: { command: 'git rm --cached .env', says: 'Stages the removal of .env from the repository, but the file stays in your folder. Add it to .gitignore so it is not added again.' },
    seeAlso: ['git mv', 'git check-ignore', 'git status'],
  },
  {
    name: 'git mv',
    kind: 'git',
    official: 'Move or rename a file, a directory, or a symlink',
    source: 'git help',
    when: 'You want to rename or move a tracked file and stage that change in one step. Git refuses if a file with the new name already exists.',
    example: { command: 'git mv notes.txt launch-notes.txt', says: 'Renames notes.txt to launch-notes.txt and stages the rename. git status shows "renamed: notes.txt -> launch-notes.txt".' },
    seeAlso: ['git rm', 'git status'],
  },
  {
    name: 'git stash',
    kind: 'git',
    official: 'Stash the changes in a dirty working directory away',
    source: 'git help',
    when: 'You are in the middle of changes and need a clean folder right now, for example to switch branches and fix something else. The stash is a shelf: put the changes away, then bring them back later. drop deletes a stash for good.',
    flags: [
      ['push -m', 'shelve the changes with a note saying what they are'],
      ['-u', 'include new untracked files too'],
      ['list', 'show every stash on the shelf'],
      ['pop', 'bring back the newest stash and remove it from the shelf'],
      ['apply', 'bring back a stash but keep it on the shelf'],
      ['drop', 'delete a stash'],
      ['show -p', 'show the changes inside a stash'],
    ],
    example: { command: 'git stash push -m "half-done countdown"', says: 'Puts your uncommitted changes away and leaves your files matching the last commit. git stash pop brings them back.' },
    seeAlso: ['git switch', 'git status'],
  },
  {
    name: 'git tag',
    kind: 'git',
    official: 'Create, list, delete or verify a tag object signed with GPG',
    source: 'git help',
    when: 'You want a permanent name for one commit, usually a release like v1.0. Unlike a branch, a tag never moves. Tags are not sent by a plain git push.',
    flags: [
      ['-a', 'make an annotated tag, which stores who tagged it, when, and a message'],
      ['-m', 'give the tag message on the command line'],
      ['-l', 'list tags, optionally matching a pattern'],
      ['-d', 'delete a tag'],
      ['--contains', 'list tags that include a given commit'],
      ['--merged', 'list tags reachable from a branch'],
      ['--sort=v:refname', 'sort version numbers in the right order'],
    ],
    example: { command: 'git tag -a v1.0 -m "First launch release"', says: 'Marks the current commit as v1.0 with a message. git push --tags sends it to the server.' },
    seeAlso: ['git describe', 'git push', 'git branch'],
  },
  {
    name: 'git describe',
    kind: 'git',
    official: 'Give an object a human readable name based on an available ref',
    source: 'git help',
    when: 'You want a readable name for the current commit based on the nearest tag, for example to stamp a version number into a build.',
    flags: [['--tags', 'count lightweight tags too, not only annotated ones']],
    example: { command: 'git describe --tags', says: 'Prints something like "v1.4.0-2-g9e1f0aa": two commits after the tag v1.4.0, at commit 9e1f0aa.' },
    seeAlso: ['git tag', 'git log'],
  },
  {
    name: 'git blame',
    kind: 'git',
    official: 'Show what revision and author last modified each line of a file',
    source: 'git help',
    when: 'You are looking at a line and want to know which commit last changed it, who made it, and when, so you can read that commit\'s message and learn why.',
    flags: [
      ['-L', 'only show a range of lines, e.g. -L 5,9'],
      ['-w', 'ignore changes that only moved spaces around'],
      ['--ignore-rev', 'skip a commit, such as a big reformat, and look past it'],
    ],
    example: { command: 'git blame -L 5,9 gravity.py', says: 'Prints lines 5 to 9 of gravity.py, each with the commit id, author and date that last changed it.' },
    seeAlso: ['git annotate', 'git log', 'git show'],
  },
  {
    name: 'git annotate',
    kind: 'git',
    official: 'Annotate file lines with commit information',
    source: 'git help',
    when: 'The same job as git blame, with a slightly different layout: which commit last touched each line of a file.',
    example: { command: 'git annotate gravity.py', says: 'Prints every line of gravity.py next to the commit, author and date that last changed it.' },
    seeAlso: ['git blame'],
  },
  {
    name: 'git bisect',
    kind: 'git',
    official: 'Use binary search to find the commit that introduced a bug',
    source: 'git help',
    when: 'Something worked in an old commit and is broken now, and you do not know which commit broke it. Git checks out the commit halfway between, you say good or bad, and it halves the search each time. Always finish with git bisect reset.',
    flags: [
      ['start', 'begin a search, optionally with the bad and good commits'],
      ['good', 'this commit works'],
      ['bad', 'this commit has the bug'],
      ['skip', 'this commit cannot be tested; pick another'],
      ['run', 'let a script test each commit: exit code 0 means good'],
      ['log', 'show the answers given so far'],
      ['reset', 'end the search and go back to where you started'],
    ],
    example: { command: 'git bisect run python3 check.py', says: 'Git tests commits with check.py by itself and prints "<id> is the first bad commit" when it finds the one that broke things.' },
    seeAlso: ['git log', 'git switch'],
  },
  {
    name: 'git reflog',
    kind: 'git',
    official: 'Manage reflog information',
    source: 'git help',
    when: 'You lost commits after a reset, rebase or deleted branch and want them back. The reflog lists every place HEAD has pointed recently, so you can find the old commit id and point a branch at it.',
    example: { command: 'git reflog', says: 'Lists where HEAD has been, newest first, as HEAD@{0}, HEAD@{1} and so on, with the command that moved it each time.' },
    seeAlso: ['git reset', 'git branch', 'git fsck'],
  },
  {
    name: 'git config',
    kind: 'git',
    official: 'Get and set repository or global options',
    source: 'git help',
    when: 'You are setting git up: your name and email for commits, your editor, or how pull and merge behave. Without --global the setting applies only to this repository.',
    flags: [
      ['--global', 'save the setting for every repository on this computer'],
      ['--unset', 'remove a setting'],
    ],
    example: { command: 'git config --global user.name "Sam Rivera"', says: 'Sets the name stamped on every commit you make on this computer. It prints nothing.' },
    seeAlso: ['git commit', 'git init'],
  },
  {
    name: 'git remote',
    kind: 'git',
    official: 'Manage set of tracked repositories',
    source: 'git help',
    when: 'You want to see or add the other copies of this repository your clone talks to, such as origin, the server copy you push to.',
    flags: [
      ['-v', 'list each remote with its web or file address'],
      ['add', 'give a new remote a short name and an address'],
      ['show', 'print details about one remote and its branches'],
    ],
    example: { command: 'git remote add origin ~/team/server/rocket.git', says: 'Saves that address under the short name origin, so git push origin and git fetch origin know where to go.' },
    seeAlso: ['git fetch', 'git push', 'git clone'],
  },
  {
    name: 'git clone',
    kind: 'git',
    official: 'Clone a repository into a new directory',
    source: 'git help',
    when: 'You want your own full copy of an existing repository, with its whole history, to work on. The source is saved as the remote called origin.',
    flags: [['--recurse-submodules', 'also fetch every submodule the project uses']],
    example: { command: 'git clone server/rocket.git rocket', says: 'Makes a new folder called rocket with all the files and the full history, set up to push back to server/rocket.git.' },
    seeAlso: ['git init', 'git remote', 'git pull'],
  },
  {
    name: 'git fetch',
    kind: 'git',
    official: 'Download objects and refs from another repository',
    source: 'git help',
    when: 'You want to see what teammates pushed without changing your own branches yet. It updates origin/main and the other remote branches; then you can compare, merge or rebase.',
    flags: [
      ['--prune', 'forget remote branches that were deleted on the server'],
      ['--tags', 'fetch all tags too'],
    ],
    example: { command: 'git fetch origin', says: 'Downloads new commits from origin and moves origin/main to match. Your own main is not touched.' },
    seeAlso: ['git pull', 'git push', 'git remote'],
  },
  {
    name: 'git pull',
    kind: 'git',
    official: 'Fetch from and integrate with another repository or a local branch',
    source: 'git help',
    when: 'You want your branch up to date with the server: it fetches, then merges or rebases the new commits into your branch. Commit or stash your changes first.',
    flags: [
      ['--rebase', 'put your local commits on top of the new ones instead of merging'],
      ['--no-rebase', 'merge the new commits in'],
      ['--recurse-submodules', 'also update the submodules'],
    ],
    example: { command: 'git pull --rebase', says: 'Downloads your teammates\' new commits and replays your unpushed commits on top of them, keeping the history in one line.' },
    seeAlso: ['git fetch', 'git merge', 'git rebase', 'git push'],
  },
  {
    name: 'git push',
    kind: 'git',
    official: 'Update remote refs along with associated objects',
    source: 'git help',
    when: 'Your commits are ready to share and you want to send them to the server. Git refuses if the server has commits you do not have; pull first. --force can wipe out other people\'s work, so prefer --force-with-lease.',
    flags: [
      ['-u', 'remember this remote branch, so later a plain git push knows where to go (also --set-upstream)'],
      ['--force-with-lease', 'overwrite the server branch only if nobody else pushed since you last fetched'],
      ['--force', 'overwrite the server branch no matter what'],
      ['--tags', 'send all your tags'],
      ['--follow-tags', 'send annotated tags that point at the commits being pushed'],
    ],
    example: { command: 'git push -u origin main', says: 'Sends your main branch to origin and remembers the link, so from now on plain git push is enough.' },
    seeAlso: ['git pull', 'git fetch', 'git remote', 'git tag'],
  },
  {
    name: 'git ls-files',
    kind: 'git',
    official: 'Show information about files in the index and the working tree',
    source: 'git help',
    when: 'You want the exact list of files git is tracking, or to look inside the index (the staging area) itself.',
    flags: [
      ['-s', 'show each file\'s mode, blob id and stage number'],
      ['-u', 'show only files that are in conflict'],
    ],
    example: { command: 'git ls-files', says: 'Prints the path of every file git tracks in this repository, one per line.' },
    seeAlso: ['git status', 'git cat-file', 'git check-ignore'],
  },
  {
    name: 'git check-ignore',
    kind: 'git',
    official: 'Debug gitignore / exclude files',
    source: 'git help',
    when: 'A file is being ignored, or not ignored, and you want to know which .gitignore line is responsible.',
    flags: [['-v', 'show the file and line number of the rule that matched']],
    example: { command: 'git check-ignore -v sim.log', says: 'Prints something like ".gitignore:3:*.log  sim.log": line 3 of .gitignore is why sim.log is ignored.' },
    seeAlso: ['git ls-files', 'git rm', 'git check-attr'],
  },
  {
    name: 'git check-attr',
    kind: 'git',
    official: 'Display gitattributes information',
    source: 'git help',
    when: 'You want to see which .gitattributes settings apply to a file, such as how it is diffed, merged, or given line endings.',
    flags: [['-a', 'show every attribute set for the file']],
    example: { command: 'git check-attr -a gravity.py', says: 'Lists each attribute that applies to gravity.py, like "gravity.py: text: set".' },
    seeAlso: ['git check-ignore', 'git lfs'],
  },
  {
    name: 'git cat-file',
    kind: 'git',
    official: 'Provide contents or details of repository objects',
    source: 'git help',
    when: 'You want to look inside git\'s storage and see what a commit, tree, blob or tag object really holds. It only reads, so it is safe to explore with.',
    flags: [
      ['-t', 'print what type of object it is'],
      ['-p', 'print the object\'s contents in a readable form'],
    ],
    example: { command: 'git cat-file -p HEAD', says: 'Prints the raw commit: its tree id, parent id, author, committer and message.' },
    seeAlso: ['git hash-object', 'git ls-files', 'git show'],
  },
  {
    name: 'git hash-object',
    kind: 'git',
    official: 'Compute object ID and optionally create an object from a file',
    source: 'git help',
    when: 'You want to see the id (hash) git would give some content. The same content always gets the same id, and changing one character changes it completely.',
    flags: [['--stdin', 'read the content from the pipe instead of a file']],
    example: { command: "printf '# orbit-sim\\n' | git hash-object --stdin", says: 'Prints the 40-character id git would store that text under. It does not save anything.' },
    seeAlso: ['git cat-file'],
  },
  {
    name: 'git submodule',
    kind: 'git',
    official: 'Initialize, update or inspect submodules',
    source: 'git help',
    when: 'Your project uses another repository, such as a library, and you want to keep it in a folder pinned to one exact commit. After a plain clone the submodule folders are empty until you run git submodule update --init.',
    flags: [
      ['add', 'clone a library into a folder and pin it'],
      ['update --init', 'after cloning, fetch each submodule and check out its pinned commit'],
      ['update', 'move each submodule back to the pinned commit'],
      ['update --remote', 'move a submodule to the newest commit of its remote branch'],
      ['status', 'show each pin: a space means matching, - not set up yet, + different from the pin'],
    ],
    example: { command: 'git submodule add ../frames.git extern/frames', says: 'Clones the frames library into extern/frames and stages the pin and the .gitmodules file, ready to commit.' },
    seeAlso: ['git subtree', 'git clone'],
  },
  {
    name: 'git subtree',
    kind: 'git',
    official: 'Merge subtrees together and split repository into subtrees',
    source: 'git-subtree manual page (Git contrib)',
    when: 'You want another project\'s files copied into a folder of yours as ordinary files, so a plain clone just works, while still being able to pull updates later. It is an add-on from Git\'s contrib folder, so check it is installed with git subtree -h.',
    flags: [
      ['--prefix', 'the folder the other project lives in'],
      ['add', 'bring the project in for the first time'],
      ['pull', 'update it to a newer version'],
      ['push', 'send your local fixes back to the project'],
      ['--squash', 'bring it in as one commit instead of its whole history'],
    ],
    example: { command: 'git subtree add --prefix=extern/frames ../frames.git v0.3.0 --squash', says: 'Copies version v0.3.0 of the frames library into extern/frames as one squashed commit plus a merge commit.' },
    seeAlso: ['git submodule'],
  },
  {
    name: 'git lfs',
    kind: 'git',
    official: 'Work with large files in Git repositories',
    source: 'git-lfs manual page',
    when: 'Your project has big binary files, like models or CAD files, that git cannot merge. Git LFS stores them outside the normal history and lets people lock a file so two edits never collide. It is a separate install.',
    flags: [
      ['install', 'set Git LFS up once on your computer'],
      ['track', 'store files matching a pattern with LFS'],
      ['--lockable', 'with track: make those files read-only until you lock them'],
      ['lock', 'claim a file so nobody else edits it'],
      ['unlock', 'release your lock when you are done'],
      ['locks', 'list who holds which lock'],
      ['--force', 'with unlock: break someone else\'s lock (talk to them first)'],
    ],
    example: { command: 'git lfs lock models/attitude.slx', says: 'Claims models/attitude.slx on the server so teammates see it is yours. git lfs locks now lists it with your name.' },
    seeAlso: ['git check-attr', 'git push'],
  },
  {
    name: 'git merge-base',
    kind: 'git',
    official: 'Find as good common ancestors as possible for a merge',
    source: 'git help',
    when: 'You want the newest commit two branches share, the point where they split. A merge compares both branches against it.',
    flags: [['--is-ancestor', 'answer with the exit code: is the first commit inside the second one\'s history?']],
    example: { command: 'git merge-base main drag-model', says: 'Prints the id of the commit where drag-model branched off main.' },
    seeAlso: ['git merge', 'git rebase'],
  },
  {
    name: 'git fsck',
    kind: 'git',
    official: 'Verifies the connectivity and validity of the objects in the database',
    source: 'git help',
    when: 'You want to check that the repository is healthy, or hunt for commits nothing points to any more, such as a dropped stash.',
    flags: [['--lost-found', 'write every unreachable commit into .git/lost-found so you can look at them']],
    example: { command: 'git fsck --lost-found', says: 'Prints lines like "dangling commit 77d2f18" for commits no branch points to, and saves their ids under .git/lost-found.' },
    seeAlso: ['git reflog', 'git gc'],
  },
  {
    name: 'git count-objects',
    kind: 'git',
    official: 'Count unpacked number of objects and their disk consumption',
    source: 'git help',
    when: 'You want to know how big the repository\'s storage has grown, for example after someone committed a large file.',
    flags: [
      ['-v', 'show more detail, including packed objects'],
      ['-H', 'print sizes in readable units like KiB and MiB'],
    ],
    example: { command: 'git count-objects -vH', says: 'Prints how many objects are stored and how much disk space they take, loose and packed.' },
    seeAlso: ['git gc'],
  },
  {
    name: 'git shortlog',
    kind: 'git',
    official: "Summarize 'git log' output",
    source: 'git help',
    when: 'You are writing release notes and want the commits in a range grouped by who wrote them.',
    example: { command: 'git shortlog v1.3.0..v1.4.0', says: 'Lists every author with a count and the message of each commit they made between the two releases.' },
    seeAlso: ['git log', 'git tag'],
  },
  {
    name: 'git rev-parse',
    kind: 'git',
    official: 'Pick out and massage parameters',
    source: 'git help',
    when: 'You want to turn any name for a commit, like HEAD~2, main or a tag, into its actual id. Scripts use it to stamp the exact commit into a build.',
    flags: [['--short', 'print the short form of the id']],
    example: { command: 'git rev-parse --short HEAD', says: 'Prints the short id of the commit you are on, like 3f9c2a1.' },
    seeAlso: ['git describe', 'git log'],
  },
  {
    name: 'git rerere',
    kind: 'git',
    official: 'Reuse recorded resolution of conflicted merges',
    source: 'git help',
    when: 'You keep fixing the same merge conflict again and again. Once rerere.enabled is on, git remembers how you fixed a conflict and applies the same fix next time.',
    flags: [
      ['status', 'list files whose conflict fix is being recorded'],
      ['diff', 'show the fix recorded so far'],
      ['forget', 'throw away a recorded fix that was wrong'],
    ],
    example: { command: 'git rerere status', says: 'Prints the conflicted files git is watching, so it can reuse your fixes later.' },
    seeAlso: ['git merge', 'git rebase', 'git config'],
  },
  {
    name: 'git range-diff',
    kind: 'git',
    official: 'Compare two commit ranges (e.g. two versions of a branch)',
    source: 'git help',
    when: 'Someone reworked their branch after review and force-pushed it, and you want to see only what changed between the old and new versions instead of reading everything again.',
    example: { command: 'git range-diff origin/main old-tip new-tip', says: 'Pairs up the old and new commits of the branch and shows how each one changed: a diff of diffs.' },
    seeAlso: ['git diff', 'git rebase', 'git push'],
  },
  {
    name: 'git gc',
    kind: 'git',
    official: 'Cleanup unnecessary files and optimize the local repository',
    source: 'git help',
    when: 'Git runs this clean-up by itself now and then. It packs objects together and, after a waiting period, deletes objects nothing can reach, which is why lost commits can eventually disappear for good.',
    example: { command: 'git gc', says: 'Packs loose objects into packfiles and cleans away old unreachable ones. Your commits and branches are unchanged.' },
    seeAlso: ['git count-objects', 'git fsck', 'git reflog'],
  },

  // ---------------------------------------------------------------- C and C++ builds
  {
    name: 'make',
    kind: 'build',
    official: 'GNU make utility to maintain groups of programs',
    source: 'make manual page (GNU Make)',
    when: 'Your project has a Makefile and you want to rebuild it. make compares file times and reruns only the steps whose inputs changed. Recipe lines in a Makefile must start with a tab, not spaces.',
    flags: [
      ['-j', 'run several jobs at once, e.g. -j"$(nproc)" for one per processor'],
      ['clean', 'a common target that deletes the built files'],
      ['install', 'a common target that copies the built program into place, often under /usr/local'],
      ['uninstall', 'a common target that removes what install copied'],
    ],
    example: { command: 'make', says: 'Runs the compile and link commands for anything out of date. With nothing changed it prints "make: \'telem_app\' is up to date."' },
    seeAlso: ['cmake', 'g++', 'gcc'],
  },
  {
    name: 'cmake',
    kind: 'build',
    official: 'CMake Command-Line Reference',
    source: 'cmake manual page (CMake)',
    when: 'Your C or C++ project has a CMakeLists.txt. You run cmake twice: once to configure (write the build files into a build folder) and once to build. Keeping the build in its own folder means deleting it never touches your source.',
    flags: [
      ['-S', 'where the source is (the folder with CMakeLists.txt)'],
      ['-B', 'where to put the build folder'],
      ['--build', 'build what is in that folder'],
      ['-D', 'set a setting, e.g. -DCMAKE_BUILD_TYPE=Release'],
      ['-G', 'choose the build tool it writes files for, e.g. -G Ninja'],
      ['--preset', 'use a named set of settings from CMakePresets.json'],
      ['--config', 'pick Debug or Release when building with a multi-config generator'],
      ['--install', 'copy the built files into their install folder'],
      ['-j', 'with --build: run several compile jobs at once'],
    ],
    example: { command: 'cmake -S . -B build && cmake --build build', says: 'Configures the project in this folder into build/, then compiles and links everything in it.' },
    seeAlso: ['ctest', 'make', 'g++'],
  },
  {
    name: 'ctest',
    kind: 'build',
    official: 'CTest Command-Line Reference',
    source: 'ctest manual page (CMake)',
    when: 'You built a CMake project that registers tests, and you want to run them all and see which passed.',
    flags: [
      ['--test-dir', 'the build folder to run tests from'],
      ['--output-on-failure', 'print a failing test\'s output'],
      ['-R', 'run only tests whose name matches a pattern'],
      ['-E', 'skip tests whose name matches a pattern'],
      ['-L', 'run only tests with a label, e.g. -L unit'],
      ['-LE', 'skip tests with a label'],
      ['-N', 'list the tests without running them'],
      ['-j', 'run several tests at once'],
      ['--preset', 'use a named test preset'],
      ['--rerun-failed', 'run only the tests that failed last time'],
    ],
    example: { command: 'ctest --test-dir build --output-on-failure', says: 'Runs every test in build/, prints a line per test, and ends with a summary like "100% tests passed, 0 tests failed out of 12".' },
    seeAlso: ['cmake'],
  },
  {
    name: 'g++',
    kind: 'build',
    official: 'GNU project C and C++ compiler',
    source: 'gcc manual page (GCC)',
    when: 'You want to turn C++ source files into a program you can run. Turn warnings on every time; they catch real bugs. -o overwrites the output file if it already exists.',
    flags: [
      ['-std=c++20', 'which version of the C++ language to use'],
      ['-Wall -Wextra', 'turn on the common warnings'],
      ['-Wpedantic', 'warn about anything outside standard C++'],
      ['-Werror', 'treat every warning as an error'],
      ['-O2', 'optimize the program for speed (-O0 means no optimizing)'],
      ['-g', 'include debug information for gdb'],
      ['-o', 'name the output file'],
      ['-c', 'compile to an object file (.o) without linking'],
      ['-I', 'add a folder to search for headers'],
      ['-l', 'link a library, e.g. -lgtest'],
      ['-fsanitize', 'add run-time checks, e.g. -fsanitize=address,undefined'],
      ['-pthread', 'build with thread support'],
      ['-MMD -MP', 'write dependency files so make knows which headers each file uses'],
      ['-S', 'stop after making assembly code'],
      ['-E', 'stop after the preprocessor and print the result'],
    ],
    example: { command: 'g++ -std=c++20 -Wall -Wextra -O2 orbit.cpp -o orbit', says: 'Compiles orbit.cpp with warnings on and optimization, and writes the program orbit. Run it with ./orbit.' },
    seeAlso: ['clang++', 'gcc', 'make', 'nm', 'gdb'],
  },
  {
    name: 'gcc',
    kind: 'build',
    official: 'GNU project C and C++ compiler',
    source: 'gcc manual page (GCC)',
    when: 'You are compiling C code (files ending in .c). It takes the same flags as g++, which is the same compiler set up for C++.',
    flags: [
      ['-std=c99', 'which version of the C language to use'],
      ['-Wall -Wextra', 'turn on the common warnings'],
      ['-O2', 'optimize for speed'],
      ['-g', 'include debug information'],
      ['-c', 'compile to an object file without linking'],
      ['-o', 'name the output file'],
    ],
    example: { command: 'gcc -std=c99 -Wall -O2 att.c fsw.c -o fsw', says: 'Compiles both C files and links them into one program called fsw.' },
    seeAlso: ['g++', 'make'],
  },
  {
    name: 'clang++',
    kind: 'build',
    official: 'the Clang C, C++, and Objective-C compiler',
    source: 'clang manual page (LLVM)',
    when: 'You want a second C++ compiler, from the LLVM project. It takes the same main flags as g++, and building with both often catches extra bugs.',
    flags: [
      ['-std=c++23', 'which version of C++ to use'],
      ['-Wall -Wextra', 'turn on the common warnings'],
      ['-O2', 'optimize for speed'],
      ['-g', 'include debug information'],
      ['-o', 'name the output file'],
      ['-fsanitize', 'add run-time checks'],
    ],
    example: { command: 'clang++ -std=c++23 -Wall -Wextra -O2 orbit.cpp -o orbit', says: 'Compiles orbit.cpp with Clang and writes the program orbit.' },
    seeAlso: ['g++'],
  },
  {
    name: 'nm',
    kind: 'build',
    official: 'list symbols from object files',
    source: 'nm manual page (GNU binutils)',
    when: 'A link failed with "undefined reference" and you want to see which functions an object file or library defines and which it only uses.',
    flags: [
      ['-C', 'show C++ names readably instead of mangled'],
      ['--defined-only', 'list only what this file provides'],
      ['--undefined-only', 'list only what this file needs from somewhere else'],
    ],
    example: { command: 'nm -C --undefined-only main.o', says: 'Lists the functions main.o calls but does not contain, each marked U, which the linker must find elsewhere.' },
    seeAlso: ['ldd', 'ar', 'g++'],
  },
  {
    name: 'ldd',
    kind: 'build',
    official: 'print shared object dependencies',
    source: 'ldd manual page (Linux man-pages)',
    when: 'You want to know which shared libraries a program needs when it starts, and whether any are missing ("not found").',
    example: { command: 'ldd build/orbit_report', says: 'Lists each shared library the program loads, like libstdc++.so.6, and the file it was found at.' },
    seeAlso: ['nm'],
  },
  {
    name: 'ar',
    kind: 'build',
    official: 'create, modify, and extract from archives',
    source: 'ar manual page (GNU binutils)',
    when: 'You want to bundle object files into a static library (a .a file) that other programs can link against.',
    flags: [
      ['rcs', 'replace or add the files, create the archive if needed, and write an index'],
      ['t', 'list what is inside the archive'],
    ],
    example: { command: 'ar rcs libtelem.a telem.o', says: 'Makes the static library libtelem.a containing telem.o, ready to link with -ltelem.' },
    seeAlso: ['ranlib', 'nm'],
  },
  {
    name: 'ranlib',
    kind: 'build',
    official: 'generate an index to an archive',
    source: 'ranlib manual page (GNU binutils)',
    when: 'You made a static library without an index and the linker needs one to find functions in it quickly. ar with the s option does the same job.',
    example: { command: 'ranlib lib/libhello.a', says: 'Adds a symbol index to libhello.a. It prints nothing.' },
    seeAlso: ['ar'],
  },
  {
    name: 'readelf',
    kind: 'build',
    official: 'display information about ELF files',
    source: 'readelf manual page (GNU binutils)',
    when: 'You want to look at how a compiled Linux program is laid out: its sections and the parts loaded into memory, for example when checking a build for a small flight computer.',
    flags: [
      ['-l', 'show the segments loaded into memory'],
      ['-S', 'show the sections, like .text and .data'],
      ['-W', 'use wide lines instead of cutting them short'],
      ['-n', 'show the notes, such as the build id'],
    ],
    example: { command: 'readelf -SW program', says: 'Prints a table of every section in program with its address and size.' },
    seeAlso: ['objdump', 'nm'],
  },
  {
    name: 'objdump',
    kind: 'build',
    official: 'display information from object files',
    source: 'objdump manual page (GNU binutils)',
    when: 'You want to see the machine instructions the compiler actually produced.',
    flags: [['-d', 'disassemble: show the code as assembly instructions']],
    example: { command: 'objdump -d orbit.o', says: 'Prints each function in orbit.o as a list of assembly instructions with their addresses.' },
    seeAlso: ['readelf', 'nm'],
  },
  {
    name: 'addr2line',
    kind: 'build',
    official: 'Convert addresses into line number/file name pairs.',
    source: 'addr2line --help (GNU binutils)',
    when: 'A crash report gave you a raw code address and you want to know which function and source line it points to.',
    flags: [
      ['-e', 'the program or object file to look in'],
      ['-f', 'also print the function name'],
      ['-C', 'show C++ names readably'],
      ['-s', 'print only the file name, not the whole path'],
    ],
    example: { command: 'addr2line -e sim_crash -f -C 0x1a2f', says: 'Prints the function name and the file:line that address 0x1a2f belongs to.' },
    seeAlso: ['gdb', 'nm'],
  },
  {
    name: 'gdb',
    kind: 'build',
    official: 'The GNU Debugger',
    source: 'gdb manual page (GDB)',
    when: 'Your program crashes or gives wrong answers and you want to stop it at a line, step through it, and look at variables. Build with -g first so gdb can show source lines.',
    flags: [
      ['-q', 'start quietly, without the welcome text'],
      ['-p', 'attach to a program that is already running, by its process id'],
      ['--args', 'pass the rest of the line as the program and its arguments'],
      ['-batch', 'run the given commands and quit'],
      ['-ex', 'run one gdb command at start, e.g. -ex bt'],
      ['-tui', 'show the source code in a window above the prompt'],
    ],
    example: { command: 'gdb -q ./orbit', says: 'Loads the orbit program and waits at the (gdb) prompt. Type run to start it and bt to see where it crashed.' },
    seeAlso: ['g++', 'valgrind', 'addr2line'],
  },
  {
    name: 'valgrind',
    kind: 'build',
    official: 'a suite of tools for debugging and profiling programs',
    source: 'valgrind manual page (Valgrind)',
    when: 'You suspect memory bugs, like reading memory that was never set or forgetting to free it, or you want to measure memory and cache use. The program runs much slower under it.',
    flags: [
      ['--tool', 'pick the tool: memcheck (default), massif for memory use, cachegrind for cache use'],
      ['--leak-check=full', 'report every memory leak in detail'],
      ['--track-origins=yes', 'show where a value that was never set came from'],
      ['-q', 'print only the errors'],
    ],
    example: { command: 'valgrind --leak-check=full ./orbit', says: 'Runs orbit and reports any bad memory reads and any memory it never freed, with the source lines.' },
    seeAlso: ['gdb', 'g++'],
  },
  {
    name: 'ccache',
    kind: 'build',
    official: 'a fast C/C++ compiler cache',
    source: 'ccache manual page',
    when: 'You rebuild the same C++ code often, for example in CI, and want repeat compiles to come from a saved copy instead of running the compiler again.',
    flags: [
      ['-s', 'show how many compiles were cache hits and misses (also --show-stats)'],
      ['-z', 'reset those counts to zero'],
    ],
    example: { command: 'ccache -s', says: 'Prints the cache statistics: hits, misses, and how full the cache folder is.' },
    seeAlso: ['cmake', 'g++'],
  },

  // ---------------------------------------------------------------- Python
  {
    name: 'python3',
    aliases: ['python'],
    kind: 'build',
    official: 'an interpreted, interactive, object-oriented programming language',
    source: 'python manual page',
    when: 'You want to run a Python program or start the Python prompt. With -m it runs a tool that lives inside Python, like pip, venv or pytest, using that exact Python.',
    flags: [
      ['-m', 'run a module as a program, e.g. python3 -m venv .venv'],
      ['-c', 'run a short piece of code given on the command line'],
      ['--version', 'print which Python this is'],
    ],
    example: { command: 'python3 -m venv .venv', says: 'Makes a virtual environment in .venv: a private Python folder where this project\'s packages go.' },
    seeAlso: ['pip', 'pytest', 'uv'],
  },
  {
    name: 'pip',
    kind: 'build',
    official: 'The PyPA recommended tool for installing Python packages.',
    source: 'pip package summary',
    when: 'You need a Python package, like numpy, for your project. Activate the project\'s virtual environment first so packages do not land in the system Python.',
    flags: [
      ['install', 'download and install packages'],
      ['-r', 'install every package listed in a requirements file'],
      ['-e', 'install your own project in editable mode, so code edits take effect without reinstalling'],
      ['freeze', 'print every installed package with its exact version'],
      ['list', 'list installed packages'],
      ['--no-cache-dir', 'do not keep downloaded files, which keeps Docker images small'],
      ['--require-hashes', 'refuse any file whose fingerprint does not match the one written down'],
    ],
    example: { command: 'pip install -r requirements.txt', says: 'Installs every package listed in requirements.txt, at the versions it names, into the active environment.' },
    seeAlso: ['python3', 'uv', 'conda', 'twine'],
  },
  {
    name: 'pytest',
    kind: 'build',
    official: 'pytest: simple powerful testing with Python',
    source: 'pytest package summary',
    when: 'You wrote test functions (names starting with test_) and want to run them all and see which pass.',
    flags: [
      ['-q', 'quiet: print less, just dots and a summary'],
      ['-v', 'verbose: one line per test'],
      ['-k', 'run only tests whose name matches an expression'],
      ['-m', 'run only tests with a marker, e.g. -m "not slow"'],
      ['-x', 'stop at the first failure'],
      ['--lf', 'rerun only the tests that failed last time'],
      ['-s', 'show print output instead of hiding it'],
      ['--cov', 'measure which lines the tests ran (needs pytest-cov)'],
      ['--doctest-modules', 'also run the examples written in docstrings'],
    ],
    example: { command: 'pytest -q tests/test_apogee.py', says: 'Runs the tests in that file and ends with a line like "5 passed in 0.12s".' },
    seeAlso: ['python3', 'mypy', 'ruff'],
  },
  {
    name: 'mypy',
    kind: 'build',
    official: 'Mypy is a program that will type check your Python code.',
    source: 'mypy --help',
    when: 'You added type hints to Python code and want a tool to check them before the program runs, catching things like passing text where a number belongs.',
    flags: [
      ['--strict', 'turn on every strict check'],
      ['--check-untyped-defs', 'also check inside functions that have no type hints'],
    ],
    example: { command: 'mypy stages.py', says: 'Checks stages.py and prints each type error with its line, or "Success: no issues found in 1 source file".' },
    seeAlso: ['ruff', 'pytest'],
  },
  {
    name: 'ruff',
    kind: 'build',
    official: 'Ruff: An extremely fast Python linter and code formatter.',
    source: 'ruff --help',
    when: 'You want a quick check of Python code for likely bugs and messy style, and to fix the simple ones automatically.',
    flags: [
      ['check', 'look for problems'],
      ['--fix', 'fix the problems that are safe to fix by itself'],
    ],
    example: { command: 'ruff check --fix nav.py', says: 'Checks nav.py, fixes what it safely can, and lists the rest with a rule code and line number.' },
    seeAlso: ['black', 'mypy', 'shellcheck'],
  },
  {
    name: 'black',
    kind: 'build',
    official: 'The uncompromising code formatter.',
    source: 'black --help',
    when: 'You want Python code laid out in one standard style so nobody argues about spacing. It rewrites the files you give it.',
    flags: [
      ['--check', 'only report which files would change; change nothing'],
      ['--diff', 'show the changes it would make'],
    ],
    example: { command: 'black --check src', says: 'Reports which files in src are not formatted and exits with an error code if any are, without editing them.' },
    seeAlso: ['ruff'],
  },
  {
    name: 'uv',
    kind: 'build',
    official: 'An extremely fast Python package manager.',
    source: 'uv --help',
    when: 'You want one fast tool to make virtual environments, lock exact package versions, and install them the same way on every machine.',
    flags: [
      ['lock', 'work out and write the exact versions to uv.lock'],
      ['sync', 'make the environment match the lock file'],
      ['--locked', 'fail if the lock file is out of date instead of changing it'],
      ['run', 'run a command inside the project environment'],
      ['venv', 'make a virtual environment'],
      ['pip compile', 'turn a list of wanted packages into pinned versions'],
      ['--generate-hashes', 'write each file\'s fingerprint into the pinned list'],
    ],
    example: { command: 'uv sync --locked', says: 'Installs exactly the versions in uv.lock into .venv, and stops with an error if the lock file does not match pyproject.toml.' },
    seeAlso: ['pip', 'python3', 'conda'],
  },
  {
    name: 'conda',
    kind: 'build',
    official: 'conda is a tool for managing and deploying applications, environments and packages.',
    source: 'conda --help',
    when: 'You need an environment that includes things pip cannot install, like a particular Python version or compiled science libraries.',
    flags: [
      ['create -n', 'make a new named environment'],
      ['activate', 'start using an environment'],
      ['env export', 'write the environment\'s packages to a file'],
    ],
    example: { command: 'conda create -n traj python=3.11', says: 'Makes an environment called traj with Python 3.11. conda activate traj switches to it.' },
    seeAlso: ['pip', 'uv'],
  },
  {
    name: 'twine',
    kind: 'build',
    official: 'Collection of utilities for publishing packages on PyPI',
    source: 'twine package summary',
    when: 'You built your Python package and want to check it and upload it to a package index. An index never lets you upload the same version number twice, so try TestPyPI first.',
    flags: [
      ['check', 'make sure the package files and description are valid'],
      ['upload', 'send the files to the index'],
      ['--repository', 'pick which index to upload to, e.g. testpypi'],
    ],
    example: { command: 'twine check dist/*', says: 'Checks every file in dist/ and prints PASSED or what is wrong with each one.' },
    seeAlso: ['pip'],
  },

  // ---------------------------------------------------------------- JavaScript
  {
    name: 'npm',
    kind: 'build',
    official: 'javascript package manager',
    source: 'npm manual page',
    when: 'You are in a JavaScript project with a package.json and want to install its packages or run one of its scripts.',
    flags: [
      ['install', 'install the packages listed in package.json'],
      ['test', 'run the project\'s test script'],
      ['run', 'run a named script from package.json'],
    ],
    example: { command: 'npm run build', says: 'Runs the "build" script written in package.json.' },
    seeAlso: ['npx'],
  },
  {
    name: 'npx',
    kind: 'build',
    official: 'Run a command from a local or remote npm package',
    source: 'npx --help',
    when: 'You want to run a tool that comes in an npm package, either one the project installed or one fetched just for this run.',
    flags: [['-y', 'do not ask before downloading a package that is not installed']],
    example: { command: 'npx vitest run src/curriculum/lessons.test.ts', says: 'Runs the project\'s own copy of vitest on that one test file and prints the results.' },
    seeAlso: ['npm'],
  },

  // ---------------------------------------------------------------- Rust
  {
    name: 'cargo',
    kind: 'build',
    official: "Rust's package manager",
    source: 'cargo --help',
    when: 'You are working on a Rust project. Cargo makes new projects, fetches libraries, builds, runs, tests and documents your code, all from Cargo.toml.',
    flags: [
      ['check', 'check the code for errors without building a program'],
      ['doc', 'build the documentation (--open shows it in a browser)'],
      ['add', 'add a library to Cargo.toml'],
      ['fmt', 'format the code in the standard style'],
      ['bench', 'run the benchmarks'],
      ['--locked', 'fail if Cargo.lock would need to change'],
    ],
    example: { command: 'cargo check', says: 'Checks the whole project for errors quickly, without making a program you can run.' },
    seeAlso: ['cargo build', 'cargo run', 'cargo test', 'cargo new', 'cargo clippy', 'rustup', 'rustc'],
  },
  {
    name: 'cargo build',
    kind: 'build',
    official: 'Compile a local package and all of its dependencies',
    source: 'cargo --list',
    when: 'You want to compile your Rust project into a program without running it. Without --release the program is built fast but runs slower.',
    flags: [
      ['--release', 'build with optimizations into target/release'],
      ['--target', 'build for another kind of computer, e.g. thumbv7em-none-eabihf'],
      ['--locked', 'fail if Cargo.lock would need to change'],
    ],
    example: { command: 'cargo build --release', says: 'Compiles the project with optimizations and writes the program into target/release/.' },
    seeAlso: ['cargo run', 'cargo test', 'rustup'],
  },
  {
    name: 'cargo test',
    kind: 'build',
    official: 'Execute all unit and integration tests and build examples of a local package',
    source: 'cargo --list',
    when: 'You wrote #[test] functions and want to build and run them all.',
    flags: [
      ['--', 'the options after it go to the test program, not to cargo'],
      ['--nocapture', 'after --: show println! output from the tests'],
      ['--ignored', 'after --: run only the tests marked #[ignore]'],
      ['--locked', 'fail if Cargo.lock would need to change'],
    ],
    example: { command: 'cargo test', says: 'Builds the project and runs every test, ending with a line like "test result: ok. 6 passed; 0 failed".' },
    seeAlso: ['cargo build', 'cargo clippy'],
  },
  {
    name: 'cargo run',
    kind: 'build',
    official: 'Run a binary or example of the local package',
    source: 'cargo --list',
    when: 'You want to build your Rust program if needed and run it straight away.',
    flags: [
      ['--release', 'build and run the optimized version'],
      ['--', 'the arguments after it go to your program'],
    ],
    example: { command: 'cargo run --release', says: 'Builds the optimized program if anything changed, then runs it and shows its output.' },
    seeAlso: ['cargo build', 'cargo new'],
  },
  {
    name: 'cargo new',
    kind: 'build',
    official: 'Create a new cargo package at <path>',
    source: 'cargo --list',
    when: 'You are starting a new Rust project. It makes the folder with Cargo.toml, a src folder and a git repository.',
    flags: [['--lib', 'make a library instead of a program']],
    example: { command: 'cargo new hello_orbit', says: 'Makes the folder hello_orbit with Cargo.toml and src/main.rs, which already prints "Hello, world!".' },
    seeAlso: ['cargo run', 'cargo build'],
  },
  {
    name: 'cargo clippy',
    kind: 'build',
    official: 'Checks a package to catch common mistakes and improve your Rust code.',
    source: 'cargo --list',
    when: 'Your Rust code compiles, and you want a stricter check that points out common mistakes and clumsy code.',
    flags: [
      ['-- -D warnings', 'treat every warning as an error, as CI usually does'],
      ['-- -W clippy::pedantic', 'turn on the extra-picky checks too'],
    ],
    example: { command: 'cargo clippy -- -D warnings', says: 'Checks the project and fails if Clippy finds anything, listing each problem with a suggested fix.' },
    seeAlso: ['cargo test', 'cargo build'],
  },
  {
    name: 'rustup',
    kind: 'build',
    official: 'The Rust toolchain installer',
    source: 'rustup --help',
    when: 'You want to install, update or switch Rust versions, or add support for building for another kind of computer.',
    flags: [
      ['show', 'print which toolchains are installed and which is active'],
      ['update', 'bring every installed toolchain up to date'],
      ['toolchain install', 'install a toolchain, e.g. nightly'],
      ['target add', 'add a build target, like a small ARM flight computer'],
      ['component add', 'add a tool, e.g. clippy or rustfmt'],
    ],
    example: { command: 'rustup target add thumbv7em-none-eabihf', says: 'Downloads what Rust needs to build for that ARM chip. Then cargo build --target thumbv7em-none-eabihf works.' },
    seeAlso: ['cargo', 'rustc'],
  },
  {
    name: 'rustc',
    kind: 'build',
    official: 'The Rust compiler',
    source: 'rustc manual page',
    when: 'You usually let cargo call it for you. You run it yourself to read a longer explanation of an error code, or to ask what it supports.',
    flags: [
      ['--explain', 'print a longer explanation of an error code, e.g. E0382'],
      ['--print', 'print information, e.g. target-list or cfg'],
      ['-O', 'optimize the program'],
      ['--edition', 'which edition of Rust to use'],
    ],
    example: { command: 'rustc --explain E0382', says: 'Prints what the "use of moved value" error means, with a small example and how to fix it.' },
    seeAlso: ['cargo', 'rustup'],
  },

  // ---------------------------------------------------------------- containers
  {
    name: 'docker',
    kind: 'build',
    official: 'A self-sufficient runtime for containers',
    source: 'docker CLI help',
    when: 'You want to package a program with everything it needs into an image, and run it the same way on any machine as a container. You type docker, then a word for what to do.',
    flags: [['--version', 'print which version of Docker is installed']],
    example: { command: 'docker run --rm python:3.12-slim python3 --version', says: 'Starts a throwaway container from the python:3.12-slim image, prints its Python version, and removes the container.' },
    seeAlso: ['docker run', 'docker build', 'docker compose', 'podman'],
  },
  {
    name: 'docker run',
    kind: 'build',
    official: 'Create and run a new container from an image',
    source: 'docker CLI help',
    when: 'You have an image and want to start a program from it in a fresh container. Files written inside the container vanish with it unless you mount a folder or volume with -v.',
    flags: [
      ['--rm', 'delete the container when it stops'],
      ['-d', 'run it in the background'],
      ['--name', 'give the container a name'],
      ['-p', 'connect a port on your computer to one in the container, e.g. -p 8080:80'],
      ['-v', 'mount a folder or volume into the container, e.g. -v "$PWD/results:/out"'],
      ['--entrypoint', 'run a different program than the image normally runs'],
      ['--user', 'run as a given user id instead of the default'],
      ['--network', 'join a named network'],
    ],
    example: { command: 'docker run --rm -v "$PWD/results:/out" landing-mc:1.0.0', says: 'Runs the landing-mc image in a throwaway container, with your results folder showing up inside it as /out.' },
    seeAlso: ['docker build', 'docker ps', 'docker exec', 'docker volume'],
  },
  {
    name: 'docker build',
    kind: 'build',
    official: 'Start a build',
    source: 'docker CLI help',
    when: 'You wrote a Dockerfile and want to turn it into an image. Each step becomes a saved layer, so rebuilds only redo the steps after a change.',
    flags: [
      ['-t', 'name and tag the image, e.g. -t apogee:0.1.0'],
      ['--build-arg', 'pass a value to an ARG line in the Dockerfile'],
      ['--target', 'stop at a named stage of a multi-stage build'],
      ['--no-cache', 'redo every step instead of reusing saved layers'],
    ],
    example: { command: 'docker build -t landing-mc:1.0.0 .', says: 'Builds an image from the Dockerfile in this folder and names it landing-mc:1.0.0.' },
    seeAlso: ['docker run', 'docker tag', 'docker history'],
  },
  {
    name: 'docker compose',
    kind: 'build',
    official: 'Define and run multi-container applications with Docker',
    source: 'docker CLI help',
    when: 'Your setup needs several containers that work together, like a simulation, a database and a dashboard, described in one compose.yaml. down -v also deletes the volumes, and the data in them.',
    flags: [
      ['up', 'create and start every service'],
      ['-d', 'with up: run in the background'],
      ['down', 'stop and remove the containers and network'],
      ['-v', 'with down: also delete the volumes'],
      ['-p', 'give the project a name'],
      ['exec', 'run a command inside a running service'],
      ['logs', 'show a service\'s output'],
      ['ps', 'list the project\'s containers'],
    ],
    example: { command: 'docker compose -p flightlog up -d', says: 'Starts every service in compose.yaml in the background, as a project named flightlog.' },
    seeAlso: ['docker run', 'docker volume'],
  },
  {
    name: 'docker tag',
    kind: 'build',
    official: 'Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE',
    source: 'docker CLI help',
    when: 'You want to give an image another name, usually the full registry address, before you push it.',
    example: { command: 'docker tag landing-mc:1.0.0 localhost:5000/gnc/landing-mc:1.0.0', says: 'Adds a second name to the same image, ready to push to the registry at localhost:5000. Nothing is copied.' },
    seeAlso: ['docker push', 'docker build'],
  },
  {
    name: 'docker push',
    kind: 'build',
    official: 'Upload an image to a registry',
    source: 'docker CLI help',
    when: 'You want to share an image by sending it to a registry, so other machines can pull it. Pushing the same tag again replaces what others get under that name.',
    example: { command: 'docker push localhost:5000/gnc/landing-mc:1.0.0', says: 'Uploads the image\'s layers to the registry and prints its digest, the fingerprint that names this exact image.' },
    seeAlso: ['docker tag', 'docker pull'],
  },
  {
    name: 'docker pull',
    kind: 'build',
    official: 'Download an image from a registry',
    source: 'docker CLI help',
    when: 'You want an image on your machine before you run it, or want to fetch the newest version of a tag.',
    example: { command: 'docker pull debian:bookworm-slim', says: 'Downloads the debian:bookworm-slim image layer by layer and prints its digest.' },
    seeAlso: ['docker push', 'docker run'],
  },
  {
    name: 'docker volume',
    kind: 'build',
    official: 'Manage volumes',
    source: 'docker CLI help',
    when: 'You want data that outlives any one container, like a database or a cache. docker volume rm deletes the data for good.',
    flags: [
      ['create', 'make a new volume'],
      ['ls', 'list volumes'],
      ['inspect', 'show where a volume lives and its details'],
      ['rm', 'delete a volume'],
    ],
    example: { command: 'docker volume create simcache', says: 'Makes a volume named simcache. Mount it with docker run -v simcache:/cache.' },
    seeAlso: ['docker run', 'docker compose'],
  },
  {
    name: 'docker ps',
    kind: 'build',
    official: 'List containers',
    source: 'docker CLI help',
    when: 'You want to see which containers are running, their names, and their ports.',
    flags: [
      ['-a', 'include containers that have stopped'],
      ['-s', 'show how much disk each container has written'],
    ],
    example: { command: 'docker ps -a', says: 'Lists every container, running or stopped, with its id, image, status and name.' },
    seeAlso: ['docker run', 'docker rm', 'docker exec'],
  },
  {
    name: 'docker exec',
    kind: 'build',
    official: 'Execute a command in a running container',
    source: 'docker CLI help',
    when: 'A container is already running and you want to run another command inside it, for example to look around or check a file.',
    example: { command: 'docker exec sleeper cat /proc/1/comm', says: 'Runs cat inside the running container named sleeper and prints the name of its main program.' },
    seeAlso: ['docker run', 'docker ps'],
  },
  {
    name: 'docker rm',
    kind: 'build',
    official: 'Remove one or more containers',
    source: 'docker CLI help',
    when: 'You are done with a stopped container and want it gone. Anything written inside it that was not in a volume is deleted with it.',
    example: { command: 'docker rm probe', says: 'Deletes the stopped container named probe and prints its name.' },
    seeAlso: ['docker ps', 'docker run'],
  },
  {
    name: 'docker history',
    kind: 'build',
    official: 'Show the history of an image',
    source: 'docker CLI help',
    when: 'You want to see the layers an image is made of, which Dockerfile step made each one, and how big each is.',
    flags: [['--no-trunc', 'show the full commands instead of cutting them short']],
    example: { command: 'docker history apogee:0.1.0', says: 'Lists each layer of the image, newest first, with its size and the step that created it.' },
    seeAlso: ['docker build'],
  },
  {
    name: 'podman',
    kind: 'build',
    official: 'Simple management tool for pods, containers and images',
    source: 'podman manual page',
    when: 'You want to run containers without Docker\'s background service. Its commands copy Docker\'s, so podman run works like docker run.',
    flags: [
      ['run', 'start a container, as with docker run'],
      ['--rm', 'with run: delete the container when it stops'],
      ['--version', 'print which version is installed'],
    ],
    example: { command: 'podman run --rm docker.io/library/debian:bookworm-slim cat /etc/os-release', says: 'Runs a throwaway Debian container and prints which system it is, with no Docker service involved.' },
    seeAlso: ['docker', 'docker run'],
  },
  {
    name: 'kubectl',
    kind: 'build',
    official: 'kubectl controls the Kubernetes cluster manager.',
    source: 'kubectl CLI help',
    when: 'You need to see or change what is running on a Kubernetes cluster: a group of machines that runs containers and restarts them when they fail.',
    flags: [
      ['get pods', 'list the running pods'],
      ['-l', 'only show things with a given label, e.g. -l app=telemetry-decoder'],
      ['describe', 'show details and recent events for one thing'],
      ['logs', 'show a pod\'s printed output'],
    ],
    example: { command: 'kubectl get pods -l app=telemetry-decoder', says: 'Lists the pods with that label, with their status and how many times each has restarted.' },
    seeAlso: ['kubectl apply', 'kubectl rollout', 'docker'],
  },
  {
    name: 'kubectl apply',
    kind: 'build',
    official: 'Apply a configuration to a resource by file name or stdin.',
    source: 'kubectl CLI help',
    when: 'You wrote or changed a YAML file describing what should run, and want the cluster to match it. It changes the live cluster, so check first with --dry-run=server.',
    flags: [
      ['-f', 'the file to apply'],
      ['--dry-run=server', 'have the cluster check the file without changing anything'],
    ],
    example: { command: 'kubectl apply -f telemetry.yaml', says: 'Makes the cluster match telemetry.yaml and prints a line like "deployment.apps/telemetry-decoder configured".' },
    seeAlso: ['kubectl', 'kubectl rollout'],
  },
  {
    name: 'kubectl rollout',
    kind: 'build',
    official: 'Manage the rollout of one or many resources.',
    source: 'kubectl CLI help',
    when: 'You changed a deployment and want to watch the new version replace the old one, or roll back if it is broken.',
    flags: [
      ['status', 'watch the update until it finishes or fails'],
      ['undo', 'go back to the previous version'],
    ],
    example: { command: 'kubectl rollout undo deployment/telemetry-decoder', says: 'Rolls the deployment back to its previous version, replacing the new pods with old ones a few at a time.' },
    seeAlso: ['kubectl apply', 'kubectl'],
  },

  // ---------------------------------------------------------------- system packages
  {
    name: 'apt-get',
    kind: 'build',
    official: 'APT package handling utility -- command-line interface',
    source: 'apt-get manual page (APT)',
    when: 'You want to install or remove software on Debian or Ubuntu from a script or a Dockerfile, where output must stay the same between versions. It needs sudo. purge also deletes the program\'s settings.',
    flags: [
      ['update', 'refresh the list of available packages'],
      ['install', 'install packages'],
      ['-y', 'answer yes to every question, for scripts'],
      ['--dry-run', 'show what would happen without doing it'],
      ['purge', 'remove a package and its settings files'],
      ['autoremove', 'remove packages nothing needs any more'],
    ],
    example: { command: 'apt-get install -y ninja-build', says: 'Installs the Ninja build tool and anything it depends on, without stopping to ask. Run it as root, or put sudo in front.' },
    seeAlso: ['apt', 'dpkg'],
  },
  {
    name: 'apt',
    kind: 'build',
    official: 'command-line interface',
    source: 'apt manual page (APT)',
    when: 'You are typing by hand on Debian or Ubuntu and want to search, install or update software, with friendlier output than apt-get. Use apt-get in scripts.',
    flags: [
      ['update', 'refresh the list of available packages'],
      ['upgrade', 'install newer versions of everything installed'],
      ['install', 'install a package'],
      ['remove', 'remove a package'],
      ['search', 'find packages by a word'],
      ['show', 'print details about a package'],
      ['list --installed', 'list what is installed'],
    ],
    example: { command: 'apt search doxygen', says: 'Lists packages whose name or description mentions doxygen, each with a one-line summary.' },
    seeAlso: ['apt-get', 'dpkg'],
  },
  {
    name: 'dpkg',
    kind: 'build',
    official: 'package manager for Debian',
    source: 'dpkg manual page',
    when: 'You want to ask which package a file came from, or which files a package installed.',
    flags: [
      ['-S', 'find which package owns a file'],
      ['-L', 'list the files a package installed'],
      ['-l', 'list installed packages and their versions'],
    ],
    example: { command: 'dpkg -S /usr/bin/rsync', says: 'Prints "rsync: /usr/bin/rsync": the rsync package put that file there.' },
    seeAlso: ['apt-get', 'apt'],
  },
  {
    name: 'nix-shell',
    kind: 'build',
    official: 'start an interactive shell based on a Nix expression',
    source: 'nix-shell manual page (Nix)',
    when: 'You want a shell with exact versions of some tools, without installing them on your whole system. Leave the shell and they are gone from your PATH.',
    flags: [
      ['-p', 'the packages to put in the shell'],
      ['--run', 'run one command in that shell and exit'],
    ],
    example: { command: "nix-shell -p hello --run 'hello'", says: 'Fetches the hello package, runs it once, and prints "Hello, world!". Your system is left unchanged.' },
    seeAlso: ['conda', 'docker'],
  },
  {
    name: 'shellcheck',
    kind: 'build',
    official: 'Shell script analysis tool',
    source: 'shellcheck manual page',
    when: 'You wrote a bash script and want it checked for common bugs, like a missing pair of quotes, before it runs on real files.',
    flags: [
      ['-S', 'only report problems of at least this level, e.g. -S error'],
      ['-f', 'choose the output format, e.g. gcc or json'],
      ['-x', 'also follow files the script loads with source'],
    ],
    example: { command: 'shellcheck bin/launch.sh', says: 'Prints each problem in bin/launch.sh with its line, a code like SC2086, and how to fix it, or nothing if the script is clean.' },
    seeAlso: ['ruff'],
  },
]
