import type { CommandRef } from './types'

export const COMMANDS: CommandRef[] = [
  // ---------------------------------------------------------------- keywords
  {
    name: 'end',
    lang: 'matlab',
    kind: 'keyword',
    official: 'Terminate block of code or indicate last array index',
    source: 'MATLAB documentation (MathWorks)',
    when: 'It has two jobs. It closes every if, for, while, switch, try, function and classdef block, and inside round brackets it means "the last position", so x(end) is the last element. A missing end makes MATLAB wait for more input or complain about the whole file.',
    flags: [
      ['x(end)', 'the last element of x'],
      ['x(end+1) = v', 'add v as a new element on the end (the array grows by one)'],
      ['X(end, 1)', 'the last row, first column'],
    ],
    example: { command: 'alt = [0 120 480 1100];\nalt(end)', says: 'Shows ans = 1100, the last altitude in the list.' },
    seeAlso: ['if', 'for', 'while', 'function'],
  },
  {
    name: 'function',
    lang: 'matlab',
    kind: 'keyword',
    official: 'Declare function name, inputs, and outputs',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want a named, reusable piece of code with its own inputs and outputs. The file name must match the first function in the file, and the variables inside it live in their own workspace, so they do not see or change your script\'s variables.',
    flags: [
      ['function y = f(x)', 'one output y, one input x'],
      ['function [a, b] = f(x, y)', 'several outputs in square brackets'],
      ['function f(x)', 'no output at all'],
      ['[~, b] = f(...)', 'the caller can skip an output it does not want with a tilde'],
    ],
    example: {
      command: 'function tw = thrustToWeight(thrust, mass)\n    tw = thrust / (mass * 9.80665);\nend',
      says: 'Defines thrustToWeight; thrustToWeight(7.607e6, 549e3) returns about 1.41.',
    },
    seeAlso: ['end', 'return'],
  },
  {
    name: 'for',
    lang: 'matlab',
    kind: 'keyword',
    official: 'for loop to repeat specified number of times',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You know in advance how many times to repeat, usually once per element or sample. Grow an array inside the loop and MATLAB copies it every pass, so make it full size first with zeros; often a whole-array expression with no loop at all is faster still.',
    flags: [
      ['k = 1:n', 'k takes 1, 2, 3 ... up to n'],
      ['k = 1:2:n', 'step by 2 instead of 1'],
      ['k = 1:numel(x)', 'one pass per element of x'],
    ],
    example: { command: 'for k = 3:-1:1\n    fprintf("T-minus %d\\n", k);\nend', says: 'Prints T-minus 3, T-minus 2 and T-minus 1 on separate lines.' },
    seeAlso: ['while', 'parfor', 'break', 'continue', 'end'],
  },
  {
    name: 'if',
    lang: 'matlab',
    kind: 'keyword',
    official: 'Execute statements if condition is true',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want code to run only when a test passes. If the test is an array, every element must be true (nonzero) for the block to run, which surprises people; use any or all to say what you mean, and && and || to join conditions.',
    flags: [
      ['elseif', 'another test, tried only if the ones above failed'],
      ['else', 'what to do when no test passed'],
      ['end', 'closes the whole block'],
    ],
    example: {
      command: 'if alt < 0\n    disp("below ground: check the sensor")\nelseif alt < 11000\n    disp("troposphere")\nelse\n    disp("above the troposphere")\nend',
      says: 'Prints one message, depending on which range alt is in.',
    },
    seeAlso: ['elseif', 'else', 'switch', 'end'],
  },
  {
    name: 'case',
    lang: 'matlab',
    kind: 'keyword',
    official: 'Execute one of several groups of statements',
    source: 'MATLAB documentation (MathWorks, switch, case, otherwise)',
    when: 'Inside a switch, each case names a value to match; put several values in curly braces to share one case. Only the first matching case runs; MATLAB never falls through into the next one, so no break is needed.',
    flags: [
      ['case "boost"', 'runs when the switch value equals "boost"'],
      ['case {"coast", "separation"}', 'runs for either value in the braces'],
    ],
    example: {
      command: 'switch mode\n    case "boost"\n        thrust = 7.6e6;\n    case {"coast", "separation"}\n        thrust = 0;\nend',
      says: 'Sets thrust to 7.6e6 during boost and to 0 while coasting or separating.',
    },
    seeAlso: ['switch', 'otherwise'],
  },
  {
    name: 'else',
    lang: 'matlab',
    kind: 'keyword',
    official: 'Execute statements if condition is true',
    source: 'MATLAB documentation (MathWorks, if, elseif, else)',
    when: 'The last, optional part of an if block: it runs when none of the tests above it were true. It takes no condition of its own.',
    example: { command: 'if fuel > 0\n    disp("burning")\nelse\n    disp("tank empty")\nend', says: 'Prints tank empty once fuel has reached 0.' },
    seeAlso: ['if', 'elseif'],
  },
  {
    name: 'switch',
    lang: 'matlab',
    kind: 'keyword',
    official: 'Execute one of several groups of statements',
    source: 'MATLAB documentation (MathWorks)',
    when: 'One value, such as a mode name, decides which of several blocks runs. It reads more clearly than a long if/elseif chain, works with text as well as numbers, and only the first matching case runs.',
    flags: [
      ['case', 'a value to match, with the code for it'],
      ['otherwise', 'the code for when no case matched'],
    ],
    example: {
      command: 'switch mode\n    case "boost"\n        disp("engines on")\n    otherwise\n        error("unknown mode: %s", mode);\nend',
      says: 'Prints engines on for "boost" and stops with an error for any mode it does not know.',
    },
    seeAlso: ['case', 'otherwise', 'if'],
  },
  {
    name: 'otherwise',
    lang: 'matlab',
    kind: 'keyword',
    official: 'Execute one of several groups of statements',
    source: 'MATLAB documentation (MathWorks, switch, case, otherwise)',
    when: 'The optional last part of a switch: it runs when no case matched. A good place to call error, so a misspelled mode is caught instead of silently doing nothing.',
    example: { command: 'otherwise\n    error("unknown mode: %s", mode);', says: 'Stops with unknown mode: ... when the value matched none of the cases.' },
    seeAlso: ['switch', 'case', 'error'],
  },
  {
    name: 'while',
    lang: 'matlab',
    kind: 'keyword',
    official: 'while loop to repeat when condition is true',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to keep going until something happens, and you do not know how many steps that takes. Make sure something inside the loop changes the condition, or it never stops (press Ctrl+C to break out).',
    example: {
      command: 'while h > 0\n    v = v - 9.81*dt;\n    h = h + v*dt;\nend',
      says: 'Steps the falling rocket forward until its height drops to 0 or below.',
    },
    seeAlso: ['for', 'break', 'continue'],
  },
  {
    name: 'break',
    lang: 'matlab',
    kind: 'keyword',
    official: 'Terminate execution of for or while loop',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to leave a loop early, the moment you have your answer. It only exits the innermost loop it is in; to leave the whole function, use return.',
    example: { command: 'for k = 1:maxSteps\n    h = h + v*dt;\n    if h <= 0\n        break\n    end\nend', says: 'Stops stepping as soon as the rocket hits the ground.' },
    seeAlso: ['continue', 'return', 'for', 'while'],
  },
  {
    name: 'continue',
    lang: 'matlab',
    kind: 'keyword',
    official: 'Pass control to next iteration of for or while loop',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to skip the rest of this pass through the loop and move on to the next one, for example to ignore a bad sample. It only affects the loop it sits in.',
    example: { command: 'for k = 1:numel(temps)\n    if isnan(temps(k))\n        continue\n    end\n    disp(temps(k))\nend', says: 'Prints every temperature except the missing (NaN) ones.' },
    seeAlso: ['break', 'for', 'while'],
  },
  {
    name: 'persistent',
    lang: 'matlab',
    kind: 'keyword',
    official: 'Define persistent variable',
    source: 'MATLAB documentation (MathWorks)',
    when: 'A function needs to remember a value between calls, like a filter buffer in a MATLAB Function block. The variable starts out empty, so test it with isempty the first time and fill it in; clearing or editing the function resets it.',
    example: { command: 'persistent buf\nif isempty(buf)\n    buf = zeros(4, 1);\nend', says: 'Creates a 4-sample buffer on the first call and keeps it for every call after.' },
    seeAlso: ['isempty', 'function'],
  },
  {
    name: 'parfor',
    lang: 'matlab',
    kind: 'keyword',
    official: 'Execute for-loop iterations in parallel on workers',
    source: 'Parallel Computing Toolbox documentation (MathWorks)',
    when: 'Each pass of a loop is independent of the others, like the runs of a Monte Carlo study, and you want several CPU cores to share them. Passes run in no fixed order, so no pass may depend on another; without Parallel Computing Toolbox it simply runs like a normal for loop.',
    example: {
      command: 'missDistance = zeros(1, 2000);\nparfor k = 1:2000\n    missDistance(k) = simulateLanding(dispersedParams(k));\nend',
      says: 'Runs 2000 landing simulations spread across the available workers.',
    },
    seeAlso: ['for'],
  },
  {
    name: 'elseif',
    lang: 'matlab',
    kind: 'keyword',
    official: 'Execute statements if condition is true',
    source: 'MATLAB documentation (MathWorks, if, elseif, else)',
    when: 'You need another test inside the same if block, tried only when the tests above it were false. Write it as one word: else if with a space starts a new, nested if that needs its own end.',
    example: { command: 'if q > 30e3\n    disp("max-q region")\nelseif q > 10e3\n    disp("rising")\nend', says: 'Prints rising when q is between 10 and 30 kPa.' },
    seeAlso: ['if', 'else'],
  },
  {
    name: 'return',
    lang: 'matlab',
    kind: 'keyword',
    official: 'Return control to invoking script or function',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to leave a function early, for example when there is nothing to compute. Any outputs must already have values when it runs; inside a loop it leaves the whole function, not just the loop.',
    example: { command: 'if isempty(rates)\n    bias = 0;\n    return\nend', says: 'Hands back a bias of 0 straight away when there is no data.' },
    seeAlso: ['break', 'function'],
  },

  // ------------------------------------------------------ MATLAB functions
  {
    name: 'sqrt',
    lang: 'matlab',
    kind: 'function',
    official: 'Square root',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You need a square root, element by element over a whole array. A negative input gives a complex result instead of an error, so a stray minus sign can quietly turn your numbers complex.',
    example: { command: 'v = sqrt(3.986e14 / 6778e3)', says: 'Shows v = 7.6686e+03, the circular orbit speed in m/s at 400 km up.' },
    seeAlso: ['abs', 'norm'],
  },
  {
    name: 'fprintf',
    lang: 'matlab',
    kind: 'function',
    official: 'Write data to text file',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want neatly formatted output, on screen or into a file. With no file ID it prints to the Command Window; it does not add a new line on its own, so end the format with \\n.',
    flags: [
      ['%d', 'a whole number'],
      ['%.2f', 'a decimal number with 2 digits after the point'],
      ['%.3e', 'scientific notation, like 1.234e+05'],
      ['%s', 'text'],
      ['\\n', 'new line'],
      ['fileID', 'first input: a file opened with fopen, instead of the screen'],
    ],
    example: { command: 'fprintf("hit the ground at t = %.1f s, v = %.2f m/s\\n", 14.3, -140.28)', says: 'Prints hit the ground at t = 14.3 s, v = -140.28 m/s.' },
    seeAlso: ['sprintf', 'disp', 'fopen'],
  },
  {
    name: 'disp',
    lang: 'matlab',
    kind: 'function',
    official: 'Display value of variable',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to show a value or a message without the "x =" that MATLAB normally prints. It takes one thing; to mix text and numbers, join them with + on a string, or use fprintf.',
    example: { command: 'disp("Stage 2 ignition")', says: 'Prints Stage 2 ignition.' },
    seeAlso: ['fprintf', 'sprintf'],
  },
  {
    name: 'norm',
    lang: 'matlab',
    kind: 'function',
    official: 'Vector and matrix norms',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want the length (magnitude) of a vector, such as a speed from a velocity, or a single number that says how big an error is. On a matrix it gives a matrix norm, not the length of each row; for row-by-row lengths use vecnorm.',
    example: { command: 'norm([3 4 0])', says: 'Shows ans = 5, the length of the vector.' },
    seeAlso: ['abs', 'sqrt', 'inv'],
  },
  {
    name: 'plot',
    lang: 'matlab',
    kind: 'function',
    official: '2-D line plot',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to see how one quantity changes with another, like altitude against time. Each call replaces what is already on the axes unless you run hold on first.',
    flags: [
      ["'b-'", 'line style: blue solid line'],
      ["'r--'", 'red dashed line'],
      ["'LineWidth', 1.5", 'a thicker line'],
    ],
    example: { command: "plot(t, h/1000, 'b-', 'LineWidth', 1.5)", says: 'Draws altitude in km against time as a thick blue line.' },
    seeAlso: ['xlabel', 'ylabel', 'title', 'legend', 'xlim'],
  },
  {
    name: 'deg2rad',
    lang: 'matlab',
    kind: 'function',
    official: 'Convert angle from degrees to radians',
    source: 'MATLAB documentation (MathWorks)',
    when: 'Your angle is in degrees but the function wants radians, as sin, cos, angle2quat and most math functions do. Forgetting it gives answers that look plausible but are wrong.',
    example: { command: 'deg2rad(30)', says: 'Shows ans = 0.5236.' },
    seeAlso: ['rad2deg', 'sind', 'cosd'],
  },
  {
    name: 'abs',
    lang: 'matlab',
    kind: 'function',
    official: 'Absolute value and complex magnitude',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You care how big something is, not its sign, such as the size of an error. It works element by element; on a complex number it gives the magnitude.',
    example: { command: 'e_max = max(abs(x - x_exact))', says: 'Gives the largest error between the model and the exact answer, whichever direction it was in.' },
    seeAlso: ['max', 'norm'],
  },
  {
    name: 'max',
    lang: 'matlab',
    kind: 'function',
    official: 'Maximum elements of array',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want the largest value, and often where it happened. On a matrix it works column by column, giving one maximum per column; with two arrays, max(a, b) keeps the larger of each pair, which is handy for clamping.',
    flags: [
      ['[m, i] = max(x)', 'also return the position i of the largest value'],
      ['max(a, b)', 'the larger of a and b, element by element'],
    ],
    example: { command: '[qmax, i] = max(q);\nt(i)', says: 'Finds the peak dynamic pressure and shows the time it happened.' },
    seeAlso: ['min', 'abs', 'find'],
  },
  {
    name: 'exp',
    lang: 'matlab',
    kind: 'function',
    official: 'Exponential',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You need e raised to a power, element by element, such as air density falling off with height. On a matrix it works element by element; the matrix exponential is expm.',
    example: { command: 'rho = 1.225 * exp(-10000 / 8500)', says: 'Shows rho = 0.3777, the rough air density in kg/m^3 at 10 km.' },
    seeAlso: ['log', 'log10'],
  },
  {
    name: 'zeros',
    lang: 'matlab',
    kind: 'function',
    official: 'Create array of all zeros',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want an array ready to fill in, especially before a loop, so MATLAB does not have to grow it one element at a time. zeros(n) alone makes an n-by-n matrix, not a list of n, so give both sizes: zeros(1, n).',
    example: { command: 'missDistance = zeros(1, 2000);', says: 'Makes a row of 2000 zeros to fill in, one per simulation run.' },
    seeAlso: ['ones', 'NaN', 'size'],
  },
  {
    name: 'ylabel',
    lang: 'matlab',
    kind: 'function',
    official: 'Label y-axis',
    source: 'MATLAB documentation (MathWorks)',
    when: 'Every plot needs its vertical axis named, with units. It labels the current axes, so call it right after plotting into the axes you mean.',
    example: { command: "ylabel('Altitude (km)')", says: 'Writes Altitude (km) along the vertical axis.' },
    seeAlso: ['xlabel', 'title', 'plot'],
  },
  {
    name: 'sin',
    lang: 'matlab',
    kind: 'function',
    official: 'Sine of argument in radians',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You need a sine and your angle is in radians. For degrees, use sind instead of converting by hand.',
    example: { command: 'sin(pi/6)', says: 'Shows ans = 0.5000.' },
    seeAlso: ['cos', 'sind', 'deg2rad'],
  },
  {
    name: 'numel',
    lang: 'matlab',
    kind: 'function',
    official: 'Number of array elements',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want the total count of elements, for example to loop over all of them. On a matrix it counts every element, rows times columns; for a single dimension use size.',
    example: { command: 'numel(zeros(4, 3))', says: 'Shows ans = 12.' },
    seeAlso: ['size', 'length'],
  },
  {
    name: 'size',
    lang: 'matlab',
    kind: 'function',
    official: 'Array size',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to know how many rows and columns an array has, or you want to make another array the same shape. Rows come first, then columns.',
    flags: [
      ['size(A)', 'rows and columns as a pair, like [4 3]'],
      ['size(A, 1)', 'just the number of rows'],
      ['ones(size(t))', 'a new array shaped like t'],
    ],
    example: { command: 'imu = zeros(4, 3);\nsize(imu)', says: 'Shows ans = 4 3: four samples, three axes.' },
    seeAlso: ['numel', 'reshape', 'zeros'],
  },
  {
    name: 'find',
    lang: 'matlab',
    kind: 'function',
    official: 'Find indices and values of nonzero elements',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want the positions where a condition is true, such as the first sample above 500 m. If nothing matches it returns an empty result, not 0, so check it with isempty.',
    flags: [
      ['find(x > 0)', 'positions of every element that passes the test'],
      ['find(x > 0, 1)', 'only the first one'],
      ["find(x > 0, 1, 'last')", 'only the last one'],
    ],
    example: { command: 'k = find(alt > 500, 1)', says: 'Gives the index of the first sample where the altitude is above 500.' },
    seeAlso: ['isempty', 'max'],
  },
  {
    name: 'mean',
    lang: 'matlab',
    kind: 'function',
    official: 'Average or mean value of array',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want the average. On a matrix it averages each column separately; pass 2 as the second input to average each row instead. A single NaN makes the answer NaN unless you add "omitnan".',
    flags: [['mean(x, 1)', 'average down each column (the default for a matrix)']],
    example: { command: 'mean([9.79 9.81 9.83])', says: 'Shows ans = 9.8100.' },
    seeAlso: ['std', 'sum'],
  },
  {
    name: 'nexttile',
    lang: 'matlab',
    kind: 'function',
    official: 'Create axes in tiled chart layout',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You are filling a grid of plots made with tiledlayout: each call moves to the next empty tile and makes it the current axes. Keep the axes it returns if you want to link or adjust tiles later.',
    flags: [
      ['nexttile', 'go to the next tile of the current layout'],
      ['ax = nexttile(tl)', 'next tile of layout tl, keeping its axes in ax'],
    ],
    example: { command: "ax(1) = nexttile(tl);  plot(t, h/1000);  ylabel('Altitude (km)')", says: 'Plots altitude in the next tile and keeps its axes as ax(1).' },
    seeAlso: ['tiledlayout', 'linkaxes', 'gobjects'],
  },
  {
    name: 'cos',
    lang: 'matlab',
    kind: 'function',
    official: 'Cosine of argument in radians',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You need a cosine and your angle is in radians. For degrees, use cosd.',
    example: { command: 'th = pi/2;\nR = [cos(th) -sin(th); sin(th) cos(th)];', says: 'Builds the 2-D rotation matrix for a 90 degree turn.' },
    seeAlso: ['sin', 'cosd', 'deg2rad'],
  },
  {
    name: 'sum',
    lang: 'matlab',
    kind: 'function',
    official: 'Sum of array elements',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to add up values. On a matrix it sums each column; sum(A, 2) sums each row. On a true/false array it counts how many are true.',
    flags: [
      ['sum(A, 2)', 'add along each row'],
      ['sum(q > 30e3)', 'count how many elements pass the test'],
    ],
    example: { command: 'tAbove = sum(q > 30e3) * dt', says: 'Counts the samples above 30 kPa and turns the count into seconds.' },
    seeAlso: ['mean', 'diff'],
  },
  {
    name: 'error',
    lang: 'matlab',
    kind: 'function',
    official: 'Throw error and display message',
    source: 'MATLAB documentation (MathWorks)',
    when: 'Something is wrong enough that the program should stop, like an unknown mode or bad input. It stops the current function and anything that called it, unless a try/catch catches it.',
    flags: [
      ['error("msg %s", x)', 'message with fprintf-style blanks to fill in'],
      ['error("pkg:id", "msg")', 'give the error an identifier first, so code can recognize it'],
    ],
    example: { command: 'error("unknown mode: %s", "hover")', says: 'Stops with the red message unknown mode: hover.' },
    seeAlso: ['assert', 'validateattributes', 'fprintf'],
  },
  {
    name: 'save',
    lang: 'matlab',
    kind: 'function',
    official: 'Save variables from workspace to file',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to keep variables for later, exactly as they are, in a .mat file. With only a file name it saves everything in the workspace; list the names to save just those.',
    flags: [
      ["save('f.mat')", 'save every variable'],
      ["save('f.mat', 't', 'alt')", 'save only t and alt (names as text)'],
    ],
    example: { command: "save('hop.mat', 't', 'alt')", says: 'Writes t and alt into hop.mat in the current folder.' },
    seeAlso: ['load', 'writetable'],
  },
  {
    name: 'load',
    lang: 'matlab',
    kind: 'function',
    official: 'Load variables from file into workspace',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want back the variables you saved in a .mat file. On its own it drops them straight into your workspace, silently replacing any with the same names; S = load(...) puts them in a struct instead, which is safer.',
    flags: [
      ["load('f.mat')", 'variables appear in the workspace'],
      ["S = load('f.mat')", 'variables arrive as fields, S.t and S.alt'],
    ],
    example: { command: "S = load('hop.mat');\nS.alt", says: 'Shows the saved altitudes without touching any other variables.' },
    seeAlso: ['save', 'readtable'],
  },
  {
    name: 'assert',
    lang: 'matlab',
    kind: 'function',
    official: 'Throw error if condition false',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want a check that must always hold, such as a requirement in a test script. If the condition is false it stops with your message; if true it does nothing at all.',
    example: { command: "assert(S.Overshoot <= 20, 'overshoot requirement failed')", says: 'Carries on quietly if overshoot is 20 percent or less, otherwise stops with the message.' },
    seeAlso: ['error', 'validateattributes'],
  },
  {
    name: 'isempty',
    lang: 'matlab',
    kind: 'function',
    official: 'Determine whether array is empty',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You need to know if something has no elements at all, such as the result of find or a persistent variable on its first call. An array full of NaN is not empty; a string "" is not empty either (it is one string with no letters).',
    example: { command: 'k = find(alt > 1e6, 1);\nisempty(k)', says: 'Shows ans = logical 1, because no sample went that high.' },
    seeAlso: ['find', 'persistent', 'isnan'],
  },
  {
    name: 'randn',
    lang: 'matlab',
    kind: 'function',
    official: 'Normally distributed random numbers',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You need random noise that follows a bell curve with mean 0 and standard deviation 1, like sensor noise or turbulence. Scale it to the size you want; call rng first if you need the same numbers every run.',
    example: { command: 'noise = 0.05 * randn(1, 100);', says: 'Makes 100 noise samples with a standard deviation of about 0.05.' },
    seeAlso: ['rng', 'std'],
  },
  {
    name: 'ones',
    lang: 'matlab',
    kind: 'function',
    official: 'Create array of all ones',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want an array filled with 1, often to scale into a constant signal or to build a column of ones for a fit. Like zeros, ones(n) makes an n-by-n matrix.',
    example: { command: 'ones(1, 4)', says: 'Shows ans = 1 1 1 1.' },
    seeAlso: ['zeros', 'size'],
  },
  {
    name: 'xlabel',
    lang: 'matlab',
    kind: 'function',
    official: 'Label x-axis',
    source: 'MATLAB documentation (MathWorks)',
    when: 'Every plot needs its horizontal axis named, with units. Pass a tiled layout as the first input to put one shared label under the whole grid.',
    flags: [['xlabel(tl, ...)', 'one label for the whole tiled layout tl']],
    example: { command: "xlabel('Time (s)')", says: 'Writes Time (s) under the horizontal axis.' },
    seeAlso: ['ylabel', 'title', 'plot'],
  },
  {
    name: 'log10',
    lang: 'matlab',
    kind: 'function',
    official: 'Common logarithm (base 10)',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You need a base-10 logarithm, most often to turn a gain ratio into decibels with 20*log10. The plain log function is the natural log (base e), not base 10.',
    example: { command: '20*log10(0.5)', says: 'Shows ans = -6.0206: a gain of one half is about -6 dB.' },
    seeAlso: ['log', 'exp'],
  },
  {
    name: 'xlim',
    lang: 'matlab',
    kind: 'function',
    official: 'Set or query x-axis limits',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to zoom the horizontal axis to a range, or read the range it has now. Give it an axes first to change a particular plot rather than the current one.',
    flags: [
      ['xlim([0 60])', 'show x from 0 to 60'],
      ['xlim(ax, [20 40])', 'set the range on axes ax'],
    ],
    example: { command: 'xlim([0 60])', says: 'Shows only the first 60 seconds of the plot.' },
    seeAlso: ['ylim', 'linkaxes'],
  },
  {
    name: 'exportgraphics',
    lang: 'matlab',
    kind: 'function',
    official: 'Export figure or plot',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want a figure saved as an image or PDF for a report, cropped tightly around the content. The file type comes from the extension you give.',
    flags: [
      ["'Resolution', 300", 'dots per inch for a picture file such as .png'],
      ["'ContentType', 'vector'", 'keep lines sharp at any zoom (for .pdf)'],
    ],
    example: { command: "exportgraphics(f, 'ascent_quicklook.png', 'Resolution', 300)", says: 'Saves figure f as a 300 dpi PNG image.' },
    seeAlso: ['plot', 'tiledlayout'],
  },
  {
    name: 'seconds',
    lang: 'matlab',
    kind: 'function',
    official: 'Duration in seconds',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want plain numbers turned into a duration, a real length of time, for example the row times of a timetable. It also works backwards: seconds of a duration gives a plain number again.',
    example: { command: 'baro = timetable(seconds([0 0.25 0.5]\'), [0.0 1.9 5.2]\');', says: 'Makes a timetable whose rows are stamped 0 s, 0.25 s and 0.5 s.' },
    seeAlso: ['timetable', 'days', 'retime'],
  },
  {
    name: 'class',
    lang: 'matlab',
    kind: 'function',
    official: 'Class of object',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to know what type a value is, such as double, char, string or cell. Handy when a result behaves oddly, for example curly versus round brackets on a cell array.',
    example: { command: 'class(9.81)', says: "Shows ans = 'double'." },
    seeAlso: ['validateattributes', 'struct'],
  },
  {
    name: 'validateattributes',
    lang: 'matlab',
    kind: 'function',
    official: 'Check validity of array',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want a function to reject bad input with a clear message, checking the type and properties (size, finite, positive...) in one line. If everything is fine it does nothing.',
    flags: [
      ["{'double'}", 'the allowed types'],
      ["{'vector', 'numel', 4, 'finite'}", 'the properties the value must have'],
      ['funcName, varName', 'names to show in the error message'],
    ],
    example: {
      command: "validateattributes(q, {'double'}, {'vector', 'numel', 4, 'finite'}, 'normq', 'q')",
      says: 'Stops with a clear error unless q is a finite vector of 4 doubles.',
    },
    seeAlso: ['assert', 'error', 'class'],
  },
  {
    name: 'ode45',
    lang: 'matlab',
    kind: 'function',
    official: 'Solve nonstiff differential equations — medium order method',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You have equations for how things change (derivatives) and want the path over time. It is the first solver to try; it chooses its own step sizes, so the times it returns are not evenly spaced. On stiff problems it crawls, and ode15s is better.',
    flags: [
      ['rhs', 'a function handle @(t, x) that returns the derivatives'],
      ['[t0 tf]', 'start and end time'],
      ['x0', 'the starting state'],
      ['opts', 'tolerances made with odeset'],
    ],
    example: { command: '[t, x] = ode45(rhs, [0 60], x0);', says: 'Integrates the motion for 60 s and returns the times and the state at each one.' },
    seeAlso: ['odeset', 'ode23'],
  },
  {
    name: 'sprintf',
    lang: 'matlab',
    kind: 'function',
    official: 'Format data into string or character vector',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want formatted text kept in a variable, such as a file name or a label, rather than printed. It uses the same % blanks as fprintf.',
    example: { command: "name = sprintf('hop_run_%03d.csv', 7)", says: "Gives name = 'hop_run_007.csv'." },
    seeAlso: ['fprintf', 'num2str'],
  },
  {
    name: 'squeeze',
    lang: 'matlab',
    kind: 'function',
    official: 'Remove dimensions of length 1',
    source: 'MATLAB documentation (MathWorks)',
    when: 'A function hands back an array with extra dimensions of size 1, like the 1-by-1-by-N results of bode, and you want a plain vector. Ordinary matrices come back unchanged.',
    example: { command: '[mag, phase] = bode(G, [2 20]);\nmag = squeeze(mag)', says: 'Turns the 1x1x2 magnitude array into a simple column of 2 values.' },
    seeAlso: ['reshape', 'bode'],
  },
  {
    name: 'interp1',
    lang: 'matlab',
    kind: 'function',
    official: '1-D data interpolation (table lookup)',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You have values at some points and want an estimate in between, like a gain at Mach 1.1 from a table. By default it draws straight lines between points and returns NaN outside the table.',
    example: { command: 'Mach = [0.8 1.0 1.2];  Kp = [5.6 5.2 4.9];\ninterp1(Mach, Kp, 1.1)', says: 'Shows ans = 5.0500, halfway between the gains at Mach 1.0 and 1.2.' },
    seeAlso: ['interp2', 'interpn'],
  },
  {
    name: 'rank',
    lang: 'matlab',
    kind: 'function',
    official: 'Rank of matrix',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to know how many independent rows or columns a matrix has, for example to test whether a system is controllable or observable. It uses a tolerance, so nearly dependent columns can count as dependent.',
    example: { command: 'rank(obsv(A, [1 0]))', says: 'Shows ans = 2 for a 2-state system, meaning the angle sensor alone can observe both states.' },
    seeAlso: ['obsv', 'ctrb', 'inv'],
  },
  {
    name: 'diag',
    lang: 'matlab',
    kind: 'function',
    official: 'Create diagonal matrix or get diagonal elements of matrix',
    source: 'MATLAB documentation (MathWorks)',
    when: 'Give it a vector and it builds a square matrix with those values on the diagonal and zeros elsewhere, handy for LQR weights. Give it a matrix and it pulls the diagonal out instead.',
    example: { command: 'diag([100 0])', says: 'Shows the matrix [100 0; 0 0].' },
    seeAlso: ['lqr', 'eye'],
  },
  {
    name: 'interp2',
    lang: 'matlab',
    kind: 'function',
    official: 'Interpolation for 2-D gridded data in meshgrid format',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want a value from a 2-D table, such as a coefficient against Mach and angle of attack. It expects the column variable first and the row variable second, the opposite of what you may expect; swap them and you get a wrong but believable number.',
    example: { command: 'interp2(alpha, M, CN, 5, 1.0)', says: 'Looks up CN at alpha = 5 deg and Mach 1.0 (columns follow alpha, rows follow Mach).' },
    seeAlso: ['interp1', 'interpn'],
  },
  {
    name: 'inv',
    lang: 'matlab',
    kind: 'function',
    official: 'Matrix inverse',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You need the actual inverse matrix. To solve A*x = b, use x = A\\b instead: it is faster and more accurate, while inv(A)*b loses digits when A is nearly singular.',
    example: { command: 'inv([2 0; 0 4])', says: 'Shows [0.5 0; 0 0.25].' },
    seeAlso: ['rank', 'norm'],
  },
  {
    name: 'NaN',
    lang: 'matlab',
    kind: 'function',
    official: 'Create array of all NaN values',
    source: 'MATLAB documentation (MathWorks)',
    when: 'NaN means "not a number": a marker for missing or not-yet-filled data. NaN(1, n) makes a row of them, so unfilled slots stand out. NaN is never equal to anything, even itself, so test with isnan, not ==.',
    example: { command: 'h = NaN(1, 5);\nh(1) = 0', says: 'Shows h = 0 NaN NaN NaN NaN.' },
    seeAlso: ['isnan', 'zeros'],
  },
  {
    name: 'tiledlayout',
    lang: 'matlab',
    kind: 'function',
    official: 'Create tiled chart layout for displaying subplots',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want a grid of plots in one figure. Make the layout, then call nexttile before each plot; one shared title or axis label can go on the layout itself.',
    flags: [
      ['tiledlayout(3, 2)', '3 rows by 2 columns of tiles'],
      ["'TileSpacing', 'compact'", 'less space between tiles'],
      ["'Padding', 'compact'", 'less space around the edge'],
    ],
    example: { command: "tl = tiledlayout(3, 2, 'TileSpacing', 'compact', 'Padding', 'compact');", says: 'Sets up a 3-by-2 grid of plots with tight spacing.' },
    seeAlso: ['nexttile', 'title', 'linkaxes'],
  },
  {
    name: 'title',
    lang: 'matlab',
    kind: 'function',
    official: 'Add title',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want a heading above a plot. Give a tiled layout as the first input to put one title over the whole grid.',
    flags: [['title(tl, ...)', 'one title for the whole tiled layout tl']],
    example: { command: "title(tl, 'Toy ascent')", says: 'Writes Toy ascent across the top of the grid of plots.' },
    seeAlso: ['xlabel', 'ylabel', 'tiledlayout'],
  },
  {
    name: 'gobjects',
    lang: 'matlab',
    kind: 'function',
    official: 'Initialize array for graphics objects',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want an array ready to hold axes or lines before a loop fills it. Use it instead of zeros, which would hold numbers rather than graphics objects.',
    example: { command: 'ax = gobjects(1, 6);', says: 'Makes an empty row of six slots for the six panels\' axes.' },
    seeAlso: ['nexttile', 'linkaxes'],
  },
  {
    name: 'linkaxes',
    lang: 'matlab',
    kind: 'function',
    official: 'Synchronize limits of multiple axes',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You have several panels sharing a time axis and want zooming one to zoom them all. Link only x when the panels have different y units.',
    flags: [["'x'", 'link only the horizontal axes']],
    example: { command: "linkaxes(ax, 'x')\nxlim(ax(1), [20 40])", says: 'Now all six panels show 20 s to 40 s together.' },
    seeAlso: ['xlim', 'nexttile', 'gobjects'],
  },
  {
    name: 'ylim',
    lang: 'matlab',
    kind: 'function',
    official: 'Set or query y-axis limits',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to set the vertical range of a plot, or read the range it has now. Reading and then setting it again freezes the limits so later drawing does not rescale them.',
    flags: [
      ['yl = ylim(ax)', 'read the current range of axes ax'],
      ['ylim(ax, yl)', 'set (and freeze) the range'],
    ],
    example: { command: 'ylim([0 150])', says: 'Shows the vertical axis from 0 to 150.' },
    seeAlso: ['xlim'],
  },
  {
    name: 'timetable',
    lang: 'matlab',
    kind: 'function',
    official: 'Tables for time series data, with timestamped rows and variables of different types',
    source: 'MATLAB documentation (MathWorks)',
    when: 'Your data is time-stamped samples, like sensor logs, and you want to line up, resample or slice them by time. The row times must be durations or datetimes, so wrap plain numbers in seconds.',
    example: { command: "gps = timetable(seconds([0.1 0.6 1.1]'), [0.4 6.1 17.2]', 'VariableNames', {'alt'});", says: 'Makes a GPS altitude log with three time-stamped rows.' },
    seeAlso: ['seconds', 'synchronize', 'retime', 'table'],
  },
  {
    name: 'synchronize',
    lang: 'matlab',
    kind: 'function',
    official: 'Synchronize timetables to common time vector, and resample or aggregate data from input timetables',
    source: 'MATLAB documentation (MathWorks)',
    when: 'Two sensors log at different times and you want their readings side by side on one set of times. You choose the times and how to fill the gaps; the choice changes the numbers you get.',
    flags: [
      ["'first'", "use the first timetable's times"],
      ["'previous'", 'fill with the last reading before each time'],
      ["'nearest'", 'fill with the closest reading in time'],
    ],
    example: { command: "bn = synchronize(baro, gps, 'first', 'nearest');", says: 'Puts GPS altitude next to each barometer sample, using the nearest GPS reading.' },
    seeAlso: ['timetable', 'retime'],
  },
  {
    name: 'cosd',
    lang: 'matlab',
    kind: 'function',
    official: 'Cosine of argument in degrees',
    source: 'MATLAB documentation (MathWorks)',
    when: 'Your angle is in degrees and you want its cosine without converting to radians. It also gives exact zeros where cos(pi/2) leaves a tiny rounding error.',
    example: { command: 'cosd(60)', says: 'Shows ans = 0.5000.' },
    seeAlso: ['sind', 'cos'],
  },
  {
    name: 'sind',
    lang: 'matlab',
    kind: 'function',
    official: 'Sine of argument in degrees',
    source: 'MATLAB documentation (MathWorks)',
    when: 'Your angle is in degrees and you want its sine without converting to radians.',
    example: { command: 'Rz = [cosd(30) -sind(30) 0; sind(30) cosd(30) 0; 0 0 1];', says: 'Builds the matrix that rotates 30 degrees about the z axis.' },
    seeAlso: ['cosd', 'sin'],
  },
  {
    name: 'linspace',
    lang: 'matlab',
    kind: 'function',
    official: 'Generate linearly spaced vector',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want a set number of evenly spaced points between two ends, both ends included. The third input is how many points, not the step size (that is what start:step:stop is for).',
    example: { command: 'linspace(0, 1, 5)', says: 'Shows 0 0.2500 0.5000 0.7500 1.0000.' },
    seeAlso: ['logspace', 'zeros'],
  },
  {
    name: 'reshape',
    lang: 'matlab',
    kind: 'function',
    official: 'Reshape array by rearranging existing elements',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want the same elements in a different shape, like a long list into rows of three. MATLAB fills column by column, not row by row, which often surprises people; put [] for one size to let MATLAB work it out.',
    flags: [['reshape(v, 3, [])', '3 rows, as many columns as needed']],
    example: { command: 'reshape(1:6, 2, 3)', says: 'Shows [1 3 5; 2 4 6], filled down the columns.' },
    seeAlso: ['size', 'squeeze'],
  },
  {
    name: 'struct',
    lang: 'matlab',
    kind: 'function',
    official: 'Structure array',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to group related values under named fields, like a stage\'s name and Isp. If you give values in curly braces, struct makes one element per value, a struct array, not one struct holding a list.',
    example: { command: "s = struct('name', {'S1', 'S2'}, 'isp', {282, 348});\ns(2).isp", says: 'Makes two stages and shows ans = 348, the second stage\'s Isp.' },
    seeAlso: ['class', 'isfield', 'table'],
  },
  {
    name: 'fzero',
    lang: 'matlab',
    kind: 'function',
    official: 'Root of nonlinear function',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want the input where a function equals zero, such as the time a falling rocket hits the ground. It needs a function handle and a starting guess, and it only finds places where the function crosses zero, not where it just touches.',
    example: { command: 'h = @(t) 100 + 50*t - 4.9*t.^2;\ntLand = fzero(h, 10)', says: 'Shows tLand = 11.9167, the time in seconds when height reaches 0.' },
    seeAlso: ['ode45'],
  },
  {
    name: 'readtable',
    lang: 'matlab',
    kind: 'function',
    official: 'Create table from file',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You have a CSV or spreadsheet with a header line and want it as a table. Each column becomes a variable named from the header, so a column t_s is read as T.t_s.',
    example: { command: "T = readtable('hop.csv');\nT.alt_m", says: 'Reads the file and shows the alt_m column.' },
    seeAlso: ['writetable', 'table', 'load'],
  },
  {
    name: 'writetable',
    lang: 'matlab',
    kind: 'function',
    official: 'Write table to file',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want a table saved as a CSV (or spreadsheet) that other programs can open. It writes the variable names as the header line and replaces a file with the same name.',
    example: { command: "writetable(T, 'hop_processed.csv')", says: 'Writes the table to hop_processed.csv, header first, then one line per row.' },
    seeAlso: ['readtable', 'save'],
  },
  {
    name: 'diff',
    lang: 'matlab',
    kind: 'function',
    official: 'Differences and approximate derivatives',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want the change from each sample to the next, for example to estimate speed from positions. The answer is one element shorter than the input, so pad it (often with NaN) before putting it back in a table.',
    example: { command: 'vz = diff(T.alt_m) ./ diff(T.t_s);', says: 'Estimates the vertical speed between each pair of samples.' },
    seeAlso: ['sum', 'NaN'],
  },
  {
    name: 'std',
    lang: 'matlab',
    kind: 'function',
    official: 'Standard deviation',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to know how spread out values are around their mean, such as the strength of simulated noise. Like mean, it works column by column on a matrix.',
    example: { command: 'std([9.79 9.81 9.83])', says: 'Shows ans = 0.0200.' },
    seeAlso: ['mean', 'randn'],
  },

  // ---------------------------------------------------------------- Simulink
  {
    name: 'set_param',
    lang: 'matlab',
    kind: 'function',
    official: 'Set Simulink parameter value',
    source: 'Simulink documentation (MathWorks)',
    when: 'You want to change a model or block setting from code instead of clicking, such as the stop time or solver. Values are usually given as text, even numbers: \'20\', not 20.',
    flags: [
      ["'StopTime', '20'", 'how long the simulation runs, in seconds'],
      ["'Solver', 'ode4'", 'which solver to use'],
      ["'RelTol', '1e-6'", 'the relative error tolerance'],
      ["'SimulationMode', ...", 'for example run a referenced model as software-in-the-loop'],
    ],
    example: { command: "set_param(mdl, 'StopTime', '30');", says: 'Makes the model simulate for 30 seconds.' },
    seeAlso: ['get_param', 'sim'],
  },
  {
    name: 'legacy_code',
    lang: 'matlab',
    kind: 'function',
    official: 'Integrate existing C/C++ code using Legacy Code Tool',
    source: 'Simulink documentation (MathWorks)',
    when: 'You have a tested C function and want to call it from a Simulink block without rewriting it. You describe the function in a struct, then call legacy_code with one action after another; you need a C compiler set up first.',
    flags: [
      ["'initialize'", 'get an empty description struct to fill in'],
      ["'sfcn_cmex_generate'", 'write the S-function C source'],
      ["'compile'", 'build it into a MEX file'],
      ["'slblock_generate'", 'make a block that uses it'],
      ["'sfcn_tlc_generate'", 'write the TLC file needed for code generation'],
    ],
    example: {
      command: "def = legacy_code('initialize');\ndef.OutputFcnSpec = 'double y1 = gyro_comp(double u1, double u2)';",
      says: 'Starts a description of the C function gyro_comp for Legacy Code Tool.',
    },
    seeAlso: ['add_block'],
  },
  {
    name: 'sim',
    lang: 'matlab',
    kind: 'function',
    official: 'Run and script programmatic simulations of Simulink models',
    source: 'Simulink documentation (MathWorks)',
    when: 'You want to run a Simulink model from a script, for tests or parameter sweeps. The logged signals come back in one output object, so keep it: out = sim(...).',
    example: { command: "out = sim('stage_accel');\na = out.accel.Data;", says: 'Runs the model and pulls the logged acceleration out of the results.' },
    seeAlso: ['set_param', 'load_system'],
  },
  {
    name: 'get_param',
    lang: 'matlab',
    kind: 'function',
    official: 'Get parameter names and values',
    source: 'Simulink documentation (MathWorks)',
    when: 'You want to read a model or block setting from code. Most values come back as text, even numbers, so convert with str2double if you need to calculate with them.',
    example: { command: "get_param(mdl, 'Solver')", says: "Shows ans = 'ode45', the model's current solver." },
    seeAlso: ['set_param'],
  },
  {
    name: 'add_block',
    lang: 'matlab',
    kind: 'function',
    official: 'Add block to model',
    source: 'Simulink documentation (MathWorks)',
    when: 'You are building a model with code: it copies a block from a library into your model under a new name. The model must already be loaded, and the new name must not be taken.',
    flags: [
      ["'simulink/Sources/Constant'", 'the library block to copy'],
      ["[mdl '/Burn rate']", 'where it goes and what it is called'],
      ["'Value', '-12'", 'set block parameters as you add it'],
    ],
    example: { command: "add_block('simulink/Sources/Constant', [mdl '/Burn rate'], 'Value', '-12');", says: 'Adds a Constant block named Burn rate that outputs -12.' },
    seeAlso: ['add_line', 'new_system', 'set_param'],
  },
  {
    name: 'add_line',
    lang: 'matlab',
    kind: 'function',
    official: 'Add line to Simulink model',
    source: 'Simulink documentation (MathWorks)',
    when: 'You are wiring a model with code: connect an output port of one block to an input port of another, named as \'Block/port number\'. An input port can only take one line.',
    example: { command: "add_line(mdl, 'Burn rate/1', 'Fuel/1');", says: 'Connects output 1 of Burn rate to input 1 of Fuel.' },
    seeAlso: ['add_block'],
  },
  {
    name: 'create',
    aliases: ['Simulink.data.dictionary.create'],
    lang: 'matlab',
    kind: 'function',
    official: 'Create new data dictionary and create Simulink.data.Dictionary object',
    source: 'Simulink documentation (MathWorks)',
    when: 'You want a new .sldd data dictionary file to hold a model\'s parameters and types, so they travel with the model instead of living in the base workspace. The lessons also call sltest.harness.create, a different function that makes a Simulink Test harness.',
    example: { command: "dd = Simulink.data.dictionary.create('ascent_gnc.sldd');", says: 'Creates ascent_gnc.sldd and gives back dd to work with it.' },
    seeAlso: ['open', 'getSection', 'addEntry', 'saveChanges'],
  },
  {
    name: 'open',
    aliases: ['Simulink.data.dictionary.open'],
    lang: 'matlab',
    kind: 'function',
    official: 'Open data dictionary for editing',
    source: 'Simulink documentation (MathWorks)',
    when: 'You want to change an existing data dictionary from code. Nothing is written to the file until you call saveChanges. The lessons also call sltest.harness.open, which opens a Simulink Test harness instead.',
    example: { command: "gnc = Simulink.data.dictionary.open('gnc.sldd');", says: 'Opens gnc.sldd and gives back gnc to edit it.' },
    seeAlso: ['create', 'saveChanges', 'getSection'],
  },
  {
    name: 'addEntry',
    lang: 'matlab',
    kind: 'method',
    official: 'Add new entry to data dictionary section',
    source: 'Simulink documentation (MathWorks)',
    when: 'You want to put a named value, such as a limit or a Simulink.Parameter, into a data dictionary section (usually Design Data, fetched with getSection). It fails if that name already exists there.',
    example: { command: "addEntry(sec, 'pitch_rate_limit', 5);", says: 'Adds pitch_rate_limit = 5 to the section sec.' },
    seeAlso: ['getSection', 'saveChanges', 'Parameter'],
  },
  {
    name: 'saveChanges',
    lang: 'matlab',
    kind: 'method',
    official: 'Save changes to data dictionary',
    source: 'Simulink documentation (MathWorks)',
    when: 'You have edited a data dictionary from code and want the changes written to the .sldd file. Until you call it, the changes exist only in memory.',
    example: { command: 'saveChanges(dd);', says: 'Writes every change made to dd into its file.' },
    seeAlso: ['addEntry', 'open', 'create'],
  },
  {
    name: 'Parameter',
    aliases: ['Simulink.Parameter'],
    lang: 'matlab',
    kind: 'class',
    official: 'Store, share, and configure parameter values',
    source: 'Simulink documentation (MathWorks)',
    when: 'You want a named value that blocks use, with extra settings such as data type, units and how it appears in generated code. The number itself lives in its Value property.',
    example: { command: 'Kp_pitch = Simulink.Parameter(0.8);\nKp_pitch.Value', says: 'Makes a parameter object for the pitch gain and shows ans = 0.8000.' },
    seeAlso: ['addEntry', 'Variant'],
  },
  {
    name: 'Variant',
    aliases: ['Simulink.Variant'],
    lang: 'matlab',
    kind: 'class',
    official: 'Specify conditions that control variant selection',
    source: 'Simulink documentation (MathWorks)',
    when: 'You want a named condition that picks which version of a subsystem is active, such as flight sensors versus bench sensors. Newer releases rename it Simulink.VariantExpression; the old name still works for now.',
    example: { command: "FLIGHT = Simulink.Variant('SENSOR_SRC == 1');", says: 'Defines FLIGHT as the variant that is active when SENSOR_SRC is 1.' },
    seeAlso: ['Parameter'],
  },

  // -------------------------------------------------- Control System Toolbox
  {
    name: 'tf',
    lang: 'matlab',
    kind: 'function',
    official: 'Transfer function model',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want a system described as a fraction of polynomials in s, to analyze or simulate it. Give the numerator and denominator coefficients, highest power first, or make s = tf(\'s\') and write the fraction as normal algebra.',
    flags: [
      ['tf(num, den)', 'numerator and denominator coefficient vectors'],
      ["s = tf('s')", 'the Laplace variable s, to type models as formulas'],
      ['tf(sys)', 'convert another model to transfer function form'],
    ],
    example: { command: "s = tf('s');\nG = 4/(s^2 + 2*s + 4)", says: 'Shows G = 4 / (s^2 + 2 s + 4) as a continuous-time transfer function.' },
    seeAlso: ['ss', 'zpk', 'step', 'feedback'],
  },
  {
    name: 'step',
    lang: 'matlab',
    kind: 'function',
    official: 'Step response plot of dynamic system; step response data',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want to see how a system reacts when its input jumps from 0 to 1, the classic test of a control loop. With no outputs it draws the plot; ask for outputs and it returns the numbers and draws nothing.',
    flags: [
      ['step(T)', 'plot the response'],
      ['step(T, 8)', 'plot from 0 to 8 s'],
      ['[y, t] = step(T)', 'return the response values and times instead'],
    ],
    example: { command: 'step(feedback(L, 1))', says: 'Plots the closed-loop step response.' },
    seeAlso: ['stepinfo', 'lsim', 'impulse'],
  },
  {
    name: 'ss',
    lang: 'matlab',
    kind: 'function',
    official: 'State-space model',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want a system in matrix form, dx/dt = A x + B u and y = C x + D u, which is how most modern control design works. ss(G) converts another model and keeps every state, which matters when poles cancel.',
    flags: [
      ['ss(A, B, C, D)', 'build from the four matrices'],
      ['ss(G)', 'convert a transfer function to state space'],
    ],
    example: { command: 'P = ss([0 1; 0 0], [0; 0.1], [1 0], 0);', says: 'Makes a state-space model of a spacecraft rotating under a torque.' },
    seeAlso: ['tf', 'lqr', 'obsv'],
  },
  {
    name: 'pole',
    lang: 'matlab',
    kind: 'function',
    official: 'Poles of dynamic system',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want the poles, the numbers that decide stability and how fast responses die away. Any pole with a positive real part means an unstable system.',
    example: { command: 'p = pole(tf(4, [1 2 4]))', says: 'Shows p = -1.0000 + 1.7321i and -1.0000 - 1.7321i: both on the left, so the system is stable.' },
    seeAlso: ['damp', 'pzmap', 'rlocus'],
  },
  {
    name: 'feedback',
    lang: 'matlab',
    kind: 'function',
    official: 'Feedback connection of multiple models',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want the closed-loop system you get when the output is measured and fed back. It assumes negative feedback; feedback(L, 1) closes the loop around L with a sensor gain of 1.',
    example: { command: 'T = feedback(4*G, 1)', says: 'Gives the closed-loop transfer function of the loop with gain 4.' },
    seeAlso: ['tf', 'step', 'margin'],
  },
  {
    name: 'margin',
    lang: 'matlab',
    kind: 'function',
    official: 'Gain margin, phase margin, and crossover frequencies',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want to know how much extra gain or delay a loop can take before it goes unstable. Pass the open loop, not the closed loop. The gain margin comes back as a ratio, so use 20*log10 to get decibels.',
    flags: [
      ['Gm', 'gain margin, as a ratio'],
      ['Pm', 'phase margin, in degrees'],
      ['Wcg, Wcp', 'the frequencies where each margin is measured'],
    ],
    example: { command: '[Gm, Pm, Wcg, Wcp] = margin(L)', says: 'Prints the margins and crossover frequencies of the open loop L.' },
    seeAlso: ['bode', 'feedback'],
  },
  {
    name: 'lsim',
    lang: 'matlab',
    kind: 'function',
    official: 'Compute time response simulation data of dynamic system to arbitrary inputs',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want the response to any input you choose, like a ramp, a recorded command or noise, not just a step. The input needs one value per time point, sampled evenly.',
    example: { command: 't = 0:0.01:5;\ny = lsim(T, t, t);', says: 'Simulates the response to a ramp input that rises 1 per second.' },
    seeAlso: ['step', 'impulse'],
  },
  {
    name: 'c2d',
    lang: 'matlab',
    kind: 'function',
    official: 'Convert model from continuous to discrete time',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'Your controller will run on a computer at a fixed rate, so you need a discrete-time version of a continuous model. The method changes the result: zero-order hold by default, Tustin to better match frequency response.',
    flags: [
      ['Ts', 'the sample time in seconds'],
      ["'zoh'", 'zero-order hold (the default)'],
      ["'tustin'", 'bilinear (Tustin) method'],
      ['opts', 'settings made with c2dOptions, such as prewarping'],
    ],
    example: { command: "Cd = c2d(C, 0.01, 'tustin');", says: 'Turns controller C into a version that runs at 100 Hz.' },
    seeAlso: ['c2dOptions', 'd2c'],
  },
  {
    name: 'stepinfo',
    lang: 'matlab',
    kind: 'function',
    official: 'Rise time, settling time, and other step-response characteristics',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want the numbers that describe a step response, to check them against requirements. Overshoot comes back in percent, and the default settling band is 2 percent.',
    flags: [
      ['S.RiseTime', 'time to go from 10% to 90% of the final value'],
      ['S.SettlingTime', 'time to stay within 2% of the final value'],
      ['S.Overshoot', 'how far past the final value it goes, in percent'],
      ['S.Peak, S.PeakTime', 'the highest value and when it happens'],
    ],
    example: { command: 'S = stepinfo(T);\nS.Overshoot', says: 'Shows the overshoot in percent, about 16.3 for this loop.' },
    seeAlso: ['step', 'assert'],
  },
  {
    name: 'lqr',
    lang: 'matlab',
    kind: 'function',
    official: 'Linear-Quadratic Regulator (LQR) design',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want the best state-feedback gains for a trade-off you choose: Q says how much you dislike state errors, R how much you dislike using control effort. Bigger Q gives a faster, more aggressive controller.',
    flags: [
      ['A, B', 'the state-space matrices'],
      ['Q', 'weight on the states (often made with diag)'],
      ['R', 'weight on the control input'],
    ],
    example: { command: 'K = lqr(A, B, diag([100 0]), 1)', says: 'Computes the gain row K that uses u = -K*x.' },
    seeAlso: ['diag', 'ss', 'place'],
  },
  {
    name: 'damp',
    lang: 'matlab',
    kind: 'function',
    official: 'Natural frequency and damping ratio',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want each pole described as a natural frequency and a damping ratio, which say how fast it oscillates and how quickly the wobble dies out. With no outputs it prints a table.',
    flags: [['[wn, zeta, p] = damp(T)', 'return the frequencies, damping ratios and poles']],
    example: { command: 'damp(T)', says: 'Prints each pole with its damping ratio, natural frequency and time constant.' },
    seeAlso: ['pole', 'pzmap'],
  },
  {
    name: 'minreal',
    lang: 'matlab',
    kind: 'function',
    official: 'Minimal realization or pole-zero cancellation',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want to cancel matching poles and zeros to get the simplest model. Be careful: cancelling an unstable pole makes the formula look calm while the real system still has that instability inside.',
    example: { command: "s = tf('s');\nminreal((s + 1)/((s + 1)*(s + 2)))", says: 'Shows 1 / (s + 2) after cancelling the matching (s + 1).' },
    seeAlso: ['tf', 'balred'],
  },
  {
    name: 'dcgain',
    lang: 'matlab',
    kind: 'function',
    official: 'Low-frequency (DC) gain of LTI system',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want the value a stable system settles to after a unit step, its steady-state gain. For an unstable system the number is meaningless, because the response never settles.',
    example: { command: 'dcgain(tf(4, [1 2 4]))', says: 'Shows ans = 1: the output ends up equal to the input.' },
    seeAlso: ['step', 'stepinfo'],
  },
  {
    name: 'bode',
    lang: 'matlab',
    kind: 'function',
    official: 'Bode frequency response of dynamic system',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want to see how a system amplifies and delays sine waves at each frequency. With no outputs it draws the plot; with outputs the magnitude comes back as a plain ratio (not dB) in a 3-D array, so use squeeze.',
    flags: [
      ['bode(L)', 'draw the magnitude and phase plots'],
      ['[mag, phase] = bode(G, w)', 'return values at the frequencies w (rad/s)'],
    ],
    example: { command: 'bode(L), grid on', says: 'Draws the Bode plot of the loop L with grid lines.' },
    seeAlso: ['margin', 'squeeze'],
  },
  {
    name: 'c2dOptions',
    lang: 'matlab',
    kind: 'function',
    official: 'Specify discretization method for continuous-time to discrete-time conversions',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want more control over c2d than a method name gives, such as Tustin with prewarping so a key frequency (like a notch) lands in exactly the right place.',
    flags: [
      ["'Method', 'tustin'", 'which conversion method to use'],
      ["'PrewarpFrequency', 60", 'the frequency (rad/s) to match exactly'],
    ],
    example: { command: "opts = c2dOptions('Method', 'tustin', 'PrewarpFrequency', 60);\nNd = c2d(N, 0.02, opts);", says: 'Discretizes the filter N at 50 Hz, matched exactly at 60 rad/s.' },
    seeAlso: ['c2d'],
  },
  {
    name: 'obsv',
    lang: 'matlab',
    kind: 'function',
    official: 'Observability of state-space model',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want to check whether a sensor lets you work out every state. If rank(obsv(A, C)) equals the number of states, the system is observable. Fine for small textbook systems; for big ones the rank test becomes numerically unreliable.',
    example: { command: 'rank(obsv(A, [0 1]))', says: 'Shows ans = 1: a rate gyro alone cannot tell you the angle.' },
    seeAlso: ['rank', 'ctrb', 'ss'],
  },
  {
    name: 'pid',
    lang: 'matlab',
    kind: 'function',
    official: 'PID controller in parallel form',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want a PID controller object you can put into a loop with feedback and analyze. The inputs are Kp, Ki and Kd in that order; put 0 for a term you do not use.',
    flags: [
      ['pid(Kp, Ki, Kd)', 'proportional, integral and derivative gains'],
      ['pid(Kp(:), 0, Kd(:))', 'an array of PD controllers, one per gain pair'],
    ],
    example: { command: 'C = pid(2, 0.5, 0.1);\nstepinfo(feedback(C*G, 1))', says: 'Makes a PID controller and reports the closed-loop step response numbers.' },
    seeAlso: ['pidtune', 'feedback'],
  },
  {
    name: 'balred',
    lang: 'matlab',
    kind: 'function',
    official: '(Not recommended) Model order reduction',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want a simpler model with fewer states that behaves almost the same, by dropping the states that matter least. MathWorks now recommends reducespec instead, but balred still works.',
    example: { command: 'G1 = balred(G, 1);', says: 'Makes a one-state approximation of G.' },
    seeAlso: ['minreal', 'hsvd', 'modred'],
  },

  // ------------------------------------------------------ Aerospace Toolbox
  {
    name: 'angle2quat',
    lang: 'matlab',
    kind: 'function',
    official: 'Convert rotation angles to quaternion',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You have yaw, pitch and roll and want the same attitude as a quaternion. Angles go in radians, the default order is yaw then pitch then roll (\'ZYX\'), and the scalar part comes first.',
    example: { command: 'q = angle2quat(deg2rad(30), 0, 0)', says: 'Shows q = 0.9659 0 0 0.2588, a 30 degree yaw.' },
    seeAlso: ['quat2dcm', 'angle2dcm', 'deg2rad'],
  },
  {
    name: 'lla2ecef',
    lang: 'matlab',
    kind: 'function',
    official: 'Convert geodetic coordinates to Earth-centered Earth-fixed (ECEF) coordinates',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You have latitude, longitude and altitude and want x, y, z in meters from Earth\'s center. Latitude and longitude go in degrees here (not radians), altitude in meters, one point per row.',
    example: { command: 'xyz = lla2ecef([28.5729, -80.6490, 3.0])', says: 'Gives the ECEF position of the Cape Canaveral pad in meters.' },
    seeAlso: ['dcmecef2ned'],
  },
  {
    name: 'convlength',
    lang: 'matlab',
    kind: 'function',
    official: 'Convert from length units to desired length units',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You need to change length units, such as feet to meters, without typing conversion factors by hand. Units are given as short text names like \'ft\' and \'m\'.',
    example: { command: "convlength(1000, 'ft', 'm')", says: 'Shows ans = 304.8000.' },
    seeAlso: ['convvel', 'convmass', 'convforce'],
  },
  {
    name: 'gravitywgs84',
    lang: 'matlab',
    kind: 'function',
    official: 'Implement 1984 World Geodetic System (WGS84) representation of Earth gravity',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You want realistic gravity that changes with latitude and height, instead of a fixed 9.81. Height comes first (meters), then geodetic latitude in degrees.',
    example: { command: 'g = gravitywgs84(10000, 28.5)', says: 'Shows about 9.7613 m/s^2, gravity 10 km above Cape Canaveral.' },
    seeAlso: ['atmosisa', 'gravitysphericalharmonic'],
  },
  {
    name: 'convvel',
    lang: 'matlab',
    kind: 'function',
    official: 'Convert from current velocity units to desired velocity units',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You need to change speed units, such as knots to meters per second. Units are short text names like \'kts\', \'m/s\' and \'km/h\'.',
    example: { command: "convvel(15, 'kts', 'm/s')", says: 'Shows ans = 7.7167.' },
    seeAlso: ['convlength', 'convang'],
  },
]
