import type { CommandRef } from './types'

export const COMMANDS: CommandRef[] = [
  {
    name: 'modred',
    lang: 'matlab',
    kind: 'function',
    official: 'Eliminate states from state-space models',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You have a state-space model with a state that barely matters (often a fast actuator) and want a smaller model without it. The default keeps the steady-state (DC) gain right; truncating instead can throw away an input path entirely, so compare step plots before and after.',
    flags: [
      ['sys', 'the state-space model to shrink'],
      ['elim', 'which states to remove, by number'],
      ["'Truncate'", "just delete the states instead of matching the DC gain (the default is 'MatchDC')"],
    ],
    example: { command: 'rMatch = modred(sys, 2);   % drop state 2, keep the DC gain', says: 'Returns a one-state model of the vehicle with the fast actuator state removed, and the same final value on a step.' },
    seeAlso: ['hsvd', 'balred', 'ss'],
  },
  {
    name: 'pidtune',
    lang: 'matlab',
    kind: 'function',
    official: 'PID tuning algorithm for linear plant model',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You have a plant model and want starting PID gains in one line. It aims for a 60 degree phase margin at a crossover it picks; the gains are only as good as the model, so check them with margin and step on the full model.',
    flags: [
      ['G', 'the plant model (tf, zpk or ss)'],
      ['type', "the controller shape: 'P', 'PI', 'PD', 'PID' or 'PIDF'"],
      ['wc', 'a crossover frequency to force, in rad/s'],
      ['opts', 'an options set from pidtuneOptions'],
      ['[C, info]', 'also return info.Stable, info.CrossoverFrequency and info.PhaseMargin'],
    ],
    example: { command: "C = pidtune(G, 'PI', 5);   % PI controller, crossover at 5 rad/s", says: 'Returns a PI controller for the plant G tuned so the loop crosses 0 dB at 5 rad/s.' },
    seeAlso: ['pidtuneOptions', 'pid', 'margin', 'step'],
  },
  {
    name: 'pidtuneOptions',
    lang: 'matlab',
    kind: 'function',
    official: 'Define options for pidtune function',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want pidtune to aim for something other than its defaults, such as a different phase margin or a design that leans toward tracking commands or rejecting disturbances.',
    flags: [
      ["'PhaseMargin'", 'the target phase margin in degrees'],
      ["'DesignFocus'", "'balanced' (default), 'reference-tracking' or 'disturbance-rejection'"],
    ],
    example: { command: "opts = pidtuneOptions('PhaseMargin', 45);", says: 'Makes an options set that tells pidtune to aim for 45 degrees of phase margin instead of 60.' },
    seeAlso: ['pidtune'],
  },
  {
    name: 'zpk',
    lang: 'matlab',
    kind: 'function',
    official: 'Zero-pole-gain model',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You know a system by its zeros, poles and gain, or you want to see an existing model in factored form so the poles and zeros are easy to read. Pass [] when there are no zeros.',
    flags: [
      ['z', 'the zeros, as a vector ([] for none)'],
      ['p', 'the poles, as a vector'],
      ['k', 'the gain'],
      ['zpk(G)', 'convert an existing model G to factored form'],
    ],
    example: { command: 'H = zpk(-1, [-2 -5], 3)', says: 'Makes and shows the model 3 (s+1) / ((s+2)(s+5)).' },
    seeAlso: ['tf', 'ss', 'pole'],
  },
  {
    name: 'frd',
    lang: 'matlab',
    kind: 'function',
    official: 'Frequency-response data model',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You have measured frequency response data (from a shaker test or a sine sweep) and want to treat it as a model, for example to check margins, without fitting equations to it.',
    flags: [
      ['response', 'the complex response at each frequency'],
      ['frequency', 'the matching frequencies, in rad/s by default'],
      ['frd(sys, w)', 'sample an existing model at the frequencies w'],
    ],
    example: { command: 'Pf = frd(resp, w);', says: 'Turns the measured complex responses resp at frequencies w (rad/s) into a model you can pass to bode or margin.' },
    seeAlso: ['bode', 'margin', 'tf'],
  },
  {
    name: 'sumblk',
    lang: 'matlab',
    kind: 'function',
    official: 'Summing junction for name-based interconnections',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You are building a closed loop with connect and need the comparison point, written as a little equation of signal names. The names must match the InputName and OutputName of the other blocks exactly.',
    flags: [
      ["'e = r - y'", 'the equation: output name on the left, signed input names on the right'],
    ],
    example: { command: "S = sumblk('e = r - y');", says: 'Makes a summing junction whose output e is the command r minus the measurement y.' },
    seeAlso: ['connect', 'feedback'],
  },
  {
    name: 'connect',
    lang: 'matlab',
    kind: 'function',
    official: 'Block diagram interconnections of dynamic systems',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You have several blocks (plant, controller, summing junctions) with named inputs and outputs and want the whole diagram as one model. It wires them by matching names, so a typo in one name leaves a signal unconnected.',
    flags: [
      ['sys1, ..., sysN', 'the blocks, each with InputName and OutputName set'],
      ['inputs', 'the signal names that become the inputs of the result'],
      ['outputs', 'the signal names that become the outputs'],
    ],
    example: { command: "T = connect(G, K, S, 'r', 'y');", says: 'Joins plant G, controller K and junction S into one closed-loop model from command r to output y.' },
    seeAlso: ['sumblk', 'feedback', 'tf'],
  },
  {
    name: 'impulse',
    lang: 'matlab',
    kind: 'function',
    official: 'Impulse response plot of dynamic system; impulse response data',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want to see how a system rings after a sharp kick, or get that response as numbers. With output arguments it returns the data instead of drawing.',
    flags: [
      ['sys', 'the model'],
      ['tFinal', 'how many seconds to simulate'],
      ['[y, t]', 'return the data instead of plotting'],
    ],
    example: { command: '[h, t] = impulse(T, 5);', says: 'Returns the impulse response of T over the first 5 seconds in h, with the matching times in t.' },
    seeAlso: ['step', 'initial', 'lsim'],
  },
  {
    name: 'initial',
    lang: 'matlab',
    kind: 'function',
    official: 'System response to initial states of state-space model',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want to see how a system with no input settles from a starting state, such as a vehicle released 1 degree off. It needs a state-space model, because the start is given as states.',
    flags: [
      ['sys', 'a state-space (ss) model'],
      ['x0', 'the starting state vector'],
      ['tFinal', 'how many seconds to simulate'],
    ],
    example: { command: '[y, t] = initial(cl, [1; 0], 6);', says: 'Simulates the closed loop cl for 6 seconds from 1 degree off and at rest, returning the output y and times t.' },
    seeAlso: ['step', 'impulse', 'ss'],
  },
  {
    name: 'd2c',
    lang: 'matlab',
    kind: 'function',
    official: 'Convert model from discrete to continuous time',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You have a discrete-time model (for example one identified from sampled data) and want the continuous-time model it came from. Use the same method the model was discretized with, or the answer will not match.',
    flags: [
      ["'zoh'", 'zero-order hold, the default'],
      ["'tustin'", 'the bilinear (Tustin) method'],
    ],
    example: { command: "sysc = d2c(sysd, 'zoh');", says: 'Turns the discrete model sysd back into continuous time, assuming a zero-order hold.' },
    seeAlso: ['c2d', 'ss', 'tf'],
  },
  {
    name: 'ctrb',
    lang: 'matlab',
    kind: 'function',
    official: 'Controllability of state-space model',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want to know if the inputs can steer every state. Check the rank of the result: full rank means controllable. The rank test is sensitive to rounding for badly scaled systems.',
    flags: [
      ['A', 'the state matrix'],
      ['B', 'the input matrix'],
    ],
    example: { command: 'Co = ctrb(A, B);   rank(Co) == size(A, 1)', says: 'Builds the controllability matrix [B, A*B, ...] and prints 1 (true) if it has full rank.' },
    seeAlso: ['obsv', 'rank', 'place'],
  },
  {
    name: 'place',
    lang: 'matlab',
    kind: 'function',
    official: 'Pole placement design',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want state feedback u = -K*x that puts the closed-loop poles exactly where you choose. Very fast poles give huge gains, and complex poles must come in conjugate pairs.',
    flags: [
      ['A, B', 'the state and input matrices'],
      ['p', 'the desired closed-loop poles'],
      ["place(A', C', p)'", 'the same trick for an observer gain'],
    ],
    example: { command: 'K = place(A, B, [-2+2i, -2-2i]);', says: 'Returns the gain K that makes the eigenvalues of A - B*K equal -2+2i and -2-2i.' },
    seeAlso: ['eig', 'ctrb', 'lqr'],
  },
  {
    name: 'eig',
    lang: 'matlab',
    kind: 'function',
    official: 'Eigenvalues and eigenvectors',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want the eigenvalues of a square matrix, for example to check that a feedback design put the closed-loop poles where you meant. For A - B*K they are the closed-loop poles; any with a positive real part means the loop is unstable.',
    flags: [
      ['A', 'a square matrix'],
      ['[V, D]', 'also return the eigenvectors (columns of V) and a diagonal matrix of eigenvalues D'],
    ],
    example: { command: 'eig(A - B*K)', says: 'Returns the closed-loop poles, such as -2+2i and -2-2i after the place design.' },
    seeAlso: ['place', 'pole', 'damp'],
  },
  {
    name: 'kalman',
    lang: 'matlab',
    kind: 'function',
    official: 'Design Kalman filter for state estimation',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You have a plant model and know roughly how noisy the process and the sensors are, and you want the best steady-state estimator gain. The noise covariances are guesses you tune, not facts.',
    flags: [
      ['sys', 'the plant, with the noise inputs included'],
      ['Qn', 'process noise covariance'],
      ['Rn', 'measurement noise covariance'],
      ['Nn', 'cross-covariance, usually 0'],
      ['sensors, known', 'which outputs are measured and which inputs are known'],
    ],
    example: { command: '[kest, L, P] = kalman(sys, 0.01, 1e-4);', says: 'Designs a Kalman estimator for sys with process noise 0.01 and sensor noise 1e-4, returning the estimator, its gain L and the error covariance P.' },
    seeAlso: ['lqr', 'ss', 'obsv'],
  },
  {
    name: 'hsvd',
    lang: 'matlab',
    kind: 'function',
    official: '(Not recommended) Hankel singular values of dynamic system',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: "You want to see how many states really matter before reducing a model: each value measures one state's share of the input-output behavior, and small ones can go. MathWorks now suggests balred for this, but hsvd still works.",
    flags: [
      ['sys', 'the model to analyze'],
    ],
    example: { command: 'hsv = hsvd(G)', says: 'Lists the Hankel singular values of G, largest first, such as 0.5275, 0.0308, 0.0037, 0.0005.' },
    seeAlso: ['balred', 'modred'],
  },
  {
    name: 'pzmap',
    lang: 'matlab',
    kind: 'function',
    official: 'Pole-zero map of dynamic system',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: "You want to see a system's poles (x) and zeros (o) on the complex plane, or get them as numbers. Poles in the right half plane mean the system is unstable.",
    flags: [
      ['sys', 'the model'],
      ['[p, z]', 'return the poles and zeros instead of plotting'],
    ],
    example: { command: '[p, z] = pzmap(G)', says: 'Returns the poles of G in p and its zeros in z; with no outputs it draws the map instead.' },
    seeAlso: ['pole', 'rlocus', 'zpk'],
  },
  {
    name: 'rlocus',
    lang: 'matlab',
    kind: 'function',
    official: 'Root locus of dynamic system',
    source: 'Control System Toolbox documentation (MathWorks)',
    when: 'You want to see how the closed-loop poles move as you turn up a single feedback gain, to pick a gain or see where the loop goes unstable. It assumes negative feedback around the open-loop model you give it.',
    flags: [
      ['sys', 'the open-loop model'],
      ['r = rlocus(sys, K)', 'return the closed-loop pole locations for the gains K'],
    ],
    example: { command: 'rlocus(L)', says: 'Draws the paths the closed-loop poles take as the gain on loop L rises from 0 toward infinity.' },
    seeAlso: ['pzmap', 'feedback', 'margin'],
  },
  {
    name: 'quatmultiply',
    lang: 'matlab',
    kind: 'function',
    official: 'Calculate product of two quaternions',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You want to combine two rotations stored as quaternions (scalar first). Order matters: quatmultiply(q, r) and quatmultiply(r, q) give different rotations.',
    flags: [
      ['q, r', 'quaternions as 1-by-4 rows (or m-by-4), scalar part first'],
    ],
    example: { command: 'qc = quatmultiply(qy, qp)', says: 'Returns the quaternion for the yaw rotation qy combined with the pitch rotation qp, as a 1-by-4 row.' },
    seeAlso: ['angle2quat', 'quat2dcm', 'dcm2quat'],
  },
  {
    name: 'dcmecef2ned',
    lang: 'matlab',
    kind: 'function',
    official: 'Convert geodetic latitude and longitude to direction cosine matrix',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You have a position or velocity in Earth-centered, Earth-fixed axes and want it in local North-East-Down axes at a launch site. The angles are in degrees.',
    flags: [
      ['lat', 'geodetic latitude, degrees'],
      ['lon', 'longitude, degrees'],
    ],
    example: { command: 'C = dcmecef2ned(28.57, -80.65);   v_ned = C * v_ecef;', says: 'Builds the rotation from ECEF to NED at the Cape and turns the ECEF vector v_ecef into north, east and down parts.' },
    seeAlso: ['lla2ecef', 'angle2dcm'],
  },
  {
    name: 'dcmbody2wind',
    lang: 'matlab',
    kind: 'function',
    official: 'Convert angle of attack and sideslip angle to direction cosine matrix',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You want to rotate a vector from body axes into wind axes, for example to split an aerodynamic force into lift and drag. The angles are in radians.',
    flags: [
      ['alpha', 'angle of attack, radians'],
      ['beta', 'sideslip angle, radians'],
    ],
    example: { command: 'Cwb = dcmbody2wind(deg2rad(4), deg2rad(2));', says: 'Builds the 3-by-3 rotation from body to wind axes for 4 degrees angle of attack and 2 degrees sideslip.' },
    seeAlso: ['angle2dcm', 'deg2rad'],
  },
  {
    name: 'convforce',
    lang: 'matlab',
    kind: 'function',
    official: 'Convert from force units to specified force units',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You have a thrust or load in one force unit and need it in another, such as pounds-force from an old engine sheet into newtons.',
    flags: [
      ['values', 'the numbers to convert'],
      ['inputUnits', "the unit they are in, such as 'lbf'"],
      ['outputUnits', "the unit you want, such as 'N'"],
    ],
    example: { command: "convforce(190000, 'lbf', 'N')", says: 'Returns about 845,000: 190,000 pounds-force in newtons.' },
    seeAlso: ['convmass', 'convlength', 'convvel'],
  },
  {
    name: 'convmass',
    lang: 'matlab',
    kind: 'function',
    official: 'Convert from mass units to specified mass units',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You have a mass in one unit and need it in another, such as pounds-mass or slugs into kilograms.',
    flags: [
      ['values', 'the numbers to convert'],
      ['inputUnits', "such as 'lbm' or 'slug'"],
      ['outputUnits', "such as 'kg'"],
    ],
    example: { command: "convmass(5000, 'lbm', 'kg')", says: 'Returns about 2268: 5000 pounds-mass in kilograms.' },
    seeAlso: ['convforce', 'convlength'],
  },
  {
    name: 'convang',
    lang: 'matlab',
    kind: 'function',
    official: 'Convert from angle units to specified angle units',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You need an angle in different units, such as degrees into radians before calling a trig function that expects radians.',
    flags: [
      ['values', 'the angles to convert'],
      ['inputUnits', "such as 'deg'"],
      ['outputUnits', "such as 'rad'"],
    ],
    example: { command: "convang(90, 'deg', 'rad')", says: 'Returns 1.5708, which is 90 degrees in radians.' },
    seeAlso: ['deg2rad', 'rad2deg'],
  },
  {
    name: 'satelliteScenario',
    lang: 'matlab',
    kind: 'class',
    official: 'Satellite scenario',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You want to simulate satellites and ground stations over a stretch of time, then ask when they can see each other. Everything else (satellites, stations, access) is added to this object.',
    flags: [
      ['startTime', 'a datetime when the scenario begins'],
      ['stopTime', 'a datetime when it ends'],
      ['sampleTime', 'the step between samples, in seconds'],
    ],
    example: { command: 'sc = satelliteScenario(startTime, stopTime, 30);', says: 'Creates an empty scenario running from startTime to stopTime with a step every 30 seconds.' },
    seeAlso: ['satellite', 'groundStation', 'datetime'],
  },
  {
    name: 'satellite',
    lang: 'matlab',
    kind: 'function',
    official: 'Add satellites to satellite scenario',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: "You want to put a spacecraft into a scenario, either from orbital elements or from a TLE file. The semi-major axis is in meters from Earth's center, not altitude, and the angles are in degrees.",
    flags: [
      ['sc', 'the scenario'],
      ['a, e, i, RAAN, argPeriapsis, trueAnomaly', 'the six orbital elements (meters and degrees)'],
      ['tleFile', 'a two-line element file instead of elements'],
      ['Name=', 'a label for the satellite'],
    ],
    example: { command: 'sat = satellite(sc, 6878137, 0, 97.4, 0, 0, 0, Name="EO-1");', says: 'Adds a satellite in a 500 km circular orbit at 97.4 degrees inclination, named EO-1.' },
    seeAlso: ['satelliteScenario', 'groundStation', 'access'],
  },
  {
    name: 'groundStation',
    lang: 'matlab',
    kind: 'function',
    official: 'Add ground station to satellite scenario',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You want a place on the ground that tracks satellites in the scenario. Setting a minimum elevation angle keeps passes that skim the horizon from counting.',
    flags: [
      ['sc', 'the scenario'],
      ['lat, lon', 'the location, in degrees'],
      ['Name=', 'a label'],
      ['MinElevationAngle=', 'lowest elevation in degrees at which a satellite counts as visible'],
    ],
    example: { command: 'gs = groundStation(sc, 28.5729, -80.6490, Name="Cape", MinElevationAngle=10);', says: 'Adds a ground station at Cape Canaveral that only counts a satellite as visible once it is 10 degrees above the horizon.' },
    seeAlso: ['satelliteScenario', 'satellite', 'access'],
  },
  {
    name: 'access',
    lang: 'matlab',
    kind: 'method',
    official: 'Add access analysis objects to satellite scenario',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You want to know when one object in the scenario can see another, such as a satellite and a ground station. It sets up the question; accessIntervals gives the answer.',
    flags: [
      ['sat, gs', 'the two objects that need a line of sight'],
    ],
    example: { command: 'ac = access(sat, gs);', says: 'Creates an access analysis between the satellite sat and the station gs.' },
    seeAlso: ['accessIntervals', 'satellite', 'groundStation'],
  },
  {
    name: 'accessIntervals',
    lang: 'matlab',
    kind: 'method',
    official: 'Intervals during which access status is true',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You set up an access analysis and now want the actual passes: when each one starts, ends and how long it lasts.',
    flags: [
      ['ac', 'an access object from access'],
    ],
    example: { command: 'intervals = accessIntervals(ac)', says: 'Returns a table with one row per pass, giving its start time, end time and duration in seconds.' },
    seeAlso: ['access', 'table'],
  },
  {
    name: 'groundTrack',
    lang: 'matlab',
    kind: 'method',
    official: 'Add ground track object to satellite or platform in scenario',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: "You want to see the path a satellite traces over the Earth's surface in the scenario viewer.",
    flags: [
      ['sat', 'the satellite'],
      ['LeadTime=', 'how far ahead to draw, in seconds'],
      ['TrailTime=', 'how much of the past track to draw, in seconds'],
    ],
    example: { command: 'groundTrack(sat, LeadTime=3*3600);', says: 'Draws the ground track of sat for the next 3 hours in the viewer.' },
    seeAlso: ['satellite', 'play'],
  },
  {
    name: 'play',
    lang: 'matlab',
    kind: 'method',
    official: 'Play satellite scenario simulation results on viewer',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You want to watch the scenario: satellites moving, ground tracks and access lines, in a 3-D globe viewer.',
    flags: [
      ['sc', 'the scenario to play'],
    ],
    example: { command: 'play(sc)', says: 'Opens the satellite scenario viewer and animates the scenario from start to stop.' },
    seeAlso: ['satelliteScenario', 'groundTrack'],
  },
  {
    name: 'atmosisa',
    lang: 'matlab',
    kind: 'function',
    official: 'Use International Standard Atmosphere model',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You need standard-day temperature, speed of sound, pressure and density at an altitude. The altitude is geopotential and in meters, and the outputs come back in a fixed order.',
    flags: [
      ['height', 'geopotential altitude in meters'],
      ['[T, a, P, rho]', 'temperature (K), speed of sound (m/s), pressure (Pa), density (kg/m^3)'],
    ],
    example: { command: '[T, a, P, rho] = atmosisa(10000)', says: 'Returns the standard atmosphere at 10 km: about 223 K, 299 m/s, 26,400 Pa and 0.41 kg/m^3.' },
    seeAlso: ['atmoscoesa', 'atmosnrlmsise00'],
  },
  {
    name: 'atmoscoesa',
    lang: 'matlab',
    kind: 'function',
    official: 'Use 1976 COESA model',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You need the 1976 US Standard Atmosphere, which goes higher than you usually need ISA for. Above about 84.9 km it extrapolates, so do not trust it for orbit.',
    flags: [
      ['height', 'geopotential altitude in meters'],
      ['[T, a, P, rho]', 'the same four outputs as atmosisa'],
    ],
    example: { command: '[T, a, P, rho] = atmoscoesa(50000)', says: 'Returns temperature, speed of sound, pressure and density at 50 km altitude, in SI units.' },
    seeAlso: ['atmosisa', 'atmosnrlmsise00'],
  },
  {
    name: 'atmosnrlmsise00',
    lang: 'matlab',
    kind: 'function',
    official: 'Implement mathematical representation of 2001 United States Naval Research Laboratory Mass Spectrometer and Incoherent Scatter Radar Exosphere',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You need air density high up, where satellites feel drag, and it depends on place, date and time of day. Density is its second output, a row of densities for each kind of gas, so check which column holds the total you want.',
    flags: [
      ['altitude', 'meters'],
      ['latitude, longitude', 'degrees'],
      ['year, dayOfYear', 'the date'],
      ['UTseconds', 'seconds since midnight UTC'],
    ],
    example: { command: '[T, rho] = atmosnrlmsise00(400e3, 28.57, -80.65, 2026, 152, 43200);', says: 'Returns temperatures and densities at 400 km above the Cape at noon UTC on day 152 of 2026.' },
    seeAlso: ['atmosisa', 'atmoscoesa'],
  },
  {
    name: 'gravitysphericalharmonic',
    lang: 'matlab',
    kind: 'function',
    official: 'Implement spherical harmonic representation of planetary gravity',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: "You need gravity more exact than a point mass, including the Earth's bulge and lumps, for orbit or trajectory work. The position is in meters in Earth-fixed (ECEF) axes, and higher degrees cost more time and memory.",
    flags: [
      ['r_ecef', 'positions in ECEF, meters, one row each'],
      ['model', "the gravity model, such as 'EGM2008'"],
      ['degree', 'how many harmonic terms to include'],
    ],
    example: { command: "[gx, gy, gz] = gravitysphericalharmonic(r_ecef, 'EGM2008', 2)", says: 'Returns the gravity components at position r_ecef using the EGM2008 model up to degree 2.' },
    seeAlso: ['gravitywgs84'],
  },
  {
    name: 'wrldmagm',
    lang: 'matlab',
    kind: 'function',
    official: 'Use World Magnetic Model',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: "You need the Earth's magnetic field at a place and date, for a magnetometer check or a compass heading. The field comes back in nanotesla in North-East-Down axes, and the date must be a decimal year.",
    flags: [
      ['height', 'meters'],
      ['latitude, longitude', 'degrees'],
      ['decimalYear', 'the date as a decimal year, from decyear'],
    ],
    example: { command: '[XYZ, H, DEC, DIP, F] = wrldmagm(0, 28.57, -80.65, decyear(2026, 1, 1));', says: 'Returns the magnetic field vector, horizontal strength, declination, inclination and total strength at the Cape on 1 January 2026.' },
    seeAlso: ['decyear'],
  },
  {
    name: 'decyear',
    lang: 'matlab',
    kind: 'function',
    official: 'Decimal year calculator',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'A function such as wrldmagm wants the date as a single number like 2026.5, and you have a year, month and day.',
    flags: [
      ['year, month, day', 'the date'],
      ['decyear(datetime)', 'convert a datetime instead'],
    ],
    example: { command: 'decyear(2026, 1, 1)', says: 'Returns 2026, because 1 January is the very start of the year.' },
    seeAlso: ['wrldmagm', 'datetime'],
  },
  {
    name: 'angle2dcm',
    lang: 'matlab',
    kind: 'function',
    official: 'Convert rotation angles to direction cosine matrix',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: "You have yaw, pitch and roll and want the 3-by-3 rotation matrix. The angles are in radians and the default order is 'ZYX'; pass degrees by mistake and you get a nonsense matrix with no error.",
    flags: [
      ['r1, r2, r3', 'the three angles in radians (yaw, pitch, roll by default)'],
      ['sequence', "the rotation order, 'ZYX' unless you say otherwise"],
    ],
    example: { command: 'C = angle2dcm(deg2rad(30), 0, 0)', says: 'Returns the rotation matrix for a 30 degree yaw.' },
    seeAlso: ['dcm2angle', 'angle2quat', 'quat2dcm'],
  },
  {
    name: 'dcm2angle',
    lang: 'matlab',
    kind: 'function',
    official: 'Create rotation angles from direction cosine matrix',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: "You have a rotation matrix and want the angles back. It uses the same default 'ZYX' order as angle2dcm and returns radians.",
    flags: [
      ['C', 'a 3-by-3 direction cosine matrix'],
      ['sequence', "the rotation order, 'ZYX' by default"],
    ],
    example: { command: '[r1, r2, r3] = dcm2angle(C);', says: 'Returns yaw, pitch and roll in radians for the rotation matrix C.' },
    seeAlso: ['angle2dcm', 'rad2deg'],
  },
  {
    name: 'quat2dcm',
    lang: 'matlab',
    kind: 'function',
    official: 'Convert quaternion to direction cosine matrix',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: "You store attitude as a quaternion (scalar first) and need the rotation matrix, for example to rotate a vector. Rows of vectors need a transpose: (quat2dcm(q) * v.').'.",
    flags: [
      ['q', 'a 1-by-4 quaternion, scalar part first'],
    ],
    example: { command: 'C = quat2dcm(q)', says: 'Returns the 3-by-3 rotation matrix for quaternion q.' },
    seeAlso: ['dcm2quat', 'angle2quat', 'quatmultiply'],
  },
  {
    name: 'dcm2quat',
    lang: 'matlab',
    kind: 'function',
    official: 'Convert direction cosine matrix to quaternion',
    source: 'Aerospace Toolbox documentation (MathWorks)',
    when: 'You have a rotation matrix and want the same rotation as a quaternion, which is smaller and easier to interpolate. A quaternion and its negative mean the same rotation, so do not be surprised by a flipped sign.',
    flags: [
      ['C', 'a 3-by-3 direction cosine matrix'],
    ],
    example: { command: 'q2 = dcm2quat(C)', says: 'Returns the scalar-first quaternion for the rotation matrix C.' },
    seeAlso: ['quat2dcm', 'angle2quat'],
  },
  {
    name: 'get',
    aliases: ['coder.mapping.api.get'],
    lang: 'matlab',
    kind: 'function',
    official: 'Get code mappings for model',
    source: 'Simulink Coder documentation (MathWorks)',
    when: "You want to set how a model's inports, outports and parameters appear in the generated C code, from a script. You get the model's code mappings object first, then call functions such as setInport on it.",
    flags: [
      ['model', 'the name of a loaded model'],
    ],
    example: { command: "cm = coder.mapping.api.get('rate_pi');", says: 'Returns the code mappings object for the model rate_pi.' },
    seeAlso: ['setInport'],
  },
  {
    name: 'setInport',
    lang: 'matlab',
    kind: 'method',
    official: 'Configure root-level inports for code and calibration file (a2l) generation',
    source: 'Simulink Coder documentation (MathWorks)',
    when: 'You want a model input to become a particular kind of variable in the generated C code, such as a global other code can write. It works on the code mappings object from coder.mapping.api.get.',
    flags: [
      ['cm', 'the code mappings object'],
      ['inport', 'the inport block name'],
      ["'StorageClass'", "how the variable is stored, such as 'ExportedGlobal' or 'ImportedExtern'"],
    ],
    example: { command: "setInport(cm, 'err', 'StorageClass', 'ExportedGlobal');", says: 'Makes the generated code define the inport err as an exported global variable.' },
    seeAlso: ['get'],
  },
  {
    name: 'new',
    aliases: ['slreq.new'],
    lang: 'matlab',
    kind: 'function',
    official: 'Create requirement set',
    source: 'Requirements Toolbox documentation (MathWorks)',
    when: 'You want to start a requirement set from a script instead of the Requirements Editor. It creates the .slreqx file in the current folder.',
    flags: [
      ['reqSetName', 'the name (or path) of the new set'],
    ],
    example: { command: "rs = slreq.new('pitchReqs');", says: 'Creates the requirement set pitchReqs.slreqx and returns it as rs.' },
    seeAlso: ['add'],
  },
  {
    name: 'add',
    lang: 'matlab',
    kind: 'method',
    official: 'Add requirements to requirement set',
    source: 'Requirements Toolbox documentation (MathWorks)',
    when: 'You want to add a requirement to a requirement set from code, with its ID and text filled in.',
    flags: [
      ['rs', 'the requirement set'],
      ["'Id', 'Summary', 'Description'", 'property names and values for the new requirement'],
    ],
    example: { command: "r1 = add(rs, 'Id', 'PC-1', 'Summary', 'Pitch rate limit');", says: 'Adds requirement PC-1 to the set rs and returns it as r1.' },
    seeAlso: ['new'],
  },
  {
    name: 'verify',
    lang: 'matlab',
    kind: 'function',
    official: 'Assess logical expression and log result',
    source: 'Simulink Test documentation (MathWorks)',
    when: 'You write an automatic pass/fail check inside a Test Sequence or Test Assessment block. It is checked at every time step while its step is active; a failure is logged but does not stop the simulation.',
    flags: [
      ['expression', 'the condition that must hold'],
    ],
    example: { command: 'verify(abs(theta - 5) < 0.1)', says: 'Checks at each step that the pitch theta is within 0.1 degree of 5, and records pass or fail.' },
    seeAlso: ['assert'],
  },
  {
    name: 'report',
    aliases: ['sltest.testmanager.report'],
    lang: 'matlab',
    kind: 'function',
    official: 'Generate report of test results',
    source: 'Simulink Test documentation (MathWorks)',
    when: 'You ran tests in the Test Manager and want a PDF or Word report to keep or hand to a reviewer.',
    flags: [
      ['resultObj', 'the results from sltest.testmanager.run'],
      ['filePath', 'where to save it, ending in .pdf, .docx or .zip'],
    ],
    example: { command: "sltest.testmanager.report(results, 'pitch_ctrl_report.pdf');", says: 'Writes a PDF report of the test results in results.' },
    seeAlso: ['run', 'exportResults'],
  },
  {
    name: 'run',
    aliases: ['sltest.testmanager.run'],
    lang: 'matlab',
    kind: 'function',
    official: 'Run tests with Test Manager',
    source: 'Simulink Test documentation (MathWorks)',
    when: "You want to run all the Simulink Test files loaded in the Test Manager from a script, for example in CI. It does not throw an error when a test fails, so check the result's NumFailed yourself. (A test runner from the MATLAB unit test framework also has a run method: runner.run(suite).)",
    example: { command: 'resultSet = sltest.testmanager.run;', says: 'Runs every loaded test file and returns a result set with counts such as NumPassed and NumFailed.' },
    seeAlso: ['report', 'exportResults', 'assertSuccess'],
  },
  {
    name: 'exportResults',
    aliases: ['sltest.testmanager.exportResults'],
    lang: 'matlab',
    kind: 'function',
    official: 'Export results set from Test Manager',
    source: 'Simulink Test documentation (MathWorks)',
    when: 'You want to keep the full Test Manager results, signals and all, in a file an engineer can open later, such as a CI artifact.',
    flags: [
      ['resultObjs', 'the result set from sltest.testmanager.run'],
      ['filePath', 'the .mldatx file to write'],
    ],
    example: { command: 'sltest.testmanager.exportResults(resultSet, "reports/attitude_results.mldatx");', says: 'Saves the result set to reports/attitude_results.mldatx.' },
    seeAlso: ['run', 'report'],
  },
  {
    name: 'fi',
    lang: 'matlab',
    kind: 'function',
    official: 'Create fixed-point numeric object',
    source: 'Fixed-Point Designer documentation (MathWorks)',
    when: 'You want to see exactly what value a number becomes when stored as a fixed-point integer on a processor without floating point. The value is rounded to the nearest step the word allows.',
    flags: [
      ['v', 'the value'],
      ['s', '1 for signed, 0 for unsigned'],
      ['w', 'word length in bits'],
      ['f', 'fraction length in bits'],
    ],
    example: { command: 'a = fi(pi, 1, 16, 10);', says: 'Stores pi as a signed 16-bit number with 10 fraction bits, which is really 3.1416015625.' },
    seeAlso: ['storedInteger', 'double'],
  },
  {
    name: 'storedInteger',
    lang: 'matlab',
    kind: 'method',
    official: 'Get stored integer value of fi object',
    source: 'Fixed-Point Designer documentation (MathWorks)',
    when: 'You want the raw integer a fixed-point value really holds, the number the generated C code works with.',
    flags: [
      ['a', 'a fi object'],
    ],
    example: { command: 'storedInteger(fi(pi, 1, 16, 10))', says: 'Returns 3217 as an int16, because 3217 / 2^10 is the stored value 3.1416015625.' },
    seeAlso: ['fi'],
  },
  {
    name: 'cvtest',
    lang: 'matlab',
    kind: 'function',
    official: 'Create model coverage test specification object',
    source: 'Simulink Coverage documentation (MathWorks)',
    when: 'You want to measure model coverage from a script: this sets up which model to run and which coverage kinds to record, such as decision, condition and MC/DC.',
    flags: [
      ['model', 'the model name'],
      ['settings.decision, .condition, .mcdc', 'set to 1 to record each kind of coverage'],
    ],
    example: { command: "testObj = cvtest('pitch_ctrl');   testObj.settings.mcdc = 1;", says: 'Creates a coverage test for the model pitch_ctrl and turns on MC/DC coverage.' },
    seeAlso: ['cvsim', 'cvhtml'],
  },
  {
    name: 'cvsim',
    lang: 'matlab',
    kind: 'function',
    official: 'Simulate and return model coverage results for test objects',
    source: 'Simulink Coverage documentation (MathWorks)',
    when: 'You set up a coverage test with cvtest and now want to run the model and collect the coverage data.',
    flags: [
      ['testObj', 'the test object from cvtest'],
    ],
    example: { command: 'covData = cvsim(testObj);', says: 'Simulates the model in testObj and returns the coverage it recorded.' },
    seeAlso: ['cvtest', 'cvhtml', 'sim'],
  },
  {
    name: 'cvhtml',
    lang: 'matlab',
    kind: 'function',
    official: 'Create HTML coverage report from model coverage objects',
    source: 'Simulink Coverage documentation (MathWorks)',
    when: 'You collected coverage data and want a report that shows each block green when fully covered and red when not. The model must be open.',
    flags: [
      ['fileName', 'the report name'],
      ['covData', 'the coverage data from cvsim'],
    ],
    example: { command: "cvhtml('pitch_ctrl_coverage', covData);", says: 'Writes an HTML coverage report named pitch_ctrl_coverage from covData.' },
    seeAlso: ['cvsim', 'cvtest'],
  },
  {
    name: 'load_system',
    lang: 'matlab',
    kind: 'function',
    official: 'Load Simulink model into memory',
    source: 'Simulink documentation (MathWorks)',
    when: 'A script needs to work with a model (set parameters, simulate) without opening a window. Only load models you trust, because a model can run code when it loads.',
    flags: [
      ['sys', 'the model name or file'],
    ],
    example: { command: 'load_system(mdl);', says: 'Loads the model named in mdl into memory, invisibly, so later commands can use it.' },
    seeAlso: ['open_system', 'new_system', 'sim'],
  },
  {
    name: 'new_system',
    lang: 'matlab',
    kind: 'function',
    official: 'Create Simulink model or library in memory',
    source: 'Simulink documentation (MathWorks)',
    when: 'You are building a model from a script. The new model exists only in memory until you save it with save_system.',
    flags: [
      ["'name'", 'the name of the new model'],
    ],
    example: { command: "new_system('stage_accel');", says: 'Creates an empty model called stage_accel in memory, without opening it.' },
    seeAlso: ['load_system', 'open_system', 'add_block'],
  },
  {
    name: 'open_system',
    lang: 'matlab',
    kind: 'function',
    official: 'Open model, library, subsystem, or block dialog box',
    source: 'Simulink documentation (MathWorks)',
    when: "You want a model (or a subsystem, or a block's dialog) open on screen. It loads the model first if needed.",
    flags: [
      ["'name'", 'a model name, or a block path such as VehicleSim/GNC'],
    ],
    example: { command: "open_system('VehicleSim');", says: 'Opens the model VehicleSim in the Simulink Editor.' },
    seeAlso: ['load_system', 'new_system'],
  },
  {
    name: 'extrinsic',
    aliases: ['coder.extrinsic'],
    lang: 'matlab',
    kind: 'function',
    official: 'Declare function as extrinsic and execute it in MATLAB',
    source: 'Simulink documentation (MathWorks)',
    when: 'Inside a MATLAB Function block you need a function the code subset does not allow, such as a plot or an old analysis routine, during simulation only. The call is left out of generated code, so never use it for anything the flight code needs, and assign the output first so the block knows its type.',
    flags: [
      ["'function'", 'the name of the function to run in MATLAB'],
    ],
    example: { command: "coder.extrinsic('legacy_density');", says: 'Tells the block to run legacy_density in MATLAB during simulation instead of compiling it.' },
  },
  {
    name: 'getSection',
    lang: 'matlab',
    kind: 'method',
    official: 'Return Simulink.data.dictionary.Section object to represent data dictionary section',
    source: 'Simulink documentation (MathWorks)',
    when: 'You want to add or read entries in a data dictionary from a script. Entries live in sections, and most design values go in Design Data.',
    flags: [
      ['dictionaryObj', 'the dictionary, from Simulink.data.dictionary.create or open'],
      ['sectionName', "'Design Data', 'Configurations' or 'Other Data'"],
    ],
    example: { command: "sec = getSection(dd, 'Design Data');", says: 'Returns the Design Data section of the dictionary dd, ready for addEntry.' },
    seeAlso: ['addEntry', 'saveChanges', 'addDataSource'],
  },
  {
    name: 'addDataSource',
    lang: 'matlab',
    kind: 'method',
    official: 'Add reference data dictionary to parent data dictionary',
    source: 'Simulink documentation (MathWorks)',
    when: 'Several component dictionaries need the same shared definitions, such as bus types. Reference one shared dictionary from each instead of copying the definitions. Call saveChanges to keep it.',
    flags: [
      ['dictionaryObj', 'the parent dictionary'],
      ['refDictionaryFile', 'the dictionary file to reference'],
    ],
    example: { command: "addDataSource(gnc, 'interfaces.sldd');", says: 'Makes the dictionary gnc see every entry defined in interfaces.sldd.' },
    seeAlso: ['getSection', 'saveChanges'],
  },
  {
    name: 'convertToModelReference',
    aliases: ['Simulink.SubSystem.convertToModelReference'],
    lang: 'matlab',
    kind: 'method',
    official: 'Convert subsystems to models',
    source: 'Simulink documentation (MathWorks)',
    when: 'A subsystem has grown into its own component and you want it in its own model file, so it can be developed, tested and put under version control on its own.',
    flags: [
      ['subsys', 'the block path of the subsystem'],
      ['modelName', 'the name of the new model'],
      ["'ReplaceSubsystem'", 'true swaps the subsystem for a Model block'],
      ["'AutoFix'", 'true lets it fix the problems it knows how to fix'],
    ],
    example: { command: "ok = Simulink.SubSystem.convertToModelReference('VehicleSim/GNC', 'GNC', 'ReplaceSubsystem', true, 'AutoFix', true);", says: 'Makes GNC.slx from the GNC subsystem, puts a Model block in its place, and returns true if it worked.' },
    seeAlso: ['open_system'],
  },
  {
    name: 'fromFile',
    aliases: ['TestSuite.fromFile', 'matlab.unittest.TestSuite.fromFile'],
    lang: 'matlab',
    kind: 'method',
    official: 'Create test suite from test file',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to run the tests in one file, such as a Simulink Test .mldatx file, through the MATLAB unit test framework.',
    flags: [
      ['file', 'the test file'],
      ['"Name"', 'keep only tests whose names match a pattern'],
    ],
    example: { command: 'suite = TestSuite.fromFile("tests/attitude_regression.mldatx");', says: 'Builds a test suite from every test in that file.' },
    seeAlso: ['addPlugin', 'assertSuccess'],
  },
  {
    name: 'addPlugin',
    lang: 'matlab',
    kind: 'method',
    official: 'Add plugin to test runner',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want a test runner to do something extra while it runs tests, such as write a JUnit XML report for a CI server.',
    flags: [
      ['runner', 'the test runner'],
      ['plugin', 'the plugin to attach'],
    ],
    example: { command: 'runner.addPlugin(XMLPlugin.producingJUnitFormat("reports/sltest.xml"));', says: 'Attaches a plugin to runner that writes the results to reports/sltest.xml.' },
    seeAlso: ['producingJUnitFormat', 'fromFile'],
  },
  {
    name: 'producingJUnitFormat',
    aliases: ['XMLPlugin.producingJUnitFormat', 'matlab.unittest.plugins.XMLPlugin.producingJUnitFormat'],
    lang: 'matlab',
    kind: 'method',
    official: 'Create plugin that produces test results in JUnit-style XML format',
    source: 'MATLAB documentation (MathWorks)',
    when: 'Your CI server (Jenkins, GitLab, GitHub Actions) reads JUnit XML to show which tests passed, and you want MATLAB tests to show up there. If the file exists, it is overwritten.',
    flags: [
      ['filename', 'the .xml file to write'],
    ],
    example: { command: 'p = XMLPlugin.producingJUnitFormat("reports/sltest.xml");', says: 'Makes a plugin that writes the test results to reports/sltest.xml in JUnit format.' },
    seeAlso: ['addPlugin'],
  },
  {
    name: 'assertSuccess',
    lang: 'matlab',
    kind: 'method',
    official: 'Assert test session ran without failure',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You ran tests in a script and want any failure to become an error, so matlab -batch exits with a nonzero code and the CI job turns red.',
    flags: [
      ['results', 'the TestResult array from running the tests'],
    ],
    example: { command: "matlab -batch \"results = runtests('tests'); assertSuccess(results)\"", says: 'Runs the tests and throws an error, failing the job, if any of them failed.' },
    seeAlso: ['fromFile', 'run', 'assert'],
  },
  {
    name: 'openProject',
    lang: 'matlab',
    kind: 'function',
    official: 'Load an existing project',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want a MATLAB or Simulink project open from a script, so its folders go on the path and its startup files run. Any project already open is closed first.',
    flags: [
      ['projectPath', 'the project folder or its .prj file'],
    ],
    example: { command: "proj = openProject('C:\\work\\launcher_gnc');", says: 'Opens the launcher_gnc project and returns it as proj.' },
    seeAlso: ['updateDependencies'],
  },
  {
    name: 'updateDependencies',
    lang: 'matlab',
    kind: 'method',
    official: 'Update project dependencies',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You changed files in a project and want its dependency graph (which file uses which) to be current before an impact check.',
    flags: [
      ['proj', 'the project, from openProject or currentProject'],
    ],
    example: { command: 'updateDependencies(proj);', says: 'Re-runs the dependency analysis for the project proj.' },
    seeAlso: ['openProject'],
  },
  {
    name: 'interpn',
    lang: 'matlab',
    kind: 'function',
    official: 'Interpolation for 1-D, 2-D, 3-D, and N-D gridded data in ndgrid format',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You have a table of values on a grid, such as an aerodynamic coefficient by Mach and angle of attack, and want values between the grid points. Rows follow the first grid vector (ndgrid order), unlike interp2, which expects meshgrid order.',
    flags: [
      ['X1, X2, ...', 'the grid vectors, one per dimension'],
      ['V', 'the table of values'],
      ['Xq1, Xq2, ...', 'the points to look up'],
    ],
    example: { command: 'interpn(M, alpha, CN, 1.0, 5)', says: 'Looks up the normal-force coefficient CN at Mach 1.0 and 5 degrees angle of attack, interpolating linearly.' },
    seeAlso: ['interp1', 'interp2'],
  },
  {
    name: 'double',
    lang: 'matlab',
    kind: 'type',
    official: 'Double-precision arrays',
    source: 'MATLAB documentation (MathWorks)',
    when: 'Every number in MATLAB is a double unless you ask otherwise. Call double(x) to turn another type, such as an integer or a fixed-point value, back into an ordinary number; integer math otherwise rounds and saturates.',
    flags: [
      ['double(X)', 'convert X to double precision'],
    ],
    example: { command: 'double(fi(pi, 1, 16, 10))', says: 'Returns 3.1416015625, the real value the fixed-point number holds.' },
    seeAlso: ['fi'],
  },
  {
    name: 'hilb',
    lang: 'matlab',
    kind: 'function',
    official: 'Hilbert matrix',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want a famously ill-conditioned test matrix to see how rounding errors grow when solving linear systems.',
    flags: [
      ['n', 'the size of the square matrix'],
    ],
    example: { command: 'H = hilb(8);   cond(H)', says: 'Makes the 8-by-8 Hilbert matrix and shows a condition number of about 1.5e10.' },
    seeAlso: ['cond', 'inv'],
  },
  {
    name: 'cond',
    lang: 'matlab',
    kind: 'function',
    official: 'Condition number for inversion',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to know how touchy a linear system is before trusting its answer. A value of 10^k means you can lose about k digits; Inf means the matrix is singular.',
    flags: [
      ['A', 'the matrix'],
    ],
    example: { command: 'cond(A)', says: 'Returns the condition number of A, near 1 for a well-behaved matrix and huge for a nearly singular one.' },
    seeAlso: ['hilb', 'inv', 'rank'],
  },
  {
    name: 'toc',
    lang: 'matlab',
    kind: 'function',
    official: 'Read elapsed time from stopwatch',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to time a piece of code. Call tic before it and toc after. Other code calling tic resets the shared stopwatch, so keep an id from tic when timing inside functions.',
    flags: [
      ['toc(id)', 'time since the tic that returned id, not the most recent one'],
    ],
    example: { command: 'id = tic;   x = A \\ b;   elapsed = toc(id)', says: 'Returns how many seconds the solve took, measured from the tic that returned id.' },
  },
  {
    name: 'isnan',
    lang: 'matlab',
    kind: 'function',
    official: 'Determine which array elements are NaN',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to find missing or invalid readings marked NaN. Comparing with x == NaN never works, because NaN is not equal to anything, even itself.',
    flags: [
      ['A', 'the array to test'],
    ],
    example: { command: 'if isnan(temps(k)) || temps(k) < -100', says: 'True when reading k is missing (NaN) or impossibly cold, so the loop can skip it.' },
    seeAlso: ['NaN', 'find'],
  },
  {
    name: 'mod',
    lang: 'matlab',
    kind: 'function',
    official: 'Remainder after division (modulo operation)',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want the remainder after dividing, for example to do something every other loop pass. For negative numbers mod keeps the sign of the divisor, unlike rem.',
    flags: [
      ['a', 'the number to divide'],
      ['m', 'the divisor'],
    ],
    example: { command: 'if mod(k, 2) ~= 0', says: 'True on odd passes, when k divided by 2 leaves a remainder of 1.' },
  },
  {
    name: 'legend',
    lang: 'matlab',
    kind: 'function',
    official: 'Add legend to axes',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You have more than one line on a plot and want a key that says which is which. Give the labels in the same order you plotted the lines.',
    flags: [
      ['labels', 'one text label per plotted line, in order'],
    ],
    example: { command: "legend('Altitude (km)', 'Speed (100 m/s)')", says: 'Adds a key to the plot naming the first line Altitude (km) and the second Speed (100 m/s).' },
    seeAlso: ['plot', 'title', 'xlabel'],
  },
  {
    name: 'logspace',
    lang: 'matlab',
    kind: 'function',
    official: 'Generate logarithmically spaced vector',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want points spread evenly on a log scale, such as frequencies for a Bode plot. The inputs are powers of ten, not the end values: logspace(-1, 3) runs from 0.1 to 1000.',
    flags: [
      ['a', 'the first point is 10^a'],
      ['b', 'the last point is 10^b'],
      ['n', 'how many points (50 if you leave it out)'],
    ],
    example: { command: 'f = logspace(-1, 3, 401);', says: 'Makes 401 frequencies from 0.1 Hz to 1000 Hz, evenly spaced on a log scale.' },
    seeAlso: ['linspace', 'semilogx'],
  },
  {
    name: 'semilogx',
    lang: 'matlab',
    kind: 'function',
    official: 'Semilog plot (x-axis has log scale)',
    source: 'MATLAB documentation (MathWorks)',
    when: 'Your x data spans many powers of ten, such as frequency, and you want it spread out evenly. If hold is already on, the axis may stay linear.',
    flags: [
      ['x, y', 'the data, as for plot'],
    ],
    example: { command: 'semilogx(f, magdB)', says: 'Plots the gain in dB against frequency with a logarithmic frequency axis.' },
    seeAlso: ['semilogy', 'plot', 'logspace'],
  },
  {
    name: 'semilogy',
    lang: 'matlab',
    kind: 'function',
    official: 'Semilog plot (y-axis has log scale)',
    source: 'MATLAB documentation (MathWorks)',
    when: 'Your y data spans many powers of ten, such as air density with altitude, and you want to see all of it. Zero and negative values cannot be shown on a log axis.',
    flags: [
      ['x, y', 'the data, as for plot'],
    ],
    example: { command: 'semilogy(t, rho)', says: 'Plots density against time with a logarithmic y axis.' },
    seeAlso: ['semilogx', 'plot'],
  },
  {
    name: 'patch',
    lang: 'matlab',
    kind: 'function',
    official: 'Create patches of colored polygons',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want a filled shape on a plot, such as a shaded band marking an engine burn in releases before xregion existed.',
    flags: [
      ['ax', 'the axes to draw in'],
      ['X, Y', 'the corner coordinates, in order'],
      ['C', 'the fill color as an RGB triplet'],
      ["'EdgeColor', 'FaceAlpha'", 'property name-value pairs for the outline and see-through amount'],
    ],
    example: { command: "patch(ax, [t1 t2 t2 t1], [yl(1) yl(1) yl(2) yl(2)], [1 0.8 0.5], 'EdgeColor', 'none')", says: 'Draws a light orange rectangle from time t1 to t2 covering the full height of the axes.' },
    seeAlso: ['xregion'],
  },
  {
    name: 'set',
    lang: 'matlab',
    kind: 'function',
    official: 'Set graphics object properties',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to change a property on several graphics objects at once, such as hiding tick labels on stacked plots. With one object, dot notation (ax.XTickLabel = []) does the same.',
    flags: [
      ['h', 'one graphics object or an array of them'],
      ['Name, Value', 'the property to change and its new value'],
    ],
    example: { command: "set(ax(1:4), 'XTickLabel', [])", says: 'Removes the x-axis tick labels from the first four axes, so only the bottom one shows time.' },
  },
  {
    name: 'grid',
    lang: 'matlab',
    kind: 'function',
    official: 'Display or hide axes grid lines',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want grid lines on a plot so values are easier to read off.',
    flags: [
      ['on / off', 'show or hide the grid'],
      ['minor', 'toggle the finer lines between ticks'],
      ['target', 'which axes, if not the current one'],
    ],
    example: { command: "grid(ax(k), 'on')", says: 'Turns grid lines on in the axes ax(k).' },
    seeAlso: ['plot', 'semilogx'],
  },
  {
    name: 'xregion',
    lang: 'matlab',
    kind: 'function',
    official: '1-D filled region between x-coordinates',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to shade a time span on a plot, such as an engine burn. It is new in R2023a; use patch in older releases.',
    flags: [
      ['ax', 'the axes (optional)'],
      ['x1, x2', 'where the region starts and ends'],
    ],
    example: { command: 'xregion(ax(k), 12.1, 50.9);', says: 'Shades the band from x = 12.1 to x = 50.9 in the axes ax(k).' },
    seeAlso: ['patch'],
  },
  {
    name: 'retime',
    lang: 'matlab',
    kind: 'function',
    official: 'Resample or aggregate data in timetable, and resolve duplicate or irregular times',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You have a timetable whose rows come at the wrong or uneven times and want it on a new regular time grid, by interpolating or by averaging into bins.',
    flags: [
      ['TT', 'the timetable'],
      ['newTimes', "a vector of new times, or a step such as 'secondly'"],
      ['method', "how to fill values: 'linear', 'mean', and so on"],
    ],
    example: { command: "baro5 = retime(baro, seconds(0:0.2:1)', 'linear');", says: 'Resamples the barometer timetable to one row every 0.2 seconds, interpolating linearly.' },
    seeAlso: ['timetable', 'synchronize', 'seconds'],
  },
  {
    name: 'eye',
    lang: 'matlab',
    kind: 'function',
    official: 'Identity matrix',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You need an identity matrix: ones on the diagonal and zeros elsewhere, such as the output matrix when every state is measured.',
    flags: [
      ['n', 'the size of the square matrix'],
      ['m, n', 'a rectangular one'],
    ],
    example: { command: 'eye(3)', says: 'Returns the 3-by-3 identity matrix.' },
    seeAlso: ['zeros', 'ones', 'diag'],
  },
  {
    name: 'length',
    lang: 'matlab',
    kind: 'function',
    official: 'Length of largest array dimension',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want the number of elements in a vector. For a matrix it returns the larger dimension, not the number of rows, which surprises people; use size or numel when that matters.',
    flags: [
      ['X', 'the array'],
    ],
    example: { command: 'length(zeros(3, 7))', says: 'Returns 7, the larger of the two dimensions.' },
    seeAlso: ['size', 'numel'],
  },
  {
    name: 'isfield',
    lang: 'matlab',
    kind: 'function',
    official: 'Determine if input is structure array field',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to check that a struct has a field before reading it, so a missing field does not stop the program.',
    flags: [
      ['S', 'the struct'],
      ['field', 'the field name to look for'],
    ],
    example: { command: "isfield(stage, 'thrust')", says: 'Returns 1 (true) if the struct stage has a field called thrust, otherwise 0.' },
    seeAlso: ['struct'],
  },
  {
    name: 'table',
    lang: 'matlab',
    kind: 'type',
    official: 'Table array with named variables that can contain different types',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You have columns of data of different types (times, numbers, text) that belong together, like a spreadsheet. The variable names become the column names.',
    flags: [
      ['var1, var2, ...', 'column vectors with the same number of rows'],
    ],
    example: { command: 'T = table(t, alt);', says: 'Makes a table with columns named t and alt, one row per sample.' },
    seeAlso: ['timetable', 'readtable', 'writetable'],
  },
  {
    name: 'categorical',
    lang: 'matlab',
    kind: 'type',
    official: 'Array that contains values assigned to categories',
    source: 'MATLAB documentation (MathWorks)',
    when: 'Your data takes a few fixed values, such as flight phase, and you want to group and count by them. It stores them compactly and treats a misspelled value as a different category, so check the category list.',
    flags: [
      ['data', 'the values'],
      ['valueset', 'the full list of allowed categories, in order'],
      ["'Ordinal', true", 'the categories have an order, so you can compare them with <'],
    ],
    example: { command: "phase = categorical({'boost'; 'boost'; 'coast'});", says: 'Makes a categorical array with the categories boost and coast.' },
    seeAlso: ['categories', 'countcats'],
  },
  {
    name: 'categories',
    lang: 'matlab',
    kind: 'function',
    official: 'List of categories in categorical array',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to see which categories a categorical array has, including ones no element uses yet.',
    flags: [
      ['A', 'the categorical array'],
    ],
    example: { command: 'categories(phase)', says: "Returns {'boost'; 'coast'}, the categories of phase." },
    seeAlso: ['categorical', 'countcats'],
  },
  {
    name: 'countcats',
    lang: 'matlab',
    kind: 'function',
    official: 'Count occurrences of categorical array elements by category',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to know how many elements fall in each category, such as how many samples were taken in each flight phase. Undefined elements are not counted.',
    flags: [
      ['A', 'the categorical array'],
    ],
    example: { command: 'countcats(phase)', says: 'Returns one count per category, in the order categories lists them, such as [4; 2].' },
    seeAlso: ['categorical', 'categories'],
  },
  {
    name: 'narginchk',
    lang: 'matlab',
    kind: 'function',
    official: 'Validate number of input arguments',
    source: 'MATLAB documentation (MathWorks)',
    when: 'Your function accepts a range of input counts and you want a clear error when it is called with too few or too many.',
    flags: [
      ['minArgs', 'the fewest inputs allowed'],
      ['maxArgs', 'the most inputs allowed'],
    ],
    example: { command: 'narginchk(2, 3);', says: 'Does nothing if the function got 2 or 3 inputs; otherwise stops with Not enough input arguments or Too many input arguments.' },
    seeAlso: ['validateattributes', 'error'],
  },
  {
    name: 'lower',
    lang: 'matlab',
    kind: 'function',
    official: 'Convert strings to lowercase',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You compare text that people type, such as option names, and want Weights and weights to count as the same.',
    flags: [
      ['str', 'the text to convert'],
    ],
    example: { command: 'switch lower(varargin{k})', says: 'Turns the option name into lowercase before the switch compares it.' },
  },
  {
    name: 'min',
    lang: 'matlab',
    kind: 'function',
    official: 'Minimum elements of array',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want the smallest value, or to cap a value from above. Paired with max it clamps a value into a range. On a matrix it works down each column.',
    flags: [
      ['A', 'the array'],
      ['min(A, B)', 'the smaller of A and B, element by element'],
      ['[M, I]', 'also return the position of the minimum'],
    ],
    example: { command: 'dv = min(max(dv, 0), 50);', says: 'Clamps the burn dv so it is never below 0 or above 50.' },
    seeAlso: ['max'],
  },
  {
    name: 'cell',
    lang: 'matlab',
    kind: 'type',
    official: 'Cell array',
    source: 'MATLAB documentation (MathWorks)',
    when: "You need a container whose slots can hold different things, such as names of different lengths or function handles. Call cell(1, n) to make the empty slots first; read a slot's contents with curly braces, c{k}.",
    flags: [
      ['cell(m, n)', 'an m-by-n cell array of empty cells'],
    ],
    example: { command: 'names = cell(1, 3);', says: 'Makes a 1-by-3 cell array of empty slots, ready to fill.' },
    seeAlso: ['cellfun', 'struct'],
  },
  {
    name: 'cellfun',
    lang: 'matlab',
    kind: 'function',
    official: 'Apply function to each cell in cell array',
    source: 'MATLAB documentation (MathWorks)',
    when: "You want to call the same function on the contents of every cell and collect the results. If the results are not single numbers, add 'UniformOutput', false.",
    flags: [
      ['func', 'the function handle to apply'],
      ['C', 'the cell array'],
      ["'UniformOutput', false", 'return the results in a cell array'],
    ],
    example: { command: 'cellfun(@(f) f(10), fs)', says: 'Calls each function handle stored in fs with 10 and returns the answers as one array.' },
    seeAlso: ['cell'],
  },
  {
    name: 'nnz',
    lang: 'matlab',
    kind: 'function',
    official: 'Number of nonzero matrix elements',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to count how many elements meet a condition: make a true/false mask and count the trues.',
    flags: [
      ['X', 'the array or logical mask'],
    ],
    example: { command: 'nnz(abs(az) >= 16)', says: 'Returns how many accelerometer samples hit the 16 g limit.' },
    seeAlso: ['find', 'numel'],
  },
  {
    name: 'log',
    lang: 'matlab',
    kind: 'function',
    official: 'Natural logarithm',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You need ln(x), such as in the rocket equation. In MATLAB log is base e; use log10 for base 10. Negative inputs give complex results, not an error.',
    flags: [
      ['X', 'the input'],
    ],
    example: { command: 'dv = isp * g0 * log(m0 / mf);', says: 'Computes the stage delta-v with the natural logarithm of the mass ratio.' },
    seeAlso: ['log10', 'exp'],
  },
  {
    name: 'num2str',
    lang: 'matlab',
    kind: 'function',
    official: 'Convert numbers to character array',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to stick a number into a piece of text, such as a label or a message. For control over the format, sprintf is often clearer.',
    flags: [
      ['A', 'the number'],
      ['precision', 'the most significant digits to show, as in num2str(pi, 8)'],
    ],
    example: { command: "disp(['Apogee: ' num2str(apo) ' m'])", says: 'Prints a line such as Apogee: 1250 m.' },
    seeAlso: ['sprintf', 'disp'],
  },
  {
    name: 'fopen',
    lang: 'matlab',
    kind: 'function',
    official: 'Open file or obtain information about open files',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to write or read a text file line by line. It returns a file id, or -1 if it failed, so check it; and always fclose when done.',
    flags: [
      ['filename', 'the file'],
      ["'w'", 'write, replacing what was there'],
      ["'a'", 'append to the end'],
      ["'r'", 'read (the default)'],
    ],
    example: { command: "fid = fopen('hop_log.txt', 'w');", says: 'Opens hop_log.txt for writing, replacing any old file, and returns its id in fid.' },
    seeAlso: ['fclose', 'fprintf'],
  },
  {
    name: 'fclose',
    lang: 'matlab',
    kind: 'function',
    official: 'Close one or all open files',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You finished with a file opened by fopen. Until you close it, some of what you wrote may not be on disk yet.',
    flags: [
      ['fid', 'the file id from fopen'],
    ],
    example: { command: 'fclose(fid);', says: 'Closes the file with id fid.' },
    seeAlso: ['fopen'],
  },
  {
    name: 'odeset',
    lang: 'matlab',
    kind: 'function',
    official: 'Create or modify options structure for ODE and PDE solvers',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to control how accurate an ODE solver is, or cap its step size. Tighter tolerances cost more steps.',
    flags: [
      ["'RelTol'", 'allowed error relative to the size of each value'],
      ["'AbsTol'", 'allowed error when values are near zero'],
      ["'MaxStep'", 'the longest step the solver may take'],
    ],
    example: { command: "opts = odeset('RelTol', 1e-6, 'AbsTol', 1e-6, 'MaxStep', T/50);", says: 'Makes solver options asking for 1e-6 relative and absolute accuracy and steps no longer than T/50.' },
    seeAlso: ['ode45', 'ode23'],
  },
  {
    name: 'ode23',
    lang: 'matlab',
    kind: 'function',
    official: 'Solve nonstiff differential equations — low order method',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want to integrate an ODE with a cheaper, lower-accuracy method than ode45, for rough answers or mildly stiff problems. At tight tolerances it needs many more steps than ode45.',
    flags: [
      ['odefun', 'a function handle f(t, x) returning dx/dt'],
      ['tspan', '[t0 tf], the time span'],
      ['y0', 'the starting state'],
      ['options', 'a structure from odeset'],
    ],
    example: { command: 'sol = ode23(f, [0 T], x0, opts);', says: 'Integrates dx/dt = f(t, x) from 0 to T starting at x0, using the options in opts.' },
    seeAlso: ['ode45', 'odeset'],
  },
  {
    name: 'rng',
    lang: 'matlab',
    kind: 'function',
    official: 'Control random number generator',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You use random numbers (noise, Monte Carlo runs) and want the same "random" results every run, so a bug can be reproduced. Seed once at the top, not inside a loop.',
    flags: [
      ['seed', 'a nonnegative integer, or "shuffle" to seed from the clock'],
    ],
    example: { command: 'rng(1);', says: 'Seeds the generator with 1, so randn gives the same sequence every time the script runs.' },
    seeAlso: ['randn'],
  },
  {
    name: 'datetime',
    lang: 'matlab',
    kind: 'type',
    official: 'Arrays that represent points in time',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You need a real date and time, such as a scenario start, that you can add durations to and compare. Set TimeZone when it matters, or times are "unzoned".',
    flags: [
      ['Y, M, D, H, MI, S', 'the date and time parts'],
      ['TimeZone=', 'the time zone, such as "UTC"'],
    ],
    example: { command: 'startTime = datetime(2026, 9, 27, 0, 0, 0, TimeZone="UTC");', says: 'Makes the moment midnight UTC on 27 September 2026.' },
    seeAlso: ['days', 'seconds', 'timetable'],
  },
  {
    name: 'days',
    lang: 'matlab',
    kind: 'function',
    official: 'Duration in days',
    source: 'MATLAB documentation (MathWorks)',
    when: 'You want a length of time in whole 24-hour days, to add to a datetime.',
    flags: [
      ['X', 'the number of days'],
    ],
    example: { command: 'stopTime = startTime + days(1);', says: 'Sets stopTime to exactly 24 hours after startTime.' },
    seeAlso: ['datetime', 'seconds'],
  },
  {
    name: 'rad2deg',
    lang: 'matlab',
    kind: 'function',
    official: 'Convert angle from radians to degrees',
    source: 'MATLAB documentation (MathWorks)',
    when: 'Functions such as dcm2angle return radians and you want degrees to read or print.',
    flags: [
      ['R', 'the angles in radians'],
    ],
    example: { command: 'rad2deg([r1 r2 r3])', says: 'Returns the three angles in degrees, such as 30 0 0.' },
    seeAlso: ['deg2rad', 'convang'],
  },
]
