import type { CommandRef } from './types'

export const COMMANDS: CommandRef[] = [
  // ---- Keywords: defining functions and classes ----
  {
    name: 'def',
    lang: 'python',
    kind: 'keyword',
    official: 'A function definition defines a user-defined function object',
    source: 'Python language reference (help("def"))',
    when: 'You want to give a piece of code a name so you can run it again and again, maybe with different inputs each time. Defining a function does not run it: the body only runs when you call the function with round brackets.',
    flags: [
      ['name(a, b)', 'the function name, then the parameters: the names the inputs get inside the function'],
      ['b=10', 'a default value, used when the caller leaves that input out'],
      ['*args', 'collects any extra inputs into a tuple'],
      ['**kwargs', 'collects any extra name=value inputs into a dictionary'],
      ['-> float', 'a note saying what type the function hands back (Python does not check it)'],
    ],
    example: {
      command: 'def delta_v(isp, m0, m1):\n    return isp * 9.81 * math.log(m0 / m1)',
      says: 'Defines a function called delta_v. Calling delta_v(300, 5000, 2000) works out the rocket equation and gives back about 2697.',
    },
    seeAlso: ['return', 'lambda', 'class', 'yield'],
  },
  {
    name: 'return',
    lang: 'python',
    kind: 'keyword',
    official: '"return" leaves the current function call with the expression list (or "None") as return value.',
    source: 'Python language reference (help("return"))',
    when: 'Inside a function, when the answer is ready and you want to hand it back to whoever called it. The function stops right there, so any lines after it do not run. A function that never reaches a return gives back None.',
    flags: [['return a, b', 'hands back several values at once, packed into a tuple']],
    example: {
      command: 'def fuel_left(start, burned):\n    return start - burned',
      says: 'fuel_left(900, 250) gives back 650, which you can store with left = fuel_left(900, 250).',
    },
    seeAlso: ['def', 'yield', 'None'],
  },
  {
    name: 'lambda',
    lang: 'python',
    kind: 'keyword',
    official: 'Lambda expressions (sometimes called lambda forms) are used to create anonymous functions.',
    source: 'Python language reference (help("lambda"))',
    when: 'You need a tiny throwaway function in one spot, most often as the key= for sorted, max or min. A lambda can only hold one expression, no statements like if blocks or loops; anything longer deserves a def.',
    flags: [['lambda x: x * 2', 'the inputs go before the colon, the value to hand back after it']],
    example: {
      command: 'sorted(crew, key=lambda p: p["age"])',
      says: 'Sorts the crew list by each person\'s age, youngest first.',
    },
    seeAlso: ['def', 'sorted', 'max', 'min'],
  },
  {
    name: 'class',
    lang: 'python',
    kind: 'keyword',
    official: 'A class definition defines a class object',
    source: 'Python language reference (help("class"))',
    when: 'You want to make your own kind of object that bundles data and the functions that work on it, like a Rocket with a mass and a burn method. Methods inside a class take self as their first input, which is the object the method was called on; forgetting self is the classic first mistake.',
    flags: [
      ['class Rocket:', 'a new class with no parent (it still inherits from object)'],
      ['class Probe(Rocket):', 'a new class that inherits everything from Rocket and can add or change parts'],
      ['__init__', 'the method that runs when you make a new object, to set its starting data'],
    ],
    example: {
      command: 'class Rocket:\n    def __init__(self, name):\n        self.name = name',
      says: 'Defines Rocket. Rocket("Artemis").name is then "Artemis".',
    },
    seeAlso: ['def', 'super', 'object', 'property', 'classmethod', 'staticmethod', 'isinstance'],
  },
  {
    name: 'yield',
    lang: 'python',
    kind: 'keyword',
    official: 'Using yield in a function definition is sufficient to cause that definition to create a generator function instead of a normal function.',
    source: 'Python language reference (help("yield"))',
    when: 'You want a function that hands out values one at a time, pausing between them, instead of building a whole list at once. Calling the function runs none of its body yet; it gives you a generator, and the code only runs as you ask for values with a for loop or next.',
    flags: [
      ['yield value', 'hands out one value and pauses until the next one is asked for'],
      ['yield from other()', 'hands out every value from another generator, one by one, then carries on'],
    ],
    example: {
      command: 'def countdown(n):\n    while n > 0:\n        yield n\n        n -= 1',
      says: 'list(countdown(3)) gives [3, 2, 1]. Each value is made only when it is asked for.',
    },
    seeAlso: ['def', 'return', 'next', 'iter', 'StopIteration'],
  },
  {
    name: 'async',
    lang: 'python',
    kind: 'keyword',
    official: 'Functions defined with "async def" syntax are always coroutine functions, even if they do not contain "await" or "async" keywords.',
    source: 'Python language reference (help("async"))',
    when: 'You are writing code that spends most of its time waiting, such as talking to many sensors or network connections, and you want the waiting to overlap. Calling an async def function does not run it; it gives a coroutine (a paused task) that has to be awaited or handed to asyncio.run.',
    flags: [['async def', 'defines a coroutine function, one that can pause at each await']],
    example: {
      command: 'async def read_sensor(name):\n    await asyncio.sleep(1)\n    return name, 21.5',
      says: 'Defines a task that waits one second without blocking the others, then returns a reading.',
    },
    seeAlso: ['await', 'def', 'asyncio.gather', 'asyncio.sleep'],
  },
  {
    name: 'await',
    lang: 'python',
    kind: 'keyword',
    official: 'Suspend the execution of coroutine on an awaitable object. Can only be used inside a coroutine function.',
    source: 'Python language reference (help("await"))',
    when: 'Inside an async def function, to wait for another task to finish and get its result, letting other tasks run in the meantime. Using it outside an async def is a SyntaxError, and forgetting it leaves you holding an unstarted coroutine instead of the answer.',
    example: {
      command: 'readings = await asyncio.gather(read_sensor("imu"), read_sensor("gps"))',
      says: 'Starts both sensor reads together and waits until both are done, so it takes about one second, not two.',
    },
    seeAlso: ['async', 'asyncio.gather', 'asyncio.sleep'],
  },
  {
    name: 'global',
    lang: 'python',
    kind: 'keyword',
    official: 'The "global" statement is a declaration which holds for the entire current code block. It means that the listed identifiers are to be interpreted as globals.',
    source: 'Python language reference (help("global"))',
    when: 'Inside a function, when you must change a variable that lives at the top level of the file. Without it, assigning to that name makes a new local variable instead. Needing global is usually a sign to pass the value in and return it instead.',
    example: {
      command: 'launches = 0\ndef launch():\n    global launches\n    launches += 1',
      says: 'Each call to launch() adds one to the launches variable at the top of the file.',
    },
    seeAlso: ['nonlocal', 'def'],
  },
  {
    name: 'nonlocal',
    lang: 'python',
    kind: 'keyword',
    official: 'The "nonlocal" statement causes the listed identifiers to refer to previously bound variables in the nearest enclosing scope excluding globals.',
    source: 'Python language reference (help("nonlocal"))',
    when: 'You have a function inside another function, and the inner one needs to change a variable that belongs to the outer one, such as a counter in a closure (an inner function that remembers the outer one\'s variables). Without it, count += 1 in the inner function fails with UnboundLocalError.',
    example: {
      command: 'def make_counter():\n    count = 0\n    def tick():\n        nonlocal count\n        count += 1\n        return count\n    return tick',
      says: 'Each call to the returned tick() adds one to the same count: 1, then 2, then 3.',
    },
    seeAlso: ['global', 'def'],
  },
  // ---- Keywords: making decisions ----
  {
    name: 'if',
    lang: 'python',
    kind: 'keyword',
    official: 'The "if" statement is used for conditional execution',
    source: 'Python language reference (help("if"))',
    when: 'You want some lines to run only when a condition is true. The lines that belong to the if must be indented under it, and the line itself ends with a colon. Remember == compares while = stores, so if x = 5: is an error.',
    flags: [
      ['elif', 'another condition to try if the ones above were false'],
      ['else', 'what to do when no condition was true'],
      ['a if cond else b', 'the one-line form: gives a when cond is true, b otherwise'],
    ],
    example: {
      command: 'if fuel < 10:\n    print("Low fuel, return to base")',
      says: 'Prints the warning only when fuel is below 10; otherwise nothing happens.',
    },
    seeAlso: ['elif', 'else', 'match', 'bool'],
  },
  {
    name: 'elif',
    lang: 'python',
    kind: 'keyword',
    official: 'It selects exactly one of the suites by evaluating the expressions one by one until one is found to be true (see section Boolean operations for the definition of true and false); then that suite is executed (and no other part of the "if" statement is executed or evaluated).',
    source: 'Python language reference (help("elif"))',
    when: 'After an if, when you have more than two cases to choose between. Python checks the conditions from the top down and runs only the first one that is true, so put the most specific test first.',
    example: {
      command: 'if speed > 11.2:\n    print("escape")\nelif speed > 7.8:\n    print("orbit")\nelse:\n    print("falls back")',
      says: 'With speed 9.0 it prints orbit. Only one branch runs.',
    },
    seeAlso: ['if', 'else', 'match'],
  },
  {
    name: 'else',
    lang: 'python',
    kind: 'keyword',
    official: 'If all expressions are false, the suite of the "else" clause, if present, is executed.',
    source: 'Python language reference (help("else"))',
    when: 'At the end of an if/elif chain, for the case where nothing else matched. It can also follow a loop (runs when the loop ends without break) or a try (runs when no exception happened), which surprises people who have only seen it after if.',
    example: {
      command: 'if countdown == 0:\n    print("Liftoff")\nelse:\n    print(countdown, "seconds")',
      says: 'Prints Liftoff when countdown is 0, and otherwise how many seconds are left.',
    },
    seeAlso: ['if', 'elif', 'try', 'for', 'while'],
  },
  {
    name: 'match',
    lang: 'python',
    kind: 'keyword',
    official: 'The match statement is used for pattern matching.',
    source: 'Python language reference (help("compound"), The match statement)',
    when: 'You want to compare one value against several shapes or values and run the first case that fits, like a tidier chain of elifs. It needs Python 3.10 or newer. A bare name in a case pattern does not compare against a variable; it catches anything and stores it in that name.',
    flags: [
      ['case pattern:', 'one shape to try; the first one that fits runs'],
      ['case _:', 'the catch-all, used when nothing above fit'],
      ['case "a" | "b":', 'fits if the value matches either pattern'],
      ['case x if x > 0:', 'a guard: the case only fits if the extra condition is also true'],
    ],
    example: {
      command: 'match command:\n    case "launch":\n        start_engines()\n    case "abort" | "stop":\n        shut_down()\n    case _:\n        print("unknown command")',
      says: 'Runs start_engines() for "launch", shut_down() for "abort" or "stop", and prints a message for anything else.',
    },
    seeAlso: ['case', 'if', 'elif', 'else'],
  },
  {
    name: 'case',
    lang: 'python',
    kind: 'keyword',
    official: 'Pattern matching takes a pattern as input (following "case") and a subject value (following "match").',
    source: 'Python language reference (help("compound"), The match statement)',
    when: 'Inside a match block, one line per shape you want to handle. Cases are tried from the top down and only the first one that fits runs. Put case _: last, because it fits everything and nothing below it would ever run.',
    flags: [
      ['case _:', 'fits anything; use it last as the default'],
      ['case (x, y):', 'fits a pair and stores its two parts in x and y'],
      ['if', 'a guard after the pattern that must also be true'],
    ],
    example: {
      command: 'match point:\n    case (0, 0):\n        print("at the origin")\n    case (x, 0):\n        print("on the x axis at", x)',
      says: 'For point = (4, 0) it prints on the x axis at 4.',
    },
    seeAlso: ['match', 'if'],
  },
  // ---- Keywords: loops ----
  {
    name: 'for',
    lang: 'python',
    kind: 'keyword',
    official: 'The "for" statement is used to iterate over the elements of a sequence (such as a string, tuple or list) or other iterable object',
    source: 'Python language reference (help("for"))',
    when: 'You want to do the same thing for every item in a list, string, range or other collection. Do not add or remove items in a list while looping over it; loop over a copy or build a new list instead.',
    flags: [
      ['for x in items:', 'x takes each item in turn'],
      ['for i, x in enumerate(items):', 'also gives each item\'s position'],
      ['else', 'runs once the loop finishes without a break'],
      ['[x * 2 for x in items]', 'a list comprehension: builds a new list in one line'],
    ],
    example: {
      command: 'for t in range(3, 0, -1):\n    print(t)',
      says: 'Prints 3, 2 and 1, each on its own line.',
    },
    seeAlso: ['in', 'while', 'break', 'continue', 'range', 'enumerate', 'zip'],
  },
  {
    name: 'in',
    lang: 'python',
    kind: 'keyword',
    official: 'The operators "in" and "not in" test for membership. "x in s" evaluates to "True" if x is a member of s, and "False" otherwise.',
    source: 'Python language reference (help("in"))',
    when: 'You want to ask "is this thing inside that collection?", or, in a for loop, to say what to loop over. On a dictionary it checks the keys, not the values, and on a string it looks for a piece of text anywhere inside.',
    flags: [['not in', 'the opposite: True when the item is missing']],
    example: {
      command: '"Io" in ["Europa", "Io", "Ganymede"]',
      says: 'Gives True, because "Io" is one of the moons in the list.',
    },
    seeAlso: ['for', 'not', 'is'],
  },
  {
    name: 'while',
    lang: 'python',
    kind: 'keyword',
    official: 'The "while" statement is used for repeated execution as long as an expression is true',
    source: 'Python language reference (help("while"))',
    when: 'You want to keep repeating until something changes, and you do not know in advance how many times. Make sure something inside the loop changes the condition, or it will loop forever (press Ctrl-C to stop it).',
    flags: [
      ['while True:', 'loops until a break inside stops it'],
      ['else', 'runs once the condition becomes false, but not after a break'],
    ],
    example: {
      command: 'altitude = 0\nwhile altitude < 100:\n    altitude += 25\nprint(altitude)',
      says: 'Climbs in steps of 25 and prints 100 once the condition is no longer true.',
    },
    seeAlso: ['for', 'break', 'continue', 'if'],
  },
  {
    name: 'break',
    lang: 'python',
    kind: 'keyword',
    official: 'It terminates the nearest enclosing loop, skipping the optional "else" clause if the loop has one.',
    source: 'Python language reference (help("break"))',
    when: 'Inside a loop, when you have found what you wanted and want to stop looping right now. It only leaves the innermost loop; a loop around that one keeps going.',
    example: {
      command: 'for reading in readings:\n    if reading < 0:\n        print("bad reading")\n        break',
      says: 'Stops the loop at the first negative reading and skips the rest.',
    },
    seeAlso: ['continue', 'for', 'while'],
  },
  {
    name: 'continue',
    lang: 'python',
    kind: 'keyword',
    official: 'It continues with the next cycle of the nearest enclosing loop.',
    source: 'Python language reference (help("continue"))',
    when: 'Inside a loop, when this item should be skipped but the loop should carry on with the next one. In a while loop, make sure the thing that moves the loop forward happens before the continue, or the loop can get stuck.',
    example: {
      command: 'for line in lines:\n    if not line.strip():\n        continue\n    print(line)',
      says: 'Skips blank lines and prints all the others.',
    },
    seeAlso: ['break', 'for', 'while', 'pass'],
  },
  {
    name: 'pass',
    lang: 'python',
    kind: 'keyword',
    official: '"pass" is a null operation — when it is executed, nothing happens.',
    source: 'Python language reference (help("pass"))',
    when: 'Python needs at least one indented line after a colon, but you have nothing to do there yet, such as an empty class or a function you will fill in later. It does not skip anything in a loop; that is continue.',
    example: { command: 'class LaunchAborted(Exception):\n    pass', says: 'Defines a new kind of exception that works just like Exception.' },
    seeAlso: ['continue', 'class', 'def'],
  },
  // ---- Keywords: logic and comparison ----
  {
    name: 'and',
    lang: 'python',
    kind: 'keyword',
    official: 'The expression "x and y" first evaluates x; if x is false, its value is returned; otherwise, y is evaluated and the resulting value is returned.',
    source: 'Python language reference (help("and"))',
    when: 'You want something to be true only when two conditions are both true. If the left side is false, Python does not even look at the right side, which lets you write safe checks like items and items[0] > 0.',
    example: { command: 'if fuel > 50 and weather == "clear":\n    print("Go for launch")', says: 'Prints Go for launch only when both conditions hold.' },
    seeAlso: ['or', 'not', 'all'],
  },
  {
    name: 'or',
    lang: 'python',
    kind: 'keyword',
    official: 'The expression "x or y" first evaluates x; if x is true, its value is returned; otherwise, y is evaluated and the resulting value is returned.',
    source: 'Python language reference (help("or"))',
    when: 'You want something to be true when at least one of two conditions is true. It hands back one of its two values, not always True or False, so name or "unknown" gives "unknown" when name is empty.',
    example: { command: 'if temp > 90 or pressure < 5:\n    print("Abort")', says: 'Prints Abort if either the temperature is too high or the pressure is too low.' },
    seeAlso: ['and', 'not', 'any'],
  },
  {
    name: 'not',
    lang: 'python',
    kind: 'keyword',
    official: 'The operator "not" yields "True" if its argument is false, "False" otherwise.',
    source: 'Python language reference (help("not"))',
    when: 'You want the opposite of a condition. Empty things count as false, so not items is True for an empty list, which is a common way to check for "nothing here".',
    flags: [['not in', 'True when an item is missing from a collection'], ['is not', 'True when two names are different objects']],
    example: { command: 'if not crew:\n    print("No crew aboard")', says: 'Prints No crew aboard when the crew list is empty.' },
    seeAlso: ['and', 'or', 'in', 'is', 'bool'],
  },
  {
    name: 'is',
    lang: 'python',
    kind: 'keyword',
    official: 'The operators "is" and "is not" test for an object’s identity: "x is y" is true if and only if x and y are the same object.',
    source: 'Python language reference (help("is"))',
    when: 'Checking whether something is None: write x is None, not x == None. Do not use is to compare numbers or strings; two equal values can be different objects, so use == for those.',
    flags: [['is not', 'True when the two are different objects']],
    example: { command: 'if reading is None:\n    print("sensor offline")', says: 'Prints sensor offline when no reading came back.' },
    seeAlso: ['None', 'id', 'in', 'not'],
  },
  {
    name: 'True',
    lang: 'python',
    kind: 'keyword',
    official: 'The two objects representing the values "False" and "True" are the only Boolean objects.',
    source: 'Python language reference (help("types"), The standard type hierarchy)',
    when: 'You need a yes value: a flag that is switched on, or a test that passed. It must start with a capital T; true on its own is just an unknown name. True behaves like the number 1, so sum([True, True, False]) is 2.',
    example: { command: 'engines_ready = True\nwhile True:\n    ...', says: 'Stores a yes flag; while True: loops until a break stops it.' },
    seeAlso: ['False', 'bool', 'None'],
  },
  {
    name: 'False',
    lang: 'python',
    kind: 'keyword',
    official: 'The two objects representing the values "False" and "True" are the only Boolean objects.',
    source: 'Python language reference (help("types"), The standard type hierarchy)',
    when: 'You need a no value: a flag that is switched off, or a test that failed. It must start with a capital F. False behaves like the number 0, and 0, empty strings, empty lists and None all count as false in an if too.',
    example: { command: 'docked = False\nif not docked:\n    print("Still in flight")', says: 'Prints Still in flight, because docked is False.' },
    seeAlso: ['True', 'bool', 'None'],
  },
  {
    name: 'None',
    lang: 'python',
    kind: 'keyword',
    official: 'This object is returned by functions that don’t explicitly return a value. It supports no special operations. There is exactly one null object, named "None" (a built-in name).',
    source: 'Python library reference (help("None"), The Null Object)',
    when: 'You need to say "no value here yet", such as a missing reading or an optional input the caller left out. Test for it with is None. A function you forgot to give a return hands back None, which is behind many "NoneType has no attribute" errors.',
    example: { command: 'def find_moon(name, moons):\n    for m in moons:\n        if m == name:\n            return m\n    return None', says: 'Gives back the moon if it is found, and None if it is not.' },
    seeAlso: ['is', 'return', 'True', 'False'],
  },
  // ---- Keywords: errors ----
  {
    name: 'try',
    lang: 'python',
    kind: 'keyword',
    official: 'The "try" statement specifies exception handlers and/or cleanup code for a group of statements',
    source: 'Python language reference (help("try"))',
    when: 'You are about to do something that might fail, like turning text into a number or opening a file, and you want to handle the failure instead of crashing. Keep the try block short, so you only catch the errors you expect from that one step.',
    flags: [
      ['except', 'what to do if a matching error happens'],
      ['else', 'runs only if no error happened'],
      ['finally', 'runs at the end no matter what'],
    ],
    example: {
      command: 'try:\n    thrust = float(text)\nexcept ValueError:\n    print("not a number:", text)',
      says: 'Turns text into a number, or prints a message instead of crashing if it cannot.',
    },
    seeAlso: ['except', 'finally', 'raise', 'with', 'Exception'],
  },
  {
    name: 'except',
    lang: 'python',
    kind: 'keyword',
    official: 'The "except" clause(s) specify one or more exception handlers.',
    source: 'Python language reference (help("except"))',
    when: 'After a try, to say which errors you expect and what to do about each. Name the exact exception type; a bare except: or except Exception: also swallows mistakes you did not mean to hide. Catching a type also catches every type below it in the exception family.',
    flags: [
      ['except ValueError:', 'handles only that type of error (and its children)'],
      ['except (ValueError, TypeError):', 'handles any of the types in the brackets'],
      ['as err', 'stores the error in err so you can print its message'],
    ],
    example: {
      command: 'except ZeroDivisionError as err:\n    print("bad input:", err)',
      says: 'If the try block divided by zero, prints bad input: division by zero.',
    },
    seeAlso: ['try', 'finally', 'as', 'raise', 'Exception'],
  },
  {
    name: 'finally',
    lang: 'python',
    kind: 'keyword',
    official: 'If "finally" is present, it specifies a ‘cleanup’ handler.',
    source: 'Python language reference (help("finally"))',
    when: 'At the end of a try, for cleanup that must happen whether the code worked or failed, such as closing a file or switching a heater off. It runs even if the try block returns or raises; for files, a with block is usually simpler.',
    example: {
      command: 'try:\n    run_burn()\nfinally:\n    close_valves()',
      says: 'Always closes the valves, even if run_burn() crashes.',
    },
    seeAlso: ['try', 'except', 'with'],
  },
  {
    name: 'raise',
    lang: 'python',
    kind: 'keyword',
    official: 'A Python program can also explicitly raise an exception with the "raise" statement.',
    source: 'Python language reference (help("EXCEPTIONS"))',
    when: 'Your code has found something wrong it cannot sensibly carry on from, such as a negative mass, and you want to stop and report it. Pick the exception type that fits (ValueError for a bad value, TypeError for the wrong kind of thing) and write a message that says what went wrong.',
    flags: [
      ['raise ValueError("...")', 'stops with this error and message'],
      ['raise', 'on its own, inside except: sends the same error on up'],
      ['from err', 'links the new error to the one that caused it'],
    ],
    example: {
      command: 'if mass <= 0:\n    raise ValueError(f"mass must be positive, got {mass}")',
      says: 'Stops the program with ValueError: mass must be positive, got -5 when mass is -5.',
    },
    seeAlso: ['try', 'except', 'assert', 'Exception', 'ValueError'],
  },
  {
    name: 'assert',
    lang: 'python',
    kind: 'keyword',
    official: 'Assert statements are a convenient way to insert debugging assertions into a program',
    source: 'Python language reference (help("assert"))',
    when: 'You want to check something you believe must be true, and stop loudly if it is not; tests use it all the time. Do not use it to check user input, because running Python with -O skips every assert.',
    flags: [['assert cond, "message"', 'the message shown in the AssertionError if the check fails']],
    example: { command: 'assert total_mass > 0, "mass must be positive"', says: 'Does nothing if the mass is positive; otherwise stops with AssertionError: mass must be positive.' },
    seeAlso: ['AssertionError', 'raise'],
  },
  // ---- Keywords: modules, names and context ----
  {
    name: 'import',
    lang: 'python',
    kind: 'keyword',
    official: 'The basic import statement (no "from" clause) is executed in two steps: 1. find a module, loading and initializing it if necessary 2. define a name or names in the local namespace for the scope where the "import" statement occurs.',
    source: 'Python language reference (help("import"))',
    when: 'You want to use code from another module, such as math, or a file of your own. Put imports at the top of the file. Naming your own file after a module you import (math.py, random.py) makes Python load your file instead.',
    flags: [
      ['import math', 'then use math.sqrt and friends'],
      ['as np', 'a shorter name to use instead'],
      ['from', 'bring in single names so you can use them without the module name'],
    ],
    example: { command: 'import math\nprint(math.sqrt(2))', says: 'Loads the math module and prints 1.4142135623730951.' },
    seeAlso: ['from', 'as'],
  },
  {
    name: 'from',
    lang: 'python',
    kind: 'keyword',
    official: 'The "from" form uses a slightly more complex process: 1. find the module specified in the "from" clause, loading and initializing it if necessary',
    source: 'Python language reference (help("from"))',
    when: 'You want just one or two names from a module and would rather write sqrt than math.sqrt. Avoid from module import *, which dumps every name in and can quietly replace names you already had. from also appears in yield from and raise ... from.',
    example: { command: 'from math import pi, sqrt\nprint(sqrt(2) * pi)', says: 'Brings in pi and sqrt by themselves and prints about 4.44.' },
    seeAlso: ['import', 'as', 'yield', 'raise'],
  },
  {
    name: 'as',
    lang: 'python',
    kind: 'keyword',
    official: 'If the module name is followed by "as", then the name following "as" is bound directly to the imported module.',
    source: 'Python language reference (help("import"))',
    when: 'You want to give something a name of your choosing: a shorter name for a module (import numpy as np), the error in an except clause, or the opened file in a with block.',
    flags: [
      ['import numpy as np', 'use np instead of numpy'],
      ['except ValueError as err', 'err holds the error'],
      ['with open(...) as f', 'f is the open file'],
    ],
    example: { command: 'with open("flight_log.txt") as f:\n    text = f.read()', says: 'Opens the file, calls it f while the block runs, and reads it all into text.' },
    seeAlso: ['import', 'except', 'with'],
  },
  {
    name: 'with',
    lang: 'python',
    kind: 'keyword',
    official: 'The "with" statement is used to wrap the execution of a block with methods defined by a context manager (see section With Statement Context Managers).',
    source: 'Python language reference (help("with"))',
    when: 'You open something that must be closed or tidied up afterwards, most often a file. When the indented block ends, even because of an error, Python closes it for you. Anything that needs the file must happen inside the block, since it is closed after.',
    flags: [['as f', 'the name the opened thing gets inside the block']],
    example: {
      command: 'with open("telemetry.csv", "w") as f:\n    f.write("t,alt\\n")',
      says: 'Creates telemetry.csv, writes a header line, and closes the file when the block ends.',
    },
    seeAlso: ['open', 'as', 'try', 'finally'],
  },
  {
    name: 'del',
    lang: 'python',
    kind: 'keyword',
    official: 'Deletion of a name removes the binding of that name from the local or global namespace, depending on whether the name occurs in a "global" statement in the same code block.',
    source: 'Python language reference (help("del"))',
    when: 'You want to remove an item from a dictionary or list by its key or position, or to forget a variable name. After del x, using x is a NameError. Deleting list items while looping over the same list skips items.',
    example: { command: 'del crew["Pilot"]', says: 'Removes the "Pilot" key and its value from the crew dictionary.' },
    seeAlso: ['dict', 'list', 'list.pop'],
  },

  // ---- Built-in functions ----
  {
    name: 'print',
    lang: 'python',
    kind: 'function',
    official: 'Prints the values to a stream, or to sys.stdout by default.',
    source: 'Python built-in docstring',
    when: 'Any time you want your program to show something: a result, a message, a value you are checking. It puts a space between values and starts a new line at the end unless you say otherwise. It shows a value; it does not hand one back, so x = print(5) stores None.',
    flags: [
      ['sep=', 'what goes between the values (a space unless you say otherwise)'],
      ['end=', 'what goes after the last value (a new line unless you say otherwise)'],
      ['file=', 'where to write instead of the screen, such as sys.stderr or an open file'],
      ['flush=True', 'push the text out right away instead of waiting'],
    ],
    example: { command: 'print("Launch in", 10, "seconds")', says: 'Shows Launch in 10 seconds on one line.' },
    seeAlso: ['input', 'repr', 'str'],
  },
  {
    name: 'len',
    lang: 'python',
    kind: 'function',
    official: 'Return the number of items in a container.',
    source: 'Python built-in docstring',
    when: 'You want to know how many items are in a list, how many letters are in a string, or how many keys are in a dictionary. The last position in a list is len(items) - 1, because counting starts at 0.',
    example: { command: 'len(["Mercury", "Venus", "Earth"])', says: 'Gives 3.' },
    seeAlso: ['range', 'list', 'str'],
  },
  {
    name: 'input',
    lang: 'python',
    kind: 'function',
    official: 'Read a string from standard input.',
    source: 'Python built-in docstring',
    when: 'Your program needs the user to type something. What comes back is always a string, even if they typed a number, so wrap it in int() or float() before doing maths with it.',
    example: { command: 'burn = float(input())', says: 'Waits for a line of typed text and turns it into a number, such as 12.5.' },
    seeAlso: ['print', 'int', 'float'],
  },
  {
    name: 'range',
    lang: 'python',
    kind: 'type',
    official: 'Return an object that produces a sequence of integers from start (inclusive) to stop (exclusive) by step.',
    source: 'Python built-in docstring',
    when: 'You want to repeat something a set number of times, or loop over counting numbers. The stop number is never included: range(5) gives 0 to 4.',
    flags: [
      ['range(stop)', 'counts from 0 up to stop - 1'],
      ['range(start, stop)', 'counts from start up to stop - 1'],
      ['range(start, stop, step)', 'jumps by step each time; a negative step counts down'],
    ],
    example: { command: 'for t in range(10, 0, -1):\n    print(t)', says: 'Counts down from 10 to 1; 0 is not printed because stop is left out.' },
    seeAlso: ['for', 'len', 'enumerate'],
  },
  {
    name: 'enumerate',
    lang: 'python',
    kind: 'type',
    official: 'Return an enumerate object.',
    source: 'Python built-in docstring',
    when: 'You are looping over a list and need each item\'s position as well as the item. It is tidier and safer than looping over range(len(items)).',
    flags: [['start=', 'the number to start counting from (0 unless you say otherwise)']],
    example: {
      command: 'for i, stage in enumerate(["boost", "coast", "burn"], start=1):\n    print(i, stage)',
      says: 'Prints 1 boost, 2 coast, 3 burn.',
    },
    seeAlso: ['for', 'range', 'zip'],
  },
  {
    name: 'zip',
    lang: 'python',
    kind: 'type',
    official: 'Yield tuples until an input is exhausted.',
    source: 'Python built-in docstring',
    when: 'You have two or more lists that line up, like names and scores, and want to walk through them side by side. It quietly stops at the shortest list, so a missing item goes unnoticed unless you pass strict=True.',
    flags: [['strict=True', 'raise ValueError if the lists are not the same length']],
    example: {
      command: 'for name, mass in zip(["Io", "Europa"], [8.9e22, 4.8e22]):\n    print(name, mass)',
      says: 'Prints Io 8.9e+22, then Europa 4.8e+22.',
    },
    seeAlso: ['enumerate', 'dict', 'for'],
  },
  {
    name: 'sorted',
    lang: 'python',
    kind: 'function',
    official: 'Return a new list containing all items from the iterable in ascending order.',
    source: 'Python built-in docstring',
    when: 'You want the items of a list (or any collection) in order, while leaving the original as it was. list.sort() sorts a list in place and returns None instead.',
    flags: [
      ['key=', 'a function that picks what to sort by, such as len or a lambda'],
      ['reverse=True', 'biggest first'],
    ],
    example: { command: 'sorted(["Mars", "Io", "Europa"], key=len)', says: 'Gives [\'Io\', \'Mars\', \'Europa\'], shortest name first.' },
    seeAlso: ['list.sort', 'reversed', 'max', 'min', 'lambda'],
  },
  {
    name: 'reversed',
    lang: 'python',
    kind: 'type',
    official: 'Return a reverse iterator over the values of the given sequence.',
    source: 'Python built-in docstring',
    when: 'You want to walk through a list or range backwards. It gives the items one at a time rather than a new list, so wrap it in list() if you want to see them all.',
    example: { command: 'list(reversed([1, 2, 3]))', says: 'Gives [3, 2, 1].' },
    seeAlso: ['sorted', 'range', 'iter'],
  },
  {
    name: 'sum',
    lang: 'python',
    kind: 'function',
    official: "Return the sum of a 'start' value (default: 0) plus an iterable of numbers",
    source: 'Python built-in docstring',
    when: 'You want to add up all the numbers in a list or loop. Adding many decimals can build up tiny rounding errors; math.fsum is more exact.',
    flags: [['start', 'a second input: the value to begin adding from (0 unless you say otherwise)']],
    example: { command: 'sum([120.5, 98.0, 101.5])', says: 'Gives 320.0, the total of the three burns.' },
    seeAlso: ['len', 'max', 'min', 'math.fsum'],
  },
  {
    name: 'max',
    lang: 'python',
    kind: 'function',
    official: 'With a single iterable argument, return its biggest item. The default keyword-only argument specifies an object to return if the provided iterable is empty. With two or more arguments, return the largest argument.',
    source: 'Python built-in docstring',
    when: 'You want the biggest value in a list, or the bigger of a few values. On an empty list it raises ValueError unless you give default=.',
    flags: [
      ['key=', 'a function that picks what to compare, such as len'],
      ['default=', 'what to give back if the list is empty'],
    ],
    example: { command: 'max(0, altitude)', says: 'Gives altitude, or 0 if altitude has gone negative.' },
    seeAlso: ['min', 'sorted', 'sum'],
  },
  {
    name: 'min',
    lang: 'python',
    kind: 'function',
    official: 'With a single iterable argument, return its smallest item. The default keyword-only argument specifies an object to return if the provided iterable is empty. With two or more arguments, return the smallest argument.',
    source: 'Python built-in docstring',
    when: 'You want the smallest value in a list, or the smaller of a few values. On an empty list it raises ValueError unless you give default=.',
    flags: [
      ['key=', 'a function that picks what to compare, such as a lambda'],
      ['default=', 'what to give back if the list is empty'],
    ],
    example: { command: 'min(throttle, 1.0)', says: 'Caps throttle at 1.0: gives 1.0 if throttle is bigger.' },
    seeAlso: ['max', 'sorted', 'sum'],
  },
  {
    name: 'abs',
    lang: 'python',
    kind: 'function',
    official: 'Return the absolute value of the argument.',
    source: 'Python built-in docstring',
    when: 'You care how far a number is from zero, not which side it is on, such as the size of an error. Comparing floats with abs(a - b) < 1e-9 is safer than a == b.',
    example: { command: 'abs(-3.5)', says: 'Gives 3.5.' },
    seeAlso: ['round', 'math.isclose'],
  },
  {
    name: 'round',
    lang: 'python',
    kind: 'function',
    official: 'Round a number to a given precision in decimal digits.',
    source: 'Python built-in docstring',
    when: 'You want a tidier number for display or a checked answer. Exact halves go to the nearest even number, so round(2.5) is 2, and round(2.675, 2) gives 2.67 because 2.675 cannot be stored exactly.',
    flags: [['ndigits', 'a second input: how many digits after the decimal point to keep (none means a whole number)']],
    example: { command: 'round(7.66666, 2)', says: 'Gives 7.67.' },
    seeAlso: ['int', 'float', 'abs'],
  },
  {
    name: 'pow',
    lang: 'python',
    kind: 'function',
    official: 'Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments',
    source: 'Python built-in docstring',
    when: 'You want a power, usually written as base ** exp instead. The three-input form finds the remainder of a huge power quickly, which checksums and cryptography use.',
    example: { command: 'pow(2, 10)', says: 'Gives 1024, the same as 2 ** 10.' },
    seeAlso: ['divmod', 'abs'],
  },
  {
    name: 'divmod',
    lang: 'python',
    kind: 'function',
    official: 'Return the tuple (x//y, x%y).',
    source: 'Python built-in docstring',
    when: 'You want both the whole-number answer and the remainder of a division, such as turning seconds into minutes and seconds. With negative numbers, // rounds down, so divmod(-7, 2) is (-4, 1).',
    example: { command: 'minutes, seconds = divmod(135, 60)', says: 'Sets minutes to 2 and seconds to 15.' },
    seeAlso: ['round', 'int'],
  },
  {
    name: 'any',
    lang: 'python',
    kind: 'function',
    official: 'Return True if bool(x) is True for any x in the iterable.',
    source: 'Python built-in docstring',
    when: 'You want to know whether at least one item passes a test. It stops at the first true item. For an empty list it gives False.',
    example: { command: 'any(t > 90 for t in temps)', says: 'Gives True if any temperature is over 90.' },
    seeAlso: ['all', 'or', 'bool'],
  },
  {
    name: 'all',
    lang: 'python',
    kind: 'function',
    official: 'Return True if bool(x) is True for all values x in the iterable.',
    source: 'Python built-in docstring',
    when: 'You want to know whether every item passes a test. It stops at the first false item. For an empty list it gives True, which can surprise you.',
    example: { command: 'all(check() for check in preflight)', says: 'Gives True only if every preflight check passes.' },
    seeAlso: ['any', 'and', 'bool'],
  },
  {
    name: 'map',
    lang: 'python',
    kind: 'type',
    official: 'Make an iterator that computes the function using arguments from each of the iterables.',
    source: 'Python built-in docstring',
    when: 'You want to run the same function on every item, such as turning a list of strings into numbers. It hands the results out one at a time, so wrap it in list() to see them; a list comprehension does the same job and is often clearer.',
    example: { command: 'list(map(float, "1.5,2.0,3.25".split(",")))', says: 'Gives [1.5, 2.0, 3.25].' },
    seeAlso: ['list', 'zip', 'lambda', 'str.split'],
  },
  {
    name: 'next',
    lang: 'python',
    kind: 'function',
    official: 'Return the next item from the iterator.',
    source: 'Python built-in docstring',
    when: 'You want just the next value from an iterator or generator, not a whole loop. When there is nothing left it raises StopIteration, unless you give a second input to hand back instead.',
    flags: [['default', 'a second input: what to give back when the iterator is used up']],
    example: { command: 'it = iter([10, 20])\nnext(it)', says: 'Gives 10. Calling next(it) again gives 20, and a third time raises StopIteration.' },
    seeAlso: ['iter', 'yield', 'StopIteration'],
  },
  {
    name: 'iter',
    lang: 'python',
    kind: 'function',
    official: 'Get an iterator from an object.',
    source: 'Python built-in docstring',
    when: 'You want to step through a collection by hand with next, or you are writing your own class that works in a for loop. An iterator can only be used once; after it runs out, looping over it again gives nothing.',
    example: { command: 'it = iter(["boost", "coast"])', says: 'Makes an iterator; next(it) then gives "boost", then "coast".' },
    seeAlso: ['next', 'for', 'StopIteration'],
  },
  {
    name: 'isinstance',
    lang: 'python',
    kind: 'function',
    official: 'Return whether an object is an instance of a class or of a subclass thereof.',
    source: 'Python built-in docstring',
    when: 'You need to check what kind of thing a value is before using it, such as in __eq__. It also says True for child classes, which is usually what you want; bool counts as an int, so isinstance(True, int) is True.',
    flags: [['(int, float)', 'a tuple of types: True if it is any one of them']],
    example: { command: 'isinstance(3.0, (int, float))', says: 'Gives True.' },
    seeAlso: ['issubclass', 'type'],
  },
  {
    name: 'issubclass',
    lang: 'python',
    kind: 'function',
    official: "Return whether 'cls' is derived from another class or is the same class.",
    source: 'Python built-in docstring',
    when: 'You want to know how two classes are related, such as whether one exception type is a child of another. The first input must be a class, not an object.',
    example: { command: 'issubclass(KeyError, LookupError)', says: 'Gives True: KeyError is a kind of LookupError.' },
    seeAlso: ['isinstance', 'type'],
  },
  {
    name: 'repr',
    lang: 'python',
    kind: 'function',
    official: 'Return the canonical string representation of the object.',
    source: 'Python built-in docstring',
    when: 'You want to see exactly what a value is while debugging, quotes and hidden characters included. It shows floats in full, so repr(0.1 + 0.2) reveals 0.30000000000000004.',
    example: { command: 'print(repr("Io\\n"))', says: 'Prints \'Io\\n\' with the quotes and the \\n visible, instead of a line break.' },
    seeAlso: ['str', 'print'],
  },
  {
    name: 'hash',
    lang: 'python',
    kind: 'function',
    official: 'Return the hash value for the given object.',
    source: 'Python built-in docstring',
    when: 'Mostly inside a __hash__ method, so your objects can be dictionary keys or set members. Things that can change, like lists, have no hash and raise TypeError. String hashes change each time Python starts.',
    example: { command: 'def __hash__(self):\n    return hash((self.x, self.y, self.z))', says: 'Makes a point hashable by hashing a tuple of its coordinates.' },
    seeAlso: ['set', 'dict', 'id'],
  },
  {
    name: 'id',
    lang: 'python',
    kind: 'function',
    official: 'Return the identity of an object.',
    source: 'Python built-in docstring',
    when: 'You want to see whether two names point at the very same object, while learning how Python stores things. The number itself means nothing and can be reused after an object is gone.',
    example: { command: 'a = [1, 2]\nb = a\nid(a) == id(b)', says: 'Gives True: a and b are two names for one list.' },
    seeAlso: ['is', 'hash'],
  },
  {
    name: 'vars',
    lang: 'python',
    kind: 'function',
    official: 'Without arguments, equivalent to locals().',
    source: 'Python built-in docstring',
    when: 'You want to see an object\'s attributes as a dictionary, which is handy for debugging a class. Objects that use __slots__ have no such dictionary and raise TypeError.',
    example: { command: 'vars(Probe("Juno", 3625))', says: 'Gives {\'name\': \'Juno\', \'mass\': 3625}.' },
    seeAlso: ['dir', 'getattr'],
  },
  {
    name: 'dir',
    lang: 'python',
    kind: 'function',
    official: 'If called without an argument, return the names in the current scope.',
    source: 'Python built-in docstring',
    when: 'You are exploring and want a list of names: those defined so far, or the attributes and methods of an object with dir(thing).',
    example: { command: 'dir("orbit")', says: 'Lists every string method, from \'__add__\' to \'upper\' and \'zfill\'.' },
    seeAlso: ['help', 'vars', 'getattr'],
  },
  {
    name: 'getattr',
    lang: 'python',
    kind: 'function',
    official: "Get a named attribute from an object; getattr(x, 'y') is equivalent to x.y.",
    source: 'Python built-in docstring',
    when: 'You have an attribute\'s name as a string, or you are not sure the attribute exists. Without a default it raises AttributeError when the attribute is missing.',
    flags: [['default', 'a third input: what to give back when the attribute is missing']],
    example: { command: 'getattr(obj, "shape", "")', says: 'Gives obj.shape if it has one, and "" if it does not.' },
    seeAlso: ['vars', 'dir', 'AttributeError'],
  },
  {
    name: 'help',
    lang: 'python',
    kind: 'function',
    official: "Calling help(thing) prints help for the python object 'thing'.",
    source: 'Python built-in docstring',
    when: 'In the Python prompt, when you want to read what a function or module does and which inputs it takes. It shows the docstring, so writing good docstrings makes help useful for your own code too.',
    example: { command: 'help(rocket.delta_v)', says: 'Shows the delta_v function\'s inputs and its docstring.' },
    seeAlso: ['dir'],
  },
  {
    name: 'open',
    lang: 'python',
    kind: 'function',
    official: 'Open file and return a stream.',
    source: 'Python built-in docstring',
    when: 'You want to read a file or write one. Use it in a with block so the file is always closed. Opening with "w" empties the file first, so use "a" to add to the end instead.',
    flags: [
      ['"r"', 'read (the default)'],
      ['"w"', 'write, emptying the file first (or creating it)'],
      ['"a"', 'add to the end of the file'],
      ['"rb"', 'read raw bytes instead of text'],
      ['encoding=', 'how the text is stored, usually "utf-8"'],
      ['newline=""', 'let the csv module handle line endings itself'],
    ],
    example: { command: 'with open("run_07.csv", newline="", encoding="utf-8") as f:\n    rows = list(csv.reader(f))', says: 'Opens the flight log, reads every row, and closes the file.' },
    seeAlso: ['with', 'FileNotFoundError', 'print'],
  },
  {
    name: 'eval',
    lang: 'python',
    kind: 'function',
    official: 'Evaluate the given source in the context of globals and locals.',
    source: 'Python built-in docstring',
    when: 'Rarely: to run a string as Python code, for example to check that repr gives back something Python can read. Never use it on text a user typed, because it runs whatever code they write.',
    example: { command: 'eval(repr(v)) == v', says: 'Gives True when repr(v) is valid Python that rebuilds the same value.' },
    seeAlso: ['repr'],
  },
  {
    name: 'hex',
    lang: 'python',
    kind: 'function',
    official: 'Return the hexadecimal representation of an integer.',
    source: 'Python built-in docstring',
    when: 'You want to see a number in base 16, as byte values and checksums are usually shown. It gives a string starting with 0x, not a number.',
    example: { command: 'hex(255)', says: 'Gives \'0xff\'.' },
    seeAlso: ['bin', 'oct', 'int'],
  },
  {
    name: 'bin',
    lang: 'python',
    kind: 'function',
    official: 'Return the binary representation of an integer.',
    source: 'Python built-in docstring',
    when: 'You want to see the individual bits of a number, such as flags in a status byte. It gives a string starting with 0b, and leading zeros are left off.',
    example: { command: 'bin(5)', says: 'Gives \'0b101\'.' },
    seeAlso: ['hex', 'oct', 'int'],
  },
  {
    name: 'oct',
    lang: 'python',
    kind: 'function',
    official: 'Return the octal representation of an integer.',
    source: 'Python built-in docstring',
    when: 'You want a number in base 8, as some codes and file permissions are written. It gives a string starting with 0o.',
    example: { command: 'oct(8)', says: 'Gives \'0o10\'.' },
    seeAlso: ['hex', 'bin', 'int'],
  },
  {
    name: 'breakpoint',
    lang: 'python',
    kind: 'function',
    official: 'Call sys.breakpointhook(*args, **kws).',
    source: 'Python built-in docstring',
    when: 'You want to pause your program at a line and look around in the debugger: print variables, step line by line, then carry on. Remove it before you hand the code in, or the program will stop and wait there.',
    example: { command: 'breakpoint()', says: 'Pauses here and opens the pdb debugger; type p fuel to see fuel, c to carry on.' },
    seeAlso: ['print'],
  },

  // ---- Built-in types ----
  {
    name: 'str',
    lang: 'python',
    kind: 'type',
    official: 'Create a new string object from the given object.',
    source: 'Python built-in docstring',
    when: 'You want text: turning a number into a string to join it with other text, or checking a value\'s type. "Fuel: " + 50 is a TypeError, so write "Fuel: " + str(50) or use an f-string.',
    example: { command: '"Stage " + str(2)', says: 'Gives \'Stage 2\'.' },
    seeAlso: ['int', 'float', 'repr', 'str.split', 'str.join'],
  },
  {
    name: 'int',
    lang: 'python',
    kind: 'type',
    official: 'Convert a number or string to an integer, or return 0 if no arguments are given.',
    source: 'Python built-in docstring',
    when: 'You want a whole number, most often from typed text. On a float it chops off the decimals instead of rounding, so int(3.9) is 3, and int("3.9") is a ValueError.',
    flags: [['base', 'a second input: the base the text is written in, such as 2 or 16']],
    example: { command: 'int("42") + 1', says: 'Gives 43.' },
    seeAlso: ['float', 'str', 'round', 'input'],
  },
  {
    name: 'float',
    lang: 'python',
    kind: 'type',
    official: 'Convert a string or number to a floating point number, if possible.',
    source: 'Python built-in docstring',
    when: 'You want a number with a decimal point, such as a measurement typed by the user. Floats are stored in binary, so 0.1 + 0.2 is 0.30000000000000004; compare them with math.isclose, not ==.',
    flags: [['"inf"', 'float("inf") is a number bigger than every other, a handy starting point for a minimum']],
    example: { command: 'float("9.81") * 2', says: 'Gives 19.62.' },
    seeAlso: ['int', 'round', 'str', 'math.isclose'],
  },
  {
    name: 'complex',
    lang: 'python',
    kind: 'type',
    official: 'Create a complex number from a real part and an optional imaginary part.',
    source: 'Python built-in docstring',
    when: 'You need numbers with an imaginary part, as in signal processing or the complex-step trick for derivatives. Python writes the imaginary unit as j, not i.',
    example: { command: 'complex(1.5, 2)', says: 'Gives (1.5+2j).' },
    seeAlso: ['float', 'abs'],
  },
  {
    name: 'bool',
    lang: 'python',
    kind: 'type',
    official: 'Returns True when the argument x is true, False otherwise.',
    source: 'Python built-in docstring',
    when: 'You want to turn a value into True or False, the way if would judge it. 0, empty strings, empty lists and None are False; almost everything else is True, including the string "False".',
    example: { command: 'bool([])', says: 'Gives False, because the list is empty.' },
    seeAlso: ['True', 'False', 'if', 'int'],
  },
  {
    name: 'list',
    lang: 'python',
    kind: 'type',
    official: 'Built-in mutable sequence.',
    source: 'Python built-in docstring',
    when: 'You want an ordered collection you can change: add to, remove from, sort. list(thing) makes a new list from any collection, such as a range or a generator. b = a does not copy a list; both names share it, so use list(a) or a.copy().',
    example: { command: 'list(range(4))', says: 'Gives [0, 1, 2, 3].' },
    seeAlso: ['tuple', 'list.append', 'list.sort', 'len', 'sorted'],
  },
  {
    name: 'tuple',
    lang: 'python',
    kind: 'type',
    official: 'Built-in immutable sequence.',
    source: 'Python built-in docstring',
    when: 'You want a fixed group of values that should not change, like an (x, y, z) position, or a list turned into something that can be a dictionary key. A tuple with one item needs a comma: (5,), not (5).',
    example: { command: 'tuple([3.0, 4.0, 0.0])', says: 'Gives (3.0, 4.0, 0.0).' },
    seeAlso: ['list', 'hash'],
  },
  {
    name: 'dict',
    lang: 'python',
    kind: 'type',
    official: 'Return a new dictionary initialized from an optional positional argument and a possibly empty set of keyword arguments.',
    source: 'Python library reference (help("dict"), Mapping Types)',
    when: 'You want to look things up by a name (a key) instead of a position, such as a moon\'s mass by its name. Keys must be unchangeable, like strings, numbers or tuples. Reading a missing key raises KeyError, so use dict.get for "maybe there".',
    example: { command: 'dict(zip(["Io", "Europa"], [1.8, 3.6]))', says: 'Gives {\'Io\': 1.8, \'Europa\': 3.6}.' },
    seeAlso: ['dict.get', 'dict.items', 'zip', 'KeyError'],
  },
  {
    name: 'set',
    lang: 'python',
    kind: 'type',
    official: 'Build an unordered collection of unique elements.',
    source: 'Python built-in docstring',
    when: 'You want each item only once, or to check membership quickly. The items have no order. {} makes an empty dictionary, not a set, so write set() for an empty set.',
    example: { command: 'set(["Io", "Io", "Europa"])', says: 'Gives {\'Io\', \'Europa\'} (in any order).' },
    seeAlso: ['set.add', 'list', 'dict', 'in'],
  },
  {
    name: 'bytes',
    lang: 'python',
    kind: 'type',
    official: 'A bytes object is an immutable array. The items are 8-bit bytes, represented by integers in the range 0 <= x < 256.',
    source: 'Python language reference (help("types"), The standard type hierarchy)',
    when: 'You are working with raw data rather than text: a packet from a sensor, a file opened with "rb", or a checksum. Each item is a number from 0 to 255, so data[0] gives an int, not a character.',
    example: { command: 'bytes([0x41, 0x42])', says: 'Gives b\'AB\', two bytes with the values 65 and 66.' },
    seeAlso: ['bytearray', 'bytes.decode', 'str.encode'],
  },
  {
    name: 'bytearray',
    lang: 'python',
    kind: 'type',
    official: 'A bytearray object is a mutable array.',
    source: 'Python language reference (help("types"), The standard type hierarchy)',
    when: 'You want bytes you can change in place, such as flipping one byte in a packet to test that a checksum catches the error. Every item must stay between 0 and 255.',
    example: { command: 'packet = bytearray(b"\\x01\\x02")\npacket[0] = 0xFF', says: 'Changes the first byte, so packet is now bytearray(b\'\\xff\\x02\').' },
    seeAlso: ['bytes'],
  },
  {
    name: 'slice',
    lang: 'python',
    kind: 'type',
    official: 'Create a slice object.',
    source: 'Python built-in docstring',
    when: 'You want to store a slice, the start:stop:step inside square brackets, in a variable so you can reuse it or give it a name. As with range, stop is not included.',
    example: { command: 'header = slice(0, 6)\npacket[header]', says: 'Gives the first six items, the same as packet[0:6].' },
    seeAlso: ['range', 'list'],
  },
  {
    name: 'object',
    lang: 'python',
    kind: 'type',
    official: 'The base class of the class hierarchy.',
    source: 'Python built-in docstring',
    when: 'Every class inherits from object, even when you do not write it. Calling object() gives a plain, unique value that is equal only to itself, which is handy as a marker for "nothing was passed".',
    example: { command: 'MISSING = object()', says: 'Makes a unique marker value that no real input can ever equal.' },
    seeAlso: ['class', 'type', 'super'],
  },
  {
    name: 'type',
    lang: 'python',
    kind: 'type',
    official: "type(object) -> the object's type",
    source: 'Python built-in docstring',
    when: 'You want to know what kind of thing a value is while exploring or debugging. To check a type in code, isinstance is usually better, because it also accepts child classes.',
    example: { command: 'type(9.81)', says: 'Gives <class \'float\'>.' },
    seeAlso: ['isinstance', 'class', 'object'],
  },
  {
    name: 'super',
    lang: 'python',
    kind: 'type',
    official: 'super() -> same as super(__class__, <first argument>)',
    source: 'Python built-in docstring',
    when: 'Inside a child class, when you want to run the parent class\'s version of a method, most often super().__init__(...) so the parent can set up its part. Forgetting it in __init__ leaves the parent\'s attributes missing.',
    example: {
      command: 'class Probe(Rocket):\n    def __init__(self, name, sensors):\n        super().__init__(name)\n        self.sensors = sensors',
      says: 'Lets Rocket set up name, then adds the probe\'s own sensors.',
    },
    seeAlso: ['class', 'object'],
  },
  {
    name: 'property',
    lang: 'python',
    kind: 'type',
    official: 'Property attribute.',
    source: 'Python built-in docstring',
    when: 'You want something that looks like a plain attribute but is worked out by a method each time it is read, such as a total mass from its parts. Written as @property above a method; you then read it without brackets.',
    flags: [['@name.setter', 'a second method that runs when someone assigns to the attribute']],
    example: {
      command: '@property\ndef total_mass(self):\n    return self.dry_mass + self.fuel',
      says: 'rocket.total_mass now gives the sum, with no () needed.',
    },
    seeAlso: ['class', 'classmethod', 'staticmethod'],
  },
  {
    name: 'classmethod',
    lang: 'python',
    kind: 'type',
    official: 'Convert a function to be a class method.',
    source: 'Python built-in docstring',
    when: 'You want a method that works on the class itself rather than one object, most often another way to build objects, like Rocket.from_dict(data). Written as @classmethod; the first input is cls, the class, not self.',
    example: {
      command: '@classmethod\ndef from_dict(cls, d):\n    return cls(d["name"])',
      says: 'Rocket.from_dict({"name": "Ares"}) builds a new Rocket from a dictionary.',
    },
    seeAlso: ['staticmethod', 'property', 'class'],
  },
  {
    name: 'staticmethod',
    lang: 'python',
    kind: 'type',
    official: 'Convert a function to be a static method.',
    source: 'Python built-in docstring',
    when: 'You want a plain helper function that lives inside a class because it belongs there, but needs neither self nor cls. Written as @staticmethod.',
    example: {
      command: '@staticmethod\ndef km_to_m(km):\n    return km * 1000',
      says: 'Rocket.km_to_m(2) gives 2000, with no object needed.',
    },
    seeAlso: ['classmethod', 'property', 'class'],
  },

  // ---- Constants ----
  {
    name: 'NotImplemented',
    lang: 'python',
    kind: 'constant',
    official: 'Numeric methods and rich comparison methods should return this value if they do not implement the operation for the operands provided.',
    source: 'Python language reference (help("types"), The standard type hierarchy)',
    when: 'Inside methods like __add__ or __eq__, when the other value is something your class does not know how to handle. Return it, do not raise it; Python then tries the other object or gives a clean TypeError. It is not the same as NotImplementedError.',
    example: {
      command: 'def __add__(self, other):\n    if not isinstance(other, Vector):\n        return NotImplemented',
      says: 'Vector(1, 2) + "hi" then fails with a clear TypeError instead of a confusing crash.',
    },
    seeAlso: ['NotImplementedError', 'isinstance'],
  },

  // ---- Exceptions ----
  {
    name: 'BaseException',
    lang: 'python',
    kind: 'exception',
    official: 'Common base class for all exceptions',
    source: 'Python built-in docstring',
    when: 'It sits at the very top of the exception family tree. You rarely catch it, because that also catches Ctrl-C (KeyboardInterrupt) and SystemExit; make your own exceptions from Exception instead.',
    example: { command: 'issubclass(SystemExit, BaseException)', says: 'Gives True, while issubclass(SystemExit, Exception) gives False.' },
    seeAlso: ['Exception', 'SystemExit'],
  },
  {
    name: 'Exception',
    lang: 'python',
    kind: 'exception',
    official: 'Common base class for all non-exit exceptions.',
    source: 'Python built-in docstring',
    when: 'The parent of nearly every error. Inherit from it to make your own error types. except Exception: catches almost everything, including your own typos, so catch something narrower when you can.',
    example: { command: 'class LaunchError(Exception):\n    pass', says: 'Defines your own error type; raise LaunchError("valve stuck") then works like any built-in error.' },
    seeAlso: ['BaseException', 'raise', 'except', 'class'],
  },
  {
    name: 'ValueError',
    lang: 'python',
    kind: 'exception',
    official: 'Inappropriate argument value (of correct type).',
    source: 'Python built-in docstring',
    when: 'The value has the right type but is not acceptable, like int("abc") or a negative mass. Raise it yourself when a function gets a value it cannot use.',
    example: { command: 'int("ten")', says: 'Stops with ValueError: invalid literal for int() with base 10: \'ten\'.' },
    seeAlso: ['TypeError', 'raise', 'except'],
  },
  {
    name: 'TypeError',
    lang: 'python',
    kind: 'exception',
    official: 'Inappropriate argument type.',
    source: 'Python built-in docstring',
    when: 'You used the wrong kind of thing, like adding a number to a string or calling a function with the wrong number of inputs. The message says which types were involved.',
    example: { command: '"Stage " + 2', says: 'Stops with TypeError: can only concatenate str (not "int") to str.' },
    seeAlso: ['ValueError', 'isinstance', 'str'],
  },
  {
    name: 'KeyError',
    lang: 'python',
    kind: 'exception',
    official: 'Mapping key not found.',
    source: 'Python built-in docstring',
    when: 'You asked a dictionary for a key it does not have. Check with in first, or use dict.get to get None (or a default) instead of an error.',
    example: { command: 'crew = {"Pilot": "Ada"}\ncrew["Doctor"]', says: 'Stops with KeyError: \'Doctor\'.' },
    seeAlso: ['dict.get', 'LookupError', 'IndexError', 'in'],
  },
  {
    name: 'IndexError',
    lang: 'python',
    kind: 'exception',
    official: 'Sequence index out of range.',
    source: 'Python built-in docstring',
    when: 'You asked for a position that a list or string does not have. With 3 items, the positions are 0, 1 and 2, so items[3] is out of range.',
    example: { command: '["boost", "coast"][2]', says: 'Stops with IndexError: list index out of range.' },
    seeAlso: ['KeyError', 'LookupError', 'len'],
  },
  {
    name: 'LookupError',
    lang: 'python',
    kind: 'exception',
    official: 'Base class for lookup errors.',
    source: 'Python built-in docstring',
    when: 'The parent of KeyError and IndexError. Catch it when you want to handle "not found" the same way for both dictionaries and lists.',
    example: { command: 'issubclass(KeyError, LookupError)', says: 'Gives True.' },
    seeAlso: ['KeyError', 'IndexError'],
  },
  {
    name: 'AttributeError',
    lang: 'python',
    kind: 'exception',
    official: 'Attribute not found.',
    source: 'Python built-in docstring',
    when: 'You asked an object for an attribute or method it does not have, often a typo or a variable that is None when you expected an object.',
    example: { command: 'None.upper()', says: 'Stops with AttributeError: \'NoneType\' object has no attribute \'upper\'.' },
    seeAlso: ['getattr', 'None'],
  },
  {
    name: 'ZeroDivisionError',
    lang: 'python',
    kind: 'exception',
    official: 'Second argument to a division or modulo operation was zero.',
    source: 'Python built-in docstring',
    when: 'You divided by zero, with /, // or %. Check the bottom number first, such as an empty list\'s length before working out an average.',
    example: { command: 'sum([]) / len([])', says: 'Stops with ZeroDivisionError: division by zero.' },
    seeAlso: ['ValueError', 'OverflowError', 'FloatingPointError'],
  },
  {
    name: 'OverflowError',
    lang: 'python',
    kind: 'exception',
    official: 'Result too large to be represented.',
    source: 'Python built-in docstring',
    when: 'A float calculation got too big to store. Whole numbers (int) never overflow in Python; floats top out around 1.8e308.',
    example: { command: '2.0 ** 10000', says: 'Stops with OverflowError: (34, \'Numerical result out of range\').' },
    seeAlso: ['ZeroDivisionError', 'FloatingPointError', 'float'],
  },
  {
    name: 'FloatingPointError',
    lang: 'python',
    kind: 'exception',
    official: 'Floating point operation failed.',
    source: 'Python built-in docstring',
    when: 'Plain Python rarely raises it, but NumPy does when you ask it to treat bad float maths, like dividing by zero, as an error with np.seterr(all="raise").',
    example: { command: 'np.seterr(all="raise")\nnp.float64(1.0) / 0.0', says: 'Stops with FloatingPointError: divide by zero encountered in scalar divide.' },
    seeAlso: ['ZeroDivisionError', 'OverflowError'],
  },
  {
    name: 'RuntimeError',
    lang: 'python',
    kind: 'exception',
    official: 'Unspecified run-time error.',
    source: 'Python built-in docstring',
    when: 'Something went wrong that no more specific error describes, like a solver that did not converge or a sensor that is not connected. Raise it with a clear message.',
    example: { command: 'raise RuntimeError("Kepler solver did not converge")', says: 'Stops with RuntimeError: Kepler solver did not converge.' },
    seeAlso: ['Exception', 'raise', 'ValueError'],
  },
  {
    name: 'NotImplementedError',
    lang: 'python',
    kind: 'exception',
    official: "Method or function hasn't been implemented yet.",
    source: 'Python built-in docstring',
    when: 'You are writing a parent class whose method each child class must fill in. Raise it in the parent\'s version, so forgetting to override it fails loudly. Do not confuse it with NotImplemented, which is returned, not raised.',
    example: { command: 'def thrust(self):\n    raise NotImplementedError', says: 'Any child class that forgets its own thrust() stops with NotImplementedError when it is called.' },
    seeAlso: ['NotImplemented', 'abc.abstractmethod', 'class'],
  },
  {
    name: 'StopIteration',
    lang: 'python',
    kind: 'exception',
    official: 'Signal the end from iterator.__next__().',
    source: 'Python built-in docstring',
    when: 'An iterator raises it to say "no more values". A for loop catches it for you and simply ends; you only see it when you call next yourself on something that is used up.',
    example: { command: 'next(iter([]))', says: 'Stops with StopIteration, because there was nothing to give.' },
    seeAlso: ['next', 'iter', 'yield'],
  },
  {
    name: 'AssertionError',
    lang: 'python',
    kind: 'exception',
    official: 'Assertion failed.',
    source: 'Python built-in docstring',
    when: 'An assert statement found its condition false. In tests, this is how a failing check is reported, with the message you wrote after the comma.',
    example: { command: 'assert 2 + 2 == 5, "maths is broken"', says: 'Stops with AssertionError: maths is broken.' },
    seeAlso: ['assert'],
  },
  {
    name: 'FileNotFoundError',
    lang: 'python',
    kind: 'exception',
    official: 'File not found.',
    source: 'Python built-in docstring',
    when: 'You tried to open a file for reading that does not exist, often because the name is misspelled or the program is running in a different folder than you think.',
    example: { command: 'open("missing.csv")', says: 'Stops with FileNotFoundError: [Errno 2] No such file or directory: \'missing.csv\'.' },
    seeAlso: ['open', 'pathlib.Path'],
  },
  {
    name: 'ImportError',
    lang: 'python',
    kind: 'exception',
    official: "Import can't find module, or can't find name in module.",
    source: 'Python built-in docstring',
    when: 'An import failed: the name is misspelled, it is not in that module, or two modules import each other (a circular import). A module that is not installed at all gives its child, ModuleNotFoundError.',
    example: { command: 'from gnc.cli import mian', says: 'Stops with ImportError: cannot import name \'mian\' from \'gnc.cli\'.' },
    seeAlso: ['import', 'from'],
  },
  {
    name: 'TimeoutError',
    lang: 'python',
    kind: 'exception',
    official: 'Timeout expired.',
    source: 'Python built-in docstring',
    when: 'Something took longer than it was allowed to, such as a sensor that never replies. Raise it yourself when you give up waiting.',
    example: { command: 'raise TimeoutError("no reply from sensor")', says: 'Stops with TimeoutError: no reply from sensor.' },
    seeAlso: ['RuntimeError', 'Exception'],
  },
  {
    name: 'SystemExit',
    lang: 'python',
    kind: 'exception',
    official: 'Request to exit from the interpreter.',
    source: 'Python built-in docstring',
    when: 'You want the program to stop with an exit code, as sys.exit does. It is not a child of Exception, so except Exception: does not stop it.',
    example: { command: 'raise SystemExit(main())', says: 'Runs main() and ends the program with the number it returns as the exit code (0 means success).' },
    seeAlso: ['sys.exit', 'BaseException'],
  },
  {
    name: 'DeprecationWarning',
    lang: 'python',
    kind: 'exception',
    official: 'Base class for warnings about deprecated features.',
    source: 'Python built-in docstring',
    when: 'You are changing your code and want to warn people that an old function will go away. Python hides these warnings by default unless they come from code run directly, so tests often turn them on.',
    example: {
      command: 'warnings.warn("rho() is deprecated, use density()", DeprecationWarning, stacklevel=2)',
      says: 'Shows a warning pointing at the caller\'s line, and the program keeps running.',
    },
    seeAlso: ['warnings.warn', 'Exception'],
  },
]
