import type { CommandRef } from './types'

export const COMMANDS: CommandRef[] = [
  {
    name: 'list.append',
    aliases: ['append'],
    lang: 'python',
    kind: 'method',
    official: 'Append object to the end of the list.',
    source: 'Python built-in docstring (list.append)',
    when: 'You want to add one item to the end of a list, such as a new reading or a new crew name. It changes the list itself and gives back None, so write crew.append(x) on its own line, never crew = crew.append(x). A deque has append too. If you pass it a list, the whole list goes in as one item; use extend to add the items one by one.',
    flags: [['x', 'the one item to add at the end']],
    example: { command: 'readings.append(4.2)', says: 'Adds 4.2 as the last item of the readings list.' },
    seeAlso: ['list.extend', 'list.insert', 'list.pop'],
  },
  {
    name: 'str.strip',
    aliases: ['strip'],
    lang: 'python',
    kind: 'method',
    official: 'Return a copy of the string with leading and trailing whitespace removed.',
    source: 'Python built-in docstring (str.strip)',
    when: 'You read a line from a file or from the user and want to drop the spaces, tabs and newline at both ends. It never changes the string you call it on; it hands back a new one, so keep it: line = line.strip().',
    example: { command: 'line = "  thrust 500 kN\\n".strip()', says: 'Gives "thrust 500 kN", with the spaces in front and the newline at the end removed.' },
    seeAlso: ['str.rstrip', 'str.split'],
  },
  {
    name: 'str.join',
    aliases: ['join'],
    lang: 'python',
    kind: 'method',
    official: 'Concatenate any number of strings.',
    source: 'Python built-in docstring (str.join)',
    when: 'You have a list of strings and want one string with a separator between each pair, such as commas or new lines. The separator comes first: ", ".join(names). Every item must already be a string, so turn numbers into strings first or you get a TypeError.',
    flags: [['iterable', 'the strings to glue together, such as a list or a generator']],
    example: { command: '", ".join(["Ada", "Lin", "Sam"])', says: 'Gives "Ada, Lin, Sam".' },
    seeAlso: ['str.split'],
  },
  {
    name: 'str.split',
    aliases: ['split'],
    lang: 'python',
    kind: 'method',
    official: 'Return a list of the substrings in the string, using sep as the separator string.',
    source: 'Python built-in docstring (str.split)',
    when: 'You want to cut a line of text into pieces, such as the fields of a telemetry row. With nothing in the brackets it cuts at any run of spaces and drops empty pieces; with a separator like "," it cuts at every one, and two commas in a row give an empty string between them.',
    flags: [['(empty)', 'cut at any run of spaces, tabs or newlines and drop empty pieces'], ['sep', 'the exact text to cut at, such as "," or "\\n"']],
    example: { command: 'name, qty, price = "gizmo,25,5".split(",")', says: 'Cuts the text at each comma into "gizmo", "25" and "5", and gives one to each name.' },
    seeAlso: ['str.join', 'str.splitlines', 'str.partition', 'str.strip'],
  },
  {
    name: 'dict.get',
    aliases: ['get'],
    lang: 'python',
    kind: 'method',
    official: 'Return the value for key if key is in the dictionary, else default.',
    source: 'Python built-in docstring (dict.get)',
    when: 'You want the value for a key that might not be in the dictionary, without a KeyError. Give a second value to use when the key is missing; without one you get None. It does not store anything, so d.get(k, []).append(x) changes a list that is thrown away (use setdefault for that).',
    flags: [['key', 'the key to look up'], ['default', 'what to hand back when the key is missing (None if you leave it out)']],
    example: { command: 'tm.get("attitude_valid", False)', says: 'Gives the value stored under "attitude_valid", or False if that key is not there.' },
    seeAlso: ['dict.setdefault', 'dict.keys'],
  },
  {
    name: 'str.lower',
    aliases: ['lower'],
    lang: 'python',
    kind: 'method',
    official: 'Return a copy of the string converted to lowercase.',
    source: 'Python built-in docstring (str.lower)',
    when: 'You want to compare or count words without caring about capital letters, such as treating "Go", "GO" and "go" as the same command. It gives back a new string; the original is untouched.',
    example: { command: '"Go  North".lower().split()', says: 'Gives ["go", "north"]: everything in small letters, then cut into words.' },
    seeAlso: ['str.upper', 'str.title', 'str.capitalize'],
  },
  {
    name: 'list.copy',
    aliases: ['copy'],
    lang: 'python',
    kind: 'method',
    official: 'Return a shallow copy of the list.',
    source: 'Python built-in docstring (list.copy)',
    when: 'You want a second list you can change without changing the first, because b = a only puts a second name on the same list. It copies only the top layer: lists inside the list are still shared. Dicts, sets and deques have copy too, and NumPy arrays have their own.',
    example: { command: 'backup = crew.copy()', says: 'Makes a new list with the same items, so adding to backup leaves crew alone.' },
    seeAlso: ['list.append'],
  },
  {
    name: 'dict.items',
    aliases: ['items'],
    lang: 'python',
    kind: 'method',
    official: 'D.items() -> a set-like object providing a view on D\'s items',
    source: 'Python built-in docstring (dict.items)',
    when: 'You want to loop over a dictionary and use each key and its value together. Each item is a (key, value) pair, so write for key, value in d.items(). It is a live view: if the dict changes, the view shows the change, and changing the dict while looping over it is an error.',
    example: { command: 'for name, limit in limits.items(): print(name, limit)', says: 'Prints each key of limits next to its value, one pair per line.' },
    seeAlso: ['dict.keys', 'dict.values'],
  },
  {
    name: 'str.replace',
    aliases: ['replace'],
    lang: 'python',
    kind: 'method',
    official: 'Return a copy with all occurrences of substring old replaced by new.',
    source: 'Python built-in docstring (str.replace)',
    when: 'You want to swap every copy of one piece of text for another, such as "&" for "&amp;". It gives back a new string. When you chain replacements, order matters: a later replace can change what an earlier one put in.',
    flags: [['old', 'the text to find'], ['new', 'the text to put in its place']],
    example: { command: '"LEO-ORBIT".replace("-", " ")', says: 'Gives "LEO ORBIT", with every dash turned into a space.' },
    seeAlso: ['re.Pattern.sub'],
  },
  {
    name: 'str.isdigit',
    aliases: ['isdigit'],
    lang: 'python',
    kind: 'method',
    official: 'Return True if the string is a digit string, False otherwise.',
    source: 'Python built-in docstring (str.isdigit)',
    when: 'You want to check that a string is made only of digits before turning it into a number. It is False for "4.2", "-3" and the empty string, because the dot, the minus sign and "nothing" are not digits.',
    example: { command: '"2026".isdigit()', says: 'Gives True. "4.2".isdigit() gives False because of the dot.' },
    seeAlso: ['str.isalnum', 'str.isspace'],
  },
  {
    name: 're.Pattern.sub',
    aliases: ['sub'],
    lang: 'python',
    kind: 'method',
    official: 'Return the string obtained by replacing the leftmost non-overlapping occurrences of pattern in string by the replacement repl.',
    source: 'Python built-in docstring (re.Pattern.sub)',
    when: 'You have a compiled pattern and want to replace every match in some text, for example wrapping *word* in <em> tags. Inside the replacement, \\1 means "what group 1 matched". Write the replacement as a raw string, r"...", so the backslash reaches the regex.',
    flags: [['repl', 'the replacement text; \\1, \\2 put back what each group matched'], ['string', 'the text to search']],
    example: { command: 'EM.sub(r"<em>\\1</em>", "*a* or *b*")', says: 'Gives "<em>a</em> or <em>b</em>": each *...* is replaced, with the text inside kept.' },
    seeAlso: ['re.Pattern.search', 're.Match.group', 'str.replace'],
  },
  {
    name: 're.Match.group',
    aliases: ['group'],
    lang: 'python',
    kind: 'method',
    official: 'Return subgroup(s) of the match by indices or names.',
    source: 'Python built-in docstring (re.Match.group)',
    when: 'A match succeeded and you want the text it found. group() or group(0) is the whole match; group(1) is what the first pair of brackets in the pattern caught. If the match failed you have None, not a match, and calling group on None is an AttributeError, so check first.',
    flags: [['0', 'the whole match (the same as leaving it empty)'], ['1, 2, ...', 'what each pair of brackets caught, counting from the left']],
    example: { command: 'FENCE.match("```python").group(1)', says: 'Gives "python", the part the first bracketed group caught.' },
    seeAlso: ['re.Match.groups', 're.Match.end', 're.Pattern.match'],
  },
  {
    name: 're.Pattern.match',
    aliases: ['match'],
    lang: 'python',
    kind: 'method',
    official: 'Matches zero or more characters at the beginning of the string.',
    source: 'Python built-in docstring (re.Pattern.match)',
    when: 'You want to know whether a string starts with your pattern, such as a line starting with "# ". It only looks at the very start; use search to look anywhere, or fullmatch to demand the whole string. It gives a match object, or None when there is no match.',
    flags: [['string', 'the text to test from its first character']],
    example: { command: 'BULLET.match("* eggs").group(1)', says: 'Matches at the start of "* eggs" and gives "eggs".' },
    seeAlso: ['re.Pattern.search', 're.Pattern.fullmatch', 're.Match.group'],
  },
  {
    name: 'dict.values',
    aliases: ['values'],
    lang: 'python',
    kind: 'method',
    official: 'D.values() -> an object providing a view on D\'s values',
    source: 'Python built-in docstring (dict.values)',
    when: 'You want only the values of a dictionary, such as every score or every member record, without the keys. It is a live view, not a list; wrap it in list(...) if you need to index it.',
    example: { command: 'sum(scores.values())', says: 'Adds up every value stored in the scores dictionary.' },
    seeAlso: ['dict.keys', 'dict.items'],
  },
  {
    name: 'list.pop',
    aliases: ['pop'],
    lang: 'python',
    kind: 'method',
    official: 'Remove and return item at index (default last).',
    source: 'Python built-in docstring (list.pop)',
    when: 'You want to take an item out of a list and use it: the last one with no argument, or the one at a position you give. On an empty list it raises IndexError. pop(0) shifts every other item along, so a queue should be a deque with popleft. dict, set and deque have pop too, each a little different: dict.pop takes a key.',
    flags: [['index', 'the position to remove (the last item if you leave it out)']],
    example: { command: 'last = stack.pop()', says: 'Removes the top item of stack and gives it to last.' },
    seeAlso: ['list.append', 'collections.deque.popleft', 'list.remove'],
  },
  {
    name: 'str.splitlines',
    aliases: ['splitlines'],
    lang: 'python',
    kind: 'method',
    official: 'Return a list of the lines in the string, breaking at line boundaries.',
    source: 'Python built-in docstring (str.splitlines)',
    when: 'You have a block of text, such as a whole file or everything typed into stdin, and want a list of its lines. Unlike split("\\n"), it does not leave an empty string at the end when the text ends with a newline.',
    example: { command: '"widget 3 10\\ngizmo 25 5\\n".splitlines()', says: 'Gives ["widget 3 10", "gizmo 25 5"], with no empty line at the end.' },
    seeAlso: ['str.split', 'io.StringIO.readline'],
  },
  {
    name: 'str.partition',
    aliases: ['partition'],
    lang: 'python',
    kind: 'method',
    official: 'Partition the string into three parts using the given separator.',
    source: 'Python built-in docstring (str.partition)',
    when: 'You want to cut a string at the first copy of a separator and always get exactly three parts back: before, the separator, after. It never fails; when the separator is missing you get the whole string and two empty strings, so unpacking into three names is always safe.',
    flags: [['sep', 'the text to cut at, such as "." or ":"']],
    example: { command: 'whole, dot, frac = "12.5".partition(".")', says: 'Gives whole "12", dot "." and frac "5".' },
    seeAlso: ['str.split'],
  },
  {
    name: 'set.add',
    aliases: ['add'],
    lang: 'python',
    kind: 'method',
    official: 'Add an element to a set.',
    source: 'Python built-in docstring (set.add)',
    when: 'You want to put one item into a set, such as a grid cell you have visited. If it is already there, nothing changes, since a set holds each item once. Lists use append instead; there is no set.append.',
    flags: [['elem', 'the item to put in (it must be hashable, so a tuple but not a list)']],
    example: { command: 'seen.add((row, col))', says: 'Puts the cell (row, col) into the seen set, if it is not in there already.' },
    seeAlso: ['list.append'],
  },
  {
    name: 'str.upper',
    aliases: ['upper'],
    lang: 'python',
    kind: 'method',
    official: 'Return a copy of the string converted to uppercase.',
    source: 'Python built-in docstring (str.upper)',
    when: 'You want a string in capital letters, for a heading, a call sign or a case-free comparison. It gives back a new string and leaves the original alone.',
    example: { command: '"abort".upper()', says: 'Gives "ABORT".' },
    seeAlso: ['str.lower', 'str.title', 'str.capitalize'],
  },
  {
    name: 'io.StringIO.write',
    aliases: ['write'],
    lang: 'python',
    kind: 'method',
    official: 'Write string to file.',
    source: 'Python built-in docstring (io.StringIO.write)',
    when: 'You are writing text into a file-like object: a StringIO, or a real file opened with open(path, "w"). Unlike print, it adds no newline, so put "\\n" at the end yourself. It gives back how many characters it wrote.',
    flags: [['s', 'the string to write; it must be a str, so turn numbers into text first']],
    example: { command: 'f.write("# columns: t [s], x, y, z [m]\\n")', says: 'Writes that header line, newline included, to the file f.' },
    seeAlso: ['io.StringIO.getvalue', 'io.StringIO.read', 'io.StringIO.close'],
  },
  {
    name: 'str.startswith',
    aliases: ['startswith'],
    lang: 'python',
    kind: 'method',
    official: 'Return True if S starts with the specified prefix, False otherwise.',
    source: 'Python built-in docstring (str.startswith)',
    when: 'You want to check how a string begins, such as a comment line starting with "#". A second number tells it where to start looking. Be careful: "#hashtag" also starts with "#", so when the rule is stricter a regex says it better.',
    flags: [['prefix', 'the text to look for at the start (a tuple of choices works too)'], ['start', 'the position to start checking from']],
    example: { command: 'line.startswith("#")', says: 'Gives True when the line begins with a # and False otherwise.' },
    seeAlso: ['str.endswith', 're.Pattern.match'],
  },
  {
    name: 'str.ljust',
    aliases: ['ljust'],
    lang: 'python',
    kind: 'method',
    official: 'Return a left-justified string of length width.',
    source: 'Python built-in docstring (str.ljust)',
    when: 'You want a string padded on the right to a set width, for lining up columns or filling in missing digits. Give a second character to pad with instead of spaces. A string already that long or longer comes back unchanged.',
    flags: [['width', 'how long the result should be'], ['fillchar', 'the character to pad with (a space if you leave it out)']],
    example: { command: '"5".ljust(2, "0")', says: 'Gives "50": the "5" padded on the right with a zero to two characters.' },
  },
  {
    name: 'collections.deque.popleft',
    aliases: ['popleft'],
    lang: 'python',
    kind: 'method',
    official: 'Remove and return the leftmost element.',
    source: 'Python built-in docstring (collections.deque.popleft)',
    when: 'You use a deque as a queue and want the item at the front, as in a breadth-first search. It is fast at any size, unlike list.pop(0). On an empty deque it raises IndexError, so loop while the queue is not empty.',
    example: { command: 'node = queue.popleft()', says: 'Removes the front item of the queue and gives it to node.' },
    seeAlso: ['collections.deque.appendleft', 'list.pop', 'list.append'],
  },
  {
    name: 'io.StringIO.read',
    aliases: ['read'],
    lang: 'python',
    kind: 'method',
    official: 'Read at most size characters, returned as a string.',
    source: 'Python built-in docstring (io.StringIO.read)',
    when: 'You want everything left in a file-like object as one string, such as sys.stdin.read() or f.read() on an open file. It reads from the current position, so right after writing to a StringIO it gives an empty string; use getvalue for that.',
    example: { command: 'text = sys.stdin.read()', says: 'Reads everything typed or piped in, as one string.' },
    seeAlso: ['io.StringIO.readline', 'io.StringIO.getvalue', 'str.splitlines'],
  },
  {
    name: 'float.hex',
    aliases: ['hex'],
    lang: 'python',
    kind: 'method',
    official: 'Return a hexadecimal representation of a floating-point number.',
    source: 'Python built-in docstring (float.hex)',
    when: 'You want to see a float\'s exact bits, to prove two results are truly identical and not just equal in the first few digits. int has no hex method (use the built-in hex() for that), but bytes has one that writes each byte as two hex digits.',
    example: { command: 'print((0.1).hex())', says: 'Prints 0x1.999999999999ap-4, the exact value stored for 0.1.' },
    seeAlso: ['float.fromhex'],
  },
  {
    name: 'str.count',
    aliases: ['count'],
    lang: 'python',
    kind: 'method',
    official: 'Return the number of non-overlapping occurrences of substring sub in string S[start:end].',
    source: 'Python built-in docstring (str.count)',
    when: 'You want to know how many times a piece of text appears in a string, such as how many dots are in "4.5". It counts copies that do not overlap. list and tuple have count too, where it counts items equal to the value.',
    flags: [['sub', 'the text to count']],
    example: { command: '"4.5".count(".")', says: 'Gives 1: there is one dot.' },
    seeAlso: ['str.index', 'collections.Counter.most_common'],
  },
  {
    name: 'io.StringIO.close',
    aliases: ['close'],
    lang: 'python',
    kind: 'method',
    official: 'Close the IO object.',
    source: 'Python built-in docstring (io.StringIO.close)',
    when: 'You are done with a file-like object and want it closed, so its contents are flushed out and it is let go. After closing, reading or writing raises ValueError. With a real file, a with block closes it for you, even when an error happens.',
    example: { command: 'f.close()', says: 'Closes the file f; anything still waiting in its buffer is written out first.' },
    seeAlso: ['io.StringIO.flush', 'io.StringIO.write'],
  },
  {
    name: 'str.encode',
    aliases: ['encode'],
    lang: 'python',
    kind: 'method',
    official: 'Encode the string using the codec registered for encoding.',
    source: 'Python built-in docstring (str.encode)',
    when: 'You have text and need bytes, for example to feed a hash function or send it over a wire. With no argument it uses UTF-8. The opposite step is bytes.decode.',
    example: { command: 'hashlib.sha256("ORBIT".encode()).hexdigest()', says: 'Turns "ORBIT" into bytes and gives their SHA-256 fingerprint as hex text.' },
    seeAlso: ['bytes.decode'],
  },
  {
    name: 'list.clear',
    aliases: ['clear'],
    lang: 'python',
    kind: 'method',
    official: 'Remove all items from list.',
    source: 'Python built-in docstring (list.clear)',
    when: 'You want to empty a list but keep the same list object, so every other name for it sees it empty too. That is different from paragraph = [], which makes a new list and leaves the old one full. dict, set and deque have clear too.',
    example: { command: 'paragraph.clear()', says: 'Removes every item, leaving paragraph as an empty list.' },
    seeAlso: ['list.pop', 'list.remove'],
  },
  {
    name: 'io.StringIO.readline',
    aliases: ['readline'],
    lang: 'python',
    kind: 'method',
    official: 'Read until newline or EOF.',
    source: 'Python built-in docstring (io.StringIO.readline)',
    when: 'You want just the next line from a file-like object, such as a header line before the data. The line keeps its newline at the end, so strip it. At the end of the file it gives an empty string.',
    example: { command: 'names = f.readline().strip().split(",")', says: 'Reads the first line, drops its newline and cuts it into column names.' },
    seeAlso: ['io.StringIO.read', 'str.strip'],
  },
  {
    name: 'str.isspace',
    aliases: ['isspace'],
    lang: 'python',
    kind: 'method',
    official: 'Return True if the string is a whitespace string, False otherwise.',
    source: 'Python built-in docstring (str.isspace)',
    when: 'You are walking through text one character at a time and want to skip spaces, tabs and newlines. It is False for the empty string.',
    example: { command: '" ".isspace()', says: 'Gives True. "a".isspace() gives False.' },
    seeAlso: ['str.isdigit', 'str.isalnum'],
  },
  {
    name: 'dict.setdefault',
    aliases: ['setdefault'],
    lang: 'python',
    kind: 'method',
    official: 'Insert key with a value of default if key is not in the dictionary.',
    source: 'Python built-in docstring (dict.setdefault)',
    when: 'You are grouping things into lists or sets inside a dict and want the key created with an empty list the first time. It stores the default only if the key is missing, then gives back what is stored, so d.setdefault(k, []).append(x) works. Note the default is built every time you call it, even when not needed.',
    flags: [['key', 'the key to look up or create'], ['default', 'what to store when the key is missing']],
    example: { command: 'groups.setdefault(word[0], []).append(word)', says: 'Makes an empty list under the first letter if there is none yet, then adds the word to that list.' },
    seeAlso: ['dict.get'],
  },
  {
    name: 'list.sort',
    aliases: ['sort'],
    lang: 'python',
    kind: 'method',
    official: 'Sort the list in ascending order and return None.',
    source: 'Python built-in docstring (list.sort)',
    when: 'You want a list put in order in place. It gives back None, so names = names.sort() leaves you with None; use sorted(...) when you want a new list. key= says what to sort by.',
    flags: [['key=', 'a function that gives the value to sort each item by']],
    example: { command: 'rows.sort(key=lambda r: r[1])', says: 'Reorders rows in place by the second item of each row.' },
    seeAlso: ['sorted'],
  },
  {
    name: 'dict.keys',
    aliases: ['keys'],
    lang: 'python',
    kind: 'method',
    official: 'D.keys() -> a set-like object providing a view on D\'s keys',
    source: 'Python built-in docstring (dict.keys)',
    when: 'You want only the keys of a dictionary. Looping over a dict already gives its keys, so you mostly need this to make a list of them or to compare key sets. It is a live view, not a list.',
    example: { command: 'list(limits.keys())', says: 'Gives a list of every key in limits.' },
    seeAlso: ['dict.values', 'dict.items'],
  },
  {
    name: 'int.from_bytes',
    aliases: ['from_bytes'],
    lang: 'python',
    kind: 'method',
    official: 'Return the integer represented by the given array of bytes.',
    source: 'Python built-in docstring (int.from_bytes)',
    when: 'You have raw bytes, from a sensor packet or a file header, and want the number they stand for. You must say the byte order: "big" puts the most important byte first, "little" puts it last. Pick the wrong one and you get a different, wrong number with no error.',
    flags: [['bytes', 'the bytes to read'], ['byteorder', '"big" or "little": which end holds the most important byte']],
    example: { command: 'int.from_bytes(hdr[0:2], "big")', says: 'Reads the first two bytes of hdr as one number, most important byte first.' },
    seeAlso: ['int.to_bytes'],
  },
  {
    name: 'dict.update',
    aliases: ['update'],
    lang: 'python',
    kind: 'method',
    official: 'Update D from dict/iterable E and F.',
    source: 'Python built-in docstring (dict.update)',
    when: 'You want to add or overwrite several keys at once from another dict. Keys already there get the new value; nothing is removed. Sets have update too, where it adds every item from the other collection.',
    flags: [['other', 'a dict (or list of pairs) whose keys to copy in'], ['key=value', 'extra keys given by name']],
    example: { command: 'config.update({"rate_hz": 50, "mode": "SAFE"})', says: 'Sets rate_hz to 50 and mode to "SAFE" in config, adding them if missing.' },
    seeAlso: ['dict.setdefault', 'dict.get'],
  },
  {
    name: 'datetime.date.isoformat',
    aliases: ['isoformat'],
    lang: 'python',
    kind: 'method',
    official: 'Return string in ISO 8601 format, YYYY-MM-DD.',
    source: 'Python built-in docstring (datetime.date.isoformat)',
    when: 'You want a date as text in the standard year-month-day form, for saving to JSON or a file. That form also sorts correctly as plain text. date.fromisoformat turns it back into a date.',
    example: { command: 'date(2026, 3, 15).isoformat()', says: 'Gives "2026-03-15".' },
    seeAlso: ['datetime.date.strftime'],
  },
  {
    name: 'collections.Counter.total',
    aliases: ['total'],
    lang: 'python',
    kind: 'method',
    official: 'Sum of the counts',
    source: 'Python built-in docstring (collections.Counter.total)',
    when: 'You have a Counter and want the sum of all its counts, for example the number of words counted, not the number of different words. It needs Python 3.10 or later.',
    example: { command: 'Counter("banana").total()', says: 'Gives 6: three a\'s, two n\'s and one b.' },
    seeAlso: ['collections.Counter.most_common'],
  },
  {
    name: 'io.StringIO.getvalue',
    aliases: ['getvalue'],
    lang: 'python',
    kind: 'method',
    official: 'Retrieve the entire contents of the object.',
    source: 'Python built-in docstring (io.StringIO.getvalue)',
    when: 'You wrote into a StringIO, for example with csv.writer, and want everything in it as one string. Use this rather than read, because read starts at the current position, which is at the end after writing.',
    example: { command: 'print(repr(out.getvalue()))', says: 'Shows the whole text written into out, such as \'name,score\\nada,91\\n\'.' },
    seeAlso: ['io.StringIO.write', 'io.StringIO.read'],
  },
  {
    name: 'str.rstrip',
    aliases: ['rstrip'],
    lang: 'python',
    kind: 'method',
    official: 'Return a copy of the string with trailing whitespace removed.',
    source: 'Python built-in docstring (str.rstrip)',
    when: 'You want to drop only the trailing spaces and newline, keeping any spaces at the start, such as the indent of a code line. Give it characters to remove instead, such as "=". bytes has rstrip too.',
    flags: [['chars', 'the characters to remove from the end instead of whitespace']],
    example: { command: 'line.rstrip()', says: 'Gives the line without the spaces and newline at its end; the start is untouched.' },
    seeAlso: ['str.strip'],
  },
  {
    name: 'str.endswith',
    aliases: ['endswith'],
    lang: 'python',
    kind: 'method',
    official: 'Return True if S ends with the specified suffix, False otherwise.',
    source: 'Python built-in docstring (str.endswith)',
    when: 'You want to check how a string ends, such as a file name ending in ".csv" or a key ending in "_g". It is exact about case: ".CSV" does not match ".csv".',
    flags: [['suffix', 'the text to look for at the end (a tuple of choices works too)']],
    example: { command: '"report.csv".endswith(".csv")', says: 'Gives True.' },
    seeAlso: ['str.startswith'],
  },
  {
    name: 'collections.deque.rotate',
    aliases: ['rotate'],
    lang: 'python',
    kind: 'method',
    official: 'Rotate the deque n steps to the right (default n=1).',
    source: 'Python built-in docstring (collections.deque.rotate)',
    when: 'You want the items of a deque moved round in a circle, like a ring of crew seats. A positive number moves items to the right, so the last item comes to the front; a negative number goes the other way.',
    flags: [['n', 'how many steps to move right (negative moves left; 1 if you leave it out)']],
    example: { command: 'dq.rotate(1)', says: 'Moves every item one place to the right; the last item wraps round to the front.' },
    seeAlso: ['collections.deque.appendleft', 'collections.deque.popleft'],
  },
  {
    name: 'dict.fromkeys',
    aliases: ['fromkeys'],
    lang: 'python',
    kind: 'method',
    official: 'Create a new dictionary with keys from iterable and values set to value.',
    source: 'Python built-in docstring (dict.fromkeys)',
    when: 'You want a new dict with a list of keys all set to the same starting value, such as every crew member at 0. Called on dict itself. Watch out: every key shares that one value, so dict.fromkeys(names, []) gives all keys the same list; use {name: [] for name in names} for separate lists.',
    flags: [['iterable', 'the keys'], ['value', 'the value every key starts with (None if you leave it out)']],
    example: { command: 'dict.fromkeys(["ada", "lin"], 0)', says: 'Gives {"ada": 0, "lin": 0}.' },
  },
  {
    name: 'float.is_integer',
    aliases: ['is_integer'],
    lang: 'python',
    kind: 'method',
    official: 'Return True if the float is an integer.',
    source: 'Python built-in docstring (float.is_integer)',
    when: 'You have a float and want to know if it has nothing after the decimal point, so you can show 3.0 as 3. Rounding errors can surprise you: adding 0.1 ten times gives 0.9999999999999999, which is not an integer.',
    example: { command: '(3.0).is_integer()', says: 'Gives True. (3.5).is_integer() gives False.' },
  },
  {
    name: 're.Pattern.fullmatch',
    aliases: ['fullmatch'],
    lang: 'python',
    kind: 'method',
    official: 'Matches against all of the string.',
    source: 'Python built-in docstring (re.Pattern.fullmatch)',
    when: 'You want to check that a whole string fits your pattern, such as an amount with at most two decimals, with nothing left over at either end. match only checks the start, and $ can still let a final newline through; fullmatch does not.',
    flags: [['string', 'the text that must match from its first character to its last']],
    example: { command: 'bool(AMOUNT.fullmatch("12.345"))', says: 'Gives False: the pattern allows two decimals, so the 5 is left over.' },
    seeAlso: ['re.Pattern.match', 're.Pattern.search'],
  },
  {
    name: 'str.title',
    aliases: ['title'],
    lang: 'python',
    kind: 'method',
    official: 'Return a version of the string where each word is titlecased.',
    source: 'Python built-in docstring (str.title)',
    when: 'You want each word to start with a capital letter, such as a crew name typed in lowercase. It treats any letter after a non-letter as a new word, so "o\'neil" becomes "O\'Neil" and "it\'s" becomes "It\'S".',
    example: { command: '"ada lovelace".title()', says: 'Gives "Ada Lovelace".' },
    seeAlso: ['str.capitalize', 'str.upper', 'str.lower'],
  },
  {
    name: 'list.extend',
    aliases: ['extend'],
    lang: 'python',
    kind: 'method',
    official: 'Extend list by appending elements from the iterable.',
    source: 'Python built-in docstring (list.extend)',
    when: 'You want to add every item of another list (or any iterable) to the end of a list, one by one. append would add the whole other list as one item instead. A deque has extend too.',
    flags: [['iterable', 'the items to add, in order']],
    example: { command: 'out = ["x"]; out.extend(["a", "b"])', says: 'Leaves out as ["x", "a", "b"].' },
    seeAlso: ['list.append', 'list.insert'],
  },
  {
    name: 'list.remove',
    aliases: ['remove'],
    lang: 'python',
    kind: 'method',
    official: 'Remove first occurrence of value.',
    source: 'Python built-in docstring (list.remove)',
    when: 'You want to take a value out of a list and do not know its position. It removes only the first copy, and raises ValueError if the value is not there. Removing items from a list while looping over it skips items; loop over a copy or build a new list. Sets and deques have remove too.',
    flags: [['value', 'the item to find and remove']],
    example: { command: 'crew.remove("Sam")', says: 'Takes the first "Sam" out of the crew list.' },
    seeAlso: ['list.pop', 'list.clear'],
  },
  {
    name: 'collections.Counter.most_common',
    aliases: ['most_common'],
    lang: 'python',
    kind: 'method',
    official: 'List the n most common elements and their counts from the most common to the least.',
    source: 'Python built-in docstring (collections.Counter.most_common)',
    when: 'You counted things with a Counter and want the top ones, such as the most frequent words or fault codes. It gives a list of (item, count) pairs, biggest first. Leave out the number to get them all.',
    flags: [['n', 'how many of the top items to give (all of them if you leave it out)']],
    example: { command: 'Counter(ids).most_common(1)', says: 'Gives a one-item list holding the most frequent id and its count, such as [("GYRO", 4)].' },
    seeAlso: ['collections.Counter.total'],
  },
  {
    name: 're.Match.groups',
    aliases: ['groups'],
    lang: 'python',
    kind: 'method',
    official: 'Return a tuple containing all the subgroups of the match, from 1.',
    source: 'Python built-in docstring (re.Match.groups)',
    when: 'A match succeeded and you want what every pair of brackets caught, all at once, as a tuple. That makes it easy to unpack into names. A group that took no part in the match comes back as None.',
    example: { command: 'LET.match("let rate = 1.5").groups()', says: 'Gives ("rate", " 1.5"), one item per bracketed group.' },
    seeAlso: ['re.Match.group'],
  },
  {
    name: 'str.isalnum',
    aliases: ['isalnum'],
    lang: 'python',
    kind: 'method',
    official: 'Return True if the string is an alpha-numeric string, False otherwise.',
    source: 'Python built-in docstring (str.isalnum)',
    when: 'You want to check that a string (often one character) is only letters and digits, such as when turning a title into a web-address slug. Spaces, dots and dashes make it False, and so does the empty string. Accented letters count as letters.',
    example: { command: '"abc123".isalnum()', says: 'Gives True. "a-1".isalnum() gives False because of the dash.' },
    seeAlso: ['str.isdigit', 'str.isspace'],
  },
  {
    name: 'bytes.decode',
    aliases: ['decode'],
    lang: 'python',
    kind: 'method',
    official: 'Decode the bytes using the codec registered for encoding.',
    source: 'Python built-in docstring (bytes.decode)',
    when: 'You have bytes, from a file header, a network packet or base64, and need text. With no argument it assumes UTF-8; if the bytes are in another encoding, say which, such as "latin1", or you get an error or garbled letters. The opposite step is str.encode.',
    flags: [['encoding', 'how the bytes stand for letters, such as "utf-8" (the default) or "latin1"']],
    example: { command: 'head[10:].decode("latin1")', says: 'Turns the bytes from position 10 on into text, reading them as Latin-1.' },
    seeAlso: ['str.encode'],
  },
  {
    name: 'str.index',
    aliases: ['index'],
    lang: 'python',
    kind: 'method',
    official: 'Return the lowest index in S where substring sub is found, such that sub is contained within S[start:end].',
    source: 'Python built-in docstring (str.index)',
    when: 'You want the position where some text first appears in a string. It raises ValueError when the text is not there; str.find gives -1 instead. Lists and tuples have index too, where it finds the position of an item equal to the value.',
    flags: [['sub', 'the text (or, on a list, the item) to look for']],
    example: { command: '"GYRO_X".index("_")', says: 'Gives 4, the position of the underscore (counting from 0).' },
    seeAlso: ['str.count'],
  },
  {
    name: 'int.conjugate',
    aliases: ['conjugate'],
    lang: 'python',
    kind: 'method',
    official: 'Returns self, the complex conjugate of any int.',
    source: 'Python built-in docstring (int.conjugate)',
    when: 'You rarely call it on an int: it is there so an int works anywhere a complex number is expected, and it simply gives the same number back. On complex numbers, and on quaternion classes in the attitude lessons, conjugate flips the sign of the imaginary parts, which undoes a rotation for a unit quaternion.',
    example: { command: '(5).conjugate()', says: 'Gives 5. (3+4j).conjugate() gives (3-4j).' },
  },
  {
    name: 'int.as_integer_ratio',
    aliases: ['as_integer_ratio'],
    lang: 'python',
    kind: 'method',
    official: 'Return integer ratio.',
    source: 'Python built-in docstring (int.as_integer_ratio)',
    when: 'You want a number written exactly as a fraction of two whole numbers. For an int the bottom is always 1. On a float it shows the exact value stored, which is how you see that 0.1 is not quite one tenth.',
    example: { command: 'print((0.1).as_integer_ratio())', says: 'Prints (3602879701896397, 36028797018963968), the exact fraction stored for 0.1.' },
    seeAlso: ['float.hex'],
  },
  {
    name: 'io.StringIO.flush',
    aliases: ['flush'],
    lang: 'python',
    kind: 'method',
    official: 'Flush write buffers, if applicable.',
    source: 'Python built-in docstring (io.StringIO.flush)',
    when: 'You are writing to a file-like object and want what is waiting in its buffer sent out now, without closing it, as a long-running logger may want after each line. On a StringIO it does nothing, since there is no buffer to empty.',
    example: { command: 'log.flush()', says: 'Sends anything still waiting in log\'s buffer out to the file.' },
    seeAlso: ['io.StringIO.close', 'io.StringIO.write'],
  },
  {
    name: 'int.to_bytes',
    aliases: ['to_bytes'],
    lang: 'python',
    kind: 'method',
    official: 'Return an array of bytes representing an integer.',
    source: 'Python built-in docstring (int.to_bytes)',
    when: 'You want a number as raw bytes, to build a packet or compare with a sensor\'s output. Say how many bytes and which byte order. If the number is too big to fit, it raises OverflowError.',
    flags: [['length', 'how many bytes to use'], ['byteorder', '"big" or "little": which end holds the most important byte']],
    example: { command: 'n.to_bytes(2, "little").hex(" ")', says: 'For n = 500, gives "f4 01": two bytes, least important first.' },
    seeAlso: ['int.from_bytes'],
  },
  {
    name: 're.Match.end',
    aliases: ['end'],
    lang: 'python',
    kind: 'method',
    official: 'Return index of the end of the substring matched by group.',
    source: 'Python built-in docstring (re.Match.end)',
    when: 'A match succeeded and you want the position just after where it stopped, so a tokenizer can carry on from there. Give a group number to get where that group ended instead.',
    flags: [['group', 'which group to ask about (the whole match if you leave it out)']],
    example: { command: 'm = NUM.match("12.5 m"); m.end()', says: 'Gives 4: the match "12.5" stops just before position 4.' },
    seeAlso: ['re.Match.group'],
  },
  {
    name: 'collections.deque.appendleft',
    aliases: ['appendleft'],
    lang: 'python',
    kind: 'method',
    official: 'Add an element to the left side of the deque.',
    source: 'Python built-in docstring (collections.deque.appendleft)',
    when: 'You want to add an item at the front of a deque. It is fast at any size, unlike list.insert(0, x), which shifts every item.',
    flags: [['x', 'the item to add at the front']],
    example: { command: 'q.appendleft(0)', says: 'Puts 0 at the left end of the deque q.' },
    seeAlso: ['collections.deque.popleft', 'list.insert'],
  },
  {
    name: 'float.fromhex',
    aliases: ['fromhex'],
    lang: 'python',
    kind: 'method',
    official: 'Create a floating-point number from a hexadecimal string.',
    source: 'Python built-in docstring (float.fromhex)',
    when: 'You have a float written in hex, such as one printed with float.hex, and want the exact number back. Called on float itself. bytes.fromhex, which the lessons use to write a packet header, is a different method: it turns hex digit pairs into bytes.',
    flags: [['string', 'the hex text to read']],
    example: { command: 'float.fromhex("0x1.999999999999ap-4")', says: 'Gives 0.1, exactly the float that was printed.' },
    seeAlso: ['float.hex'],
  },
  {
    name: 'str.capitalize',
    aliases: ['capitalize'],
    lang: 'python',
    kind: 'method',
    official: 'Return a capitalized version of the string.',
    source: 'Python built-in docstring (str.capitalize)',
    when: 'You want the first letter of a string in capitals, such as a label at the start of a sentence. It also makes every other letter small, so "GPS drift" becomes "Gps drift".',
    example: { command: 'f"{name.capitalize()} rate (deg/s)"', says: 'For name = "roll", gives "Roll rate (deg/s)".' },
    seeAlso: ['str.title', 'str.upper'],
  },
  {
    name: 'list.insert',
    aliases: ['insert'],
    lang: 'python',
    kind: 'method',
    official: 'Insert object before index.',
    source: 'Python built-in docstring (list.insert)',
    when: 'You want to put an item into a list at a given position; the items from there on move one place right. insert(0, x) on a long list is slow, since everything shifts; a deque with appendleft is faster.',
    flags: [['index', 'the position the new item will have'], ['object', 'the item to put in']],
    example: { command: 'waypoints.insert(0, "launch pad")', says: 'Puts "launch pad" at the front of waypoints.' },
    seeAlso: ['list.append', 'list.pop', 'collections.deque.appendleft'],
  },
  {
    name: 'datetime.date.strftime',
    aliases: ['strftime'],
    lang: 'python',
    kind: 'method',
    official: 'format -> strftime() style string.',
    source: 'Python built-in docstring (datetime.date.strftime)',
    when: 'You want a date or time written out in your own format, such as "Sun 15 Mar". Each % code stands for one part. datetime objects have it too, with hour and minute codes that a plain date shows as zeros.',
    flags: [['%a', 'short day name, such as Sun'], ['%d', 'day of the month, two digits'], ['%b', 'short month name, such as Mar'], ['%H', 'hour, 00 to 23'], ['%M', 'minute, 00 to 59']],
    example: { command: 't.strftime("%a %d %b %H:%M")', says: 'Gives something like "Sun 15 Mar 09:30".' },
    seeAlso: ['datetime.date.isoformat'],
  },
  {
    name: 'int.bit_count',
    aliases: ['bit_count'],
    lang: 'python',
    kind: 'method',
    official: 'Number of ones in the binary representation of the absolute value of self.',
    source: 'Python built-in docstring (int.bit_count)',
    when: 'You want to know how many bits of a number are 1, such as how many status flags are on. It needs Python 3.10 or later; bin(x).count("1") works everywhere.',
    example: { command: 'status.bit_count()', says: 'For status = 0b1011, gives 3: three flags are on.' },
  },
  {
    name: 're.Pattern.search',
    aliases: ['search'],
    lang: 'python',
    kind: 'method',
    official: 'Scan through string looking for a match, and return a corresponding match object instance.',
    source: 'Python built-in docstring (re.Pattern.search)',
    when: 'You want to find your pattern anywhere in a string, not only at the start. It gives the first match as a match object, or None if there is none, so check before using the result.',
    flags: [['string', 'the text to look through']],
    example: { command: 'm = LINE.search(line)', says: 'Looks through line for the first place LINE matches and gives that match, or None.' },
    seeAlso: ['re.Pattern.match', 're.Pattern.fullmatch', 're.Match.group'],
  },
]
