import type { CommandRef } from './types'

export const COMMANDS: CommandRef[] = [
  {
    name: 'numpy.linspace',
    aliases: ['np.linspace'],
    lang: 'python',
    kind: 'function',
    official: 'Return evenly spaced numbers over a specified interval.',
    source: 'NumPy docstring',
    when: 'You want a fixed number of evenly spaced points between a start and an end, such as time stamps for a simulation or a plot. The third number is how many points, not the gap between them, and the end value is included: 201 points from 0 to 5 gives steps of 0.025.',
    flags: [
      ['start, stop', 'the first and last value'],
      ['num', 'how many points to make (50 if you leave it out)'],
      ['endpoint=False', 'leave the stop value out, handy for one full turn of an angle'],
      ['retstep=True', 'also hand back the step size between points'],
    ],
    example: { command: 't = np.linspace(0.0, 10.0, 5)', says: 'Makes the array [0. 2.5 5. 7.5 10.]: five points, both ends included.' },
    seeAlso: ['numpy.arange', 'numpy.logspace'],
  },
  {
    name: 'numpy.load',
    aliases: ['np.load'],
    lang: 'python',
    kind: 'function',
    official: 'Load arrays or pickled objects from ``.npy``, ``.npz`` or pickled files.',
    source: 'NumPy docstring',
    when: 'You want back an array you saved earlier with np.save (a .npy file) or np.savez (a .npz file), with its shape and type exactly as they were. For a file too big for memory, mmap_mode="r" opens it instantly and reads only the parts you touch.',
    flags: [
      ['file', 'the path of the .npy or .npz file'],
      ['mmap_mode="r"', 'leave the data on disk and read pieces only when you use them'],
      ['allow_pickle', 'off by default, because loading pickled Python objects can run someone else\'s code'],
    ],
    example: { command: 'gyro = np.load("gyro.npy")', says: 'Reads the array saved in gyro.npy back into memory, same shape and dtype as when it was saved.' },
    seeAlso: ['numpy.save', 'numpy.memmap'],
  },
  {
    name: 'numpy.loadtxt',
    aliases: ['np.loadtxt'],
    lang: 'python',
    kind: 'function',
    official: 'Load data from a text file.',
    source: 'NumPy docstring',
    when: 'You have a plain CSV or text file that holds only numbers, and you want it as a 2-D array with one column per field. Any text, such as a timestamp, makes it fail with "could not convert string to float"; use pandas for mixed columns.',
    flags: [
      ['delimiter=","', 'what separates the columns (spaces unless you say otherwise)'],
      ['skiprows=1', 'skip the first line, usually the header of column names'],
    ],
    example: { command: 'data = np.loadtxt("flight.csv", delimiter=",", skiprows=1)', says: 'Reads flight.csv, skips the header line, and gives a float64 array with one row per line and one column per field.' },
    seeAlso: ['numpy.savetxt', 'pandas.read_csv'],
  },
  {
    name: 'numpy.log',
    aliases: ['np.log'],
    lang: 'python',
    kind: 'function',
    official: 'Natural logarithm, element-wise.',
    source: 'NumPy docstring',
    when: 'You need the natural log (base e), as in the rocket equation. Careful: log of 0 gives -inf and log of a negative number gives nan, each with only a warning, not an error.',
    example: { command: 'dv = 311 * 9.80665 * np.log(m0 / m_dry)', says: 'Works out a rocket\'s delta-v from the rocket equation, using the natural log of the mass ratio.' },
    seeAlso: ['numpy.log10', 'numpy.log2', 'numpy.exp'],
  },
  {
    name: 'numpy.log10',
    aliases: ['np.log10'],
    lang: 'python',
    kind: 'function',
    official: 'Return the base 10 logarithm of the input array, element-wise.',
    source: 'NumPy docstring',
    when: 'You want the base-10 log, most often to turn a gain into decibels with 20 * np.log10(abs(g)). A gain of exactly 0 gives -inf.',
    example: { command: 'print(20 * np.log10(abs(h)))', says: 'Prints the gain h in decibels: 10 becomes 20.0, 0.1 becomes -20.0.' },
    seeAlso: ['numpy.log', 'numpy.logspace'],
  },
  {
    name: 'numpy.log2',
    aliases: ['np.log2'],
    lang: 'python',
    kind: 'function',
    official: 'Base-2 logarithm of `x`.',
    source: 'NumPy docstring',
    when: 'You want to know "2 to what power gives this?", for example how many times to halve a step size, or the order of accuracy from an error ratio. The answer is a float, so round it up with np.ceil before using it as a count.',
    example: { command: 'print(np.log2(1024))', says: 'Prints 10.0, because 2 to the 10th power is 1024.' },
    seeAlso: ['numpy.log', 'numpy.ceil'],
  },
  {
    name: 'numpy.logspace',
    aliases: ['np.logspace'],
    lang: 'python',
    kind: 'function',
    official: 'Return numbers spaced evenly on a log scale.',
    source: 'NumPy docstring',
    when: 'You want points spread evenly on a log scale, like frequencies for a Bode plot that cover 0.1 to 100 rad/s. The start and stop are powers of 10, not the values themselves: np.logspace(-1, 2, ...) runs from 0.1 to 100.',
    flags: [
      ['start, stop', 'the powers of 10 to begin and end at'],
      ['num', 'how many points to make'],
    ],
    example: { command: 'w = np.logspace(-1, 2, 2000)', says: 'Makes 2000 frequencies from 0.1 to 100 rad/s, spaced evenly on a log scale.' },
    seeAlso: ['numpy.linspace', 'numpy.log10'],
  },
  {
    name: 'numpy.max',
    aliases: ['np.max'],
    lang: 'python',
    kind: 'function',
    official: 'Return the maximum of an array or maximum along an axis.',
    source: 'NumPy docstring',
    when: 'You want the largest value in an array, or the largest in each row or column. One nan anywhere makes the answer nan; use np.nanmax to skip them.',
    flags: [
      ['axis', 'which direction to look along; that axis disappears from the result (leave out for the whole array)'],
    ],
    example: { command: 'print(np.max(np.abs(x - x_exact)))', says: 'Prints the worst error: the largest gap between the computed and exact values.' },
    seeAlso: ['numpy.maximum', 'numpy.argmax', 'max'],
  },
  {
    name: 'numpy.maximum',
    aliases: ['np.maximum'],
    lang: 'python',
    kind: 'function',
    official: 'Element-wise maximum of array elements.',
    source: 'NumPy docstring',
    when: 'You want to compare two arrays (or an array and a number) item by item and keep the bigger of each pair, such as clipping negatives to zero with np.maximum(0.0, x). Not the same as np.max, which finds the single largest value in one array.',
    example: { command: 'sunlit = np.maximum(0.0, normals @ s_hat)', says: 'Keeps each panel\'s sunlight value, but turns every negative one (a panel facing away from the Sun) into 0.0.' },
    seeAlso: ['numpy.minimum', 'numpy.max', 'numpy.clip'],
  },
  {
    name: 'numpy.mean',
    aliases: ['np.mean'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the arithmetic mean along the specified axis.',
    source: 'NumPy docstring',
    when: 'You want the average of an array, or one average per row or column. A single nan makes the result nan; use np.nanmean to skip gaps.',
    flags: [
      ['axis', 'which direction to average along; axis=0 gives one mean per column'],
    ],
    example: { command: 'print(np.mean([10.0, 20.0, 60.0]))', says: 'Prints 30.0, the average of the three values.' },
    seeAlso: ['numpy.median', 'numpy.nanmean', 'numpy.std'],
  },
  {
    name: 'numpy.median',
    aliases: ['np.median'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the median along the specified axis.',
    source: 'NumPy docstring',
    when: 'You want the middle value, which one wild reading cannot drag around the way it drags the mean. Good for a typical time step or a noise floor.',
    flags: [
      ['axis', 'which direction to take the median along'],
      ['keepdims=True', 'keep the reduced axis as length 1 so the result still lines up with the original'],
    ],
    example: { command: 'print(np.median([3.0, 100.0, 5.0]))', says: 'Prints 5.0: the middle value, not pulled up by the 100.' },
    seeAlso: ['numpy.mean', 'numpy.percentile'],
  },
  {
    name: 'numpy.memmap',
    aliases: ['np.memmap'],
    lang: 'python',
    kind: 'class',
    official: 'Create a memory-map to an array stored in a *binary* file on disk.',
    source: 'NumPy docstring',
    when: 'Your data is too big for memory, like hours of telemetry, and you want to treat the file as if it were an array. A raw binary file forgets its dtype and shape, so you must give the same ones every time you open it.',
    flags: [
      ['filename', 'the file on disk'],
      ['dtype', 'the type of each number, such as np.float64'],
      ['mode', '"r" read only, "r+" read and write, "w+" create a new file'],
      ['shape', 'the array\'s shape (needed when creating)'],
    ],
    example: { command: 'tlm = np.memmap("telemetry.f64", dtype=np.float64, mode="r").reshape(-1, 8)', says: 'Opens the telemetry file as an array with 8 columns, reading from disk only the rows you actually use.' },
    seeAlso: ['numpy.load', 'numpy.lib.format.open_memmap'],
  },
  {
    name: 'numpy.meshgrid',
    aliases: ['np.meshgrid'],
    lang: 'python',
    kind: 'function',
    official: 'Return a tuple of coordinate matrices from coordinate vectors.',
    source: 'NumPy docstring',
    when: 'You have a list of x values and a list of y values and want every (x, y) pair laid out as a grid, to evaluate a function over an image or a table. By default the first two axes are swapped from what you might expect; indexing="ij" keeps them in the order you passed them.',
    flags: [
      ['indexing="ij"', 'make the first index follow the first input, the second follow the second'],
    ],
    example: { command: 'xs, ys = np.meshgrid(np.arange(640), np.arange(480))', says: 'Makes two 480 by 640 arrays: xs holds each pixel\'s column number, ys its row number.' },
    seeAlso: ['numpy.mgrid', 'numpy.arange'],
  },
  {
    name: 'numpy.mgrid',
    aliases: ['np.mgrid'],
    lang: 'python',
    kind: 'constant',
    official: 'An instance which returns a dense multi-dimensional "meshgrid".',
    source: 'NumPy docstring',
    when: 'A shortcut for a grid of index numbers, written with square brackets and slices instead of a function call. Like range, the stop is left out: 0:3 gives 0, 1, 2.',
    example: { command: 'yy, xx = np.mgrid[0:480, 0:640]', says: 'Makes two 480 by 640 arrays holding each pixel\'s row number and column number.' },
    seeAlso: ['numpy.meshgrid', 'numpy.r_'],
  },
  {
    name: 'numpy.minimum',
    aliases: ['np.minimum'],
    lang: 'python',
    kind: 'function',
    official: 'Element-wise minimum of array elements.',
    source: 'NumPy docstring',
    when: 'You want to compare two arrays (or an array and a number) item by item and keep the smaller of each pair, such as capping values at 1.0. Not the same as np.min, which finds the single smallest value.',
    example: { command: 'w = np.minimum(1.0, k / r)', says: 'Gives a weight for each residual, never bigger than 1.0.' },
    seeAlso: ['numpy.maximum', 'numpy.clip'],
  },
  {
    name: 'numpy.moveaxis',
    aliases: ['np.moveaxis'],
    lang: 'python',
    kind: 'function',
    official: 'Move axes of an array to new positions.',
    source: 'NumPy docstring',
    when: 'Your array\'s axes are in the wrong order for what you want to do next, for example quaternions stored as rows of 4 when you want to unpack the four parts. It returns a view, so no data is copied.',
    flags: [
      ['source', 'the axis to move (-1 means the last)'],
      ['destination', 'where it should end up'],
    ],
    example: { command: 'w, x, y, z = np.moveaxis(q, -1, 0)', says: 'Moves the last axis (the 4 parts) to the front, so each of w, x, y, z gets one part for every quaternion.' },
    seeAlso: ['numpy.ndarray'],
  },
  {
    name: 'numpy.nan',
    aliases: ['np.nan'],
    lang: 'python',
    kind: 'constant',
    official: 'IEEE 754 floating point representation of Not a Number (NaN).',
    source: 'NumPy documentation (Constants)',
    when: 'You need to mark a missing or bad value inside a float array, like a sensor dropout. NaN spreads through any arithmetic and is not equal to anything, even itself, so np.nan == np.nan is False; test for it with np.isnan.',
    example: { command: 'T = np.array([21.4, 21.9, np.nan, 22.3])', says: 'Makes a temperature array with the third reading marked as missing.' },
    seeAlso: ['numpy.isnan', 'numpy.nanmean', 'numpy.inf'],
  },
  {
    name: 'numpy.nanmean',
    aliases: ['np.nanmean'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the arithmetic mean along the specified axis, ignoring NaNs.',
    source: 'NumPy docstring',
    when: 'Your data has gaps marked as nan and you want the average of the values that are really there. If a whole row or column is nan, the answer for it is nan, with a warning.',
    flags: [
      ['axis', 'which direction to average along; axis=0 gives one mean per column'],
    ],
    example: { command: 'print(np.nanmean(np.array([21.4, np.nan, 22.0])))', says: 'Prints 21.7, the mean of the two real readings, skipping the gap.' },
    seeAlso: ['numpy.mean', 'numpy.nanstd', 'numpy.isnan'],
  },
  {
    name: 'numpy.nanstd',
    aliases: ['np.nanstd'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the standard deviation along the specified axis, while ignoring NaNs.',
    source: 'NumPy docstring',
    when: 'Your data has gaps marked as nan and you want the spread of the real values. Like np.std it divides by N unless you pass ddof=1.',
    flags: [
      ['ddof=1', 'divide by N - 1, the sample standard deviation'],
    ],
    example: { command: 'print(np.nanstd(np.array([1.0, np.nan, 3.0])))', says: 'Prints 1.0, the spread of the two real values.' },
    seeAlso: ['numpy.std', 'numpy.nanmean'],
  },
  {
    name: 'numpy.ndarray',
    aliases: ['np.ndarray'],
    lang: 'python',
    kind: 'class',
    official: 'An array object represents a multidimensional, homogeneous array of fixed-size items.',
    source: 'NumPy docstring',
    when: 'It is the type of every NumPy array, so you write it in type hints like def f(x: np.ndarray). Build arrays with np.array or np.zeros; calling np.ndarray(...) directly is a low-level trick, mainly for wrapping memory that already exists, such as shared memory.',
    flags: [
      ['shape', 'the size along each axis'],
      ['dtype', 'the type of every item'],
      ['buffer', 'existing memory to use instead of new memory'],
    ],
    example: { command: 'def speed(v: np.ndarray) -> np.ndarray:', says: 'Labels the function as taking a NumPy array and giving one back.' },
    seeAlso: ['numpy.array', 'numpy.typing.NDArray'],
  },
  {
    name: 'numpy.nonzero',
    aliases: ['np.nonzero'],
    lang: 'python',
    kind: 'function',
    official: 'Return the indices of the elements that are non-zero.',
    source: 'NumPy docstring',
    when: 'You have a True/False mask and want the positions of the Trues. It always returns a tuple with one index array per axis, so for a 1-D array add [0] to get the positions themselves.',
    example: { command: 'print(np.nonzero(alt > 100.0)[0])', says: 'Prints the positions where the altitude is above 100, such as [1 3].' },
    seeAlso: ['numpy.flatnonzero', 'numpy.where', 'numpy.argmax'],
  },
  {
    name: 'numpy.ones',
    aliases: ['np.ones'],
    lang: 'python',
    kind: 'function',
    official: 'Return a new array of given shape and type, filled with ones.',
    source: 'NumPy docstring',
    when: 'You need an array of ones to start from, such as a column of ones in a fit. The default type is float64; pass dtype to get something else.',
    flags: [
      ['shape', 'one number, or a tuple like (2, 3)'],
      ['dtype', 'the type of each item, such as np.int64'],
    ],
    example: { command: 'print(np.ones((2, 3)))', says: 'Prints a 2 by 3 array of 1. values.' },
    seeAlso: ['numpy.zeros', 'numpy.ones_like', 'numpy.full'],
  },
  {
    name: 'numpy.ones_like',
    aliases: ['np.ones_like'],
    lang: 'python',
    kind: 'function',
    official: 'Return an array of ones with the same shape and type as a given array.',
    source: 'NumPy docstring',
    when: 'You want an array of ones that matches another array\'s shape, such as the constant column in a least-squares fit. It copies the type too, so ones_like of an integer array is integers.',
    example: { command: 'H = np.column_stack([np.ones_like(t), t])', says: 'Builds a two-column matrix: a column of ones for the bias and a column of times for the drift.' },
    seeAlso: ['numpy.ones', 'numpy.zeros_like'],
  },
  {
    name: 'numpy.outer',
    aliases: ['np.outer'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the outer product of two vectors.',
    source: 'NumPy docstring',
    when: 'You want every item of one vector multiplied by every item of another, laid out as a matrix, as in inertia and projection formulas. Inputs are flattened to 1-D first, so it is not a general matrix product.',
    example: { command: 'print(np.outer([1, 2, 3], [1, 10]))', says: 'Prints a 3 by 2 matrix: rows [1 10], [2 20] and [3 30].' },
    seeAlso: ['numpy.dot', 'numpy.eye'],
  },
  {
    name: 'numpy.percentile',
    aliases: ['np.percentile'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the q-th percentile of the data along the specified axis.',
    source: 'NumPy docstring',
    when: 'You want the value that a given percent of your data falls below, such as the 99.87th percentile of a Monte Carlo miss distance, or a band holding 99 percent of runs. q is a percent from 0 to 100, not a fraction.',
    flags: [
      ['q', 'the percent, or a list of them like [0.5, 99.5]'],
      ['axis', 'which direction to work along; axis=0 gives one answer per time step'],
    ],
    example: { command: 'lo, hi = np.percentile(runs, [0.5, 99.5], axis=0)', says: 'Gives the lower and upper edge of the band that holds 99 percent of the runs at each time step.' },
    seeAlso: ['numpy.median', 'numpy.std'],
  },
  {
    name: 'numpy.pi',
    aliases: ['np.pi'],
    lang: 'python',
    kind: 'constant',
    official: '``pi = 3.1415926535897932384626433...``',
    source: 'NumPy documentation (Constants)',
    when: 'Any time you need pi, for circles, angles and frequencies. It is a float, so sin(np.pi) comes out as a tiny number near zero, not exactly 0.',
    example: { command: 'w = 2 * np.pi * 47.0', says: 'Turns 47 Hz into an angular frequency of about 295.3 rad/s.' },
    seeAlso: ['math.pi', 'numpy.radians'],
  },
  {
    name: 'numpy.poly',
    aliases: ['np.poly'],
    lang: 'python',
    kind: 'function',
    official: 'Find the coefficients of a polynomial with the given sequence of roots.',
    source: 'NumPy docstring',
    when: 'You know where you want the roots, such as the poles of a controller, and need the polynomial that has them. Coefficients come out highest power first; with complex poles, take .real at the end.',
    example: { command: 'print(np.poly([-1.0, -2.0]))', says: 'Prints [1. 3. 2.], meaning s^2 + 3s + 2, whose roots are -1 and -2.' },
    seeAlso: ['numpy.roots', 'numpy.polyval'],
  },
  {
    name: 'numpy.polyfit',
    aliases: ['np.polyfit'],
    lang: 'python',
    kind: 'function',
    official: 'Least squares polynomial fit.',
    source: 'NumPy docstring',
    when: 'You have points and want the polynomial of a chosen degree that fits them best. Coefficients come out highest power first. A high degree over many points can go wild between them, so keep the degree low.',
    flags: [
      ['x, y', 'the points to fit'],
      ['deg', 'the degree of the polynomial'],
    ],
    example: { command: 'print(np.polyfit([0, 1, 2], [1, 3, 5], 1))', says: 'Prints [2. 1.], the line y = 2x + 1.' },
    seeAlso: ['numpy.polyval', 'numpy.linalg.lstsq'],
  },
  {
    name: 'numpy.polymul',
    aliases: ['np.polymul'],
    lang: 'python',
    kind: 'function',
    official: 'Find the product of two polynomials.',
    source: 'NumPy docstring',
    when: 'You want to multiply two polynomials given as coefficient lists, such as building a transfer function\'s denominator. Coefficients go highest power first.',
    example: { command: 'den = np.polymul([1.0, 0.0, 0.0], [0.02, 1.0])', says: 'Multiplies s^2 by (0.02s + 1) and gives [0.02 1. 0. 0.].' },
    seeAlso: ['numpy.polyval', 'numpy.roots'],
  },
  {
    name: 'numpy.polynomial',
    aliases: ['np.polynomial'],
    lang: 'python',
    kind: 'module',
    official: 'A sub-package for efficiently dealing with polynomials.',
    source: 'NumPy docstring',
    when: 'You want NumPy\'s newer polynomial tools, including special families like Legendre polynomials. Watch out: here coefficients go lowest power first, the opposite of np.polyval and np.roots.',
    example: { command: 'from numpy.polynomial import legendre as L', says: 'Loads the Legendre polynomial tools under the short name L.' },
    seeAlso: ['numpy.polynomial.legendre'],
  },
  {
    name: 'numpy.polynomial.legendre',
    aliases: ['np.polynomial.legendre'],
    lang: 'python',
    kind: 'module',
    official: 'This module provides a number of objects (mostly functions) useful for dealing with Legendre series, including a `Legendre` class that encapsulates the usual arithmetic operations.',
    source: 'NumPy docstring',
    when: 'You work with Legendre polynomials, for example to place the collocation points in a spectral method. Lessons import it under a short name like L or leg; coefficients go lowest power first.',
    example: { command: 'from numpy.polynomial import legendre as leg', says: 'Loads the Legendre tools under the short name leg, so you can write leg.legroots.' },
    seeAlso: ['numpy.polynomial.legendre.Legendre', 'numpy.polynomial.legendre.legroots'],
  },
  {
    name: 'numpy.polynomial.legendre.Legendre',
    aliases: ['np.polynomial.legendre.Legendre', 'L.Legendre'],
    lang: 'python',
    kind: 'class',
    official: 'A Legendre series class.',
    source: 'NumPy docstring',
    when: 'You want a Legendre polynomial as one object that you can differentiate, add or find the roots of with methods like .deriv() and .roots(). The coefficients it holds are for P0, P1, P2 and so on, lowest first.',
    example: { command: 'p = L.Legendre([0, 0, 1])', says: 'Makes the Legendre polynomial P2(x), which is (3x^2 - 1) / 2.' },
    seeAlso: ['numpy.polynomial.legendre.Legendre.basis', 'numpy.polynomial.legendre'],
  },
  {
    name: 'numpy.polynomial.legendre.Legendre.basis',
    aliases: ['np.polynomial.legendre.Legendre.basis', 'L.Legendre.basis'],
    lang: 'python',
    kind: 'method',
    official: 'Series basis polynomial of degree `deg`.',
    source: 'NumPy docstring',
    when: 'You want the single Legendre polynomial of a given degree, P_N, as an object. Chain methods on it: .deriv() for its derivative and .roots() for where it crosses zero.',
    flags: [
      ['deg', 'the degree N of the polynomial'],
    ],
    example: { command: 'print(L.Legendre.basis(2).roots())', says: 'Prints [-0.57735027 0.57735027], the two points where P2 is zero.' },
    seeAlso: ['numpy.polynomial.legendre.Legendre', 'numpy.polynomial.legendre.legroots'],
  },
  {
    name: 'numpy.polynomial.legendre.legder',
    aliases: ['np.polynomial.legendre.legder', 'leg.legder', 'legder'],
    lang: 'python',
    kind: 'function',
    official: 'Differentiate a Legendre series.',
    source: 'NumPy docstring',
    when: 'You have a Legendre series as a list of coefficients and want its derivative, also as Legendre coefficients. The result is one shorter than what you passed in.',
    example: { command: 'print(leg.legder([0, 0, 1]))', says: 'Prints [0. 3.]: the derivative of P2 is 3 times P1.' },
    seeAlso: ['numpy.polynomial.legendre.legroots'],
  },
  {
    name: 'numpy.polynomial.legendre.legroots',
    aliases: ['np.polynomial.legendre.legroots', 'leg.legroots', 'legroots'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the roots of a Legendre series.',
    source: 'NumPy docstring',
    when: 'You want the points where a Legendre series is zero, such as the inner nodes of Legendre-Gauss-Lobatto collocation. Sort the result yourself if you need the order.',
    example: { command: 'print(leg.legroots([0, 0, 1]))', says: 'Prints [-0.57735027 0.57735027], where P2 is zero.' },
    seeAlso: ['numpy.polynomial.legendre.legder', 'numpy.sort'],
  },
  {
    name: 'numpy.polyval',
    aliases: ['np.polyval'],
    lang: 'python',
    kind: 'function',
    official: 'Evaluate a polynomial at specific values.',
    source: 'NumPy docstring',
    when: 'You have polynomial coefficients and want its value at some points, such as a transfer function at s = 1j * w for a Bode plot. Coefficients go highest power first.',
    flags: [
      ['p', 'the coefficients, highest power first'],
      ['x', 'the value or array of values to plug in'],
    ],
    example: { command: 'g = np.polyval(num, 1j * w) / np.polyval(den, 1j * w)', says: 'Works out the transfer function\'s complex gain at every frequency in w.' },
    seeAlso: ['numpy.roots', 'numpy.polyfit'],
  },
  {
    name: 'numpy.prod',
    aliases: ['np.prod'],
    lang: 'python',
    kind: 'function',
    official: 'Return the product of array elements over a given axis.',
    source: 'NumPy docstring',
    when: 'You want everything in an array multiplied together, such as the volume of a box from its three sides. Integers can overflow and wrap around without an error, so use floats for big products.',
    example: { command: 'print(np.prod([2.0, 3.0, 4.0]))', says: 'Prints 24.0.' },
    seeAlso: ['numpy.sum', 'numpy.cumsum'],
  },
  {
    name: 'numpy.ptp',
    aliases: ['np.ptp'],
    lang: 'python',
    kind: 'function',
    official: 'Range of values (maximum - minimum) along an axis.',
    source: 'NumPy docstring',
    when: 'You want the spread of values from lowest to highest in one call, such as how much energy drifted in a simulation. In NumPy 2 the method form arr.ptp() is gone; np.ptp(arr) still works.',
    example: { command: 'print(np.ptp([3.0, 9.0, 1.0]))', says: 'Prints 8.0, the gap between the largest (9) and smallest (1).' },
    seeAlso: ['numpy.max'],
  },
  {
    name: 'numpy.r_',
    aliases: ['np.r_'],
    lang: 'python',
    kind: 'constant',
    official: 'Translates slice objects to concatenation along the first axis.',
    source: 'NumPy docstring',
    when: 'A quick way to glue arrays end to end with square brackets, such as position and velocity into one state vector. It uses brackets, not parentheses: np.r_[r0, v0].',
    example: { command: 'state = np.r_[r0, v0]', says: 'Joins the 3 position values and 3 velocity values into one array of 6.' },
    seeAlso: ['numpy.concatenate', 'numpy.hstack', 'numpy.mgrid'],
  },
  {
    name: 'numpy.rad2deg',
    aliases: ['np.rad2deg'],
    lang: 'python',
    kind: 'function',
    official: 'Convert angles from radians to degrees.',
    source: 'NumPy docstring',
    when: 'You computed an angle in radians and want to show it in degrees. It does exactly the same as np.degrees.',
    example: { command: 'print(np.rad2deg(np.pi / 2))', says: 'Prints 90.0.' },
    seeAlso: ['numpy.degrees', 'numpy.deg2rad', 'numpy.radians'],
  },
  {
    name: 'numpy.radians',
    aliases: ['np.radians'],
    lang: 'python',
    kind: 'function',
    official: 'Convert angles from degrees to radians.',
    source: 'NumPy docstring',
    when: 'You have angles in degrees and are about to hand them to np.sin, np.cos or np.tan, which all expect radians. Forgetting it gives answers that look reasonable but are wrong.',
    example: { command: 'print(np.sin(np.radians(30.0)))', says: 'Prints 0.49999999999999994, the sine of 30 degrees, a hair off 0.5 because of rounding.' },
    seeAlso: ['numpy.degrees', 'numpy.deg2rad', 'numpy.rad2deg'],
  },
  {
    name: 'numpy.random',
    aliases: ['np.random'],
    lang: 'python',
    kind: 'module',
    official: 'Random Number Generation',
    source: 'NumPy docstring',
    when: 'Where NumPy keeps its random number tools. Make one generator with np.random.default_rng(seed) and draw from it; the older functions called straight on np.random share one hidden global state that any library can disturb.',
    example: { command: 'rng = np.random.default_rng(42)', says: 'Makes a random number generator from seed 42, so the run repeats exactly next time.' },
    seeAlso: ['numpy.random.default_rng', 'numpy.random.SeedSequence', 'random'],
  },
  {
    name: 'numpy.random.SeedSequence',
    aliases: ['np.random.SeedSequence'],
    lang: 'python',
    kind: 'class',
    official: 'SeedSequence mixes sources of entropy in a reproducible way to set the initial state for independent and very probably non-overlapping BitGenerators.',
    source: 'NumPy docstring',
    when: 'You run many Monte Carlo cases, maybe in parallel, and each needs its own random stream that does not overlap the others yet repeats exactly. Do not just use seed, seed+1, seed+2; spawn children from one SeedSequence instead.',
    flags: [
      ['entropy', 'the starting seed: a number, or a list like [campaign_seed, case_index]'],
      ['.spawn(n)', 'make n independent child seeds'],
    ],
    example: { command: 'seeds = np.random.SeedSequence(2024).spawn(400)', says: 'Makes 400 child seeds, one per case, each able to start its own generator.' },
    seeAlso: ['numpy.random.default_rng'],
  },
  {
    name: 'numpy.random.default_rng',
    aliases: ['np.random.default_rng'],
    lang: 'python',
    kind: 'function',
    official: 'Construct a new Generator with the default BitGenerator (PCG64).',
    source: 'NumPy docstring',
    when: 'Any time you need random numbers: make one generator at the start with a seed and draw everything from it, so the run can be repeated exactly. Without a seed you get different numbers every run.',
    flags: [
      ['seed', 'a starting number (or a SeedSequence) that fixes the whole stream'],
    ],
    example: { command: 'rng = np.random.default_rng(0)\nnoise = rng.normal(0.0, 0.2, size=100)', says: 'Makes a seeded generator, then draws 100 noise values from a bell curve with mean 0 and spread 0.2.' },
    seeAlso: ['numpy.random.SeedSequence', 'numpy.random.normal'],
  },
  {
    name: 'numpy.random.normal',
    aliases: ['np.random.normal'],
    lang: 'python',
    kind: 'function',
    official: 'Draw random samples from a normal (Gaussian) distribution.',
    source: 'NumPy docstring',
    when: 'You see it in older code that draws bell-curve random numbers. It uses NumPy\'s hidden global generator, so an extra draw anywhere in the program changes every later number; prefer rng.normal from a generator made with default_rng.',
    flags: [
      ['loc, scale', 'the mean and the spread (standard deviation), 0 and 1 by default'],
      ['size', 'how many numbers to draw, or the shape of the array'],
    ],
    example: { command: 'x = np.random.normal(size=3)', says: 'Draws three bell-curve numbers from the global generator, different each run unless it was seeded.' },
    seeAlso: ['numpy.random.default_rng', 'numpy.random.seed'],
  },
  {
    name: 'numpy.random.random',
    aliases: ['np.random.random'],
    lang: 'python',
    kind: 'function',
    official: 'Return random floats in the half-open interval [0.0, 1.0).',
    source: 'NumPy docstring',
    when: 'You see it in older code that wants random numbers from 0 up to (but never exactly) 1. It draws from the hidden global generator, so one extra call anywhere shifts every number after it.',
    flags: [
      ['size', 'how many numbers, or the shape of the array (one number if left out)'],
    ],
    example: { command: 'np.random.random()', says: 'Gives one random float such as 0.548, somewhere from 0 up to but not including 1.' },
    seeAlso: ['numpy.random.default_rng', 'numpy.random.seed'],
  },
  {
    name: 'numpy.random.seed',
    aliases: ['np.random.seed'],
    lang: 'python',
    kind: 'function',
    official: 'Reseed the singleton RandomState instance.',
    source: 'NumPy docstring',
    when: 'Older code calls it to make the global random functions repeat. Any library that also draws from the global generator will still change your numbers, which is why the lessons use np.random.default_rng(seed) instead.',
    example: { command: 'np.random.seed(42)', says: 'Resets the global generator, so np.random.normal and friends give the same sequence as last time.' },
    seeAlso: ['numpy.random.default_rng', 'numpy.random.normal'],
  },
  {
    name: 'numpy.real',
    aliases: ['np.real'],
    lang: 'python',
    kind: 'function',
    official: 'Return the real part of the complex argument.',
    source: 'NumPy docstring',
    when: 'A calculation gave complex numbers whose imaginary parts should be zero, or you only want the real parts. Check that the imaginary parts really are tiny before throwing them away.',
    example: { command: 'print(np.real([1 + 2j, 3 - 1j]))', says: 'Prints [1. 3.].' },
    seeAlso: ['numpy.angle', 'numpy.abs'],
  },
  {
    name: 'numpy.roll',
    aliases: ['np.roll'],
    lang: 'python',
    kind: 'function',
    official: 'Roll array elements along a given axis.',
    source: 'NumPy docstring',
    when: 'You want to shift every item along by some places, with the ones falling off the end wrapping round to the front, as in a GNSS code shift register or reordering a quaternion from [x, y, z, w] to [w, x, y, z].',
    flags: [
      ['shift', 'how many places to move (negative moves left)'],
      ['axis', 'which axis to roll along (the whole flattened array if left out)'],
    ],
    example: { command: 'print(np.roll([1, 2, 3, 4], 1))', says: 'Prints [4 1 2 3]: everything moves right one place and the last item wraps to the front.' },
    seeAlso: ['numpy.concatenate'],
  },
  {
    name: 'numpy.roots',
    aliases: ['np.roots'],
    lang: 'python',
    kind: 'function',
    official: 'Return the roots of a polynomial with coefficients given in p.',
    source: 'NumPy docstring',
    when: 'You want the roots of a polynomial, such as a system\'s poles from its denominator. Coefficients go highest power first, and the roots are not promised to come back in the same order each call.',
    example: { command: 'print(np.roots([1.0, 4.0, 3.0]))', says: 'Prints [-3. -1.], the roots of s^2 + 4s + 3.' },
    seeAlso: ['numpy.poly', 'numpy.polyval', 'numpy.sort_complex'],
  },
  {
    name: 'numpy.round',
    aliases: ['np.round'],
    lang: 'python',
    kind: 'function',
    official: 'Evenly round to the given number of decimals.',
    source: 'NumPy docstring',
    when: 'You want tidier numbers to print or compare. Halfway values round to the nearest even number, so np.round(2.5) is 2.0 and np.round(3.5) is 4.0.',
    flags: [
      ['decimals', 'how many digits after the point to keep (0 if left out)'],
    ],
    example: { command: 'print(np.round(9.80665, 2))', says: 'Prints 9.81.' },
    seeAlso: ['round', 'numpy.set_printoptions', 'numpy.floor'],
  },
  {
    name: 'numpy.save',
    aliases: ['np.save'],
    lang: 'python',
    kind: 'function',
    official: 'Save an array to a binary file in NumPy ``.npy`` format.',
    source: 'NumPy docstring',
    when: 'You want to store one array on disk exactly, with its shape and dtype, and load it back later with np.load. It is smaller and much faster than text; .npy is added to the name if it is missing.',
    flags: [
      ['file', 'the path to write'],
      ['arr', 'the array to save'],
    ],
    example: { command: 'np.save("gyro.npy", gyro)', says: 'Writes the gyro array to gyro.npy, header with shape and dtype included.' },
    seeAlso: ['numpy.load', 'numpy.savetxt'],
  },
  {
    name: 'numpy.savetxt',
    aliases: ['np.savetxt'],
    lang: 'python',
    kind: 'function',
    official: 'Save an array to a text file.',
    source: 'NumPy docstring',
    when: 'You want an array in a file people can read, such as a CSV of golden reference values for a test. Use fmt="%.17g" so every float is written in full and nothing is lost to rounding.',
    flags: [
      ['fmt', 'how to write each number, such as "%.17g" for full precision'],
      ['delimiter=","', 'what goes between columns'],
      ['header', 'a first line of notes, written after a #'],
    ],
    example: { command: 'np.savetxt("alt.csv", np.column_stack([t, alt]), delimiter=",", header="t,alt")', says: 'Writes the times and altitudes to alt.csv as two columns, with the line # t,alt at the top.' },
    seeAlso: ['numpy.loadtxt', 'numpy.save'],
  },
  {
    name: 'numpy.searchsorted',
    aliases: ['np.searchsorted'],
    lang: 'python',
    kind: 'function',
    official: 'Find indices where elements should be inserted to maintain order.',
    source: 'NumPy docstring',
    when: 'You have a sorted array, like sample times, and want to know where some values would slot in, for example to find the last sample before a given time. The array must already be sorted, or the answers are nonsense with no warning.',
    flags: [
      ['a', 'the sorted array'],
      ['v', 'the values to look up'],
      ['side="right"', 'on a tie, give the position after the equal item instead of before it'],
    ],
    example: { command: 'print(np.searchsorted([2.0, 4.0, 6.0], [1.0, 4.0, 5.0, 7.0]))', says: 'Prints [0 1 2 3]: where each value would go to keep the list in order.' },
    seeAlso: ['numpy.sort', 'numpy.interp'],
  },
  {
    name: 'numpy.set_printoptions',
    aliases: ['np.set_printoptions'],
    lang: 'python',
    kind: 'function',
    official: 'Set printing options.',
    source: 'NumPy docstring',
    when: 'Printed arrays are hard to read, full of long decimals or e-notation. This changes how every array prints from then on; it changes only the display, never the values.',
    flags: [
      ['precision', 'how many digits to show after the point'],
      ['suppress=True', 'show tiny numbers as plain decimals instead of e-notation'],
    ],
    example: { command: 'np.set_printoptions(precision=4, suppress=True)', says: 'Makes arrays print with 4 decimals and no scientific notation.' },
    seeAlso: ['numpy.round', 'numpy.array2string'],
  },
  {
    name: 'numpy.shares_memory',
    aliases: ['np.shares_memory'],
    lang: 'python',
    kind: 'function',
    official: 'Determine if two arrays share memory.',
    source: 'NumPy docstring',
    when: 'You want to know for sure whether an array is a view (a window onto another array\'s data) or a separate copy, before you change it. It can be slow for big, oddly strided arrays.',
    example: { command: 'print(np.shares_memory(t, t[::2]))', says: 'Prints True: the slice is a view, so writing to it changes t too.' },
    seeAlso: ['numpy.ndarray'],
  },
  {
    name: 'numpy.sign',
    aliases: ['np.sign'],
    lang: 'python',
    kind: 'function',
    official: 'Returns an element-wise indication of the sign of a number.',
    source: 'NumPy docstring',
    when: 'You want -1 for negative values, 1 for positive and 0 for zero, often to spot where a signal crosses zero with np.diff(np.sign(x)). Exactly zero gives 0, which can hide a crossing that lands right on it.',
    example: { command: 'print(np.sign([-3.0, 0.0, 2.5]))', says: 'Prints [-1. 0. 1.].' },
    seeAlso: ['numpy.diff', 'numpy.abs'],
  },
  {
    name: 'numpy.sin',
    aliases: ['np.sin'],
    lang: 'python',
    kind: 'function',
    official: 'Trigonometric sine, element-wise.',
    source: 'NumPy docstring',
    when: 'You need the sine of an angle, or of a whole array of angles at once. The angle must be in radians; convert degrees with np.radians first.',
    example: { command: 'mode = np.sin(2 * np.pi * 47.0 * t)', says: 'Makes a 47 Hz wave, one value for each time in t.' },
    seeAlso: ['numpy.cos', 'numpy.tan', 'numpy.radians'],
  },
  {
    name: 'numpy.sinh',
    aliases: ['np.sinh'],
    lang: 'python',
    kind: 'function',
    official: 'Hyperbolic sine, element-wise.',
    source: 'NumPy docstring',
    when: 'Hyperbolic functions show up in orbit formulas for hyperbolic paths, where sin and cos become sinh and cosh. It grows very fast, so large inputs overflow to inf.',
    example: { command: 'print(np.sinh(1.0))', says: 'Prints 1.1752011936438014.' },
    seeAlso: ['numpy.cosh', 'numpy.tanh', 'numpy.sin'],
  },
  {
    name: 'numpy.sort',
    aliases: ['np.sort'],
    lang: 'python',
    kind: 'function',
    official: 'Return a sorted copy of an array.',
    source: 'NumPy docstring',
    when: 'You want the values in order, smallest first. It hands back a new sorted array and leaves the original alone, unlike a.sort(), which sorts in place and returns None.',
    flags: [
      ['axis', 'which axis to sort along (the last one if left out)'],
    ],
    example: { command: 'print(np.sort([3, 1, 2]))', says: 'Prints [1 2 3].' },
    seeAlso: ['numpy.argsort', 'numpy.sort_complex', 'sorted'],
  },
  {
    name: 'numpy.sort_complex',
    aliases: ['np.sort_complex'],
    lang: 'python',
    kind: 'function',
    official: 'Sort a complex array using the real part first, then the imaginary part.',
    source: 'NumPy docstring',
    when: 'You want eigenvalues or poles in a fixed order so two lists can be compared. It always returns complex numbers, even if every imaginary part is zero.',
    example: { command: 'print(np.sort_complex(np.linalg.eigvals(A - B @ K)))', says: 'Prints the closed-loop eigenvalues sorted by real part, then imaginary part.' },
    seeAlso: ['numpy.sort', 'numpy.linalg.eigvals', 'numpy.roots'],
  },
  {
    name: 'numpy.spacing',
    aliases: ['np.spacing'],
    lang: 'python',
    kind: 'function',
    official: 'Return the distance between x and the nearest adjacent number.',
    source: 'NumPy docstring',
    when: 'You want to know how finely floats can tell values apart near some number: the gap to the next float, called one ulp. The gap grows with the size of the number, so large values are stored more coarsely.',
    example: { command: 'print(np.spacing(6.4e6))', says: 'Prints 9.313225746154785e-10: near Earth\'s radius in meters, float64 steps are about a billionth of a meter.' },
    seeAlso: ['numpy.finfo'],
  },
  {
    name: 'numpy.sqrt',
    aliases: ['np.sqrt'],
    lang: 'python',
    kind: 'function',
    official: 'Return the non-negative square-root of an array, element-wise.',
    source: 'NumPy docstring',
    when: 'You need a square root, of one number or a whole array, such as a speed from its components or an RMS error. A negative input gives nan with only a warning; to get complex answers, pass complex numbers.',
    example: { command: 'v0 = np.sqrt(MU / r0)', says: 'Works out the circular orbit speed at radius r0.' },
    seeAlso: ['numpy.square', 'numpy.hypot', 'numpy.linalg.norm'],
  },
  {
    name: 'numpy.square',
    aliases: ['np.square'],
    lang: 'python',
    kind: 'function',
    official: 'Return the element-wise square of the input.',
    source: 'NumPy docstring',
    when: 'You want every value squared, as in a sum of squares or a root-mean-square error. The same as x**2.',
    example: { command: 'rms = np.sqrt(np.mean(np.square(err)))', says: 'Works out the RMS error: square each error, average them, take the square root.' },
    seeAlso: ['numpy.sqrt', 'numpy.mean'],
  },
  {
    name: 'numpy.stack',
    aliases: ['np.stack'],
    lang: 'python',
    kind: 'function',
    official: 'Join a sequence of arrays along a new axis.',
    source: 'NumPy docstring',
    when: 'You have several arrays of exactly the same shape, like x, y and z, and want them side by side in one bigger array. It adds a new axis; to join along an axis that already exists, use np.concatenate.',
    flags: [
      ['arrays', 'a list of arrays, all the same shape'],
      ['axis', 'where the new axis goes; axis=-1 or axis=1 puts x, y, z as columns'],
    ],
    example: { command: 'r = np.stack([x, y, z], axis=1)', says: 'Turns three arrays of N values into one N by 3 array, one row per point.' },
    seeAlso: ['numpy.concatenate', 'numpy.vstack', 'numpy.column_stack'],
  },
  {
    name: 'numpy.std',
    aliases: ['np.std'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the standard deviation along the specified axis.',
    source: 'NumPy docstring',
    when: 'You want to know how spread out your values are around their mean. It divides by N by default; pandas and Python\'s statistics module divide by N - 1, so pass ddof=1 to match them.',
    flags: [
      ['axis', 'which direction to work along'],
      ['ddof=1', 'divide by N - 1, the sample standard deviation'],
    ],
    example: { command: 'sigma = np.std(miss_m)', says: 'Gives the spread of the miss distances, in meters.' },
    seeAlso: ['numpy.var', 'numpy.mean', 'numpy.nanstd'],
  },
  {
    name: 'numpy.sum',
    aliases: ['np.sum'],
    lang: 'python',
    kind: 'function',
    official: 'Sum of array elements over a given axis.',
    source: 'NumPy docstring',
    when: 'You want the total of an array, or one total per row or column. It adds in pairs, so it is more accurate than a running total in a loop; one nan makes the result nan.',
    flags: [
      ['axis', 'which direction to add along; that axis disappears from the result'],
      ['keepdims=True', 'keep that axis as length 1 so the result still lines up with the original'],
    ],
    example: { command: 'print(np.sum([[1, 2], [3, 4]], axis=0))', says: 'Prints [4 6], the total of each column.' },
    seeAlso: ['sum', 'numpy.mean', 'numpy.cumsum'],
  },
  {
    name: 'numpy.tan',
    aliases: ['np.tan'],
    lang: 'python',
    kind: 'function',
    official: 'Compute tangent element-wise.',
    source: 'NumPy docstring',
    when: 'You need the tangent of an angle, such as the width a sensor beam covers at a given height. Input is in radians, and near 90 degrees the answer shoots up toward huge numbers.',
    example: { command: 'r = h * np.tan(np.radians(10.0))', says: 'Works out the radius of the spot a 10 degree beam lights up from height h.' },
    seeAlso: ['numpy.sin', 'numpy.arctan2', 'numpy.radians'],
  },
  {
    name: 'numpy.tanh',
    aliases: ['np.tanh'],
    lang: 'python',
    kind: 'function',
    official: 'Compute hyperbolic tangent element-wise.',
    source: 'NumPy docstring',
    when: 'Hyperbolic tangent turns up in physics formulas such as fuel slosh; it rises smoothly from -1 to 1 and levels off. Big inputs give exactly 1.0 or -1.0.',
    example: { command: 'print(np.tanh(3.0))', says: 'Prints 0.9950547536867305, already close to 1.' },
    seeAlso: ['numpy.sinh', 'numpy.cosh'],
  },
  {
    name: 'numpy.testing',
    aliases: ['np.testing'],
    lang: 'python',
    kind: 'module',
    official: 'Common test support for all numpy test scripts.',
    source: 'NumPy docstring',
    when: 'You write tests that check arrays. It holds assert_allclose for floats that only need to be close and assert_array_equal for values that must match exactly.',
    example: { command: 'from numpy.testing import assert_allclose', says: 'Loads the closeness checker so tests can call assert_allclose directly.' },
    seeAlso: ['numpy.testing.assert_allclose', 'numpy.testing.assert_array_equal', 'pytest.approx'],
  },
  {
    name: 'numpy.testing.assert_allclose',
    aliases: ['np.testing.assert_allclose', 'assert_allclose'],
    lang: 'python',
    kind: 'function',
    official: 'Raises an AssertionError if two objects are not equal up to desired tolerance.',
    source: 'NumPy docstring',
    when: 'A test compares computed float arrays with expected ones, which almost never match bit for bit. The default rtol is 1e-7 and atol is 0, so values that should be zero need an atol or the test fails.',
    flags: [
      ['actual, desired', 'what your code gave and what it should give'],
      ['rtol', 'allowed gap relative to the desired value'],
      ['atol', 'allowed gap in absolute terms, needed near zero'],
    ],
    example: { command: 'np.testing.assert_allclose(quat_to_dcm(q), quat_to_dcm(-q), atol=1e-15)', says: 'Passes silently if the two matrices agree to within 1e-15, and fails the test showing the worst mismatch if not.' },
    seeAlso: ['numpy.testing.assert_array_equal', 'numpy.allclose', 'pytest.approx'],
  },
  {
    name: 'numpy.testing.assert_array_equal',
    aliases: ['np.testing.assert_array_equal', 'assert_array_equal'],
    lang: 'python',
    kind: 'function',
    official: 'Raises an AssertionError if two array_like objects are not equal.',
    source: 'NumPy docstring',
    when: 'A test checks values that are exact by nature: integer indices, booleans, shapes. Do not use it for computed floats; tiny rounding differences between computers will make it fail.',
    flags: [
      ['actual, desired', 'what your code gave and what it should give'],
    ],
    example: { command: 'assert_array_equal(np.argsort(mag)[:3], [4, 0, 7])', says: 'Passes only if the three brightest-star indices match exactly, in order.' },
    seeAlso: ['numpy.testing.assert_allclose', 'numpy.array_equal'],
  },
  {
    name: 'numpy.trace',
    aliases: ['np.trace'],
    lang: 'python',
    kind: 'function',
    official: 'Return the sum along diagonals of the array.',
    source: 'NumPy docstring',
    when: 'You want the sum of a matrix\'s diagonal, as in GDOP from a covariance matrix or recovering a quaternion from a rotation matrix. It equals the sum of the eigenvalues.',
    example: { command: 'gdop = np.sqrt(np.trace(Q))', says: 'Adds up the diagonal of the covariance Q and takes the square root to get GDOP.' },
    seeAlso: ['numpy.diag', 'numpy.linalg.eigvals'],
  },
  {
    name: 'numpy.trapezoid',
    aliases: ['np.trapezoid'],
    lang: 'python',
    kind: 'function',
    official: 'Integrate along the given axis using the composite trapezoidal rule.',
    source: 'NumPy docstring',
    when: 'You have samples of a curve and want the area under it. Pass the x values too, or it assumes a spacing of 1. In NumPy 2 this replaced the old name np.trapz.',
    flags: [
      ['y', 'the sampled values'],
      ['x', 'where the samples were taken'],
    ],
    example: { command: 'v = np.trapezoid(accel, t)', says: 'Adds up acceleration over time to get the change in velocity.' },
    seeAlso: ['numpy.cumsum', 'numpy.linspace'],
  },
  {
    name: 'numpy.triu_indices',
    aliases: ['np.triu_indices'],
    lang: 'python',
    kind: 'function',
    official: 'Return the indices for the upper-triangle of an (n, m) array.',
    source: 'NumPy docstring',
    when: 'You want every pair (i, j) with i < j just once, such as each pair of stars in a catalog, without writing a double loop. The second argument 1 skips the diagonal, so no item is paired with itself.',
    flags: [
      ['n', 'the size of the square array'],
      ['k', 'which diagonal to start from; 1 leaves the main diagonal out'],
    ],
    example: { command: 'i, j = np.triu_indices(3, 1)', says: 'Gives i = [0 0 1] and j = [1 2 2]: the pairs (0,1), (0,2) and (1,2).' },
    seeAlso: ['numpy.meshgrid'],
  },
  {
    name: 'numpy.typing',
    aliases: ['np.typing', 'npt'],
    lang: 'python',
    kind: 'module',
    official: 'Large parts of the NumPy API have :pep:`484`-style type annotations.',
    source: 'NumPy docstring',
    when: 'You add type hints to code that handles arrays. Import it as npt and write npt.NDArray[np.float64] to say "an array of float64". Python does not check hints when it runs; a tool like mypy does.',
    example: { command: 'import numpy.typing as npt', says: 'Loads NumPy\'s typing helpers under the short name npt.' },
    seeAlso: ['numpy.typing.NDArray', 'typing'],
  },
  {
    name: 'numpy.typing.NDArray',
    aliases: ['np.typing.NDArray', 'npt.NDArray'],
    lang: 'python',
    kind: 'type',
    official: 'Can be used during runtime for typing arrays with a given dtype and unspecified shape.',
    source: 'NumPy docstring',
    when: 'You want a type hint that says both "this is a NumPy array" and what dtype it holds. It says nothing about the shape, and Python itself never checks it while running.',
    example: { command: 'def mean_accel(a: npt.NDArray[np.float64]) -> float:', says: 'Labels the function as taking an array of float64 values and returning a float.' },
    seeAlso: ['numpy.typing', 'numpy.ndarray'],
  },
  {
    name: 'numpy.unique',
    aliases: ['np.unique'],
    lang: 'python',
    kind: 'function',
    official: 'Find the unique elements of an array.',
    source: 'NumPy docstring',
    when: 'You want each distinct value once, for example to count how many different particles are left after resampling. The result comes back sorted, not in the original order.',
    example: { command: 'print(np.unique([3, 1, 3, 2, 1]))', says: 'Prints [1 2 3].' },
    seeAlso: ['numpy.sort', 'set'],
  },
  {
    name: 'numpy.unravel_index',
    aliases: ['np.unravel_index'],
    lang: 'python',
    kind: 'function',
    official: 'Converts a flat index or array of flat indices into a tuple of coordinate arrays.',
    source: 'NumPy docstring',
    when: 'np.argmax on a 2-D array gives one count as if the array were a single long line; this turns that count back into a row and a column.',
    flags: [
      ['indices', 'the flat position, such as the result of np.argmax'],
      ['shape', 'the array\'s shape'],
    ],
    example: { command: 'row, col = np.unravel_index(np.argmax(img), img.shape)', says: 'Finds the row and column of the brightest pixel.' },
    seeAlso: ['numpy.argmax', 'numpy.argmin'],
  },
  {
    name: 'numpy.unwrap',
    aliases: ['np.unwrap'],
    lang: 'python',
    kind: 'function',
    official: 'Unwrap by taking the complement of large deltas with respect to the period.',
    source: 'NumPy docstring',
    when: 'An angle you recorded jumps from +179 to -179 degrees because angles wrap around, and you want a smooth curve instead, such as the phase on a Bode plot. It works in radians, so convert before and after.',
    example: { command: 'phase_deg = np.degrees(np.unwrap(np.angle(g)))', says: 'Turns the gain\'s wrapped phase into a smooth curve in degrees with no 360 degree jumps.' },
    seeAlso: ['numpy.angle', 'numpy.degrees'],
  },
  {
    name: 'numpy.vander',
    aliases: ['np.vander'],
    lang: 'python',
    kind: 'function',
    official: 'Generate a Vandermonde matrix.',
    source: 'NumPy docstring',
    when: 'You fit a polynomial by least squares and need the matrix whose columns are 1, t, t^2 and so on. By default the powers run highest first; increasing=True flips them. High degrees make the matrix badly conditioned.',
    flags: [
      ['x', 'the sample points'],
      ['N', 'how many columns'],
      ['increasing=True', 'put the columns in the order 1, t, t^2, ...'],
    ],
    example: { command: 'A = np.vander(t, 3, increasing=True)', says: 'Builds a matrix with the columns 1, t and t^2, ready for a quadratic fit.' },
    seeAlso: ['numpy.polyfit', 'numpy.linalg.lstsq'],
  },
  {
    name: 'numpy.var',
    aliases: ['np.var'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the variance along the specified axis.',
    source: 'NumPy docstring',
    when: 'You want the variance of your data, the standard deviation squared. It divides by N by default; pass ddof=1 for the sample variance.',
    flags: [
      ['axis', 'which direction to work along'],
      ['ddof=1', 'divide by N - 1, the sample variance'],
    ],
    example: { command: 'print(np.var([1.0, 2.0, 3.0, 4.0]), np.var([1.0, 2.0, 3.0, 4.0], ddof=1))', says: 'Prints 1.25 1.6666666666666667: dividing by N, then by N - 1.' },
    seeAlso: ['numpy.std', 'numpy.mean'],
  },
  {
    name: 'numpy.vstack',
    aliases: ['np.vstack'],
    lang: 'python',
    kind: 'function',
    official: 'Stack arrays in sequence vertically (row wise).',
    source: 'NumPy docstring',
    when: 'You want arrays piled on top of each other as rows. 1-D arrays become rows, so three arrays of length 4 give a 3 by 4 array.',
    example: { command: 'R = np.vstack([east, north, up])', says: 'Builds a 3 by 3 matrix with the east, north and up directions as its rows.' },
    seeAlso: ['numpy.stack', 'numpy.hstack', 'numpy.column_stack'],
  },
  {
    name: 'numpy.where',
    aliases: ['np.where'],
    lang: 'python',
    kind: 'function',
    official: 'Return elements chosen from `x` or `y` depending on `condition`.',
    source: 'NumPy docstring',
    when: 'You want to choose between two values item by item from a condition, like an if/else over a whole array. Both choices are worked out for every item before picking, so a division by zero in the branch you do not want still warns.',
    flags: [
      ['condition', 'a True/False array'],
      ['x, y', 'the value to use where it is True, and where it is False'],
      ['condition alone', 'with no x and y, gives the positions of the Trues, like np.nonzero'],
    ],
    example: { command: 'print(np.where(alt > 100e3, "space", "air"))', says: 'Prints space for every altitude above 100 km and air for the rest.' },
    seeAlso: ['numpy.nonzero', 'numpy.maximum', 'numpy.clip'],
  },
  {
    name: 'numpy.zeros',
    aliases: ['np.zeros'],
    lang: 'python',
    kind: 'function',
    official: 'Return a new array of given shape and type, filled with zeros.',
    source: 'NumPy docstring',
    when: 'You need an array to fill in later, like a table of results or a starting state. The default type is float64; pass dtype for something else.',
    flags: [
      ['shape', 'one number, or a tuple like (3, 3)'],
      ['dtype', 'the type of each item, such as np.int64'],
    ],
    example: { command: 'I_cg = np.zeros((3, 3))', says: 'Makes a 3 by 3 array of 0.0, ready to add inertia terms into.' },
    seeAlso: ['numpy.ones', 'numpy.zeros_like', 'numpy.empty'],
  },
  {
    name: 'numpy.zeros_like',
    aliases: ['np.zeros_like'],
    lang: 'python',
    kind: 'function',
    official: 'Return an array of zeros with the same shape and type as a given array.',
    source: 'NumPy docstring',
    when: 'You want a zero array that matches another array\'s shape, such as one height per Monte Carlo case. It copies the type too: zeros_like an integer array is integers, so storing 0.5 in it quietly gives 0.',
    example: { command: 'h = np.zeros_like(v0)', says: 'Makes an array of zeros with the same shape and dtype as v0, one slot per case.' },
    seeAlso: ['numpy.zeros', 'numpy.ones_like', 'numpy.empty_like'],
  },
]
