import type { CommandRef } from './types'

export const COMMANDS: CommandRef[] = [
  {
    name: 'numpy',
    aliases: ['np'],
    lang: 'python',
    kind: 'module',
    official: 'Provides 1. An array object of arbitrary homogeneous items 2. Fast mathematical operations over arrays 3. Linear Algebra, Fourier Transforms, Random Number Generation',
    source: 'NumPy docstring',
    when: 'You want to work with many numbers at once: a whole flight log, a matrix, a set of vectors. Lessons always import it as np, so every NumPy name you see starts with np. Arrays hold one type of value each, so a mix of text and numbers is not what they are for.',
    example: { command: 'import numpy as np', says: 'Loads NumPy and lets you call it np, so np.array, np.sqrt and the rest are ready to use.' },
    seeAlso: ['numpy.array', 'numpy.linalg'],
  },
  {
    name: 'numpy.__version__',
    aliases: ['np.__version__'],
    lang: 'python',
    kind: 'constant',
    official: 'Module to expose more detailed version info for the installed `numpy`',
    source: 'NumPy docstring (numpy.version)',
    when: 'You need to know which NumPy version a program is really using, for example when two environments give different answers. It is a plain string like "2.4.6", not a function, so there are no parentheses.',
    example: { command: 'python -c "import numpy; print(numpy.__version__)"', says: 'Prints the installed NumPy version, such as 2.4.6.' },
    seeAlso: ['numpy'],
  },
  {
    name: 'numpy.abs',
    aliases: ['np.abs'],
    lang: 'python',
    kind: 'function',
    official: 'Calculate the absolute value element-wise.',
    source: 'NumPy docstring',
    when: 'You want the size of each value with its sign dropped, such as how far each reading is from its target. It works on a whole array at once. For complex numbers it gives the length (magnitude), not the real part.',
    example: { command: 'miss = np.abs(np.array([-3.0, 2.5, -0.5]))', says: 'Gives [3. 2.5 0.5]: every miss distance, all positive.' },
    seeAlso: ['abs', 'numpy.hypot'],
  },
  {
    name: 'numpy.all',
    aliases: ['np.all'],
    lang: 'python',
    kind: 'function',
    official: 'Test whether all array elements along a given axis evaluate to True.',
    source: 'NumPy docstring',
    when: 'You want to check that a condition holds for every element, such as "every time step is positive". It returns a single True or False. An empty array counts as True, because nothing broke the rule.',
    example: { command: 'np.all(np.diff(t) > 0)', says: 'True if the timestamps only ever go up, with no repeats and no steps backward.' },
    seeAlso: ['all', 'numpy.isfinite', 'numpy.diff'],
  },
  {
    name: 'numpy.allclose',
    aliases: ['np.allclose'],
    lang: 'python',
    kind: 'function',
    official: 'Returns True if two arrays are element-wise equal within a tolerance.',
    source: 'NumPy docstring',
    when: 'You want to compare floating-point results, where tiny rounding errors make == say False. It says True if every pair is close enough. Set the tolerances on purpose; the defaults may be looser or tighter than your problem needs.',
    flags: [['rtol=', 'allowed difference as a fraction of the expected value'], ['atol=', 'allowed difference as a fixed amount, which matters near zero']],
    example: { command: 'print(np.allclose(Q.T @ Q, np.eye(3), atol=1e-12))', says: 'Prints True if Q is a proper rotation matrix, up to rounding.' },
    seeAlso: ['numpy.array_equal', 'numpy.testing.assert_allclose'],
  },
  {
    name: 'numpy.angle',
    aliases: ['np.angle'],
    lang: 'python',
    kind: 'function',
    official: 'Return the angle of the complex argument.',
    source: 'NumPy docstring',
    when: 'You have complex numbers, such as a frequency response, and you want the phase: the direction each one points. The answer is in radians, so wrap it in np.degrees to read it in degrees.',
    example: { command: 'print(np.degrees(np.angle(1 + 1j)))', says: 'Prints 45.0: the complex number 1 + 1j points halfway between the real and imaginary axes.' },
    seeAlso: ['numpy.abs', 'numpy.degrees', 'numpy.arctan2'],
  },
  {
    name: 'numpy.arange',
    aliases: ['np.arange'],
    lang: 'python',
    kind: 'function',
    official: 'Return evenly spaced values within a given interval.',
    source: 'NumPy docstring',
    when: 'You want evenly spaced numbers with a fixed step, such as sample times or indices. The stop value is left out, like range. With a fractional step, rounding can add or drop the last point, so use np.linspace when you need an exact count.',
    flags: [['start, stop, step', 'where to begin, where to stop (not included), and the gap'], ['dtype=', 'the type of number to make']],
    example: { command: 't = np.arange(0.0, 1.0, 0.25)', says: 'Gives [0. 0.25 0.5 0.75]: times from 0 up to, but not including, 1 second.' },
    seeAlso: ['range', 'numpy.linspace'],
  },
  {
    name: 'numpy.arccos',
    aliases: ['np.arccos'],
    lang: 'python',
    kind: 'function',
    official: 'Trigonometric inverse cosine, element-wise.',
    source: 'NumPy docstring',
    when: 'You know a cosine, such as the dot product of two unit vectors, and want the angle back. It answers in radians, from 0 to pi. An input even slightly past 1 from rounding gives nan (not a number) instead of an error, so clip it to [-1, 1] first.',
    example: { command: 'angle = np.degrees(np.arccos(np.clip(d, -1.0, 1.0)))', says: 'Turns the dot product d into the angle between two directions, in degrees, safe from rounding.' },
    seeAlso: ['numpy.cos', 'numpy.clip', 'numpy.arcsin'],
  },
  {
    name: 'numpy.arcsin',
    aliases: ['np.arcsin'],
    lang: 'python',
    kind: 'function',
    official: 'Inverse sine, element-wise.',
    source: 'NumPy docstring',
    when: 'You know a sine and want the angle back, such as a latitude from a height ratio. The answer is in radians, from -pi/2 to pi/2. Inputs past -1 or 1 give nan (not a number).',
    example: { command: 'lat = np.degrees(np.arcsin(r[2] / np.linalg.norm(r)))', says: 'Gives the latitude of position r, in degrees.' },
    seeAlso: ['numpy.arccos', 'numpy.arctan', 'numpy.sin'],
  },
  {
    name: 'numpy.arctan',
    aliases: ['np.arctan'],
    lang: 'python',
    kind: 'function',
    official: 'Trigonometric inverse tangent, element-wise.',
    source: 'NumPy docstring',
    when: 'You know a slope or a ratio and want its angle. It only returns angles from -90 to +90 degrees, so it cannot tell opposite directions apart; use np.arctan2 when you have both parts.',
    example: { command: 'slope_deg = np.degrees(np.arctan(0.1))', says: 'Gives about 5.71: the angle of a slope that rises 1 for every 10 across.' },
    seeAlso: ['numpy.arctan2', 'numpy.tan'],
  },
  {
    name: 'numpy.arctan2',
    aliases: ['np.arctan2'],
    lang: 'python',
    kind: 'function',
    official: 'Element-wise arc tangent of ``x1/x2`` choosing the quadrant correctly.',
    source: 'NumPy docstring',
    when: 'You have a y part and an x part, such as the two sides of a velocity, and want the direction they point, all the way round. Give y first, then x. It keeps the signs, so it lands in the right quarter, where plain arctan(y / x) can be off by 180 degrees.',
    flags: [['y, x', 'the vertical part first, then the horizontal part']],
    example: { command: 'print(np.degrees(np.arctan2(-1.0, -1.0)))', says: 'Prints -135.0: pointing down and to the left. arctan(-1 / -1) would wrongly say 45.' },
    seeAlso: ['numpy.arctan', 'numpy.hypot', 'numpy.degrees'],
  },
  {
    name: 'numpy.argmax',
    aliases: ['np.argmax'],
    lang: 'python',
    kind: 'function',
    official: 'Returns the indices of the maximum values along an axis.',
    source: 'NumPy docstring',
    when: 'You want where the largest value is, not the value itself, such as the time of peak pressure. It gives an index you can use in another array. If the largest value appears twice, you get the first one.',
    example: { command: 'i = np.argmax(alt)\nprint(t[i], alt[i])', says: 'Finds the index of the highest altitude, then prints the time and the altitude at that point.' },
    seeAlso: ['numpy.argmin', 'numpy.max', 'numpy.argsort'],
  },
  {
    name: 'numpy.argmin',
    aliases: ['np.argmin'],
    lang: 'python',
    kind: 'function',
    official: 'Returns the indices of the minimum values along an axis.',
    source: 'NumPy docstring',
    when: 'You want where the smallest value is, such as the sample closest to a target: np.argmin(np.abs(x - target)). It gives an index, not the value.',
    example: { command: 'k = np.argmin(np.abs(t - 60.0))', says: 'Finds the index of the sample whose time is closest to 60 seconds.' },
    seeAlso: ['numpy.argmax', 'numpy.abs'],
  },
  {
    name: 'numpy.argsort',
    aliases: ['np.argsort'],
    lang: 'python',
    kind: 'function',
    official: 'Returns the indices that would sort an array.',
    source: 'NumPy docstring',
    when: 'You want the order that would sort an array, so you can sort something else the same way, such as crew names by score. It returns positions, smallest value first; the array itself does not change. Sort the negated values for largest first.',
    example: { command: 'order = np.argsort(np.array([120.0, 185.0, 210.0, 190.0]))', says: 'Gives [0 1 3 2]: the positions of the altitudes from lowest to highest.' },
    seeAlso: ['numpy.sort', 'numpy.argmax', 'sorted'],
  },
  {
    name: 'numpy.array',
    aliases: ['np.array'],
    lang: 'python',
    kind: 'function',
    official: 'Create an array.',
    source: 'NumPy docstring',
    when: 'You want to turn a list, or a list of lists, into a NumPy array so math works on every element at once. It makes a copy. Give it floats (1.0, not 1) when you plan to store decimals, or an integer array will quietly cut them off.',
    flags: [['dtype=', 'the type of number to store, such as float or np.float32']],
    example: { command: 'F = np.array([[1.0, 0.1], [0.0, 1.0]])', says: 'Makes a 2-by-2 array of floats: one row per inner list.' },
    seeAlso: ['numpy.asarray', 'numpy.ndarray', 'numpy.zeros'],
  },
  {
    name: 'numpy.array2string',
    aliases: ['np.array2string'],
    lang: 'python',
    kind: 'function',
    official: 'Return a string representation of an array.',
    source: 'NumPy docstring',
    when: 'You want to print an array neatly, with a set number of digits, inside a longer message. It only changes how the numbers look, not their values.',
    flags: [['precision=', 'how many digits to show after the decimal point']],
    example: { command: 'print("eigenvalues:", np.array2string(w, precision=3))', says: 'Prints the eigenvalues rounded to 3 digits after the point, such as [1.235 2.5 ].' },
    seeAlso: ['numpy.set_printoptions', 'print'],
  },
  {
    name: 'numpy.array_equal',
    aliases: ['np.array_equal'],
    lang: 'python',
    kind: 'function',
    official: 'True if two arrays have the same shape and elements, False otherwise.',
    source: 'NumPy docstring',
    when: 'You want to know if two arrays are exactly the same: same shape and every value identical. Good for integers, saved-and-loaded data or repeated runs with the same seed. After float arithmetic, use np.allclose instead, because tiny rounding differences make this False.',
    example: { command: 'print(np.array_equal(back, gyro))', says: 'Prints True if the data read back from the file matches the original exactly.' },
    seeAlso: ['numpy.allclose', 'numpy.testing.assert_array_equal'],
  },
  {
    name: 'numpy.array_split',
    aliases: ['np.array_split'],
    lang: 'python',
    kind: 'function',
    official: 'Split an array into multiple sub-arrays.',
    source: 'NumPy docstring',
    when: 'You want to cut an array into a set number of pieces, such as one chunk per worker thread. Unlike np.split, it is fine when the length does not divide evenly; the first pieces get one extra element.',
    example: { command: 'chunks = np.array_split(np.arange(10), 3)', says: 'Gives three pieces: [0 1 2 3], [4 5 6] and [7 8 9].' },
    seeAlso: ['numpy.concatenate'],
  },
  {
    name: 'numpy.asarray',
    aliases: ['np.asarray'],
    lang: 'python',
    kind: 'function',
    official: 'Convert the input to an array.',
    source: 'NumPy docstring',
    when: 'Your function might be handed a list, a tuple or an array, and you want an array either way. Unlike np.array, it does not copy something that is already a suitable array, so changing the result can change the caller\'s data.',
    flags: [['dtype=', 'the type of number you need, such as float or complex']],
    example: { command: 's = np.asarray(s, dtype=float)', says: 'Makes sure s is a float array, whatever the caller passed in.' },
    seeAlso: ['numpy.array', 'numpy.atleast_1d'],
  },
  {
    name: 'numpy.atleast_1d',
    aliases: ['np.atleast_1d'],
    lang: 'python',
    kind: 'function',
    official: 'Convert inputs to arrays with at least one dimension.',
    source: 'NumPy docstring',
    when: 'Your code should accept either a single number or a list of them. It turns a plain number into a one-element array, and leaves arrays alone, so the same code works for both.',
    example: { command: 'y0 = np.atleast_1d(np.asarray(y0, dtype=float))', says: 'Turns 7.0 into [7.] and leaves a six-number state as it is.' },
    seeAlso: ['numpy.atleast_2d', 'numpy.asarray'],
  },
  {
    name: 'numpy.atleast_2d',
    aliases: ['np.atleast_2d'],
    lang: 'python',
    kind: 'function',
    official: 'View inputs as arrays with at least two dimensions.',
    source: 'NumPy docstring',
    when: 'Your code expects a table (rows and columns) but might be given a single row. A 1-D array of length n becomes one row, shape (1, n).',
    example: { command: 'S = np.atleast_2d([1.0, 2.0])', says: 'Gives an array of shape (1, 2): one row with two columns.' },
    seeAlso: ['numpy.atleast_1d'],
  },
  {
    name: 'numpy.block',
    aliases: ['np.block'],
    lang: 'python',
    kind: 'function',
    official: 'Assemble an nd-array from nested lists of blocks.',
    source: 'NumPy docstring',
    when: 'You want to build a big matrix out of smaller matrices, laid out the way you would draw it on paper. Each inner list is one row of blocks. The blocks in a row must have the same height, and each block row the same total width.',
    example: { command: 'M = np.block([[A, B], [np.zeros((1, 2)), np.eye(1)]])', says: 'Puts A and B side by side on top, and a row of zeros with a 1 underneath.' },
    seeAlso: ['numpy.hstack', 'numpy.vstack', 'numpy.concatenate'],
  },
  {
    name: 'numpy.ceil',
    aliases: ['np.ceil'],
    lang: 'python',
    kind: 'function',
    official: 'Return the ceiling of the input, element-wise.',
    source: 'NumPy docstring',
    when: 'You want to round up to the next whole number, such as the number of time steps needed to cover a burn. The result is still a float (3.0, not 3), so wrap it in int() when you need a count.',
    example: { command: 'steps = int(np.ceil(2.1))', says: 'Gives 3: 2.1 rounded up.' },
    seeAlso: ['numpy.floor', 'numpy.round'],
  },
  {
    name: 'numpy.clip',
    aliases: ['np.clip'],
    lang: 'python',
    kind: 'function',
    official: 'Clip (limit) the values in an array.',
    source: 'NumPy docstring',
    when: 'You want to keep values inside limits, such as a fin angle that cannot pass plus or minus 5 degrees. Anything below the low limit becomes the low limit, anything above becomes the high one. It returns a new array unless you tell it otherwise.',
    flags: [['a, a_min, a_max', 'the values, then the lowest and highest allowed']],
    example: { command: 'cmd = np.clip(np.array([-8.0, 3.0, 7.0]), -5, 5)', says: 'Gives [-5. 3. 5.]: the extreme commands are held at the limits.' },
    seeAlso: ['numpy.minimum', 'numpy.maximum'],
  },
  {
    name: 'numpy.column_stack',
    aliases: ['np.column_stack'],
    lang: 'python',
    kind: 'function',
    official: 'Stack 1-D arrays as columns into a 2-D array.',
    source: 'NumPy docstring',
    when: 'You have several 1-D arrays of the same length and want them as the columns of one table, such as time next to altitude. Each input becomes one column.',
    example: { command: 'H = np.column_stack([np.ones_like(t), t])', says: 'Makes a two-column matrix: a column of ones and a column of times, ready for a straight-line fit.' },
    seeAlso: ['numpy.hstack', 'numpy.vstack', 'numpy.stack'],
  },
  {
    name: 'numpy.concatenate',
    aliases: ['np.concatenate'],
    lang: 'python',
    kind: 'function',
    official: 'Join a sequence of arrays along an existing axis.',
    source: 'NumPy docstring',
    when: 'You want to join arrays end to end into one, such as velocity and acceleration into one state derivative. They must match in every direction except the one you join along. Pass them as one list or tuple, not as separate arguments.',
    flags: [['axis=', 'which direction to join along (0, down the rows, unless you say otherwise)']],
    example: { command: 'return np.concatenate([v, a])', says: 'Joins the 3-number velocity and the 3-number acceleration into one 6-number array.' },
    seeAlso: ['numpy.hstack', 'numpy.vstack', 'numpy.stack'],
  },
  {
    name: 'numpy.convolve',
    aliases: ['np.convolve'],
    lang: 'python',
    kind: 'function',
    official: 'Returns the discrete, linear convolution of two one-dimensional sequences.',
    source: 'NumPy docstring',
    when: 'You want to slide one sequence across another and add up the products, as when a system\'s impulse response meets an input, or to multiply two polynomials from their coefficients. The full result is longer than either input, so trim it when you need the original length.',
    example: { command: 'print(np.convolve([1, 1], [1, 2, 3]))', says: 'Prints [1 3 5 3], the coefficients of (x + 1)(x^2 + 2x + 3).' },
    seeAlso: ['numpy.polymul'],
  },
  {
    name: 'numpy.cos',
    aliases: ['np.cos'],
    lang: 'python',
    kind: 'function',
    official: 'Cosine element-wise.',
    source: 'NumPy docstring',
    when: 'You want the cosine of every angle in an array at once. Angles must be in radians; convert degrees first with np.deg2rad or np.radians.',
    example: { command: 'x = a * np.cos(nu)', says: 'Gives the x position for each angle nu around an orbit of radius a.' },
    seeAlso: ['numpy.sin', 'numpy.arccos', 'numpy.deg2rad'],
  },
  {
    name: 'numpy.cosh',
    aliases: ['np.cosh'],
    lang: 'python',
    kind: 'function',
    official: 'Hyperbolic cosine, element-wise.',
    source: 'NumPy docstring',
    when: 'You need the hyperbolic cosine, which turns up in formulas for hanging cables and in some orbit equations. Its values grow very fast, so big inputs overflow to inf.',
    example: { command: 'print(np.cosh(0.0))', says: 'Prints 1.0.' },
    seeAlso: ['numpy.sinh', 'numpy.cos'],
  },
  {
    name: 'numpy.count_nonzero',
    aliases: ['np.count_nonzero'],
    lang: 'python',
    kind: 'function',
    official: 'Counts the number of non-zero values in the array ``a``.',
    source: 'NumPy docstring',
    when: 'You want to count how many elements are not zero, or how many are True in a condition. It gives a plain count, not positions.',
    example: { command: 'print(np.count_nonzero(np.abs(H) > 1e-14), "of", H.size)', says: 'Prints how many entries of H are really nonzero, out of how many there are.' },
    seeAlso: ['numpy.flatnonzero', 'numpy.nonzero'],
  },
  {
    name: 'numpy.cov',
    aliases: ['np.cov'],
    lang: 'python',
    kind: 'function',
    official: 'Estimate a covariance matrix, given data and weights.',
    source: 'NumPy docstring',
    when: 'You have many samples of several quantities and want their covariance matrix: how much each one spreads, and how they move together. By default each row is one variable; if your data has one variable per column, pass rowvar=False, or you get a wrong-shaped answer.',
    flags: [['rowvar=False', 'each column is a variable and each row one observation']],
    example: { command: 'print(np.round(np.cov(samples, rowvar=False), 2))', says: 'Prints the covariance matrix of the samples, one row and column per variable.' },
    seeAlso: ['numpy.var', 'numpy.std', 'numpy.mean'],
  },
  {
    name: 'numpy.cross',
    aliases: ['np.cross'],
    lang: 'python',
    kind: 'function',
    official: 'Return the cross product of two (arrays of) vectors.',
    source: 'NumPy docstring',
    when: 'You want the cross product of two 3-D vectors: a vector at right angles to both, such as an orbit\'s angular momentum from position and velocity. Order matters: swapping the two flips the sign.',
    example: { command: 'print(np.cross([1, 0, 0], [0, 1, 0]))', says: 'Prints [0 0 1]: x cross y gives z.' },
    seeAlso: ['numpy.dot', 'numpy.linalg.norm'],
  },
  {
    name: 'numpy.cumsum',
    aliases: ['np.cumsum'],
    lang: 'python',
    kind: 'function',
    official: 'Return the cumulative sum of the elements along a given axis.',
    source: 'NumPy docstring',
    when: 'You want a running total, such as distance flown so far from each step. The result has the same length as the input: each place holds the sum of everything up to and including it. Many tiny float steps can build up rounding error over a long run.',
    flags: [['axis=', 'which direction to add along in a 2-D array']],
    example: { command: 'print(np.cumsum([1.0, 2.0, 3.0, 4.0]))', says: 'Prints [ 1. 3. 6. 10.]: the total after each step.' },
    seeAlso: ['numpy.sum', 'numpy.diff'],
  },
  {
    name: 'numpy.datetime64',
    aliases: ['np.datetime64'],
    lang: 'python',
    kind: 'class',
    official: 'If created from a 64-bit integer, it represents an offset from ``1970-01-01T00:00:00``.',
    source: 'NumPy docstring',
    when: 'You want real dates and times in an array, such as timestamps for a plot of a ground-station pass. Add time spans (np.timedelta64) to move along. Time zones are dropped, so treat every value as UTC.',
    example: { command: 'start = np.datetime64("2026-03-14T06:12:00")', says: 'Makes a timestamp for 6:12 in the morning on March 14, 2026.' },
    seeAlso: ['numpy.arange'],
  },
  {
    name: 'numpy.deg2rad',
    aliases: ['np.deg2rad'],
    lang: 'python',
    kind: 'function',
    official: 'Convert angles from degrees to radians.',
    source: 'NumPy docstring',
    when: 'You have angles in degrees and NumPy\'s trig functions need radians. Convert once, where the data comes in, so the rest of the code uses one unit.',
    example: { command: 'rate = np.deg2rad(2.0)', says: 'Gives about 0.0349: 2 degrees per second in radians per second.' },
    seeAlso: ['numpy.radians', 'numpy.degrees', 'numpy.rad2deg'],
  },
  {
    name: 'numpy.degrees',
    aliases: ['np.degrees'],
    lang: 'python',
    kind: 'function',
    official: 'Convert angles from radians to degrees.',
    source: 'NumPy docstring',
    when: 'You have an angle in radians and want to show it in degrees, which people read more easily. It is the same as np.rad2deg.',
    example: { command: 'print(np.degrees(np.pi / 2))', says: 'Prints 90.0.' },
    seeAlso: ['numpy.rad2deg', 'numpy.radians', 'numpy.deg2rad'],
  },
  {
    name: 'numpy.delete',
    aliases: ['np.delete'],
    lang: 'python',
    kind: 'function',
    official: 'Return a new array with sub-arrays along an axis deleted.',
    source: 'NumPy docstring',
    when: 'You want a copy of an array with some elements taken out, such as every point except the current one. The original is not changed, and each call copies the whole array, so avoid it inside a long loop.',
    example: { command: 'print(np.delete(np.array([10, 20, 30, 40]), 1))', says: 'Prints [10 30 40]: the element at index 1 is gone.' },
    seeAlso: ['numpy.concatenate'],
  },
  {
    name: 'numpy.diag',
    aliases: ['np.diag'],
    lang: 'python',
    kind: 'function',
    official: 'Extract a diagonal or construct a diagonal array.',
    source: 'NumPy docstring',
    when: 'Give it a list and it builds a square matrix with those numbers down the diagonal and zeros elsewhere, handy for covariances. Give it a matrix and it pulls the diagonal out instead. Same name, opposite jobs, so check what you pass in.',
    example: { command: 'P0 = np.diag([4.0, 9.0])', says: 'Makes [[4. 0.] [0. 9.]], a covariance with variances 4 and 9 and no coupling.' },
    seeAlso: ['numpy.eye', 'numpy.fill_diagonal', 'numpy.trace'],
  },
  {
    name: 'numpy.diff',
    aliases: ['np.diff'],
    lang: 'python',
    kind: 'function',
    official: 'Calculate the n-th discrete difference along the given axis.',
    source: 'NumPy docstring',
    when: 'You want the change from each element to the next, such as the time between samples. The result is one element shorter than the input, so line it up with care.',
    example: { command: 'dt = np.diff(np.array([0.0, 0.1, 0.2, 0.4]))', says: 'Gives [0.1 0.1 0.2]: the last gap is twice as long, a sign of a dropped sample.' },
    seeAlso: ['numpy.gradient', 'numpy.cumsum'],
  },
  {
    name: 'numpy.dot',
    aliases: ['np.dot'],
    lang: 'python',
    kind: 'function',
    official: 'Dot product of two arrays.',
    source: 'NumPy docstring',
    when: 'You want the dot product of two vectors, or a matrix product. For 2-D arrays it is the same as the @ operator, which reads more clearly. For arrays with more than two dimensions the two behave differently.',
    example: { command: 'print(np.dot([3.0, 4.0], [3.0, 4.0]))', says: 'Prints 25.0: 3 times 3 plus 4 times 4.' },
    seeAlso: ['numpy.cross', 'numpy.einsum', 'numpy.outer'],
  },
  {
    name: 'numpy.e',
    aliases: ['np.e'],
    lang: 'python',
    kind: 'constant',
    official: 'Euler\'s constant, base of natural logarithms, Napier\'s constant.',
    source: 'NumPy documentation (Constants)',
    when: 'You need the number e, about 2.718, the base of natural logarithms, as when finding the time a decay drops to 1/e of its start. It is a plain number, not a function.',
    example: { command: 'tau_guess = t[np.argmax(p < p0 / np.e)]', says: 'Finds the first time the pressure falls below about 37 percent of its starting value.' },
    seeAlso: ['numpy.exp', 'numpy.pi'],
  },
  {
    name: 'numpy.einsum',
    aliases: ['np.einsum'],
    lang: 'python',
    kind: 'function',
    official: 'Evaluates the Einstein summation convention on the operands.',
    source: 'NumPy docstring',
    when: 'You want a sum of products described by letters, such as the dot product of every row with itself. Letters that appear in the inputs but not after the arrow are summed over. It is powerful but easy to get wrong, so check the result on a small case first.',
    flags: [['"ij,ij->i"', 'the subscripts: one label per axis of each input, then the output after the arrow']],
    example: { command: 'd2 = np.einsum("ij,ij->i", v, v)', says: 'Gives the squared length of each row of v, without making a separate squared array.' },
    seeAlso: ['numpy.dot', 'numpy.linalg.norm'],
  },
  {
    name: 'numpy.empty',
    aliases: ['np.empty'],
    lang: 'python',
    kind: 'function',
    official: 'Return a new array of given shape and type, without initializing entries.',
    source: 'NumPy docstring',
    when: 'You are about to fill every slot of an array yourself, such as one row per time step, and want the space quickly. The starting values are leftover memory, not zeros, so any slot you forget to fill holds garbage.',
    example: { command: 'out = np.empty((n + 1, 6))', says: 'Makes room for n + 1 rows of 6 numbers each, to be filled in a loop.' },
    seeAlso: ['numpy.zeros', 'numpy.empty_like', 'numpy.full'],
  },
  {
    name: 'numpy.empty_like',
    aliases: ['np.empty_like'],
    lang: 'python',
    kind: 'function',
    official: 'Return a new array with the same shape and type as a given array.',
    source: 'NumPy docstring',
    when: 'You want a new, unfilled array with the same shape and type as one you already have. Like np.empty, it starts with garbage, so fill every element.',
    example: { command: 'y = np.empty_like(x)', says: 'Makes an array the same shape as x, ready to receive results.' },
    seeAlso: ['numpy.empty', 'numpy.zeros_like', 'numpy.ones_like'],
  },
  {
    name: 'numpy.errstate',
    aliases: ['np.errstate'],
    lang: 'python',
    kind: 'class',
    official: 'Context manager for floating-point error handling.',
    source: 'NumPy docstring',
    when: 'You want to change what NumPy does about divide by zero, overflow or invalid results for one block of code only. Use it with with; the old setting comes back when the block ends, even if it raised an error. Setting "raise" turns quiet nan and inf results into errors that point at the line.',
    flags: [['divide=', 'what to do on division by zero'], ['invalid=', 'what to do on an invalid result such as 0/0'], ['over=', 'what to do on overflow'], ['all=', 'set all of them at once'], ['"raise", "warn", "ignore"', 'the choices: raise an error, print a warning, or say nothing']],
    example: { command: 'with np.errstate(divide="raise", invalid="raise"):\n    rate = dv / dt', says: 'Stops with a FloatingPointError if any dt is zero, instead of quietly making inf or nan.' },
    seeAlso: ['numpy.geterr', 'with'],
  },
  {
    name: 'numpy.exp',
    aliases: ['np.exp'],
    lang: 'python',
    kind: 'function',
    official: 'Calculate the exponential of all elements in the input array.',
    source: 'NumPy docstring',
    when: 'You want e raised to each value, as in growth, decay or an atmosphere that thins with height. Large inputs (above about 709) overflow to inf.',
    example: { command: 'rho = 1.225 * np.exp(-h / 8500.0)', says: 'Gives the air density at each height h in meters, falling off with an 8.5 km scale height.' },
    seeAlso: ['numpy.log', 'numpy.e'],
  },
  {
    name: 'numpy.eye',
    aliases: ['np.eye'],
    lang: 'python',
    kind: 'function',
    official: 'Return a 2-D array with ones on the diagonal and zeros elsewhere.',
    source: 'NumPy docstring',
    when: 'You want an identity matrix: ones down the diagonal, zeros everywhere else. It is the starting point for many formulas, and the matrix version of the number 1.',
    example: { command: 'I = np.eye(3)', says: 'Makes the 3-by-3 identity matrix.' },
    seeAlso: ['numpy.diag', 'numpy.zeros'],
  },
  {
    name: 'numpy.fill_diagonal',
    aliases: ['np.fill_diagonal'],
    lang: 'python',
    kind: 'function',
    official: 'Fill the main diagonal of the given array of any dimensionality.',
    source: 'NumPy docstring',
    when: 'You want to set the diagonal of an existing matrix, such as zeroing each point\'s distance to itself. It changes the array in place and returns None, so do not assign its result.',
    example: { command: 'np.fill_diagonal(D, 0.0)', says: 'Sets every diagonal entry of D to zero; the rest of D is unchanged.' },
    seeAlso: ['numpy.diag', 'numpy.eye'],
  },
  {
    name: 'numpy.finfo',
    aliases: ['np.finfo'],
    lang: 'python',
    kind: 'class',
    official: 'Machine limits for floating point types.',
    source: 'NumPy docstring',
    when: 'You want to know the limits of a floating-point type, most often its eps: the gap between 1 and the next number it can store. Use it to choose sensible tolerances instead of guessing.',
    example: { command: 'print(np.finfo(np.float64).eps)', says: 'Prints 2.220446049250313e-16, the precision of a float64 near 1.' },
    seeAlso: ['numpy.float64', 'numpy.float32', 'numpy.spacing'],
  },
  {
    name: 'numpy.flatnonzero',
    aliases: ['np.flatnonzero'],
    lang: 'python',
    kind: 'function',
    official: 'Return indices that are non-zero in the flattened version of a.',
    source: 'NumPy docstring',
    when: 'You want the positions where a condition is True, as one list of indices, such as which samples are dropouts. It treats the array as if it were flattened into one row.',
    example: { command: 'print(np.flatnonzero(np.array([12.0, 16.0, 9.0, 20.0]) > 15.0))', says: 'Prints [1 3]: the positions of the readings above 15.' },
    seeAlso: ['numpy.nonzero', 'numpy.where', 'numpy.count_nonzero'],
  },
  {
    name: 'numpy.float32',
    aliases: ['np.float32'],
    lang: 'python',
    kind: 'class',
    official: 'Single-precision floating-point number type, compatible with C ``float``.',
    source: 'NumPy docstring',
    when: 'You want to save memory, or match hardware or a file that stores 32-bit floats. It keeps only about 7 significant digits, so positions in meters from Earth\'s center lose the decimals.',
    example: { command: 'print(float(np.float32(6378137.3)))', says: 'Prints 6378137.5: float32 cannot hold the .3.' },
    seeAlso: ['numpy.float64', 'numpy.finfo'],
  },
  {
    name: 'numpy.float64',
    aliases: ['np.float64'],
    lang: 'python',
    kind: 'class',
    official: 'Double-precision floating-point number type, compatible with Python :class:`float` and C ``double``.',
    source: 'NumPy docstring',
    when: 'The standard floating-point type, with about 16 significant digits; NumPy uses it unless told otherwise. It is the same as Python\'s float. Even so, 0.1 + 0.2 is not exactly 0.3.',
    example: { command: 'tlm = np.fromfile("telemetry.f64", dtype=np.float64)', says: 'Reads the file as a long run of 64-bit floats.' },
    seeAlso: ['numpy.float32', 'numpy.finfo', 'float'],
  },
  {
    name: 'numpy.floor',
    aliases: ['np.floor'],
    lang: 'python',
    kind: 'function',
    official: 'Return the floor of the input, element-wise.',
    source: 'NumPy docstring',
    when: 'You want to round down to the whole number below, such as counting complete laps. For negative numbers "down" means further from zero: -2.1 becomes -3.0. The result is still a float.',
    example: { command: 'k = np.floor(M / (2 * np.pi))', says: 'Counts how many whole laps the angle M has gone round.' },
    seeAlso: ['numpy.ceil', 'numpy.round'],
  },
  {
    name: 'numpy.fromfile',
    aliases: ['np.fromfile'],
    lang: 'python',
    kind: 'function',
    official: 'Construct an array from data in a text or binary file.',
    source: 'NumPy docstring',
    when: 'You have a raw binary file of numbers and want it all in memory as an array. The file does not record its type or shape, so you must give the right dtype and reshape yourself; a wrong dtype gives nonsense without an error.',
    flags: [['dtype=', 'the type of number the file holds']],
    example: { command: 'everything = np.fromfile("telemetry.f64", dtype=np.float64).reshape(-1, 8)', says: 'Loads the whole file as float64 values and arranges them in rows of 8 channels.' },
    seeAlso: ['numpy.memmap', 'numpy.load'],
  },
  {
    name: 'numpy.full',
    aliases: ['np.full'],
    lang: 'python',
    kind: 'function',
    official: 'Return a new array of given shape and type, filled with `fill_value`.',
    source: 'NumPy docstring',
    when: 'You want an array where every element starts at the same value, such as equal weights for N particles.',
    flags: [['shape, fill_value', 'how big to make it, then the value to put everywhere'], ['dtype=', 'the type of number to store']],
    example: { command: 'weights = np.full(4, 0.25)', says: 'Gives [0.25 0.25 0.25 0.25].' },
    seeAlso: ['numpy.zeros', 'numpy.ones', 'numpy.empty'],
  },
  {
    name: 'numpy.geterr',
    aliases: ['np.geterr'],
    lang: 'python',
    kind: 'function',
    official: 'Get the current way of handling floating-point errors.',
    source: 'NumPy docstring',
    when: 'You want to see NumPy\'s current policy for floating-point problems such as divide by zero. It returns a dictionary, with "warn" as the usual answer.',
    example: { command: 'print(np.geterr()["divide"])', says: 'Prints warn: dividing by zero gives a warning and carries on.' },
    seeAlso: ['numpy.errstate'],
  },
  {
    name: 'numpy.gradient',
    aliases: ['np.gradient'],
    lang: 'python',
    kind: 'function',
    official: 'Return the gradient of an N-dimensional array.',
    source: 'NumPy docstring',
    when: 'You want a rate of change from samples, such as vertical speed from altitude readings. Pass the time array too; without it NumPy assumes a step of 1 between samples, and gets it wrong wherever the spacing is uneven. Differencing noisy data makes the noise bigger.',
    flags: [['y, t', 'the values, then the times (or positions) they were taken at']],
    example: { command: 'vz = np.gradient(alt, t)', says: 'Gives the climb rate at every sample, from the altitudes and their actual times.' },
    seeAlso: ['numpy.diff'],
  },
  {
    name: 'numpy.histogram2d',
    aliases: ['np.histogram2d'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the bi-dimensional histogram of two data samples.',
    source: 'NumPy docstring',
    when: 'You have many (x, y) points and want to count how many fall in each square of a grid, such as building an image from detector hits.',
    flags: [['bins=', 'how many squares, or the exact edges, for x and for y']],
    example: { command: 'img, _, _ = np.histogram2d(hits[:, 0], hits[:, 1], bins=[edges, edges])', says: 'Counts the hits in each grid square and returns the counts as a 2-D array, plus the edges.' },
    seeAlso: ['numpy.column_stack'],
  },
  {
    name: 'numpy.hstack',
    aliases: ['np.hstack'],
    lang: 'python',
    kind: 'function',
    official: 'Stack arrays in sequence horizontally (column wise).',
    source: 'NumPy docstring',
    when: 'You want to join arrays side by side. For 2-D arrays that adds columns; for 1-D arrays it simply joins them end to end.',
    example: { command: 'print(np.hstack([np.array([1, 2]), np.array([3])]))', says: 'Prints [1 2 3].' },
    seeAlso: ['numpy.vstack', 'numpy.column_stack', 'numpy.concatenate'],
  },
  {
    name: 'numpy.hypot',
    aliases: ['np.hypot'],
    lang: 'python',
    kind: 'function',
    official: 'Given the "legs" of a right triangle, return its hypotenuse.',
    source: 'NumPy docstring',
    when: 'You want the length of the long side of a right triangle, the square root of a squared plus b squared, such as a horizontal speed from its two parts. It avoids the overflow that squaring a huge number can cause.',
    example: { command: 'print(np.hypot(3.0, 4.0))', says: 'Prints 5.0.' },
    seeAlso: ['numpy.arctan2', 'numpy.linalg.norm', 'numpy.sqrt'],
  },
  {
    name: 'numpy.inf',
    aliases: ['np.inf'],
    lang: 'python',
    kind: 'constant',
    official: 'IEEE 754 floating point representation of (positive) infinity.',
    source: 'NumPy documentation (Constants)',
    when: 'You need infinity, such as a starting value for "the worst so far" that any real number will beat, or ord=np.inf in a norm. It is a float. inf minus inf, or 0 times inf, gives nan.',
    example: { command: 'worst = -np.inf', says: 'Starts the worst score below every possible number, so the first real value replaces it.' },
    seeAlso: ['numpy.nan', 'numpy.isfinite'],
  },
  {
    name: 'numpy.int64',
    aliases: ['np.int64'],
    lang: 'python',
    kind: 'class',
    official: 'Signed integer type, compatible with C ``long``.',
    source: 'NumPy docstring',
    when: 'NumPy\'s usual whole-number type, which holds numbers up to about 9.2 billion billion. Unlike a Python int it has a fixed size, so going past the limit wraps round to a wrong number, often without any warning.',
    example: { command: 'counts = np.zeros(3, dtype=np.int64)', says: 'Makes [0 0 0] as 64-bit whole numbers.' },
    seeAlso: ['int', 'numpy.float64'],
  },
  {
    name: 'numpy.interp',
    aliases: ['np.interp'],
    lang: 'python',
    kind: 'function',
    official: 'One-dimensional linear interpolation for monotonically increasing sample points.',
    source: 'NumPy docstring',
    when: 'You have values at some times and want estimates at other times, joining neighboring points with straight lines. The known times must go up. Outside their range it repeats the first or last value instead of extending the line.',
    flags: [['x, xp, fp', 'the new times, the known times, then the known values']],
    example: { command: 'print(np.interp(0.15, [0.0, 0.1, 0.2], [0.5, 1.0, 1.5]))', says: 'Prints 1.25: halfway between the values at 0.1 and 0.2.' },
    seeAlso: ['numpy.searchsorted'],
  },
  {
    name: 'numpy.isfinite',
    aliases: ['np.isfinite'],
    lang: 'python',
    kind: 'function',
    official: 'Test element-wise for finiteness (not infinity and not Not a Number).',
    source: 'NumPy docstring',
    when: 'You want to check that numbers are ordinary values, not inf or nan (not a number). Use it as a mask to keep the good readings, or with np.all to check a whole result.',
    example: { command: 'assert np.all(np.isfinite(C))', says: 'Stops the program if any entry of C is inf or nan.' },
    seeAlso: ['numpy.isnan', 'numpy.all', 'numpy.inf'],
  },
  {
    name: 'numpy.isnan',
    aliases: ['np.isnan'],
    lang: 'python',
    kind: 'function',
    official: 'Test element-wise for NaN and return result as a boolean array.',
    source: 'NumPy docstring',
    when: 'You want to find nan (not a number) values, such as gaps in sensor data. You cannot test with == because nan is not equal to anything, even itself.',
    example: { command: 'print(np.isnan(T).sum())', says: 'Prints how many readings in T are missing.' },
    seeAlso: ['numpy.isfinite', 'numpy.nan', 'numpy.nanmean'],
  },
  {
    name: 'numpy.kron',
    aliases: ['np.kron'],
    lang: 'python',
    kind: 'function',
    official: 'Kronecker product of two arrays.',
    source: 'NumPy docstring',
    when: 'You want to repeat a small matrix in blocks, scaled by the entries of another, such as placing a weight matrix once per step down the diagonal of a big one. The result can get very large, fast.',
    example: { command: 'Qbar = np.kron(np.eye(N), Q)', says: 'Builds a big block-diagonal matrix with N copies of Q down the diagonal.' },
    seeAlso: ['numpy.block', 'numpy.eye', 'numpy.outer'],
  },
  {
    name: 'numpy.lib',
    aliases: ['np.lib'],
    lang: 'python',
    kind: 'module',
    official: '``numpy.lib`` is mostly a space for implementing functions that don\'t belong in core or in another NumPy submodule with a clear purpose (e.g. ``random``, ``fft``, ``linalg``, ``ma``).',
    source: 'NumPy docstring',
    when: 'You rarely use it directly. In ORBIT you meet it through np.lib.format, the part that reads and writes .npy files.',
    example: { command: 'np.lib.format.open_memmap("accel.npy", mode="w+", dtype=np.float32, shape=(1000, 3))', says: 'Reaches into numpy.lib to create a new .npy file on disk.' },
    seeAlso: ['numpy.lib.format'],
  },
  {
    name: 'numpy.lib.format',
    aliases: ['np.lib.format'],
    lang: 'python',
    kind: 'module',
    official: 'A simple format for saving numpy arrays to disk with the full information about them.',
    source: 'NumPy docstring',
    when: 'You want to know how .npy files work, or to make one that is bigger than memory. The file starts with a small header that records the shape and type, so it loads back correctly.',
    example: { command: 'np.lib.format.open_memmap("accel.npy", mode="w+", dtype=np.float32, shape=(1000, 3))', says: 'Creates a new .npy file that remembers its own shape and type.' },
    seeAlso: ['numpy.lib.format.open_memmap', 'numpy.save', 'numpy.load'],
  },
  {
    name: 'numpy.lib.format.open_memmap',
    aliases: ['np.lib.format.open_memmap'],
    lang: 'python',
    kind: 'function',
    official: 'Open a .npy file as a memory-mapped array.',
    source: 'NumPy docstring',
    when: 'You want to create a .npy file too big to fit in memory and fill it piece by piece. The data lives on disk and only the parts you touch are loaded. Changes may not reach the file until you flush or delete the array.',
    flags: [['mode="w+"', 'create a new file (or overwrite one) for reading and writing'], ['dtype=', 'the type of number to store'], ['shape=', 'how many rows and columns']],
    example: { command: 'out = np.lib.format.open_memmap("accel.npy", mode="w+", dtype=np.float32, shape=(3_000_000, 3))', says: 'Creates a 3-million-row file on disk that you can fill like an ordinary array.' },
    seeAlso: ['numpy.memmap', 'numpy.load', 'numpy.save'],
  },
  {
    name: 'numpy.linalg',
    aliases: ['np.linalg'],
    lang: 'python',
    kind: 'module',
    official: 'The NumPy linear algebra functions rely on BLAS and LAPACK to provide efficient low level implementations of standard linear algebra algorithms.',
    source: 'NumPy docstring',
    when: 'You want linear algebra: solve equations, invert matrices, find lengths, eigenvalues or decompositions. Lessons reach it as np.linalg.',
    example: { command: 'x = np.linalg.solve(A, b)', says: 'Uses numpy.linalg to solve A x = b.' },
    seeAlso: ['numpy.linalg.solve', 'numpy.linalg.norm', 'numpy.linalg.inv'],
  },
  {
    name: 'numpy.linalg.LinAlgError',
    aliases: ['np.linalg.LinAlgError'],
    lang: 'python',
    kind: 'exception',
    official: 'Generic Python-exception-derived object raised by linalg functions.',
    source: 'NumPy docstring',
    when: 'You want to catch the error NumPy raises when a linear algebra step fails, such as a matrix that cannot be inverted or a Cholesky on one that is not positive definite. Catch it, so you can report the problem or fall back to something safer.',
    example: { command: 'try:\n    L = np.linalg.cholesky(P)\nexcept np.linalg.LinAlgError:\n    print("P is not positive definite")', says: 'Tries to factor P and prints a message instead of crashing if it fails.' },
    seeAlso: ['numpy.linalg.cholesky', 'numpy.linalg.inv', 'except'],
  },
  {
    name: 'numpy.linalg.cholesky',
    aliases: ['np.linalg.cholesky'],
    lang: 'python',
    kind: 'function',
    official: 'Cholesky decomposition.',
    source: 'NumPy docstring',
    when: 'You have a symmetric, positive definite matrix, such as a covariance, and want its "square root" L with L @ L.T equal to it. It is also a quick test: it fails with LinAlgError if the matrix is not positive definite. It only reads one triangle, so a matrix that has drifted off symmetric can pass without a warning.',
    example: { command: 'L = np.linalg.cholesky(np.array([[4.0, 2.0], [2.0, 3.0]]))', says: 'Gives the lower triangle [[2. 0.] [1. 1.414...]], and L @ L.T gives the matrix back.' },
    seeAlso: ['numpy.linalg.LinAlgError', 'numpy.linalg.eigh', 'numpy.linalg.qr'],
  },
  {
    name: 'numpy.linalg.cond',
    aliases: ['np.linalg.cond'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the condition number of a matrix.',
    source: 'NumPy docstring',
    when: 'You want to know how much a matrix magnifies small errors before you trust a solve with it. A condition number of 10 to the n means you can lose about n of float64\'s 16 digits.',
    example: { command: 'print(np.linalg.cond(np.array([[1.0, 0.0], [0.0, 1e-6]])))', says: 'Prints 1000000.0: solving with this matrix can lose about 6 digits.' },
    seeAlso: ['numpy.linalg.svd', 'numpy.linalg.solve'],
  },
  {
    name: 'numpy.linalg.det',
    aliases: ['np.linalg.det'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the determinant of an array.',
    source: 'NumPy docstring',
    when: 'You want the determinant of a square matrix, such as checking that a rotation matrix has determinant 1. Do not use it to test whether a matrix is nearly singular; its size depends on scale, so use np.linalg.cond for that.',
    example: { command: 'print(np.linalg.det(np.array([[2.0, 1.0], [1.0, 3.0]])))', says: 'Prints about 5.0 (5.000000000000001, with rounding).' },
    seeAlso: ['numpy.linalg.cond', 'numpy.linalg.inv'],
  },
  {
    name: 'numpy.linalg.eig',
    aliases: ['np.linalg.eig'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the eigenvalues and right eigenvectors of a square array.',
    source: 'NumPy docstring',
    when: 'You want the eigenvalues and eigenvectors of any square matrix, such as to see whether a system is stable. The answers can be complex and come in no particular order. Each eigenvector is a column of the second result, not a row.',
    example: { command: 'w, V = np.linalg.eig(A)', says: 'Gives the eigenvalues in w and the matching eigenvectors as the columns of V.' },
    seeAlso: ['numpy.linalg.eigh', 'numpy.linalg.eigvals'],
  },
  {
    name: 'numpy.linalg.eigh',
    aliases: ['np.linalg.eigh'],
    lang: 'python',
    kind: 'function',
    official: 'Return the eigenvalues and eigenvectors of a complex Hermitian (conjugate symmetric) or a real symmetric matrix.',
    source: 'NumPy docstring',
    when: 'You have a symmetric matrix, such as a covariance or an inertia matrix, and want its eigenvalues and eigenvectors. It is faster than eig, always gives real eigenvalues sorted smallest first, and perpendicular eigenvectors. It only reads one triangle, so do not give it a matrix that is not symmetric.',
    example: { command: 'w, Q = np.linalg.eigh(P)', says: 'Gives the variances along the main axes of the covariance P in w, and those axes as the columns of Q.' },
    seeAlso: ['numpy.linalg.eig', 'numpy.linalg.eigvalsh'],
  },
  {
    name: 'numpy.linalg.eigvals',
    aliases: ['np.linalg.eigvals'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the eigenvalues of a general matrix.',
    source: 'NumPy docstring',
    when: 'You want only the eigenvalues of a square matrix, not the eigenvectors, such as to check stability. They may be complex and are in no set order.',
    example: { command: 'print(np.linalg.eigvals(np.array([[0.0, 1.0], [-2.0, -3.0]])))', says: 'Prints [-1. -2.]: both negative, so this system settles down.' },
    seeAlso: ['numpy.linalg.eig', 'numpy.linalg.eigvalsh'],
  },
  {
    name: 'numpy.linalg.eigvalsh',
    aliases: ['np.linalg.eigvalsh'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the eigenvalues of a complex Hermitian or real symmetric matrix.',
    source: 'NumPy docstring',
    when: 'You want only the eigenvalues of a symmetric matrix, such as to check that a covariance is positive definite. They come back real and sorted smallest first.',
    example: { command: 'print(np.all(np.linalg.eigvalsh(P) > 0))', says: 'Prints True if P is positive definite.' },
    seeAlso: ['numpy.linalg.eigh', 'numpy.linalg.eigvals'],
  },
  {
    name: 'numpy.linalg.inv',
    aliases: ['np.linalg.inv'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the inverse of a matrix.',
    source: 'NumPy docstring',
    when: 'You truly need the inverse matrix itself. To solve A x = b, use np.linalg.solve(A, b) instead; it is faster and more accurate than inv(A) @ b. It raises LinAlgError for a singular matrix.',
    example: { command: 'print(np.linalg.inv(np.array([[2.0, 0.0], [0.0, 4.0]])))', says: 'Prints [[0.5 0. ] [0. 0.25]].' },
    seeAlso: ['numpy.linalg.solve', 'numpy.linalg.pinv', 'numpy.linalg.LinAlgError'],
  },
  {
    name: 'numpy.linalg.lstsq',
    aliases: ['np.linalg.lstsq'],
    lang: 'python',
    kind: 'function',
    official: 'Return the least-squares solution to a linear matrix equation.',
    source: 'NumPy docstring',
    when: 'You have more equations than unknowns, such as fitting a line to many noisy points, and want the best fit. It returns four things; take [0] for the answer. Pass rcond=None to use the current default cutoff and avoid a warning.',
    flags: [['rcond=None', 'use the recommended cutoff for treating tiny singular values as zero']],
    example: { command: 'x = np.linalg.lstsq(H, y, rcond=None)[0]', says: 'Gives the intercept and slope of the line that best fits the points.' },
    seeAlso: ['numpy.linalg.solve', 'numpy.linalg.pinv', 'numpy.polyfit'],
  },
  {
    name: 'numpy.linalg.matrix_power',
    aliases: ['np.linalg.matrix_power'],
    lang: 'python',
    kind: 'function',
    official: 'Raise a square matrix to the (integer) power `n`.',
    source: 'NumPy docstring',
    when: 'You want a square matrix multiplied by itself n times, such as stepping a system forward n steps at once. A ** n does something else: it raises each element separately.',
    example: { command: 'print(np.linalg.matrix_power(np.array([[1.0, 1.0], [0.0, 1.0]]), 3))', says: 'Prints [[1. 3.] [0. 1.]]: three steps of the same update.' },
    seeAlso: ['numpy.linalg.inv'],
  },
  {
    name: 'numpy.linalg.matrix_rank',
    aliases: ['np.linalg.matrix_rank'],
    lang: 'python',
    kind: 'function',
    official: 'Return matrix rank of array using SVD method',
    source: 'NumPy docstring',
    when: 'You want to know how many independent directions a matrix really has, such as whether sensors measure truly different things. With floats, "zero" means "below a cutoff", and you can set that cutoff yourself with tol.',
    flags: [['tol=', 'singular values below this count as zero']],
    example: { command: 'print(np.linalg.matrix_rank(np.array([[1.0, 2.0], [2.0, 4.0]])))', says: 'Prints 1: the second row is just twice the first.' },
    seeAlso: ['numpy.linalg.svd', 'numpy.linalg.cond'],
  },
  {
    name: 'numpy.linalg.norm',
    aliases: ['np.linalg.norm'],
    lang: 'python',
    kind: 'function',
    official: 'Matrix or vector norm.',
    source: 'NumPy docstring',
    when: 'You want the length of a vector, such as the distance to Earth\'s center from a position, or the size of a matrix. By default it is the usual straight-line length. On a 2-D array with no axis it measures the whole array as one, so pass axis=1 for one length per row.',
    flags: [['axis=', 'measure along this direction, such as axis=1 for one length per row'], ['keepdims=True', 'keep the measured axis with size 1, so you can divide by the result directly'], ['ord=', 'which kind of length; ord=np.inf is the biggest single component']],
    example: { command: 'rn = np.linalg.norm(r)', says: 'Gives the distance from the center to position r.' },
    seeAlso: ['numpy.hypot', 'numpy.dot', 'numpy.sqrt'],
  },
  {
    name: 'numpy.linalg.pinv',
    aliases: ['np.linalg.pinv'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the (Moore-Penrose) pseudo-inverse of a matrix.',
    source: 'NumPy docstring',
    when: 'You want the best available "inverse" of a matrix that has none, because it is not square or not full rank. Multiplying by it gives the least-squares answer. Tiny singular values below the cutoff are treated as zero.',
    flags: [['rcond=', 'the relative cutoff below which singular values count as zero']],
    example: { command: 'print(np.linalg.pinv(np.array([[1.0, 2.0], [2.0, 4.0]])) @ np.array([1.0, 2.0]))', says: 'Prints [0.2 0.4], the smallest answer that fits the equations.' },
    seeAlso: ['numpy.linalg.inv', 'numpy.linalg.lstsq', 'numpy.linalg.svd'],
  },
  {
    name: 'numpy.linalg.qr',
    aliases: ['np.linalg.qr'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the qr factorization of a matrix.',
    source: 'NumPy docstring',
    when: 'You want to split a matrix into Q, whose columns are perpendicular unit vectors, and R, an upper triangle, often for a stable least-squares fit. Signs can differ from a hand calculation; both answers are correct.',
    example: { command: 'Q, R = np.linalg.qr(A)', says: 'Gives Q and R with Q @ R equal to A.' },
    seeAlso: ['numpy.linalg.lstsq', 'numpy.linalg.svd', 'numpy.linalg.cholesky'],
  },
  {
    name: 'numpy.linalg.solve',
    aliases: ['np.linalg.solve'],
    lang: 'python',
    kind: 'function',
    official: 'Solve a linear matrix equation, or system of linear scalar equations.',
    source: 'NumPy docstring',
    when: 'You want x in A x = b for a square matrix A: the everyday tool for linear equations. Prefer it to multiplying by np.linalg.inv(A). It raises LinAlgError if A is singular, but a nearly singular A gives an inaccurate answer without complaint, so check np.linalg.cond.',
    example: { command: 'x = np.linalg.solve(np.array([[2.0, 1.0], [1.0, 3.0]]), np.array([3.0, 5.0]))', says: 'Gives [0.8 1.4], the x that makes A x equal b.' },
    seeAlso: ['numpy.linalg.inv', 'numpy.linalg.lstsq', 'numpy.linalg.cond'],
  },
  {
    name: 'numpy.linalg.svd',
    aliases: ['np.linalg.svd'],
    lang: 'python',
    kind: 'function',
    official: 'Singular Value Decomposition.',
    source: 'NumPy docstring',
    when: 'You want the singular values of a matrix, how strongly it stretches in each direction, and optionally the directions too. It returns U, the singular values, and Vt; the third result is already transposed. The singular values come largest first.',
    flags: [['compute_uv=False', 'return only the singular values'], ['full_matrices=False', 'give the smaller, trimmed U and Vt']],
    example: { command: 'U, s, Vt = np.linalg.svd(H, full_matrices=False)', says: 'Splits H into U, the singular values s, and Vt, trimmed to the sizes you need.' },
    seeAlso: ['numpy.linalg.pinv', 'numpy.linalg.matrix_rank', 'numpy.linalg.cond'],
  },
]
