import type { CommandRef } from './types'

export const COMMANDS: CommandRef[] = [
  // ---------------------------------------------------------------- pytest
  {
    name: 'pytest.mark.skipif',
    lang: 'python',
    kind: 'function',
    official: 'skip the given test function if any of the conditions evaluate to True.',
    source: 'pytest built-in marker help (pytest --markers)',
    when: 'A test can only run on some machines, such as one that needs a POSIX (Linux or macOS) feature, and you want it skipped cleanly elsewhere instead of failing. Always give a reason, because that is what shows up in the report.',
    flags: [
      ['condition', 'the first argument; when it is True the test is skipped'],
      ['reason=', 'a short note saying why, printed in the test report'],
    ],
    example: {
      command: '@pytest.mark.skipif(sys.platform == "win32", reason="uses POSIX shared memory")',
      says: 'Skips the test below on Windows and prints the reason in the report. Everywhere else it runs as normal.',
    },
    seeAlso: ['pytest.mark.skip', 'pytest.mark', 'pytest.mark.slow'],
  },
  {
    name: 'pytest.mark.slow',
    lang: 'python',
    kind: 'function',
    official: 'A decorator for applying a mark on test functions and classes.',
    source: 'pytest docstring',
    when: 'A test takes a long time, like a long filter soak or a big Monte Carlo run, and you want to leave it out of the quick run. slow is a marker you invent, not a built-in one, so register it in pyproject.toml or conftest.py; with --strict-markers a typo such as slwo becomes an error instead of silently un-marking the test.',
    example: {
      command: '@pytest.mark.slow\ndef test_nav_filter_long_soak(): ...',
      says: 'Labels the test slow, so pytest -m "not slow" leaves it out and pytest -m slow runs only tests like it.',
    },
    seeAlso: ['pytest.mark', 'pytest.mark.skipif', 'pytest.mark.hil'],
  },
  {
    name: 'pytest.param',
    lang: 'python',
    kind: 'function',
    official: 'Specify a parameter in `pytest.mark.parametrize`_ calls or :ref:`parametrized fixtures <fixture-parametrize-marks>`.',
    source: 'pytest docstring',
    when: 'You are writing a table of cases for pytest.mark.parametrize and want one row to have a readable name, or its own marker such as skip. Without an id, pytest names the case from its values, which gets hard to read fast.',
    flags: [
      ['values', 'the values for this one case, in the same order as the parameter names'],
      ['id=', 'the name shown in square brackets after the test name'],
      ['marks=', 'a marker for just this case, such as pytest.mark.skip(reason=...)'],
    ],
    example: {
      command: 'pytest.param(2.0, 0.73, id="gto")',
      says: 'One test case with the values 2.0 and 0.73. The report calls it test_x[gto], and pytest -k gto reruns just this row.',
    },
    seeAlso: ['pytest.mark.parametrize', 'pytest.fixture', 'pytest.mark.skip'],
  },
  {
    name: 'pytest.raises',
    lang: 'python',
    kind: 'function',
    official: 'Assert that a code block/function call raises an exception type, or one of its subclasses.',
    source: 'pytest docstring',
    when: 'You want to test that bad input is refused: the code inside the with block must raise the error you name, or the test fails. match= is searched as a regular expression, so characters like . ( and + have special meanings in it.',
    flags: [
      ['exception type', 'the error you expect, such as ValueError'],
      ['match=', 'text (a regular expression) that must appear in the error message'],
      ['as exc', 'keeps the caught error so you can check it afterwards, such as exc.value.code'],
    ],
    example: {
      command: 'with pytest.raises(ValueError, match="m0 >= mf"):\n    delta_v(isp=300, m0=500, mf=1000)',
      says: 'Passes only if the call raises ValueError with m0 >= mf in its message. If nothing is raised, the test fails.',
    },
    seeAlso: ['pytest', 'pytest.approx', 'raise', 'ValueError'],
  },

  // ---------------------------------------------------------------- scipy top level
  {
    name: 'scipy',
    lang: 'python',
    kind: 'module',
    official: 'SciPy: A scientific computing package for Python',
    source: 'SciPy docstring',
    when: 'You need ready-made, well-tested numerical tools built on NumPy: solving differential equations, finding roots, fitting curves, filtering signals, statistics, rotations. Most code imports one part of it at a time, such as from scipy import linalg, rather than scipy on its own.',
    example: { command: 'import scipy\nprint(scipy.__version__)', says: 'Loads SciPy and prints which version is installed, such as 1.17.1.' },
    seeAlso: ['numpy', 'scipy.__version__', 'scipy.integrate', 'scipy.optimize'],
  },
  {
    name: 'scipy.__version__',
    lang: 'python',
    kind: 'constant',
    official: 'SciPy version string',
    source: 'SciPy docstring',
    when: 'You want to record which SciPy produced a result, for example in the header of a saved reference file, so a later change in numbers can be traced. It is text, not a number, so comparing versions as strings goes wrong ("1.10" sorts before "1.9").',
    example: {
      command: 'f.write(f"# method: scipy {scipy.__version__} DOP853\\n")',
      says: 'Writes a comment line such as # method: scipy 1.17.1 DOP853 into the file.',
    },
    seeAlso: ['scipy'],
  },

  // ---------------------------------------------------------------- scipy.constants
  {
    name: 'scipy.constants',
    aliases: ['constants'],
    lang: 'python',
    kind: 'module',
    official: 'Physical and mathematical constants and units.',
    source: 'SciPy docstring',
    when: 'You need a physical constant or a unit conversion and do not want to type the digits yourself. Every value is in SI units (meters, kilograms, seconds, pascals): multiply by a unit to go into SI, divide to come out of it.',
    example: { command: 'from scipy import constants\nprint(constants.g)', says: 'Prints 9.80665, standard gravity in m/s^2.' },
    seeAlso: ['scipy.constants.g', 'scipy.constants.physical_constants'],
  },
  {
    name: 'scipy.constants.G',
    aliases: ['constants.G'],
    lang: 'python',
    kind: 'constant',
    official: 'Newtonian constant of gravitation',
    source: 'SciPy docstring (scipy.constants)',
    when: 'You are working out gravity between two masses from scratch. Capital G is the universal constant in m^3/(kg s^2); lowercase g is surface gravity, and mixing them up is a classic bug. For Earth orbits, the measured product mu = G times Earth\'s mass is more accurate than multiplying the two yourself.',
    example: { command: 'print(constants.G)', says: 'Prints 6.6743e-11, the gravitational constant in m^3/(kg s^2).' },
    seeAlso: ['scipy.constants.g', 'scipy.constants.physical_constants'],
  },
  {
    name: 'scipy.constants.atm',
    aliases: ['constants.atm'],
    lang: 'python',
    kind: 'constant',
    official: 'standard atmosphere in pascals',
    source: 'SciPy docstring (scipy.constants)',
    when: 'You need sea-level air pressure, or want to turn a pressure in atmospheres into pascals. It is a fixed standard value, not the actual pressure today.',
    example: { command: 'print(constants.atm)', says: 'Prints 101325.0, the pascals in one standard atmosphere.' },
    seeAlso: ['scipy.constants.psi'],
  },
  {
    name: 'scipy.constants.c',
    aliases: ['constants.c'],
    lang: 'python',
    kind: 'constant',
    official: 'speed of light in vacuum',
    source: 'SciPy docstring (scipy.constants)',
    when: 'You are turning a radio signal\'s travel time into a distance, as in radar or GPS ranging. It is in meters per second, so a time in microseconds must be changed to seconds first.',
    example: { command: 'print(constants.c)', says: 'Prints 299792458.0, the speed of light in m/s.' },
    seeAlso: ['scipy.constants'],
  },
  {
    name: 'scipy.constants.degree',
    aliases: ['constants.degree'],
    lang: 'python',
    kind: 'constant',
    official: 'degree in radians',
    source: 'SciPy docstring (scipy.constants)',
    when: 'You have an angle in degrees and a function that wants radians, as np.sin does. Multiply by it to go into radians and divide by it to come back.',
    example: { command: 'print(round(np.sin(30.0 * constants.degree), 3))', says: 'Prints 0.5, the sine of 30 degrees.' },
    seeAlso: ['numpy.radians', 'numpy.degrees'],
  },
  {
    name: 'scipy.constants.foot',
    aliases: ['constants.foot'],
    lang: 'python',
    kind: 'constant',
    official: 'one foot in meters',
    source: 'SciPy docstring (scipy.constants)',
    when: 'A number arrives in feet, such as an aircraft altitude, and your code works in meters. Multiply feet by it to get meters; divide meters by it to get feet.',
    example: { command: 'print(round(35000 * constants.foot))', says: 'Prints 10668, the meters in 35,000 feet.' },
    seeAlso: ['scipy.constants.nautical_mile'],
  },
  {
    name: 'scipy.constants.g',
    aliases: ['constants.g'],
    lang: 'python',
    kind: 'constant',
    official: 'standard acceleration of gravity',
    source: 'SciPy docstring (scipy.constants)',
    when: 'You need standard gravity, for example in the rocket equation where specific impulse in seconds is multiplied by g. It is a fixed agreed value, 9.80665 m/s^2, not the real gravity at your altitude, which gets weaker as you climb.',
    example: {
      command: 'dv = 300 * constants.g * np.log(500 / 200)',
      says: 'Gives about 2696 m/s, the delta-v for a 300 s engine taking a rocket from 500 kg down to 200 kg.',
    },
    seeAlso: ['scipy.constants.G'],
  },
  {
    name: 'scipy.constants.nautical_mile',
    aliases: ['constants.nautical_mile'],
    lang: 'python',
    kind: 'constant',
    official: 'one nautical mile in meters',
    source: 'SciPy docstring (scipy.constants)',
    when: 'A distance comes in nautical miles, as sea and air navigation often does. Multiply by it to get meters.',
    example: { command: 'print(10 * constants.nautical_mile)', says: 'Prints 18520.0, the meters in ten nautical miles.' },
    seeAlso: ['scipy.constants.foot'],
  },
  {
    name: 'scipy.constants.physical_constants',
    aliases: ['constants.physical_constants'],
    lang: 'python',
    kind: 'constant',
    official: 'Dictionary of physical constants, of the format ``physical_constants[name] = (value, unit, uncertainty)``.',
    source: 'SciPy docstring (scipy.constants)',
    when: 'You want a constant together with its unit and how precisely it is known. You look it up by its full official name, spelled exactly, or you get a KeyError.',
    example: {
      command: 'value, unit, uncertainty = constants.physical_constants["Newtonian constant of gravitation"]',
      says: 'Sets value to 6.6743e-11, unit to m^3 kg^-1 s^-2 and uncertainty to 1.5e-15.',
    },
    seeAlso: ['scipy.constants.G', 'dict'],
  },
  {
    name: 'scipy.constants.pound_force',
    aliases: ['constants.pound_force'],
    lang: 'python',
    kind: 'constant',
    official: 'one pound force in newtons',
    source: 'SciPy docstring (scipy.constants)',
    when: 'An engine thrust or load comes in pounds-force (lbf) and you need newtons. Multiply by it; do not confuse it with the pound as a mass.',
    example: { command: 'print(round(7500 * constants.pound_force))', says: 'Prints 33362, the newtons in 7,500 lbf of thrust.' },
    seeAlso: ['scipy.constants.psi'],
  },
  {
    name: 'scipy.constants.psi',
    aliases: ['constants.psi'],
    lang: 'python',
    kind: 'constant',
    official: 'one psi in pascals',
    source: 'SciPy docstring (scipy.constants)',
    when: 'A pressure, such as a tank or chamber pressure, is in pounds per square inch and you need pascals. Multiply by it to get pascals.',
    example: { command: 'print(round(300 * constants.psi))', says: 'Prints 2068427, the pascals in a 300 psi chamber pressure.' },
    seeAlso: ['scipy.constants.atm', 'scipy.constants.pound_force'],
  },

  // ---------------------------------------------------------------- scipy.integrate
  {
    name: 'scipy.integrate',
    lang: 'python',
    kind: 'module',
    official: 'Integration and ODEs',
    source: 'SciPy docstring',
    when: 'You need to add up the area under a curve or step a differential equation (a rule for how something changes) forward in time. In ORBIT you mostly import solve_ivp from it.',
    example: { command: 'from scipy.integrate import solve_ivp', says: 'Brings in SciPy\'s differential-equation solver so you can call it as solve_ivp.' },
    seeAlso: ['scipy.integrate.solve_ivp'],
  },
  {
    name: 'scipy.integrate.solve_ivp',
    aliases: ['solve_ivp'],
    lang: 'python',
    kind: 'function',
    official: 'Solve an initial value problem for a system of ODEs.',
    source: 'SciPy docstring',
    when: 'You know where something starts and a function that gives its rate of change, like an orbit\'s velocity and acceleration, and you want its whole path over time. Your function must take (t, y) in that order, and the default tolerances are loose, so set rtol and atol for anything that matters. The answer is in sol.t and sol.y, with one row of sol.y per state.',
    flags: [
      ['fun', 'your function f(t, y) that returns the rates of change'],
      ['t_span', 'the start and end time, as a pair like (0.0, 600.0)'],
      ['y0', 'the starting state, a list or array'],
      ['method=', 'which solver to use, such as "RK45" (the default), "DOP853" or "Radau"'],
      ['rtol= / atol=', 'relative and absolute error limits; smaller is more accurate but slower'],
      ['args=', 'extra values passed on to your function, as a tuple like (MU,)'],
      ['t_eval=', 'the exact times you want the answer at'],
      ['events=', 'functions that stop or mark the run when they cross zero, such as hitting the ground'],
      ['dense_output=', 'True to get sol.sol, a function you can ask for the state at any time'],
      ['max_step=', 'the largest time step the solver may take'],
    ],
    example: {
      command: 'sol = solve_ivp(lambda t, y: -y, (0.0, 1.0), [1.0], rtol=1e-10, atol=1e-12)\nprint(round(sol.y[0, -1], 6))',
      says: 'Solves y\' = -y from y = 1 and prints 0.367879, the value at t = 1 (that is e to the minus 1).',
    },
    seeAlso: ['scipy.integrate', 'numpy.linspace'],
  },

  // ---------------------------------------------------------------- scipy.interpolate
  {
    name: 'scipy.interpolate',
    lang: 'python',
    kind: 'module',
    official: 'Sub-package for functions and objects used in interpolation.',
    source: 'SciPy docstring',
    when: 'You have a table of measured points, like drag against Mach number or thrust against time, and need values between them. Each tool here builds a function once from the table that you then call as often as you like.',
    example: { command: 'from scipy.interpolate import CubicSpline, PchipInterpolator', says: 'Brings in two ways of drawing a smooth curve through table points.' },
    seeAlso: ['scipy.interpolate.interp1d', 'scipy.interpolate.CubicSpline', 'numpy.interp'],
  },
  {
    name: 'scipy.interpolate.CubicSpline',
    aliases: ['CubicSpline'],
    lang: 'python',
    kind: 'class',
    official: 'Piecewise cubic interpolator to fit values (C2 smooth).',
    source: 'SciPy docstring',
    when: 'You want a smooth curve through table points, with no sudden bends, for example a drag table you will differentiate. It can overshoot, bulging above the highest point near sharp changes, and outside the table it keeps the last cubic going, which can give wild values. Build it once, not on every call.',
    flags: [
      ['x', 'the table\'s input values, in increasing order'],
      ['y', 'the table\'s output values, one for each x'],
    ],
    example: {
      command: 'cs = CubicSpline([0.5, 1.0, 1.5, 2.0], [0.30, 0.55, 0.45, 0.35])\nprint(round(float(cs(1.2)), 3))',
      says: 'Builds a smooth drag curve through four Mach points and prints 0.532, the drag coefficient at Mach 1.2.',
    },
    seeAlso: ['scipy.interpolate.PchipInterpolator', 'scipy.interpolate.interp1d'],
  },
  {
    name: 'scipy.interpolate.PchipInterpolator',
    aliases: ['PchipInterpolator'],
    lang: 'python',
    kind: 'class',
    official: 'PCHIP shape-preserving interpolator (C1 smooth).',
    source: 'SciPy docstring',
    when: 'You want a smooth curve that never overshoots the data, such as a thrust curve that must not go above its peak or below zero. It is a little less smooth than CubicSpline, which is the price of never bulging.',
    flags: [
      ['x', 'the table\'s input values, in increasing order'],
      ['y', 'the table\'s output values, one for each x'],
    ],
    example: {
      command: 'pc = PchipInterpolator([0, 1, 2, 3], [0.0, 900.0, 900.0, 0.0])\nprint(float(pc(1.5)))',
      says: 'Prints 900.0: the flat top of the thrust curve stays flat. A CubicSpline through the same points gives 1012.5 there.',
    },
    seeAlso: ['scipy.interpolate.CubicSpline'],
  },
  {
    name: 'scipy.interpolate.RegularGridInterpolator',
    aliases: ['RegularGridInterpolator'],
    lang: 'python',
    kind: 'class',
    official: 'Interpolator of specified order on a rectilinear grid in N ≥ 1 dimensions.',
    source: 'SciPy docstring',
    when: 'Your table depends on two or more inputs, like an aero coefficient over Mach and angle of attack. You pass the grid as a tuple of axes, even for one axis, and ask for points as rows like [[mach, alpha]]; a point outside the grid raises an error by default.',
    flags: [
      ['points', 'a tuple of the grid axes, such as (mach, alpha)'],
      ['values', 'the table, with one dimension per axis'],
    ],
    example: {
      command: 'cn_of = RegularGridInterpolator((mach, alpha), cn)\nprint(cn_of([[1.2, 4.0]]))',
      says: 'Prints a one-value array: the normal-force coefficient at Mach 1.2 and 4 degrees, blended from the nearest grid points.',
    },
    seeAlso: ['scipy.interpolate.interp1d'],
  },
  {
    name: 'scipy.interpolate.interp1d',
    aliases: ['interp1d'],
    lang: 'python',
    kind: 'class',
    official: 'Interpolate a 1-D function (legacy).',
    source: 'SciPy docstring',
    when: 'You want straight-line interpolation in a one-input table and a function you can call later. By default asking for a value outside the table raises ValueError; "legacy" means SciPy keeps it working but suggests newer tools for new code.',
    flags: [
      ['x, y', 'the table\'s inputs and outputs'],
      ['bounds_error=', 'False to stop it raising an error outside the table'],
      ['fill_value=', 'what to give outside the table: a pair (low, high) to hold the end values, or "extrapolate" to extend the end lines'],
    ],
    example: {
      command: 'cd_of = interp1d([0.5, 1.0, 2.0], [0.30, 0.50, 0.40])\nprint(float(cd_of(1.5)))',
      says: 'Prints 0.45, halfway between the table values at Mach 1.0 and 2.0.',
    },
    seeAlso: ['numpy.interp', 'scipy.interpolate.CubicSpline'],
  },

  // ---------------------------------------------------------------- scipy.linalg
  {
    name: 'scipy.linalg',
    aliases: ['linalg'],
    lang: 'python',
    kind: 'module',
    official: 'Linear algebra functions.',
    source: 'SciPy docstring',
    when: 'You are working with matrices: solving systems of equations, factoring, matrix exponentials, Riccati equations for controllers. It covers everything in numpy.linalg and more, and some functions with the same name behave slightly differently.',
    example: { command: 'from scipy import linalg\nprint(linalg.det(A))', says: 'Brings in SciPy\'s linear algebra tools and prints the determinant of A.' },
    seeAlso: ['numpy.linalg', 'scipy.linalg.solve'],
  },
  {
    name: 'scipy.linalg.LinAlgError',
    aliases: ['linalg.LinAlgError'],
    lang: 'python',
    kind: 'exception',
    official: 'Generic Python-exception-derived object raised by linalg functions.',
    source: 'SciPy docstring',
    when: 'A matrix operation cannot be done, for example a Cholesky factorization of a matrix that is not positive definite, or inverting a singular matrix. Catch it to handle a bad covariance matrix instead of crashing.',
    example: {
      command: 'try:\n    L = linalg.cholesky(P)\nexcept linalg.LinAlgError:\n    print("covariance is not positive definite")',
      says: 'Prints the message instead of crashing when P cannot be factored.',
    },
    seeAlso: ['scipy.linalg.cholesky', 'try'],
  },
  {
    name: 'scipy.linalg.cho_factor',
    aliases: ['cho_factor'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the Cholesky decomposition of a matrix, to use in cho_solve',
    source: 'SciPy docstring',
    when: 'You will solve A x = b for a symmetric positive-definite A, like a covariance matrix, possibly with many different b. Factor once, then reuse the result; what it returns is meant only for cho_solve, since the unused half of the matrix holds leftover numbers.',
    example: {
      command: 'c = cho_factor(A)\nx = cho_solve(c, b)',
      says: 'Factors A once and then solves A x = b using the factor.',
    },
    seeAlso: ['scipy.linalg.cho_solve', 'scipy.linalg.cholesky'],
  },
  {
    name: 'scipy.linalg.cho_solve',
    aliases: ['cho_solve'],
    lang: 'python',
    kind: 'function',
    official: 'Solve the linear equations A x = b, given the Cholesky factorization of A.',
    source: 'SciPy docstring',
    when: 'You already have cho_factor(A) and want x for A x = b, fast and without forming an inverse. The first argument is the whole pair cho_factor returned, not just the matrix.',
    example: {
      command: 'x = cho_solve(cho_factor(A), b)',
      says: 'With A = [[4, 2], [2, 3]] and b = [2, 1], gives x = [0.5, 0.0].',
    },
    seeAlso: ['scipy.linalg.cho_factor', 'scipy.linalg.solve'],
  },
  {
    name: 'scipy.linalg.cholesky',
    aliases: ['linalg.cholesky'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the Cholesky decomposition of a matrix.',
    source: 'SciPy docstring',
    when: 'You need the "square root" L of a covariance matrix, with L times its transpose giving back the matrix, for example to draw correlated random samples. By default it returns the upper triangle, unlike numpy.linalg.cholesky, so pass lower=True for L. It raises LinAlgError if the matrix is not positive definite.',
    flags: [['lower=', 'True for the lower-triangular factor L; the default False gives the upper one']],
    example: {
      command: 'L = linalg.cholesky(np.array([[4.0, 2.0], [2.0, 3.0]]), lower=True)',
      says: 'Gives L = [[2, 0], [1, 1.414]], and L @ L.T is the original matrix.',
    },
    seeAlso: ['scipy.linalg.cho_factor', 'scipy.linalg.LinAlgError', 'numpy.linalg.cholesky'],
  },
  {
    name: 'scipy.linalg.det',
    aliases: ['linalg.det'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the determinant of a matrix',
    source: 'SciPy docstring',
    when: 'You want one number that says how a square matrix scales areas or volumes; zero means the matrix cannot be inverted. Rounding makes a nearly singular matrix give a tiny number instead of exactly 0, so do not test it with == 0.',
    example: { command: 'print(linalg.det(np.array([[2.0, 1.0], [1.0, 3.0]])))', says: 'Prints 5.0.' },
    seeAlso: ['numpy.linalg.det', 'scipy.linalg.inv'],
  },
  {
    name: 'scipy.linalg.eigvals',
    aliases: ['linalg.eigvals'],
    lang: 'python',
    kind: 'function',
    official: 'Compute eigenvalues from an ordinary or generalized eigenvalue problem.',
    source: 'SciPy docstring',
    when: 'You want to know if a system settles or blows up: for a continuous system every eigenvalue of A - B K needs a negative real part. The answers always come back as complex numbers, even when they are real, so look at .real.',
    example: {
      command: 'print(linalg.eigvals(np.array([[0.0, 1.0], [-2.0, -3.0]])))',
      says: 'Prints [-1.+0.j -2.+0.j]: both negative, so this system settles.',
    },
    seeAlso: ['numpy.linalg.eig', 'scipy.linalg.solve_continuous_are'],
  },
  {
    name: 'scipy.linalg.expm',
    aliases: ['expm', 'linalg.expm'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the matrix exponential of an array.',
    source: 'SciPy docstring',
    when: 'You need the state transition matrix of a linear system, e to the (A times dt), which carries the state forward one time step exactly. Do not use np.exp for this: that takes e to the power of each entry separately and gives a different, wrong matrix.',
    example: {
      command: 'Phi = linalg.expm(np.array([[0.0, 1.0], [0.0, 0.0]]) * 0.5)',
      says: 'Gives [[1, 0.5], [0, 1]]: position gains 0.5 times velocity over half a second.',
    },
    seeAlso: ['numpy.exp', 'scipy.signal.cont2discrete'],
  },
  {
    name: 'scipy.linalg.inv',
    aliases: ['linalg.inv'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the inverse of a matrix.',
    source: 'SciPy docstring',
    when: 'You truly need the inverse matrix itself. To solve A x = b, use solve instead: it is faster and more accurate than inv(A) @ b.',
    example: { command: 'print(np.allclose(A @ linalg.inv(A), np.eye(2)))', says: 'Prints True: A times its inverse is the identity matrix, up to rounding.' },
    seeAlso: ['scipy.linalg.solve', 'numpy.linalg.inv'],
  },
  {
    name: 'scipy.linalg.qr',
    aliases: ['linalg.qr'],
    lang: 'python',
    kind: 'function',
    official: 'Compute QR decomposition of a matrix.',
    source: 'SciPy docstring',
    when: 'You are solving a least-squares fit and want an accurate answer: write A as Q times R, then solve the small triangular system R x = Q.T b. The default gives a full square Q; for a tall matrix you usually want mode="economic".',
    flags: [['mode=', '"economic" for the thin Q and small square R, instead of the full square Q']],
    example: {
      command: 'Q, R = linalg.qr(A, mode="economic")',
      says: 'For a 101 by 7 matrix A, gives Q as 101 by 7 and R as 7 by 7.',
    },
    seeAlso: ['scipy.linalg.solve_triangular', 'numpy.linalg.lstsq'],
  },
  {
    name: 'scipy.linalg.solve',
    aliases: ['linalg.solve', 'solve'],
    lang: 'python',
    kind: 'function',
    official: 'Solve the equation ``a @ x = b`` for ``x``, where `a` is a square matrix.',
    source: 'SciPy docstring',
    when: 'You have a square system of equations A x = b and want x. It is the right tool instead of computing the inverse; it raises LinAlgError if A is singular.',
    flags: [['assume_a=', 'tell it the matrix type, such as "pos" for symmetric positive definite, so it can use a faster method']],
    example: {
      command: 'print(linalg.solve(np.array([[2.0, 1.0], [1.0, 3.0]]), [5.0, 10.0]))',
      says: 'Prints [1. 3.], since 2*1 + 3 = 5 and 1 + 3*3 = 10.',
    },
    seeAlso: ['numpy.linalg.solve', 'scipy.linalg.inv', 'scipy.linalg.cho_solve'],
  },
  {
    name: 'scipy.linalg.solve_continuous_are',
    aliases: ['solve_continuous_are', 'linalg.solve_continuous_are'],
    lang: 'python',
    kind: 'function',
    official: 'Solves the continuous-time algebraic Riccati equation (CARE).',
    source: 'SciPy docstring',
    when: 'You are designing an LQR controller (a feedback gain that balances error against effort) for a continuous-time system. It returns the matrix P, not the gain, so you still compute K from P; it is slow, so compute it once rather than every step.',
    flags: [
      ['A, B', 'the system and input matrices'],
      ['Q, R', 'weights: how much you care about state error and about control effort'],
    ],
    example: {
      command: 'P = linalg.solve_continuous_are(A, B, Q, R)\nK = np.linalg.solve(R, B.T @ P)',
      says: 'Solves for P, then turns it into the LQR gain K, so the control law is u = -K x.',
    },
    seeAlso: ['scipy.linalg.solve_discrete_are', 'scipy.linalg.eigvals'],
  },
  {
    name: 'scipy.linalg.solve_discrete_are',
    aliases: ['solve_discrete_are', 'linalg.solve_discrete_are'],
    lang: 'python',
    kind: 'function',
    official: 'Solves the discrete-time algebraic Riccati equation (DARE).',
    source: 'SciPy docstring',
    when: 'You need a steady-state gain for a system that updates in fixed time steps: a discrete LQR controller, or the settled Kalman filter covariance. For the Kalman filter case you pass the transposes F.T and H.T, which is easy to forget.',
    flags: [
      ['A, B', 'the discrete system and input matrices (F.T and H.T for a Kalman filter)'],
      ['Q, R', 'the weights, or the process and measurement noise for a Kalman filter'],
    ],
    example: {
      command: 'P_ss = solve_discrete_are(F.T, H.T, Q, R)',
      says: 'Gives the covariance the Kalman filter settles to after running for a long time.',
    },
    seeAlso: ['scipy.linalg.solve_continuous_are'],
  },
  {
    name: 'scipy.linalg.solve_triangular',
    aliases: ['solve_triangular', 'linalg.solve_triangular'],
    lang: 'python',
    kind: 'function',
    official: 'Solve the equation ``a @ x = b`` for ``x``, where `a` is a triangular matrix.',
    source: 'SciPy docstring',
    when: 'Your matrix is triangular, such as a Cholesky factor L or the R from QR, so the system can be solved quickly by substitution. It assumes upper triangular by default, so pass lower=True for L; it does not check, and quietly uses the wrong half if you forget.',
    flags: [['lower=', 'True if the matrix is lower triangular; the default is upper']],
    example: {
      command: 'y = solve_triangular(L, b, lower=True)\nx = solve_triangular(L.T, y, lower=False)',
      says: 'Solves forward through L, then back through its transpose, giving x for (L L.T) x = b.',
    },
    seeAlso: ['scipy.linalg.cholesky', 'scipy.linalg.qr'],
  },

  // ---------------------------------------------------------------- scipy.ndimage
  {
    name: 'scipy.ndimage',
    lang: 'python',
    kind: 'module',
    official: 'This package contains various functions for multidimensional image processing.',
    source: 'SciPy docstring',
    when: 'You are treating an array as an image, such as a camera frame of the Moon\'s surface, and want to blur it, find peaks or move it. Its functions work on NumPy arrays of any number of dimensions.',
    example: { command: 'from scipy.ndimage import gaussian_filter, maximum_filter', says: 'Brings in a blur and a local-maximum filter for image arrays.' },
    seeAlso: ['scipy.ndimage.gaussian_filter'],
  },
  {
    name: 'scipy.ndimage.gaussian_filter',
    aliases: ['gaussian_filter'],
    lang: 'python',
    kind: 'function',
    official: 'Multidimensional Gaussian filter.',
    source: 'SciPy docstring',
    when: 'You want to smooth an image, averaging each pixel with its neighbors so noise fades, as in a corner detector. sigma is measured in pixels, so a bigger sigma blurs more; integer arrays come back as integers, so convert to float first.',
    flags: [['sigma', 'how wide the blur is, in pixels']],
    example: { command: 'Ixx = gaussian_filter(Ix * Ix, 1.5)', says: 'Blurs the squared image gradient over about a 1.5-pixel radius.' },
    seeAlso: ['scipy.ndimage.maximum_filter'],
  },
  {
    name: 'scipy.ndimage.maximum_filter',
    aliases: ['maximum_filter'],
    lang: 'python',
    kind: 'function',
    official: 'Calculate a multidimensional maximum filter.',
    source: 'SciPy docstring',
    when: 'You want the peaks of an image, such as the strongest corners: replace each pixel with the largest value near it, and the pixels that did not change are local maxima. Flat areas also count as "unchanged", so add a threshold.',
    flags: [['size=', 'the width of the square neighborhood, in pixels']],
    example: {
      command: 'peaks = (R == maximum_filter(R, size=5)) & (R > thresh)',
      says: 'Marks True where R is the biggest value in its 5 by 5 patch and also above the threshold.',
    },
    seeAlso: ['scipy.ndimage.gaussian_filter'],
  },
  {
    name: 'scipy.ndimage.shift',
    aliases: ['ndshift'],
    lang: 'python',
    kind: 'function',
    official: 'Shift an array.',
    source: 'SciPy docstring',
    when: 'You want to slide an image by a known number of pixels, even a fraction, to test an image-matching routine. The shift is given as (rows, columns), which is (y, x), not (x, y); lessons import it as ndshift so it does not clash with other names.',
    flags: [
      ['shift', 'how far to move along each axis, as (rows, columns)'],
      ['order=', 'how to fill in between pixels: 1 for straight-line blending, 3 (the default) for smooth curves'],
      ['mode=', 'how to fill the edge that is uncovered, such as "nearest" to copy the edge pixels'],
    ],
    example: {
      command: 'img2 = ndshift(img, (2.0, -3.5), order=1, mode="nearest")',
      says: 'Moves the image down 2 rows and left 3.5 columns, filling the uncovered edge with copies of the nearest edge pixels.',
    },
    seeAlso: ['numpy.roll'],
  },

  // ---------------------------------------------------------------- scipy.optimize
  {
    name: 'scipy.optimize',
    lang: 'python',
    kind: 'module',
    official: 'SciPy ``optimize`` provides functions for minimizing (or maximizing) objective functions, possibly subject to constraints.',
    source: 'SciPy docstring',
    when: 'You need to find where a function is zero, where it is smallest, or which model parameters best fit your data. To maximize something, minimize its negative.',
    example: { command: 'from scipy.optimize import brentq, minimize', says: 'Brings in a root finder and a general minimizer.' },
    seeAlso: ['scipy.optimize.minimize', 'scipy.optimize.brentq'],
  },
  {
    name: 'scipy.optimize.NonlinearConstraint',
    aliases: ['NonlinearConstraint'],
    lang: 'python',
    kind: 'class',
    official: 'Nonlinear constraint on the variables.',
    source: 'SciPy docstring',
    when: 'You are minimizing something but the answer must also meet a rule, such as the missile ending exactly on the target line. Setting the lower and upper bounds equal makes it an equality: the value must be exactly that number.',
    flags: [
      ['fun', 'a function of the variables that the rule is about'],
      ['lb, ub', 'the lowest and highest values fun is allowed to take'],
    ],
    example: {
      command: 'res = minimize(effort, u0, constraints=[NonlinearConstraint(terminal_y, 0.0, 0.0)])',
      says: 'Finds the least-effort controls u whose terminal_y(u) comes out exactly 0.',
    },
    seeAlso: ['scipy.optimize.minimize'],
  },
  {
    name: 'scipy.optimize.brentq',
    aliases: ['brentq'],
    lang: 'python',
    kind: 'function',
    official: "Find a root of a function in a bracketing interval using Brent's method.",
    source: 'SciPy docstring',
    when: 'You want where a function of one number crosses zero, and you know two points on either side of it. It always converges if f(a) and f(b) have opposite signs; if they have the same sign it raises ValueError instead of guessing.',
    flags: [
      ['f, a, b', 'the function and the two ends of the bracket'],
      ['args=', 'extra values passed on to f, as a tuple'],
      ['xtol= / rtol=', 'how close the answer must be'],
      ['full_output=', 'True to also get an info object with the number of iterations'],
    ],
    example: {
      command: 'print(round(brentq(lambda x: x**2 - 2, 0.0, 2.0), 6))',
      says: 'Prints 1.414214, the square root of 2, found between 0 and 2.',
    },
    seeAlso: ['scipy.optimize.newton', 'scipy.optimize.root'],
  },
  {
    name: 'scipy.optimize.curve_fit',
    aliases: ['curve_fit'],
    lang: 'python',
    kind: 'function',
    official: 'Use non-linear least squares to fit a function, f, to data.',
    source: 'SciPy docstring',
    when: 'You have measurements and a model formula with unknown numbers in it, and want the numbers that fit best. Your model must take x first and the parameters after it; give a starting guess with p0, because the default of all ones can land on a poor fit.',
    flags: [
      ['f', 'your model, f(x, a, b, ...)'],
      ['xdata, ydata', 'the measurements'],
      ['p0=', 'your starting guess for the parameters'],
    ],
    example: {
      command: 'popt, pcov = curve_fit(model, t, p, p0=[300.0, 2460.0])',
      says: 'popt holds the best-fit parameters; the square roots of the diagonal of pcov are their one-sigma uncertainties.',
    },
    seeAlso: ['scipy.optimize.least_squares', 'numpy.polyfit'],
  },
  {
    name: 'scipy.optimize.least_squares',
    aliases: ['least_squares'],
    lang: 'python',
    kind: 'function',
    official: 'Solve a nonlinear least-squares problem with bounds on the variables.',
    source: 'SciPy docstring',
    when: 'You want parameters that make a list of errors (residuals) as small as possible, with more control than curve_fit, such as limits on each parameter. Your function returns the residuals themselves, not their squared sum.',
    flags: [
      ['fun', 'a function returning the array of residuals'],
      ['x0', 'the starting guess'],
      ['bounds=', 'lowest and highest allowed values, as (lower, upper)'],
    ],
    example: {
      command: 'sol = least_squares(residuals, x0=[300.0, 2460.0])\nprint(sol.x)',
      says: 'Prints the parameters that best fit the data.',
    },
    seeAlso: ['scipy.optimize.curve_fit', 'scipy.optimize.minimize'],
  },
  {
    name: 'scipy.optimize.minimize',
    aliases: ['minimize'],
    lang: 'python',
    kind: 'function',
    official: 'Minimization of scalar function of one or more variables.',
    source: 'SciPy docstring',
    when: 'You want the inputs that make a single number (a cost) as small as possible. It finds a nearby low point, not always the lowest, and x is always an array even for one variable, so write x[0]. Check res.success before trusting res.x.',
    flags: [
      ['fun', 'the cost function, taking an array x'],
      ['x0=', 'the starting guess'],
      ['method=', 'which algorithm, such as "Nelder-Mead" (needs no derivatives) or "SLSQP"'],
      ['constraints=', 'rules the answer must satisfy'],
      ['options=', 'extra settings as a dict, such as {"maxiter": 500}'],
    ],
    example: {
      command: 'res = minimize(lambda x: (x[0] - 3.0)**2 + 1.0, x0=[0.0])\nprint(round(res.x[0], 4), round(res.fun, 4))',
      says: 'Prints 3.0 1.0: the lowest point is at x = 3, where the cost is 1.',
    },
    seeAlso: ['scipy.optimize.least_squares', 'scipy.optimize.NonlinearConstraint'],
  },
  {
    name: 'scipy.optimize.newton',
    aliases: ['newton'],
    lang: 'python',
    kind: 'function',
    official: "Find a root of a real or complex function using the Newton-Raphson (or secant or Halley's) method.",
    source: 'SciPy docstring',
    when: 'You want a root fast and have a good starting guess, as when solving Kepler\'s equation for an orbit. Give fprime (the derivative) for Newton\'s method; without it, it uses the slower secant method. From a bad guess it can wander off or fail, unlike brentq.',
    flags: [
      ['func, x0', 'the function and the starting guess'],
      ['fprime=', 'the derivative of the function'],
      ['tol=', 'how close the answer must be'],
      ['full_output=', 'True to also get info on how it converged'],
    ],
    example: {
      command: 'E = newton(lambda E: E - 0.1*np.sin(E) - 1.0, 1.0, fprime=lambda E: 1 - 0.1*np.cos(E))',
      says: 'Solves Kepler\'s equation for eccentricity 0.1 and mean anomaly 1.0, giving E = 1.088598.',
    },
    seeAlso: ['scipy.optimize.brentq', 'scipy.optimize.root'],
  },
  {
    name: 'scipy.optimize.root',
    aliases: ['root'],
    lang: 'python',
    kind: 'function',
    official: 'Find a root of a vector function.',
    source: 'SciPy docstring',
    when: 'You have several equations in several unknowns and want the values that make them all zero at once, like a position from two range measurements. Different starting guesses can find different answers, and you should check sol.success.',
    flags: [
      ['fun', 'a function returning one residual per equation'],
      ['x0=', 'the starting guess, one value per unknown'],
      ['args=', 'extra values passed on to fun, as a tuple'],
    ],
    example: {
      command: 'sol = root(lambda v, s, p: [v[0] + v[1] - s, v[0] * v[1] - p], x0=[4.0, 1.0], args=(7.0, 10.0))',
      says: 'Finds two numbers that add to 7 and multiply to 10: sol.x is [5. 2.] and sol.success is True.',
    },
    seeAlso: ['scipy.optimize.brentq', 'scipy.optimize.newton'],
  },

  // ---------------------------------------------------------------- scipy.signal
  {
    name: 'scipy.signal',
    lang: 'python',
    kind: 'module',
    official: 'Signal processing',
    source: 'SciPy docstring',
    when: 'You are filtering sensor data, looking at its frequencies, or describing a control system with transfer functions. It has nothing to do with Python\'s built-in signal module for operating-system signals, which is why lessons write from scipy import signal.',
    example: { command: 'from scipy import signal', says: 'Brings in SciPy\'s signal tools so you can call signal.butter, signal.bode and the rest.' },
    seeAlso: ['scipy.signal.butter', 'scipy.signal.TransferFunction'],
  },
  {
    name: 'scipy.signal.TransferFunction',
    aliases: ['signal.TransferFunction'],
    lang: 'python',
    kind: 'class',
    official: 'Linear Time Invariant system class in transfer function form.',
    source: 'SciPy docstring',
    when: 'You want to describe a linear system by its transfer function, a fraction of two polynomials in s, and then plot or simulate it. The coefficients go highest power first, so s^2 + 4s is [1, 4, 0], with the 0 for the missing constant.',
    flags: [
      ['num', 'the top polynomial\'s coefficients, highest power first'],
      ['den', 'the bottom polynomial\'s coefficients, highest power first'],
    ],
    example: {
      command: 'L = signal.TransferFunction([20.0], [1.0, 4.0, 0.0])',
      says: 'Makes the system 20 / (s^2 + 4 s), ready for signal.bode or signal.step.',
    },
    seeAlso: ['scipy.signal.bode', 'scipy.signal.step', 'scipy.signal.tf2ss'],
  },
  {
    name: 'scipy.signal.bode',
    aliases: ['signal.bode'],
    lang: 'python',
    kind: 'function',
    official: 'Calculate Bode magnitude and phase data of a continuous-time system.',
    source: 'SciPy docstring',
    when: 'You want to see how a system responds at each frequency, to judge stability margins. Frequencies are in radians per second, not hertz; the magnitude comes back in decibels and the phase in degrees.',
    flags: [
      ['system', 'a TransferFunction, or another linear system'],
      ['w', 'the frequencies to check, in rad/s; np.logspace gives an evenly spread log scale'],
    ],
    example: {
      command: 'w, mag_db, phase_deg = signal.bode(L, np.logspace(-1, 2, 2000))',
      says: 'Gives the gain in dB and phase in degrees at 2000 frequencies from 0.1 to 100 rad/s, ready to plot.',
    },
    seeAlso: ['scipy.signal.TransferFunction', 'scipy.signal.freqz'],
  },
  {
    name: 'scipy.signal.butter',
    aliases: ['signal.butter'],
    lang: 'python',
    kind: 'function',
    official: 'Butterworth digital and analog filter design.',
    source: 'SciPy docstring',
    when: 'You want a smooth low-pass filter to take noise out of sensor data. Always pass fs (the sample rate) so the cutoff is in hertz; without it the cutoff is read as a fraction of half the sample rate, a common mistake.',
    flags: [
      ['N', 'the filter order; higher cuts more sharply'],
      ['Wn', 'the cutoff frequency'],
      ['btype=', 'the kind: "low" (the default), "high", "bandpass" or "bandstop"'],
      ['fs=', 'the sample rate in hertz'],
    ],
    example: {
      command: 'b, a = signal.butter(4, 5.0, btype="low", fs=100.0)',
      says: 'Designs a 4th-order low-pass filter with a 5 Hz cutoff for data sampled at 100 Hz, as the coefficient arrays b and a.',
    },
    seeAlso: ['scipy.signal.filtfilt', 'scipy.signal.lfilter', 'scipy.signal.freqz'],
  },
  {
    name: 'scipy.signal.cont2discrete',
    aliases: ['signal.cont2discrete'],
    lang: 'python',
    kind: 'function',
    official: 'Transform a continuous to a discrete state-space system.',
    source: 'SciPy docstring',
    when: 'You designed something in continuous time and need the version that runs on a computer updating every T seconds. The method matters: "zoh" suits a plant driven by held commands, "bilinear" suits a controller, and they give different numbers.',
    flags: [
      ['system', 'the continuous system, such as (num, den)'],
      ['dt', 'the time step in seconds'],
      ['method=', 'how to convert: "zoh" (zero-order hold) or "bilinear" (Tustin)'],
    ],
    example: {
      command: 'num_d, den_d, dt = signal.cont2discrete(([1.0], [1.0, 0.0, 0.0]), 0.1, method="zoh")',
      says: 'Turns 1/s^2 into its 0.1 s version: num_d is [[0, 0.005, 0.005]] and den_d is [1, -2, 1].',
    },
    seeAlso: ['scipy.signal.TransferFunction', 'scipy.linalg.expm'],
  },
  {
    name: 'scipy.signal.filtfilt',
    aliases: ['signal.filtfilt'],
    lang: 'python',
    kind: 'function',
    official: 'Apply a digital filter forward and backward to a signal.',
    source: 'SciPy docstring',
    when: 'You are cleaning up recorded data after the flight and want no time lag. Because it runs backward too, it uses future samples, so it cannot run live on a flight computer; use lfilter for that.',
    flags: [
      ['b, a', 'the filter coefficients, such as from signal.butter'],
      ['x', 'the signal to filter'],
    ],
    example: { command: 'y_filt = signal.filtfilt(b, a, y_noisy)', says: 'Gives a smoothed copy of y_noisy with no delay against the original.' },
    seeAlso: ['scipy.signal.lfilter', 'scipy.signal.butter'],
  },
  {
    name: 'scipy.signal.freqz',
    aliases: ['signal.freqz'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the frequency response of a digital filter.',
    source: 'SciPy docstring',
    when: 'You want to check what a digital filter does at each frequency before trusting it. Pass fs so frequencies are in hertz; the response H is complex, so take np.abs(H) for the gain.',
    flags: [
      ['b, a', 'the filter coefficients'],
      ['worN=', 'how many frequencies to check, or a list of the exact ones'],
      ['fs=', 'the sample rate in hertz'],
    ],
    example: {
      command: 'f, H = signal.freqz(b, a, worN=[1.0, 5.0, 20.0], fs=100.0)\nprint(np.round(np.abs(H), 3))',
      says: 'For the 5 Hz Butterworth filter, prints [1. 0.707 0.002]: it passes 1 Hz, halves the power at 5 Hz and blocks 20 Hz.',
    },
    seeAlso: ['scipy.signal.butter', 'scipy.signal.bode'],
  },
  {
    name: 'scipy.signal.lfilter',
    aliases: ['signal.lfilter', 'lfilter'],
    lang: 'python',
    kind: 'function',
    official: 'Filter data along one-dimension with an IIR or FIR filter.',
    source: 'SciPy docstring',
    when: 'You want to filter data the way a flight computer would, using only past and present samples. That makes the output lag behind the input, which filtfilt avoids but only for recorded data.',
    flags: [
      ['b', 'the coefficients on the inputs'],
      ['a', 'the coefficients on past outputs, with a[0] usually 1'],
      ['x', 'the signal to filter'],
    ],
    example: {
      command: 'print(signal.lfilter([0.2], [1.0, -0.8], np.ones(5)))',
      says: 'Prints [0.2 0.36 0.488 0.5904 0.67232]: the output creeping up toward 1 after a step.',
    },
    seeAlso: ['scipy.signal.filtfilt', 'scipy.signal.butter'],
  },
  {
    name: 'scipy.signal.periodogram',
    aliases: ['signal.periodogram'],
    lang: 'python',
    kind: 'function',
    official: 'Estimate power spectral density using a periodogram.',
    source: 'SciPy docstring',
    when: 'You want to see which frequencies are strong in a signal, like a vibration tone in accelerometer data. It is quick but very noisy; welch gives a smoother estimate.',
    flags: [
      ['x', 'the signal'],
      ['fs=', 'the sample rate in hertz, so f comes out in hertz'],
    ],
    example: { command: 'f, P = signal.periodogram(x, fs=fs)', says: 'Gives the frequencies f and the power at each one, P, for the whole signal in one go.' },
    seeAlso: ['scipy.signal.welch'],
  },
  {
    name: 'scipy.signal.step',
    aliases: ['signal.step'],
    lang: 'python',
    kind: 'function',
    official: 'Step response of continuous-time system.',
    source: 'SciPy docstring',
    when: 'You want to see how a system reacts when its input jumps from 0 to 1, to read off overshoot and settling time. Pass T to choose the times, or it picks its own.',
    flags: [
      ['system', 'a TransferFunction, or another linear system'],
      ['T=', 'the times to compute the response at'],
    ],
    example: { command: 't_out, y = signal.step(sys, T=np.linspace(0, 5, 500))', says: 'Gives the system\'s output y over the first 5 seconds after a unit step.' },
    seeAlso: ['scipy.signal.TransferFunction'],
  },
  {
    name: 'scipy.signal.tf2ss',
    aliases: ['signal.tf2ss'],
    lang: 'python',
    kind: 'function',
    official: 'Transfer function to state-space representation.',
    source: 'SciPy docstring',
    when: 'You have a transfer function but need matrices A, B, C, D, for example to simulate it step by step. Many different matrices describe the same system, so do not expect to recognize the states as physical quantities.',
    flags: [
      ['num', 'the top polynomial\'s coefficients'],
      ['den', 'the bottom polynomial\'s coefficients'],
    ],
    example: {
      command: 'A, B, C, D = signal.tf2ss([100.0], [1.0, 2.0, 100.0])',
      says: 'Gives A = [[-2, -100], [1, 0]], B = [[1], [0]], C = [[0, 100]] and D = [[0]].',
    },
    seeAlso: ['scipy.signal.TransferFunction'],
  },
  {
    name: 'scipy.signal.welch',
    aliases: ['signal.welch'],
    lang: 'python',
    kind: 'function',
    official: "Estimate power spectral density using Welch's method.",
    source: 'SciPy docstring',
    when: 'You want a clean picture of a signal\'s frequencies, like the noise floor of an IMU. It averages many short pieces, so a smaller nperseg gives a smoother curve but less detail between frequencies.',
    flags: [
      ['x', 'the signal'],
      ['fs=', 'the sample rate in hertz'],
      ['nperseg=', 'how many samples in each piece that gets averaged'],
    ],
    example: {
      command: 'f, P = signal.welch(accel, fs=fs, nperseg=4096)',
      says: 'Gives a smoothed power spectrum of the accelerometer data, averaged over 4096-sample pieces.',
    },
    seeAlso: ['scipy.signal.periodogram'],
  },

  // ---------------------------------------------------------------- scipy.spatial.transform
  {
    name: 'scipy.spatial.transform',
    lang: 'python',
    kind: 'module',
    official: 'This package implements various spatial transformations.',
    source: 'SciPy docstring',
    when: 'You need to handle 3-D rotations: attitudes, Euler angles, quaternions, rotation matrices. Lessons import Rotation from it, renamed R.',
    example: { command: 'from scipy.spatial.transform import Rotation as R, Slerp', says: 'Brings in the Rotation class, called R from here on, and Slerp for blending rotations.' },
    seeAlso: ['scipy.spatial.transform.Rotation', 'scipy.spatial.transform.Slerp'],
  },
  {
    name: 'scipy.spatial.transform.Rotation',
    aliases: ['Rotation'],
    lang: 'python',
    kind: 'class',
    official: 'Rotation in 3 dimensions.',
    source: 'SciPy docstring',
    when: 'You want one object that holds an attitude and can turn it into any form: matrix, quaternion, Euler angles, rotation vector. You never call Rotation(...) directly; you build one with R.from_euler, R.from_quat and the other from_ methods.',
    example: {
      command: 'r = R.from_euler("z", 90, degrees=True)\nprint(np.round(r.apply([1.0, 0.0, 0.0]), 3))',
      says: 'Turns the x axis a quarter turn about z and prints [0. 1. 0.].',
    },
    seeAlso: ['scipy.spatial.transform.Rotation.from_euler', 'scipy.spatial.transform.Rotation.from_quat', 'scipy.spatial.transform.Slerp'],
  },
  {
    name: 'scipy.spatial.transform.Rotation.from_euler',
    aliases: ['R.from_euler', 'Rotation.from_euler'],
    lang: 'python',
    kind: 'method',
    official: 'Initialize from Euler angles.',
    source: 'SciPy docstring',
    when: 'Your attitude comes as angles, such as yaw, pitch and roll. Capital letters ("ZYX") turn about the body\'s own moving axes and lowercase ("xyz") about fixed axes, which gives a different rotation; the angles are radians unless you pass degrees=True.',
    flags: [
      ['seq', 'the axes in order, such as "ZYX" (moving axes) or "xyz" (fixed axes)'],
      ['angles', 'one angle per axis in seq'],
      ['degrees=', 'True if the angles are in degrees'],
    ],
    example: {
      command: 'att = R.from_euler("ZYX", [30, 10, 5], degrees=True)',
      says: 'Makes an attitude with 30 degrees of yaw, then 10 of pitch, then 5 of roll.',
    },
    seeAlso: ['scipy.spatial.transform.Rotation', 'scipy.spatial.transform.Rotation.from_quat'],
  },
  {
    name: 'scipy.spatial.transform.Rotation.from_matrix',
    aliases: ['R.from_matrix', 'Rotation.from_matrix'],
    lang: 'python',
    kind: 'method',
    official: 'Initialize from rotation matrix.',
    source: 'SciPy docstring',
    when: 'You have a 3 by 3 rotation matrix, for example from multiplying small steps together, and want to read it as angles or a rotation vector. A matrix that has drifted slightly from a true rotation is quietly corrected to the nearest one.',
    flags: [['matrix', 'a 3 by 3 rotation matrix, or a stack of them']],
    example: { command: 'print(R.from_matrix(np.eye(3)).magnitude())', says: 'Prints 0.0: the identity matrix is no rotation at all.' },
    seeAlso: ['scipy.spatial.transform.Rotation'],
  },
  {
    name: 'scipy.spatial.transform.Rotation.from_quat',
    aliases: ['R.from_quat', 'Rotation.from_quat'],
    lang: 'python',
    kind: 'method',
    official: 'Initialize from quaternions.',
    source: 'SciPy docstring',
    when: 'Your attitude comes as a quaternion, four numbers. SciPy expects the order x, y, z, w (scalar last) unless you pass scalar_first=True; many flight systems store w first, and reading those numbers the wrong way gives a completely wrong attitude without any error.',
    flags: [
      ['quat', 'the four quaternion numbers'],
      ['scalar_first=', 'True if the numbers are in the order w, x, y, z'],
    ],
    example: {
      command: 'att = R.from_quat(q_wxyz, scalar_first=True)',
      says: 'Reads a quaternion stored as w, x, y, z into a Rotation correctly.',
    },
    seeAlso: ['scipy.spatial.transform.Rotation', 'scipy.spatial.transform.Rotation.identity'],
  },
  {
    name: 'scipy.spatial.transform.Rotation.from_rotvec',
    aliases: ['R.from_rotvec', 'Rotation.from_rotvec'],
    lang: 'python',
    kind: 'method',
    official: 'Initialize from rotation vectors.',
    source: 'SciPy docstring',
    when: 'You have a rotation as one vector: its direction is the axis and its length is the angle in radians, such as a gyro\'s summed angle over a time step.',
    flags: [['rotvec', 'the rotation vector, length in radians']],
    example: {
      command: 'R.from_rotvec([0.0, 0.0, np.pi / 2]).as_matrix()',
      says: 'Gives the matrix for a quarter turn about z: [[0, -1, 0], [1, 0, 0], [0, 0, 1]].',
    },
    seeAlso: ['scipy.spatial.transform.Rotation'],
  },
  {
    name: 'scipy.spatial.transform.Rotation.identity',
    aliases: ['R.identity', 'Rotation.identity'],
    lang: 'python',
    kind: 'method',
    official: 'Get identity rotation(s).',
    source: 'SciPy docstring',
    when: 'You need a starting attitude of "no rotation at all", for example at the start of a simulation.',
    example: { command: 'q0 = R.identity().as_quat()', says: 'Gives [0. 0. 0. 1.], the no-rotation quaternion in SciPy\'s x, y, z, w order.' },
    seeAlso: ['scipy.spatial.transform.Rotation'],
  },
  {
    name: 'scipy.spatial.transform.Slerp',
    aliases: ['Slerp'],
    lang: 'python',
    kind: 'class',
    official: 'Spherical Linear Interpolation of Rotations.',
    source: 'SciPy docstring',
    when: 'You know the attitude at a few times and want it smoothly in between, turning at a steady rate. Averaging quaternion numbers directly does not do this correctly. You can only ask for times between the first and last key.',
    flags: [
      ['times', 'the times of the known attitudes, in increasing order'],
      ['rotations', 'one Rotation holding the known attitudes'],
    ],
    example: {
      command: 'keys = R.from_euler("z", [[0], [90]], degrees=True)\nslerp = Slerp([0.0, 2.0], keys)',
      says: 'slerp([1.0]) then gives the attitude at t = 1 s: 45 degrees about z, exactly halfway.',
    },
    seeAlso: ['scipy.spatial.transform.Rotation'],
  },

  // ---------------------------------------------------------------- scipy.special
  {
    name: 'scipy.special',
    lang: 'python',
    kind: 'module',
    official: 'Special functions',
    source: 'SciPy docstring',
    when: 'You need a named math function that plain NumPy does not have, such as the error function or Bessel functions. Almost all of them work on whole arrays at once.',
    example: { command: 'from scipy.special import erf', says: 'Brings in the error function.' },
    seeAlso: ['scipy.special.erf'],
  },
  {
    name: 'scipy.special.erf',
    aliases: ['erf'],
    lang: 'python',
    kind: 'function',
    official: 'Returns the error function of complex argument.',
    source: 'SciPy docstring',
    when: 'You need the error function, which shows up in the normal distribution and in heat and diffusion problems. It works on whole arrays, but Numba cannot compile a call to it inside a jit function.',
    example: { command: 'print(round(float(erf(1.0)), 4))', says: 'Prints 0.8427.' },
    seeAlso: ['scipy.stats.norm.cdf'],
  },

  // ---------------------------------------------------------------- scipy.stats
  {
    name: 'scipy.stats',
    aliases: ['stats'],
    lang: 'python',
    kind: 'module',
    official: 'This module contains a large number of probability distributions, summary and frequency statistics, correlation functions and statistical tests, masked statistics, kernel density estimation, quasi-Monte Carlo functionality, and more.',
    source: 'SciPy docstring',
    when: 'You need probability distributions (normal, chi-squared, beta and others) or statistics on Monte Carlo results. Every distribution has the same methods: pdf, cdf, ppf, sf, rvs and fit.',
    example: { command: 'from scipy import stats\nprint(round(stats.norm.cdf(3.0), 5))', says: 'Prints 0.99865, the chance a normal value is below 3 sigma.' },
    seeAlso: ['scipy.stats.norm', 'numpy.random.default_rng'],
  },
  {
    name: 'scipy.stats.beta',
    aliases: ['stats.beta'],
    lang: 'python',
    kind: 'function',
    official: 'A beta continuous random variable.',
    source: 'SciPy docstring',
    when: 'You are describing an unknown probability, a number between 0 and 1, such as the true failure rate behind a Monte Carlo campaign. Its two shape numbers come from counts: failures + 1 and successes.',
    flags: [['a, b', 'the two shape parameters']],
    example: {
      command: 'print(round(stats.beta.ppf(0.95, 1, 1000), 4))',
      says: 'Prints 0.003: after 1000 good runs and no bad ones, you can say with 95% confidence the failure rate is below 0.3%.',
    },
    seeAlso: ['scipy.stats.beta.ppf', 'scipy.stats.binom'],
  },
  {
    name: 'scipy.stats.beta.ppf',
    aliases: ['stats.beta.ppf', 'beta.ppf'],
    lang: 'python',
    kind: 'method',
    official: 'Percent point function (inverse of `cdf`) at q of the given RV.',
    source: 'SciPy docstring',
    when: 'You want an upper confidence bound on a failure rate from k failures in n runs. The shape numbers are k + 1 and n - k, which breaks when k equals n, so handle that case separately.',
    flags: [
      ['q', 'the confidence level, such as 0.95'],
      ['a, b', 'the shape parameters, k + 1 and n - k'],
    ],
    example: {
      command: 'upper = stats.beta.ppf(0.95, k + 1, n - k)',
      says: 'Gives the 95% upper bound on the true failure rate after k failures in n runs.',
    },
    seeAlso: ['scipy.stats.beta', 'scipy.stats.norm.ppf'],
  },
  {
    name: 'scipy.stats.binom',
    aliases: ['stats.binom'],
    lang: 'python',
    kind: 'function',
    official: 'A binomial discrete random variable.',
    source: 'SciPy docstring',
    when: 'You count how many of n independent tries come out one way, each with the same chance p, like failures in a batch of simulation runs. It only gives whole numbers of successes.',
    flags: [
      ['n', 'the number of tries'],
      ['p', 'the chance of the event on each try'],
    ],
    example: {
      command: 'print(round(stats.binom.cdf(1, 100, 0.01), 4))',
      says: 'Prints 0.7358: with a 1% failure rate, 100 runs show at most one failure about 74% of the time.',
    },
    seeAlso: ['scipy.stats.binom.cdf', 'scipy.stats.beta'],
  },
  {
    name: 'scipy.stats.binom.cdf',
    aliases: ['stats.binom.cdf'],
    lang: 'python',
    kind: 'method',
    official: 'Cumulative distribution function of the given RV.',
    source: 'SciPy docstring',
    when: 'You want the chance of k or fewer events in n tries. "Fewer than k" is cdf(k - 1), an easy off-by-one to get wrong.',
    flags: [
      ['k', 'the count; the result covers k and everything below'],
      ['n, p', 'the number of tries and the chance on each'],
    ],
    example: {
      command: 'print(round(stats.binom.cdf(0, 300, 0.01), 4))',
      says: 'Prints 0.049: with a 1% failure rate, 300 runs all pass only about 5% of the time.',
    },
    seeAlso: ['scipy.stats.binom', 'scipy.stats.norm.cdf'],
  },
  {
    name: 'scipy.stats.chi2',
    aliases: ['stats.chi2', 'chi2'],
    lang: 'python',
    kind: 'function',
    official: 'A chi-squared continuous random variable.',
    source: 'SciPy docstring',
    when: 'You are checking whether a filter\'s errors are the size it claims, or whether a measurement is an outlier. A sum of squared normalized errors follows this distribution, and df (degrees of freedom) is how many squared terms were added.',
    flags: [['df', 'degrees of freedom: how many squared errors are summed']],
    example: {
      command: 'threshold = chi2.ppf(0.999, df=1)',
      says: 'Gives 10.83: a single normalized squared residual above this happens only 1 time in 1000 by chance.',
    },
    seeAlso: ['scipy.stats.chi2.ppf', 'scipy.stats.chi2.sf'],
  },
  {
    name: 'scipy.stats.chi2.ppf',
    aliases: ['stats.chi2.ppf', 'chi2.ppf'],
    lang: 'python',
    kind: 'method',
    official: 'Percent point function (inverse of `cdf`) at q of the given RV.',
    source: 'SciPy docstring',
    when: 'You want a cutoff: the value a chi-squared statistic stays under a chosen fraction of the time, for outlier gates and filter consistency bounds.',
    flags: [
      ['q', 'the fraction, such as 0.95 or 0.999'],
      ['df', 'the degrees of freedom'],
    ],
    example: { command: 'print(round(chi2.ppf(0.95, df=2), 3))', says: 'Prints 5.991, the 95% gate for a two-number measurement.' },
    seeAlso: ['scipy.stats.chi2', 'scipy.stats.chi2.sf'],
  },
  {
    name: 'scipy.stats.chi2.sf',
    aliases: ['stats.chi2.sf'],
    lang: 'python',
    kind: 'method',
    official: 'Survival function (1 - `cdf`) at x of the given RV.',
    source: 'SciPy docstring',
    when: 'You have a chi-squared statistic and want its p-value: the chance of a value this large or larger if everything is working. A tiny p-value suggests an outlier or a wrong model.',
    flags: [
      ['x', 'the statistic you measured'],
      ['df', 'the degrees of freedom'],
    ],
    example: { command: 'p = stats.chi2.sf(12.0, 3)', says: 'Gives about 0.0074: a result this big happens by chance less than 1% of the time.' },
    seeAlso: ['scipy.stats.chi2.ppf', 'scipy.stats.norm.sf'],
  },
  {
    name: 'scipy.stats.genpareto',
    aliases: ['stats.genpareto'],
    lang: 'python',
    kind: 'function',
    official: 'A generalized Pareto continuous random variable.',
    source: 'SciPy docstring',
    when: 'You want to model the rare extreme end of your results, the part above a high threshold, to estimate chances far beyond anything the runs showed. It is fitted only to the amounts above the threshold, not to all the data.',
    flags: [
      ['c', 'the shape: how heavy the tail is'],
      ['scale=', 'how spread out the tail is'],
    ],
    example: {
      command: 'xi, _, sig = stats.genpareto.fit(x[x > u] - u, floc=0)',
      says: 'Fits the tail above threshold u, giving its shape xi and scale sig.',
    },
    seeAlso: ['scipy.stats.genpareto.fit', 'scipy.stats.genpareto.sf'],
  },
  {
    name: 'scipy.stats.genpareto.fit',
    aliases: ['stats.genpareto.fit'],
    lang: 'python',
    kind: 'method',
    official: 'Return estimates of shape (if applicable), location, and scale parameters from data.',
    source: 'SciPy docstring',
    when: 'You have the amounts by which results exceed a threshold and want the tail\'s shape and scale. Pin the location with floc=0, since the amounts start at zero, or the fit can wander.',
    flags: [
      ['data', 'the excesses above the threshold'],
      ['floc=', 'fix the location instead of fitting it; 0 for excesses'],
    ],
    example: {
      command: 'xi, loc, sig = stats.genpareto.fit(x[x > u] - u, floc=0)',
      says: 'Returns three numbers: the shape, the location (0, as fixed) and the scale.',
    },
    seeAlso: ['scipy.stats.genpareto', 'scipy.stats.norm.fit'],
  },
  {
    name: 'scipy.stats.genpareto.sf',
    aliases: ['stats.genpareto.sf'],
    lang: 'python',
    kind: 'method',
    official: 'Survival function (1 - `cdf`) at x of the given RV.',
    source: 'SciPy docstring',
    when: 'You have a fitted tail and want the chance of going beyond some level. The answer is the chance given that you are already past the threshold, so multiply by how often the threshold is crossed.',
    flags: [
      ['x', 'how far past the threshold'],
      ['c', 'the fitted shape'],
      ['scale=', 'the fitted scale'],
    ],
    example: {
      command: 'p = 0.1 * stats.genpareto.sf(level - u, xi, scale=sig)',
      says: 'Gives the chance of exceeding level, where 10% of runs pass the threshold u.',
    },
    seeAlso: ['scipy.stats.genpareto', 'scipy.stats.norm.sf'],
  },
  {
    name: 'scipy.stats.kurtosis',
    aliases: ['stats.kurtosis'],
    lang: 'python',
    kind: 'function',
    official: 'Compute the kurtosis (Fisher or Pearson) of a dataset.',
    source: 'SciPy docstring',
    when: 'You want to know if data has heavier tails than a normal distribution, meaning more big outliers. By default it gives excess kurtosis, so normal data gives about 0, not 3; a big positive number means heavy tails.',
    example: {
      command: 'print(round(stats.kurtosis(noise[:, 0]), 3))',
      says: 'Prints a number near 0 for normal noise, and clearly above 0 if there are more outliers than a normal distribution would have.',
    },
    seeAlso: ['numpy.std', 'scipy.stats.norm'],
  },
  {
    name: 'scipy.stats.lognorm',
    aliases: ['stats.lognorm'],
    lang: 'python',
    kind: 'function',
    official: 'A lognormal continuous random variable.',
    source: 'SciPy docstring',
    when: 'A quantity is always positive and skewed toward big values, like a miss distance or a time to failure, so its logarithm is normal. The parameters are unusual: s is the spread of the log, and scale is the median, not the mean.',
    flags: [
      ['s', 'the standard deviation of the logarithm'],
      ['scale=', 'the median, e to the mean of the logarithm'],
    ],
    example: { command: 'parent = stats.lognorm(0.5, scale=40.0)\nprint(parent.median())', says: 'Prints 40.0: the scale is the median.' },
    seeAlso: ['scipy.stats.norm'],
  },
  {
    name: 'scipy.stats.norm',
    aliases: ['stats.norm'],
    lang: 'python',
    kind: 'function',
    official: 'A normal continuous random variable.',
    source: 'SciPy docstring',
    when: 'You are working with the bell curve: sensor noise, dispersions in a Monte Carlo run, 3-sigma limits. loc is the mean and scale is the standard deviation, not the variance; call it with them to get a "frozen" distribution you can reuse.',
    flags: [
      ['loc=', 'the mean'],
      ['scale=', 'the standard deviation'],
    ],
    example: {
      command: 'isp = stats.norm(loc=300.0, scale=2.0).rvs(size=10_000, random_state=0)',
      says: 'Draws 10,000 random specific impulses around 300 s with a 2 s standard deviation, the same ones every time.',
    },
    seeAlso: ['scipy.stats.norm.cdf', 'scipy.stats.norm.ppf', 'numpy.random.default_rng'],
  },
  {
    name: 'scipy.stats.norm.cdf',
    aliases: ['stats.norm.cdf'],
    lang: 'python',
    kind: 'method',
    official: 'Cumulative distribution function of the given RV.',
    source: 'SciPy docstring',
    when: 'You want the chance that a normal value is at or below some number. Without loc and scale it uses the standard normal, mean 0 and standard deviation 1, so give them or convert to sigmas first.',
    flags: [
      ['x', 'the value'],
      ['loc, scale', 'the mean and standard deviation, if not 0 and 1'],
    ],
    example: {
      command: 'print(round(stats.norm.cdf(1.0) - stats.norm.cdf(-1.0), 4))',
      says: 'Prints 0.6827: about 68% of normal values fall within one sigma of the mean.',
    },
    seeAlso: ['scipy.stats.norm.ppf', 'scipy.stats.norm.sf'],
  },
  {
    name: 'scipy.stats.norm.fit',
    aliases: ['stats.norm.fit'],
    lang: 'python',
    kind: 'method',
    official: 'Return estimates of shape (if applicable), location, and scale parameters from data.',
    source: 'SciPy docstring',
    when: 'You have samples and want the mean and standard deviation of the normal curve that fits them best. It fits a normal curve even to data that is plainly not normal, so plot a histogram before trusting it.',
    flags: [['data', 'the samples']],
    example: {
      command: 'loc, scale = stats.norm.fit(isp)',
      says: 'For the 10,000 samples drawn around 300 s, gives a loc near 300 and a scale near 2.',
    },
    seeAlso: ['scipy.stats.norm', 'numpy.mean', 'numpy.std'],
  },
  {
    name: 'scipy.stats.norm.pdf',
    aliases: ['stats.norm.pdf'],
    lang: 'python',
    kind: 'method',
    official: 'Probability density function at x of the given RV.',
    source: 'SciPy docstring',
    when: 'You want the height of the bell curve at a value, for example to draw it over a histogram. It is a density, not a chance, so it can be bigger than 1 when the curve is narrow.',
    flags: [
      ['x', 'the value or array of values'],
      ['loc, scale', 'the mean and standard deviation (the second and third arguments)'],
    ],
    example: { command: 'print(round(stats.norm.pdf(0.0), 4))', says: 'Prints 0.3989, the peak height of the standard bell curve.' },
    seeAlso: ['scipy.stats.norm.cdf'],
  },
  {
    name: 'scipy.stats.norm.ppf',
    aliases: ['stats.norm.ppf'],
    lang: 'python',
    kind: 'method',
    official: 'Percent point function (inverse of `cdf`) at q of the given RV.',
    source: 'SciPy docstring',
    when: 'You know a probability and want the value that goes with it, such as "how many sigmas cover 99.87%". It is the reverse of cdf.',
    flags: [
      ['q', 'the probability, between 0 and 1'],
      ['loc, scale', 'the mean and standard deviation, if not 0 and 1'],
    ],
    example: { command: 'print(round(stats.norm.ppf(0.9987), 4))', says: 'Prints 3.0115: 99.87% of normal values are below about 3 sigma.' },
    seeAlso: ['scipy.stats.norm.cdf'],
  },
  {
    name: 'scipy.stats.norm.sf',
    aliases: ['stats.norm.sf'],
    lang: 'python',
    kind: 'method',
    official: 'Survival function (1 - `cdf`) at x of the given RV.',
    source: 'SciPy docstring',
    when: 'You want the chance of being above a value, especially far out in the tail. It is 1 - cdf, but more accurate for tiny answers, where 1 - cdf rounds to zero.',
    flags: [
      ['x', 'the value'],
      ['loc, scale', 'the mean and standard deviation, if not 0 and 1'],
    ],
    example: { command: 'print(f"{stats.norm.sf(4.0):.3e}")', says: 'Prints 3.167e-05, the chance of a value more than 4 sigma above the mean.' },
    seeAlso: ['scipy.stats.norm.cdf', 'scipy.stats.chi2.sf'],
  },
  {
    name: 'scipy.stats.rayleigh',
    aliases: ['stats.rayleigh'],
    lang: 'python',
    kind: 'function',
    official: 'A Rayleigh continuous random variable.',
    source: 'SciPy docstring',
    when: 'You are describing a distance made of two independent normal errors, such as a landing miss distance from x and y errors of the same size. Using a normal curve for this is wrong, since a distance is never negative.',
    flags: [['scale=', 'the sigma of each of the two underlying normal errors']],
    example: {
      command: 'print(round(stats.rayleigh(scale=10.0).ppf(0.9973), 1))',
      says: 'Prints 34.4: with 10 m errors in each direction, 99.73% of landings fall within 34.4 m.',
    },
    seeAlso: ['scipy.stats.rayleigh.fit', 'scipy.stats.norm'],
  },
  {
    name: 'scipy.stats.rayleigh.fit',
    aliases: ['stats.rayleigh.fit'],
    lang: 'python',
    kind: 'method',
    official: 'Return estimates of shape (if applicable), location, and scale parameters from data.',
    source: 'SciPy docstring',
    when: 'You have miss distances and want the Rayleigh scale that fits them. Pass floc=0 so it fits only the scale; otherwise it also shifts the curve and gives a wrong answer.',
    flags: [
      ['data', 'the distances'],
      ['floc=', 'fix the location, usually at 0'],
    ],
    example: {
      command: 'scale = stats.rayleigh.fit(miss, floc=0)[1]',
      says: 'Returns (location, scale); [1] picks out the fitted scale.',
    },
    seeAlso: ['scipy.stats.rayleigh', 'scipy.stats.norm.fit'],
  },
  {
    name: 'scipy.stats.uniform',
    aliases: ['stats.uniform'],
    lang: 'python',
    kind: 'function',
    official: 'A uniform continuous random variable.',
    source: 'SciPy docstring',
    when: 'Every value in a range is equally likely, such as a mass factor you only know lies between two limits. The range is loc to loc + scale: scale is the width, not the upper end, which is an easy mistake to make.',
    flags: [
      ['loc=', 'the lower end'],
      ['scale=', 'the width of the range'],
    ],
    example: {
      command: 'mix = stats.uniform(loc=0.98, scale=0.04)',
      says: 'Makes a distribution spread evenly from 0.98 to 1.02.',
    },
    seeAlso: ['scipy.stats.norm', 'numpy.random.default_rng'],
  },
]
