import type { CommandRef } from './types'

export const COMMANDS: CommandRef[] = [
  {
    name: 'math.exp',
    aliases: ['exp'],
    lang: 'python',
    kind: 'function',
    official: 'Return e raised to the power of x.',
    source: 'Python standard library docstring',
    when: 'You need e (about 2.718) raised to a power, as in exponential decay of air density with height. You give it only the power: math.exp(2) is e squared. Very large powers (about 710 and up) raise OverflowError instead of giving infinity.',
    example: { command: 'rho = 1.225 * math.exp(-10 / 8.5)', says: 'Air density at 10 km with an 8.5 km scale height: about 0.378 kg per cubic meter.' },
    seeAlso: ['math.log', 'math.expm1', 'numpy.exp'],
  },
  {
    name: 'math.expm1',
    lang: 'python',
    kind: 'function',
    official: 'Return exp(x)-1.',
    source: 'Python standard library docstring',
    when: 'You need e**x - 1 for a very small x. Writing math.exp(x) - 1 throws away most of the digits, because the answer is very close to 1 and the subtraction cancels them; expm1 keeps them.',
    example: { command: 'print(math.expm1(1e-10))', says: 'Prints 1.00000000005e-10. math.exp(1e-10) - 1 would print 1.000000082740371e-10, wrong from the eighth digit on.' },
    seeAlso: ['math.exp', 'math.log1p'],
  },
  {
    name: 'math.factorial',
    aliases: ['factorial'],
    lang: 'python',
    kind: 'function',
    official: 'Find n!.',
    source: 'Python standard library docstring',
    when: 'You need n factorial, written n!: 1 x 2 x 3 x ... x n, the number of ways to put n things in order. It only takes whole numbers 0 or more: a negative number raises ValueError, and a float such as 5.0 raises TypeError.',
    example: { command: 'print(factorial(6))', says: 'Prints 720, the number of ways six crew members can line up for the hatch.' },
    seeAlso: ['math.comb', 'math.lgamma'],
  },
  {
    name: 'math.floor',
    lang: 'python',
    kind: 'function',
    official: 'Return the floor of x as an Integral.',
    source: 'Python standard library docstring',
    when: 'You want to round down to the whole number below, as an int. Watch negative numbers: math.floor(-2.5) is -3, not -2, because -3 is the whole number below.',
    example: { command: 'print(math.floor(7 / 2))', says: 'Prints 3: 3.5 rounded down.' },
    seeAlso: ['math.ceil', 'round', 'int'],
  },
  {
    name: 'math.fsum',
    lang: 'python',
    kind: 'function',
    official: 'Return an accurate floating point sum of values in the iterable seq.',
    source: 'Python standard library docstring',
    when: 'You are adding up many floats and want the most accurate total. A plain sum lets tiny rounding errors pile up; fsum keeps track of the lost bits and returns the correctly rounded answer. It is slower than sum, so use it where accuracy matters.',
    example: { command: 'print(sum([0.1] * 10), math.fsum([0.1] * 10))', says: 'Prints 0.9999999999999999 1.0: only fsum gets exactly 1.0.' },
    seeAlso: ['sum', 'numpy.sum'],
  },
  {
    name: 'math.gcd',
    aliases: ['gcd'],
    lang: 'python',
    kind: 'function',
    official: 'Greatest Common Divisor.',
    source: 'Python standard library docstring',
    when: 'You need the greatest common divisor: the biggest whole number that divides every one of the numbers with nothing left over. It helps to simplify fractions or find when two repeating events line up. It only takes integers.',
    example: { command: 'print(gcd(12, 18))', says: 'Prints 6: 6 goes into 12 twice and into 18 three times.' },
  },
  {
    name: 'math.hypot',
    lang: 'python',
    kind: 'function',
    official: 'Multidimensional Euclidean distance from the origin to a point.',
    source: 'Python standard library docstring',
    when: 'You need the length of an arrow such as (x, y) or (x, y, z): its straight-line distance from the origin. It is safer than writing math.sqrt(x*x + y*y) yourself, which can overflow or lose accuracy with very big or very small numbers.',
    example: { command: 'print(math.hypot(3, 4))', says: 'Prints 5.0, the long side of a right triangle with sides 3 and 4.' },
    seeAlso: ['math.sqrt', 'numpy.hypot', 'numpy.linalg.norm'],
  },
  {
    name: 'math.isclose',
    lang: 'python',
    kind: 'function',
    official: 'Determine whether two floating point numbers are close in value.',
    source: 'Python standard library docstring',
    when: 'You want to know whether two floats are equal apart from rounding error, since == on floats often fails (0.1 + 0.2 == 0.3 is False). By default it only allows a relative difference, so nothing is ever close to 0.0 unless you also give abs_tol.',
    flags: [
      ['rel_tol=', 'how far apart they may be, as a fraction of their size (1e-9 unless you say otherwise)'],
      ['abs_tol=', 'how far apart they may be as a plain amount; needed when comparing with zero'],
    ],
    example: { command: 'print(math.isclose(0.1 + 0.2, 0.3))', says: 'Prints True: the two differ only by rounding error.' },
    seeAlso: ['pytest.approx', 'numpy.allclose'],
  },
  {
    name: 'math.isfinite',
    lang: 'python',
    kind: 'function',
    official: 'Return True if x is neither an infinity nor a NaN, and False otherwise.',
    source: 'Python standard library docstring',
    when: 'You want to check that a number is a normal, usable value: not infinity and not nan (not a number). It is the best guard on sensor inputs, because every comparison with nan is False, so a check like peak > limit quietly lets bad data through.',
    example: { command: 'print(math.isfinite(float("inf")))', says: 'Prints False: infinity is not a finite number.' },
    seeAlso: ['math.isnan', 'numpy.isfinite'],
  },
  {
    name: 'math.isnan',
    lang: 'python',
    kind: 'function',
    official: 'Return True if x is a NaN (not a number), and False otherwise.',
    source: 'Python standard library docstring',
    when: 'You need to know whether a value is nan (not a number), the result of undefined math such as inf - inf. You cannot test for it with ==, because nan == nan is False. It does not catch infinity; math.isfinite does.',
    example: { command: 'print(math.isnan(float("nan")))', says: 'Prints True.' },
    seeAlso: ['math.isfinite', 'numpy.isnan'],
  },
  {
    name: 'math.lgamma',
    lang: 'python',
    kind: 'function',
    official: 'Natural logarithm of absolute value of Gamma function at x.',
    source: 'Python standard library docstring',
    when: 'You need the natural log of the gamma function, which extends factorials: gamma(n) is (n - 1)!. Working with the log lets you handle factorial-sized numbers that are far too big for a float.',
    example: { command: 'print(math.lgamma(1001))', says: 'Prints 5912.128178488163, the natural log of 1000!, a number with 2568 digits.' },
    seeAlso: ['math.factorial', 'math.log'],
  },
  {
    name: 'math.log',
    lang: 'python',
    kind: 'function',
    official: 'Return the logarithm of x to the given base.',
    source: 'Python standard library docstring',
    when: 'You need a logarithm. With one argument it is the natural log (base e, written ln in math); give a second argument for another base. Zero or a negative number raises ValueError: math domain error.',
    flags: [['base', 'the second argument: the base to use (e if you leave it out)']],
    example: { command: 'dv = 311 * 9.80665 * math.log(5000 / 2000)', says: 'The rocket equation: a 311 s engine taking a stage from 5000 kg to 2000 kg gives about 2795 m/s of speed change.' },
    seeAlso: ['math.log10', 'math.log2', 'math.exp', 'numpy.log'],
  },
  {
    name: 'math.log10',
    lang: 'python',
    kind: 'function',
    official: 'Return the base 10 logarithm of x.',
    source: 'Python standard library docstring',
    when: 'You need a base-10 logarithm, as in decibels or counting how many digits a number has. It is more exact than math.log(x, 10), which gives 2.9999999999999996 for 1000.',
    example: { command: 'print(math.log10(1000))', says: 'Prints 3.0, because 10 x 10 x 10 is 1000.' },
    seeAlso: ['math.log', 'math.log2', 'numpy.log10'],
  },
  {
    name: 'math.log1p',
    lang: 'python',
    kind: 'function',
    official: 'Return the natural logarithm of 1+x (base e).',
    source: 'Python standard library docstring',
    when: 'You need ln(1 + x) for a very small x. Writing math.log(1 + x) loses digits, because 1 + x is rounded before the log is taken; log1p keeps them. It often appears next to math.expm1.',
    example: { command: 'print(math.log1p(1e-10))', says: 'Prints 9.999999999500001e-11. math.log(1 + 1e-10) would print 1.000000082690371e-10, wrong from the eighth digit on.' },
    seeAlso: ['math.log', 'math.expm1'],
  },
  {
    name: 'math.log2',
    lang: 'python',
    kind: 'function',
    official: 'Return the base 2 logarithm of x.',
    source: 'Python standard library docstring',
    when: 'You need a base-2 logarithm: how many times you can halve something, how many bits a number needs, or how many steps a binary search takes.',
    example: { command: 'print(math.log2(1024))', says: 'Prints 10.0: halving 1024 ten times reaches 1.' },
    seeAlso: ['math.log', 'math.log10', 'numpy.log2'],
  },
  {
    name: 'math.pi',
    aliases: ['pi'],
    lang: 'python',
    kind: 'constant',
    official: 'The mathematical constant π = 3.141592..., to available precision.',
    source: 'Python documentation (docs.python.org)',
    when: 'Any formula with pi in it: circles, angles in radians, orbital periods. It is a float, so it is accurate to about 15 digits, not exact: math.sin(math.pi) gives 1.2246467991473532e-16, not 0.',
    example: { command: 'T = 2 * math.pi * math.sqrt(6771e3**3 / 3.986e14)', says: 'The period of a circular orbit 400 km up: about 5545 seconds, a little over 92 minutes.' },
    seeAlso: ['math.e', 'math.radians', 'numpy.pi'],
  },
  {
    name: 'math.radians',
    lang: 'python',
    kind: 'function',
    official: 'Convert angle x from degrees to radians.',
    source: 'Python standard library docstring',
    when: 'You have an angle in degrees and are about to call math.sin, math.cos or math.tan, which all expect radians. Forgetting to convert gives answers that look reasonable but are wrong.',
    example: { command: 'print(math.sin(math.radians(30)))', says: 'Prints 0.49999999999999994: the sine of 30 degrees is one half, apart from rounding.' },
    seeAlso: ['math.degrees', 'math.sin', 'numpy.radians'],
  },
  {
    name: 'math.sin',
    aliases: ['sin'],
    lang: 'python',
    kind: 'function',
    official: 'Return the sine of x (measured in radians).',
    source: 'Python standard library docstring',
    when: 'You need the sine of an angle, for example to split a speed into its up and sideways parts. The angle must be in radians; convert degrees first with math.radians.',
    example: { command: 'vy = 7660 * math.sin(math.radians(35.0))', says: 'The part of a 7660 m/s speed that points 35 degrees up: about 4394 m/s.' },
    seeAlso: ['math.cos', 'math.radians', 'numpy.sin'],
  },
  {
    name: 'math.sqrt',
    aliases: ['sqrt'],
    lang: 'python',
    kind: 'function',
    official: 'Return the square root of x.',
    source: 'Python standard library docstring',
    when: 'You need a square root, as in the length of a vector. A negative number raises ValueError: math domain error; cmath.sqrt gives complex answers instead.',
    example: { command: 'print(math.sqrt(3 * 3 + 4 * 4))', says: 'Prints 5.0.' },
    seeAlso: ['math.hypot', 'cmath.sqrt', 'numpy.sqrt'],
  },
  {
    name: 'math.ulp',
    lang: 'python',
    kind: 'function',
    official: 'Return the value of the least significant bit of the float x.',
    source: 'Python standard library docstring',
    when: 'You want to know how precise a float can be at a certain size: the gap between x and the next float above it. The gap grows with the number, so a float near 1e16 cannot even hold whole numbers exactly.',
    example: { command: 'print(math.ulp(1.0))', says: 'Prints 2.220446049250313e-16, the gap just above 1.0.' },
    seeAlso: ['sys.float_info.epsilon', 'numpy.spacing'],
  },
  {
    name: 'multiprocessing',
    aliases: ['mp'],
    lang: 'python',
    kind: 'module',
    official: 'multiprocessing is a package that supports spawning processes using an API similar to the threading module.',
    source: 'Python documentation (docs.python.org)',
    when: 'Your program crunches many independent cases, like a Monte Carlo sweep, and you want to use several CPU cores at once. Each worker is a separate Python process, so it gets around the GIL (the lock that lets only one thread run Python at a time), but everything sent to a worker is copied, and the code that starts workers belongs under if __name__ == "__main__":.',
    example: { command: 'import multiprocessing as mp', says: 'Loads the module under the short name mp, as the lessons do.' },
    seeAlso: ['multiprocessing.Pool', 'concurrent.futures.ProcessPoolExecutor', 'joblib'],
  },
  {
    name: 'multiprocessing.Pool',
    aliases: ['mp.Pool'],
    lang: 'python',
    kind: 'function',
    official: 'Returns a process pool object',
    source: 'Python standard library docstring',
    when: 'You want to run the same function on many inputs using several processes. pool.map(f, items) hands back the results in the same order as the inputs. The function must be defined at the top level of a file, not a lambda, so it can be sent to the workers.',
    flags: [
      ['processes=', 'how many worker processes (one per CPU core unless you say otherwise)'],
      ['pool.map(f, items)', 'call f on each item in the workers and return the results in order'],
      ['chunksize=', 'how many items to send a worker at a time'],
    ],
    example: { command: 'with mp.Pool(processes=4) as pool:\n    results = pool.map(run_case, range(1000))', says: 'Runs run_case on 0 to 999 in four worker processes and collects the 1000 results in order.' },
    seeAlso: ['multiprocessing.get_context', 'concurrent.futures.ProcessPoolExecutor', 'os.cpu_count'],
  },
  {
    name: 'multiprocessing.get_context',
    aliases: ['mp.get_context'],
    lang: 'python',
    kind: 'function',
    official: 'Return a context object which has the same attributes as the multiprocessing module.',
    source: 'Python documentation (docs.python.org)',
    when: 'You need to choose how new processes are started. "fork" makes each worker a copy of the running program (fast, Linux and macOS only); "spawn" starts a fresh Python (the default on Windows and macOS). The context has the same tools as the module, such as Pool, using that start method.',
    flags: [['"fork"', 'start each worker as a copy of the current process']],
    example: { command: 'ctx = mp.get_context("fork")\nwith ctx.Pool(4) as pool:\n    print(pool.map(check_case, range(8)))', says: 'Starts four workers by forking, runs check_case on 0 to 7 and prints the eight results in order.' },
    seeAlso: ['multiprocessing.Pool'],
  },
  {
    name: 'multiprocessing.shared_memory',
    aliases: ['shared_memory'],
    lang: 'python',
    kind: 'module',
    official: 'Provides shared memory for direct access across processes.',
    source: 'Python standard library docstring',
    when: 'Several processes need to read the same large block of data, such as a big NumPy array, without each one getting its own copy. Only the block\'s name is sent to the workers.',
    example: { command: 'from multiprocessing import shared_memory', says: 'Makes shared_memory.SharedMemory available by its short name.' },
    seeAlso: ['multiprocessing.shared_memory.SharedMemory', 'concurrent.futures.ProcessPoolExecutor'],
  },
  {
    name: 'multiprocessing.shared_memory.SharedMemory',
    aliases: ['shared_memory.SharedMemory', 'SharedMemory'],
    lang: 'python',
    kind: 'class',
    official: 'Creates a new shared memory block or attaches to an existing shared memory block.',
    source: 'Python standard library docstring',
    when: 'You make a block of memory once and let worker processes attach to it by name. Wrap it in a NumPy array with buffer=shm.buf to use it. Every process must call close() when done, and the creator must call unlink() once at the end, or the memory stays reserved.',
    flags: [
      ['create=True', 'make a new block instead of attaching to an existing one'],
      ['size=', 'how many bytes the new block holds'],
      ['name=', 'attach to the existing block with this name'],
      ['.buf', 'the block\'s bytes, to hand to numpy.ndarray as buffer='],
      ['.close()', 'this process is finished with the block'],
      ['.unlink()', 'free the block for good (call once, in the creator)'],
    ],
    example: { command: 'shm = shared_memory.SharedMemory(create=True, size=data.nbytes)', says: 'Reserves a new shared block big enough for the data array; workers attach with SharedMemory(name=shm.name).' },
    seeAlso: ['multiprocessing.shared_memory', 'numpy.ndarray'],
  },
  {
    name: 'operator',
    lang: 'python',
    kind: 'module',
    official: 'Operator interface.',
    source: 'Python standard library docstring',
    when: 'You want an everyday operator such as +, < or [ ] as an ordinary function you can pass around, most often as a key for sorted, min or max. The one the lessons use is itemgetter.',
    example: { command: 'from operator import itemgetter', says: 'Makes itemgetter available by its short name.' },
    seeAlso: ['operator.itemgetter', 'sorted'],
  },
  {
    name: 'operator.itemgetter',
    aliases: ['itemgetter'],
    lang: 'python',
    kind: 'class',
    official: 'Return a callable object that fetches the given item(s) from its operand.',
    source: 'Python standard library docstring',
    when: 'You want a key function that picks out one field, such as key=itemgetter("margin") to sort dicts by their margin. It is a tidy, slightly faster stand-in for lambda r: r["margin"], and it does not fall into the late-binding trap when made in a loop.',
    example: { command: 'ranked = sorted(cases, key=itemgetter("margin"))', says: 'Sorts the list of case dicts from smallest margin to largest.' },
    seeAlso: ['sorted', 'lambda', 'max'],
  },
  {
    name: 'os',
    lang: 'python',
    kind: 'module',
    official: 'OS routines for NT or Posix depending on what system we\'re on.',
    source: 'Python standard library docstring',
    when: 'Your program needs to ask the operating system something: an environment variable, the number of CPU cores, a file\'s size. For building and joining file paths, pathlib.Path is usually easier to read.',
    example: { command: 'import os', says: 'Loads the module so you can use os.environ, os.cpu_count and os.path.' },
    seeAlso: ['os.path', 'pathlib.Path', 'sys'],
  },
  {
    name: 'os.cpu_count',
    lang: 'python',
    kind: 'function',
    official: 'Return the number of CPUs in the system; return None if indeterminable.',
    source: 'Python standard library docstring',
    when: 'You want to know how many CPU cores the machine has, for example to choose how many worker processes to start. It counts every core on the machine, not how many your program is allowed to use, and it can return None.',
    example: { command: 'print("cores:", os.cpu_count())', says: 'Prints something like cores: 8.' },
    seeAlso: ['multiprocessing.Pool', 'platform.machine'],
  },
  {
    name: 'os.environ',
    lang: 'python',
    kind: 'constant',
    official: 'A mapping object where keys and values are strings that represent the process environment.',
    source: 'Python documentation (docs.python.org)',
    when: 'You want to read or set environment variables: named settings such as HOME or DATABASE_URL that the shell hands to every program. os.environ["NAME"] raises KeyError when the variable is not set, and every value is a string, so convert numbers yourself.',
    flags: [['["NAME"]', 'read one variable (KeyError if missing), or set it by assigning a string']],
    example: { command: 'os.environ["OPENBLAS_NUM_THREADS"] = "1"', says: 'Sets the variable for this program and any program it starts, so NumPy\'s math library uses one core.' },
    seeAlso: ['os.environ.get', 'subprocess.run'],
  },
  {
    name: 'os.environ.get',
    lang: 'python',
    kind: 'method',
    official: 'D.get(k[,d]) -> D[k] if k in D, else d.  d defaults to None.',
    source: 'Python standard library docstring (Mapping.get)',
    when: 'You want an environment variable but have a sensible fallback when it is not set. The fallback is used only when the variable is missing, not when it is set to an empty string.',
    flags: [['default', 'the second argument: what to hand back when the variable is not set (None if you leave it out)']],
    example: { command: 'version = os.environ.get("APP_VERSION", "unknown")', says: 'Gets APP_VERSION, or the string unknown when it is not set.' },
    seeAlso: ['os.environ', 'dict.get'],
  },
  {
    name: 'os.path',
    lang: 'python',
    kind: 'module',
    official: 'Common operations on Posix pathnames.',
    source: 'Python standard library docstring',
    when: 'You are working with file paths as plain strings: taking them apart, making them absolute, checking file sizes. New code mostly uses pathlib.Path instead, but os.path is everywhere in older code.',
    example: { command: 'print(os.path.getsize("telemetry.csv"), "bytes")', says: 'Prints the size of telemetry.csv, such as 2500000 bytes.' },
    seeAlso: ['os.path.getsize', 'pathlib.Path'],
  },
  {
    name: 'os.path.abspath',
    lang: 'python',
    kind: 'function',
    official: 'Return an absolute path.',
    source: 'Python standard library docstring',
    when: 'You want the full path of a file, starting from the top folder /, instead of a relative one like data/log.csv. It is worked out from the folder you are in now, and it does not check that the file exists.',
    example: { command: 'print(os.path.abspath("logs"))', says: 'Prints the full path, such as /home/you/orbit/logs.' },
    seeAlso: ['os.path.dirname', 'pathlib.Path'],
  },
  {
    name: 'os.path.dirname',
    lang: 'python',
    kind: 'function',
    official: 'Returns the directory component of a pathname',
    source: 'Python standard library docstring',
    when: 'You want only the folder part of a path. It just cuts the text at the last slash; the file does not have to exist.',
    example: { command: 'print(os.path.dirname("/home/you/orbit/sim.py"))', says: 'Prints /home/you/orbit.' },
    seeAlso: ['os.path.abspath', 'pathlib.Path'],
  },
  {
    name: 'os.path.getsize',
    lang: 'python',
    kind: 'function',
    official: 'Return the size of a file, reported by os.stat().',
    source: 'Python standard library docstring',
    when: 'You want to know how big a file is, for example to compare a CSV file with the same data saved as Parquet. The answer is in bytes; divide by 1e6 for megabytes. A missing file raises FileNotFoundError.',
    example: { command: 'csv_mb = os.path.getsize("imu.csv") / 1e6', says: 'The size of imu.csv in megabytes.' },
    seeAlso: ['os.path', 'pathlib.Path'],
  },
  {
    name: 'pathlib',
    lang: 'python',
    kind: 'module',
    official: 'Object-oriented filesystem paths.',
    source: 'Python standard library docstring (Python 3.12)',
    when: 'You work with files and folders. Paths become objects that you join with /, and they know their own name, suffix and parent folder, which is clearer than gluing strings together.',
    example: { command: 'from pathlib import Path', says: 'Makes Path available by its short name, the way nearly all code uses it.' },
    seeAlso: ['pathlib.Path', 'os.path'],
  },
  {
    name: 'pathlib.Path',
    aliases: ['Path'],
    lang: 'python',
    kind: 'class',
    official: 'PurePath subclass that can make system calls.',
    source: 'Python standard library docstring',
    when: 'You need the path of a file or folder. Join parts with /, as in Path("data") / "run_07.csv", then ask it things or read and write through it. Making a Path does not create the file or check that it exists.',
    flags: [
      ['/', 'join a folder and a name into a longer path'],
      ['.read_text() / .write_text(s)', 'read the whole file as a string, or replace it with s'],
      ['.exists()', 'True if something is really there'],
      ['.name / .stem / .suffix / .parent', 'the last part, that part without its extension, the extension, and the folder above'],
      ['.resolve()', 'the full, real path'],
      ['.expanduser()', 'turn a leading ~ into your home folder'],
      ['.mkdir() / .iterdir()', 'make the folder, or loop over what is inside it'],
    ],
    example: { command: 'text = (Path("data") / "run_07.csv").read_text()', says: 'Reads the whole file data/run_07.csv into one string.' },
    seeAlso: ['pathlib.Path.home', 'open', 'os.path'],
  },
  {
    name: 'pathlib.Path.home',
    aliases: ['Path.home'],
    lang: 'python',
    kind: 'method',
    official: 'Return a new path pointing to the user\'s home directory (as returned by os.path.expanduser(\'~\')).',
    source: 'Python standard library docstring',
    when: 'You want your home folder, the one ~ stands for in the shell, as a Path. It is the same as Path("~").expanduser().',
    example: { command: 'print(Path.home() / "orbit")', says: 'Prints something like /home/you/orbit.' },
    seeAlso: ['pathlib.Path'],
  },
  {
    name: 'platform',
    lang: 'python',
    kind: 'module',
    official: 'This module tries to retrieve as much platform-identifying data as possible.',
    source: 'Python standard library docstring',
    when: 'You want to record which machine, operating system and Python produced a result, for example at the top of a benchmark report.',
    example: { command: 'print(platform.system(), platform.machine())', says: 'Prints something like Linux x86_64.' },
    seeAlso: ['platform.system', 'platform.machine', 'platform.python_version', 'sys.platform'],
  },
  {
    name: 'platform.machine',
    lang: 'python',
    kind: 'function',
    official: 'Returns the machine type, e.g. \'i386\'',
    source: 'Python standard library docstring',
    when: 'You want the processor family, such as x86_64 or arm64. It does not name the exact processor model; on Linux that is in /proc/cpuinfo.',
    example: { command: 'print(platform.machine())', says: 'Prints x86_64 on most PCs, or arm64 on an Apple Silicon Mac.' },
    seeAlso: ['platform', 'os.cpu_count'],
  },
  {
    name: 'platform.python_version',
    lang: 'python',
    kind: 'function',
    official: 'Returns the Python version as string \'major.minor.patchlevel\'',
    source: 'Python standard library docstring',
    when: 'You want the running Python\'s version as text, for a report or a log. It is a string, so do not compare versions with < (as text, "3.10" comes before "3.9"); use sys.version_info for that.',
    example: { command: 'print(platform.python_version())', says: 'Prints the version, such as 3.11.9.' },
    seeAlso: ['platform', 'sys.executable'],
  },
  {
    name: 'platform.release',
    lang: 'python',
    kind: 'function',
    official: 'Returns the system\'s release, e.g. \'2.2.0\' or \'NT\'',
    source: 'Python standard library docstring',
    when: 'You want the operating system\'s release number, such as the Linux kernel version, usually printed next to platform.system().',
    example: { command: 'print(platform.system() + " " + platform.release())', says: 'Prints something like Linux 6.8.0-45-generic.' },
    seeAlso: ['platform.system', 'platform'],
  },
  {
    name: 'platform.system',
    lang: 'python',
    kind: 'function',
    official: 'Returns the system/OS name, e.g. \'Linux\', \'Windows\' or \'Java\'.',
    source: 'Python standard library docstring',
    when: 'You want the operating system\'s name: Linux, Windows, or Darwin, which is what macOS calls itself here.',
    example: { command: 'print(platform.system())', says: 'Prints Linux, Windows or Darwin.' },
    seeAlso: ['platform.release', 'sys.platform'],
  },
  {
    name: 'pstats',
    lang: 'python',
    kind: 'module',
    official: 'Class for printing reports on profiled python code.',
    source: 'Python standard library docstring',
    when: 'You have profiled a program with cProfile and want to read the results: sort them, trim the long file paths and print the top lines.',
    example: { command: 'import pstats', says: 'Loads the module that turns profile data into a readable table.' },
    seeAlso: ['pstats.Stats', 'cProfile.Profile'],
  },
  {
    name: 'pstats.Stats',
    lang: 'python',
    kind: 'class',
    official: 'This class is used for creating reports from data generated by the Profile class.',
    source: 'Python standard library docstring',
    when: 'You want the table of where a profiled program spent its time. Sort by "cumulative" to see which functions, counting everything they call, cost the most; sort by "tottime" to see where the time is spent inside the function itself.',
    flags: [
      ['a profile or a file name', 'what to read: a cProfile.Profile object or a saved file such as "sim.prof"'],
      ['.strip_dirs()', 'show file names without their long folder paths'],
      ['.sort_stats("cumulative")', 'order by time including everything each function calls ("tottime" for its own time only)'],
      ['.print_stats(n)', 'print the first n rows'],
    ],
    example: { command: 'pstats.Stats(pr).strip_dirs().sort_stats("cumulative").print_stats(6)', says: 'Prints the six functions with the most total time, with short file names.' },
    seeAlso: ['cProfile.Profile', 'pstats'],
  },
  {
    name: 'random',
    lang: 'python',
    kind: 'module',
    official: 'Random variable generators.',
    source: 'Python standard library docstring',
    when: 'You need random numbers for a simulation, a shuffle or a game. They come from a formula started by a seed, so the same seed repeats them exactly, and they are not safe for passwords or keys. For large arrays of random numbers, numpy.random.default_rng is faster.',
    example: { command: 'import random', says: 'Loads the module so you can call random.random, random.uniform and random.gauss.' },
    seeAlso: ['random.Random', 'random.seed', 'numpy.random.default_rng'],
  },
  {
    name: 'random.Random',
    lang: 'python',
    kind: 'class',
    official: 'Random number generator base class used by bound module functions.',
    source: 'Python standard library docstring',
    when: 'You want a random number generator of your own, with its own seed, so part of your program gets a repeatable stream no matter what else draws random numbers. Make one per simulation and draw from it: rng.random(), rng.uniform() and rng.gauss() are methods on it.',
    flags: [['seed', 'the starting number; the same seed always gives the same sequence']],
    example: { command: 'rng = random.Random(20250922)\nprint(rng.random())', says: 'Prints 0.1788585863088027, and the same number on every run and every computer.' },
    seeAlso: ['random.seed', 'numpy.random.default_rng'],
  },
  {
    name: 'random.__file__',
    lang: 'python',
    kind: 'constant',
    official: 'The pathname of the file from which the module was loaded, if it was loaded from a file.',
    source: 'Python language reference (data model)',
    when: 'You want to know which file an import really loaded. If a file of your own called random.py sits next to your script, Python imports it instead of the standard one, and __file__ gives it away.',
    example: { command: 'print(random.__file__)', says: 'Prints something like /usr/lib/python3.11/random.py. If it shows your own folder, your file is hiding the real module.' },
    seeAlso: ['sys.path', 'pathlib.Path'],
  },
  {
    name: 'random.gauss',
    lang: 'python',
    kind: 'function',
    official: 'Gaussian distribution.',
    source: 'Python standard library docstring',
    when: 'You need random numbers from a bell curve (the normal distribution), for noise on a sensor or spread in a part\'s size. The second argument is the standard deviation, not the variance.',
    flags: [
      ['mu', 'the first argument: the center of the bell'],
      ['sigma', 'the second argument: the standard deviation, how wide the bell is'],
    ],
    example: { command: 'noise = random.gauss(0.0, 0.5)', says: 'A random sensor error: about two times in three it is within 0.5 of zero.' },
    seeAlso: ['random.uniform', 'random.Random', 'numpy.random.normal'],
  },
  {
    name: 'random.random',
    lang: 'python',
    kind: 'function',
    official: 'random() -> x in the interval [0, 1).',
    source: 'Python standard library docstring',
    when: 'You need a random float from 0 up to, but not including, 1. Comparing it with a probability is a quick way to make something happen some of the time.',
    example: { command: 'if random.random() < 0.05:\n    reading = float("nan")', says: 'About one time in twenty, the reading is replaced with nan: a simulated sensor fault.' },
    seeAlso: ['random.uniform', 'random.seed', 'numpy.random.random'],
  },
  {
    name: 'random.seed',
    lang: 'python',
    kind: 'function',
    official: 'Initialize internal state from a seed.',
    source: 'Python standard library docstring',
    when: 'You want the module\'s random numbers to repeat exactly from run to run. It resets one generator shared by the whole program, so any other code that draws numbers shifts your sequence; your own random.Random(seed) is safer.',
    example: { command: 'random.seed(1)\nprint(random.random())', says: 'Prints 0.13436424411240122 every time.' },
    seeAlso: ['random.Random', 'numpy.random.seed'],
  },
  {
    name: 'random.uniform',
    lang: 'python',
    kind: 'function',
    official: 'Get a random number in the range [a, b) or [a, b] depending on rounding.',
    source: 'Python standard library docstring',
    when: 'You want a random float between two limits, every value equally likely, such as a thrust that may be up to 2 percent off.',
    flags: [['a, b', 'the lowest and highest values']],
    example: { command: 'thrust = random.uniform(0.98, 1.02) * 9000', says: 'A thrust anywhere from 8820 to 9180 newtons.' },
    seeAlso: ['random.gauss', 'random.random'],
  },
  {
    name: 're',
    lang: 'python',
    kind: 'module',
    official: 'Support for regular expressions (RE).',
    source: 'Python standard library docstring',
    when: 'You need to find or change text that follows a pattern, such as every number in a line or every **bold** word. Write patterns as raw strings, r"...", so the backslashes reach re unchanged. For fixed text, str methods such as str.replace are simpler.',
    example: { command: 'import re', says: 'Loads the regular expression module.' },
    seeAlso: ['re.compile', 're.sub', 're.findall', 'str.replace'],
  },
  {
    name: 're.compile',
    lang: 'python',
    kind: 'function',
    official: 'Compile a regular expression pattern, returning a Pattern object.',
    source: 'Python standard library docstring',
    when: 'You use the same pattern many times: compile it once, give it a name, and call its methods, such as .match and .sub. Python remembers recently used patterns anyway, so the main gain is that the code reads better.',
    example: { command: 'HEADING = re.compile(r"^(#{1,6})\\s+(.*)$")', says: 'Keeps a pattern for Markdown headings, ready to use as HEADING.match(line).' },
    seeAlso: ['re.Pattern.match', 're.Pattern.sub', 're.Pattern.fullmatch'],
  },
  {
    name: 're.findall',
    lang: 'python',
    kind: 'function',
    official: 'Return a list of all non-overlapping matches in the string.',
    source: 'Python standard library docstring',
    when: 'You want every match of a pattern, as a list of strings. If the pattern has a group in brackets ( ), you get only the text of the group, not the whole match.',
    example: { command: 're.findall(r"\\d+", "3 cats and 12 dogs")', says: 'Returns [\'3\', \'12\']: every run of digits.' },
    seeAlso: ['re.compile', 're.sub'],
  },
  {
    name: 're.match',
    lang: 'python',
    kind: 'function',
    official: 'Try to apply the pattern at the start of the string, returning a Match object, or None if no match was found.',
    source: 'Python standard library docstring',
    when: 'You want to check whether a string starts with a pattern. It only looks at the start (re.search looks anywhere), and it returns None when there is no match, so check before calling .group(). To check the whole string, use re.fullmatch.',
    example: { command: 're.match(r"[A-Za-z_]\\w*", "total_2 * 2").group()', says: 'Returns \'total_2\', the name at the start of the text.' },
    seeAlso: ['re.Match.group', 're.Pattern.fullmatch', 're.compile'],
  },
  {
    name: 're.split',
    lang: 'python',
    kind: 'function',
    official: 'Split the source string by the occurrences of the pattern, returning a list containing the resulting substrings.',
    source: 'Python standard library docstring',
    when: 'You want to cut text wherever a pattern matches, such as any mix of commas and spaces. If you wrap the pattern in a group ( ), the separators are kept in the list too.',
    example: { command: 're.split(r"[,\\s]+", "imu, gps  baro")', says: 'Returns [\'imu\', \'gps\', \'baro\'].' },
    seeAlso: ['str.split', 're.findall'],
  },
  {
    name: 're.sub',
    lang: 'python',
    kind: 'function',
    official: 'Return the string obtained by replacing the leftmost non-overlapping occurrences of the pattern in string by the replacement repl.',
    source: 'Python standard library docstring',
    when: 'You want to replace every match of a pattern. In the replacement, \\1 means "the text the first group matched". Watch out: .+ grabs as much as it can, so use .+? to stop at the first possible end.',
    flags: [
      ['pattern', 'what to look for'],
      ['repl', 'what to put instead; \\1, \\2 bring back the groups'],
      ['string', 'the text to work on'],
    ],
    example: { command: 're.sub(r"\\*\\*(.+?)\\*\\*", r"<b>\\1</b>", "a **b** c")', says: 'Returns \'a <b>b</b> c\'.' },
    seeAlso: ['re.compile', 're.Pattern.sub', 'str.replace'],
  },
  {
    name: 'resource',
    lang: 'python',
    kind: 'module',
    official: 'This module provides basic mechanisms for measuring and controlling system resources utilized by a program.',
    source: 'Python documentation (docs.python.org)',
    when: 'You want to measure what your program has used, such as its peak memory. It works on Linux and macOS only, not on Windows.',
    example: { command: 'import resource', says: 'Loads the module (on Windows this line fails).' },
    seeAlso: ['resource.getrusage', 'tracemalloc'],
  },
  {
    name: 'resource.RUSAGE_SELF',
    lang: 'python',
    kind: 'constant',
    official: 'Pass to getrusage() to request resources consumed by the calling process, which is the sum of resources used by all threads in the process.',
    source: 'Python documentation (docs.python.org)',
    when: 'You pass it to resource.getrusage to ask about your own program, rather than about programs it started.',
    example: { command: 'usage = resource.getrusage(resource.RUSAGE_SELF)', says: 'Gets the resource totals of the running program.' },
    seeAlso: ['resource.getrusage'],
  },
  {
    name: 'resource.getrusage',
    lang: 'python',
    kind: 'function',
    official: 'This function returns an object that describes the resources consumed by either the current process or its children, as specified by the who parameter.',
    source: 'Python documentation (docs.python.org)',
    when: 'You want numbers about what a process has used so far: processor time, peak memory and more. Watch the units: ru_maxrss (peak memory) is in kilobytes on Linux but in bytes on macOS.',
    flags: [
      ['who', 'whose usage: resource.RUSAGE_SELF for this program'],
      ['.ru_maxrss', 'the peak memory used'],
    ],
    example: { command: 'peak_mb = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024', says: 'The program\'s peak memory in megabytes, on Linux.' },
    seeAlso: ['resource.RUSAGE_SELF', 'tracemalloc.get_traced_memory'],
  },
  {
    name: 'signal',
    lang: 'python',
    kind: 'module',
    official: 'This module provides mechanisms to use signal handlers in Python.',
    source: 'Python standard library docstring (_signal)',
    when: 'You want your program to react to signals: short messages the operating system sends a running program, such as SIGTERM when it is asked to stop. Only the main thread can set handlers.',
    example: { command: 'import signal', says: 'Loads the module. (from scipy import signal is a different thing, for filters.)' },
    seeAlso: ['signal.signal', 'signal.SIGTERM'],
  },
  {
    name: 'signal.SIGTERM',
    lang: 'python',
    kind: 'constant',
    official: 'Termination signal.',
    source: 'Python documentation (docs.python.org)',
    when: 'The polite "please stop" signal that kill and service managers send by default. Unlike SIGKILL, a program can catch it and save its work before it exits.',
    example: { command: 'signal.signal(signal.SIGTERM, on_term)', says: 'Asks Python to call on_term when the program is told to stop.' },
    seeAlso: ['signal.signal', 'sys.exit'],
  },
  {
    name: 'signal.signal',
    lang: 'python',
    kind: 'function',
    official: 'Set the action for the given signal.',
    source: 'Python standard library docstring',
    when: 'You want a function of yours to run when a signal arrives, for example to save a log before stopping. The handler is always called with two arguments, the signal number and the current stack frame, even if it ignores them.',
    flags: [
      ['signalnum', 'which signal, such as signal.SIGTERM'],
      ['handler', 'the function to call, taking (signum, frame)'],
    ],
    example: { command: 'def on_term(signum, frame):\n    save_log()\n    sys.exit(0)\n\nsignal.signal(signal.SIGTERM, on_term)', says: 'From now on, when the program is told to stop, it saves its log and then exits cleanly.' },
    seeAlso: ['signal.SIGTERM', 'sys.exit'],
  },
  {
    name: 'sqlite3',
    lang: 'python',
    kind: 'module',
    official: 'The sqlite3 extension module provides a DB-API 2.0 (PEP 249) compliant interface to the SQLite library, and requires SQLite 3.7.15 or newer.',
    source: 'Python standard library docstring',
    when: 'You want a real SQL database inside a Python program, with nothing to install: the whole database is one file. Put values into queries with ? placeholders, never with f-strings, so odd input cannot break the query.',
    example: { command: 'import sqlite3', says: 'Loads the module that talks to SQLite.' },
    seeAlso: ['sqlite3.connect', 'SELECT'],
  },
  {
    name: 'sqlite3.connect',
    lang: 'python',
    kind: 'function',
    official: 'Opens a connection to the SQLite database file database.',
    source: 'Python standard library docstring',
    when: 'You want to open a SQLite database file; it is created if it does not exist. Changes are not saved until you call con.commit(). Using the connection in a with block commits for you, but does not close it.',
    flags: [['database', 'the file to open, such as "fleet.db" (":memory:" for a throwaway one)']],
    example: { command: 'con = sqlite3.connect("fleet.db")\nrows = con.execute("SELECT name FROM rockets").fetchall()', says: 'Opens fleet.db and fetches every rocket name as a list of tuples.' },
    seeAlso: ['sqlite3', 'sqlite3.sqlite_version'],
  },
  {
    name: 'sqlite3.sqlite_version',
    lang: 'python',
    kind: 'constant',
    official: 'Version number of the runtime SQLite library as a string.',
    source: 'Python documentation (docs.python.org)',
    when: 'You want to know which SQLite library Python is using, which decides what SQL works (RETURNING, for example, needs 3.35 or newer). It is a string.',
    example: { command: 'print(sqlite3.sqlite_version)', says: 'Prints something like 3.45.1.' },
    seeAlso: ['sqlite3.connect', 'platform.python_version'],
  },
  {
    name: 'statistics',
    lang: 'python',
    kind: 'module',
    official: 'Basic statistics module.',
    source: 'Python standard library docstring',
    when: 'You want summary numbers for a short list: average, median, spread, quartiles. For large arrays, NumPy does the same much faster.',
    example: { command: 'import statistics', says: 'Loads the module.' },
    seeAlso: ['statistics.mean', 'statistics.median', 'statistics.stdev', 'numpy.mean'],
  },
  {
    name: 'statistics.mean',
    aliases: ['stats.mean'],
    lang: 'python',
    kind: 'function',
    official: 'Return the sample arithmetic mean of data.',
    source: 'Python standard library docstring',
    when: 'You want the average: add them up and divide by how many there are. An empty list raises StatisticsError instead of returning 0.',
    example: { command: 'print(statistics.mean([9.79, 9.82, 9.81]))', says: 'Prints 9.806666666666667.' },
    seeAlso: ['statistics.median', 'numpy.mean'],
  },
  {
    name: 'statistics.median',
    lang: 'python',
    kind: 'function',
    official: 'Return the median (middle value) of numeric data.',
    source: 'Python standard library docstring',
    when: 'You want the middle value once the numbers are sorted (the average of the two middle ones when the count is even). Unlike the mean, one wild reading barely moves it.',
    example: { command: 'print(statistics.median([12.1, 11.9, 250.0, 12.0]))', says: 'Prints 12.05: the bad 250.0 reading does not drag it up.' },
    seeAlso: ['statistics.mean', 'statistics.quantiles', 'numpy.median'],
  },
  {
    name: 'statistics.quantiles',
    lang: 'python',
    kind: 'function',
    official: 'Divide *data* into *n* continuous intervals with equal probability.',
    source: 'Python standard library docstring',
    when: 'You want cut points that split your data into equal-sized groups, such as quartiles for a timing report. It returns n - 1 numbers, and needs at least two data points.',
    flags: [['n=', 'how many groups (4 for quartiles, the default; 100 for percentiles)']],
    example: { command: 'q1, med, q3 = statistics.quantiles(ms, n=4)', says: 'Splits the timings into four equal groups and gives the three cut points: first quartile, median and third quartile.' },
    seeAlso: ['statistics.median', 'numpy.percentile'],
  },
  {
    name: 'statistics.stdev',
    lang: 'python',
    kind: 'function',
    official: 'Return the square root of the sample variance.',
    source: 'Python standard library docstring',
    when: 'You want the standard deviation of a sample: how spread out the values are. It divides by n - 1, while numpy.std divides by n unless told otherwise, so the two disagree a little on short lists. It needs at least two values.',
    example: { command: 'print(statistics.stdev([2, 4, 4, 4, 5, 5, 7, 9]))', says: 'Prints 2.138089935299395.' },
    seeAlso: ['statistics.mean', 'numpy.std'],
  },
  {
    name: 'struct',
    lang: 'python',
    kind: 'module',
    official: 'Functions to convert between Python values and C structs.',
    source: 'Python standard library docstring',
    when: 'You need to read or write binary data laid out exactly, byte by byte, such as a telemetry packet or a C struct. Start every format with a byte-order character (< little-endian, > big-endian), or struct adds padding the way this machine\'s C compiler would.',
    example: { command: 'import struct', says: 'Loads the module.' },
    seeAlso: ['struct.pack', 'struct.unpack', 'struct.calcsize', 'int.from_bytes'],
  },
  {
    name: 'struct.calcsize',
    lang: 'python',
    kind: 'function',
    official: 'Return size in bytes of the struct described by the format string.',
    source: 'Python standard library docstring',
    when: 'You want to know how many bytes a format takes before you read or send it. Without a byte-order character it counts padding, so the answer can be bigger than the fields added up.',
    example: { command: 'print(struct.calcsize("<HIf"), struct.calcsize("@HIf"))', says: 'Prints 10 12: the same three fields take 12 bytes once padding is added.' },
    seeAlso: ['struct.pack', 'struct.unpack'],
  },
  {
    name: 'struct.pack',
    lang: 'python',
    kind: 'function',
    official: 'Return a bytes object containing the values v1, v2, ... packed according to the format string.',
    source: 'Python standard library docstring',
    when: 'You want to turn numbers into the exact bytes a device or file format expects. Each value must fit its type, or struct.error is raised.',
    flags: [
      ['< > @', 'byte order first: little-endian, big-endian, or this machine\'s own with padding'],
      ['H I', 'unsigned 16-bit and 32-bit whole numbers'],
      ['f d', '4-byte and 8-byte floats'],
    ],
    example: { command: 'rec = struct.pack("<HIf", 7, 1000, 1.5)', says: 'Packs channel 7, time 1000 ms and value 1.5 into 10 bytes, little-endian.' },
    seeAlso: ['struct.unpack', 'struct.calcsize', 'bytes'],
  },
  {
    name: 'struct.unpack',
    lang: 'python',
    kind: 'function',
    official: 'Return a tuple containing values unpacked according to the format string.',
    source: 'Python standard library docstring',
    when: 'You have bytes in a known layout and want the numbers back. The bytes must be exactly as long as the format, and the answer is always a tuple, even for one value, so write (v,) = struct.unpack("<f", data).',
    flags: [
      ['format', 'the same kind of format string as struct.pack'],
      ['buffer', 'the bytes to read'],
    ],
    example: { command: 'print(struct.unpack("<HIf", rec))', says: 'Prints (7, 1000, 1.5).' },
    seeAlso: ['struct.pack', 'struct.unpack_from'],
  },
  {
    name: 'struct.unpack_from',
    lang: 'python',
    kind: 'function',
    official: 'Return a tuple containing values unpacked according to the format string.',
    source: 'Python standard library docstring',
    when: 'You want to read fields that start partway into a longer block of bytes, without slicing out a copy first. The bytes only need to be long enough from that point on.',
    flags: [['offset', 'the third argument: which byte to start at (0 unless you say otherwise)']],
    example: { command: 'print(struct.unpack_from("<If", blob, 4))', says: 'Reads a 32-bit whole number and a float starting at byte 4, such as (1000, 1.5).' },
    seeAlso: ['struct.unpack', 'struct.calcsize'],
  },
  {
    name: 'subprocess',
    lang: 'python',
    kind: 'module',
    official: 'Subprocesses with accessible I/O streams',
    source: 'Python standard library docstring',
    when: 'Your Python program needs to run another program, such as git or a compiled simulator, and maybe read what it prints.',
    example: { command: 'import subprocess', says: 'Loads the module.' },
    seeAlso: ['subprocess.run', 'sys.executable'],
  },
  {
    name: 'subprocess.run',
    lang: 'python',
    kind: 'function',
    official: 'Run command with arguments and return a CompletedProcess instance.',
    source: 'Python standard library docstring',
    when: 'You want to run another program and wait for it to finish. Pass the command as a list of words, not one string. A program that fails does not raise an error unless you add check=True; look at result.returncode otherwise.',
    flags: [
      ['a list of words', 'the program and its arguments, such as ["git", "status"]'],
      ['capture_output=True', 'keep what it prints in result.stdout and result.stderr instead of showing it'],
      ['text=True', 'give the output as str instead of bytes'],
      ['check=True', 'raise CalledProcessError if the program fails'],
      ['env=', 'the environment variables the program sees'],
    ],
    example: { command: 'result = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True, text=True)', says: 'Runs git and keeps what it printed: result.stdout holds the commit ID and result.returncode the exit code.' },
    seeAlso: ['sys.executable', 'os.environ', 'sys.exit'],
  },
  {
    name: 'sys',
    lang: 'python',
    kind: 'module',
    official: 'This module provides access to some objects used or maintained by the interpreter and to functions that interact strongly with the interpreter.',
    source: 'Python standard library docstring',
    when: 'You need to talk to the Python interpreter itself: the command-line arguments, standard input and output, the exit code, and where modules are found.',
    example: { command: 'import sys', says: 'Loads the module.' },
    seeAlso: ['sys.argv', 'sys.exit', 'sys.stdin', 'sys.path'],
  },
  {
    name: 'sys.argv',
    lang: 'python',
    kind: 'constant',
    official: 'The list of command line arguments passed to a Python script.',
    source: 'Python documentation (docs.python.org)',
    when: 'You want the words typed after your program\'s name on the command line. sys.argv[0] is the script\'s own name, so the first real argument is sys.argv[1]. They are all strings; convert numbers with int or float. For more than one or two, argparse is easier.',
    example: { command: 'altitude_km = float(sys.argv[1])', says: 'Run as python3 orbit.py 400, this gives 400.0.' },
    seeAlso: ['argparse.ArgumentParser', 'sys.exit'],
  },
  {
    name: 'sys.base_prefix',
    lang: 'python',
    kind: 'constant',
    official: 'Set during Python startup, before site.py is run, to the same value as prefix.',
    source: 'Python documentation (docs.python.org)',
    when: 'You want the top folder of the Python installation a virtual environment was made from. Compare it with sys.prefix: the two differ exactly when you are inside a virtual environment.',
    example: { command: 'print(sys.prefix != sys.base_prefix)', says: 'Prints True inside a virtual environment, False outside one.' },
    seeAlso: ['sys.prefix', 'sys.executable'],
  },
  {
    name: 'sys.executable',
    lang: 'python',
    kind: 'constant',
    official: 'A string giving the absolute path of the executable binary for the Python interpreter, on systems where this makes sense.',
    source: 'Python documentation (docs.python.org)',
    when: 'You want the full path of the Python program running your code, usually to start another Python with subprocess. That way it is the same Python with the same installed packages, not whatever python means in the shell.',
    example: { command: 'subprocess.run([sys.executable, "-c", "print(1 + 1)"])', says: 'Starts a second copy of this same Python, which prints 2.' },
    seeAlso: ['subprocess.run', 'sys.prefix'],
  },
  {
    name: 'sys.exit',
    lang: 'python',
    kind: 'function',
    official: 'Exit the interpreter by raising SystemExit(status).',
    source: 'Python standard library docstring',
    when: 'You want your program to stop now and report an exit code to the shell. None or 0 means success; a string is printed to the error stream and gives exit code 1. It works by raising SystemExit, so finally blocks still run.',
    flags: [['status', 'the exit code: 0 or None for success, another number for failure, or a message string (code 1)']],
    example: { command: 'sys.exit(main())', says: 'Runs main and hands its return value to the shell as the exit code.' },
    seeAlso: ['SystemExit', 'sys.argv'],
  },
  {
    name: 'sys.float_info',
    lang: 'python',
    kind: 'constant',
    official: 'A named tuple holding information about the float type.',
    source: 'Python standard library docstring',
    when: 'You want the facts about floats on this machine: the largest one, the smallest gap, how many digits they hold.',
    example: { command: 'print(sys.float_info.max)', says: 'Prints 1.7976931348623157e+308, the biggest float there is.' },
    seeAlso: ['sys.float_info.epsilon', 'sys.float_info.dig', 'numpy.finfo'],
  },
  {
    name: 'sys.float_info.dig',
    lang: 'python',
    kind: 'constant',
    official: 'DBL_DIG -- maximum number of decimal digits that can be faithfully represented in a float',
    source: 'Python standard library docstring (sys.float_info field)',
    when: 'You want to know how many decimal digits a float holds faithfully: 15. Printing more digits than that shows rounding noise, not real information.',
    example: { command: 'print(sys.float_info.dig)', says: 'Prints 15.' },
    seeAlso: ['sys.float_info', 'sys.float_info.epsilon'],
  },
  {
    name: 'sys.float_info.epsilon',
    lang: 'python',
    kind: 'constant',
    official: 'DBL_EPSILON -- Difference between 1 and the next representable float',
    source: 'Python standard library docstring (sys.float_info field)',
    when: 'You want the gap between 1.0 and the next float above it, the size of rounding error near 1. The gap grows for bigger numbers, so for other sizes use math.ulp(x).',
    example: { command: 'print(sys.float_info.epsilon)', says: 'Prints 2.220446049250313e-16.' },
    seeAlso: ['math.ulp', 'numpy.finfo', 'sys.float_info'],
  },
  {
    name: 'sys.getsizeof',
    lang: 'python',
    kind: 'function',
    official: 'Return the size of object in bytes.',
    source: 'Python standard library docstring',
    when: 'You want to know how many bytes one Python object takes in memory. For a list it counts only the list itself, not the objects inside it.',
    example: { command: 'print(sys.getsizeof(9.81))', says: 'Prints 24: a single Python float takes 24 bytes, three times the 8 bytes a NumPy array needs per number.' },
    seeAlso: ['tracemalloc.get_traced_memory', 'numpy.ndarray'],
  },
  {
    name: 'sys.path',
    lang: 'python',
    kind: 'constant',
    official: 'A list of strings that specifies the search path for modules.',
    source: 'Python documentation (docs.python.org)',
    when: 'You want to see the list of folders Python searches, in order, when you import something. The first entry is your script\'s folder, which is why a file called random.py next to your script hides the real random module.',
    example: { command: 'for entry in sys.path[:3]:\n    print(entry)', says: 'Prints the first three folders Python searches for imports.' },
    seeAlso: ['random.__file__', 'sys.prefix'],
  },
  {
    name: 'sys.platform',
    lang: 'python',
    kind: 'constant',
    official: 'This string contains a platform identifier that can be used to append platform-specific components to sys.path, for instance.',
    source: 'Python documentation (docs.python.org)',
    when: 'You want a short name for the operating system, to skip or change code on one of them: "linux", "darwin" (macOS) or "win32" (Windows, even 64-bit Windows).',
    example: { command: '@pytest.mark.skipif(sys.platform == "win32", reason="uses POSIX shared memory")', says: 'Skips the test on Windows.' },
    seeAlso: ['platform.system', 'pytest.mark.skip'],
  },
  {
    name: 'sys.prefix',
    lang: 'python',
    kind: 'constant',
    official: 'A string giving the site-specific directory prefix where the platform independent Python files are installed; on Unix, the default is /usr/local.',
    source: 'Python documentation (docs.python.org)',
    when: 'You want the top folder of the Python environment in use: your virtual environment\'s folder when one is active.',
    example: { command: 'print(sys.prefix)', says: 'Prints something like /home/you/orbit/.venv.' },
    seeAlso: ['sys.base_prefix', 'sys.executable'],
  },
  {
    name: 'sys.stderr',
    lang: 'python',
    kind: 'constant',
    official: 'standard error object; used for error messages',
    source: 'Python standard library docstring (sys module)',
    when: 'You want to print an error, a warning or progress messages without mixing them into the program\'s real output, which may be going into a file or another program.',
    example: { command: 'print("gps dropout at t=41.2", file=sys.stderr)', says: 'Shows the message on the error stream; python3 sim.py > out.txt still shows it on screen and keeps it out of out.txt.' },
    seeAlso: ['sys.stdout', 'print'],
  },
  {
    name: 'sys.stdin',
    lang: 'python',
    kind: 'constant',
    official: 'standard input file object; used by input()',
    source: 'Python standard library docstring (sys module)',
    when: 'You want to read what is typed or piped into your program (with < or |). Looping over it gives one line at a time, each still ending in a newline.',
    example: { command: 'for line in sys.stdin:\n    print(line.strip().upper())', says: 'Prints every line of input in capitals.' },
    seeAlso: ['sys.stdin.read', 'input'],
  },
  {
    name: 'sys.stdin.read',
    lang: 'python',
    kind: 'method',
    official: 'Read at most n characters from stream.',
    source: 'Python standard library docstring (io.TextIOBase.read)',
    when: 'You want all of the input at once, as one string. It waits until the input ends: the end of a piped file, or Ctrl+D typed on a new line.',
    example: { command: 'lines = sys.stdin.read().splitlines()', says: 'Reads everything piped in and splits it into a list of lines without the newlines.' },
    seeAlso: ['sys.stdin', 'str.splitlines', 'input'],
  },
  {
    name: 'sys.stdout',
    lang: 'python',
    kind: 'constant',
    official: 'standard output file object; used by print()',
    source: 'Python standard library docstring (sys module)',
    when: 'The normal output stream, where print writes. You name it when a tool asks where to send output, such as a logging handler.',
    example: { command: 'handler = logging.StreamHandler(sys.stdout)', says: 'Sends log messages to normal output instead of the error stream.' },
    seeAlso: ['sys.stderr', 'print', 'logging.StreamHandler'],
  },
  {
    name: 'time',
    lang: 'python',
    kind: 'module',
    official: 'This module provides various functions to manipulate time values.',
    source: 'Python standard library docstring',
    when: 'You want to time how long code takes, or make a program wait. For dates and times of day, the datetime module is easier.',
    example: { command: 'import time', says: 'Loads the module.' },
    seeAlso: ['time.perf_counter', 'time.sleep', 'datetime.datetime.now'],
  },
  {
    name: 'time.perf_counter',
    lang: 'python',
    kind: 'function',
    official: 'Performance counter for benchmarking.',
    source: 'Python standard library docstring',
    when: 'You want to time how long some code takes: read it before and after, and subtract. A single reading means nothing (it is not the time of day); only the difference between two readings does.',
    example: { command: 'start = time.perf_counter()\nsimulate()\nprint(f"{time.perf_counter() - start:.3f} s")', says: 'Prints how long simulate took, such as 0.412 s.' },
    seeAlso: ['timeit.repeat', 'time.sleep'],
  },
  {
    name: 'time.sleep',
    lang: 'python',
    kind: 'function',
    official: 'Delay execution for a given number of seconds.',
    source: 'Python standard library docstring',
    when: 'You want the program to wait for some seconds, for example to stand in for a slow network request. Inside async code it freezes everything; use await asyncio.sleep there instead.',
    flags: [['seconds', 'how long to wait; fractions such as 0.25 are fine']],
    example: { command: 'time.sleep(0.25)', says: 'Waits a quarter of a second, then carries on.' },
    seeAlso: ['asyncio.sleep', 'time.perf_counter'],
  },
  {
    name: 'timeit',
    lang: 'python',
    kind: 'module',
    official: 'Tool for measuring execution time of small code snippets.',
    source: 'Python standard library docstring',
    when: 'You want to measure how fast a small piece of code is, fairly. It runs the code many times and lets you take the best time, which filters out interruptions. It also works from the shell as python3 -m timeit.',
    flags: [['-s', 'setup code, run once and not timed']],
    example: { command: 'python3 -m timeit -s "import math" "math.sqrt(2.0)"', says: 'Runs the snippet millions of times and prints the best time per loop, such as 20000000 loops, best of 5: 15 nsec per loop.' },
    seeAlso: ['timeit.timeit', 'timeit.repeat', 'time.perf_counter'],
  },
  {
    name: 'timeit.repeat',
    lang: 'python',
    kind: 'function',
    official: 'Convenience function to create Timer object and call repeat method.',
    source: 'Python standard library docstring',
    when: 'You want several timings of the same code so you can take the fastest, the one least disturbed by other programs. Each of the repeat rounds runs the code number times.',
    flags: [
      ['number=', 'how many runs in each timed batch'],
      ['repeat=', 'how many batches to time'],
    ],
    example: { command: 'best = min(timeit.repeat(lambda: simulate(300.0), number=20, repeat=5)) / 20', says: 'Times 20 runs, five times over, and keeps the best time for a single run.' },
    seeAlso: ['timeit.timeit', 'time.perf_counter'],
  },
  {
    name: 'timeit.timeit',
    lang: 'python',
    kind: 'function',
    official: 'Convenience function to create Timer object and call timeit method.',
    source: 'Python standard library docstring',
    when: 'You want the time for running some code a number of times. Watch the default: without number= it runs the code a million times, which is far too many for anything slow.',
    flags: [['number=', 'how many times to run the code (1,000,000 unless you say otherwise)']],
    example: { command: 't = min(timeit.timeit(lambda: kalman_1d(z), number=1) for _ in range(3))', says: 'Times kalman_1d once, three times over, and keeps the fastest.' },
    seeAlso: ['timeit.repeat', 'time.perf_counter'],
  },
  {
    name: 'tomllib',
    lang: 'python',
    kind: 'module',
    official: 'This module provides an interface for parsing TOML (Tom\'s Obvious Minimal Language, https://toml.io).',
    source: 'Python documentation (docs.python.org)',
    when: 'You want to read a TOML file, the settings format of pyproject.toml. It can only read, not write, and the file must be opened in binary mode, "rb".',
    example: { command: 'import tomllib', says: 'Loads the module (Python 3.11 and newer).' },
    seeAlso: ['tomllib.load', 'json.loads'],
  },
  {
    name: 'tomllib.load',
    lang: 'python',
    kind: 'function',
    official: 'Parse TOML from a binary file object.',
    source: 'Python standard library docstring',
    when: 'You want the contents of a TOML file as a dict. Open the file with "rb"; a file opened as text raises TypeError.',
    example: { command: 'with open("pyproject.toml", "rb") as f:\n    config = tomllib.load(f)\nprint(config["project"]["name"])', says: 'Prints the project name from pyproject.toml.' },
    seeAlso: ['tomllib', 'json.loads', 'open'],
  },
  {
    name: 'tracemalloc',
    lang: 'python',
    kind: 'module',
    official: 'Debug module to trace memory blocks allocated by Python.',
    source: 'Python standard library docstring (_tracemalloc)',
    when: 'You want to measure how much memory your Python code allocates while it runs, NumPy arrays included. The program runs slower while tracing is on.',
    example: { command: 'import tracemalloc', says: 'Loads the module.' },
    seeAlso: ['tracemalloc.start', 'tracemalloc.get_traced_memory', 'resource.getrusage'],
  },
  {
    name: 'tracemalloc.get_traced_memory',
    lang: 'python',
    kind: 'function',
    official: 'Get the current size and peak size of memory blocks traced by tracemalloc.',
    source: 'Python standard library docstring',
    when: 'You want to know how much memory is in use now, and the most there has been, since tracing started. It returns (current, peak) in bytes. Read it before tracemalloc.stop, which throws the numbers away.',
    example: { command: 'current, peak = tracemalloc.get_traced_memory()\nprint(f"peak {peak / 1e6:.1f} MB")', says: 'Prints the highest memory use since tracing started, such as peak 80.0 MB.' },
    seeAlso: ['tracemalloc.start', 'tracemalloc.stop'],
  },
  {
    name: 'tracemalloc.start',
    lang: 'python',
    kind: 'function',
    official: 'Start tracing Python memory allocations.',
    source: 'Python standard library docstring',
    when: 'You want to begin counting memory. Only memory allocated after this call is counted.',
    example: { command: 'tracemalloc.start()', says: 'Starts tracing memory allocations.' },
    seeAlso: ['tracemalloc.get_traced_memory', 'tracemalloc.stop'],
  },
  {
    name: 'tracemalloc.stop',
    lang: 'python',
    kind: 'function',
    official: 'Stop tracing Python memory allocations.',
    source: 'Python standard library docstring',
    when: 'You are done measuring memory. Stopping also forgets everything it recorded, so read tracemalloc.get_traced_memory first.',
    example: { command: 'tracemalloc.stop()', says: 'Stops tracing and clears the recorded numbers.' },
    seeAlso: ['tracemalloc.start', 'tracemalloc.get_traced_memory'],
  },
  {
    name: 'typing',
    lang: 'python',
    kind: 'module',
    official: 'The typing module: Support for gradual typing as defined by PEP 484 and subsequent PEPs.',
    source: 'Python standard library docstring',
    when: 'You are writing type hints, notes on what types a function takes and returns, and need names beyond the built-in ones, such as Protocol or TypeVar. Python does not check the hints when it runs; a tool such as mypy does.',
    example: { command: 'from typing import Protocol, runtime_checkable', says: 'Makes Protocol and runtime_checkable available by their short names.' },
    seeAlso: ['typing.Protocol', 'typing.TypeVar', 'typing.Sequence'],
  },
  {
    name: 'typing.Generic',
    aliases: ['Generic'],
    lang: 'python',
    kind: 'class',
    official: 'Abstract base class for generic types.',
    source: 'Python standard library docstring',
    when: 'You are writing a class that works with any one type, chosen by whoever uses it, such as a buffer of floats or a buffer of strings. You name the type slot with a TypeVar and list it in Generic[...].',
    example: { command: 'class Buffer(Generic[T]):\n    def push(self, item: T) -> None: ...', says: 'Declares a Buffer that holds items of one type T, so a type checker treats Buffer[float] and Buffer[str] separately.' },
    seeAlso: ['typing.TypeVar', 'typing.Protocol'],
  },
  {
    name: 'typing.Iterable',
    lang: 'python',
    kind: 'type',
    official: 'A generic version of collections.abc.Iterable.',
    source: 'Python standard library docstring',
    when: 'You are hinting a parameter that your function only loops over: a list, tuple, set or generator all fit. collections.abc.Iterable is the same thing and is preferred in new code.',
    example: { command: 'def total(xs: Iterable[float]) -> float:', says: 'Says total accepts anything it can loop over that gives floats.' },
    seeAlso: ['typing.Sequence', 'collections.abc.Sequence'],
  },
  {
    name: 'typing.NewType',
    aliases: ['NewType'],
    lang: 'python',
    kind: 'class',
    official: 'NewType creates simple unique types with almost zero runtime overhead.',
    source: 'Python standard library docstring',
    when: 'You want a type checker to tell apart two things that are both plain floats, such as meters and feet. At run time it changes nothing: Metres(8420.0) is just the float 8420.0.',
    example: { command: 'Metres = NewType("Metres", float)', says: 'Makes Metres a separate type for the checker, while staying a plain float when the program runs.' },
    seeAlso: ['typing.TypeVar'],
  },
  {
    name: 'typing.Protocol',
    aliases: ['Protocol'],
    lang: 'python',
    kind: 'class',
    official: 'Base class for protocol classes.',
    source: 'Python standard library docstring',
    when: 'You want to describe what an object must be able to do (the methods it must have) without making it inherit from anything. Any class with those methods fits; the type checker matches by shape.',
    example: { command: 'class Altimeter(Protocol):\n    def read(self) -> float: ...', says: 'Any object with a read() method returning a float now counts as an Altimeter.' },
    seeAlso: ['typing.runtime_checkable', 'abc.ABC'],
  },
  {
    name: 'typing.Sequence',
    lang: 'python',
    kind: 'type',
    official: 'A generic version of collections.abc.Sequence.',
    source: 'Python standard library docstring',
    when: 'You are hinting a parameter that your function loops over and indexes, such as samples[0]: lists and tuples both fit. collections.abc.Sequence is the same thing and is preferred in new code.',
    example: { command: 'def peak(samples: Sequence[float]) -> float | None:', says: 'Says peak accepts a list or a tuple of floats and may return None.' },
    seeAlso: ['typing.Iterable', 'collections.abc.Sequence'],
  },
  {
    name: 'typing.TypeVar',
    aliases: ['TypeVar'],
    lang: 'python',
    kind: 'class',
    official: 'Type variable.',
    source: 'Python standard library docstring',
    when: 'You need a placeholder type that stands for "the same type each time", so a function can say it returns whatever type it was given. By convention it is called T.',
    example: { command: 'T = TypeVar("T")\ndef first(items: list[T]) -> T: ...', says: 'Says first returns the same type the list holds: an int from a list of ints.' },
    seeAlso: ['typing.Generic', 'typing.NewType'],
  },
  {
    name: 'typing.get_type_hints',
    aliases: ['get_type_hints'],
    lang: 'python',
    kind: 'function',
    official: 'Return type hints for an object.',
    source: 'Python standard library docstring',
    when: 'You want to read a function\'s or class\'s type hints while the program runs, as a dict.',
    example: { command: 'get_type_hints(mean)', says: 'Returns {\'values\': list[float], \'return\': <class \'float\'>}.' },
    seeAlso: ['inspect.signature'],
  },
  {
    name: 'typing.runtime_checkable',
    aliases: ['runtime_checkable'],
    lang: 'python',
    kind: 'function',
    official: 'Mark a protocol class as a runtime protocol.',
    source: 'Python standard library docstring',
    when: 'You want isinstance to work with a Protocol. It only checks that the methods exist, not that they take the right arguments or return the right type.',
    example: { command: '@runtime_checkable\nclass Altimeter(Protocol):\n    def read(self) -> float: ...', says: 'Now isinstance(sensor, Altimeter) is True for any object with a read method.' },
    seeAlso: ['typing.Protocol', 'isinstance'],
  },
  {
    name: 'unittest',
    lang: 'python',
    kind: 'module',
    official: 'Python unit testing framework, based on Erich Gamma\'s JUnit and Kent Beck\'s Smalltalk testing framework (used with permission).',
    source: 'Python standard library docstring',
    when: 'You want Python\'s built-in testing tools, with no extra install. ORBIT\'s lessons mostly use pytest, which runs unittest tests too.',
    example: { command: 'python3 -m unittest', says: 'Finds files named test*.py in this folder and below, runs their tests and reports the results.' },
    seeAlso: ['unittest.TestCase', 'unittest.mock', 'pytest'],
  },
  {
    name: 'unittest.TestCase',
    lang: 'python',
    kind: 'class',
    official: 'A class whose instances are single test cases.',
    source: 'Python standard library docstring',
    when: 'You write tests the unittest way: a class that inherits from TestCase, with methods whose names start with test. Check results with the self.assert... methods, which explain what differed when a test fails.',
    flags: [
      ['self.assertEqual(a, b)', 'fail unless a == b'],
      ['self.assertAlmostEqual(a, b)', 'fail unless a and b agree to 7 decimal places'],
    ],
    example: { command: 'class TestSummarise(unittest.TestCase):\n    def test_mean(self):\n        self.assertEqual(summarise([1, 2, 3])["mean"], 2)', says: 'Defines a test that passes when the mean of 1, 2 and 3 comes out as 2.' },
    seeAlso: ['unittest', 'pytest', 'assert'],
  },
  {
    name: 'unittest.mock',
    lang: 'python',
    kind: 'module',
    official: 'unittest.mock is a library for testing in Python.',
    source: 'Python documentation (docs.python.org)',
    when: 'You want a stand-in for part of your program, such as a valve driver or a sensor, that records how it was used. That lets a test run without the real hardware and check the calls afterward.',
    example: { command: 'from unittest.mock import Mock, create_autospec', says: 'Makes Mock and create_autospec available by their short names.' },
    seeAlso: ['unittest.mock.create_autospec', 'unittest.mock.Mock', 'unittest.mock.call'],
  },
  {
    name: 'unittest.mock.Mock',
    aliases: ['Mock'],
    lang: 'python',
    kind: 'class',
    official: 'Create a new `Mock` object.',
    source: 'Python standard library docstring',
    when: 'You need a quick fake object that accepts any method call and remembers it. Careful: it accepts misspelled methods too, so a typo still passes the test. create_autospec, or Mock(spec=TheClass), rejects methods the real class does not have.',
    flags: [['spec=', 'a class to copy; then only its methods are allowed']],
    example: { command: 'v = Mock()\nv.open()\nprint(v.method_calls)', says: 'Prints [call.open()].' },
    seeAlso: ['unittest.mock.create_autospec', 'unittest.mock.call'],
  },
  {
    name: 'unittest.mock.call',
    aliases: ['call'],
    lang: 'python',
    kind: 'function',
    official: 'call() is a helper object for making simpler assertions, for comparing with call_args, call_args_list, mock_calls and method_calls.',
    source: 'Python documentation (docs.python.org)',
    when: 'You write down the calls you expect a mock to have received, to compare with its method_calls list. call.open() means "open was called with no arguments".',
    example: { command: 'assert valve.method_calls == [call.open(), call.close()]', says: 'Passes only if the valve was opened and then closed, in that order, and nothing else.' },
    seeAlso: ['unittest.mock.call.open', 'unittest.mock.call.close', 'unittest.mock.create_autospec'],
  },
  {
    name: 'unittest.mock.call.close',
    aliases: ['call.close'],
    lang: 'python',
    kind: 'function',
    official: 'call() is a helper object for making simpler assertions, for comparing with call_args, call_args_list, mock_calls and method_calls.',
    source: 'Python documentation (docs.python.org)',
    when: 'In a list of expected calls, call.close() stands for "the close method was called with no arguments". Put arguments inside the brackets to expect those arguments.',
    example: { command: 'assert valve.method_calls == [call.open(), call.close()]', says: 'Expects open and then close, with no arguments, and nothing else.' },
    seeAlso: ['unittest.mock.call', 'unittest.mock.call.open'],
  },
  {
    name: 'unittest.mock.call.open',
    aliases: ['call.open'],
    lang: 'python',
    kind: 'function',
    official: 'call() is a helper object for making simpler assertions, for comparing with call_args, call_args_list, mock_calls and method_calls.',
    source: 'Python documentation (docs.python.org)',
    when: 'In a list of expected calls, call.open() stands for "the open method was called with no arguments". Any method name works the same way.',
    example: { command: 'assert valve.method_calls[0] == call.open()', says: 'Passes if the first thing done to the valve was calling open with no arguments.' },
    seeAlso: ['unittest.mock.call', 'unittest.mock.call.close'],
  },
  {
    name: 'unittest.mock.create_autospec',
    aliases: ['create_autospec'],
    lang: 'python',
    kind: 'function',
    official: 'Create a mock object using another object as a spec.',
    source: 'Python standard library docstring',
    when: 'You want a mock shaped exactly like a real class: it has that class\'s methods and nothing else, so calling a misspelled method fails in the test instead of on the vehicle.',
    flags: [['instance=True', 'fake an object of the class, not the class itself']],
    example: { command: 'valve = create_autospec(Valve, instance=True)', says: 'Makes a fake Valve object with only open and close, which records every call.' },
    seeAlso: ['unittest.mock.Mock', 'unittest.mock.call'],
  },
  {
    name: 'warnings',
    lang: 'python',
    kind: 'module',
    official: 'Python part of the warnings subsystem.',
    source: 'Python standard library docstring',
    when: 'You want to tell whoever uses your code about something that is not an error yet, such as a function that will be removed. Warnings print a message and let the program carry on.',
    example: { command: 'import warnings', says: 'Loads the module.' },
    seeAlso: ['warnings.warn', 'warnings.catch_warnings', 'DeprecationWarning'],
  },
  {
    name: 'warnings.catch_warnings',
    lang: 'python',
    kind: 'class',
    official: 'A context manager that copies and restores the warnings filter upon exiting the context.',
    source: 'Python standard library docstring',
    when: 'You want to change how warnings are handled for a few lines only, for example to record them in a test or silence one noisy call. Everything goes back to how it was when the with block ends.',
    flags: [['record=True', 'collect the warnings in a list instead of printing them']],
    example: { command: 'with warnings.catch_warnings(record=True) as caught:\n    warnings.simplefilter("always")\n    rho(10.0)', says: 'Runs rho and collects any warnings it gives in the list caught, instead of printing them.' },
    seeAlso: ['warnings.simplefilter', 'warnings.warn'],
  },
  {
    name: 'warnings.simplefilter',
    lang: 'python',
    kind: 'function',
    official: 'Insert a simple entry into the list of warnings filters (at the front).',
    source: 'Python standard library docstring',
    when: 'You want to decide what happens to warnings: show them every time, hide them, or turn them into errors. Use it inside warnings.catch_warnings so the change does not leak into the rest of the program.',
    flags: [
      ['"always"', 'show every warning, even repeats'],
      ['"ignore"', 'hide warnings'],
      ['"error"', 'turn warnings into exceptions'],
    ],
    example: { command: 'warnings.simplefilter("ignore")', says: 'Hides every warning from here on (until the catch_warnings block ends).' },
    seeAlso: ['warnings.catch_warnings', 'warnings.warn'],
  },
  {
    name: 'warnings.warn',
    lang: 'python',
    kind: 'function',
    official: 'Issue a warning, or maybe ignore it or raise an exception.',
    source: 'Python standard library docstring',
    when: 'You want to warn the caller without stopping the program, such as when an old function is still used. By default each warning shows only once per place, and DeprecationWarning is hidden unless the call comes from your main script or a test run.',
    flags: [
      ['message', 'the text to show'],
      ['category', 'the kind of warning, such as DeprecationWarning'],
      ['stacklevel=2', 'blame the caller\'s line, not this one'],
    ],
    example: { command: 'warnings.warn("rho() is deprecated, use density()", DeprecationWarning, stacklevel=2)', says: 'Warns that rho is going away, pointing at the line that called rho rather than at rho itself.' },
    seeAlso: ['warnings.catch_warnings', 'DeprecationWarning'],
  },
  {
    name: 'zlib',
    lang: 'python',
    kind: 'module',
    official: 'The functions in this module allow compression and decompression using the zlib library, which is based on GNU zip.',
    source: 'Python standard library docstring',
    when: 'You want to compress or decompress bytes in the zlib format, the one used inside git\'s object files, .png images and .zip files, or to compute a CRC-32 checksum.',
    example: { command: 'import zlib', says: 'Loads the module.' },
    seeAlso: ['zlib.decompress', 'zlib.crc32'],
  },
  {
    name: 'zlib.crc32',
    lang: 'python',
    kind: 'function',
    official: 'Compute a CRC-32 checksum of data.',
    source: 'Python standard library docstring',
    when: 'You want a quick checksum to spot accidental damage to data, such as a corrupted packet. It is not protection against someone changing the data on purpose; use hashlib or hmac for that. It takes bytes, not str.',
    example: { command: 'print(hex(zlib.crc32(b"123456789")))', says: 'Prints 0xcbf43926, the standard CRC-32 check value.' },
    seeAlso: ['hashlib.sha256', 'zlib'],
  },
  {
    name: 'zlib.decompress',
    lang: 'python',
    kind: 'function',
    official: 'Returns a bytes object containing the uncompressed data.',
    source: 'Python standard library docstring',
    when: 'You have bytes compressed with zlib, such as a git object file, and want the original bytes back. Data that is not valid zlib raises zlib.error.',
    example: { command: 'raw = open(".git/objects/3b/18e512dba79e4c8300dd08aeb37f8e728b8dad", "rb").read()\nprint(zlib.decompress(raw))', says: 'Prints the object\'s real contents, such as b\'blob 12\\x00hello world\\n\'.' },
    seeAlso: ['zlib', 'bytes.decode'],
  },
]
