import type { CommandRef } from './types'

const DOC = 'Python standard library docstring'
const REF = 'Python Library Reference (docs.python.org)'

export const COMMANDS: CommandRef[] = [
  {
    name: 'abc',
    lang: 'python',
    kind: 'module',
    official: 'Abstract Base Classes (ABCs) according to PEP 3119.',
    source: DOC,
    when: 'You want a base class that spells out which methods every subclass must have. You import ABC and abstractmethod from it; on its own the module does nothing.',
    example: { command: 'from abc import ABC, abstractmethod', says: 'Brings in the two tools you need to write an abstract base class.' },
    seeAlso: ['abc.ABC', 'abc.abstractmethod', 'typing.Protocol'],
  },
  {
    name: 'abc.ABC',
    aliases: ['ABC'],
    lang: 'python',
    kind: 'class',
    official: 'Helper class that provides a standard way to create an ABC using inheritance.',
    source: DOC,
    when: 'Inherit from it to make an abstract base class: a class that only describes what its subclasses must do. Python refuses to create an object of any subclass that has not filled in every @abstractmethod, and raises TypeError the moment you try.',
    example: {
      command: 'class SensorBase(ABC):\n    @abstractmethod\n    def read(self) -> float: ...',
      says: 'SensorBase() now raises TypeError. Only a subclass that writes its own read can be created.',
    },
    seeAlso: ['abc.abstractmethod', 'typing.Protocol', 'class'],
  },
  {
    name: 'abc.abstractmethod',
    aliases: ['abstractmethod'],
    lang: 'python',
    kind: 'function',
    official: 'A decorator indicating abstract methods.',
    source: DOC,
    when: 'Put @abstractmethod above a method in an ABC to say every subclass must write its own version. It only has an effect in a class that inherits from ABC; on a plain class it is silently ignored.',
    example: { command: '@abstractmethod\ndef read(self) -> float: ...', says: 'Marks read as required: a subclass that leaves it out cannot be created.' },
    seeAlso: ['abc.ABC'],
  },
  {
    name: 'argparse',
    lang: 'python',
    kind: 'module',
    official: 'Command-line parsing library',
    source: DOC,
    when: 'You want your script to take options from the command line, like --seed 42, and get a --help page for free. It reads sys.argv for you, converts the values and prints a clear error when the user types something wrong.',
    example: { command: 'python sim.py --help', says: 'Prints the usage line and every option with its help text, all written by argparse from your add_argument calls.' },
    seeAlso: ['argparse.ArgumentParser', 'sys.argv'],
  },
  {
    name: 'argparse.ArgumentParser',
    lang: 'python',
    kind: 'class',
    official: 'Object for parsing command line strings into Python objects.',
    source: DOC,
    when: 'Make one at the start of a command-line program, add one add_argument call per option, then call parse_args. Watch out: type=bool does not do what it looks like, because any non-empty text, even "False", becomes True. Use action="store_true" for on/off switches.',
    flags: [
      ['prog=', 'the program name shown in the usage line and --help'],
      ['description=', 'a line of text shown at the top of --help'],
      ['.add_argument(...)', 'declare one argument; a name starting with -- makes it optional'],
      ['.parse_args()', 'read the command line and return the values as attributes'],
    ],
    example: {
      command: 'parser = argparse.ArgumentParser(prog="sim.py")\nparser.add_argument("cases", type=int)\nargs = parser.parse_args(["400"])',
      says: 'args.cases is the int 400. Leave out the list and parse_args reads what the user typed.',
    },
    seeAlso: ['argparse.BooleanOptionalAction', 'sys.argv'],
  },
  {
    name: 'argparse.BooleanOptionalAction',
    lang: 'python',
    kind: 'class',
    official: 'The BooleanOptionalAction is available in argparse and adds support for boolean actions such as --foo and --no-foo.',
    source: REF,
    when: 'Use it as action= for an on/off option when you want both spellings: --save turns it on and --no-save turns it off. It needs Python 3.9 or later.',
    example: {
      command: 'parser.add_argument("--save", action=argparse.BooleanOptionalAction, default=True)',
      says: '--save gives args.save == True, --no-save gives False, and leaving both out keeps the default, True.',
    },
    seeAlso: ['argparse.ArgumentParser'],
  },
  {
    name: 'asyncio',
    lang: 'python',
    kind: 'module',
    official: 'The asyncio package, tracking PEP 3156.',
    source: DOC,
    when: 'Your program spends most of its time waiting: for replies from other computers, for timers. asyncio lets many waits overlap on one thread, using async def and await. Watch out: time.sleep inside a coroutine freezes every task; use await asyncio.sleep.',
    example: { command: 'asyncio.run(main())', says: 'Starts the event loop, runs the coroutine main until it finishes, and returns its result.' },
    seeAlso: ['async', 'await', 'asyncio.gather', 'asyncio.create_task'],
  },
  {
    name: 'asyncio.Queue',
    lang: 'python',
    kind: 'class',
    official: 'A queue, useful for coordinating producer and consumer coroutines.',
    source: DOC,
    when: 'Several worker tasks share a pile of jobs, and each takes the next job as soon as it is free. Watch out: every get() needs a matching task_done(), or await queue.join() waits forever.',
    flags: [
      ['.put(item)', 'await it to add an item'],
      ['.get()', 'await it to take the next item, waiting if the queue is empty'],
      ['.task_done()', 'tell the queue one item is finished'],
      ['.join()', 'await it to wait until every item is finished'],
    ],
    example: {
      command: 'queue = asyncio.Queue()\nawait queue.put("burn 1")',
      says: 'Makes an empty queue and adds one job. A worker doing await queue.get() receives "burn 1".',
    },
    seeAlso: ['asyncio.create_task', 'collections.deque'],
  },
  {
    name: 'asyncio.create_task',
    lang: 'python',
    kind: 'function',
    official: 'Schedule the execution of a coroutine object in a spawn task.',
    source: DOC,
    when: 'You want a coroutine to start running now, in the background, while your code carries on. Keep the task it hands back in a variable or list and await it later; a task nobody holds on to can vanish before it finishes.',
    example: { command: 'tasks = [asyncio.create_task(worker()) for _ in range(3)]', says: 'Starts three worker tasks at once and keeps them in a list.' },
    seeAlso: ['asyncio.gather', 'await'],
  },
  {
    name: 'asyncio.gather',
    lang: 'python',
    kind: 'function',
    official: 'Return a future aggregating results from the given coroutines/futures.',
    source: DOC,
    when: 'You have several coroutines and want them to wait side by side, then collect every result at once. The results come back in the order you passed them in, not the order they finished.',
    flags: [['*coros', 'the coroutines to run; put * before a list or generator to spread it out']],
    example: {
      command: 'a, b = await asyncio.gather(fetch("a", 1), fetch("b", 1))',
      says: 'Runs both fetches at the same time, so it takes about 1 second instead of 2, and returns both results in order.',
    },
    seeAlso: ['asyncio.create_task', 'asyncio.sleep', 'await'],
  },
  {
    name: 'asyncio.sleep',
    lang: 'python',
    kind: 'function',
    official: 'Coroutine that completes after a given time (in seconds).',
    source: DOC,
    when: 'Inside async code, to wait some seconds while other tasks keep running. It must be awaited: asyncio.sleep(1) without await waits for nothing.',
    example: { command: 'await asyncio.sleep(0.5)', says: 'Pauses this task for half a second while other tasks run.' },
    seeAlso: ['time.sleep', 'await', 'asyncio.gather'],
  },
  {
    name: 'base64',
    lang: 'python',
    kind: 'module',
    official: 'Base16, Base32, Base64 (RFC 3548), Base85 and Ascii85 data encodings',
    source: DOC,
    when: 'You need to write raw bytes, such as a hash, using only printable letters and digits, so they fit in text, a URL or a file name. The text comes out about a third longer than the bytes.',
    example: { command: 'base64.b64encode(b"GO")', says: "Returns b'R08=': two bytes written as four safe characters." },
    seeAlso: ['base64.urlsafe_b64encode', 'hashlib'],
  },
  {
    name: 'base64.urlsafe_b64encode',
    lang: 'python',
    kind: 'function',
    official: 'Encode bytes using the URL- and filesystem-safe Base64 alphabet.',
    source: DOC,
    when: 'You want Base64 text that is safe in URLs and file names: it uses - and _ instead of + and /. It takes bytes and gives back bytes, so add .decode() to get a str.',
    example: {
      command: 'print(base64.urlsafe_b64encode(digest).rstrip(b"=").decode())',
      says: 'Prints the hash as URL-safe text with the = padding removed, the way a wheel\'s RECORD file stores it.',
    },
    seeAlso: ['hashlib.sha256'],
  },
  {
    name: 'bisect',
    lang: 'python',
    kind: 'module',
    official: 'Bisection algorithms.',
    source: DOC,
    when: 'Your list is already sorted and you want to find where a value belongs, or insert it in its place, fast. It halves the search each step, so a million items take about 20 checks. Watch out: on an unsorted list it gives wrong answers without any error.',
    example: { command: 'import bisect', says: 'Makes bisect_left, bisect_right and insort available as bisect.bisect_left and so on.' },
    seeAlso: ['bisect.bisect_left', 'bisect.bisect_right', 'bisect.insort'],
  },
  {
    name: 'bisect.bisect_left',
    lang: 'python',
    kind: 'function',
    official: 'Return the index where to insert item x in list a, assuming a is sorted.',
    source: DOC,
    when: 'Find the first position in a sorted list whose value is at least x: where x is, or where it would go. It is the same as C++ std::lower_bound.',
    example: { command: 'bisect.bisect_left([10, 20, 30], 20)', says: 'Returns 1, the position of the 20.' },
    seeAlso: ['bisect.bisect_right', 'bisect.insort'],
  },
  {
    name: 'bisect.bisect_right',
    lang: 'python',
    kind: 'function',
    official: 'Return the index where to insert item x in list a, assuming a is sorted.',
    source: DOC,
    when: 'Like bisect_left, but when x is already in the list it gives the position just after it. Handy for turning a number into a band using a sorted list of breakpoints.',
    example: { command: 'return "FDCBA"[bisect.bisect_right([60, 70, 80, 90], score)]', says: 'Turns a score into a letter grade: 75 gives "C" and 90 gives "A".' },
    seeAlso: ['bisect.bisect_left'],
  },
  {
    name: 'bisect.insort',
    lang: 'python',
    kind: 'function',
    official: 'Insert item x in list a, and keep it sorted assuming a is sorted.',
    source: DOC,
    when: 'Put a new value into a sorted list so it stays sorted. Finding the spot is fast, but the insert still shifts every later item along, so each call costs O(n) on a long list.',
    example: { command: 'a = [10, 20, 30]\nbisect.insort(a, 25)', says: 'a is now [10, 20, 25, 30].' },
    seeAlso: ['bisect.bisect_right', 'heapq.heappush'],
  },
  {
    name: 'cProfile',
    lang: 'python',
    kind: 'module',
    official: "Python interface for the 'lsprof' profiler.",
    source: DOC,
    when: 'You want to know which functions your program spends its time in, before you try to speed anything up. The profiler slows every function call a little, so time your final fix with timeit, not with cProfile.',
    flags: [
      ['-s cumulative', 'sort the table by cumulative time'],
      ['-o file', 'save the results to a file for pstats or snakeviz'],
    ],
    example: { command: 'python -m cProfile -s cumulative sim_script.py', says: 'Runs the script under the profiler and prints one row per function, the biggest total time first.' },
    seeAlso: ['cProfile.Profile', 'pstats', 'timeit'],
  },
  {
    name: 'cProfile.Profile',
    lang: 'python',
    kind: 'class',
    official: 'Builds a profiler object using the specified timer function.',
    source: DOC,
    when: 'Profile just one part of a program: run it inside a with block, then hand the profiler to pstats.Stats to sort and print the table.',
    example: {
      command: 'with cProfile.Profile() as pr:\n    sim.run_all()',
      says: 'Records every function call made by sim.run_all(). pstats.Stats(pr) then sorts and prints them.',
    },
    seeAlso: ['pstats.Stats', 'cProfile'],
  },
  {
    name: 'cmath',
    lang: 'python',
    kind: 'module',
    official: 'This module provides access to mathematical functions for complex numbers.',
    source: DOC,
    when: 'You need square roots, exponentials or trig of complex numbers. The math versions refuse: math.sqrt(-1) raises ValueError, while cmath.sqrt(-1) gives 1j.',
    example: { command: 'cmath.sqrt(-1)', says: 'Returns 1j, the imaginary unit.' },
    seeAlso: ['math', 'complex'],
  },
  {
    name: 'cmath.cos',
    lang: 'python',
    kind: 'function',
    official: 'Return the cosine of z.',
    source: DOC,
    when: 'Cosine of a complex number, for example in the complex-step trick for exact derivatives. It accepts plain floats too, but always gives back a complex number.',
    example: { command: 'cmath.cos(1.0 + 1e-20j).imag / 1e-20', says: '-0.8414709848078965: the derivative of cos at 1, which is -sin(1), correct to every digit.' },
    seeAlso: ['math.cos', 'cmath.sin'],
  },
  {
    name: 'cmath.exp',
    aliases: ['cexp'],
    lang: 'python',
    kind: 'function',
    official: 'Return the exponential value e**z.',
    source: DOC,
    when: 'e to the power of a complex number, the heart of Euler\'s formula e^(i x) = cos x + i sin x. The answer is always complex, even for a real input.',
    example: { command: 'cmath.exp(1j * cmath.pi)', says: '(-1+1.2246467991473532e-16j): e to the i pi is -1, plus a tiny rounding error.' },
    seeAlso: ['math.exp', 'cmath.sin'],
  },
  {
    name: 'cmath.sin',
    aliases: ['csin'],
    lang: 'python',
    kind: 'function',
    official: 'Return the sine of z.',
    source: DOC,
    when: 'Sine of a complex number, for example in the complex-step trick for exact derivatives. The answer is always complex.',
    example: { command: 'cmath.sin(1.0 + 1e-20j).imag / 1e-20', says: '0.5403023058681398, which is cos(1): the derivative of sin at 1.' },
    seeAlso: ['math.sin', 'cmath.cos'],
  },
  {
    name: 'cmath.sqrt',
    lang: 'python',
    kind: 'function',
    official: 'Return the square root of z.',
    source: DOC,
    when: 'A square root that works for negative and complex numbers. The answer is always complex, even when it is a whole number like 2.',
    example: { command: 'cmath.sqrt(-4)', says: 'Returns 2j. math.sqrt(-4) would raise ValueError.' },
    seeAlso: ['math.sqrt', 'cmath.exp'],
  },
  {
    name: 'collections',
    lang: 'python',
    kind: 'module',
    official: "This module implements specialized container datatypes providing alternatives to Python's general purpose built-in containers, dict, list, set, and tuple.",
    source: DOC,
    when: 'Plain dicts, lists and tuples cover most jobs. Reach for collections when you are counting (Counter), filling a dict without checking keys (defaultdict), running a fast queue (deque), or want a tuple with names (namedtuple).',
    example: { command: 'from collections import Counter, defaultdict, deque', says: 'Brings in three of its containers so you can use them without the collections. prefix.' },
    seeAlso: ['collections.Counter', 'collections.defaultdict', 'collections.deque', 'collections.namedtuple'],
  },
  {
    name: 'collections.Counter',
    aliases: ['Counter'],
    lang: 'python',
    kind: 'class',
    official: 'Dict subclass for counting hashable items.',
    source: DOC,
    when: 'Count how many times each thing appears. A missing key counts as 0 instead of raising KeyError. It prints as Counter({...}), so wrap it in dict(...) when a plain dict is expected.',
    flags: [['.most_common(n)', 'the n most frequent items as (item, count) pairs, biggest first']],
    example: { command: 'Counter("mississippi").most_common(2)', says: "[('i', 4), ('s', 4)]: the two most common letters and their counts." },
    seeAlso: ['collections.Counter.most_common', 'collections.defaultdict', 'dict'],
  },
  {
    name: 'collections.abc',
    lang: 'python',
    kind: 'module',
    official: 'Abstract Base Classes (ABCs) for collections, according to PEP 3119.',
    source: 'Python standard library docstring (Python 3.13)',
    when: 'It holds classes that describe what a container can do, such as Sequence, Mapping and Iterable. Use them in type hints to accept any container that behaves the right way, not only a list.',
    example: { command: 'from collections.abc import Sequence', says: 'Brings in Sequence for type hints like xs: Sequence[float].' },
    seeAlso: ['collections.abc.Sequence', 'typing'],
  },
  {
    name: 'collections.abc.Sequence',
    aliases: ['Sequence'],
    lang: 'python',
    kind: 'class',
    official: 'All the operations on a read-only sequence.',
    source: DOC,
    when: 'A type hint for a parameter that only needs to be indexed and measured with len: a list, a tuple and a range all fit. Watch out: a str is a Sequence too, so isinstance(x, Sequence) is True for text.',
    example: { command: 'def mean(xs: Sequence[float]) -> float:', says: 'Says mean takes any ordered, indexable collection of floats, such as a list or a tuple.' },
    seeAlso: ['typing.Sequence', 'collections.abc'],
  },
  {
    name: 'collections.defaultdict',
    aliases: ['defaultdict'],
    lang: 'python',
    kind: 'class',
    official: 'The default factory is called without arguments to produce a new value when a key is not present, in __getitem__ only.',
    source: DOC,
    when: 'Group or count into a dict without checking whether each key exists first. Pass the function, not a call: defaultdict(list), not defaultdict(list()). Watch out: even just reading a missing key adds it.',
    example: {
      command: 'groups = defaultdict(list)\ngroups["LOX"].append(3.2)',
      says: 'No KeyError: the missing key "LOX" gets a new empty list, and 3.2 goes into it.',
    },
    seeAlso: ['collections.Counter', 'dict.setdefault', 'dict'],
  },
  {
    name: 'collections.deque',
    aliases: ['deque'],
    lang: 'python',
    kind: 'class',
    official: 'A list-like sequence optimized for data accesses near its endpoints.',
    source: DOC,
    when: 'A queue: add at one end and take from the other, both fast. list.pop(0) shifts every item and slows down on long lists; deque.popleft() does not. With maxlen it keeps only the most recent items.',
    flags: [
      ['maxlen=', 'keep at most this many items; old ones fall off the other end'],
      ['.append(x)', 'add at the back'],
      ['.popleft()', 'remove and return the item at the front'],
    ],
    example: {
      command: 'last3 = deque([1, 2, 3], maxlen=3)\nlast3.append(4)',
      says: 'last3 is now deque([2, 3, 4], maxlen=3): the oldest reading fell off the front.',
    },
    seeAlso: ['collections.deque.popleft', 'collections.deque.appendleft', 'list.pop'],
  },
  {
    name: 'collections.namedtuple',
    aliases: ['namedtuple'],
    lang: 'python',
    kind: 'function',
    official: 'Returns a new subclass of tuple with named fields.',
    source: DOC,
    when: 'A small fixed bundle of values where each position has a name, such as a reading with a time and a value. It is still a tuple, so you cannot change a field after making it.',
    flags: [
      ['"Point"', 'the type name, used when it prints'],
      ['["x", "y"]', 'the field names, in order'],
    ],
    example: {
      command: 'Point = namedtuple("Point", ["x", "y"])\np = Point(3, 4)',
      says: 'p.x is 3 and p.y is 4, and p still unpacks and indexes like a tuple.',
    },
    seeAlso: ['dataclasses.dataclass', 'tuple'],
  },
  {
    name: 'concurrent.futures',
    lang: 'python',
    kind: 'module',
    official: 'Execute computations asynchronously using threads or processes.',
    source: DOC,
    when: 'Run the same function on many inputs in parallel, with a pool of threads or processes behind a few simple methods: map, submit and as_completed.',
    example: { command: 'from concurrent.futures import ProcessPoolExecutor', says: 'Brings in the process pool so you can write ProcessPoolExecutor(...) directly.' },
    seeAlso: ['concurrent.futures.ProcessPoolExecutor', 'concurrent.futures.ThreadPoolExecutor', 'multiprocessing'],
  },
  {
    name: 'concurrent.futures.ProcessPoolExecutor',
    aliases: ['ProcessPoolExecutor'],
    lang: 'python',
    kind: 'class',
    official: 'An Executor subclass that executes calls asynchronously using a pool of at most max_workers processes.',
    source: REF,
    when: 'CPU-heavy pure-Python work, like Monte Carlo cases, that you want spread across your cores. Each worker is a separate Python, so the function and its arguments must be picklable (savable as bytes), and the pool should be started under if __name__ == "__main__":.',
    flags: [
      ['max_workers=', 'how many processes run at once'],
      ['initializer= / initargs=', 'a function run once in each new worker, and its arguments'],
      ['.map(f, xs)', 'call f on every item; results come back in input order'],
      ['.submit(f, x)', 'start one call and get a future back right away'],
    ],
    example: {
      command: 'with ProcessPoolExecutor(max_workers=4) as ex:\n    miss = list(ex.map(run_case, seeds))',
      says: 'Runs run_case on every seed, four processes at a time, with results in the same order as seeds.',
    },
    seeAlso: ['concurrent.futures.ThreadPoolExecutor', 'concurrent.futures.as_completed', 'multiprocessing.Pool'],
  },
  {
    name: 'concurrent.futures.ThreadPoolExecutor',
    aliases: ['ThreadPoolExecutor'],
    lang: 'python',
    kind: 'class',
    official: 'An Executor subclass that uses a pool of at most max_workers threads to execute calls asynchronously.',
    source: REF,
    when: 'Many tasks that mostly wait, such as downloads or file reads, or code that lets go of the GIL, like NumPy or a C++ extension. For pure-Python number crunching the threads take turns under the GIL and give little or no speed-up; use ProcessPoolExecutor.',
    flags: [
      ['max_workers=', 'how many threads run at once'],
      ['.map(f, xs)', 'call f on every item; results come back in input order'],
      ['.submit(f, x)', 'start one call and get a future back right away'],
    ],
    example: {
      command: 'with ThreadPoolExecutor(max_workers=8) as pool:\n    sizes = list(pool.map(fetch, urls))',
      says: 'Fetches up to eight URLs at once and returns the results in the same order as urls.',
    },
    seeAlso: ['concurrent.futures.ProcessPoolExecutor', 'asyncio'],
  },
  {
    name: 'concurrent.futures.as_completed',
    aliases: ['as_completed'],
    lang: 'python',
    kind: 'function',
    official: 'An iterator over the given futures that yields each as it completes.',
    source: DOC,
    when: 'You started calls with submit and want each result as soon as it is ready, for example to print progress. They arrive in the order they finish, not the order they started, so keep a dict from each future to its case number.',
    example: {
      command: 'for fut in as_completed(futures):\n    print(fut.result())',
      says: 'Prints each result the moment its case finishes, fastest first.',
    },
    seeAlso: ['concurrent.futures.ProcessPoolExecutor', 'asyncio.gather'],
  },
  {
    name: 'contextlib',
    lang: 'python',
    kind: 'module',
    official: 'Utilities for with-statement contexts.',
    source: DOC,
    when: 'Ready-made helpers for with blocks: build a context manager from a small generator (contextmanager), or ignore one kind of error (suppress).',
    example: { command: 'from contextlib import contextmanager', says: 'Brings in the decorator that turns a generator into a context manager.' },
    seeAlso: ['contextlib.contextmanager', 'contextlib.suppress', 'with'],
  },
  {
    name: 'contextlib.contextmanager',
    aliases: ['contextmanager'],
    lang: 'python',
    kind: 'function',
    official: 'This function is a decorator that can be used to define a factory function for with statement context managers, without needing to create a class or separate __enter__() and __exit__() methods.',
    source: REF,
    when: 'Write a small context manager as a generator instead of a class: the code before yield is the setup, the code after it is the clean-up. Put the yield inside try / finally, or the clean-up is skipped when the with block raises an error.',
    example: {
      command: '@contextmanager\ndef opened(valve):\n    valve.open()\n    try:\n        yield valve\n    finally:\n        valve.close()',
      says: 'with opened(v): ... opens the valve for the block and always closes it afterward, even after an error.',
    },
    seeAlso: ['with', 'yield', 'contextlib.suppress'],
  },
  {
    name: 'contextlib.suppress',
    lang: 'python',
    kind: 'class',
    official: 'Context manager to suppress specified exceptions',
    source: DOC,
    when: 'Ignore one named kind of error inside a with block, such as deleting a file that may already be gone. Only the types you name are ignored, and the rest of the block after the error is skipped.',
    example: {
      command: 'with contextlib.suppress(FileNotFoundError):\n    os.remove("old_run.csv")',
      says: 'Deletes old_run.csv if it is there and carries on quietly if it is not.',
    },
    seeAlso: ['contextlib.contextmanager', 'try', 'FileNotFoundError'],
  },
  {
    name: 'copy',
    lang: 'python',
    kind: 'module',
    official: 'Generic (shallow and deep) copying operations.',
    source: DOC,
    when: 'You need a real copy of an object. Remember b = a never copies anything; it only gives the same object a second name.',
    example: { command: 'import copy', says: 'Makes copy.deepcopy available.' },
    seeAlso: ['copy.deepcopy', 'list.copy'],
  },
  {
    name: 'copy.deepcopy',
    lang: 'python',
    kind: 'function',
    official: 'Deep copy operation on arbitrary Python objects.',
    source: DOC,
    when: 'You need a fully separate copy of nested data, such as a dict of lists, so changing the copy never touches the original. Watch out: .copy(), list(x) and x[:] are shallow, so the inner lists are still shared.',
    example: { command: 'snapshot = copy.deepcopy(state)', says: 'snapshot gets its own copy of every inner list and dict; later changes to state do not show up in it.' },
    seeAlso: ['list.copy', 'is'],
  },
  {
    name: 'csv',
    lang: 'python',
    kind: 'module',
    official: 'CSV parsing and writing.',
    source: DOC,
    when: 'Read and write CSV files: comma-separated values, one row per line. It handles quoting for you, such as a comma inside a name. Every value it reads is a string, so convert numbers with float() or int(), and open files with newline="".',
    example: { command: 'import csv', says: 'Makes csv.reader, csv.writer, csv.DictReader and csv.DictWriter available.' },
    seeAlso: ['csv.DictReader', 'csv.writer', 'open'],
  },
  {
    name: 'csv.DictReader',
    lang: 'python',
    kind: 'class',
    official: 'Create an object that operates like a regular reader but maps the information in each row to a dict whose keys are given by the optional fieldnames parameter.',
    source: REF,
    when: 'Read a CSV file that has a header line and get each row as a dict keyed by column name, so your code does not depend on column order. The values are still strings: row["ax"] is "9.79", not 9.79.',
    flags: [['f', 'an open file, or an io.StringIO holding CSV text']],
    example: { command: 'rows = list(csv.DictReader(f))', says: 'Reads every data row. rows[0]["ax"] is the text in the ax column of the first one.' },
    seeAlso: ['csv.reader', 'csv.DictWriter', 'io.StringIO'],
  },
  {
    name: 'csv.DictWriter',
    lang: 'python',
    kind: 'class',
    official: 'Create an object which operates like a regular writer but maps dictionaries onto output rows.',
    source: REF,
    when: 'Write a list of dicts as CSV rows under a header. A dict with a key that is not in fieldnames raises ValueError.',
    flags: [
      ['fieldnames=', 'the column names, in the order to write them'],
      ['.writeheader()', 'write the header row'],
      ['.writerows(rows)', 'write a list of dicts, one row each'],
    ],
    example: {
      command: 'writer = csv.DictWriter(f, fieldnames=["t", "ax", "ay", "az"])\nwriter.writeheader()',
      says: 'Writes the header line t,ax,ay,az. writer.writerows(rows) then adds one line per dict.',
    },
    seeAlso: ['csv.DictReader', 'csv.writer'],
  },
  {
    name: 'csv.reader',
    lang: 'python',
    kind: 'function',
    official: 'The returned object is an iterator. Each iteration returns a row of the CSV file (which can span multiple input lines).',
    source: DOC,
    when: 'Read CSV as plain lists of strings, one list per row, header included. Nothing is converted, so \'9.79\' stays text until you call float().',
    example: { command: 'list(csv.reader(["t,alt_m", "0.5,12.5"]))', says: "[['t', 'alt_m'], ['0.5', '12.5']]: lists of strings, header row included." },
    seeAlso: ['csv.DictReader', 'csv.writer', 'float'],
  },
  {
    name: 'csv.writer',
    lang: 'python',
    kind: 'function',
    official: "Return a writer object responsible for converting the user's data into delimited strings on the given file-like object.",
    source: REF,
    when: 'Turn lists into CSV text. By default it ends each row with \\r\\n; pass lineterminator="\\n" for plain newlines, and open real files with newline="" to avoid blank lines on Windows.',
    flags: [
      ['lineterminator=', 'what ends each row'],
      ['.writerow(row)', 'write one list as one row'],
      ['.writerows(rows)', 'write a list of rows'],
    ],
    example: {
      command: 'writer = csv.writer(out, lineterminator="\\n")\nwriter.writerows([["t", "alt"], [0, 12.5]])',
      says: 'Writes two lines into out: t,alt and 0,12.5.',
    },
    seeAlso: ['csv.reader', 'csv.DictWriter', 'io.StringIO'],
  },
  {
    name: 'dataclasses',
    lang: 'python',
    kind: 'module',
    official: 'This module provides a decorator and functions for automatically adding generated special methods such as __init__() and __repr__() to user-defined classes.',
    source: REF,
    when: 'You are writing a class that mostly holds data. The module holds the @dataclass decorator and its helpers: field, asdict, astuple and replace.',
    example: { command: 'from dataclasses import dataclass, field', says: 'Brings in the decorator and the field helper.' },
    seeAlso: ['dataclasses.dataclass', 'dataclasses.field', 'dataclasses.asdict'],
  },
  {
    name: 'dataclasses.FrozenInstanceError',
    lang: 'python',
    kind: 'exception',
    official: 'Raised when an implicitly defined __setattr__() or __delattr__() is called on a dataclass which was defined with frozen=True. It is a subclass of AttributeError.',
    source: REF,
    when: 'This is the error you get when you try to change a field of a @dataclass(frozen=True) object. It is a kind of AttributeError, so except AttributeError catches it too. To get a changed version, use dataclasses.replace.',
    example: { command: 'p.x = 5', says: "On a frozen dataclass, raises dataclasses.FrozenInstanceError: cannot assign to field 'x'." },
    seeAlso: ['dataclasses.dataclass', 'dataclasses.replace', 'AttributeError'],
  },
  {
    name: 'dataclasses.asdict',
    aliases: ['asdict'],
    lang: 'python',
    kind: 'function',
    official: 'Return the fields of a dataclass instance as a new dictionary mapping field names to field values.',
    source: DOC,
    when: 'Turn a dataclass object into a plain dict, for example to pass to json.dumps. It also converts dataclasses, lists and dicts nested inside, all the way down.',
    example: { command: 'asdict(Stage("S1", 5200.0))', says: "{'name': 'S1', 'mass_kg': 5200.0}, for a dataclass Stage with fields name and mass_kg." },
    seeAlso: ['dataclasses.astuple', 'json.dumps', 'dataclasses.dataclass'],
  },
  {
    name: 'dataclasses.astuple',
    lang: 'python',
    kind: 'function',
    official: 'Return the fields of a dataclass instance as a new tuple of field values.',
    source: DOC,
    when: 'Get a dataclass object\'s field values as a plain tuple, in the order the fields are written in the class.',
    example: { command: 'dataclasses.astuple(Stage("S1", 5200.0))', says: "('S1', 5200.0)" },
    seeAlso: ['dataclasses.asdict'],
  },
  {
    name: 'dataclasses.dataclass',
    aliases: ['dataclass'],
    lang: 'python',
    kind: 'function',
    official: 'Add dunder methods based on the fields defined in the class.',
    source: DOC,
    when: 'A class that mostly holds data. List the fields with type hints and @dataclass writes __init__, __repr__ and __eq__ for you. Watch out: a list or dict default must be written field(default_factory=list); a plain [] raises ValueError.',
    flags: [
      ['frozen=True', 'objects cannot be changed after they are made'],
      ['order=True', 'also write <, <=, > and >=, comparing the fields in order'],
    ],
    example: {
      command: '@dataclass(frozen=True)\nclass Reading:\n    t: float\n    alt_m: float',
      says: 'Reading(0.5, 120.0) now works, prints as Reading(t=0.5, alt_m=120.0), and cannot be changed afterward.',
    },
    seeAlso: ['dataclasses.field', 'dataclasses.replace', 'collections.namedtuple'],
  },
  {
    name: 'dataclasses.field',
    aliases: ['field'],
    lang: 'python',
    kind: 'function',
    official: 'Return an object to identify dataclass fields.',
    source: DOC,
    when: 'Give one dataclass field extra settings. Most often it is a list default, where every object needs its own new list.',
    flags: [
      ['default_factory=', 'a function called to make a fresh default for each object, such as list'],
      ['default=', 'a plain default value'],
      ['compare=False', 'leave this field out of == and ordering'],
    ],
    example: { command: 'tags: list[str] = field(default_factory=list)', says: 'Each new object gets its own empty list instead of all of them sharing one.' },
    seeAlso: ['dataclasses.dataclass'],
  },
  {
    name: 'dataclasses.replace',
    lang: 'python',
    kind: 'function',
    official: 'Return a new object replacing specified fields with new values.',
    source: DOC,
    when: 'Get a changed copy of a dataclass object while the original stays as it was. It is how you "change" a frozen dataclass. The copy is shallow: a list field is shared with the original.',
    example: { command: 'later = replace(reading, alt_m=130.0)', says: 'A new Reading with the same t and alt_m set to 130.0; reading itself is unchanged.' },
    seeAlso: ['dataclasses.dataclass', 'dataclasses.FrozenInstanceError'],
  },
  {
    name: 'datetime',
    lang: 'python',
    kind: 'module',
    official: 'Fast implementation of the datetime type.',
    source: DOC,
    when: 'Dates, times and lengths of time: date, datetime, timedelta and timezone. Watch out: the module and the class inside it are both called datetime, so datetime.datetime.now() is module, then class, then method.',
    example: { command: 'from datetime import date, timedelta', says: 'Brings in the date and timedelta classes so you can use them without a prefix.' },
    seeAlso: ['datetime.date', 'datetime.datetime', 'datetime.timedelta', 'time'],
  },
  {
    name: 'datetime.date',
    aliases: ['date'],
    lang: 'python',
    kind: 'class',
    official: 'An idealized naive date, assuming the current Gregorian calendar always was, and always will be, in effect.',
    source: REF,
    when: 'A calendar day with no time: year, month, day. Dates can be compared and subtracted, and a date plus a timedelta is another date. Months count from 1, so date(2026, 1, 10) is January 10.',
    flags: [['.today()', 'the date on the computer\'s clock right now']],
    example: { command: 'date(2026, 3, 1) + timedelta(days=14)', says: 'datetime.date(2026, 3, 15): two weeks later.' },
    seeAlso: ['datetime.timedelta', 'datetime.date.isoformat', 'datetime.date.fromisoformat'],
  },
  {
    name: 'datetime.date.fromisoformat',
    aliases: ['date.fromisoformat'],
    lang: 'python',
    kind: 'function',
    official: 'Construct a date from a string in ISO 8601 format.',
    source: DOC,
    when: 'Turn text like "2026-03-15" back into a date, for example when loading JSON. Text in any other shape raises ValueError.',
    example: { command: 'date.fromisoformat("2026-03-15")', says: 'datetime.date(2026, 3, 15)' },
    seeAlso: ['datetime.date.isoformat', 'datetime.date'],
  },
  {
    name: 'datetime.datetime',
    aliases: ['dt.datetime'],
    lang: 'python',
    kind: 'class',
    official: 'A datetime object is a single object containing all the information from a date object and a time object.',
    source: REF,
    when: 'A date plus a time of day, down to microseconds. Without tzinfo it is "naive" and does not know its time zone; for flight data always pass tzinfo=timezone.utc. Comparing a naive datetime with one that has a zone raises TypeError.',
    flags: [['tzinfo=', 'the time zone; use timezone.utc for UTC']],
    example: { command: 't = datetime(2026, 9, 22, 12, 0, 0, tzinfo=timezone.utc)', says: 'Noon UTC on September 22, 2026.' },
    seeAlso: ['datetime.timezone.utc', 'datetime.timedelta', 'datetime.datetime.now'],
  },
  {
    name: 'datetime.datetime.now',
    aliases: ['datetime.now'],
    lang: 'python',
    kind: 'function',
    official: 'Returns new datetime object representing current time local to tz.',
    source: DOC,
    when: 'Read the clock: the current date and time. Watch out: as a default argument, def stamp(t=datetime.now()) runs only once, when the function is defined, so every call gets the same time. Use None as the default and call now() inside.',
    flags: [['tz', 'pass timezone.utc to get the time in UTC, with the zone attached']],
    example: { command: 'datetime.now(timezone.utc)', says: 'The current time in UTC, such as 2026-09-29 14:03:12.401233+00:00.' },
    seeAlso: ['datetime.datetime', 'time.perf_counter'],
  },
  {
    name: 'datetime.timedelta',
    aliases: ['timedelta'],
    lang: 'python',
    kind: 'class',
    official: 'Difference between two datetime values.',
    source: DOC,
    when: 'A length of time, like 14 days or 18 seconds. Add it to a date or datetime to move forward and subtract it to move back; subtracting one datetime from another gives you one.',
    flags: [
      ['days=', 'a number of days'],
      ['seconds=', 'a number of seconds'],
    ],
    example: { command: 't_gps = t_utc + timedelta(seconds=18)', says: 'The time 18 seconds after t_utc: the gap between GPS time and UTC.' },
    seeAlso: ['datetime.date', 'datetime.datetime'],
  },
  {
    name: 'datetime.timezone',
    aliases: ['timezone'],
    lang: 'python',
    kind: 'class',
    official: 'Fixed offset from UTC implementation of tzinfo.',
    source: DOC,
    when: 'A fixed offset from UTC. Almost always you want its ready-made timezone.utc. It knows nothing about daylight saving time, so a named zone like America/New_York needs zoneinfo instead.',
    example: { command: 'timezone(timedelta(hours=-5))', says: 'A zone five hours behind UTC, which prints as UTC-05:00.' },
    seeAlso: ['datetime.timezone.utc', 'datetime.datetime'],
  },
  {
    name: 'datetime.timezone.utc',
    aliases: ['timezone.utc', 'dt.timezone.utc'],
    lang: 'python',
    kind: 'constant',
    official: 'The UTC timezone, timezone(timedelta(0)).',
    source: REF,
    when: 'Pass it as tzinfo= so a datetime is clearly in UTC, the time flight and ground systems log in. A datetime with a zone and one without cannot be compared or subtracted.',
    example: { command: 'GPS_EPOCH = datetime(1980, 1, 6, tzinfo=timezone.utc)', says: 'The start of GPS time: midnight UTC on January 6, 1980.' },
    seeAlso: ['datetime.datetime', 'datetime.timezone'],
  },
  {
    name: 'decimal',
    lang: 'python',
    kind: 'module',
    official: 'C decimal arithmetic module',
    source: DOC,
    when: 'Exact decimal arithmetic, for money and anything else that must add up to the cent. Floats store numbers in binary, so 0.1 + 0.2 is not exactly 0.3; with Decimal it is.',
    example: { command: 'from decimal import Decimal', says: 'Brings in the Decimal type.' },
    seeAlso: ['decimal.Decimal', 'float'],
  },
  {
    name: 'decimal.Decimal',
    aliases: ['Decimal'],
    lang: 'python',
    kind: 'class',
    official: 'Construct a new Decimal object.',
    source: DOC,
    when: 'Make it from a string, like Decimal("0.10"). Made from a float, Decimal(0.1) keeps the float\'s tiny binary error. sum() of an empty list gives the int 0, so pass Decimal("0") as the start value.',
    example: { command: 'Decimal("0.10") + Decimal("0.20") == Decimal("0.30")', says: 'True, exactly. The same sum with floats gives False.' },
    seeAlso: ['float', 'round', 'sum'],
  },
  {
    name: 'enum',
    lang: 'python',
    kind: 'module',
    official: 'Implementation of an enumeration class.',
    source: REF,
    when: 'You want a fixed set of named choices, such as flight modes, instead of loose strings or numbers. The module holds the Enum base class.',
    example: { command: 'from enum import Enum', says: 'Brings in Enum so you can write class Mode(Enum):.' },
    seeAlso: ['enum.Enum'],
  },
  {
    name: 'enum.Enum',
    aliases: ['Enum'],
    lang: 'python',
    kind: 'class',
    official: 'Create a collection of name/value pairs.',
    source: DOC,
    when: 'Inherit from it to make a fixed set of named values, so a typo becomes an error instead of a silently wrong string. Compare members with is. Plain members cannot be compared with <, so sort on .value.',
    example: {
      command: 'class Mode(Enum):\n    PAD = 1\n    ASCENT = 2',
      says: 'Mode.ASCENT.value is 2, Mode(2) is Mode.ASCENT, and list(Mode) gives both members in order.',
    },
    seeAlso: ['class', 'is'],
  },
  {
    name: 'functools',
    lang: 'python',
    kind: 'module',
    official: 'functools.py - Tools for working with functions and callable objects',
    source: DOC,
    when: 'Tools that take or give back functions: remember answers (lru_cache), fill in arguments ahead of time (partial), fold a list into one value (reduce), and keep a decorated function\'s name (wraps).',
    example: { command: 'from functools import lru_cache, partial, reduce', says: 'Brings in three of its tools so you can use them without a prefix.' },
    seeAlso: ['functools.lru_cache', 'functools.partial', 'functools.reduce', 'functools.wraps'],
  },
  {
    name: 'functools.cached_property',
    aliases: ['cached_property'],
    lang: 'python',
    kind: 'class',
    official: 'Transform a method of a class into a property whose value is computed once and then cached as a normal attribute for the life of the instance.',
    source: REF,
    when: 'A property that is slow to work out and does not change: the method runs on the first read, and the result is stored on the object for every later read. If the data it depends on changes, the stored value goes stale until you del it.',
    example: {
      command: '@cached_property\ndef summary(self): ...',
      says: 'The first obj.summary runs the method; every later read returns the saved result.',
    },
    seeAlso: ['property', 'functools.lru_cache'],
  },
  {
    name: 'functools.lru_cache',
    aliases: ['lru_cache'],
    lang: 'python',
    kind: 'function',
    official: 'Least-recently-used cache decorator.',
    source: DOC,
    when: 'A function that gets called again and again with the same arguments, such as a recursive one, can remember its answers. The arguments must be hashable: passing a list raises TypeError.',
    flags: [['maxsize=', 'how many answers to remember; None means no limit']],
    example: {
      command: '@lru_cache(maxsize=None)\ndef fib(n): return n if n < 2 else fib(n - 1) + fib(n - 2)',
      says: 'fib(80) now returns at once, because each fib(k) is worked out only one time.',
    },
    seeAlso: ['functools.cached_property', 'hash'],
  },
  {
    name: 'functools.partial',
    aliases: ['partial'],
    lang: 'python',
    kind: 'class',
    official: 'partial(func, *args, **keywords) - new function with partial application of the given arguments and keywords.',
    source: DOC,
    when: 'Make a new function with some arguments already filled in. Watch out: positional values fill from the left, so partial(power, 2) fixes the base, not the exponent; use a keyword such as exp=2 for a later one.',
    example: { command: 'int_from_binary = partial(int, base=2)', says: 'int_from_binary("101") returns 5.' },
    seeAlso: ['lambda', 'functools.reduce'],
  },
  {
    name: 'functools.reduce',
    aliases: ['reduce'],
    lang: 'python',
    kind: 'function',
    official: 'Apply a function of two arguments cumulatively to the items of a sequence or iterable, from left to right, so as to reduce the iterable to a single value.',
    source: DOC,
    when: 'Combine a whole list into one value by applying a two-argument function again and again, left to right. Give a start value as the third argument: on an empty list without one, it raises TypeError. For plain sums and products, sum() and math.prod() read better.',
    example: { command: 'reduce(lambda acc, x: acc * x, [2, 3, 4], 1)', says: '24, worked out as ((1 * 2) * 3) * 4.' },
    seeAlso: ['sum', 'itertools.accumulate', 'lambda'],
  },
  {
    name: 'functools.wraps',
    aliases: ['wraps'],
    lang: 'python',
    kind: 'function',
    official: 'Decorator factory to apply update_wrapper() to a wrapper function',
    source: DOC,
    when: 'Put @functools.wraps(func) on the wrapper inside every decorator you write. It copies the original function\'s name and docstring onto the wrapper; without it, help(), tracebacks and inspect.signature all see a function called wrapper.',
    example: {
      command: '@functools.wraps(func)\ndef wrapper(*args, **kwargs):',
      says: 'wrapper now reports the name and docstring of func.',
    },
    seeAlso: ['inspect.signature', 'def'],
  },
  {
    name: 'hashlib',
    lang: 'python',
    kind: 'module',
    official: 'hashlib module - A common interface to many hash functions.',
    source: DOC,
    when: 'Compute a hash: a short fingerprint of some bytes that changes completely if even one byte changes. Used to check downloads, name git objects and pin exact package files.',
    example: { command: 'import hashlib', says: 'Makes hashlib.sha256 and the other hash functions available.' },
    seeAlso: ['hashlib.sha256', 'hmac'],
  },
  {
    name: 'hashlib.sha1',
    lang: 'python',
    kind: 'function',
    official: 'Returns a sha1 hash object; optionally initialized with a string',
    source: DOC,
    when: 'SHA-1 is the hash git uses to name its objects. It is no longer safe against deliberate forgery, so use sha256 for anything to do with security.',
    example: { command: 'hashlib.sha1(b"hello").hexdigest()', says: 'aaf4c61ddcc5e8a2dabede0f3b482cd9aea9434d: 40 hex characters.' },
    seeAlso: ['hashlib.sha256'],
  },
  {
    name: 'hashlib.sha256',
    lang: 'python',
    kind: 'function',
    official: 'Returns a sha256 hash object; optionally initialized with a string',
    source: DOC,
    when: 'Fingerprint some bytes: check that a wheel is exactly the file you expect, or tag a result so you can tell later whether it changed. It takes bytes, so call .encode() on a str first.',
    flags: [
      ['.hexdigest()', 'the hash as 64 hex characters'],
      ['.digest()', 'the hash as 32 raw bytes'],
    ],
    example: { command: 'hashlib.sha256("orbit".encode()).hexdigest()[:12]', says: '4fa1a13ac468: a short fingerprint. The same text always gives the same one.' },
    seeAlso: ['hashlib.sha1', 'hmac.new', 'str.encode'],
  },
  {
    name: 'heapq',
    lang: 'python',
    kind: 'module',
    official: 'Heap queue algorithm (a.k.a. priority queue).',
    source: DOC,
    when: 'Keep a plain list arranged so the smallest item is always at position 0, which makes a priority queue. Adding and removing each take O(log n). Watch out: only heap[0] is in order, not the rest, and it is always the smallest; push negated numbers to get the largest.',
    example: { command: 'import heapq', says: 'Makes heapq.heappush, heapq.heappop and heapq.nlargest available.' },
    seeAlso: ['heapq.heappush', 'heapq.heappop', 'bisect'],
  },
  {
    name: 'heapq.heappop',
    lang: 'python',
    kind: 'function',
    official: 'Pop the smallest item off the heap, maintaining the heap invariant.',
    source: DOC,
    when: 'Take the smallest item off a heap list. It raises IndexError when the heap is empty.',
    example: { command: 'heapq.heappop(todo)', says: "(1, 'launch'): the tuple with the smallest first number comes out first." },
    seeAlso: ['heapq.heappush'],
  },
  {
    name: 'heapq.heappush',
    lang: 'python',
    kind: 'function',
    official: 'Push item onto heap, maintaining the heap invariant.',
    source: DOC,
    when: 'Add an item to a heap list and keep the heap order. Push tuples like (priority, name) to order by priority; when two priorities tie, the names are compared next.',
    example: { command: 'heapq.heappush(todo, (1, "launch"))', says: 'Adds the job with priority 1. heapq.heappop(todo) will hand it out before any bigger number.' },
    seeAlso: ['heapq.heappop', 'bisect.insort'],
  },
  {
    name: 'heapq.nlargest',
    lang: 'python',
    kind: 'function',
    official: 'Find the n largest elements in a dataset.',
    source: DOC,
    when: 'Get the n biggest items, largest first, without sorting everything. It copes with n bigger than the list. For just one item, max() is simpler.',
    example: { command: 'heapq.nlargest(2, [5, 1, 8, 3, 9])', says: '[9, 8]' },
    seeAlso: ['max', 'sorted'],
  },
  {
    name: 'hmac',
    lang: 'python',
    kind: 'module',
    official: 'HMAC (Keyed-Hashing for Message Authentication) module.',
    source: DOC,
    when: 'Prove a message came from someone who knows a secret key and was not changed on the way. A plain hash cannot do that, because anyone who changes the message can recompute it.',
    example: { command: 'import zlib, hmac, hashlib', says: 'Brings in the checksum, keyed-hash and hash modules the command lesson uses.' },
    seeAlso: ['hmac.new', 'hmac.compare_digest', 'hashlib'],
  },
  {
    name: 'hmac.compare_digest',
    lang: 'python',
    kind: 'function',
    official: "Return 'a == b'.",
    source: DOC,
    when: 'Compare two tags or tokens when checking a signature. Unlike ==, it takes the same time whether the first character differs or the last one, so an attacker cannot work out the tag by timing guesses.',
    example: { command: 'hmac.compare_digest(tag_received, tag_expected)', says: 'True only if the two tags are exactly the same.' },
    seeAlso: ['hmac.new'],
  },
  {
    name: 'hmac.new',
    lang: 'python',
    kind: 'function',
    official: 'Create a new hashing object and return it.',
    source: DOC,
    when: 'Compute the authentication tag for a command or message using a secret key. Both the key and the message must be bytes.',
    flags: [
      ['key', 'the secret, as bytes'],
      ['msg', 'the message, as bytes'],
      ['digestmod', 'the hash to use, such as hashlib.sha256'],
    ],
    example: { command: 'tag = hmac.new(key, cmd, hashlib.sha256).hexdigest()', says: 'The tag for cmd. Only someone who has key can make a matching one.' },
    seeAlso: ['hmac.compare_digest', 'hashlib.sha256'],
  },
  {
    name: 'importlib',
    lang: 'python',
    kind: 'module',
    official: 'A pure Python implementation of import.',
    source: DOC,
    when: 'Control importing from code: import a module whose name you only learn while the program runs, or read package data and version numbers through its submodules.',
    example: { command: 'import importlib.util', says: 'Brings in importlib and its util submodule.' },
    seeAlso: ['importlib.import_module', 'importlib.metadata', 'importlib.resources', 'import'],
  },
  {
    name: 'importlib.import_module',
    lang: 'python',
    kind: 'function',
    official: 'Import a module.',
    source: DOC,
    when: 'Import a module whose name you only have as a string, for example one read from a config file. It gives back the module object.',
    example: { command: 'backend = importlib.import_module("setuptools.build_meta")', says: 'The same as import setuptools.build_meta, but the name can come from a variable.' },
    seeAlso: ['import', 'importlib'],
  },
  {
    name: 'importlib.metadata',
    lang: 'python',
    kind: 'module',
    official: 'importlib.metadata is a library that provides access to the metadata of an installed Distribution Package, such as its entry points or its top-level names (Import Packages, modules, if any).',
    source: REF,
    when: 'Read facts about installed packages: which version is installed, and the entry points each one declares in its pyproject.toml.',
    example: { command: 'from importlib.metadata import version', says: 'Brings in version so you can ask what is installed.' },
    seeAlso: ['importlib.metadata.version', 'importlib.metadata.entry_points'],
  },
  {
    name: 'importlib.metadata.EntryPoint',
    aliases: ['EntryPoint'],
    lang: 'python',
    kind: 'class',
    official: 'An entry point as defined by Python packaging conventions.',
    source: DOC,
    when: 'One named pointer to a function in an installed package: what the [project.scripts] and entry-points tables in pyproject.toml create. Call .load() to import the function it points at.',
    flags: [
      ['name=', 'the entry point\'s name, such as the command name'],
      ['value=', '"module:function", the thing to load'],
      ['group=', 'the list it belongs to, such as console_scripts'],
      ['.load()', 'import the module and return the object'],
    ],
    example: {
      command: 'ep = EntryPoint(name="gnc-orbit", value="gnc.cli:main", group="console_scripts")',
      says: 'ep.load() imports gnc.cli and gives back its main function.',
    },
    seeAlso: ['importlib.metadata.entry_points'],
  },
  {
    name: 'importlib.metadata.entry_points',
    aliases: ['entry_points'],
    lang: 'python',
    kind: 'function',
    official: 'Return EntryPoint objects for all installed packages.',
    source: DOC,
    when: 'Find plugins: every installed package that joined a named group. If no package has joined, you get nothing back, not an error.',
    flags: [['group=', 'only the entry points in this group']],
    example: { command: 'for ep in entry_points(group="traj.guidance"):', says: 'Loops over every installed plugin in the traj.guidance group.' },
    seeAlso: ['importlib.metadata.EntryPoint'],
  },
  {
    name: 'importlib.metadata.version',
    aliases: ['version'],
    lang: 'python',
    kind: 'function',
    official: 'Get the version string for the named package.',
    source: DOC,
    when: 'Ask which version of a package is really installed, using the name you would pip install. It raises PackageNotFoundError when the package is not installed.',
    example: { command: 'print(version("gnc-toolkit"))', says: 'Prints the installed version, such as 0.3.0, read from the package\'s .dist-info folder.' },
    seeAlso: ['importlib.metadata'],
  },
  {
    name: 'importlib.resources',
    lang: 'python',
    kind: 'module',
    official: 'Read resources contained within a package.',
    source: DOC,
    when: 'Read data files that ship inside your package, such as an atmosphere table, wherever it got installed, instead of guessing paths.',
    example: { command: 'from importlib.resources import files', says: 'Brings in files, which finds a package\'s folder.' },
    seeAlso: ['importlib.resources.files', 'pathlib.Path'],
  },
  {
    name: 'importlib.resources.files',
    aliases: ['files'],
    lang: 'python',
    kind: 'function',
    official: 'Get a Traversable resource from a package',
    source: DOC,
    when: 'Find a data file that ships inside an installed package, wherever pip put it. Paths built from the current folder break once the package is installed somewhere else; this does not.',
    example: {
      command: 'json.loads(files("gnc").joinpath("data/earth.json").read_text())',
      says: 'Reads earth.json from inside the installed gnc package and turns it into a dict.',
    },
    seeAlso: ['importlib.resources', 'json.loads'],
  },
  {
    name: 'importlib.util',
    lang: 'python',
    kind: 'module',
    official: 'Utility code for constructing importers, etc.',
    source: DOC,
    when: 'Lower-level import helpers. The lessons use resolve_name to see exactly which module a relative import like ..constants points at.',
    example: { command: 'importlib.util.resolve_name("..constants", "gnc.nav")', says: "'gnc.constants': two dots go up from gnc.nav to gnc." },
    seeAlso: ['importlib', 'import'],
  },
  {
    name: 'inspect',
    lang: 'python',
    kind: 'module',
    official: 'Get useful information from live Python objects.',
    source: DOC,
    when: 'Look inside objects while the program runs: a function\'s parameters, its source code, whether it is a generator. Test tools use it to check code.',
    example: { command: 'inspect.isgeneratorfunction(read_numbers)', says: 'True if read_numbers has a yield in it.' },
    seeAlso: ['inspect.signature'],
  },
  {
    name: 'inspect.signature',
    lang: 'python',
    kind: 'function',
    official: 'Get a signature object for the passed callable.',
    source: DOC,
    when: 'See a function\'s real parameter list. A decorator without functools.wraps hides it, so the signature shows only (*args, **kwargs).',
    example: { command: 'print(inspect.signature(circular_speed))', says: 'Prints the parameter list, such as (r_km, mu=398600.4418).' },
    seeAlso: ['functools.wraps', 'help'],
  },
  {
    name: 'io',
    lang: 'python',
    kind: 'module',
    official: 'The io module provides the Python interfaces to stream handling.',
    source: DOC,
    when: 'Tools for streams: things you read from or write to like a file. Its StringIO and BytesIO behave like files but live in memory.',
    example: { command: 'import io', says: 'Makes io.StringIO and io.BytesIO available.' },
    seeAlso: ['io.StringIO', 'io.BytesIO', 'open'],
  },
  {
    name: 'io.BytesIO',
    lang: 'python',
    kind: 'class',
    official: 'Buffered I/O implementation using an in-memory bytes buffer.',
    source: DOC,
    when: 'A file in memory for bytes: anything that writes to a binary file can write here instead, with nothing saved to disk. Call .getvalue() to get the bytes back.',
    example: { command: 'fig.savefig(io.BytesIO(), format="png")', says: 'Draws the figure into memory, which forces the full render without writing a file.' },
    seeAlso: ['io.StringIO', 'bytes'],
  },
  {
    name: 'io.StringIO',
    lang: 'python',
    kind: 'class',
    official: 'Text I/O implementation using an in-memory buffer.',
    source: DOC,
    when: 'A string that behaves like an open text file. Use it to test code that reads or writes files without touching the disk, or to build CSV text in memory.',
    flags: [['.getvalue()', 'all the text written so far, as one string']],
    example: {
      command: 'list(csv.DictReader(io.StringIO("t,alt\\n0,12.5\\n")))',
      says: "[{'t': '0', 'alt': '12.5'}]: csv reads the string as if it were a file.",
    },
    seeAlso: ['io.StringIO.getvalue', 'csv.DictReader', 'io.BytesIO'],
  },
  {
    name: 'itertools',
    lang: 'python',
    kind: 'module',
    official: 'Functional tools for creating and using iterators.',
    source: DOC,
    when: 'Building blocks for loops: counting forever, joining iterables, taking a slice, grouping, and every pair or ordering of items. Most tools hand back lazy iterators, so wrap them in list(...) to see the values; an iterator can only be walked through once.',
    example: { command: 'from itertools import chain', says: 'Brings in chain, so you write chain(...) with no prefix.' },
    seeAlso: ['itertools.chain', 'itertools.islice', 'itertools.combinations', 'iter'],
  },
  {
    name: 'itertools.accumulate',
    aliases: ['accumulate'],
    lang: 'python',
    kind: 'class',
    official: 'Return series of accumulated sums (or other binary function results).',
    source: DOC,
    when: 'Running totals: each item is the sum of everything up to it. It hands back an iterator, so wrap it in list(...) to see the numbers.',
    example: { command: 'list(accumulate([1, 2, 3, 4]))', says: '[1, 3, 6, 10]' },
    seeAlso: ['functools.reduce', 'sum'],
  },
  {
    name: 'itertools.chain',
    aliases: ['chain'],
    lang: 'python',
    kind: 'class',
    official: 'Return a chain object whose .__next__() method returns elements from the first iterable until it is exhausted, then elements from the next iterable, until all of the iterables are exhausted.',
    source: DOC,
    when: 'Loop over several iterables one after another as if they were one, without building a new list.',
    example: { command: 'list(chain([1, 2], [3], [4, 5]))', says: '[1, 2, 3, 4, 5]' },
    seeAlso: ['itertools.chain.from_iterable', 'list.extend'],
  },
  {
    name: 'itertools.chain.from_iterable',
    aliases: ['chain.from_iterable'],
    lang: 'python',
    kind: 'function',
    official: 'Alternative chain() constructor taking a single iterable argument that evaluates lazily.',
    source: DOC,
    when: 'Flatten one level: turn a list of lists into one stream of items. Use it when the iterables you want to join are themselves inside one list.',
    example: { command: 'list(chain.from_iterable([[1, 2], [3]]))', says: '[1, 2, 3]' },
    seeAlso: ['itertools.chain'],
  },
  {
    name: 'itertools.combinations',
    aliases: ['combinations'],
    lang: 'python',
    kind: 'class',
    official: 'Return successive r-length combinations of elements in the iterable.',
    source: DOC,
    when: 'Every group of r different items where order does not matter, such as every pair of sensors to cross-check. The count grows fast: 100 items give 4,950 pairs and 161,700 groups of three.',
    example: { command: 'list(combinations("abc", 2))', says: "[('a', 'b'), ('a', 'c'), ('b', 'c')]" },
    seeAlso: ['itertools.permutations', 'itertools.product', 'math.comb'],
  },
  {
    name: 'itertools.count',
    lang: 'python',
    kind: 'class',
    official: 'Return a count object whose .__next__() method returns consecutive values.',
    source: DOC,
    when: 'Count up forever: 0, 1, 2 and on, or from any start you give. It never stops by itself, so pair it with islice, zip or a break.',
    flags: [['start', 'the first number (0 unless you say otherwise)']],
    example: { command: 'list(islice(count(10), 3))', says: '[10, 11, 12]' },
    seeAlso: ['itertools.islice', 'range', 'enumerate'],
  },
  {
    name: 'itertools.groupby',
    aliases: ['groupby'],
    lang: 'python',
    kind: 'class',
    official: 'make an iterator that returns consecutive keys and groups from the iterable',
    source: DOC,
    when: 'Bunch together neighbors that are equal and walk through each run. It only groups items that sit next to each other, so sort by the same key first if equal items can be scattered.',
    flags: [['key=', 'a function that gives the value to group by']],
    example: { command: '[(k, len(list(g))) for k, g in groupby("aaabcc")]', says: "[('a', 3), ('b', 1), ('c', 2)]" },
    seeAlso: ['sorted', 'operator.itemgetter', 'collections.defaultdict'],
  },
  {
    name: 'itertools.islice',
    aliases: ['islice'],
    lang: 'python',
    kind: 'class',
    official: 'Return an iterator whose next() method returns selected values from an iterable.',
    source: DOC,
    when: 'Take a slice, such as the first 3 items, from any iterator, even a generator or an endless one, where [:3] does not work. The items it steps over are used up.',
    example: { command: 'list(islice(evens(), 4))', says: '[0, 2, 4, 6]: the first four values from a generator that never ends.' },
    seeAlso: ['itertools.count', 'slice'],
  },
  {
    name: 'itertools.permutations',
    aliases: ['permutations'],
    lang: 'python',
    kind: 'class',
    official: 'Return successive r-length permutations of elements in the iterable.',
    source: DOC,
    when: 'Every possible ordering of the items. The count is n factorial, so 10 items already give 3,628,800 orderings.',
    example: { command: 'list(permutations(range(3)))', says: '[(0, 1, 2), (0, 2, 1), (1, 0, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0)]' },
    seeAlso: ['itertools.combinations', 'math.factorial'],
  },
  {
    name: 'itertools.product',
    aliases: ['product'],
    lang: 'python',
    kind: 'class',
    official: 'Cartesian product of input iterables. Equivalent to nested for-loops.',
    source: DOC,
    when: 'Every way of picking one item from each iterable, the same as nested for loops, such as every row of a truth table.',
    flags: [['repeat=', 'use the same iterable this many times']],
    example: { command: 'list(product([0, 1], repeat=3))', says: 'All 8 rows, from (0, 0, 0) up to (1, 1, 1).' },
    seeAlso: ['itertools.combinations', 'for'],
  },
  {
    name: 'json',
    lang: 'python',
    kind: 'module',
    official: 'JSON (JavaScript Object Notation) <https://json.org> is a subset of JavaScript syntax (ECMA-262 3rd edition) used as a lightweight data interchange format.',
    source: DOC,
    when: 'Turn dicts, lists, strings, numbers, True, False and None into JSON text and back. JSON has no tuples, sets or dates: tuples come back as lists, and sets and dates raise TypeError until you convert them.',
    example: { command: 'import json', says: 'Makes json.dumps, json.loads, json.dump and json.load available.' },
    seeAlso: ['json.dumps', 'json.loads', 'json.dump'],
  },
  {
    name: 'json.JSONDecodeError',
    lang: 'python',
    kind: 'exception',
    official: 'Subclass of ValueError with the following additional properties:',
    source: DOC,
    when: 'The error json.loads raises when the text is not valid JSON. It is a kind of ValueError, and its message gives the line and column where reading failed.',
    example: { command: 'json.loads("{bad}")', says: 'Raises json.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1).' },
    seeAlso: ['json.loads', 'ValueError'],
  },
  {
    name: 'json.dump',
    lang: 'python',
    kind: 'function',
    official: 'Serialize ``obj`` as a JSON formatted stream to ``fp`` (a ``.write()``-supporting file-like object).',
    source: DOC,
    when: 'Write a value as JSON straight into an open file. Without the s it writes to a file; json.dumps gives you back a string.',
    flags: [['indent=', 'spaces per level of nesting, for readable output']],
    example: { command: 'json.dump(prov, f, indent=2)', says: 'Writes the dict prov into the open file f as neatly indented JSON.' },
    seeAlso: ['json.dumps', 'open'],
  },
  {
    name: 'json.dumps',
    lang: 'python',
    kind: 'function',
    official: 'Serialize ``obj`` to a JSON formatted ``str``.',
    source: DOC,
    when: 'Turn data into JSON text, to save it, send it or fingerprint it. Watch out: dict keys that are not strings, such as ints, become strings, so they do not come back the same.',
    flags: [
      ['indent=', 'spaces per level of nesting, for readable output'],
      ['sort_keys=True', 'write keys in sorted order, so the same data always gives the same text'],
    ],
    example: { command: 'json.dumps({"b": 2, "a": [1, 2]}, sort_keys=True)', says: '\'{"a": [1, 2], "b": 2}\': one string of JSON text, keys in order.' },
    seeAlso: ['json.loads', 'json.dump', 'dataclasses.asdict'],
  },
  {
    name: 'json.loads',
    lang: 'python',
    kind: 'function',
    official: 'Deserialize ``s`` (a ``str``, ``bytes`` or ``bytearray`` instance containing a JSON document) to a Python object.',
    source: DOC,
    when: 'Read JSON text and get back dicts, lists, strings, numbers, booleans and None. Broken text raises json.JSONDecodeError.',
    example: { command: 'json.loads(\'{"stage": 2, "go": true}\')', says: "{'stage': 2, 'go': True}: JSON's true becomes Python's True." },
    seeAlso: ['json.dumps', 'json.JSONDecodeError'],
  },
  {
    name: 'logging',
    lang: 'python',
    kind: 'module',
    official: 'Logging package for Python.',
    source: DOC,
    when: 'Record what a program is doing, with a level on each message, and decide in one place what gets shown and where it goes. Modules should only get a logger with getLogger(__name__); leave basicConfig to the main script.',
    example: { command: 'import logging', says: 'Makes logging.getLogger, logging.basicConfig and the level names available.' },
    seeAlso: ['logging.getLogger', 'logging.basicConfig', 'print'],
  },
  {
    name: 'logging.DEBUG',
    lang: 'python',
    kind: 'constant',
    official: 'Detailed information, typically only of interest to a developer trying to diagnose a problem.',
    source: REF,
    when: 'The lowest everyday level (its number is 10), for detail you only want while hunting a bug. Both the logger and the handler must allow DEBUG, or the lines are still dropped.',
    example: { command: 'logging.basicConfig(level=logging.DEBUG)', says: 'Shows every message, DEBUG and up.' },
    seeAlso: ['logging.INFO', 'logging.basicConfig'],
  },
  {
    name: 'logging.ERROR',
    lang: 'python',
    kind: 'constant',
    official: 'Due to a more serious problem, the software has not been able to perform some function.',
    source: REF,
    when: 'The level (number 40) for something that failed: a sensor timed out, a file could not be written. Only CRITICAL is more serious.',
    example: { command: 'log.setLevel(logging.ERROR)', says: 'The logger now drops DEBUG, INFO and WARNING messages and keeps ERROR and CRITICAL.' },
    seeAlso: ['logging.WARNING', 'logging.getLogger'],
  },
  {
    name: 'logging.FileHandler',
    lang: 'python',
    kind: 'class',
    official: 'A handler class which writes formatted logging records to disk files.',
    source: DOC,
    when: 'Send log messages to a file. By default it adds to the end of the file, so old runs pile up unless you pass mode="w".',
    flags: [['mode="w"', 'start a fresh file each run instead of adding to the end']],
    example: {
      command: 'to_file = logging.FileHandler("campaign.log", mode="w")',
      says: 'A handler that writes to campaign.log, emptied first. Attach it with log.addHandler(to_file).',
    },
    seeAlso: ['logging.StreamHandler', 'logging.Formatter'],
  },
  {
    name: 'logging.Formatter',
    lang: 'python',
    kind: 'class',
    official: 'Formatter instances are used to convert a LogRecord to text.',
    source: DOC,
    when: 'Decide how each log line looks: time, level, logger name, message. Give it a format string with %(...)s fields and attach it to a handler with setFormatter.',
    flags: [
      ['%(levelname)s', 'the level, such as INFO'],
      ['%(name)s', 'the logger\'s name'],
      ['%(message)s', 'your message'],
      ['%(asctime)s', 'the date and time'],
      ['%(lineno)d', 'the line number that logged it'],
    ],
    example: {
      command: 'console.setFormatter(logging.Formatter("%(levelname)-8s %(message)s"))',
      says: 'Lines now look like "INFO     engine armed", with the level padded to 8 characters.',
    },
    seeAlso: ['logging.StreamHandler', 'logging.basicConfig'],
  },
  {
    name: 'logging.INFO',
    lang: 'python',
    kind: 'constant',
    official: 'Confirmation that things are working as expected.',
    source: REF,
    when: 'The level (number 20) for normal progress messages, like "stage 2 ignition". The default level is WARNING, so INFO lines stay hidden until you lower it.',
    example: { command: 'logging.basicConfig(level=logging.INFO)', says: 'Shows INFO messages and anything more serious; DEBUG stays hidden.' },
    seeAlso: ['logging.DEBUG', 'logging.WARNING', 'logging.basicConfig'],
  },
  {
    name: 'logging.StreamHandler',
    lang: 'python',
    kind: 'class',
    official: 'A handler class which writes logging records, appropriately formatted, to a stream.',
    source: DOC,
    when: 'Send log messages to the terminal. It writes to sys.stderr unless you pass another stream, such as sys.stdout.',
    example: { command: 'handler = logging.StreamHandler(sys.stdout)', says: 'A handler that prints log lines to normal output. Attach it with log.addHandler(handler).' },
    seeAlso: ['logging.FileHandler', 'logging.Formatter', 'sys.stderr'],
  },
  {
    name: 'logging.WARNING',
    lang: 'python',
    kind: 'constant',
    official: "An indication that something unexpected happened, or that a problem might occur in the near future (e.g. 'disk space low'). The software is still working as expected.",
    source: REF,
    when: 'The level (number 30) for something odd that did not stop the program, like a rejected sensor reading. It is the default, so with no setup you see WARNING and up.',
    example: { command: 'log.setLevel(logging.WARNING)', says: 'The logger now drops DEBUG and INFO messages and keeps WARNING and anything more serious.' },
    seeAlso: ['logging.INFO', 'logging.ERROR'],
  },
  {
    name: 'logging.basicConfig',
    lang: 'python',
    kind: 'function',
    official: 'Do basic configuration for the logging system.',
    source: DOC,
    when: 'Set up logging for the whole program in one line, at the start of the main script. Watch out: it does nothing if logging is already set up, so a second call is silently ignored.',
    flags: [
      ['level=', 'the lowest level to show'],
      ['format=', 'how each line looks, using %(...)s fields'],
    ],
    example: {
      command: 'logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")',
      says: 'log.info("armed") on the logger named guidance now prints: INFO guidance: armed',
    },
    seeAlso: ['logging.getLogger', 'logging.Formatter'],
  },
  {
    name: 'logging.getLogger',
    lang: 'python',
    kind: 'function',
    official: 'Return a logger with the specified name, creating it if necessary.',
    source: DOC,
    when: 'Get the logger for a name; the same name always gives back the same logger. Write log = logging.getLogger(__name__) at the top of each module.',
    example: { command: 'log = logging.getLogger("guidance")', says: 'The logger named guidance. log.info(...) and log.warning(...) then send messages under that name.' },
    seeAlso: ['logging.basicConfig', 'logging.DEBUG'],
  },
  {
    name: 'math',
    lang: 'python',
    kind: 'module',
    official: 'This module provides access to the mathematical functions defined by the C standard.',
    source: DOC,
    when: 'Everyday math on single numbers: square roots, trig, logs, rounding, and constants like pi. Angles are in radians. For whole arrays use NumPy; math works on one number at a time.',
    example: { command: 'import math', says: 'Makes math.sqrt, math.pi and the rest available.' },
    seeAlso: ['math.sqrt', 'math.pi', 'cmath'],
  },
  {
    name: 'math.acos',
    lang: 'python',
    kind: 'function',
    official: 'Return the arc cosine (measured in radians) of x.',
    source: DOC,
    when: 'The angle whose cosine is x, in radians from 0 to pi, such as the angle between two unit vectors. Anything outside -1 to 1 raises ValueError, and rounding can push a dot product to 1.0000000002, so clamp it first.',
    example: { command: 'math.degrees(math.acos(-0.4))', says: '113.578...: an angle between 0 and 180 degrees.' },
    seeAlso: ['math.asin', 'math.atan2', 'math.degrees'],
  },
  {
    name: 'math.asin',
    lang: 'python',
    kind: 'function',
    official: 'Return the arc sine (measured in radians) of x.',
    source: DOC,
    when: 'The angle whose sine is x, in radians from -pi/2 to pi/2. Anything outside -1 to 1 raises ValueError.',
    example: { command: 'math.degrees(math.asin(2.0 / 5.5))', says: '21.32...: an angle between -90 and 90 degrees.' },
    seeAlso: ['math.acos', 'math.sin'],
  },
  {
    name: 'math.atan',
    lang: 'python',
    kind: 'function',
    official: 'Return the arc tangent (measured in radians) of x.',
    source: DOC,
    when: 'The angle whose tangent is x, from -pi/2 to pi/2. Dividing y by x loses the signs, so it cannot tell opposite directions apart; for the angle of a point, use math.atan2(y, x).',
    example: { command: 'math.degrees(math.atan(1200 / 3000))', says: '21.80...: the climb angle for 1200 m up over 3000 m across.' },
    seeAlso: ['math.atan2'],
  },
  {
    name: 'math.atan2',
    lang: 'python',
    kind: 'function',
    official: 'Return the arc tangent (measured in radians) of y/x.',
    source: DOC,
    when: 'The angle of the point (x, y), from -pi to pi, right in every quadrant and fine when x is 0. Note the order: y comes first, then x.',
    example: { command: 'math.degrees(math.atan2(-1, -1))', says: '-135.0. Plain atan(-1 / -1) would say 45, pointing the opposite way.' },
    seeAlso: ['math.atan', 'math.degrees'],
  },
  {
    name: 'math.ceil',
    lang: 'python',
    kind: 'function',
    official: 'Return the ceiling of x as an Integral.',
    source: DOC,
    when: 'Round up to the whole number above, for things like how many pages or tanks you need. It gives back an int.',
    example: { command: 'math.ceil(11 / 5)', says: '3: 2.2 rounded up.' },
    seeAlso: ['math.floor', 'round', 'int'],
  },
  {
    name: 'math.comb',
    lang: 'python',
    kind: 'function',
    official: 'Number of ways to choose k items from n items without repetition and without order.',
    source: DOC,
    when: 'Count the ways to choose k items out of n when order does not matter, for example which 2 of 3 redundant sensors are working.',
    example: { command: 'math.comb(3, 2)', says: '3: the pairs AB, AC and BC.' },
    seeAlso: ['itertools.combinations', 'math.factorial'],
  },
  {
    name: 'math.copysign',
    lang: 'python',
    kind: 'function',
    official: 'Return a float with the magnitude (absolute value) of x but the sign of y.',
    source: DOC,
    when: 'Give one number the sign of another. It is used in the stable quadratic formula so you never subtract two nearly equal numbers.',
    example: { command: 'math.copysign(5.0, -0.2)', says: 'Gives -5.0: the size of 5.0 with the sign of -0.2.' },
    seeAlso: ['abs'],
  },
  {
    name: 'math.cos',
    aliases: ['cos'],
    lang: 'python',
    kind: 'function',
    official: 'Return the cosine of x (measured in radians).',
    source: DOC,
    when: 'The cosine of an angle in radians. An angle in degrees gives a wrong answer without any error, so convert with math.radians first.',
    example: { command: 'math.cos(math.radians(60))', says: '0.5000000000000001: one half, with a tiny rounding error.' },
    seeAlso: ['math.sin', 'math.radians', 'cmath.cos'],
  },
  {
    name: 'math.degrees',
    lang: 'python',
    kind: 'function',
    official: 'Convert angle x from radians to degrees.',
    source: DOC,
    when: 'Turn an angle from radians, which the math functions give back, into degrees for people to read.',
    example: { command: 'math.degrees(math.pi / 2)', says: 'Gives 90.0: a right angle, turned from radians into degrees.' },
    seeAlso: ['math.radians', 'math.atan2'],
  },
  {
    name: 'math.e',
    lang: 'python',
    kind: 'constant',
    official: 'The mathematical constant e = 2.718281..., to available precision.',
    source: REF,
    when: 'The number e, about 2.71828, the base of natural logarithms. It is a float, so math.log(math.e) is 1.0.',
    example: { command: 'math.log(math.e)', says: 'Gives 1.0, because the natural log of e is exactly one.' },
    seeAlso: ['math.exp', 'math.log', 'math.pi'],
  },
  {
    name: 'math.erfc',
    lang: 'python',
    kind: 'function',
    official: 'Complementary error function at x.',
    source: DOC,
    when: 'For a normal (bell-curve) spread, math.erfc(z / math.sqrt(2)) is the chance that a value lands more than z standard deviations from the middle, on either side. Handy for false-alarm rates.',
    example: { command: 'math.erfc(3.5 / math.sqrt(2))', says: '0.000465...: about a 1 in 2,150 chance of a reading beyond 3.5 sigma.' },
    seeAlso: ['math.sqrt', 'statistics'],
  },
  {
    name: 'importlib.util.resolve_name',
    aliases: ['resolve_name'],
    lang: 'python',
    kind: 'function',
    official: 'Resolve a relative module name to an absolute one.',
    source: 'Python standard library docstring',
    when: 'You want to see which real module a relative import such as `from .filters import ...` points to, given the package it is written in. Each leading dot climbs one package up, so two dots from `gnc.nav` land in `gnc`.',
    example: { command: 'importlib.util.resolve_name(".filters", "gnc.nav")', says: 'Gives "gnc.nav.filters": the absolute name that the relative import .filters means inside the package gnc.nav.' },
    seeAlso: ['importlib'],
  },
]
