import type { CommandRef } from './types'

export const COMMANDS: CommandRef[] = [
  // CasADi
  {
    name: 'casadi',
    aliases: ['ca'],
    lang: 'python',
    kind: 'module',
    official:
      'CasADi is a symbolic framework for numeric optimization implementing automatic differentiation in forward and reverse modes on sparse matrix-valued computational graphs.',
    source: 'CasADi project description (package metadata)',
    when: 'You have a nonlinear optimization problem, like the least-fuel landing, and want a tool that works out every derivative for you. You describe the unknowns as symbols, write the cost and the rules with them, and hand the whole thing to a solver such as IPOPT. It is not part of Python: install it with pip install casadi first.',
    example: {
      command: 'import casadi as ca\nx = ca.MX.sym("x"); print(ca.vertcat(x, 2 * x))',
      says: 'Prints vertcat(x, (2.*x)): the math is kept as a formula about x, not worked out to a number.',
    },
    seeAlso: ['casadi.MX', 'casadi.nlpsol'],
  },
  {
    name: 'casadi.DM',
    aliases: ['ca.DM'],
    lang: 'python',
    kind: 'class',
    official: 'Sparse matrix class. SX and DM are specializations.',
    source: 'CasADi docstring (Matrix, the class DM is made from)',
    when: 'You need a matrix of plain numbers inside a CasADi problem, such as a known starting state to compare with the unknown one. The answers a solver hands back are DM too. To get ordinary numbers out, use float(d) for a single value or d.full() for a NumPy array.',
    example: {
      command: 'x0 = ca.DM([1000.0, -50.0])     # height m, velocity m/s\nprint(x0)',
      says: 'Makes a 2-by-1 column of fixed numbers and prints [1000, -50].',
    },
    seeAlso: ['casadi.MX', 'casadi.vertcat'],
  },
  {
    name: 'casadi.MX',
    aliases: ['ca.MX'],
    lang: 'python',
    kind: 'class',
    official: 'MX - Matrix expression.',
    source: 'CasADi docstring',
    when: 'You want matrices that stand for unknowns. Math on an MX does not give a number; it builds up a formula that CasADi can later differentiate and hand to a solver. Because it has no value yet, you cannot print a number from it or use it in a Python if.',
    example: {
      command: 'a = ca.MX.sym("a", 4)\nprint(a.shape)',
      says: 'Makes a symbolic column of 4 unknown thrust values and prints (4, 1).',
    },
    seeAlso: ['casadi.MX.sym', 'casadi.DM'],
  },
  {
    name: 'casadi.MX.sym',
    aliases: ['ca.MX.sym'],
    lang: 'python',
    kind: 'function',
    official: 'Create an nrow-by-ncol symbolic primitive.',
    source: 'CasADi docstring',
    when: 'You are setting up the unknowns of a CasADi problem: every quantity the solver is allowed to choose. With only a name you get a single unknown; add a row and column count for a whole grid of them.',
    flags: [
      ['name', 'a label for the symbol, shown when it is printed'],
      ['nrow', 'how many rows (leave out for a single value)'],
      ['ncol', 'how many columns (leave out for a column)'],
    ],
    example: {
      command: 'X = ca.MX.sym("X", 2, N + 1)    # height and velocity at each node',
      says: 'Makes a 2-row grid of unknowns with one column per time node.',
    },
    seeAlso: ['casadi.MX', 'casadi.vertcat'],
  },
  {
    name: 'casadi.inf',
    aliases: ['ca.inf'],
    lang: 'python',
    kind: 'constant',
    official: 'A floating-point positive infinity.',
    source: 'Python documentation (math.inf, the same value)',
    when: 'You are writing the bounds for a solver and one side has no limit. Put -ca.inf for "no lower limit" and ca.inf for "no upper limit". It is an ordinary Python float, the same as float("inf").',
    example: {
      command: 'inf = ca.inf\nlbx = [0.0, -inf]    # height at least 0, velocity any value',
      says: 'Sets a lower bound of 0 on the first unknown and no lower bound at all on the second.',
    },
    seeAlso: ['casadi.nlpsol'],
  },
  {
    name: 'casadi.nlpsol',
    aliases: ['ca.nlpsol'],
    lang: 'python',
    kind: 'function',
    official: 'Create an NLP solver',
    source: 'CasADi docstring',
    when: 'Your problem is written, and you want a solver for it. An NLP (nonlinear program) is a problem with a cost to make as small as possible and rules that can curve. You get back a solver you then call with a starting guess and the bounds. Always check that the solver reports success before trusting the answer.',
    flags: [
      ['name', 'a short label for the solver, such as "s"'],
      ['"ipopt"', 'which solver program to use underneath'],
      ['nlp', 'a dictionary: "x" the unknowns, "f" the cost, "g" the constraints'],
      ['opts', 'a dictionary of settings, such as "ipopt.tol" and "ipopt.max_iter"'],
      ['x0=, lbx=, ubx=, lbg=, ubg=', 'when calling the solver: the starting guess and the lower and upper bounds'],
    ],
    example: {
      command: 'solver = ca.nlpsol("s", "ipopt", {"x": x, "f": (x - 3) ** 2})\nsol = solver(x0=0)',
      says: 'IPOPT searches from x = 0 and sol["x"] comes back as 3, where the cost is smallest.',
    },
    seeAlso: ['casadi.MX.sym', 'casadi.vertcat', 'casadi.inf'],
  },
  {
    name: 'casadi.sum1',
    aliases: ['ca.sum1'],
    lang: 'python',
    kind: 'function',
    official: 'Return a row-wise summation of elements.',
    source: 'CasADi docstring',
    when: 'You want to add up the entries of a column, such as the thrust used on every interval, to build a total cost. The 1 means it adds along the first direction, down the rows, so a matrix gives one total per column.',
    example: {
      command: 'ca.sum1(ca.DM([4.0, 6.0, 5.0]))',
      says: 'Adds 4 + 6 + 5 and gives 15.',
    },
    seeAlso: ['casadi.vec', 'casadi.vertcat'],
  },
  {
    name: 'casadi.vec',
    aliases: ['ca.vec'],
    lang: 'python',
    kind: 'function',
    official: 'make a vector',
    source: 'CasADi docstring',
    when: 'A solver wants all its unknowns in one tall column, but you built them as a grid. vec stacks the columns of the grid on top of each other. It goes column by column, not row by row, so remember that order when you unpack the answer.',
    example: {
      command: 'ca.vec(ca.DM([[1, 2], [3, 4]]))',
      says: 'Gives the column [1, 3, 2, 4]: first column, then second column.',
    },
    seeAlso: ['casadi.vertcat', 'casadi.MX.sym'],
  },
  {
    name: 'casadi.vertcat',
    aliases: ['ca.vertcat'],
    lang: 'python',
    kind: 'function',
    official: 'Concatenate vertically, six matrices.',
    source: 'CasADi docstring (_vertcat, which vertcat calls)',
    when: 'You want to stack several values or columns into one tall column, for example all the unknowns of a problem, or a list of constraints with ca.vertcat(*g). The pieces must all have the same number of columns.',
    example: {
      command: 'f_k = ca.vertcat(v, a - g0)    # rate of change of height and velocity',
      says: 'Makes a 2-by-1 column: velocity on top, net acceleration underneath.',
    },
    seeAlso: ['casadi.vec', 'casadi.DM'],
  },

  // CVXPY
  {
    name: 'cvxpy',
    aliases: ['cp'],
    lang: 'python',
    kind: 'module',
    official: 'CVXPY is a Python-embedded modeling language for convex optimization problems.',
    source: 'CVXPY README (package metadata)',
    when: 'You have an optimization problem that is convex (bowl-shaped, so it has one best answer and no false ones) and want to write it the way it looks on paper. CVXPY checks it really is convex, rewrites it for a solver and hands back the answer. If your problem is not convex, it refuses instead of guessing.',
    example: {
      command: 'import cvxpy as cp\nT = cp.Variable(2)',
      says: 'Loads CVXPY under its usual short name and makes two unknown engine thrusts.',
    },
    seeAlso: ['cvxpy.Variable', 'cvxpy.Problem'],
  },
  {
    name: 'cvxpy.ECOS',
    aliases: ['cp.ECOS'],
    lang: 'python',
    kind: 'constant',
    official: "The solver to use. For example, 'CLARABEL', 'SCS', or 'OSQP'.",
    source: 'CVXPY docstring (Problem.solve, the solver argument)',
    when: 'You want CVXPY to use the ECOS solver instead of choosing one itself. It is just the text "ECOS", used as solver=cp.ECOS. Recent CVXPY versions no longer install ECOS for you, so if you get a SolverError saying it is not installed, run pip install ecos.',
    flags: [
      ['abstol=, reltol=', 'how close to the true answer ECOS must get before it stops'],
    ],
    example: {
      command: 'prob.solve(solver=cp.ECOS, abstol=1e-8, reltol=1e-8)',
      says: 'Solves the problem with ECOS and tighter stopping tolerances than the defaults.',
    },
    seeAlso: ['cvxpy.Problem'],
  },
  {
    name: 'cvxpy.Minimize',
    aliases: ['cp.Minimize'],
    lang: 'python',
    kind: 'class',
    official: 'An optimization objective for minimization.',
    source: 'CVXPY docstring',
    when: 'You are saying what the solver should make as small as possible: fuel, cost, error. Wrap the expression in cp.Minimize and pass it to cp.Problem. The expression must be convex, or CVXPY will refuse the problem.',
    example: {
      command: 'goal = cp.Minimize(1.2 * T[0] + T[1])    # engine 1 costs more',
      says: 'Sets the goal: the cheapest mix of the two engine thrusts.',
    },
    seeAlso: ['cvxpy.Problem', 'cvxpy.Variable'],
  },
  {
    name: 'cvxpy.Problem',
    aliases: ['cp.Problem'],
    lang: 'python',
    kind: 'class',
    official: 'A convex optimization problem.',
    source: 'CVXPY docstring',
    when: 'You have a goal and a list of constraints and want to solve them together. Call .solve() on the problem, then check prob.status before using prob.value (the best cost) or your variables\' .value. Only "optimal" means you can trust the answer.',
    flags: [
      ['objective', 'the goal, such as cp.Minimize(...)'],
      ['constraints', 'a Python list of rules, such as [cp.sum(T) >= 50, T >= 0]'],
      ['.solve()', 'runs a solver; you can pass solver= to pick one'],
    ],
    example: {
      command: 'prob = cp.Problem(cp.Minimize(1.2 * T[0] + T[1]), [cp.sum(T) >= 50, T >= 0, T <= 40])\nprob.solve(); print(prob.status, prob.value)',
      says: 'Prints optimal 52.0: engine 2 runs at its 40 kN limit and engine 1 makes up the other 10 kN.',
    },
    seeAlso: ['cvxpy.Minimize', 'cvxpy.Variable', 'cvxpy.ECOS'],
  },
  {
    name: 'cvxpy.Variable',
    aliases: ['cp.Variable'],
    lang: 'python',
    kind: 'class',
    official: 'The optimization variables in a problem.',
    source: 'CVXPY docstring',
    when: 'You need an unknown that the solver gets to choose. Give a size for several at once, or nothing for a single number. It has no value until the problem is solved; then .value holds the answer (and is None before that).',
    flags: [['shape', 'how many unknowns: 2 for two, (3, 4) for a grid, nothing for one']],
    example: {
      command: 'u = cp.Variable(3)    # thrust acceleration, x y z',
      says: 'Makes three unknowns. After solving, u.value is a NumPy array with the best values.',
    },
    seeAlso: ['cvxpy.Problem', 'cvxpy.norm', 'cvxpy.sum'],
  },
  {
    name: 'cvxpy.norm',
    aliases: ['cp.norm'],
    lang: 'python',
    kind: 'function',
    official: 'Wrapper on the different norm atoms.',
    source: 'CVXPY docstring',
    when: 'You need the length of a vector inside a CVXPY problem, for example "the thrust must not be more than its limit". With 2 it is the ordinary straight-line length. Use it on the small side of <=: norm(u) <= limit is convex, but norm(u) >= limit is not and will be refused.',
    flags: [
      ['x', 'the vector (or part of one, like r[:2])'],
      ['2', 'which norm: 2 is ordinary length, 1 adds the sizes, "inf" takes the biggest'],
    ],
    example: {
      command: 'cp.norm(u, 2) <= sigma    # thrust cone',
      says: 'A constraint: the length of the thrust vector u stays within sigma.',
    },
    seeAlso: ['cvxpy.Variable', 'cvxpy.sum'],
  },
  {
    name: 'cvxpy.sum',
    aliases: ['cp.sum'],
    lang: 'python',
    kind: 'function',
    official: 'Sum the entries of an expression over a given axis.',
    source: 'CVXPY docstring',
    when: 'You want the total of a CVXPY variable or expression, like the combined thrust of all engines. Use cp.sum, not Python\'s built-in sum, which works on plain numbers and gets slow on big CVXPY expressions.',
    example: {
      command: 'cp.sum(T) >= 50    # together at least 50 kN',
      says: 'A constraint: the thrusts in T must add up to at least 50.',
    },
    seeAlso: ['cvxpy.norm', 'cvxpy.Variable'],
  },

  // Hypothesis
  {
    name: 'hypothesis',
    lang: 'python',
    kind: 'module',
    official: 'Hypothesis is a library for writing unit tests which are parametrized by some source of data.',
    source: 'Hypothesis docstring',
    when: 'You want to test that something is always true (a rotation keeps a vector\'s length, say) on hundreds of inputs you did not pick yourself. Hypothesis generates them, hunting for edges like 0, -0.0 and huge numbers, and when a test fails it shrinks the input to the simplest one that still fails. It works inside pytest.',
    example: {
      command: 'from hypothesis import given, strategies as st',
      says: 'Brings in the given decorator and the strategies module under its usual short name st.',
    },
    seeAlso: ['hypothesis.given', 'hypothesis.strategies', 'pytest'],
  },
  {
    name: 'hypothesis.assume',
    aliases: ['assume'],
    lang: 'python',
    kind: 'function',
    official:
      'Calling ``assume`` is like an :ref:`assert <python:assert>` that marks the |test case| as bad, rather than failing the test.',
    source: 'Hypothesis docstring',
    when: 'A generated input is one your function is not meant to handle, such as a zero-length vector you cannot normalize. assume(...) throws that one example away and Hypothesis tries another. If you throw away most examples, Hypothesis gives up with an error; then build a better strategy instead.',
    example: {
      command: 'assume((x, y, z) != (0.0, 0.0, 0.0))    # the zero vector is out of bounds',
      says: 'Skips this example when all three parts are zero, without failing the test.',
    },
    seeAlso: ['hypothesis.given', 'hypothesis.strategies.floats'],
  },
  {
    name: 'hypothesis.given',
    aliases: ['given'],
    lang: 'python',
    kind: 'function',
    official: 'The |@given| decorator turns a function into a Hypothesis test.',
    source: 'Hypothesis docstring',
    when: 'You have a test function that takes inputs, and you want Hypothesis to call it many times with generated values. Put @given above it with one strategy per input; by default it runs 100 examples. The test function still needs a name starting with test_ so pytest finds it.',
    flags: [['strategy, ...', 'one strategy for each argument of the test, in order']],
    example: {
      command: '@given(angles)\ndef test_wrap_stays_in_range(a):\n    assert -pi <= wrap(a) <= pi',
      says: 'Runs the test on 100 generated angles and reports the simplest one that breaks it, if any.',
    },
    seeAlso: ['hypothesis.strategies', 'hypothesis.assume', 'pytest'],
  },
  {
    name: 'hypothesis.strategies',
    aliases: ['st'],
    lang: 'python',
    kind: 'module',
    official: 'A ``SearchStrategy`` tells Hypothesis how to generate that kind of input.',
    source: 'Hypothesis docstring (SearchStrategy, the kind of object this module makes)',
    when: 'You are describing which inputs a property test should try: floats in a range, lists, tuples, a choice from a few values. Each function here makes a strategy, a recipe for inputs. Keep the range as wide as your function really accepts; the bugs live at the edges.',
    example: {
      command: 'st.lists(st.floats(min_value=0, max_value=500), min_size=1)',
      says: 'A recipe for non-empty lists of numbers from 0 to 500, such as a list of altitudes.',
    },
    seeAlso: ['hypothesis.strategies.floats', 'hypothesis.strategies.composite', 'hypothesis.given'],
  },
  {
    name: 'hypothesis.strategies.composite',
    aliases: ['st.composite'],
    lang: 'python',
    kind: 'function',
    official: 'Defines a strategy that is built out of potentially arbitrarily many other strategies.',
    source: 'Hypothesis docstring',
    when: 'An input takes several steps to build, like a random unit quaternion made from four floats and then normalized. Write a function decorated with @st.composite whose first argument is draw; each draw(strategy) pulls one value. Calling your function then gives a new strategy.',
    flags: [['draw', 'the first argument; draw(strategy) takes one value from a strategy']],
    example: {
      command: '@st.composite\ndef unit_quats(draw):\n    q = [draw(part) for _ in range(4)]\n    ...',
      says: 'Defines unit_quats(), a strategy you can pass to @given like any built-in one.',
    },
    seeAlso: ['hypothesis.strategies', 'hypothesis.given'],
  },
  {
    name: 'hypothesis.strategies.floats',
    aliases: ['st.floats'],
    lang: 'python',
    kind: 'function',
    official: 'Returns a strategy which generates floats.',
    source: 'Hypothesis docstring',
    when: 'Your function takes decimal numbers. With no bounds it tries everything a float can be, including nan (not a number), inf (infinity) and -0.0, which is often exactly what finds the bug. Set bounds only to what the function truly promises to handle.',
    flags: [
      ['min_value=, max_value=', 'the smallest and largest number to try'],
      ['allow_nan=', 'False to never try nan'],
      ['allow_infinity=', 'False to never try inf or -inf'],
    ],
    example: {
      command: 'angles = st.floats(min_value=-10.0, max_value=10.0)',
      says: 'A recipe for angles between -10 and 10 radians, well outside -pi to pi, to test a wrapping function.',
    },
    seeAlso: ['hypothesis.strategies', 'hypothesis.given'],
  },

  // joblib
  {
    name: 'joblib',
    lang: 'python',
    kind: 'module',
    official: 'Joblib is a set of tools to provide **lightweight pipelining in Python**.',
    source: 'joblib docstring',
    when: 'You want to run the same function on many inputs across several processor cores, like hundreds of Monte Carlo landing runs, or keep slow results on disk between runs. It is a separate package: pip install joblib.',
    example: {
      command: 'from joblib import Parallel, delayed',
      says: 'Brings in the two pieces you need to run a loop on several cores.',
    },
    seeAlso: ['joblib.Parallel', 'joblib.delayed', 'joblib.Memory'],
  },
  {
    name: 'joblib.Memory',
    aliases: ['Memory'],
    lang: 'python',
    kind: 'class',
    official:
      'A context object for caching a function\'s return value each time it is called with the same input arguments.',
    source: 'joblib docstring',
    when: 'A slow calculation, like building a big lookup table, gives the same answer every time for the same arguments. Memory saves each answer in a folder on disk, so tomorrow\'s run loads it instantly. It notices changed arguments and edits to the function, but not changed data files the function reads; delete the folder when those change.',
    flags: [
      ['location', 'the folder on disk where answers are kept'],
      ['verbose=0', 'work quietly, without printing a line for each call'],
      ['.cache', 'used as @memory.cache above the function to save'],
    ],
    example: {
      command: 'memory = Memory("table_cache", verbose=0)\n@memory.cache\ndef kepler_table(e): ...',
      says: 'The first call works out the table and saves it; later calls with the same e read it from table_cache.',
    },
    seeAlso: ['joblib.Parallel'],
  },
  {
    name: 'joblib.Parallel',
    aliases: ['Parallel'],
    lang: 'python',
    kind: 'class',
    official: 'Helper class for readable parallel mapping.',
    source: 'joblib docstring',
    when: 'You have many independent cases that each take a while, and want them spread across cores. Make a Parallel and call it with a loop of delayed calls; you get a list of results in the same order. For tiny, fast cases the cost of starting workers can make it slower than a plain loop.',
    flags: [['n_jobs=', 'how many workers to use; -1 means every core']],
    example: {
      command: 'results = Parallel(n_jobs=4)(delayed(run_case)(s) for s in seeds)',
      says: 'Runs run_case once for every seed on 4 cores and returns the results as a list, in seed order.',
    },
    seeAlso: ['joblib.delayed', 'joblib.Memory'],
  },
  {
    name: 'joblib.delayed',
    aliases: ['delayed'],
    lang: 'python',
    kind: 'function',
    official: 'Decorator used to capture the arguments of a function.',
    source: 'joblib docstring',
    when: 'You are writing the loop you hand to Parallel. Read delayed(f)(x) as "call f on x, but later, in a worker". Without it, f(x) would run right away, one at a time, before Parallel ever sees it.',
    example: {
      command: 'delayed(run_case)(42)',
      says: 'Packs up "run run_case with 42" as a job for Parallel to hand to a worker; nothing runs yet.',
    },
    seeAlso: ['joblib.Parallel'],
  },

  // Matplotlib
  {
    name: 'matplotlib',
    lang: 'python',
    kind: 'module',
    official: 'An object-oriented plotting library.',
    source: 'Matplotlib docstring',
    when: 'You want to draw graphs from your data: altitude over time, a ground track, a heat map. Most of the time you use its pyplot part, imported as plt; the top-level matplotlib module is where you pick the backend and find the colormaps.',
    example: {
      command: 'import matplotlib\nmatplotlib.use("Agg")',
      says: 'Loads Matplotlib and tells it to draw into memory instead of opening a window.',
    },
    seeAlso: ['matplotlib.pyplot', 'matplotlib.use'],
  },
  {
    name: 'matplotlib.animation',
    lang: 'python',
    kind: 'module',
    official: 'Abstract base class for Animations.',
    source: 'Matplotlib docstring (matplotlib.animation.Animation, the base of this module\'s animations)',
    when: 'You want a moving plot, such as a lander descending frame by frame, saved as a GIF or a video. The module holds FuncAnimation, which makes the frames, and writers like PillowWriter, which save them.',
    example: {
      command: 'from matplotlib.animation import FuncAnimation, PillowWriter',
      says: 'Brings in the animation maker and the GIF writer.',
    },
    seeAlso: ['matplotlib.animation.FuncAnimation', 'matplotlib.animation.PillowWriter'],
  },
  {
    name: 'matplotlib.animation.FuncAnimation',
    aliases: ['FuncAnimation'],
    lang: 'python',
    kind: 'class',
    official: '`TimedAnimation` subclass that makes an animation by repeatedly calling a function *func*.',
    source: 'Matplotlib docstring',
    when: 'You want each frame of a movie to be the same plot with its data moved on a little. Write an update function that changes existing lines with set_data and returns them. Keep the result in a variable (anim = ...), or Python may throw the animation away and it freezes on the first frame.',
    flags: [
      ['fig', 'the figure to animate'],
      ['func', 'your update function, called once per frame with the frame number'],
      ['frames=', 'how many frames, or the values to pass to the update function'],
      ['interval=', 'milliseconds between frames'],
      ['blit=True', 'redraw only what changed, which is faster'],
    ],
    example: {
      command: 'anim = FuncAnimation(fig, update, frames=120, interval=1000 / 30, blit=True)',
      says: 'Makes a 120-frame animation at 30 frames per second by calling update(0), update(1), and so on.',
    },
    seeAlso: ['matplotlib.animation.PillowWriter', 'matplotlib.pyplot.subplots'],
  },
  {
    name: 'matplotlib.animation.PillowWriter',
    aliases: ['PillowWriter'],
    lang: 'python',
    kind: 'class',
    official:
      'Abstract base class for writing movies, providing a way to grab frames by calling `~AbstractMovieWriter.grab_frame`.',
    source: 'Matplotlib docstring (inherited from AbstractMovieWriter)',
    when: 'You want to save an animation as a GIF. It uses the Pillow image library, which comes with Matplotlib, so it works anywhere without extra programs (an MP4 would need ffmpeg). It keeps every frame in memory, so very long animations can use a lot of it.',
    flags: [['fps=', 'frames per second in the saved file']],
    example: {
      command: 'anim.save("descent.gif", writer=PillowWriter(fps=30))',
      says: 'Writes the animation to descent.gif, playing at 30 frames per second.',
    },
    seeAlso: ['matplotlib.animation.FuncAnimation'],
  },
  {
    name: 'matplotlib.colormaps',
    lang: 'python',
    kind: 'function',
    official: 'Container for colormaps that are known to Matplotlib by name.',
    source: 'Matplotlib docstring',
    when: 'You want a colormap (a smooth run of colors for turning numbers into colors) by its name, such as "viridis". Look it up with square brackets, then call it with numbers from 0 to 1 to get colors back.',
    example: {
      command: 'cmap = matplotlib.colormaps["viridis"]\nprint(cmap(0.0))',
      says: 'Prints the darkest viridis color as red, green, blue and opacity: about (0.267, 0.005, 0.329, 1.0).',
    },
    seeAlso: ['matplotlib.colors.Normalize', 'matplotlib.colors'],
  },
  {
    name: 'matplotlib.colors',
    lang: 'python',
    kind: 'module',
    official: 'A module for converting numbers or color arguments to *RGB* or *RGBA*.',
    source: 'Matplotlib docstring',
    when: 'You need to work with colors themselves: turn a color name into numbers, numbers into a hex code, or data values into the 0 to 1 range a colormap needs.',
    example: {
      command: 'from matplotlib.colors import Normalize, TwoSlopeNorm',
      says: 'Brings in the two tools that turn data values into colormap positions.',
    },
    seeAlso: ['matplotlib.colors.to_rgb', 'matplotlib.colors.Normalize'],
  },
  {
    name: 'matplotlib.colors.Normalize',
    aliases: ['Normalize'],
    lang: 'python',
    kind: 'class',
    official:
      'A class which, when called, maps values within the interval ``[vmin, vmax]`` linearly to the interval ``[0.0, 1.0]``.',
    source: 'Matplotlib docstring',
    when: 'You want to control which data values get the ends of a colormap. vmin gets the first color and vmax the last. Watch out with signed data: if the range is not balanced around zero, zero will not land on the middle color.',
    flags: [
      ['vmin=', 'the value that maps to 0, the first color'],
      ['vmax=', 'the value that maps to 1, the last color'],
    ],
    example: {
      command: 'Normalize(vmin=0, vmax=10)(2.5)',
      says: 'Gives 0.25: 2.5 is a quarter of the way from 0 to 10.',
    },
    seeAlso: ['matplotlib.colors.TwoSlopeNorm', 'matplotlib.colormaps'],
  },
  {
    name: 'matplotlib.colors.TwoSlopeNorm',
    aliases: ['TwoSlopeNorm'],
    lang: 'python',
    kind: 'class',
    official: 'Normalize data with a set center.',
    source: 'Matplotlib docstring (TwoSlopeNorm.__init__)',
    when: 'Your data has a meaningful middle, like a landing miss of 0 m, but is not balanced around it (from -2 to 6, say). TwoSlopeNorm stretches each side separately so the center value always gets the middle color of a diverging colormap.',
    flags: [
      ['vcenter=', 'the value that maps to 0.5, the middle color'],
      ['vmin=', 'the value that maps to 0'],
      ['vmax=', 'the value that maps to 1'],
    ],
    example: {
      command: 'TwoSlopeNorm(vmin=-2.0, vcenter=0.0, vmax=6.0)([-2, 0, 6])',
      says: 'Gives [0, 0.5, 1]: a miss of exactly 0 lands on the white center.',
    },
    seeAlso: ['matplotlib.colors.Normalize'],
  },
  {
    name: 'matplotlib.colors.to_hex',
    aliases: ['to_hex'],
    lang: 'python',
    kind: 'function',
    official: 'Convert *c* to a hex color.',
    source: 'Matplotlib docstring',
    when: 'You have a color as a name or as three numbers from 0 to 1 and need the #rrggbb code, for a web page or a style file.',
    example: {
      command: 'to_hex("tab:red")',
      says: 'Gives "#d62728", the red of Matplotlib\'s default colors.',
    },
    seeAlso: ['matplotlib.colors.to_rgb'],
  },
  {
    name: 'matplotlib.colors.to_rgb',
    aliases: ['to_rgb'],
    lang: 'python',
    kind: 'function',
    official: 'Convert the :mpltype:`color` *c* to an RGB color tuple.',
    source: 'Matplotlib docstring',
    when: 'You want to do math on a color, such as checking how it looks to someone who is color-blind. It turns any color name or hex code into three numbers from 0 to 1 for red, green and blue. Any opacity is dropped.',
    example: {
      command: 'r, g, b = to_rgb("tab:red")',
      says: 'Sets r, g and b to about 0.84, 0.15 and 0.16.',
    },
    seeAlso: ['matplotlib.colors.to_hex'],
  },
  {
    name: 'matplotlib.dates',
    aliases: ['mdates'],
    lang: 'python',
    kind: 'module',
    official:
      'Matplotlib provides sophisticated date plotting capabilities, standing on the shoulders of python :mod:`datetime` and the add-on module dateutil_.',
    source: 'Matplotlib docstring',
    when: 'Your x axis is real dates and times, like telemetry stamped in UTC, and you want to choose where the ticks go and how they read. Behind the scenes Matplotlib stores each time as a number of days since 1970.',
    example: {
      command: 'import matplotlib.dates as mdates',
      says: 'Loads the date tools under their usual short name.',
    },
    seeAlso: ['matplotlib.dates.DateFormatter', 'matplotlib.dates.MinuteLocator'],
  },
  {
    name: 'matplotlib.dates.DateFormatter',
    aliases: ['mdates.DateFormatter'],
    lang: 'python',
    kind: 'class',
    official: 'Format a tick (in days since the epoch) with a `~datetime.datetime.strftime` format string.',
    source: 'Matplotlib docstring',
    when: 'You want time ticks written your way, such as 17:32 instead of a long date. It uses the same codes as Python\'s strftime: %H hours, %M minutes, %S seconds, %Y-%m-%d a date.',
    flags: [['fmt', 'the format string, such as "%H:%M:%S"']],
    example: {
      command: 'ax.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M"))',
      says: 'Writes each tick on the time axis as hours and minutes, like 17:32.',
    },
    seeAlso: ['matplotlib.dates.MinuteLocator'],
  },
  {
    name: 'matplotlib.dates.MinuteLocator',
    aliases: ['mdates.MinuteLocator'],
    lang: 'python',
    kind: 'class',
    official: 'Make ticks on occurrences of each minute.',
    source: 'Matplotlib docstring',
    when: 'Your time axis covers minutes and you want ticks on whole minutes, or every few minutes. Pair it with a DateFormatter so the ticks read well.',
    flags: [['byminute=', 'which minutes get a tick, such as range(0, 60, 2) for the even ones']],
    example: {
      command: 'ax.xaxis.set_major_locator(mdates.MinuteLocator(byminute=range(0, 60, 2)))',
      says: 'Puts a tick every two minutes, on the even minutes.',
    },
    seeAlso: ['matplotlib.dates.DateFormatter'],
  },
  {
    name: 'matplotlib.pyplot',
    aliases: ['plt'],
    lang: 'python',
    kind: 'module',
    official: '`matplotlib.pyplot` is a state-based interface to matplotlib.',
    source: 'Matplotlib docstring',
    when: 'You want to make figures. "State-based" means pyplot remembers a current figure and current axes, and plt.plot and friends draw on those. That is handy for quick plots but can surprise you when there are several panels; for real scripts, get fig and ax from plt.subplots and draw on ax.',
    example: {
      command: 'import matplotlib.pyplot as plt',
      says: 'Loads pyplot under its usual short name plt, as nearly every Python project does.',
    },
    seeAlso: ['matplotlib.pyplot.subplots', 'matplotlib.pyplot.show', 'matplotlib'],
  },
  {
    name: 'matplotlib.pyplot.axhline',
    aliases: ['plt.axhline'],
    lang: 'python',
    kind: 'function',
    official: 'Add a horizontal line spanning the whole or fraction of the Axes.',
    source: 'Matplotlib docstring',
    when: 'You want a limit or target line across a plot, like a maximum pressure. plt.axhline draws on the current axes, which may not be the panel you expect; with several panels use ax.axhline on the one you mean.',
    flags: [
      ['y', 'the height of the line, in data units'],
      ['color=', 'the line color'],
    ],
    example: {
      command: 'plt.axhline(35.0, color="red")    # max-q limit, kPa',
      says: 'Draws a red line straight across the current plot at 35.',
    },
    seeAlso: ['matplotlib.pyplot.gca', 'matplotlib.pyplot.subplots'],
  },
  {
    name: 'matplotlib.pyplot.figure',
    aliases: ['plt.figure'],
    lang: 'python',
    kind: 'function',
    official: 'Create a new figure, or activate an existing figure.',
    source: 'Matplotlib docstring',
    when: 'You want an empty figure (the whole image) to add panels to yourself. If you just want a figure with a grid of panels, plt.subplots does both steps at once. Close figures you are done with, or a long script keeps them all in memory.',
    flags: [
      ['figsize=', 'width and height in inches'],
      ['layout="constrained"', 'space the panels automatically so labels do not overlap'],
    ],
    example: {
      command: 'fig = plt.figure(figsize=(8.0, 6.0), layout="constrained")',
      says: 'Makes a new, empty 8-by-6-inch figure that will space its panels neatly.',
    },
    seeAlso: ['matplotlib.pyplot.subplots'],
  },
  {
    name: 'matplotlib.pyplot.gca',
    aliases: ['plt.gca'],
    lang: 'python',
    kind: 'function',
    official: 'Get the current Axes.',
    source: 'Matplotlib docstring',
    when: 'You want the panel pyplot will draw on next. It is usually the one made last, not the one you drew on last, which is how plt calls end up on the wrong panel. If none exists yet, it makes one.',
    example: {
      command: 'ax = plt.gca()',
      says: 'Gives you the current panel so you can call ax methods on it.',
    },
    seeAlso: ['matplotlib.pyplot.subplots', 'matplotlib.pyplot.axhline'],
  },
  {
    name: 'matplotlib.pyplot.rcParams',
    aliases: ['plt.rcParams'],
    lang: 'python',
    kind: 'constant',
    official: 'A dict-like key-value store for config parameters, including validation.',
    source: 'Matplotlib docstring (RcParams)',
    when: 'You want to change a default for every plot in a script, such as the font size or the color cycle. Set it before you make the figures; plots already made keep their old look.',
    flags: [
      ['"font.size"', 'the default text size in points'],
      ['"axes.prop_cycle"', 'the colors lines get, in order'],
      ['"pdf.fonttype"', 'set to 42 so PDF text stays real, selectable text'],
    ],
    example: {
      command: 'plt.rcParams["font.size"] = 18    # slide figures',
      says: 'Makes all text in figures made after this line 18 points.',
    },
    seeAlso: ['matplotlib.pyplot'],
  },
  {
    name: 'matplotlib.pyplot.show',
    aliases: ['plt.show'],
    lang: 'python',
    kind: 'function',
    official: 'Display all open figures.',
    source: 'Matplotlib docstring',
    when: 'You want the figures to appear in a window. It waits until you close them, and on a machine with no screen (or with the Agg backend) it shows nothing. In a script that also saves, save first, then show.',
    example: {
      command: 'plt.show()',
      says: 'Opens a window for each open figure and waits until you close them.',
    },
    seeAlso: ['matplotlib.use', 'matplotlib.pyplot.subplots'],
  },
  {
    name: 'matplotlib.pyplot.subplots',
    aliases: ['plt.subplots'],
    lang: 'python',
    kind: 'function',
    official: 'Create a figure and a set of subplots.',
    source: 'Matplotlib docstring',
    when: 'Almost every plot starts here. It gives you the figure and its panels (Axes) in one go, so you can draw on each panel by name. With one panel you get one ax; with several you get an array of them, or unpack them straight away.',
    flags: [
      ['nrows, ncols', 'how many rows and columns of panels (1 and 1 unless you say)'],
      ['figsize=', 'width and height in inches'],
      ['sharex=True', 'all panels share one x axis, so zooming one zooms all'],
      ['layout="constrained"', 'space the panels so labels do not overlap'],
      ['dpi=', 'dots per inch, how sharp a saved image is'],
    ],
    example: {
      command: 'fig, (ax_q, ax_h) = plt.subplots(2, 1, sharex=True, figsize=(6, 5))',
      says: 'Makes a figure with two panels stacked on top of each other that share one time axis.',
    },
    seeAlso: ['matplotlib.pyplot.figure', 'matplotlib.pyplot.gca'],
  },
  {
    name: 'matplotlib.ticker',
    lang: 'python',
    kind: 'module',
    official: 'This module contains classes for configuring tick locating and formatting.',
    source: 'Matplotlib docstring',
    when: 'The automatic ticks on an axis are not what you want. Locators decide where ticks go; formatters decide what each tick says. Set them with ax.xaxis.set_major_locator and ax.xaxis.set_major_formatter.',
    example: {
      command: 'from matplotlib.ticker import MultipleLocator, AutoMinorLocator, FuncFormatter',
      says: 'Brings in two tick locators and a formatter that uses your own function.',
    },
    seeAlso: ['matplotlib.ticker.MultipleLocator', 'matplotlib.ticker.StrMethodFormatter'],
  },
  {
    name: 'matplotlib.ticker.AutoMinorLocator',
    aliases: ['AutoMinorLocator'],
    lang: 'python',
    kind: 'class',
    official:
      'Place evenly spaced minor ticks, with the step size and maximum number of ticks chosen automatically.',
    source: 'Matplotlib docstring',
    when: 'You want small in-between ticks (minor ticks) between the labeled ones, to make values easier to read off. Give a number to split each gap into that many pieces.',
    flags: [['n', 'how many pieces to split each gap between major ticks into']],
    example: {
      command: 'ax.xaxis.set_minor_locator(AutoMinorLocator(3))',
      says: 'With major ticks every 30 s, adds a short tick every 10 s.',
    },
    seeAlso: ['matplotlib.ticker.MultipleLocator'],
  },
  {
    name: 'matplotlib.ticker.EngFormatter',
    aliases: ['EngFormatter'],
    lang: 'python',
    kind: 'class',
    official:
      'Format axis values using engineering prefixes to represent powers of 1000, plus a specified unit, e.g., 10 MHz instead of 1e7.',
    source: 'Matplotlib docstring',
    when: 'Your values span thousands or millions, like frequencies or thrust in newtons, and you want ticks that read 2.5 kHz instead of 2500.',
    flags: [['unit=', 'the unit written after the prefix, such as "Hz" or "N"']],
    example: {
      command: 'EngFormatter(unit="Hz")(2500)',
      says: 'Gives "2.5 kHz".',
    },
    seeAlso: ['matplotlib.ticker.StrMethodFormatter', 'matplotlib.ticker.FuncFormatter'],
  },
  {
    name: 'matplotlib.ticker.FuncFormatter',
    aliases: ['FuncFormatter'],
    lang: 'python',
    kind: 'class',
    official: 'Use a user-defined function for formatting.',
    source: 'Matplotlib docstring',
    when: 'No ready-made formatter writes ticks the way you want, like T+30 s for mission time. Write a function that takes the tick value x and its position number pos, and returns the text.',
    flags: [['func', 'your function f(x, pos) that returns the tick text']],
    example: {
      command: 'ax.xaxis.set_major_formatter(FuncFormatter(lambda x, pos: f"T+{x:.0f} s"))',
      says: 'Writes each tick as mission time, so 30 shows as T+30 s.',
    },
    seeAlso: ['matplotlib.ticker.StrMethodFormatter'],
  },
  {
    name: 'matplotlib.ticker.MultipleLocator',
    aliases: ['MultipleLocator'],
    lang: 'python',
    kind: 'class',
    official: 'Place ticks at every integer multiple of a base plus an offset.',
    source: 'Matplotlib docstring',
    when: 'Your axis has a natural step, like 30 seconds or 45 degrees, and you want a tick on every multiple of it. Pick a step that suits the range; a tiny step on a long axis makes thousands of ticks.',
    flags: [['base', 'the step between ticks']],
    example: {
      command: 'ax.xaxis.set_major_locator(MultipleLocator(30.0))',
      says: 'Puts a major tick at 0, 30, 60 and so on, as far as the axis goes.',
    },
    seeAlso: ['matplotlib.ticker.AutoMinorLocator'],
  },
  {
    name: 'matplotlib.ticker.StrMethodFormatter',
    aliases: ['StrMethodFormatter'],
    lang: 'python',
    kind: 'class',
    official: 'Use a new-style format string (as used by `str.format`) to format the tick.',
    source: 'Matplotlib docstring',
    when: 'You want every tick written with the same number format, like two decimal places. Inside the braces the value must be called x; any other name gives an error.',
    flags: [['fmt', 'the format string, such as "{x:.2f}"']],
    example: {
      command: 'ax.yaxis.set_major_formatter(StrMethodFormatter("{x:.2f}"))',
      says: 'Writes every y tick with two decimals, so 3.14159 shows as 3.14.',
    },
    seeAlso: ['matplotlib.ticker.FuncFormatter', 'matplotlib.ticker.EngFormatter'],
  },
  {
    name: 'matplotlib.use',
    lang: 'python',
    kind: 'function',
    official: 'Select the backend used for rendering and GUI integration.',
    source: 'Matplotlib docstring',
    when: 'Your script only saves figures and may run where there is no screen, like a build server. matplotlib.use("Agg") makes it draw into memory instead of opening windows. Call it near the top, before you make any figures.',
    flags: [['"Agg"', 'the backend that draws into memory and saves PNG files, with no window']],
    example: {
      command: 'matplotlib.use("Agg")',
      says: 'From now on figures are drawn off screen; savefig still works, plt.show shows nothing.',
    },
    seeAlso: ['matplotlib.pyplot.show', 'matplotlib'],
  },

  // Numba
  {
    name: 'numba',
    lang: 'python',
    kind: 'module',
    official: 'Numba is an open source, NumPy-aware optimizing compiler for Python sponsored by Anaconda, Inc.',
    source: 'Numba README (package metadata)',
    when: 'A Python loop over numbers is too slow and you cannot rewrite it as NumPy array math. Numba compiles the function to machine code so the loop runs about as fast as C. It only understands numbers, NumPy arrays and a subset of Python, not general objects.',
    example: {
      command: 'from numba import njit, prange',
      says: 'Brings in the compiling decorator and the parallel version of range.',
    },
    seeAlso: ['numba.njit', 'numba.prange'],
  },
  {
    name: 'numba.jit',
    aliases: ['jit'],
    lang: 'python',
    kind: 'function',
    official: 'This decorator is used to compile a Python function into native code.',
    source: 'Numba docstring',
    when: 'You meet it in older code; prefer @njit. In older Numba, plain @jit quietly fell back to slow "object mode" when it could not compile a function, so code ran but was no faster. jit(forceobj=True) asks for that slow mode on purpose.',
    flags: [['forceobj=True', 'force object mode: it runs, but gets none of the speed-up']],
    example: {
      command: 'erf_obj = jit(forceobj=True)(erf_total)',
      says: 'Makes a "compiled" version that runs in object mode, handy for seeing how slow that mode is.',
    },
    seeAlso: ['numba.njit'],
  },
  {
    name: 'numba.njit',
    aliases: ['njit'],
    lang: 'python',
    kind: 'function',
    official: 'Legacy decorator that is equivalent to the preferred API: jit().',
    source: 'Numba docstring',
    when: 'You want a numeric function compiled for speed and want an error, not a silent slow version, if Numba cannot manage it. The first call is slow because that is when it compiles; time the calls after it.',
    flags: [
      ['cache=True', 'save the compiled code on disk so the next run skips compiling'],
      ['parallel=True', 'allow prange loops to run on several cores'],
      ['nogil=True', 'let other Python threads run while this function does'],
    ],
    example: {
      command: '@njit(cache=True)\ndef coast(h, v, dt): ...',
      says: 'Compiles coast on its first call and keeps the machine code on disk for next time.',
    },
    seeAlso: ['numba.prange', 'numba.jit'],
  },
  {
    name: 'numba.prange',
    aliases: ['prange'],
    lang: 'python',
    kind: 'class',
    official: 'Provides a 1D parallel iterator that generates a sequence of integers.',
    source: 'Numba docstring',
    when: 'Inside an @njit(parallel=True) function, you want a loop\'s iterations shared out across cores. Write prange where you would write range. The iterations must not depend on each other, and sums done in parallel can differ in the last digits from run to run, so compare with a tolerance.',
    example: {
      command: 'for i in prange(v0s.size):\n    out[i] = simulate(v0s[i])',
      says: 'Runs the simulations for different starting speeds at the same time on several cores.',
    },
    seeAlso: ['numba.njit', 'numba.set_num_threads'],
  },
  {
    name: 'numba.set_num_threads',
    lang: 'python',
    kind: 'function',
    official: 'Set the number of threads to use for parallel execution.',
    source: 'Numba docstring',
    when: 'You want to choose how many cores Numba\'s prange loops use, for example to measure how the speed changes with 1, 2, 3 and 4. By default it uses every core it can see. It cannot go above that starting number.',
    flags: [['n', 'how many threads to use']],
    example: {
      command: 'numba.set_num_threads(2)',
      says: 'Parallel Numba loops after this line run on 2 threads.',
    },
    seeAlso: ['numba.prange'],
  },
  {
    name: 'numba.typed',
    lang: 'python',
    kind: 'module',
    official: 'Python wrapper that connects CPython interpreter to the Numba typed-list.',
    source: 'Numba source docstring (numba.typed.typedlist)',
    when: 'You need a list or dictionary that compiled Numba code can use directly, without converting it on every call. For lists of numbers, a NumPy array is usually faster still.',
    example: {
      command: 'from numba import njit, typed',
      says: 'Brings in the compiler and the typed containers.',
    },
    seeAlso: ['numba.typed.List'],
  },
  {
    name: 'numba.typed.List',
    aliases: ['typed.List'],
    lang: 'python',
    kind: 'class',
    official: 'A typed-list usable in Numba compiled functions.',
    source: 'Numba docstring',
    when: 'You have a Python list you must pass into an @njit function many times. A plain list gets copied on every call; a typed.List does not. Every item must be the same type. For numbers, converting once to a NumPy array is usually the better fix.',
    example: {
      command: 'tl = typed.List([1.0, 2.5, 4.0])\nsumsq(tl)',
      says: 'Makes a list Numba can read without copying, then passes it to a compiled function.',
    },
    seeAlso: ['numba.njit', 'numba.typed'],
  },

  // pandas
  {
    name: 'pandas',
    aliases: ['pd'],
    lang: 'python',
    kind: 'module',
    official: 'pandas - a powerful data analysis and manipulation library for Python',
    source: 'pandas docstring',
    when: 'Your data is a table: rows of telemetry with named columns and, often, a time for each row. pandas loads it, lines rows up by time, and resamples, groups and joins it. Check the column types (df.dtypes) after loading; a time column read as plain text is a common trap.',
    example: {
      command: 'import pandas as pd',
      says: 'Loads pandas under its usual short name pd.',
    },
    seeAlso: ['pandas.DataFrame', 'pandas.read_csv'],
  },
  {
    name: 'pandas.Categorical',
    aliases: ['pd.Categorical'],
    lang: 'python',
    kind: 'class',
    official: 'Represent a categorical variable in classic R / S-plus fashion.',
    source: 'pandas docstring',
    when: 'A column holds a few repeated labels, like a flight phase that is always ascent, coast or descent. Storing it as categories keeps each label once and a small number per row, which saves a lot of memory and file space on big tables.',
    example: {
      command: 'pd.Categorical(["ascent", "coast", "ascent"]).categories',
      says: 'Shows the distinct labels, ascent and coast; each row just points to one of them.',
    },
    seeAlso: ['pandas.DataFrame', 'pandas.read_parquet'],
  },
  {
    name: 'pandas.DataFrame',
    aliases: ['pd.DataFrame'],
    lang: 'python',
    kind: 'class',
    official: 'Two-dimensional, size-mutable, potentially heterogeneous tabular data.',
    source: 'pandas docstring',
    when: 'You want a table: named columns that share one index (the row labels, often times). Build one from a dictionary of columns. df["col"] gives a column as a Series; df.loc[rows, cols] picks by label.',
    flags: [
      ['data', 'a dictionary of column name to values'],
      ['index=', 'the row labels, such as a DatetimeIndex'],
    ],
    example: {
      command: 'peaks = pd.DataFrame({"run": [0, 1, 2], "max_q_kPa": [33.5, 36.1, 31.9]})',
      says: 'Makes a 3-row table with a run column and a max-q column.',
    },
    seeAlso: ['pandas.Series', 'pandas.read_csv', 'pandas.merge'],
  },
  {
    name: 'pandas.DatetimeIndex',
    aliases: ['pd.DatetimeIndex'],
    lang: 'python',
    kind: 'class',
    official: 'Immutable ndarray-like of datetime64 data.',
    source: 'pandas docstring',
    when: 'You want a table\'s rows labeled by real times, so you can slice by time, resample, and line up streams. You usually get one from pd.date_range or pd.to_datetime rather than making it directly. Immutable means you replace it rather than change it in place.',
    flags: [['name=', 'a name for the index, such as "time_utc"']],
    example: {
      command: 'pd.DatetimeIndex(idx, name="time_utc")',
      says: 'Turns a list of times into a row index called time_utc.',
    },
    seeAlso: ['pandas.date_range', 'pandas.to_datetime'],
  },
  {
    name: 'pandas.Series',
    aliases: ['pd.Series'],
    lang: 'python',
    kind: 'class',
    official: 'One-dimensional ndarray with axis labels (including time series).',
    source: 'pandas docstring',
    when: 'You have one column of values with a label for each, like chamber pressure over time. Math between two Series lines them up by label, not by position, so labels that appear in only one give NaN (not a number).',
    flags: [
      ['data', 'the values'],
      ['index=', 'the label for each value'],
      ['name=', 'a name for the column'],
    ],
    example: {
      command: 'p = pd.Series([352.4, 318.9, 410.2], index=["E1", "E2", "E3"], name="thrust_kN")\nprint(p["E2"])',
      says: 'Prints 318.9, the value labeled E2.',
    },
    seeAlso: ['pandas.DataFrame'],
  },
  {
    name: 'pandas.Timedelta',
    aliases: ['pd.Timedelta'],
    lang: 'python',
    kind: 'class',
    official: 'Represents a duration, the difference between two dates or times.',
    source: 'pandas docstring',
    when: 'You need a length of time, to shift timestamps or to give a time tolerance. Where pandas expects a time span, a bare number like 0.003 is an error; write pd.Timedelta("3ms").',
    flags: [
      ['seconds=', 'the length in seconds (minutes=, hours= and so on also work)'],
      ['"3ms"', 'a length written as text: 3 milliseconds'],
    ],
    example: {
      command: 'utc = as_gps - pd.Timedelta(seconds=18)    # GPS runs 18 s ahead of UTC',
      says: 'Moves every GPS time back 18 seconds to get UTC.',
    },
    seeAlso: ['pandas.Timestamp', 'pandas.to_timedelta'],
  },
  {
    name: 'pandas.Timestamp',
    aliases: ['pd.Timestamp'],
    lang: 'python',
    kind: 'class',
    official: 'Pandas replacement for python datetime.datetime object.',
    source: 'pandas docstring',
    when: 'You need one moment in time, such as liftoff. Always give a time zone for real events; a time with no zone cannot be compared with one that has a zone.',
    flags: [['tz=', 'the time zone, such as "UTC"']],
    example: {
      command: 't0 = pd.Timestamp("2026-03-14 17:30:00", tz="UTC")    # liftoff',
      says: 'Makes the moment 17:30 UTC on 14 March 2026.',
    },
    seeAlso: ['pandas.Timedelta', 'pandas.to_datetime'],
  },
  {
    name: 'pandas.date_range',
    aliases: ['pd.date_range'],
    lang: 'python',
    kind: 'function',
    official: 'Return a fixed frequency DatetimeIndex.',
    source: 'pandas docstring',
    when: 'You want evenly spaced times, such as a 100 Hz sensor clock, to use as a table\'s index. Give a start and either how many (periods) or an end.',
    flags: [
      ['start', 'the first time'],
      ['periods=', 'how many times to make'],
      ['freq=', 'the spacing, such as "10ms" or "1s"'],
    ],
    example: {
      command: 't = pd.date_range("2026-03-14 12:00:00", periods=300, freq="10ms")',
      says: 'Makes 300 times, 10 milliseconds apart: three seconds of 100 Hz samples.',
    },
    seeAlso: ['pandas.DatetimeIndex', 'pandas.Timestamp'],
  },
  {
    name: 'pandas.merge',
    aliases: ['pd.merge'],
    lang: 'python',
    kind: 'function',
    official: 'Merge DataFrame or named Series objects with a database-style join.',
    source: 'pandas docstring',
    when: 'You want to combine two tables into one by matching rows that share a key, like a run number. The match must be exact, so it is wrong for timestamps from two sensors, which almost never match exactly; use merge_asof for those.',
    flags: [
      ['on=', 'the key column both tables share'],
      ['how=', '"inner" (the default) keeps only matching keys; "left", "right" or "outer" keep more'],
    ],
    example: {
      command: 'table = pd.merge(peaks, inputs, on="run")',
      says: 'Makes one table with each run\'s peak and its inputs side by side; runs missing from either table are dropped.',
    },
    seeAlso: ['pandas.merge_asof', 'pandas.DataFrame'],
  },
  {
    name: 'pandas.merge_asof',
    aliases: ['pd.merge_asof'],
    lang: 'python',
    kind: 'function',
    official: 'Perform a merge by key distance.',
    source: 'pandas docstring',
    when: 'You want to line up two streams recorded at different rates, like GPS and an IMU, by nearest time rather than exact time. You get one row per row of the left table. Both tables must be sorted by the key, or it raises an error.',
    flags: [
      ['on=', 'the key column, usually time'],
      ['direction=', '"backward" (the default) takes the latest earlier row; "nearest" and "forward" also exist'],
      ['tolerance=', 'the farthest a match may be; beyond it you get NaN. Datetime keys need a pd.Timedelta'],
    ],
    example: {
      command: 'both = pd.merge_asof(gps, imu, on="t", direction="nearest", tolerance=0.003)',
      says: 'Gives each GPS fix the IMU reading closest in time, if there is one within 3 ms.',
    },
    seeAlso: ['pandas.merge', 'pandas.Timedelta'],
  },
  {
    name: 'pandas.read_csv',
    aliases: ['pd.read_csv'],
    lang: 'python',
    kind: 'function',
    official: 'Read a comma-separated values (csv) file into DataFrame.',
    source: 'pandas docstring',
    when: 'Your data arrives as a CSV file, the most common telemetry export. CSV is plain text, so times come in as text unless you say otherwise: use parse_dates, and check df.dtypes after every load.',
    flags: [
      ['path', 'the file name, or a file-like object such as io.StringIO(text)'],
      ['parse_dates=', 'the columns to turn into real times'],
      ['index_col=', 'the column to use as the row labels'],
    ],
    example: {
      command: 'df = pd.read_csv("flight.csv", parse_dates=["time_utc"], index_col="time_utc")',
      says: 'Loads flight.csv with real times as the row labels, ready to slice by time.',
    },
    seeAlso: ['pandas.read_parquet', 'pandas.DataFrame'],
  },
  {
    name: 'pandas.read_parquet',
    aliases: ['pd.read_parquet'],
    lang: 'python',
    kind: 'function',
    official: 'Load a parquet object from the file path, returning a DataFrame.',
    source: 'pandas docstring',
    when: 'Your data is in a Parquet file: compressed, stored column by column, with types and time zones kept. Name only the columns you need and it reads only those, which is much faster on big files. It needs pyarrow installed to do the file work.',
    flags: [
      ['path', 'the file name'],
      ['columns=', 'the columns to read; the rest are skipped'],
      ['filters=', 'conditions, so only matching row groups are read'],
    ],
    example: {
      command: 'gz = pd.read_parquet("imu.parquet", columns=["gz_dps"])',
      says: 'Reads just the gz_dps column from imu.parquet, skipping the rest of the file.',
    },
    seeAlso: ['pandas.read_csv', 'pyarrow.parquet'],
  },
  {
    name: 'pandas.to_datetime',
    aliases: ['pd.to_datetime'],
    lang: 'python',
    kind: 'function',
    official: 'Convert argument to datetime.',
    source: 'pandas docstring',
    when: 'You have times as text or as plain numbers of seconds and want real times. For numbers, say the unit and the epoch (the moment they count from); getting the epoch wrong shifts every time without any error.',
    flags: [
      ['unit=', 'what the numbers count, such as "s" for seconds'],
      ['origin=', 'the moment they count from; the Unix epoch, 1970, unless you say'],
      ['utc=True', 'mark the result as UTC'],
    ],
    example: {
      command: 'as_gps = pd.to_datetime(stamp, unit="s", origin=pd.Timestamp("1980-01-06"), utc=True)',
      says: 'Reads stamp as seconds since the GPS epoch of 6 January 1980.',
    },
    seeAlso: ['pandas.Timestamp', 'pandas.to_timedelta'],
  },
  {
    name: 'pandas.to_timedelta',
    aliases: ['pd.to_timedelta'],
    lang: 'python',
    kind: 'function',
    official: 'Convert argument to timedelta.',
    source: 'pandas docstring',
    when: 'You have plain numbers, like seconds since liftoff, and want lengths of time you can add to a Timestamp. Always give the unit.',
    flags: [['unit=', 'what the numbers count, such as "s" for seconds']],
    example: {
      command: 'idx = t0 + pd.to_timedelta(met, unit="s")',
      says: 'Turns mission-elapsed seconds into real UTC times by adding them to liftoff.',
    },
    seeAlso: ['pandas.Timedelta', 'pandas.to_datetime'],
  },

  // PyArrow
  {
    name: 'pyarrow',
    aliases: ['pa'],
    lang: 'python',
    kind: 'module',
    official: 'PyArrow is the python implementation of Apache Arrow.',
    source: 'PyArrow docstring',
    when: 'You work with big column-based data files, especially Parquet. Apache Arrow is a standard way to hold tables in memory column by column. pandas uses pyarrow behind the scenes for Parquet; you use it directly for control over types, row groups and compression.',
    example: {
      command: 'import pyarrow as pa\nimport pyarrow.parquet as pq',
      says: 'Loads pyarrow and its Parquet part under their usual short names.',
    },
    seeAlso: ['pyarrow.parquet', 'pyarrow.csv'],
  },
  {
    name: 'pyarrow.csv',
    aliases: ['pv'],
    lang: 'python',
    kind: 'module',
    official: 'A class that reads an entire CSV file into a Arrow Table',
    source: 'Apache Arrow C++ documentation comment (arrow/csv/reader.h, the reader this module wraps)',
    when: 'You want to read a large CSV file fast, straight into an Arrow table, with the column types you choose, often to convert it to Parquet.',
    example: {
      command: 'import pyarrow.csv as pv',
      says: 'Loads the CSV tools under the short name pv.',
    },
    seeAlso: ['pyarrow.csv.read_csv', 'pyarrow.csv.ConvertOptions'],
  },
  {
    name: 'pyarrow.csv.ConvertOptions',
    aliases: ['pv.ConvertOptions'],
    lang: 'python',
    kind: 'class',
    official: 'Options for converting CSV data.',
    source: 'PyArrow docstring',
    when: 'You want to tell the CSV reader what type each column is, instead of letting it guess. Guessing can pick a type that is too big, or read a time as text.',
    flags: [['column_types=', 'a dictionary of column name to Arrow type']],
    example: {
      command: 'pv.ConvertOptions(column_types={"sat_id": pa.int32(), "value": pa.float64()})',
      says: 'Settings that make sat_id a 32-bit whole number and value a 64-bit decimal.',
    },
    seeAlso: ['pyarrow.csv.read_csv'],
  },
  {
    name: 'pyarrow.csv.read_csv',
    aliases: ['pv.read_csv'],
    lang: 'python',
    kind: 'function',
    official: 'Read a Table from a stream of CSV data.',
    source: 'PyArrow docstring',
    when: 'You want a CSV file as an Arrow table, for example to write it out as Parquet. It gives a pyarrow Table, not a pandas DataFrame; call .to_pandas() if you want one.',
    flags: [['convert_options=', 'a ConvertOptions saying each column\'s type']],
    example: {
      command: 'table = pv.read_csv("telemetry.csv", convert_options=pv.ConvertOptions(column_types=types))',
      says: 'Reads telemetry.csv into an Arrow table with the column types you chose.',
    },
    seeAlso: ['pyarrow.csv.ConvertOptions', 'pyarrow.parquet.write_table'],
  },
  {
    name: 'pyarrow.float64',
    aliases: ['pa.float64'],
    lang: 'python',
    kind: 'function',
    official: 'Create double-precision floating point type.',
    source: 'PyArrow docstring',
    when: 'You are choosing a column type and the column holds decimal numbers that need full precision, like a sensor value. It is the same size as a normal Python float. Arrow prints it as double.',
    example: {
      command: 'pa.float64()',
      says: 'Gives the Arrow type for 64-bit decimal numbers; it prints as double.',
    },
    seeAlso: ['pyarrow.int32', 'pyarrow.string'],
  },
  {
    name: 'pyarrow.int32',
    aliases: ['pa.int32'],
    lang: 'python',
    kind: 'function',
    official: 'Create instance of signed int32 type.',
    source: 'PyArrow docstring',
    when: 'You are choosing a column type for whole numbers that stay small, like a satellite ID. 32 bits hold values up to about 2.1 billion and take half the space of the 64-bit default.',
    example: {
      command: 'pa.int32()',
      says: 'Gives the Arrow type for 32-bit whole numbers that can be negative.',
    },
    seeAlso: ['pyarrow.float64'],
  },
  {
    name: 'pyarrow.parquet',
    aliases: ['pq'],
    lang: 'python',
    kind: 'module',
    official: 'Arrow read adapter class for deserializing Parquet files as Arrow row batches.',
    source: 'Apache Arrow C++ documentation comment (parquet/arrow/reader.h, the reader this module wraps)',
    when: 'You want to read or write Parquet files with full control: which columns and rows to read, how big each row group is, which compression to use. Parquet stores data column by column in row groups, so reading one column or one day skips most of the file.',
    example: {
      command: 'import pyarrow.parquet as pq',
      says: 'Loads the Parquet tools under the short name pq.',
    },
    seeAlso: ['pyarrow.parquet.read_table', 'pyarrow.parquet.write_table', 'pyarrow.parquet.ParquetFile'],
  },
  {
    name: 'pyarrow.parquet.ParquetFile',
    aliases: ['pq.ParquetFile'],
    lang: 'python',
    kind: 'class',
    official: 'Reader interface for a single Parquet file.',
    source: 'PyArrow docstring',
    when: 'You want to look inside a Parquet file without loading it all: its metadata (row groups, rows, column ranges), or its rows a batch at a time when the file is bigger than memory.',
    flags: [
      ['.metadata', 'the file\'s summary: row groups, rows and each column\'s minimum and maximum'],
      ['.iter_batches(batch_size=, columns=)', 'hand back the rows a chunk at a time'],
    ],
    example: {
      command: 'meta = pq.ParquetFile("tlm.parquet").metadata\nprint(meta.num_row_groups)',
      says: 'Prints how many row groups the file has, reading only its small footer.',
    },
    seeAlso: ['pyarrow.parquet.read_table'],
  },
  {
    name: 'pyarrow.parquet.read_table',
    aliases: ['pq.read_table'],
    lang: 'python',
    kind: 'function',
    official: 'Read a Table from Parquet format',
    source: 'PyArrow docstring',
    when: 'You want part of a Parquet file as an Arrow table: only some columns, or only rows that pass a filter. Filters skip whole row groups whose minimum and maximum rule them out, so data written in time order filters fast by time.',
    flags: [
      ['columns=', 'the columns to read'],
      ['filters=', 'a list of (column, operator, value) conditions, such as ("ts", ">=", start)'],
    ],
    example: {
      command: 'day = pq.read_table("telemetry.parquet", columns=["sat_id", "value"],\n                    filters=[("ts", ">=", start), ("ts", "<", end)])',
      says: 'Reads two columns for one day only, skipping row groups outside it.',
    },
    seeAlso: ['pyarrow.parquet.write_table', 'pyarrow.parquet.ParquetFile'],
  },
  {
    name: 'pyarrow.parquet.write_table',
    aliases: ['pq.write_table'],
    lang: 'python',
    kind: 'function',
    official: 'Write a Table to Parquet format.',
    source: 'PyArrow docstring',
    when: 'You want to save an Arrow table as a Parquet file, choosing how it is laid out. Sort the data first (by time, say) so each row group covers a narrow range and later reads can skip most of them.',
    flags: [
      ['row_group_size=', 'the most rows in each row group'],
      ['compression=', 'how to compress, such as "zstd" or "snappy"'],
    ],
    example: {
      command: 'pq.write_table(table, "telemetry.parquet", row_group_size=500_000, compression="zstd")',
      says: 'Writes the table in chunks of 500,000 rows, each compressed with zstd.',
    },
    seeAlso: ['pyarrow.parquet.read_table', 'pyarrow.csv.read_csv'],
  },
  {
    name: 'pyarrow.string',
    aliases: ['pa.string'],
    lang: 'python',
    kind: 'function',
    official: 'Create UTF8 variable-length string type.',
    source: 'PyArrow docstring',
    when: 'You are choosing a column type for text, like a channel name. If the column only ever holds a few repeated names, a categorical (dictionary) type takes far less space.',
    example: {
      command: 'pa.string()',
      says: 'Gives the Arrow type for text of any length.',
    },
    seeAlso: ['pyarrow.int32', 'pyarrow.float64'],
  },
  {
    name: 'pyarrow.timestamp',
    aliases: ['pa.timestamp'],
    lang: 'python',
    kind: 'function',
    official: 'Create instance of timestamp type with resolution and optional time zone.',
    source: 'PyArrow docstring',
    when: 'You are choosing a column type for moments in time. Give the resolution (how fine the ticks are) and, for real events, a time zone, so the times keep their meaning when someone else reads the file.',
    flags: [
      ['unit', 'the resolution: "s", "ms", "us" (microseconds) or "ns"'],
      ['tz=', 'the time zone, such as "UTC"'],
    ],
    example: {
      command: 'pa.timestamp("us", tz="UTC")',
      says: 'Gives the type timestamp[us, tz=UTC]: times to the microsecond, in UTC.',
    },
    seeAlso: ['pyarrow.int32', 'pyarrow.csv.ConvertOptions'],
  },

  // pytest
  {
    name: 'pytest',
    lang: 'python',
    kind: 'module',
    official: 'pytest: unit and functional testing with Python.',
    source: 'pytest docstring',
    when: 'You want to check your code automatically. Run pytest in a folder and it finds files named test_*.py, runs every function named test_* in them, and reports which ones failed. A plain assert is all a test needs. It is a separate package: pip install pytest.',
    flags: [
      ['-q', 'quiet: less output'],
      ['-m "not slow"', 'run only tests whose markers match'],
      ['-k word', 'run only tests whose names contain word'],
    ],
    example: {
      command: 'pytest -q tests',
      says: 'Runs every test in the tests folder and prints a dot for each pass and a summary line.',
    },
    seeAlso: ['pytest.approx', 'pytest.fixture', 'pytest.mark.parametrize'],
  },
  {
    name: 'pytest.approx',
    lang: 'python',
    kind: 'function',
    official:
      'Assert that two numbers (or two ordered sequences of numbers) are equal to each other within some tolerance.',
    source: 'pytest docstring',
    when: 'You are comparing decimal numbers in a test. Floats are rarely exactly equal (0.1 + 0.2 is not 0.3), so compare within a tolerance. A relative tolerance on an expected value of 0 allows no gap at all; give abs= when the answer should be zero.',
    flags: [
      ['rel=', 'allowed gap as a fraction of the expected value, such as 1e-9'],
      ['abs=', 'allowed gap as a fixed amount, needed when the expected value is 0'],
    ],
    example: {
      command: 'pytest.approx(0.3) == 0.1 + 0.2',
      says: 'Gives True, where a plain 0.1 + 0.2 == 0.3 gives False.',
    },
    seeAlso: ['pytest'],
  },
  {
    name: 'pytest.fixture',
    lang: 'python',
    kind: 'function',
    official: 'Decorator to mark a fixture factory function.',
    source: 'pytest docstring',
    when: 'Several tests need the same thing set up, like a fake altimeter or a loaded table. Write it once as a fixture; any test that names it as a parameter gets it. Code after a yield in the fixture runs as cleanup afterwards.',
    flags: [
      ['scope=', 'how long one copy lives: "function" (the default), "module" or "session"'],
      ['params=', 'a list of versions; every test using it runs once per version'],
    ],
    example: {
      command: '@pytest.fixture(scope="module")\ndef nav_table():\n    return load_table("nav.csv")',
      says: 'Loads the table once for all the tests in this file that ask for nav_table.',
    },
    seeAlso: ['pytest', 'pytest.mark.parametrize'],
  },
  {
    name: 'pytest.importorskip',
    lang: 'python',
    kind: 'function',
    official:
      'Import and return the requested module ``modname``, or skip the current test if the module cannot be imported.',
    source: 'pytest docstring',
    when: 'A test needs a package that only some machines have, like the hardware drivers on the test rig. Elsewhere the test is reported as skipped instead of failing.',
    flags: [['modname', 'the dotted name of the module to import']],
    example: {
      command: 'drivers = pytest.importorskip("avionics.drivers")    # only on the rig',
      says: 'Imports the drivers if they exist; otherwise this test is skipped.',
    },
    seeAlso: ['pytest.mark.skip'],
  },
  {
    name: 'pytest.mark',
    lang: 'python',
    kind: 'constant',
    official: 'Factory for :class:`MarkDecorator` objects - exposed as a ``pytest.mark`` singleton instance.',
    source: 'pytest docstring',
    when: 'You want to tag a test: to run it once per case, skip it, or group it (slow, hil) so you can pick which to run with -m. pytest.mark.anything makes a marker; register your own names in the settings file, or pytest warns about a possible typo.',
    example: {
      command: 'pytest.mark.slow',
      says: 'A marker named slow; put @pytest.mark.slow above a test, then run pytest -m "not slow" to leave those out.',
    },
    seeAlso: ['pytest.mark.parametrize', 'pytest.mark.skip', 'pytest.mark.hil'],
  },
  {
    name: 'pytest.mark.hil',
    lang: 'python',
    kind: 'function',
    official: 'A decorator for applying a mark on test functions and classes.',
    source: 'pytest docstring (MarkDecorator)',
    when: 'hil is not built in: it is a marker a team makes up for tests that need a hardware-in-the-loop rig (real flight hardware wired to a simulator). Mark those tests so everyday runs can leave them out with -m "not hil". Register it in the settings file with a short description.',
    example: {
      command: '@pytest.mark.hil\ndef test_baro_reads_pad_pressure(): ...',
      says: 'Tags the test as needing the rig; pytest -m "not hil" skips it.',
    },
    seeAlso: ['pytest.mark', 'pytest.importorskip'],
  },
  {
    name: 'pytest.mark.parametrize',
    lang: 'python',
    kind: 'function',
    official: 'call a test function multiple times passing in different arguments in turn.',
    source: 'pytest built-in marker description (pytest --markers)',
    when: 'You want to run one test on a table of cases without copying it. Each case is reported as its own test, so you can see exactly which one failed. With several names, give each case as a tuple.',
    flags: [
      ['argnames', 'the parameter name, or several separated by commas: "method, p"'],
      ['argvalues', 'a list of values, or of tuples when there are several names'],
      ['ids=', 'readable names for the cases, shown in the report'],
    ],
    example: {
      command: '@pytest.mark.parametrize("phi_deg", [0.0, 30.0, 90.0, 180.0])\ndef test_roll_keeps_length(phi_deg): ...',
      says: 'Runs the test four times, once for each angle, and reports each run on its own.',
    },
    seeAlso: ['pytest.mark', 'pytest.fixture'],
  },
  {
    name: 'pytest.mark.skip',
    lang: 'python',
    kind: 'function',
    official: 'skip the given test function with an optional reason.',
    source: 'pytest built-in marker description (pytest --markers)',
    when: 'A test cannot run yet, or one case in a parametrize table is not supported. The test is reported as skipped with your reason, so it is not forgotten. A skipped test protects nothing; come back to it.',
    flags: [['reason=', 'why it is skipped, shown in the report']],
    example: {
      command: 'pytest.param(384400, id="lunar", marks=pytest.mark.skip(reason="needs third-body gravity"))',
      says: 'Keeps the lunar case in the table but skips it, showing the reason.',
    },
    seeAlso: ['pytest.mark', 'pytest.importorskip'],
  },
]
