import type { CommandRef } from './types'

export const COMMANDS: CommandRef[] = [
  {
    name: 'std::cell',
    aliases: ['core::cell'],
    lang: 'rust',
    kind: 'module',
    official: 'Shareable mutable containers.',
    source: 'Rust standard library documentation',
    when: 'You need to change a value through a shared reference, which normal borrowing forbids. The types in here (Cell and RefCell) move the "only one writer" check from compile time to run time, so a mistake becomes a panic instead of a compile error.',
    flags: [
      ['Cell', 'swap a small Copy value in and out'],
      ['RefCell', 'borrow the inside, checked while the program runs'],
    ],
    example: { command: 'use std::cell::{Cell, RefCell};', says: 'Brings the two interior-mutability types into scope so you can write Cell and RefCell directly.' },
    seeAlso: ['std::cell::Cell', 'std::cell::RefCell'],
  },
  {
    name: 'std::cmp',
    aliases: ['core::cmp'],
    lang: 'rust',
    kind: 'module',
    official: 'Utilities for comparing and ordering values.',
    source: 'Rust standard library documentation',
    when: 'You are comparing or ordering values: min and max, sorting keys, or the Ordering you get back from a comparison. Floats only have a partial order because of NaN, so sorting them needs total_cmp or partial_cmp.',
    example: { command: 'let top = std::cmp::max(apogee_a, apogee_b);', says: 'Keeps whichever of the two apogee heights is bigger.' },
    seeAlso: ['std::ops'],
  },
  {
    name: 'std::collections',
    lang: 'rust',
    kind: 'module',
    official: 'Collection types.',
    source: 'Rust standard library documentation',
    when: 'You need a container beyond Vec: a map from keys to values, a set, or a double-ended queue. Pick HashMap for fast lookups in any order and BTreeMap when you want the keys kept sorted.',
    flags: [
      ['HashMap', 'key to value, fast, no fixed order'],
      ['BTreeMap', 'key to value, kept sorted by key'],
    ],
    example: { command: 'use std::collections::{BTreeMap, HashMap};', says: 'Brings both map types into scope for the rest of the file.' },
    seeAlso: ['std::collections::HashMap', 'std::collections::BTreeMap'],
  },
  {
    name: 'std::fmt',
    aliases: ['core::fmt'],
    lang: 'rust',
    kind: 'module',
    official: 'Utilities for formatting and printing Strings.',
    source: 'Rust standard library documentation',
    when: 'You are teaching your own type how to print itself, by implementing Display (for people) or Debug (for programmers). The formatter and its Result type both live here, so impls usually start with use std::fmt; and write fmt::Formatter and fmt::Result.',
    flags: [
      ['fmt::Display', 'the trait behind {} in println!'],
      ['fmt::Debug', 'the trait behind {:?}'],
      ['fmt::Formatter', 'where your impl writes its text'],
      ['fmt::Result', 'what the fmt method returns: Ok or an error'],
    ],
    example: { command: 'impl fmt::Display for Vec3 {\n    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result { write!(f, "({}, {}, {})", self.x, self.y, self.z) }\n}', says: 'Lets println!("{v}") print a Vec3 as (1, 2, 3).' },
    seeAlso: ['std::fmt::Debug', 'core::fmt::Write', 'write!'],
  },
  {
    name: 'std::fs',
    lang: 'rust',
    kind: 'module',
    official: 'Filesystem manipulation operations.',
    source: 'Rust standard library documentation',
    when: 'Your program needs to read or write files on disk. It needs an operating system, so it does not exist in no_std code on a microcontroller.',
    example: { command: 'let log = std::fs::read_to_string("telemetry.log")?;', says: 'Reads the whole telemetry.log file into one String, or returns the error if it cannot.' },
    seeAlso: ['std::fs::read_to_string'],
  },
  {
    name: 'std::hint',
    aliases: ['core::hint'],
    lang: 'rust',
    kind: 'module',
    official: 'Hints to compiler that affects how code should be emitted or optimized.',
    source: 'Rust standard library documentation',
    when: 'You want to give the compiler or processor a hint without changing what the code means: stop it from optimizing away a benchmark, or tell the CPU you are busy-waiting.',
    flags: [
      ['black_box', 'hide a value from the optimizer'],
      ['spin_loop', 'say "I am waiting in a loop"'],
    ],
    example: { command: 'use std::hint::black_box;', says: 'Brings black_box into scope, usually for a benchmark.' },
    seeAlso: ['std::hint::black_box', 'std::hint::spin_loop'],
  },
  {
    name: 'std::marker',
    aliases: ['core::marker'],
    lang: 'rust',
    kind: 'module',
    official: 'Primitive traits and types representing basic properties of types.',
    source: 'Rust standard library documentation',
    when: 'You meet traits that describe what a type is rather than what it does: Send (safe to move to another thread), Sync (safe to share between threads), Copy and Sized. They have no methods; the compiler mostly works them out for you.',
    flags: [
      ['Send', 'can be moved to another thread'],
      ['Sync', 'can be shared between threads by reference'],
    ],
    example: { command: 'fn launch<T: Send + \'static>(job: T) { /* ... */ }', says: 'Only accepts values that are safe to hand to another thread.' },
    seeAlso: ['std::thread'],
  },
  {
    name: 'std::net',
    lang: 'rust',
    kind: 'module',
    official: 'Networking primitives for TCP/UDP communication.',
    source: 'Rust standard library documentation',
    when: 'Your program talks over a network with TCP or UDP, such as a ground-station tool listening for telemetry packets. Like std::fs it needs an operating system, so it is not in core.',
    example: { command: 'let sock = std::net::UdpSocket::bind("0.0.0.0:5005")?;', says: 'Opens a UDP socket that listens for packets on port 5005.' },
    seeAlso: ['std::fs'],
  },
  {
    name: 'std::ops',
    aliases: ['core::ops'],
    lang: 'rust',
    kind: 'module',
    official: 'Overloadable operators.',
    source: 'Rust standard library documentation',
    when: 'You want your own type to work with operators such as +, -, * or *v. Each operator is a trait in here (Add, Sub, Mul, Neg, AddAssign, Deref, Index, ...); implement the trait and the operator works.',
    flags: [
      ['Add, Sub, Mul, Neg', 'the traits behind +, -, * and unary minus'],
      ['AddAssign', 'the trait behind +='],
      ['Deref', 'the trait behind *v'],
    ],
    example: { command: 'use std::ops::{Add, AddAssign, Mul, Neg, Sub};', says: 'Brings the operator traits into scope so you can implement them for a Vec3.' },
    seeAlso: ['std::ops::Add', 'std::ops::Deref'],
  },
  {
    name: 'std::panic',
    aliases: ['core::panic'],
    lang: 'rust',
    kind: 'module',
    official: 'Panic support in the standard library.',
    source: 'Rust standard library documentation',
    when: 'You want to control what happens when the program panics: record the details with a panic hook, or (rarely) stop an unwinding panic at a boundary. A panic is for bugs, not for errors you expect; use Result for those.',
    flags: [
      ['panic::set_hook', 'install a function that runs with the panic details'],
      ['panic::catch_unwind', 'stop an unwinding panic at a boundary'],
    ],
    example: { command: 'panic::set_hook(Box::new(|info| eprintln!("CRASH RECORD: {info}")));', says: 'Makes every panic print a crash record line before the program stops.' },
    seeAlso: ['std::panic::catch_unwind', 'core::panic::PanicInfo'],
  },
  {
    name: 'std::sync',
    lang: 'rust',
    kind: 'module',
    official: 'Useful synchronization primitives.',
    source: 'Rust standard library documentation',
    when: 'Threads need to share data safely. Arc shares ownership across threads, Mutex and RwLock let one thread change the data at a time, and OnceLock sets a value exactly once. Holding a lock too long makes every other thread wait.',
    flags: [
      ['Arc', 'shared ownership that works across threads'],
      ['Mutex', 'one thread at a time may use the data'],
      ['RwLock', 'many readers or one writer'],
      ['OnceLock', 'a value set once, then read forever'],
      ['atomic', 'integers changed in one indivisible step'],
    ],
    example: { command: 'use std::sync::{Arc, Mutex};', says: 'Brings the two types for sharing changeable data between threads into scope.' },
    seeAlso: ['std::sync::Arc', 'std::sync::atomic', 'std::thread'],
  },
  {
    name: 'std::sync::atomic',
    aliases: ['core::sync::atomic'],
    lang: 'rust',
    kind: 'module',
    official: 'Atomic types',
    source: 'Rust standard library documentation',
    when: 'Several threads, or a main loop and an interrupt handler, update a counter or flag, and you want no lock. An atomic operation happens in one indivisible step, so no one sees it half-done. The Ordering argument says how other memory reads and writes may move around it; Relaxed is enough for a plain counter.',
    flags: [
      ['AtomicU32', 'a u32 that can be changed atomically, even in a static'],
      ['fetch_add', 'add and return the old value, in one step'],
      ['Ordering::Relaxed', 'no ordering promise beyond the operation itself'],
    ],
    example: { command: 'static TICKS: AtomicU32 = AtomicU32::new(0);\nTICKS.fetch_add(1, Ordering::Relaxed);', says: 'Adds one to a global tick counter safely, even from an interrupt.' },
    seeAlso: ['std::sync', 'std::sync::Arc'],
  },
  {
    name: 'std::task',
    aliases: ['core::task'],
    lang: 'rust',
    kind: 'module',
    official: 'Types and Traits for working with asynchronous tasks.',
    source: 'Rust standard library documentation',
    when: 'You look under async/await: an executor polls futures and passes them a Context holding a Waker, and each poll returns Poll::Ready or Poll::Pending. Everyday async code never touches these; executors and hand-written futures do.',
    flags: [
      ['Context', 'what poll receives; it holds the Waker'],
      ['Poll', 'Ready(value) or Pending'],
      ['Waker', 'how a future asks to be polled again'],
    ],
    example: { command: 'use std::task::{Context, Poll, Waker};', says: 'Brings the pieces needed to poll a future by hand into scope.' },
    seeAlso: ['std::future::Future'],
  },
  {
    name: 'std::thread',
    lang: 'rust',
    kind: 'module',
    official: 'Native threads.',
    source: 'Rust standard library documentation',
    when: 'You want work to run at the same time as the rest of the program, on another operating-system thread. Data moved into a thread must be Send, and a borrowed value must outlive the thread, which is why thread::scope exists.',
    flags: [
      ['thread::spawn', 'start a thread that owns what it uses'],
      ['thread::scope', 'start threads that may borrow local data'],
      ['join', 'wait for a thread and get its result'],
    ],
    example: { command: 'use std::thread;', says: 'Lets you write thread::spawn and thread::scope.' },
    seeAlso: ['std::thread::spawn', 'std::thread::scope'],
  },
  {
    name: 'std::cell::Cell',
    aliases: ['core::cell::Cell'],
    lang: 'rust',
    kind: 'type',
    official: 'A mutable memory location.',
    source: 'Rust standard library documentation',
    when: 'You need to change a small Copy value (a counter, a flag) through a shared reference. get copies the value out and set puts a new one in; you can never borrow the inside, so it cannot go wrong. It is not Sync, so it cannot be shared between threads.',
    flags: [
      ['Cell::new(v)', 'wrap a starting value'],
      ['get()', 'copy the value out'],
      ['set(v)', 'replace the value'],
    ],
    example: { command: 'let reads = Cell::new(0u32);\nreads.set(reads.get() + 1);', says: 'Counts one more sensor read, even though reads is not declared mut.' },
    seeAlso: ['std::cell::RefCell', 'std::cell'],
  },
  {
    name: 'std::cell::RefCell',
    aliases: ['core::cell::RefCell'],
    lang: 'rust',
    kind: 'type',
    official: 'A mutable memory location with dynamically checked borrow rules',
    source: 'Rust standard library documentation',
    when: 'You need to change something inside a shared value, often together with Rc. It checks the borrowing rules while the program runs: many borrow() at once, or one borrow_mut(), never both. Breaking that rule is a panic at run time, not a compile error.',
    flags: [
      ['RefCell::new(v)', 'wrap a value'],
      ['borrow()', 'read access, many at once'],
      ['borrow_mut()', 'write access, only one at a time'],
      ['try_borrow_mut()', 'like borrow_mut but returns an error instead of panicking'],
    ],
    example: { command: 'let log = Rc::new(RefCell::new(Vec::new()));\nlog.borrow_mut().push("stage 1 sep");', says: 'Adds an event to a log that several owners share.' },
    seeAlso: ['std::cell::Cell', 'std::rc::Rc'],
  },
  {
    name: 'core::convert::Infallible',
    aliases: ['std::convert::Infallible'],
    lang: 'rust',
    kind: 'type',
    official: 'The error type for errors that can never happen.',
    source: 'Rust standard library documentation',
    when: 'A trait asks you for an error type, but your operation can never fail, such as a pretend I2C bus in a test. Using Infallible says so in the type, and the compiler knows that Err can never happen.',
    example: { command: 'impl ErrorType for FakeBus { type Error = Infallible; }', says: 'Says the fake bus never returns an error.' },
    seeAlso: ['std::error::Error'],
  },
  {
    name: 'core::fmt::Write',
    aliases: ['std::fmt::Write'],
    lang: 'rust',
    kind: 'type',
    official: 'A trait for writing or formatting into Unicode-accepting buffers or streams.',
    source: 'Rust standard library documentation',
    when: 'You want write! to format text into something that is not a file or the screen, such as a String or a fixed-size heapless::String. Do not mix it up with std::io::Write, which writes bytes to files and sockets.',
    flags: [
      ['write!(buf, ...)', 'format text into buf; returns an error if it does not fit'],
      ['write_str', 'the one method you implement yourself'],
    ],
    example: { command: 'use core::fmt::Write;\nwrite!(line, "T+{t} temp={temp:.1}").unwrap();', says: 'Formats a telemetry line into a heapless String.' },
    seeAlso: ['std::fmt', 'write!', 'heapless'],
  },
  {
    name: 'core::panic::PanicInfo',
    lang: 'rust',
    kind: 'type',
    official: 'A struct providing information about a panic.',
    source: 'Rust standard library documentation',
    when: 'You write the #[panic_handler] function that a no_std program must have, and it receives a &PanicInfo with the message and the file and line where the panic happened. With std, a panic hook receives the same details.',
    flags: [
      ['location()', 'the file and line of the panic, if known'],
      ['message()', 'the panic message'],
    ],
    example: { command: '#[panic_handler]\nfn panic(_info: &PanicInfo) -> ! { loop {} }', says: 'Stops the microcontroller in an endless loop if anything panics.' },
    seeAlso: ['std::panic', 'cortex_m_rt'],
  },
  {
    name: 'std::collections::BTreeMap',
    lang: 'rust',
    kind: 'type',
    official: 'An ordered map based on a B-Tree.',
    source: 'Rust standard library documentation',
    when: 'You want a key-value map that keeps its keys in sorted order, so looping over it goes smallest key first. It is a bit slower than HashMap for single lookups.',
    flags: [
      ['BTreeMap::new()', 'an empty map'],
      ['insert(k, v)', 'add or replace a pair'],
      ['entry(k).or_insert(v)', 'get the value, adding v first if the key is missing'],
      ['first_key_value()', 'the pair with the smallest key'],
      ['range(a..b)', 'the pairs with keys in a range'],
    ],
    example: { command: 'let mut passes = BTreeMap::new();\npasses.insert(1415, "Svalbard");', says: 'Stores a ground-station pass under its time, kept in time order.' },
    seeAlso: ['std::collections::HashMap', 'std::collections'],
  },
  {
    name: 'std::collections::HashMap',
    lang: 'rust',
    kind: 'type',
    official: 'A hash map implemented with quadratic probing and SIMD lookup.',
    source: 'Rust standard library documentation',
    when: 'You want to look values up by a key, like a Python dict. Lookups are fast, but looping over it gives the pairs in no particular order, and the order can change from run to run.',
    flags: [
      ['HashMap::new()', 'an empty map'],
      ['insert(k, v)', 'add or replace a pair'],
      ['get(&k)', 'Some(&value) or None'],
      ['entry(k).or_insert(v)', 'get the value, adding v first if the key is missing'],
    ],
    example: { command: '*counts.entry("GYRO").or_insert(0) += 1;', says: 'Adds one to the GYRO count, starting it at 0 the first time.' },
    seeAlso: ['std::collections::BTreeMap', 'std::collections'],
  },
  {
    name: 'std::error::Error',
    lang: 'rust',
    kind: 'type',
    official: 'Error is a trait representing the basic expectations for error values, i.e., values of type E in Result<T, E>.',
    source: 'Rust standard library documentation',
    when: 'You make your own error type and want it to work with ?, Box<dyn Error> and crates like anyhow. It needs Debug and Display first, and its optional source() method returns the lower-level error that caused this one.',
    flags: [
      ['source()', 'the error that caused this one, if any'],
    ],
    example: { command: 'impl std::error::Error for FrameError {}', says: 'Marks FrameError as a proper error type; Display and Debug must already exist.' },
    seeAlso: ['std::fmt::Debug', 'thiserror', 'anyhow'],
  },
  {
    name: 'std::fmt::Debug',
    aliases: ['core::fmt::Debug'],
    lang: 'rust',
    kind: 'type',
    official: '? formatting.',
    source: 'Rust standard library documentation',
    when: 'You want to print a value for yourself while debugging, with {:?}, or {:#?} for one field per line. Almost every type derives it with #[derive(Debug)]; it is not meant for messages to users (that is Display).',
    flags: [
      ['#[derive(Debug)]', 'let the compiler write it for you'],
      ['{:?}', 'print with Debug'],
      ['{:#?}', 'print with Debug, spread over lines'],
    ],
    example: { command: '#[derive(Debug)]\nstruct Burn { dv: f64, secs: u32 }\nprintln!("{:?}", burn);', says: 'Prints Burn { dv: 12.5, secs: 40 }.' },
    seeAlso: ['std::fmt', 'std::error::Error'],
  },
  {
    name: 'std::future::Future',
    aliases: ['core::future::Future'],
    lang: 'rust',
    kind: 'type',
    official: 'A future represents an asynchronous computation, commonly obtained by use of async.',
    source: 'Rust standard library documentation',
    when: 'You look at what an async fn really returns: a value that does nothing until an executor polls it. Forgetting .await on a future means its work never runs, and the compiler warns you.',
    flags: [
      ['poll', 'the method an executor calls to push the work forward'],
      ['Output', 'the type of the finished value'],
    ],
    example: { command: 'fn read_sensor() -> impl Future<Output = f32> { async { 21.5 } }', says: 'Returns a future that gives 21.5 once it is awaited.' },
    seeAlso: ['std::future::ready', 'std::task'],
  },
  {
    name: 'std::num::ParseFloatError',
    lang: 'rust',
    kind: 'type',
    official: 'An error which can be returned when parsing a float.',
    source: 'Rust standard library documentation',
    when: 'You parse text into an f64 or f32 with parse, and this is the error you get back when the text is not a number. Rust always expects a dot as the decimal point, so "12,5" fails.',
    example: { command: 'let bad: Result<f64, ParseFloatError> = "12,5".parse();', says: 'Gives Err, because a comma is not a decimal point in Rust.' },
    seeAlso: ['std::num::ParseIntError'],
  },
  {
    name: 'std::num::ParseIntError',
    lang: 'rust',
    kind: 'type',
    official: 'An error which can be returned when parsing an integer.',
    source: 'Rust standard library documentation',
    when: 'You parse text into an integer (parse, or from_str_radix for hex) and this is the error when it fails: empty text, a bad digit, or a number too big for the type.',
    example: { command: 'let b = u8::from_str_radix("0Z", 16);', says: 'Gives Err(ParseIntError), because Z is not a hex digit.' },
    seeAlso: ['std::num::ParseFloatError', 'thiserror'],
  },
  {
    name: 'std::ops::Add',
    aliases: ['core::ops::Add'],
    lang: 'rust',
    kind: 'type',
    official: 'The addition operator +.',
    source: 'Rust standard library documentation',
    when: 'You want a + b to work for your own type, such as adding two Vec3 velocity vectors. You choose the result type with type Output. For a Copy type you usually also derive Clone and Copy, so a + b does not use up a and b.',
    flags: [
      ['type Output', 'what a + b produces'],
      ['fn add(self, rhs)', 'the code that runs for +'],
    ],
    example: { command: 'impl Add for Vec3 {\n    type Output = Vec3;\n    fn add(self, o: Vec3) -> Vec3 { Vec3 { x: self.x + o.x, y: self.y + o.y, z: self.z + o.z } }\n}', says: 'Lets you write v + dv for two Vec3 values.' },
    seeAlso: ['std::ops'],
  },
  {
    name: 'std::ops::Deref',
    aliases: ['core::ops::Deref'],
    lang: 'rust',
    kind: 'type',
    official: 'Used for immutable dereferencing operations, like *v.',
    source: 'Rust standard library documentation',
    when: 'You make a wrapper type (a smart pointer or a newtype) and want *w, and method calls, to reach the value inside. Use it for pointer-like wrappers, not to fake inheritance between ordinary structs.',
    flags: [
      ['type Target', 'what *w gives you'],
      ['fn deref(&self)', 'returns a reference to the inside'],
    ],
    example: { command: 'impl Deref for Meters {\n    type Target = f64;\n    fn deref(&self) -> &f64 { &self.0 }\n}', says: 'Lets *altitude read the f64 inside a Meters value.' },
    seeAlso: ['std::ops', 'std::rc::Rc'],
  },
  {
    name: 'std::rc::Rc',
    aliases: ['alloc::rc::Rc'],
    lang: 'rust',
    kind: 'type',
    official: 'A single-threaded reference-counting pointer. ‘Rc’ stands for ‘Reference Counted’.',
    source: 'Rust standard library documentation',
    when: 'Several parts of a single-threaded program need to own the same value. Rc::clone just adds one to a count, and the value is freed when the last owner goes away. It is not Send; use Arc across threads. Two Rc values pointing at each other are never freed.',
    flags: [
      ['Rc::new(v)', 'put v on the heap with a count of 1'],
      ['Rc::clone(&rc)', 'another owner; the count goes up by 1'],
      ['Rc::strong_count(&rc)', 'how many owners there are'],
    ],
    example: { command: 'let plan = Rc::new(flight_plan);\nlet copy = Rc::clone(&plan);', says: 'Gives the same flight plan two owners without copying it.' },
    seeAlso: ['std::sync::Arc', 'std::cell::RefCell'],
  },
  {
    name: 'std::sync::Arc',
    aliases: ['alloc::sync::Arc'],
    lang: 'rust',
    kind: 'type',
    official: 'A thread-safe reference-counting pointer. ‘Arc’ stands for ‘Atomically Reference Counted’.',
    source: 'Rust standard library documentation',
    when: 'Several threads need to own the same value. It works like Rc but keeps its count with atomic operations, so it is safe across threads. It only gives shared, read-only access; wrap the inside in a Mutex or RwLock to change it.',
    flags: [
      ['Arc::new(v)', 'put v on the heap, shared'],
      ['Arc::clone(&a)', 'another owner, usually moved into a thread'],
    ],
    example: { command: 'let state = Arc::new(Mutex::new(0u32));\nlet s2 = Arc::clone(&state);', says: 'Makes a second handle to the same locked counter, ready to move into a thread.' },
    seeAlso: ['std::rc::Rc', 'std::sync', 'std::thread::spawn'],
  },
  {
    name: 'std::time::Instant',
    lang: 'rust',
    kind: 'type',
    official: 'A measurement of a monotonically nondecreasing clock. Opaque and useful only with Duration.',
    source: 'Rust standard library documentation',
    when: 'You want to time how long some code takes. Take Instant::now() before and call elapsed() after. It only measures durations; it cannot tell you the date or time of day.',
    flags: [
      ['Instant::now()', 'the moment right now'],
      ['elapsed()', 'how long ago that moment was, as a Duration'],
    ],
    example: { command: 'let t0 = Instant::now();\nrun_filter();\nprintln!("{:?}", t0.elapsed());', says: 'Prints how long run_filter took, such as 1.84ms.' },
    seeAlso: ['std::hint::black_box'],
  },
  {
    name: 'std::vec::Vec',
    aliases: ['alloc::vec::Vec'],
    lang: 'rust',
    kind: 'type',
    official: 'A contiguous growable array type, written as Vec<T>, short for ‘vector’.',
    source: 'Rust standard library documentation',
    when: 'You want a list that can grow and shrink while the program runs. It keeps its items side by side on the heap, so it does not exist in core; no_std code uses a fixed-capacity list such as heapless::Vec instead.',
    flags: [
      ['Vec::new()', 'an empty list, no heap memory yet'],
      ['Vec::with_capacity(n)', 'room for n items up front'],
      ['push / pop', 'add or remove at the end'],
    ],
    example: { command: 'let mut temps: Vec<f32> = Vec::with_capacity(64);', says: 'Makes an empty list of temperatures with room for 64 before it has to grow.' },
    seeAlso: ['std::vec::Vec::push', 'heapless', 'vec!'],
  },
  {
    name: 'std::vec::Vec::push',
    aliases: ['Vec::push', 'std::Vec::push'],
    lang: 'rust',
    kind: 'method',
    official: 'Appends an element to the back of a collection.',
    source: 'Rust standard library documentation',
    when: 'You add one item to the end of a Vec. If there is no room left, the Vec asks the heap for a bigger block and moves everything there, which takes time; with_capacity up front avoids that in a flight loop.',
    flags: [
      ['value', 'the item to add; the Vec takes ownership of it'],
    ],
    example: { command: 'readings.push(22.4);', says: 'Adds 22.4 to the end of readings.' },
    seeAlso: ['std::vec::Vec'],
  },
  {
    name: 'std::env::args',
    lang: 'rust',
    kind: 'function',
    official: 'Returns the arguments that this program was started with (normally passed via the command line).',
    source: 'Rust standard library documentation',
    when: 'Your program reads the words typed after its name on the command line. The first item is the program name itself, so the first real argument is nth(1).',
    example: { command: 'let path = std::env::args().nth(1).unwrap_or("frames.txt".to_string());', says: 'Uses the first command-line argument as the file name, or frames.txt if there is none.' },
    seeAlso: ['std::fs::read_to_string'],
  },
  {
    name: 'std::fs::read_to_string',
    lang: 'rust',
    kind: 'function',
    official: 'Reads the entire contents of a file into a string.',
    source: 'Rust standard library documentation',
    when: 'You want a whole text file in one String. It returns a Result, because the file may be missing or not valid UTF-8 text, so pair it with ? or a match.',
    flags: [
      ['path', 'the file to read'],
    ],
    example: { command: 'let text = std::fs::read_to_string("frames.txt")?;', says: 'Reads frames.txt into text, or hands the error back to the caller.' },
    seeAlso: ['std::fs', 'std::env::args'],
  },
  {
    name: 'std::future::ready',
    aliases: ['core::future::ready'],
    lang: 'rust',
    kind: 'function',
    official: 'Creates a future that is immediately ready with a value.',
    source: 'Rust standard library documentation',
    when: 'You need a future that is finished straight away, for example to stand in for real async work in a small example or a test.',
    flags: [
      ['value', 'what the future gives when awaited'],
    ],
    example: { command: 'std::future::ready(()).await;', says: 'Completes at once; the task keeps going without waiting.' },
    seeAlso: ['std::future::Future'],
  },
  {
    name: 'std::hint::black_box',
    aliases: ['core::hint::black_box'],
    lang: 'rust',
    kind: 'function',
    official: 'An identity function that hints to the compiler to be maximally pessimistic about what black_box could do.',
    source: 'Rust standard library documentation',
    when: 'You are benchmarking and want the compiler to treat a value as unknown, so it cannot compute the answer ahead of time or delete work whose result is unused. It changes nothing about the value; it only blocks optimizations.',
    flags: [
      ['value', 'passed back unchanged'],
    ],
    example: { command: 'b.iter(|| mean_static(black_box(&mut gyro), 1000));', says: 'Benchmarks mean_static without letting the optimizer see through the gyro.' },
    seeAlso: ['criterion', 'std::time::Instant', 'std::hint'],
  },
  {
    name: 'std::hint::spin_loop',
    aliases: ['core::hint::spin_loop'],
    lang: 'rust',
    kind: 'function',
    official: 'Emits a machine instruction to signal the processor that it is running in a busy-wait spin-loop (“spin lock”).',
    source: 'Rust standard library documentation',
    when: 'You are busy-waiting in a loop for another thread or core, such as a producer waiting for room in a queue. It tells the processor to go easy while waiting. It does not sleep or give up the thread.',
    example: { command: 'while producer.enqueue(sample).is_err() { std::hint::spin_loop(); }', says: 'Keeps trying to add the sample, politely, until the queue has room.' },
    seeAlso: ['std::hint', 'std::thread'],
  },
  {
    name: 'std::mem::forget',
    aliases: ['core::mem::forget'],
    lang: 'rust',
    kind: 'function',
    official: 'Takes ownership and “forgets” about the value without running its destructor.',
    source: 'Rust standard library documentation',
    when: 'You give up a value without running its cleanup (its Drop code), for example when you hand its memory to C code. It is safe, because leaking memory is not undefined behavior, but whatever the value held is never freed.',
    flags: [
      ['value', 'what to forget; it is moved in and never dropped'],
    ],
    example: { command: 'std::mem::forget(buffer);', says: 'Leaves the buffer allocated forever, with no destructor run.' },
    seeAlso: ['std::mem::take', 'std::mem::replace'],
  },
  {
    name: 'std::mem::replace',
    aliases: ['core::mem::replace'],
    lang: 'rust',
    kind: 'function',
    official: 'Moves src into the referenced dest, returning the previous dest value.',
    source: 'Rust standard library documentation',
    when: 'You need to move a value out through a &mut reference, and you put a value of your choosing back in its place. Rust will not let you leave a hole in something you only borrowed.',
    flags: [
      ['dest', 'a &mut to the place to change'],
      ['src', 'the new value to put there'],
    ],
    example: { command: 'let old_mode = std::mem::replace(&mut self.mode, Mode::Safe);', says: 'Switches to Safe mode and hands back the mode that was there before.' },
    seeAlso: ['std::mem::take', 'std::mem::forget'],
  },
  {
    name: 'std::mem::take',
    aliases: ['core::mem::take'],
    lang: 'rust',
    kind: 'function',
    official: 'Replaces dest with the default value of T, returning the previous dest value.',
    source: 'Rust standard library documentation',
    when: 'You want to move a value out through a &mut reference and leave the type\'s default behind: an empty Vec or String, 0 for numbers. It is the usual fix for error E0507, "cannot move out of a mutable reference". The type must implement Default.',
    flags: [
      ['dest', 'a &mut to the place to empty'],
    ],
    example: { command: 'let payload = std::mem::take(&mut frame.payload);', says: 'Takes the payload out of the frame and leaves an empty Vec in its place.' },
    seeAlso: ['std::mem::replace', 'std::mem::forget'],
  },
  {
    name: 'std::mem::size_of',
    aliases: ['core::mem::size_of'],
    lang: 'rust',
    kind: 'function',
    official: 'Returns the size of a type in bytes.',
    source: 'Rust standard library documentation',
    when: 'You want to know how many bytes a type takes, for example to check a telemetry struct or to see what a String header costs. Put the type in the turbofish: size_of::<T>(). Padding counts, so the answer can be more than the sum of the fields.',
    flags: [
      ['::<T>', 'the type to measure'],
    ],
    example: { command: 'println!("{}", std::mem::size_of::<[f64; 3]>());', says: 'Prints 24: three 8-byte floats.' },
    seeAlso: ['std::vec::Vec', 'static_assertions'],
  },
  {
    name: 'core::ptr::read_volatile',
    aliases: ['std::ptr::read_volatile'],
    lang: 'rust',
    kind: 'function',
    official: 'Performs a volatile read of the value from src without moving it.',
    source: 'Rust standard library documentation',
    when: 'You read a hardware register through a raw pointer, and the compiler must do the read every single time instead of reusing an old value. It is unsafe: the pointer must be valid and properly aligned.',
    flags: [
      ['src', 'a raw pointer to the value to read'],
    ],
    example: { command: 'let status = unsafe { core::ptr::read_volatile(addr) };', says: 'Reads the register at addr fresh from the hardware.' },
    seeAlso: ['std::ptr::null_mut'],
  },
  {
    name: 'std::ptr::null_mut',
    aliases: ['core::ptr::null_mut'],
    lang: 'rust',
    kind: 'function',
    official: 'Creates a null mutable raw pointer.',
    source: 'Rust standard library documentation',
    when: 'You need a raw *mut T that points at nothing yet, such as a register address before it is mapped. Reading or writing through it is undefined behavior; check is_null() first.',
    flags: [
      ['::<T>', 'the pointed-to type, usually worked out by the compiler'],
    ],
    example: { command: 'let rb = RegisterBlock { base: std::ptr::null_mut() };', says: 'Makes a register block whose base pointer is not set yet.' },
    seeAlso: ['core::ptr::read_volatile'],
  },
  {
    name: 'core::slice::from_raw_parts',
    aliases: ['std::slice::from_raw_parts'],
    lang: 'rust',
    kind: 'function',
    official: 'Forms a slice from a pointer and a length.',
    source: 'Rust standard library documentation',
    when: 'C code hands you a pointer and a length, and you want an ordinary Rust slice to read. It is unsafe: you promise the pointer is valid for that many items and nothing changes them while the slice lives.',
    flags: [
      ['data', 'pointer to the first item'],
      ['len', 'how many items (not bytes)'],
    ],
    example: { command: 'let xs = unsafe { core::slice::from_raw_parts(samples, len) };', says: 'Views the C array of samples as a &[f64] of length len.' },
    seeAlso: ['std::slice::from_raw_parts_mut'],
  },
  {
    name: 'std::slice::from_raw_parts_mut',
    aliases: ['core::slice::from_raw_parts_mut'],
    lang: 'rust',
    kind: 'function',
    official: 'Performs the same functionality as from_raw_parts, except that a mutable slice is returned.',
    source: 'Rust standard library documentation',
    when: 'Like from_raw_parts, but you get a slice you can change. It is unsafe, and the two halves you make from one buffer must never overlap, or you break the one-writer rule.',
    flags: [
      ['data', 'pointer to the first item'],
      ['len', 'how many items (not bytes)'],
    ],
    example: { command: 'let left = unsafe { std::slice::from_raw_parts_mut(p, mid) };', says: 'Makes a changeable slice of the first mid items starting at p.' },
    seeAlso: ['core::slice::from_raw_parts'],
  },
  {
    name: 'std::panic::catch_unwind',
    lang: 'rust',
    kind: 'function',
    official: 'Invokes a closure, capturing the cause of an unwinding panic if one occurs.',
    source: 'Rust standard library documentation',
    when: 'You call Rust from C (or another boundary) and must not let a panic escape across it. It is not a way to handle ordinary errors, and it catches nothing when the profile sets panic = "abort".',
    flags: [
      ['f', 'the closure to run'],
    ],
    example: { command: 'let r = std::panic::catch_unwind(|| step_filter(&state));', says: 'Gives Ok(result) normally, or Err(...) if step_filter panicked.' },
    seeAlso: ['std::panic'],
  },
  {
    name: 'std::thread::scope',
    lang: 'rust',
    kind: 'function',
    official: 'Creates a scope for spawning scoped threads.',
    source: 'Rust standard library documentation',
    when: 'You want several threads to work on local data by borrowing it, without Arc. Every thread spawned inside the scope is joined before scope returns, so the borrows are safe.',
    flags: [
      ['|s| ...', 'the closure that receives the scope'],
      ['s.spawn(...)', 'start a thread inside the scope'],
    ],
    example: { command: 'std::thread::scope(|s| {\n    s.spawn(|| sum(&left));\n    s.spawn(|| sum(&right));\n});', says: 'Adds up both halves on two threads, then waits for both before going on.' },
    seeAlso: ['std::thread::spawn', 'std::thread'],
  },
  {
    name: 'std::thread::spawn',
    lang: 'rust',
    kind: 'function',
    official: 'Spawns a new thread, returning a JoinHandle for it.',
    source: 'Rust standard library documentation',
    when: 'You want to run a closure on a new thread. The thread may outlive the function that started it, so the closure must own what it uses (write move) and it must be Send. Call join() on the handle to wait for it and get its result.',
    flags: [
      ['move || ...', 'the work to run; move hands it ownership of what it captures'],
      ['join()', 'wait for the thread and get its result'],
    ],
    example: { command: 'let h = std::thread::spawn(move || integrate(orbit));\nlet state = h.join().unwrap();', says: 'Integrates the orbit on another thread, then waits for the answer.' },
    seeAlso: ['std::thread::scope', 'std::sync::Arc', 'std::thread'],
  },
  {
    name: 'std::f64::consts::FRAC_PI_2',
    aliases: ['core::f64::consts::FRAC_PI_2', 'FRAC_PI_2', 'consts::FRAC_PI_2'],
    lang: 'rust',
    kind: 'constant',
    official: 'π/2',
    source: 'Rust standard library documentation',
    when: 'You need a quarter turn, 90 degrees, in radians. Using the constant is more exact than typing 1.5708 yourself, and small errors like that add up in a navigation filter.',
    example: { command: 'let q = UnitQuaternion::from_axis_angle(&Vector3::z_axis(), FRAC_PI_2);', says: 'Builds a rotation of 90 degrees about the z axis.' },
    seeAlso: ['std::f64::consts::PI', 'nalgebra'],
  },
  {
    name: 'std::f64::consts::PI',
    aliases: ['core::f64::consts::PI', 'PI', 'consts::PI'],
    lang: 'rust',
    kind: 'constant',
    official: 'Archimedes’ constant (π)',
    source: 'Rust standard library documentation',
    when: 'You need pi, for example to turn degrees into radians. It is an f64; for f32 math use std::f32::consts::PI.',
    example: { command: 'let rad = deg * std::f64::consts::PI / 180.0;', says: 'Converts an angle from degrees to radians.' },
    seeAlso: ['std::f64::consts::FRAC_PI_2'],
  },
  {
    name: 'nalgebra',
    lang: 'rust',
    kind: 'module',
    official: 'nalgebra is meant to be a general-purpose, low-dimensional, linear algebra library, with an optimized set of tools for computer graphics and physics.',
    source: 'nalgebra crate documentation',
    when: 'You need vectors, matrices, quaternions and rotations for guidance, navigation and attitude math. Sizes known at compile time (Matrix3, Vector3) live on the stack and work in no_std; DMatrix sizes are chosen at run time and use the heap.',
    flags: [
      ['Vector3, Matrix3, SMatrix', 'fixed sizes, checked at compile time'],
      ['DMatrix, DVector', 'sizes chosen while running, on the heap'],
      ['UnitQuaternion, Rotation3', 'rotations that are always valid'],
      ['Isometry3', 'a rotation plus a translation'],
    ],
    example: { command: 'use nalgebra::{Matrix3, Vector3};', says: 'Brings a 3x3 matrix and a 3-vector type into scope.' },
    seeAlso: ['std::f64::consts::FRAC_PI_2', 'micromath'],
  },
  {
    name: 'cortex_m_rt',
    lang: 'rust',
    kind: 'module',
    official: 'Startup code and minimal runtime for Cortex-M microcontrollers',
    source: 'cortex-m-rt crate documentation',
    when: 'You write a bare-metal program for an ARM Cortex-M chip. It sets up memory and the vector table before your code runs, and #[entry] marks your main function, which must never return (-> !).',
    flags: [
      ['#[entry]', 'marks the function the chip runs after reset'],
    ],
    example: { command: 'use cortex_m_rt::entry;\n\n#[entry]\nfn main() -> ! { loop {} }', says: 'Declares the program\'s starting point on the microcontroller.' },
    seeAlso: ['core::panic::PanicInfo', 'stm32f4'],
  },
  {
    name: 'heapless',
    lang: 'rust',
    kind: 'module',
    official: 'static friendly data structures that don\'t require dynamic memory allocation',
    source: 'heapless crate documentation',
    when: 'You want a Vec, String or queue on a microcontroller with no heap. The capacity is part of the type, like Vec<f32, 4>, and when it is full push hands the item back in an Err instead of growing.',
    flags: [
      ['Vec<T, N>', 'a list of at most N items'],
      ['String<N>', 'text of at most N bytes'],
      ['spsc::Queue<T, N>', 'a first-in, first-out queue for one producer and one consumer'],
    ],
    example: { command: 'let mut temps: heapless::Vec<f32, 4> = heapless::Vec::new();', says: 'Makes a list that can hold at most four temperatures, with no heap.' },
    seeAlso: ['std::vec::Vec', 'core::fmt::Write'],
  },
  {
    name: 'embedded_hal',
    lang: 'rust',
    kind: 'module',
    official: 'A Hardware Abstraction Layer (HAL) for embedded systems',
    source: 'embedded-hal crate documentation',
    when: 'You write a driver (for an IMU or a pressure sensor, say) that should work on any chip. Write it against these traits, such as I2c or OutputPin, and every chip\'s HAL that implements them can run it.',
    flags: [
      ['digital::OutputPin', 'a pin you can set high or low'],
      ['delay::DelayNs', 'wait a number of nanoseconds, microseconds or milliseconds'],
      ['i2c::I2c', 'talk to devices on an I2C bus'],
      ['i2c::ErrorType', 'names the bus\'s error type'],
    ],
    example: { command: 'pub struct Mpu6050<I: embedded_hal::i2c::I2c> { i2c: I }', says: 'Makes a driver that works with any I2C bus that implements the trait.' },
    seeAlso: ['stm32f4xx_hal', 'core::convert::Infallible'],
  },
  {
    name: 'stm32f4xx_hal',
    lang: 'rust',
    kind: 'module',
    official: 'Multi device hardware abstraction on top of the peripheral access API for the STMicro STM32F4 series microcontrollers.',
    source: 'stm32f4xx-hal crate documentation',
    when: 'You program an STM32F4 chip and want friendly types (pins, timers, I2C) instead of raw registers. It implements the embedded_hal traits, so generic drivers work on it.',
    flags: [
      ['pac', 'the raw register access underneath (the stm32f4 crate)'],
      ['prelude::*', 'the extension traits that add methods such as split()'],
    ],
    example: { command: 'use stm32f4xx_hal::{pac, prelude::*};', says: 'Brings in the chip\'s registers and the HAL\'s helper traits.' },
    seeAlso: ['embedded_hal', 'stm32f4'],
  },
  {
    name: 'thiserror',
    lang: 'rust',
    kind: 'module',
    official: 'This library provides a convenient derive macro for the standard library\'s std::error::Error trait.',
    source: 'thiserror crate documentation',
    when: 'You write a library and want a typed error enum without writing Display and Error impls by hand. It generates plain standard code, so it does not appear in your public interface.',
    flags: [
      ['#[derive(Error)]', 'writes impl std::error::Error for you'],
      ['#[error("...")]', 'the Display message for a variant; {field} or {0} fills in data'],
      ['#[from]', 'lets ? convert that error into this variant, and keeps it as the source'],
    ],
    example: { command: '#[derive(Debug, Error)]\nenum FrameError { #[error("unknown APID {0}")] UnknownApid(u16) }', says: 'Prints unknown APID 42 for FrameError::UnknownApid(42).' },
    seeAlso: ['anyhow', 'std::error::Error'],
  },
  {
    name: 'anyhow',
    lang: 'rust',
    kind: 'module',
    official: 'This library provides anyhow::Error, a trait object based error type for easy idiomatic error handling in Rust applications.',
    source: 'anyhow crate documentation',
    when: 'You write an application (not a library) and just want to report what failed and why. Any standard error converts into anyhow::Error with ?, and context adds a line explaining what you were doing. Callers cannot match on the cases, so libraries use thiserror instead.',
    flags: [
      ['Result<T>', 'short for Result<T, anyhow::Error>'],
      ['.context(...) / .with_context(|| ...)', 'wrap an error with an explanation'],
      ['bail!(...)', 'return an error right away'],
    ],
    example: { command: 'let text = std::fs::read_to_string(path).with_context(|| format!("could not read frame log {path}"))?;', says: 'Reads the file, or fails with a message that names the file.' },
    seeAlso: ['thiserror', 'std::error::Error', 'bail!'],
  },
  {
    name: 'criterion',
    lang: 'rust',
    kind: 'module',
    official: 'A statistics-driven micro-benchmarking library written in Rust.',
    source: 'criterion crate documentation',
    when: 'You want to measure how fast a function is, and whether a change really made it faster. It runs the code many times and does the statistics. Put it under [dev-dependencies] with harness = false for the bench, and wrap inputs in black_box.',
    flags: [
      ['Criterion', 'the object that runs benchmarks'],
      ['bench_function(name, |b| ...)', 'one named benchmark'],
      ['b.iter(|| ...)', 'the code to time'],
      ['criterion_group! / criterion_main!', 'collect benchmarks and make main'],
    ],
    example: { command: 'c.bench_function("gyro static", |b| b.iter(|| mean_static(black_box(&mut gyro), 1000)));', says: 'Times mean_static and reports its average time per call.' },
    seeAlso: ['std::hint::black_box', 'criterion_group!', 'criterion_main!'],
  },
  {
    name: 'proptest',
    lang: 'rust',
    kind: 'module',
    official: 'Proptest is a property testing framework (i.e., the QuickCheck family) inspired by the Hypothesis framework for Python.',
    source: 'proptest crate documentation (README)',
    when: 'You want to test that a rule holds for many random inputs, not just the few you thought of. When it finds a failure, it shrinks the input to the simplest one that still fails.',
    flags: [
      ['prelude::*', 'everything a test file needs'],
      ['proptest! { ... }', 'wraps tests whose arguments are generated'],
      ['a in -1.0e6f64..1.0e6', 'where an input comes from'],
      ['prop_assert!', 'a check that works with shrinking'],
    ],
    example: { command: 'proptest! {\n    #[test]\n    fn tick_in_range(a in -1.0e6f64..1.0e6) { prop_assert!(a.is_finite()); }\n}', says: 'Runs the check on many random values between minus and plus one million.' },
    seeAlso: ['proptest!', 'prop_assert!'],
  },
  {
    name: 'libfuzzer_sys',
    lang: 'rust',
    kind: 'module',
    official: 'Bindings to libFuzzer: a runtime for coverage-guided fuzzing.',
    source: 'libfuzzer-sys crate documentation',
    when: 'You want to throw huge numbers of random byte strings at a parser to find crashes. cargo fuzz uses this crate, and fuzz_target! marks the function to feed. It needs nightly Rust.',
    flags: [
      ['fuzz_target!(|data: &[u8]| ...)', 'the code the fuzzer calls with each input'],
    ],
    example: { command: 'fuzz_target!(|data: &[u8]| { let _ = frame2::parse_frame_v2(data); });', says: 'Feeds random bytes to the frame parser to look for panics.' },
    seeAlso: ['fuzz_target!', 'proptest'],
  },
  {
    name: 'hifitime',
    lang: 'rust',
    kind: 'module',
    official: 'Hifitime is a powerful Rust and Python library designed for time management.',
    source: 'hifitime crate documentation',
    when: 'You need precise spacecraft time: epochs in time scales such as UTC, TAI, TT or GPS, with leap seconds handled for you. Plain std::time cannot do that.',
    flags: [
      ['Epoch', 'one moment in time'],
      ['TimeScale', 'which clock: UTC, TAI, TT, GPST, ...'],
    ],
    example: { command: 'let e = Epoch::from_gregorian_utc_at_midnight(2026, 1, 1);', says: 'Makes the moment 2026-01-01 00:00 UTC, ready to show in other time scales.' },
    seeAlso: ['std::time::Instant'],
  },
  {
    name: 'micromath',
    lang: 'rust',
    kind: 'module',
    official: 'Embedded-friendly (i.e. #![no_std]) math library featuring fast, safe floating point approximations for common arithmetic operations, as well as 2D and 3D vector types, statistical analysis functions, and quaternions.',
    source: 'micromath crate documentation',
    when: 'You need sin, cos or sqrt on f32 in no_std code, where core has none, and speed matters more than the last digits. The answers are approximations; use libm when you need them accurate.',
    flags: [
      ['F32Ext', 'the trait that adds sin, cos, sqrt and more to f32'],
    ],
    example: { command: 'use micromath::F32Ext;\nlet s = F32Ext::sin(0.5f32);', says: 'Gives a value within about 0.0001 of the true sin(0.5), which is 0.479426.' },
    seeAlso: ['nalgebra'],
  },
  {
    name: 'rtt_target',
    lang: 'rust',
    kind: 'module',
    official: 'Target side implementation of the RTT (Real-Time Transfer) I/O protocol',
    source: 'rtt-target crate documentation',
    when: 'You want println!-style messages from a microcontroller to your laptop through the debug probe, fast enough not to upset real-time code.',
    flags: [
      ['rtt_init_print!()', 'set up the channel, once, at the start'],
      ['rprintln!(...)', 'print a line over it'],
    ],
    example: { command: 'rtt_init_print!();\nrprintln!("tick {}", tick);', says: 'Shows tick 1, tick 2, ... in the probe\'s terminal on your laptop.' },
    seeAlso: ['rtt_init_print!', 'rprintln!', 'cortex_m_rt'],
  },
  {
    name: 'critical_section',
    lang: 'rust',
    kind: 'module',
    official: 'A critical section that works everywhere!',
    source: 'critical-section crate documentation',
    when: 'You share data between the main loop and an interrupt handler. critical_section::with runs a short closure while nothing else can interrupt, and its Mutex only opens with the token that closure gets. Keep the work inside short, because interrupts wait.',
    flags: [
      ['with(|cs| ...)', 'run a closure inside a critical section'],
      ['Mutex<T>', 'data that can only be reached with the cs token'],
    ],
    example: { command: 'critical_section::with(|cs| LATEST.borrow(cs).replace(Some(frame)));', says: 'Stores the newest frame with interrupts held off for a moment.' },
    seeAlso: ['std::cell::RefCell', 'std::sync::atomic'],
  },
  {
    name: 'static_assertions',
    lang: 'rust',
    kind: 'module',
    official: 'Assertions to ensure correct assumptions about constants, types, and more.',
    source: 'static_assertions crate documentation',
    when: 'You want the build to fail if a fact about your types changes, such as a radio frame no longer being exactly 16 bytes. The checks run while compiling and produce no code.',
    flags: [
      ['assert_eq_size!(A, B)', 'fail the build unless A and B are the same size'],
      ['const_assert!(expr)', 'fail the build unless a compile-time condition is true'],
    ],
    example: { command: 'assert_eq_size!(Frame, [u8; 16]);', says: 'Stops the build if Frame is not exactly 16 bytes.' },
    seeAlso: ['assert_eq_size!', 'const_assert!', 'std::mem::size_of'],
  },
  {
    name: 'stm32f4',
    lang: 'rust',
    kind: 'module',
    official: 'Peripheral access API for STM32F4 microcontrollers',
    source: 'stm32f4 crate documentation',
    when: 'You want to reach an STM32F4 chip\'s registers directly, with names for every register and bit field. It is generated from the chip\'s description file; HAL crates build on it.',
    flags: [
      ['stm32f411', 'the module for one particular chip'],
      ['Peripherals::take()', 'get the chip\'s registers, only once'],
    ],
    example: { command: 'let dp = stm32f411::Peripherals::take().unwrap();', says: 'Takes ownership of all the chip\'s peripheral registers.' },
    seeAlso: ['stm32f4xx_hal', 'cortex_m_rt'],
  },
  {
    name: 'embassy_executor',
    lang: 'rust',
    kind: 'module',
    official: 'An async/await executor designed for embedded usage.',
    source: 'embassy-executor crate documentation',
    when: 'You write a microcontroller program as several async tasks that take turns, with no heap and no operating system. When every task is waiting, the chip sleeps until an interrupt wakes it.',
    flags: [
      ['#[embassy_executor::main]', 'sets up the executor and runs main as the first task'],
      ['#[embassy_executor::task]', 'turns an async fn into a task'],
      ['Spawner', 'starts more tasks'],
    ],
    example: { command: 'spawner.spawn(heartbeat(led).unwrap());', says: 'Starts the heartbeat task running alongside main.' },
    seeAlso: ['embassy_time', 'embassy_stm32'],
  },
  {
    name: 'embassy_stm32',
    lang: 'rust',
    kind: 'module',
    official: 'The embassy-stm32 HAL aims to provide a safe, idiomatic hardware abstraction layer for all STM32 families.',
    source: 'embassy-stm32 crate documentation',
    when: 'You use Embassy on an STM32 chip. init sets up the clocks and hands back the peripherals, and the drivers work with async/await.',
    flags: [
      ['init(config)', 'set up the chip and get its peripherals'],
      ['gpio::{Level, Output, Speed}', 'drive a pin high or low'],
    ],
    example: { command: 'let p = embassy_stm32::init(Default::default());', says: 'Starts the chip with default clock settings and returns its peripherals.' },
    seeAlso: ['embassy_executor', 'embassy_time'],
  },
  {
    name: 'embassy_time',
    lang: 'rust',
    kind: 'module',
    official: 'Timekeeping, delays and timeouts.',
    source: 'embassy-time crate documentation',
    when: 'An Embassy task needs to wait or repeat on a schedule. Awaiting a Timer lets other tasks run meanwhile instead of wasting the processor in a busy loop.',
    flags: [
      ['Timer::after_millis(n)', 'wait n milliseconds'],
      ['Ticker::every(d)', 'fire at a steady rate'],
      ['Duration::from_hz(n)', 'the gap between ticks at n per second'],
    ],
    example: { command: 'Timer::after_millis(500).await;', says: 'Pauses this task for half a second while other tasks run.' },
    seeAlso: ['embassy_executor'],
  },
]
