import type { CommandRef } from './types'

export const COMMANDS: CommandRef[] = [
  {
    name: 'slice::len',
    aliases: ['len'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns the number of elements in the slice.',
    source: 'Rust standard library documentation',
    when: 'You need to know how many items are in an array, a slice or a Vec, for example to divide a sum by the count. It counts items, but on a String or &str the len method counts bytes, so "°C".len() is 3, not 2.',
    example: { command: 'let mean = samples.iter().sum::<f64>() / samples.len() as f64;', says: 'Divides the total by the number of samples; as f64 turns the count (a usize) into a decimal number first.' },
    seeAlso: ['slice::is_empty', 'Iterator::count'],
  },
  {
    name: 'slice::iter',
    aliases: ['iter'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns an iterator over the slice.',
    source: 'Rust standard library documentation',
    when: 'You want to walk through a Vec, an array or a slice without giving it away: each item comes out as a shared reference (&T), so the collection is still yours afterwards. Chain steps such as map, filter and sum onto it. To change the items, use iter_mut instead.',
    example: { command: 'for b in burns.iter() { println!("{b}"); }', says: 'Prints each burn in order; burns can still be used after the loop.' },
    seeAlso: ['slice::iter_mut', 'Iterator::map', 'Iterator::enumerate'],
  },
  {
    name: 'Result::unwrap',
    aliases: ['unwrap'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns the contained Ok value, consuming the self value.',
    source: 'Rust standard library documentation',
    when: 'You have a Result and are sure it is Ok, as in quick examples and tests: "12.5".parse::<f64>().unwrap(). If it is an Err, the program panics (stops with an error message), so in real flight code use ? or match instead. Option has an unwrap too, which panics on None.',
    example: { command: 'let altitude: f64 = "10500".parse().unwrap();', says: 'Turns the text into the number 10500.0; with text like "ten" the program would panic.' },
    seeAlso: ['Option::expect', 'Option::unwrap_or', 'str::parse'],
  },
  {
    name: 'Vec::push',
    aliases: ['push'],
    lang: 'rust',
    kind: 'method',
    official: 'Appends an element to the back of a collection.',
    source: 'Rust standard library documentation',
    when: 'You want to add one item to the end of a Vec, such as a new reading. The vector must be declared with let mut. You cannot push while a reference into the same vector is still in use (for example inside a for loop over it): the borrow checker stops you, because the vector might move to a bigger buffer. String has its own push for one char.',
    flags: [['value', 'the item to add at the end']],
    example: { command: 'samples.push(0.40);', says: 'Adds 0.40 as the last item of samples.' },
    seeAlso: ['Vec::pop', 'Extend::extend', 'String::push_str'],
  },
  {
    name: 'Iterator::map',
    aliases: ['map'],
    lang: 'rust',
    kind: 'method',
    official: 'Takes a closure and creates an iterator which calls that closure on each element.',
    source: 'Rust standard library documentation',
    when: 'You want to turn each item into something else, like bytes into u32 values or text into numbers. It is lazy: nothing happens until something uses up the iterator, such as collect, sum or a for loop. Option and Result have their own map, which changes only the value inside Some or Ok.',
    flags: [['|x| ...', 'a closure (a small unnamed function) that gets one item and returns the new one']],
    example: { command: 'let sum: u32 = packet.iter().map(|&b| b as u32).sum();', says: 'Widens each byte to a u32 and adds them all up, so the total cannot overflow a u8.' },
    seeAlso: ['Iterator::filter', 'Iterator::collect', 'Iterator::fold'],
  },
  {
    name: 'RwLock::read',
    aliases: ['read'],
    lang: 'rust',
    kind: 'method',
    official: 'Locks this RwLock with shared read access, blocking the current thread until it can be acquired.',
    source: 'Rust standard library documentation',
    when: 'Many threads need to read shared data, like a target attitude, and only now and then does one write it. Many readers can hold the lock at once, but a writer waits until they are all gone. It returns a Result (an Err only if a thread panicked while holding the lock), so lessons add .unwrap(); the lock opens again when the guard goes out of scope.',
    example: { command: 'let t = target.read().unwrap();', says: 'Waits for shared read access and gives a guard t; t[2] then reads the yaw target.' },
    seeAlso: ['RwLock::write', 'Mutex::lock'],
  },
  {
    name: 'str::parse',
    aliases: ['parse'],
    lang: 'rust',
    kind: 'method',
    official: 'Parses this string slice into another type.',
    source: 'Rust standard library documentation',
    when: 'You want to turn text into a number, such as a value typed by an operator or read from a log line. Rust must know the target type: write it on the variable (let x: f64 = s.parse()?) or with the turbofish, parse::<f64>(). It returns a Result, and "12,5" with a comma is an Err, not 12.5.',
    flags: [['::<T>', 'the type to parse into, such as f64 or i32, when the variable does not already say it']],
    example: { command: 'let bad: Result<f64, std::num::ParseFloatError> = "12,5".parse();', says: 'Gives an Err, because a comma is not a decimal point in Rust.' },
    seeAlso: ['Result::unwrap', 'Result::map_err', 'str::trim'],
  },
  {
    name: 'Iterator::next',
    aliases: ['next'],
    lang: 'rust',
    kind: 'method',
    official: 'Advances the iterator and returns the next value.',
    source: 'Rust standard library documentation',
    when: 'You want to take items out of an iterator one at a time, such as the first and second word of a command. It gives Some(item) until the iterator is used up, then None. The iterator variable must be let mut, because each call moves it forward. A for loop calls next for you.',
    example: { command: 'let mut words = "set 42.5".split_whitespace();\nlet cmd = words.next();', says: 'cmd is Some("set"); the next call gives Some("42.5"), and the one after that None.' },
    seeAlso: ['Iterator::nth', 'str::split_whitespace'],
  },
  {
    name: 'Iterator::collect',
    aliases: ['collect'],
    lang: 'rust',
    kind: 'method',
    official: 'Transforms an iterator into a collection.',
    source: 'Rust standard library documentation',
    when: 'You want to gather the items of an iterator into a collection, most often a Vec. Rust must know which collection, so write the type on the variable (let v: Vec<f64> = ...). Collecting into Result<Vec<f64>, _> gives Ok with all the values, or the first Err.',
    example: { command: 'let rates: Vec<f64> = clean.windows(2).map(|w| w[0] - w[1]).collect();', says: 'Builds a new Vec holding the difference between each pair of neighboring altitudes.' },
    seeAlso: ['Iterator::map', 'Iterator::filter'],
  },
  {
    name: 'Iterator::sum',
    aliases: ['sum'],
    lang: 'rust',
    kind: 'method',
    official: 'Sums the elements of an iterator.',
    source: 'Rust standard library documentation',
    when: 'You want to add up all the items, such as samples before dividing by the count. Rust must know the type of the total, so write let s: f64 = ... or sum::<f64>(). Integer totals can overflow (a panic in a debug build), so widen small types first, for example map(|&b| b as u32).',
    flags: [['::<T>', 'the type of the total, such as f64 or u32']],
    example: { command: 'let mean = rates.iter().sum::<f64>() / rates.len() as f64;', says: 'Adds all the rates and divides by how many there are.' },
    seeAlso: ['Iterator::fold', 'Iterator::count', 'slice::len'],
  },
  {
    name: 'RefCell::borrow',
    aliases: ['borrow'],
    lang: 'rust',
    kind: 'method',
    official: 'Immutably borrows the wrapped value.',
    source: 'Rust standard library documentation',
    when: 'You want to read the value inside a RefCell, which lets you change data through a shared reference and checks the borrow rules while the program runs. It gives a guard that acts like &T. If a borrow_mut is alive at the same moment, the program panics, so keep the guard short-lived.',
    example: { command: 'println!("{} events", events.borrow().len());', says: 'Borrows the Vec inside the RefCell just long enough to count it.' },
    seeAlso: ['RefCell::borrow_mut', 'RefCell::try_borrow_mut'],
  },
  {
    name: 'Scope::spawn',
    aliases: ['spawn'],
    lang: 'rust',
    kind: 'method',
    official: 'Spawns a new thread within a scope, returning a ScopedJoinHandle for it.',
    source: 'Rust standard library documentation',
    when: 'You want to start a thread inside thread::scope(|s| { ... }) that can borrow local variables: the scope waits for every thread it started before it ends. Plain thread::spawn cannot borrow, because its thread might outlive the data; it needs move and values the thread owns.',
    flags: [['|| { ... }', 'the closure the new thread runs; it may borrow variables from outside the scope']],
    example: { command: 'thread::scope(|s| {\n    s.spawn(|| left[0] += 1);\n    s.spawn(|| right[0] += 1);\n});', says: 'Runs two threads, each changing its own half of the counts, and waits for both before going on.' },
    seeAlso: ['JoinHandle::join', 'slice::split_at_mut'],
  },
  {
    name: 'ToString::to_string',
    aliases: ['to_string'],
    lang: 'rust',
    kind: 'method',
    official: 'Converts the given value to a String.',
    source: 'Rust standard library documentation',
    when: 'You want an owned String made from a &str, or from any value that prints with {}, such as a number. Lessons use it to store a name in a struct or an error: name: name.to_string(). It copies the text into new memory every time.',
    example: { command: 'Err(PressureError::UnknownUnit("atm".to_string()))', says: 'Puts an owned copy of the text "atm" inside the error.' },
    seeAlso: ['String::push_str'],
  },
  {
    name: 'Cell::get',
    aliases: ['get'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns a copy of the contained value.',
    source: 'Rust standard library documentation',
    when: 'You want to read the value in a Cell, a box that lets you change a Copy value (like a counter) through a shared reference. You get a copy, never a reference. A Cell cannot be shared between threads, so the compiler refuses to let two threads use one.',
    example: { command: 'self.reads.set(self.reads.get() + 1);', says: 'Reads the counter, adds one and stores it back, even though the method only has &self.' },
    seeAlso: ['Cell::set', 'RefCell::borrow'],
  },
  {
    name: 'slice::iter_mut',
    aliases: ['iter_mut'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns an iterator that allows modifying each value.',
    source: 'Rust standard library documentation',
    when: 'You want to change every item of a Vec or an array in place, such as converting all temperatures. Each item comes out as &mut T, so write *t to change it. While the loop runs, nothing else may use the collection.',
    example: { command: 'for t in temps_c.iter_mut() { *t += 273.15; }', says: 'Adds 273.15 to every temperature, turning Celsius into kelvin in place.' },
    seeAlso: ['slice::iter'],
  },
  {
    name: 'u8::wrapping_add',
    aliases: ['wrapping_add'],
    lang: 'rust',
    kind: 'method',
    official: 'Wrapping (modular) addition.',
    source: 'Rust standard library documentation',
    when: 'You want an addition that wraps around past the top of the type on purpose, like a packet sequence counter or an 8-bit checksum: 250_u8.wrapping_add(10) is 4. Every integer type has it (u16, u32, i8 and so on). Plain + would panic on overflow in a debug build.',
    flags: [['rhs', 'the number to add']],
    example: { command: 'seq = seq.wrapping_add(1);', says: 'Counts the sequence number up by one; for a u16 it goes from 65535 back to 0.' },
    seeAlso: ['u8::checked_add', 'u8::saturating_add', 'u8::overflowing_add', 'u32::wrapping_sub'],
  },
  {
    name: 'JoinHandle::join',
    aliases: ['join'],
    lang: 'rust',
    kind: 'method',
    official: 'Waits for the associated thread to finish.',
    source: 'Rust standard library documentation',
    when: 'You want to wait for a thread started with thread::spawn to finish and get back what it returned. It returns a Result that is an Err if the thread panicked, so lessons write handle.join().unwrap(). Without a join, main can end and stop the whole program before the thread is done.',
    example: { command: 'let lines = handle.join().unwrap();', says: 'Waits for the worker thread and gets its return value, here the log lines.' },
    seeAlso: ['Scope::spawn'],
  },
  {
    name: 'RefCell::borrow_mut',
    aliases: ['borrow_mut'],
    lang: 'rust',
    kind: 'method',
    official: 'Mutably borrows the wrapped value.',
    source: 'Rust standard library documentation',
    when: 'You want to change the value inside a RefCell through a shared reference, such as adding to a log that several subsystems share through Rc. It gives a guard that acts like &mut T. If any other borrow is still alive, the program panics with "already borrowed", so do not keep the guard longer than you need it.',
    example: { command: 'events.borrow_mut().push(String::from("armed-ack"));', says: 'Borrows the Vec mutably for this one line and adds an entry.' },
    seeAlso: ['RefCell::borrow', 'RefCell::try_borrow_mut', 'RefCell::replace'],
  },
  {
    name: 'Option::unwrap_or',
    aliases: ['unwrap_or'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns the contained Some value or a provided default.',
    source: 'Rust standard library documentation',
    when: 'You want the value from an Option, or a fallback when it is None, such as a default limit. The fallback is worked out even when it is not needed, so for an expensive one use unwrap_or_else.',
    flags: [['default', 'the value to use when it is None']],
    example: { command: 'let limit = operator_limit.unwrap_or(100.0);', says: 'Uses the operator limit if one was given, otherwise 100.0.' },
    seeAlso: ['Option::unwrap_or_default', 'Option::expect', 'Option::ok_or'],
  },
  {
    name: 'Iterator::fold',
    aliases: ['fold'],
    lang: 'rust',
    kind: 'method',
    official: 'Folds every element into an accumulator by applying an operation, returning the final result.',
    source: 'Rust standard library documentation',
    when: 'You want to combine all the items into one value with your own rule, such as a wrapping checksum or the highest point of a flight. You give a starting value and a closure that gets the running result and the next item. For a plain total, sum is shorter.',
    flags: [['init', 'the starting value'], ['|acc, x| ...', 'gives the new running result from the old one and the next item']],
    example: { command: 'let expected = body.iter().fold(0u8, |acc, &b| acc.wrapping_add(b));', says: 'Adds up all the bytes, wrapping at 256, to get the frame checksum.' },
    seeAlso: ['Iterator::sum', 'u8::wrapping_add'],
  },
  {
    name: 'Iterator::enumerate',
    aliases: ['enumerate'],
    lang: 'rust',
    kind: 'method',
    official: 'Creates an iterator which gives the current iteration count as well as the next value.',
    source: 'Rust standard library documentation',
    when: 'You need each item and its position, such as the sample number and the value. It gives pairs (index, item), with the index starting at 0 as a usize.',
    example: { command: 'for (i, temp) in temps_c.iter().enumerate() { println!("{i}: {temp}"); }', says: 'Prints each temperature with its index: 0, 1, 2 and so on.' },
    seeAlso: ['slice::iter'],
  },
  {
    name: 'Option::expect',
    aliases: ['expect'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns the contained Some value, consuming the self value.',
    source: 'Rust standard library documentation',
    when: 'Like unwrap, but you write the panic message yourself, saying why it should never be None. Result has an expect too, used the same way in tests: parse_frame(&bytes).expect("valid frame"). It still crashes if you are wrong, so keep it for things that really cannot fail.',
    flags: [['msg', 'the text printed if it panics']],
    example: { command: 'let pkt = PacketView::new(&buffer).expect("short packet");', says: 'Gives the packet view, or stops the program with "short packet" if the buffer was too short.' },
    seeAlso: ['Result::unwrap', 'Option::unwrap_or'],
  },
  {
    name: 'f64::min',
    aliases: ['min'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns the minimum of the two numbers, ignoring NaN.',
    source: 'Rust standard library documentation',
    when: 'You want to keep a number from going above a cap: x.min(limit) gives the smaller of the two. If one of them is NaN (not a number), you get the other one. On an iterator, min() finds the smallest item and gives an Option.',
    flags: [['other', 'the number to compare with']],
    example: { command: 'self.level_kg = (self.level_kg + kg).min(self.capacity_kg);', says: 'Adds the propellant but never lets the level go above the tank capacity.' },
    seeAlso: ['f64::max', 'f64::clamp'],
  },
  {
    name: 'f64::clamp',
    aliases: ['clamp'],
    lang: 'rust',
    kind: 'method',
    official: 'Restrict a value to a certain interval unless it is NaN.',
    source: 'Rust standard library documentation',
    when: 'You want to keep a value inside a range, like a rate command limited to plus or minus a maximum step. It panics if min is bigger than max, or if either one is NaN.',
    flags: [['min', 'the lowest value allowed'], ['max', 'the highest value allowed']],
    example: { command: 'let delta = (command - self.out).clamp(-self.max_step, self.max_step);', says: 'Limits the change to at most max_step in either direction.' },
    seeAlso: ['f64::min', 'f64::max'],
  },
  {
    name: 'str::split',
    aliases: ['split'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns an iterator over substrings of this string slice, separated by characters matched by a pattern.',
    source: 'Rust standard library documentation',
    when: 'You want to cut text at a separator, such as the fields of a comma-separated record. It gives an iterator of &str pieces that borrow from the original text. Two separators in a row give an empty piece between them.',
    flags: [['pat', 'the separator, such as the char \',\' or a string']],
    example: { command: 'for field in "id=7,alt=412".split(\',\') { println!("{field}"); }', says: 'Prints id=7 and then alt=412.' },
    seeAlso: ['str::split_once', 'str::split_whitespace', 'str::lines'],
  },
  {
    name: 'f64::to_degrees',
    aliases: ['to_degrees'],
    lang: 'rust',
    kind: 'method',
    official: 'Converts radians to degrees.',
    source: 'Rust standard library documentation',
    when: 'You want to show an angle to people. Rust\'s sin, cos and rotations work in radians, and to_degrees converts a result for printing.',
    example: { command: 'let deg = std::f64::consts::FRAC_PI_2.to_degrees();', says: 'Turns pi/2 radians into 90 degrees.' },
    seeAlso: ['f64::to_radians', 'f64::sin'],
  },
  {
    name: 'Iterator::filter',
    aliases: ['filter'],
    lang: 'rust',
    kind: 'method',
    official: 'Creates an iterator which uses a closure to determine if an element should be yielded.',
    source: 'Rust standard library documentation',
    when: 'You want to keep only the items that pass a test. The closure gets a reference to each item, which is why patterns like |&h| show up. Like map, it is lazy: you still need collect, sum or a loop.',
    flags: [['|x| ...', 'gives true for the items to keep']],
    example: { command: 'let clean: Vec<f64> = alt_m.iter().copied().filter(|&h| h <= alt_m[0]).collect();', says: 'Keeps only the altitudes no higher than the first one.' },
    seeAlso: ['Iterator::map', 'Iterator::any'],
  },
  {
    name: 'Mutex::lock',
    aliases: ['lock'],
    lang: 'rust',
    kind: 'method',
    official: 'Acquires a mutex, blocking the current thread until it is able to do so.',
    source: 'Rust standard library documentation',
    when: 'You want to change data shared between threads, usually a Mutex inside an Arc. Only one thread holds the lock at a time; the others wait. It returns a Result (an Err if a thread panicked while holding it), so lessons write lock().unwrap(). The lock opens again when the guard goes out of scope, so a guard kept too long blocks everyone else.',
    example: { command: 'let mut n = counter.lock().unwrap();\n*n += 1;', says: 'Waits for the lock, then adds one to the shared packet count.' },
    seeAlso: ['RwLock::write', 'RwLock::read', 'AtomicU32::fetch_add'],
  },
  {
    name: 'f64::to_radians',
    aliases: ['to_radians'],
    lang: 'rust',
    kind: 'method',
    official: 'Converts degrees to radians.',
    source: 'Rust standard library documentation',
    when: 'You have an angle in degrees and want to pass it to sin, cos or a rotation, which all expect radians.',
    example: { command: 'let rad = 120f64.to_radians();', says: 'Gives about 2.0944, the same angle in radians.' },
    seeAlso: ['f64::to_degrees', 'f64::cos'],
  },
  {
    name: 'f64::abs',
    aliases: ['abs'],
    lang: 'rust',
    kind: 'method',
    official: 'Computes the absolute value of self.',
    source: 'Rust standard library documentation',
    when: 'You want the size of a number without its sign, most often to compare two decimal numbers with a tolerance: (a - b).abs() < 1e-9. Computed floats are rarely exactly equal, so do not compare them with ==.',
    example: { command: 'assert!((out - 0.45).abs() < 1e-6);', says: 'Passes when out is within one millionth of 0.45.' },
    seeAlso: ['f64::sqrt', 'f64::is_finite'],
  },
  {
    name: 'BTreeMap::insert',
    aliases: ['insert'],
    lang: 'rust',
    kind: 'method',
    official: 'Inserts a key-value pair into the map.',
    source: 'Rust standard library documentation',
    when: 'You want to store a value under a key in a BTreeMap, which keeps its keys in sorted order. If the key was already there, the new value replaces the old one, and insert gives back the old one as Some(old); otherwise it gives None.',
    flags: [['key', 'the key, such as a time in ms'], ['value', 'the value to store under it']],
    example: { command: 'log.insert(300, 97.8);', says: 'Stores the pressure 97.8 bar under the time 300 ms.' },
    seeAlso: ['BTreeMap::range', 'BTreeMap::first_key_value', 'HashMap::entry'],
  },
  {
    name: 'Cell::set',
    aliases: ['set'],
    lang: 'rust',
    kind: 'method',
    official: 'Sets the contained value.',
    source: 'Rust standard library documentation',
    when: 'You want to replace the value in a Cell through a shared reference, such as counting reads inside a &self method.',
    flags: [['val', 'the new value']],
    example: { command: 'count.set(count.get() + 1);', says: 'Adds one to the counter in the Cell.' },
    seeAlso: ['Cell::get'],
  },
  {
    name: 'Pin::as_mut',
    aliases: ['as_mut'],
    lang: 'rust',
    kind: 'method',
    official: 'Gets a mutable reference to the pinned value this Pin<Ptr> points to.',
    source: 'Rust standard library documentation',
    when: 'You want a short-lived Pin<&mut T> from a pinned Box, most often to call poll on a future by hand without giving up the Box. Other types have an as_mut too: on a raw pointer it turns a *mut T into an Option<&mut T> (None for null), and a Box gives a &mut to what it holds.',
    example: { command: 'match fut.as_mut().poll(&mut cx) {\n    Poll::Ready(v) => println!("ready: {v}"),\n    Poll::Pending => println!("pending"),\n}', says: 'Polls the boxed future once and prints its value if it has already finished.' },
    seeAlso: ['Future::poll'],
  },
  {
    name: 'Result::ok',
    aliases: ['ok'],
    lang: 'rust',
    kind: 'method',
    official: 'Converts from Result<T, E> to Option<T>.',
    source: 'Rust standard library documentation',
    when: 'You want to turn a Result into an Option and drop the error, for example to use ? inside a function that returns Option. The reason for the failure is thrown away, so do not use it where someone needs to know why.',
    example: { command: 'let za = a.read().ok()?[2];', says: 'Reads the sensor; on an error the function returns None, otherwise it takes the z value.' },
    seeAlso: ['Option::ok_or', 'Result::is_ok'],
  },
  {
    name: 'pointer::is_null',
    aliases: ['is_null'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns true if the pointer is null.',
    source: 'Rust standard library documentation',
    when: 'You got a raw pointer from C and want to check it before you use it; FFI functions should return early on a null pointer. A pointer that is not null can still point at freed memory, so this check alone does not make it safe.',
    example: { command: 'if samples.is_null() || out.is_null() || len == 0 {\n    return -1;\n}', says: 'Refuses to run when C passed a null pointer or no data.' },
    seeAlso: ['pointer::add', 'slice::as_ptr'],
  },
  {
    name: 'slice::as_ptr',
    aliases: ['as_ptr'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns a raw pointer to the slice’s buffer.',
    source: 'Rust standard library documentation',
    when: 'You want to pass a slice to a C function, or walk it with raw pointers in unsafe code. The pointer is only valid while the slice is alive and unchanged, and it does not know how many items there are, so pass the length too (data.len()).',
    example: { command: 'unsafe { crc16_sys::crc16_ccitt(data.as_ptr(), data.len()) }', says: 'Hands C a pointer to the first byte and the number of bytes.' },
    seeAlso: ['slice::as_mut_ptr', 'pointer::add'],
  },
  {
    name: 'pointer::add',
    aliases: ['add'],
    lang: 'rust',
    kind: 'method',
    official: 'Adds an unsigned offset to a pointer.',
    source: 'Rust standard library documentation',
    when: 'In unsafe code, you want to move a raw pointer forward by a number of items (not bytes). Moving it outside the buffer (more than one past its end) is undefined behavior, which means the program may do anything, even if you never read there.',
    flags: [['count', 'how many items to move forward']],
    example: { command: 'total += unsafe { *p.add(i) };', says: 'Reads the item i places after p and adds it to the total.' },
    seeAlso: ['slice::as_ptr', 'pointer::is_null'],
  },
  {
    name: 'str::split_whitespace',
    aliases: ['split_whitespace'],
    lang: 'rust',
    kind: 'method',
    official: 'Splits a string slice by whitespace.',
    source: 'Rust standard library documentation',
    when: 'You want to break a line into words, however many spaces or tabs are between them. Empty pieces are dropped, so "  set   42  " gives just "set" and "42".',
    example: { command: 'let mut words = "burn  12.5".split_whitespace();', says: 'Gives an iterator over "burn" and "12.5".' },
    seeAlso: ['str::split', 'Iterator::next', 'str::trim'],
  },
  {
    name: 'String::capacity',
    aliases: ['capacity'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns this String’s capacity, in bytes.',
    source: 'Rust standard library documentation',
    when: 'You want to see how much memory a String has reserved, which can be more than its len. Adding text past the capacity makes the String move to a bigger buffer. Lessons use it to show what a String holds.',
    example: { command: 'let s = String::from("DRAGON-7");\nprintln!("len = {}, capacity = {}", s.len(), s.capacity());', says: 'Prints len = 8, capacity = 8: eight bytes of text in an eight-byte buffer.' },
    seeAlso: ['String::push_str', 'slice::len'],
  },
  {
    name: 'String::push_str',
    aliases: ['push_str'],
    lang: 'rust',
    kind: 'method',
    official: 'Appends a given string slice onto the end of this String.',
    source: 'Rust standard library documentation',
    when: 'You want to add a &str to the end of a String you own (declared with let mut). It takes a string slice, so pass &other for a String. For a single char, use push.',
    flags: [['string', 'the text to add']],
    example: { command: 'out.push_str(callsign);', says: 'Adds the callsign text to the end of out.' },
    seeAlso: ['Vec::push', 'ToString::to_string'],
  },
  {
    name: 'u8::checked_add',
    aliases: ['checked_add'],
    lang: 'rust',
    kind: 'method',
    official: 'Checked integer addition.',
    source: 'Rust standard library documentation',
    when: 'You want an addition where overflow would be a bug, such as a mission clock: you get Some(sum), or None if the result does not fit, and then you decide what to do. Every integer type has it.',
    flags: [['rhs', 'the number to add']],
    example: { command: '250_u8.checked_add(10)', says: 'Gives None, because 260 does not fit in a u8; 250_u8.checked_add(5) gives Some(255).' },
    seeAlso: ['u8::wrapping_add', 'u8::saturating_add', 'i64::checked_div'],
  },
  {
    name: 'Into::into',
    aliases: ['into'],
    lang: 'rust',
    kind: 'method',
    official: 'Converts this type into the (usually inferred) input type.',
    source: 'Rust standard library documentation',
    when: 'You want to convert a value into another type that has a From conversion, like degrees into radians. The target type must be clear from the context, such as a type on the variable or a function argument. Write an impl From and into comes for free.',
    example: { command: 'let r2: Radians = slew.into();', says: 'Converts slew to the Radians type using its From impl.' },
    seeAlso: ['TryInto::try_into'],
  },
  {
    name: 'Iterator::count',
    aliases: ['count'],
    lang: 'rust',
    kind: 'method',
    official: 'Consumes the iterator, counting the number of iterations and returning it.',
    source: 'Rust standard library documentation',
    when: 'You want to know how many items an iterator gives. It uses the iterator up. On text, s.chars().count() counts characters, while s.len() counts bytes.',
    example: { command: '"°C".chars().count()', says: 'Gives 2, while "°C".len() gives 3.' },
    seeAlso: ['slice::len', 'str::chars'],
  },
  {
    name: 'f64::cos',
    aliases: ['cos'],
    lang: 'rust',
    kind: 'method',
    official: 'Computes the cosine of a number (in radians).',
    source: 'Rust standard library documentation',
    when: 'You want the cosine of an angle in radians, for rotations, orbit geometry or test signals. Turn degrees into radians first with to_radians.',
    example: { command: 'let x = r * theta.cos();', says: 'Gives the x position on a circle of radius r at the angle theta.' },
    seeAlso: ['f64::sin', 'f64::to_radians'],
  },
  {
    name: 'Instant::elapsed',
    aliases: ['elapsed'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns the amount of time elapsed since this instant.',
    source: 'Rust standard library documentation',
    when: 'You want to time how long some code takes, as a rough benchmark: take Instant::now() before and call elapsed() after. It gives a Duration, which prints with {:?}. One run is noisy, so time many loops.',
    example: { command: 'let t0 = Instant::now();\nrun_filter();\nprintln!("{:?}", t0.elapsed());', says: 'Prints how long run_filter took, such as 1.2ms.' },
  },
  {
    name: 'RefCell::try_borrow_mut',
    aliases: ['try_borrow_mut'],
    lang: 'rust',
    kind: 'method',
    official: 'Mutably borrows the wrapped value, returning an error if the value is currently borrowed.',
    source: 'Rust standard library documentation',
    when: 'Like borrow_mut, but it gives an Err instead of panicking when the value is already borrowed, so you can handle the refusal with match.',
    example: { command: 'match events.try_borrow_mut() {\n    Ok(mut log) => log.push(String::from("first try")),\n    Err(e) => println!("could not write: {}", e),\n}', says: 'Adds to the log if nobody else is borrowing it, otherwise prints why it could not.' },
    seeAlso: ['RefCell::borrow_mut', 'RefCell::borrow'],
  },
  {
    name: 'Location::file',
    aliases: ['file'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns the name of the source file from which the panic originated.',
    source: 'Rust standard library documentation',
    when: 'In a panic hook, you want to know which source file the panic came from, for a crash record. Use it together with line.',
    example: { command: 'format!("{}:{}", l.file(), l.line())', says: 'Gives text like src/main.rs:42.' },
    seeAlso: ['Location::line', 'PanicHookInfo::location'],
  },
  {
    name: 'slice::sort',
    aliases: ['sort'],
    lang: 'rust',
    kind: 'method',
    official: 'Sorts the slice in ascending order, preserving initial order of equal elements.',
    source: 'Rust standard library documentation',
    when: 'You want a Vec or an array of integers, strings or enums in order, smallest first. It sorts in place and gives back nothing. It does not compile for f64, because NaN has no place in the order; use sort_by with total_cmp for decimal numbers.',
    example: { command: 'queue.sort();', says: 'Rearranges queue in place from smallest to largest.' },
    seeAlso: ['slice::sort_by', 'f64::total_cmp'],
  },
  {
    name: 'str::split_once',
    aliases: ['split_once'],
    lang: 'rust',
    kind: 'method',
    official: 'Splits the string on the first occurrence of the specified delimiter and returns prefix before delimiter and suffix after delimiter.',
    source: 'Rust standard library documentation',
    when: 'You want to split a key=value line into its two parts at the first separator. It gives Some((before, after)), or None when the separator is missing, which works well with ?.',
    flags: [['delimiter', 'the separator, such as \'=\'']],
    example: { command: 'let (key, value) = "limit=120".split_once(\'=\')?;', says: 'Gives key "limit" and value "120"; with no \'=\' the function returns None.' },
    seeAlso: ['str::split', 'str::trim'],
  },
  {
    name: 'str::trim',
    aliases: ['trim'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns a string slice with leading and trailing whitespace removed.',
    source: 'Rust standard library documentation',
    when: 'You want to drop the spaces, tabs and newline at both ends of some text, such as a line read from a file or typed by an operator. It gives a slice of the same text and copies nothing.',
    example: { command: '"  abort\\n".trim()', says: 'Gives "abort".' },
    seeAlso: ['str::split_whitespace', 'str::parse'],
  },
  {
    name: 'Vec::pop',
    aliases: ['pop'],
    lang: 'rust',
    kind: 'method',
    official: 'Removes the last element from a vector and returns it, or None if it is empty.',
    source: 'Rust standard library documentation',
    when: 'You want to remove the last item and get it back, as with a stack of commands. It gives Some(item), or None when the vector is empty, which makes while let Some(cmd) = commands.pop() a natural loop.',
    example: { command: 'while let Some(cmd) = commands.pop() { println!("{cmd}"); }', says: 'Takes commands off the end, last one first, until the Vec is empty.' },
    seeAlso: ['Vec::push', 'slice::last'],
  },
  {
    name: 'Iterator::copied',
    aliases: ['copied'],
    lang: 'rust',
    kind: 'method',
    official: 'Creates an iterator which copies all of its elements.',
    source: 'Rust standard library documentation',
    when: 'You want an iterator of plain values (f64) instead of references (&f64), so closures and fold get numbers. It only works for Copy types, such as numbers.',
    example: { command: 'let fastest = rates.iter().copied().fold(f64::MIN, f64::max);', says: 'Finds the largest rate.' },
    seeAlso: ['slice::iter', 'Iterator::fold'],
  },
  {
    name: 'slice::windows',
    aliases: ['windows'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns an iterator over all contiguous windows of length size.',
    source: 'Rust standard library documentation',
    when: 'You want to look at overlapping neighbors, such as each pair of samples to get a rate. windows(2) gives [a, b], then [b, c], and so on; a slice shorter than the size gives none. It panics if the size is 0.',
    flags: [['size', 'how many items in each window']],
    example: { command: 'for w in alt.windows(2) { println!("{}", w[1] - w[0]); }', says: 'Prints the change between each pair of neighboring altitudes.' },
    seeAlso: ['slice::iter', 'Iterator::map'],
  },
  {
    name: 'HashMap::entry',
    aliases: ['entry'],
    lang: 'rust',
    kind: 'method',
    official: 'Gets the given key’s corresponding entry in the map for in-place manipulation.',
    source: 'Rust standard library documentation',
    when: 'You want to look up a key so you can change or create its value in one step, most often to count things. BTreeMap has the same entry method.',
    flags: [['key', 'the key to find or add']],
    example: { command: '*counts.entry("IMU").or_insert(0) += 1;', says: 'Starts the IMU count at 0 if it is new, then adds one.' },
    seeAlso: ['Entry::or_insert', 'BTreeMap::insert'],
  },
  {
    name: 'Entry::or_insert',
    aliases: ['or_insert'],
    lang: 'rust',
    kind: 'method',
    official: 'Ensures a value is in the entry by inserting the default if empty, and returns a mutable reference to the value in the entry.',
    source: 'Rust standard library documentation',
    when: 'After entry(key), you give the value to store if the key is missing, and you get a &mut to the value either way. Put * in front to change it.',
    flags: [['default', 'the value to store if the key is not there yet']],
    example: { command: '*sorted.entry(p).or_insert(0) += 1;', says: 'Adds one to the count for the packet type p, starting from 0.' },
    seeAlso: ['HashMap::entry'],
  },
  {
    name: 'u8::saturating_add',
    aliases: ['saturating_add'],
    lang: 'rust',
    kind: 'method',
    official: 'Saturating integer addition.',
    source: 'Rust standard library documentation',
    when: 'You want an addition that stops at the type\'s largest value instead of wrapping, like a gauge that should read full and never flip back to empty: 250_u8.saturating_add(10) is 255.',
    flags: [['rhs', 'the number to add']],
    example: { command: '127_i8.saturating_add(1)', says: 'Gives 127, the largest i8, instead of wrapping to -128.' },
    seeAlso: ['u32::saturating_sub', 'u8::wrapping_add', 'u8::checked_add'],
  },
  {
    name: 'TryInto::try_into',
    aliases: ['try_into'],
    lang: 'rust',
    kind: 'method',
    official: 'Performs the conversion.',
    source: 'Rust standard library documentation',
    when: 'You want to convert between types where the value might not fit, such as i32 into u16. It gives Ok with the value, or an Err if it is out of range; write the target type, as in let ok: Result<u16, _> = x.try_into();. A plain as cast would quietly cut the number instead.',
    example: { command: 'let ok: Result<u16, _> = 1_200_i32.try_into();', says: 'Gives Ok(1200); 70_000_i32 would give an Err, because a u16 stops at 65535.' },
    seeAlso: ['Into::into'],
  },
  {
    name: 'Iterator::take',
    aliases: ['take'],
    lang: 'rust',
    kind: 'method',
    official: 'Creates an iterator that yields the first n elements, or fewer if the underlying iterator ends sooner.',
    source: 'Rust standard library documentation',
    when: 'You want only the first few items of an iterator, for example a preview of a long sequence. std::mem::take, which the lessons also use, is a different function: it swaps a value out and leaves its default behind.',
    flags: [['n', 'how many items at most']],
    example: { command: 'let first: Vec<f64> = grid().take(4).collect();', says: 'Collects just the first four sample times from the grid.' },
    seeAlso: ['Iterator::nth', 'Iterator::collect'],
  },
  {
    name: 'slice::sort_by',
    aliases: ['sort_by'],
    lang: 'rust',
    kind: 'method',
    official: 'Sorts the slice in ascending order with a comparison function, preserving initial order of equal elements.',
    source: 'Rust standard library documentation',
    when: 'You want to sort with your own comparison, most often for decimal numbers: v.sort_by(|a, b| a.total_cmp(b)). The closure gives back an Ordering: Less, Equal or Greater.',
    flags: [['|a, b| ...', 'compares two items and gives an Ordering']],
    example: { command: 'v.sort_by(|a, b| a.total_cmp(b));', says: 'Sorts a Vec of f64 values from smallest to largest.' },
    seeAlso: ['slice::sort', 'f64::total_cmp'],
  },
  {
    name: 'f64::total_cmp',
    aliases: ['total_cmp'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns the ordering between self and other.',
    source: 'Rust standard library documentation',
    when: 'You want to compare two decimal numbers in a way that always gives an answer, even for NaN, so they can be sorted. Swap the sides, b.total_cmp(a), for largest first. It puts -0.0 before 0.0, and a normal NaN after every number.',
    flags: [['other', 'a reference to the number to compare with']],
    example: { command: '2.5_f64.total_cmp(&1.0)', says: 'Gives Ordering::Greater.' },
    seeAlso: ['slice::sort_by'],
  },
  {
    name: 'str::to_uppercase',
    aliases: ['to_uppercase'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns the uppercase equivalent of this string slice, as a new String.',
    source: 'Rust standard library documentation',
    when: 'You want a capital-letter copy of some text, such as a callsign. It gives a new String and leaves the original alone. To compare text without caring about case, eq_ignore_ascii_case copies nothing.',
    example: { command: '"dragon".to_uppercase()', says: 'Gives the String "DRAGON".' },
    seeAlso: ['str::eq_ignore_ascii_case'],
  },
  {
    name: 'RefCell::into_inner',
    aliases: ['into_inner'],
    lang: 'rust',
    kind: 'method',
    official: 'Consumes the RefCell, returning the wrapped value.',
    source: 'Rust standard library documentation',
    when: 'You own a RefCell and are done with it, and want the value out, such as a log a worker thread hands back. It uses up the RefCell, so no borrow can still be alive.',
    example: { command: 'log.into_inner()', says: 'Takes the Vec out of the RefCell and gives it back.' },
    seeAlso: ['RefCell::borrow_mut'],
  },
  {
    name: 'Future::poll',
    aliases: ['poll'],
    lang: 'rust',
    kind: 'method',
    official: 'Attempts to resolve the future to a final value, registering the current task for wakeup if the value is not yet available.',
    source: 'Rust standard library documentation',
    when: 'You want a future to make progress once. Normally .await or an async runtime (an executor) calls it for you; the lessons call it by hand to show what happens inside. The future must be pinned (Pin<&mut Self>), and the answer is Poll::Ready(value) or Poll::Pending.',
    flags: [['cx', 'the Context, which carries the waker that says when to poll again']],
    example: { command: 'let mut cx = Context::from_waker(Waker::noop());\nlet p = fut.as_mut().poll(&mut cx);', says: 'Runs the future until it finishes or has to wait, and gives Ready or Pending.' },
    seeAlso: ['Pin::as_mut'],
  },
  {
    name: 'Drop::drop',
    aliases: ['drop'],
    lang: 'rust',
    kind: 'method',
    official: 'Executes the destructor for this type.',
    source: 'Rust standard library documentation',
    when: 'You write drop inside an impl Drop to run cleanup code when a value goes out of scope, like closing a valve. You never call it yourself: h.drop() is a compile error; use drop(h) (std::mem::drop) to end a value early.',
    example: { command: 'impl Drop for Heater {\n    fn drop(&mut self) { println!("heater off"); }\n}', says: 'Prints heater off by itself when a Heater goes out of scope.' },
    seeAlso: ['Clone::clone'],
  },
  {
    name: 'f64::sin',
    aliases: ['sin'],
    lang: 'rust',
    kind: 'method',
    official: 'Computes the sine of a number (in radians).',
    source: 'Rust standard library documentation',
    when: 'You want the sine of an angle in radians, for rotations or test signals. Turn degrees into radians first with to_radians.',
    example: { command: 'let y = r * theta.sin();', says: 'Gives the y position on a circle of radius r at the angle theta.' },
    seeAlso: ['f64::cos', 'f64::to_radians'],
  },
  {
    name: 'Iterator::all',
    aliases: ['all'],
    lang: 'rust',
    kind: 'method',
    official: 'Tests if every element of the iterator matches a predicate.',
    source: 'Rust standard library documentation',
    when: 'You want to check that every item passes a test. It stops at the first item that fails, and gives true for an empty iterator.',
    flags: [['|x| ...', 'the test for each item']],
    example: { command: '(0..3).all(|_| self.read().is_ok())', says: 'True if three reads in a row succeed; it stops at the first failed read.' },
    seeAlso: ['Iterator::any'],
  },
  {
    name: 'Result::is_ok',
    aliases: ['is_ok'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns true if the result is Ok.',
    source: 'Rust standard library documentation',
    when: 'You only want to know whether a Result succeeded, not its value. It does not take the value out; use match or ? for that.',
    example: { command: 'if sensor.read().is_ok() { println!("sensor alive"); }', says: 'Prints only when the read worked.' },
    seeAlso: ['Result::is_err', 'Result::ok'],
  },
  {
    name: 'Iterator::any',
    aliases: ['any'],
    lang: 'rust',
    kind: 'method',
    official: 'Tests if any element of the iterator matches a predicate.',
    source: 'Rust standard library documentation',
    when: 'You want to check whether at least one item passes a test. It stops at the first match, and gives false for an empty iterator.',
    flags: [['|x| ...', 'the test for each item']],
    example: { command: 'let saw_arm = events.borrow().iter().any(|e| e == "arm");', says: 'True if any logged event is "arm".' },
    seeAlso: ['Iterator::all', 'slice::contains'],
  },
  {
    name: 'OnceLock::get_or_init',
    aliases: ['get_or_init'],
    lang: 'rust',
    kind: 'method',
    official: 'Gets the contents of the cell, initializing it to f() if the cell was uninitialized.',
    source: 'Rust standard library documentation',
    when: 'You want to set up a value the first time anyone needs it, such as a calibration table in a static, and share it after that. The closure runs only once, even if several threads ask at the same moment.',
    flags: [['|| ...', 'builds the value the first time']],
    example: { command: 'static SCALE: OnceLock<[f64; 3]> = OnceLock::new();\nlet s = SCALE.get_or_init(|| [1.0, 1.02, 0.98]);', says: 'Builds the scale factors on the first call; later calls get the same array.' },
    seeAlso: ['Mutex::lock'],
  },
  {
    name: 'RwLock::write',
    aliases: ['write'],
    lang: 'rust',
    kind: 'method',
    official: 'Locks this RwLock with exclusive write access, blocking the current thread until it can be acquired.',
    source: 'Rust standard library documentation',
    when: 'You want to change data behind a RwLock. It waits until no reader or writer holds the lock, then gives you the only access. Like read, it returns a Result, and a guard kept too long keeps every reader waiting.',
    example: { command: 'let mut t = target_attitude.write().unwrap();\nt[2] = 45.0;', says: 'Waits for sole access and sets the yaw target to 45 degrees.' },
    seeAlso: ['RwLock::read', 'Mutex::lock'],
  },
  {
    name: 'Extend::extend',
    aliases: ['extend'],
    lang: 'rust',
    kind: 'method',
    official: 'Extends a collection with the contents of an iterator.',
    source: 'Rust standard library documentation',
    when: 'You want to add all the items from another collection or iterator to the end of a Vec in one call. It takes the other collection by value, so a Vec you pass in is used up.',
    flags: [['iter', 'the items to add, such as another Vec']],
    example: { command: 'waypoints.extend(extra);', says: 'Adds every waypoint from extra to the end of waypoints.' },
    seeAlso: ['Vec::push'],
  },
  {
    name: 'slice::split_at_mut',
    aliases: ['split_at_mut'],
    lang: 'rust',
    kind: 'method',
    official: 'Divides one mutable slice into two at an index.',
    source: 'Rust standard library documentation',
    when: 'You want two &mut pieces of one slice that do not overlap, so two threads or two parts of your code can change them at the same time. The borrow checker cannot tell that v[0] and v[1] are separate, but it trusts split_at_mut. It panics if the index is past the end.',
    flags: [['mid', 'the index where the second piece starts']],
    example: { command: 'let (left, right) = counts.split_at_mut(1);', says: 'left is counts[..1] and right is counts[1..], and both can be changed.' },
    seeAlso: ['slice::split_at', 'Scope::spawn'],
  },
  {
    name: 'slice::as_mut_ptr',
    aliases: ['as_mut_ptr'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns an unsafe mutable pointer to the slice’s buffer.',
    source: 'Rust standard library documentation',
    when: 'You want a raw pointer you can write through, for unsafe code or a C function that fills a buffer. The same rules as as_ptr apply: it is valid only while the slice lives, and you pass the length too.',
    example: { command: 'let p = v.as_mut_ptr();', says: 'p points at the first f64 of v.' },
    seeAlso: ['slice::as_ptr', 'pointer::add'],
  },
  {
    name: 'slice::copy_within',
    aliases: ['copy_within'],
    lang: 'rust',
    kind: 'method',
    official: 'Copies elements from one part of the slice to another part of itself, using a memmove.',
    source: 'Rust standard library documentation',
    when: 'You want to shift items inside one array or slice, for example to drop the oldest sample from a fixed buffer. The two ranges may overlap. It panics if either one runs past the end, and the items must be Copy.',
    flags: [['src', 'the range to copy, such as 1..'], ['dest', 'the index to copy it to']],
    example: { command: 'self.buf.copy_within(1.., 0);', says: 'Moves every item one place to the left; the last slot keeps its old value until you overwrite it.' },
    seeAlso: ['slice::copy_from_slice'],
  },
  {
    name: 'slice::get_unchecked',
    aliases: ['get_unchecked'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns a reference to an element or subslice, without doing bounds checking.',
    source: 'Rust standard library documentation',
    when: 'In unsafe code, you want to index without the bounds check because you have proved the index is in range. Out of range, it is undefined behavior instead of a panic, so almost always use v[i] or get instead.',
    flags: [['index', 'a position or a range, such as ..self.len']],
    example: { command: 'unsafe { self.buf.get_unchecked(..self.len) }', says: 'Gives the first len items without checking; the SAFETY comment must say why len is in range.' },
    seeAlso: ['slice::len'],
  },
  {
    name: 'slice::split_at',
    aliases: ['split_at'],
    lang: 'rust',
    kind: 'method',
    official: 'Divides one slice into two at an index.',
    source: 'Rust standard library documentation',
    when: 'You want to cut a slice in two at an index, such as a frame body and its last checksum byte. Both pieces borrow from the original. It panics if the index is bigger than the length, and bytes.len() - 1 itself panics on an empty slice, so check the length first.',
    flags: [['mid', 'the index where the second piece starts']],
    example: { command: 'let (body, last) = bytes.split_at(bytes.len() - 1);', says: 'body is every byte but the last; last holds just the checksum byte.' },
    seeAlso: ['slice::split_at_mut'],
  },
  {
    name: 'slice::contains',
    aliases: ['contains'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns true if the slice contains an element with the given value.',
    source: 'Rust standard library documentation',
    when: 'You want to know whether a value is in an array, a slice or a Vec, such as a list of known APIDs. Pass a reference: contains(&apid). It checks the items one by one, so for a big set a HashSet is faster.',
    flags: [['x', 'a reference to the value to look for']],
    example: { command: '[100, 200].contains(&apid)', says: 'True when apid is 100 or 200.' },
    seeAlso: ['Iterator::any'],
  },
  {
    name: 'str::lines',
    aliases: ['lines'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns an iterator over the lines of a string, as string slices.',
    source: 'Rust standard library documentation',
    when: 'You want to go through text one line at a time, such as a file read into a String. It handles both \\n and \\r\\n line endings, and the pieces leave the ending out.',
    example: { command: 'for (i, line) in text.lines().enumerate() { println!("{}: {line}", i + 1); }', says: 'Prints each line with its line number, starting at 1.' },
    seeAlso: ['str::split', 'Iterator::enumerate'],
  },
  {
    name: 'Iterator::nth',
    aliases: ['nth'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns the nth element of the iterator.',
    source: 'Rust standard library documentation',
    when: 'You want the item at a position, counting from 0, such as the first command-line argument: std::env::args().nth(1), because index 0 is the program name. It gives an Option and uses up the items before it.',
    flags: [['n', 'the position, starting at 0']],
    example: { command: 'let path = std::env::args().nth(1).unwrap_or("frames.txt".to_string());', says: 'Uses the first argument after the program name, or frames.txt if none was given.' },
    seeAlso: ['Iterator::next', 'Option::unwrap_or'],
  },
  {
    name: 'PanicHookInfo::location',
    aliases: ['location'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns information about the location from which the panic originated, if available.',
    source: 'Rust standard library documentation',
    when: 'Inside a panic hook set with std::panic::set_hook, you want to know where the panic happened. It gives an Option<&Location>; call file and line on it.',
    example: { command: 'let place = info.location().map(|l| format!("{}:{}", l.file(), l.line())).unwrap_or_default();', says: 'Gives text like src/main.rs:42, or an empty String if the place is unknown.' },
    seeAlso: ['Location::file', 'Location::line', 'PanicHookInfo::payload_as_str'],
  },
  {
    name: 'Location::line',
    aliases: ['line'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns the line number from which the panic originated.',
    source: 'Rust standard library documentation',
    when: 'Together with file, you want the line number where a panic started, for a crash log.',
    example: { command: 'println!("line {}", l.line());', says: 'Prints the line number of the panic.' },
    seeAlso: ['Location::file'],
  },
  {
    name: 'Option::unwrap_or_default',
    aliases: ['unwrap_or_default'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns the contained Some value or a default.',
    source: 'Rust standard library documentation',
    when: 'You want the value from an Option, or the type\'s default when it is None: 0 for numbers, an empty String, an empty Vec.',
    example: { command: 'let name: String = maybe_name.unwrap_or_default();', says: 'Gives the name, or an empty String if there was none.' },
    seeAlso: ['Option::unwrap_or'],
  },
  {
    name: 'PanicHookInfo::payload_as_str',
    aliases: ['payload_as_str'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns the payload associated with the panic, if it is a string.',
    source: 'Rust standard library documentation',
    when: 'In a panic hook, you want the panic message as text, for a crash record. It gives None when the message is not a string, so add a fallback.',
    example: { command: 'let msg = info.payload_as_str().unwrap_or("(no message)");', says: 'Gets the message, or "(no message)" if the panic carried no text.' },
    seeAlso: ['PanicHookInfo::location'],
  },
  {
    name: 'i64::checked_div',
    aliases: ['checked_div'],
    lang: 'rust',
    kind: 'method',
    official: 'Checked integer division.',
    source: 'Rust standard library documentation',
    when: 'You want to divide integers without crashing on a zero divisor: you get None instead of a panic. Integer division also drops the fraction, so 7 / 2 is 3.',
    flags: [['rhs', 'the number to divide by']],
    example: { command: 'total.checked_div(count as i64)', says: 'Gives Some(mean), or None when count is 0.' },
    seeAlso: ['u8::checked_add'],
  },
  {
    name: 'f64::sqrt',
    aliases: ['sqrt'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns the square root of a number.',
    source: 'Rust standard library documentation',
    when: 'You want a square root, as in the length of a vector, sqrt(x² + y² + z²). A negative number gives NaN (not a number), not an error.',
    example: { command: 'let speed = (vx * vx + vy * vy + vz * vz).sqrt();', says: 'Gives the length of the velocity vector.' },
    seeAlso: ['f64::abs', 'f64::is_finite'],
  },
  {
    name: 'Clone::clone',
    aliases: ['clone'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns a duplicate of the value.',
    source: 'Rust standard library documentation',
    when: 'You want a full, separate copy of a value such as a Vec, so you can keep the original and hand the copy away. For a Vec or a String it copies the whole buffer. For Rc and Arc, lessons write Rc::clone(&log): that only adds one more owner and copies nothing.',
    example: { command: 'let backup = samples.clone();', says: 'Makes a second Vec with the same samples in its own memory.' },
    seeAlso: ['Drop::drop'],
  },
  {
    name: 'f64::max',
    aliases: ['max'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns the maximum of the two numbers, ignoring NaN.',
    source: 'Rust standard library documentation',
    when: 'You want the larger of two numbers, for a floor like x.max(0.0) or a running highest value. If one of them is NaN, you get the other one.',
    flags: [['other', 'the number to compare with']],
    example: { command: 'let thrust = raw.max(0.0);', says: 'Treats any negative reading as 0.0.' },
    seeAlso: ['f64::min', 'f64::clamp'],
  },
  {
    name: 'str::chars',
    aliases: ['chars'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns an iterator over the chars of a string slice.',
    source: 'Rust standard library documentation',
    when: 'You want to go through text one character at a time. One char can take up to 4 bytes, so count characters with chars().count(), not len().',
    example: { command: 'for c in "GO".chars() { println!("{c}"); }', says: 'Prints G, then O.' },
    seeAlso: ['Iterator::count', 'slice::len'],
  },
  {
    name: 'str::eq_ignore_ascii_case',
    aliases: ['eq_ignore_ascii_case'],
    lang: 'rust',
    kind: 'method',
    official: 'Checks that two strings are an ASCII case-insensitive match.',
    source: 'Rust standard library documentation',
    when: 'You want to compare commands without caring about capital letters, like ABORT, Abort and abort. It only folds the letters A to Z, and it copies nothing.',
    flags: [['other', 'the text to compare with']],
    example: { command: 'command.trim().eq_ignore_ascii_case("abort")', says: 'True for "Abort\\n" or "ABORT", false for "abort now".' },
    seeAlso: ['str::to_uppercase', 'str::trim'],
  },
  {
    name: 'slice::last',
    aliases: ['last'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns the last element of the slice, or None if it is empty.',
    source: 'Rust standard library documentation',
    when: 'You want to look at the last item without removing it, such as the newest reading. It gives Some(&item), or None when the slice is empty.',
    example: { command: 'let last: Option<&f64> = readings.last();', says: 'A reference to the newest reading, or None if there are none.' },
    seeAlso: ['Vec::pop'],
  },
  {
    name: 'Result::map_err',
    aliases: ['map_err'],
    lang: 'rust',
    kind: 'method',
    official: 'Maps a Result<T, E> to Result<T, F> by applying a function to a contained Err value, leaving an Ok value untouched.',
    source: 'Rust standard library documentation',
    when: 'You want to change the error type, often from a library error into your own enum, so ? can pass it up. An Ok value goes through untouched.',
    flags: [['|e| ...', 'turns the old error into the new one']],
    example: { command: 'let v: f64 = number.parse().map_err(|_| PressureError::BadNumber(number.to_string()))?;', says: 'Parses the number, and on failure returns your own BadNumber error instead.' },
    seeAlso: ['Option::ok_or', 'str::parse'],
  },
  {
    name: 'Option::ok_or',
    aliases: ['ok_or'],
    lang: 'rust',
    kind: 'method',
    official: 'Transforms the Option<T> into a Result<T, E>, mapping Some(v) to Ok(v) and None to Err(err).',
    source: 'Rust standard library documentation',
    when: 'You want to turn an Option into a Result by giving the error to use for None, so ? works in a function that returns Result.',
    flags: [['err', 'the error to use when it is None']],
    example: { command: 'let text = value_of(line).ok_or(ConfigError::MissingEquals)?;', says: 'Gets the value, or returns MissingEquals when the line had none.' },
    seeAlso: ['Result::ok', 'Result::map_err'],
  },
  {
    name: 'slice::is_empty',
    aliases: ['is_empty'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns true if the slice has a length of 0.',
    source: 'Rust standard library documentation',
    when: 'You want to check that there are no items before you divide by the length or take the first one. It reads more clearly than len() == 0.',
    example: { command: 'if samples.is_empty() { return 0.0; }', says: 'Returns 0.0 instead of dividing by zero.' },
    seeAlso: ['slice::len'],
  },
  {
    name: 'f64::is_finite',
    aliases: ['is_finite'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns true if this number is neither infinite nor NaN.',
    source: 'Rust standard library documentation',
    when: 'You want to check that a computed value is a real number, not infinity or NaN (not a number), for example after a division and before you use it.',
    example: { command: 'debug_assert!(x.is_finite());', says: 'In a debug build, stops the program if x became infinite or NaN.' },
    seeAlso: ['f64::sqrt'],
  },
  {
    name: 'BTreeMap::range',
    aliases: ['range'],
    lang: 'rust',
    kind: 'method',
    official: 'Constructs a double-ended iterator over a sub-range of elements in the map.',
    source: 'Rust standard library documentation',
    when: 'You want to walk only the keys in a range, in sorted order, such as log entries between two times. You get (key, value) pairs as references.',
    flags: [['range', 'which keys, such as 150..=350 (both ends included) or 150..350 (end left out)']],
    example: { command: 'for (t, p) in log.range(150..=350) { println!("{t} ms: {p} bar"); }', says: 'Prints the entries at 200 ms and 300 ms only.' },
    seeAlso: ['BTreeMap::insert', 'BTreeMap::first_key_value'],
  },
  {
    name: 'BTreeMap::first_key_value',
    aliases: ['first_key_value'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns the first key-value pair in the map.',
    source: 'Rust standard library documentation',
    when: 'You want the entry with the smallest key, such as the earliest time in a log. It gives Some((&key, &value)), or None if the map is empty.',
    example: { command: 'println!("first: {:?}", log.first_key_value());', says: 'Prints first: Some((100, 12.4)) for the chamber pressure log.' },
    seeAlso: ['BTreeMap::range'],
  },
  {
    name: 'u8::overflowing_add',
    aliases: ['overflowing_add'],
    lang: 'rust',
    kind: 'method',
    official: 'Calculates self + rhs.',
    source: 'Rust standard library documentation',
    when: 'You want an addition that also tells you whether it wrapped: you get a pair of the wrapped result and true or false.',
    flags: [['rhs', 'the number to add']],
    example: { command: '250_u8.overflowing_add(10)', says: 'Gives (4, true): the answer wrapped around.' },
    seeAlso: ['u8::wrapping_add', 'u8::checked_add'],
  },
  {
    name: 'u32::saturating_sub',
    aliases: ['saturating_sub'],
    lang: 'rust',
    kind: 'method',
    official: 'Saturating integer subtraction.',
    source: 'Rust standard library documentation',
    when: 'You want a subtraction that stops at zero (the type\'s smallest value) instead of wrapping around to a huge number, like the propellant left after a burn.',
    flags: [['rhs', 'the number to subtract']],
    example: { command: '1_500_u32.saturating_sub(2_000)', says: 'Gives 0 instead of wrapping around.' },
    seeAlso: ['u32::wrapping_sub', 'u8::saturating_add'],
  },
  {
    name: 'u32::wrapping_sub',
    aliases: ['wrapping_sub'],
    lang: 'rust',
    kind: 'method',
    official: 'Wrapping (modular) subtraction.',
    source: 'Rust standard library documentation',
    when: 'You want a subtraction that wraps around below zero on purpose, as with differences between wrapping counters. On amounts that cannot go below zero, like grams of propellant, it gives a huge wrong answer.',
    flags: [['rhs', 'the number to subtract']],
    example: { command: '1_500_u32.wrapping_sub(2_000)', says: 'Gives 4294966796, because it wrapped around below zero.' },
    seeAlso: ['u32::saturating_sub', 'u8::wrapping_add'],
  },
  {
    name: 'AtomicU32::fetch_add',
    aliases: ['fetch_add'],
    lang: 'rust',
    kind: 'method',
    official: 'Adds to the current value, returning the previous value.',
    source: 'Rust standard library documentation',
    when: 'You want to add to a counter shared between threads or with an interrupt handler, without a lock. Ordering::Relaxed is enough for a plain counter. It wraps on overflow and gives back the old value.',
    flags: [['val', 'the amount to add'], ['order', 'the memory ordering, such as Ordering::Relaxed for a simple counter']],
    example: { command: 'TICKS.fetch_add(1, Ordering::Relaxed);', says: 'Adds one to the shared tick counter in a single step that no other thread can split.' },
    seeAlso: ['Mutex::lock'],
  },
  {
    name: 'Result::is_err',
    aliases: ['is_err'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns true if the result is Err.',
    source: 'Rust standard library documentation',
    when: 'You only want to know whether a Result failed, not the error itself, for example to try again: while producer.enqueue(sample).is_err() { ... }.',
    example: { command: 'if "12,5".parse::<f64>().is_err() { println!("bad number"); }', says: 'Prints bad number, because the parse failed.' },
    seeAlso: ['Result::is_ok'],
  },
  {
    name: 'RefCell::replace',
    aliases: ['replace'],
    lang: 'rust',
    kind: 'method',
    official: 'Replaces the wrapped value with a new one, returning the old value, without deinitializing either one.',
    source: 'Rust standard library documentation',
    when: 'You want to put a new value into a RefCell and get the old one back in one step, such as the latest frame shared with an interrupt. It panics if the value is borrowed at that moment.',
    flags: [['t', 'the new value']],
    example: { command: 'LATEST.borrow(cs).replace(Some(frame));', says: 'Stores the newest frame and gives back the one it replaced.' },
    seeAlso: ['RefCell::borrow_mut'],
  },
  {
    name: 'Option::as_ref',
    aliases: ['as_ref'],
    lang: 'rust',
    kind: 'method',
    official: 'Converts from &Option<T> to Option<&T>.',
    source: 'Rust standard library documentation',
    when: 'You want to look at the value inside an Option without taking it out: it turns &Option<T> into Option<&T>, so you can map over it and leave the original where it is.',
    example: { command: 'latest.as_ref().map(|f| f.seq)', says: 'Gives the sequence number of the stored frame, if there is one, without moving the frame.' },
    seeAlso: ['Option::unwrap_or'],
  },
  {
    name: 'usize::is_power_of_two',
    aliases: ['is_power_of_two'],
    lang: 'rust',
    kind: 'method',
    official: 'Returns true if and only if self == 2^k for some unsigned integer k.',
    source: 'Rust standard library documentation',
    when: 'You want to check a size that must be 1, 2, 4, 8 and so on, such as a ring-buffer depth. It works at compile time too, in a const or a const_assert!. Zero is not a power of two.',
    example: { command: 'const_assert!(QUEUE_DEPTH.is_power_of_two());', says: 'Stops the build if QUEUE_DEPTH is not a power of two.' },
  },
  {
    name: 'slice::copy_from_slice',
    aliases: ['copy_from_slice'],
    lang: 'rust',
    kind: 'method',
    official: 'Copies all elements from src into self, using a memcpy.',
    source: 'Rust standard library documentation',
    when: 'You want to copy a whole slice into another one of exactly the same length, such as filling registers in a fake bus. It panics if the lengths differ.',
    flags: [['src', 'the slice to copy from, the same length as the destination']],
    example: { command: 'regs[0x3B..0x41].copy_from_slice(&[0x20, 0x00, 0xF0, 0x00, 0x40, 0x00]);', says: 'Writes six bytes into registers 0x3B to 0x40.' },
    seeAlso: ['slice::copy_within'],
  },
]
