import type { CommandRef } from './types'

const STD = 'Rust standard library documentation'

export const COMMANDS: CommandRef[] = [
  /* ── Keywords ─────────────────────────────────────────────────────────── */
  {
    name: 'let',
    lang: 'rust',
    kind: 'keyword',
    official: 'Bind a value to a variable.',
    source: STD,
    when: 'Every time you make a new variable. A plain let cannot be changed later; write let mut if you will change it. Writing let again with the same name makes a brand new variable that hides the old one (called shadowing), which is allowed and common.',
    flags: [
      ['let x: f64 = ...', 'give the type yourself instead of letting Rust work it out'],
      ['let (a, b) = ...', 'unpack a tuple into two variables at once'],
      ['let Some(x) = ... else { ... }', 'let-else: unpack or leave the function early'],
    ],
    example: { command: 'let mass_kg: f64 = 549_054.0;', says: 'Makes a variable mass_kg holding 549054.0 as a 64-bit decimal number. It cannot be changed afterwards.' },
    seeAlso: ['mut', 'const'],
  },
  {
    name: 'fn',
    lang: 'rust',
    kind: 'keyword',
    official: 'A function or function pointer.',
    source: STD,
    when: 'To write a function: a named piece of code you can call again and again. Every parameter needs a type, and -> Type says what comes back. The last line without a semicolon is the value returned; adding a semicolon there by mistake returns () instead.',
    flags: [
      ['-> T', 'the type the function hands back'],
      ['pub fn', 'a function other modules may call'],
      ['const fn', 'a function that can also run while compiling'],
      ['&self / &mut self', 'the first parameter of a method, the value it was called on'],
    ],
    example: { command: 'fn deg_to_rad(deg: f64) -> f64 {\n    deg * std::f64::consts::PI / 180.0\n}', says: 'Defines a function that takes an angle in degrees and gives back the same angle in radians.' },
    seeAlso: ['return', 'impl', 'pub'],
  },
  {
    name: 'mut',
    lang: 'rust',
    kind: 'keyword',
    official: 'A mutable variable, reference, or pointer.',
    source: STD,
    when: 'When a value has to change after you make it: a counter, a buffer you push into, a struct you update. Rust variables cannot change unless you say mut. A &mut reference lets a function change your value, but while it exists nothing else may read or change that value.',
    flags: [
      ['let mut', 'a variable you may change'],
      ['&mut x', 'lend x to someone who may change it'],
      ['*mut T', 'a raw pointer you may write through (unsafe code only)'],
    ],
    example: { command: 'let mut fuel_kg = 1200.0;\nfuel_kg -= 35.5;', says: 'Makes a changeable variable, then burns 35.5 kg so it now holds 1164.5.' },
    seeAlso: ['let'],
  },
  {
    name: 'self',
    lang: 'rust',
    kind: 'keyword',
    official: 'The receiver of a method, or the current module.',
    source: STD,
    when: 'Inside a method, self is the value the method was called on, like this in other languages. The first parameter decides how the method gets it: &self only reads it, &mut self may change it, and plain self takes it over, so you cannot use the value after the call.',
    flags: [
      ['&self', 'the method only looks at the value'],
      ['&mut self', 'the method may change the value'],
      ['self', 'the method takes ownership and uses the value up'],
      ['self.field', 'reach one field of the value'],
    ],
    example: { command: 'fn is_low(&self) -> bool {\n    self.fuel_kg < 100.0\n}', says: 'A method that reads the fuel of the tank it was called on and says whether it is below 100 kg.' },
    seeAlso: ['Self', 'impl'],
  },
  {
    name: 'use',
    lang: 'rust',
    kind: 'keyword',
    official: 'Import or rename items from other crates or modules, use values under ergonomic clones semantic, or specify precise capturing with use<..>.',
    source: STD,
    when: 'At the top of a file, to bring a name in so you can write HashMap instead of std::collections::HashMap every time. It only makes a shortcut; the crate still has to be listed in Cargo.toml if it is not part of the standard library.',
    flags: [
      ['{A, B}', 'bring in several names from one place'],
      ['as', 'give the name a different local name'],
      ['*', 'bring in everything public from a module (common in tests: use super::*)'],
      ['as _', 'link a crate in without naming it (use panic_halt as _;)'],
    ],
    example: { command: 'use std::collections::{BTreeMap, HashMap};', says: 'Lets the rest of the file write BTreeMap and HashMap by their short names.' },
    seeAlso: ['mod', 'crate', 'super', 'as'],
  },
  {
    name: 'for',
    lang: 'rust',
    kind: 'keyword',
    official: 'Iteration with in, trait implementation with impl, or higher-ranked trait bounds (for<\'a>).',
    source: STD,
    when: 'To do something once for each item in a collection or range. for x in v moves the items out of v so v is gone afterwards; loop over &v to only borrow them. You cannot push to or remove from the same Vec inside its own loop.',
    flags: [
      ['in 0..n', 'count from 0 up to n - 1'],
      ['in &v', 'visit each item without taking the Vec away'],
      ['in &mut v', 'visit each item and allow changing it'],
      ['impl Trait for Type', 'the other use of for: say which type gets the trait'],
    ],
    example: { command: 'for (i, t) in temps.iter().enumerate() {\n    println!("sensor {i}: {t} C");\n}', says: 'Prints one line per temperature, each with its position number: sensor 0: 21.5 C, and so on.' },
    seeAlso: ['in', 'while', 'loop', 'Iterator'],
  },
  {
    name: 'pub',
    lang: 'rust',
    kind: 'keyword',
    official: 'Make an item visible to others.',
    source: STD,
    when: 'To let code outside a module use a function, struct, field or module. Everything in Rust is private unless you write pub. Making a struct pub does not make its fields pub; each field needs its own pub.',
    flags: [
      ['pub fn', 'a function other modules can call'],
      ['pub struct / pub field', 'a type, or one field of it, others can see'],
      ['pub mod', 'a module others can reach into'],
    ],
    example: { command: 'pub struct Tank {\n    pub name: String,\n    fuel_kg: f64,\n}', says: 'Other modules can see Tank and its name, but fuel_kg stays private to this module.' },
    seeAlso: ['mod', 'use'],
  },
  {
    name: 'in',
    lang: 'rust',
    kind: 'keyword',
    official: 'Iterate over a series of values with for.',
    source: STD,
    when: 'Only as part of a for loop, between the loop variable and the thing you loop over. A range written 0..10 stops before 10; write 0..=10 to include 10.',
    flags: [
      ['a..b', 'from a up to but not including b'],
      ['a..=b', 'from a up to and including b'],
    ],
    example: { command: 'for stage in 1..=3 {\n    println!("stage {stage} ready");\n}', says: 'Prints stage 1 ready, stage 2 ready, stage 3 ready.' },
    seeAlso: ['for'],
  },
  {
    name: 'impl',
    lang: 'rust',
    kind: 'keyword',
    official: 'Implementations of functionality for a type, or a type implementing some functionality.',
    source: STD,
    when: 'To give a struct or enum its methods (impl Tank { ... }) or to make it fit a trait (impl Display for Vec3 { ... }). In a parameter or return type, impl Trait means some type that has this trait, without naming which one.',
    flags: [
      ['impl Type { }', 'methods and constructors like new() for your own type'],
      ['impl Trait for Type { }', 'fill in the methods a trait asks for'],
      ['-> impl Fn(f64) -> f64', 'return some value that has the trait, here a closure'],
    ],
    example: { command: 'impl Tank {\n    fn new(name: &str) -> Self {\n        Tank { name: name.to_string(), fuel_kg: 0.0 }\n    }\n}', says: 'Gives Tank a constructor, so Tank::new("LOX") makes an empty tank named LOX.' },
    seeAlso: ['struct', 'trait', 'Self', 'fn'],
  },
  {
    name: 'struct',
    lang: 'rust',
    kind: 'keyword',
    official: 'A type that is composed of other types.',
    source: STD,
    when: 'To group values that belong together, like the x, y and z of a vector or the name and fuel of a tank, into one new type. Methods go in a separate impl block. A tuple struct such as struct Meters(f64); wraps one value so it cannot be mixed up with other f64s.',
    flags: [
      ['struct Name { field: Type }', 'named fields, read as value.field'],
      ['struct Name(Type);', 'a tuple struct, fields read as value.0'],
      ['#[derive(...)]', 'let the compiler write Debug, Clone, PartialEq and so on for you'],
    ],
    example: { command: '#[derive(Debug, Clone, Copy)]\nstruct Vec3 { x: f64, y: f64, z: f64 }', says: 'Defines a 3D vector type that can be printed with {:?} and copied freely.' },
    seeAlso: ['impl', 'enum', 'Debug'],
  },
  {
    name: 'if',
    lang: 'rust',
    kind: 'keyword',
    official: 'Evaluate a block if a condition holds.',
    source: STD,
    when: 'To run code only when a condition is true. The condition must really be a bool; Rust will not treat 0 or an empty list as false. An if with an else can give back a value, so you can write let x = if a { 1 } else { 2 };.',
    flags: [
      ['else if', 'try another condition'],
      ['if let Some(x) = ...', 'run the block only if the value matches the pattern'],
    ],
    example: { command: 'let phase = if altitude_m > 1_000.0 { "descent" } else { "terminal" };', says: 'Sets phase to "descent" above 1000 m and "terminal" at or below it.' },
    seeAlso: ['else', 'match'],
  },
  {
    name: 'as',
    lang: 'rust',
    kind: 'keyword',
    official: 'Cast between types, rename an import, or qualify paths to associated items.',
    source: STD,
    when: 'To turn one number type into another, like counts as f32, or to rename something you import. Careful: as never fails and never warns, so 70000 as u16 quietly becomes 4464 and 3.9 as i32 becomes 3. Use try_into when a value might not fit.',
    flags: [
      ['x as T', 'convert x to number type T, cutting off what does not fit'],
      ['use a::b as c', 'bring b in under the name c'],
      ['&mut x as &mut dyn Trait', 'treat a value as a trait object'],
    ],
    example: { command: 'let g = counts as f32 / 16_384.0;', says: 'Turns the whole-number sensor reading into an f32 so it can be divided into a fraction of g.' },
    seeAlso: ['use', 'From'],
  },
  {
    name: 'unsafe',
    lang: 'rust',
    kind: 'keyword',
    official: 'Code or interfaces whose memory safety cannot be verified by the type system.',
    source: STD,
    when: 'Only for the few things the compiler cannot check: reading through a raw pointer, touching a static mut, calling C code or a function marked unsafe. It does not switch the borrow checker off; it means you promise the rules hold. Keep each unsafe block tiny and write a // SAFETY: comment saying why it is fine.',
    flags: [
      ['unsafe { ... }', 'a block where you take responsibility for the unchecked operations'],
      ['unsafe fn', 'a function callers may only call inside unsafe'],
      ['unsafe impl Send for T {}', 'promise a type is safe to send between threads'],
      ['unsafe extern "C" { ... }', 'declare C functions you will call'],
    ],
    example: { command: 'let first = unsafe { *samples.add(0) };', says: 'Reads the value a raw pointer points at. You must be sure the pointer is valid, because Rust cannot check it.' },
    seeAlso: ['extern', 'static'],
  },
  {
    name: 'match',
    lang: 'rust',
    kind: 'keyword',
    official: 'Control flow based on pattern matching.',
    source: STD,
    when: 'To choose what to do based on which shape a value has: each enum variant, a range of numbers, Some or None, Ok or Err. The compiler makes you cover every case, which is the point; _ catches whatever is left. Arms are tried top to bottom, so put the narrow cases first.',
    flags: [
      ['pattern => value,', 'one arm: if it matches, this is the result'],
      ['_', 'anything not matched above'],
      ['a..=b', 'a range of numbers'],
      ['x if cond', 'a guard: the arm only matches when cond is true'],
      ['A | B', 'either pattern'],
      ['e @ Pattern', 'match the pattern and also keep the whole value as e'],
    ],
    example: { command: 'let band = match alt_m {\n    0 => "on the pad",\n    1..=999 => "low",\n    1_000..=9_999 => "climbing",\n    _ => "high",\n};', says: 'Picks a label for the altitude in meters: 0 is on the pad, 1 to 999 is low, 1000 to 9999 is climbing, anything higher is high.' },
    seeAlso: ['enum', 'if', 'Option', 'Result'],
  },
  {
    name: 'return',
    lang: 'rust',
    kind: 'keyword',
    official: 'Returns a value from a function.',
    source: STD,
    when: 'To leave a function early, usually when an input is bad. At the end of a function you normally leave return out and just write the value with no semicolon. The ? operator is a short way to return an error early.',
    example: { command: 'if temp_c > 150.0 {\n    return Err(format!("sensor reads {} C, out of range", temp_c));\n}', says: 'Stops the function right there and hands back an error message when the reading is too high.' },
    seeAlso: ['fn', 'Err'],
  },
  {
    name: 'static',
    lang: 'rust',
    kind: 'keyword',
    official: 'A static item is a value which is valid for the entire duration of your program (a \'static lifetime).',
    source: STD,
    when: "For one value that lives at a fixed place for the whole run, such as a counter shared with an interrupt. A static mut can be changed but every use needs unsafe, so prefer an atomic or a Mutex. The lifetime 'static on a reference, as in &'static str, means the data lasts until the program ends.",
    flags: [
      ['static NAME: T = ...;', 'one global value, names written in CAPITALS'],
      ['static mut', 'a changeable global; every read and write is unsafe'],
      ["'static", 'a lifetime meaning lives for the whole program'],
    ],
    example: { command: 'static TICKS: AtomicU32 = AtomicU32::new(0);', says: 'Makes one global tick counter that any code, including an interrupt, can safely add to.' },
    seeAlso: ['const', 'unsafe', 'Mutex'],
  },
  {
    name: 'const',
    lang: 'rust',
    kind: 'keyword',
    official: 'Compile-time constants, compile-time blocks, compile-time evaluable functions, and raw pointers.',
    source: STD,
    when: 'For a fixed number with a name, like a conversion factor or a buffer size, that never changes. The value is worked out while compiling and pasted in wherever it is used, and the type must be written out. In *const T it means a raw pointer you may only read through.',
    flags: [
      ['const NAME: T = ...;', 'a named constant, written in CAPITALS'],
      ['const fn', 'a function that can also run while compiling'],
      ['*const T', 'a read-only raw pointer'],
    ],
    example: { command: 'const LBF_TO_N: f64 = 4.448_221_615_260_5;', says: 'Names the pound-force to newton factor so the code says LBF_TO_N instead of a bare number.' },
    seeAlso: ['static', 'let'],
  },
  {
    name: 'true',
    lang: 'rust',
    kind: 'keyword',
    official: 'A value of type bool representing logical true.',
    source: STD,
    when: 'For a yes/on/passed value. Rust bools are their own type, so true is not the number 1 and you cannot use a number where a bool is expected.',
    example: { command: 'let mut armed = true;', says: 'Makes a changeable flag that starts as true.' },
    seeAlso: ['false', 'if'],
  },
  {
    name: 'mod',
    lang: 'rust',
    kind: 'keyword',
    official: 'Organize code into modules.',
    source: STD,
    when: 'To split a program into named parts, each with its own private inside. mod frames { ... } holds the code right there; mod frames; on its own line tells Rust to load it from frames.rs. Items inside are private unless marked pub.',
    flags: [
      ['mod name { ... }', 'a module written inline'],
      ['mod name;', 'a module that lives in name.rs'],
      ['#[cfg(test)] mod tests', 'a module compiled only for cargo test'],
    ],
    example: { command: 'pub mod frames {\n    pub fn deg_to_rad(d: f64) -> f64 { d.to_radians() }\n}', says: 'Makes a module named frames with one public function, called from outside as frames::deg_to_rad.' },
    seeAlso: ['pub', 'use', 'super', 'crate'],
  },
  {
    name: 'type',
    lang: 'rust',
    kind: 'keyword',
    official: 'Define an alias for an existing type.',
    source: STD,
    when: 'To give a long type a short name, or, inside a trait, to name a type the implementer chooses, such as type Item = f64; in an Iterator. An alias is only a new name: it does not stop you mixing it up with the original type.',
    flags: [
      ['type Name = Type;', 'a shorter name for a type'],
      ['type Item = ...;', 'the associated type an Iterator hands out'],
      ['type Error = ...;', 'the error type TryFrom returns'],
    ],
    example: { command: 'type Reading = [f64; 3];', says: 'Lets you write Reading anywhere you mean an array of three f64s.' },
    seeAlso: ['trait', 'struct'],
  },
  {
    name: 'false',
    lang: 'rust',
    kind: 'keyword',
    official: 'A value of type bool representing logical false.',
    source: STD,
    when: 'For a no/off/failed value. It is not the same as 0, and Rust will not treat 0 or an empty value as false in an if.',
    example: { command: 'let mut valve_open = false;', says: 'Makes a changeable flag that starts as false.' },
    seeAlso: ['true', 'if'],
  },
  {
    name: 'enum',
    lang: 'rust',
    kind: 'keyword',
    official: 'A type that can be any one of several variants.',
    source: STD,
    when: 'When a value is exactly one of a few choices, like a flight mode or a command, and each choice can carry its own data. You use match to handle it, and the compiler tells you if you forgot a variant. Option and Result are enums too.',
    flags: [
      ['Variant', 'a choice with no data'],
      ['Variant(T)', 'a choice carrying values in order'],
      ['Variant { a: T }', 'a choice carrying named fields'],
    ],
    example: { command: 'enum Command {\n    Hold,\n    SetThrottle(f64),\n    Fire { engine: u8, ms: u32 },\n}', says: 'Defines a command that is either Hold, a throttle setting, or a burn of one engine for some milliseconds.' },
    seeAlso: ['match', 'struct', 'Option', 'Result'],
  },
  {
    name: 'Self',
    lang: 'rust',
    kind: 'keyword',
    official: 'The implementing type within a trait or impl block, or the current type within a type definition.',
    source: STD,
    when: 'Inside an impl or trait block, as a short way to name the type you are working on, most often in -> Self for a constructor. Do not confuse it with lowercase self, which is the value, not the type.',
    flags: [
      ['-> Self', 'returns a value of this type'],
      ['Self { ... }', 'build a value of this type'],
      ['Self::Item', 'an associated type of this type'],
    ],
    example: { command: 'fn new() -> Self {\n    Self { x: 0.0, y: 0.0, z: 0.0 }\n}', says: 'A constructor that returns a zero vector of whatever type the impl block is for.' },
    seeAlso: ['self', 'impl', 'trait'],
  },
  {
    name: 'loop',
    lang: 'rust',
    kind: 'keyword',
    official: 'Loop indefinitely.',
    source: STD,
    when: 'For a loop with no built-in end, such as the main loop of flight software, or a retry that stops with break. break can hand a value out: let n = loop { ... break n; };. Without a break it never ends, which on a microcontroller is exactly what you want.',
    example: { command: 'let tries = loop {\n    attempts += 1;\n    if link_up() { break attempts; }\n};', says: 'Keeps trying until the link comes up, then gives back how many attempts it took.' },
    seeAlso: ['break', 'while', 'for'],
  },
  {
    name: 'move',
    lang: 'rust',
    kind: 'keyword',
    official: 'Capture a closure’s environment by value.',
    source: STD,
    when: 'Before a closure that must own the variables it uses, most often one you give to thread::spawn, because the thread may outlive the function that made it. After the move you can no longer use those variables yourself; clone an Arc first if both sides need it.',
    example: { command: 'let c2 = Arc::clone(&config);\nlet h = thread::spawn(move || c2.len());', says: 'Gives the new thread its own handle to the shared config; the thread reads its length.' },
    seeAlso: ['Arc', 'FnOnce'],
  },
  {
    name: 'else',
    lang: 'rust',
    kind: 'keyword',
    official: 'What expression to evaluate when an if condition evaluates to false.',
    source: STD,
    when: 'After an if, for what to do when the condition is false. When the if gives back a value, the else is required and both branches must give the same type. It also ends a let-else, which must leave the function (return, break or panic) inside its block.',
    flags: [
      ['else if', 'check another condition'],
      ['let ... else { return }', 'let-else: unpack a value or leave early'],
    ],
    example: { command: 'let Some(tank) = tanks.get(0) else {\n    return;\n};', says: 'Takes the first tank if there is one; if the list is empty, leaves the function.' },
    seeAlso: ['if', 'match'],
  },
  {
    name: 'while',
    lang: 'rust',
    kind: 'keyword',
    official: 'Loop while a condition is upheld.',
    source: STD,
    when: 'To repeat while a condition stays true, when you do not know how many rounds it will take. while let Some(x) = ... keeps going until it gets None, which is handy for queues and iterators. Make sure something inside changes the condition, or it never stops.',
    flags: [['while let Some(x) = q.pop()', 'keep taking items until there are none']],
    example: { command: 'while let Some(cmd) = commands.pop() {\n    run(cmd);\n}', says: 'Takes commands off the end of the list and runs each one until the list is empty.' },
    seeAlso: ['loop', 'for', 'break'],
  },
  {
    name: 'dyn',
    lang: 'rust',
    kind: 'keyword',
    official: 'dyn is a prefix of a trait object’s type.',
    source: STD,
    when: 'When one list or parameter must hold different types that share a trait, like a Vec<Box<dyn Sensor>> holding a gyro and an accelerometer. The right method is chosen while running, which costs a little time and makes the pointer twice as big. A dyn value always sits behind a pointer: &dyn, &mut dyn or Box<dyn>.',
    flags: [
      ['Box<dyn Trait>', 'an owned value of any type with the trait'],
      ['&mut dyn Trait', 'a borrowed one you may change'],
    ],
    example: { command: 'let mut suite: Vec<Box<dyn Sensor>> = vec![Box::new(Gyro::new()), Box::new(Accel::new())];', says: 'Makes one list holding two different sensor types, each used through the Sensor trait.' },
    seeAlso: ['trait', 'Box', 'impl'],
  },
  {
    name: 'super',
    lang: 'rust',
    kind: 'keyword',
    official: 'The parent of the current module.',
    source: STD,
    when: 'In a path, to reach the module one level up, most often use super::*; at the top of a tests module so the tests see the code they test.',
    example: { command: '#[cfg(test)]\nmod tests {\n    use super::*;\n}', says: 'Lets the tests use every name from the module around them.' },
    seeAlso: ['crate', 'self', 'mod', 'use'],
  },
  {
    name: 'trait',
    lang: 'rust',
    kind: 'keyword',
    official: 'A common interface for a group of types.',
    source: STD,
    when: 'To describe what a group of types can do, such as a Sensor trait that every sensor type implements with its own read method. Code can then work with any type that has the trait. A trait can give a default body for a method, which types may keep or replace.',
    flags: [
      ['fn name(&self) -> T;', 'a method every implementer must write'],
      ['fn name(&self) { ... }', 'a default method they get for free'],
      ['T: Trait', 'a bound: only types with this trait are allowed'],
    ],
    example: { command: 'trait Sensor {\n    fn read(&mut self) -> Result<[f64; 3], SensorError>;\n}', says: 'Declares that every sensor type must have a read method returning three values or an error.' },
    seeAlso: ['impl', 'dyn', 'where'],
  },
  {
    name: 'async',
    lang: 'rust',
    kind: 'keyword',
    official: 'Returns a Future instead of blocking the current thread.',
    source: STD,
    when: 'For a function that spends time waiting, on a timer or a device, so other tasks can run meanwhile, as in the Embassy lessons. Calling an async fn does nothing yet; it only makes a future, and the work happens when something awaits it or an executor runs it.',
    flags: [
      ['async fn', 'a function that returns a future'],
      ['async { ... }', 'a block that becomes a future'],
    ],
    example: { command: 'async fn heartbeat(mut led: Output<\'static>) {\n    loop { led.toggle(); Timer::after_millis(500).await; }\n}', says: 'A task that blinks an LED every half second and lets other tasks run while it waits.' },
    seeAlso: ['await'],
  },
  {
    name: 'extern',
    lang: 'rust',
    kind: 'keyword',
    official: 'Link to or import external code.',
    source: STD,
    when: 'To call C code from Rust, or to let C call a Rust function, with extern "C" so both sides agree on how arguments are passed. Calling a C function is unsafe, because Rust cannot check what it does with your pointers.',
    flags: [
      ['extern "C" fn', 'a Rust function C code can call'],
      ['unsafe extern "C" { ... }', 'declare C functions Rust will call'],
      ['#[unsafe(no_mangle)]', 'keep the exact function name so the C linker finds it'],
    ],
    example: { command: '#[unsafe(no_mangle)]\npub extern "C" fn gnc_saturate(x: f64, lo: f64, hi: f64) -> f64 {\n    x.clamp(lo, hi)\n}', says: 'Makes a Rust function that C or C++ flight code can call by the name gnc_saturate.' },
    seeAlso: ['unsafe'],
  },
  {
    name: 'await',
    lang: 'rust',
    kind: 'keyword',
    official: 'Suspend execution until the result of a Future is ready.',
    source: STD,
    when: 'After a future, written with a dot (timer.await), inside an async function, to wait for it without blocking other tasks. It only works inside async code; a normal fn cannot await.',
    example: { command: 'Timer::after_millis(500).await;', says: 'Pauses this task for half a second while other tasks keep running.' },
    seeAlso: ['async'],
  },
  {
    name: 'break',
    lang: 'rust',
    kind: 'keyword',
    official: 'Exit early from a loop or labelled block.',
    source: STD,
    when: "To stop a loop right away. In a loop it can carry a value out (break n). With nested loops, a label like 'rows: lets you break out of the outer loop, not just the inner one.",
    flags: [
      ['break value', 'leave a loop and hand out a value'],
      ["break 'label", 'leave the loop with that label'],
    ],
    example: { command: 'match words.next() {\n    Some(w) => handle(w),\n    None => break,\n}', says: 'Handles the next word, or stops the loop when there are no words left.' },
    seeAlso: ['loop', 'while', 'for'],
  },
  {
    name: 'where',
    lang: 'rust',
    kind: 'keyword',
    official: 'Add constraints that must be upheld to use an item.',
    source: STD,
    when: 'To list trait bounds after a function signature instead of inside the angle brackets, when there are several or they are long. It means the same thing as writing them inline, just easier to read.',
    example: { command: "fn compare<A, B>(a: &mut A, b: &mut B) -> Option<f64>\nwhere\n    A: Sensor,\n    B: Sensor,\n{ ... }", says: 'Says both A and B must be sensor types before the function body starts.' },
    seeAlso: ['trait', 'impl'],
  },
  {
    name: 'crate',
    lang: 'rust',
    kind: 'keyword',
    official: 'A Rust binary or library.',
    source: STD,
    when: 'At the start of a path, crate means the root of your own project, so crate::gnc::guidance works from any file. A crate is also the name for one Rust package you build or download.',
    example: { command: 'use crate::gnc::frames::deg_to_rad as d2r;', says: 'Brings in deg_to_rad from your own crate\'s gnc::frames module under the short name d2r.' },
    seeAlso: ['super', 'mod', 'use'],
  },

  /* ── Standard macros ──────────────────────────────────────────────────── */
  {
    name: 'println!',
    lang: 'rust',
    kind: 'macro',
    official: 'Prints to the standard output, with a newline.',
    source: STD,
    when: 'To show a line of text on the screen: results, messages, values you are checking. The first argument is always a string with {} holes that get filled in. It panics if the output cannot be written, and on a microcontroller there is no screen for it, so embedded code uses rprintln! or defmt instead.',
    flags: [
      ['{}', 'fill in a value in its normal, user-facing form (Display)'],
      ['{:?}', 'fill in a value in its debugging form (Debug)'],
      ['{name}', 'fill in the variable called name directly'],
      ['{:.3}', 'show a decimal number with 3 digits after the point'],
      ['{:>13}', 'right-align in a space 13 characters wide'],
      ['{:#04x}', 'show as hexadecimal with 0x in front'],
    ],
    example: { command: 'println!("tick {} gyro_z = {:.3} rad/s", tick, rate);', says: 'Prints something like tick 7 gyro_z = 0.012 rad/s and moves to a new line.' },
    seeAlso: ['print!', 'eprintln!', 'format!', 'Display', 'Debug'],
  },
  {
    name: 'vec!',
    lang: 'rust',
    kind: 'macro',
    official: 'Creates a Vec containing the arguments.',
    source: STD,
    when: 'To make a Vec with starting values written out in one line. vec![0.0; n] makes n copies of one value. Every item must be the same type.',
    flags: [
      ['vec![a, b, c]', 'a Vec holding exactly these values'],
      ['vec![x; n]', 'a Vec holding n copies of x'],
    ],
    example: { command: 'let altitude_m = vec![1200.0, 1350.0, 1490.0];', says: 'Makes a Vec<f64> holding the three altitudes, in that order.' },
    seeAlso: ['Vec'],
  },
  {
    name: 'format!',
    lang: 'rust',
    kind: 'macro',
    official: 'Creates a String using interpolation of runtime expressions.',
    source: STD,
    when: 'When you want the text println! would print, but as a String you can keep, return or store. It uses the same {} holes. It allocates memory, so embedded code without a heap uses write! into a fixed-size string instead.',
    example: { command: 'let msg = format!("gimbal pitch {pitch_deg} deg, yaw {yaw_deg} deg");', says: 'Builds a String such as gimbal pitch 2.5 deg, yaw -1 deg without printing it.' },
    seeAlso: ['println!', 'write!', 'String'],
  },
  {
    name: 'assert_eq!',
    lang: 'rust',
    kind: 'macro',
    official: 'Asserts that two expressions are equal to each other (using PartialEq).',
    source: STD,
    when: 'In tests, to check that what you got equals what you expected. When they differ it panics and prints both values, which is why it is better than assert!(a == b). Do not use it on floats that come from arithmetic; compare with a tolerance instead.',
    flags: [
      ['assert_eq!(got, want)', 'the two values to compare; both need Debug and PartialEq'],
      [', "message {x}"', 'an optional extra message shown on failure'],
    ],
    example: { command: 'assert_eq!(parse_kpa("2.5 bar"), Ok(250.0));', says: 'Passes if the parser turns 2.5 bar into 250 kPa; otherwise the test fails and shows both values.' },
    seeAlso: ['assert!', 'debug_assert!', 'PartialEq'],
  },
  {
    name: 'write!',
    lang: 'rust',
    kind: 'macro',
    official: 'Writes formatted data into a buffer.',
    source: STD,
    when: 'Mostly inside impl Display, to write your type\'s text into the Formatter f. It also writes into a fixed-size heapless String on a microcontroller. It returns a Result: in fmt it is passed on, elsewhere you must handle it, because the buffer can be full.',
    flags: [
      ['write!(f, ...)', 'the destination first, then a format string like println!'],
    ],
    example: { command: 'write!(f, "({:.3}, {:.3}, {:.3})", self.x, self.y, self.z)', says: 'Inside Display for Vec3, writes the vector as (1.000, 0.000, -2.500).' },
    seeAlso: ['format!', 'Display', 'println!'],
  },
  {
    name: 'assert!',
    lang: 'rust',
    kind: 'macro',
    official: 'Asserts that a boolean expression is true at runtime.',
    source: STD,
    when: 'In tests, and in normal code to stop straight away if something that must be true is not. If the condition is false it panics. It is checked in release builds too; use debug_assert! for checks that should only run while developing.',
    flags: [
      ['assert!(cond)', 'panic if cond is false'],
      ['assert!(cond, "msg {x}")', 'panic with your own message'],
    ],
    example: { command: 'assert!(max_step > 0.0, "max_step must be positive, got {max_step}");', says: 'Stops the program with that message if max_step is zero or negative.' },
    seeAlso: ['assert_eq!', 'debug_assert!', 'matches!'],
  },
  {
    name: 'print!',
    lang: 'rust',
    kind: 'macro',
    official: 'Prints to the standard output.',
    source: STD,
    when: 'Like println! but without the new line at the end, so several prints end up on one line. The text may not show until a newline is printed, because output is buffered.',
    example: { command: 'for (k, v) in &counts {\n    print!("{k}={v} ");\n}\nprintln!();', says: 'Prints every key and count on one line, then ends the line.' },
    seeAlso: ['println!', 'eprintln!'],
  },
  {
    name: 'matches!',
    lang: 'rust',
    kind: 'macro',
    official: 'Returns whether the given expression matches the provided pattern.',
    source: STD,
    when: 'When you only need a yes or no about which variant a value is, without pulling data out. It is handy in tests for errors that cannot be compared with ==.',
    example: { command: 'assert!(matches!(parse_hex_line("00 ZZ"), Err(FrameError::BadHex(_))));', says: 'Passes if parsing the bad line gives a BadHex error, whatever is inside it.' },
    seeAlso: ['match', 'assert!'],
  },
  {
    name: 'debug_assert!',
    lang: 'rust',
    kind: 'macro',
    official: 'Asserts that a boolean expression is true at runtime.',
    source: STD,
    when: 'For a check you want while developing and testing but not in the finished, fast build. It runs in debug builds and is removed in cargo build --release, so never put code with side effects inside it.',
    example: { command: 'debug_assert!(dt_s > 0.0, "time step must be positive");', says: 'In a debug build, panics with that message if the time step is not positive; in release it does nothing.' },
    seeAlso: ['assert!', 'cfg!'],
  },
  {
    name: 'eprintln!',
    lang: 'rust',
    kind: 'macro',
    official: 'Prints to the standard error, with a newline.',
    source: STD,
    when: 'For error and warning messages, so they go to standard error and stay separate from the program\'s real output, even when that output is sent to a file.',
    example: { command: 'eprintln!("CRASH RECORD: {msg} at {place}");', says: 'Prints the crash message to standard error, not standard output.' },
    seeAlso: ['println!'],
  },
  {
    name: 'cfg!',
    lang: 'rust',
    kind: 'macro',
    official: 'Evaluates boolean combinations of configuration flags at compile-time.',
    source: STD,
    when: 'To ask, in ordinary code, which kind of build this is, for example whether debug checks are on. It gives true or false, but both branches of your code are still compiled; to leave code out completely, use the #[cfg(...)] attribute.',
    example: { command: 'println!("debug checks = {}", cfg!(debug_assertions));', says: 'Prints true in a normal debug build and false in a release build.' },
    seeAlso: ['debug_assert!'],
  },

  /* ── Macros from other crates ─────────────────────────────────────────── */
  {
    name: 'prop_assert!',
    lang: 'rust',
    kind: 'macro',
    official: 'Similar to assert! from std, but returns a test failure instead of panicking if the condition fails.',
    source: 'proptest crate documentation',
    when: 'Inside a proptest! test, instead of assert!. Because it returns a failure rather than panicking, proptest can keep trying smaller inputs and report the smallest one that breaks your rule.',
    example: { command: 'prop_assert!(w > -180.0 && w <= 180.0);', says: 'Fails the property test, and shows the input, if the wrapped angle is outside -180 to 180.' },
    seeAlso: ['proptest!', 'assert!'],
  },
  {
    name: 'rprintln!',
    lang: 'rust',
    kind: 'macro',
    official: 'Prints to the print RTT channel, with a newline. Works just like the standard println.',
    source: 'rtt-target crate documentation',
    when: 'On a microcontroller, to send text to your laptop through the debug probe. Call rtt_init_print!() once first, or the text is quietly thrown away. The chip does the formatting itself, which costs flash space and time.',
    example: { command: 'rprintln!("boot: attitude board v{}", 3u8);', says: 'Shows boot: attitude board v3 in the probe tool on your laptop.' },
    seeAlso: ['rtt_init_print!', 'println!', 'info!'],
  },
  {
    name: 'proptest!',
    lang: 'rust',
    kind: 'macro',
    official: 'Easily define proptest tests.',
    source: 'proptest crate documentation',
    when: 'To test a rule that should hold for every input, not just a few you picked. It runs each test with random values, 256 cases by default, and if one fails it shrinks it to a small example. The crate goes in [dev-dependencies].',
    flags: [
      ['a: u32', 'any random u32'],
      ['a in -1.0e6f64..1.0e6', 'random values from this range'],
      ['#[test]', 'written on each test inside the block'],
    ],
    example: { command: 'proptest! {\n    #[test]\n    fn midpoint_lies_between(a: u32, b: u32) {\n        let m = mid_tick(a, b);\n        prop_assert!(a.min(b) <= m && m <= a.max(b));\n    }\n}', says: 'Checks with hundreds of random pairs that the midpoint always lies between the two ticks.' },
    seeAlso: ['prop_assert!', 'assert!'],
  },
  {
    name: 'info!',
    aliases: ['defmt::info!'],
    lang: 'rust',
    kind: 'macro',
    official: 'Logs data at info level.',
    source: 'defmt crate documentation',
    when: 'In embedded code using defmt, for normal milestones like boot complete. defmt sends only a small number and the raw values; your laptop does the formatting, so it uses far less flash than rprintln!. Messages below the level set in DEFMT_LOG are left out of the build.',
    example: { command: 'defmt::info!("tick {} gyro_z = {} rad/s", tick, rate);', says: 'Logs the tick and rate at info level; probe-rs shows the finished line on your laptop.' },
    seeAlso: ['warn!', 'rprintln!'],
  },
  {
    name: 'bail!',
    aliases: ['anyhow::bail!'],
    lang: 'rust',
    kind: 'macro',
    official: 'Return early with an error.',
    source: 'anyhow crate documentation',
    when: 'In a function that returns anyhow::Result, to stop and return an error made from a message in one line. It is short for return Err(anyhow!(...)), so it leaves the function right away.',
    example: { command: 'if frames.is_empty() {\n    bail!("{path} holds no frames");\n}', says: 'Leaves the function with the error "log.bin holds no frames" when the file had no frames.' },
    seeAlso: ['return', 'Err', 'Result'],
  },
  {
    name: 'criterion_group!',
    lang: 'rust',
    kind: 'macro',
    official: 'Macro used to define a function group for the benchmark harness; see the criterion_main! macro for more details.',
    source: 'criterion crate documentation',
    when: 'In a benchmark file under benches/, to bundle your benchmark functions under one name. It does nothing alone; criterion_main! must run the group.',
    flags: [['criterion_group!(name, f1, f2)', 'the group name, then the benchmark functions in it']],
    example: { command: 'criterion_group!(benches, bench_dispatch);', says: 'Makes a group called benches holding the bench_dispatch benchmark.' },
    seeAlso: ['criterion_main!'],
  },
  {
    name: 'criterion_main!',
    lang: 'rust',
    kind: 'macro',
    official: 'Macro which expands to a benchmark harness.',
    source: 'criterion crate documentation',
    when: 'Last line of a Criterion benchmark file: it writes the main function that runs your groups when you type cargo bench. The bench also needs harness = false in Cargo.toml, or Rust\'s own test runner gets in the way.',
    example: { command: 'criterion_main!(benches);', says: 'Creates main so cargo bench runs every benchmark in the benches group.' },
    seeAlso: ['criterion_group!'],
  },
  {
    name: 'fuzz_target!',
    lang: 'rust',
    kind: 'macro',
    official: 'Define a fuzz target.',
    source: 'libfuzzer-sys crate documentation',
    when: 'With cargo fuzz, to hand a function millions of random byte strings looking for one that makes it panic or crash. Your code should return errors for bad input, never panic, and the fuzzer finds the places where it does not.',
    example: { command: 'fuzz_target!(|data: &[u8]| {\n    let _ = frame2::parse_frame_v2(data);\n});', says: 'Feeds random bytes to the frame parser; any panic is saved as a crash file you can replay.' },
    seeAlso: ['proptest!'],
  },
  {
    name: 'rtt_init_print!',
    lang: 'rust',
    kind: 'macro',
    official: 'Initializes RTT with a single up channel and sets it as the print channel for the printing macros.',
    source: 'rtt-target crate documentation',
    when: 'Once, at the start of main on a microcontroller, before any rprintln!. It sets up a 1024-byte buffer in RAM that the debug probe reads from.',
    example: { command: 'rtt_init_print!();', says: 'Sets up the channel so later rprintln! lines reach your laptop.' },
    seeAlso: ['rprintln!'],
  },
  {
    name: 'warn!',
    aliases: ['defmt::warn!'],
    lang: 'rust',
    kind: 'macro',
    official: 'Logs data at warn level.',
    source: 'defmt crate documentation',
    when: 'In embedded code using defmt, for something unusual that is not yet a failure, like a reading above its limit. It ranks above info!, so it still shows when DEFMT_LOG=warn hides the info! lines.',
    example: { command: 'defmt::warn!("rate above limit: {}", rate);', says: 'Logs the rate as a warning, shown on your laptop by probe-rs.' },
    seeAlso: ['info!', 'rprintln!'],
  },
  {
    name: 'assert_eq_size!',
    lang: 'rust',
    kind: 'macro',
    official: 'Asserts that types are equal in size.',
    source: 'static_assertions crate documentation',
    when: 'To make the build fail if a type is not the exact size you need, for example a telemetry frame that must be a set number of bytes. The check happens while compiling and costs nothing when running. Padding the compiler adds counts toward the size.',
    example: { command: 'assert_eq_size!(Frame, [u8; FRAME_BYTES]);', says: 'Stops the build unless Frame takes exactly FRAME_BYTES bytes.' },
    seeAlso: ['const_assert!'],
  },
  {
    name: 'const_assert!',
    lang: 'rust',
    kind: 'macro',
    official: 'Asserts that constant expressions evaluate to true.',
    source: 'static_assertions crate documentation',
    when: 'To check a rule about constants while compiling, such as a queue depth being a power of two. If it is false the build fails, so the mistake never reaches the rocket. Only constants and const fn calls can go inside.',
    example: { command: 'const_assert!(QUEUE_DEPTH.is_power_of_two());', says: 'Stops the build if QUEUE_DEPTH is not 2, 4, 8, 16 and so on.' },
    seeAlso: ['assert_eq_size!', 'const'],
  },

  /* ── Prelude and common standard types, traits and variants ───────────── */
  {
    name: 'String',
    aliases: ['std::string::String'],
    lang: 'rust',
    kind: 'type',
    official: 'A UTF-8–encoded, growable string.',
    source: STD,
    when: 'For text you own and may change or build up, like a log message. A plain "text" literal is a &str, a borrowed view; turn it into a String with String::from or .to_string(). You cannot index a String with s[0], because one character may take several bytes.',
    flags: [
      ['String::from("...")', 'make a String from a literal'],
      ['String::new()', 'an empty String'],
      ['.push_str(s)', 'add text on the end'],
      ['&s / .as_str()', 'borrow it as a &str'],
    ],
    example: { command: 'let backup = String::from("IMU-B");', says: 'Makes an owned, changeable String holding IMU-B.' },
    seeAlso: ['format!', 'Vec'],
  },
  {
    name: 'Vec',
    aliases: ['std::vec::Vec'],
    lang: 'rust',
    kind: 'type',
    official: 'A contiguous growable array type, written as Vec<T>, short for ‘vector’.',
    source: STD,
    when: 'For a list of values of one type that can grow or shrink. Reading v[i] past the end panics; use v.get(i) to get an Option instead. Pushing may move the whole list in memory, so Rust will not let you keep a reference into it while you push.',
    flags: [
      ['Vec<T>', 'the item type in angle brackets'],
      ['Vec::new()', 'an empty Vec'],
      ['Vec::with_capacity(n)', 'an empty Vec with room reserved for n items'],
      ['.push(x) / .pop()', 'add to or take from the end'],
    ],
    example: { command: 'let mut log: Vec<f64> = Vec::new();\nlog.push(101.3);', says: 'Makes an empty list of f64s and adds one pressure reading to it.' },
    seeAlso: ['vec!', 'String', 'Box'],
  },
  {
    name: 'Ok',
    aliases: ['Result::Ok'],
    lang: 'rust',
    kind: 'function',
    official: 'Contains the success value',
    source: STD,
    when: 'To wrap the answer of a function that returns a Result when things went well, and as the pattern that matches success in a match. A function with nothing to report returns Ok(()).',
    example: { command: 'match parse_frame(&bytes) {\n    Ok((apid, payload)) => println!("ok: APID {apid}, payload {payload:?}"),\n    Err(e) => println!("dropped: {e}"),\n}', says: 'Prints the frame\'s fields when parsing worked, or why the frame was dropped.' },
    seeAlso: ['Err', 'Result'],
  },
  {
    name: 'Result',
    aliases: ['std::result::Result'],
    lang: 'rust',
    kind: 'type',
    official: 'Result is a type that represents either success (Ok) or failure (Err).',
    source: STD,
    when: 'As the return type of anything that can fail, like parsing or reading a sensor, instead of crashing. The caller has to deal with the error: match on it, pass it up with ?, or call unwrap, which panics on Err. The compiler warns if you ignore a Result.',
    flags: [
      ['Result<T, E>', 'T is the success value, E the error'],
      ['?', 'give back the Ok value, or return the Err from this function straight away'],
      ['.unwrap() / .expect("msg")', 'take the Ok value or panic'],
    ],
    example: { command: 'fn parse_kpa(s: &str) -> Result<f64, PressureError> { ... }', says: 'Promises to return either a pressure in kPa or a PressureError saying what was wrong.' },
    seeAlso: ['Ok', 'Err', 'Option', 'match'],
  },
  {
    name: 'Err',
    aliases: ['Result::Err'],
    lang: 'rust',
    kind: 'function',
    official: 'Contains the error value',
    source: STD,
    when: 'To wrap the reason something failed, in a function that returns a Result, and as the pattern that matches failure in a match. Use a proper error type, often an enum, so callers can tell the failures apart.',
    example: { command: 'return Err(FrameError::UnknownApid(apid));', says: 'Leaves the function reporting that the frame had an APID nobody knows.' },
    seeAlso: ['Ok', 'Result', 'bail!'],
  },
  {
    name: 'Some',
    aliases: ['Option::Some'],
    lang: 'rust',
    kind: 'function',
    official: 'Some value of type T.',
    source: STD,
    when: 'To wrap a value in an Option when there is one, and as the pattern that pulls it out in match, if let or while let.',
    example: { command: 'if let Some(d) = over_by {\n    println!("over the limit by {d} bar");\n}', says: 'Prints the amount only if there is one; does nothing when over_by is None.' },
    seeAlso: ['None', 'Option'],
  },
  {
    name: 'Debug',
    aliases: ['std::fmt::Debug', 'fmt::Debug'],
    lang: 'rust',
    kind: 'type',
    official: '? formatting.',
    source: STD,
    when: 'So a value can be printed with {:?} while you are checking your code. You almost always get it with #[derive(Debug)] rather than writing it. assert_eq! and unwrap need it to show values when they fail.',
    flags: [
      ['#[derive(Debug)]', 'have the compiler write it'],
      ['{:?}', 'print on one line'],
      ['{:#?}', 'print spread over several lines, easier to read for big structs'],
    ],
    example: { command: '#[derive(Debug)]\nstruct Vec3 { x: f64, y: f64, z: f64 }\nprintln!("{:?}", v);', says: 'Prints Vec3 { x: 1.0, y: 0.0, z: -2.5 }.' },
    seeAlso: ['Display', 'println!'],
  },
  {
    name: 'Box',
    aliases: ['std::boxed::Box'],
    lang: 'rust',
    kind: 'type',
    official: 'A pointer type that uniquely owns a heap allocation of type T.',
    source: STD,
    when: 'To put a value on the heap: for a list of different types behind one trait (Vec<Box<dyn Sensor>>), or for a type that contains itself, like a command that holds another command. The value is freed when the Box is dropped. Most bare-metal code has no heap, so no Box.',
    flags: [
      ['Box::new(x)', 'move x onto the heap'],
      ['Box<dyn Trait>', 'an owned value of any type with that trait'],
    ],
    example: { command: 'Box::new(Command::Fire { engine: 2, ms: 800 })', says: 'Makes a heap copy of the fire command that can sit inside another command or a list of trait objects.' },
    seeAlso: ['dyn', 'Rc', 'Vec'],
  },
  {
    name: 'RefCell',
    aliases: ['std::cell::RefCell', 'core::cell::RefCell'],
    lang: 'rust',
    kind: 'type',
    official: 'A mutable memory location with dynamically checked borrow rules',
    source: STD,
    when: 'When something shared must still be changed, such as a log several parts write to. It checks the borrowing rules while running instead of while compiling: asking for borrow_mut while another borrow is still alive panics. Not for threads; use Mutex there.',
    flags: [
      ['RefCell::new(x)', 'wrap a value'],
      ['.borrow()', 'read it'],
      ['.borrow_mut()', 'change it; panics if already borrowed'],
      ['Rc<RefCell<T>>', 'shared by several owners and changeable'],
    ],
    example: { command: 'let log = Rc::new(RefCell::new(Vec::new()));\nlog.borrow_mut().push(String::from("boot"));', says: 'Makes a shared, changeable log and adds boot to it.' },
    seeAlso: ['Cell', 'Rc', 'Mutex'],
  },
  {
    name: 'None',
    aliases: ['Option::None'],
    lang: 'rust',
    kind: 'constant',
    official: 'No value.',
    source: STD,
    when: 'To say there is no value, where other languages use null. Rust makes you check for it before you use the value inside, so a missing value cannot crash you by surprise; calling unwrap on None, though, panics.',
    example: { command: 'let operator_limit: Option<f64> = None;', says: 'Records that the operator has not set a limit yet.' },
    seeAlso: ['Some', 'Option'],
  },
  {
    name: 'Option',
    aliases: ['std::option::Option'],
    lang: 'rust',
    kind: 'type',
    official: 'The Option type.',
    source: STD,
    when: 'For a value that might be missing: the first reading above a limit, an item looked up by key, a setting nobody filled in. It is either Some(value) or None, and you must handle both. unwrap panics on None; prefer match, if let, unwrap_or or ?.',
    flags: [
      ['Option<T>', 'maybe a T'],
      ['.unwrap_or(x)', 'the value, or x if there is none'],
      ['?', 'inside a function returning Option: give back the value, or return None'],
    ],
    example: { command: 'fn first_above(p: &[f64], limit: f64) -> Option<usize> { ... }', says: 'Returns the position of the first pressure above the limit, or None if no reading is.' },
    seeAlso: ['Some', 'None', 'Result', 'match'],
  },
  {
    name: 'PartialEq',
    aliases: ['std::cmp::PartialEq'],
    lang: 'rust',
    kind: 'type',
    official: 'Trait for comparisons using the equality operator.',
    source: STD,
    when: 'So values of your type can be compared with == and !=, and checked with assert_eq!. Usually you derive it. f64 has PartialEq but not Eq, because NaN is not equal even to itself.',
    example: { command: '#[derive(Debug, Clone, Copy, PartialEq)]\nenum Mode { Safe, Ascent }', says: 'Lets you write if mode == Mode::Safe.' },
    seeAlso: ['Eq', 'PartialOrd', 'assert_eq!'],
  },
  {
    name: 'Clone',
    aliases: ['std::clone::Clone'],
    lang: 'rust',
    kind: 'type',
    official: 'A common trait that allows explicit creation of a duplicate value.',
    source: STD,
    when: 'When you need a second, independent copy of a value, so you call .clone() on purpose. For a String or Vec that copies all the data, which can be slow; for an Rc or Arc it only adds one to the owner count.',
    example: { command: 'let backup = plan.clone();', says: 'Makes a full, separate copy of plan, so changing one does not change the other.' },
    seeAlso: ['Copy', 'Rc'],
  },
  {
    name: 'Copy',
    aliases: ['std::marker::Copy'],
    lang: 'rust',
    kind: 'type',
    official: 'Types whose values can be duplicated simply by copying bits.',
    source: STD,
    when: 'For small plain values like numbers, bools and a Vec3 of three f64s: assigning or passing them copies them instead of moving them, so the original stays usable. You can only derive it together with Clone, and not for types holding a String, Vec or Box.',
    example: { command: '#[derive(Clone, Copy)]\nstruct Vec3 { x: f64, y: f64, z: f64 }', says: 'After let b = a;, both a and b can still be used.' },
    seeAlso: ['Clone'],
  },
  {
    name: 'Rc',
    aliases: ['std::rc::Rc'],
    lang: 'rust',
    kind: 'type',
    official: 'A single-threaded reference-counting pointer. ‘Rc’ stands for ‘Reference Counted’.',
    source: STD,
    when: 'When several parts of a program need to own the same value and none is clearly in charge. Rc::clone only adds an owner; the value is freed when the last owner goes away. It cannot cross threads (use Arc), and it gives read-only access unless you put a RefCell inside.',
    flags: [
      ['Rc::new(x)', 'the first owner'],
      ['Rc::clone(&rc)', 'one more owner of the same value'],
      ['Rc::strong_count(&rc)', 'how many owners there are right now'],
    ],
    example: { command: 'let power = Subsystem { name: "EPS", log: Rc::clone(&log) };', says: 'Gives the power subsystem a share of the same log; the owner count goes up by one.' },
    seeAlso: ['Arc', 'RefCell', 'Box'],
  },
  {
    name: 'Arc',
    aliases: ['std::sync::Arc'],
    lang: 'rust',
    kind: 'type',
    official: 'A thread-safe reference-counting pointer. ‘Arc’ stands for ‘Atomically Reference Counted’.',
    source: STD,
    when: 'Like Rc, but for sharing a value between threads. Clone the Arc and move the clone into each thread. It only allows reading; to change the value from several threads put a Mutex or RwLock inside.',
    flags: [
      ['Arc::new(x)', 'the first owner'],
      ['Arc::clone(&a)', 'one more owner, usually for another thread'],
      ['Arc<Mutex<T>>', 'shared between threads and changeable'],
    ],
    example: { command: 'let packets = Arc::new(Mutex::new(0u64));\nlet counter = Arc::clone(&packets);', says: 'Makes a packet counter that can be shared, and a second handle to give to a worker thread.' },
    seeAlso: ['Rc', 'Mutex', 'RwLock', 'Send', 'move'],
  },
  {
    name: 'Drop',
    aliases: ['std::ops::Drop'],
    lang: 'rust',
    kind: 'type',
    official: 'Custom code within the destructor.',
    source: STD,
    when: 'To run clean-up code automatically when a value goes away, like closing a valve or turning a heater off. Rust calls drop for you at the end of the scope, in reverse order of creation. You never call value.drop() yourself; use drop(value) to end it early.',
    example: { command: 'impl Drop for Valve {\n    fn drop(&mut self) {\n        println!("closing {}", self.name);\n    }\n}', says: 'Prints closing and the valve name whenever a Valve goes out of scope.' },
    seeAlso: ['Box'],
  },
  {
    name: 'Default',
    aliases: ['std::default::Default'],
    lang: 'rust',
    kind: 'type',
    official: 'A trait for giving a type a useful default value.',
    source: STD,
    when: 'To give a type a starting value: zero for numbers, empty for strings and lists, and whatever you choose for your own types. With ..Default::default() you set only the fields you care about and take the rest from the default.',
    flags: [
      ['#[derive(Default)]', 'every field gets its own default'],
      ['impl Default for T', 'choose the defaults yourself'],
      ['..Default::default()', 'fill in all the other fields'],
    ],
    example: { command: 'let cfg = FilterConfig { gain: 0.2, ..Default::default() };', says: 'Makes a filter config with gain 0.2 and every other setting at its default.' },
    seeAlso: ['struct'],
  },
  {
    name: 'Cell',
    aliases: ['std::cell::Cell'],
    lang: 'rust',
    kind: 'type',
    official: 'A mutable memory location.',
    source: STD,
    when: 'To change a small Copy value, like a counter, even through a shared & reference. You get and set the whole value; you never borrow what is inside, so it can never panic. Use RefCell for bigger things like a Vec.',
    flags: [
      ['Cell::new(x)', 'wrap a value'],
      ['.get()', 'copy the value out'],
      ['.set(x)', 'replace the value'],
    ],
    example: { command: 'let count = Cell::new(0u32);\ncount.set(count.get() + 1);', says: 'Adds one to the counter without needing mut on count.' },
    seeAlso: ['RefCell'],
  },
  {
    name: 'BTreeMap',
    aliases: ['std::collections::BTreeMap'],
    lang: 'rust',
    kind: 'type',
    official: 'An ordered map based on a B-Tree.',
    source: STD,
    when: 'For a map from keys to values when you want to walk through it in key order, such as readings by time. It is a little slower than a HashMap for single lookups but always gives the same, sorted order.',
    flags: [
      ['BTreeMap::new()', 'an empty map'],
      ['.insert(k, v)', 'store v under key k'],
      ['.range(a..b)', 'visit only the keys in a range'],
    ],
    example: { command: 'let mut log: BTreeMap<u32, f64> = BTreeMap::new();\nlog.insert(120, 101.3);', says: 'Stores a pressure under time 120 s; looping over log gives times in order.' },
    seeAlso: ['HashMap', 'Ord'],
  },
  {
    name: 'Mutex',
    aliases: ['std::sync::Mutex'],
    lang: 'rust',
    kind: 'type',
    official: 'A mutual exclusion primitive useful for protecting shared data',
    source: STD,
    when: 'To let several threads change the same data one at a time. lock() waits for your turn and gives a guard; the lock is released when the guard goes away. Holding a lock for long, or locking two in different orders, can freeze your program. On a microcontroller the lessons use critical_section::Mutex instead.',
    flags: [
      ['Mutex::new(x)', 'wrap the shared data'],
      ['.lock()', 'wait for the lock; returns a Result you usually unwrap'],
    ],
    example: { command: '*counter.lock().unwrap() += 1;', says: 'Waits for the lock, adds one to the shared count, and releases the lock at the end of the line.' },
    seeAlso: ['Arc', 'RwLock', 'RefCell'],
  },
  {
    name: 'Display',
    aliases: ['std::fmt::Display', 'fmt::Display'],
    lang: 'rust',
    kind: 'type',
    official: 'Format trait for an empty format, {}.',
    source: STD,
    when: 'So your type can be printed with plain {} in a clean form meant for people, and turned into text with .to_string(). Unlike Debug it cannot be derived; you write fmt yourself, usually with write!. Error types implement it to give their message.',
    flags: [['fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result', 'the one method you write']],
    example: { command: 'impl fmt::Display for Vec3 {\n    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {\n        write!(f, "({:.3}, {:.3}, {:.3})", self.x, self.y, self.z)\n    }\n}', says: 'Now println!("{v}") prints the vector as (1.000, 0.000, -2.500).' },
    seeAlso: ['Debug', 'write!', 'println!'],
  },
  {
    name: 'Send',
    aliases: ['std::marker::Send'],
    lang: 'rust',
    kind: 'type',
    official: 'Types that can be transferred across thread boundaries.',
    source: STD,
    when: 'You rarely write it, but you meet it in errors: thread::spawn only accepts values that are Send. Rc and RefCell are not Send, which is why the compiler stops you sending them to another thread; use Arc and Mutex.',
    example: { command: "F: FnOnce() -> T + Send + 'static,", says: 'Part of thread::spawn: the closure must be safe to send to another thread and own all its data.' },
    seeAlso: ['Arc', 'Mutex'],
  },
  {
    name: 'HashMap',
    aliases: ['std::collections::HashMap'],
    lang: 'rust',
    kind: 'type',
    official: 'A hash map implemented with quadratic probing and SIMD lookup.',
    source: STD,
    when: 'For fast lookup of values by key, like counts per sensor name. Its order when you loop over it is random and changes between runs, so use a BTreeMap when order matters.',
    flags: [
      ['HashMap::new()', 'an empty map'],
      ['.insert(k, v) / .get(&k)', 'store and look up'],
      ['.entry(k).or_insert(0)', 'get the value for k, adding 0 first if it is missing'],
    ],
    example: { command: 'let mut counts: HashMap<&str, u32> = HashMap::new();\n*counts.entry("gyro").or_insert(0) += 1;', says: 'Counts one more message from the gyro, starting at 0 the first time.' },
    seeAlso: ['BTreeMap', 'Hash', 'Eq'],
  },
  {
    name: 'From',
    aliases: ['std::convert::From'],
    lang: 'rust',
    kind: 'type',
    official: 'Used to do value-to-value conversions while consuming the input value. It is the reciprocal of Into.',
    source: STD,
    when: 'To say how to turn one type into another, like Degrees into Radians, or a library error into your own error type. Once From is written you also get .into() for free, and ? uses it to convert errors automatically. It must never fail; use TryFrom for conversions that can.',
    example: { command: 'impl From<Degrees> for Radians {\n    fn from(d: Degrees) -> Self { Radians(d.0.to_radians()) }\n}', says: 'Lets you write Radians::from(Degrees(90.0)) or let r: Radians = d.into();.' },
    seeAlso: ['as', 'Result'],
  },
  {
    name: 'Iterator',
    aliases: ['std::iter::Iterator'],
    lang: 'rust',
    kind: 'type',
    official: 'A trait for dealing with iterators.',
    source: STD,
    when: 'Anything you can walk through one item at a time: .iter() on a Vec, a range, the lines of a file. You get map, filter, sum and many more for free by writing just next. Iterators are lazy, so nothing happens until something like for, sum or collect uses them.',
    flags: [
      ['type Item = T;', 'what each step hands out'],
      ['fn next(&mut self) -> Option<Self::Item>', 'the next item, or None when finished'],
    ],
    example: { command: 'impl Iterator for TimeGrid {\n    type Item = f64;\n    fn next(&mut self) -> Option<f64> { ... }\n}', says: 'Makes TimeGrid usable in a for loop, handing out one time value per step.' },
    seeAlso: ['for', 'Option', 'type'],
  },
  {
    name: 'FnOnce',
    aliases: ['std::ops::FnOnce'],
    lang: 'rust',
    kind: 'type',
    official: 'The version of the call operator that takes a by-value receiver.',
    source: STD,
    when: 'As a bound for a closure you will call only once, which may use up what it captured. It is the most permissive of the three, so thread::spawn asks for it. Calling it twice is a compile error.',
    example: { command: 'fn run_once<F: FnOnce() -> Vec<String>>(f: F) -> Vec<String> { f() }', says: 'Accepts any closure that produces a list of strings and calls it exactly once.' },
    seeAlso: ['FnMut', 'Fn', 'move'],
  },
  {
    name: 'RwLock',
    aliases: ['std::sync::RwLock'],
    lang: 'rust',
    kind: 'type',
    official: 'A reader-writer lock',
    source: STD,
    when: 'Like a Mutex, but many threads may read at the same time; only writing needs to be alone. Good for data read often and changed rarely, such as a target attitude. A writer waits until every reader has finished.',
    flags: [
      ['.read()', 'shared read access'],
      ['.write()', 'exclusive write access'],
    ],
    example: { command: 'let target_attitude = RwLock::new([0.0f64, 0.0, 0.0]);\nlet t = target_attitude.read().unwrap();', says: 'Makes a shared attitude target and takes a read lock to look at it.' },
    seeAlso: ['Mutex', 'Arc'],
  },
  {
    name: 'Fn',
    aliases: ['std::ops::Fn'],
    lang: 'rust',
    kind: 'type',
    official: 'The version of the call operator that takes an immutable receiver.',
    source: STD,
    when: 'As a bound for a closure you may call many times that only reads what it captured. It is the strictest of the three, so the fewest closures fit it. Written with its arguments and result, like Fn(f64) -> f64.',
    example: { command: 'fn apply_twice<F: Fn(f64) -> f64>(f: F, x: f64) -> f64 { f(f(x)) }', says: 'Calls the closure on x, then again on the result; apply_twice(|v| v * 2.0, 3.0) gives 12.' },
    seeAlso: ['FnMut', 'FnOnce'],
  },
  {
    name: 'FnMut',
    aliases: ['std::ops::FnMut'],
    lang: 'rust',
    kind: 'type',
    official: 'The version of the call operator that takes a mutable receiver.',
    source: STD,
    when: 'As a bound for a closure you call several times that changes something it captured, like a counter. The parameter holding it must be declared mut.',
    example: { command: 'fn call_three_times<F: FnMut()>(mut f: F) { f(); f(); f(); }', says: 'Calls the closure three times, letting it update its captured state each time.' },
    seeAlso: ['Fn', 'FnOnce'],
  },
  {
    name: 'Eq',
    aliases: ['std::cmp::Eq'],
    lang: 'rust',
    kind: 'type',
    official: 'Trait for comparisons corresponding to equivalence relations.',
    source: STD,
    when: 'A promise that every value equals itself, needed for HashMap keys. You derive it next to PartialEq; it adds no methods. Types with f32 or f64 inside cannot have it, because NaN is not equal to itself.',
    example: { command: '#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\nenum Axis { X, Y, Z }', says: 'Makes Axis usable as a HashMap key.' },
    seeAlso: ['PartialEq', 'Hash', 'Ord'],
  },
  {
    name: 'PartialOrd',
    aliases: ['std::cmp::PartialOrd'],
    lang: 'rust',
    kind: 'type',
    official: 'Trait for types that form a partial order.',
    source: STD,
    when: 'So values can be compared with <, >, <= and >=. Derived on an enum, earlier variants count as smaller. Floats have it, but a comparison with NaN is always false, which is why .sort() will not work on a Vec<f64>; use sort_by with total_cmp.',
    example: { command: '#[derive(PartialEq, PartialOrd)]\nenum Alert { Info, Warning, Critical }', says: 'Lets you write if level >= Alert::Warning.' },
    seeAlso: ['Ord', 'PartialEq'],
  },
  {
    name: 'Ord',
    aliases: ['std::cmp::Ord'],
    lang: 'rust',
    kind: 'type',
    official: 'Trait for types that form a total order.',
    source: STD,
    when: 'When every pair of values can be put in order, with no NaN-like exceptions. Needed for .sort(), .max() and BTreeMap keys. Derive it together with PartialOrd, Eq and PartialEq.',
    example: { command: '#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]\nenum Stage { Boost, Coast, Entry }', says: 'Stages can now be sorted and used as BTreeMap keys, in the order they are written.' },
    seeAlso: ['PartialOrd', 'Eq', 'BTreeMap'],
  },
  {
    name: 'Hash',
    aliases: ['std::hash::Hash'],
    lang: 'rust',
    kind: 'type',
    official: 'A hashable type.',
    source: STD,
    when: 'So a value can be a HashMap key or go in a HashSet. Derive it along with PartialEq and Eq; two values that are equal must give the same hash. f64 does not have it.',
    example: { command: '#[derive(PartialEq, Eq, Hash)]\nstruct SensorId(u16);', says: 'Lets you use SensorId as a HashMap key.' },
    seeAlso: ['HashMap', 'Eq'],
  },
]
