/* ============================================================================
   ORBIT command reference: the shell batch
   ----------------------------------------------------------------------------
   Bash keywords and built-in commands, and the process, network, service and
   system tools the Terminal course and the Linux lessons teach. `official` is
   word for word: `help -d` from bash 5.2 for keywords and built-ins, and the
   NAME line of the Ubuntu 24.04 manual page for everything else.
   ========================================================================== */
import type { CommandRef } from './types'

export const COMMANDS: CommandRef[] = [
  /* ---------------------------------------------------------------- keywords */
  {
    name: 'if',
    kind: 'keyword',
    official: 'Execute commands based on conditional.',
    source: 'bash built-in help',
    when: 'You want the script to choose between two paths. `if` runs a command and looks at its exit status: 0 (success) takes the `then` part, anything else takes the `else` part, and exactly one part ever runs.',
    flags: [
      ['then', 'starts the commands to run when the condition succeeds'],
      ['elif', '"else if": asks another question when the first one failed'],
      ['else', 'starts the commands to run when every question failed'],
      ['fi', 'ends the whole if ("if" backwards)'],
    ],
    example: {
      command: 'if grep -q ERROR app.log; then echo "look at the log"; else echo "all quiet"; fi',
      says: 'Prints "look at the log" when app.log contains ERROR, and "all quiet" when it does not.',
    },
    seeAlso: ['test', '[[', 'case', 'true'],
  },
  {
    name: 'for',
    kind: 'keyword',
    official: 'Execute commands for each member in a list.',
    source: 'bash built-in help',
    when: 'You want to do the same job to every item in a list: a few words, every file a wildcard matches, or every argument a script was given. Quote the loop variable, `"$f"`, so a name with a space stays one name.',
    flags: [
      ['in', 'the list comes after it: words, a wildcard like *.txt, or "$@"'],
      ['do', 'starts the commands to repeat'],
      ['done', 'ends the loop'],
    ],
    example: {
      command: 'for planet in mercury venus earth; do mkdir "$planet"; done',
      says: 'Runs mkdir three times, once per name, and makes three folders: mercury, venus and earth.',
    },
    seeAlso: ['while', 'break', 'continue'],
  },
  {
    name: 'while',
    kind: 'keyword',
    official: 'Execute commands as long as a test succeeds.',
    source: 'bash built-in help',
    when: 'You want to repeat something for as long as a condition holds, or read a file or a command\'s output one line at a time with `while IFS= read -r line`.',
    flags: [
      ['do', 'starts the commands to repeat'],
      ['done', 'ends the loop; < file after it feeds the loop its input'],
    ],
    example: {
      command: 'while IFS= read -r line; do echo "line: $line"; done < flight-plan.txt',
      says: 'Reads flight-plan.txt one line at a time and prints each line with "line: " in front of it.',
    },
    seeAlso: ['until', 'read', 'for', 'break'],
  },
  {
    name: 'until',
    kind: 'keyword',
    official: 'Execute commands as long as a test does not succeed.',
    source: 'bash built-in help',
    when: 'You want to repeat something until a condition becomes true: the mirror image of `while`. Make sure something in the body changes the condition, or the loop never ends.',
    example: {
      command: 'i=3; until (( i == 0 )); do echo "T-minus $i"; i=$((i-1)); done',
      says: 'Prints T-minus 3, T-minus 2 and T-minus 1, then stops, because i has reached 0.',
    },
    seeAlso: ['while', 'for'],
  },
  {
    name: 'case',
    kind: 'keyword',
    official: 'Execute commands based on pattern matching.',
    source: 'bash built-in help',
    when: 'You want to pick one of several branches by matching a word against patterns, like sorting file names by their ending or handling each option a script accepts. The first matching pattern wins.',
    flags: [
      ['pattern)', 'a wildcard pattern to match, like *.log; | separates choices'],
      [';;', 'ends one branch'],
      ['*)', 'the catch-all branch for anything no other pattern matched'],
      ['esac', 'ends the whole case ("case" backwards)'],
    ],
    example: {
      command: 'case "$f" in *.log) echo "log" ;; *.csv) echo "table" ;; *) echo "unknown" ;; esac',
      says: 'Prints log when $f ends in .log, table when it ends in .csv, and unknown for anything else.',
    },
    seeAlso: ['if', 'getopts'],
  },
  {
    name: 'function',
    kind: 'keyword',
    official: 'Define shell function.',
    source: 'bash built-in help',
    when: 'You want to give a few commands a name and run them like one command. ORBIT writes functions as `name() { …; }`; putting the word `function` in front is another bash spelling of the same thing.',
    example: {
      command: 'greet() { echo "Hello, $1"; }; greet Ada',
      says: 'Defines a function called greet, then runs it with the argument Ada. It prints Hello, Ada.',
    },
    seeAlso: ['local', 'return', 'type'],
  },
  {
    name: '[[',
    kind: 'keyword',
    official: 'Execute conditional command.',
    source: 'bash built-in help',
    when: 'You want bash\'s own, safer version of `[ … ]`. Inside `[[ ]]` an empty or spaced variable does not break the test, and you can match wildcard patterns and regular expressions. It works in bash but not in plain `sh`.',
    flags: [
      ['==', 'matches a wildcard pattern like *.log (quote it to mean the exact text)'],
      ['=~', 'matches a regular expression; the captured parts land in BASH_REMATCH'],
      ['&&', 'and: both tests must be true'],
      ['||', 'or: either test may be true'],
      ['-n', 'is the text not empty?'],
      ['-z', 'is the text empty?'],
    ],
    example: {
      command: '[[ $name == *.log ]] && echo "a log file"',
      says: 'Prints "a log file" when the name in $name ends in .log, and nothing otherwise.',
    },
    seeAlso: ['test', 'if'],
  },
  {
    name: 'time',
    kind: 'keyword',
    official: "Report time consumed by pipeline's execution.",
    source: 'bash built-in help',
    when: 'You want to know how long a command takes, for example to check whether a change really made a job faster. One run can be off, so time it a few times.',
    example: {
      command: 'time xargs -n 1 ./run_case.sh < cases.txt',
      says: 'Runs the cases, then prints three times: real (clock on the wall), user and sys (time the processor spent working).',
    },
    seeAlso: ['timeout'],
  },

  /* ---------------------------------------------------------------- built-ins */
  {
    name: 'test',
    aliases: ['['],
    kind: 'builtin',
    official: 'Evaluate conditional expression.',
    source: 'bash built-in help',
    when: 'You want to ask a yes-or-no question about a file, some text or a number, usually as the condition of an `if`. It prints nothing and answers with its exit status. `[` needs a space after it and a `]` at the end, and variables inside it need double quotes.',
    flags: [
      ['-f', 'is there a file with this name?'],
      ['-d', 'is there a folder with this name?'],
      ['-e', 'does it exist at all, file or folder?'],
      ['-s', 'does it exist and is it not empty?'],
      ['-z', 'is this text empty?'],
      ['-n', 'is this text not empty?'],
      ['=', 'are the two texts the same?'],
      ['!=', 'are the two texts different?'],
      ['-eq', 'are the two numbers equal? (-ne: not equal)'],
      ['-lt', 'is the first number less than the second? (-le: less or equal)'],
      ['-gt', 'is the first number greater than the second? (-ge: greater or equal)'],
      ['!', 'flips the answer: true becomes false'],
    ],
    example: {
      command: 'if [ ! -f config.txt ]; then echo "no config yet"; fi',
      says: 'Prints "no config yet" when there is no file called config.txt in this folder.',
    },
    seeAlso: ['[[', 'if', 'true'],
  },
  {
    name: 'true',
    kind: 'builtin',
    official: 'Return a successful result.',
    source: 'bash built-in help',
    when: 'You need a command that does nothing and succeeds: an endless `while true` loop, or `|| true` after a command whose failure is fine, so a `set -e` script carries on.',
    example: {
      command: 'true && echo "this runs"',
      says: 'true finishes with status 0, success, so the echo after && runs and prints "this runs".',
    },
    seeAlso: ['false', 'if'],
  },
  {
    name: 'false',
    kind: 'builtin',
    official: 'Return an unsuccessful result.',
    source: 'bash built-in help',
    when: 'You need a command that does nothing and fails, usually to see what `&&`, `||` or `if` do when a command fails.',
    example: {
      command: 'false || echo "this runs too"',
      says: 'false finishes with status 1, a failure, so the echo after || runs.',
    },
    seeAlso: ['true', 'if'],
  },
  {
    name: 'exit',
    kind: 'builtin',
    official: 'Exit the shell.',
    source: 'bash built-in help',
    when: 'You want a script to stop right now and report how it went with a number: `exit 0` for success, 1 for a failure, 2 for "you used it wrong". Typed at the prompt of a real terminal, it closes the terminal.',
    flags: [
      ['0', 'stop and report success'],
      ['1', 'stop and report a general failure'],
      ['2', 'stop and report that the script was used wrongly'],
    ],
    example: {
      command: 'if [ $# -eq 0 ]; then echo "usage: count.sh FILE" >&2; exit 2; fi',
      says: 'When the script got no arguments, prints a usage line to standard error and stops with status 2.',
    },
    seeAlso: ['return', 'trap'],
  },
  {
    name: 'read',
    kind: 'builtin',
    official: 'Read a line from the standard input and split it into fields.',
    source: 'bash built-in help',
    when: 'You want a script to take in text one line at a time, from a file, a command or the keyboard, and keep it in variables. Use `-r` every time, and `IFS=` in front to keep the line exactly as it is.',
    flags: [
      ['-r', 'keep backslashes as they are (use it on every read)'],
      ['-a', 'split the line into an array, one word per element'],
      ["-d ''", 'read up to a zero byte instead of a new line, to pair with find -print0'],
    ],
    example: {
      command: 'IFS= read -r first < flight-plan.txt; echo "$first"',
      says: 'Stores the first line of flight-plan.txt in the variable first, then prints it.',
    },
    seeAlso: ['while', 'mapfile'],
  },
  {
    name: 'local',
    kind: 'builtin',
    official: 'Define local variables.',
    source: 'bash built-in help',
    when: 'You set a variable inside a function and want it to belong to that function only, so it cannot overwrite a variable of the same name elsewhere. Write `local n` on one line and `n=$(cmd)` on the next: `local n=$(cmd)` hides whether the command failed.',
    example: {
      command: 'count_errors() { local n; n=$(grep -c ERROR "$1"); echo "$n"; }',
      says: 'Defines a function whose variable n exists only while the function runs. Called as count_errors app.log, it prints how many lines contain ERROR.',
    },
    seeAlso: ['function', 'declare', 'return'],
  },
  {
    name: 'declare',
    kind: 'builtin',
    official: 'Set variable values and attributes.',
    source: 'bash built-in help',
    when: 'You want to see exactly what a variable holds, including whether it is empty or was never set, or to make an array or a lookup table.',
    flags: [
      ['-p', 'print the variable the way you would have to type it'],
      ['-a', 'an ordinary array, numbered from 0'],
      ['-A', 'an associative array: a lookup table with names as keys'],
      ['-x', 'mark for export (on its own: list the exported variables)'],
      ['-f', 'show the definition of a function'],
    ],
    example: {
      command: 'declare -p planet',
      says: 'Prints declare -- planet="mars", showing exactly what planet holds.',
    },
    seeAlso: ['local', 'readonly', 'export'],
  },
  {
    name: 'readonly',
    kind: 'builtin',
    official: 'Mark shell variables as unchangeable.',
    source: 'bash built-in help',
    when: 'You want a value that must never change while the script runs, such as the exit codes your script uses. Any later attempt to change it is an error.',
    example: {
      command: 'readonly EX_USAGE=2',
      says: 'Sets EX_USAGE to 2 for good. Trying EX_USAGE=3 afterwards prints "EX_USAGE: readonly variable".',
    },
    seeAlso: ['declare', 'exit'],
  },
  {
    name: 'export',
    kind: 'builtin',
    official: 'Set export attribute for shell variables.',
    source: 'bash built-in help',
    when: 'You want the programs and scripts you start to see a variable. A plain variable stays in your shell; an exported one is copied to every child. Write the name with no dollar sign.',
    example: {
      command: 'export PLANET=Mars',
      says: 'Sets PLANET and exports it, so bash next-stop.sh now prints Next stop: Mars.',
    },
    seeAlso: ['env', 'printenv', 'unset'],
  },
  {
    name: 'unset',
    kind: 'builtin',
    official: 'Unset values and attributes of shell variables and functions.',
    source: 'bash built-in help',
    when: 'You want a variable (or one element of an array) gone completely, not just empty, or you changed `IFS` and want the normal splitting back.',
    example: {
      command: 'unset PLANET',
      says: 'Removes PLANET, so it is no longer set in this shell or passed to the programs you start.',
    },
    seeAlso: ['export', 'declare'],
  },
  {
    name: 'set',
    kind: 'builtin',
    official: 'Set or unset values of shell options and positional parameters.',
    source: 'bash built-in help',
    when: 'You want a script to be stricter or to show what it does. `set -euo pipefail` near the top makes it stop at the first failure, the first unset variable and the first failing stage of a pipeline.',
    flags: [
      ['-e', 'stop the script as soon as a command fails'],
      ['-u', 'using a variable that was never set is an error'],
      ['-o pipefail', 'a pipeline fails if any stage in it fails'],
      ['-x', 'print each command before running it (+x turns it off)'],
      ['-E', 'let an ERR trap work inside functions too'],
      ['--', 'replace the script\'s arguments with the words that follow'],
    ],
    example: {
      command: 'set -euo pipefail',
      says: 'Prints nothing. From here on, the script stops at the first failed command, unset variable or broken pipeline.',
    },
    seeAlso: ['shopt', 'trap', 'bash'],
  },
  {
    name: 'shopt',
    kind: 'builtin',
    official: 'Set and unset shell options.',
    source: 'bash built-in help',
    when: 'You want to switch on one of bash\'s extra options, most often to change what a wildcard that matches nothing does.',
    flags: [
      ['-s', 'switch the named option on'],
      ['nullglob', 'a wildcard that matches nothing becomes nothing'],
      ['failglob', 'a wildcard that matches nothing is an error'],
      ['inherit_errexit', 'set -e also works inside $( … )'],
    ],
    example: {
      command: 'shopt -s nullglob',
      says: 'From now on, for f in *.png runs zero times in a folder with no .png files, instead of once with the text *.png.',
    },
    seeAlso: ['set'],
  },
  {
    name: 'trap',
    kind: 'builtin',
    official: 'Trap signals and other events.',
    source: 'bash built-in help',
    when: 'You want a script to clean up after itself, like deleting its scratch folder, however it ends: normally, on an error, or when someone presses Ctrl-C. Put the command in single quotes so its variables are filled in when it runs.',
    flags: [
      ['EXIT', 'run the command whenever the script ends, any way at all'],
      ['INT TERM', 'run it on Ctrl-C or a polite kill'],
      ['ERR', 'run it when a command fails (with set -E, inside functions too)'],
      ['-p', 'show the traps that are set'],
      ['- SIG', 'put that signal back to normal'],
      ["'' SIG", 'ignore that signal'],
    ],
    example: {
      command: 'trap \'rm -rf "$tmp"\' EXIT',
      says: 'Prints nothing now. When the script ends, for any reason, it deletes the scratch folder named in $tmp.',
    },
    seeAlso: ['kill', 'exit', 'set'],
  },
  {
    name: 'source',
    aliases: ['.'],
    kind: 'builtin',
    official: 'Execute commands from a file in the current shell.',
    source: 'bash built-in help',
    when: 'You want a file\'s settings, like variables, functions or a changed PATH, to land in the shell you are using. Running the file with bash would change only a child shell, which forgets everything when it ends.',
    example: {
      command: 'source .venv/bin/activate',
      says: 'Runs the activate script inside your own shell, so python3 and pip now come from the project\'s .venv folder.',
    },
    seeAlso: ['bash', 'export'],
  },
  {
    name: 'exec',
    kind: 'builtin',
    official: 'Replace the shell with the given command.',
    source: 'bash built-in help',
    when: 'A wrapper script has finished its setup and should become the real program, or a script wants to send all its later output to a file or open a file for a lock. Nothing after an `exec` that runs a program is ever reached.',
    example: {
      command: 'exec ./sim "$@"',
      says: 'Replaces the script with ./sim, handing on every argument, so the simulation takes over the script\'s process.',
    },
    seeAlso: ['flock', 'bash'],
  },
  {
    name: 'shift',
    kind: 'builtin',
    official: 'Shift positional parameters.',
    source: 'bash built-in help',
    when: 'A script has dealt with its first argument and wants the rest renumbered, so the old $2 becomes $1. Common after reading an option and its value.',
    flags: [
      ['n', 'drop n arguments at once, as in shift 2'],
      ['$((OPTIND - 1))', 'drop every option getopts has already read'],
    ],
    example: {
      command: 'shift 2',
      says: 'Drops the first two arguments. What was $3 is now $1, and $# is two smaller.',
    },
    seeAlso: ['getopts'],
  },
  {
    name: 'wait',
    kind: 'builtin',
    official: 'Wait for job completion and return exit status.',
    source: 'bash built-in help',
    when: 'You started commands in the background with `&` and need them to finish before going on, or you want their exit status.',
    example: {
      command: 'sleep 30 & wait "$!"',
      says: 'Starts sleep in the background, then waits for it ($! is its process id). A trap can still run the moment a signal arrives.',
    },
    seeAlso: ['sleep', 'jobs', 'kill', 'trap'],
  },
  {
    name: 'mapfile',
    kind: 'builtin',
    official: 'Read lines from the standard input into an indexed array variable.',
    source: 'bash built-in help',
    when: 'You want every line of a file or a command\'s output in an array, one line per element, with spaces kept. Feed it with `< <(cmd)`, not a pipe, or the array is lost.',
    flags: [
      ['-t', 'drop the new line from the end of each element'],
      ["-d ''", 'split at zero bytes instead of new lines'],
    ],
    example: {
      command: 'mapfile -t ids < <(grep FAIL run.log | cut -d= -f2)',
      says: 'Fills the array ids with one failed case id per element, taken from the FAIL lines of run.log.',
    },
    seeAlso: ['read', 'declare'],
  },
  {
    name: 'type',
    kind: 'builtin',
    official: 'Display information about command type.',
    source: 'bash built-in help',
    when: 'A command behaves oddly and you want to know what that name really is: a program on the disk, a bash built-in, a function or an alias.',
    flags: [['-a', 'show every match, in the order the shell would try them']],
    example: {
      command: 'type -a python3',
      says: 'Lists every python3 the shell can find, for example python3 is /usr/local/bin/python3 and python3 is /usr/bin/python3.',
    },
    seeAlso: ['command', 'which', 'hash', 'alias'],
  },
  {
    name: 'command',
    kind: 'builtin',
    official: 'Execute a simple command or display information about commands.',
    source: 'bash built-in help',
    when: 'A script wants to check whether a program is installed before using it, or a function wants to call the real program it has the same name as.',
    flags: [['-v', 'print where the command is, or fail quietly if there is none']],
    example: {
      command: 'command -v python3 || echo "python3 is not installed"',
      says: 'Prints the path of python3, such as /usr/bin/python3, or the message when there is no python3.',
    },
    seeAlso: ['type', 'which'],
  },
  {
    name: 'hash',
    kind: 'builtin',
    official: 'Remember or display program locations.',
    source: 'bash built-in help',
    when: 'You moved or deleted a program and the shell keeps looking for it in the old place, with an error that names a path that no longer exists.',
    flags: [
      ['-r', 'forget every remembered location'],
      ['-d', 'forget one name, as in hash -d sim'],
    ],
    example: {
      command: 'hash -r',
      says: 'Empties bash\'s list of where it found each command, so the next time it searches PATH again.',
    },
    seeAlso: ['type', 'which'],
  },
  {
    name: 'alias',
    kind: 'builtin',
    official: 'Define or display aliases.',
    source: 'bash built-in help',
    when: 'You want a short name, or a safer default, for a command you type all the time. Put it in ~/.bashrc to keep it. With no arguments it lists the aliases you have.',
    example: {
      command: "alias cp='cp -i'",
      says: 'From now on in this shell, cp asks before overwriting a file.',
    },
    seeAlso: ['type', 'cp'],
  },
  {
    name: 'history',
    kind: 'builtin',
    official: 'Display or manipulate the history list.',
    source: 'bash built-in help',
    when: 'You want to find a command you typed earlier. The Up arrow brings back the last ones; `history` lists them all, numbered.',
    example: {
      command: 'history | grep rsync',
      says: 'Shows every rsync command you typed recently, each with its number in the history list.',
    },
    seeAlso: ['grep'],
  },
  {
    name: 'umask',
    kind: 'builtin',
    official: 'Display or set file mode mask.',
    source: 'bash built-in help',
    when: 'You want new files and folders to start out more private (or more shared) than usual. The mask lists permission bits to block; programs you start inherit it.',
    flags: [
      ['022', 'the usual: files 644, folders 755, everyone may read'],
      ['027', 'your group may read, everyone else gets nothing'],
      ['077', 'private: files 600, folders 700'],
    ],
    example: {
      command: 'umask 077',
      says: 'From now on, new files in this shell are made 600 and new folders 700: only you can read them.',
    },
    seeAlso: ['chmod'],
  },
  {
    name: 'kill',
    kind: 'builtin',
    official: 'Send a signal to a job.',
    source: 'bash built-in help',
    when: 'You want to stop, pause or resume a running program. Plain `kill` politely asks it to stop, so it can save its work. Keep `kill -9` for a program that ignored that request: it cannot save anything.',
    flags: [
      ['-TERM', 'politely ask it to stop (the default, signal 15)'],
      ['-9', 'force it to stop at once (SIGKILL); nothing gets saved'],
      ['-STOP', 'pause it'],
      ['-CONT', 'resume a paused one'],
      ['-s', 'name the signal, as in kill -s INT'],
      ['-l', 'list every signal'],
      ['%1', 'a job number from jobs instead of a process id'],
    ],
    example: {
      command: 'kill 4471',
      says: 'Sends SIGTERM to process 4471, a polite request to stop. A program with a handler saves its data first; one without stops with status 143.',
    },
    seeAlso: ['ps', 'pgrep', 'pkill', 'trap', 'jobs'],
  },
  {
    name: 'getopts',
    kind: 'builtin',
    official: 'Parse option arguments.',
    source: 'bash built-in help',
    when: 'You want your script to take short options like `-c 4 -v`, the way real tools do, and to reject ones it does not know.',
    flags: [
      ['":c:t:v"', 'the option letters; a colon after a letter means it takes a value'],
      ['leading :', 'report problems quietly and let the script handle them'],
      ['$OPTARG', 'the value given with the option'],
      ['$OPTIND', 'where the options end; shift $((OPTIND - 1)) removes them'],
    ],
    example: {
      command: 'while getopts ":c:v" opt; do case $opt in c) cases=$OPTARG ;; v) verbose=1 ;; *) usage ;; esac; done',
      says: 'Reads options such as -c 4 -v: stores 4 in cases, sets verbose, and calls usage for anything else.',
    },
    seeAlso: ['shift', 'case', 'while'],
  },
  {
    name: 'return',
    kind: 'builtin',
    official: 'Return from a shell function.',
    source: 'bash built-in help',
    when: 'A function has its answer and should stop now, handing back a status: 0 for success, a small number for a kind of failure. To hand back text, print it and capture it with $( ) instead.',
    example: {
      command: 'has_errors() { grep -q ERROR "$1" || return 1; return 0; }',
      says: 'Defines a function that returns 0 when the file contains ERROR and 1 when it does not, so it works as the condition of an if.',
    },
    seeAlso: ['function', 'exit', 'local'],
  },
  {
    name: 'break',
    kind: 'builtin',
    official: 'Exit for, while, or until loops.',
    source: 'bash built-in help',
    when: 'A loop has found what it was looking for, or hit a problem, and should stop early. The script carries on after `done`.',
    flags: [['2', 'leave two loops at once, when one loop is inside another']],
    example: {
      command: 'for f in runs/*.log; do grep -q ERROR "$f" && { echo "first error in $f"; break; }; done',
      says: 'Checks the logs in order and stops the loop at the first one that contains ERROR, naming it.',
    },
    seeAlso: ['continue', 'for', 'while'],
  },
  {
    name: 'continue',
    kind: 'builtin',
    official: 'Resume for, while, or until loops.',
    source: 'bash built-in help',
    when: 'This item should be skipped, but the loop should go on with the next one.',
    example: {
      command: 'for f in runs/*; do [[ -e $f ]] || continue; echo "checking $f"; done',
      says: 'Skips anything that does not exist (such as an unmatched *) and prints a line for every real file.',
    },
    seeAlso: ['break', 'for', 'while'],
  },
  {
    name: 'jobs',
    kind: 'builtin',
    official: 'Display status of jobs.',
    source: 'bash built-in help',
    when: 'You started things in the background with `&`, or paused one with Ctrl-Z, and want to see them with their job numbers.',
    example: {
      command: 'jobs',
      says: 'Lists each job, such as [1]+ Running sleep 300 &. The + marks the job fg and bg act on by default.',
    },
    seeAlso: ['fg', 'bg', 'kill', 'disown'],
  },
  {
    name: 'fg',
    kind: 'builtin',
    official: 'Move job to the foreground.',
    source: 'bash built-in help',
    when: 'A job is running in the background or paused, and you want it back in front: to watch it, type to it, or stop it with Ctrl-C.',
    example: {
      command: 'fg %1',
      says: 'Brings job 1 to the front. It owns your keyboard again until it finishes.',
    },
    seeAlso: ['bg', 'jobs'],
  },
  {
    name: 'bg',
    kind: 'builtin',
    official: 'Move jobs to the background.',
    source: 'bash built-in help',
    when: 'You pressed Ctrl-Z on a slow command. Ctrl-Z only pauses it; `bg` lets it keep running in the background while you get your prompt back.',
    example: {
      command: 'bg %1',
      says: 'Resumes the paused job 1 in the background and prints [1]+ sleep 300 &.',
    },
    seeAlso: ['fg', 'jobs'],
  },
  {
    name: 'disown',
    kind: 'builtin',
    official: 'Remove jobs from current shell.',
    source: 'bash built-in help',
    when: 'You started a long job with `&` and forgot to protect it. `disown` takes it off the shell\'s list, so closing the terminal no longer stops it.',
    example: {
      command: 'disown %2',
      says: 'Job 2 vanishes from jobs and keeps running after you log out. From now on you can reach it only by its process id.',
    },
    seeAlso: ['nohup', 'jobs', 'tmux'],
  },
  {
    name: 'eval',
    kind: 'builtin',
    official: 'Execute arguments as a shell command.',
    source: 'bash built-in help',
    when: 'A program prints shell commands for you to run, like ssh-agent does. Never `eval` text that came from a user or a file you do not trust: it runs whatever that text says.',
    example: {
      command: 'eval "$(ssh-agent -s)"',
      says: 'Starts ssh-agent and runs the lines it prints, which set SSH_AUTH_SOCK so ssh can find the agent.',
    },
    seeAlso: ['ssh-agent', 'source'],
  },
  {
    name: 'ulimit',
    kind: 'builtin',
    official: 'Modify shell resource limits.',
    source: 'bash built-in help',
    when: 'You want to see or change a limit the shell puts on the programs it starts, most often to let a crashing program leave a core file for the debugger.',
    flags: [
      ['-c', 'the largest core file allowed (0 means none)'],
      ['-s', 'the stack size, in kilobytes'],
      ['-n', 'how many files a program may have open'],
    ],
    example: {
      command: 'ulimit -c unlimited',
      says: 'Lets programs started from this shell write a core file of any size when they crash.',
    },
    seeAlso: ['coredumpctl'],
  },

  /* ------------------------------------------------------ shells and programs */
  {
    name: 'bash',
    kind: 'system',
    official: 'GNU Bourne-Again SHell',
    source: 'bash manual page',
    when: 'You want to run a script, or start a fresh shell. `bash script.sh` runs the file in a new child shell, so it works without `chmod +x`, and a `cd` inside it does not move you.',
    flags: [
      ['-x', 'trace: print each command, with variables filled in, before it runs'],
      ['-c', 'run the text that follows as a command'],
      ['-l', 'start as a login shell, which reads ~/.bash_profile'],
      ['-i', 'start as an interactive shell, which reads ~/.bashrc'],
    ],
    example: {
      command: 'bash -x archive.sh',
      says: 'Runs archive.sh and prints every command with a + in front before running it, so you see what really ran.',
    },
    seeAlso: ['sh', 'set', 'source', 'shellcheck'],
  },
  {
    name: 'sh',
    kind: 'system',
    official: 'command interpreter (shell)',
    source: 'sh manual page (dash, the sh on Ubuntu)',
    when: 'A script starts with `#!/bin/sh`, or you need a shell to run one command line. On Ubuntu `sh` is dash, a small shell without bash extras such as `[[ ]]` and arrays.',
    flags: [['-c', 'run the text that follows as a command']],
    example: {
      command: "sudo sh -c 'echo hello > /root/f'",
      says: 'Runs the whole line, redirect included, as root, so the file can be written where your own shell may not write.',
    },
    seeAlso: ['bash', 'sudo'],
  },
  {
    name: 'env',
    kind: 'system',
    official: 'run a program in a modified environment',
    source: 'env manual page (GNU coreutils)',
    when: 'You want to see every exported variable, or run one command with a setting changed without touching your own shell.',
    flags: [
      ['NAME=value', 'set a variable for that one command only'],
      ['-i', 'start the command with an empty environment'],
      ['-S', 'split one shebang argument into several'],
    ],
    example: {
      command: 'env',
      says: 'Lists every exported variable, one per line, as NAME=value: HOME=/home/you, PATH=… and so on.',
    },
    seeAlso: ['export', 'printenv'],
  },
  {
    name: 'printenv',
    kind: 'system',
    official: 'print all or part of environment',
    source: 'printenv manual page (GNU coreutils)',
    when: 'You want to see one environment variable, or check whether a variable really was exported. It shows only exported ones, not every shell variable.',
    example: {
      command: 'printenv PATH',
      says: 'Prints the value of PATH, the folders the shell searches for commands, separated by colons.',
    },
    seeAlso: ['env', 'export'],
  },
  {
    name: 'whoami',
    kind: 'system',
    official: 'print effective user name',
    source: 'whoami manual page (GNU coreutils)',
    when: 'You want to know which user account your shell is running as, for example to put your name into a file name.',
    example: {
      command: 'whoami',
      says: 'Prints your user name. In ORBIT\'s practice terminal that is you.',
    },
    seeAlso: ['id'],
  },
  {
    name: 'id',
    kind: 'system',
    official: 'print real and effective user and group IDs',
    source: 'id manual page (GNU coreutils)',
    when: 'You want your user number and group number, for example so files a container writes belong to you and not to root.',
    flags: [
      ['-u', 'print only the user id number'],
      ['-g', 'print only the group id number'],
    ],
    example: {
      command: 'id -u',
      says: 'Prints your user id number, such as 1000. Root is always 0.',
    },
    seeAlso: ['whoami', 'sudo'],
  },
  {
    name: 'sudo',
    kind: 'system',
    official: 'execute a command as another user',
    source: 'sudo manual page',
    when: 'A command needs to run as root, the administrator, such as installing packages or writing to /etc. It runs with the power to change or delete anything, so read the command twice first. `sudo cmd > file` does not work, because your own shell does the redirect; use `cmd | sudo tee file`.',
    example: {
      command: 'echo "export SIM_TOOLS=/opt/simtools/bin" | sudo tee /etc/profile.d/simtools.sh',
      says: 'Asks for your password, then tee, running as root, writes the line into /etc/profile.d/simtools.sh, a folder your own shell may not write to.',
    },
    seeAlso: ['apt', 'tee', 'sh'],
  },
  {
    name: 'which',
    kind: 'system',
    official: 'locate a command',
    source: 'which manual page (debianutils)',
    when: 'You want to know which file runs when you type a command name. `type -a` tells you more, because it also knows about built-ins, functions and aliases.',
    example: {
      command: 'which python3',
      says: 'Prints the path of the python3 the shell would run, such as /usr/bin/python3.',
    },
    seeAlso: ['type', 'command', 'hash'],
  },
  {
    name: 'man',
    kind: 'system',
    official: 'an interface to the system reference manuals',
    source: 'man manual page',
    when: 'You want the official manual for a command: every flag and what it does. The page opens in `less`, so `/` searches, `n` finds the next match and `q` quits.',
    example: {
      command: 'man errno',
      says: 'Opens the manual page for errno, which lists the error names such as ENOENT (no such file) and what each one means.',
    },
    seeAlso: ['less'],
  },
  {
    name: 'sleep',
    kind: 'system',
    official: 'delay for a specified amount of time',
    source: 'sleep manual page (GNU coreutils)',
    when: 'You want a script to pause before trying again, or you need a harmless long-running command to practice job control on.',
    example: {
      command: 'sleep 300 &',
      says: 'Starts a five-minute pause in the background and prints its job number and process id, such as [1] 17.',
    },
    seeAlso: ['wait', 'timeout', 'jobs'],
  },
  {
    name: 'timeout',
    kind: 'system',
    official: 'run a command with a time limit',
    source: 'timeout manual page (GNU coreutils)',
    when: 'A command might run forever, like a program with a stuck loop or `tail -f`, and you want it stopped after a set time. It exits with status 124 when it had to stop the command.',
    example: {
      command: 'timeout 5 tail -f run.log',
      says: 'Follows run.log for five seconds, then stops tail. echo $? afterwards prints 124.',
    },
    seeAlso: ['sleep', 'kill', 'time'],
  },
  {
    name: 'date',
    kind: 'system',
    official: 'print or set the system date and time',
    source: 'date manual page (GNU coreutils)',
    when: 'You want today\'s date or the time, often stamped into a file or folder name inside a script.',
    flags: [
      ['+%F', 'the date as year-month-day, like 2026-09-29'],
      ['+%u', 'the day of the week as a number, Monday = 1'],
      ['-u', 'use UTC, the same clock everywhere on Earth'],
    ],
    example: {
      command: 'mkdir "run-$(date +%F)"',
      says: 'Makes a folder named after today, such as run-2026-09-29.',
    },
    seeAlso: ['mkdir'],
  },

  /* ---------------------------------------------------------------- processes */
  {
    name: 'ps',
    kind: 'system',
    official: 'report a snapshot of the current processes.',
    source: 'ps manual page (procps-ng)',
    when: 'You want to see which programs are running, with their process ids (PIDs), state and memory. It is a photograph of one moment; `top` is the live video.',
    flags: [
      ['aux', 'every process, BSD style: user, CPU, memory, state'],
      ['-ef', 'every process, System V style, with the parent\'s PID'],
      ['-o', 'choose the columns, as in -o pid,ppid,stat,rss,args'],
      ['-p', 'only the process with this PID'],
      ['--forest', 'draw who started whom as a tree'],
    ],
    example: {
      command: 'ps -o pid,ppid,stat,args -p 18',
      says: 'Shows process 18: its PID, its parent\'s PID, its state (R running, S sleeping, T stopped) and its command.',
    },
    seeAlso: ['pgrep', 'top', 'kill'],
  },
  {
    name: 'pgrep',
    kind: 'system',
    official: 'look up, signal, or wait for processes based on name and other attributes',
    source: 'pgrep manual page (procps-ng)',
    when: 'You want the process id of a program by its name. Run it before `pkill` with the same pattern: its list is exactly what `pkill` would hit.',
    flags: [
      ['-a', 'show the full command line next to each PID'],
      ['-f', 'match against the whole command line, not only the program name'],
      ['-c', 'print only how many match'],
    ],
    example: {
      command: 'pgrep -a python3',
      says: 'Prints each matching process id and command, such as 8 python3 sim.py.',
    },
    seeAlso: ['pkill', 'ps', 'kill'],
  },
  {
    name: 'pkill',
    kind: 'system',
    official: 'look up, signal, or wait for processes based on name and other attributes',
    source: 'pkill manual page (procps-ng)',
    when: 'You want to signal every process whose name matches a pattern, without looking up PIDs. The pattern can match more than you meant, such as the editor holding your script, so check it with `pgrep -a` first.',
    flags: [['-f', 'match against the whole command line, not only the program name']],
    example: {
      command: 'pkill -f sim.py',
      says: 'Sends SIGTERM to every process whose command line contains sim.py.',
    },
    seeAlso: ['pgrep', 'kill'],
  },
  {
    name: 'top',
    kind: 'system',
    official: 'display Linux processes',
    source: 'top manual page (procps-ng)',
    when: 'You want a live view of what is using the processor and memory right now. Inside it, P sorts by CPU, M by memory, 1 shows each core, k sends a signal and q quits.',
    flags: [
      ['-b', 'batch mode: print plain text instead of a live screen'],
      ['-n 1', 'print one frame and stop'],
    ],
    example: {
      command: 'top -b -n 1 | head -8',
      says: 'Prints one frame of top: the load average, CPU and memory summary, then the busiest processes.',
    },
    seeAlso: ['htop', 'ps', 'uptime'],
  },
  {
    name: 'htop',
    kind: 'system',
    official: 'interactive process viewer',
    source: 'htop manual page',
    when: 'You want what `top` shows, with color, a bar for each core, a searchable tree (F5) and a menu for sending signals (F9).',
    example: {
      command: 'htop',
      says: 'Opens a live, colored list of processes that updates every second or two. Press q to leave.',
    },
    seeAlso: ['top', 'ps'],
  },
  {
    name: 'uptime',
    kind: 'system',
    official: 'Tell how long the system has been running.',
    source: 'uptime manual page (procps-ng)',
    when: 'You want the load average, how many tasks are running or waiting, to judge how busy a machine is. Compare it with the number of cores from `nproc`.',
    example: {
      command: 'uptime',
      says: 'Prints the time, how long the machine has been up, and the load average over 1, 5 and 15 minutes, such as 0.94, 0.89, 1.02.',
    },
    seeAlso: ['nproc', 'top'],
  },
  {
    name: 'nproc',
    kind: 'system',
    official: 'print the number of processing units available',
    source: 'nproc manual page (GNU coreutils)',
    when: 'You want to know how many cores you can use, to read a load average or to run as many jobs at once as there are cores.',
    example: {
      command: 'make -j"$(nproc)"',
      says: 'Runs the build with one job per core: on a 4-core machine, make -j4.',
    },
    seeAlso: ['uptime', 'xargs', 'make'],
  },
  {
    name: 'nice',
    kind: 'system',
    official: 'run a program with modified scheduling priority',
    source: 'nice manual page (GNU coreutils)',
    when: 'You want a long job to let other programs use the processor first. Niceness only changes who gets the CPU; it does not protect the job from being stopped.',
    flags: [['-n', 'how nice to be, from -20 (goes first) to 19 (goes last)']],
    example: {
      command: 'nice -n 19 ./job',
      says: 'Starts ./job at the lowest priority, so it only uses the processor when nothing else wants it.',
    },
    seeAlso: ['renice', 'top'],
  },
  {
    name: 'renice',
    kind: 'system',
    official: 'alter priority of running processes',
    source: 'renice manual page (util-linux)',
    when: 'A job is already running and you want to change how nice it is, without restarting it.',
    example: {
      command: 'renice -n 19 -p 4471',
      says: 'Lowers the priority of running process 4471 to 19, the nicest setting.',
    },
    seeAlso: ['nice', 'ps'],
  },
  {
    name: 'nohup',
    kind: 'system',
    official: 'run a command immune to hangups, with output to a non-tty',
    source: 'nohup manual page (GNU coreutils)',
    when: 'You want a job to keep running after you close the terminal or your SSH connection drops. A plain `&` job is stopped by the hang-up; `tmux` is better still, because you can come back to its screen.',
    example: {
      command: 'nohup ./run_campaign.sh &',
      says: 'Starts the script in the background, ignoring the hang-up signal, with its output going to nohup.out.',
    },
    seeAlso: ['setsid', 'disown', 'tmux'],
  },
  {
    name: 'setsid',
    kind: 'system',
    official: 'run a program in a new session',
    source: 'setsid manual page (util-linux)',
    when: 'You want a program cut loose from your terminal completely, so no hang-up can ever reach it.',
    example: {
      command: 'setsid python3 sim_plain.py > setsid.out 2>&1 &',
      says: 'Starts the simulation in a brand-new session with no terminal, writing all its output to setsid.out.',
    },
    seeAlso: ['nohup', 'disown', 'tmux'],
  },
  {
    name: 'flock',
    kind: 'system',
    official: 'manage locks from shell scripts',
    source: 'flock manual page (util-linux)',
    when: 'A script run by cron or a timer must never run twice at once. The lock is freed by the system when the script ends, even after a crash.',
    flags: [
      ['-n', 'do not wait: fail at once if another copy holds the lock'],
      ['-w', 'wait at most this many seconds for the lock'],
    ],
    example: {
      command: 'exec 9>/var/lock/sync.lock; flock -n 9 || exit 0',
      says: 'Opens the lock file and takes the lock. If another copy of the script already has it, this copy quietly stops.',
    },
    seeAlso: ['exec', 'crontab'],
  },
  {
    name: 'chrt',
    kind: 'system',
    official: 'manipulate the real-time attributes of a process',
    source: 'chrt manual page (util-linux)',
    when: 'You are setting up real-time work, like a control loop, and want to see or set which scheduling policy a process runs under.',
    flags: [
      ['-p', 'show (or set) the policy of a running process'],
      ['-m', 'list each policy and its priority range'],
    ],
    example: {
      command: 'chrt -p $$',
      says: 'Prints the scheduling policy and priority of your shell, such as SCHED_OTHER with priority 0.',
    },
    seeAlso: ['taskset', 'nice'],
  },
  {
    name: 'taskset',
    kind: 'system',
    official: "set or retrieve a process's CPU affinity",
    source: 'taskset manual page (util-linux)',
    when: 'You want a program to run on one particular core only, so it keeps that core\'s caches and other work stays out of its way.',
    flags: [['-c', 'the core numbers to allow, as in -c 3']],
    example: {
      command: 'taskset -c 3 ./loop',
      says: 'Starts ./loop pinned to core 3.',
    },
    seeAlso: ['chrt', 'nproc'],
  },

  /* ------------------------------------------------------------------ remote */
  {
    name: 'ssh',
    kind: 'system',
    official: 'OpenSSH remote login client',
    source: 'ssh manual page (OpenSSH)',
    when: 'You want to log in to another computer, or run one command there, over an encrypted connection. If it warns that the remote host identification has changed, stop and find out why before going on.',
    flags: [
      ['-i', 'which private key file to use'],
      ['-p', 'which port to connect to (normally 22)'],
      ['-G', 'print the settings it would use, without connecting'],
      ['-A', 'let the remote side use your agent\'s keys (only on hosts you trust)'],
      ['-L', 'local forward: a port here reaches an address seen from the server'],
      ['-R', 'remote forward: a port on the server reaches your side'],
      ['-D', 'a SOCKS proxy through the server'],
      ['-f', 'go into the background after logging in'],
      ['-N', 'run no remote command, only forward ports'],
    ],
    example: {
      command: 'ssh -f -N -L 9000:127.0.0.1:8899 sim01',
      says: 'Opens a tunnel in the background: http://localhost:9000 on your laptop now shows the page served on port 8899 inside sim01.',
    },
    seeAlso: ['ssh-keygen', 'ssh-copy-id', 'ssh-add', 'scp', 'rsync'],
  },
  {
    name: 'ssh-keygen',
    kind: 'system',
    official: 'OpenSSH authentication key utility',
    source: 'ssh-keygen manual page (OpenSSH)',
    when: 'You want a key pair so you can log in without typing a password. The private key never leaves your machine and must stay mode 600; if it is ever pasted anywhere, make a new one.',
    flags: [
      ['-t ed25519', 'the kind of key to make (-t rsa -b 4096 only for old servers)'],
      ['-C', 'a comment, by habit "who@where"'],
      ['-f', 'the file to write the key to'],
      ['-N', 'the passphrase that locks the key (leave it off to be asked)'],
      ['-l', 'show a key\'s fingerprint (with -f for the file)'],
      ['-R', 'remove a host from known_hosts, only after checking why its key changed'],
    ],
    example: {
      command: 'ssh-keygen -t ed25519 -C "eng@laptop"',
      says: 'Makes a new key pair, asks for a passphrase, and saves ~/.ssh/id_ed25519 (private) and ~/.ssh/id_ed25519.pub (public).',
    },
    seeAlso: ['ssh-copy-id', 'ssh-add', 'ssh'],
  },
  {
    name: 'ssh-copy-id',
    kind: 'system',
    official: 'use locally available keys to authorise logins on a remote machine',
    source: 'ssh-copy-id manual page (OpenSSH)',
    when: 'You made a key pair and want a server to accept it. It adds your public key to the server\'s ~/.ssh/authorized_keys, with the right permissions.',
    flags: [
      ['-i', 'which public key to install'],
      ['-f', 'install it even if it seems to be there already'],
    ],
    example: {
      command: 'ssh-copy-id -i ~/.ssh/id_ed25519.pub sim01',
      says: 'Asks for your password on sim01 one last time and installs the key. After that, ssh sim01 logs in with the key.',
    },
    seeAlso: ['ssh-keygen', 'ssh'],
  },
  {
    name: 'ssh-agent',
    kind: 'system',
    official: 'OpenSSH authentication agent',
    source: 'ssh-agent manual page (OpenSSH)',
    when: 'Your key has a passphrase and you are tired of typing it. The agent holds unlocked keys in memory and answers for you. On a desktop it usually starts by itself; on a server you start it.',
    flags: [['-s', 'print its settings as commands for sh and bash']],
    example: {
      command: 'eval "$(ssh-agent -s)"',
      says: 'Starts an agent and sets SSH_AUTH_SOCK, so ssh and ssh-add can find it.',
    },
    seeAlso: ['ssh-add', 'eval'],
  },
  {
    name: 'ssh-add',
    kind: 'system',
    official: 'adds private key identities to the OpenSSH authentication agent',
    source: 'ssh-add manual page (OpenSSH)',
    when: 'You want to unlock a key once and hand it to the agent, so later ssh, scp and git commands do not ask for the passphrase.',
    flags: [
      ['-l', 'list the keys the agent holds'],
      ['-D', 'remove every key from the agent'],
      ['-t', 'the key expires after this many seconds, as in -t 3600'],
      ['-c', 'ask you to confirm each time the key is used'],
    ],
    example: {
      command: 'ssh-add ~/.ssh/id_ed25519',
      says: 'Asks for the passphrase once and gives the unlocked key to the agent.',
    },
    seeAlso: ['ssh-agent', 'ssh-keygen', 'ssh'],
  },
  {
    name: 'scp',
    kind: 'system',
    official: 'OpenSSH secure file copy',
    source: 'scp manual page (OpenSSH)',
    when: 'You want to copy a file to or from another computer over SSH, once. It overwrites a file of the same name at the far end without asking. For big folders or repeat copies, `rsync` is better: it sends only what changed and can resume.',
    flags: [['-r', 'copy a folder and everything inside it']],
    example: {
      command: 'scp results.tar.gz sim01:/srv/',
      says: 'Copies results.tar.gz from this folder into /srv/ on the machine sim01.',
    },
    seeAlso: ['rsync', 'ssh', 'cp'],
  },
  {
    name: 'curl',
    kind: 'system',
    official: 'transfer a URL',
    source: 'curl manual page',
    when: 'You want to fetch a web page or call a web service from the terminal, often to check that a server answers. Its exit status says what went wrong: 6 for a name that does not exist, 7 for a refused connection, 22 for an HTTP error with -f.',
    flags: [
      ['-s', 'silent: no progress bar'],
      ['-S', 'still show an error when silent'],
      ['-f', 'fail with status 22 when the server answers with an error'],
      ['-o', 'write the page to a file (-o /dev/null throws it away)'],
      ['-w', 'print facts after the transfer, like %{http_code}'],
      ['--max-time', 'give up after this many seconds'],
      ['-H', 'add a header to the request'],
    ],
    example: {
      command: 'curl -fsS -o /dev/null -w "%{http_code}\\n" http://127.0.0.1:8899/',
      says: 'Asks the local server for its front page and prints only the HTTP status code, such as 200.',
    },
    seeAlso: ['ss', 'ssh'],
  },

  /* --------------------------------------------------------------- terminals */
  {
    name: 'tmux',
    kind: 'system',
    official: 'terminal multiplexer',
    source: 'tmux manual page',
    when: 'You want a long job on a remote machine to survive a dropped connection or a closed laptop, and to get its screen back later. The session lives on the server; your terminal is only a window onto it. `tmux kill-session` really does stop the programs inside.',
    flags: [
      ['new -s NAME', 'start a session with a name (-d: start it detached)'],
      ['ls', 'list the sessions'],
      ['a -t NAME', 'attach: go back into a session'],
      ['has-session -t NAME', 'exit 0 if that session exists, for scripts'],
      ['kill-session -t NAME', 'end a session and everything running in it'],
      ['capture-pane -p', 'print what a pane shows, for scripts'],
      ['Ctrl-b d', 'detach and leave everything running'],
    ],
    example: {
      command: 'tmux new -s campaign',
      says: 'Starts a session called campaign. Press Ctrl-b then d to leave it running, and tmux a -t campaign to come back.',
    },
    seeAlso: ['screen', 'nohup', 'ssh'],
  },
  {
    name: 'screen',
    kind: 'system',
    official: 'screen manager with VT100/ANSI terminal emulation',
    source: 'screen manual page',
    when: 'You are on a machine with no tmux and need a session that survives a disconnect. Its prefix key is Ctrl-a instead of Ctrl-b.',
    flags: [
      ['-r', 'reattach to a detached session'],
      ['Ctrl-a d', 'detach and leave it running'],
    ],
    example: {
      command: 'screen -r',
      says: 'Reattaches to your detached screen session, with the job still running inside it.',
    },
    seeAlso: ['tmux'],
  },
  {
    name: 'vim',
    kind: 'system',
    official: "Vi IMproved, a programmer's text editor",
    source: 'vim manual page',
    when: 'You need to edit a file on a machine that has no other editor. It starts in normal mode, where keys are commands: press `i` to type, `Esc` to stop typing, then `:wq` to save and quit or `:q!` to quit without saving.',
    flags: [
      ['-R', 'open the file read-only'],
      ['-r', 'recover your changes from a swap file after a crash'],
      [':wq', 'write the file and quit'],
      [':q!', 'quit and throw away your changes'],
    ],
    example: {
      command: 'vim sweep.yaml',
      says: 'Opens sweep.yaml in vim, in normal mode. Press i to start typing and Esc when you are done.',
    },
    seeAlso: ['less', 'crontab'],
  },

  /* ----------------------------------------------------- services and logs */
  {
    name: 'crontab',
    kind: 'system',
    official: 'maintains crontab files for individual users',
    source: 'crontab manual page (cron)',
    when: 'You want a command to run on a schedule, like every night at 2:30. Each line is five time fields and a command. `crontab -r` deletes your whole schedule with no question asked, so keep a copy with `crontab -l > crontab.bak`.',
    flags: [
      ['-l', 'list your scheduled jobs'],
      ['-e', 'edit them in an editor'],
      ['-r', 'remove them all, without asking'],
      ['FILE', 'install the schedule from a file, replacing the old one'],
    ],
    example: {
      command: 'crontab -l',
      says: 'Prints your schedule, such as 30 2 * * * /srv/campaign/bin/nightly.sh >> /srv/campaign/out/cron.log 2>&1.',
    },
    seeAlso: ['systemctl', 'systemd-analyze', 'flock'],
  },
  {
    name: 'systemctl',
    kind: 'system',
    official: 'Control the systemd system and service manager',
    source: 'systemctl manual page (systemd)',
    when: 'You want to start, stop or check a service: a program the system keeps running in the background, like a web server or a data logger. `start` runs it now; `enable` makes it start at every boot.',
    flags: [
      ['status NAME', 'is it running, since when, its PID and recent log lines'],
      ['start / stop / restart NAME', 'run it now, stop it, or both'],
      ['enable / disable NAME', 'start it at boot, or not'],
      ['is-active NAME', 'answers by exit status, for scripts'],
      ['--failed', 'list everything that has failed'],
      ['cat NAME', 'show the unit file systemd is using'],
      ['daemon-reload', 're-read unit files after you edit one'],
      ['list-timers', 'show scheduled timers and when they next run'],
      ['--no-pager', 'print straight out instead of opening less'],
    ],
    example: {
      command: 'systemctl status sim-sweep --no-pager',
      says: 'Shows whether the sim-sweep service is running, since when, its process id and its last few log lines.',
    },
    seeAlso: ['journalctl', 'systemd-analyze'],
  },
  {
    name: 'journalctl',
    kind: 'system',
    official: 'Print log entries from the systemd journal',
    source: 'journalctl manual page (systemd)',
    when: 'A service or the system misbehaved and you want its log. Everything a service prints is captured here automatically.',
    flags: [
      ['-u', 'only this unit (service)'],
      ['-f', 'follow: keep printing new lines as they arrive'],
      ['-n', 'only the last N lines'],
      ['--since', 'only entries after a time, as in --since "-10 min"'],
      ['-p', 'only this priority or worse, as in -p err'],
      ['-b', 'only this boot (-b -1: the one before)'],
      ['-k', 'only kernel messages'],
      ['--no-pager', 'print straight out instead of opening less'],
      ['--disk-usage', 'how much space the journal takes'],
    ],
    example: {
      command: 'journalctl -u sim-bad --no-pager -n 10',
      says: 'Prints the last ten log lines of the sim-bad service, including why it failed.',
    },
    seeAlso: ['systemctl', 'dmesg'],
  },
  {
    name: 'systemd-analyze',
    kind: 'system',
    official: 'Analyze and debug system manager',
    source: 'systemd-analyze manual page (systemd)',
    when: 'You wrote a unit file or a timer schedule and want it checked before you trust it.',
    flags: [
      ['verify FILE', 'check a unit file for mistakes before loading it'],
      ['calendar "SPEC"', 'show when an OnCalendar= schedule would next fire'],
    ],
    example: {
      command: 'systemd-analyze calendar "Mon..Fri 08:00"',
      says: 'Prints the schedule in its full form and the next time it fires: the next weekday at 08:00.',
    },
    seeAlso: ['systemctl', 'crontab'],
  },
  {
    name: 'coredumpctl',
    kind: 'system',
    official: 'Retrieve and process saved core dumps and metadata',
    source: 'coredumpctl manual page (systemd)',
    when: 'A program crashed on a machine where systemd collects core files, and you want to find the snapshot of its memory and open it in the debugger.',
    flags: [
      ['list', 'show the crashes that were saved'],
      ['debug', 'open the latest one in gdb'],
    ],
    example: {
      command: 'coredumpctl list',
      says: 'Lists each saved crash with its time, process id, signal and program.',
    },
    seeAlso: ['ulimit', 'dmesg'],
  },
  {
    name: 'dmesg',
    kind: 'system',
    official: 'print or control the kernel ring buffer',
    source: 'dmesg manual page (util-linux)',
    when: 'A program died with no message, like exit 137 or 139, and you want the kernel\'s own record: the out-of-memory killer and crashes are written here.',
    flags: [
      ['-T', 'show readable times instead of seconds since boot'],
      ['--level', 'only these levels, as in --level=err,warn'],
    ],
    example: {
      command: 'dmesg -T | grep -i -e "out of memory" -e "killed process"',
      says: 'Shows the kernel\'s lines about programs it killed because memory ran out, with the time and the process name.',
    },
    seeAlso: ['journalctl', 'strace'],
  },
  {
    name: 'strace',
    kind: 'system',
    official: 'trace system calls and signals',
    source: 'strace manual page',
    when: 'A program fails with an unhelpful message, or none, and you want to watch what it asks the operating system for, such as which files it tries to open.',
    flags: [
      ['-e trace=openat', 'only show attempts to open files'],
      ['-f', 'follow child processes too'],
      ['-c', 'count the calls and print a summary at the end'],
    ],
    example: {
      command: 'strace -e trace=openat cat nosuchfile.yaml',
      says: 'Shows every file cat tries to open, ending with nosuchfile.yaml = -1 ENOENT (No such file or directory).',
    },
    seeAlso: ['lsof', 'dmesg'],
  },
  {
    name: 'lsof',
    kind: 'system',
    official: 'list open files',
    source: 'lsof manual page',
    when: 'You want to know which program has a file, folder or port open: why a disk will not unmount, why deleting a big file freed no space, or who is using port 8080.',
    flags: [
      ['+L1', 'files that were deleted but are still open'],
      ['-p', 'the open files of this process id'],
      ['+D', 'everything open under this folder'],
      ['-i :PORT', 'who is using this network port'],
    ],
    example: {
      command: 'lsof +L1',
      says: 'Lists files that were deleted while a program still holds them open. Their space comes back only when that program closes them.',
    },
    seeAlso: ['strace', 'ss', 'df'],
  },
  {
    name: 'lsblk',
    kind: 'system',
    official: 'list block devices',
    source: 'lsblk manual page (util-linux)',
    when: 'You want to see the disks and partitions a machine has, and where each one is mounted.',
    flags: [['-f', 'also show each filesystem\'s type and label']],
    example: {
      command: 'lsblk -f',
      says: 'Lists each disk and partition as a tree, with its filesystem type and the folder it is mounted on.',
    },
    seeAlso: ['df'],
  },
  {
    name: 'uname',
    kind: 'system',
    official: 'print system information',
    source: 'uname manual page (GNU coreutils)',
    when: 'You want to know which operating system kernel a machine, or a container, is running.',
    flags: [['-r', 'the kernel release (version)']],
    example: {
      command: 'uname -r',
      says: 'Prints the kernel version, such as 6.8.0-45-generic. A container prints the same, because it shares the host\'s kernel.',
    },
    seeAlso: ['docker'],
  },
  {
    name: 'ss',
    kind: 'system',
    official: 'another utility to investigate sockets',
    source: 'ss manual page (iproute2)',
    when: 'You want to see which programs are listening on which network ports, for example to check that your server really started, or that a tunnel is open.',
    flags: [
      ['-l', 'only listening sockets'],
      ['-t', 'only TCP'],
      ['-n', 'show port numbers instead of names'],
      ['-p', 'show which process owns each one'],
      ['-s', 'a summary count'],
    ],
    example: {
      command: 'ss -ltnp',
      says: 'Lists every TCP port something is listening on, with the program. 127.0.0.1 means only this machine can reach it; 0.0.0.0 means every network.',
    },
    seeAlso: ['ip', 'lsof', 'curl'],
  },
  {
    name: 'ip',
    kind: 'system',
    official: 'show / manipulate routing, network devices, interfaces and tunnels',
    source: 'ip manual page (iproute2)',
    when: 'You want to know a machine\'s network addresses, or where its traffic goes out.',
    flags: [
      ['-br a', 'a brief list of every interface and its addresses'],
      ['a show eth0', 'the details of one interface'],
      ['r', 'the routes: where traffic for each network is sent'],
    ],
    example: {
      command: 'ip -br a',
      says: 'Prints one line per network interface, such as lo UNKNOWN 127.0.0.1/8, with its state and addresses.',
    },
    seeAlso: ['ss', 'curl'],
  },

  /* ---------------------------------------------------------------- packages */
  {
    name: 'apt-cache',
    kind: 'system',
    official: 'query the APT cache',
    source: 'apt-cache manual page (APT)',
    when: 'You want to know which version of a package is installed and which versions you could install, without changing anything.',
    flags: [['policy NAME', 'the installed version, the candidate, and every version available']],
    example: {
      command: 'apt-cache policy rsync',
      says: 'Prints the installed and candidate versions of rsync and where each available version comes from.',
    },
    seeAlso: ['apt', 'apt-get'],
  },
]
