// Regenerates src/curriculum/lessons/manifest.ts from the lesson files on disk.
// Run with plain Node 22 (type stripping): `node scripts/lessons-manifest.ts`,
// or `npm run lessons:manifest`. The build runs it first, so a stale manifest
// cannot ship; the validator test fails if the committed one drifts.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseLesson } from '../src/curriculum/lessons/parse.ts'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const dir = path.join(root, 'src', 'curriculum', 'lessons')

export interface ManifestEntry {
  id: string
  title: string
  minutes: number
  covers: string[]
  file: string
}

export function buildManifest(): Record<string, ManifestEntry[]> {
  const out: Record<string, ManifestEntry[]> = {}
  for (const moduleId of fs.readdirSync(dir).sort()) {
    const modDir = path.join(dir, moduleId)
    if (!fs.statSync(modDir).isDirectory()) continue
    const files = fs.readdirSync(modDir).filter((f) => f.endsWith('.md')).sort()
    if (files.length === 0) continue
    out[moduleId] = files.map((file) => {
      const { header } = parseLesson(fs.readFileSync(path.join(modDir, file), 'utf8'), `${moduleId}/${file}`)
      return { ...header, file: `${moduleId}/${file}` }
    })
  }
  return out
}

export function renderManifest(manifest: Record<string, ManifestEntry[]>): string {
  return [
    '// Generated by scripts/lessons-manifest.ts — do not edit by hand.',
    '// Lesson metadata for every module that has lessons on disk; bodies load lazily.',
    "import type { LessonMeta } from './types'",
    '',
    `export const LESSON_MANIFEST: Record<string, LessonMeta[]> = ${JSON.stringify(manifest, null, 2)}`,
    '',
  ].join('\n')
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const manifest = buildManifest()
  const target = path.join(dir, 'manifest.ts')
  fs.writeFileSync(target, renderManifest(manifest))
  const modules = Object.keys(manifest).length
  const lessons = Object.values(manifest).reduce((a, l) => a + l.length, 0)
  console.log(`lessons-manifest: ${lessons} lessons across ${modules} modules → ${path.relative(root, target)}`)
}
