// Regenerates src/curriculum/lessons/manifest.ts from the lesson files on disk.
// Run with plain Node 22 (type stripping): `node scripts/lessons-manifest.ts`,
// or `npm run lessons:manifest`. The build runs it first, so a stale manifest
// cannot ship; the validator test fails if the committed one drifts.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseLesson } from '../src/curriculum/lessons/parse.ts'
import { CODING } from '../src/curriculum/coding.ts'
import { GNC_ADVANCED } from '../src/curriculum/gnc-advanced.ts'
import { GNC_CORE } from '../src/curriculum/gnc-core.ts'
import { GNC_FOUNDATIONS } from '../src/curriculum/gnc-foundations.ts'
import { CAREER } from '../src/curriculum/tracks-aux.ts'

// The leaf sources rather than src/curriculum/index.ts: that module attaches
// lessons via import.meta.glob, which only exists under Vite, and this script
// has to run under plain Node so the build can regenerate before bundling.
const TOPICS = new Map<string, string[]>(
  [...GNC_FOUNDATIONS, ...GNC_CORE, ...GNC_ADVANCED, ...CODING, ...CAREER].map((m) => [
    m.id,
    m.topics,
  ]),
)

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const dir = path.join(root, 'src', 'curriculum', 'lessons')

export interface ManifestEntry {
  id: string
  title: string
  minutes: number
  covers: string[]
  file: string
}

/**
 * How much of a module the written lessons actually teach. Derived, never
 * hand-maintained: a module is complete exactly when its lessons' `covers`
 * entries account for every topic the module lists.
 *
 * This exists so the app can be honest while the corpus is still being
 * written. A module with four of eleven topics taught says so on its card
 * instead of presenting a half-written module as the finished article.
 */
export interface CoverageEntry {
  covered: number
  total: number
  complete: boolean
  /** Topics no lesson covers yet, verbatim. */
  missing: string[]
}

export function buildManifest(): Record<string, ManifestEntry[]> {
  const out: Record<string, ManifestEntry[]> = {}
  for (const moduleId of fs.readdirSync(dir).sort()) {
    const modDir = path.join(dir, moduleId)
    if (!fs.statSync(modDir).isDirectory()) continue
    const files = fs.readdirSync(modDir).filter((f) => f.endsWith('.md')).sort()
    if (files.length === 0) continue
    out[moduleId] = files.map((file) => {
      const { header } = parseLesson(fs.readFileSync(path.join(modDir, file), 'utf8'), `${moduleId}/${file}`)
      return { ...header, file: `${moduleId}/${file}` }
    })
  }
  return out
}

export function buildCoverage(
  manifest: Record<string, ManifestEntry[]> = buildManifest(),
): Record<string, CoverageEntry> {
  const out: Record<string, CoverageEntry> = {}
  for (const [moduleId, lessons] of Object.entries(manifest)) {
    const topics = TOPICS.get(moduleId)
    if (!topics) continue
    const covered = new Set<string>()
    for (const l of lessons) for (const c of l.covers) if (topics.includes(c)) covered.add(c)
    const missing = topics.filter((t) => !covered.has(t))
    out[moduleId] = {
      covered: covered.size,
      total: topics.length,
      complete: missing.length === 0,
      missing,
    }
  }
  return out
}

export function renderManifest(
  manifest: Record<string, ManifestEntry[]>,
  coverage: Record<string, CoverageEntry> = buildCoverage(manifest),
): string {
  return [
    '// Generated by scripts/lessons-manifest.ts — do not edit by hand.',
    '// Lesson metadata for every module that has lessons on disk; bodies load lazily.',
    "import type { LessonMeta } from './types'",
    '',
    `export const LESSON_MANIFEST: Record<string, LessonMeta[]> = ${JSON.stringify(manifest, null, 2)}`,
    '',
    '/** Derived: how much of each module its lessons actually teach. */',
    'export interface LessonCoverage {',
    '  covered: number',
    '  total: number',
    '  complete: boolean',
    '  missing: string[]',
    '}',
    '',
    `export const LESSON_COVERAGE: Record<string, LessonCoverage> = ${JSON.stringify(coverage, null, 2)}`,
    '',
  ].join('\n')
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const manifest = buildManifest()
  const coverage = buildCoverage(manifest)
  const target = path.join(dir, 'manifest.ts')
  fs.writeFileSync(target, renderManifest(manifest, coverage))
  const modules = Object.keys(manifest).length
  const lessons = Object.values(manifest).reduce((a, l) => a + l.length, 0)
  const done = Object.values(coverage).filter((c) => c.complete).length
  console.log(
    `lessons-manifest: ${lessons} lessons across ${modules} modules ` +
      `(${done} fully covered, ${modules - done} still being written) → ${path.relative(root, target)}`,
  )
}
